CalcHeatBalanceInsideSurf – EnergyPlusFortran
CalcHeatBalanceInsideSurf Subroutine
641 statements
Source File
subroutine CalcHeatBalanceInsideSurf(ZoneToResimulate)
Uses:
DataPrecisionGlobals
DataGlobals
DataEnvironment
DataHeatBalFanSys
DataHeatBalance
DataHeatBalSurface
DataSurfaces
DataInterfaces
DataDaylightingDevices
DataMoistureBalance
DataMoistureBalanceEMPD
DataAirflowNetwork
HeatBalanceMovableInsulation
WindowManager
HeatBalFiniteDiffManager
HeatBalanceHAMTManager
ConvectionCoefficients
HeatBalanceIntRadExchange
MoistureBalanceEMPDManager
ScheduleManager
General
DaylightingDevices
DataZoneEquipment
DataLoopNode
HeatBalanceSurfaceManager
Psychrometrics
OutputReportTabular
DataSizing
DataTimings
WindowEquivalentLayer
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: ZoneToResimulate
Calls
Called By
Source Code
CalcHeatBalanceInsideSurf
Source Code
SUBROUTINE CalcHeatBalanceInsideSurf(ZoneToResimulate)
          ! SUBROUTINE INFORMATION:
          !       AUTHOR         George Walton
          !       DATE WRITTEN   December 1979
          !       MODIFIED       Jun 1990 (RDT for new CTF arrays)
          !                      Dec 1999 (FCW for window calculation)
          !                      May 2000 (FCW for window frame and dividers)
          !                      Aug 2000 (RJL for MTF moisture calculations)
          !                      Sep 2000 (RKS for new radiant exchange algorithm)
          !                      Dec 2000 (RKS for radiant system model addition)
          !                      Jul 2003 (CC) set the reference temperatures for inside surface heat balance
          !                                    depending on convection algorithms and/or air models used
          !                      May 2006 (RR  account for exterior window screen)
          !                      Jul 2008 (P. Biddulph include calls to HAMT)
          !                      Sep 2011 LKL/BG - resimulate only zones needing it for Radiant systems
          !       RE-ENGINEERED  Mar 1998 (RKS)
          ! PURPOSE OF THIS SUBROUTINE:
          ! This subroutine performs a heat balance on the outside face of each
          ! surface in the building.
          ! METHODOLOGY EMPLOYED:
          ! Various boundary conditions are set and additional parameters are set-
          ! up.  Then, the proper heat balance equation is selected based on whether
          ! the surface is a partition or not and on whether or not movable
          ! insulation is present on the inside face.
          ! REFERENCES:
          ! (I)BLAST legacy routine HBSRF
          ! USE STATEMENTS:
  USE DataPrecisionGlobals
  USE DataGlobals
  USE DataEnvironment
  USE DataHeatBalFanSys
  USE DataHeatBalance
  USE DataHeatBalSurface
  USE DataSurfaces
  USE DataInterfaces,               ONLY: ShowMessage,ShowContinueError,ShowContinueErrorTimeStamp,ShowFatalError,  &
                ShowSevereError,ShowSevereMessage,ShowWarningError,ShowWarningMessage,ShowErrorMessage,  &
                ShowRecurringSevereErrorAtEnd,ShowRecurringWarningErrorAtEnd,ShowRecurringContinueErrorAtEnd,  &
                SetupOutputVariable
  USE DataDaylightingDevices
  USE DataMoistureBalance,          ONLY : TempOutsideAirFD,RhoVaporAirOut,RhoVaporAirIn,HConvExtFD,HMassConvExtFD, &
                                           HConvInFD,HMassConvInFD,RhoVaporSurfIn, &
                                           HSkyFD,HGrndFD,HAirFD
  USE DataMoistureBalanceEMPD,      ONLY : MoistEMPDNew, MoistEMPDFlux
  USE DataAirflowNetwork,           ONLY : SimulateAirflowNetwork,AirflowNetworkControlSimple
  USE HeatBalanceMovableInsulation, ONLY : EvalInsideMovableInsulation
  USE WindowManager,                ONLY : CalcWindowHeatBalance
  USE HeatBalFiniteDiffManager,     ONLY : ManageHeatBalFiniteDiff, SurfaceFD
  USE HeatBalanceHAMTManager,       ONLY : ManageHeatBalHAMT,UpdateHeatBalHAMT
  USE ConvectionCoefficients,       ONLY : InitExteriorConvectionCoeff, InitInteriorConvectionCoeffs, &
                                           SetExtConvectionCoeff, SetIntConvectionCoeff
  USE HeatBalanceIntRadExchange,    ONLY : CalcInteriorRadExchange
  USE MoistureBalanceEMPDManager,   ONLY : CalcMoistureBalanceEMPD,UpdateMoistureBalanceEMPD
  USE ScheduleManager,              ONLY : GetCurrentScheduleValue
  USE General,                      ONLY : RoundSigDigits
  USE DaylightingDevices,           ONLY : FindTDDPipe
  USE DataZoneEquipment,            ONLY : ZoneEquipConfig
  USE DataLoopNode,                 ONLY : Node
  USE HeatBalanceSurfaceManager,    ONLY : CalculateZoneMRT
  USE Psychrometrics
  USE OutputReportTabular, ONLY: loadConvectedNormal,loadConvectedWithPulse,netSurfRadSeq
  USE DataSizing, ONLY: CurOverallSimDay
  USE DataTimings
  USE WindowEquivalentLayer,        ONLY : EQLWindowOutsideEffectiveEmiss
  IMPLICIT NONE    ! Enforce explicit typing of all variables in this routine
          ! SUBROUTINE ARGUMENT DEFINITIONS:
  INTEGER, INTENT(IN), OPTIONAL :: ZoneToResimulate  ! if passed in, then only calculate surfaces that have this zone
          ! SUBROUTINE PARAMETER DEFINITIONS:
  REAL(r64), PARAMETER :: Sigma = 5.6697d-08          ! Stefan-Boltzmann constant
  REAL(r64), PARAMETER :: IterDampConst = 5.0d0         ! Damping constant for inside surface temperature iterations
  INTEGER,   PARAMETER :: ItersReevalConvCoeff = 30   ! Number of iterations between inside convection coefficient reevaluations
  REAL(r64), PARAMETER :: MaxAllowedDelTemp = 0.002d0   ! Convergence criteria for inside surface temperatures
  INTEGER,   PARAMETER :: MaxIterations = 500         ! Maximum number of iterations allowed for inside surface temps
  INTEGER,   PARAMETER :: IterationsForCondFDRelaxChange = 5 ! number of iterations for inside temps that triggers a change
                                                              ! in the CondFD relaxation factor.
  INTEGER,   PARAMETER :: MinEMPDIterations = 4       ! Minimum number of iterations required for EMPD solution
          ! INTERFACE BLOCK SPECIFICATIONS:
          ! na
          ! DERIVED TYPE DEFINITIONS:
          ! na
          ! SUBROUTINE LOCAL VARIABLE DECLARATIONS:
  REAL(r64)        :: AbsInt          ! Solar absorptance of inside movable insulation
  INTEGER          :: ConstrNum       ! Construction index for the current surface
  LOGICAL          :: Converged       ! .true. if inside heat balance has converged
  REAL(r64)        :: F1              ! Intermediate calculation value
  REAL(r64)        :: HMovInsul       ! "Convection" coefficient of movable insulation
  REAL(r64) :: MaxDelTemp      ! Maximum change in surface temperature for any
                                      !  opaque surface from one iteration to the next
  INTEGER          :: SurfNum         ! Surface number
  INTEGER          :: ZoneNum         ! Zone number the current surface is attached to
  INTEGER          :: ConstrNumSh     ! Shaded construction number for a window
  INTEGER          :: RoughSurf       ! Outside surface roughness
  REAL(r64)        :: EmisOut         ! Glass outside surface emissivity
  REAL(r64), SAVE, ALLOCATABLE, DIMENSION(:) :: TempInsOld ! Holds previous iteration's value for convergence check
  REAL(r64)        :: RhoVaporSat     ! Local temporary saturated vapor density for checking
  REAL(r64) :: TempSurfOutTmp  ! Local Temporary Surface temperature for the outside surface face
  REAL(r64)        :: TempSurfInSat   ! Local temperary surface dew point temperature
  LOGICAL, SAVE    :: FirstTime = .TRUE. ! Used for trapping errors or other problems
  INTEGER          :: OtherSideSurfNum   ! Surface number index for other side of an interzone partition
  INTEGER, SAVE    :: MinIterations   ! Minimum number of iterations for the inside heat balance
!  CHARACTER(len=25):: ErrMsg
!  CHARACTER(len=5) :: TimeStmp
  INTEGER, SAVE    :: ErrCount=0
  INTEGER          :: PipeNum         ! TDD pipe object number
  INTEGER          :: SurfNum2        ! TDD:DIFFUSER object number
  REAL(r64)        :: Ueff            ! 1 / effective R value between TDD:DOME and TDD:DIFFUSER
  INTEGER           :: ZoneEquipConfigNum
!  LOGICAL           :: ControlledZoneAirFlag
  INTEGER           :: NodeNum
  REAL(r64)         :: SumSysMCp             ! Zone sum of air system MassFlowRate*Cp
  REAL(r64)         :: SumSysMCpT            ! Zone sum of air system MassFlowRate*Cp*T
  REAL(r64)         :: MassFlowRate
  REAL(r64)         :: NodeTemp
  REAL(r64)         :: CpAir
  REAL(r64), SAVE, ALLOCATABLE, DIMENSION(:) :: RefAirTemp ! reference air temperatures
  LOGICAL, SAVE     :: MyEnvrnFlag=.true.
!  LOGICAL, SAVE     :: DoThisLoop
  INTEGER, SAVE     :: InsideSurfErrCount=0
  REAL(r64) :: Wsurf ! Moisture ratio for HAMT
  REAL(r64) :: RhoAirZone ! Zone moisture density for HAMT
  INTEGER :: OtherSideZoneNum ! Zone Number index for other side of an interzone partition HAMT
  INTEGER,SAVE :: WarmupSurfTemp
  LOGICAL :: PartialResimulate
  INTEGER          :: TimeStepInDay=0 ! time step number
          ! FLOW:
  IF (FirstTime) THEN
    ALLOCATE(TempInsOld(TotSurfaces))
    ALLOCATE(RefAirTemp(TotSurfaces))
    IF (ANY(HeatTransferAlgosUsed == UseEMPD)) THEN
      MinIterations = MinEMPDIterations
    ELSE
      MinIterations = 1
    END IF
    IF (DisplayAdvancedReportVariables) THEN
      CALL SetupOutputVariable('Surface Inside Face Heat Balance Calculation Iteration Count []',InsideSurfIterations, &
                            'ZONE','Sum','Simulation')
    ENDIF
  ENDIF
  IF (BeginEnvrnFlag .and. MyEnvrnFlag) THEN
    TempInsOld=23.0d0
    RefAirTemp=23.0d0
    TempEffBulkAir=23.0d0
    WarmupSurfTemp=0
    MyEnvrnFlag=.false.
  ENDIF
  IF (.not. BeginEnvrnFlag) THEN
    MyEnvrnFlag=.true.
  ENDIF
  PartialResimulate=.false.
  ! determine reference air temperatures
  DO SurfNum = 1, TotSurfaces
      ZoneNum = Surface(SurfNum)%Zone
      IF (.NOT. Surface(SurfNum)%HeatTransSurf .OR. ZoneNum == 0) CYCLE  ! Skip non-heat transfer surfaces
      IF (Surface(SurfNum)%Class == SurfaceClass_TDD_Dome) CYCLE  ! Skip TDD:DOME objects.  Inside temp is handled by TDD:DIFFUSER.
      IF (PRESENT(ZoneToResimulate)) THEN
        PartialResimulate=.true.
        IF ((ZoneNum /= ZoneToResimulate) .AND. (AdjacentZoneToSurface(SurfNum) /= ZoneToResimulate)) THEN
          CYCLE ! skip surfaces that are not associated with this zone
        ENDIF
      ENDIF
      IF (PartialResimulate) THEN
         WinHeatGain(Surfnum)                     = 0.0d0
         WinHeatGainRep(Surfnum)                  = 0.0d0
         WinHeatLossRep(Surfnum)                  = 0.0d0
         WinGainConvGlazToZoneRep(Surfnum)        = 0.0D0
         WinGainIRGlazToZoneRep(Surfnum)          = 0.0D0
         WinLossSWZoneToOutWinRep(Surfnum)        = 0.0D0
         WinGainFrameDividertoZoneRep(Surfnum)    = 0.0D0
         WinGainConvGlazShadGapToZoneRep(Surfnum) = 0.0D0
         WinGainConvShadeToZoneRep(Surfnum)       = 0.0D0
         OtherConvGainInsideFaceToZoneRep(Surfnum)= 0.0D0
         WinGainIRShadeToZoneRep(Surfnum)         = 0.0D0
         SurfaceWindow(Surfnum)%FrameQRadOutAbs   = 0.0d0
         SurfaceWindow(Surfnum)%FrameQRadInAbs    = 0.0d0
         SurfaceWindow(Surfnum)%DividerQRadOutAbs = 0.0d0
         SurfaceWindow(Surfnum)%DividerQRadInAbs  = 0.0d0
      ENDIF
      SELECT CASE (Surface(SurfNum)%TAirRef)
        CASE (ZoneMeanAirTemp)
            RefAirTemp(SurfNum) = MAT(ZoneNum)
            TempEffBulkAir(SurfNum) = MAT(ZoneNum)  ! for reporting surf adjacent air temp
        CASE (AdjacentAirTemp)
            RefAirTemp(SurfNum) = TempEffBulkAir(SurfNum)
        CASE (ZoneSupplyAirTemp)
            ! determine ZoneEquipConfigNum for this zone
            ZoneEquipConfigNum = ZoneNum
            ! check whether this zone is a controlled zone or not
            IF (.NOT. Zone(ZoneNum)%IsControlled) THEN
                CALL ShowFatalError('Zones must be controlled for Ceiling-Diffuser Convection model. No system serves zone '//  &
                                    TRIM(Zone(ZoneNum)%Name))
                RETURN
            END IF
            ! determine supply air conditions
            SumSysMCp = 0.0d0
            SumSysMCpT = 0.0d0
            DO NodeNum = 1, ZoneEquipConfig(ZoneEquipConfigNum)%NumInletNodes
                NodeTemp = Node(ZoneEquipConfig(ZoneEquipConfigNum)%InletNode(NodeNum))%Temp
                MassFlowRate = Node(ZoneEquipConfig(ZoneEquipConfigNum)%InletNode(NodeNum))%MassFlowRate
                CpAir = PsyCpAirFnWTdb(ZoneAirHumRat(ZoneNum), NodeTemp)
                SumSysMCp = SumSysMCp + MassFlowRate * CpAir
                SumSysMCpT = SumSysMCpT + MassFlowRate * CpAir * NodeTemp
            END DO
            ! a weighted average of the inlet temperatures.
            IF (SumSysMCp > 0.d0) THEN ! protect div by zero
              RefAirTemp(SurfNum)     = SumSysMCpT/SumSysMCp  ! BG changed 02-16-2005 to add index (SurfNum)
            ELSE
              RefAirTemp(SurfNum)     = NodeTemp
            ENDIF
            TempEffBulkAir(SurfNum) = RefAirTemp(SurfNum)   ! for reporting surf adjacent air temp
        CASE DEFAULT
            ! currently set to mean air temp but should add error warning here
            RefAirTemp(SurfNum)     = MAT(ZoneNum)
            TempEffBulkAir(SurfNum) = MAT(ZoneNum)  ! for reporting surf adjacent air temp
      END SELECT
  END DO
  InsideSurfIterations = 0
  ! Following variables must be reset due to possible recall of this routine by radiant and Resimulate routines.
  ! CalcWindowHeatBalance is called, then, multiple times and these need to be initialized before each call to
  ! CalcWindowHeatBalance.
  IF (.not. PartialResimulate) THEN
    WinHeatGain                     = 0.0d0
    WinHeatGainRep                  = 0.0d0
    WinHeatLossRep                  = 0.0d0
    WinGainConvGlazToZoneRep        = 0.0D0
    WinGainIRGlazToZoneRep          = 0.0D0
    WinLossSWZoneToOutWinRep        = 0.0D0
    WinGainFrameDividertoZoneRep    = 0.0D0
    WinGainConvGlazShadGapToZoneRep = 0.0D0
    WinGainConvShadeToZoneRep       = 0.0D0
    OtherConvGainInsideFaceToZoneRep= 0.0D0
    WinGainIRShadeToZoneRep         = 0.0D0
    SurfaceWindow%FrameQRadOutAbs   = 0.0d0
    SurfaceWindow%FrameQRadInAbs    = 0.0d0
    SurfaceWindow%DividerQRadOutAbs = 0.0d0
    SurfaceWindow%DividerQRadInAbs  = 0.0d0
  ENDIF
  Converged = .FALSE.
  DO WHILE (.NOT. Converged) ! Start of main inside heat balance DO loop...
    TempInsOld = TempSurfIn ! Keep track of last iteration's temperature values
    IF (PRESENT(ZoneToResimulate)) THEN
      CALL CalcInteriorRadExchange(TempSurfIn,InsideSurfIterations,NetLWRadToSurf,  &
         ZoneToResimulate,calledfrom='Inside') ! Update the radiation balance
    ELSE
      CALL CalcInteriorRadExchange(TempSurfIn,InsideSurfIterations,NetLWRadToSurf,  &
         calledfrom='Inside') ! Update the radiation balance
    ENDIF
          ! Every 30 iterations, recalculate the inside convection coefficients in case
          ! there has been a significant drift in the surface temperatures predicted.
          ! This is not fool-proof and it basically means that the outside surface
          ! heat balance is in error (potentially) once HConvIn is re-evaluated.
          ! The choice of 30 is not significant--just want to do this a couple of
          ! times before the iteration limit is hit.
    IF ((InsideSurfIterations>0).AND.(MOD(InsideSurfIterations,ItersReevalConvCoeff)==0)) THEN
      IF (PRESENT(ZoneToResimulate)) THEN
        CALL InitInteriorConvectionCoeffs(TempSurfIn,ZoneToResimulate)
      ELSE
        CALL InitInteriorConvectionCoeffs(TempSurfIn)
      ENDIF
    ENDIF
    DO SurfNum = 1, TotSurfaces   ! Perform a heat balance on all of the inside surface...
      ZoneNum = Surface(SurfNum)%Zone
      IF (.NOT. Surface(SurfNum)%HeatTransSurf .OR. ZoneNum == 0) CYCLE  ! Skip non-heat transfer surfaces
      IF (Surface(SurfNum)%Class == SurfaceClass_TDD_Dome) CYCLE  ! Skip TDD:DOME objects.  Inside temp is handled by TDD:DIFFUSER.
      IF (PRESENT(ZoneToResimulate)) THEN
        IF ((ZoneNum /= ZoneToResimulate) .AND. (AdjacentZoneToSurface(SurfNum) /= ZoneToResimulate)) THEN
          CYCLE ! skip surfaces that are not associated with this zone
        ENDIF
      ENDIF
      ConstrNum = Surface(SurfNum)%Construction
      !Calculate the inside surface moisture quantities
       !calculate the inside surface moisture transfer conditions
      RhoVaporAirIn(SurfNum)=PsyRhovFnTdbWPb(MAT(ZoneNum),ZoneAirHumRat(ZoneNum),OutBaroPress)
       !check for saturation conditions of air
      RhoVaporSat=PsyRhovFnTdbRh(MAT(ZoneNum),1.0d0,'HB,SurfMan:InsideSurf')
      IF (RhoVaporAirIn(SurfNum) .GT. RhoVaporSat) RhoVaporAirIn(SurfNum)=RhoVaporSat
      HConvInFD(SurfNum)=HConvIn(SurfNum)
      HMassConvInFD(SurfNum)=HConvInFD(SurfNum)/((PsyRhoAirFnPbTdbW(OutBaroPress,MAT(ZoneNum),ZoneAirHumRat(ZoneNum))+ &
                   RhoVaporAirIn(SurfNum))*PsyCpAirFnWTdb(ZoneAirHumRat(ZoneNum),MAT(ZoneNum)))
          ! Perform heat balance on the inside face of the surface ...
          ! The following are possibilities here:
          !   (a) the surface is a partition, in which case the temperature of both sides are the same
          !   (b) standard (or interzone) opaque surface with no movable insulation, normal heat balance equation
          !   (c) standard (or interzone) window: call to CalcWindowHeatBalance to get window layer temperatures
          !   (d) standard opaque surface with movable insulation, special two-part equation
          ! In the surface calculation there are the following Algorithm types for opaque surfaces that
          ! do not have movable insulation:
          !   (a) the regular CTF calc (SolutionAlgo = UseCTF)
          !   (b) the EMPD calc (Solutionalgo = UseEMPD)
          !   (c) the CondFD calc (SolutionAlgo = UseCondFD)
          !   (d) the HAMT calc (solutionalgo = UseHAMT).
      IF (Surface(SurfNum)%ExtBoundCond == SurfNum .and. Surface(SurfNum)%Class /= SurfaceClass_Window) THEN
!CR6869 -- let Window HB take care of it      IF (Surface(SurfNum)%ExtBoundCond == SurfNum) THEN
        ! Surface is a partition
        IF ( Surface(SurfNum)%HeatTransferAlgorithm == HeatTransferModel_CTF .OR. &
             Surface(SurfNum)%HeatTransferAlgorithm == HeatTransferModel_EMPD) THEN  !Regular CTF Surface and/or EMPD surface
           If (Surface(SurfNum)%HeatTransferAlgorithm == HeatTransferModel_EMPD) Then
             Call CalcMoistureBalanceEMPD(SurfNum, TempSurfInTmp(SurfNum), &
                   TH(SurfNum,2,2), MAT(ZoneNum),TempSurfInSat)
           End If
           TempSurfInTmp(SurfNum) = ( CTFConstInPart(SurfNum)             & ! Constant portion of conduction eq (history terms)
                                    +QRadThermInAbs(SurfNum)             & ! LW radiation from internal sources
                                    +QRadSWInAbs(SurfNum)                & ! SW radiation from internal sources
                                    +HConvIn(SurfNum)*RefAirTemp(SurfNum) & ! Convection from surface to zone air
                                    +NetLWRadToSurf(SurfNum)             & ! Net radiant exchange with other zone surfaces
                                    +Construct(ConstrNum)%CTFSourceIn(0) & ! Heat source/sink term for radiant systems
                                     *QsrcHist(SurfNum,1)                & ! (if there is one present)
                                    +QHTRadSysSurf(SurfNum)              & ! Radiant flux from a high temperature radiant heater
                                    +QHWBaseboardSurf(SurfNum)           & ! Radiant flux from a hot water baseboard heater
                                    +QSteamBaseboardSurf(SurfNum)        & ! Radiant flux from a steam baseboard heater
                                    +QElecBaseboardSurf(SurfNum)         & ! Radiant flux from an electric baseboard heater
                                    +IterDampConst                       &
                                     *TempInsOld(SurfNum) )              & ! Iterative damping term (for stability)
                                  /( Construct(ConstrNum)%CTFInside(0)   & ! Conduction term (both partition sides same temp)
                                    -Construct(ConstrNum)%CTFCross(0)    & ! Conduction term (both partition sides same temp)
                                    +HConvIn(SurfNum)+IterDampConst )   ! Convection and damping term
            If (Surface(SurfNum)%HeatTransferAlgorithm == HeatTransferModel_EMPD) Then
              TempSurfInTmp(SurfNum) = TempSurfInTmp(SurfNum)              &
                                      -MoistEMPDFlux(SurfNum)              &
                                      /( Construct(ConstrNum)%CTFInside(0) &  ! Conduction term (both partition sides same temp)
                                        -Construct(ConstrNum)%CTFCross(0)  &  ! Conduction term (both partition sides same temp)
                                        +HConvIn(SurfNum)+IterDampConst )   ! Convection and damping term
              if (TempSurfInSat .GT. TempSurfInTmp(SurfNum)) then
                 TempSurfInTmp(SurfNum) = TempSurfInSat    ! Surface temp cannot be below dew point
              end if
            End If
          ! if any mixed heat transfer models in zone, apply limits to CTF result
          IF (ANY(Surface(Zone(ZoneNum)%SurfaceFirst:Zone(ZoneNum)%SurfaceLast)%HeatTransferAlgorithm == HeatTransferModel_CondFD)&
              .OR. &
              ANY(Surface(Zone(ZoneNum)%SurfaceFirst:Zone(ZoneNum)%SurfaceLast)%HeatTransferAlgorithm == HeatTransferModel_HAMT) )&
              THEN
            TempSurfInTmp(SurfNum) = MAX(MinSurfaceTempLimit,MIN(MaxSurfaceTempLimit,TempSurfInTmp(SurfNum)))  !Limit Check
          ENDIF
          IF (Construct(ConstrNum)%SourceSinkPresent) THEN  ! Set the appropriate parameters for the radiant system
            ! Radiant system does not need the damping coefficient terms (hopefully)
            RadSysTiHBConstCoef(SurfNum) = ( CTFConstInPart(SurfNum)       & ! Constant portion of conduction eq (history terms)
                                            +QRadThermInAbs(SurfNum)       & ! LW radiation from internal sources
                                            +QRadSWInAbs(SurfNum)          & ! SW radiation from internal sources
                                            +HConvIn(SurfNum)*RefAirTemp(SurfNum) & ! Convection from surface to zone air
                                            +QHTRadSysSurf(SurfNum)        & ! Radiant flux from high temperature radiant heater
                                            +QHWBaseboardSurf(SurfNum)     & ! Radiant flux from a hot water baseboard heater
                                            +QSteamBaseboardSurf(SurfNum)  & ! Radiant flux from a steam baseboard heater
                                            +QElecBaseboardSurf(SurfNum)   & ! Radiant flux from an electric baseboard heater
                                            +NetLWRadToSurf(SurfNum) )     & ! Net radiant exchange with other zone surfaces
                                          /( Construct(ConstrNum)%CTFInside(0) & ! Cond term (both partition sides same temp)
                                            -Construct(ConstrNum)%CTFCross(0)  & ! Cond term (both partition sides same temp)
                                            +HConvIn(SurfNum) )              ! Convection and damping term
            RadSysTiHBToutCoef(SurfNum)  = 0.0d0  ! The outside temp is assumed to be equal to the inside temp for a partition
            RadSysTiHBQsrcCoef(SurfNum)  = Construct(ConstrNum)%CTFSourceIn(0) & ! QTF term for the source
                                          /( Construct(ConstrNum)%CTFInside(0) & ! Cond term (both partition sides same temp)
                                            -Construct(ConstrNum)%CTFCross(0)  & ! Cond term (both partition sides same temp)
                                            +HConvIn(SurfNum) )                  ! Convection and damping term
            RadSysToHBConstCoef(SurfNum) = RadSysTiHBConstCoef(SurfNum) ! Partitions are assumed to be symmetric
            RadSysToHBTinCoef(SurfNum)   = RadSysTiHBToutCoef(SurfNum)  ! Partitions are assumed to be symmetric
            RadSysToHBQsrcCoef(SurfNum)  = RadSysTiHBQsrcCoef(SurfNum)  ! Partitions are assumed to be symmetric
          END IF
        ELSE IF(Surface(SurfNum)%HeatTransferAlgorithm == HeatTransferModel_CondFD .OR. &
                Surface(SurfNum)%HeatTransferAlgorithm == HeatTransferModel_HAMT) THEN
          IF(Surface(SurfNum)%HeatTransferAlgorithm == HeatTransferModel_HAMT) &
             CALL ManageHeatBalHAMT(SurfNum,TempSurfInTmp(SurfNum),TempSurfOutTmp)  !HAMT
          If(Surface(SurfNum)%HeatTransferAlgorithm  == HeatTransferModel_CondFD )  &
             CALL ManageHeatBalFiniteDiff(SurfNum,TempSurfInTmp(SurfNum),TempSurfOutTmp)
          TH(SurfNum,1,1) = TempSurfOutTmp
        End If
        TempSurfIn(SurfNum) = TempSurfInTmp(SurfNum)
      ELSE  ! Standard surface or interzone surface
        IF (Surface(SurfNum)%Class /= SurfaceClass_Window) THEN ! Opaque surface
          HMovInsul = 0.0d0
          IF (Surface(SurfNum)%MaterialMovInsulInt > 0) &
            CALL EvalInsideMovableInsulation(SurfNum,HMovInsul,AbsInt)
          IF (HMovInsul <= 0.0d0) THEN  ! No movable insulation present, normal heat balance equation
            IF (Surface(SurfNum)%HeatTransferAlgorithm == HeatTransferModel_CTF .OR. &
                Surface(SurfNum)%HeatTransferAlgorithm == HeatTransferModel_EMPD) THEN ! Regular CTF Surface and/or EMPD surface
               IF (Surface(SurfNum)%HeatTransferAlgorithm == HeatTransferModel_EMPD) THEN
                  Call CalcMoistureBalanceEMPD(SurfNum, TempSurfInTmp(SurfNum), &
                      TH(SurfNum,2,2), MAT(ZoneNum),TempSurfInSat)
               End If
               TempSurfInTmp(SurfNum) = ( CTFConstInPart(SurfNum)              & ! Constant part of conduction eq (history terms)
                                        +QRadThermInAbs(SurfNum)              & ! LW radiation from internal sources
                                        +QRadSWInAbs(SurfNum)                 & ! SW radiation from internal sources
                                        +HConvIn(SurfNum)*RefAirTemp(SurfNum) & ! Convection from surface to zone air
                                        +NetLWRadToSurf(SurfNum)              & ! Net radiant exchange with other zone surfaces
                                        +Construct(ConstrNum)%CTFSourceIn(0)  & ! Heat source/sink term for radiant systems
                                         *QsrcHist(SurfNum,1)                 & ! (if there is one present)
                                        +QHTRadSysSurf(SurfNum)               & ! Radiant flux from high temp radiant heater
                                        +QHWBaseboardSurf(SurfNum)            & ! Radiant flux from a hot water baseboard heater
                                        +QSteamBaseboardSurf(SurfNum)         & ! Radiant flux from a steam baseboard heater
                                        +QElecBaseboardSurf(SurfNum)          & ! Radiant flux from an electric baseboard heater
                                        +IterDampConst                        &
                                         *TempInsOld(SurfNum)                 & ! Iterative damping term (for stability)
                                        +Construct(ConstrNum)%CTFCross(0)     & ! Current conduction from
                                         *TH(SurfNum,1,1) )                   & ! the outside surface
                                      /( Construct(ConstrNum)%CTFInside(0)    & ! Coefficient for conduction (current time)
                                        +HConvIn(SurfNum)+IterDampConst )         ! Convection and damping term
               IF (Surface(SurfNum)%HeatTransferAlgorithm == HeatTransferModel_EMPD) THEN
                 TempSurfInTmp(SurfNum) = TempSurfInTmp(SurfNum)              &
                                          -MoistEMPDFlux(SurfNum)              &
                                          /( Construct(ConstrNum)%CTFInside(0) &  ! Coefficient for conduction (current time)
                                            +HConvIn(SurfNum)+IterDampConst )   ! Convection and damping term
                 if (TempSurfInSat .GT. TempSurfInTmp(SurfNum)) then
                   TempSurfInTmp(SurfNum) = TempSurfInSat ! Surface temp cannot be below dew point
                 end if
               End If
             ! if any mixed heat transfer models in zone, apply limits to CTF result
              IF (ANY(Surface(Zone(ZoneNum)%SurfaceFirst:Zone(ZoneNum)%SurfaceLast)%HeatTransferAlgorithm &
                       == HeatTransferModel_CondFD) .OR. &
                  ANY(Surface(Zone(ZoneNum)%SurfaceFirst:Zone(ZoneNum)%SurfaceLast)%HeatTransferAlgorithm &
                       == HeatTransferModel_HAMT) )&
                  THEN
                TempSurfInTmp(SurfNum) = MAX(MinSurfaceTempLimit,MIN(MaxSurfaceTempLimit,TempSurfInTmp(SurfNum)))  !Limit Check
              ENDIF
              IF (Construct(ConstrNum)%SourceSinkPresent) THEN  ! Set the appropriate parameters for the radiant system
                ! Radiant system does not need the damping coefficient terms (hopefully)
                RadSysTiHBConstCoef(SurfNum) = ( CTFConstInPart(SurfNum)       & ! Constant portion of cond eq (history terms)
                                                +QRadThermInAbs(SurfNum)       & ! LW radiation from internal sources
                                                +QRadSWInAbs(SurfNum)          & ! SW radiation from internal sources
                                                +HConvIn(SurfNum)*RefAirTemp(SurfNum) & ! Convection from surface to zone air
                                                +QHTRadSysSurf(SurfNum)        & ! Radiant flux from high temp radiant heater
                                                +QHWBaseboardSurf(SurfNum)     & ! Radiant flux from a hot water baseboard heater
                                                +QSteamBaseboardSurf(SurfNum)  & ! Radiant flux from a steam baseboard heater
                                                +QElecBaseboardSurf(SurfNum)   & ! Radiant flux from an electric baseboard heater
                                                +NetLWRadToSurf(SurfNum) )     & ! Net radiant exchange with other zone surfaces
                                              /( Construct(ConstrNum)%CTFInside(0) & ! Cond term (both partition sides same temp)
                                                +HConvIn(SurfNum) )              ! Convection and damping term
                RadSysTiHBToutCoef(SurfNum)  = Construct(ConstrNum)%CTFCross(0)    & ! Outside temp=inside temp for a partition
                                              /( Construct(ConstrNum)%CTFInside(0) & ! Cond term (both partition sides same temp)
                                                +HConvIn(SurfNum) )              ! Convection and damping term
                RadSysTiHBQsrcCoef(SurfNum)  = Construct(ConstrNum)%CTFSourceIn(0) & ! QTF term for the source
                                              /( Construct(ConstrNum)%CTFInside(0) & ! Cond term (both partition sides same temp)
                                                +HConvIn(SurfNum) )              ! Convection and damping term
                IF (Surface(SurfNum)%ExtBoundCond > 0) THEN ! This is an interzone partition and we need to set outside params
                  ! The inside coefficients of one side are equal to the outside coefficients of the other side.  But,
                  ! the inside coefficients are set up once the heat balance equation for that side has been calculated.
                  ! For both sides to actually have been set, we have to wait until we get to the second side in the surface
                  ! derived type.  At that point, both inside coefficient sets have been evaluated.
                  IF (Surface(SurfNum)%ExtBoundCond < SurfNum) THEN ! Both of the inside coefficients have now been set
                    OtherSideSurfNum                      = Surface(SurfNum)%ExtBoundCond
                    RadSysToHBConstCoef(OtherSideSurfNum) = RadSysTiHBConstCoef(SurfNum)
                    RadSysToHBTinCoef(OtherSideSurfNum)   = RadSysTiHBToutCoef(SurfNum)
                    RadSysToHBQsrcCoef(OtherSideSurfNum)  = RadSysTiHBQsrcCoef(SurfNum)
                    RadSysToHBConstCoef(SurfNum)          = RadSysTiHBConstCoef(OtherSideSurfNum)
                    RadSysToHBTinCoef(SurfNum)            = RadSysTiHBToutCoef(OtherSideSurfNum)
                    RadSysToHBQsrcCoef(SurfNum)           = RadSysTiHBQsrcCoef(OtherSideSurfNum)
                  END IF
                END IF
              END IF
            Else If(Surface(SurfNum)%HeatTransferAlgorithm  == HeatTransferModel_CondFD .OR. &
                    Surface(SurfNum)%HeatTransferAlgorithm == HeatTransferModel_HAMT) THEN
              IF(Surface(SurfNum)%HeatTransferAlgorithm == HeatTransferModel_HAMT) THEN
                 IF (Surface(SurfNum)%ExtBoundCond > 0) THEN
                    ! HAMT get the correct other side zone zone air temperature --
                    OtherSideSurfNum = Surface(SurfNum)%ExtBoundCond
                    ZoneNum = Surface(SurfNum)%Zone
                    OtherSideZoneNum = Surface(OtherSideSurfNum)%Zone
                    TempOutsideAirFD(SurfNum)= MAT(OtherSideZoneNum)
                 ENDIF
                CALL ManageHeatBalHAMT(SurfNum,TempSurfInTmp(SurfNum),TempSurfOutTmp)
              ENDIF
              If(Surface(SurfNum)%HeatTransferAlgorithm  == HeatTransferModel_CondFD )   &
                  CALL ManageHeatBalFiniteDiff(SurfNum,TempSurfInTmp(SurfNum),TempSurfOutTmp)
              TH(SurfNum,1,1) = TempSurfOutTmp
            End If
            TempSurfIn(SurfNum) = TempSurfInTmp(SurfNum)
          ELSE    ! Movable insulation present
            IF (Construct(ConstrNum)%SourceSinkPresent.AND.FirstTime) &
              CALL ShowSevereError('Movable insulation is not valid with embedded sources/sinks')
            F1 = HMovInsul/( HMovInsul + HConvIn(SurfNum) + IterDampConst )
            TempSurfIn(SurfNum) = ( CTFConstInPart(SurfNum)                          &
                                   +QRadSWInAbs(SurfNum)                             &
                                   +Construct(ConstrNum)%CTFCross(0)*TH(SurfNum,1,1) &
                                   +F1*( QRadThermInAbs(SurfNum)                     &
                                        +HConvIn(SurfNum)*RefAirTemp(SurfNum)        & ! Convection from surface to zone air
                                        +NetLWRadToSurf(SurfNum)                     &
                                        +QHTRadSysSurf(SurfNum)                      &
                                        +QHWBaseboardSurf(SurfNum)                   &
                                        +QSteamBaseboardSurf(SurfNum)                &
                                        +QElecBaseboardSurf(SurfNum)                 &
                                        +IterDampConst*TempInsOld(SurfNum) )       ) &
                                 /( Construct(ConstrNum)%CTFInside(0)                &
                                   +HMovInsul - F1*HMovInsul )
            TempSurfInTmp(SurfNum) = ( Construct(ConstrNum)%CTFInside(0)     &
                                       *TempSurfIn(SurfNum)                  &
                                      +HMovInsul*TempSurfIn(SurfNum)         &
                                      -QRadSWInAbs(SurfNum)                  &
                                      -CTFConstInPart(SurfNum)               &
                                      -Construct(ConstrNum)%CTFCross(0)      &
                                       *TH(SurfNum,1,1) )                    &
                                    /( HMovInsul )
            ! if any mixed heat transfer models in zone, apply limits to CTF result
            IF (ANY(Surface(Zone(ZoneNum)%SurfaceFirst:Zone(ZoneNum)%SurfaceLast)%HeatTransferAlgorithm &
                     == HeatTransferModel_CondFD) .OR. &
                ANY(Surface(Zone(ZoneNum)%SurfaceFirst:Zone(ZoneNum)%SurfaceLast)%HeatTransferAlgorithm &
                     == HeatTransferModel_HAMT) )&
                THEN
              TempSurfInTmp(SurfNum) = MAX(MinSurfaceTempLimit,MIN(MaxSurfaceTempLimit,TempSurfInTmp(SurfNum)))  !Limit Check
            ENDIF
          END IF
        ELSE  ! Window
          IF (Construct(ConstrNum)%SourceSinkPresent.AND.FirstTime) &
            CALL ShowSevereError('Windows are not allowed to have embedded sources/sinks')
          IF (SurfaceWindow(SurfNum)%OriginalClass == SurfaceClass_TDD_Diffuser) THEN ! Tubular daylighting device
            ! Lookup up the TDD:DOME object
            PipeNum = FindTDDPipe(SurfNum)
            SurfNum2 = TDDPipe(PipeNum)%Dome
            Ueff = 1.0d0 / TDDPipe(PipeNum)%Reff
            ! Similar to opaque surface but outside surface temp of TDD:DOME is used, and no embedded sources/sinks.
            ! Absorbed shortwave radiation is treated similar to a regular window, but only 1 glass layer is allowed.
            !   = QRadSWwinAbs(SurfNum,1)/2.0
            TempSurfInTmp(SurfNum) = ( QRadThermInAbs(SurfNum)             & ! LW radiation from internal sources
                                      +QRadSWwinAbs(SurfNum,1)/2.0d0       & ! SW radiation from internal sources and solar
                                      +HConvIn(SurfNum)*RefAirTemp(SurfNum) & ! Convection from surface to zone air
                                      +NetLWRadToSurf(SurfNum)             & ! Net radiant exchange with other zone surfaces
                                      +IterDampConst                       &
                                       *TempInsOld(SurfNum)                & ! Iterative damping term (for stability)
                                      +Ueff*TH(SurfNum2,1,1) )             & ! Current conduction from the outside surface
                                    /( Ueff                                & ! Coefficient for conduction (current time)
                                      +HConvIn(SurfNum)+IterDampConst ) ! Convection and damping term
            TempSurfIn(SurfNum) = TempSurfInTmp(SurfNum)
            ! Calculate window heat gain for TDD:DIFFUSER since this calculation is usually done in WindowManager
            WinHeatGain(SurfNum) = WinTransSolar(SurfNum) & ! Transmitted solar
              + HConvIn(SurfNum) * Surface(SurfNum)%Area * (TempSurfIn(SurfNum) - RefAirTemp(SurfNum)) & ! Convection
              + Construct(Surface(SurfNum)%Construction)%InsideAbsorpThermal * Surface(SurfNum)%Area & ! IR exchange
              * (Sigma * TempSurfIn(SurfNum)**4 - (SurfaceWindow(SurfNum)%IRfromParentZone + QHTRadSysSurf(SurfNum) + &
                 QHWBaseboardSurf(SurfNum) + QSteamBaseboardSurf(SurfNum) + QElecBaseboardSurf(SurfNum)))     & ! IR
              - QS(Surface(SurfNum)%Zone) * Surface(SurfNum)%Area * Construct(Surface(SurfNum)%Construction)%TransDiff
              ! Zone diffuse interior shortwave reflected back into the TDD
            !fill out report vars for components of Window Heat Gain
            WinGainConvGlazToZoneRep(SurfNum) = HConvIn(SurfNum) * Surface(SurfNum)%Area &
                                                * (TempSurfIn(SurfNum) - RefAirTemp(SurfNum))
            WinGainIRGlazToZoneRep(SurfNum) = Construct(Surface(SurfNum)%Construction)%InsideAbsorpThermal &
                                              * Surface(SurfNum)%Area  &
                 * (Sigma * TempSurfIn(SurfNum)**4 - (SurfaceWindow(SurfNum)%IRfromParentZone + QHTRadSysSurf(SurfNum) + &
                      QHWBaseboardSurf(SurfNum) + QSteamBaseboardSurf(SurfNum) + QElecBaseboardSurf(SurfNum)))
            WinLossSWZoneToOutWinRep(SurfNum) = QS(Surface(SurfNum)%Zone) * Surface(SurfNum)%Area &
                                                 * Construct(Surface(SurfNum)%Construction)%TransDiff
            IF(WinHeatGain(SurfNum) >= 0.0d0) THEN
              WinHeatGainRep(SurfNum) = WinHeatGain(SurfNum)
              WinHeatGainRepEnergy(SurfNum) = WinHeatGainRep(SurfNum) * TimeStepZone * SecInHour
            ELSE
              WinHeatLossRep(SurfNum) = -WinHeatGain(SurfNum)
              WinHeatLossRepEnergy(SurfNum) = WinHeatLossRep(SurfNum) * TimeStepZone * SecInHour
            END IF
            TDDPipe(PipeNum)%HeatGain = WinHeatGainRep(SurfNum)
            TDDPipe(PipeNum)%HeatLoss = WinHeatLossRep(SurfNum)
          ELSE ! Regular window
            IF(InsideSurfIterations == 0) THEN  ! Do windows only once
              IF(SurfaceWindow(SurfNum)%StormWinFlag==1) ConstrNum = Surface(SurfNum)%StormWinConstruction
              ! Get outside convection coeff for exterior window here to avoid calling
              ! InitExteriorConvectionCoeff from CalcWindowHeatBalance, which avoids circular reference
              ! (HeatBalanceSurfaceManager USEing and WindowManager and
              ! WindowManager USEing HeatBalanceSurfaceManager)
              IF(Surface(SurfNum)%ExtBoundCond == ExternalEnvironment) THEN
                RoughSurf = Material(Construct(ConstrNum)%LayerPoint(1))%Roughness
                EmisOut = Material(Construct(ConstrNum)%LayerPoint(1))%AbsorpThermalFront
                IF(SurfaceWindow(SurfNum)%ShadingFlag == ExtShadeOn .OR. SurfaceWindow(SurfNum)%ShadingFlag==ExtBlindOn .OR. &
                   SurfaceWindow(SurfNum)%ShadingFlag == ExtScreenOn) THEN
                        ! Exterior shade in place
                  ConstrNumSh = SurfaceWindow(SurfNum)%ShadedConstruction
                  RoughSurf = Material(Construct(ConstrNumSh)%LayerPoint(1))%Roughness
                  EmisOut = Material(Construct(ConstrNumSh)%LayerPoint(1))%AbsorpThermal
                END IF
                ! Get the outside effective emissivity for Equivalent layer model
                IF ( Construct(ConstrNum)%WindowTypeEQL ) THEN
                   EmisOut = EQLWindowOutsideEffectiveEmiss(ConstrNum)
                ENDIF
                ! Set Exterior Convection Coefficient...
                IF (Surface(SurfNum)%ExtConvCoeff > 0) THEN
                  HcExtSurf(SurfNum)=SetExtConvectionCoeff(SurfNum)
                ELSEIF (Surface(SurfNum)%ExtWind) THEN  ! Window is exposed to wind (and possibly rain)
                  ! Calculate exterior heat transfer coefficients with windspeed (windspeed is calculated internally in subroutine)
                  CALL InitExteriorConvectionCoeff(SurfNum,0.0d0,RoughSurf,EmisOut,TH(SurfNum,1,1), &
                    HcExtSurf(SurfNum),HSkyExtSurf(SurfNum),HGrdExtSurf(SurfNum),HAirExtSurf(SurfNum))
                  IF (IsRain) THEN  ! Raining: since wind exposed, outside window surface gets wet
                    HcExtSurf(SurfNum)=1000.0d0 ! Reset HcExtSurf because of wetness
                  ENDIF
                ELSE  ! Not Wind exposed
                  ! Calculate exterior heat transfer coefficients for windspeed = 0
                  CALL InitExteriorConvectionCoeff(SurfNum,0.0d0,RoughSurf,EmisOut,TH(SurfNum,1,1), &
                    HcExtSurf(SurfNum),HSkyExtSurf(SurfNum),HGrdExtSurf(SurfNum),HAirExtSurf(SurfNum))
                END IF
              ELSE   ! Interior Surface
                IF (Surface(SurfNum)%ExtConvCoeff > 0) THEN
                  HcExtSurf(SurfNum)=SetExtConvectionCoeff(SurfNum)
                ELSE
                ! Exterior Convection Coefficient for the Interior or Interzone Window is the Interior Convection Coeff of same
                  HcExtSurf(SurfNum)=HConvIn(Surface(SurfNum)%ExtBoundCond)
                ENDIF
              ENDIF
              ! Following call determines inside surface temperature of glazing, and of
              ! frame and/or divider, if present
              CALL CalcWindowHeatBalance(SurfNum,HcExtSurf(SurfNum),TempSurfInTmp(SurfNum),TH(SurfNum,1,1))
              IF(WinHeatGain(SurfNum) >= 0.0d0) THEN
                WinHeatGainRep(SurfNum) = WinHeatGain(SurfNum)
                WinHeatGainRepEnergy(SurfNum) = WinHeatGainRep(SurfNum) * TimeStepZone * SecInHour
              ELSE
                WinHeatLossRep(SurfNum) = -WinHeatGain(SurfNum)
                WinHeatLossRepEnergy(SurfNum) = WinHeatLossRep(SurfNum) * TimeStepZone * SecInHour
              END IF
              TempSurfIn(SurfNum) = TempSurfInTmp(SurfNum)
            END IF
          END IF
        END IF
      END IF    ! ...end of inside surface heat balance equation selection
      TH(SurfNum,1,2)        = TempSurfIn(SurfNum)
      TempSurfInRep(SurfNum) = TempSurfIn(SurfNum)
      TempSurfOut(SurfNum)   = TH(SurfNum,1,1)  ! For reporting
      ! sign convention is positive means energy going into inside face from the air.
      QdotConvInRep(surfNum) = - Surface(SurfNum)%Area * HConvIn(SurfNum) * (TempSurfIn(SurfNum)-RefAirTemp(SurfNum))
      QdotConvInRepPerArea(surfNum) = - HConvIn(SurfNum) * (TempSurfIn(SurfNum)-RefAirTemp(SurfNum))
      QConvInReport(surfNum)          =  QdotConvInRep(surfNum)* SecInHour * TimeStepZone
      ! The QdotConvInRep which is called "Surface Inside Face Convection Heat Gain" is stored during
      ! sizing for both the normal and pulse cases so that load components can be derived later.
      IF (ZoneSizingCalc .AND. CompLoadReportIsReq) THEN
        IF (.NOT. WarmupFlag) THEN
          TimeStepInDay = (HourOfDay-1)*NumOfTimeStepInHour + TimeStep
          IF (isPulseZoneSizing) THEN
            loadConvectedWithPulse(surfNum,TimeStepInDay,CurOverallSimDay) = QdotConvInRep(surfNum)
          ELSE
            loadConvectedNormal(surfNum,TimeStepInDay,CurOverallSimDay) = QdotConvInRep(surfNum)
            netSurfRadSeq(surfNum,TimeStepInDay,CurOverallSimDay) = QdotRadNetSurfInRep(surfNum)
          END IF
        END IF
      END IF
      IF (SurfaceWindow(SurfNum)%OriginalClass == SurfaceClass_TDD_Diffuser) THEN ! Tubular daylighting device
        ! Tubular daylighting devices are treated as one big object with an effective R value.
        ! The outside face temperature of the TDD:DOME and the inside face temperature of the
        ! TDD:DIFFUSER are calculated with the outside and inside heat balances respectively.
        !
        ! Below, the resulting temperatures are copied to the inside face of the TDD:DOME
        ! and the outside face of the TDD:DIFFUSER for reporting.
        ! Set inside temp variables of TDD:DOME equal to inside temp of TDD:DIFFUSER
        TH(SurfNum2,1,2) = TempSurfIn(SurfNum)
        TempSurfIn(SurfNum2) = TempSurfIn(SurfNum)
        TempSurfInTmp(SurfNum2) = TempSurfIn(SurfNum)
        TempSurfInRep(SurfNum2) = TempSurfIn(SurfNum)
        ! Set outside temp reporting variable of TDD:DOME (since it gets skipped otherwise)
        TempSurfOut(SurfNum2) = TH(SurfNum2,1,1)
        ! Reset outside temp variables of TDD:DIFFUSER equal to outside temp of TDD:DOME
        TH(SurfNum,1,1) = TH(SurfNum2,1,1)
        TempSurfOut(SurfNum) = TH(SurfNum2,1,1)
      END IF
      IF ((TH(SurfNum,1,2) > MaxSurfaceTempLimit) .OR. &
          (TH(SurfNum,1,2) < MinSurfaceTempLimit) ) THEN
        IF (WarmupFlag) WarmupSurfTemp=WarmupSurfTemp+1
        IF (.not. WarmupFlag  .or. (WarmupFlag .and. WarmupSurfTemp > 10) .or. DisplayExtraWarnings) THEN
          IF (TH(SurfNum,1,2) < MinSurfaceTempLimit) THEN
            IF (Surface(SurfNum)%LowTempErrCount == 0) THEN
              CALL ShowSevereMessage('Temperature (low) out of bounds ['//TRIM(RoundSigDigits(TH(SurfNum,1,2),2))//  &
                                 '] for zone="'//trim(Zone(ZoneNum)%Name)//'", for surface="'//TRIM(Surface(SurfNum)%Name)//'"')
              CALL ShowContinueErrorTimeStamp(' ')
              IF (.not. Zone(ZoneNum)%TempOutOfBoundsReported) THEN
                CALL ShowContinueError('Zone="'//trim(Zone(ZoneNum)%Name)//'", Diagnostic Details:')
                IF (Zone(ZoneNum)%FloorArea > 0.0d0) THEN
                  CALL ShowContinueError('...Internal Heat Gain ['//  &
                       trim(RoundSigDigits(Zone(ZoneNum)%InternalHeatGains/Zone(ZoneNum)%FloorArea,3))//'] W/m2')
                ELSE
                  CALL ShowContinueError('...Internal Heat Gain (no floor) ['//  &
                       trim(RoundSigDigits(Zone(ZoneNum)%InternalHeatGains,3))//'] W')
                ENDIF
                IF (SimulateAirflowNetwork <= AirflowNetworkControlSimple) THEN
                  CALL ShowContinueError('...Infiltration/Ventilation ['//  &
                         trim(RoundSigDigits(Zone(ZoneNum)%NominalInfilVent,3))//'] m3/s')
                  CALL ShowContinueError('...Mixing/Cross Mixing ['//  &
                         trim(RoundSigDigits(Zone(ZoneNum)%NominalMixing,3))//'] m3/s')
                ELSE
                  CALL ShowContinueError('...Airflow Network Simulation: Nominal Infiltration/Ventilation/Mixing not available.')
                ENDIF
                IF (Zone(ZoneNum)%isControlled) THEN
                  CALL ShowContinueError('...Zone is part of HVAC controlled system.')
                ELSE
                  CALL ShowContinueError('...Zone is not part of HVAC controlled system.')
                ENDIF
                Zone(ZoneNum)%TempOutOfBoundsReported=.true.
              ENDIF
              CALL ShowRecurringSevereErrorAtEnd('Temperature (low) out of bounds for zone='//trim(Zone(ZoneNum)%Name)//  &
                             ' for surface='//TRIM(Surface(SurfNum)%Name),  &
                             Surface(SurfNum)%LowTempErrCount,ReportMaxOf=TH(SurfNum,1,2),ReportMaxUnits='C',  &
                             ReportMinOf=TH(SurfNum,1,2),ReportMinUnits='C')
            ELSE
              CALL ShowRecurringSevereErrorAtEnd('Temperature (low) out of bounds for zone='//trim(Zone(ZoneNum)%Name)//  &
                             ' for surface='//TRIM(Surface(SurfNum)%Name),  &
                             Surface(SurfNum)%LowTempErrCount,ReportMaxOf=TH(SurfNum,1,2),ReportMaxUnits='C',  &
                             ReportMinOf=TH(SurfNum,1,2),ReportMinUnits='C')
            ENDIF
          ELSE
            IF (Surface(SurfNum)%HighTempErrCount == 0) THEN
              CALL ShowSevereMessage('Temperature (high) out of bounds ('//TRIM(RoundSigDigits(TH(SurfNum,1,2),2))//  &
                                 '] for zone="'//trim(Zone(ZoneNum)%Name)//'", for surface="'//TRIM(Surface(SurfNum)%Name)//'"')
              CALL ShowContinueErrorTimeStamp(' ')
              IF (.not. Zone(ZoneNum)%TempOutOfBoundsReported) THEN
                CALL ShowContinueError('Zone="'//trim(Zone(ZoneNum)%Name)//'", Diagnostic Details:')
                IF (Zone(ZoneNum)%FloorArea > 0.0d0) THEN
                  CALL ShowContinueError('...Internal Heat Gain ['//  &
                       trim(RoundSigDigits(Zone(ZoneNum)%InternalHeatGains/Zone(ZoneNum)%FloorArea,3))//'] W/m2')
                ELSE
                  CALL ShowContinueError('...Internal Heat Gain (no floor) ['//  &
                       trim(RoundSigDigits(Zone(ZoneNum)%InternalHeatGains,3))//'] W')
                ENDIF
                IF (SimulateAirflowNetwork <= AirflowNetworkControlSimple) THEN
                  CALL ShowContinueError('...Infiltration/Ventilation ['//  &
                         trim(RoundSigDigits(Zone(ZoneNum)%NominalInfilVent,3))//'] m3/s')
                  CALL ShowContinueError('...Mixing/Cross Mixing ['//  &
                         trim(RoundSigDigits(Zone(ZoneNum)%NominalMixing,3))//'] m3/s')
                ELSE
                  CALL ShowContinueError('...Airflow Network Simulation: Nominal Infiltration/Ventilation/Mixing not available.')
                ENDIF
                IF (Zone(ZoneNum)%isControlled) THEN
                  CALL ShowContinueError('...Zone is part of HVAC controlled system.')
                ELSE
                  CALL ShowContinueError('...Zone is not part of HVAC controlled system.')
                ENDIF
                Zone(ZoneNum)%TempOutOfBoundsReported=.true.
              ENDIF
              CALL ShowRecurringSevereErrorAtEnd('Temperature (high) out of bounds for zone='//trim(Zone(ZoneNum)%Name)//  &
                             ' for surface='//TRIM(Surface(SurfNum)%Name),  &
                             Surface(SurfNum)%HighTempErrCount,ReportMaxOf=TH(SurfNum,1,2),ReportMaxUnits='C',  &
                             ReportMinOf=TH(SurfNum,1,2),ReportMinUnits='C')
            ELSE
              CALL ShowRecurringSevereErrorAtEnd('Temperature (high) out of bounds for zone='//trim(Zone(ZoneNum)%Name)//  &
                            ' for surface='//TRIM(Surface(SurfNum)%Name),  &
                             Surface(SurfNum)%HighTempErrCount,ReportMaxOf=TH(SurfNum,1,2),ReportMaxUnits='C',  &
                             ReportMinOf=TH(SurfNum,1,2),ReportMinUnits='C')
            ENDIF
          ENDIF
          IF (Zone(ZoneNum)%EnforcedReciprocity) THEN
            IF (WarmupSurfTemp > 3) THEN
              CALL ShowSevereError('CalcHeatBalanceInsideSurf: Zone="'//trim(Zone(ZoneNum)%Name)//  &
                 '" has view factor enforced reciprocity')
              CALL ShowContinueError(' and is having temperature out of bounds errors. Please correct zone geometry and rerun.')
              CALL ShowFatalError('CalcHeatBalanceInsideSurf: Program terminates due to preceding conditions.')
            ENDIF
          ELSEIF (WarmupSurfTemp > 10) THEN
              CALL ShowFatalError('CalcHeatBalanceInsideSurf: Program terminates due to preceding conditions.')
          ENDIF
        END IF
      END IF
      IF ((TH(SurfNum,1,2) > MaxSurfaceTempLimitBeforeFatal) .OR. &
          (TH(SurfNum,1,2) < MinSurfaceTempLimitBeforeFatal) ) THEN
        IF (.not. WarmupFlag) THEN
          IF (TH(SurfNum,1,2) < MinSurfaceTempLimitBeforeFatal) THEN
            CALL ShowSevereError('Temperature (low) out of bounds ['//TRIM(RoundSigDigits(TH(SurfNum,1,2),2))//  &
                                 '] for zone="'//trim(Zone(ZoneNum)%Name)//'", for surface="'//TRIM(Surface(SurfNum)%Name)//'"')
            CALL ShowContinueErrorTimeStamp(' ')
            IF (.not. Zone(ZoneNum)%TempOutOfBoundsReported) THEN
              CALL ShowContinueError('Zone="'//trim(Zone(ZoneNum)%Name)//'", Diagnostic Details:')
              IF (Zone(ZoneNum)%FloorArea > 0.0d0) THEN
                CALL ShowContinueError('...Internal Heat Gain ['//  &
                     trim(RoundSigDigits(Zone(ZoneNum)%InternalHeatGains/Zone(ZoneNum)%FloorArea,3))//'] W/m2')
              ELSE
                CALL ShowContinueError('...Internal Heat Gain (no floor) ['//  &
                     trim(RoundSigDigits(Zone(ZoneNum)%InternalHeatGains/Zone(ZoneNum)%FloorArea,3))//'] W')
              ENDIF
              IF (SimulateAirflowNetwork <= AirflowNetworkControlSimple) THEN
                CALL ShowContinueError('...Infiltration/Ventilation ['//  &
                       trim(RoundSigDigits(Zone(ZoneNum)%NominalInfilVent,3))//'] m3/s')
                CALL ShowContinueError('...Mixing/Cross Mixing ['//  &
                       trim(RoundSigDigits(Zone(ZoneNum)%NominalMixing,3))//'] m3/s')
              ELSE
                CALL ShowContinueError('...Airflow Network Simulation: Nominal Infiltration/Ventilation/Mixing not available.')
              ENDIF
              IF (Zone(ZoneNum)%isControlled) THEN
                CALL ShowContinueError('...Zone is part of HVAC controlled system.')
              ELSE
                CALL ShowContinueError('...Zone is not part of HVAC controlled system.')
              ENDIF
              Zone(ZoneNum)%TempOutOfBoundsReported=.true.
            ENDIF
            CALL ShowFatalError('Program terminates due to preceding condition.')
          ELSE
            CALL ShowSevereError('Temperature (high) out of bounds ['//TRIM(RoundSigDigits(TH(SurfNum,1,2),2))//  &
                                 '] for zone="'//trim(Zone(ZoneNum)%Name)//'", for surface="'//TRIM(Surface(SurfNum)%Name)//'"')
            CALL ShowContinueErrorTimeStamp(' ')
            IF (.not. Zone(ZoneNum)%TempOutOfBoundsReported) THEN
              CALL ShowContinueError('Zone="'//trim(Zone(ZoneNum)%Name)//'", Diagnostic Details:')
              IF (Zone(ZoneNum)%FloorArea > 0.0d0) THEN
                CALL ShowContinueError('...Internal Heat Gain ['//  &
                     trim(RoundSigDigits(Zone(ZoneNum)%InternalHeatGains/Zone(ZoneNum)%FloorArea,3))//'] W/m2')
              ELSE
                CALL ShowContinueError('...Internal Heat Gain (no floor) ['//  &
                     trim(RoundSigDigits(Zone(ZoneNum)%InternalHeatGains/Zone(ZoneNum)%FloorArea,3))//'] W')
              ENDIF
              IF (SimulateAirflowNetwork <= AirflowNetworkControlSimple) THEN
                CALL ShowContinueError('...Infiltration/Ventilation ['//  &
                       trim(RoundSigDigits(Zone(ZoneNum)%NominalInfilVent,3))//'] m3/s')
                CALL ShowContinueError('...Mixing/Cross Mixing ['//  &
                       trim(RoundSigDigits(Zone(ZoneNum)%NominalMixing,3))//'] m3/s')
              ELSE
                CALL ShowContinueError('...Airflow Network Simulation: Nominal Infiltration/Ventilation/Mixing not available.')
              ENDIF
              IF (Zone(ZoneNum)%isControlled) THEN
                CALL ShowContinueError('...Zone is part of HVAC controlled system.')
              ELSE
                CALL ShowContinueError('...Zone is not part of HVAC controlled system.')
              ENDIF
              Zone(ZoneNum)%TempOutOfBoundsReported=.true.
            ENDIF
            CALL ShowFatalError('Program terminates due to preceding condition.')
          ENDIF
        END IF
      END IF
    END DO  ! ...end of loop over all surfaces for inside heat balances
          ! Interzone surface updating: interzone surfaces have other side temperatures
          ! which can vary as the simulation iterates through the inside heat
          ! balance.  This block is intended to "lock" the opposite side (outside)
          ! temperatures to the correct value, namely the value calculated by the
          ! inside surface heat balance for the other side.
    DO SurfNum = 1, TotSurfaces
      IF (PRESENT(ZoneToResimulate)) THEN
        IF ((Surface(SurfNum)%Zone /= ZoneToResimulate) .AND. (AdjacentZoneToSurface(SurfNum) /= ZoneToResimulate)) THEN
          CYCLE ! skip surfaces that are not associated with this zone
        ENDIF
      ENDIF
          ! Interzones must have an exterior boundary condition greater than zero
          ! (meaning that the other side is a surface) and the surface number must
          ! not be the surface itself (which is just a simple partition)
      IF ( (Surface(SurfNum)%ExtBoundCond > 0) .AND. (Surface(SurfNum)%ExtBoundCond /= SurfNum) ) THEN
          ! Set the outside surface temperature to the inside surface temperature
          ! of the interzone pair and reassign the reporting variable.  By going
          ! through all of the surfaces, this should pick up the other side as well
          ! as affect the next iteration.
        TH(SurfNum,1,1)      = TH(Surface(SurfNum)%ExtBoundCond,1,2)
        TempSurfOut(SurfNum) = TH(SurfNum,1,1)
      END IF
    END DO
    InsideSurfIterations = InsideSurfIterations + 1
          ! Convergence check
    MaxDelTemp      = 0.0d0
    DO SurfNum = 1, TotSurfaces   ! Loop through all surfaces to check for convergence...
      IF (.NOT. Surface(SurfNum)%HeatTransSurf) CYCLE  ! Skip non-heat transfer surfaces
      IF (PRESENT(ZoneToResimulate)) THEN
        IF ((Surface(SurfNum)%Zone /= ZoneToResimulate) .AND. (AdjacentZoneToSurface(SurfNum) /= ZoneToResimulate)) THEN
          CYCLE ! skip surfaces that are not associated with this zone
        ENDIF
      ENDIF
      ConstrNum = Surface(SurfNum)%Construction
      IF(Construct(ConstrNum)%TransDiff <= 0.0d0) THEN  ! Opaque surface
        MaxDelTemp = MAX(ABS(TempSurfIn(SurfNum)-TempInsOld(SurfNum)),MaxDelTemp)
        IF (Surface(SurfNum)%HeatTransferAlgorithm  == HeatTransferModel_CondFD) THEN
          ! also check all internal nodes as well as surface faces
          MaxDelTemp = MAX(MaxDelTemp, SurfaceFD(SurfNum)%MaxNodeDelTemp)
        ENDIF
      END IF
    END DO  ! ...end of loop to check for convergence
    IF (.NOT. ANY(HeatTransferAlgosUsed == UseCondFD)) THEN
      IF (MaxDelTemp <= MaxAllowedDelTemp) Converged = .TRUE.
    ELSE
      IF (MaxDelTemp <= MaxAllowedDelTempCondFD) Converged = .TRUE.
!Feb2012      IF ((InsideSurfIterations > IterationsForCondFDRelaxChange) .and. (.NOT. Converged) .AND.   &
!Feb2012          (.NOT. CondFDVariableProperties)) THEN
!Feb2012          ! adjust relaxation factor down, assume large number of iterations is result of instability
!Feb2012        CondFDRelaxFactor = CondFDRelaxFactor * 0.9d0
!Feb2012        IF (CondFDRelaxFactor < 0.2d0) CondFDRelaxFactor = 0.2d0
  ! resets relaxation factor to speed up iterations when under-relaxatation is not needed.
      IF (InsideSurfIterations <=1) THEN
        CondFDRelaxFactor=CondFDRelaxFactorInput
      ENDIF
      IF ((InsideSurfIterations > IterationsForCondFDRelaxChange) .and. .not. Converged) THEN
          ! adjust relaxation factor down, assume large number of iterations is result of instability
        CondFDRelaxFactor = CondFDRelaxFactor * 0.9d0
        IF (CondFDRelaxFactor < 0.1d0) CondFDRelaxFactor = 0.1d0
      ENDIF
    ENDIF
#ifdef EP_Count_Calls
    NumMaxInsideSurfIterations=MAX(NumMaxInsideSurfIterations,InsideSurfIterations)
#endif
    IF (InsideSurfIterations < MinIterations) Converged = .FALSE.
    IF (InsideSurfIterations > MaxIterations) THEN
      IF (.NOT.WarmupFlag) THEN
        ErrCount=ErrCount+1
        IF (ErrCount < 16) THEN
          IF (.NOT. ANY(HeatTransferAlgosUsed == UseCondFD)) THEN
            CALL ShowWarningError('Inside surface heat balance did not converge '// &
                 'with Max Temp Difference [C] ='//TRIM(RoundSigDigits(MaxDelTemp,3))//  &
                 ' vs Max Allowed Temp Diff [C] ='//TRIM(RoundSigDigits(MaxAllowedDelTemp,3)))
            CALL ShowContinueErrorTimeStamp(' ')
          ELSE
            CALL ShowWarningError('Inside surface heat balance did not converge '// &
                 'with Max Temp Difference [C] ='//TRIM(RoundSigDigits(MaxDelTemp,3))//  &
                 ' vs Max Allowed Temp Diff [C] ='//TRIM(RoundSigDigits(MaxAllowedDelTempCondFD,6)))
            CALL ShowContinueErrorTimeStamp(' ')
          ENDIF
        ELSE
          CALL ShowRecurringWarningErrorAtEnd('Inside surface heat balance convergence problem continues',  &
                                               InsideSurfErrCount,ReportMaxOf=MaxDelTemp,ReportMinOf=MaxDelTemp,  &
                                               ReportMaxUnits='[C]',ReportMinUnits='[C]')
        ENDIF
      ENDIF
      EXIT ! DO loop
    END IF
  END DO    ! ...end of main inside heat balance DO loop (ends when Converged)
  ! Update SumHmXXXX
  IF ( ANY(HeatTransferAlgosUsed == UseCondFD) .OR. &
       ANY(HeatTransferAlgosUsed == UseEMPD) .OR. ANY(HeatTransferAlgosUsed == UseHAMT)) THEN
    DO SurfNum = 1, TotSurfaces
      IF (.NOT. Surface(SurfNum)%HeatTransSurf) CYCLE ! Skip non-heat transfer surfaces
      IF (Surface(SurfNum)%Class == SurfaceClass_Window) CYCLE
      ZoneNum = Surface(SurfNum)%Zone
      IF (PRESENT(ZoneToResimulate)) THEN
        IF ((ZoneNum /= ZoneToResimulate) .AND. (AdjacentZoneToSurface(SurfNum) /= ZoneToResimulate)) THEN
          CYCLE ! skip surfaces that are not associated with this zone
        ENDIF
      ENDIF
      IF(Surface(SurfNum)%HeatTransferAlgorithm == HeatTransferModel_HAMT) THEN
         CALL UpdateHeatBalHAMT(SurfNum)
         SumHmAW(ZoneNum)= SumHmAW(ZoneNum)+HMassConvInFD(SurfNum)*Surface(SurfNum)%Area*  &
                           (RhoVaporSurfIn(SurfNum)-RhoVaporAirIn(SurfNum))
         RhoAirZone=PsyRhoAirFnPbTdbW(OutBaroPress,Mat(Surface(SurfNum)%Zone),PsyWFnTdbRhPb(Mat(Surface(SurfNum)%Zone),  &
              PsyRhFnTdbRhov(Mat(Surface(SurfNum)%Zone),RhoVaporAirIn(SurfNum),'RhoAirZone'),OutBaroPress))
         Wsurf=PsyWFnTdbRhPb(TempSurfInTmp(SurfNum), &
              PsyRhFnTdbRhov(TempSurfInTmp(SurfNum),RhoVaporSurfIn(SurfNum),'Wsurf'),OutBaroPress)
         SumHmARa(ZoneNum)= SumHmARa(ZoneNum)+HMassConvInFD(SurfNum)*Surface(SurfNum)%Area*RhoAirZone
         SumHmARaW(ZoneNum)= SumHmARaW(ZoneNum)+HMassConvInFD(SurfNum)*Surface(SurfNum)%Area*RhoAirZone*Wsurf
      ENDIF
      IF (Surface(SurfNum)%HeatTransferAlgorithm == HeatTransferModel_EMPD) THEN
         ! need to calculate the amount of moisture that is entering or
         ! leaving the zone  Qm [kg/sec] = hmi * Area * (Del Rhov)
         ! {Hmi [m/sec];     Area [m2];    Rhov [kg moist/m3]  }
         ! Positive values are into the zone and negative values are
         ! leaving the zone.  SumHmAw is the sum of the moisture entering or
         ! leaving the zone from all of the surfaces and is a rate.  Multiply
         ! by time to get the actual amount affecting the zone volume of air.
         CALL UpdateMoistureBalanceEMPD(SurfNum)
         RhoVaporSurfIn(SurfNum) = MoistEMPDNew(SurfNum)
            !SUMC(ZoneNum) = SUMC(ZoneNum)-MoistEMPDFlux(SurfNum)*Surface(SurfNum)%Area
         SumHmAW(ZoneNum)= SumHmAW(ZoneNum)+HMassConvInFD(SurfNum)*Surface(SurfNum)%Area*  &
                           (RhoVaporSurfIn(SurfNum)-RhoVaporAirIn(SurfNum))
         SumHmARa(ZoneNum)= SumHmARa(ZoneNum)+HMassConvInFD(SurfNum)*Surface(SurfNum)%Area* &
                      PsyRhoAirFnPbTdbW(OutBaroPress,  &
                                        TempSurfInTmp(SurfNum),  &
                                        PsyWFnTdbRhPb(TempSurfInTmp(SurfNum),  &
                                                      PsyRhFnTdbRhovLBnd0C(TempSurfInTmp(SurfNum),  &
                                                                           RhoVaporAirIn(SurfNum)),  &
                                                      OutBaroPress))
         SumHmARaW(ZoneNum)= SumHmARaW(ZoneNum)+HMassConvInFD(SurfNum)*Surface(SurfNum)%Area*RhoVaporSurfIn(SurfNum)
      END IF
    END DO
  ENDIF
! Calculate ZoneWinHeatGain/Loss
  IF (.not. PartialResimulate) THEN
    ZoneWinHeatGain         =0.d0
    ZoneWinHeatGainRep      =0.d0
    ZoneWinHeatGainRepEnergy=0.d0
    ZoneWinHeatLossRep      =0.d0
    ZoneWinHeatLossRepEnergy=0.d0
  ELSE
    ZoneWinHeatGain(ZoneToResimulate)         =0.d0
    ZoneWinHeatGainRep(ZoneToResimulate)      =0.d0
    ZoneWinHeatGainRepEnergy(ZoneToResimulate)=0.d0
    ZoneWinHeatLossRep(ZoneToResimulate)      =0.d0
    ZoneWinHeatLossRepEnergy(ZoneToResimulate)=0.d0
  ENDIF
  DO SurfNum=1,TotSurfaces
    IF(.not. Surface(SurfNum)%ExtSolar) CYCLE        ! WindowManager's definition of ZoneWinHeatGain/Loss
    IF(Surface(SurfNum)%Class /= SurfaceClass_Window) CYCLE
    ZoneNum=Surface(SurfNum)%Zone
    IF (ZoneNum == 0) CYCLE
    IF (PRESENT(ZoneToResimulate)) THEN
      IF ((ZoneNum /= ZoneToResimulate) .AND. (AdjacentZoneToSurface(SurfNum) /= ZoneToResimulate)) THEN
        CYCLE ! skip surfaces that are not associated with this zone
      ENDIF
    ENDIF
    ZoneWinHeatGain(ZoneNum) = ZoneWinHeatGain(ZoneNum) + WinHeatGain(SurfNum)
  ENDDO
  DO ZoneNum = 1,NumOfZones
    IF ( PRESENT(ZoneToResimulate)  .AND. (ZoneNum /= ZoneToResimulate)) CYCLE
    IF(ZoneWinHeatGain(ZoneNum) >= 0.0d0) THEN
      ZoneWinHeatGainRep(ZoneNum) = ZoneWinHeatGain(ZoneNum)
      ZoneWinHeatGainRepEnergy(ZoneNum) = ZoneWinHeatGainRep(ZoneNum) * TimeStepZone * SecInHour
    ELSE
      ZoneWinHeatLossRep(ZoneNum) = -ZoneWinHeatGain(ZoneNum)
      ZoneWinHeatLossRepEnergy(ZoneNum) = ZoneWinHeatLossRep(ZoneNum) * TimeStepZone * SecInHour
    END IF
  END DO
  IF (PRESENT(ZoneToResimulate)) THEN
    CALL CalculateZoneMRT(ZoneToResimulate) ! Update here so that the proper value of MRT is available to radiant systems
  ELSE
    CALL CalculateZoneMRT ! Update here so that the proper value of MRT is available to radiant systems
  ENDIF
  FirstTime = .FALSE.
  RETURN
END SUBROUTINE CalcHeatBalanceInsideSurf
All Procedures
AbortEnergyPlus AbsoluteAirMass ActivateDemandManagers ActivateEMSControls AddBlankKeys addChargesToOperand AddCompSizeTableEntry AddEndUseSubcategory AddError addFootNoteSubTable AddInstruction AddMeter addMonthlyCharge AddMonthlyFieldSetInput AddMonthlyReport AddNeighborInformation AddObjectDefandParse addOperand AddRecordFromSection AddRecordToOutputVariableStructure AddSectionDef AddShadowRelateTableEntry AddSQLiteComponentSizingRecord AddSQLiteComponentSizingRecord AddSQLiteSystemSizingRecord AddSQLiteSystemSizingRecord AddSQLiteZoneSizingRecord AddSQLiteZoneSizingRecord AddTOCEntry AddTOCZoneLoadComponentTable AddToOutputVariableList AddVariablesForMonthlyReport AddVariableSlatBlind AddWindow AdjustAirSetpointsforOpTempCntrl AdjustCBF AdjustCBF AdjustChangeInLoadByEMSControls AdjustChangeInLoadByHowServed AdjustChangeInLoadForLastStageUpperRangeLimit AdjustCoolingSetPointforTempAndHumidityControl adjusthhat AdjustPumpFlowRequestByEMSControls AdjustReportingHourAndMinutes AdjustVBGap AdvanceRootFinder AFECFR AFECOI AFECPD AFECPF AFEDMP AFEDOP AFEDWC AFEELR AFEEXF AFEFAN AFEHEX AFEHOP AFEPLR AFESCR AFESEL AFESOP AFETMU AirflowNetworkVentingControl AirMass AIRMOV AllocateAirflowNetworkData AllocateAirHeatBalArrays AllocateAndInitData AllocateAndSetUpVentReports AllocateCFSStateHourlyData AllocateForCFSRefPointsGeometry AllocateForCFSRefPointsState AllocateHeatBalArrays AllocateLoadComponentArrays AllocateModuleArrays AllocateModuleArrays AllocateSurfaceHeatBalArrays AllocateWeatherData angle_2dvector AnisoSkyViewFactors AnyPlantLoopSidesNeedSim AnyPlantSplitterMixerLacksContinuity AreaPolygon ArgCheck array_to_vector ASHRAETauModel ASHWAT_OffNormalProperties ASHWAT_Solar ASHWAT_Thermal ASSIGNMENT (=) AssignNodeNumber AssignReportNumber AssignResourceTypeNum AssignReverseConstructionNumber AssignVariablePt AttachCustomMeters AttachMeters AuditBranches AUTOTDMA BaseThermalPropertySet_Diffusivity BeginEnvrnInitializeRuntimeLanguage BetweenDates BetweenGlassForcedFlow BetweenGlassShadeForcedFlow BetweenGlassShadeNaturalFlow BisectionMethod BlindBeamBeamTrans BlindOpticsBeam BlindOpticsDiffuse BoreholeResistance BoundValueToNodeMinMaxAvail BoundValueToWithinTwoValues BracketRoot BranchPressureDrop BrentMethod BuildGap BuildKeyVarList Calc4PipeFanCoil Calc_EN673 Calc_ISO15099 CalcActiveTranspiredCollector CalcAggregateLoad CalcAirflowNetworkAirBalance CalcAirflowNetworkCO2Balance CalcAirflowNetworkGCBalance CalcAirflowNetworkHeatBalance CalcAirflowNetworkMoisBalance CalcAirFlowSimple CalcAirLoopSplitter CalcAirMixer CalcAirToAirGenericHeatExch CalcAirToAirPlateHeatExch CalcAirZoneReturnPlenum CalcAirZoneSupplyPlenum CalcAlamdariHammondStableHorizontal CalcAlamdariHammondUnstableHorizontal CalcAlamdariHammondVerticalWall CalcAngleFactorMRT CalcApproximateViewFactors CalcASHRAEDetailedIntConvCoeff CalcASHRAESimpExtConvectCoeff CalcASHRAESimpleIntConvCoeff CalcASHRAEVerticalWall CalcATMixer CalcAwbiHattonHeatedFloor CalcAwbiHattonHeatedWall CalcBasinHeaterPower CalcBasinHeaterPowerForMultiModeDXCoil CalcBeamSolarOnWinRevealSurface CalcBeamSolDiffuseReflFactors CalcBeamSolSpecularReflFactors CalcBeausoleilMorrisonMixedAssistedWall CalcBeausoleilMorrisonMixedOpposingWall CalcBeausoleilMorrisonMixedStableCeiling CalcBeausoleilMorrisonMixedStableFloor CalcBeausoleilMorrisonMixedUnstableCeiling CalcBeausoleilMorrisonMixedUnstableFloor CalcBLASTAbsorberModel CalcBlockenWindward CalcBoilerModel CalcBoilerModel CalcBottomFluxCoefficents CalcBottomSurfTemp CalcBuriedPipeSoil CalcCBF CalcCBF CalcCBVAV CalcCeilingDiffuserInletCorr CalcCeilingDiffuserIntConvCoeff CalcChillerHeaterModel CalcChillerIPLV CalcChillerModel CalcClearRoof CalcCoilUAbyEffectNTU CalcColdestSetPoint CalcComplexWindowOverlap CalcComplexWindowThermal CalcCompSuctionTempResidual CalcCondEntSetPoint CalcConnectionsDrainTemp CalcConnectionsFlowRates CalcConnectionsHeatRecovery CalcConstCOPChillerModel CalcConvCoeffAbsPlateAndWater CalcConvCoeffBetweenPlates CalcCoolBeam CalcCoolTower CalcCoordinateTransformation CalcCoPlanarNess CalcCostEstimate CalcCTGeneratorModel CalcDayltgCoefficients CalcDayltgCoeffsMapPoints CalcDayltgCoeffsRefMapPoints CalcDayltgCoeffsRefPoints CalcDesiccantBalancedHeatExch CalcDesignSpecificationOutdoorAir CalcDesuperheaterHeatingCoil CalcDesuperheaterWaterHeater CalcDetailedHcInForDVModel CalcDetailedSystem CalcDetailedTransSystem CalcDetailFlatFinCoolingCoil CalcDetIceStorLMTDstar CalcDiffTSysAvailMgr CalcDirectAir CalcDirectEvapCooler CalcDirectResearchSpecialEvapCooler CalcDoe2DXCoil CalcDOE2Leeward CalcDOE2Windward CalcDryFinEffCoef CalcDryIndirectEvapCooler CalcDuct CalcDXCoilStandardRating CalcDXHeatingCoil CalcEarthTube CalcEcoRoof CalcEffectiveness CalcEffectiveSHR CalcEffectiveSHR CalcEffectiveSHR CalcEffectiveSHR CalcElecSteamHumidifier CalcElectricBaseboard CalcElectricChillerHeatRecovery CalcElectricChillerModel CalcElectricEIRChillerModel CalcElectricHeatingCoil CalcEmmelRoof CalcEmmelVertical CalcEngineChillerHeatRec CalcEngineDrivenChillerModel CalcEQLOpticalProperty CalcEQLWindowOpticalProperty CalcEQLWindowSHGCAndTransNormal CalcEQLWindowStandardRatings CalcEQLWindowUvalue CalcEquipmentDrainTemp CalcEquipmentFlowRates CalcExhaustAbsorberChillerModel CalcExhaustAbsorberHeaterModel CalcExteriorVentedCavity CalcFisherPedersenCeilDiffuserCeiling CalcFisherPedersenCeilDiffuserFloor CalcFisherPedersenCeilDiffuserWalls CalcFluidHeatExchanger CalcFohannoPolidoriVerticalWall CalcFollowOATempSetPoint CalcFollowSysNodeTempSetPoint CalcFourPipeIndUnit CalcFrameDividerShadow CalcFuelCellAuxHeater CalcFuelCellGeneratorModel CalcFuelCellGenHeatRecovery CalcFurnaceOutput CalcFurnaceResidual CalcGasAbsorberChillerModel CalcGasAbsorberHeaterModel CalcGasCooler CalcGasHeatingCoil CalcGenericDesiccantDehumidifier CalcGoldsteinNovoselacCeilingDiffuserFloor CalcGoldsteinNovoselacCeilingDiffuserWall CalcGoldsteinNovoselacCeilingDiffuserWindow CalcGroundTempSetPoint CalcGroundwaterWell CalcGshpModel CalcGshpModel CalcGTChillerModel CalcHeatBalanceAir CalcHeatBalanceInsideSurf CalcHeatBalanceInsideSurf CalcHeatBalanceOutsideSurf CalcHeatBalanceOutsideSurf CalcHeatBalFiniteDiff CalcHeatBalHAMT CalcHeatPumpWaterHeater CalcHeatTransCoeffAndCoverTemp CalcHfExteriorSparrow CalcHighTempRadiantSystem CalcHighTempRadiantSystemSP CalcHiTurnOffSysAvailMgr CalcHiTurnOnSysAvailMgr CalcHnASHRAETARPExterior CalcHPCoolingSimple CalcHPHeatingSimple CalcHPWHDXCoil CalcHWBaseboard CalcHXAssistedCoolingCoil CalcHXEffectTerm CalcHybridVentSysAvailMgr CalcIBesselFunc CalcICEngineGeneratorModel CalcICEngineGenHeatRecovery CalcIceStorageCapacity CalcIceStorageCharge CalcIceStorageDischarge CalcIceStorageDormant CalcICSSolarCollector CalcIdealCondEntSetPoint CalcIfSetpointMet CalcIndirectAbsorberModel CalcIndirectResearchSpecialEvapCooler CalcInteriorRadExchange CalcInteriorSolarDistribution CalcInteriorSolarOverlaps CalcInteriorWinTransDifSolInitialDistribution CalcISO15099WindowIntConvCoeff CalcKaradagChilledCeiling CalcKBesselFunc CalcKhalifaEq3WallAwayFromHeat CalcKhalifaEq4CeilingAwayFromHeat CalcKhalifaEq5WallsNearHeat CalcKhalifaEq6NonHeatedWalls CalcKhalifaEq7Ceiling CalcLoadCenterThermalLoad CalcLoTurnOffSysAvailMgr CalcLoTurnOnSysAvailMgr CalcLowTempCFloRadiantSystem CalcLowTempCFloRadSysComps CalcLowTempElecRadiantSystem CalcLowTempHydrRadiantSystem CalcLowTempHydrRadSysComps CalcMatrixInverse CalcMcAdams CalcMerkelVariableSpeedTower CalcMicroCHPNoNormalizeGeneratorModel CalcMinIntWinSolidAngs CalcMitchell CalcMixedAirSetPoint CalcMoistureBalanceEMPD CalcMoreNodeInfo CalcMoWITTLeeward CalcMoWITTWindward CalcMSHeatPump CalcMTGeneratorModel CalcMultiSpeedDXCoil CalcMultiSpeedDXCoilCooling CalcMultiSpeedDXCoilHeating CalcMultiStageElectricHeatingCoil CalcMultiStageGasHeatingCoil CalcMultiZoneAverageCoolingSetPoint CalcMultiZoneAverageHeatingSetPoint CalcMultiZoneAverageMaxHumSetPoint CalcMultiZoneAverageMinHumSetPoint CalcMultiZoneMaxHumSetPoint CalcMultiZoneMinHumSetPoint CalcMundtModel CalcNCycSysAvailMgr CalcNewZoneHeatCoolFlowRates CalcNewZoneHeatOnlyFlowRates CalcNodeMassFlows CalcNominalWindowCond CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNusselt CalcNusseltJurges CalcNVentSysAvailMgr CalcOAController CalcOAMassFlow CalcOAMassFlow CalcOAMixer CalcOAOnlyMassFlow CalcOAPretreatSetPoint CalcOAUnitCoilComps CalcObstrMultiplier CalcOptStartSysAvailMgr CalcOtherSideDemand CalcOutdoorAirUnit CalcOutsideAirSetPoint CalcOutsideSurfTemp CalcParallelPIU CalcPassiveExteriorBaffleGap CalcPassiveSystem CalcPassiveTranspiredCollector CalcPerSolarBeam CalcPipeHeatTransCoef CalcPipesHeatTransfer CalcPipeTransBeam CalcPlantValves CalcPollution CalcPolyhedronVolume CalcPolynomCoef CalcPondGroundHeatExchanger CalcPredictedHumidityRatio CalcPredictedSystemLoad CalcPTUnit CalcPumps CalcPurchAirLoads CalcPurchAirMinOAMassFlow CalcPurchAirMixedAir CalcPVTcollectors CalcQiceChargeMaxByChiller CalcQiceChargeMaxByITS CalcQiceDischageMax CalcRABFlowSetPoint CalcRackSystem CalcRadSysHXEffectTerm CalcRadTemp CalcRainCollector CalcReformEIRChillerModel CalcResearchSpecialPartLoad CalcReturnAirPath CalcRfFlrCoordinateTransformation CalcSandiaPV CalcSatVapPressFromTemp CalcSchedOffSysAvailMgr CalcSchedOnSysAvailMgr CalcSchedSysAvailMgr CalcScheduledDualSetPoint CalcScheduledSetPoint CalcScreenTransmittance CalcScriptF CalcSeriesPIU CalcSetpointTempTarget CalcSHRUserDefinedCurves CalcSimpleController CalcSimpleHeatingCoil CalcSimplePV CalcSingleSpeedEvapFluidCooler CalcSingleSpeedTower CalcSingZoneClSetPoint CalcSingZoneHtSetPoint CalcSingZoneMaxHumSetPoint CalcSingZoneMinHumSetPoint CalcSingZoneRhSetPoint CalcSkySolDiffuseReflFactors CalcSolarCollector CalcSolarFlux CalcSolidDesiccantDehumidifier CalcSourceFlux CalcSourceTempCoefficents CalcSparrowLeeward CalcSparrowWindward CalcSpecialDayTypes CalcStandAloneERV CalcStandardRatings CalcStaticProperties CalcSteamAirCoil CalcSteamBaseboard CalcSurfaceCentroid CalcSurfaceGroundHeatExchanger CalcSystemEnergyUse CalcSZOneStageCoolingSetPt CalcSZOneStageHeatingSetPt CalcTankTemp CalcTDDTransSolAniso CalcTDDTransSolHorizon CalcTDDTransSolIso CalcTempDistModel CalcTempIntegral CalcTESCoilChargeOnlyMode CalcTESCoilCoolingAndChargeMode CalcTESCoilCoolingAndDischargeMode CalcTESCoilCoolingOnlyMode CalcTESCoilDischargeOnlyMode CalcTESCoilOffMode CalcTESIceStorageTank CalcTESWaterStorageTank CalcThermalChimney CalcThermalComfortAdaptiveASH55 CalcThermalComfortAdaptiveCEN15251 CalcThermalComfortFanger CalcThermalComfortKSU CalcThermalComfortPierce CalcThermalComfortSimpleASH55 CalcTimeNeeded CalcTopFluxCoefficents CalcTopSurfTemp CalcTotalFLux CalcTotCapSHR CalcTotCapSHR_VSWSHP CalcTransAbsorProduct CalcTransRefAbsOfCover CalcTRNSYSPV CalcTrombeWallIntConvCoeff CalcTwoSpeedDXCoilIEERResidual CalcTwoSpeedDXCoilStandardRating CalcTwoSpeedEvapFluidCooler CalcTwoSpeedTower CalcUAIce CalcUCSDCV CalcUCSDDV CalcUCSDUE CalcUCSDUI CalculateAirChillerSets CalculateBasisLength CalculateCase CalculateCoil CalculateCompressors CalculateCondensers CalculateCTFs CalculateDailySolarCoeffs CalculateDayOfWeek CalculateEpsFromNTUandZ CalculateExponentialMatrix CalculateFuncResults CalculateGammas CalculateInverseMatrix CalculateMoodyFrictionFactor CalculateNTUfromEpsAndZ CalculatePollution CalculateSecondary CalculateSubcoolers CalculateSunDirectionCosines CalculateTransCompressors CalculateWalkIn CalculateWaterUseage CalculateWaterUseage CalculateWindowBeamProperties CalculateZoneMRT CalculateZoneVolume CalcUnitaryCoolingSystem CalcUnitaryHeatingSystem CalcUnitarySuppHeatingSystem CalcUnitarySuppSystemtoSP CalcUnitarySystemLoadResidual CalcUnitarySystemToLoad CalcUnitHeater CalcUnitHeaterComponents CalcUnitVentilator CalcUnitVentilatorComponents CalcUnmetPlantDemand CalcUpdateHeatRecovery CalcUpdateHeatRecovery CalcUserDefinedInsideHcModel CalcUserDefinedOutsideHcModel CalcVariableSpeedTower CalcVarSpeedCoilCooling CalcVarSpeedCoilHeating CalcVarSpeedHeatPump CalcVarSpeedHeatPump CalcVAVVS CalcVentilatedSlab CalcVentilatedSlabComps CalcVentilatedSlabRadComps CalcVentSlabHXEffectTerm CalcVerticalGroundHeatExchanger CalcViewFactorToShelf CalcVRF CalcVRFCondenser CalcVRFCoolingCoil CalcVSTowerApproach CalcWallCoordinateTransformation CalcWaltonStableHorizontalOrTilt CalcWaltonUnstableHorizontalOrTilt CalcWarmestSetPoint CalcWarmestSetPointTempFlow CalcWaterMainsTemp CalcWaterSource CalcWaterStorageTank CalcWaterThermalTankMixed CalcWaterThermalTankStratified CalcWaterThermalTankZoneGains CalcWaterToAirHeatpump CalcWatertoAirHPCooling CalcWatertoAirHPHeating CalcWaterToAirResidual CalcWatertoWaterHPCooling CalcWatertoWaterHPHeating CalcWaterUseZoneGains CalcWetIndirectEvapCooler CalcWindowACOutput CalcWindowBlindProperties CalcWindowHeatBalance CalcWindowProfileAngles CalcWindowScreenProperties CalcWindowStaticProperties CalcWindPressure CalcWindPressureCoeffs CalcWindTurbine CalcWinFrameAndDividerTemps CalcWinTransDifSolInitialDistribution CalcWrapperModel CalcZoneAirComfortSetpoints CalcZoneAirTempSetpoints CalcZoneComponentLoadSums CalcZoneDehumidifier CalcZoneEvaporativeCoolerUnit CalcZoneLeavingConditions CalcZoneMassBalance CalcZonePipesHeatGain CalcZoneSums CartesianPipeCellInformation_ctor CellType_IsFieldCell CFSHasControlledShade CFSNGlz CFSRefPointPosFactor CFSRefPointSolidAngle CFSShadeAndBeamInitialization CFSUFactor cGetCoilAirOutletNode cGetCoilSteamInletNode cGetCoilSteamOutletNode CharPreDefTableEntry CheckActuatorNode CheckAndAddAirNodeNumber CheckAndFixCFSLayer CheckAndReadCustomSprectrumData CheckAndReadFaults CheckAndSetConstructionProperties CheckBracketRoundOff CheckBranchForOASys CheckCachedIPErrors CheckCFSStates CheckCoilWaterInletNode CheckControllerListOrder CheckControllerLists CheckConvexity CheckCostEstimateInput CheckCreatedZoneItemName CheckCurveLimitsForIPLV CheckCurveLimitsForStandardRatings CheckDayScheduleValueMinMax CheckDXCoolingCoilInOASysExists CheckFDSurfaceTempLimits CheckFFSchedule CheckFluidPropertyName CheckForActualFileName CheckForBalancedFlow CheckForControllerWaterCoil CheckForGeometricTransform CheckForGeometricTransform CheckForMisMatchedEnvironmentSpecifications CheckForOutOfRangeTempResult CheckForOutOfRangeTemps CheckForRequestedReporting CheckForRunawayPlantTemps CheckForSensorAndSetpointNode CheckGasCoefs CheckHeatingCoilSchedule CheckHXAssistedCoolingCoilSchedule CheckIFAnyEMS CheckIFAnyIdealCondEntSetPoint CheckIfAnyPlant CheckIfNodeSetpointManagedByEMS CheckIncrementRoundOff CheckInternalConsistency CheckLightsReplaceableMinMaxForZone CheckLocationValidity CheckLoopExitNode CheckLowerUpperBracket CheckMarkedNodes CheckMaxActiveController CheckMaxConstraint CheckMicroCHPThermalBalance CheckMinActiveController CheckMinConstraint checkMinimumMonthlyCharge CheckMinMaxCurveBoundaries CheckMinMaxRange CheckModelBoundOutput_HumRat CheckModelBoundOutput_Temp CheckModelBounds CheckModelBoundsHumRatEq CheckModelBoundsRH_HumRatEq CheckModelBoundsRH_TempEq CheckModelBoundsTempEq CheckNodeConnections CheckNodeSetPoint CheckNonSingularity CheckOAControllerName CheckOutAirNodeNumber CheckPlantConvergence CheckPlantMixerSplitterConsistency CheckPlantOnAbort CheckPollutionMeterReporting CheckRefrigerationInput CheckReportVariable CheckRootFinderCandidate CheckRootFinderConvergence CheckScheduledSurfaceGains CheckScheduleValue CheckScheduleValueMinMax Checksetpoints CheckSimpleController CheckSlope CheckSteamCoilSchedule CheckSubSurfaceMiscellaneous CheckSysSizing CheckSystemBranchFlow CheckTDDsAndLightShelvesInDaylitZones CheckThisAirSystemForSizing CheckThisZoneForSizing CheckThreading CheckUniqueNodes CheckUnitarySysCoilInOASysExists CheckUsedConstructions CheckValidSimulationObjects CheckWarmupConvergence CheckWaterCoilSchedule CheckWeatherFileValidity CheckWindowShadingControlFrameDivider CheckZoneEquipmentList CheckZoneSizing CHKBKS CHKGSS CHKSBS CLIP CLIPPOLY CloseDFSFile CloseMiscOpenFiles CloseMoistureBalanceEMPD CloseOutOpenFiles CloseOutputFiles CloseOutputTabularFile CloseReportIllumMaps CloseSocket CloseWeatherFile CoilAreaFracIter CoilCompletelyDry CoilCompletelyWet CoilOutletStreamCondition CoilPartWetPartDry COMMAND_ARGUMENT_COUNT CompactObjectsCheck CompareTwoVectors ComplexFenestrationLuminances ComputeDelayedComponents ComputeDifSolExcZonesWIZWindows ComputeIntSolarAbsorpFactors ComputeIntSWAbsorpFactors ComputeIntThermalAbsorpFactors ComputeLifeCycleCostAndReport ComputeLoadComponentDecayCurve ComputeNominalUwithConvCoeffs ComputePresentValue ComputeTariff ComputeTaxAndDepreciation ComputeWinShadeAbsorpFactors CondOutTempResidual ConstructBasis ControlCBVAVOutput ControlCompOutput ControlCompOutput ControlCoolBeam ControlCoolingSystem ControlCycWindACOutput ControlDesiccantDehumidifier ControlDXHeatingSystem ControlDXSystem ControlFluidHeatExchanger ControlHeatingSystem ControlHumidifier ControlMSHPOutput ControlPTUnitOutput ControlPVTcollector ControlReformEIRChillerModel ControlSuppHeatSystem ControlUnitarySystemOutput ControlUnitarySystemtoLoad ControlUnitarySystemtoSP ControlVRF ControlVSEvapUnitToMeetLoad ControlVSHPOutput ControlVSHPOutput ConvectionFactor ConvertCasetoLower ConvertCasetoUpper ConvertIP ConvertIPdelta ConvertToElementTag ConvertToEscaped CoolBeamResidual CoolingCoil CoolWaterHumRatResidual CoolWaterTempResidual CoolWatertoAirHPHumRatResidual CoolWatertoAirHPTempResidual CorrectZoneAirTemp CorrectZoneContaminants CorrectZoneHumRat CostInfoOut CPCW CPHW CreateBoundaryList CreateBoundaryListCount CreateCategoryNativeVariables CreateCellArray CreateCurrentDateTimeString CreateDefaultComputation CreateEnergyReportStructure CreateFCfactorConstructions CreateHVACStepFullString CreateHVACTimeIntervalString CreateHVACTimeString CreateNewellAreaVector CreateNewellSurfaceNormalVector CreatePartitionCenterList CreatePartitionRegionList CreatePredefinedMonthlyReports CreateRegionList CreateRegionListCount CreateShadedWindowConstruction CreateSQLiteConstructionsTable CreateSQLiteConstructionsTable CreateSQLiteDatabase CreateSQLiteDatabase CreateSQLiteDaylightMap CreateSQLiteDaylightMap CreateSQLiteDaylightMapTitle CreateSQLiteDaylightMapTitle CreateSQLiteEnvironmentPeriodRecord CreateSQLiteEnvironmentPeriodRecord CreateSQLiteErrorRecord CreateSQLiteErrorRecord CreateSQLiteInfiltrationTable CreateSQLiteInfiltrationTable CreateSQLiteMaterialsTable CreateSQLiteMaterialsTable CreateSQLiteMeterDictionaryRecord CreateSQLiteMeterDictionaryRecord CreateSQLiteMeterRecord CreateSQLiteMeterRecord CreateSQLiteNominalBaseboardHeatTable CreateSQLiteNominalBaseboardHeatTable CreateSQLiteNominalElectricEquipmentTable CreateSQLiteNominalElectricEquipmentTable CreateSQLiteNominalGasEquipmentTable CreateSQLiteNominalGasEquipmentTable CreateSQLiteNominalHotWaterEquipmentTable CreateSQLiteNominalHotWaterEquipmentTable CreateSQLiteNominalLightingTable CreateSQLiteNominalLightingTable CreateSQLiteNominalOtherEquipmentTable CreateSQLiteNominalOtherEquipmentTable CreateSQLiteNominalPeopleTable CreateSQLiteNominalPeopleTable CreateSQLiteNominalSteamEquipmentTable CreateSQLiteNominalSteamEquipmentTable CreateSQLiteReportVariableDataRecord CreateSQLiteReportVariableDataRecord CreateSQLiteReportVariableDictionaryRecord CreateSQLiteReportVariableDictionaryRecord CreateSQLiteRoomAirModelTable CreateSQLiteRoomAirModelTable CreateSQLiteSchedulesTable CreateSQLiteSimulationsRecord CreateSQLiteSimulationsRecord CreateSQLiteStringTableRecord CreateSQLiteSurfacesTable CreateSQLiteSurfacesTable CreateSQLiteTabularDataRecords CreateSQLiteTabularDataRecords CreateSQLiteTimeIndexRecord CreateSQLiteTimeIndexRecord CreateSQLiteVentilationTable CreateSQLiteVentilationTable CreateSQLiteZoneGroupTable CreateSQLiteZoneGroupTable CreateSQLiteZoneListTable CreateSQLiteZoneListTable CreateSQLiteZoneTable CreateSQLiteZoneTable CreateStormWindowConstructions CreateSysTimeIntervalString CreateTCConstructions CreateTimeIntervalString CreateTimeString CreatExtBooundCondName CreateZoneExtendedOutput CreateZoneExtendedOutput CrossProduct CrossProduct cSurfaceClass CTRANS CurveValue DateToString DateToStringWithMonth DaylghtAltAndAzimuth DayltgAveInteriorReflectance DayltgClosestObstruction DayltgCrossProduct DayltgCurrentExtHorizIllum DayltgDirectIllumComplexFenestration DayltgDirectSunDiskComplexFenestration DayltgElecLightingControl DayltgExtHorizIllum DayltgGlare DayltgGlarePositionFactor DayltgGlareWithIntWins DayltgHitBetWinObstruction DayltgHitInteriorObstruction DayltgHitObstruction DayltgInteriorIllum DayltgInteriorMapIllum DayltgInteriorTDDIllum DayltgInterReflectedIllum DayltgInterReflectedIllumComplexFenestration DayltgInterReflIllFrIntWins DayltgLuminousEfficacy DayltgPierceSurface DayltgSetupAdjZoneListsAndPointers DayltgSkyLuminance DayltgSurfaceLumFromSun dCheckScheduleValueMinMax1 dCheckScheduleValueMinMax2 DeallocateLoadComponentArrays DebugRootFinder DecodeHHMMField DecodeMonDayHrMin DeflectionTemperatures DeflectionWidths DegradF DElightDaylightCoefficients DElightDaylightCoefficients DElightElecLtgCtrl DElightElecLtgCtrl DElightFreeMemory DElightFreeMemory DElightInputGenerator DElightInputGenerator DElightOutputGenerator DElightOutputGenerator DensityCFSFillGas Depth DERIV DetailsForSurfaces DetectOscillatingZoneTemp DetermineAzimuthAndTilt DetermineBranchFlowRequest DetermineBuildingFloorArea DetermineDateTokens DetermineFrequency DetermineIndexGroupFromMeterGroup DetermineIndexGroupKeyFromMeterName DetermineMaxBackSurfaces DetermineMeterIPUnits DetermineMinuteForReporting DeterminePolygonOverlap DetermineShadowingCombinations DetermineSunUpDown DevelopMesh DiffuseAverage DiffuseAverageProfAngGnd DiffuseAverageProfAngSky DisplayMaterialRoughness DisplayNumberandString DisplaySimDaysProgress DisplayString distance DistributeBBElecRadGains DistributeBBRadGains DistributeBBSteamRadGains DistributeHTRadGains DistributePlantLoad DistributePressureOnBranch DistributeTDDAbsorbedSolar DistributeUserDefinedPlantLoad DL_RES_r2 DLAG DOE2DXCoilHumRatResidual DOE2DXCoilHumRatResidual DOE2DXCoilResidual DOE2DXCoilResidual DOE2DXCoilResidual DoEndOfIterationOperations DomainRectangle_Contains DOMakeUPPERCase DoOneTimeInitializations DOSameString DoShadeControl DoStartOfTimeStepInitializations DownInterpolate4HistoryValues DumpAirLoopStatistics DumpCurrentLineBuffer DUMPVD DUMPVR DXCoilCyclingHumRatResidual DXCoilCyclingHumRatResidual DXCoilCyclingResidual DXCoilCyclingResidual DXCoilVarSpeedHumRatResidual DXCoilVarSpeedHumRatResidual DXCoilVarSpeedResidual DXCoilVarSpeedResidual DXFOut DXFOutLines DXFOutWireFrame DXHeatingCoilResidual DXHeatingCoilResidual DXHeatingCoilResidual DynamicClothingModel DynamicExtConvSurfaceClassification DynamicIntConvSurfaceClassification EchoOutActuatorKeyChoices EchoOutInternalVariableChoices EffectiveEPSLB EffectiveEPSLF EIRChillerHeatRecovery EN673ISO10292 EncodeMonDayHrMin EndEnergyPlus EndUniqueNodeCheck EnthalpyResidual epElapsedTime epGetTimeUsed epGetTimeUsedperCall epStartTime epStopTime epSummaryTimes eptime EQLWindowInsideEffectiveEmiss EQLWindowOutsideEffectiveEmiss EQLWindowSurfaceHeatBalance EquationsSolver ERF EstimateHEXSurfaceArea EvalInsideMovableInsulation EvalOutsideMovableInsulation EvaluateAdiabaticSurfaceTemperature EvaluateBasementCellTemperature EvaluateCellNeighborDirections evaluateChargeBlock evaluateChargeSimple EvaluateExpression EvaluateExtHcModels EvaluateFarfieldBoundaryTemperature EvaluateFarfieldCharacteristics EvaluateFieldCellTemperature EvaluateGroundSurfaceTemperature EvaluateIntHcModels EvaluateLoopSetPointLoad EvaluateNeighborCharacteristics evaluateQualify evaluateRatchet EvaluateSoilRhoCp EvaluateStack EvolveParaUCSDCV ExitCalcController ExpandComplexState ExpressAsCashFlows ExtendObjectDefinition ExteriorBCEqns ExternalInterfaceExchangeVariables ExternalInterfaceInitializeErlVariable ExternalInterfaceSetErlVariable ExternalInterfaceSetSchedule ExtOrIntShadeNaturalFlow Fabric_EstimateDiffuseProps FACSKY FalsePositionMethod FEQX FI FigureACAncillaries FigureAirEnthalpy FigureAirHeatCap FigureAuxilHeatGasHeatCap FigureBeamSolDiffuseReflFactors FigureBeamSolSpecularReflFactors FigureConstGradPattern FigureDayltgCoeffsAtPointsForSunPosition FigureDayltgCoeffsAtPointsForWindowElements FigureDayltgCoeffsAtPointsSetupForWindow FigureElectricalStorageZoneGains FigureFuelCellZoneGains FigureFuelEnthalpy FigureFuelHeatCap FigureGaseousWaterEnthalpy FigureHeightPattern FigureHXleavingGasHeatCap FigureInverterZoneGains FigureLHVofFuel FigureLiquidWaterEnthalpy FigureLiquidWaterHeatCap FigureMapPointDayltgFactorsToAddIllums FigureMicroCHPZoneGains FigureNDheightInZone FigurePowerConditioningLosses FigureProductGasesEnthalpy FigureProductGasHeatCap FigureRefPointDayltgFactorsToAddIllums FigureRefrigerationZoneGains FigureSolarBeamAtTimestep FigureSunCosines FigureSurfMapPattern FigureTDDZoneGains FigureTransformerZoneGains FigureTransientConstraints FigureTwoGradInterpPattern FILJAC FillBasisElement FillDefaultsSWP FillRemainingPredefinedEntries FillWeatherPredefinedEntries film filmg filmi filmPillar FILSKY FinalizeCFS FinalizeCFSLAYER FinalRateCoils FindAirLoopBranchConnection FindAirPlantCondenserLoopFromBranchList FindAllNumbersinList FindArrayIndex FindCompSPInput FindCompSPLoad FindCondenserLoopBranchConnection FindControlledZoneIndexFromSystemNodeNumberForZone FindDeltaTempRangeInput FindDemandSideMatch FindEMSVariable FindFirstLastPtr FindFirstRecord FindGlycol FindHXDemandSideLoopFlow FindInBasis FindItem FindIteminList FindIteminSortedList FindItemInVariableList FindLoopSideInCallingOrder FindNextRecord FindNonSpace FindNumberinList FindOAMixerMatchForOASystem FindPlantLoopBranchConnection FindRangeBasedOrUncontrolledInput FindRangeVariable FindRefrigerant FindRootSimpleController FindStratifiedTankSensedTemp FindTariffIndex FindTDDPipe FindUnitNumber FinishDebugOutputFiles FixViewFactors FluidCellInformation_ctor FM_BEAM FM_DIFF FM_F FNU forcedventilation FourPipeInductionUnitHasMixer FourPipeIUCoolingResidual FourPipeIUHeatingResidual FRA FrostControl FrostControlSetPointLimit FrostControlSetPointLimit FuelCellProductGasEnthResidual FUN FuncDetermineCoolantWaterExitTemp FuncDetermineCWMdotForInternalFlowControl FuncDetermineEngineTemp FV GasElecHeatingCoilResidual GASSES90 GassesLow GatherBEPSResultsForTimestep GatherBinResultsForTimestep GatherComponentLoadsHVAC GatherComponentLoadsIntGain GatherComponentLoadsSurfAbsFact GatherComponentLoadsSurface GatherForEconomics GatherForPredefinedReport GatherHeatGainReport GatherMonthlyResultsForTimestep GatherPeakDemandForTimestep GatherSourceEnergyEndUseResultsForTimestep GaussElimination generate_ears GenerateDElightDaylightCoefficients GenerateDElightDaylightCoefficients GeneratorPowerOutput GenericCrack GenOutputVariablesAuditReport Get2DMatrix Get2DMatrixDimensions GET_COMMAND GET_COMMAND_ARGUMENT Get_Environment_Variable GetActualDXCoilIndex GetAirBranchIndex GetAirFlowFlag GetAirflowNetworkInput GetAirHeatBalanceInput GetAirLoopAvailabilityManager GetAirModelDatas GetAirNodeData GetAirPathData GetAngleFactorList GetATMixer GetATMixerOutNode GetATMixerPriNode GetATMixers GetATMixerSecNode GetAttShdSurfaceData GetAverageTempByType GetBaseboardInput GetBaseboardInput GetBasementFloorHeatFlux GetBasementWallHeatFlux GetBLASTAbsorberInput GetBoilerInput GetBoilerInput GetBranchData GetBranchFanTypeName GetBranchFlow GetBranchInput GetBranchList GetBranchListInput GetBuildingData GetCBVAV GetCellWidths GetCellWidthsCount GetChildrenData GetChillerheaterInput GetCoilAirFlowRate GetCoilAirFlowRateVariableSpeed GetCoilAirInletNode GetCoilAirOutletNode GetCoilAvailScheduleIndex GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacityByIndexType GetCoilCapacityVariableSpeed GetCoilCondenserInletNode GetCoilControlNodeNum GetCoilGroupTypeNum GetCoilIndex GetCoilIndex GetCoilIndex GetCoilIndexVariableSpeed GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNodeVariableSpeed GetCoilMaxSteamFlowRate GetCoilMaxWaterFlowRate GetCoilMaxWaterFlowRate GetCoilMaxWaterFlowRate GetCoilObjectTypeNum GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNodeVariableSpeed GetCoilSteamInletNode GetCoilSteamOutletNode GetCoilTypeNum GetCoilWaterInletNode GetCoilWaterInletNode GetCoilWaterOutletNode GetColumnUsingTabs GetComfortSetpoints GetComponentData GetCondFDInput GetConductivityGlycol GetConnectorList GetConnectorListInput GetConstCOPChillerInput GetConstructData GetControlledZoneIndex GetControllerActuatorNodeNum GetControllerInput GetCoolBeams GetCoolingCoilTypeNameAndIndex GetCooltower GetCostEstimateInput GetCrossVentData GetCTGeneratorInput GetCTGeneratorResults GetCurrentHVACTime GetCurrentMeterValue GetCurrentScheduleValue GetCurveCheck GetCurveIndex GetCurveInput GetCurveMinMaxValues GetCurveName GetCurveObjectTypeNum GetCurveType GetCustomMeterInput GetDaylightingParametersDetaild GetDaylightingParametersInput GetDayScheduleIndex GetDemandManagerInput GetDemandManagerListInput GetDensityGlycol GetDesiccantDehumidifierInput GetDesignDayData GetDesignLightingLevelForZone GetDetShdSurfaceData GetDirectAirInput GetDisplacementVentData GetDSTData GetDualDuctInput GetDualDuctOutdoorAirRecircUse GetDuctInput GetDXCoilAirFlow GetDXCoilAvailSchPtr GetDXCoilBypassedFlowFrac GetDXCoilCapFTCurveIndex GetDXCoilIndex GetDXCoilNumberOfSpeeds GetDXCoils GetDXCoolingSystemInput GetDXHeatPumpSystemInput GetEarthTube GetElecReformEIRChillerInput GetElectricBaseboardInput GetElectricChillerInput GetElectricEIRChillerInput GetEMSInput GetEngineDrivenChillerInput GetEnvironmentalImpactFactorInfo GetEvapFluidCoolerInput GetEvapInput GetExhaustAbsorberInput GetExhaustAirInletNode GetExteriorEnergyUseInput GetExtVentedCavityIndex GetExtVentedCavityIndex GetExtVentedCavityTsColl GetExtVentedCavityTsColl GetFanAvailSchPtr GetFanCoilIndex GetFanCoilInletAirNode GetFanCoilMixedAirNode GetFanCoilOutAirNode GetFanCoilReturnAirNode GetFanCoilUnits GetFanCoilZoneInletAirNode GetFanDesignVolumeFlowRate GetFanIndex GetFanIndexForTwoSpeedCoil GetFanInletNode GetFanInput GetFanOutletNode GetFanPower GetFanSpeedRatioCurveIndex GetFanType GetFanVolFlow GetFarfieldTemp GetFirstBranchInletNodeName GetFluidCoolerInput GetFluidDensityTemperatureLimits GetFluidHeatExchangerInput GetFluidPropertiesData GetFluidSpecificHeatTemperatureLimits GetFrameAndDividerData GetFuelCellGeneratorInput GetFuelCellGeneratorResults GetFuelFactorInfo GetFurnaceInput GetGasAbsorberInput GetGeneratorFuelSupplyInput GetGeometryParameters GetGlycolNameByIndex GetGroundheatExchangerInput GetGroundReflectances GetGroundTemps GetGshpInput GetGshpInput GetGTChillerInput GetHeatBalanceInput GetHeatBalHAMTInput GetHeatExchangerObjectTypeNum GetHeatingCoilIndex GetHeatingCoilInput GetHeatingCoilNumberOfStages GetHeatingCoilPLFCurveIndex GetHeatingCoilTypeNum GetHeatReclaimSourceIndex GetHeatRecoveryInput GetHighTempRadiantSystem GetHPCoolingCoilIndex GetHTSubSurfaceData GetHTSurfaceData GetHTSurfExtVentedCavityData GetHumidifierInput GetHVACSingleDuctSysIndex GetHWBaseboardInput GetHXAssistedCoolingCoilInput GetHXCoilAirFlowRate GetHXCoilType GetHXCoilTypeAndName GetHXDXCoilIndex GetHXDXCoilName GetHybridVentilationControlStatus GetHybridVentilationInputs GetICEGeneratorResults GetICEngineGeneratorInput GetIceStorageInput GetIDFRecordsStats GetIndirectAbsorberInput GetIndUnits GetInputEconomicsChargeBlock GetInputEconomicsChargeSimple GetInputEconomicsComputation GetInputEconomicsCurrencyType GetInputEconomicsQualify GetInputEconomicsRatchet GetInputEconomicsTariff GetInputEconomicsVariable GetInputForLifeCycleCost GetInputFuelAndPollutionFactors GetInputLifeCycleCostNonrecurringCost GetInputLifeCycleCostParameters GetInputLifeCycleCostRecurringCosts GetInputLifeCycleCostUseAdjustment GetInputLifeCycleCostUsePriceEscalation GetInputTabularMonthly GetInputTabularPredefined GetInputTabularStyle GetInputTabularTimeBins GetInputViewFactors GetInputViewFactorsbyName GetInputZoneEvaporativeCoolerUnit GetInstantMeterValue GetInternalBranchData GetInternalHeatGainsInput GetInternalVariableValue GetInternalVariableValue GetInternalVariableValueExternalInterface GetInternalVariableValueExternalInterface GetInterpolatedSatProp GetInterpValue GetIntMassSurfaceData GetLastBranchOutletNodeName GetLastWord GetLightWellData GetListOfObjectsInIDD GetListofSectionsinInput GetLocationInfo GetLoopMixer GetLoopSidePumpIndex GetLoopSplitter GetLowTempRadiantSystem GetMaterialData GetMatrixInput getMaxAndSum GetMeteredVariables GetMeterIndex GetMeterResourceType GetMicroCHPGeneratorInput GetMicroCHPGeneratorResults GetMinOATCompressor GetMixerInput GetMixerInput GetMoistureBalanceEMPDInput GetMonthlyCostForResource GetMovableInsulationData GetMSHeatPumpInput GetMTGeneratorExhaustNode GetMTGeneratorInput GetMTGeneratorResults GetMundtData GetNewUnitNumber GetNextEnvironment GetNodeConnectionType GetNodeList GetNodeListsInput GetNodeNums GetNTUforCrossFlowBothUnmixed GetNumberOfSchedules GetNumberOfSurfaceLists GetNumberOfSurfListVentSlab GetNumChildren GetNumMeteredVariables GetNumOAControllers GetNumOAMixers GetNumOASystems GetNumObjectsFound GetNumObjectsInIDD GetNumRangeCheckErrorsFound GetNumSectionsFound GetNumSectionsinInput GetNumSegmentsForHorizontalTrenches GetNumSplitterMixerInConntrList GetOACompListNumber GetOACompName GetOACompType GetOACompTypeNum GetOAControllerInputs GetOAMixerIndex GetOAMixerInletNodeNumber GetOAMixerInputs GetOAMixerMixedNodeNumber GetOAMixerNodeNumbers GetOAMixerReliefNodeNumber GetOAMixerReturnNodeNumber GetOARequirements GetOASysControllerListIndex GetOASysNumCoolingCoils GetOASysNumHeatingCoils GetOASysNumSimpControllers GetOASystemNumber GetObjectDefInIDD GetObjectDefMaxArgs GetObjectItem GetObjectItemfromFile GetObjectItemNum GetOnlySingleNode GetOperationSchemeInput GetOSCData GetOSCMData GetOutAirNodesInput GetOutdoorAirUnitInputs GetOutdoorAirUnitOutAirNode GetOutdoorAirUnitReturnAirNode GetOutdoorAirUnitZoneInletNode GetOutsideAirSysInputs GetOutsideEnergySourcesInput GetParentData GetPipeInput GetPipesHeatTransfer GetPipingSystemsInput GetPIUs GetPlantAvailabilityManager GetPlantInput GetPlantLoopData GetPlantOperationInput GetPlantProfileInput GetPlantSizingInput GetPlantValvesInput GetPollutionFactorInput GetPondGroundHeatExchanger GetPowerManagerInput GetPressureCurveTypeAndIndex GetPressureSystemInput GetPreviousHVACTime GetProjectControlData GetProjectData GetPTUnit GetPTUnitMixedAirNode GetPTUnitOutAirNode GetPTUnitReturnAirNode GetPTUnitZoneInletAirNode GetPumpInput GetPurchasedAir GetPurchasedAirMixedAirHumRat GetPurchasedAirMixedAirTemp GetPurchasedAirOutAirMassFlow GetPurchasedAirReturnAirNode GetPurchasedAirZoneInletAirNode GetPVGeneratorResults GetPVInput GetPVTcollectorsInput GetPVTThermalPowerProduction GetQualityRefrig GetRecordLocations GetRectDetShdSurfaceData GetRectSubSurfaces GetRectSurfaces GetRefrigeratedRackIndex GetRefrigerationInput GetReportVariableInput GetRequiredMassFlowRate GetResidCrossFlowBothUnmixed GetResourceTypeChar GetReturnAirNodeForZone GetReturnAirPathInput GetRoomAirModelParameters GetRunPeriodData GetRunPeriodDesignData GetRuntimeLanguageUserInput GetSatDensityRefrig GetSatEnthalpyRefrig GetSatPressureRefrig GetSatSpecificHeatRefrig GetSatTemperatureRefrig GetScheduledSurfaceGains GetScheduleIndex GetScheduleMaxValue GetScheduleMinValue GetScheduleName GetScheduleType GetScheduleValuesForDay GetSecondaryInletNode GetSecondaryOutletNode GetSetPointManagerInputs GetShadingSurfReflectanceData GetShadowingInput GetShelfInput GetSimpleAirModelInputs GetSimpleShdSurfaceData GetSimpleWatertoAirHPInput GetSingleDayScheduleValues GetSiteAtmosphereData GetSizingParams GetSnowGroundRefModifiers GetSolarCollectorInput GetSpecialDayPeriodData GetSpecificHeatGlycol getSpecificUnitDivider getSpecificUnitIndex getSpecificUnitMultiplier GetSplitterInput GetSplitterInput GetSplitterNodeNumbers GetSplitterOutletNumber GetStandAloneERV GetStandAloneERVNodes GetStandAloneERVOutAirNode GetStandAloneERVReturnAirNode GetStandAloneERVZoneInletAirNode GetStandardMeterResourceType GetSteamBaseboardInput GetSteamCoilAvailScheduleIndex GetSteamCoilControlNodeNum GetSteamCoilIndex GetSteamCoilInput GetSTM GetStormWindowData GetSupHeatDensityRefrig GetSupHeatEnthalpyRefrig GetSupHeatPressureRefrig GetSupplyAirFlowRate GetSupplyAirFlowRate GetSupplyAirInletNode GetSupplyInletNode GetSupplyOutletNode GetSurfaceCountForOSCM GetSurfaceData GetSurfaceGroundHeatExchanger GetSurfaceHeatTransferAlgorithmOverrides GetSurfaceIndecesForOSCM GetSurfaceListsInputs GetSurfHBDataForMundtModel GetSurfHBDataForTempDistModel GetSysAvailManagerInputs GetSysAvailManagerListInputs GetSysInput GetSystemNodeNumberForZone GetSystemSizingInput GetTDDInput GetTESCoilIndex GetTESCoilInput GetThermalChimney GetTowerInput GetTranspiredCollectorIndex GetTranspiredCollectorInput GetTypeOfCoil GetUFADZoneData GetUnitarySystemDXCoolingCoilIndex GetUnitarySystemInput GetUnitarySystemOAHeatCoolCoil GetUnitConversion GetUnitHeaterInput GetUnitsString GetUnitSubString GetUnitVentilatorInput GetUnitVentilatorMixedAirNode GetUnitVentilatorOutAirNode GetUnitVentilatorReturnAirNode GetUnitVentilatorZoneInletAirNode GetUserConvectionCoefficients GetUserDefinedComponents GetUserDefinedOpSchemeInput GetUserDefinedPatternData GetUTSCTsColl GetVariableKeyCountandType GetVariableKeyCountandType GetVariableKeys GetVariableKeys GetVariableTypeAndIndex GetVariableUnitsString GetVarSpeedCoilInput GetVentilatedSlabInput GetVertices GetViscosityGlycol GetVRFInput GetVSCoilCondenserInletNode GetVSCoilMinOATCompressor GetVSCoilNumOfSpeeds GetWaterCoilAvailScheduleIndex GetWaterCoilCapacity GetWaterCoilIndex GetWaterCoilInput GetWaterMainsTemperatures GetWaterManagerInput GetWaterSource GetWaterThermalTankInput GetWatertoAirHPInput GetWatertoWaterHPInput GetWaterUseInput GetWeatherProperties GetWeatherStation GetWindowAC GetWindowACMixedAirNode GetWindowACOutAirNode GetWindowACReturnAirNode GetWindowACZoneInletAirNode GetWindowGapAirflowControlData GetWindowGlassSpectralData GetWindowShadingControlData GetWindTurbineInput GetWrapperInput GetWTGeneratorResults GetZoneAirDistribution GetZoneAirLoopEquipment GetZoneAirSetpoints GetZoneAndZoneListNames GetZoneContaminanInputs GetZoneContaminanSetpoints GetZoneData GetZoneDehumidifierInput GetZoneDehumidifierNodeNumber GetZoneEqAvailabilityManager GetZoneEquipment GetZoneEquipmentData GetZoneEquipmentData1 GetZoneInfilAirChangeRate GetZoneLoads GetZonePlenumInput GetZoneSizingInput GLtoAMB GoAhead guess HasFractionalScheduleValue hatter HCInWindowStandardRatings HConvGap HcUCSDCV HcUCSDDV HcUCSDUF HeatingCoilVarSpeedCycResidual HeatingCoilVarSpeedResidual HeatPumpRunFrac HeatPumpRunFrac HeatPumpRunFrac HeatWatertoAirHPTempResidual Height HEMINT HIC_ASHRAE HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterHeatingCoilResidual HRadPar HTRANS HTRANS0 HTRANS1 HWBaseboardUAResidual HXAssistDXCoilResidual HXAssistedCoolCoilHRResidual HXAssistedCoolCoilHRResidual HXAssistedCoolCoilTempResidual HXAssistedCoolCoilTempResidual HXDemandSideLoopFlowResidual HybridVentilationControl IAM iCheckScheduleValue ICSCollectorAnalyticalSoluton iGetCoilAirOutletNode iGetCoilSteamInletNode iGetCoilSteamOutletNode INCLOS incrementEconVar IncrementInstMeterCache incrementSteps incrementTableEntry InitAirflowNetwork InitAirflowNetworkData InitAirHeatBalance InitAirLoops InitAirLoopSplitter InitAirMixer InitAirTerminalUserDefined InitAirZoneReturnPlenum InitAirZoneSupplyPlenum InitATMixer InitBaseboard InitBaseboard InitBLASTAbsorberModel InitBoiler InitBoiler InitBoreholeHXSimVars InitBSDFWindows InitCBVAV InitCoilUserDefined InitComplexWindows InitComponentNodes InitConductionTransferFunctions InitConnections InitConstCOPChiller InitController InitCoolBeam InitCTGenerators InitCurveReporting InitDaylightingDevices InitDemandManagers InitDesiccantDehumidifier InitDetailedIceStorage InitDirectAir InitDualDuct InitDuct InitDXCoil InitDXCoolingSystem InitDXHeatPumpSystem InitElecReformEIRChiller InitElectricBaseboard InitElectricChiller InitElectricEIRChiller InitEMS InitEMSControlledConstructions InitEMSControlledSurfaceProperties InitEnergyReports InitEngineDrivenChiller InitEquivalentLayerWindowCalculations InitEvapCooler InitEvapFluidCooler InitExhaustAbsorber InitExteriorConvectionCoeff InitFan InitFanCoilUnits InitFluidCooler InitFluidHeatExchanger InitFuelCellGenerators InitFurnace InitGasAbsorber InitGlassOpticalCalculations InitGshp InitGshp InitGTChiller InitHeatBalance InitHeatBalFiniteDiff InitHeatBalHAMT InitHeatingCoil InitHeatRecovery InitHighTempRadiantSystem InitHumidifier InitHWBaseboard InitHXAssistedCoolingCoil InitHybridVentSysAvailMgr InitialInitHeatBalFiniteDiff InitializeCFSDaylighting InitializeCFSStateData InitializeComponentSizingTable InitializeConstructionsTables InitializeDaylightMapTables InitializeEnvironmentPeriodsTable InitializeErrorsTable InitializeGlycolTempLimits InitializeHeatTransferPipes InitializeIndexes InitializeIndexes InitializeLoops InitializeMaterialsTable InitializeMeters initializeMonetaryUnit InitializeNominalBaseboardHeatTable InitializeNominalElectricEquipmentTable InitializeNominalGasEquipmentTable InitializeNominalHotWaterEquipmentTable InitializeNominalInfiltrationTable InitializeNominalLightingTable InitializeNominalOtherEquipmentTable InitializeNominalPeopleTable InitializeNominalSteamEquipmentTable InitializeNominalVentilationTable InitializeOperatingMode InitializeOutput InitializePipes InitializePredefinedMonthlyTitles InitializePsychRoutines InitializePumps InitializeRefrigerantLimits InitializeReportMeterDataDictionaryTable InitializeReportMeterDataTables InitializeReportVariableDataDictionaryTable InitializeReportVariableDataTables InitializeRoomAirModelTable InitializeRootFinder InitializeRuntimeLanguage InitializeSchedulesTable InitializeSimulationsTable InitializeSQLiteTables InitializeSurfacesTable InitializeSystemSizingTable InitializeTabularDataTable InitializeTabularDataTable InitializeTabularDataView InitializeTabularDataView InitializeTabularMonthly InitializeTimeIndicesTable InitializeViews InitializeWeather InitializeZoneGroupTable InitializeZoneInfoTable InitializeZoneListTable InitializeZoneSizingTable InitICEngineGenerators InitIndirectAbsorpChiller InitIndUnit InitInteriorConvectionCoeffs InitInteriorRadExchange InitInternalHeatGains InitIntSolarDistribution InitLoadBasedControl InitLoadDistribution InitLowTempRadiantSystem InitMicroCHPNoNormalizeGenerators InitMoistureBalanceEMPD InitMSHeatPump InitMTGenerators InitMundtModel InitOAController InitOAMixer InitOneTimePlantSizingInfo InitOutAirNodes InitOutdoorAirUnit InitOutsideAirSys InitPipesHeatTransfer InitPipingSystems InitPIU InitPlantProfile InitPlantUserComponent InitPlantValves InitPollutionMeterReporting InitPondGroundHeatExchanger InitPressureDrop InitPTUnit InitPurchasedAir InitPVTcollectors InitRefrigeration InitRefrigerationPlantConnections InitReturnAirPath InitSecretObjects InitSetPointManagers InitSimpleIceStorage InitSimpleMixingConvectiveHeatGains InitSimpleWatertoAirHP InitSimVars InitSimVars InitSimVars InitSimVars InitSolarCalculations InitSolarCollector InitSolarHeatGains InitSolReflRecSurf InitStandAloneERV InitSteamBaseboard InitSteamCoil InitSurfaceGroundHeatExchanger InitSurfaceHeatBalance InitSys InitSysAvailManagers InitSystemOutputRequired InitTempDistModel InitTESCoil InitThermalAndFluxHistories InitThermalComfort InitTower InitTranspiredCollector InitTRNSYSPV InitUCSDCV InitUCSDDV InitUCSDUF InitUniqueNodeCheck InitUnitarySystems InitUnitHeater InitUnitVentilator InitVarSpeedCoil InitVentilatedSlab InitVRF InitWaterCoil InitWaterSource InitWaterThermalTank InitWatertoAirHP InitWatertoWaterHP InitWindowAC InitWindTurbine InitWrapper InitZoneAirLoopEquipment InitZoneAirSetpoints InitZoneAirUserDefined InitZoneContSetpoints InitZoneDehumidifier InitZoneEquipment InitZoneEvaporativeCoolerUnit InPolygon InsertCurrencySymbol int_times_vector INTCPT Integer_IsInRange IntegerIsWithinTwoValues IntegerToString InterConnectTwoPlantLoopSides InteriorBCEqns InteriorNodeEqns InternalRangeCheck InternalSetupTankDemandComponent InternalSetupTankSupplyComponent interp INTERP InterpBlind InterpDefValuesForGlycolConc Interpolate Interpolate_Lagrange InterpolateBetweenFourValues InterpolateBetweenTwoValues InterpolatePipeTransBeam InterpProfAng InterpProfSlatAng InterpretWeatherDataLine InterpSlatAng InterpSw InterpValuesForGlycolConc IntInterfaceNodeEqns IntPreDefTableEntry IntToStr Invert3By3Matrix InvertMatrix InvJulianDay IPTrimSigDigits iRoundSigDigits IS_BEAM IS_DIFF IS_DSRATIO IS_F IS_LWP IS_OPENNESS IS_SWP isCompLoadRepReq IsControlledShade IsConverged_CurrentToPrevIteration IsConverged_PipeCurrentToPrevIteration IsCurveInputTypeValid IsCurveOutputTypeValid isExternalInterfaceErlVariable IsGlazeLayerX IsGZSLayer isInQuadrilateral IsInRange isInTriangle IsLeapYear IsNodeOnSetPtManager IsParentObject IsParentObjectCompSet IsShadingLayer IssueSevereAlphaInputFieldError IssueSevereInputFieldError IssueSevereRealInputFieldError IsValidConnectionType IsVBLayer isWithinRange ITERATE IterateRootFinder iTrimSigDigits JGDate JulianDay LClimb LDSumMax LDSumMean LEEDtariffReporting LimitCoilCapacity LimitController LimitTUCapacity LinesOut linint LoadEquipList LoadInterface LogicalToInteger LogicalToInteger LogPlantConvergencePoints lookupOperator LookUpScheduleValue LookUpSeason LookupSItoIP lubksb LUBKSB ludcmp LUDCMP LUdecomposition LUsolution MakeAnchorName MakeHVACTimeIntervalString MakeMirrorSurface MakeRectangularVertices MakeRelativeRectangularVertices MakeTransition MakeUPPERCase ManageAirflowNetworkBalance ManageAirHeatBalance ManageAirLoops ManageAirModel ManageBranchInput ManageControllers ManageCoolTower ManageDemand ManageEarthTube ManageElectCenterStorageInteractions ManageElectricLoadCenters ManageElectStorInteractions ManageEMS ManageExteriorEnergyUse ManageGeneratorControlState ManageGeneratorFuelFlow ManageHeatBalance ManageHeatBalFiniteDiff ManageHeatBalHAMT ManageHVAC ManageHybridVentilation ManageInsideAdaptiveConvectionAlgo ManageInternalHeatGains ManageInverter ManageMundtModel ManageNonZoneEquipment ManageOutsideAdaptiveConvectionAlgo ManageOutsideAirSystem ManagePlantLoadDistribution ManagePlantLoops ManageRefrigeratedCaseRacks ManageSetPoints ManageSimulation ManageSingleCommonPipe ManageSizing ManageSurfaceHeatBalance ManageSystemAvailability ManageThermalChimney ManageThermalComfort ManageTransformers ManageTwoWayCommonPipe ManageUCSDCVModel ManageUCSDDVModel ManageUCSDUFModels ManageUserDefinedPatterns ManageWater ManageWaterInits ManageWeather ManageZoneAirLoopEquipment ManageZoneAirUpdates ManageZoneContaminanUpdates ManageZoneEquipment MapExtConvClassificationToHcModels MapIntConvClassificationToHcModels MarkNode MatchAndSetColorTextString MatchPlantSys MatrixIndex matrixQBalance MeshPartition_CompareByDimension MeshPartition_SelectionSort MeshPartitionArray_Contains MinePlantStructForInfo MixedAirControlTempResidual ModifyWindow Modulus MonthToMonthNumber MovingAvg MRXINV MSHPCyclingResidual MSHPHeatRecovery MSHPVarSpeedResidual MultiModeDXCoilHumRatResidual MultiModeDXCoilHumRatResidual MultiModeDXCoilResidual MultiModeDXCoilResidual MultiModeDXCoilResidual MultiSpeedDXCoolingCoilStandardRatings MultiSpeedDXHeatingCoilStandardRatings MULTOL MyPlantSizingIndex NeighborInformationArray_Value NETRAD NewEMSVariable NewExpression newPreDefColumn newPreDefReport newPreDefSubTable NEWTON NodeHasSPMCtrlVarType NormalArea NumBranchesInBranchList NumCompsInBranch nusselt NusseltNumber OpenEPlusWeatherFile OPENNESS_LW OpenOutputFiles OpenOutputTabularFile OpenWeatherFile OPERATOR (*) OPERATOR (+) OPERATOR (-) OPERATOR (.dot.) OPERATOR (.twodcross.) OPERATOR (.twoddot.) OPERATOR (/) ORDER OutBaroPressAt OutDewPointTempAt OutDryBulbTempAt OutsidePipeHeatTransCoef OutWetBulbTempAt P01 PanesDeflection ParametricObjectsCheck parseComputeLine ParseExpression ParseStack ParseTime PartLoadFactor PassiveGapNusseltNumber PassPressureAcrossInterface PassPressureAcrossMixer PassPressureAcrossSplitter PD_BEAM PD_BEAM_CASE_I PD_BEAM_CASE_II PD_BEAM_CASE_III PD_BEAM_CASE_IV PD_BEAM_CASE_V PD_BEAM_CASE_VI PD_DIFF PD_LW PD_LWP PD_SWP PerformanceCurveObject PerformanceTableObject PerformIterationLoop PerformPipeCellSimulation PerformPipeCircuitSimulation PerformSolarCalculations PerformTemperatureFieldUpdate PierceSurface PierceSurfaceVector PipeCircuitInfo_InitInOutCells PipeSegmentInfo_InitPipeCells PIUInducesPlenumAir PIUnitHasMixer PlaneEquation PlantHalfLoopSolver PlantMassFlowRatesFunc PLRResidual PLRResidual PLRResidualMixedTank PLRResidualStratifiedTank PMVResidual POLY1F POLY2F POLYF polygon_contains_point_2d popStack pos PostIPProcessing POWER PreDefTableEntry PredictSystemLoads PredictZoneContaminants PreparePipeCircuitSimulation PrepDebugFilesAndVariables PreProcessorCheck PrepVariablesISO15099 PreScanReportingVariables PresProfile PressureCurveValue ProcessDataDicFile ProcessDateString ProcessEMSInput ProcessEPWHeader ProcessForDayTypes ProcessInput ProcessInputDataFile ProcessIntervalFields ProcessMinMaxDefLine ProcessNumber ProcessScheduleInput ProcessSurfaceVertices ProcessTokens ProduceMinMaxString ProduceMinMaxStringWStartMinute ProduceRDDMDD ProfileAngle PropagateResolvedFlow PStack PsyCpAirFnWTdb PsyHfgAirFnWTdb PsyHFnTdbRhPb PsyHFnTdbW PsyHgAirFnWTdb PsyPsatFnTemp PsyPsatFnTemp_raw PsyRhFnTdbRhov PsyRhFnTdbRhovLBnd0C PsyRhFnTdbWPb PsyRhoAirFnPbTdbW PsyRhovFnTdbRh PsyRhovFnTdbRhLBnd0C PsyRhovFnTdbWPb PsyTdbFnHW PsyTdpFnTdbTwbPb PsyTdpFnWPb PsyTsatFnHPb PsyTsatFnPb PsyTwbFnTdbWPb PsyTwbFnTdbWPb_raw PsyVFnTdbWPb PsyWFnTdbH PsyWFnTdbRhPb PsyWFnTdbTwbPb PsyWFnTdpPb psz Pt2Plane PullCompInterconnectTrigger PumpDataForTable PushBranchFlowCharacteristics PushInnerTimeStepArrays pushStack PushSystemTimestepHistories PushSystemTimestepHistories PushZoneTimestepHistories PushZoneTimestepHistories QsortC QsortPartition RadialCellInfo_XY_CrossSectArea RadialCellInformation_ctor RadialSizing_Thickness Rainflow RangeCheck RB_BEAM RB_DIFF RB_F RB_LWP RB_SWP rCheckDayScheduleValueMinMax rCheckScheduleValue rCheckScheduleValueMinMax1 rCheckScheduleValueMinMax2 ReadEnergyMeters ReadEPlusWeatherForDay ReadGeneralDomainInputs ReadHorizontalTrenchInputs ReadINIFile ReadInputLine ReadPipeCircuitInputs ReadPipeSegmentInputs ReadTableData ReadUserWeatherInput ReadWeatherForDay Real_ConstrainTo Real_IsInRange real_times_vector ReAllocateAndPreserveOutputVariablesForSimulation ReallocateIntegerArray ReallocateIVar ReallocateRealArray ReallocateRVar RealPreDefTableEntry RealToStr RecKeepHeatBalance RecordOutput RectangleF_Contains ReformEIRChillerCondInletTempResidual ReformEIRChillerHeatRecovery RegisterNodeConnection RegisterPlantCompDesignFlow RegulateCondenserCompFlowReqOp ReInitPlantLoopsAtFirstHVACIteration RemoveSpaces RemoveTrailingZeros reorder ReplaceBlanksWithUnderscores ReplaceBlanksWithUnderscores ReportAirflowNetwork ReportAirHeatBalance ReportAirLoopConnections ReportAirTerminalUserDefined ReportAndTestGlycols ReportAndTestRefrigerants ReportBaseboard ReportBaseboard ReportCBVAV ReportChillerIPLV ReportCoilUserDefined ReportCompSetMeterVariables ReportController ReportCoolBeam ReportCoolTower ReportCTFs ReportCWTankInits ReportDemandManagerList ReportDesiccantDehumidifier ReportDetailedIceStorage ReportDirectAir ReportDualDuct ReportDualDuctConnections ReportDuct ReportDXCoil ReportDXCoilRating ReportDYMeters ReportEarthTube ReportEconomicVariable ReportElectricBaseboard ReportEMS ReportEvapCooler ReportEvapFluidCooler ReportExteriorEnergyUse ReportFan ReportFanCoilUnit ReportFatalGlycolErrors ReportFatalRefrigerantErrors ReportFiniteDiffInits ReportFluidCooler ReportFluidHeatExchanger ReportForTabularReports ReportFurnace ReportGlass ReportHeatBalance ReportHeatingCoil ReportHeatRecovery ReportHighTempRadiantSystem ReportHRMeters ReportHumidifier ReportHWBaseboard ReportIllumMap ReportingFreqName ReportingThisVariable ReportInternalHeatGains ReportLoopConnections ReportLowTempRadiantSystem ReportMaxVentilationLoads ReportMeterDetails ReportMissing_RangeData ReportMixer ReportMNMeters ReportMoistureBalanceEMPD ReportMSHeatPump ReportNodeConnections ReportOAController ReportOAMixer ReportOrphanFluids ReportOrphanRecordObjects ReportOrphanSchedules ReportOutdoorAirUnit ReportOutputFileHeaders ReportParentChildren ReportPipesHeatTransfer ReportPIU ReportPlantProfile ReportPlantUserComponent ReportPlantValves ReportPondGroundHeatExchanger ReportPTUnit ReportPumps ReportPurchasedAir ReportPV ReportRackSystem ReportRefrigerationComponents ReportReturnAirPath ReportRuntimeLanguage ReportScheduleDetails ReportScheduleValues ReportSizingOutput ReportSMMeters ReportSolarCollector ReportSplitter ReportStandAloneERV ReportStandAloneWaterUse ReportSteamBaseboard ReportSteamCoil ReportSurfaceErrors ReportSurfaceGroundHeatExchngr ReportSurfaceHeatBalance ReportSurfaces ReportSurfaceShading ReportSys ReportSysSizing ReportSystemEnergyUse ReportThermalChimney ReportTowers ReportTSMeters ReportUnitarySystem ReportUnitHeater ReportUnitVentilator ReportVentilatedSlab ReportVRFCondenser ReportVRFTerminalUnit ReportWarmupConvergence ReportWaterCoil ReportWaterManager ReportWaterThermalTank ReportWaterUse ReportWeatherAndTimeInformation ReportWindowAC ReportWindTurbine ReportZoneAirLoopEquipment ReportZoneAirUserDefined ReportZoneDehumidifier ReportZoneEquipment ReportZoneEvaporativeCoolerUnit ReportZoneMeanAirTemp ReportZoneReturnPlenum ReportZoneSizing ReportZoneSupplyPlenum ResetAllPlantInterConnectFlags ResetController ResetEnvironmentCounter ResetHVACControl ResetNodeData ResetPerformanceCurveOutput ResetRootFinder ResetTerminalUnitFlowLimits ResetWeekDaysByMonth Resimulate resist ReSolveAirLoopControllers ResolveAirLoopFlowLimits ResolveLocationInformation ResolveLockoutFlags ResolveLoopFlowVsPressure ResolveParallelFlows ResolveSysFlow ReverseAndRecalculate RevertZoneTimestepHistories RevertZoneTimestepHistories RevisePlantCallingOrder RezeroZoneSizingArrays RhoH2O RHtoVP RKG RoundSigDigits rRoundSigDigits rTrimSigDigits SafeCopyPlantNode SafeDiv SafeDivide SameString SandiaCellTemperature SandiaEffectiveIrradiance SandiaF1 SandiaF2 SandiaImp SandiaIsc SandiaIx SandiaIxx SandiaModuleTemperature SandiaTcellFromTmodule SandiaVmp SandiaVoc SaveSimpleController ScanForReports ScanPlantLoopsForNodeNum ScanPlantLoopsForObject sCheckDayScheduleValueMinMax ScheduleAverageHoursPerWeek SEARCH SearchAscTable SearchWindow5DataFile SecantFormula SecantMethod selectTariff SetActuatedBranchFlowRate SetAdditionalNeighborData SetAllFlowLocks SetAllPlantSimFlagsToValue SetATMixerPriFlow SetATMixerPriFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetCoilDesFlow SetCoilSystemCoolingData SetCoilSystemHeatingDXFlag SetCompFlowRate SetComponentFlowRate SetCurrentWeather SetCurveOutputMinMaxValues SetDSTDateRanges SetDXCoilTypeData SetDXCoolingCoilData SetEquivalentLayerWindowProperties SetErlValueNumber SetExtConvectionCoeff SetFanData SetHeatExchangerData SetHeatToReturnAirFlag SetInitialMeterReportingAndOutputNames SetIntConvectionCoeff SetInternalVariableValue SetMinMax setNativeVariables SetNodeResult SetOAControllerData SetOnOffMassFlowRate SetOnOffMassFlowRate SetOnOffMassFlowRate SetOnOffMassFlowRateVSCoil SetOnOffMassFlowRateVSCoil SetOutAirNodes SetOutBulbTempAt SetPredefinedTables SetSimpleWSHPData SETSKY SetSpecialDayDates SetSpeedVariables SetStormWindowControl SetSurfHBDataForMundtModel SetSurfHBDataForTempDistModel SetSurfTmeanAir SETUP4x4_A SetupAdaptiveConvectionRadiantSurfaceData SetupAdaptiveConvectionStaticMetaData SetupAirLoopControllersTracer SetupAllOutputVariables SetUpAndSort SetupBranchControlTypes SetupCellNeighbors SetupCommonPipes SetupComplexFenestrationMaterialInput SetupComplexFenestrationStateInput SetupComplexWindowStateGeometry SetUpCompSets SetupDElightOutput4EPlus SetupDElightOutput4EPlus SetUpDesignDay SetupEMSActuator SetupEMSIntegerActuator SetupEMSIntegerInternalVariable SetupEMSInternalVariable SetupEMSLogicalActuator SetupEMSRealActuator SetupEMSRealInternalVariable SetupEnvironmentTypes SetupFuelConstituentData SetupGeneratorControlStateManager SetupIndividualControllerTracer SetupInitialPlantCallingOrder SetupIntegerOutputVariable SetupInterpolationValues SetupLoopFlowRequest SetupMeteredVarsForSetPt SetupMundtModel SetupNodeSetpointsAsActuators SetupNodeVarsForReporting SetupOutputVariable SetupPipeCircuitInOutCells SetupPlantEMSActuators SetupPollutionCalculations SetupPollutionMeterReporting SetupPossibleOperators SetupPrimaryAirSystemAvailMgrAsActuators SetupPumpMinMaxFlows SetupRealOutputVariable SetupRealOutputVariable_IntKey SetupReportInput SetupReports SetupRootFinder SetUpSchemeColors SetupShadeSurfacesForSolarCalcs SetupSimpleWindowGlazingSystem SetupSimulation SetupStratifiedNodes SetupSurfaceConstructionActuators SetupSurfaceConvectionActuators SetupSurfaceOutdoorBoundaryConditionActuators SetUpSysSizingArrays SetupTankDemandComponent SetupTankSupplyComponent SetupThermostatActuators SetupTimePointers SetupUnitConversions SetupWeekDaysByMonth SetupWindowShadingControlActuators SetupZoneEquipmentForConvectionFlowRegime SetupZoneGeometry SetupZoneInfoAsInternalDataAvail SetupZoneInternalGain SetupZoneInternalGain SetupZoneSizing SetUpZoneSizingArrays SetUTSCQdotSource SetVarSpeedCoilData SetVentedModuleQdotSource SetVSHPAirFlow SetVSHPAirFlow SetWindSpeedAt SetZoneEquipSimOrder shading shadingedge shadingin SHADOW SharedDVCVUFDataInit SHDBKS SHDGSS SHDRVL SHDSBS shift ShiftPipeTemperaturesForNewIteration ShiftPlantLoopSideCallingOrder ShiftTemperaturesForNewIteration ShiftTemperaturesForNewTimeStep ShowAuditErrorMessage ShowBranchesOnLoop ShowContinueError ShowContinueError ShowContinueErrorTimeStamp ShowContinueErrorTimeStamp ShowErrorMessage ShowErrorMessage ShowFatalError ShowFatalError ShowMessage ShowMessage ShowPsychrometricSummary ShowRecurringContinueErrorAtEnd ShowRecurringContinueErrorAtEnd ShowRecurringErrors ShowRecurringSevereErrorAtEnd ShowRecurringSevereErrorAtEnd ShowRecurringWarningErrorAtEnd ShowRecurringWarningErrorAtEnd ShowSevereError ShowSevereError ShowSevereMessage ShowSevereMessage ShowWarningError ShowWarningError ShowWarningMessage ShowWarningMessage showWarningsBasedOnTotal Sim4PipeFanCoil SimAirChillerSet SimAirLoop SimAirLoopComponent SimAirLoopComponents SimAirLoops SimAirLoopSplitter SimAirMixer SimAirTerminalUserDefined SimAirZonePlenum SimATMixer SimBaseboard SimBLASTAbsorber SimBoiler SimCBVAV SimCBVAV SimCentralGroundSourceHeatPump SimChiller SimCoilUserDefined SimComponentModelFan SimConstVol SimCoolBeam SimCostEstimate SimCTGenerator SimCTPlantHeatRecovery SimCyclingWindowAC SimDesiccantDehumidifier SimDetailedIceStorage SimDirectAir SimDistrictEnergy SimDualDuctConstVol SimDualDuctVarVol SimDualDuctVAVOutdoorAir SimDuct SimDXCoil SimDXCoilMultiMode SimDXCoilMultiSpeed SimDXCoolingSystem SimDXHeatPumpSystem SimElecBaseBoard SimElectricBaseBoard SimElectricConvective SimElectricEIRChiller SimEvapCooler SimEvapFluidCoolers SimExhaustAbsorber SimFanCoilUnit SimFluidCoolers SimFluidHeatExchanger SimFourPipeIndUnit SimFuelCellGenerator SimFuelCellPlantHeatRecovery SimFurnace SimGasAbsorber SimGroundHeatExchangers SimHeatPumpWaterHeater SimHeatRecovery SimHighTempRadiantSystem SimHPWatertoWaterCOOLING SimHPWatertoWaterHEATING SimHPWatertoWaterSimple SimHumidifier SimHVAC SimHWBaseboard SimHWConvective SimHXAssistedCoolingCoil SimICEngineGenerator SimICEPlantHeatRecovery SimIceStorage SimIndirectAbsorber SimIndUnit SimLowTempRadiantSystem SimMicroCHPGenerator SimMicroCHPPlantHeatRecovery SimMSHeatPump SimMSHP SimMTGenerator SimMTPlantHeatRecovery SimMultiSpeedCoils SimOAComponent SimOAController SimOAMixer SimOnOffFan SimOutdoorAirEquipComps SimOutdoorAirUnit SimOutsideAirSys SimOutsideEnergy SimPackagedTerminalUnit SimPipes SimPipesHeatTransfer SimPipingSystemCircuit SimPIU SimPlantEquip SimPlantValves SimpleCoolingCoilUAResidual SimpleEvapFluidCoolerUAResidual SimpleFluidCoolerUAResidual SimpleHeatingCoilUAResidual SimpleTowerApproachResidual SimpleTowerTrResidual SimpleTowerUAResidual SimPondGroundHeatExchanger SimPressureDropSystem SimPTUnit SimPumps SimPurchasedAir SimPVGenerator SimPVTcollectors SimReformulatedEIRChiller SimRefrigCondenser SimReturnAirPath SimSelectedEquipment SimSetPointManagers SimSimpleEvapFluidCooler SimSimpleFan SimSimpleFluidCooler SimSimpleTower SimSolarCollector SimStandAloneERV SimSteamBaseboard SimSteamBoiler SimSteamCoils SimSurfaceGroundHeatExchanger SimSysAvailManager SimTESCoil SimTowers SimTranspiredCollector SimulateAllInteriorRadialSoilSlices SimulateAllLoopSideBranches SimulateAllLoopSidePumps SimulateDemandManagerList SimulateDetailedRefrigerationSystems SimulateDetailedTransRefrigSystems SimulateDualDuct SimulateFanComponents SimulateFluidCell SimulateHeatingCoilComponents SimulateInnerMostRadialSoilSlice SimulateLoopSideBranchGroup SimulateOuterMostRadialSoilSlice SimulatePlantProfile SimulateRadialInsulationCell SimulateRadialPipeCell SimulateRadialToCartesianInterface SimulateSingleDuct SimulateSteamCoilComponents SimulateVRF SimulateWaterCoilComponents SimulateWaterHeaterStandAlone SimulateWaterUse SimulateWaterUseConnection SimUnitaryBypassVAV SimUnitarySystem SimUnitHeater SimUnitVentilator SimUnitVentOAMixer SimUserDefinedPlantComponent SimVariableSpeedCoils SimVariableSpeedHP SimVariableSpeedHP SimVariableTower SimVariableVolumeFan SimVAV SimVAVVS SimVentilatedSlab SimVentSlabOAMixer SimVRF SimVRFCondenserPlant SimWaterCoils SimWaterSource SimWaterThermalTank SimWatertoAirHP SimWatertoAirHPSimple SimWindowAC SimWindTurbine SimZoneAirLoopEquipment SimZoneAirUserDefined SimZoneDehumidifier SimZoneEquipment SimZoneEvaporativeCoolerUnit SimZoneExhaustFan SimZoneOutAirUnitComps SingelSpeedDXCoolingCoilStandardRatings SingleSpeedDXHeatingCoilStandardRatings SingleSpeedFluidCooler SizeAbsorpChiller SizeAirLoopBranches SizeAirLoops SizeBaseboard SizeBoiler SizeBoiler SizeCBVAV SizeConstCOPChiller SizeController SizeCoolBeam SizeDemandSidePlantConnections SizeDirectAir SizeDualDuct SizeDXCoil SizeElecReformEIRChiller SizeElectricBaseboard SizeElectricBaseboard SizeElectricChiller SizeElectricEIRChiller SizeEngineDrivenChiller SizeEvapCooler SizeEvapFluidCooler SizeExhaustAbsorber SizeFan SizeFanCoilUnit SizeFluidCooler SizeFluidHeatExchanger SizeFurnace SizeGasAbsorber SizeGTChiller SizeHeatingCoil SizeHeatRecovery SizeHighTempRadiantSystem SizeHumidifier SizeHVACWaterToAir SizeHWBaseboard SizeIndirectAbsorpChiller SizeIndUnit SizeLowTempRadiantSystem SizeMSHeatPump SizeOAController SizeOutdoorAirUnit SizePIU SizePlantLoop SizePTUnit SizePump SizePurchasedAir SizePVT SizeStandAloneERV SizeStandAloneWaterHeater SizeSteamBaseboard SizeSteamCoil SizeSupplySidePlantConnections SizeSys SizeTankForDemandSide SizeTankForSupplySide SizeTESCoil SizeTower SizeUCSDUF SizeUnitarySystem SizeUnitHeater SizeUnitVentilator SizeVarSpeedCoil SizeVentilatedSlab SizeVRF SizeVRFCondenser SizeVSMerkelTower SizeWaterCoil SizeWaterManager SizeWaterSource SizeWindowAC SizeWrapper SizeZoneDehumidifier SizeZoneEquipment SizeZoneEvaporativeCoolerUnit SkipEPlusWFHeader SkyDifSolarShading SkyGndWeight SkyWeight SLtoAMB SLtoGL SLVSKY solar_EN673 solarISO15099 SolarSprectrumAverage SOLMATS SolveAirLoopControllers SolveForWindowTemperatures SolveRegression SolveRegulaFalsi SolverMoistureBalanceEMPD SOLVZP SortHistory Specular_Adjust Specular_EstimateDiffuseProps Specular_F Specular_OffNormal Specular_RATDiff Specular_SWP SQLiteBegin SQLiteBegin SQLiteBindDouble SQLiteBindInteger SQLiteBindLogicalMacro SQLiteBindNULL SQLiteBindText SQLiteBindTextMacro SQLiteClearBindings SQLiteCloseDatabase SQLiteColumnInt SQLiteColumnIntMacro SQLiteCommit SQLiteCommit SQLiteExecuteCommand SQLiteExecuteCommandMacro SQLiteFinalizeCommand SQLiteOpenDatabase SQLiteOpenDatabaseMacro SQLitePrepareStatement SQLitePrepareStatementMacro SQLiteResetCommand SQLiteStepCommand SQLiteWriteMessage SQLiteWriteMessageMacro SQLiteWriteMessageMacro StandardIndexTypeKey StandardVariableTypeKey StartingWindowTemps StartingWinTempsForNominalCond SteamHeatingCoilResidual StorageType StoreAPumpOnCurrentTempLoop storeIterationResults StoreRecurringErrorMessage StringValue StrToReal SumAllInternalCO2Gains SumAllInternalConvectionGains SumAllInternalGenericContamGains SumAllInternalLatentGains SumAllInternalRadiationGains SumAllReturnAirConvectionGains SumAllReturnAirLatentGains SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumInternalCO2GainsByTypes SumInternalConvectionGainsByTypes SumInternalLatentGainsByTypes SumInternalRadiationGainsByTypes SummarizeErrors SumReturnAirConvectionGainsByTypes SumZoneImpacts SUN3 SUN4 SupSATResidual SurfaceScheduledSolarInc SurveyDemandManagers SystemPropertiesAtLambdaAndPhi SystemSpectralPropertiesAtPhi TableLookupObject TARCOG90 TBND TdbFnHRhPb TDMA TDMA_R TellMeHowManyObjectItemArgs TemperaturesFromEnergy TempIPtoSI TempSItoIP terpld TESCoilHumRatResidual TESCoilResidual TestAirPathIntegrity TestBranchIntegrity TestCompSet TestCompSetInletOutletNodes TestInletOutletNodes TestReturnAirPathIntegrity TestSupplyAirPathIntegrity therm1d TightenNodeMinMaxAvails TimestepInitComplexFenestration TimestepTypeName TraceAirLoopController TraceAirLoopControllers TraceIndividualController TraceIterationStamp TrackAirLoopController TrackAirLoopControllers TRadC TransAndReflAtPhi TransformVertsByAspect TransTDD Triangulate TrimSigDigits TurnOffLoopEquipment TurnOffLoopSideEquipment TurnOffReportRangeCheckErrors TurnOnPlantLoopPipes TurnOnReportRangeCheckErrors TwoSpeedFluidCooler UnitarySystemHeatRecovery UpdateAbsorberChillerComponentGeneratorSide UpdateAirflowNetwork UpdateAirMixer UpdateAirSysCompPtrArray UpdateAirSysSubCompPtrArray UpdateAirSysSubSubCompPtrArray UpdateAirZoneReturnPlenum UpdateAirZoneSupplyPlenum UpdateAnyLoopDemandAlterations UpdateATMixer UpdateBaseboard UpdateBaseboardPlantConnection UpdateBasementSurfaceTemperatures UpdateBBElecRadSourceValAvg UpdateBBRadSourceValAvg UpdateBBSteamRadSourceValAvg UpdateBLASTAbsorberRecords UpdateBoilerRecords UpdateBoilerRecords UpdateBracket UpdateBranchConnections UpdateChillerComponentCondenserSide UpdateChillerheaterRecords UpdateChillerRecords UpdateColdWeatherProtection UpdateCommonPipe UpdateComplexWindows UpdateComponentHeatRecoverySide UpdateConstCOPChillerRecords UpdateController UpdateCoolBeam UpdateCoolTower UpdateCTGeneratorRecords UpdateDataandReport UpdateDemandManagers UpdateDesiccantDehumidifier UpdateDetailedIceStorage UpdateDualDuct UpdateDuct UpdateDXCoil UpdateElectricBaseboard UpdateElectricChillerRecords UpdateElectricEIRChillerRecords UpdateEMSTrendVariables UpdateEngineDrivenChiller UpdateEvapCooler UpdateEvapFluidCooler UpdateEvaporativeCondenserBasinHeater UpdateEvaporativeCondenserWaterUse UpdateExhaustAbsorberCoolRecords UpdateExhaustAbsorberHeatRecords UpdateExhaustAirFlows UpdateFan UpdateFinalSurfaceHeatBalance UpdateFluidCooler UpdateFluidHeatExchanger UpdateFuelCellGeneratorRecords UpdateGasAbsorberCoolRecords UpdateGasAbsorberHeatRecords UpdateGSHPRecords UpdateGSHPRecords UpdateGSHPRecords UpdateGTChillerRecords UpdateHalfLoopInletTemp UpdateHeatBalHAMT UpdateHeatingCoil UpdateHeatRecovery UpdateHighTempRadiantSystem UpdateHistories UpdateHistory UpdateHTRadSourceValAvg UpdateHumidifier UpdateHVACInterface UpdateHWBaseboard UpdateHWBaseboardPlantConnection UpdateIceFractions UpdateICEngineGeneratorRecords UpdateIndirectAbsorberRecords UpdateInternalGainValues UpdateIrrigation UpdateLoadCenterRecords UpdateLoopSideReportVars UpdateLowTempRadiantSystem UpdateMeterReporting UpdateMeters UpdateMeterValues UpdateMicroCHPGeneratorRecords UpdateMinMax UpdateMixedAirSetPoints UpdateMoistureBalanceEMPD UpdateMoistureBalanceFD UpdateMSHeatPump UpdateMTGeneratorRecords UpdateNode UpdateNodeThermalHistory UpdateOAController UpdateOAMixer UpdateOAPretreatSetPoints UpdatePipesHeatTransfer UpdatePipingSystems UpdatePlantLoopInterface UpdatePlantMixer UpdatePlantProfile UpdatePlantSplitter UpdatePlantValves UpdatePondGroundHeatExchanger UpdatePrecipitation UpdatePressureDrop UpdatePurchasedAir UpdatePVTcollectors UpdateRadSysSourceValAvg UpdateRecords UpdateReformEIRChillerRecords UpdateRefrigCondenser UpdateReportWaterSystem UpdateRootFinder UpdateScheduleValues UpdateSetPointManagers UpdateSimpleWatertoAirHP UpdateSoilProps UpdateSolarCollector UpdateSplitter UpdateSQLiteErrorRecord UpdateSQLiteErrorRecord UpdateSQLiteSimulationRecord UpdateSQLiteSimulationRecord UpdateSteamBaseboard UpdateSteamBaseboardPlantConnection UpdateSteamCoil UpdateSurfaceGroundHeatExchngr UpdateSys UpdateSysSizing UpdateSystemOutputRequired UpdateTabularReports UpdateTEStorage UpdateThermalHistories UpdateTowers UpdateTranspiredCollector UpdateUnitarySystemControl UpdateUtilityBills UpdateVarSpeedCoil UpdateVentilatedSlab UpdateVerticalGroundHeatExchanger UpdateVRFCondenser UpdateWaterCoil UpdateWaterConnections UpdateWaterManager UpdateWaterSource UpdateWaterThermalTank UpdateWaterToAirCoilPlantConnection UpdateWatertoAirHP UpdateWeatherData UpdateWholeBuildingRecords UpdateZoneAirLoopEquipment UpdateZoneCompPtrArray UpdateZoneDehumidifier UpdateZoneEquipment UpdateZoneInletConvergenceLog UpdateZoneListAndGroupLoads UpdateZoneSizing UpdateZoneSubCompPtrArray UpdateZoneSubSubCompPtrArray ValidateAndSetSysAvailabilityManagerType ValidateComponent ValidateDistributionSystem ValidateEMSProgramName ValidateEMSVariableName ValidateExhaustFanInput ValidateFlowControlPaths ValidateFuelType ValidateIndexType ValidateMaterialRoughness ValidateMonthDay ValidateNStandardizeMeterTitles ValidateObjectandParse ValidatePipeConstruction ValidatePLFCurve ValidateSection ValidateSectionsInput ValidateVariableType value_to_vector ValueToString VAVVSCoolingResidual VAVVSHCFanOnResidual VAVVSHWFanOnResidual VAVVSHWNoFanResidual VB_CriticalSlatAngle VB_DIFF VB_LWP VB_ShadeControl VB_SLAT_RADIUS_RATIO VB_SOL4 VB_SOL46_CURVE VB_SOL6 VB_SWP vec2d_cross_product vec2d_dot_product vec_cross_product vec_dot_product VecLength VecNegate VecNormalize VecRound VecSquaredLength vector_add vector_div_int vector_div_real vector_subtract vector_times_int vector_times_real vector_to_array VerifyControlledZoneForThermostat VerifyCustomMetersElecPowerMgr VerifyHeatExchangerParent VerifyName VerifySetPointManagers VerifyThermostatInZone VerifyUniqueBaseboardName VerifyUniqueBoilerName VerifyUniqueChillerName VerifyUniqueCoilName ViewFac VisibleSprectrumAverage Volume VRMLOut VSCoilCyclingHumResidual VSCoilCyclingResidual VSCoilCyclingResidual VSCoilSpeedHumResidual VSCoilSpeedResidual VSCoilSpeedResidual VSEvapUnitLoadResidual VSHPCyclingResidual VSHPCyclingResidual VSHPSpeedResidual VSHPSpeedResidual VSMerkelResidual W5InitGlassParameters W5LsqFit W5LsqFit2 W6CoordsFromWorldVect warnIfNativeVarname WetCoilOutletCondition WhichCompSet WhichParentCompSet WhichParentSet Width WindowGapAirflowControl WindowGasConductance WindowGasPropertiesAtTemp WindowHeatBalanceEquations WindowScheduledSolarAbs WindowShadingManager WindowTempsForNominalCond WindSpeedAt Windward WorldVectFromW6 WriteAdaptiveComfortTable WriteAirLoopStatistics WriteBEPSTable WriteCompCostTable WriteComponentSizing WriteCumulativeReportMeterData WriteDaylightMapTitle WriteDemandEndUseSummary WriteInputArguments WriteIntegerData WriteIntegerVariableOutput WriteMeterDictionaryItem WriteModifiedArguments WriteMonthlyTables WriteOutputArguments WriteOutputEN673 WritePoint WritePredefinedTables WriteRealData WriteRealVariableOutput WriteReportHeaders WriteReportIntegerData WriteReportMeterData WriteReportRealData WriteReportVariableDictionaryItem WriteRootFinderStatus WriteRootFinderTrace WriteRootFinderTraceHeader WriteSourceEnergyEndUseSummary writeSubtitle WriteSurfaceShadowing WriteTable WriteTableOfContents WriteTabularLifeCycleCostReport WriteTabularReports WriteTabularTariffReports WriteTARCOGInputFile writeTextLine WriteTimeBinTables WriteTimeStampFormatData WriteTrace WriteVeriSumTable WriteZoneLoadComponentTable WVDC XNormalArea XYRectangle XZRectangle YNormalArea YZRectangle ZeroHVACValues ZNormalArea
Call graph
calcheatbalanceinsidesurf calls setupoutputvariable, showfatalerror, wingainirglaztozonerep, roundsigdigits, winheatgain, winheatlossrep, wingainframedividertozonerep, winheatgainrep, wingainconvglaztozonerep, wingainconvshadetozonerep, wingainirshadetozonerep, winlossswzonetooutwinrep, wingainconvglazshadgaptozonerep, zoneequipconfig, initinteriorconvectioncoeffs, otherconvgaininsidefacetozonerep, tempeffbulkair, hmassconvinfd, tempsurfintmp, zoneairhumrat, hconvinfd, qhwbaseboardsurf, calcmoisturebalanceempd, qhtradsyssurf, showcontinueerror, zonewinheatlossrep, sumhmara, psyrhfntdbrhov, sumhmaraw, showwarningerror, surface, moistempdnew, updatemoisturebalanceempd, psyrhfntdbrhovlbnd0c, zonewinheatgainrep, zonewinheatgain, zonewinheatgainrepenergy, calculatezonemrt, zonewinheatlossrepenergy, zone, node, hairextsurf, qelecbaseboardsurf, hskyextsurf, showcontinueerrortimestamp, qsteambaseboardsurf, moistempdflux, radsystihbconstcoef, radsystihbtoutcoef, manageheatbalhamt, radsystihbqsrccoef, wintranssolar, qradtherminabs, manageheatbalfinitediff, qs, evalinsidemovableinsulation, eqlwindowoutsideeffectiveemiss, winheatgainrepenergy, psywfntdbrhpb, psycpairfnwtdb, calcwindowheatbalance, winheatlossrepenergy, qdotconvinrep, tempsurfinrep, qdotconvinrepperarea, tempsurfout, showrecurringwarningerroratend, mat, qconvinreport, loadconvectednormal, psyrhovfntdbwpb, loadconvectedwithpulse, hconvin, netsurfradseq, showseveremessage, qdotradnetsurfinrep, showrecurringsevereerroratend, tddpipe, surfacewindow, findtddpipe, qradswwinabs, qradswinabs, tempsurfin, netlwradtosurf, rhovaporsurfin, th, ctfconstinpart, radsystohbqsrccoef, initexteriorconvectioncoeff, radsystohbtincoef, material, setextconvectioncoeff, hcextsurf, updateheatbalhamt, qsrchist, rhovaporairin, surfacefd, adjacentzonetosurface, sumhmaw, construct, calcinteriorradexchange, hgrdextsurf, radsystohbconstcoef, tempoutsideairfd, psyrhoairfnpbtdbw, showsevereerror, psyrhovfntdbrh
showfatalerror calls roundsigdigits, abortenergyplus, displaystring, showerrormessage, createsqliteerrorrecord
showcontinueerror calls showerrormessage, updatesqliteerrorrecord
psyrhfntdbrhov calls trimsigdigits, showrecurringwarningerroratend, showwarningmessage, showcontinueerror, showcontinueerrortimestamp, psypsatfntemp
showwarningerror calls showerrormessage, createsqliteerrorrecord, matchcounts, messagesearch
psyrhfntdbrhovlbnd0c calls trimsigdigits, showrecurringwarningerroratend, showwarningmessage, showcontinueerror, showcontinueerrortimestamp
showcontinueerrortimestamp calls showerrormessage, updatesqliteerrorrecord, createsystimeintervalstring
psywfntdbrhpb calls trimsigdigits, showrecurringwarningerroratend, showwarningmessage, showcontinueerror, showcontinueerrortimestamp, psypsatfntemp
psycpairfnwtdb calls psyhfntdbw
showrecurringwarningerroratend calls matchcounts, messagesearch
showseveremessage calls showerrormessage, createsqliteerrorrecord, matchcounts, messagesearch
showrecurringsevereerroratend calls matchcounts, messagesearch
psyrhoairfnpbtdbw calls roundsigdigits, showcontinueerror, showcontinueerrortimestamp, showsevereerror, showfatalerror
showsevereerror calls showerrormessage, createsqliteerrorrecord, matchcounts, messagesearch
psyrhovfntdbrh calls psypsatfntemp
abortenergyplus calls roundsigdigits, displaystring, testairpathintegrity, updatesqlitesimulationrecord, checkmarkednodes, reportairloopconnections, showrecurringerrors, testcompsetinletoutletnodes, summarizeerrors, reportsurfaceerrors, reportloopconnections, closemiscopenfiles, setupnodevarsforreporting, closesocket, closeoutopenfiles, reportsurfaces, testbranchintegrity, checkplantonabort, epelapsedtime, epstoptime, epsummarytimes, showmessage, checknodeconnections
showerrormessage calls showfatalerror, displaystring
testairpathintegrity calls showcontinueerror, showsevereerror, airtozonenodeinfo, nodeid
showrecurringerrors calls roundsigdigits, createsqliteerrorrecord, showmessage, removetrailingzeros, recurringerrors, updatesqliteerrorrecord
summarizeerrors calls showmessage, matchcounts, summaries, moredetails
closemiscopenfiles calls closedfsfile, closereportillummaps
reportsurfaces calls showwarningerror, detailsforsurfaces, setupschemecolors, vrmlout, scanforreports, dxfoutwireframe, costinfoout, linesout, dxfout
epstoptime calls showfatalerror, tstop
epsummarytimes calls roundsigdigits
showmessage calls showerrormessage
detailsforsurfaces calls roundsigdigits, surface, zone, surfacewindow, construct, getschedulename, oscm, nominalu, framedivider, getschedulemaxvalue, 2, computenominaluwithconvcoeffs, 3, osc, trimsigdigits, 4, csurfaceclass, userintconvectioncoeffs, userextconvectioncoeffs, getscheduleminvalue
setupschemecolors calls showwarningerror, getobjectitemnum, getobjectdefmaxargs, matchandsetcolortextstring, getobjectitem
vrmlout calls showfatalerror, showcontinueerror, showwarningerror, surface, zone, triangulate, getnewunitnumber
dxfoutwireframe calls showfatalerror, surface, zone, surfacewindow, trimsigdigits, getnewunitnumber, zonedaylight, dxfcolorno
costinfoout calls showfatalerror, surface, construct, csurfaceclass, getnewunitnumber
linesout calls showfatalerror, roundsigdigits, showcontinueerror, showwarningerror, surface, csurfaceclass, getnewunitnumber
dxfout calls showfatalerror, showcontinueerror, showwarningerror, surface, zone, surfacewindow, trimsigdigits, triangulate, getnewunitnumber, zonedaylight, dxfcolorno, illummapcalc
computenominaluwithconvcoeffs calls surface
matchandsetcolortextstring calls finditem
triangulate calls roundsigdigits, showcontinueerror, showwarningerror, showmessage, csurfaceclass, generate_ears, calcrfflrcoordinatetransformation, calcwallcoordinatetransformation
generate_ears calls polygon_contains_point_2d, angle_2dvector
psypsatfntemp calls psypsatfntemp_raw
psypsatfntemp_raw calls trimsigdigits, showrecurringwarningerroratend, showwarningmessage, showcontinueerror, showcontinueerrortimestamp, showsevereerror, showfatalerror
resimulate calls calcheatbalanceinsidesurf
managedemand calls resimulate