ControlUnitarySystemOutput – EnergyPlusFortran
ControlUnitarySystemOutput Subroutine
599 statements
Source File
private subroutine ControlUnitarySystemOutput(UnitarySysNum, FirstHVACIteration, OnOffAirFlowRatio, HXUnitOn, ZoneLoad, FullSensibleOutput, CompOn)
Uses:
General
DataHeatBalFanSys
Psychrometrics
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UnitarySysNum
logical, intent(in) :: FirstHVACIteration
real(kind=R64), intent(inout) :: OnOffAirFlowRatio
logical, intent(inout), optional :: HXUnitOn
real(kind=R64), intent(in) :: ZoneLoad
real(kind=R64), intent(inout) :: FullSensibleOutput
integer, intent(inout), optional :: CompOn
Calls
Called By
Source Code
ControlUnitarySystemOutput
Source Code
SUBROUTINE ControlUnitarySystemOutput(UnitarySysNum, FirstHVACIteration, OnOffAirFlowRatio, HXUnitOn, &
                                      ZoneLoad, FullSensibleOutput, CompOn)
          ! SUBROUTINE INFORMATION:
          !       AUTHOR         Richard Raustad, FSEC
          !       DATE WRITTEN   February 2013
          !       MODIFIED       na
          !       RE-ENGINEERED  na
          ! PURPOSE OF THIS SUBROUTINE:
          ! This subroutine determines operating PLR and calculates the load based system output.
          ! METHODOLOGY EMPLOYED:
          ! na
          ! REFERENCES:
          ! na
          ! USE STATEMENTS:
  USE General,           ONLY: SolveRegulaFalsi, TrimSigDigits
  USE DataHeatBalFanSys, ONLY: TempControlType
  USE Psychrometrics,    ONLY: PsyCpAirFnWTdb
  IMPLICIT NONE    ! Enforce explicit typing of all variables in this routine
          ! SUBROUTINE ARGUMENT DEFINITIONS:
  INTEGER, INTENT(IN)              :: UnitarySysNum    ! Index of AirloopHVAC:UnitarySystem object
  LOGICAL, INTENT(IN)              :: FirstHVACIteration  ! True when first HVAC iteration
  REAL(R64), INTENT(INOUT)         :: OnOffAirFlowRatio   ! ratio of heating PLR to cooling PLR (is this correct?)
  LOGICAL, INTENT(INOUT), OPTIONAL :: HXUnitOn            ! Flag to control HX for HXAssisted Cooling Coil
  REAL(R64), INTENT(IN)            :: ZoneLoad
  REAL(R64), INTENT(INOUT)         :: FullSensibleOutput
  INTEGER, OPTIONAL, INTENT(INOUT) :: CompOn
          ! SUBROUTINE PARAMETER DEFINITIONS:
  INTEGER,   PARAMETER  ::  MaxIter = 100        ! maximum number of iterations
  REAL(r64), PARAMETER  ::  MinPLR  = 0.0d0      ! minimum part load ratio allowed
          ! INTERFACE BLOCK SPECIFICATIONS
          ! na
          ! DERIVED TYPE DEFINITIONS
          ! na
          ! SUBROUTINE LOCAL VARIABLE DEFINITIONS:
          ! na
          ! SUBROUTINE LOCAL VARIABLE DECLARATIONS:
  CHARACTER(len=MaxNameLength)  :: CompName           ! Name of Unitary System object
  INTEGER                       :: InletNode          ! DX System inlet node number
  INTEGER                       :: OutletNode         ! DX System outlet node number
  INTEGER                       :: OpMode             ! fan operating mode (cycling or constant)
  REAL(R64)                     :: PartLoadRatio      ! operating part-load ratio
  REAL(R64)                     :: SensOutputOff      ! sensible output at PLR = 0 [W]
  REAL(R64)                     :: LatOutputOff       ! latent output at PLR = 0 [W]
  REAL(R64)                     :: SensOutputOn       ! sensible output at PLR = 1 [W]
  REAL(R64)                     :: LatOutputOn        ! latent output at PLR = 1 [W]
  REAL(R64)                     :: CoolPLR            ! cooing part load ratio
  REAL(R64)                     :: HeatPLR            ! heating part load ratio
  REAL(r64), DIMENSION(10)      :: Par                ! parameters passed to RegulaFalsi function
  INTEGER                       :: SolFlag            ! return flag from RegulaFalsi for sensible load
  INTEGER                       :: SolFlagLat         ! return flag from RegulaFalsi for latent load
  REAL(r64)                     :: TempLoad           ! represents either a sensible or latent load [W]
  REAL(r64)                     :: TempSysOutput      ! represents either a sensible or latent capacity [W]
  REAL(R64)                     :: TempSensOutput     ! iterative sensible capacity [W]
  REAL(R64)                     :: TempLatOutput      ! iterative latent capacity [W]
  REAL(R64)                     :: TempMinPLR         ! iterative minimum PLR
  REAL(R64)                     :: TempMaxPLR         ! iterative maximum PLR
  INTEGER                       :: SpeedNum           ! multi-speed coil speed number
  INTEGER                       :: CompressorONFlag   ! 0= compressor off, 1= compressor off
  REAL(r64)                     :: CoolingOnlySensibleOutput ! use to calculate dehumidification induced heating [W]
  REAL(r64)                     :: CpAir                     ! specific heat of air [J/kg_C]
  CompName = UnitarySystem(UnitarySysNum)%Name
  InletNode = UnitarySystem(UnitarySysNum)%UnitarySystemInletNodeNum
  OutletNode = UnitarySystem(UnitarySysNum)%UnitarySystemOutletNodeNum
  OpMode = UnitarySystem(UnitarySysNum)%FanOpMode
  ! Pass full mass flow rate on FirstHVACIteration to set MassFlowRateMax
  IF(FirstHVACIteration .AND. UnitarySystem(UnitarySysNum)%AirLoopEquipment)THEN
    IF (UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_CoolingSingleSpeed .OR. &
        UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_CoolingHXAssisted .OR. &
        UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == CoilDX_HeatingEmpirical .OR. &
        UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == Coil_HeatingAirToAirVariableSpeed .OR. &
        UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == Coil_CoolingAirToAirVariableSpeed .OR. &
        UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == Coil_CoolingWaterToAirHPSimple .OR. &
        UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == Coil_HeatingWaterToAirHPSimple) THEN
      PartLoadRatio = 1.0d0
      IF(HeatingLoad)THEN
        UnitarySystem(UnitarySysNum)%HeatingSpeedNum = UnitarySystem(UnitarySysNum)%NumOfSpeedHeating
        UnitarySystem(UnitarySysNum)%HeatingSpeedRatio = 1.0d0
      ELSE
!        CoolingLoad = .TRUE.
        UnitarySystem(UnitarySysNum)%CoolingSpeedNum = UnitarySystem(UnitarySysNum)%NumOfSpeedCooling
        UnitarySystem(UnitarySysNum)%CoolingSpeedRatio = 1.0d0
      END IF
    ELSE
      IF(HeatingLoad)THEN
        PartLoadRatio = 0.0d0
        UnitarySystem(UnitarySysNum)%HeatingSpeedNum = UnitarySystem(UnitarySysNum)%NumOfSpeedHeating
        UnitarySystem(UnitarySysNum)%HeatingSpeedRatio = 1.0d0
        IF (UnitarySystem(UnitarySysNum)%Staged .AND. ABS(UnitarySystem(UnitarySysNum)%StageNum) .LT. &
            UnitarySystem(UnitarySysNum)%NumOfSpeedHeating) THEN
          UnitarySystem(UnitarySysNum)%HeatingSpeedNum = ABS(UnitarySystem(UnitarySysNum)%StageNum)
          IF (UnitarySystem(UnitarySysNum)%HeatingSpeedNum == 1) UnitarySystem(UnitarySysNum)%HeatingSpeedRatio = 0.0d0
        END IF
      ELSE
!        CoolingLoad = .TRUE.
        PartLoadRatio = 1.0d0
        UnitarySystem(UnitarySysNum)%CoolingSpeedNum = UnitarySystem(UnitarySysNum)%NumOfSpeedCooling
        UnitarySystem(UnitarySysNum)%CoolingSpeedRatio = 1.0d0
        IF (UnitarySystem(UnitarySysNum)%Staged .AND. ABS(UnitarySystem(UnitarySysNum)%StageNum) .LT. &
            UnitarySystem(UnitarySysNum)%NumOfSpeedCooling) THEN
          UnitarySystem(UnitarySysNum)%CoolingSpeedNum = ABS(UnitarySystem(UnitarySysNum)%StageNum)
          IF (UnitarySystem(UnitarySysNum)%CoolingSpeedNum == 1) UnitarySystem(UnitarySysNum)%CoolingSpeedRatio = 0.0d0
        END IF
      END IF
    END IF
    CALL SetOnOffMassFlowRate(UnitarySysNum, OnOffAirFlowRatio, PartLoadRatio)
    IF(HeatingLoad)THEN
      UnitarySystem(UnitarySysNum)%HeatingPartLoadFrac=1.0d0
    ELSE
      UnitarySystem(UnitarySysNum)%CoolingPartLoadFrac=1.0d0
    END IF
    CompOn=0
    RETURN
  END IF
  IF(GetCurrentScheduleValue(UnitarySystem(UnitarySysNum)%SysAvailSchedPtr) .LE. 0.0d0)THEN
    RETURN
  END IF
  PartLoadRatio = 0.0d0   ! Get no load result
  SolFlag = 0    ! # of iterations IF positive, -1 means failed to converge, -2 means bounds are incorrect
  SolFlagLat = 0    ! # of iterations IF positive, -1 means failed to converge, -2 means bounds are incorrect
  SensOutputOff = 0.0d0
  LatOutputOff  = 0.0d0
  CoolPLR       = 0.0d0
  HeatPLR       = 0.0d0
  CompressorONFlag = 0
  UnitarySystem(UnitarySysNum)%WSHPRuntimeFrac   = 0.0d0
  CALL SetOnOffMassFlowRate(UnitarySysNum, OnOffAirFlowRatio, PartLoadRatio)
  IF (HeatingLoad) THEN
    UnitarySystem(UnitarySysNum)%HeatingCoilSensDemand   = ZoneLoad
    UnitarySystem(UnitarySysNum)%CoolingCoilSensDemand   = 0.0d0
    UnitarySystem(UnitarySysNum)%CoolingCoilLatentDemand = 0.0d0
  ELSE IF(CoolingLoad .OR. MoistureLoad < 0.0d0)THEN
    UnitarySystem(UnitarySysNum)%HeatingCoilSensDemand   = 0.0d0
    IF(CoolingLoad)THEN
      UnitarySystem(UnitarySysNum)%CoolingCoilSensDemand   = ABS(ZoneLoad)
    ELSE
      UnitarySystem(UnitarySysNum)%CoolingCoilSensDemand   = 0.0d0
    END IF
    UnitarySystem(UnitarySysNum)%CoolingCoilLatentDemand = ABS(MoistureLoad)
  ELSE
    RETURN
  END IF
  CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR, &
                               OnOffAirFlowRatio,SensOutputOff,LatOutputOff,HXUnitOn,CompOn=CompressorONFlag)
  FullSensibleOutput = SensOutputOff
  IF(.NOT. HeatingLoad .AND. .NOT. CoolingLoad) THEN
    ! no load
    IF(MoistureLoad >= 0.0d0 .OR. MoistureLoad > LatOutputOff) RETURN
    ! Dehumcontrol_Multimode only controls RH if there is a sensible load
    IF(UnitarySystem(UnitarySysNum)%DehumidControlType_Num .EQ. DehumidControl_Multimode) RETURN
  END IF
! determine if PLR=0 meets the load
  SELECT CASE (TempControlType(UnitarySystem(UnitarySysNum)%ControlZoneNum))
    CASE(SingleHeatingSetPoint)
      IF(HeatingLoad .AND. SensOutputOff .GT. ZoneLoad .AND. (MoistureLoad >= 0.0d0 .OR. MoistureLoad .GT. LatOutputOff))RETURN
      IF(.NOT. HeatingLoad .AND. (MoistureLoad >= 0.0d0 .OR. MoistureLoad .GT. LatOutputOff))RETURN
    CASE(SingleCoolingSetPoint)
      IF(CoolingLoad .AND. SensOutputOff .LT. ZoneLoad .AND. (MoistureLoad >= 0.0d0 .OR. MoistureLoad .GT. LatOutputOff))RETURN
      IF(.NOT. CoolingLoad .AND. (MoistureLoad >= 0.0d0 .OR. MoistureLoad .GT. LatOutputOff))RETURN
    CASE(SingleHeatCoolSetPoint, DualSetPointWithDeadBand)
      IF(HeatingLoad .AND. SensOutputOff .GT. ZoneLoad .AND. (MoistureLoad >= 0.0d0 .OR. MoistureLoad .GT. LatOutputOff))RETURN
      IF(CoolingLoad .AND. SensOutputOff .LT. ZoneLoad .AND. (MoistureLoad >= 0.0d0 .OR. MoistureLoad .GT. LatOutputOff))RETURN
      IF(.NOT. HeatingLoad .AND. .NOT. CoolingLoad .AND. (MoistureLoad >= 0.0d0 .OR. MoistureLoad .GT. LatOutputOff))RETURN
    CASE DEFAULT
      ! should never get here
  END SELECT
! if a variable speed unit, the SensOutputOff at SpeedNum=1 must be checked to see if it exceeds the ZoneLoad
! This is still no load but at the first speed above idle
  IF(HeatingLoad .AND. UnitarySystem(UnitarySysNum)%NumOfSpeedHeating > 0 .OR. &
     CoolingLoad .AND. UnitarySystem(UnitarySysNum)%NumOfSpeedCooling > 0)THEN
    IF(UnitarySystem(UnitarySysNum)%Staged)THEN
      IF(HeatingLoad)THEN
        UnitarySystem(UnitarySysNum)%HeatingSpeedNum   = UnitarySystem(UnitarySysNum)%StageNum
      ELSE
        UnitarySystem(UnitarySysNum)%CoolingSpeedNum   = ABS(UnitarySystem(UnitarySysNum)%StageNum)
      END IF
    ELSE
      IF(HeatingLoad)THEN
        UnitarySystem(UnitarySysNum)%HeatingSpeedNum   = 1
      ELSE
        UnitarySystem(UnitarySysNum)%CoolingSpeedNum   = 1
      END IF
    END IF
    CALL SetOnOffMassFlowRate(UnitarySysNum, OnOffAirFlowRatio, PartLoadRatio)
    CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR, &
                                 OnOffAirFlowRatio,SensOutputOff,LatOutputOff,HXUnitOn,CompOn=CompressorONFlag)
    FullSensibleOutput = SensOutputOff
    SELECT CASE (TempControlType(UnitarySystem(UnitarySysNum)%ControlZoneNum))
      CASE(SingleHeatingSetPoint)
        IF(HeatingLoad .AND. SensOutputOff .GT. ZoneLoad .AND. (MoistureLoad >= 0.0d0 .OR. MoistureLoad .GT. LatOutputOff))RETURN
        IF(.NOT. HeatingLoad .AND. (MoistureLoad >= 0.0d0 .OR. MoistureLoad .GT. LatOutputOff))RETURN
      CASE(SingleCoolingSetPoint)
        IF(CoolingLoad .AND. SensOutputOff .LT. ZoneLoad .AND. (MoistureLoad >= 0.0d0 .OR. MoistureLoad .GT. LatOutputOff))RETURN
        IF(.NOT. CoolingLoad .AND. (MoistureLoad >= 0.0d0 .OR. MoistureLoad .GT. LatOutputOff))RETURN
      CASE(SingleHeatCoolSetPoint, DualSetPointWithDeadBand)
        IF(HeatingLoad .AND. SensOutputOff .GT. ZoneLoad .AND. (MoistureLoad >= 0.0d0 .OR. MoistureLoad .GT. LatOutputOff))RETURN
        IF(CoolingLoad .AND. SensOutputOff .LT. ZoneLoad .AND. (MoistureLoad >= 0.0d0 .OR. MoistureLoad .GT. LatOutputOff))RETURN
        IF(.NOT. HeatingLoad .AND. .NOT. CoolingLoad .AND. (MoistureLoad >= 0.0d0 .OR. MoistureLoad .GT. LatOutputOff))RETURN
      CASE DEFAULT
      ! should never get here
    END SELECT
  END IF
  PartLoadRatio = 1.0d0  ! Get full load result
  IF(PRESENT(CompOn))THEN
    CompressorONFlag = CompOn
  ELSE
    CompressorONFlag = 1
  END IF
  IF(HeatingLoad)THEN
    CoolPLR       = 0.0d0
    HeatPLR       = 1.0d0
    UnitarySystem(UnitarySysNum)%HeatingSpeedRatio = 1.0d0
    UnitarySystem(UnitarySysNum)%HeatingCycRatio = 1.0d0
    UnitarySystem(UnitarySysNum)%WSHPRuntimeFrac   = HeatPLR
    UnitarySystem(UnitarySysNum)%HeatingSpeedNum = UnitarySystem(UnitarySysNum)%NumOfSpeedHeating
    IF (UnitarySystem(UnitarySysNum)%Staged .AND. UnitarySystem(UnitarySysNum)%StageNum > 0) THEN
      UnitarySystem(UnitarySysNum)%HeatingSpeedNum = MIN(UnitarySystem(UnitarySysNum)%StageNum, &
                                                         UnitarySystem(UnitarySysNum)%NumOfSpeedHeating)
      CALL SetOnOffMassFlowRate(UnitarySysNum, OnOffAirFlowRatio, PartLoadRatio)
      UnitarySystem(UnitarySysNum)%HeatingSpeedRatio = 0.0d0
      CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR, &
                         OnOffAirFlowRatio,SensOutputOff,LatOutputOff,HXUnitOn,CompOn=CompressorONFlag)
      IF(SensOutputOff .GT. ZoneLoad)RETURN
      UnitarySystem(UnitarySysNum)%HeatingSpeedRatio = 1.0d0
    END IF
  ELSEIF(CoolingLoad .OR. MoistureLoad < LatOutputOff)THEN
    CoolPLR       = 1.0d0
    HeatPLR       = 0.0d0
    UnitarySystem(UnitarySysNum)%CoolingSpeedRatio = 1.0d0
    UnitarySystem(UnitarySysNum)%CoolingCycRatio   = 1.0d0
    UnitarySystem(UnitarySysNum)%WSHPRuntimeFrac   = CoolPLR
    UnitarySystem(UnitarySysNum)%CoolingSpeedNum = UnitarySystem(UnitarySysNum)%NumOfSpeedCooling
    IF (UnitarySystem(UnitarySysNum)%Staged .AND. UnitarySystem(UnitarySysNum)%StageNum < 0) THEN
      UnitarySystem(UnitarySysNum)%CoolingSpeedNum = MIN(ABS(UnitarySystem(UnitarySysNum)%StageNum), &
                                                         UnitarySystem(UnitarySysNum)%NumOfSpeedCooling)
      CALL SetOnOffMassFlowRate(UnitarySysNum, OnOffAirFlowRatio, PartLoadRatio)
      UnitarySystem(UnitarySysNum)%CoolingSpeedRatio = 0.0d0
      CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR, &
                         OnOffAirFlowRatio,SensOutputOff,LatOutputOff,HXUnitOn,CompOn=CompressorONFlag)
      IF(SensOutputOff .LT. ZoneLoad)RETURN
      UnitarySystem(UnitarySysNum)%CoolingSpeedRatio = 1.0d0
    END IF
  ELSE
    ! will return here when no cooling or heating load and MoistureLoad > LatOutputOff (i.e., PLR=0)
    RETURN
  END IF
  CALL SetOnOffMassFlowRate(UnitarySysNum, OnOffAirFlowRatio, PartLoadRatio)
  CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR, &
                         OnOffAirFlowRatio,SensOutputOn,LatOutputOn,HXUnitOn,CompOn=CompressorONFlag)
  FullSensibleOutput = SensOutputOn
  ! turn on HX if DehumidControl_Multimode
  IF(UnitarySystem(UnitarySysNum)%DehumidControlType_Num .EQ. DehumidControl_Multimode .AND. &
     MoistureLoad < 0.0d0 .AND. MoistureLoad < LatOutputOn .AND. CoolingLoad)THEN
    HXUnitOn = .TRUE.
    CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR, &
                         OnOffAirFlowRatio,SensOutputOn,LatOutputOn,HXUnitOn,CompOn=CompressorONFlag)
    FullSensibleOutput = SensOutputOn
  END IF
  ! test to see if full capacity is less than load, if so set to PLR=1 and RETURN if no moisture load
  IF(HeatingLoad .AND. UnitarySystem(UnitarySysNum)%NumOfSpeedHeating .LE. 1 .OR. &
     CoolingLoad .AND. UnitarySystem(UnitarySysNum)%NumOfSpeedCooling .LE. 1)THEN
  SELECT CASE (TempControlType(UnitarySystem(UnitarySysNum)%ControlZoneNum))
    CASE(SingleHeatingSetPoint)
      IF(HeatingLoad .AND. SensOutputOn .LT. ZoneLoad)THEN
        UnitarySystem(UnitarySysNum)%HeatingPartLoadFrac = 1.0d0
        UnitarySystem(UnitarySysNum)%WSHPRuntimeFrac     = 1.0d0
        IF(MoistureLoad >= 0.0d0 .OR. (MoistureLoad < 0.0d0 .AND. MoistureLoad < LatOutputOn))RETURN
      END IF
      IF(.NOT. HeatingLoad .AND. &
         (MoistureLoad >= 0.0d0 .OR. (MoistureLoad < 0.0d0 .AND. MoistureLoad < LatOutputOn)))RETURN
    CASE(SingleCoolingSetPoint)
      IF(CoolingLoad .AND. SensOutputOn .GT. ZoneLoad)THEN
        UnitarySystem(UnitarySysNum)%CoolingPartLoadFrac = 1.0d0
        UnitarySystem(UnitarySysNum)%WSHPRuntimeFrac     = 1.0d0
        IF(MoistureLoad >= 0.0d0 .OR. (MoistureLoad < 0.0d0 .AND. MoistureLoad < LatOutputOn))RETURN
      END IF
      IF(.NOT. CoolingLoad .AND. &
        (MoistureLoad >= 0.0d0 .OR. (MoistureLoad < 0.0d0 .AND. MoistureLoad < LatOutputOn)))RETURN
    CASE(SingleHeatCoolSetPoint, DualSetPointWithDeadBand)
      IF(HeatingLoad .AND. SensOutputOn .LT. ZoneLoad)THEN
        UnitarySystem(UnitarySysNum)%HeatingPartLoadFrac = 1.0d0
        UnitarySystem(UnitarySysNum)%WSHPRuntimeFrac     = 1.0d0
        IF(MoistureLoad >= 0.0d0 .OR. (MoistureLoad < 0.0d0 .AND. MoistureLoad > LatOutputOn))THEN
          RETURN
        END IF
      END IF
      IF(CoolingLoad .AND. SensOutputOn .GT. ZoneLoad)THEN
        UnitarySystem(UnitarySysNum)%CoolingPartLoadFrac = 1.0d0
        UnitarySystem(UnitarySysNum)%WSHPRuntimeFrac     = 1.0d0
        RETURN
      END IF
      IF(.NOT. HeatingLoad .AND. .NOT. CoolingLoad .AND. &
        (MoistureLoad >= 0.0d0 .OR. (MoistureLoad < 0.0d0 .AND. MoistureLoad < LatOutputOn)))THEN
        RETURN
      END IF
  CASE DEFAULT
    ! no other choices for thermostat control
  END SELECT
  END IF
! will find speed for multispeed coils here and then RegulaFalsi on PLR at a fixed speed
! Do the non-variable or non-multispeed coils have a NumOfSpeed = 0 ? We don't need to do this for single speed coils.
! Check to see which speed to meet the load
  UnitarySystem(UnitarySysNum)%HeatingSpeedNum = 0
  UnitarySystem(UnitarySysNum)%CoolingSpeedNum = 0
  IF (.NOT. UnitarySystem(UnitarySysNum)%Staged) THEN
    IF(HeatingLoad)THEN
      DO SpeedNum=1,UnitarySystem(UnitarySysNum)%NumOfSpeedHeating
        CoolPLR       = 0.0d0
        HeatPLR       = 1.0d0
        IF(SpeedNum == 1)THEN
          UnitarySystem(UnitarySysNum)%HeatingSpeedRatio = 0.0d0
        ELSE
          UnitarySystem(UnitarySysNum)%HeatingSpeedRatio = 1.0d0
        END IF
        UnitarySystem(UnitarySysNum)%HeatingCycRatio = 1.0d0
        UnitarySystem(UnitarySysNum)%HeatingSpeedNum = SpeedNum
        CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR, &
                         OnOffAirFlowRatio,SensOutputOn,LatOutputOn,HXUnitOn,CompOn=CompressorONFlag)
        IF(UnitarySystem(UnitarySysNum)%HeatingCoilType_Num /= Coil_HeatingWaterToAirHPVSEquationFit) THEN
          UnitarySystem(UnitarySysNum)%HeatingSpeedRatio = 0.0d0
          UnitarySystem(UnitarySysNum)%HeatingSpeedNum = SpeedNum-1
          IF(UnitarySystem(UnitarySysNum)%HeatingSpeedNum .EQ. 0)THEN
            UnitarySystem(UnitarySysNum)%HeatingCycRatio = 0.0d0
            HeatPLR = 0.0d0
          ELSE
            UnitarySystem(UnitarySysNum)%HeatingCycRatio = 1.0d0
            HeatPLR = 1.0d0
          END IF
          CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR, &
                       OnOffAirFlowRatio,SensOutputOff,LatOutputOff,HXUnitOn,CompOn=CompressorONFlag)
          UnitarySystem(UnitarySysNum)%HeatingSpeedNum = SpeedNum
        END IF
        IF (ZoneLoad <= SensOutputOn) THEN
          EXIT
        END IF
      END DO
    ELSE ! Cooling or moisture load
      DO SpeedNum=1,UnitarySystem(UnitarySysNum)%NumOfSpeedCooling
        CoolPLR       = 1.0d0
        HeatPLR       = 0.0d0
        IF(SpeedNum == 1)THEN
          UnitarySystem(UnitarySysNum)%CoolingSpeedRatio = 0.0d0
        ELSE
          UnitarySystem(UnitarySysNum)%CoolingSpeedRatio = 1.0d0
        END IF
        UnitarySystem(UnitarySysNum)%CoolingCycRatio = 1.0d0
        UnitarySystem(UnitarySysNum)%CoolingSpeedNum = SpeedNum
        CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR,OnOffAirFlowRatio, &
                                     SensOutputOn,LatOutputOn,HXUnitOn,CompOn=CompressorONFlag)
        IF(UnitarySystem(UnitarySysNum)%CoolingCoilType_Num /= Coil_CoolingWaterToAirHPVSEquationFit) THEN
          UnitarySystem(UnitarySysNum)%CoolingSpeedRatio = 0.0d0
          UnitarySystem(UnitarySysNum)%CoolingSpeedNum = SpeedNum-1
          IF(UnitarySystem(UnitarySysNum)%CoolingSpeedNum .EQ. 0)THEN
            UnitarySystem(UnitarySysNum)%CoolingCycRatio = 0.0d0
            CoolPLR = 0.0d0
          ELSE
            UnitarySystem(UnitarySysNum)%CoolingCycRatio = 1.0d0
            CoolPLR = 1.0d0
          END IF
          CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR,OnOffAirFlowRatio, &
                                       SensOutputOff,LatOutputOff,HXUnitOn,CompOn=CompressorONFlag)
          UnitarySystem(UnitarySysNum)%CoolingSpeedNum = SpeedNum
          END IF
        IF (ZoneLoad >= SensOutputOn) THEN
          EXIT
        END IF
      END DO
    END IF
  ELSE ! IF (.NOT. UnitarySystem(UnitarySysNum)%Staged) THEN
  ! Staged control
   IF(HeatingLoad)THEN
      CoolPLR       = 0.0d0
      HeatPLR       = 1.0d0
      SpeedNum = UnitarySystem(UnitarySysNum)%StageNum
      IF(SpeedNum == 1)THEN
        UnitarySystem(UnitarySysNum)%HeatingSpeedRatio = 0.0d0
      ELSE
        UnitarySystem(UnitarySysNum)%HeatingSpeedRatio = 1.0d0
        SpeedNum = MIN(UnitarySystem(UnitarySysNum)%StageNum,UnitarySystem(UnitarySysNum)%NumOfSpeedHeating)
      END IF
      UnitarySystem(UnitarySysNum)%HeatingCycRatio = 1.0d0
      UnitarySystem(UnitarySysNum)%HeatingSpeedNum = SpeedNum
      CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR, &
                         OnOffAirFlowRatio,SensOutputOn,LatOutputOn,HXUnitOn,CompOn=CompressorONFlag)
      IF(UnitarySystem(UnitarySysNum)%HeatingCoilType_Num /= Coil_HeatingWaterToAirHPVSEquationFit) THEN
        UnitarySystem(UnitarySysNum)%HeatingSpeedRatio = 0.0d0
        UnitarySystem(UnitarySysNum)%HeatingSpeedNum = SpeedNum-1
        IF(UnitarySystem(UnitarySysNum)%HeatingSpeedNum .EQ. 0)THEN
          UnitarySystem(UnitarySysNum)%HeatingCycRatio = 0.0d0
          HeatPLR = 0.0d0
        ELSE
          UnitarySystem(UnitarySysNum)%HeatingCycRatio = 1.0d0
          HeatPLR = 1.0d0
        END IF
        CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR, &
                       OnOffAirFlowRatio,SensOutputOff,LatOutputOff,HXUnitOn,CompOn=CompressorONFlag)
        UnitarySystem(UnitarySysNum)%HeatingSpeedNum = SpeedNum
      END IF
      IF (ZoneLoad <= SensOutputOn) THEN
!        EXIT ????????????
      END IF
   ELSE ! Cooling or moisture load
      CoolPLR       = 1.0d0
      HeatPLR       = 0.0d0
      SpeedNum = ABS(UnitarySystem(UnitarySysNum)%StageNum)
      IF(SpeedNum == 1)THEN
        UnitarySystem(UnitarySysNum)%CoolingSpeedRatio = 0.0d0
      ELSE
        UnitarySystem(UnitarySysNum)%CoolingSpeedRatio = 1.0d0
        SpeedNum = MIN(ABS(UnitarySystem(UnitarySysNum)%StageNum),UnitarySystem(UnitarySysNum)%NumOfSpeedCooling)
      END IF
      UnitarySystem(UnitarySysNum)%CoolingCycRatio = 1.0d0
      UnitarySystem(UnitarySysNum)%CoolingSpeedNum = SpeedNum
      CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR,OnOffAirFlowRatio, &
                                   SensOutputOn,LatOutputOn,HXUnitOn,CompOn=CompressorONFlag)
      IF(UnitarySystem(UnitarySysNum)%CoolingCoilType_Num /= Coil_CoolingWaterToAirHPVSEquationFit) THEN
        UnitarySystem(UnitarySysNum)%CoolingSpeedRatio = 0.0d0
        UnitarySystem(UnitarySysNum)%CoolingSpeedNum = SpeedNum-1
        IF(UnitarySystem(UnitarySysNum)%CoolingSpeedNum .EQ. 0)THEN
          UnitarySystem(UnitarySysNum)%CoolingCycRatio = 0.0d0
          CoolPLR = 0.0d0
        ELSE
          UnitarySystem(UnitarySysNum)%CoolingCycRatio = 1.0d0
          CoolPLR = 1.0d0
        END IF
        CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR,OnOffAirFlowRatio, &
                                     SensOutputOff,LatOutputOff,HXUnitOn,CompOn=CompressorONFlag)
        UnitarySystem(UnitarySysNum)%CoolingSpeedNum = SpeedNum
      END IF
      IF (ZoneLoad >= SensOutputOn) THEN
!        EXIT ???????????
      END IF
   END IF
  END IF ! IF (.NOT. UnitarySystem(UnitarySysNum)%Staged) THEN
  FullSensibleOutput = SensOutputOn
  IF(.NOT. HeatingLoad .AND. .NOT. CoolingLoad .AND. (MoistureLoad >= 0.0d0 .OR. MoistureLoad < LatOutputOn))THEN
    ! if no load, or only a moisture load which can't be met at PLR=1, RETURN
    RETURN
  END IF
  ! must test to see if load is bounded by capacity before calling RegulaFalsi
  IF((HeatingLoad .AND. ZoneLoad < SensOutputOn) .OR. (CoolingLoad .AND. ZoneLoad > SensOutputOn))THEN
    IF((HeatingLoad .AND. ZoneLoad > SensOutputOff) .OR. (CoolingLoad .AND. ZoneLoad < SensOutputOff))THEN
      Par(1)  = REAL(UnitarySysNum,r64)
      Par(2)  = 0.0d0  ! FLAG, IF 1.0 then FirstHVACIteration equals TRUE, if 0.0 then FirstHVACIteration equals false
      IF(FirstHVACIteration)Par(2)=1.0d0
      Par(3)  = REAL(UnitarySystem(UnitarySysNum)%FanOpMode,r64)
      Par(4)  = CompressorONFlag ! CompOp
      Par(5)  = ZoneLoad
      Par(6)  = 0.0d0 ! FLAG, 0.0 if heating load, 1.0 IF cooling or moisture load
      IF(CoolingLoad)Par(6)  = 1.0d0
      Par(7)  = 1.0d0 ! FLAG, 0.0 if latent load, 1.0 if sensible load to be met
      Par(8)  = OnOffAirFlowRatio ! Ratio of compressor ON mass flow rate to AVERAGE mass flow rate over time step
      Par(9)  = 0.0d0 ! HXUnitOn is always false for HX
      Par(10) = UnitarySystem(UnitarySysNum)%HeatingPartLoadFrac
!     Tolerance is in fraction of load, MaxIter = 30, SolFalg = # of iterations or error as appropriate
      CALL SolveRegulaFalsi(0.001d0, MaxIter, SolFlag, PartLoadRatio, CalcUnitarySystemLoadResidual, 0.0d0, 1.0d0, Par)
      IF (SolFlag == -1) THEN
        IF(HeatingLoad)THEN
          ! IF iteration limit is exceeded, find tighter boundary of solution and repeat RegulaFalsi
          ! This does cause a problem when coil cannot turn on when OAT < min allowed or scheduled off
          ! If max iteration limit is exceeded, how do we know if the heating coil is operating?
          TempMaxPLR = -0.1d0
          TempSensOutput = SensOutputOff
          DO WHILE((TempSensOutput - ZoneLoad) .LT. 0.0d0 .AND. TempMaxPLR .LT. 1.0d0)
            ! find upper limit of HeatingPLR
            TempMaxPLR = TempMaxPLR + 0.1d0
            ! SUBROUTINE SetSpeedVariables(UnitarySysNum, SensibleLoad, PartLoadRatio)
            CALL SetSpeedVariables(UnitarySysNum, .TRUE., TempMaxPLR)
            CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,TempMaxPLR, &
                                         OnOffAirFlowRatio,TempSensOutput,TempLatOutput,HXUnitOn,CompOn=CompressorONFlag)
          END DO
          TempMinPLR = TempMaxPLR
          DO WHILE((TempSensOutput - ZoneLoad) .GT. 0.0d0 .AND. TempMinPLR .GT. 0.0d0)
            ! pull upper limit of HeatingPLR down to last valid limit (i.e. heat output still exceeds SystemSensibleLoad)
            TempMaxPLR = TempMinPLR
            ! find minimum limit of HeatingPLR
            TempMinPLR = TempMinPLR - 0.01d0
            CALL SetSpeedVariables(UnitarySysNum, .TRUE., TempMinPLR)
            CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,TempMinPLR, &
                                         OnOffAirFlowRatio,TempSensOutput,TempLatOutput,HXUnitOn,CompOn=CompressorONFlag)
          END DO
          ! Now solve again with tighter PLR limits
          CALL SolveRegulaFalsi(0.001d0, MaxIter, SolFlag, HeatPLR, CalcUnitarySystemLoadResidual, TempMinPLR, TempMaxPLR, Par)
          CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR, &
                                       OnOffAirFlowRatio,TempSensOutput,TempLatOutput,HXUnitOn,CompOn=CompressorONFlag)
        ELSEIF(CoolingLoad)THEN
          ! RegulaFalsi may not find cooling PLR when the latent degradation model is used.
          ! IF iteration limit is exceeded, find tighter boundary of solution and repeat RegulaFalsi
          TempMaxPLR = -0.1d0
          TempSysOutput = SensOutputOff
          TempLoad = ZoneLoad
          DO WHILE((TempSysOutput - TempLoad) .GT. 0.0d0 .AND. TempMaxPLR .LT. 1.0d0)
            ! find upper limit of HeatingPLR
            TempMaxPLR = TempMaxPLR + 0.1d0
            CALL SetSpeedVariables(UnitarySysNum, .TRUE., TempMaxPLR)
            CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,TempMaxPLR,HeatPLR, &
                                       OnOffAirFlowRatio,TempSensOutput,TempLatOutput,HXUnitOn,CompOn=CompressorONFlag)
            TempSysOutput = TempSensOutput
          END DO
          TempMinPLR = TempMaxPLR
          DO WHILE((TempSysOutput - TempLoad) .LT. 0.0d0 .AND. TempMinPLR .GT. 0.0d0)
            ! pull upper limit of HeatingPLR DOwn to last valid limit (i.e. heat output still exceeds SystemSensibleLoad)
            TempMaxPLR = TempMinPLR
            ! find minimum limit of HeatingPLR
            TempMinPLR = TempMinPLR - 0.01d0
            CALL SetSpeedVariables(UnitarySysNum, .TRUE., TempMinPLR)
            CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,TempMinPLR,HeatPLR, &
                                         OnOffAirFlowRatio,TempSensOutput,TempLatOutput,HXUnitOn,CompOn=CompressorONFlag)
            TempSysOutput = TempSensOutput
          END DO
          ! Now solve again with tighter PLR limits
          CALL SolveRegulaFalsi(0.001d0, MaxIter, SolFlag, CoolPLR, CalcUnitarySystemLoadResidual, TempMinPLR, TempMaxPLR, Par)
          CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR, &
                                       OnOffAirFlowRatio,TempSensOutput,TempLatOutput,HXUnitOn,CompOn=CompressorONFlag)
        END IF ! IF(HeatingLoad)THEN
        IF (SolFlag == -1) THEN
          IF(ABS(ZoneLoad - TempSensOutput) .GT. SmallLoad)THEN
            IF(UnitarySystem(UnitarySysNum)%MaxIterIndex == 0)THEN
              CALL ShowWarningMessage('Coil control failed to converge for ' &
               //TRIM(UnitarySystem(UnitarySysNum)%UnitarySystemType)//':'//TRIM(UnitarySystem(UnitarySysNum)%Name))
              CALL ShowContinueError('  Iteration limit exceeded in calculating system sensible part-load ratio.')
              CALL ShowContinueErrorTimeStamp('Sensible load to be met = ' &
               //TRIM(TrimSigDigits(ZoneLoad,2))//' (watts), sensible output = ' &
               //TRIM(TrimSigDigits(TempSensOutput,2))//' (watts), and the simulation continues.')
            END IF
            CALL ShowRecurringWarningErrorAtEnd(TRIM(UnitarySystem(UnitarySysNum)%UnitarySystemType)//' "'&
             //TRIM(UnitarySystem(UnitarySysNum)%Name)//'" - Iteration limit exceeded in calculating'// &
             ' sensible part-load ratio error continues. Sensible load statistics:' &
             ,UnitarySystem(UnitarySysNum)%MaxIterIndex,ZoneLoad,ZoneLoad)
          END IF
        ELSEIF (SolFlag == -2) THEN
          IF(UnitarySystem(UnitarySysNum)%RegulaFalsIFailedIndex == 0)THEN
            CALL ShowWarningMessage('Coil control failed for ' &
             //TRIM(UnitarySystem(UnitarySysNum)%UnitarySystemType)//':'//TRIM(UnitarySystem(UnitarySysNum)%Name))
            CALL ShowContinueError('  sensible part-load ratio determined to be outside the range of 0-1.')
            CALL ShowContinueErrorTimeStamp('Sensible load to be met = ' &
            //TRIM(TrimSigDigits(ZoneLoad,2))//' (watts), and the simulation continues.')
          END IF
          CALL ShowRecurringWarningErrorAtEnd(TRIM(UnitarySystem(UnitarySysNum)%UnitarySystemType)//' "'&
           //TRIM(UnitarySystem(UnitarySysNum)%Name)//'" - '// &
           ' sensible part-load ratio out of range error continues. Sensible load statistics:' &
           ,UnitarySystem(UnitarySysNum)%RegulaFalsIFailedIndex,ZoneLoad,ZoneLoad)
        END IF
      ELSEIF (SolFlag == -2) THEN
        IF(UnitarySystem(UnitarySysNum)%RegulaFalsIFailedIndex == 0)THEN
          CALL ShowWarningMessage('Coil control failed for ' &
            //TRIM(UnitarySystem(UnitarySysNum)%UnitarySystemType)//':'//TRIM(UnitarySystem(UnitarySysNum)%Name))
          CALL ShowContinueError('  sensible part-load ratio determined to be outside the range of 0-1.')
          CALL ShowContinueErrorTimeStamp('Sensible load to be met = ' &
           //TRIM(TrimSigDigits(ZoneLoad,2))//' (watts), and the simulation continues.')
        END IF
        CALL ShowRecurringWarningErrorAtEnd(TRIM(UnitarySystem(UnitarySysNum)%UnitarySystemType)//' "'&
        //TRIM(UnitarySystem(UnitarySysNum)%Name)//'" - '// &
        ' sensible part-load ratio out of range error continues. Sensible load statistics:' &
        ,UnitarySystem(UnitarySysNum)%RegulaFalsIFailedIndex,ZoneLoad,ZoneLoad)
      END IF ! IF (SolFlag == -1) THEN
    ELSE ! load is not bounded by capacity. Leave PLR=1 or turn off unit?
      UnitarySystem(UnitarySysNum)%CoolingPartLoadFrac = 0.0d0
      UnitarySystem(UnitarySysNum)%HeatingPartLoadFrac = 0.0d0
      CoolPLR = 0.0d0
      HeatPLR = 0.0d0
      PartLoadRatio = 0.0d0
    END IF ! IF((HeatingLoad .AND. ZoneLoad > SensOutputOff) .OR. (CoolingLoad .AND. ZoneLoad < SensOutputOff))THEN
  END IF ! IF((HeatingLoad .AND. ZoneLoad < SensOutputOn) .OR. (CoolingLoad .AND. ZoneLoad > SensOutputOn))THEN
  IF(HeatingLoad .AND. (UnitarySystem(UnitarySysNum)%MultiSpeedHeatingCoil .OR. &
                        UnitarySystem(UnitarySysNum)%VarSpeedHeatingCoil)) THEN
    IF(UnitarySystem(UnitarySysNum)%HeatingSpeedNum == 1)THEN
      UnitarySystem(UnitarySysNum)%HeatingCycRatio   = PartLoadRatio
      UnitarySystem(UnitarySysNum)%HeatingSpeedRatio = 0.0d0
    ELSE
      UnitarySystem(UnitarySysNum)%HeatingCycRatio   = 1.0d0
      UnitarySystem(UnitarySysNum)%HeatingSpeedRatio = PartLoadRatio
    END IF
    HeatPLR = PartLoadRatio
    CoolPLR = 0.0d0
    UnitarySystem(UnitarySysNum)%CoolingCycRatio   = 0.0d0
    UnitarySystem(UnitarySysNum)%CoolingSpeedRatio = 0.0d0
  ELSEIF(CoolingLoad .AND. (UnitarySystem(UnitarySysNum)%MultiSpeedCoolingCoil .OR. &
                            UnitarySystem(UnitarySysNum)%VarSpeedCoolingCoil))THEN
    IF(UnitarySystem(UnitarySysNum)%CoolingSpeedNum == 1)THEN
      UnitarySystem(UnitarySysNum)%CoolingCycRatio   = PartLoadRatio
      UnitarySystem(UnitarySysNum)%CoolingSpeedRatio = 0.0d0
    ELSE
      UnitarySystem(UnitarySysNum)%CoolingCycRatio   = 1.0d0
      UnitarySystem(UnitarySysNum)%CoolingSpeedRatio = PartLoadRatio
    END IF
    UnitarySystem(UnitarySysNum)%HeatingCycRatio   = 0.0d0
    UnitarySystem(UnitarySysNum)%HeatingSpeedRatio = 0.0d0
    HeatPLR = 0.0d0
    CoolPLR = PartLoadRatio
  ELSE
    HeatPLR = UnitarySystem(UnitarySysNum)%HeatingPartLoadFrac
    CoolPLR = UnitarySystem(UnitarySysNum)%CoolingPartLoadFrac
  END IF
  CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR, &
                               OnOffAirFlowRatio,TempSensOutput,TempLatOutput,HXUnitOn,CompOn=CompressorONFlag)
! FullSensibleOutput is used to set supplemental heater PLR in calling routine
! OnOffAirFlowRatio is used to average air flow between ON and OFF state
  FullSensibleOutput = TempSensOutput
  ! RETURN of the moisture load is met
  IF(MoistureLoad >= 0.0d0 .OR. (MoistureLoad < 0.0d0 .AND. MoistureLoad >= TempLatOutput))RETURN
  ! Multimode does not meet the latent load, only the sensible load with or without HX active
  IF(.NOT. CoolingLoad .AND. UnitarySystem(UnitarySysNum)%DehumidControlType_Num .EQ. DehumidControl_Multimode)RETURN
!  IF(HeatingLoad .AND. UnitarySystem(UnitarySysNum)%DehumidControlType_Num .EQ. DehumidControl_CoolReheat)RETURN
  IF (( UnitarySystem(UnitarySysNum)%DehumidControlType_Num .EQ. DehumidControl_CoolReheat .OR. &
          UnitarySystem(UnitarySysNum)%DehumidControlType_Num .EQ. DehumidControl_Multimode))THEN
    ! find maximum latent output IF not already calculated
    IF(HeatingLoad)THEN
      CoolPLR = 1.0d0
      UnitarySystem(UnitarySysNum)%CoolingPartLoadFrac = 1.0d0
      UnitarySystem(UnitarySysNum)%CoolingSpeedNum = UnitarySystem(UnitarySysNum)%NumOfSpeedCooling
      UnitarySystem(UnitarySysNum)%CoolingSpeedRatio = 1.0d0
      UnitarySystem(UnitarySysNum)%CoolingCycRatio   = 1.0d0
      UnitarySystem(UnitarySysNum)%WSHPRuntimeFrac   = CoolPLR
      IF(UnitarySystem(UnitarySysNum)%CoolingSpeedNum .GT. 0)THEN
        UnitarySystem(UnitarySysNum)%HeatingPartLoadFrac = 0.0d0
        UnitarySystem(UnitarySysNum)%HeatingSpeedNum = 0
        HeatPLR = 0.0d0
        CoolingLoad = .TRUE.
        HeatingLoad = .FALSE.
        UnitarySystem(UnitarySysNum)%HeatingCoilSensDemand = 0.0d0
        UnitarySystem(UnitarySysNum)%CoolingCoilLatentDemand = MoistureLoad
        CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,0.0d0,0.0d0, &
                                   OnOffAirFlowRatio,TempSensOutput,TempLatOutput,HXUnitOn,CompOn=CompressorONFlag)
        CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR, &
                                   OnOffAirFlowRatio,TempSensOutput,LatOutputOn,HXUnitOn,CompOn=CompressorONFlag)
      ELSE
        UnitarySystem(UnitarySysNum)%HeatingCoilSensDemand = 0.0d0
        UnitarySystem(UnitarySysNum)%CoolingCoilLatentDemand = 0.0d0
        CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,0.0d0,0.0d0, &
                                   OnOffAirFlowRatio,TempSensOutput,TempLatOutput,HXUnitOn,CompOn=CompressorONFlag)
        UnitarySystem(UnitarySysNum)%CoolingCoilLatentDemand = MoistureLoad
        CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR, &
                                   OnOffAirFlowRatio,TempSensOutput,LatOutputOn,HXUnitOn,CompOn=CompressorONFlag)
      END IF
    END IF
    IF(UnitarySystem(UnitarySysNum)%DehumidControlType_Num .EQ. DehumidControl_Multimode .AND. &
       MoistureLoad < LatOutputOn)THEN
      HXUnitOn = .TRUE.
      CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR, &
                                   OnOffAirFlowRatio,TempSensOutput,LatOutputOn,HXUnitOn,CompOn=CompressorONFlag)
      FullSensibleOutput = TempSensOutput
    END IF
!    IF ((HeatingLoad .AND. MoistureLoad < TempLatOutput) .OR. &
!        (CoolingLoad .AND. MoistureLoad < TempLatOutput .AND. MoistureLoad > LatOutputOn) .OR. &
!        ((.NOT. HeatingLoad) .AND. (.NOT. CoolingLoad) .AND. MoistureLoad > LatOutputOn)) THEN
    IF ((MoistureLoad < TempLatOutput) .AND. (MoistureLoad > LatOutputOn)) THEN ! bounds check for RegulaFalsi
      ! save heating PLR
      HeatPLR = UnitarySystem(UnitarySysNum)%HeatingPartLoadFrac
      Par(1)  = REAL(UnitarySysNum,r64)
      Par(2)  = 0.0d0  ! FLAG, if 1.0 then FirstHVACIteration equals TRUE, if 0.0 then FirstHVACIteration equals false
      IF(FirstHVACIteration)Par(2)=1.0d0
      Par(3)  = REAL(UnitarySystem(UnitarySysNum)%FanOpMode,r64)
      Par(4)  = CompressorONFlag ! CompOp
      IF(UnitarySystem(UnitarySysNum)%DehumidControlType_Num .EQ. DehumidControl_Multimode)THEN
        Par(5)  = ZoneLoad
        Par(7)  = 1.0d0 ! FLAG, 0.0 if latent load, 1.0 if sensible load to be met
      ELSE
        Par(5)  = MoistureLoad
        Par(7)  = 0.0d0 ! FLAG, 0.0 if latent load, 1.0 if sensible load to be met
      END IF
      Par(6)  = 1.0d0 ! FLAG, 0.0 if heating load, 1.0 if cooling or moisture load
!      IF(HeatingLoad)Par(6)  = 0.0d0
      Par(8)  = OnOffAirFlowRatio ! Ratio of compressor ON mass flow rate to AVERAGE mass flow rate over time step
      IF (HXUnitOn) THEN
        Par(9) = 1.0d0
      ELSE
        Par(9) = 0.0d0
      END IF
      Par(10) = UnitarySystem(UnitarySysNum)%HeatingPartLoadFrac
    ! Tolerance is fraction of load, MaxIter = 30, SolFalg = # of iterations or error as appropriate
      CALL SolveRegulaFalsi(0.001d0, MaxIter, SolFlagLat, PartLoadRatio, CalcUnitarySystemLoadResidual, 0.0d0, 1.0d0, Par)
!      IF (HeatingLoad) THEN
!        UnitarySystem(UnitarySysNum)%HeatingPartLoadFrac = PartLoadRatio
!      ELSE
        UnitarySystem(UnitarySysNum)%CoolingPartLoadFrac = PartLoadRatio
!      END IF
      UnitarySystem(UnitarySysNum)%HeatingPartLoadFrac = HeatPLR
    ELSEIF(MoistureLoad < LatOutputOn .AND. CoolingLoad)THEN
!     Logic below needs further look...what to do if the bounds check for RegulaFalsi fail?
!     I'm not even sure if this should be done.
!     It's wrong anyway, since there won't be a cooling load if multimode (see RETURN about 80 lines up).
      IF(UnitarySystem(UnitarySysNum)%DehumidControlType_Num .NE. DehumidControl_Multimode) THEN
        UnitarySystem(UnitarySysNum)%CoolingPartLoadFrac = 1.0d0
      END IF
    END IF
  END IF
  CoolPLR = UnitarySystem(UnitarySysNum)%CoolingPartLoadFrac
  HeatPLR = UnitarySystem(UnitarySysNum)%HeatingPartLoadFrac
  CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR, &
                               OnOffAirFlowRatio,TempSensOutput,TempLatOutput,HXUnitOn,CompOn=CompressorONFlag)
  IF (SolFlagLat == -1) THEN
    ! RegulaFalsi may not find cooling PLR when the latent degradation model is used.
    ! IF iteration limit is exceeded, find tighter boundary of solution and repeat RegulaFalsi
    TempMaxPLR = -0.1d0
    TempLatOutput = LatOutputOff
    DO WHILE((TempLatOutput - MoistureLoad) .GT. 0.0d0 .AND. TempMaxPLR .LT. 1.0d0)
      ! find upper limit of HeatingPLR
      TempMaxPLR = TempMaxPLR + 0.1d0
      CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,TempMaxPLR,HeatPLR, &
                                   OnOffAirFlowRatio,TempSensOutput,TempLatOutput,HXUnitOn,CompOn=CompressorONFlag)
    END DO
    TempMinPLR = TempMaxPLR
    DO WHILE((TempLatOutput - MoistureLoad) .LT. 0.0 .AND. TempMinPLR .GT. 0.0d0)
      ! pull upper limit of HeatingPLR DOwn to last valid limit (i.e. heat output still exceeds SystemSensibleLoad)
      TempMaxPLR = TempMinPLR
      ! find minimum limit of HeatingPLR
      TempMinPLR = TempMinPLR - 0.01d0
      CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,TempMinPLR,HeatPLR, &
                                   OnOffAirFlowRatio,TempSensOutput,TempLatOutput,HXUnitOn,CompOn=CompressorONFlag)
    END DO
    ! Now solve again with tighter PLR limits
    CALL SolveRegulaFalsi(0.001d0, MaxIter, SolFlagLat, CoolPLR, CalcUnitarySystemLoadResidual, TempMinPLR, TempMaxPLR, Par)
    CALL CalcUnitarySystemToLoad(UnitarySysNum,FirstHVACIteration,CoolPLR,HeatPLR, &
                                 OnOffAirFlowRatio,TempSensOutput,TempLatOutput,HXUnitOn,CompOn=CompressorONFlag)
    IF (SolFlagLat == -1) THEN
      IF(ABS(MoistureLoad - TempLatOutput) .GT. SmallLoad)THEN
        IF(UnitarySystem(UnitarySysNum)%LatMaxIterIndex == 0)THEN
          CALL ShowWarningMessage('Coil control failed to converge for ' &
               //TRIM(UnitarySystem(UnitarySysNum)%UnitarySystemType)//':'//TRIM(UnitarySystem(UnitarySysNum)%Name))
          CALL ShowContinueError('  Iteration limit exceeded in calculating system Latent part-load ratio.')
          CALL ShowContinueErrorTimeStamp('Latent load to be met = ' &
             //TRIM(TrimSigDigits(MoistureLoad,2))//' (watts), Latent output = ' &
             //TRIM(TrimSigDigits(TempLatOutput,2))//' (watts), and the simulation continues.')
        END IF
        CALL ShowRecurringWarningErrorAtEnd(TRIM(UnitarySystem(UnitarySysNum)%UnitarySystemType)//' "'&
          //TRIM(UnitarySystem(UnitarySysNum)%Name)//'" - Iteration limit exceeded in calculating'// &
          ' Latent part-load ratio error continues. Latent load statistics:' &
          ,UnitarySystem(UnitarySysNum)%LatMaxIterIndex,MoistureLoad,MoistureLoad)
      END IF
    ELSEIF (SolFlagLat == -2) THEN
      IF(UnitarySystem(UnitarySysNum)%LatRegulaFalsIFailedIndex == 0)THEN
        CALL ShowWarningMessage('Coil control failed for ' &
              //TRIM(UnitarySystem(UnitarySysNum)%UnitarySystemType)//':'//TRIM(UnitarySystem(UnitarySysNum)%Name))
        CALL ShowContinueError('  Latent part-load ratio determined to be outside the range of 0-1.')
        CALL ShowContinueErrorTimeStamp('Latent load to be met = ' &
           //TRIM(TrimSigDigits(MoistureLoad,2))//' (watts), and the simulation continues.')
      END IF
      CALL ShowRecurringWarningErrorAtEnd(TRIM(UnitarySystem(UnitarySysNum)%UnitarySystemType)//' "'&
        //TRIM(UnitarySystem(UnitarySysNum)%Name)//'" - '// &
        ' Latent part-load ratio out of range error continues. Latent load statistics:' &
        ,UnitarySystem(UnitarySysNum)%LatRegulaFalsIFailedIndex,MoistureLoad,MoistureLoad)
    END IF
  ELSEIF (SolFlagLat == -2) THEN
    IF(UnitarySystem(UnitarySysNum)%LatRegulaFalsIFailedIndex == 0)THEN
      CALL ShowWarningMessage('Coil control failed for ' &
              //TRIM(UnitarySystem(UnitarySysNum)%UnitarySystemType)//':'//TRIM(UnitarySystem(UnitarySysNum)%Name))
      CALL ShowContinueError('  Latent part-load ratio determined to be outside the range of 0-1.')
      CALL ShowContinueErrorTimeStamp('Latent load to be met = ' &
           //TRIM(TrimSigDigits(MoistureLoad,2))//' (watts), and the simulation continues.')
    END IF
    CALL ShowRecurringWarningErrorAtEnd(TRIM(UnitarySystem(UnitarySysNum)%UnitarySystemType)//' "'&
        //TRIM(UnitarySystem(UnitarySysNum)%Name)//'" - '// &
        ' Latent part-load ratio out of range error continues. Latent load statistics:' &
        ,UnitarySystem(UnitarySysNum)%LatRegulaFalsIFailedIndex,MoistureLoad,MoistureLoad)
  END IF
  FullSensibleOutput = TempSensOutput
  CpAir = PsyCpAirFnWTdb(Node(UnitarySystem(UnitarySysNum)%CoolCoilInletNodeNum)%HumRat, &
                         Node(UnitarySystem(UnitarySysNum)%CoolCoilInletNodeNum)%Temp)
  CoolingOnlySensibleOutput = Node(UnitarySystem(UnitarySysNum)%CoolCoilInletNodeNum)%MassFlowRate * CpAir * &
     ((Node(UnitarySystem(UnitarySysNum)%NodeNumOfControlledZone)%Temp-&
      Node(UnitarySystem(UnitarySysNum)%CoolCoilOutletNodeNum)%Temp)- &
      (Node(UnitarySystem(UnitarySysNum)%HeatCoilOutletNodeNum)%Temp-&
      Node(UnitarySystem(UnitarySysNum)%HeatCoilInletNodeNum)%Temp))
  IF(QToHeatSetPt .LT. 0.0d0)THEN
!   Calculate the reheat coil load wrt the heating setpoint temperature. Reheat coil picks up
!   the entire excess sensible cooling (DX cooling coil and impact of outdoor air).
    UnitarySystem(UnitarySysNum)%DehumidInducedHeatingDemandRate = MAX(0.0d0,(CoolingOnlySensibleOutput+QToHeatSetPt))
!   Heating mode and dehumidification is required
  ELSEIF(QToHeatSetPt .GE. 0.0d0)THEN
!   Calculate the reheat coil load as the sensible capacity of the DX cooling coil only. Let
!   the heating coil pick up the load due to outdoor air.
    UnitarySystem(UnitarySysNum)%DehumidInducedHeatingDemandRate = MAX(0.0d0,CoolingOnlySensibleOutput)
  END IF
  RETURN
END SUBROUTINE ControlUnitarySystemOutput
All Procedures
AbortEnergyPlus AbsoluteAirMass ActivateDemandManagers ActivateEMSControls AddBlankKeys addChargesToOperand AddCompSizeTableEntry AddEndUseSubcategory AddError addFootNoteSubTable AddInstruction AddMeter addMonthlyCharge AddMonthlyFieldSetInput AddMonthlyReport AddNeighborInformation AddObjectDefandParse addOperand AddRecordFromSection AddRecordToOutputVariableStructure AddSectionDef AddShadowRelateTableEntry AddSQLiteComponentSizingRecord AddSQLiteComponentSizingRecord AddSQLiteSystemSizingRecord AddSQLiteSystemSizingRecord AddSQLiteZoneSizingRecord AddSQLiteZoneSizingRecord AddTOCEntry AddTOCZoneLoadComponentTable AddToOutputVariableList AddVariablesForMonthlyReport AddVariableSlatBlind AddWindow AdjustAirSetpointsforOpTempCntrl AdjustCBF AdjustCBF AdjustChangeInLoadByEMSControls AdjustChangeInLoadByHowServed AdjustChangeInLoadForLastStageUpperRangeLimit AdjustCoolingSetPointforTempAndHumidityControl adjusthhat AdjustPumpFlowRequestByEMSControls AdjustReportingHourAndMinutes AdjustVBGap AdvanceRootFinder AFECFR AFECOI AFECPD AFECPF AFEDMP AFEDOP AFEDWC AFEELR AFEEXF AFEFAN AFEHEX AFEHOP AFEPLR AFESCR AFESEL AFESOP AFETMU AirflowNetworkVentingControl AirMass AIRMOV AllocateAirflowNetworkData AllocateAirHeatBalArrays AllocateAndInitData AllocateAndSetUpVentReports AllocateCFSStateHourlyData AllocateForCFSRefPointsGeometry AllocateForCFSRefPointsState AllocateHeatBalArrays AllocateLoadComponentArrays AllocateModuleArrays AllocateModuleArrays AllocateSurfaceHeatBalArrays AllocateWeatherData angle_2dvector AnisoSkyViewFactors AnyPlantLoopSidesNeedSim AnyPlantSplitterMixerLacksContinuity AreaPolygon ArgCheck array_to_vector ASHRAETauModel ASHWAT_OffNormalProperties ASHWAT_Solar ASHWAT_Thermal ASSIGNMENT (=) AssignNodeNumber AssignReportNumber AssignResourceTypeNum AssignReverseConstructionNumber AssignVariablePt AttachCustomMeters AttachMeters AuditBranches AUTOTDMA BaseThermalPropertySet_Diffusivity BeginEnvrnInitializeRuntimeLanguage BetweenDates BetweenGlassForcedFlow BetweenGlassShadeForcedFlow BetweenGlassShadeNaturalFlow BisectionMethod BlindBeamBeamTrans BlindOpticsBeam BlindOpticsDiffuse BoreholeResistance BoundValueToNodeMinMaxAvail BoundValueToWithinTwoValues BracketRoot BranchPressureDrop BrentMethod BuildGap BuildKeyVarList Calc4PipeFanCoil Calc_EN673 Calc_ISO15099 CalcActiveTranspiredCollector CalcAggregateLoad CalcAirflowNetworkAirBalance CalcAirflowNetworkCO2Balance CalcAirflowNetworkGCBalance CalcAirflowNetworkHeatBalance CalcAirflowNetworkMoisBalance CalcAirFlowSimple CalcAirLoopSplitter CalcAirMixer CalcAirToAirGenericHeatExch CalcAirToAirPlateHeatExch CalcAirZoneReturnPlenum CalcAirZoneSupplyPlenum CalcAlamdariHammondStableHorizontal CalcAlamdariHammondUnstableHorizontal CalcAlamdariHammondVerticalWall CalcAngleFactorMRT CalcApproximateViewFactors CalcASHRAEDetailedIntConvCoeff CalcASHRAESimpExtConvectCoeff CalcASHRAESimpleIntConvCoeff CalcASHRAEVerticalWall CalcATMixer CalcAwbiHattonHeatedFloor CalcAwbiHattonHeatedWall CalcBasinHeaterPower CalcBasinHeaterPowerForMultiModeDXCoil CalcBeamSolarOnWinRevealSurface CalcBeamSolDiffuseReflFactors CalcBeamSolSpecularReflFactors CalcBeausoleilMorrisonMixedAssistedWall CalcBeausoleilMorrisonMixedOpposingWall CalcBeausoleilMorrisonMixedStableCeiling CalcBeausoleilMorrisonMixedStableFloor CalcBeausoleilMorrisonMixedUnstableCeiling CalcBeausoleilMorrisonMixedUnstableFloor CalcBLASTAbsorberModel CalcBlockenWindward CalcBoilerModel CalcBoilerModel CalcBottomFluxCoefficents CalcBottomSurfTemp CalcBuriedPipeSoil CalcCBF CalcCBF CalcCBVAV CalcCeilingDiffuserInletCorr CalcCeilingDiffuserIntConvCoeff CalcChillerHeaterModel CalcChillerIPLV CalcChillerModel CalcClearRoof CalcCoilUAbyEffectNTU CalcColdestSetPoint CalcComplexWindowOverlap CalcComplexWindowThermal CalcCompSuctionTempResidual CalcCondEntSetPoint CalcConnectionsDrainTemp CalcConnectionsFlowRates CalcConnectionsHeatRecovery CalcConstCOPChillerModel CalcConvCoeffAbsPlateAndWater CalcConvCoeffBetweenPlates CalcCoolBeam CalcCoolTower CalcCoordinateTransformation CalcCoPlanarNess CalcCostEstimate CalcCTGeneratorModel CalcDayltgCoefficients CalcDayltgCoeffsMapPoints CalcDayltgCoeffsRefMapPoints CalcDayltgCoeffsRefPoints CalcDesiccantBalancedHeatExch CalcDesignSpecificationOutdoorAir CalcDesuperheaterHeatingCoil CalcDesuperheaterWaterHeater CalcDetailedHcInForDVModel CalcDetailedSystem CalcDetailedTransSystem CalcDetailFlatFinCoolingCoil CalcDetIceStorLMTDstar CalcDiffTSysAvailMgr CalcDirectAir CalcDirectEvapCooler CalcDirectResearchSpecialEvapCooler CalcDoe2DXCoil CalcDOE2Leeward CalcDOE2Windward CalcDryFinEffCoef CalcDryIndirectEvapCooler CalcDuct CalcDXCoilStandardRating CalcDXHeatingCoil CalcEarthTube CalcEcoRoof CalcEffectiveness CalcEffectiveSHR CalcEffectiveSHR CalcEffectiveSHR CalcEffectiveSHR CalcElecSteamHumidifier CalcElectricBaseboard CalcElectricChillerHeatRecovery CalcElectricChillerModel CalcElectricEIRChillerModel CalcElectricHeatingCoil CalcEmmelRoof CalcEmmelVertical CalcEngineChillerHeatRec CalcEngineDrivenChillerModel CalcEQLOpticalProperty CalcEQLWindowOpticalProperty CalcEQLWindowSHGCAndTransNormal CalcEQLWindowStandardRatings CalcEQLWindowUvalue CalcEquipmentDrainTemp CalcEquipmentFlowRates CalcExhaustAbsorberChillerModel CalcExhaustAbsorberHeaterModel CalcExteriorVentedCavity CalcFisherPedersenCeilDiffuserCeiling CalcFisherPedersenCeilDiffuserFloor CalcFisherPedersenCeilDiffuserWalls CalcFluidHeatExchanger CalcFohannoPolidoriVerticalWall CalcFollowOATempSetPoint CalcFollowSysNodeTempSetPoint CalcFourPipeIndUnit CalcFrameDividerShadow CalcFuelCellAuxHeater CalcFuelCellGeneratorModel CalcFuelCellGenHeatRecovery CalcFurnaceOutput CalcFurnaceResidual CalcGasAbsorberChillerModel CalcGasAbsorberHeaterModel CalcGasCooler CalcGasHeatingCoil CalcGenericDesiccantDehumidifier CalcGoldsteinNovoselacCeilingDiffuserFloor CalcGoldsteinNovoselacCeilingDiffuserWall CalcGoldsteinNovoselacCeilingDiffuserWindow CalcGroundTempSetPoint CalcGroundwaterWell CalcGshpModel CalcGshpModel CalcGTChillerModel CalcHeatBalanceAir CalcHeatBalanceInsideSurf CalcHeatBalanceInsideSurf CalcHeatBalanceOutsideSurf CalcHeatBalanceOutsideSurf CalcHeatBalFiniteDiff CalcHeatBalHAMT CalcHeatPumpWaterHeater CalcHeatTransCoeffAndCoverTemp CalcHfExteriorSparrow CalcHighTempRadiantSystem CalcHighTempRadiantSystemSP CalcHiTurnOffSysAvailMgr CalcHiTurnOnSysAvailMgr CalcHnASHRAETARPExterior CalcHPCoolingSimple CalcHPHeatingSimple CalcHPWHDXCoil CalcHWBaseboard CalcHXAssistedCoolingCoil CalcHXEffectTerm CalcHybridVentSysAvailMgr CalcIBesselFunc CalcICEngineGeneratorModel CalcICEngineGenHeatRecovery CalcIceStorageCapacity CalcIceStorageCharge CalcIceStorageDischarge CalcIceStorageDormant CalcICSSolarCollector CalcIdealCondEntSetPoint CalcIfSetpointMet CalcIndirectAbsorberModel CalcIndirectResearchSpecialEvapCooler CalcInteriorRadExchange CalcInteriorSolarDistribution CalcInteriorSolarOverlaps CalcInteriorWinTransDifSolInitialDistribution CalcISO15099WindowIntConvCoeff CalcKaradagChilledCeiling CalcKBesselFunc CalcKhalifaEq3WallAwayFromHeat CalcKhalifaEq4CeilingAwayFromHeat CalcKhalifaEq5WallsNearHeat CalcKhalifaEq6NonHeatedWalls CalcKhalifaEq7Ceiling CalcLoadCenterThermalLoad CalcLoTurnOffSysAvailMgr CalcLoTurnOnSysAvailMgr CalcLowTempCFloRadiantSystem CalcLowTempCFloRadSysComps CalcLowTempElecRadiantSystem CalcLowTempHydrRadiantSystem CalcLowTempHydrRadSysComps CalcMatrixInverse CalcMcAdams CalcMerkelVariableSpeedTower CalcMicroCHPNoNormalizeGeneratorModel CalcMinIntWinSolidAngs CalcMitchell CalcMixedAirSetPoint CalcMoistureBalanceEMPD CalcMoreNodeInfo CalcMoWITTLeeward CalcMoWITTWindward CalcMSHeatPump CalcMTGeneratorModel CalcMultiSpeedDXCoil CalcMultiSpeedDXCoilCooling CalcMultiSpeedDXCoilHeating CalcMultiStageElectricHeatingCoil CalcMultiStageGasHeatingCoil CalcMultiZoneAverageCoolingSetPoint CalcMultiZoneAverageHeatingSetPoint CalcMultiZoneAverageMaxHumSetPoint CalcMultiZoneAverageMinHumSetPoint CalcMultiZoneMaxHumSetPoint CalcMultiZoneMinHumSetPoint CalcMundtModel CalcNCycSysAvailMgr CalcNewZoneHeatCoolFlowRates CalcNewZoneHeatOnlyFlowRates CalcNodeMassFlows CalcNominalWindowCond CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNusselt CalcNusseltJurges CalcNVentSysAvailMgr CalcOAController CalcOAMassFlow CalcOAMassFlow CalcOAMixer CalcOAOnlyMassFlow CalcOAPretreatSetPoint CalcOAUnitCoilComps CalcObstrMultiplier CalcOptStartSysAvailMgr CalcOtherSideDemand CalcOutdoorAirUnit CalcOutsideAirSetPoint CalcOutsideSurfTemp CalcParallelPIU CalcPassiveExteriorBaffleGap CalcPassiveSystem CalcPassiveTranspiredCollector CalcPerSolarBeam CalcPipeHeatTransCoef CalcPipesHeatTransfer CalcPipeTransBeam CalcPlantValves CalcPollution CalcPolyhedronVolume CalcPolynomCoef CalcPondGroundHeatExchanger CalcPredictedHumidityRatio CalcPredictedSystemLoad CalcPTUnit CalcPumps CalcPurchAirLoads CalcPurchAirMinOAMassFlow CalcPurchAirMixedAir CalcPVTcollectors CalcQiceChargeMaxByChiller CalcQiceChargeMaxByITS CalcQiceDischageMax CalcRABFlowSetPoint CalcRackSystem CalcRadSysHXEffectTerm CalcRadTemp CalcRainCollector CalcReformEIRChillerModel CalcResearchSpecialPartLoad CalcReturnAirPath CalcRfFlrCoordinateTransformation CalcSandiaPV CalcSatVapPressFromTemp CalcSchedOffSysAvailMgr CalcSchedOnSysAvailMgr CalcSchedSysAvailMgr CalcScheduledDualSetPoint CalcScheduledSetPoint CalcScreenTransmittance CalcScriptF CalcSeriesPIU CalcSetpointTempTarget CalcSHRUserDefinedCurves CalcSimpleController CalcSimpleHeatingCoil CalcSimplePV CalcSingleSpeedEvapFluidCooler CalcSingleSpeedTower CalcSingZoneClSetPoint CalcSingZoneHtSetPoint CalcSingZoneMaxHumSetPoint CalcSingZoneMinHumSetPoint CalcSingZoneRhSetPoint CalcSkySolDiffuseReflFactors CalcSolarCollector CalcSolarFlux CalcSolidDesiccantDehumidifier CalcSourceFlux CalcSourceTempCoefficents CalcSparrowLeeward CalcSparrowWindward CalcSpecialDayTypes CalcStandAloneERV CalcStandardRatings CalcStaticProperties CalcSteamAirCoil CalcSteamBaseboard CalcSurfaceCentroid CalcSurfaceGroundHeatExchanger CalcSystemEnergyUse CalcSZOneStageCoolingSetPt CalcSZOneStageHeatingSetPt CalcTankTemp CalcTDDTransSolAniso CalcTDDTransSolHorizon CalcTDDTransSolIso CalcTempDistModel CalcTempIntegral CalcTESCoilChargeOnlyMode CalcTESCoilCoolingAndChargeMode CalcTESCoilCoolingAndDischargeMode CalcTESCoilCoolingOnlyMode CalcTESCoilDischargeOnlyMode CalcTESCoilOffMode CalcTESIceStorageTank CalcTESWaterStorageTank CalcThermalChimney CalcThermalComfortAdaptiveASH55 CalcThermalComfortAdaptiveCEN15251 CalcThermalComfortFanger CalcThermalComfortKSU CalcThermalComfortPierce CalcThermalComfortSimpleASH55 CalcTimeNeeded CalcTopFluxCoefficents CalcTopSurfTemp CalcTotalFLux CalcTotCapSHR CalcTotCapSHR_VSWSHP CalcTransAbsorProduct CalcTransRefAbsOfCover CalcTRNSYSPV CalcTrombeWallIntConvCoeff CalcTwoSpeedDXCoilIEERResidual CalcTwoSpeedDXCoilStandardRating CalcTwoSpeedEvapFluidCooler CalcTwoSpeedTower CalcUAIce CalcUCSDCV CalcUCSDDV CalcUCSDUE CalcUCSDUI CalculateAirChillerSets CalculateBasisLength CalculateCase CalculateCoil CalculateCompressors CalculateCondensers CalculateCTFs CalculateDailySolarCoeffs CalculateDayOfWeek CalculateEpsFromNTUandZ CalculateExponentialMatrix CalculateFuncResults CalculateGammas CalculateInverseMatrix CalculateMoodyFrictionFactor CalculateNTUfromEpsAndZ CalculatePollution CalculateSecondary CalculateSubcoolers CalculateSunDirectionCosines CalculateTransCompressors CalculateWalkIn CalculateWaterUseage CalculateWaterUseage CalculateWindowBeamProperties CalculateZoneMRT CalculateZoneVolume CalcUnitaryCoolingSystem CalcUnitaryHeatingSystem CalcUnitarySuppHeatingSystem CalcUnitarySuppSystemtoSP CalcUnitarySystemLoadResidual CalcUnitarySystemToLoad CalcUnitHeater CalcUnitHeaterComponents CalcUnitVentilator CalcUnitVentilatorComponents CalcUnmetPlantDemand CalcUpdateHeatRecovery CalcUpdateHeatRecovery CalcUserDefinedInsideHcModel CalcUserDefinedOutsideHcModel CalcVariableSpeedTower CalcVarSpeedCoilCooling CalcVarSpeedCoilHeating CalcVarSpeedHeatPump CalcVarSpeedHeatPump CalcVAVVS CalcVentilatedSlab CalcVentilatedSlabComps CalcVentilatedSlabRadComps CalcVentSlabHXEffectTerm CalcVerticalGroundHeatExchanger CalcViewFactorToShelf CalcVRF CalcVRFCondenser CalcVRFCoolingCoil CalcVSTowerApproach CalcWallCoordinateTransformation CalcWaltonStableHorizontalOrTilt CalcWaltonUnstableHorizontalOrTilt CalcWarmestSetPoint CalcWarmestSetPointTempFlow CalcWaterMainsTemp CalcWaterSource CalcWaterStorageTank CalcWaterThermalTankMixed CalcWaterThermalTankStratified CalcWaterThermalTankZoneGains CalcWaterToAirHeatpump CalcWatertoAirHPCooling CalcWatertoAirHPHeating CalcWaterToAirResidual CalcWatertoWaterHPCooling CalcWatertoWaterHPHeating CalcWaterUseZoneGains CalcWetIndirectEvapCooler CalcWindowACOutput CalcWindowBlindProperties CalcWindowHeatBalance CalcWindowProfileAngles CalcWindowScreenProperties CalcWindowStaticProperties CalcWindPressure CalcWindPressureCoeffs CalcWindTurbine CalcWinFrameAndDividerTemps CalcWinTransDifSolInitialDistribution CalcWrapperModel CalcZoneAirComfortSetpoints CalcZoneAirTempSetpoints CalcZoneComponentLoadSums CalcZoneDehumidifier CalcZoneEvaporativeCoolerUnit CalcZoneLeavingConditions CalcZoneMassBalance CalcZonePipesHeatGain CalcZoneSums CartesianPipeCellInformation_ctor CellType_IsFieldCell CFSHasControlledShade CFSNGlz CFSRefPointPosFactor CFSRefPointSolidAngle CFSShadeAndBeamInitialization CFSUFactor cGetCoilAirOutletNode cGetCoilSteamInletNode cGetCoilSteamOutletNode CharPreDefTableEntry CheckActuatorNode CheckAndAddAirNodeNumber CheckAndFixCFSLayer CheckAndReadCustomSprectrumData CheckAndReadFaults CheckAndSetConstructionProperties CheckBracketRoundOff CheckBranchForOASys CheckCachedIPErrors CheckCFSStates CheckCoilWaterInletNode CheckControllerListOrder CheckControllerLists CheckConvexity CheckCostEstimateInput CheckCreatedZoneItemName CheckCurveLimitsForIPLV CheckCurveLimitsForStandardRatings CheckDayScheduleValueMinMax CheckDXCoolingCoilInOASysExists CheckFDSurfaceTempLimits CheckFFSchedule CheckFluidPropertyName CheckForActualFileName CheckForBalancedFlow CheckForControllerWaterCoil CheckForGeometricTransform CheckForGeometricTransform CheckForMisMatchedEnvironmentSpecifications CheckForOutOfRangeTempResult CheckForOutOfRangeTemps CheckForRequestedReporting CheckForRunawayPlantTemps CheckForSensorAndSetpointNode CheckGasCoefs CheckHeatingCoilSchedule CheckHXAssistedCoolingCoilSchedule CheckIFAnyEMS CheckIFAnyIdealCondEntSetPoint CheckIfAnyPlant CheckIfNodeSetpointManagedByEMS CheckIncrementRoundOff CheckInternalConsistency CheckLightsReplaceableMinMaxForZone CheckLocationValidity CheckLoopExitNode CheckLowerUpperBracket CheckMarkedNodes CheckMaxActiveController CheckMaxConstraint CheckMicroCHPThermalBalance CheckMinActiveController CheckMinConstraint checkMinimumMonthlyCharge CheckMinMaxCurveBoundaries CheckMinMaxRange CheckModelBoundOutput_HumRat CheckModelBoundOutput_Temp CheckModelBounds CheckModelBoundsHumRatEq CheckModelBoundsRH_HumRatEq CheckModelBoundsRH_TempEq CheckModelBoundsTempEq CheckNodeConnections CheckNodeSetPoint CheckNonSingularity CheckOAControllerName CheckOutAirNodeNumber CheckPlantConvergence CheckPlantMixerSplitterConsistency CheckPlantOnAbort CheckPollutionMeterReporting CheckRefrigerationInput CheckReportVariable CheckRootFinderCandidate CheckRootFinderConvergence CheckScheduledSurfaceGains CheckScheduleValue CheckScheduleValueMinMax Checksetpoints CheckSimpleController CheckSlope CheckSteamCoilSchedule CheckSubSurfaceMiscellaneous CheckSysSizing CheckSystemBranchFlow CheckTDDsAndLightShelvesInDaylitZones CheckThisAirSystemForSizing CheckThisZoneForSizing CheckThreading CheckUniqueNodes CheckUnitarySysCoilInOASysExists CheckUsedConstructions CheckValidSimulationObjects CheckWarmupConvergence CheckWaterCoilSchedule CheckWeatherFileValidity CheckWindowShadingControlFrameDivider CheckZoneEquipmentList CheckZoneSizing CHKBKS CHKGSS CHKSBS CLIP CLIPPOLY CloseDFSFile CloseMiscOpenFiles CloseMoistureBalanceEMPD CloseOutOpenFiles CloseOutputFiles CloseOutputTabularFile CloseReportIllumMaps CloseSocket CloseWeatherFile CoilAreaFracIter CoilCompletelyDry CoilCompletelyWet CoilOutletStreamCondition CoilPartWetPartDry COMMAND_ARGUMENT_COUNT CompactObjectsCheck CompareTwoVectors ComplexFenestrationLuminances ComputeDelayedComponents ComputeDifSolExcZonesWIZWindows ComputeIntSolarAbsorpFactors ComputeIntSWAbsorpFactors ComputeIntThermalAbsorpFactors ComputeLifeCycleCostAndReport ComputeLoadComponentDecayCurve ComputeNominalUwithConvCoeffs ComputePresentValue ComputeTariff ComputeTaxAndDepreciation ComputeWinShadeAbsorpFactors CondOutTempResidual ConstructBasis ControlCBVAVOutput ControlCompOutput ControlCompOutput ControlCoolBeam ControlCoolingSystem ControlCycWindACOutput ControlDesiccantDehumidifier ControlDXHeatingSystem ControlDXSystem ControlFluidHeatExchanger ControlHeatingSystem ControlHumidifier ControlMSHPOutput ControlPTUnitOutput ControlPVTcollector ControlReformEIRChillerModel ControlSuppHeatSystem ControlUnitarySystemOutput ControlUnitarySystemtoLoad ControlUnitarySystemtoSP ControlVRF ControlVSEvapUnitToMeetLoad ControlVSHPOutput ControlVSHPOutput ConvectionFactor ConvertCasetoLower ConvertCasetoUpper ConvertIP ConvertIPdelta ConvertToElementTag ConvertToEscaped CoolBeamResidual CoolingCoil CoolWaterHumRatResidual CoolWaterTempResidual CoolWatertoAirHPHumRatResidual CoolWatertoAirHPTempResidual CorrectZoneAirTemp CorrectZoneContaminants CorrectZoneHumRat CostInfoOut CPCW CPHW CreateBoundaryList CreateBoundaryListCount CreateCategoryNativeVariables CreateCellArray CreateCurrentDateTimeString CreateDefaultComputation CreateEnergyReportStructure CreateFCfactorConstructions CreateHVACStepFullString CreateHVACTimeIntervalString CreateHVACTimeString CreateNewellAreaVector CreateNewellSurfaceNormalVector CreatePartitionCenterList CreatePartitionRegionList CreatePredefinedMonthlyReports CreateRegionList CreateRegionListCount CreateShadedWindowConstruction CreateSQLiteConstructionsTable CreateSQLiteConstructionsTable CreateSQLiteDatabase CreateSQLiteDatabase CreateSQLiteDaylightMap CreateSQLiteDaylightMap CreateSQLiteDaylightMapTitle CreateSQLiteDaylightMapTitle CreateSQLiteEnvironmentPeriodRecord CreateSQLiteEnvironmentPeriodRecord CreateSQLiteErrorRecord CreateSQLiteErrorRecord CreateSQLiteInfiltrationTable CreateSQLiteInfiltrationTable CreateSQLiteMaterialsTable CreateSQLiteMaterialsTable CreateSQLiteMeterDictionaryRecord CreateSQLiteMeterDictionaryRecord CreateSQLiteMeterRecord CreateSQLiteMeterRecord CreateSQLiteNominalBaseboardHeatTable CreateSQLiteNominalBaseboardHeatTable CreateSQLiteNominalElectricEquipmentTable CreateSQLiteNominalElectricEquipmentTable CreateSQLiteNominalGasEquipmentTable CreateSQLiteNominalGasEquipmentTable CreateSQLiteNominalHotWaterEquipmentTable CreateSQLiteNominalHotWaterEquipmentTable CreateSQLiteNominalLightingTable CreateSQLiteNominalLightingTable CreateSQLiteNominalOtherEquipmentTable CreateSQLiteNominalOtherEquipmentTable CreateSQLiteNominalPeopleTable CreateSQLiteNominalPeopleTable CreateSQLiteNominalSteamEquipmentTable CreateSQLiteNominalSteamEquipmentTable CreateSQLiteReportVariableDataRecord CreateSQLiteReportVariableDataRecord CreateSQLiteReportVariableDictionaryRecord CreateSQLiteReportVariableDictionaryRecord CreateSQLiteRoomAirModelTable CreateSQLiteRoomAirModelTable CreateSQLiteSchedulesTable CreateSQLiteSimulationsRecord CreateSQLiteSimulationsRecord CreateSQLiteStringTableRecord CreateSQLiteSurfacesTable CreateSQLiteSurfacesTable CreateSQLiteTabularDataRecords CreateSQLiteTabularDataRecords CreateSQLiteTimeIndexRecord CreateSQLiteTimeIndexRecord CreateSQLiteVentilationTable CreateSQLiteVentilationTable CreateSQLiteZoneGroupTable CreateSQLiteZoneGroupTable CreateSQLiteZoneListTable CreateSQLiteZoneListTable CreateSQLiteZoneTable CreateSQLiteZoneTable CreateStormWindowConstructions CreateSysTimeIntervalString CreateTCConstructions CreateTimeIntervalString CreateTimeString CreatExtBooundCondName CreateZoneExtendedOutput CreateZoneExtendedOutput CrossProduct CrossProduct cSurfaceClass CTRANS CurveValue DateToString DateToStringWithMonth DaylghtAltAndAzimuth DayltgAveInteriorReflectance DayltgClosestObstruction DayltgCrossProduct DayltgCurrentExtHorizIllum DayltgDirectIllumComplexFenestration DayltgDirectSunDiskComplexFenestration DayltgElecLightingControl DayltgExtHorizIllum DayltgGlare DayltgGlarePositionFactor DayltgGlareWithIntWins DayltgHitBetWinObstruction DayltgHitInteriorObstruction DayltgHitObstruction DayltgInteriorIllum DayltgInteriorMapIllum DayltgInteriorTDDIllum DayltgInterReflectedIllum DayltgInterReflectedIllumComplexFenestration DayltgInterReflIllFrIntWins DayltgLuminousEfficacy DayltgPierceSurface DayltgSetupAdjZoneListsAndPointers DayltgSkyLuminance DayltgSurfaceLumFromSun dCheckScheduleValueMinMax1 dCheckScheduleValueMinMax2 DeallocateLoadComponentArrays DebugRootFinder DecodeHHMMField DecodeMonDayHrMin DeflectionTemperatures DeflectionWidths DegradF DElightDaylightCoefficients DElightDaylightCoefficients DElightElecLtgCtrl DElightElecLtgCtrl DElightFreeMemory DElightFreeMemory DElightInputGenerator DElightInputGenerator DElightOutputGenerator DElightOutputGenerator DensityCFSFillGas Depth DERIV DetailsForSurfaces DetectOscillatingZoneTemp DetermineAzimuthAndTilt DetermineBranchFlowRequest DetermineBuildingFloorArea DetermineDateTokens DetermineFrequency DetermineIndexGroupFromMeterGroup DetermineIndexGroupKeyFromMeterName DetermineMaxBackSurfaces DetermineMeterIPUnits DetermineMinuteForReporting DeterminePolygonOverlap DetermineShadowingCombinations DetermineSunUpDown DevelopMesh DiffuseAverage DiffuseAverageProfAngGnd DiffuseAverageProfAngSky DisplayMaterialRoughness DisplayNumberandString DisplaySimDaysProgress DisplayString distance DistributeBBElecRadGains DistributeBBRadGains DistributeBBSteamRadGains DistributeHTRadGains DistributePlantLoad DistributePressureOnBranch DistributeTDDAbsorbedSolar DistributeUserDefinedPlantLoad DL_RES_r2 DLAG DOE2DXCoilHumRatResidual DOE2DXCoilHumRatResidual DOE2DXCoilResidual DOE2DXCoilResidual DOE2DXCoilResidual DoEndOfIterationOperations DomainRectangle_Contains DOMakeUPPERCase DoOneTimeInitializations DOSameString DoShadeControl DoStartOfTimeStepInitializations DownInterpolate4HistoryValues DumpAirLoopStatistics DumpCurrentLineBuffer DUMPVD DUMPVR DXCoilCyclingHumRatResidual DXCoilCyclingHumRatResidual DXCoilCyclingResidual DXCoilCyclingResidual DXCoilVarSpeedHumRatResidual DXCoilVarSpeedHumRatResidual DXCoilVarSpeedResidual DXCoilVarSpeedResidual DXFOut DXFOutLines DXFOutWireFrame DXHeatingCoilResidual DXHeatingCoilResidual DXHeatingCoilResidual DynamicClothingModel DynamicExtConvSurfaceClassification DynamicIntConvSurfaceClassification EchoOutActuatorKeyChoices EchoOutInternalVariableChoices EffectiveEPSLB EffectiveEPSLF EIRChillerHeatRecovery EN673ISO10292 EncodeMonDayHrMin EndEnergyPlus EndUniqueNodeCheck EnthalpyResidual epElapsedTime epGetTimeUsed epGetTimeUsedperCall epStartTime epStopTime epSummaryTimes eptime EQLWindowInsideEffectiveEmiss EQLWindowOutsideEffectiveEmiss EQLWindowSurfaceHeatBalance EquationsSolver ERF EstimateHEXSurfaceArea EvalInsideMovableInsulation EvalOutsideMovableInsulation EvaluateAdiabaticSurfaceTemperature EvaluateBasementCellTemperature EvaluateCellNeighborDirections evaluateChargeBlock evaluateChargeSimple EvaluateExpression EvaluateExtHcModels EvaluateFarfieldBoundaryTemperature EvaluateFarfieldCharacteristics EvaluateFieldCellTemperature EvaluateGroundSurfaceTemperature EvaluateIntHcModels EvaluateLoopSetPointLoad EvaluateNeighborCharacteristics evaluateQualify evaluateRatchet EvaluateSoilRhoCp EvaluateStack EvolveParaUCSDCV ExitCalcController ExpandComplexState ExpressAsCashFlows ExtendObjectDefinition ExteriorBCEqns ExternalInterfaceExchangeVariables ExternalInterfaceInitializeErlVariable ExternalInterfaceSetErlVariable ExternalInterfaceSetSchedule ExtOrIntShadeNaturalFlow Fabric_EstimateDiffuseProps FACSKY FalsePositionMethod FEQX FI FigureACAncillaries FigureAirEnthalpy FigureAirHeatCap FigureAuxilHeatGasHeatCap FigureBeamSolDiffuseReflFactors FigureBeamSolSpecularReflFactors FigureConstGradPattern FigureDayltgCoeffsAtPointsForSunPosition FigureDayltgCoeffsAtPointsForWindowElements FigureDayltgCoeffsAtPointsSetupForWindow FigureElectricalStorageZoneGains FigureFuelCellZoneGains FigureFuelEnthalpy FigureFuelHeatCap FigureGaseousWaterEnthalpy FigureHeightPattern FigureHXleavingGasHeatCap FigureInverterZoneGains FigureLHVofFuel FigureLiquidWaterEnthalpy FigureLiquidWaterHeatCap FigureMapPointDayltgFactorsToAddIllums FigureMicroCHPZoneGains FigureNDheightInZone FigurePowerConditioningLosses FigureProductGasesEnthalpy FigureProductGasHeatCap FigureRefPointDayltgFactorsToAddIllums FigureRefrigerationZoneGains FigureSolarBeamAtTimestep FigureSunCosines FigureSurfMapPattern FigureTDDZoneGains FigureTransformerZoneGains FigureTransientConstraints FigureTwoGradInterpPattern FILJAC FillBasisElement FillDefaultsSWP FillRemainingPredefinedEntries FillWeatherPredefinedEntries film filmg filmi filmPillar FILSKY FinalizeCFS FinalizeCFSLAYER FinalRateCoils FindAirLoopBranchConnection FindAirPlantCondenserLoopFromBranchList FindAllNumbersinList FindArrayIndex FindCompSPInput FindCompSPLoad FindCondenserLoopBranchConnection FindControlledZoneIndexFromSystemNodeNumberForZone FindDeltaTempRangeInput FindDemandSideMatch FindEMSVariable FindFirstLastPtr FindFirstRecord FindGlycol FindHXDemandSideLoopFlow FindInBasis FindItem FindIteminList FindIteminSortedList FindItemInVariableList FindLoopSideInCallingOrder FindNextRecord FindNonSpace FindNumberinList FindOAMixerMatchForOASystem FindPlantLoopBranchConnection FindRangeBasedOrUncontrolledInput FindRangeVariable FindRefrigerant FindRootSimpleController FindStratifiedTankSensedTemp FindTariffIndex FindTDDPipe FindUnitNumber FinishDebugOutputFiles FixViewFactors FluidCellInformation_ctor FM_BEAM FM_DIFF FM_F FNU forcedventilation FourPipeInductionUnitHasMixer FourPipeIUCoolingResidual FourPipeIUHeatingResidual FRA FrostControl FrostControlSetPointLimit FrostControlSetPointLimit FuelCellProductGasEnthResidual FUN FuncDetermineCoolantWaterExitTemp FuncDetermineCWMdotForInternalFlowControl FuncDetermineEngineTemp FV GasElecHeatingCoilResidual GASSES90 GassesLow GatherBEPSResultsForTimestep GatherBinResultsForTimestep GatherComponentLoadsHVAC GatherComponentLoadsIntGain GatherComponentLoadsSurfAbsFact GatherComponentLoadsSurface GatherForEconomics GatherForPredefinedReport GatherHeatGainReport GatherMonthlyResultsForTimestep GatherPeakDemandForTimestep GatherSourceEnergyEndUseResultsForTimestep GaussElimination generate_ears GenerateDElightDaylightCoefficients GenerateDElightDaylightCoefficients GeneratorPowerOutput GenericCrack GenOutputVariablesAuditReport Get2DMatrix Get2DMatrixDimensions GET_COMMAND GET_COMMAND_ARGUMENT Get_Environment_Variable GetActualDXCoilIndex GetAirBranchIndex GetAirFlowFlag GetAirflowNetworkInput GetAirHeatBalanceInput GetAirLoopAvailabilityManager GetAirModelDatas GetAirNodeData GetAirPathData GetAngleFactorList GetATMixer GetATMixerOutNode GetATMixerPriNode GetATMixers GetATMixerSecNode GetAttShdSurfaceData GetAverageTempByType GetBaseboardInput GetBaseboardInput GetBasementFloorHeatFlux GetBasementWallHeatFlux GetBLASTAbsorberInput GetBoilerInput GetBoilerInput GetBranchData GetBranchFanTypeName GetBranchFlow GetBranchInput GetBranchList GetBranchListInput GetBuildingData GetCBVAV GetCellWidths GetCellWidthsCount GetChildrenData GetChillerheaterInput GetCoilAirFlowRate GetCoilAirFlowRateVariableSpeed GetCoilAirInletNode GetCoilAirOutletNode GetCoilAvailScheduleIndex GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacityByIndexType GetCoilCapacityVariableSpeed GetCoilCondenserInletNode GetCoilControlNodeNum GetCoilGroupTypeNum GetCoilIndex GetCoilIndex GetCoilIndex GetCoilIndexVariableSpeed GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNodeVariableSpeed GetCoilMaxSteamFlowRate GetCoilMaxWaterFlowRate GetCoilMaxWaterFlowRate GetCoilMaxWaterFlowRate GetCoilObjectTypeNum GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNodeVariableSpeed GetCoilSteamInletNode GetCoilSteamOutletNode GetCoilTypeNum GetCoilWaterInletNode GetCoilWaterInletNode GetCoilWaterOutletNode GetColumnUsingTabs GetComfortSetpoints GetComponentData GetCondFDInput GetConductivityGlycol GetConnectorList GetConnectorListInput GetConstCOPChillerInput GetConstructData GetControlledZoneIndex GetControllerActuatorNodeNum GetControllerInput GetCoolBeams GetCoolingCoilTypeNameAndIndex GetCooltower GetCostEstimateInput GetCrossVentData GetCTGeneratorInput GetCTGeneratorResults GetCurrentHVACTime GetCurrentMeterValue GetCurrentScheduleValue GetCurveCheck GetCurveIndex GetCurveInput GetCurveMinMaxValues GetCurveName GetCurveObjectTypeNum GetCurveType GetCustomMeterInput GetDaylightingParametersDetaild GetDaylightingParametersInput GetDayScheduleIndex GetDemandManagerInput GetDemandManagerListInput GetDensityGlycol GetDesiccantDehumidifierInput GetDesignDayData GetDesignLightingLevelForZone GetDetShdSurfaceData GetDirectAirInput GetDisplacementVentData GetDSTData GetDualDuctInput GetDualDuctOutdoorAirRecircUse GetDuctInput GetDXCoilAirFlow GetDXCoilAvailSchPtr GetDXCoilBypassedFlowFrac GetDXCoilCapFTCurveIndex GetDXCoilIndex GetDXCoilNumberOfSpeeds GetDXCoils GetDXCoolingSystemInput GetDXHeatPumpSystemInput GetEarthTube GetElecReformEIRChillerInput GetElectricBaseboardInput GetElectricChillerInput GetElectricEIRChillerInput GetEMSInput GetEngineDrivenChillerInput GetEnvironmentalImpactFactorInfo GetEvapFluidCoolerInput GetEvapInput GetExhaustAbsorberInput GetExhaustAirInletNode GetExteriorEnergyUseInput GetExtVentedCavityIndex GetExtVentedCavityIndex GetExtVentedCavityTsColl GetExtVentedCavityTsColl GetFanAvailSchPtr GetFanCoilIndex GetFanCoilInletAirNode GetFanCoilMixedAirNode GetFanCoilOutAirNode GetFanCoilReturnAirNode GetFanCoilUnits GetFanCoilZoneInletAirNode GetFanDesignVolumeFlowRate GetFanIndex GetFanIndexForTwoSpeedCoil GetFanInletNode GetFanInput GetFanOutletNode GetFanPower GetFanSpeedRatioCurveIndex GetFanType GetFanVolFlow GetFarfieldTemp GetFirstBranchInletNodeName GetFluidCoolerInput GetFluidDensityTemperatureLimits GetFluidHeatExchangerInput GetFluidPropertiesData GetFluidSpecificHeatTemperatureLimits GetFrameAndDividerData GetFuelCellGeneratorInput GetFuelCellGeneratorResults GetFuelFactorInfo GetFurnaceInput GetGasAbsorberInput GetGeneratorFuelSupplyInput GetGeometryParameters GetGlycolNameByIndex GetGroundheatExchangerInput GetGroundReflectances GetGroundTemps GetGshpInput GetGshpInput GetGTChillerInput GetHeatBalanceInput GetHeatBalHAMTInput GetHeatExchangerObjectTypeNum GetHeatingCoilIndex GetHeatingCoilInput GetHeatingCoilNumberOfStages GetHeatingCoilPLFCurveIndex GetHeatingCoilTypeNum GetHeatReclaimSourceIndex GetHeatRecoveryInput GetHighTempRadiantSystem GetHPCoolingCoilIndex GetHTSubSurfaceData GetHTSurfaceData GetHTSurfExtVentedCavityData GetHumidifierInput GetHVACSingleDuctSysIndex GetHWBaseboardInput GetHXAssistedCoolingCoilInput GetHXCoilAirFlowRate GetHXCoilType GetHXCoilTypeAndName GetHXDXCoilIndex GetHXDXCoilName GetHybridVentilationControlStatus GetHybridVentilationInputs GetICEGeneratorResults GetICEngineGeneratorInput GetIceStorageInput GetIDFRecordsStats GetIndirectAbsorberInput GetIndUnits GetInputEconomicsChargeBlock GetInputEconomicsChargeSimple GetInputEconomicsComputation GetInputEconomicsCurrencyType GetInputEconomicsQualify GetInputEconomicsRatchet GetInputEconomicsTariff GetInputEconomicsVariable GetInputForLifeCycleCost GetInputFuelAndPollutionFactors GetInputLifeCycleCostNonrecurringCost GetInputLifeCycleCostParameters GetInputLifeCycleCostRecurringCosts GetInputLifeCycleCostUseAdjustment GetInputLifeCycleCostUsePriceEscalation GetInputTabularMonthly GetInputTabularPredefined GetInputTabularStyle GetInputTabularTimeBins GetInputViewFactors GetInputViewFactorsbyName GetInputZoneEvaporativeCoolerUnit GetInstantMeterValue GetInternalBranchData GetInternalHeatGainsInput GetInternalVariableValue GetInternalVariableValue GetInternalVariableValueExternalInterface GetInternalVariableValueExternalInterface GetInterpolatedSatProp GetInterpValue GetIntMassSurfaceData GetLastBranchOutletNodeName GetLastWord GetLightWellData GetListOfObjectsInIDD GetListofSectionsinInput GetLocationInfo GetLoopMixer GetLoopSidePumpIndex GetLoopSplitter GetLowTempRadiantSystem GetMaterialData GetMatrixInput getMaxAndSum GetMeteredVariables GetMeterIndex GetMeterResourceType GetMicroCHPGeneratorInput GetMicroCHPGeneratorResults GetMinOATCompressor GetMixerInput GetMixerInput GetMoistureBalanceEMPDInput GetMonthlyCostForResource GetMovableInsulationData GetMSHeatPumpInput GetMTGeneratorExhaustNode GetMTGeneratorInput GetMTGeneratorResults GetMundtData GetNewUnitNumber GetNextEnvironment GetNodeConnectionType GetNodeList GetNodeListsInput GetNodeNums GetNTUforCrossFlowBothUnmixed GetNumberOfSchedules GetNumberOfSurfaceLists GetNumberOfSurfListVentSlab GetNumChildren GetNumMeteredVariables GetNumOAControllers GetNumOAMixers GetNumOASystems GetNumObjectsFound GetNumObjectsInIDD GetNumRangeCheckErrorsFound GetNumSectionsFound GetNumSectionsinInput GetNumSegmentsForHorizontalTrenches GetNumSplitterMixerInConntrList GetOACompListNumber GetOACompName GetOACompType GetOACompTypeNum GetOAControllerInputs GetOAMixerIndex GetOAMixerInletNodeNumber GetOAMixerInputs GetOAMixerMixedNodeNumber GetOAMixerNodeNumbers GetOAMixerReliefNodeNumber GetOAMixerReturnNodeNumber GetOARequirements GetOASysControllerListIndex GetOASysNumCoolingCoils GetOASysNumHeatingCoils GetOASysNumSimpControllers GetOASystemNumber GetObjectDefInIDD GetObjectDefMaxArgs GetObjectItem GetObjectItemfromFile GetObjectItemNum GetOnlySingleNode GetOperationSchemeInput GetOSCData GetOSCMData GetOutAirNodesInput GetOutdoorAirUnitInputs GetOutdoorAirUnitOutAirNode GetOutdoorAirUnitReturnAirNode GetOutdoorAirUnitZoneInletNode GetOutsideAirSysInputs GetOutsideEnergySourcesInput GetParentData GetPipeInput GetPipesHeatTransfer GetPipingSystemsInput GetPIUs GetPlantAvailabilityManager GetPlantInput GetPlantLoopData GetPlantOperationInput GetPlantProfileInput GetPlantSizingInput GetPlantValvesInput GetPollutionFactorInput GetPondGroundHeatExchanger GetPowerManagerInput GetPressureCurveTypeAndIndex GetPressureSystemInput GetPreviousHVACTime GetProjectControlData GetProjectData GetPTUnit GetPTUnitMixedAirNode GetPTUnitOutAirNode GetPTUnitReturnAirNode GetPTUnitZoneInletAirNode GetPumpInput GetPurchasedAir GetPurchasedAirMixedAirHumRat GetPurchasedAirMixedAirTemp GetPurchasedAirOutAirMassFlow GetPurchasedAirReturnAirNode GetPurchasedAirZoneInletAirNode GetPVGeneratorResults GetPVInput GetPVTcollectorsInput GetPVTThermalPowerProduction GetQualityRefrig GetRecordLocations GetRectDetShdSurfaceData GetRectSubSurfaces GetRectSurfaces GetRefrigeratedRackIndex GetRefrigerationInput GetReportVariableInput GetRequiredMassFlowRate GetResidCrossFlowBothUnmixed GetResourceTypeChar GetReturnAirNodeForZone GetReturnAirPathInput GetRoomAirModelParameters GetRunPeriodData GetRunPeriodDesignData GetRuntimeLanguageUserInput GetSatDensityRefrig GetSatEnthalpyRefrig GetSatPressureRefrig GetSatSpecificHeatRefrig GetSatTemperatureRefrig GetScheduledSurfaceGains GetScheduleIndex GetScheduleMaxValue GetScheduleMinValue GetScheduleName GetScheduleType GetScheduleValuesForDay GetSecondaryInletNode GetSecondaryOutletNode GetSetPointManagerInputs GetShadingSurfReflectanceData GetShadowingInput GetShelfInput GetSimpleAirModelInputs GetSimpleShdSurfaceData GetSimpleWatertoAirHPInput GetSingleDayScheduleValues GetSiteAtmosphereData GetSizingParams GetSnowGroundRefModifiers GetSolarCollectorInput GetSpecialDayPeriodData GetSpecificHeatGlycol getSpecificUnitDivider getSpecificUnitIndex getSpecificUnitMultiplier GetSplitterInput GetSplitterInput GetSplitterNodeNumbers GetSplitterOutletNumber GetStandAloneERV GetStandAloneERVNodes GetStandAloneERVOutAirNode GetStandAloneERVReturnAirNode GetStandAloneERVZoneInletAirNode GetStandardMeterResourceType GetSteamBaseboardInput GetSteamCoilAvailScheduleIndex GetSteamCoilControlNodeNum GetSteamCoilIndex GetSteamCoilInput GetSTM GetStormWindowData GetSupHeatDensityRefrig GetSupHeatEnthalpyRefrig GetSupHeatPressureRefrig GetSupplyAirFlowRate GetSupplyAirFlowRate GetSupplyAirInletNode GetSupplyInletNode GetSupplyOutletNode GetSurfaceCountForOSCM GetSurfaceData GetSurfaceGroundHeatExchanger GetSurfaceHeatTransferAlgorithmOverrides GetSurfaceIndecesForOSCM GetSurfaceListsInputs GetSurfHBDataForMundtModel GetSurfHBDataForTempDistModel GetSysAvailManagerInputs GetSysAvailManagerListInputs GetSysInput GetSystemNodeNumberForZone GetSystemSizingInput GetTDDInput GetTESCoilIndex GetTESCoilInput GetThermalChimney GetTowerInput GetTranspiredCollectorIndex GetTranspiredCollectorInput GetTypeOfCoil GetUFADZoneData GetUnitarySystemDXCoolingCoilIndex GetUnitarySystemInput GetUnitarySystemOAHeatCoolCoil GetUnitConversion GetUnitHeaterInput GetUnitsString GetUnitSubString GetUnitVentilatorInput GetUnitVentilatorMixedAirNode GetUnitVentilatorOutAirNode GetUnitVentilatorReturnAirNode GetUnitVentilatorZoneInletAirNode GetUserConvectionCoefficients GetUserDefinedComponents GetUserDefinedOpSchemeInput GetUserDefinedPatternData GetUTSCTsColl GetVariableKeyCountandType GetVariableKeyCountandType GetVariableKeys GetVariableKeys GetVariableTypeAndIndex GetVariableUnitsString GetVarSpeedCoilInput GetVentilatedSlabInput GetVertices GetViscosityGlycol GetVRFInput GetVSCoilCondenserInletNode GetVSCoilMinOATCompressor GetVSCoilNumOfSpeeds GetWaterCoilAvailScheduleIndex GetWaterCoilCapacity GetWaterCoilIndex GetWaterCoilInput GetWaterMainsTemperatures GetWaterManagerInput GetWaterSource GetWaterThermalTankInput GetWatertoAirHPInput GetWatertoWaterHPInput GetWaterUseInput GetWeatherProperties GetWeatherStation GetWindowAC GetWindowACMixedAirNode GetWindowACOutAirNode GetWindowACReturnAirNode GetWindowACZoneInletAirNode GetWindowGapAirflowControlData GetWindowGlassSpectralData GetWindowShadingControlData GetWindTurbineInput GetWrapperInput GetWTGeneratorResults GetZoneAirDistribution GetZoneAirLoopEquipment GetZoneAirSetpoints GetZoneAndZoneListNames GetZoneContaminanInputs GetZoneContaminanSetpoints GetZoneData GetZoneDehumidifierInput GetZoneDehumidifierNodeNumber GetZoneEqAvailabilityManager GetZoneEquipment GetZoneEquipmentData GetZoneEquipmentData1 GetZoneInfilAirChangeRate GetZoneLoads GetZonePlenumInput GetZoneSizingInput GLtoAMB GoAhead guess HasFractionalScheduleValue hatter HCInWindowStandardRatings HConvGap HcUCSDCV HcUCSDDV HcUCSDUF HeatingCoilVarSpeedCycResidual HeatingCoilVarSpeedResidual HeatPumpRunFrac HeatPumpRunFrac HeatPumpRunFrac HeatWatertoAirHPTempResidual Height HEMINT HIC_ASHRAE HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterHeatingCoilResidual HRadPar HTRANS HTRANS0 HTRANS1 HWBaseboardUAResidual HXAssistDXCoilResidual HXAssistedCoolCoilHRResidual HXAssistedCoolCoilHRResidual HXAssistedCoolCoilTempResidual HXAssistedCoolCoilTempResidual HXDemandSideLoopFlowResidual HybridVentilationControl IAM iCheckScheduleValue ICSCollectorAnalyticalSoluton iGetCoilAirOutletNode iGetCoilSteamInletNode iGetCoilSteamOutletNode INCLOS incrementEconVar IncrementInstMeterCache incrementSteps incrementTableEntry InitAirflowNetwork InitAirflowNetworkData InitAirHeatBalance InitAirLoops InitAirLoopSplitter InitAirMixer InitAirTerminalUserDefined InitAirZoneReturnPlenum InitAirZoneSupplyPlenum InitATMixer InitBaseboard InitBaseboard InitBLASTAbsorberModel InitBoiler InitBoiler InitBoreholeHXSimVars InitBSDFWindows InitCBVAV InitCoilUserDefined InitComplexWindows InitComponentNodes InitConductionTransferFunctions InitConnections InitConstCOPChiller InitController InitCoolBeam InitCTGenerators InitCurveReporting InitDaylightingDevices InitDemandManagers InitDesiccantDehumidifier InitDetailedIceStorage InitDirectAir InitDualDuct InitDuct InitDXCoil InitDXCoolingSystem InitDXHeatPumpSystem InitElecReformEIRChiller InitElectricBaseboard InitElectricChiller InitElectricEIRChiller InitEMS InitEMSControlledConstructions InitEMSControlledSurfaceProperties InitEnergyReports InitEngineDrivenChiller InitEquivalentLayerWindowCalculations InitEvapCooler InitEvapFluidCooler InitExhaustAbsorber InitExteriorConvectionCoeff InitFan InitFanCoilUnits InitFluidCooler InitFluidHeatExchanger InitFuelCellGenerators InitFurnace InitGasAbsorber InitGlassOpticalCalculations InitGshp InitGshp InitGTChiller InitHeatBalance InitHeatBalFiniteDiff InitHeatBalHAMT InitHeatingCoil InitHeatRecovery InitHighTempRadiantSystem InitHumidifier InitHWBaseboard InitHXAssistedCoolingCoil InitHybridVentSysAvailMgr InitialInitHeatBalFiniteDiff InitializeCFSDaylighting InitializeCFSStateData InitializeComponentSizingTable InitializeConstructionsTables InitializeDaylightMapTables InitializeEnvironmentPeriodsTable InitializeErrorsTable InitializeGlycolTempLimits InitializeHeatTransferPipes InitializeIndexes InitializeIndexes InitializeLoops InitializeMaterialsTable InitializeMeters initializeMonetaryUnit InitializeNominalBaseboardHeatTable InitializeNominalElectricEquipmentTable InitializeNominalGasEquipmentTable InitializeNominalHotWaterEquipmentTable InitializeNominalInfiltrationTable InitializeNominalLightingTable InitializeNominalOtherEquipmentTable InitializeNominalPeopleTable InitializeNominalSteamEquipmentTable InitializeNominalVentilationTable InitializeOperatingMode InitializeOutput InitializePipes InitializePredefinedMonthlyTitles InitializePsychRoutines InitializePumps InitializeRefrigerantLimits InitializeReportMeterDataDictionaryTable InitializeReportMeterDataTables InitializeReportVariableDataDictionaryTable InitializeReportVariableDataTables InitializeRoomAirModelTable InitializeRootFinder InitializeRuntimeLanguage InitializeSchedulesTable InitializeSimulationsTable InitializeSQLiteTables InitializeSurfacesTable InitializeSystemSizingTable InitializeTabularDataTable InitializeTabularDataTable InitializeTabularDataView InitializeTabularDataView InitializeTabularMonthly InitializeTimeIndicesTable InitializeViews InitializeWeather InitializeZoneGroupTable InitializeZoneInfoTable InitializeZoneListTable InitializeZoneSizingTable InitICEngineGenerators InitIndirectAbsorpChiller InitIndUnit InitInteriorConvectionCoeffs InitInteriorRadExchange InitInternalHeatGains InitIntSolarDistribution InitLoadBasedControl InitLoadDistribution InitLowTempRadiantSystem InitMicroCHPNoNormalizeGenerators InitMoistureBalanceEMPD InitMSHeatPump InitMTGenerators InitMundtModel InitOAController InitOAMixer InitOneTimePlantSizingInfo InitOutAirNodes InitOutdoorAirUnit InitOutsideAirSys InitPipesHeatTransfer InitPipingSystems InitPIU InitPlantProfile InitPlantUserComponent InitPlantValves InitPollutionMeterReporting InitPondGroundHeatExchanger InitPressureDrop InitPTUnit InitPurchasedAir InitPVTcollectors InitRefrigeration InitRefrigerationPlantConnections InitReturnAirPath InitSecretObjects InitSetPointManagers InitSimpleIceStorage InitSimpleMixingConvectiveHeatGains InitSimpleWatertoAirHP InitSimVars InitSimVars InitSimVars InitSimVars InitSolarCalculations InitSolarCollector InitSolarHeatGains InitSolReflRecSurf InitStandAloneERV InitSteamBaseboard InitSteamCoil InitSurfaceGroundHeatExchanger InitSurfaceHeatBalance InitSys InitSysAvailManagers InitSystemOutputRequired InitTempDistModel InitTESCoil InitThermalAndFluxHistories InitThermalComfort InitTower InitTranspiredCollector InitTRNSYSPV InitUCSDCV InitUCSDDV InitUCSDUF InitUniqueNodeCheck InitUnitarySystems InitUnitHeater InitUnitVentilator InitVarSpeedCoil InitVentilatedSlab InitVRF InitWaterCoil InitWaterSource InitWaterThermalTank InitWatertoAirHP InitWatertoWaterHP InitWindowAC InitWindTurbine InitWrapper InitZoneAirLoopEquipment InitZoneAirSetpoints InitZoneAirUserDefined InitZoneContSetpoints InitZoneDehumidifier InitZoneEquipment InitZoneEvaporativeCoolerUnit InPolygon InsertCurrencySymbol int_times_vector INTCPT Integer_IsInRange IntegerIsWithinTwoValues IntegerToString InterConnectTwoPlantLoopSides InteriorBCEqns InteriorNodeEqns InternalRangeCheck InternalSetupTankDemandComponent InternalSetupTankSupplyComponent interp INTERP InterpBlind InterpDefValuesForGlycolConc Interpolate Interpolate_Lagrange InterpolateBetweenFourValues InterpolateBetweenTwoValues InterpolatePipeTransBeam InterpProfAng InterpProfSlatAng InterpretWeatherDataLine InterpSlatAng InterpSw InterpValuesForGlycolConc IntInterfaceNodeEqns IntPreDefTableEntry IntToStr Invert3By3Matrix InvertMatrix InvJulianDay IPTrimSigDigits iRoundSigDigits IS_BEAM IS_DIFF IS_DSRATIO IS_F IS_LWP IS_OPENNESS IS_SWP isCompLoadRepReq IsControlledShade IsConverged_CurrentToPrevIteration IsConverged_PipeCurrentToPrevIteration IsCurveInputTypeValid IsCurveOutputTypeValid isExternalInterfaceErlVariable IsGlazeLayerX IsGZSLayer isInQuadrilateral IsInRange isInTriangle IsLeapYear IsNodeOnSetPtManager IsParentObject IsParentObjectCompSet IsShadingLayer IssueSevereAlphaInputFieldError IssueSevereInputFieldError IssueSevereRealInputFieldError IsValidConnectionType IsVBLayer isWithinRange ITERATE IterateRootFinder iTrimSigDigits JGDate JulianDay LClimb LDSumMax LDSumMean LEEDtariffReporting LimitCoilCapacity LimitController LimitTUCapacity LinesOut linint LoadEquipList LoadInterface LogicalToInteger LogicalToInteger LogPlantConvergencePoints lookupOperator LookUpScheduleValue LookUpSeason LookupSItoIP lubksb LUBKSB ludcmp LUDCMP LUdecomposition LUsolution MakeAnchorName MakeHVACTimeIntervalString MakeMirrorSurface MakeRectangularVertices MakeRelativeRectangularVertices MakeTransition MakeUPPERCase ManageAirflowNetworkBalance ManageAirHeatBalance ManageAirLoops ManageAirModel ManageBranchInput ManageControllers ManageCoolTower ManageDemand ManageEarthTube ManageElectCenterStorageInteractions ManageElectricLoadCenters ManageElectStorInteractions ManageEMS ManageExteriorEnergyUse ManageGeneratorControlState ManageGeneratorFuelFlow ManageHeatBalance ManageHeatBalFiniteDiff ManageHeatBalHAMT ManageHVAC ManageHybridVentilation ManageInsideAdaptiveConvectionAlgo ManageInternalHeatGains ManageInverter ManageMundtModel ManageNonZoneEquipment ManageOutsideAdaptiveConvectionAlgo ManageOutsideAirSystem ManagePlantLoadDistribution ManagePlantLoops ManageRefrigeratedCaseRacks ManageSetPoints ManageSimulation ManageSingleCommonPipe ManageSizing ManageSurfaceHeatBalance ManageSystemAvailability ManageThermalChimney ManageThermalComfort ManageTransformers ManageTwoWayCommonPipe ManageUCSDCVModel ManageUCSDDVModel ManageUCSDUFModels ManageUserDefinedPatterns ManageWater ManageWaterInits ManageWeather ManageZoneAirLoopEquipment ManageZoneAirUpdates ManageZoneContaminanUpdates ManageZoneEquipment MapExtConvClassificationToHcModels MapIntConvClassificationToHcModels MarkNode MatchAndSetColorTextString MatchPlantSys MatrixIndex matrixQBalance MeshPartition_CompareByDimension MeshPartition_SelectionSort MeshPartitionArray_Contains MinePlantStructForInfo MixedAirControlTempResidual ModifyWindow Modulus MonthToMonthNumber MovingAvg MRXINV MSHPCyclingResidual MSHPHeatRecovery MSHPVarSpeedResidual MultiModeDXCoilHumRatResidual MultiModeDXCoilHumRatResidual MultiModeDXCoilResidual MultiModeDXCoilResidual MultiModeDXCoilResidual MultiSpeedDXCoolingCoilStandardRatings MultiSpeedDXHeatingCoilStandardRatings MULTOL MyPlantSizingIndex NeighborInformationArray_Value NETRAD NewEMSVariable NewExpression newPreDefColumn newPreDefReport newPreDefSubTable NEWTON NodeHasSPMCtrlVarType NormalArea NumBranchesInBranchList NumCompsInBranch nusselt NusseltNumber OpenEPlusWeatherFile OPENNESS_LW OpenOutputFiles OpenOutputTabularFile OpenWeatherFile OPERATOR (*) OPERATOR (+) OPERATOR (-) OPERATOR (.dot.) OPERATOR (.twodcross.) OPERATOR (.twoddot.) OPERATOR (/) ORDER OutBaroPressAt OutDewPointTempAt OutDryBulbTempAt OutsidePipeHeatTransCoef OutWetBulbTempAt P01 PanesDeflection ParametricObjectsCheck parseComputeLine ParseExpression ParseStack ParseTime PartLoadFactor PassiveGapNusseltNumber PassPressureAcrossInterface PassPressureAcrossMixer PassPressureAcrossSplitter PD_BEAM PD_BEAM_CASE_I PD_BEAM_CASE_II PD_BEAM_CASE_III PD_BEAM_CASE_IV PD_BEAM_CASE_V PD_BEAM_CASE_VI PD_DIFF PD_LW PD_LWP PD_SWP PerformanceCurveObject PerformanceTableObject PerformIterationLoop PerformPipeCellSimulation PerformPipeCircuitSimulation PerformSolarCalculations PerformTemperatureFieldUpdate PierceSurface PierceSurfaceVector PipeCircuitInfo_InitInOutCells PipeSegmentInfo_InitPipeCells PIUInducesPlenumAir PIUnitHasMixer PlaneEquation PlantHalfLoopSolver PlantMassFlowRatesFunc PLRResidual PLRResidual PLRResidualMixedTank PLRResidualStratifiedTank PMVResidual POLY1F POLY2F POLYF polygon_contains_point_2d popStack pos PostIPProcessing POWER PreDefTableEntry PredictSystemLoads PredictZoneContaminants PreparePipeCircuitSimulation PrepDebugFilesAndVariables PreProcessorCheck PrepVariablesISO15099 PreScanReportingVariables PresProfile PressureCurveValue ProcessDataDicFile ProcessDateString ProcessEMSInput ProcessEPWHeader ProcessForDayTypes ProcessInput ProcessInputDataFile ProcessIntervalFields ProcessMinMaxDefLine ProcessNumber ProcessScheduleInput ProcessSurfaceVertices ProcessTokens ProduceMinMaxString ProduceMinMaxStringWStartMinute ProduceRDDMDD ProfileAngle PropagateResolvedFlow PStack PsyCpAirFnWTdb PsyHfgAirFnWTdb PsyHFnTdbRhPb PsyHFnTdbW PsyHgAirFnWTdb PsyPsatFnTemp PsyPsatFnTemp_raw PsyRhFnTdbRhov PsyRhFnTdbRhovLBnd0C PsyRhFnTdbWPb PsyRhoAirFnPbTdbW PsyRhovFnTdbRh PsyRhovFnTdbRhLBnd0C PsyRhovFnTdbWPb PsyTdbFnHW PsyTdpFnTdbTwbPb PsyTdpFnWPb PsyTsatFnHPb PsyTsatFnPb PsyTwbFnTdbWPb PsyTwbFnTdbWPb_raw PsyVFnTdbWPb PsyWFnTdbH PsyWFnTdbRhPb PsyWFnTdbTwbPb PsyWFnTdpPb psz Pt2Plane PullCompInterconnectTrigger PumpDataForTable PushBranchFlowCharacteristics PushInnerTimeStepArrays pushStack PushSystemTimestepHistories PushSystemTimestepHistories PushZoneTimestepHistories PushZoneTimestepHistories QsortC QsortPartition RadialCellInfo_XY_CrossSectArea RadialCellInformation_ctor RadialSizing_Thickness Rainflow RangeCheck RB_BEAM RB_DIFF RB_F RB_LWP RB_SWP rCheckDayScheduleValueMinMax rCheckScheduleValue rCheckScheduleValueMinMax1 rCheckScheduleValueMinMax2 ReadEnergyMeters ReadEPlusWeatherForDay ReadGeneralDomainInputs ReadHorizontalTrenchInputs ReadINIFile ReadInputLine ReadPipeCircuitInputs ReadPipeSegmentInputs ReadTableData ReadUserWeatherInput ReadWeatherForDay Real_ConstrainTo Real_IsInRange real_times_vector ReAllocateAndPreserveOutputVariablesForSimulation ReallocateIntegerArray ReallocateIVar ReallocateRealArray ReallocateRVar RealPreDefTableEntry RealToStr RecKeepHeatBalance RecordOutput RectangleF_Contains ReformEIRChillerCondInletTempResidual ReformEIRChillerHeatRecovery RegisterNodeConnection RegisterPlantCompDesignFlow RegulateCondenserCompFlowReqOp ReInitPlantLoopsAtFirstHVACIteration RemoveSpaces RemoveTrailingZeros reorder ReplaceBlanksWithUnderscores ReplaceBlanksWithUnderscores ReportAirflowNetwork ReportAirHeatBalance ReportAirLoopConnections ReportAirTerminalUserDefined ReportAndTestGlycols ReportAndTestRefrigerants ReportBaseboard ReportBaseboard ReportCBVAV ReportChillerIPLV ReportCoilUserDefined ReportCompSetMeterVariables ReportController ReportCoolBeam ReportCoolTower ReportCTFs ReportCWTankInits ReportDemandManagerList ReportDesiccantDehumidifier ReportDetailedIceStorage ReportDirectAir ReportDualDuct ReportDualDuctConnections ReportDuct ReportDXCoil ReportDXCoilRating ReportDYMeters ReportEarthTube ReportEconomicVariable ReportElectricBaseboard ReportEMS ReportEvapCooler ReportEvapFluidCooler ReportExteriorEnergyUse ReportFan ReportFanCoilUnit ReportFatalGlycolErrors ReportFatalRefrigerantErrors ReportFiniteDiffInits ReportFluidCooler ReportFluidHeatExchanger ReportForTabularReports ReportFurnace ReportGlass ReportHeatBalance ReportHeatingCoil ReportHeatRecovery ReportHighTempRadiantSystem ReportHRMeters ReportHumidifier ReportHWBaseboard ReportIllumMap ReportingFreqName ReportingThisVariable ReportInternalHeatGains ReportLoopConnections ReportLowTempRadiantSystem ReportMaxVentilationLoads ReportMeterDetails ReportMissing_RangeData ReportMixer ReportMNMeters ReportMoistureBalanceEMPD ReportMSHeatPump ReportNodeConnections ReportOAController ReportOAMixer ReportOrphanFluids ReportOrphanRecordObjects ReportOrphanSchedules ReportOutdoorAirUnit ReportOutputFileHeaders ReportParentChildren ReportPipesHeatTransfer ReportPIU ReportPlantProfile ReportPlantUserComponent ReportPlantValves ReportPondGroundHeatExchanger ReportPTUnit ReportPumps ReportPurchasedAir ReportPV ReportRackSystem ReportRefrigerationComponents ReportReturnAirPath ReportRuntimeLanguage ReportScheduleDetails ReportScheduleValues ReportSizingOutput ReportSMMeters ReportSolarCollector ReportSplitter ReportStandAloneERV ReportStandAloneWaterUse ReportSteamBaseboard ReportSteamCoil ReportSurfaceErrors ReportSurfaceGroundHeatExchngr ReportSurfaceHeatBalance ReportSurfaces ReportSurfaceShading ReportSys ReportSysSizing ReportSystemEnergyUse ReportThermalChimney ReportTowers ReportTSMeters ReportUnitarySystem ReportUnitHeater ReportUnitVentilator ReportVentilatedSlab ReportVRFCondenser ReportVRFTerminalUnit ReportWarmupConvergence ReportWaterCoil ReportWaterManager ReportWaterThermalTank ReportWaterUse ReportWeatherAndTimeInformation ReportWindowAC ReportWindTurbine ReportZoneAirLoopEquipment ReportZoneAirUserDefined ReportZoneDehumidifier ReportZoneEquipment ReportZoneEvaporativeCoolerUnit ReportZoneMeanAirTemp ReportZoneReturnPlenum ReportZoneSizing ReportZoneSupplyPlenum ResetAllPlantInterConnectFlags ResetController ResetEnvironmentCounter ResetHVACControl ResetNodeData ResetPerformanceCurveOutput ResetRootFinder ResetTerminalUnitFlowLimits ResetWeekDaysByMonth Resimulate resist ReSolveAirLoopControllers ResolveAirLoopFlowLimits ResolveLocationInformation ResolveLockoutFlags ResolveLoopFlowVsPressure ResolveParallelFlows ResolveSysFlow ReverseAndRecalculate RevertZoneTimestepHistories RevertZoneTimestepHistories RevisePlantCallingOrder RezeroZoneSizingArrays RhoH2O RHtoVP RKG RoundSigDigits rRoundSigDigits rTrimSigDigits SafeCopyPlantNode SafeDiv SafeDivide SameString SandiaCellTemperature SandiaEffectiveIrradiance SandiaF1 SandiaF2 SandiaImp SandiaIsc SandiaIx SandiaIxx SandiaModuleTemperature SandiaTcellFromTmodule SandiaVmp SandiaVoc SaveSimpleController ScanForReports ScanPlantLoopsForNodeNum ScanPlantLoopsForObject sCheckDayScheduleValueMinMax ScheduleAverageHoursPerWeek SEARCH SearchAscTable SearchWindow5DataFile SecantFormula SecantMethod selectTariff SetActuatedBranchFlowRate SetAdditionalNeighborData SetAllFlowLocks SetAllPlantSimFlagsToValue SetATMixerPriFlow SetATMixerPriFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetCoilDesFlow SetCoilSystemCoolingData SetCoilSystemHeatingDXFlag SetCompFlowRate SetComponentFlowRate SetCurrentWeather SetCurveOutputMinMaxValues SetDSTDateRanges SetDXCoilTypeData SetDXCoolingCoilData SetEquivalentLayerWindowProperties SetErlValueNumber SetExtConvectionCoeff SetFanData SetHeatExchangerData SetHeatToReturnAirFlag SetInitialMeterReportingAndOutputNames SetIntConvectionCoeff SetInternalVariableValue SetMinMax setNativeVariables SetNodeResult SetOAControllerData SetOnOffMassFlowRate SetOnOffMassFlowRate SetOnOffMassFlowRate SetOnOffMassFlowRateVSCoil SetOnOffMassFlowRateVSCoil SetOutAirNodes SetOutBulbTempAt SetPredefinedTables SetSimpleWSHPData SETSKY SetSpecialDayDates SetSpeedVariables SetStormWindowControl SetSurfHBDataForMundtModel SetSurfHBDataForTempDistModel SetSurfTmeanAir SETUP4x4_A SetupAdaptiveConvectionRadiantSurfaceData SetupAdaptiveConvectionStaticMetaData SetupAirLoopControllersTracer SetupAllOutputVariables SetUpAndSort SetupBranchControlTypes SetupCellNeighbors SetupCommonPipes SetupComplexFenestrationMaterialInput SetupComplexFenestrationStateInput SetupComplexWindowStateGeometry SetUpCompSets SetupDElightOutput4EPlus SetupDElightOutput4EPlus SetUpDesignDay SetupEMSActuator SetupEMSIntegerActuator SetupEMSIntegerInternalVariable SetupEMSInternalVariable SetupEMSLogicalActuator SetupEMSRealActuator SetupEMSRealInternalVariable SetupEnvironmentTypes SetupFuelConstituentData SetupGeneratorControlStateManager SetupIndividualControllerTracer SetupInitialPlantCallingOrder SetupIntegerOutputVariable SetupInterpolationValues SetupLoopFlowRequest SetupMeteredVarsForSetPt SetupMundtModel SetupNodeSetpointsAsActuators SetupNodeVarsForReporting SetupOutputVariable SetupPipeCircuitInOutCells SetupPlantEMSActuators SetupPollutionCalculations SetupPollutionMeterReporting SetupPossibleOperators SetupPrimaryAirSystemAvailMgrAsActuators SetupPumpMinMaxFlows SetupRealOutputVariable SetupRealOutputVariable_IntKey SetupReportInput SetupReports SetupRootFinder SetUpSchemeColors SetupShadeSurfacesForSolarCalcs SetupSimpleWindowGlazingSystem SetupSimulation SetupStratifiedNodes SetupSurfaceConstructionActuators SetupSurfaceConvectionActuators SetupSurfaceOutdoorBoundaryConditionActuators SetUpSysSizingArrays SetupTankDemandComponent SetupTankSupplyComponent SetupThermostatActuators SetupTimePointers SetupUnitConversions SetupWeekDaysByMonth SetupWindowShadingControlActuators SetupZoneEquipmentForConvectionFlowRegime SetupZoneGeometry SetupZoneInfoAsInternalDataAvail SetupZoneInternalGain SetupZoneInternalGain SetupZoneSizing SetUpZoneSizingArrays SetUTSCQdotSource SetVarSpeedCoilData SetVentedModuleQdotSource SetVSHPAirFlow SetVSHPAirFlow SetWindSpeedAt SetZoneEquipSimOrder shading shadingedge shadingin SHADOW SharedDVCVUFDataInit SHDBKS SHDGSS SHDRVL SHDSBS shift ShiftPipeTemperaturesForNewIteration ShiftPlantLoopSideCallingOrder ShiftTemperaturesForNewIteration ShiftTemperaturesForNewTimeStep ShowAuditErrorMessage ShowBranchesOnLoop ShowContinueError ShowContinueError ShowContinueErrorTimeStamp ShowContinueErrorTimeStamp ShowErrorMessage ShowErrorMessage ShowFatalError ShowFatalError ShowMessage ShowMessage ShowPsychrometricSummary ShowRecurringContinueErrorAtEnd ShowRecurringContinueErrorAtEnd ShowRecurringErrors ShowRecurringSevereErrorAtEnd ShowRecurringSevereErrorAtEnd ShowRecurringWarningErrorAtEnd ShowRecurringWarningErrorAtEnd ShowSevereError ShowSevereError ShowSevereMessage ShowSevereMessage ShowWarningError ShowWarningError ShowWarningMessage ShowWarningMessage showWarningsBasedOnTotal Sim4PipeFanCoil SimAirChillerSet SimAirLoop SimAirLoopComponent SimAirLoopComponents SimAirLoops SimAirLoopSplitter SimAirMixer SimAirTerminalUserDefined SimAirZonePlenum SimATMixer SimBaseboard SimBLASTAbsorber SimBoiler SimCBVAV SimCBVAV SimCentralGroundSourceHeatPump SimChiller SimCoilUserDefined SimComponentModelFan SimConstVol SimCoolBeam SimCostEstimate SimCTGenerator SimCTPlantHeatRecovery SimCyclingWindowAC SimDesiccantDehumidifier SimDetailedIceStorage SimDirectAir SimDistrictEnergy SimDualDuctConstVol SimDualDuctVarVol SimDualDuctVAVOutdoorAir SimDuct SimDXCoil SimDXCoilMultiMode SimDXCoilMultiSpeed SimDXCoolingSystem SimDXHeatPumpSystem SimElecBaseBoard SimElectricBaseBoard SimElectricConvective SimElectricEIRChiller SimEvapCooler SimEvapFluidCoolers SimExhaustAbsorber SimFanCoilUnit SimFluidCoolers SimFluidHeatExchanger SimFourPipeIndUnit SimFuelCellGenerator SimFuelCellPlantHeatRecovery SimFurnace SimGasAbsorber SimGroundHeatExchangers SimHeatPumpWaterHeater SimHeatRecovery SimHighTempRadiantSystem SimHPWatertoWaterCOOLING SimHPWatertoWaterHEATING SimHPWatertoWaterSimple SimHumidifier SimHVAC SimHWBaseboard SimHWConvective SimHXAssistedCoolingCoil SimICEngineGenerator SimICEPlantHeatRecovery SimIceStorage SimIndirectAbsorber SimIndUnit SimLowTempRadiantSystem SimMicroCHPGenerator SimMicroCHPPlantHeatRecovery SimMSHeatPump SimMSHP SimMTGenerator SimMTPlantHeatRecovery SimMultiSpeedCoils SimOAComponent SimOAController SimOAMixer SimOnOffFan SimOutdoorAirEquipComps SimOutdoorAirUnit SimOutsideAirSys SimOutsideEnergy SimPackagedTerminalUnit SimPipes SimPipesHeatTransfer SimPipingSystemCircuit SimPIU SimPlantEquip SimPlantValves SimpleCoolingCoilUAResidual SimpleEvapFluidCoolerUAResidual SimpleFluidCoolerUAResidual SimpleHeatingCoilUAResidual SimpleTowerApproachResidual SimpleTowerTrResidual SimpleTowerUAResidual SimPondGroundHeatExchanger SimPressureDropSystem SimPTUnit SimPumps SimPurchasedAir SimPVGenerator SimPVTcollectors SimReformulatedEIRChiller SimRefrigCondenser SimReturnAirPath SimSelectedEquipment SimSetPointManagers SimSimpleEvapFluidCooler SimSimpleFan SimSimpleFluidCooler SimSimpleTower SimSolarCollector SimStandAloneERV SimSteamBaseboard SimSteamBoiler SimSteamCoils SimSurfaceGroundHeatExchanger SimSysAvailManager SimTESCoil SimTowers SimTranspiredCollector SimulateAllInteriorRadialSoilSlices SimulateAllLoopSideBranches SimulateAllLoopSidePumps SimulateDemandManagerList SimulateDetailedRefrigerationSystems SimulateDetailedTransRefrigSystems SimulateDualDuct SimulateFanComponents SimulateFluidCell SimulateHeatingCoilComponents SimulateInnerMostRadialSoilSlice SimulateLoopSideBranchGroup SimulateOuterMostRadialSoilSlice SimulatePlantProfile SimulateRadialInsulationCell SimulateRadialPipeCell SimulateRadialToCartesianInterface SimulateSingleDuct SimulateSteamCoilComponents SimulateVRF SimulateWaterCoilComponents SimulateWaterHeaterStandAlone SimulateWaterUse SimulateWaterUseConnection SimUnitaryBypassVAV SimUnitarySystem SimUnitHeater SimUnitVentilator SimUnitVentOAMixer SimUserDefinedPlantComponent SimVariableSpeedCoils SimVariableSpeedHP SimVariableSpeedHP SimVariableTower SimVariableVolumeFan SimVAV SimVAVVS SimVentilatedSlab SimVentSlabOAMixer SimVRF SimVRFCondenserPlant SimWaterCoils SimWaterSource SimWaterThermalTank SimWatertoAirHP SimWatertoAirHPSimple SimWindowAC SimWindTurbine SimZoneAirLoopEquipment SimZoneAirUserDefined SimZoneDehumidifier SimZoneEquipment SimZoneEvaporativeCoolerUnit SimZoneExhaustFan SimZoneOutAirUnitComps SingelSpeedDXCoolingCoilStandardRatings SingleSpeedDXHeatingCoilStandardRatings SingleSpeedFluidCooler SizeAbsorpChiller SizeAirLoopBranches SizeAirLoops SizeBaseboard SizeBoiler SizeBoiler SizeCBVAV SizeConstCOPChiller SizeController SizeCoolBeam SizeDemandSidePlantConnections SizeDirectAir SizeDualDuct SizeDXCoil SizeElecReformEIRChiller SizeElectricBaseboard SizeElectricBaseboard SizeElectricChiller SizeElectricEIRChiller SizeEngineDrivenChiller SizeEvapCooler SizeEvapFluidCooler SizeExhaustAbsorber SizeFan SizeFanCoilUnit SizeFluidCooler SizeFluidHeatExchanger SizeFurnace SizeGasAbsorber SizeGTChiller SizeHeatingCoil SizeHeatRecovery SizeHighTempRadiantSystem SizeHumidifier SizeHVACWaterToAir SizeHWBaseboard SizeIndirectAbsorpChiller SizeIndUnit SizeLowTempRadiantSystem SizeMSHeatPump SizeOAController SizeOutdoorAirUnit SizePIU SizePlantLoop SizePTUnit SizePump SizePurchasedAir SizePVT SizeStandAloneERV SizeStandAloneWaterHeater SizeSteamBaseboard SizeSteamCoil SizeSupplySidePlantConnections SizeSys SizeTankForDemandSide SizeTankForSupplySide SizeTESCoil SizeTower SizeUCSDUF SizeUnitarySystem SizeUnitHeater SizeUnitVentilator SizeVarSpeedCoil SizeVentilatedSlab SizeVRF SizeVRFCondenser SizeVSMerkelTower SizeWaterCoil SizeWaterManager SizeWaterSource SizeWindowAC SizeWrapper SizeZoneDehumidifier SizeZoneEquipment SizeZoneEvaporativeCoolerUnit SkipEPlusWFHeader SkyDifSolarShading SkyGndWeight SkyWeight SLtoAMB SLtoGL SLVSKY solar_EN673 solarISO15099 SolarSprectrumAverage SOLMATS SolveAirLoopControllers SolveForWindowTemperatures SolveRegression SolveRegulaFalsi SolverMoistureBalanceEMPD SOLVZP SortHistory Specular_Adjust Specular_EstimateDiffuseProps Specular_F Specular_OffNormal Specular_RATDiff Specular_SWP SQLiteBegin SQLiteBegin SQLiteBindDouble SQLiteBindInteger SQLiteBindLogicalMacro SQLiteBindNULL SQLiteBindText SQLiteBindTextMacro SQLiteClearBindings SQLiteCloseDatabase SQLiteColumnInt SQLiteColumnIntMacro SQLiteCommit SQLiteCommit SQLiteExecuteCommand SQLiteExecuteCommandMacro SQLiteFinalizeCommand SQLiteOpenDatabase SQLiteOpenDatabaseMacro SQLitePrepareStatement SQLitePrepareStatementMacro SQLiteResetCommand SQLiteStepCommand SQLiteWriteMessage SQLiteWriteMessageMacro SQLiteWriteMessageMacro StandardIndexTypeKey StandardVariableTypeKey StartingWindowTemps StartingWinTempsForNominalCond SteamHeatingCoilResidual StorageType StoreAPumpOnCurrentTempLoop storeIterationResults StoreRecurringErrorMessage StringValue StrToReal SumAllInternalCO2Gains SumAllInternalConvectionGains SumAllInternalGenericContamGains SumAllInternalLatentGains SumAllInternalRadiationGains SumAllReturnAirConvectionGains SumAllReturnAirLatentGains SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumInternalCO2GainsByTypes SumInternalConvectionGainsByTypes SumInternalLatentGainsByTypes SumInternalRadiationGainsByTypes SummarizeErrors SumReturnAirConvectionGainsByTypes SumZoneImpacts SUN3 SUN4 SupSATResidual SurfaceScheduledSolarInc SurveyDemandManagers SystemPropertiesAtLambdaAndPhi SystemSpectralPropertiesAtPhi TableLookupObject TARCOG90 TBND TdbFnHRhPb TDMA TDMA_R TellMeHowManyObjectItemArgs TemperaturesFromEnergy TempIPtoSI TempSItoIP terpld TESCoilHumRatResidual TESCoilResidual TestAirPathIntegrity TestBranchIntegrity TestCompSet TestCompSetInletOutletNodes TestInletOutletNodes TestReturnAirPathIntegrity TestSupplyAirPathIntegrity therm1d TightenNodeMinMaxAvails TimestepInitComplexFenestration TimestepTypeName TraceAirLoopController TraceAirLoopControllers TraceIndividualController TraceIterationStamp TrackAirLoopController TrackAirLoopControllers TRadC TransAndReflAtPhi TransformVertsByAspect TransTDD Triangulate TrimSigDigits TurnOffLoopEquipment TurnOffLoopSideEquipment TurnOffReportRangeCheckErrors TurnOnPlantLoopPipes TurnOnReportRangeCheckErrors TwoSpeedFluidCooler UnitarySystemHeatRecovery UpdateAbsorberChillerComponentGeneratorSide UpdateAirflowNetwork UpdateAirMixer UpdateAirSysCompPtrArray UpdateAirSysSubCompPtrArray UpdateAirSysSubSubCompPtrArray UpdateAirZoneReturnPlenum UpdateAirZoneSupplyPlenum UpdateAnyLoopDemandAlterations UpdateATMixer UpdateBaseboard UpdateBaseboardPlantConnection UpdateBasementSurfaceTemperatures UpdateBBElecRadSourceValAvg UpdateBBRadSourceValAvg UpdateBBSteamRadSourceValAvg UpdateBLASTAbsorberRecords UpdateBoilerRecords UpdateBoilerRecords UpdateBracket UpdateBranchConnections UpdateChillerComponentCondenserSide UpdateChillerheaterRecords UpdateChillerRecords UpdateColdWeatherProtection UpdateCommonPipe UpdateComplexWindows UpdateComponentHeatRecoverySide UpdateConstCOPChillerRecords UpdateController UpdateCoolBeam UpdateCoolTower UpdateCTGeneratorRecords UpdateDataandReport UpdateDemandManagers UpdateDesiccantDehumidifier UpdateDetailedIceStorage UpdateDualDuct UpdateDuct UpdateDXCoil UpdateElectricBaseboard UpdateElectricChillerRecords UpdateElectricEIRChillerRecords UpdateEMSTrendVariables UpdateEngineDrivenChiller UpdateEvapCooler UpdateEvapFluidCooler UpdateEvaporativeCondenserBasinHeater UpdateEvaporativeCondenserWaterUse UpdateExhaustAbsorberCoolRecords UpdateExhaustAbsorberHeatRecords UpdateExhaustAirFlows UpdateFan UpdateFinalSurfaceHeatBalance UpdateFluidCooler UpdateFluidHeatExchanger UpdateFuelCellGeneratorRecords UpdateGasAbsorberCoolRecords UpdateGasAbsorberHeatRecords UpdateGSHPRecords UpdateGSHPRecords UpdateGSHPRecords UpdateGTChillerRecords UpdateHalfLoopInletTemp UpdateHeatBalHAMT UpdateHeatingCoil UpdateHeatRecovery UpdateHighTempRadiantSystem UpdateHistories UpdateHistory UpdateHTRadSourceValAvg UpdateHumidifier UpdateHVACInterface UpdateHWBaseboard UpdateHWBaseboardPlantConnection UpdateIceFractions UpdateICEngineGeneratorRecords UpdateIndirectAbsorberRecords UpdateInternalGainValues UpdateIrrigation UpdateLoadCenterRecords UpdateLoopSideReportVars UpdateLowTempRadiantSystem UpdateMeterReporting UpdateMeters UpdateMeterValues UpdateMicroCHPGeneratorRecords UpdateMinMax UpdateMixedAirSetPoints UpdateMoistureBalanceEMPD UpdateMoistureBalanceFD UpdateMSHeatPump UpdateMTGeneratorRecords UpdateNode UpdateNodeThermalHistory UpdateOAController UpdateOAMixer UpdateOAPretreatSetPoints UpdatePipesHeatTransfer UpdatePipingSystems UpdatePlantLoopInterface UpdatePlantMixer UpdatePlantProfile UpdatePlantSplitter UpdatePlantValves UpdatePondGroundHeatExchanger UpdatePrecipitation UpdatePressureDrop UpdatePurchasedAir UpdatePVTcollectors UpdateRadSysSourceValAvg UpdateRecords UpdateReformEIRChillerRecords UpdateRefrigCondenser UpdateReportWaterSystem UpdateRootFinder UpdateScheduleValues UpdateSetPointManagers UpdateSimpleWatertoAirHP UpdateSoilProps UpdateSolarCollector UpdateSplitter UpdateSQLiteErrorRecord UpdateSQLiteErrorRecord UpdateSQLiteSimulationRecord UpdateSQLiteSimulationRecord UpdateSteamBaseboard UpdateSteamBaseboardPlantConnection UpdateSteamCoil UpdateSurfaceGroundHeatExchngr UpdateSys UpdateSysSizing UpdateSystemOutputRequired UpdateTabularReports UpdateTEStorage UpdateThermalHistories UpdateTowers UpdateTranspiredCollector UpdateUnitarySystemControl UpdateUtilityBills UpdateVarSpeedCoil UpdateVentilatedSlab UpdateVerticalGroundHeatExchanger UpdateVRFCondenser UpdateWaterCoil UpdateWaterConnections UpdateWaterManager UpdateWaterSource UpdateWaterThermalTank UpdateWaterToAirCoilPlantConnection UpdateWatertoAirHP UpdateWeatherData UpdateWholeBuildingRecords UpdateZoneAirLoopEquipment UpdateZoneCompPtrArray UpdateZoneDehumidifier UpdateZoneEquipment UpdateZoneInletConvergenceLog UpdateZoneListAndGroupLoads UpdateZoneSizing UpdateZoneSubCompPtrArray UpdateZoneSubSubCompPtrArray ValidateAndSetSysAvailabilityManagerType ValidateComponent ValidateDistributionSystem ValidateEMSProgramName ValidateEMSVariableName ValidateExhaustFanInput ValidateFlowControlPaths ValidateFuelType ValidateIndexType ValidateMaterialRoughness ValidateMonthDay ValidateNStandardizeMeterTitles ValidateObjectandParse ValidatePipeConstruction ValidatePLFCurve ValidateSection ValidateSectionsInput ValidateVariableType value_to_vector ValueToString VAVVSCoolingResidual VAVVSHCFanOnResidual VAVVSHWFanOnResidual VAVVSHWNoFanResidual VB_CriticalSlatAngle VB_DIFF VB_LWP VB_ShadeControl VB_SLAT_RADIUS_RATIO VB_SOL4 VB_SOL46_CURVE VB_SOL6 VB_SWP vec2d_cross_product vec2d_dot_product vec_cross_product vec_dot_product VecLength VecNegate VecNormalize VecRound VecSquaredLength vector_add vector_div_int vector_div_real vector_subtract vector_times_int vector_times_real vector_to_array VerifyControlledZoneForThermostat VerifyCustomMetersElecPowerMgr VerifyHeatExchangerParent VerifyName VerifySetPointManagers VerifyThermostatInZone VerifyUniqueBaseboardName VerifyUniqueBoilerName VerifyUniqueChillerName VerifyUniqueCoilName ViewFac VisibleSprectrumAverage Volume VRMLOut VSCoilCyclingHumResidual VSCoilCyclingResidual VSCoilCyclingResidual VSCoilSpeedHumResidual VSCoilSpeedResidual VSCoilSpeedResidual VSEvapUnitLoadResidual VSHPCyclingResidual VSHPCyclingResidual VSHPSpeedResidual VSHPSpeedResidual VSMerkelResidual W5InitGlassParameters W5LsqFit W5LsqFit2 W6CoordsFromWorldVect warnIfNativeVarname WetCoilOutletCondition WhichCompSet WhichParentCompSet WhichParentSet Width WindowGapAirflowControl WindowGasConductance WindowGasPropertiesAtTemp WindowHeatBalanceEquations WindowScheduledSolarAbs WindowShadingManager WindowTempsForNominalCond WindSpeedAt Windward WorldVectFromW6 WriteAdaptiveComfortTable WriteAirLoopStatistics WriteBEPSTable WriteCompCostTable WriteComponentSizing WriteCumulativeReportMeterData WriteDaylightMapTitle WriteDemandEndUseSummary WriteInputArguments WriteIntegerData WriteIntegerVariableOutput WriteMeterDictionaryItem WriteModifiedArguments WriteMonthlyTables WriteOutputArguments WriteOutputEN673 WritePoint WritePredefinedTables WriteRealData WriteRealVariableOutput WriteReportHeaders WriteReportIntegerData WriteReportMeterData WriteReportRealData WriteReportVariableDictionaryItem WriteRootFinderStatus WriteRootFinderTrace WriteRootFinderTraceHeader WriteSourceEnergyEndUseSummary writeSubtitle WriteSurfaceShadowing WriteTable WriteTableOfContents WriteTabularLifeCycleCostReport WriteTabularReports WriteTabularTariffReports WriteTARCOGInputFile writeTextLine WriteTimeBinTables WriteTimeStampFormatData WriteTrace WriteVeriSumTable WriteZoneLoadComponentTable WVDC XNormalArea XYRectangle XZRectangle YNormalArea YZRectangle ZeroHVACValues ZNormalArea
Call graph
controlunitarysystemoutput calls showrecurringwarningerroratend, getcurrentschedulevalue, psycpairfnwtdb, setspeedvariables, node, showwarningmessage, setonoffmassflowrate, showcontinueerror, solveregulafalsi, trimsigdigits, tempcontroltype, showcontinueerrortimestamp, calcunitarysystemtoload
getcurrentschedulevalue calls showcontinueerror, showwarningerror
setspeedvariables calls heatpumprunfrac
setonoffmassflowrate calls setaverageairflow
calcunitarysystemtoload calls psycpairfnwtdb, node, setonoffmassflowrate, setaverageairflow, calcunitarycoolingsystem, calcunitarysuppheatingsystem, psyhfntdbw, calcunitaryheatingsystem, simulatefancomponents
showcontinueerror calls showerrormessage, updatesqliteerrorrecord
showwarningerror calls showerrormessage, createsqliteerrorrecord, matchcounts, messagesearch
showerrormessage calls displaystring, showfatalerror
showfatalerror calls showerrormessage, displaystring, abortenergyplus, roundsigdigits, createsqliteerrorrecord
abortenergyplus calls displaystring, roundsigdigits, testairpathintegrity, updatesqlitesimulationrecord, checkmarkednodes, reportairloopconnections, showrecurringerrors, testcompsetinletoutletnodes, summarizeerrors, reportsurfaceerrors, reportloopconnections, closemiscopenfiles, setupnodevarsforreporting, closesocket, closeoutopenfiles, reportsurfaces, testbranchintegrity, checkplantonabort, epelapsedtime, epstoptime, epsummarytimes, showmessage, checknodeconnections
testairpathintegrity calls showcontinueerror, showsevereerror, airtozonenodeinfo, nodeid
showrecurringerrors calls updatesqliteerrorrecord, roundsigdigits, createsqliteerrorrecord, showmessage, removetrailingzeros, recurringerrors
summarizeerrors calls showmessage, matchcounts, summaries, moredetails
closemiscopenfiles calls closedfsfile, closereportillummaps
reportsurfaces calls showwarningerror, detailsforsurfaces, setupschemecolors, vrmlout, scanforreports, dxfoutwireframe, costinfoout, linesout, dxfout
epstoptime calls showfatalerror, tstop
epsummarytimes calls roundsigdigits
showmessage calls showerrormessage
showsevereerror calls showerrormessage, createsqliteerrorrecord, matchcounts, messagesearch
detailsforsurfaces calls trimsigdigits, roundsigdigits, getschedulename, oscm, nominalu, zone, framedivider, getschedulemaxvalue, 2, computenominaluwithconvcoeffs, 3, osc, construct, 4, csurfaceclass, userintconvectioncoeffs, userextconvectioncoeffs, surface, getscheduleminvalue, surfacewindow
setupschemecolors calls showwarningerror, getobjectitemnum, getobjectdefmaxargs, matchandsetcolortextstring, getobjectitem
vrmlout calls showcontinueerror, showwarningerror, showfatalerror, zone, surface, triangulate, getnewunitnumber
dxfoutwireframe calls trimsigdigits, showfatalerror, zone, surface, surfacewindow, getnewunitnumber, zonedaylight, dxfcolorno
costinfoout calls showfatalerror, construct, csurfaceclass, surface, getnewunitnumber
linesout calls showcontinueerror, showwarningerror, showfatalerror, roundsigdigits, csurfaceclass, surface, getnewunitnumber
dxfout calls trimsigdigits, showcontinueerror, showwarningerror, showfatalerror, zone, surface, surfacewindow, triangulate, getnewunitnumber, zonedaylight, dxfcolorno, illummapcalc
computenominaluwithconvcoeffs calls surface
matchandsetcolortextstring calls finditem
triangulate calls showcontinueerror, showwarningerror, roundsigdigits, showmessage, csurfaceclass, generate_ears, calcrfflrcoordinatetransformation, calcwallcoordinatetransformation
generate_ears calls polygon_contains_point_2d, angle_2dvector
setaverageairflow calls getcurrentschedulevalue, node
calcunitarycoolingsystem calls node, heatpumprunfrac, simwatertoairhp, simdxcoilmultimode, simdxcoil, simwatertoairhpsimple, simdxcoilmultispeed, simvariablespeedcoils, simulatewatercoilcomponents, simhxassistedcoolingcoil
calcunitarysuppheatingsystem calls node, solveregulafalsi, simulatewatercoilcomponents, simulatesteamcoilcomponents, simulateheatingcoilcomponents
calcunitaryheatingsystem calls node, heatpumprunfrac, simwatertoairhp, simdxcoil, simwatertoairhpsimple, simdxcoilmultispeed, simvariablespeedcoils, simulatewatercoilcomponents, simulatesteamcoilcomponents, simulateheatingcoilcomponents, showfatalerror, callcoiltypes
controlunitarysystemtoload calls controlunitarysystemoutput
simunitarysystem calls controlunitarysystemtoload