GetCurveInput – EnergyPlusFortran
GetCurveInput Subroutine
1770 statements
Source File
private subroutine GetCurveInput()
Uses:
InputProcessor
DataIPShortCuts
General
Arguments
None
Calls
Called By
Source Code
GetCurveInput
Source Code
SUBROUTINE GetCurveInput
          ! SUBROUTINE INFORMATION:
          !       AUTHOR         Fred Buhl
          !       DATE WRITTEN   May 2000
          !       MODIFIED       January 2006, Rick Strand, added a curve type (quadratic-linear)
          !                      July 2006, L. Gu, added a curve type (bicubic)
          !                      July 2006, BG added triquadratic.
          !                      April 2008, LL Added Linear Curve; July 2008, restructure for easier renaming
          !                      Feb 2009, R. Raustad - FSEC, added exponent curve
          !                      22Aug2010 Craig Wray, added new curves for fan component model:
          !                          FanPressureRise, ExponentialSkewNormal, Sigmoid, RectangularHyperbola1,
          !                          RectangularHyperbola2, ExponentialDecay
          !       RE-ENGINEERED  na
          ! PURPOSE OF THIS SUBROUTINE:
          ! Obtains input data for EnergyPlus equipment performance curves
          ! METHODOLOGY EMPLOYED:
          ! Uses "Get" routines to read in data.
          ! REFERENCES:
          ! na
          ! USE STATEMENTS:
  USE InputProcessor, ONLY: GetNumObjectsFound, GetObjectItem, VerifyName, GetObjectDefMaxArgs, FindItemInList,MakeUPPERcase
  USE DataIPShortCuts  ! Data for field names, blank numerics
  USE General, ONLY: RoundSigDigits
!  USE DataGlobals, ONLY: DisplayExtraWarnings, OutputFileInits
  IMPLICIT NONE    ! Enforce explicit typing of all variables in this routine
          ! SUBROUTINE ARGUMENT DEFINITIONS:
          ! na
          ! SUBROUTINE PARAMETER DEFINITIONS:
          ! na
          ! INTERFACE BLOCK SPECIFICATIONS
          ! na
          ! DERIVED TYPE DEFINITIONS
          ! na
          ! SUBROUTINE LOCAL VARIABLE DECLARATIONS:
INTEGER :: NumBiquad     ! Number of biquadratic curve objects in the input data file
INTEGER :: NumCubic      ! Number of cubic curve objects in the input data file
INTEGER :: NumQuartic    ! Number of quartic (4th order polynomial) objects in the input data file
INTEGER :: NumQuad       ! Number of quadratic curve objects in the input data file
INTEGER :: NumQuadLinear ! Number of quadratic linear curve objects in the input data file
INTEGER :: NumQLinear    ! Number of quad linear curve objects in the input data file
INTEGER :: NumLinear     ! Number of linear curve objects in the input data file
INTEGER :: NumBicubic    ! Number of bicubic curve objects in the input data file
INTEGER :: NumTriQuad    ! Number of triquadratic curve objects in the input file
INTEGER :: NumExponent   ! Number of exponent curve objects in the input file
INTEGER :: NumOneVarTab  ! Number of one variable table objects in the input file
INTEGER :: NumTwoVarTab  ! Number of two variable table objects in the input file
INTEGER :: NumMultVarLookup ! Number of multivariable tables
INTEGER :: NumLookupTables ! total number of one, two, and multivariable tables
INTEGER :: NumFanPressRise ! cpw22Aug2010 Number of fan pressure rise curve objects in the input file
INTEGER :: NumExpSkewNorm  ! cpw22Aug2010 Number of exponential skew normal curve objects in the input file
INTEGER :: NumSigmoid      ! cpw22Aug2010 Number of sigmoid curve objects in the input file
INTEGER :: NumRectHyper1   ! cpw22Aug2010 Number of rectangular hyperbola Type 1 curve objects in the input file
INTEGER :: NumRectHyper2   ! cpw22Aug2010 Number of rectangular hyperbola Type 2 curve objects in the input file
INTEGER :: NumExpDecay     ! cpw22Aug2010 Number of exponential decay curve objects in the input file
INTEGER :: NumDoubleExpDecay     ! ykt July 2011
INTEGER :: NumTables     ! Total tables in the input file
INTEGER :: CurveIndex ! do loop index
INTEGER :: CurveNum   ! current curve number
CHARACTER(len=MaxNameLength), &
                   DIMENSION(13) :: Alphas  ! Alpha items for object
REAL(r64), DIMENSION(10000)        :: Numbers ! Numeric items for object
INTEGER                         :: NumAlphas  ! Number of Alphas for each GetObjectItem call
INTEGER                         :: NumNumbers ! Number of Numbers for each GetObjectItem call
INTEGER                         :: IOStatus   ! Used in GetObjectItem
LOGICAL                         :: ErrorsFound=.false.  ! Set to true if errors in input, fatal at end of routine
LOGICAL                         :: IsNotOK              ! Flag to verify name
LOGICAL                         :: IsBlank              ! Flag for blank name
CHARACTER(len=MaxNameLength) :: CurrentModuleObject  ! for ease in renaming.
INTEGER   :: MaxTableNums=0     ! Maximum number of numeric input fields in Tables
INTEGER   :: MaxTableData=0     ! Maximum number of numeric input field pairs in Tables
INTEGER   :: TotalArgs=0        ! Total number of alpha and numeric arguments (max) for a
                                !   certain object in the input file
INTEGER   :: TableNum=0         ! Index to TableData structure
INTEGER   :: TableDataIndex=0   ! Loop counter for table data
INTEGER   :: NumTableEntries=0  ! Number of data pairs in table data
INTEGER   :: NumXVar
INTEGER   :: NumX2Var
REAL(r64), ALLOCATABLE, DIMENSION(:):: XVar
REAL(r64), ALLOCATABLE, DIMENSION(:):: X2Var
INTEGER :: VarIndex
INTEGER :: TempVarIndex
INTEGER :: TempVarIndex1
REAL(r64) :: MinTableData
REAL(r64) :: MaxTableDataValue
INTEGER   :: NextXVar
LOGICAL :: FoundNewData
Real(r64), ALLOCATABLE, DIMENSION(:) :: TempArray1
Real(r64), ALLOCATABLE, DIMENSION(:) :: TempArray2
Real(r64), ALLOCATABLE, DIMENSION(:) :: TempArray3
CHARACTER(len=MaxNameLength) :: FileName  ! name of external table data file
INTEGER,EXTERNAL   :: GetNewUnitNumber
LOGICAL            :: ReadFromFile       ! True if external data file exists
INTEGER :: CurveFound
! Find the number of each type of curve (note: Current Module object not used here, must rename manually)
NumBiQuad     = GetNumObjectsFound('Curve:Biquadratic')
NumCubic      = GetNumObjectsFound('Curve:Cubic')
NumQuartic    = GetNumObjectsFound('Curve:Quartic')
NumQuad       = GetNumObjectsFound('Curve:Quadratic')
NumQLinear    = GetNumObjectsFound('Curve:QuadLinear')
NumQuadLinear = GetNumObjectsFound('Curve:QuadraticLinear')
NumLinear     = GetNumObjectsFound('Curve:Linear')
NumBicubic    = GetNumObjectsFound('Curve:Bicubic')
NumTriQuad    = GetNumObjectsFound('Curve:Triquadratic')
NumExponent   = GetNumObjectsFound('Curve:Exponent')
NumMultVarLookup = GetNumObjectsFound('Table:MultiVariableLookup')
NumFanPressRise = GetNumObjectsFound('Curve:FanPressureRise')       !cpw22Aug2010
NumExpSkewNorm  = GetNumObjectsFound('Curve:ExponentialSkewNormal') !cpw22Aug2010
NumSigmoid      = GetNumObjectsFound('Curve:Sigmoid')               !cpw22Aug2010
NumRectHyper1   = GetNumObjectsFound('Curve:RectangularHyperbola1') !cpw22Aug2010
NumRectHyper2   = GetNumObjectsFound('Curve:RectangularHyperbola2') !cpw22Aug2010
NumExpDecay     = GetNumObjectsFound('Curve:ExponentialDecay')      !cpw22Aug2010
NumDoubleExpDecay=GetNumObjectsFound('Curve:DoubleExponentialDecay') !ykt July 2011
NumOneVarTab  = GetNumObjectsFound('Table:OneIndependentVariable')
NumTwoVarTab  = GetNumObjectsFound('Table:TwoIndependentVariables')
NumCurves     = NumBiQuad + NumCubic + NumQuad + NumQuadLinear + NumLinear + NumBicubic &
              + NumTriQuad + NumExponent + NumQuartic + NumOneVarTab + NumTwoVarTab + NumMultVarLookup &
              + NumFanPressRise + NumExpSkewNorm + NumSigmoid + NumRectHyper1 & !cpw22Aug2010
              + NumRectHyper2 + NumExpDecay + NumDoubleExpDecay + NumQLinear
! intermediate count for one and two variable performance tables
NumTables     = NumOneVarTab + NumTwoVarTab
! final count for all tables
NumLookupTables = NumOneVarTab + NumTwoVarTab + NumMultVarLookup
IF(NumLookupTables .GT. 0)ALLOCATE(TableLookup(NumLookupTables))
IF(NumOneVarTab .GT. 0)THEN
  CALL GetObjectDefMaxArgs('Table:OneIndependentVariable',TotalArgs,NumAlphas,NumNumbers)
  MaxTableNums=MAX(MaxTableNums,NumNumbers)
  MaxTableData=MAX(MaxTableData,MaxTableNums)
END IF
IF(NumTwoVarTab .GT. 0)THEN
  CALL GetObjectDefMaxArgs('Table:TwoIndependentVariables',TotalArgs,NumAlphas,NumNumbers)
  MaxTableNums=MAX(MaxTableNums,NumNumbers)
  MaxTableData=MAX(MaxTableData,MaxTableNums)
END IF
! allocate the data structure
ALLOCATE(PerfCurve(NumCurves))
ALLOCATE(PerfCurveTableData(NumLookupTables))
ALLOCATE(TableData(NumLookupTables))
ALLOCATE(TempTableData(NumTables))
ALLOCATE(Temp2TableData(NumTables))
! initialize the array
CurveNum=0
! Loop over biquadratic curves and load data
CurrentModuleObject='Curve:Biquadratic'
DO CurveIndex=1,NumBiQuad
  CALL GetObjectItem(CurrentModuleObject,CurveIndex,Alphas,NumAlphas,Numbers,NumNumbers,IOStatus,     &
                NumBlank=lNumericFieldBlanks,AlphaFieldnames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
  CurveNum = CurveNum+1
  IsNotOK=.FALSE.
  IsBlank=.FALSE.
  CALL VerifyName(Alphas(1),PerfCurve%Name,CurveNum-1,IsNotOK,IsBlank,TRIM(CurrentModuleObject)//' Name')
  IF (IsNotOK) THEN
    ErrorsFound=.true.
    IF (IsBlank) Alphas(1)='xxxxx'
  ENDIF
  ! Need to verify that this name isn't used in Pressure Curves as well.
  IF (NumPressureCurves > 0) THEN
    CurveFound=FindItemInList(Alphas(1),PressureCurve%Name,NumPressureCurves)
    IF (CurveFound /= 0) THEN
      CALL ShowSevereError('GetCurveInput: '//trim(CurrentModuleObject)//'="'//trim(Alphas(1))//'", duplicate curve name.')
      CALL ShowContinueError('...Curve name duplicates one of the Pressure Curves. Names must be unique across all curves.')
      ErrorsFound=.true.
    ENDIF
  ENDIF
  ! could add checks for blank numeric fields, and use field names for errors.
  PerfCurve(CurveNum)%Name = Alphas(1)
  PerfCurve(CurveNum)%CurveType = Biquadratic
  PerfCurve(CurveNum)%ObjectType = CurveType_Biquadratic
  PerfCurve(CurveNum)%InterpolationType = EVALUATECURVETOLIMITS
  PerfCurve(CurveNum)%Coeff1 = Numbers(1)
  PerfCurve(CurveNum)%Coeff2 = Numbers(2)
  PerfCurve(CurveNum)%Coeff3 = Numbers(3)
  PerfCurve(CurveNum)%Coeff4 = Numbers(4)
  PerfCurve(CurveNum)%Coeff5 = Numbers(5)
  PerfCurve(CurveNum)%Coeff6 = Numbers(6)
  PerfCurve(CurveNum)%Var1Min = Numbers(7)
  PerfCurve(CurveNum)%Var1Max = Numbers(8)
  PerfCurve(CurveNum)%Var2Min = Numbers(9)
  PerfCurve(CurveNum)%Var2Max = Numbers(10)
  IF(NumNumbers > 10 .AND. .NOT. lNumericFieldBlanks(11))THEN
    PerfCurve(CurveNum)%CurveMin        = Numbers(11)
    PerfCurve(CurveNum)%CurveMinPresent = .TRUE.
  END IF
  IF(NumNumbers > 11 .AND. .NOT. lNumericFieldBlanks(12))THEN
    PerfCurve(CurveNum)%CurveMax        = Numbers(12)
    PerfCurve(CurveNum)%CurveMaxPresent = .TRUE.
  END IF
  IF (Numbers(7) > Numbers(8)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(7))//' ['//TRIM(RoundSigDigits(Numbers(7),2))//'] > '//  &
       TRIM(cNumericFieldNames(8))//' ['//TRIM(RoundSigDigits(Numbers(8),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (Numbers(9) > Numbers(10)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(9))//' ['//TRIM(RoundSigDigits(Numbers(9),2))//'] > '//  &
       TRIM(cNumericFieldNames(10))//' ['//TRIM(RoundSigDigits(Numbers(10),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (NumAlphas .GE. 2) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(2))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for X is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 3) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(3))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for Y is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 4) THEN
    IF (.NOT. IsCurveOutputTypeValid(Alphas(4))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Output Unit Type is invalid.')
    END IF
  END IF
END DO
! Loop over cubic curves and load data
CurrentModuleObject='Curve:Cubic'
DO CurveIndex=1,NumCubic
  CALL GetObjectItem(CurrentModuleObject,CurveIndex,Alphas,NumAlphas,Numbers,NumNumbers,IOStatus,     &
                NumBlank=lNumericFieldBlanks,AlphaFieldnames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
  CurveNum = CurveNum+1
  IsNotOK=.FALSE.
  IsBlank=.FALSE.
  CALL VerifyName(Alphas(1),PerfCurve%Name,CurveNum-1,IsNotOK,IsBlank,TRIM(CurrentModuleObject)//' Name')
  IF (IsNotOK) THEN
    ErrorsFound=.true.
    IF (IsBlank) Alphas(1)='xxxxx'
  ENDIF
  ! Need to verify that this name isn't used in Pressure Curves as well.
  IF (NumPressureCurves > 0) THEN
    CurveFound=FindItemInList(Alphas(1),PressureCurve%Name,NumPressureCurves)
    IF (CurveFound /= 0) THEN
      CALL ShowSevereError('GetCurveInput: '//trim(CurrentModuleObject)//'="'//trim(Alphas(1))//'", duplicate curve name.')
      CALL ShowContinueError('...Curve name duplicates one of the Pressure Curves. Names must be unique across all curves.')
      ErrorsFound=.true.
    ENDIF
  ENDIF
  PerfCurve(CurveNum)%Name = Alphas(1)
  PerfCurve(CurveNum)%CurveType = Cubic
  PerfCurve(CurveNum)%ObjectType = CurveType_Cubic
  PerfCurve(CurveNum)%InterpolationType = EVALUATECURVETOLIMITS
  PerfCurve(CurveNum)%Coeff1 = Numbers(1)
  PerfCurve(CurveNum)%Coeff2 = Numbers(2)
  PerfCurve(CurveNum)%Coeff3 = Numbers(3)
  PerfCurve(CurveNum)%Coeff4 = Numbers(4)
  PerfCurve(CurveNum)%Var1Min = Numbers(5)
  PerfCurve(CurveNum)%Var1Max = Numbers(6)
  IF(NumNumbers > 6 .AND. .NOT. lNumericFieldBlanks(7))THEN
    PerfCurve(CurveNum)%CurveMin        = Numbers(7)
    PerfCurve(CurveNum)%CurveMinPresent = .TRUE.
  END IF
  IF(NumNumbers > 7 .AND. .NOT. lNumericFieldBlanks(8))THEN
    PerfCurve(CurveNum)%CurveMax        = Numbers(8)
    PerfCurve(CurveNum)%CurveMaxPresent = .TRUE.
  END IF
  IF (Numbers(5) > Numbers(6)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(5))//'['//TRIM(RoundSigDigits(Numbers(5),2))//'] > '//  &
       TRIM(cNumericFieldNames(6))//' ['//TRIM(RoundSigDigits(Numbers(6),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (NumAlphas .GE. 2) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(2))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for X is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 3) THEN
    IF (.NOT. IsCurveOutputTypeValid(Alphas(3))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Output Unit Type is invalid.')
    END IF
  END IF
END DO
! Loop over quadrinomial curves and load data
CurrentModuleObject='Curve:Quartic'
DO CurveIndex=1,NumQuartic
  CALL GetObjectItem(CurrentModuleObject,CurveIndex,Alphas,NumAlphas,Numbers,NumNumbers,IOStatus,     &
                NumBlank=lNumericFieldBlanks,AlphaFieldnames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
  CurveNum = CurveNum+1
  IsNotOK=.FALSE.
  IsBlank=.FALSE.
  CALL VerifyName(Alphas(1),PerfCurve%Name,CurveNum-1,IsNotOK,IsBlank,TRIM(CurrentModuleObject)//' Name')
  IF (IsNotOK) THEN
    ErrorsFound=.true.
    IF (IsBlank) Alphas(1)='xxxxx'
  ENDIF
  ! Need to verify that this name isn't used in Pressure Curves as well.
  IF (NumPressureCurves > 0) THEN
    CurveFound=FindItemInList(Alphas(1),PressureCurve%Name,NumPressureCurves)
    IF (CurveFound /= 0) THEN
      CALL ShowSevereError('GetCurveInput: '//trim(CurrentModuleObject)//'="'//trim(Alphas(1))//'", duplicate curve name.')
      CALL ShowContinueError('...Curve name duplicates one of the Pressure Curves. Names must be unique across all curves.')
      ErrorsFound=.true.
    ENDIF
  ENDIF
  PerfCurve(CurveNum)%Name = Alphas(1)
  PerfCurve(CurveNum)%CurveType = Quartic
  PerfCurve(CurveNum)%ObjectType = CurveType_Quartic
  PerfCurve(CurveNum)%InterpolationType = EVALUATECURVETOLIMITS
  PerfCurve(CurveNum)%Coeff1 = Numbers(1)
  PerfCurve(CurveNum)%Coeff2 = Numbers(2)
  PerfCurve(CurveNum)%Coeff3 = Numbers(3)
  PerfCurve(CurveNum)%Coeff4 = Numbers(4)
  PerfCurve(CurveNum)%Coeff5 = Numbers(5)
  PerfCurve(CurveNum)%Var1Min = Numbers(6)
  PerfCurve(CurveNum)%Var1Max = Numbers(7)
  IF(NumNumbers > 7 .AND. .NOT. lNumericFieldBlanks(8))THEN
    PerfCurve(CurveNum)%CurveMin        = Numbers(8)
    PerfCurve(CurveNum)%CurveMinPresent = .TRUE.
  END IF
  IF(NumNumbers > 8 .AND. .NOT. lNumericFieldBlanks(9))THEN
    PerfCurve(CurveNum)%CurveMax        = Numbers(9)
    PerfCurve(CurveNum)%CurveMaxPresent = .TRUE.
  END IF
  IF (Numbers(6) > Numbers(7)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(6))//'['//TRIM(RoundSigDigits(Numbers(6),2))//'] > '//  &
       TRIM(cNumericFieldNames(7))//' ['//TRIM(RoundSigDigits(Numbers(7),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (NumAlphas .GE. 2) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(2))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for X is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 3) THEN
    IF (.NOT. IsCurveOutputTypeValid(Alphas(3))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Output Unit Type is invalid.')
    END IF
  END IF
END DO
! Loop over quadratic curves and load data
CurrentModuleObject='Curve:Quadratic'
DO CurveIndex=1,NumQuad
  CALL GetObjectItem(CurrentModuleObject,CurveIndex,Alphas,NumAlphas,Numbers,NumNumbers,IOStatus,     &
                NumBlank=lNumericFieldBlanks,AlphaFieldnames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
  CurveNum = CurveNum+1
  IsNotOK=.FALSE.
  IsBlank=.FALSE.
  CALL VerifyName(Alphas(1),PerfCurve%Name,CurveNum-1,IsNotOK,IsBlank,TRIM(CurrentModuleObject)//' Name')
  IF (IsNotOK) THEN
    ErrorsFound=.true.
    IF (IsBlank) Alphas(1)='xxxxx'
  ENDIF
  ! Need to verify that this name isn't used in Pressure Curves as well.
  IF (NumPressureCurves > 0) THEN
    CurveFound=FindItemInList(Alphas(1),PressureCurve%Name,NumPressureCurves)
    IF (CurveFound /= 0) THEN
      CALL ShowSevereError('GetCurveInput: '//trim(CurrentModuleObject)//'="'//trim(Alphas(1))//'", duplicate curve name.')
      CALL ShowContinueError('...Curve name duplicates one of the Pressure Curves. Names must be unique across all curves.')
      ErrorsFound=.true.
    ENDIF
  ENDIF
  PerfCurve(CurveNum)%Name = Alphas(1)
  PerfCurve(CurveNum)%CurveType = Quadratic
  PerfCurve(CurveNum)%ObjectType = CurveType_Quadratic
  PerfCurve(CurveNum)%InterpolationType = EVALUATECURVETOLIMITS
  PerfCurve(CurveNum)%Coeff1 = Numbers(1)
  PerfCurve(CurveNum)%Coeff2 = Numbers(2)
  PerfCurve(CurveNum)%Coeff3 = Numbers(3)
  PerfCurve(CurveNum)%Var1Min = Numbers(4)
  PerfCurve(CurveNum)%Var1Max = Numbers(5)
  IF(NumNumbers > 5 .AND. .NOT. lNumericFieldBlanks(6))THEN
    PerfCurve(CurveNum)%CurveMin        = Numbers(6)
    PerfCurve(CurveNum)%CurveMinPresent = .TRUE.
  END IF
  IF(NumNumbers > 6 .AND. .NOT. lNumericFieldBlanks(7))THEN
    PerfCurve(CurveNum)%CurveMax        = Numbers(7)
    PerfCurve(CurveNum)%CurveMaxPresent = .TRUE.
  END IF
  IF (Numbers(4) > Numbers(5)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(4))//' ['//TRIM(RoundSigDigits(Numbers(4),2))//'] > '//  &
       TRIM(cNumericFieldNames(5))//' ['//TRIM(RoundSigDigits(Numbers(5),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (NumAlphas .GE. 2) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(2))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for X is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 3) THEN
    IF (.NOT. IsCurveOutputTypeValid(Alphas(3))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Output Unit Type is invalid.')
    END IF
  END IF
END DO
! Loop over quadratic-linear curves and load data
CurrentModuleObject='Curve:QuadraticLinear'
DO CurveIndex=1,NumQuadLinear
  CALL GetObjectItem(CurrentModuleObject,CurveIndex,Alphas,NumAlphas,Numbers,NumNumbers,IOStatus,     &
                NumBlank=lNumericFieldBlanks,AlphaFieldnames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
  CurveNum = CurveNum+1
  IsNotOK=.FALSE.
  IsBlank=.FALSE.
  CALL VerifyName(Alphas(1),PerfCurve%Name,CurveNum-1,IsNotOK,IsBlank,TRIM(CurrentModuleObject)//' Name')
  IF (IsNotOK) THEN
    ErrorsFound=.true.
    IF (IsBlank) Alphas(1)='xxxxx'
  ENDIF
  ! Need to verify that this name isn't used in Pressure Curves as well.
  IF (NumPressureCurves > 0) THEN
    CurveFound=FindItemInList(Alphas(1),PressureCurve%Name,NumPressureCurves)
    IF (CurveFound /= 0) THEN
      CALL ShowSevereError('GetCurveInput: '//trim(CurrentModuleObject)//'="'//trim(Alphas(1))//'", duplicate curve name.')
      CALL ShowContinueError('...Curve name duplicates one of the Pressure Curves. Names must be unique across all curves.')
      ErrorsFound=.true.
    ENDIF
  ENDIF
  PerfCurve(CurveNum)%Name      = Alphas(1)
  PerfCurve(CurveNum)%CurveType = QuadraticLinear
  PerfCurve(CurveNum)%ObjectType = CurveType_QuadraticLinear
  PerfCurve(CurveNum)%InterpolationType = EVALUATECURVETOLIMITS
  PerfCurve(CurveNum)%Coeff1    = Numbers(1)
  PerfCurve(CurveNum)%Coeff2    = Numbers(2)
  PerfCurve(CurveNum)%Coeff3    = Numbers(3)
  PerfCurve(CurveNum)%Coeff4    = Numbers(4)
  PerfCurve(CurveNum)%Coeff5    = Numbers(5)
  PerfCurve(CurveNum)%Coeff6    = Numbers(6)
  PerfCurve(CurveNum)%Var1Min   = Numbers(7)
  PerfCurve(CurveNum)%Var1Max   = Numbers(8)
  PerfCurve(CurveNum)%Var2Min   = Numbers(9)
  PerfCurve(CurveNum)%Var2Max   = Numbers(10)
  IF(NumNumbers > 10 .AND. .NOT. lNumericFieldBlanks(11))THEN
    PerfCurve(CurveNum)%CurveMin        = Numbers(11)
    PerfCurve(CurveNum)%CurveMinPresent = .TRUE.
  END IF
  IF(NumNumbers > 11 .AND. .NOT. lNumericFieldBlanks(12))THEN
    PerfCurve(CurveNum)%CurveMax        = Numbers(12)
    PerfCurve(CurveNum)%CurveMaxPresent = .TRUE.
  END IF
  IF (Numbers(7) > Numbers(8)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(7))//' ['//TRIM(RoundSigDigits(Numbers(7),2))//'] > '//  &
       TRIM(cNumericFieldNames(8))//' ['//TRIM(RoundSigDigits(Numbers(8),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (Numbers(9) > Numbers(10)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(9))//' ['//TRIM(RoundSigDigits(Numbers(9),2))//'] > '//  &
       TRIM(cNumericFieldNames(10))//' ['//TRIM(RoundSigDigits(Numbers(10),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (NumAlphas .GE. 2) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(2))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for X is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 3) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(3))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for Y is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 4) THEN
    IF (.NOT. IsCurveOutputTypeValid(Alphas(4))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Output Unit Type is invalid.')
    END IF
  END IF
END DO
! Loop over linear curves and load data
CurrentModuleObject='Curve:Linear'
DO CurveIndex=1,NumLinear
  CALL GetObjectItem(CurrentModuleObject,CurveIndex,Alphas,NumAlphas,Numbers,NumNumbers,IOStatus,     &
                NumBlank=lNumericFieldBlanks,AlphaFieldnames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
  CurveNum = CurveNum+1
  IsNotOK=.FALSE.
  IsBlank=.FALSE.
  CALL VerifyName(Alphas(1),PerfCurve%Name,CurveNum-1,IsNotOK,IsBlank,TRIM(CurrentModuleObject)//' Name')
  IF (IsNotOK) THEN
    ErrorsFound=.true.
    IF (IsBlank) Alphas(1)='xxxxx'
  ENDIF
  ! Need to verify that this name isn't used in Pressure Curves as well.
  IF (NumPressureCurves > 0) THEN
    CurveFound=FindItemInList(Alphas(1),PressureCurve%Name,NumPressureCurves)
    IF (CurveFound /= 0) THEN
      CALL ShowSevereError('GetCurveInput: '//trim(CurrentModuleObject)//'="'//trim(Alphas(1))//'", duplicate curve name.')
      CALL ShowContinueError('...Curve name duplicates one of the Pressure Curves. Names must be unique across all curves.')
      ErrorsFound=.true.
    ENDIF
  ENDIF
  PerfCurve(CurveNum)%Name      = Alphas(1)
  PerfCurve(CurveNum)%CurveType = Linear
  PerfCurve(CurveNum)%ObjectType = CurveType_Linear
  PerfCurve(CurveNum)%InterpolationType = EVALUATECURVETOLIMITS
  PerfCurve(CurveNum)%Coeff1    = Numbers(1)
  PerfCurve(CurveNum)%Coeff2    = Numbers(2)
  PerfCurve(CurveNum)%Var1Min   = Numbers(3)
  PerfCurve(CurveNum)%Var1Max   = Numbers(4)
  IF(NumNumbers > 4 .AND. .NOT. lNumericFieldBlanks(5))THEN
    PerfCurve(CurveNum)%CurveMin        = Numbers(5)
    PerfCurve(CurveNum)%CurveMinPresent = .TRUE.
  END IF
  IF(NumNumbers > 5 .AND. .NOT. lNumericFieldBlanks(6))THEN
    PerfCurve(CurveNum)%CurveMax        = Numbers(6)
    PerfCurve(CurveNum)%CurveMaxPresent = .TRUE.
  END IF
  IF (Numbers(3) > Numbers(4)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(3))//' ['//TRIM(RoundSigDigits(Numbers(3),2))//'] > '//  &
       TRIM(cNumericFieldNames(4))//' ['//TRIM(RoundSigDigits(Numbers(4),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (NumAlphas .GE. 2) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(2))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for X is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 3) THEN
    IF (.NOT. IsCurveOutputTypeValid(Alphas(3))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Output Unit Type is invalid.')
    END IF
  END IF
END DO
! Loop over bicubic curves and load data
CurrentModuleObject='Curve:Bicubic'
DO CurveIndex=1,NumBicubic
  CALL GetObjectItem(CurrentModuleObject,CurveIndex,Alphas,NumAlphas,Numbers,NumNumbers,IOStatus,     &
                NumBlank=lNumericFieldBlanks,AlphaFieldnames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
  CurveNum = CurveNum+1
  IsNotOK=.FALSE.
  IsBlank=.FALSE.
  CALL VerifyName(Alphas(1),PerfCurve%Name,CurveNum-1,IsNotOK,IsBlank,TRIM(CurrentModuleObject)//' Name')
  IF (IsNotOK) THEN
    ErrorsFound=.true.
    IF (IsBlank) Alphas(1)='xxxxx'
  ENDIF
  ! Need to verify that this name isn't used in Pressure Curves as well.
  IF (NumPressureCurves > 0) THEN
    CurveFound=FindItemInList(Alphas(1),PressureCurve%Name,NumPressureCurves)
    IF (CurveFound /= 0) THEN
      CALL ShowSevereError('GetCurveInput: '//trim(CurrentModuleObject)//'="'//trim(Alphas(1))//'", duplicate curve name.')
      CALL ShowContinueError('...Curve name duplicates one of the Pressure Curves. Names must be unique across all curves.')
      ErrorsFound=.true.
    ENDIF
  ENDIF
  PerfCurve(CurveNum)%Name      = Alphas(1)
  PerfCurve(CurveNum)%CurveType = Bicubic
  PerfCurve(CurveNum)%ObjectType = CurveType_BiCubic
  PerfCurve(CurveNum)%InterpolationType = EVALUATECURVETOLIMITS
  PerfCurve(CurveNum)%Coeff1    = Numbers(1)
  PerfCurve(CurveNum)%Coeff2    = Numbers(2)
  PerfCurve(CurveNum)%Coeff3    = Numbers(3)
  PerfCurve(CurveNum)%Coeff4    = Numbers(4)
  PerfCurve(CurveNum)%Coeff5    = Numbers(5)
  PerfCurve(CurveNum)%Coeff6    = Numbers(6)
  PerfCurve(CurveNum)%Coeff7    = Numbers(7)
  PerfCurve(CurveNum)%Coeff8    = Numbers(8)
  PerfCurve(CurveNum)%Coeff9    = Numbers(9)
  PerfCurve(CurveNum)%Coeff10   = Numbers(10)
  PerfCurve(CurveNum)%Var1Min   = Numbers(11)
  PerfCurve(CurveNum)%Var1Max   = Numbers(12)
  PerfCurve(CurveNum)%Var2Min   = Numbers(13)
  PerfCurve(CurveNum)%Var2Max   = Numbers(14)
  IF(NumNumbers > 14 .AND. .NOT. lNumericFieldBlanks(15))THEN
    PerfCurve(CurveNum)%CurveMin        = Numbers(15)
    PerfCurve(CurveNum)%CurveMinPresent = .TRUE.
  END IF
  IF(NumNumbers > 15 .AND. .NOT. lNumericFieldBlanks(16))THEN
    PerfCurve(CurveNum)%CurveMax        = Numbers(16)
    PerfCurve(CurveNum)%CurveMaxPresent = .TRUE.
  END IF
  IF (Numbers(11) > Numbers(12)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(11))//' ['//TRIM(RoundSigDigits(Numbers(11),2))//'] > '//  &
       TRIM(cNumericFieldNames(12))//' ['//TRIM(RoundSigDigits(Numbers(12),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (Numbers(13) > Numbers(14)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(13))//' ['//TRIM(RoundSigDigits(Numbers(13),2))//'] > '//  &
       TRIM(cNumericFieldNames(14))//' ['//TRIM(RoundSigDigits(Numbers(14),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (NumAlphas .GE. 2) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(2))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for X is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 3) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(3))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for Y is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 4) THEN
    IF (.NOT. IsCurveOutputTypeValid(Alphas(4))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Output Unit Type is invalid.')
    END IF
  END IF
END DO
! Loop over Triquadratic curves and load data
CurrentModuleObject='Curve:Triquadratic'
DO CurveIndex=1,NumTriQuad
  CALL GetObjectItem(CurrentModuleObject,CurveIndex,Alphas,NumAlphas,Numbers,NumNumbers,IOStatus,     &
                NumBlank=lNumericFieldBlanks,AlphaFieldnames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
  CurveNum = CurveNum+1
  IsNotOK=.FALSE.
  IsBlank=.FALSE.
  CALL VerifyName(Alphas(1),PerfCurve%Name,CurveNum-1,IsNotOK,IsBlank,TRIM(CurrentModuleObject)//' Name')
  IF (IsNotOK) THEN
    ErrorsFound=.true.
    IF (IsBlank) Alphas(1)='xxxxx'
  ENDIF
  ! Need to verify that this name isn't used in Pressure Curves as well.
  IF (NumPressureCurves > 0) THEN
    CurveFound=FindItemInList(Alphas(1),PressureCurve%Name,NumPressureCurves)
    IF (CurveFound /= 0) THEN
      CALL ShowSevereError('GetCurveInput: '//trim(CurrentModuleObject)//'="'//trim(Alphas(1))//'", duplicate curve name.')
      CALL ShowContinueError('...Curve name duplicates one of the Pressure Curves. Names must be unique across all curves.')
      ErrorsFound=.true.
    ENDIF
  ENDIF
  PerfCurve(CurveNum)%Name = Alphas(1)
  PerfCurve(CurveNum)%CurveType = TriQuadratic
  PerfCurve(CurveNum)%ObjectType = CurveType_TriQuadratic
  PerfCurve(CurveNum)%InterpolationType = EVALUATECURVETOLIMITS
  Allocate(PerfCurve(CurveNum)%Tri2ndOrder(1))
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA0 = Numbers(1)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA1 = Numbers(2)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA2 = Numbers(3)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA3 = Numbers(4)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA4 = Numbers(5)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA5 = Numbers(6)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA6 = Numbers(7)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA7 = Numbers(8)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA8 = Numbers(9)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA9 = Numbers(10)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA10 = Numbers(11)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA11 = Numbers(12)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA12 = Numbers(13)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA13 = Numbers(14)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA14 = Numbers(15)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA15 = Numbers(16)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA16 = Numbers(17)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA17 = Numbers(18)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA18 = Numbers(19)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA19 = Numbers(20)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA20 = Numbers(21)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA21 = Numbers(22)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA22 = Numbers(23)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA23 = Numbers(24)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA24 = Numbers(25)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA25 = Numbers(26)
  PerfCurve(CurveNum)%Tri2ndOrder%CoeffA26 = Numbers(27)
  PerfCurve(CurveNum)%Var1Min = Numbers(28)
  PerfCurve(CurveNum)%Var1Max = Numbers(29)
  PerfCurve(CurveNum)%Var2Min = Numbers(30)
  PerfCurve(CurveNum)%Var2Max = Numbers(31)
  PerfCurve(CurveNum)%Var3Min = Numbers(32)
  PerfCurve(CurveNum)%Var3Max = Numbers(33)
  IF(NumNumbers > 33 .AND. .NOT. lNumericFieldBlanks(34))THEN
    PerfCurve(CurveNum)%CurveMin        = Numbers(34)
    PerfCurve(CurveNum)%CurveMinPresent = .TRUE.
  END IF
  IF(NumNumbers > 34 .AND. .NOT. lNumericFieldBlanks(35))THEN
    PerfCurve(CurveNum)%CurveMax        = Numbers(35)
    PerfCurve(CurveNum)%CurveMaxPresent = .TRUE.
  END IF
  IF (Numbers(28) > Numbers(29)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(28))//' ['//TRIM(RoundSigDigits(Numbers(28),2))//'] > '//  &
       TRIM(cNumericFieldNames(29))//' ['//TRIM(RoundSigDigits(Numbers(29),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (Numbers(30) > Numbers(31)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(30))//' ['//TRIM(RoundSigDigits(Numbers(30),2))//'] > '//  &
       TRIM(cNumericFieldNames(31))//' ['//TRIM(RoundSigDigits(Numbers(31),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (Numbers(32) > Numbers(33)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(32))//' ['//TRIM(RoundSigDigits(Numbers(32),2))//'] > '//  &
       TRIM(cNumericFieldNames(33))//' ['//TRIM(RoundSigDigits(Numbers(33),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (NumAlphas .GE. 2) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(2))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for X is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 3) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(3))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for Y is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 4) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(4))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for Z is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 5) THEN
    IF (.NOT. IsCurveOutputTypeValid(Alphas(5))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Output Unit Type is invalid.')
    END IF
  END IF
END DO
! Loop over quad linear curves and load data
CurrentModuleObject='Curve:QuadLinear'
DO CurveIndex=1,NumQLinear
  CALL GetObjectItem(CurrentModuleObject,CurveIndex,Alphas,NumAlphas,Numbers,NumNumbers,IOStatus,     &
                NumBlank=lNumericFieldBlanks,AlphaFieldnames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
  CurveNum = CurveNum+1
  IsNotOK=.FALSE.
  IsBlank=.FALSE.
  CALL VerifyName(Alphas(1),PerfCurve%Name,CurveNum-1,IsNotOK,IsBlank,TRIM(CurrentModuleObject)//' Name')
  IF (IsNotOK) THEN
    ErrorsFound=.true.
    IF (IsBlank) Alphas(1)='xxxxx'
  ENDIF
  ! Need to verify that this name isn't used in Pressure Curves as well.
  IF (NumPressureCurves > 0) THEN
    CurveFound=FindItemInList(Alphas(1),PressureCurve%Name,NumPressureCurves)
    IF (CurveFound /= 0) THEN
      CALL ShowSevereError('GetCurveInput: '//trim(CurrentModuleObject)//'="'//trim(Alphas(1))//'", duplicate curve name.')
      CALL ShowContinueError('...Curve name duplicates one of the Pressure Curves. Names must be unique across all curves.')
      ErrorsFound=.true.
    ENDIF
  ENDIF
  PerfCurve(CurveNum)%Name      = Alphas(1)
  PerfCurve(CurveNum)%CurveType = QuadLinear
  PerfCurve(CurveNum)%ObjectType = CurveType_QuadLinear
  PerfCurve(CurveNum)%InterpolationType = EVALUATECURVETOLIMITS
  PerfCurve(CurveNum)%Coeff1    = Numbers(1)
  PerfCurve(CurveNum)%Coeff2    = Numbers(2)
  PerfCurve(CurveNum)%Coeff3    = Numbers(3)
  PerfCurve(CurveNum)%Coeff4    = Numbers(4)
  PerfCurve(CurveNum)%Coeff5    = Numbers(5)
  PerfCurve(CurveNum)%Var1Min   = Numbers(6)
  PerfCurve(CurveNum)%Var1Max   = Numbers(7)
  PerfCurve(CurveNum)%Var2Min   = Numbers(8)
  PerfCurve(CurveNum)%Var2Max   = Numbers(9)
  PerfCurve(CurveNum)%Var3Min   = Numbers(10)
  PerfCurve(CurveNum)%Var3Max   = Numbers(11)
  PerfCurve(CurveNum)%Var4Min   = Numbers(12)
  PerfCurve(CurveNum)%Var4Max   = Numbers(13)
  IF(NumNumbers > 13 .AND. .NOT. lNumericFieldBlanks(14))THEN
    PerfCurve(CurveNum)%CurveMin        = Numbers(14)
    PerfCurve(CurveNum)%CurveMinPresent = .TRUE.
  END IF
  IF(NumNumbers > 14 .AND. .NOT. lNumericFieldBlanks(15))THEN
    PerfCurve(CurveNum)%CurveMax        = Numbers(15)
    PerfCurve(CurveNum)%CurveMaxPresent = .TRUE.
  END IF
  IF (Numbers(6) > Numbers(7)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(6))//' ['//TRIM(RoundSigDigits(Numbers(6),2))//'] > '//  &
       TRIM(cNumericFieldNames(7))//' ['//TRIM(RoundSigDigits(Numbers(7),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (Numbers(8) > Numbers(9)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(8))//' ['//TRIM(RoundSigDigits(Numbers(8),2))//'] > '//  &
       TRIM(cNumericFieldNames(9))//' ['//TRIM(RoundSigDigits(Numbers(9),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (Numbers(10) > Numbers(11)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(10))//' ['//TRIM(RoundSigDigits(Numbers(10),2))//'] > '//  &
       TRIM(cNumericFieldNames(11))//' ['//TRIM(RoundSigDigits(Numbers(11),2))//']')
    ErrorsFound=.true.
  ENDIF
    IF (Numbers(12) > Numbers(13)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(12))//' ['//TRIM(RoundSigDigits(Numbers(12),2))//'] > '//  &
       TRIM(cNumericFieldNames(13))//' ['//TRIM(RoundSigDigits(Numbers(13),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (NumAlphas .GE. 2) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(2))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for W is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 3) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(3))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for X is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 4) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(4))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for Y is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 5) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(5))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for Z is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 6) THEN
    IF (.NOT. IsCurveOutputTypeValid(Alphas(6))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Output Unit Type is invalid.')
    END IF
  END IF
END DO
! Loop over Exponent curves and load data
CurrentModuleObject='Curve:Exponent'
DO CurveIndex=1,NumExponent
  CALL GetObjectItem(CurrentModuleObject,CurveIndex,Alphas,NumAlphas,Numbers,NumNumbers,IOStatus,     &
                NumBlank=lNumericFieldBlanks,AlphaFieldnames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
  CurveNum = CurveNum+1
  IsNotOK=.FALSE.
  IsBlank=.FALSE.
  CALL VerifyName(Alphas(1),PerfCurve%Name,CurveNum-1,IsNotOK,IsBlank,TRIM(CurrentModuleObject)//' Name')
  IF (IsNotOK) THEN
    ErrorsFound=.true.
    IF (IsBlank) Alphas(1)='xxxxx'
  ENDIF
  ! Need to verify that this name isn't used in Pressure Curves as well.
  IF (NumPressureCurves > 0) THEN
    CurveFound=FindItemInList(Alphas(1),PressureCurve%Name,NumPressureCurves)
    IF (CurveFound /= 0) THEN
      CALL ShowSevereError('GetCurveInput: '//trim(CurrentModuleObject)//'="'//trim(Alphas(1))//'", duplicate curve name.')
      CALL ShowContinueError('...Curve name duplicates one of the Pressure Curves. Names must be unique across all curves.')
      ErrorsFound=.true.
    ENDIF
  ENDIF
  PerfCurve(CurveNum)%Name      = Alphas(1)
  PerfCurve(CurveNum)%CurveType = Exponent
  PerfCurve(CurveNum)%ObjectType = CurveType_Exponent
  PerfCurve(CurveNum)%InterpolationType = EVALUATECURVETOLIMITS
  PerfCurve(CurveNum)%Coeff1    = Numbers(1)
  PerfCurve(CurveNum)%Coeff2    = Numbers(2)
  PerfCurve(CurveNum)%Coeff3    = Numbers(3)
  PerfCurve(CurveNum)%Var1Min   = Numbers(4)
  PerfCurve(CurveNum)%Var1Max   = Numbers(5)
  IF(NumNumbers > 5 .AND. .NOT. lNumericFieldBlanks(6))THEN
    PerfCurve(CurveNum)%CurveMin        = Numbers(6)
    PerfCurve(CurveNum)%CurveMinPresent = .TRUE.
  END IF
  IF(NumNumbers > 6 .AND. .NOT. lNumericFieldBlanks(7))THEN
    PerfCurve(CurveNum)%CurveMax        = Numbers(7)
    PerfCurve(CurveNum)%CurveMaxPresent = .TRUE.
  END IF
  IF (NumAlphas .GE. 2) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(2))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for X is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 3) THEN
    IF (.NOT. IsCurveOutputTypeValid(Alphas(3))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Output Unit Type is invalid.')
    END IF
  END IF
END DO
! cpw22Aug2010 Loop over Fan Pressure Rise curves and load data - udated 15Sep2010 for unit types
CurrentModuleObject='Curve:FanPressureRise'
DO CurveIndex=1,NumFanPressRise
  CALL GetObjectItem(CurrentModuleObject,CurveIndex,Alphas,NumAlphas,Numbers,NumNumbers,IOStatus,     &
                NumBlank=lNumericFieldBlanks,AlphaFieldnames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
  CurveNum = CurveNum+1
  IsNotOK=.FALSE.
  IsBlank=.FALSE.
  CALL VerifyName(Alphas(1),PerfCurve%Name,CurveNum-1,IsNotOK,IsBlank,TRIM(CurrentModuleObject)//' Name')
  IF (IsNotOK) THEN
    ErrorsFound=.true.
    IF (IsBlank) Alphas(1)='xxxxx'
  ENDIF
  ! Need to verify that this name isn't used in Pressure Curves as well.
  IF (NumPressureCurves > 0) THEN
    CurveFound=FindItemInList(Alphas(1),PressureCurve%Name,NumPressureCurves)
    IF (CurveFound /= 0) THEN
      CALL ShowSevereError('GetCurveInput: '//trim(CurrentModuleObject)//'="'//trim(Alphas(1))//'", duplicate curve name.')
      CALL ShowContinueError('...Curve name duplicates one of the Pressure Curves. Names must be unique across all curves.')
      ErrorsFound=.true.
    ENDIF
  ENDIF
  PerfCurve(CurveNum)%Name = Alphas(1)
  PerfCurve(CurveNum)%CurveType = FanPressureRise
  PerfCurve(CurveNum)%ObjectType = CurveType_FanPressureRise
  PerfCurve(CurveNum)%InterpolationType = EVALUATECURVETOLIMITS
  PerfCurve(CurveNum)%Coeff1 = Numbers(1)
  PerfCurve(CurveNum)%Coeff2 = Numbers(2)
  PerfCurve(CurveNum)%Coeff3 = Numbers(3)
  PerfCurve(CurveNum)%Coeff4 = Numbers(4)
  PerfCurve(CurveNum)%Var1Min = Numbers(5)
  PerfCurve(CurveNum)%Var1Max = Numbers(6)
  PerfCurve(CurveNum)%Var2Min = Numbers(7)
  PerfCurve(CurveNum)%Var2Max = Numbers(8)
  IF(NumNumbers > 8 .AND. .NOT. lNumericFieldBlanks(9))THEN
    PerfCurve(CurveNum)%CurveMin        = Numbers(9)
    PerfCurve(CurveNum)%CurveMinPresent = .TRUE.
  END IF
  IF(NumNumbers > 9 .AND. .NOT. lNumericFieldBlanks(10))THEN
    PerfCurve(CurveNum)%CurveMax        = Numbers(10)
    PerfCurve(CurveNum)%CurveMaxPresent = .TRUE.
  END IF
  IF (Numbers(5) > Numbers(6)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(5))//'['//TRIM(RoundSigDigits(Numbers(5),2))//'] > '//  &
       TRIM(cNumericFieldNames(6))//' ['//TRIM(RoundSigDigits(Numbers(6),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (Numbers(7) > Numbers(8)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(7))//'['//TRIM(RoundSigDigits(Numbers(7),2))//'] > '//  &
       TRIM(cNumericFieldNames(8))//' ['//TRIM(RoundSigDigits(Numbers(8),2))//']')
    ErrorsFound=.true.
  ENDIF
END DO !Fan Pressure Rise
! cpw22Aug2010 Loop over Exponential Skew Normal curves and load data
CurrentModuleObject='Curve:ExponentialSkewNormal'
DO CurveIndex=1,NumExpSkewNorm
  CALL GetObjectItem(CurrentModuleObject,CurveIndex,Alphas,NumAlphas,Numbers,NumNumbers,IOStatus,     &
                NumBlank=lNumericFieldBlanks,AlphaFieldnames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
  CurveNum = CurveNum+1
  IsNotOK=.FALSE.
  IsBlank=.FALSE.
  CALL VerifyName(Alphas(1),PerfCurve%Name,CurveNum-1,IsNotOK,IsBlank,TRIM(CurrentModuleObject)//' Name')
  IF (IsNotOK) THEN
    ErrorsFound=.true.
    IF (IsBlank) Alphas(1)='xxxxx'
  ENDIF
  ! Need to verify that this name isn't used in Pressure Curves as well.
  IF (NumPressureCurves > 0) THEN
    CurveFound=FindItemInList(Alphas(1),PressureCurve%Name,NumPressureCurves)
    IF (CurveFound /= 0) THEN
      CALL ShowSevereError('GetCurveInput: '//trim(CurrentModuleObject)//'="'//trim(Alphas(1))//'", duplicate curve name.')
      CALL ShowContinueError('...Curve name duplicates one of the Pressure Curves. Names must be unique across all curves.')
      ErrorsFound=.true.
    ENDIF
  ENDIF
  PerfCurve(CurveNum)%Name = Alphas(1)
  PerfCurve(CurveNum)%CurveType = ExponentialSkewNormal
  PerfCurve(CurveNum)%ObjectType = CurveType_ExponentialSkewNormal
  PerfCurve(CurveNum)%InterpolationType = EVALUATECURVETOLIMITS
  PerfCurve(CurveNum)%Coeff1 = Numbers(1)
  PerfCurve(CurveNum)%Coeff2 = Numbers(2)
  PerfCurve(CurveNum)%Coeff3 = Numbers(3)
  PerfCurve(CurveNum)%Coeff4 = Numbers(4)
  PerfCurve(CurveNum)%Var1Min = Numbers(5)
  PerfCurve(CurveNum)%Var1Max = Numbers(6)
  IF(NumNumbers > 6 .AND. .NOT. lNumericFieldBlanks(7))THEN
    PerfCurve(CurveNum)%CurveMin        = Numbers(7)
    PerfCurve(CurveNum)%CurveMinPresent = .TRUE.
  END IF
  IF(NumNumbers > 7 .AND. .NOT. lNumericFieldBlanks(9))THEN
    PerfCurve(CurveNum)%CurveMax        = Numbers(9)
    PerfCurve(CurveNum)%CurveMaxPresent = .TRUE.
  END IF
  IF (Numbers(5) > Numbers(6)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(5))//'['//TRIM(RoundSigDigits(Numbers(5),2))//'] > '//  &
       TRIM(cNumericFieldNames(6))//' ['//TRIM(RoundSigDigits(Numbers(6),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (NumAlphas .GE. 2) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(2))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for X is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 3) THEN
    IF (.NOT. IsCurveOutputTypeValid(Alphas(3))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Output Unit Type is invalid.')
    END IF
  END IF
END DO !Exponential Skew Normal
! cpw22Aug2010 Loop over Sigmoid curves and load data
CurrentModuleObject='Curve:Sigmoid'
DO CurveIndex=1,NumSigmoid
  CALL GetObjectItem(CurrentModuleObject,CurveIndex,Alphas,NumAlphas,Numbers,NumNumbers,IOStatus,     &
                NumBlank=lNumericFieldBlanks,AlphaFieldnames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
  CurveNum = CurveNum+1
  IsNotOK=.FALSE.
  IsBlank=.FALSE.
  CALL VerifyName(Alphas(1),PerfCurve%Name,CurveNum-1,IsNotOK,IsBlank,TRIM(CurrentModuleObject)//' Name')
  IF (IsNotOK) THEN
    ErrorsFound=.true.
    IF (IsBlank) Alphas(1)='xxxxx'
  ENDIF
  ! Need to verify that this name isn't used in Pressure Curves as well.
  IF (NumPressureCurves > 0) THEN
    CurveFound=FindItemInList(Alphas(1),PressureCurve%Name,NumPressureCurves)
    IF (CurveFound /= 0) THEN
      CALL ShowSevereError('GetCurveInput: '//trim(CurrentModuleObject)//'="'//trim(Alphas(1))//'", duplicate curve name.')
      CALL ShowContinueError('...Curve name duplicates one of the Pressure Curves. Names must be unique across all curves.')
      ErrorsFound=.true.
    ENDIF
  ENDIF
  PerfCurve(CurveNum)%Name = Alphas(1)
  PerfCurve(CurveNum)%CurveType = Sigmoid
  PerfCurve(CurveNum)%ObjectType = CurveType_Sigmoid
  PerfCurve(CurveNum)%InterpolationType = EVALUATECURVETOLIMITS
  PerfCurve(CurveNum)%Coeff1 = Numbers(1)
  PerfCurve(CurveNum)%Coeff2 = Numbers(2)
  PerfCurve(CurveNum)%Coeff3 = Numbers(3)
  PerfCurve(CurveNum)%Coeff4 = Numbers(4)
  PerfCurve(CurveNum)%Coeff5 = Numbers(5)
  PerfCurve(CurveNum)%Var1Min = Numbers(6)
  PerfCurve(CurveNum)%Var1Max = Numbers(7)
  IF(NumNumbers > 7 .AND. .NOT. lNumericFieldBlanks(8))THEN
    PerfCurve(CurveNum)%CurveMin        = Numbers(8)
    PerfCurve(CurveNum)%CurveMinPresent = .TRUE.
  END IF
  IF(NumNumbers > 8 .AND. .NOT. lNumericFieldBlanks(9))THEN
    PerfCurve(CurveNum)%CurveMax        = Numbers(9)
    PerfCurve(CurveNum)%CurveMaxPresent = .TRUE.
  END IF
  IF (Numbers(6) > Numbers(7)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(6))//'['//TRIM(RoundSigDigits(Numbers(6),2))//'] > '//  &
       TRIM(cNumericFieldNames(7))//' ['//TRIM(RoundSigDigits(Numbers(7),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (NumAlphas .GE. 2) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(2))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for X is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 3) THEN
    IF (.NOT. IsCurveOutputTypeValid(Alphas(3))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Output Unit Type is invalid.')
    END IF
  END IF
END DO !Sigmoid
! cpw22Aug2010 Loop over Rectangular Hyperbola Type 1 curves and load data
CurrentModuleObject='Curve:RectangularHyperbola1'
DO CurveIndex=1,NumRectHyper1
  CALL GetObjectItem(CurrentModuleObject,CurveIndex,Alphas,NumAlphas,Numbers,NumNumbers,IOStatus,     &
                NumBlank=lNumericFieldBlanks,AlphaFieldnames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
  CurveNum = CurveNum+1
  IsNotOK=.FALSE.
  IsBlank=.FALSE.
  CALL VerifyName(Alphas(1),PerfCurve%Name,CurveNum-1,IsNotOK,IsBlank,TRIM(CurrentModuleObject)//' Name')
  IF (IsNotOK) THEN
    ErrorsFound=.true.
    IF (IsBlank) Alphas(1)='xxxxx'
  ENDIF
  ! Need to verify that this name isn't used in Pressure Curves as well.
  IF (NumPressureCurves > 0) THEN
    CurveFound=FindItemInList(Alphas(1),PressureCurve%Name,NumPressureCurves)
    IF (CurveFound /= 0) THEN
      CALL ShowSevereError('GetCurveInput: '//trim(CurrentModuleObject)//'="'//trim(Alphas(1))//'", duplicate curve name.')
      CALL ShowContinueError('...Curve name duplicates one of the Pressure Curves. Names must be unique across all curves.')
      ErrorsFound=.true.
    ENDIF
  ENDIF
  PerfCurve(CurveNum)%Name = Alphas(1)
  PerfCurve(CurveNum)%CurveType = RectangularHyperbola1
  PerfCurve(CurveNum)%ObjectType = CurveType_RectangularHyperbola1
  PerfCurve(CurveNum)%InterpolationType = EVALUATECURVETOLIMITS
  PerfCurve(CurveNum)%Coeff1 = Numbers(1)
  PerfCurve(CurveNum)%Coeff2 = Numbers(2)
  PerfCurve(CurveNum)%Coeff3 = Numbers(3)
  PerfCurve(CurveNum)%Var1Min = Numbers(4)
  PerfCurve(CurveNum)%Var1Max = Numbers(5)
  IF(NumNumbers > 5 .AND. .NOT. lNumericFieldBlanks(6))THEN
    PerfCurve(CurveNum)%CurveMin        = Numbers(6)
    PerfCurve(CurveNum)%CurveMinPresent = .TRUE.
  END IF
  IF(NumNumbers > 6 .AND. .NOT. lNumericFieldBlanks(7))THEN
    PerfCurve(CurveNum)%CurveMax        = Numbers(7)
    PerfCurve(CurveNum)%CurveMaxPresent = .TRUE.
  END IF
  IF (Numbers(4) > Numbers(5)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(4))//'['//TRIM(RoundSigDigits(Numbers(4),2))//'] > '//  &
       TRIM(cNumericFieldNames(5))//' ['//TRIM(RoundSigDigits(Numbers(5),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (NumAlphas .GE. 2) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(2))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for X is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 3) THEN
    IF (.NOT. IsCurveOutputTypeValid(Alphas(3))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Output Unit Type is invalid.')
    END IF
  END IF
END DO !Rectangular Hyperbola Type 1
! cpw22Aug2010 Loop over Rectangular Hyperbola Type 2 curves and load data
CurrentModuleObject='Curve:RectangularHyperbola2'
DO CurveIndex=1,NumRectHyper2
  CALL GetObjectItem(CurrentModuleObject,CurveIndex,Alphas,NumAlphas,Numbers,NumNumbers,IOStatus,     &
                NumBlank=lNumericFieldBlanks,AlphaFieldnames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
  CurveNum = CurveNum+1
  IsNotOK=.FALSE.
  IsBlank=.FALSE.
  CALL VerifyName(Alphas(1),PerfCurve%Name,CurveNum-1,IsNotOK,IsBlank,TRIM(CurrentModuleObject)//' Name')
  IF (IsNotOK) THEN
    ErrorsFound=.true.
    IF (IsBlank) Alphas(1)='xxxxx'
  ENDIF
  ! Need to verify that this name isn't used in Pressure Curves as well.
  IF (NumPressureCurves > 0) THEN
    CurveFound=FindItemInList(Alphas(1),PressureCurve%Name,NumPressureCurves)
    IF (CurveFound /= 0) THEN
      CALL ShowSevereError('GetCurveInput: '//trim(CurrentModuleObject)//'="'//trim(Alphas(1))//'", duplicate curve name.')
      CALL ShowContinueError('...Curve name duplicates one of the Pressure Curves. Names must be unique across all curves.')
      ErrorsFound=.true.
    ENDIF
  ENDIF
  PerfCurve(CurveNum)%Name = Alphas(1)
  PerfCurve(CurveNum)%CurveType = RectangularHyperbola2
  PerfCurve(CurveNum)%ObjectType = CurveType_RectangularHyperbola2
  PerfCurve(CurveNum)%InterpolationType = EVALUATECURVETOLIMITS
  PerfCurve(CurveNum)%Coeff1 = Numbers(1)
  PerfCurve(CurveNum)%Coeff2 = Numbers(2)
  PerfCurve(CurveNum)%Coeff3 = Numbers(3)
  PerfCurve(CurveNum)%Var1Min = Numbers(4)
  PerfCurve(CurveNum)%Var1Max = Numbers(5)
  IF(NumNumbers > 5 .AND. .NOT. lNumericFieldBlanks(6))THEN
    PerfCurve(CurveNum)%CurveMin        = Numbers(6)
    PerfCurve(CurveNum)%CurveMinPresent = .TRUE.
  END IF
  IF(NumNumbers > 6 .AND. .NOT. lNumericFieldBlanks(7))THEN
    PerfCurve(CurveNum)%CurveMax        = Numbers(7)
    PerfCurve(CurveNum)%CurveMaxPresent = .TRUE.
  END IF
  IF (Numbers(4) > Numbers(5)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(4))//'['//TRIM(RoundSigDigits(Numbers(4),2))//'] > '//  &
       TRIM(cNumericFieldNames(5))//' ['//TRIM(RoundSigDigits(Numbers(5),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (NumAlphas .GE. 2) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(2))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for X is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 3) THEN
    IF (.NOT. IsCurveOutputTypeValid(Alphas(3))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Output Unit Type is invalid.')
    END IF
  END IF
END DO !Rectangular Hyperbola Type 2
! cpw22Aug2010 Loop over Exponential Decay curves and load data
CurrentModuleObject='Curve:ExponentialDecay'
DO CurveIndex=1,NumExpDecay
  CALL GetObjectItem(CurrentModuleObject,CurveIndex,Alphas,NumAlphas,Numbers,NumNumbers,IOStatus,     &
                NumBlank=lNumericFieldBlanks,AlphaFieldnames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
  CurveNum = CurveNum+1
  IsNotOK=.FALSE.
  IsBlank=.FALSE.
  CALL VerifyName(Alphas(1),PerfCurve%Name,CurveNum-1,IsNotOK,IsBlank,TRIM(CurrentModuleObject)//' Name')
  IF (IsNotOK) THEN
    ErrorsFound=.true.
    IF (IsBlank) Alphas(1)='xxxxx'
  ENDIF
  ! Need to verify that this name isn't used in Pressure Curves as well.
  IF (NumPressureCurves > 0) THEN
    CurveFound=FindItemInList(Alphas(1),PressureCurve%Name,NumPressureCurves)
    IF (CurveFound /= 0) THEN
      CALL ShowSevereError('GetCurveInput: '//trim(CurrentModuleObject)//'="'//trim(Alphas(1))//'", duplicate curve name.')
      CALL ShowContinueError('...Curve name duplicates one of the Pressure Curves. Names must be unique across all curves.')
      ErrorsFound=.true.
    ENDIF
  ENDIF
  PerfCurve(CurveNum)%Name = Alphas(1)
  PerfCurve(CurveNum)%CurveType = ExponentialDecay
  PerfCurve(CurveNum)%ObjectType = CurveType_ExponentialDecay
  PerfCurve(CurveNum)%InterpolationType = EVALUATECURVETOLIMITS
  PerfCurve(CurveNum)%Coeff1 = Numbers(1)
  PerfCurve(CurveNum)%Coeff2 = Numbers(2)
  PerfCurve(CurveNum)%Coeff3 = Numbers(3)
  PerfCurve(CurveNum)%Var1Min = Numbers(4)
  PerfCurve(CurveNum)%Var1Max = Numbers(5)
  IF(NumNumbers > 5 .AND. .NOT. lNumericFieldBlanks(6))THEN
    PerfCurve(CurveNum)%CurveMin        = Numbers(6)
    PerfCurve(CurveNum)%CurveMinPresent = .TRUE.
  END IF
  IF(NumNumbers > 6 .AND. .NOT. lNumericFieldBlanks(7))THEN
    PerfCurve(CurveNum)%CurveMax        = Numbers(7)
    PerfCurve(CurveNum)%CurveMaxPresent = .TRUE.
  END IF
  IF (Numbers(4) > Numbers(5)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(4))//'['//TRIM(RoundSigDigits(Numbers(4),2))//'] > '//  &
       TRIM(cNumericFieldNames(5))//' ['//TRIM(RoundSigDigits(Numbers(5),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (NumAlphas .GE. 2) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(2))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for X is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 3) THEN
    IF (.NOT. IsCurveOutputTypeValid(Alphas(3))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Output Unit Type is invalid.')
    END IF
  END IF
END DO !Exponential Decay
! ykt July,2011 Loop over DoubleExponential Decay curves and load data
CurrentModuleObject='Curve:DoubleExponentialDecay'
DO CurveIndex=1,NumDoubleExpDecay
  CALL GetObjectItem(CurrentModuleObject,CurveIndex,Alphas,NumAlphas,Numbers,NumNumbers,IOStatus,     &
                NumBlank=lNumericFieldBlanks,AlphaFieldnames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
  CurveNum = CurveNum+1
  IsNotOK=.FALSE.
  IsBlank=.FALSE.
  CALL VerifyName(Alphas(1),PerfCurve%Name,CurveNum-1,IsNotOK,IsBlank,TRIM(CurrentModuleObject)//' Name')
  IF (IsNotOK) THEN
    ErrorsFound=.true.
    IF (IsBlank) Alphas(1)='xxxxx'
  ENDIF
  ! Need to verify that this name isn't used in Pressure Curves as well.
  IF (NumPressureCurves > 0) THEN
    CurveFound=FindItemInList(Alphas(1),PressureCurve%Name,NumPressureCurves)
    IF (CurveFound /= 0) THEN
      CALL ShowSevereError('GetCurveInput: '//trim(CurrentModuleObject)//'="'//trim(Alphas(1))//'", duplicate curve name.')
      CALL ShowContinueError('...Curve name duplicates one of the Pressure Curves. Names must be unique across all curves.')
      ErrorsFound=.true.
    ENDIF
  ENDIF
  PerfCurve(CurveNum)%Name = Alphas(1)
  PerfCurve(CurveNum)%CurveType = DoubleExponentialDecay
  PerfCurve(CurveNum)%ObjectType = CurveType_DoubleExponentialDecay
  PerfCurve(CurveNum)%InterpolationType = EVALUATECURVETOLIMITS
  PerfCurve(CurveNum)%Coeff1 = Numbers(1)
  PerfCurve(CurveNum)%Coeff2 = Numbers(2)
  PerfCurve(CurveNum)%Coeff3 = Numbers(3)
  PerfCurve(CurveNum)%Coeff4 = Numbers(4)
  PerfCurve(CurveNum)%Coeff5 = Numbers(5)
  PerfCurve(CurveNum)%Var1Min = Numbers(6)
  PerfCurve(CurveNum)%Var1Max = Numbers(7)
  IF(NumNumbers > 7 .AND. .NOT. lNumericFieldBlanks(8))THEN
    PerfCurve(CurveNum)%CurveMin        = Numbers(8)
    PerfCurve(CurveNum)%CurveMinPresent = .TRUE.
  END IF
  IF(NumNumbers > 8 .AND. .NOT. lNumericFieldBlanks(9))THEN
    PerfCurve(CurveNum)%CurveMax        = Numbers(9)
    PerfCurve(CurveNum)%CurveMaxPresent = .TRUE.
  END IF
!  IF (Numbers(4) > Numbers(5)) THEN  ! error
!    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
!    CALL ShowContinueError(TRIM(cNumericFieldNames(4))//'['//TRIM(RoundSigDigits(Numbers(4),2))//'] > '//  &
!       TRIM(cNumericFieldNames(5))//' ['//TRIM(RoundSigDigits(Numbers(5),2))//']')
!    ErrorsFound=.true.
!  ENDIF
  IF (NumAlphas .GE. 2) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(2))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Input Unit Type for X is invalid.')
    END IF
  END IF
  IF (NumAlphas .GE. 3) THEN
    IF (.NOT. IsCurveOutputTypeValid(Alphas(3))) THEN
      CALL ShowWarningError('In '//TRIM(CurrentModuleObject)//' named ' // TRIM(Alphas(1)) //   &
                            ' the Output Unit Type is invalid.')
    END IF
  END IF
END DO !Exponential Decay
TableNum = 0
! Loop over one variable tables and load data
CurrentModuleObject='Table:OneIndependentVariable'
DO CurveIndex=1,NumOneVarTab
  CALL GetObjectItem(CurrentModuleObject,CurveIndex,Alphas,NumAlphas,Numbers,NumNumbers,IOStatus,     &
                NumBlank=lNumericFieldBlanks,AlphaFieldnames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
  CurveNum = CurveNum+1
  TableNum = TableNum + 1
  NumTableEntries = (NumNumbers - 5) / 2
  ALLOCATE(TableData(TableNum)%X1(NumTableEntries))
  ALLOCATE(TableData(TableNum)%Y(NumTableEntries))
  IsNotOK=.FALSE.
  IsBlank=.FALSE.
  CALL VerifyName(Alphas(1),PerfCurve%Name,CurveNum-1,IsNotOK,IsBlank,TRIM(CurrentModuleObject)//' Name')
  IF (IsNotOK) THEN
    ErrorsFound=.true.
    IF (IsBlank) Alphas(1)='xxxxx'
  ENDIF
  ! Need to verify that this name isn't used in Pressure Curves as well.
  IF (NumPressureCurves > 0) THEN
    CurveFound=FindItemInList(Alphas(1),PressureCurve%Name,NumPressureCurves)
    IF (CurveFound /= 0) THEN
      CALL ShowSevereError('GetCurveInput: '//trim(CurrentModuleObject)//'="'//trim(Alphas(1))//'", duplicate curve name.')
      CALL ShowContinueError('...Curve name duplicates one of the Pressure Curves. Names must be unique across all curves.')
      ErrorsFound=.true.
    ENDIF
  ENDIF
  PerfCurve(CurveNum)%Name = Alphas(1)
  PerfCurve(CurveNum)%ObjectType = CurveType_TableOneIV
  PerfCurve(CurveNum)%TableIndex = TableNum
  SELECT CASE (Alphas(2))
  CASE('LINEAR')
  PerfCurve(CurveNum)%CurveType = Linear
  TableLookup(TableNum)%InterpolationOrder = 2
  CASE('QUADRATIC')
  PerfCurve(CurveNum)%CurveType = Quadratic
  TableLookup(TableNum)%InterpolationOrder = 3
  CASE('CUBIC')
  PerfCurve(CurveNum)%CurveType = Cubic
  TableLookup(TableNum)%InterpolationOrder = 4
  CASE('QUARTIC')
  PerfCurve(CurveNum)%CurveType = Quartic
  TableLookup(TableNum)%InterpolationOrder = 5
  CASE('EXPONENT')
  PerfCurve(CurveNum)%CurveType = Exponent
  TableLookup(TableNum)%InterpolationOrder = 4
  CASE DEFAULT
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cAlphaFieldNames(2))//' ['//TRIM(Alphas(2))//'] is not a valid choice. ')
    ErrorsFound=.true.
  END SELECT
  SELECT CASE (Alphas(3))
  CASE('LINEARINTERPOLATIONOFTABLE')
    PerfCurve(CurveNum)%InterpolationType = LINEARINTERPOLATIONOFTABLE
  CASE('LAGRANGEINTERPOLATIONLINEAREXTRAPOLATION')
    PerfCurve(CurveNum)%InterpolationType = LAGRANGEINTERPOLATIONLINEAREXTRAPOLATION
  CASE('EVALUATECURVETOLIMITS')
    PerfCurve(CurveNum)%InterpolationType = EVALUATECURVETOLIMITS
  CASE DEFAULT
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cAlphaFieldNames(2))//' ['//TRIM(Alphas(2))//'] is not a valid choice. ')
    ErrorsFound=.true.
  END SELECT
  IF(lNumericFieldBlanks(1))THEN
    PerfCurve(CurveNum)%Var1Min = 99999999999.D0
  ELSE
    PerfCurve(CurveNum)%Var1Min = Numbers(1)
  END IF
  IF(lNumericFieldBlanks(2))THEN
    PerfCurve(CurveNum)%Var1Max = -99999999999.D0
  ELSE
    PerfCurve(CurveNum)%Var1Max = Numbers(2)
  END IF
  IF(.NOT. lNumericFieldBlanks(1) .AND. .NOT. lNumericFieldBlanks(2))THEN
    IF (Numbers(1) > Numbers(2)) THEN  ! error
      CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
      CALL ShowContinueError(TRIM(cNumericFieldNames(1))//' ['//TRIM(RoundSigDigits(Numbers(1),2))//'] > '//  &
         TRIM(cNumericFieldNames(2))//' ['//TRIM(RoundSigDigits(Numbers(2),2))//']')
      ErrorsFound=.true.
    ENDIF
  END IF
  IF (NumAlphas .GE. 4) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(4))) THEN
      CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
      CALL ShowContinueError(TRIM(cAlphaFieldNames(4))//' ['//TRIM(Alphas(4))//'] is invalid')
    END IF
  END IF
  IF (NumAlphas .GE. 5) THEN
    IF (.NOT. IsCurveOutputTypeValid(Alphas(5))) THEN
      CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
      CALL ShowContinueError(TRIM(cAlphaFieldNames(5))//' ['//TRIM(Alphas(5))//'] is invlaid')
    END IF
  END IF
  ! read this value first to allow normalization of min/max table output fields
  IF(.NOT. lNumericFieldBlanks(5))THEN
    TableData(TableNum)%NormalPoint = Numbers(5)
    IF(Numbers(5) .EQ. 0.0D0)THEN
      CALL ShowSevereError('GetTableInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
      CALL ShowContinueError('...'//TRIM(cNumericFieldNames(5))// &
                             ' ['//TRIM(RoundSigDigits(Numbers(5),6))//'] is not a valid choice.')
      CALL ShowContinueError('...Setting Normalization Reference to 1 and the simulation continues.')
      TableData(TableNum)%NormalPoint = 1.0D0
    END IF
  ELSE
    TableData(TableNum)%NormalPoint = 1.0D0
  END IF
  IF(.NOT. lNumericFieldBlanks(3))THEN
    PerfCurve(CurveNum)%CurveMin        = Numbers(3)/TableData(TableNum)%NormalPoint
    PerfCurve(CurveNum)%CurveMinPresent = .TRUE.
  END IF
  IF(.NOT. lNumericFieldBlanks(4))THEN
    PerfCurve(CurveNum)%CurveMax        = Numbers(4)/TableData(TableNum)%NormalPoint
    PerfCurve(CurveNum)%CurveMaxPresent = .TRUE.
  END IF
  MaxTableNums = (NumNumbers-5)/2
  IF(MOD((NumNumbers-5),2) .NE. 0)THEN
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError('The number of data entries must be evenly divisable by 2. Number of data entries = ' &
                           //trim(RoundSigDigits(NumNumbers-5)))
    ErrorsFound=.true.
  ELSE
    DO TableDataIndex = 1, MaxTableNums
      TableData(TableNum)%X1(TableDataIndex) = Numbers((TableDataIndex-1)*2 + 5 + 1)
      TableData(TableNum)%Y(TableDataIndex)  = Numbers((TableDataIndex-1)*2 + 5 + 2)/ &
                                                     TableData(TableNum)%NormalPoint
    END DO
  END IF
  ! convert raw table data to multidimensional array
  ! find number of x variables
  NumXVar = 1
  NextXVar = 1
  TempTableData = TableData
  DO WHILE (NumXVar .LE. MaxTableNums)
    MinTableData = 999999.0D0
    MinTableData = MINVAL(TempTableData(TableNum)%X1)
    DO VarIndex = 1, MaxTableNums
      IF(TempTableData(TableNum)%X1(VarIndex) .EQ. MinTableData)THEN
        TableData(TableNum)%X1(NumXVar) = TempTableData(TableNum)%X1(VarIndex)
        TableData(TableNum)%Y(NumXVar)  = TempTableData(TableNum)%Y(VarIndex)
        TempTableData(TableNum)%X1(VarIndex) = 999999.0D0
        NumXVar = NumXVar + 1
      END IF
    END DO
    NextXVar = NumXVar
  END DO
  ! move table data to performance curve table data structure
  ALLOCATE(PerfCurveTableData(TableNum)%X1(NumXVar-1))
  ALLOCATE(PerfCurveTableData(TableNum)%Y(NumXVar-1,1))
  PerfCurveTableData(TableNum)%X1 = TableData(TableNum)%X1
  DO VarIndex = 1, NumXVar-1
    PerfCurveTableData(TableNum)%Y(VarIndex,1) = TableData(TableNum)%Y(VarIndex)
  END DO
! create curve objects when regression analysis is required
  IF(PerfCurve(CurveNum)%InterpolationType .EQ. EVALUATECURVETOLIMITS)THEN
    SELECT CASE(PerfCurve(CurveNum)%CurveType)
      CASE(LINEAR,QUADRATIC,CUBIC,QUARTIC)
        ALLOCATE(TempArray1(SIZE(PerfCurveTableData(TableNum)%X1)))
        TempArray1 = PerfCurveTableData(TableNum)%X1
        ALLOCATE(TempArray2(SIZE(PerfCurveTableData(TableNum)%Y)))
        DO VarIndex = 1, SIZE(PerfCurveTableData(TableNum)%Y)
         TempArray2(VarIndex) = PerfCurveTableData(TableNum)%Y(VarIndex,1)
        END DO
        CALL SolveRegression(CurveNum,CurrentModuleObject,PerfCurve(CurveNum)%Name,TempArray1,TempArray2)
        DEALLOCATE(TempArray1)
        DEALLOCATE(TempArray2)
      CASE DEFAULT
        CALL ShowWarningError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
        CALL ShowContinueError('The requested regression analysis is not available at this time. Curve type = ' &
                              //Alphas(2))
        PerfCurve(CurveIndex)%InterpolationType = LinearInterpolationOfTable
    END SELECT
  END IF
! move table data to more compact array to allow interpolation using multivariable lookup table method
TableLookup(TableNum)%NumIndependentVars = 1
TableLookup(TableNum)%NumX1Vars = SIZE(PerfCurveTableData(TableNum)%X1)
ALLOCATE(TableLookup(TableNum)%X1Var(TableLookup(TableNum)%NumX1Vars))
ALLOCATE(TableLookup(TableNum)%TableLookupZData(SIZE(PerfCurveTableData(TableNum)%Y),1,1,1,1))
TableLookup(TableNum)%X1Var = PerfCurveTableData(TableNum)%X1
TableLookup(TableNum)%TableLookupZData(:,1,1,1,1) = PerfCurveTableData(TableNum)%Y(:,1)
END DO
! Loop over two variable tables and load data
CurrentModuleObject='Table:TwoIndependentVariables'
DO CurveIndex=1,NumTwoVarTab
  CALL GetObjectItem(CurrentModuleObject,CurveIndex,Alphas,NumAlphas,Numbers,NumNumbers,IOStatus,     &
                NumBlank=lNumericFieldBlanks,AlphaFieldnames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
  CurveNum = CurveNum+1
  TableNum = TableNum + 1
  NumTableEntries = (NumNumbers - 7) / 3
  ALLOCATE(TableData(TableNum)%X1(NumTableEntries))
  ALLOCATE(TableData(TableNum)%X2(NumTableEntries))
  ALLOCATE(TableData(TableNum)%Y(NumTableEntries))
  IsNotOK=.FALSE.
  IsBlank=.FALSE.
  CALL VerifyName(Alphas(1),PerfCurve%Name,CurveNum-1,IsNotOK,IsBlank,TRIM(CurrentModuleObject)//' Name')
  IF (IsNotOK) THEN
    ErrorsFound=.true.
    IF (IsBlank) Alphas(1)='xxxxx'
  ENDIF
  ! Need to verify that this name isn't used in Pressure Curves as well.
  IF (NumPressureCurves > 0) THEN
    CurveFound=FindItemInList(Alphas(1),PressureCurve%Name,NumPressureCurves)
    IF (CurveFound /= 0) THEN
      CALL ShowSevereError('GetCurveInput: '//trim(CurrentModuleObject)//'="'//trim(Alphas(1))//'", duplicate curve name.')
      CALL ShowContinueError('...Curve name duplicates one of the Pressure Curves. Names must be unique across all curves.')
      ErrorsFound=.true.
    ENDIF
  ENDIF
  PerfCurve(CurveNum)%Name = Alphas(1)
  PerfCurve(CurveNum)%ObjectType = CurveType_TableTwoIV
  PerfCurve(CurveNum)%TableIndex = TableNum
  SELECT CASE (Alphas(2))
  CASE('BICUBIC')
  PerfCurve(CurveNum)%CurveType = BiCubic
  TableLookup(TableNum)%InterpolationOrder = 4
  CASE('BIQUADRATIC')
  PerfCurve(CurveNum)%CurveType = BiQuadratic
  TableLookup(TableNum)%InterpolationOrder = 3
  CASE('QUADRATICLINEAR')
  PerfCurve(CurveNum)%CurveType = QuadraticLinear
  TableLookup(TableNum)%InterpolationOrder = 3
  CASE('TRIQUADRATIC')
  PerfCurve(CurveNum)%CurveType = TriQuadratic
  TableLookup(TableNum)%InterpolationOrder = 3
  CASE DEFAULT
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cAlphaFieldNames(2))//' ['//TRIM(Alphas(2))//'] is not a valid choice. ')
    ErrorsFound=.true.
  END SELECT
  SELECT CASE (Alphas(3))
  CASE('LINEARINTERPOLATIONOFTABLE')
    PerfCurve(CurveNum)%InterpolationType = LINEARINTERPOLATIONOFTABLE
  CASE('LAGRANGEINTERPOLATIONLINEAREXTRAPOLATION')
    PerfCurve(CurveNum)%InterpolationType = LAGRANGEINTERPOLATIONLINEAREXTRAPOLATION
  CASE('EVALUATECURVETOLIMITS')
    PerfCurve(CurveNum)%InterpolationType = EVALUATECURVETOLIMITS
  CASE DEFAULT
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cAlphaFieldNames(2))//' ['//TRIM(Alphas(2))//'] is not a valid choice. ')
    ErrorsFound=.true.
  END SELECT
  PerfCurve(CurveNum)%Var1Min = Numbers(1)
  PerfCurve(CurveNum)%Var1Max = Numbers(2)
  PerfCurve(CurveNum)%Var2Min = Numbers(3)
  PerfCurve(CurveNum)%Var2Max = Numbers(4)
  IF (Numbers(1) > Numbers(2)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(1))//' ['//TRIM(RoundSigDigits(Numbers(1),2))//'] > '//  &
       TRIM(cNumericFieldNames(2))//' ['//TRIM(RoundSigDigits(Numbers(2),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (Numbers(3) > Numbers(4)) THEN  ! error
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(3))//' ['//TRIM(RoundSigDigits(Numbers(3),2))//'] > '//  &
       TRIM(cNumericFieldNames(4))//' ['//TRIM(RoundSigDigits(Numbers(4),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (NumAlphas .GE. 4) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(4))) THEN
      CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
      CALL ShowContinueError(TRIM(cAlphaFieldNames(4))//' ['//TRIM(Alphas(4))//'] is invlaid')
    END IF
  END IF
  IF (NumAlphas .GE. 5) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(5))) THEN
      CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
      CALL ShowContinueError(TRIM(cAlphaFieldNames(5))//' ['//TRIM(Alphas(5))//'] is invlaid')
    END IF
  END IF
  IF (NumAlphas .GE. 6) THEN
    IF (.NOT. IsCurveOutputTypeValid(Alphas(6))) THEN
      CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
      CALL ShowContinueError(TRIM(cAlphaFieldNames(6))//' ['//TRIM(Alphas(6))//'] is invlaid')
    END IF
  END IF
  IF(.NOT. lNumericFieldBlanks(7))THEN
    TableData(TableNum)%NormalPoint = Numbers(7)
    IF(Numbers(7) .EQ. 0.0D0)THEN
      CALL ShowSevereError('GetTableInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
      CALL ShowContinueError('...'//TRIM(cNumericFieldNames(7))// &
                             ' ['//TRIM(RoundSigDigits(Numbers(7),6))//'] is not a valid choice.')
      CALL ShowContinueError('...Setting Normalization Reference to 1 and the simulation continues.')
      TableData(TableNum)%NormalPoint = 1.0D0
    END IF
  ELSE
    TableData(TableNum)%NormalPoint = 1.0D0
  END IF
  IF(.NOT. lNumericFieldBlanks(5))THEN
    PerfCurve(CurveNum)%CurveMin        = Numbers(5)/TableData(TableNum)%NormalPoint
    PerfCurve(CurveNum)%CurveMinPresent = .TRUE.
  END IF
  IF(.NOT. lNumericFieldBlanks(6))THEN
    PerfCurve(CurveNum)%CurveMax        = Numbers(6)/TableData(TableNum)%NormalPoint
    PerfCurve(CurveNum)%CurveMaxPresent = .TRUE.
  END IF
  MaxTableNums = (NumNumbers-7)/3
  IF(MOD((NumNumbers-7),3) .NE. 0)THEN
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError('The number of data entries must be evenly divisable by 3. Number of data entries = ' &
                           //trim(RoundSigDigits(NumNumbers-7)))
    ErrorsFound=.true.
  ELSE
    DO TableDataIndex = 1, MaxTableNums
      TableData(TableNum)%X1(TableDataIndex) = Numbers((TableDataIndex-1)*3 + 7 + 1)
      TableData(TableNum)%X2(TableDataIndex) = Numbers((TableDataIndex-1)*3 + 7 + 2)
      TableData(TableNum)%Y(TableDataIndex)  = Numbers((TableDataIndex-1)*3 + 7 + 3)/ &
                                                     TableData(TableNum)%NormalPoint
    END DO
  END IF
!  convert raw table data to multidimensional array
   ! find number of x variables
   ALLOCATE(Xvar(MaxTableNums))
   ALLOCATE(X2var(MaxTableNums))
   NumXVar = 1
   NextXVar = 1
   XVar(1) = 1.0D0
   TempTableData = TableData
   Temp2TableData = TableData
   DO WHILE (NumXVar .LE. MaxTableNums)
     MinTableData = 999999.0D0
     MinTableData = MINVAL(TempTableData(TableNum)%X1)
     DO VarIndex = 1, MaxTableNums
       IF(TempTableData(TableNum)%X1(VarIndex) .EQ. MinTableData)THEN
         TableData(TableNum)%X1(NumXVar) = TempTableData(TableNum)%X1(VarIndex)
         TableData(TableNum)%X2(NumXVar) = TempTableData(TableNum)%X2(VarIndex)
         TableData(TableNum)%Y(NumXVar)  = TempTableData(TableNum)%Y(VarIndex)
         TempTableData(TableNum)%X1(VarIndex) = 999999.0D0
         NumXVar = NumXVar + 1
       END IF
     END DO
     Temp2TableData(TableNum)%X2(NextXVar:NumXVar-1) = &
       TableData(TableNum)%X2(NextXVar:NumXVar-1)
     Temp2TableData(TableNum)%Y(NextXVar:NumXVar-1) = &
       TableData(TableNum)%Y(NextXVar:NumXVar-1)
     DO TempVarIndex = NumXVar-1, NextXVar, -1
       MaxTableDataValue = -999999.0D0
       DO TempVarIndex1 = NextXVar, NumXVar-1
         IF(Temp2TableData(TableNum)%X2(TempVarIndex1) .GT. MaxTableDataValue)THEN
           MaxTableDataValue = Temp2TableData(TableNum)%X2(TempVarIndex1)
         END IF
       END DO
       DO TempVarIndex1 = NextXVar, NumXVar-1
         IF(Temp2TableData(TableNum)%X2(TempVarIndex1) .NE. MaxTableDataValue)CYCLE
           TableData(TableNum)%X2(TempVarIndex) = &
             Temp2TableData(TableNum)%X2(TempVarIndex1)
           TableData(TableNum)%Y(TempVarIndex) = &
             Temp2TableData(TableNum)%Y(TempVarIndex1)
           Temp2TableData(TableNum)%X2(TempVarIndex1) = -999999.0D0
         EXIT
       END DO
     END DO
     NextXVar = NumXVar
   END DO
   ! reorganize table data
     NumXVar = 1
     NumX2Var = 1
     XVar(1)= TableData(TableNum)%X1(1)
     DO VarIndex = 2, MaxTableNums
       IF(TableData(TableNum)%X1(VarIndex) .NE. &
            TableData(TableNum)%X1(VarIndex-1)) THEN
         NumXVar = NumXVar + 1
         XVar(NumXVar)= TableData(TableNum)%X1(VarIndex)
       END IF
     END DO
     X2Var(1) = TableData(TableNum)%X2(1)
     DO VarIndex = 2, MaxTableNums
       FoundNewData = .TRUE.
       DO TempVarIndex = 1, NumX2Var
         IF(TableData(TableNum)%X2(VarIndex) .EQ. &
              X2Var(TempVarIndex)) THEN
           FoundNewData = .FALSE.
         END IF
       END DO
       IF(FoundNewData)THEN
         NumX2Var = NumX2Var + 1
         X2Var(NumX2Var) = TableData(TableNum)%X2(VarIndex)
       END IF
     END DO
     ! move table data to performance curve table data structure
     ALLOCATE(PerfCurveTableData(TableNum)%X1(NumXVar))
     ALLOCATE(PerfCurveTableData(TableNum)%X2(NumX2Var))
     ALLOCATE(PerfCurveTableData(TableNum)%Y(NumXVar,NumX2Var))
     PerfCurveTableData(TableNum)%X1 = -9999999.0D0
     PerfCurveTableData(TableNum)%X2 = -9999999.0D0
     PerfCurveTableData(TableNum)%Y = -9999999.0D0
     DO VarIndex = 1, NumXVar
       PerfCurveTableData(TableNum)%X1(VarIndex) = XVar(VarIndex)
       DO TempVarIndex = 1, NumX2Var
         PerfCurveTableData(TableNum)%X2(TempVarIndex) = X2Var(TempVarIndex)
         DO TempVarIndex1 = 1, MaxTableNums
           IF((TableData(TableNum)%X1(TempVarIndex1) .EQ. &
               PerfCurveTableData(TableNum)%X1(VarIndex)) .AND. &
              (TableData(TableNum)%X2(TempVarIndex1) .EQ. &
               PerfCurveTableData(TableNum)%X2(TempVarIndex)))THEN
             PerfCurveTableData(TableNum)%Y(VarIndex,TempVarIndex) = &
               TableData(TableNum)%Y(TempVarIndex1)
           END IF
         END DO
       END DO
     END DO
     DEALLOCATE(Xvar)
     DEALLOCATE(X2var)
! create curve objects when regression analysis is required
  IF(PerfCurve(CurveNum)%InterpolationType .EQ. EVALUATECURVETOLIMITS)THEN
    SELECT CASE(PerfCurve(CurveNum)%CurveType)
      CASE(BIQUADRATIC,QUADRATICLINEAR)
        ALLOCATE(TempArray1(SIZE(TableData(TableNum)%X1)))
        TempArray1 = TableData(TableNum)%X1
        ALLOCATE(TempArray3(SIZE(TableData(TableNum)%X2)))
        TempArray3 = TableData(TableNum)%X2
        ALLOCATE(TempArray2(SIZE(TableData(TableNum)%Y)))
        DO VarIndex = 1, SIZE(TableData(TableNum)%Y)
         TempArray2(VarIndex) = TableData(TableNum)%Y(VarIndex)
        END DO
        CALL SolveRegression(CurveNum,CurrentModuleObject,PerfCurve(CurveNum)%Name,TempArray1,TempArray2,TempArray3)
        DEALLOCATE(TempArray1)
        DEALLOCATE(TempArray2)
        DEALLOCATE(TempArray3)
      CASE DEFAULT
        CALL ShowWarningError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
        CALL ShowContinueError('The requested regression analysis is not available at this time. Curve type = ' &
                              //Alphas(2))
        PerfCurve(CurveIndex)%InterpolationType = LinearInterpolationOfTable
    END SELECT
  END IF
! move table data to more compact array to allow interpolation using multivariable lookup table method
TableLookup(TableNum)%NumIndependentVars = 2
TableLookup(TableNum)%NumX1Vars = SIZE(PerfCurveTableData(TableNum)%X1)
TableLookup(TableNum)%NumX2Vars = SIZE(PerfCurveTableData(TableNum)%X2)
ALLOCATE(TableLookup(TableNum)%X1Var(TableLookup(TableNum)%NumX1Vars))
ALLOCATE(TableLookup(TableNum)%X2Var(TableLookup(TableNum)%NumX2Vars))
ALLOCATE(TableLookup(TableNum)%TableLookupZData(SIZE(PerfCurveTableData(TableNum)%Y(:,1)),  &
    SIZE(PerfCurveTableData(TableNum)%Y(1,:)),1,1,1))
TableLookup(TableNum)%X1Var = PerfCurveTableData(TableNum)%X1
TableLookup(TableNum)%X2Var = PerfCurveTableData(TableNum)%X2
TableLookup(TableNum)%TableLookupZData(:,:,1,1,1) = PerfCurveTableData(TableNum)%Y(:,:)
END DO
! Loop over multiple variable tables and load data (strict lookup only - no curve creation
CurrentModuleObject='Table:MultiVariableLookup'
TableNum = NumTables
DO CurveIndex=1,NumMultVarLookup
  CALL GetObjectItem(CurrentModuleObject,CurveIndex,Alphas,NumAlphas,Numbers,NumNumbers,IOStatus,     &
                NumBlank=lNumericFieldBlanks,AlphaBlank=lAlphaFieldBlanks,AlphaFieldnames=cAlphaFieldNames, &
                NumericFieldNames=cNumericFieldNames)
  CurveNum = CurveNum+1
  TableNum = TableNum + 1
  IsNotOK=.FALSE.
  IsBlank=.FALSE.
  CALL VerifyName(Alphas(1),PerfCurve%Name,CurveNum-1,IsNotOK,IsBlank,TRIM(CurrentModuleObject)//' Name')
  IF (IsNotOK) THEN
    ErrorsFound=.true.
    IF (IsBlank) Alphas(1)='xxxxx'
  ENDIF
  ! Need to verify that this name isn't used in Pressure Curves as well.
  IF (NumPressureCurves > 0) THEN
    CurveFound=FindItemInList(Alphas(1),PressureCurve%Name,NumPressureCurves)
    IF (CurveFound /= 0) THEN
      CALL ShowSevereError('GetCurveInput: '//trim(CurrentModuleObject)//'="'//trim(Alphas(1))//'", duplicate curve name.')
      CALL ShowContinueError('...Curve name duplicates one of the Pressure Curves. Names must be unique across all curves.')
      ErrorsFound=.true.
    ENDIF
  ENDIF
  PerfCurve(CurveNum)%Name = Alphas(1)
  PerfCurve(CurveNum)%ObjectType = CurveType_TableMultiIV
  PerfCurve(CurveNum)%TableIndex = TableNum
  SELECT CASE (Alphas(2))
    CASE('LINEARINTERPOLATIONOFTABLE')
      PerfCurve(CurveNum)%InterpolationType = LINEARINTERPOLATIONOFTABLE
  CASE('LAGRANGEINTERPOLATIONLINEAREXTRAPOLATION')
      PerfCurve(CurveNum)%InterpolationType = LAGRANGEINTERPOLATIONLINEAREXTRAPOLATION
    CASE('EVALUATECURVETOLIMITS')
     PerfCurve(CurveNum)%InterpolationType = EVALUATECURVETOLIMITS
    CASE DEFAULT
      CALL ShowSevereError('GetTableInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
      CALL ShowContinueError(TRIM(cAlphaFieldNames(2))//' ['//TRIM(Alphas(2))//'] is not a valid choice. ')
      ErrorsFound=.true.
  END SELECT
  SELECT CASE (Alphas(3))
  CASE('LINEAR')
  PerfCurve(CurveNum)%CurveType = Linear
  CASE('QUADRATIC')
  PerfCurve(CurveNum)%CurveType = Quadratic
  CASE('CUBIC')
  PerfCurve(CurveNum)%CurveType = Cubic
  CASE('QUARTIC')
  PerfCurve(CurveNum)%CurveType = Quartic
  CASE('EXPONENT')
  PerfCurve(CurveNum)%CurveType = Exponent
  CASE('BIQUADRATIC')
  PerfCurve(CurveNum)%CurveType = BiQuadratic
  CASE('QUADRATICINEAR')
  PerfCurve(CurveNum)%CurveType = QuadraticLinear
  CASE('BICUBIC')
  PerfCurve(CurveNum)%CurveType = BiCubic
  CASE('TRIQUADRATIC')
  PerfCurve(CurveNum)%CurveType = TriQuadratic
  CASE DEFAULT
    CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cAlphaFieldNames(3))//' ['//TRIM(Alphas(3))//'] is not a valid choice. ')
    ErrorsFound=.true.
  END SELECT
  SELECT CASE (Alphas(4))
    CASE('SINGLELINEINDEPENDENTVARIABLEWITHMATRIX')
      PerfCurve(CurveNum)%DataFormat = SINGLELINEINDEPENDENTVARIABLEWITHMATRIX
    CASE DEFAULT
      CALL ShowSevereError('GetTableInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
      CALL ShowContinueError(TRIM(cAlphaFieldNames(4))//' ['//TRIM(Alphas(4))//'] is not a valid choice. ')
      ErrorsFound=.true.
  END SELECT
  TableLookup(TableNum)%InterpolationOrder = Numbers(1)
  IF(.NOT. lNumericFieldBlanks(2))THEN
    TableData(TableNum)%NormalPoint = Numbers(2)
    IF(Numbers(2) .EQ. 0.0D0)THEN
      CALL ShowSevereError('GetTableInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
      CALL ShowContinueError('...'//TRIM(cNumericFieldNames(2))// &
                             ' ['//TRIM(RoundSigDigits(Numbers(2),6))//'] is not a valid choice.')
      CALL ShowContinueError('...Setting Normalization Reference to 1 and the simulation continues.')
      TableData(TableNum)%NormalPoint = 1.0D0
    END IF
  ELSE
    TableData(TableNum)%NormalPoint = 1.0D0
  END IF
  PerfCurve(CurveNum)%Var1Min = Numbers(3)
  PerfCurve(CurveNum)%Var1Max = Numbers(4)
  PerfCurve(CurveNum)%Var2Min = Numbers(5)
  PerfCurve(CurveNum)%Var2Max = Numbers(6)
  PerfCurve(CurveNum)%Var3Min = Numbers(7)
  PerfCurve(CurveNum)%Var3Max = Numbers(8)
  PerfCurve(CurveNum)%Var4Min = Numbers(9)
  PerfCurve(CurveNum)%Var4Max = Numbers(10)
  PerfCurve(CurveNum)%Var5Min = Numbers(11)
  PerfCurve(CurveNum)%Var5Max = Numbers(12)
  IF (Numbers(3) > Numbers(4)) THEN  ! error
    CALL ShowSevereError('GetTableInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(3))//' ['//TRIM(RoundSigDigits(Numbers(3),2))//'] > '//  &
       TRIM(cNumericFieldNames(4))//' ['//TRIM(RoundSigDigits(Numbers(4),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (Numbers(5) > Numbers(6)) THEN  ! error
    CALL ShowSevereError('GetTableInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(5))//' ['//TRIM(RoundSigDigits(Numbers(5),2))//'] > '//  &
       TRIM(cNumericFieldNames(6))//' ['//TRIM(RoundSigDigits(Numbers(6),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (Numbers(7) > Numbers(8)) THEN  ! error
    CALL ShowSevereError('GetTableInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(7))//' ['//TRIM(RoundSigDigits(Numbers(7),2))//'] > '//  &
       TRIM(cNumericFieldNames(8))//' ['//TRIM(RoundSigDigits(Numbers(8),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (Numbers(9) > Numbers(10)) THEN  ! error
    CALL ShowSevereError('GetTableInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(9))//' ['//TRIM(RoundSigDigits(Numbers(9),2))//'] > '//  &
       TRIM(cNumericFieldNames(10))//' ['//TRIM(RoundSigDigits(Numbers(10),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (Numbers(11) > Numbers(12)) THEN  ! error
    CALL ShowSevereError('GetTableInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError(TRIM(cNumericFieldNames(11))//' ['//TRIM(RoundSigDigits(Numbers(11),2))//'] > '//  &
       TRIM(cNumericFieldNames(12))//' ['//TRIM(RoundSigDigits(Numbers(12),2))//']')
    ErrorsFound=.true.
  ENDIF
  IF (NumAlphas .GE. 8) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(8))) THEN
      CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
      CALL ShowContinueError(TRIM(cAlphaFieldNames(8))//' ['//TRIM(Alphas(8))//'] is invlaid')
    END IF
  END IF
  IF (NumAlphas .GE. 9) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(9))) THEN
      CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
      CALL ShowContinueError(TRIM(cAlphaFieldNames(9))//' ['//TRIM(Alphas(9))//'] is invlaid')
    END IF
  END IF
  IF (NumAlphas .GE. 10) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(10))) THEN
      CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
      CALL ShowContinueError(TRIM(cAlphaFieldNames(10))//' ['//TRIM(Alphas(10))//'] is invlaid')
    END IF
  END IF
  IF (NumAlphas .GE. 11) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(11))) THEN
      CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
      CALL ShowContinueError(TRIM(cAlphaFieldNames(11))//' ['//TRIM(Alphas(11))//'] is invlaid')
    END IF
  END IF
  IF (NumAlphas .GE. 12) THEN
    IF (.NOT. IsCurveInputTypeValid(Alphas(12))) THEN
      CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
      CALL ShowContinueError(TRIM(cAlphaFieldNames(12))//' ['//TRIM(Alphas(12))//'] is invlaid')
    END IF
  END IF
  IF (NumAlphas .GE. 13) THEN
    IF (.NOT. IsCurveOutputTypeValid(Alphas(13))) THEN
      CALL ShowSevereError('GetCurveInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
      CALL ShowContinueError(TRIM(cAlphaFieldNames(13))//' ['//TRIM(Alphas(13))//'] is invlaid')
    END IF
  END IF
  IF(.NOT. lNumericFieldBlanks(13))THEN
    PerfCurve(CurveNum)%CurveMin        = Numbers(13)/TableData(TableNum)%NormalPoint
    PerfCurve(CurveNum)%CurveMinPresent = .TRUE.
  END IF
  IF(.NOT. lNumericFieldBlanks(14))THEN
    PerfCurve(CurveNum)%CurveMax        = Numbers(14)/TableData(TableNum)%NormalPoint
    PerfCurve(CurveNum)%CurveMaxPresent = .TRUE.
  END IF
  IF(Alphas(6) .EQ. 'ASCENDING')THEN
   PerfCurve(CurveNum)%X1SortOrder=ASCENDING
  ELSE IF(Alphas(6) .EQ. 'DESCENDING')THEN
   PerfCurve(CurveNum)%X1SortOrder=DESCENDING
  ELSE
    CALL ShowSevereError('GetTableInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError('...Invalid '//TRIM(cAlphaFieldNames(6))//' = '//TRIM(Alphas(6)))
    ErrorsFound=.true.
  END IF
  IF(Alphas(7) .EQ. 'ASCENDING')THEN
    PerfCurve(CurveNum)%X2SortOrder=ASCENDING
  ELSE IF(Alphas(7) .EQ. 'DESCENDING')THEN
    PerfCurve(CurveNum)%X2SortOrder=DESCENDING
  ELSE
    CALL ShowSevereError('GetTableInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
    CALL ShowContinueError('...Invalid '//TRIM(cAlphaFieldNames(7))//' = '//TRIM(Alphas(7)))
    ErrorsFound=.true.
  END IF
  IF(.NOT. lAlphaFieldBlanks(5))THEN
    ReadFromFile = .TRUE.
    FileName = Alphas(5)
  ELSE
    ReadFromFile = .FALSE.
    FileName = ' '
  END IF
  CALL ReadTableData(CurveNum, CurrentModuleObject, ReadFromFile, FileName, Alphas, Numbers, NumNumbers, ErrorsFound)
  IF(PerfCurve(CurveNum)%InterpolationType .EQ. EVALUATECURVETOLIMITS)THEN
    SELECT CASE(TableLookup(TableNum)%NumIndependentVars)
      CASE(1)
        ALLOCATE(TempArray1(SIZE(TableLookup(TableNum)%TableLookupZData(:,1,1,1,1))))
        ALLOCATE(TempArray2(SIZE(TempArray1)))
        TempArray1 = TableLookup(TableNum)%X1Var
        TempArray2 = TableLookup(TableNum)%TableLookupZData(:,1,1,1,1)
        CALL SolveRegression(CurveNum,CurrentModuleObject,PerfCurve(CurveNum)%Name,TempArray1,TempArray2)
        DEALLOCATE(TempArray1)
        DEALLOCATE(TempArray2)
        ! Save array info in performance table arrays in case the performance table routine is selected in regression routine
        ALLOCATE(PerfCurveTableData(TableNum)%X1(SIZE(TableLookup(TableNum)%X1Var)))
        ALLOCATE(PerfCurveTableData(TableNum)%Y(SIZE(TableLookup(TableNum)%X1Var),1))
        PerfCurveTableData(TableNum)%X1 = TableLookup(TableNum)%X1Var
        PerfCurveTableData(TableNum)%Y(:,1) = TableLookup(TableNum)%TableLookupZData(:,1,1,1,1)
      CASE(2)
        ALLOCATE(TempArray1(SIZE(TableLookup(TableNum)%TableLookupZData(:,:,1,1,1))))
        ALLOCATE(TempArray2(SIZE(TempArray1)))
        ALLOCATE(TempArray3(SIZE(TempArray1)))
        TableDataIndex = 0
        DO VarIndex = 1, TableLookup(TableNum)%NumX1Vars
          DO TempVarIndex = 1, TableLookup(TableNum)%NumX2Vars
            TableDataIndex = TableDataIndex + 1
            TempArray1(TableDataIndex) = TableLookup(TableNum)%X1Var(VarIndex)
            TempArray2(TableDataIndex) = TableLookup(TableNum)%X2Var(TempVarIndex)
            TempArray3(TableDataIndex) = TableLookup(TableNum)%TableLookupZData(VarIndex,TempVarIndex,1,1,1)
          END DO
        END DO
        CALL SolveRegression(CurveNum,CurrentModuleObject,PerfCurve(CurveNum)%Name,TempArray1,TempArray3,TempArray2)
        DEALLOCATE(TempArray1)
        DEALLOCATE(TempArray2)
        DEALLOCATE(TempArray3)
        ! Save array info in performance table arrays in case the performance table routine is selected in regression routine
        ALLOCATE(PerfCurveTableData(TableNum)%X1(SIZE(TableLookup(TableNum)%X1Var)))
        ALLOCATE(PerfCurveTableData(TableNum)%X2(SIZE(TableLookup(TableNum)%X2Var)))
        ALLOCATE(PerfCurveTableData(TableNum)%Y(SIZE(TableLookup(TableNum)%X1Var),SIZE(TableLookup(TableNum)%X2Var)))
        PerfCurveTableData(TableNum)%X1 = TableLookup(TableNum)%X1Var
        PerfCurveTableData(TableNum)%X2 = TableLookup(TableNum)%X2Var
        PerfCurveTableData(TableNum)%Y(:,:) = TableLookup(TableNum)%TableLookupZData(:,:,1,1,1)
    CASE DEFAULT
      CALL ShowSevereError('GetTableInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
      CALL ShowContinueError('...Invalid '//TRIM(cAlphaFieldNames(2))//' = '//TRIM(Alphas(2)))
      CALL ShowContinueError('...Choice not allowed with more than 2 indpendent variables.')
      ErrorsFound=.true.
    END SELECT
  ELSE
    SELECT CASE(TableLookup(TableNum)%NumIndependentVars)
      CASE(1)
        ! Save array info in performance table arrays in case the performance table routine is selected in regression routine
        ALLOCATE(PerfCurveTableData(TableNum)%X1(SIZE(TableLookup(TableNum)%X1Var)))
        ALLOCATE(PerfCurveTableData(TableNum)%Y(SIZE(TableLookup(TableNum)%X1Var),1))
        PerfCurveTableData(TableNum)%X1 = TableLookup(TableNum)%X1Var
        PerfCurveTableData(TableNum)%Y(:,1) = TableLookup(TableNum)%TableLookupZData(:,1,1,1,1)
        ! if linear interpolation of table is selected, switch interpolation type
      CASE(2)
        ! Save array info in performance table arrays in case the performance table routine is selected in regression routine
        ALLOCATE(PerfCurveTableData(TableNum)%X1(SIZE(TableLookup(TableNum)%X1Var)))
        ALLOCATE(PerfCurveTableData(TableNum)%X2(SIZE(TableLookup(TableNum)%X2Var)))
        ALLOCATE(PerfCurveTableData(TableNum)%Y(SIZE(TableLookup(TableNum)%X1Var),SIZE(TableLookup(TableNum)%X2Var)))
        PerfCurveTableData(TableNum)%X1 = TableLookup(TableNum)%X1Var
        PerfCurveTableData(TableNum)%X2 = TableLookup(TableNum)%X2Var
        PerfCurveTableData(TableNum)%Y(:,:) = TableLookup(TableNum)%TableLookupZData(:,:,1,1,1)
        ! if linear interpolation of table is selected, switch interpolation type
    CASE DEFAULT
      ! if linear interpolation of table is selected, fatal if more than 2 independent variables
      IF(PerfCurve(CurveNum)%InterpolationType == LINEARINTERPOLATIONOFTABLE)THEN
        CALL ShowSevereError('GetTableInput: For '//TRIM(CurrentModuleObject)//': '//TRIM(Alphas(1)))
        CALL ShowContinueError('...Invalid '//TRIM(cAlphaFieldNames(2))//' = '//TRIM(Alphas(2)))
        CALL ShowContinueError('...Choice not allowed with more than 2 indpendent variables.')
        ErrorsFound=.true.
      END IF
    END SELECT
  END IF
END DO
IF (ErrorsFound) THEN
  CALL ShowFatalError('GetCurveInput: Errors found in getting Curve Objects.  Preceding condition(s) cause termination.')
END IF
RETURN
END SUBROUTINE GetCurveInput
All Procedures
AbortEnergyPlus AbsoluteAirMass ActivateDemandManagers ActivateEMSControls AddBlankKeys addChargesToOperand AddCompSizeTableEntry AddEndUseSubcategory AddError addFootNoteSubTable AddInstruction AddMeter addMonthlyCharge AddMonthlyFieldSetInput AddMonthlyReport AddNeighborInformation AddObjectDefandParse addOperand AddRecordFromSection AddRecordToOutputVariableStructure AddSectionDef AddShadowRelateTableEntry AddSQLiteComponentSizingRecord AddSQLiteComponentSizingRecord AddSQLiteSystemSizingRecord AddSQLiteSystemSizingRecord AddSQLiteZoneSizingRecord AddSQLiteZoneSizingRecord AddTOCEntry AddTOCZoneLoadComponentTable AddToOutputVariableList AddVariablesForMonthlyReport AddVariableSlatBlind AddWindow AdjustAirSetpointsforOpTempCntrl AdjustCBF AdjustCBF AdjustChangeInLoadByEMSControls AdjustChangeInLoadByHowServed AdjustChangeInLoadForLastStageUpperRangeLimit AdjustCoolingSetPointforTempAndHumidityControl adjusthhat AdjustPumpFlowRequestByEMSControls AdjustReportingHourAndMinutes AdjustVBGap AdvanceRootFinder AFECFR AFECOI AFECPD AFECPF AFEDMP AFEDOP AFEDWC AFEELR AFEEXF AFEFAN AFEHEX AFEHOP AFEPLR AFESCR AFESEL AFESOP AFETMU AirflowNetworkVentingControl AirMass AIRMOV AllocateAirflowNetworkData AllocateAirHeatBalArrays AllocateAndInitData AllocateAndSetUpVentReports AllocateCFSStateHourlyData AllocateForCFSRefPointsGeometry AllocateForCFSRefPointsState AllocateHeatBalArrays AllocateLoadComponentArrays AllocateModuleArrays AllocateModuleArrays AllocateSurfaceHeatBalArrays AllocateWeatherData angle_2dvector AnisoSkyViewFactors AnyPlantLoopSidesNeedSim AnyPlantSplitterMixerLacksContinuity AreaPolygon ArgCheck array_to_vector ASHRAETauModel ASHWAT_OffNormalProperties ASHWAT_Solar ASHWAT_Thermal ASSIGNMENT (=) AssignNodeNumber AssignReportNumber AssignResourceTypeNum AssignReverseConstructionNumber AssignVariablePt AttachCustomMeters AttachMeters AuditBranches AUTOTDMA BaseThermalPropertySet_Diffusivity BeginEnvrnInitializeRuntimeLanguage BetweenDates BetweenGlassForcedFlow BetweenGlassShadeForcedFlow BetweenGlassShadeNaturalFlow BisectionMethod BlindBeamBeamTrans BlindOpticsBeam BlindOpticsDiffuse BoreholeResistance BoundValueToNodeMinMaxAvail BoundValueToWithinTwoValues BracketRoot BranchPressureDrop BrentMethod BuildGap BuildKeyVarList Calc4PipeFanCoil Calc_EN673 Calc_ISO15099 CalcActiveTranspiredCollector CalcAggregateLoad CalcAirflowNetworkAirBalance CalcAirflowNetworkCO2Balance CalcAirflowNetworkGCBalance CalcAirflowNetworkHeatBalance CalcAirflowNetworkMoisBalance CalcAirFlowSimple CalcAirLoopSplitter CalcAirMixer CalcAirToAirGenericHeatExch CalcAirToAirPlateHeatExch CalcAirZoneReturnPlenum CalcAirZoneSupplyPlenum CalcAlamdariHammondStableHorizontal CalcAlamdariHammondUnstableHorizontal CalcAlamdariHammondVerticalWall CalcAngleFactorMRT CalcApproximateViewFactors CalcASHRAEDetailedIntConvCoeff CalcASHRAESimpExtConvectCoeff CalcASHRAESimpleIntConvCoeff CalcASHRAEVerticalWall CalcATMixer CalcAwbiHattonHeatedFloor CalcAwbiHattonHeatedWall CalcBasinHeaterPower CalcBasinHeaterPowerForMultiModeDXCoil CalcBeamSolarOnWinRevealSurface CalcBeamSolDiffuseReflFactors CalcBeamSolSpecularReflFactors CalcBeausoleilMorrisonMixedAssistedWall CalcBeausoleilMorrisonMixedOpposingWall CalcBeausoleilMorrisonMixedStableCeiling CalcBeausoleilMorrisonMixedStableFloor CalcBeausoleilMorrisonMixedUnstableCeiling CalcBeausoleilMorrisonMixedUnstableFloor CalcBLASTAbsorberModel CalcBlockenWindward CalcBoilerModel CalcBoilerModel CalcBottomFluxCoefficents CalcBottomSurfTemp CalcBuriedPipeSoil CalcCBF CalcCBF CalcCBVAV CalcCeilingDiffuserInletCorr CalcCeilingDiffuserIntConvCoeff CalcChillerHeaterModel CalcChillerIPLV CalcChillerModel CalcClearRoof CalcCoilUAbyEffectNTU CalcColdestSetPoint CalcComplexWindowOverlap CalcComplexWindowThermal CalcCompSuctionTempResidual CalcCondEntSetPoint CalcConnectionsDrainTemp CalcConnectionsFlowRates CalcConnectionsHeatRecovery CalcConstCOPChillerModel CalcConvCoeffAbsPlateAndWater CalcConvCoeffBetweenPlates CalcCoolBeam CalcCoolTower CalcCoordinateTransformation CalcCoPlanarNess CalcCostEstimate CalcCTGeneratorModel CalcDayltgCoefficients CalcDayltgCoeffsMapPoints CalcDayltgCoeffsRefMapPoints CalcDayltgCoeffsRefPoints CalcDesiccantBalancedHeatExch CalcDesignSpecificationOutdoorAir CalcDesuperheaterHeatingCoil CalcDesuperheaterWaterHeater CalcDetailedHcInForDVModel CalcDetailedSystem CalcDetailedTransSystem CalcDetailFlatFinCoolingCoil CalcDetIceStorLMTDstar CalcDiffTSysAvailMgr CalcDirectAir CalcDirectEvapCooler CalcDirectResearchSpecialEvapCooler CalcDoe2DXCoil CalcDOE2Leeward CalcDOE2Windward CalcDryFinEffCoef CalcDryIndirectEvapCooler CalcDuct CalcDXCoilStandardRating CalcDXHeatingCoil CalcEarthTube CalcEcoRoof CalcEffectiveness CalcEffectiveSHR CalcEffectiveSHR CalcEffectiveSHR CalcEffectiveSHR CalcElecSteamHumidifier CalcElectricBaseboard CalcElectricChillerHeatRecovery CalcElectricChillerModel CalcElectricEIRChillerModel CalcElectricHeatingCoil CalcEmmelRoof CalcEmmelVertical CalcEngineChillerHeatRec CalcEngineDrivenChillerModel CalcEQLOpticalProperty CalcEQLWindowOpticalProperty CalcEQLWindowSHGCAndTransNormal CalcEQLWindowStandardRatings CalcEQLWindowUvalue CalcEquipmentDrainTemp CalcEquipmentFlowRates CalcExhaustAbsorberChillerModel CalcExhaustAbsorberHeaterModel CalcExteriorVentedCavity CalcFisherPedersenCeilDiffuserCeiling CalcFisherPedersenCeilDiffuserFloor CalcFisherPedersenCeilDiffuserWalls CalcFluidHeatExchanger CalcFohannoPolidoriVerticalWall CalcFollowOATempSetPoint CalcFollowSysNodeTempSetPoint CalcFourPipeIndUnit CalcFrameDividerShadow CalcFuelCellAuxHeater CalcFuelCellGeneratorModel CalcFuelCellGenHeatRecovery CalcFurnaceOutput CalcFurnaceResidual CalcGasAbsorberChillerModel CalcGasAbsorberHeaterModel CalcGasCooler CalcGasHeatingCoil CalcGenericDesiccantDehumidifier CalcGoldsteinNovoselacCeilingDiffuserFloor CalcGoldsteinNovoselacCeilingDiffuserWall CalcGoldsteinNovoselacCeilingDiffuserWindow CalcGroundTempSetPoint CalcGroundwaterWell CalcGshpModel CalcGshpModel CalcGTChillerModel CalcHeatBalanceAir CalcHeatBalanceInsideSurf CalcHeatBalanceInsideSurf CalcHeatBalanceOutsideSurf CalcHeatBalanceOutsideSurf CalcHeatBalFiniteDiff CalcHeatBalHAMT CalcHeatPumpWaterHeater CalcHeatTransCoeffAndCoverTemp CalcHfExteriorSparrow CalcHighTempRadiantSystem CalcHighTempRadiantSystemSP CalcHiTurnOffSysAvailMgr CalcHiTurnOnSysAvailMgr CalcHnASHRAETARPExterior CalcHPCoolingSimple CalcHPHeatingSimple CalcHPWHDXCoil CalcHWBaseboard CalcHXAssistedCoolingCoil CalcHXEffectTerm CalcHybridVentSysAvailMgr CalcIBesselFunc CalcICEngineGeneratorModel CalcICEngineGenHeatRecovery CalcIceStorageCapacity CalcIceStorageCharge CalcIceStorageDischarge CalcIceStorageDormant CalcICSSolarCollector CalcIdealCondEntSetPoint CalcIfSetpointMet CalcIndirectAbsorberModel CalcIndirectResearchSpecialEvapCooler CalcInteriorRadExchange CalcInteriorSolarDistribution CalcInteriorSolarOverlaps CalcInteriorWinTransDifSolInitialDistribution CalcISO15099WindowIntConvCoeff CalcKaradagChilledCeiling CalcKBesselFunc CalcKhalifaEq3WallAwayFromHeat CalcKhalifaEq4CeilingAwayFromHeat CalcKhalifaEq5WallsNearHeat CalcKhalifaEq6NonHeatedWalls CalcKhalifaEq7Ceiling CalcLoadCenterThermalLoad CalcLoTurnOffSysAvailMgr CalcLoTurnOnSysAvailMgr CalcLowTempCFloRadiantSystem CalcLowTempCFloRadSysComps CalcLowTempElecRadiantSystem CalcLowTempHydrRadiantSystem CalcLowTempHydrRadSysComps CalcMatrixInverse CalcMcAdams CalcMerkelVariableSpeedTower CalcMicroCHPNoNormalizeGeneratorModel CalcMinIntWinSolidAngs CalcMitchell CalcMixedAirSetPoint CalcMoistureBalanceEMPD CalcMoreNodeInfo CalcMoWITTLeeward CalcMoWITTWindward CalcMSHeatPump CalcMTGeneratorModel CalcMultiSpeedDXCoil CalcMultiSpeedDXCoilCooling CalcMultiSpeedDXCoilHeating CalcMultiStageElectricHeatingCoil CalcMultiStageGasHeatingCoil CalcMultiZoneAverageCoolingSetPoint CalcMultiZoneAverageHeatingSetPoint CalcMultiZoneAverageMaxHumSetPoint CalcMultiZoneAverageMinHumSetPoint CalcMultiZoneMaxHumSetPoint CalcMultiZoneMinHumSetPoint CalcMundtModel CalcNCycSysAvailMgr CalcNewZoneHeatCoolFlowRates CalcNewZoneHeatOnlyFlowRates CalcNodeMassFlows CalcNominalWindowCond CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNusselt CalcNusseltJurges CalcNVentSysAvailMgr CalcOAController CalcOAMassFlow CalcOAMassFlow CalcOAMixer CalcOAOnlyMassFlow CalcOAPretreatSetPoint CalcOAUnitCoilComps CalcObstrMultiplier CalcOptStartSysAvailMgr CalcOtherSideDemand CalcOutdoorAirUnit CalcOutsideAirSetPoint CalcOutsideSurfTemp CalcParallelPIU CalcPassiveExteriorBaffleGap CalcPassiveSystem CalcPassiveTranspiredCollector CalcPerSolarBeam CalcPipeHeatTransCoef CalcPipesHeatTransfer CalcPipeTransBeam CalcPlantValves CalcPollution CalcPolyhedronVolume CalcPolynomCoef CalcPondGroundHeatExchanger CalcPredictedHumidityRatio CalcPredictedSystemLoad CalcPTUnit CalcPumps CalcPurchAirLoads CalcPurchAirMinOAMassFlow CalcPurchAirMixedAir CalcPVTcollectors CalcQiceChargeMaxByChiller CalcQiceChargeMaxByITS CalcQiceDischageMax CalcRABFlowSetPoint CalcRackSystem CalcRadSysHXEffectTerm CalcRadTemp CalcRainCollector CalcReformEIRChillerModel CalcResearchSpecialPartLoad CalcReturnAirPath CalcRfFlrCoordinateTransformation CalcSandiaPV CalcSatVapPressFromTemp CalcSchedOffSysAvailMgr CalcSchedOnSysAvailMgr CalcSchedSysAvailMgr CalcScheduledDualSetPoint CalcScheduledSetPoint CalcScreenTransmittance CalcScriptF CalcSeriesPIU CalcSetpointTempTarget CalcSHRUserDefinedCurves CalcSimpleController CalcSimpleHeatingCoil CalcSimplePV CalcSingleSpeedEvapFluidCooler CalcSingleSpeedTower CalcSingZoneClSetPoint CalcSingZoneHtSetPoint CalcSingZoneMaxHumSetPoint CalcSingZoneMinHumSetPoint CalcSingZoneRhSetPoint CalcSkySolDiffuseReflFactors CalcSolarCollector CalcSolarFlux CalcSolidDesiccantDehumidifier CalcSourceFlux CalcSourceTempCoefficents CalcSparrowLeeward CalcSparrowWindward CalcSpecialDayTypes CalcStandAloneERV CalcStandardRatings CalcStaticProperties CalcSteamAirCoil CalcSteamBaseboard CalcSurfaceCentroid CalcSurfaceGroundHeatExchanger CalcSystemEnergyUse CalcSZOneStageCoolingSetPt CalcSZOneStageHeatingSetPt CalcTankTemp CalcTDDTransSolAniso CalcTDDTransSolHorizon CalcTDDTransSolIso CalcTempDistModel CalcTempIntegral CalcTESCoilChargeOnlyMode CalcTESCoilCoolingAndChargeMode CalcTESCoilCoolingAndDischargeMode CalcTESCoilCoolingOnlyMode CalcTESCoilDischargeOnlyMode CalcTESCoilOffMode CalcTESIceStorageTank CalcTESWaterStorageTank CalcThermalChimney CalcThermalComfortAdaptiveASH55 CalcThermalComfortAdaptiveCEN15251 CalcThermalComfortFanger CalcThermalComfortKSU CalcThermalComfortPierce CalcThermalComfortSimpleASH55 CalcTimeNeeded CalcTopFluxCoefficents CalcTopSurfTemp CalcTotalFLux CalcTotCapSHR CalcTotCapSHR_VSWSHP CalcTransAbsorProduct CalcTransRefAbsOfCover CalcTRNSYSPV CalcTrombeWallIntConvCoeff CalcTwoSpeedDXCoilIEERResidual CalcTwoSpeedDXCoilStandardRating CalcTwoSpeedEvapFluidCooler CalcTwoSpeedTower CalcUAIce CalcUCSDCV CalcUCSDDV CalcUCSDUE CalcUCSDUI CalculateAirChillerSets CalculateBasisLength CalculateCase CalculateCoil CalculateCompressors CalculateCondensers CalculateCTFs CalculateDailySolarCoeffs CalculateDayOfWeek CalculateEpsFromNTUandZ CalculateExponentialMatrix CalculateFuncResults CalculateGammas CalculateInverseMatrix CalculateMoodyFrictionFactor CalculateNTUfromEpsAndZ CalculatePollution CalculateSecondary CalculateSubcoolers CalculateSunDirectionCosines CalculateTransCompressors CalculateWalkIn CalculateWaterUseage CalculateWaterUseage CalculateWindowBeamProperties CalculateZoneMRT CalculateZoneVolume CalcUnitaryCoolingSystem CalcUnitaryHeatingSystem CalcUnitarySuppHeatingSystem CalcUnitarySuppSystemtoSP CalcUnitarySystemLoadResidual CalcUnitarySystemToLoad CalcUnitHeater CalcUnitHeaterComponents CalcUnitVentilator CalcUnitVentilatorComponents CalcUnmetPlantDemand CalcUpdateHeatRecovery CalcUpdateHeatRecovery CalcUserDefinedInsideHcModel CalcUserDefinedOutsideHcModel CalcVariableSpeedTower CalcVarSpeedCoilCooling CalcVarSpeedCoilHeating CalcVarSpeedHeatPump CalcVarSpeedHeatPump CalcVAVVS CalcVentilatedSlab CalcVentilatedSlabComps CalcVentilatedSlabRadComps CalcVentSlabHXEffectTerm CalcVerticalGroundHeatExchanger CalcViewFactorToShelf CalcVRF CalcVRFCondenser CalcVRFCoolingCoil CalcVSTowerApproach CalcWallCoordinateTransformation CalcWaltonStableHorizontalOrTilt CalcWaltonUnstableHorizontalOrTilt CalcWarmestSetPoint CalcWarmestSetPointTempFlow CalcWaterMainsTemp CalcWaterSource CalcWaterStorageTank CalcWaterThermalTankMixed CalcWaterThermalTankStratified CalcWaterThermalTankZoneGains CalcWaterToAirHeatpump CalcWatertoAirHPCooling CalcWatertoAirHPHeating CalcWaterToAirResidual CalcWatertoWaterHPCooling CalcWatertoWaterHPHeating CalcWaterUseZoneGains CalcWetIndirectEvapCooler CalcWindowACOutput CalcWindowBlindProperties CalcWindowHeatBalance CalcWindowProfileAngles CalcWindowScreenProperties CalcWindowStaticProperties CalcWindPressure CalcWindPressureCoeffs CalcWindTurbine CalcWinFrameAndDividerTemps CalcWinTransDifSolInitialDistribution CalcWrapperModel CalcZoneAirComfortSetpoints CalcZoneAirTempSetpoints CalcZoneComponentLoadSums CalcZoneDehumidifier CalcZoneEvaporativeCoolerUnit CalcZoneLeavingConditions CalcZoneMassBalance CalcZonePipesHeatGain CalcZoneSums CartesianPipeCellInformation_ctor CellType_IsFieldCell CFSHasControlledShade CFSNGlz CFSRefPointPosFactor CFSRefPointSolidAngle CFSShadeAndBeamInitialization CFSUFactor cGetCoilAirOutletNode cGetCoilSteamInletNode cGetCoilSteamOutletNode CharPreDefTableEntry CheckActuatorNode CheckAndAddAirNodeNumber CheckAndFixCFSLayer CheckAndReadCustomSprectrumData CheckAndReadFaults CheckAndSetConstructionProperties CheckBracketRoundOff CheckBranchForOASys CheckCachedIPErrors CheckCFSStates CheckCoilWaterInletNode CheckControllerListOrder CheckControllerLists CheckConvexity CheckCostEstimateInput CheckCreatedZoneItemName CheckCurveLimitsForIPLV CheckCurveLimitsForStandardRatings CheckDayScheduleValueMinMax CheckDXCoolingCoilInOASysExists CheckFDSurfaceTempLimits CheckFFSchedule CheckFluidPropertyName CheckForActualFileName CheckForBalancedFlow CheckForControllerWaterCoil CheckForGeometricTransform CheckForGeometricTransform CheckForMisMatchedEnvironmentSpecifications CheckForOutOfRangeTempResult CheckForOutOfRangeTemps CheckForRequestedReporting CheckForRunawayPlantTemps CheckForSensorAndSetpointNode CheckGasCoefs CheckHeatingCoilSchedule CheckHXAssistedCoolingCoilSchedule CheckIFAnyEMS CheckIFAnyIdealCondEntSetPoint CheckIfAnyPlant CheckIfNodeSetpointManagedByEMS CheckIncrementRoundOff CheckInternalConsistency CheckLightsReplaceableMinMaxForZone CheckLocationValidity CheckLoopExitNode CheckLowerUpperBracket CheckMarkedNodes CheckMaxActiveController CheckMaxConstraint CheckMicroCHPThermalBalance CheckMinActiveController CheckMinConstraint checkMinimumMonthlyCharge CheckMinMaxCurveBoundaries CheckMinMaxRange CheckModelBoundOutput_HumRat CheckModelBoundOutput_Temp CheckModelBounds CheckModelBoundsHumRatEq CheckModelBoundsRH_HumRatEq CheckModelBoundsRH_TempEq CheckModelBoundsTempEq CheckNodeConnections CheckNodeSetPoint CheckNonSingularity CheckOAControllerName CheckOutAirNodeNumber CheckPlantConvergence CheckPlantMixerSplitterConsistency CheckPlantOnAbort CheckPollutionMeterReporting CheckRefrigerationInput CheckReportVariable CheckRootFinderCandidate CheckRootFinderConvergence CheckScheduledSurfaceGains CheckScheduleValue CheckScheduleValueMinMax Checksetpoints CheckSimpleController CheckSlope CheckSteamCoilSchedule CheckSubSurfaceMiscellaneous CheckSysSizing CheckSystemBranchFlow CheckTDDsAndLightShelvesInDaylitZones CheckThisAirSystemForSizing CheckThisZoneForSizing CheckThreading CheckUniqueNodes CheckUnitarySysCoilInOASysExists CheckUsedConstructions CheckValidSimulationObjects CheckWarmupConvergence CheckWaterCoilSchedule CheckWeatherFileValidity CheckWindowShadingControlFrameDivider CheckZoneEquipmentList CheckZoneSizing CHKBKS CHKGSS CHKSBS CLIP CLIPPOLY CloseDFSFile CloseMiscOpenFiles CloseMoistureBalanceEMPD CloseOutOpenFiles CloseOutputFiles CloseOutputTabularFile CloseReportIllumMaps CloseSocket CloseWeatherFile CoilAreaFracIter CoilCompletelyDry CoilCompletelyWet CoilOutletStreamCondition CoilPartWetPartDry COMMAND_ARGUMENT_COUNT CompactObjectsCheck CompareTwoVectors ComplexFenestrationLuminances ComputeDelayedComponents ComputeDifSolExcZonesWIZWindows ComputeIntSolarAbsorpFactors ComputeIntSWAbsorpFactors ComputeIntThermalAbsorpFactors ComputeLifeCycleCostAndReport ComputeLoadComponentDecayCurve ComputeNominalUwithConvCoeffs ComputePresentValue ComputeTariff ComputeTaxAndDepreciation ComputeWinShadeAbsorpFactors CondOutTempResidual ConstructBasis ControlCBVAVOutput ControlCompOutput ControlCompOutput ControlCoolBeam ControlCoolingSystem ControlCycWindACOutput ControlDesiccantDehumidifier ControlDXHeatingSystem ControlDXSystem ControlFluidHeatExchanger ControlHeatingSystem ControlHumidifier ControlMSHPOutput ControlPTUnitOutput ControlPVTcollector ControlReformEIRChillerModel ControlSuppHeatSystem ControlUnitarySystemOutput ControlUnitarySystemtoLoad ControlUnitarySystemtoSP ControlVRF ControlVSEvapUnitToMeetLoad ControlVSHPOutput ControlVSHPOutput ConvectionFactor ConvertCasetoLower ConvertCasetoUpper ConvertIP ConvertIPdelta ConvertToElementTag ConvertToEscaped CoolBeamResidual CoolingCoil CoolWaterHumRatResidual CoolWaterTempResidual CoolWatertoAirHPHumRatResidual CoolWatertoAirHPTempResidual CorrectZoneAirTemp CorrectZoneContaminants CorrectZoneHumRat CostInfoOut CPCW CPHW CreateBoundaryList CreateBoundaryListCount CreateCategoryNativeVariables CreateCellArray CreateCurrentDateTimeString CreateDefaultComputation CreateEnergyReportStructure CreateFCfactorConstructions CreateHVACStepFullString CreateHVACTimeIntervalString CreateHVACTimeString CreateNewellAreaVector CreateNewellSurfaceNormalVector CreatePartitionCenterList CreatePartitionRegionList CreatePredefinedMonthlyReports CreateRegionList CreateRegionListCount CreateShadedWindowConstruction CreateSQLiteConstructionsTable CreateSQLiteConstructionsTable CreateSQLiteDatabase CreateSQLiteDatabase CreateSQLiteDaylightMap CreateSQLiteDaylightMap CreateSQLiteDaylightMapTitle CreateSQLiteDaylightMapTitle CreateSQLiteEnvironmentPeriodRecord CreateSQLiteEnvironmentPeriodRecord CreateSQLiteErrorRecord CreateSQLiteErrorRecord CreateSQLiteInfiltrationTable CreateSQLiteInfiltrationTable CreateSQLiteMaterialsTable CreateSQLiteMaterialsTable CreateSQLiteMeterDictionaryRecord CreateSQLiteMeterDictionaryRecord CreateSQLiteMeterRecord CreateSQLiteMeterRecord CreateSQLiteNominalBaseboardHeatTable CreateSQLiteNominalBaseboardHeatTable CreateSQLiteNominalElectricEquipmentTable CreateSQLiteNominalElectricEquipmentTable CreateSQLiteNominalGasEquipmentTable CreateSQLiteNominalGasEquipmentTable CreateSQLiteNominalHotWaterEquipmentTable CreateSQLiteNominalHotWaterEquipmentTable CreateSQLiteNominalLightingTable CreateSQLiteNominalLightingTable CreateSQLiteNominalOtherEquipmentTable CreateSQLiteNominalOtherEquipmentTable CreateSQLiteNominalPeopleTable CreateSQLiteNominalPeopleTable CreateSQLiteNominalSteamEquipmentTable CreateSQLiteNominalSteamEquipmentTable CreateSQLiteReportVariableDataRecord CreateSQLiteReportVariableDataRecord CreateSQLiteReportVariableDictionaryRecord CreateSQLiteReportVariableDictionaryRecord CreateSQLiteRoomAirModelTable CreateSQLiteRoomAirModelTable CreateSQLiteSchedulesTable CreateSQLiteSimulationsRecord CreateSQLiteSimulationsRecord CreateSQLiteStringTableRecord CreateSQLiteSurfacesTable CreateSQLiteSurfacesTable CreateSQLiteTabularDataRecords CreateSQLiteTabularDataRecords CreateSQLiteTimeIndexRecord CreateSQLiteTimeIndexRecord CreateSQLiteVentilationTable CreateSQLiteVentilationTable CreateSQLiteZoneGroupTable CreateSQLiteZoneGroupTable CreateSQLiteZoneListTable CreateSQLiteZoneListTable CreateSQLiteZoneTable CreateSQLiteZoneTable CreateStormWindowConstructions CreateSysTimeIntervalString CreateTCConstructions CreateTimeIntervalString CreateTimeString CreatExtBooundCondName CreateZoneExtendedOutput CreateZoneExtendedOutput CrossProduct CrossProduct cSurfaceClass CTRANS CurveValue DateToString DateToStringWithMonth DaylghtAltAndAzimuth DayltgAveInteriorReflectance DayltgClosestObstruction DayltgCrossProduct DayltgCurrentExtHorizIllum DayltgDirectIllumComplexFenestration DayltgDirectSunDiskComplexFenestration DayltgElecLightingControl DayltgExtHorizIllum DayltgGlare DayltgGlarePositionFactor DayltgGlareWithIntWins DayltgHitBetWinObstruction DayltgHitInteriorObstruction DayltgHitObstruction DayltgInteriorIllum DayltgInteriorMapIllum DayltgInteriorTDDIllum DayltgInterReflectedIllum DayltgInterReflectedIllumComplexFenestration DayltgInterReflIllFrIntWins DayltgLuminousEfficacy DayltgPierceSurface DayltgSetupAdjZoneListsAndPointers DayltgSkyLuminance DayltgSurfaceLumFromSun dCheckScheduleValueMinMax1 dCheckScheduleValueMinMax2 DeallocateLoadComponentArrays DebugRootFinder DecodeHHMMField DecodeMonDayHrMin DeflectionTemperatures DeflectionWidths DegradF DElightDaylightCoefficients DElightDaylightCoefficients DElightElecLtgCtrl DElightElecLtgCtrl DElightFreeMemory DElightFreeMemory DElightInputGenerator DElightInputGenerator DElightOutputGenerator DElightOutputGenerator DensityCFSFillGas Depth DERIV DetailsForSurfaces DetectOscillatingZoneTemp DetermineAzimuthAndTilt DetermineBranchFlowRequest DetermineBuildingFloorArea DetermineDateTokens DetermineFrequency DetermineIndexGroupFromMeterGroup DetermineIndexGroupKeyFromMeterName DetermineMaxBackSurfaces DetermineMeterIPUnits DetermineMinuteForReporting DeterminePolygonOverlap DetermineShadowingCombinations DetermineSunUpDown DevelopMesh DiffuseAverage DiffuseAverageProfAngGnd DiffuseAverageProfAngSky DisplayMaterialRoughness DisplayNumberandString DisplaySimDaysProgress DisplayString distance DistributeBBElecRadGains DistributeBBRadGains DistributeBBSteamRadGains DistributeHTRadGains DistributePlantLoad DistributePressureOnBranch DistributeTDDAbsorbedSolar DistributeUserDefinedPlantLoad DL_RES_r2 DLAG DOE2DXCoilHumRatResidual DOE2DXCoilHumRatResidual DOE2DXCoilResidual DOE2DXCoilResidual DOE2DXCoilResidual DoEndOfIterationOperations DomainRectangle_Contains DOMakeUPPERCase DoOneTimeInitializations DOSameString DoShadeControl DoStartOfTimeStepInitializations DownInterpolate4HistoryValues DumpAirLoopStatistics DumpCurrentLineBuffer DUMPVD DUMPVR DXCoilCyclingHumRatResidual DXCoilCyclingHumRatResidual DXCoilCyclingResidual DXCoilCyclingResidual DXCoilVarSpeedHumRatResidual DXCoilVarSpeedHumRatResidual DXCoilVarSpeedResidual DXCoilVarSpeedResidual DXFOut DXFOutLines DXFOutWireFrame DXHeatingCoilResidual DXHeatingCoilResidual DXHeatingCoilResidual DynamicClothingModel DynamicExtConvSurfaceClassification DynamicIntConvSurfaceClassification EchoOutActuatorKeyChoices EchoOutInternalVariableChoices EffectiveEPSLB EffectiveEPSLF EIRChillerHeatRecovery EN673ISO10292 EncodeMonDayHrMin EndEnergyPlus EndUniqueNodeCheck EnthalpyResidual epElapsedTime epGetTimeUsed epGetTimeUsedperCall epStartTime epStopTime epSummaryTimes eptime EQLWindowInsideEffectiveEmiss EQLWindowOutsideEffectiveEmiss EQLWindowSurfaceHeatBalance EquationsSolver ERF EstimateHEXSurfaceArea EvalInsideMovableInsulation EvalOutsideMovableInsulation EvaluateAdiabaticSurfaceTemperature EvaluateBasementCellTemperature EvaluateCellNeighborDirections evaluateChargeBlock evaluateChargeSimple EvaluateExpression EvaluateExtHcModels EvaluateFarfieldBoundaryTemperature EvaluateFarfieldCharacteristics EvaluateFieldCellTemperature EvaluateGroundSurfaceTemperature EvaluateIntHcModels EvaluateLoopSetPointLoad EvaluateNeighborCharacteristics evaluateQualify evaluateRatchet EvaluateSoilRhoCp EvaluateStack EvolveParaUCSDCV ExitCalcController ExpandComplexState ExpressAsCashFlows ExtendObjectDefinition ExteriorBCEqns ExternalInterfaceExchangeVariables ExternalInterfaceInitializeErlVariable ExternalInterfaceSetErlVariable ExternalInterfaceSetSchedule ExtOrIntShadeNaturalFlow Fabric_EstimateDiffuseProps FACSKY FalsePositionMethod FEQX FI FigureACAncillaries FigureAirEnthalpy FigureAirHeatCap FigureAuxilHeatGasHeatCap FigureBeamSolDiffuseReflFactors FigureBeamSolSpecularReflFactors FigureConstGradPattern FigureDayltgCoeffsAtPointsForSunPosition FigureDayltgCoeffsAtPointsForWindowElements FigureDayltgCoeffsAtPointsSetupForWindow FigureElectricalStorageZoneGains FigureFuelCellZoneGains FigureFuelEnthalpy FigureFuelHeatCap FigureGaseousWaterEnthalpy FigureHeightPattern FigureHXleavingGasHeatCap FigureInverterZoneGains FigureLHVofFuel FigureLiquidWaterEnthalpy FigureLiquidWaterHeatCap FigureMapPointDayltgFactorsToAddIllums FigureMicroCHPZoneGains FigureNDheightInZone FigurePowerConditioningLosses FigureProductGasesEnthalpy FigureProductGasHeatCap FigureRefPointDayltgFactorsToAddIllums FigureRefrigerationZoneGains FigureSolarBeamAtTimestep FigureSunCosines FigureSurfMapPattern FigureTDDZoneGains FigureTransformerZoneGains FigureTransientConstraints FigureTwoGradInterpPattern FILJAC FillBasisElement FillDefaultsSWP FillRemainingPredefinedEntries FillWeatherPredefinedEntries film filmg filmi filmPillar FILSKY FinalizeCFS FinalizeCFSLAYER FinalRateCoils FindAirLoopBranchConnection FindAirPlantCondenserLoopFromBranchList FindAllNumbersinList FindArrayIndex FindCompSPInput FindCompSPLoad FindCondenserLoopBranchConnection FindControlledZoneIndexFromSystemNodeNumberForZone FindDeltaTempRangeInput FindDemandSideMatch FindEMSVariable FindFirstLastPtr FindFirstRecord FindGlycol FindHXDemandSideLoopFlow FindInBasis FindItem FindIteminList FindIteminSortedList FindItemInVariableList FindLoopSideInCallingOrder FindNextRecord FindNonSpace FindNumberinList FindOAMixerMatchForOASystem FindPlantLoopBranchConnection FindRangeBasedOrUncontrolledInput FindRangeVariable FindRefrigerant FindRootSimpleController FindStratifiedTankSensedTemp FindTariffIndex FindTDDPipe FindUnitNumber FinishDebugOutputFiles FixViewFactors FluidCellInformation_ctor FM_BEAM FM_DIFF FM_F FNU forcedventilation FourPipeInductionUnitHasMixer FourPipeIUCoolingResidual FourPipeIUHeatingResidual FRA FrostControl FrostControlSetPointLimit FrostControlSetPointLimit FuelCellProductGasEnthResidual FUN FuncDetermineCoolantWaterExitTemp FuncDetermineCWMdotForInternalFlowControl FuncDetermineEngineTemp FV GasElecHeatingCoilResidual GASSES90 GassesLow GatherBEPSResultsForTimestep GatherBinResultsForTimestep GatherComponentLoadsHVAC GatherComponentLoadsIntGain GatherComponentLoadsSurfAbsFact GatherComponentLoadsSurface GatherForEconomics GatherForPredefinedReport GatherHeatGainReport GatherMonthlyResultsForTimestep GatherPeakDemandForTimestep GatherSourceEnergyEndUseResultsForTimestep GaussElimination generate_ears GenerateDElightDaylightCoefficients GenerateDElightDaylightCoefficients GeneratorPowerOutput GenericCrack GenOutputVariablesAuditReport Get2DMatrix Get2DMatrixDimensions GET_COMMAND GET_COMMAND_ARGUMENT Get_Environment_Variable GetActualDXCoilIndex GetAirBranchIndex GetAirFlowFlag GetAirflowNetworkInput GetAirHeatBalanceInput GetAirLoopAvailabilityManager GetAirModelDatas GetAirNodeData GetAirPathData GetAngleFactorList GetATMixer GetATMixerOutNode GetATMixerPriNode GetATMixers GetATMixerSecNode GetAttShdSurfaceData GetAverageTempByType GetBaseboardInput GetBaseboardInput GetBasementFloorHeatFlux GetBasementWallHeatFlux GetBLASTAbsorberInput GetBoilerInput GetBoilerInput GetBranchData GetBranchFanTypeName GetBranchFlow GetBranchInput GetBranchList GetBranchListInput GetBuildingData GetCBVAV GetCellWidths GetCellWidthsCount GetChildrenData GetChillerheaterInput GetCoilAirFlowRate GetCoilAirFlowRateVariableSpeed GetCoilAirInletNode GetCoilAirOutletNode GetCoilAvailScheduleIndex GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacityByIndexType GetCoilCapacityVariableSpeed GetCoilCondenserInletNode GetCoilControlNodeNum GetCoilGroupTypeNum GetCoilIndex GetCoilIndex GetCoilIndex GetCoilIndexVariableSpeed GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNodeVariableSpeed GetCoilMaxSteamFlowRate GetCoilMaxWaterFlowRate GetCoilMaxWaterFlowRate GetCoilMaxWaterFlowRate GetCoilObjectTypeNum GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNodeVariableSpeed GetCoilSteamInletNode GetCoilSteamOutletNode GetCoilTypeNum GetCoilWaterInletNode GetCoilWaterInletNode GetCoilWaterOutletNode GetColumnUsingTabs GetComfortSetpoints GetComponentData GetCondFDInput GetConductivityGlycol GetConnectorList GetConnectorListInput GetConstCOPChillerInput GetConstructData GetControlledZoneIndex GetControllerActuatorNodeNum GetControllerInput GetCoolBeams GetCoolingCoilTypeNameAndIndex GetCooltower GetCostEstimateInput GetCrossVentData GetCTGeneratorInput GetCTGeneratorResults GetCurrentHVACTime GetCurrentMeterValue GetCurrentScheduleValue GetCurveCheck GetCurveIndex GetCurveInput GetCurveMinMaxValues GetCurveName GetCurveObjectTypeNum GetCurveType GetCustomMeterInput GetDaylightingParametersDetaild GetDaylightingParametersInput GetDayScheduleIndex GetDemandManagerInput GetDemandManagerListInput GetDensityGlycol GetDesiccantDehumidifierInput GetDesignDayData GetDesignLightingLevelForZone GetDetShdSurfaceData GetDirectAirInput GetDisplacementVentData GetDSTData GetDualDuctInput GetDualDuctOutdoorAirRecircUse GetDuctInput GetDXCoilAirFlow GetDXCoilAvailSchPtr GetDXCoilBypassedFlowFrac GetDXCoilCapFTCurveIndex GetDXCoilIndex GetDXCoilNumberOfSpeeds GetDXCoils GetDXCoolingSystemInput GetDXHeatPumpSystemInput GetEarthTube GetElecReformEIRChillerInput GetElectricBaseboardInput GetElectricChillerInput GetElectricEIRChillerInput GetEMSInput GetEngineDrivenChillerInput GetEnvironmentalImpactFactorInfo GetEvapFluidCoolerInput GetEvapInput GetExhaustAbsorberInput GetExhaustAirInletNode GetExteriorEnergyUseInput GetExtVentedCavityIndex GetExtVentedCavityIndex GetExtVentedCavityTsColl GetExtVentedCavityTsColl GetFanAvailSchPtr GetFanCoilIndex GetFanCoilInletAirNode GetFanCoilMixedAirNode GetFanCoilOutAirNode GetFanCoilReturnAirNode GetFanCoilUnits GetFanCoilZoneInletAirNode GetFanDesignVolumeFlowRate GetFanIndex GetFanIndexForTwoSpeedCoil GetFanInletNode GetFanInput GetFanOutletNode GetFanPower GetFanSpeedRatioCurveIndex GetFanType GetFanVolFlow GetFarfieldTemp GetFirstBranchInletNodeName GetFluidCoolerInput GetFluidDensityTemperatureLimits GetFluidHeatExchangerInput GetFluidPropertiesData GetFluidSpecificHeatTemperatureLimits GetFrameAndDividerData GetFuelCellGeneratorInput GetFuelCellGeneratorResults GetFuelFactorInfo GetFurnaceInput GetGasAbsorberInput GetGeneratorFuelSupplyInput GetGeometryParameters GetGlycolNameByIndex GetGroundheatExchangerInput GetGroundReflectances GetGroundTemps GetGshpInput GetGshpInput GetGTChillerInput GetHeatBalanceInput GetHeatBalHAMTInput GetHeatExchangerObjectTypeNum GetHeatingCoilIndex GetHeatingCoilInput GetHeatingCoilNumberOfStages GetHeatingCoilPLFCurveIndex GetHeatingCoilTypeNum GetHeatReclaimSourceIndex GetHeatRecoveryInput GetHighTempRadiantSystem GetHPCoolingCoilIndex GetHTSubSurfaceData GetHTSurfaceData GetHTSurfExtVentedCavityData GetHumidifierInput GetHVACSingleDuctSysIndex GetHWBaseboardInput GetHXAssistedCoolingCoilInput GetHXCoilAirFlowRate GetHXCoilType GetHXCoilTypeAndName GetHXDXCoilIndex GetHXDXCoilName GetHybridVentilationControlStatus GetHybridVentilationInputs GetICEGeneratorResults GetICEngineGeneratorInput GetIceStorageInput GetIDFRecordsStats GetIndirectAbsorberInput GetIndUnits GetInputEconomicsChargeBlock GetInputEconomicsChargeSimple GetInputEconomicsComputation GetInputEconomicsCurrencyType GetInputEconomicsQualify GetInputEconomicsRatchet GetInputEconomicsTariff GetInputEconomicsVariable GetInputForLifeCycleCost GetInputFuelAndPollutionFactors GetInputLifeCycleCostNonrecurringCost GetInputLifeCycleCostParameters GetInputLifeCycleCostRecurringCosts GetInputLifeCycleCostUseAdjustment GetInputLifeCycleCostUsePriceEscalation GetInputTabularMonthly GetInputTabularPredefined GetInputTabularStyle GetInputTabularTimeBins GetInputViewFactors GetInputViewFactorsbyName GetInputZoneEvaporativeCoolerUnit GetInstantMeterValue GetInternalBranchData GetInternalHeatGainsInput GetInternalVariableValue GetInternalVariableValue GetInternalVariableValueExternalInterface GetInternalVariableValueExternalInterface GetInterpolatedSatProp GetInterpValue GetIntMassSurfaceData GetLastBranchOutletNodeName GetLastWord GetLightWellData GetListOfObjectsInIDD GetListofSectionsinInput GetLocationInfo GetLoopMixer GetLoopSidePumpIndex GetLoopSplitter GetLowTempRadiantSystem GetMaterialData GetMatrixInput getMaxAndSum GetMeteredVariables GetMeterIndex GetMeterResourceType GetMicroCHPGeneratorInput GetMicroCHPGeneratorResults GetMinOATCompressor GetMixerInput GetMixerInput GetMoistureBalanceEMPDInput GetMonthlyCostForResource GetMovableInsulationData GetMSHeatPumpInput GetMTGeneratorExhaustNode GetMTGeneratorInput GetMTGeneratorResults GetMundtData GetNewUnitNumber GetNextEnvironment GetNodeConnectionType GetNodeList GetNodeListsInput GetNodeNums GetNTUforCrossFlowBothUnmixed GetNumberOfSchedules GetNumberOfSurfaceLists GetNumberOfSurfListVentSlab GetNumChildren GetNumMeteredVariables GetNumOAControllers GetNumOAMixers GetNumOASystems GetNumObjectsFound GetNumObjectsInIDD GetNumRangeCheckErrorsFound GetNumSectionsFound GetNumSectionsinInput GetNumSegmentsForHorizontalTrenches GetNumSplitterMixerInConntrList GetOACompListNumber GetOACompName GetOACompType GetOACompTypeNum GetOAControllerInputs GetOAMixerIndex GetOAMixerInletNodeNumber GetOAMixerInputs GetOAMixerMixedNodeNumber GetOAMixerNodeNumbers GetOAMixerReliefNodeNumber GetOAMixerReturnNodeNumber GetOARequirements GetOASysControllerListIndex GetOASysNumCoolingCoils GetOASysNumHeatingCoils GetOASysNumSimpControllers GetOASystemNumber GetObjectDefInIDD GetObjectDefMaxArgs GetObjectItem GetObjectItemfromFile GetObjectItemNum GetOnlySingleNode GetOperationSchemeInput GetOSCData GetOSCMData GetOutAirNodesInput GetOutdoorAirUnitInputs GetOutdoorAirUnitOutAirNode GetOutdoorAirUnitReturnAirNode GetOutdoorAirUnitZoneInletNode GetOutsideAirSysInputs GetOutsideEnergySourcesInput GetParentData GetPipeInput GetPipesHeatTransfer GetPipingSystemsInput GetPIUs GetPlantAvailabilityManager GetPlantInput GetPlantLoopData GetPlantOperationInput GetPlantProfileInput GetPlantSizingInput GetPlantValvesInput GetPollutionFactorInput GetPondGroundHeatExchanger GetPowerManagerInput GetPressureCurveTypeAndIndex GetPressureSystemInput GetPreviousHVACTime GetProjectControlData GetProjectData GetPTUnit GetPTUnitMixedAirNode GetPTUnitOutAirNode GetPTUnitReturnAirNode GetPTUnitZoneInletAirNode GetPumpInput GetPurchasedAir GetPurchasedAirMixedAirHumRat GetPurchasedAirMixedAirTemp GetPurchasedAirOutAirMassFlow GetPurchasedAirReturnAirNode GetPurchasedAirZoneInletAirNode GetPVGeneratorResults GetPVInput GetPVTcollectorsInput GetPVTThermalPowerProduction GetQualityRefrig GetRecordLocations GetRectDetShdSurfaceData GetRectSubSurfaces GetRectSurfaces GetRefrigeratedRackIndex GetRefrigerationInput GetReportVariableInput GetRequiredMassFlowRate GetResidCrossFlowBothUnmixed GetResourceTypeChar GetReturnAirNodeForZone GetReturnAirPathInput GetRoomAirModelParameters GetRunPeriodData GetRunPeriodDesignData GetRuntimeLanguageUserInput GetSatDensityRefrig GetSatEnthalpyRefrig GetSatPressureRefrig GetSatSpecificHeatRefrig GetSatTemperatureRefrig GetScheduledSurfaceGains GetScheduleIndex GetScheduleMaxValue GetScheduleMinValue GetScheduleName GetScheduleType GetScheduleValuesForDay GetSecondaryInletNode GetSecondaryOutletNode GetSetPointManagerInputs GetShadingSurfReflectanceData GetShadowingInput GetShelfInput GetSimpleAirModelInputs GetSimpleShdSurfaceData GetSimpleWatertoAirHPInput GetSingleDayScheduleValues GetSiteAtmosphereData GetSizingParams GetSnowGroundRefModifiers GetSolarCollectorInput GetSpecialDayPeriodData GetSpecificHeatGlycol getSpecificUnitDivider getSpecificUnitIndex getSpecificUnitMultiplier GetSplitterInput GetSplitterInput GetSplitterNodeNumbers GetSplitterOutletNumber GetStandAloneERV GetStandAloneERVNodes GetStandAloneERVOutAirNode GetStandAloneERVReturnAirNode GetStandAloneERVZoneInletAirNode GetStandardMeterResourceType GetSteamBaseboardInput GetSteamCoilAvailScheduleIndex GetSteamCoilControlNodeNum GetSteamCoilIndex GetSteamCoilInput GetSTM GetStormWindowData GetSupHeatDensityRefrig GetSupHeatEnthalpyRefrig GetSupHeatPressureRefrig GetSupplyAirFlowRate GetSupplyAirFlowRate GetSupplyAirInletNode GetSupplyInletNode GetSupplyOutletNode GetSurfaceCountForOSCM GetSurfaceData GetSurfaceGroundHeatExchanger GetSurfaceHeatTransferAlgorithmOverrides GetSurfaceIndecesForOSCM GetSurfaceListsInputs GetSurfHBDataForMundtModel GetSurfHBDataForTempDistModel GetSysAvailManagerInputs GetSysAvailManagerListInputs GetSysInput GetSystemNodeNumberForZone GetSystemSizingInput GetTDDInput GetTESCoilIndex GetTESCoilInput GetThermalChimney GetTowerInput GetTranspiredCollectorIndex GetTranspiredCollectorInput GetTypeOfCoil GetUFADZoneData GetUnitarySystemDXCoolingCoilIndex GetUnitarySystemInput GetUnitarySystemOAHeatCoolCoil GetUnitConversion GetUnitHeaterInput GetUnitsString GetUnitSubString GetUnitVentilatorInput GetUnitVentilatorMixedAirNode GetUnitVentilatorOutAirNode GetUnitVentilatorReturnAirNode GetUnitVentilatorZoneInletAirNode GetUserConvectionCoefficients GetUserDefinedComponents GetUserDefinedOpSchemeInput GetUserDefinedPatternData GetUTSCTsColl GetVariableKeyCountandType GetVariableKeyCountandType GetVariableKeys GetVariableKeys GetVariableTypeAndIndex GetVariableUnitsString GetVarSpeedCoilInput GetVentilatedSlabInput GetVertices GetViscosityGlycol GetVRFInput GetVSCoilCondenserInletNode GetVSCoilMinOATCompressor GetVSCoilNumOfSpeeds GetWaterCoilAvailScheduleIndex GetWaterCoilCapacity GetWaterCoilIndex GetWaterCoilInput GetWaterMainsTemperatures GetWaterManagerInput GetWaterSource GetWaterThermalTankInput GetWatertoAirHPInput GetWatertoWaterHPInput GetWaterUseInput GetWeatherProperties GetWeatherStation GetWindowAC GetWindowACMixedAirNode GetWindowACOutAirNode GetWindowACReturnAirNode GetWindowACZoneInletAirNode GetWindowGapAirflowControlData GetWindowGlassSpectralData GetWindowShadingControlData GetWindTurbineInput GetWrapperInput GetWTGeneratorResults GetZoneAirDistribution GetZoneAirLoopEquipment GetZoneAirSetpoints GetZoneAndZoneListNames GetZoneContaminanInputs GetZoneContaminanSetpoints GetZoneData GetZoneDehumidifierInput GetZoneDehumidifierNodeNumber GetZoneEqAvailabilityManager GetZoneEquipment GetZoneEquipmentData GetZoneEquipmentData1 GetZoneInfilAirChangeRate GetZoneLoads GetZonePlenumInput GetZoneSizingInput GLtoAMB GoAhead guess HasFractionalScheduleValue hatter HCInWindowStandardRatings HConvGap HcUCSDCV HcUCSDDV HcUCSDUF HeatingCoilVarSpeedCycResidual HeatingCoilVarSpeedResidual HeatPumpRunFrac HeatPumpRunFrac HeatPumpRunFrac HeatWatertoAirHPTempResidual Height HEMINT HIC_ASHRAE HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterHeatingCoilResidual HRadPar HTRANS HTRANS0 HTRANS1 HWBaseboardUAResidual HXAssistDXCoilResidual HXAssistedCoolCoilHRResidual HXAssistedCoolCoilHRResidual HXAssistedCoolCoilTempResidual HXAssistedCoolCoilTempResidual HXDemandSideLoopFlowResidual HybridVentilationControl IAM iCheckScheduleValue ICSCollectorAnalyticalSoluton iGetCoilAirOutletNode iGetCoilSteamInletNode iGetCoilSteamOutletNode INCLOS incrementEconVar IncrementInstMeterCache incrementSteps incrementTableEntry InitAirflowNetwork InitAirflowNetworkData InitAirHeatBalance InitAirLoops InitAirLoopSplitter InitAirMixer InitAirTerminalUserDefined InitAirZoneReturnPlenum InitAirZoneSupplyPlenum InitATMixer InitBaseboard InitBaseboard InitBLASTAbsorberModel InitBoiler InitBoiler InitBoreholeHXSimVars InitBSDFWindows InitCBVAV InitCoilUserDefined InitComplexWindows InitComponentNodes InitConductionTransferFunctions InitConnections InitConstCOPChiller InitController InitCoolBeam InitCTGenerators InitCurveReporting InitDaylightingDevices InitDemandManagers InitDesiccantDehumidifier InitDetailedIceStorage InitDirectAir InitDualDuct InitDuct InitDXCoil InitDXCoolingSystem InitDXHeatPumpSystem InitElecReformEIRChiller InitElectricBaseboard InitElectricChiller InitElectricEIRChiller InitEMS InitEMSControlledConstructions InitEMSControlledSurfaceProperties InitEnergyReports InitEngineDrivenChiller InitEquivalentLayerWindowCalculations InitEvapCooler InitEvapFluidCooler InitExhaustAbsorber InitExteriorConvectionCoeff InitFan InitFanCoilUnits InitFluidCooler InitFluidHeatExchanger InitFuelCellGenerators InitFurnace InitGasAbsorber InitGlassOpticalCalculations InitGshp InitGshp InitGTChiller InitHeatBalance InitHeatBalFiniteDiff InitHeatBalHAMT InitHeatingCoil InitHeatRecovery InitHighTempRadiantSystem InitHumidifier InitHWBaseboard InitHXAssistedCoolingCoil InitHybridVentSysAvailMgr InitialInitHeatBalFiniteDiff InitializeCFSDaylighting InitializeCFSStateData InitializeComponentSizingTable InitializeConstructionsTables InitializeDaylightMapTables InitializeEnvironmentPeriodsTable InitializeErrorsTable InitializeGlycolTempLimits InitializeHeatTransferPipes InitializeIndexes InitializeIndexes InitializeLoops InitializeMaterialsTable InitializeMeters initializeMonetaryUnit InitializeNominalBaseboardHeatTable InitializeNominalElectricEquipmentTable InitializeNominalGasEquipmentTable InitializeNominalHotWaterEquipmentTable InitializeNominalInfiltrationTable InitializeNominalLightingTable InitializeNominalOtherEquipmentTable InitializeNominalPeopleTable InitializeNominalSteamEquipmentTable InitializeNominalVentilationTable InitializeOperatingMode InitializeOutput InitializePipes InitializePredefinedMonthlyTitles InitializePsychRoutines InitializePumps InitializeRefrigerantLimits InitializeReportMeterDataDictionaryTable InitializeReportMeterDataTables InitializeReportVariableDataDictionaryTable InitializeReportVariableDataTables InitializeRoomAirModelTable InitializeRootFinder InitializeRuntimeLanguage InitializeSchedulesTable InitializeSimulationsTable InitializeSQLiteTables InitializeSurfacesTable InitializeSystemSizingTable InitializeTabularDataTable InitializeTabularDataTable InitializeTabularDataView InitializeTabularDataView InitializeTabularMonthly InitializeTimeIndicesTable InitializeViews InitializeWeather InitializeZoneGroupTable InitializeZoneInfoTable InitializeZoneListTable InitializeZoneSizingTable InitICEngineGenerators InitIndirectAbsorpChiller InitIndUnit InitInteriorConvectionCoeffs InitInteriorRadExchange InitInternalHeatGains InitIntSolarDistribution InitLoadBasedControl InitLoadDistribution InitLowTempRadiantSystem InitMicroCHPNoNormalizeGenerators InitMoistureBalanceEMPD InitMSHeatPump InitMTGenerators InitMundtModel InitOAController InitOAMixer InitOneTimePlantSizingInfo InitOutAirNodes InitOutdoorAirUnit InitOutsideAirSys InitPipesHeatTransfer InitPipingSystems InitPIU InitPlantProfile InitPlantUserComponent InitPlantValves InitPollutionMeterReporting InitPondGroundHeatExchanger InitPressureDrop InitPTUnit InitPurchasedAir InitPVTcollectors InitRefrigeration InitRefrigerationPlantConnections InitReturnAirPath InitSecretObjects InitSetPointManagers InitSimpleIceStorage InitSimpleMixingConvectiveHeatGains InitSimpleWatertoAirHP InitSimVars InitSimVars InitSimVars InitSimVars InitSolarCalculations InitSolarCollector InitSolarHeatGains InitSolReflRecSurf InitStandAloneERV InitSteamBaseboard InitSteamCoil InitSurfaceGroundHeatExchanger InitSurfaceHeatBalance InitSys InitSysAvailManagers InitSystemOutputRequired InitTempDistModel InitTESCoil InitThermalAndFluxHistories InitThermalComfort InitTower InitTranspiredCollector InitTRNSYSPV InitUCSDCV InitUCSDDV InitUCSDUF InitUniqueNodeCheck InitUnitarySystems InitUnitHeater InitUnitVentilator InitVarSpeedCoil InitVentilatedSlab InitVRF InitWaterCoil InitWaterSource InitWaterThermalTank InitWatertoAirHP InitWatertoWaterHP InitWindowAC InitWindTurbine InitWrapper InitZoneAirLoopEquipment InitZoneAirSetpoints InitZoneAirUserDefined InitZoneContSetpoints InitZoneDehumidifier InitZoneEquipment InitZoneEvaporativeCoolerUnit InPolygon InsertCurrencySymbol int_times_vector INTCPT Integer_IsInRange IntegerIsWithinTwoValues IntegerToString InterConnectTwoPlantLoopSides InteriorBCEqns InteriorNodeEqns InternalRangeCheck InternalSetupTankDemandComponent InternalSetupTankSupplyComponent interp INTERP InterpBlind InterpDefValuesForGlycolConc Interpolate Interpolate_Lagrange InterpolateBetweenFourValues InterpolateBetweenTwoValues InterpolatePipeTransBeam InterpProfAng InterpProfSlatAng InterpretWeatherDataLine InterpSlatAng InterpSw InterpValuesForGlycolConc IntInterfaceNodeEqns IntPreDefTableEntry IntToStr Invert3By3Matrix InvertMatrix InvJulianDay IPTrimSigDigits iRoundSigDigits IS_BEAM IS_DIFF IS_DSRATIO IS_F IS_LWP IS_OPENNESS IS_SWP isCompLoadRepReq IsControlledShade IsConverged_CurrentToPrevIteration IsConverged_PipeCurrentToPrevIteration IsCurveInputTypeValid IsCurveOutputTypeValid isExternalInterfaceErlVariable IsGlazeLayerX IsGZSLayer isInQuadrilateral IsInRange isInTriangle IsLeapYear IsNodeOnSetPtManager IsParentObject IsParentObjectCompSet IsShadingLayer IssueSevereAlphaInputFieldError IssueSevereInputFieldError IssueSevereRealInputFieldError IsValidConnectionType IsVBLayer isWithinRange ITERATE IterateRootFinder iTrimSigDigits JGDate JulianDay LClimb LDSumMax LDSumMean LEEDtariffReporting LimitCoilCapacity LimitController LimitTUCapacity LinesOut linint LoadEquipList LoadInterface LogicalToInteger LogicalToInteger LogPlantConvergencePoints lookupOperator LookUpScheduleValue LookUpSeason LookupSItoIP lubksb LUBKSB ludcmp LUDCMP LUdecomposition LUsolution MakeAnchorName MakeHVACTimeIntervalString MakeMirrorSurface MakeRectangularVertices MakeRelativeRectangularVertices MakeTransition MakeUPPERCase ManageAirflowNetworkBalance ManageAirHeatBalance ManageAirLoops ManageAirModel ManageBranchInput ManageControllers ManageCoolTower ManageDemand ManageEarthTube ManageElectCenterStorageInteractions ManageElectricLoadCenters ManageElectStorInteractions ManageEMS ManageExteriorEnergyUse ManageGeneratorControlState ManageGeneratorFuelFlow ManageHeatBalance ManageHeatBalFiniteDiff ManageHeatBalHAMT ManageHVAC ManageHybridVentilation ManageInsideAdaptiveConvectionAlgo ManageInternalHeatGains ManageInverter ManageMundtModel ManageNonZoneEquipment ManageOutsideAdaptiveConvectionAlgo ManageOutsideAirSystem ManagePlantLoadDistribution ManagePlantLoops ManageRefrigeratedCaseRacks ManageSetPoints ManageSimulation ManageSingleCommonPipe ManageSizing ManageSurfaceHeatBalance ManageSystemAvailability ManageThermalChimney ManageThermalComfort ManageTransformers ManageTwoWayCommonPipe ManageUCSDCVModel ManageUCSDDVModel ManageUCSDUFModels ManageUserDefinedPatterns ManageWater ManageWaterInits ManageWeather ManageZoneAirLoopEquipment ManageZoneAirUpdates ManageZoneContaminanUpdates ManageZoneEquipment MapExtConvClassificationToHcModels MapIntConvClassificationToHcModels MarkNode MatchAndSetColorTextString MatchPlantSys MatrixIndex matrixQBalance MeshPartition_CompareByDimension MeshPartition_SelectionSort MeshPartitionArray_Contains MinePlantStructForInfo MixedAirControlTempResidual ModifyWindow Modulus MonthToMonthNumber MovingAvg MRXINV MSHPCyclingResidual MSHPHeatRecovery MSHPVarSpeedResidual MultiModeDXCoilHumRatResidual MultiModeDXCoilHumRatResidual MultiModeDXCoilResidual MultiModeDXCoilResidual MultiModeDXCoilResidual MultiSpeedDXCoolingCoilStandardRatings MultiSpeedDXHeatingCoilStandardRatings MULTOL MyPlantSizingIndex NeighborInformationArray_Value NETRAD NewEMSVariable NewExpression newPreDefColumn newPreDefReport newPreDefSubTable NEWTON NodeHasSPMCtrlVarType NormalArea NumBranchesInBranchList NumCompsInBranch nusselt NusseltNumber OpenEPlusWeatherFile OPENNESS_LW OpenOutputFiles OpenOutputTabularFile OpenWeatherFile OPERATOR (*) OPERATOR (+) OPERATOR (-) OPERATOR (.dot.) OPERATOR (.twodcross.) OPERATOR (.twoddot.) OPERATOR (/) ORDER OutBaroPressAt OutDewPointTempAt OutDryBulbTempAt OutsidePipeHeatTransCoef OutWetBulbTempAt P01 PanesDeflection ParametricObjectsCheck parseComputeLine ParseExpression ParseStack ParseTime PartLoadFactor PassiveGapNusseltNumber PassPressureAcrossInterface PassPressureAcrossMixer PassPressureAcrossSplitter PD_BEAM PD_BEAM_CASE_I PD_BEAM_CASE_II PD_BEAM_CASE_III PD_BEAM_CASE_IV PD_BEAM_CASE_V PD_BEAM_CASE_VI PD_DIFF PD_LW PD_LWP PD_SWP PerformanceCurveObject PerformanceTableObject PerformIterationLoop PerformPipeCellSimulation PerformPipeCircuitSimulation PerformSolarCalculations PerformTemperatureFieldUpdate PierceSurface PierceSurfaceVector PipeCircuitInfo_InitInOutCells PipeSegmentInfo_InitPipeCells PIUInducesPlenumAir PIUnitHasMixer PlaneEquation PlantHalfLoopSolver PlantMassFlowRatesFunc PLRResidual PLRResidual PLRResidualMixedTank PLRResidualStratifiedTank PMVResidual POLY1F POLY2F POLYF polygon_contains_point_2d popStack pos PostIPProcessing POWER PreDefTableEntry PredictSystemLoads PredictZoneContaminants PreparePipeCircuitSimulation PrepDebugFilesAndVariables PreProcessorCheck PrepVariablesISO15099 PreScanReportingVariables PresProfile PressureCurveValue ProcessDataDicFile ProcessDateString ProcessEMSInput ProcessEPWHeader ProcessForDayTypes ProcessInput ProcessInputDataFile ProcessIntervalFields ProcessMinMaxDefLine ProcessNumber ProcessScheduleInput ProcessSurfaceVertices ProcessTokens ProduceMinMaxString ProduceMinMaxStringWStartMinute ProduceRDDMDD ProfileAngle PropagateResolvedFlow PStack PsyCpAirFnWTdb PsyHfgAirFnWTdb PsyHFnTdbRhPb PsyHFnTdbW PsyHgAirFnWTdb PsyPsatFnTemp PsyPsatFnTemp_raw PsyRhFnTdbRhov PsyRhFnTdbRhovLBnd0C PsyRhFnTdbWPb PsyRhoAirFnPbTdbW PsyRhovFnTdbRh PsyRhovFnTdbRhLBnd0C PsyRhovFnTdbWPb PsyTdbFnHW PsyTdpFnTdbTwbPb PsyTdpFnWPb PsyTsatFnHPb PsyTsatFnPb PsyTwbFnTdbWPb PsyTwbFnTdbWPb_raw PsyVFnTdbWPb PsyWFnTdbH PsyWFnTdbRhPb PsyWFnTdbTwbPb PsyWFnTdpPb psz Pt2Plane PullCompInterconnectTrigger PumpDataForTable PushBranchFlowCharacteristics PushInnerTimeStepArrays pushStack PushSystemTimestepHistories PushSystemTimestepHistories PushZoneTimestepHistories PushZoneTimestepHistories QsortC QsortPartition RadialCellInfo_XY_CrossSectArea RadialCellInformation_ctor RadialSizing_Thickness Rainflow RangeCheck RB_BEAM RB_DIFF RB_F RB_LWP RB_SWP rCheckDayScheduleValueMinMax rCheckScheduleValue rCheckScheduleValueMinMax1 rCheckScheduleValueMinMax2 ReadEnergyMeters ReadEPlusWeatherForDay ReadGeneralDomainInputs ReadHorizontalTrenchInputs ReadINIFile ReadInputLine ReadPipeCircuitInputs ReadPipeSegmentInputs ReadTableData ReadUserWeatherInput ReadWeatherForDay Real_ConstrainTo Real_IsInRange real_times_vector ReAllocateAndPreserveOutputVariablesForSimulation ReallocateIntegerArray ReallocateIVar ReallocateRealArray ReallocateRVar RealPreDefTableEntry RealToStr RecKeepHeatBalance RecordOutput RectangleF_Contains ReformEIRChillerCondInletTempResidual ReformEIRChillerHeatRecovery RegisterNodeConnection RegisterPlantCompDesignFlow RegulateCondenserCompFlowReqOp ReInitPlantLoopsAtFirstHVACIteration RemoveSpaces RemoveTrailingZeros reorder ReplaceBlanksWithUnderscores ReplaceBlanksWithUnderscores ReportAirflowNetwork ReportAirHeatBalance ReportAirLoopConnections ReportAirTerminalUserDefined ReportAndTestGlycols ReportAndTestRefrigerants ReportBaseboard ReportBaseboard ReportCBVAV ReportChillerIPLV ReportCoilUserDefined ReportCompSetMeterVariables ReportController ReportCoolBeam ReportCoolTower ReportCTFs ReportCWTankInits ReportDemandManagerList ReportDesiccantDehumidifier ReportDetailedIceStorage ReportDirectAir ReportDualDuct ReportDualDuctConnections ReportDuct ReportDXCoil ReportDXCoilRating ReportDYMeters ReportEarthTube ReportEconomicVariable ReportElectricBaseboard ReportEMS ReportEvapCooler ReportEvapFluidCooler ReportExteriorEnergyUse ReportFan ReportFanCoilUnit ReportFatalGlycolErrors ReportFatalRefrigerantErrors ReportFiniteDiffInits ReportFluidCooler ReportFluidHeatExchanger ReportForTabularReports ReportFurnace ReportGlass ReportHeatBalance ReportHeatingCoil ReportHeatRecovery ReportHighTempRadiantSystem ReportHRMeters ReportHumidifier ReportHWBaseboard ReportIllumMap ReportingFreqName ReportingThisVariable ReportInternalHeatGains ReportLoopConnections ReportLowTempRadiantSystem ReportMaxVentilationLoads ReportMeterDetails ReportMissing_RangeData ReportMixer ReportMNMeters ReportMoistureBalanceEMPD ReportMSHeatPump ReportNodeConnections ReportOAController ReportOAMixer ReportOrphanFluids ReportOrphanRecordObjects ReportOrphanSchedules ReportOutdoorAirUnit ReportOutputFileHeaders ReportParentChildren ReportPipesHeatTransfer ReportPIU ReportPlantProfile ReportPlantUserComponent ReportPlantValves ReportPondGroundHeatExchanger ReportPTUnit ReportPumps ReportPurchasedAir ReportPV ReportRackSystem ReportRefrigerationComponents ReportReturnAirPath ReportRuntimeLanguage ReportScheduleDetails ReportScheduleValues ReportSizingOutput ReportSMMeters ReportSolarCollector ReportSplitter ReportStandAloneERV ReportStandAloneWaterUse ReportSteamBaseboard ReportSteamCoil ReportSurfaceErrors ReportSurfaceGroundHeatExchngr ReportSurfaceHeatBalance ReportSurfaces ReportSurfaceShading ReportSys ReportSysSizing ReportSystemEnergyUse ReportThermalChimney ReportTowers ReportTSMeters ReportUnitarySystem ReportUnitHeater ReportUnitVentilator ReportVentilatedSlab ReportVRFCondenser ReportVRFTerminalUnit ReportWarmupConvergence ReportWaterCoil ReportWaterManager ReportWaterThermalTank ReportWaterUse ReportWeatherAndTimeInformation ReportWindowAC ReportWindTurbine ReportZoneAirLoopEquipment ReportZoneAirUserDefined ReportZoneDehumidifier ReportZoneEquipment ReportZoneEvaporativeCoolerUnit ReportZoneMeanAirTemp ReportZoneReturnPlenum ReportZoneSizing ReportZoneSupplyPlenum ResetAllPlantInterConnectFlags ResetController ResetEnvironmentCounter ResetHVACControl ResetNodeData ResetPerformanceCurveOutput ResetRootFinder ResetTerminalUnitFlowLimits ResetWeekDaysByMonth Resimulate resist ReSolveAirLoopControllers ResolveAirLoopFlowLimits ResolveLocationInformation ResolveLockoutFlags ResolveLoopFlowVsPressure ResolveParallelFlows ResolveSysFlow ReverseAndRecalculate RevertZoneTimestepHistories RevertZoneTimestepHistories RevisePlantCallingOrder RezeroZoneSizingArrays RhoH2O RHtoVP RKG RoundSigDigits rRoundSigDigits rTrimSigDigits SafeCopyPlantNode SafeDiv SafeDivide SameString SandiaCellTemperature SandiaEffectiveIrradiance SandiaF1 SandiaF2 SandiaImp SandiaIsc SandiaIx SandiaIxx SandiaModuleTemperature SandiaTcellFromTmodule SandiaVmp SandiaVoc SaveSimpleController ScanForReports ScanPlantLoopsForNodeNum ScanPlantLoopsForObject sCheckDayScheduleValueMinMax ScheduleAverageHoursPerWeek SEARCH SearchAscTable SearchWindow5DataFile SecantFormula SecantMethod selectTariff SetActuatedBranchFlowRate SetAdditionalNeighborData SetAllFlowLocks SetAllPlantSimFlagsToValue SetATMixerPriFlow SetATMixerPriFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetCoilDesFlow SetCoilSystemCoolingData SetCoilSystemHeatingDXFlag SetCompFlowRate SetComponentFlowRate SetCurrentWeather SetCurveOutputMinMaxValues SetDSTDateRanges SetDXCoilTypeData SetDXCoolingCoilData SetEquivalentLayerWindowProperties SetErlValueNumber SetExtConvectionCoeff SetFanData SetHeatExchangerData SetHeatToReturnAirFlag SetInitialMeterReportingAndOutputNames SetIntConvectionCoeff SetInternalVariableValue SetMinMax setNativeVariables SetNodeResult SetOAControllerData SetOnOffMassFlowRate SetOnOffMassFlowRate SetOnOffMassFlowRate SetOnOffMassFlowRateVSCoil SetOnOffMassFlowRateVSCoil SetOutAirNodes SetOutBulbTempAt SetPredefinedTables SetSimpleWSHPData SETSKY SetSpecialDayDates SetSpeedVariables SetStormWindowControl SetSurfHBDataForMundtModel SetSurfHBDataForTempDistModel SetSurfTmeanAir SETUP4x4_A SetupAdaptiveConvectionRadiantSurfaceData SetupAdaptiveConvectionStaticMetaData SetupAirLoopControllersTracer SetupAllOutputVariables SetUpAndSort SetupBranchControlTypes SetupCellNeighbors SetupCommonPipes SetupComplexFenestrationMaterialInput SetupComplexFenestrationStateInput SetupComplexWindowStateGeometry SetUpCompSets SetupDElightOutput4EPlus SetupDElightOutput4EPlus SetUpDesignDay SetupEMSActuator SetupEMSIntegerActuator SetupEMSIntegerInternalVariable SetupEMSInternalVariable SetupEMSLogicalActuator SetupEMSRealActuator SetupEMSRealInternalVariable SetupEnvironmentTypes SetupFuelConstituentData SetupGeneratorControlStateManager SetupIndividualControllerTracer SetupInitialPlantCallingOrder SetupIntegerOutputVariable SetupInterpolationValues SetupLoopFlowRequest SetupMeteredVarsForSetPt SetupMundtModel SetupNodeSetpointsAsActuators SetupNodeVarsForReporting SetupOutputVariable SetupPipeCircuitInOutCells SetupPlantEMSActuators SetupPollutionCalculations SetupPollutionMeterReporting SetupPossibleOperators SetupPrimaryAirSystemAvailMgrAsActuators SetupPumpMinMaxFlows SetupRealOutputVariable SetupRealOutputVariable_IntKey SetupReportInput SetupReports SetupRootFinder SetUpSchemeColors SetupShadeSurfacesForSolarCalcs SetupSimpleWindowGlazingSystem SetupSimulation SetupStratifiedNodes SetupSurfaceConstructionActuators SetupSurfaceConvectionActuators SetupSurfaceOutdoorBoundaryConditionActuators SetUpSysSizingArrays SetupTankDemandComponent SetupTankSupplyComponent SetupThermostatActuators SetupTimePointers SetupUnitConversions SetupWeekDaysByMonth SetupWindowShadingControlActuators SetupZoneEquipmentForConvectionFlowRegime SetupZoneGeometry SetupZoneInfoAsInternalDataAvail SetupZoneInternalGain SetupZoneInternalGain SetupZoneSizing SetUpZoneSizingArrays SetUTSCQdotSource SetVarSpeedCoilData SetVentedModuleQdotSource SetVSHPAirFlow SetVSHPAirFlow SetWindSpeedAt SetZoneEquipSimOrder shading shadingedge shadingin SHADOW SharedDVCVUFDataInit SHDBKS SHDGSS SHDRVL SHDSBS shift ShiftPipeTemperaturesForNewIteration ShiftPlantLoopSideCallingOrder ShiftTemperaturesForNewIteration ShiftTemperaturesForNewTimeStep ShowAuditErrorMessage ShowBranchesOnLoop ShowContinueError ShowContinueError ShowContinueErrorTimeStamp ShowContinueErrorTimeStamp ShowErrorMessage ShowErrorMessage ShowFatalError ShowFatalError ShowMessage ShowMessage ShowPsychrometricSummary ShowRecurringContinueErrorAtEnd ShowRecurringContinueErrorAtEnd ShowRecurringErrors ShowRecurringSevereErrorAtEnd ShowRecurringSevereErrorAtEnd ShowRecurringWarningErrorAtEnd ShowRecurringWarningErrorAtEnd ShowSevereError ShowSevereError ShowSevereMessage ShowSevereMessage ShowWarningError ShowWarningError ShowWarningMessage ShowWarningMessage showWarningsBasedOnTotal Sim4PipeFanCoil SimAirChillerSet SimAirLoop SimAirLoopComponent SimAirLoopComponents SimAirLoops SimAirLoopSplitter SimAirMixer SimAirTerminalUserDefined SimAirZonePlenum SimATMixer SimBaseboard SimBLASTAbsorber SimBoiler SimCBVAV SimCBVAV SimCentralGroundSourceHeatPump SimChiller SimCoilUserDefined SimComponentModelFan SimConstVol SimCoolBeam SimCostEstimate SimCTGenerator SimCTPlantHeatRecovery SimCyclingWindowAC SimDesiccantDehumidifier SimDetailedIceStorage SimDirectAir SimDistrictEnergy SimDualDuctConstVol SimDualDuctVarVol SimDualDuctVAVOutdoorAir SimDuct SimDXCoil SimDXCoilMultiMode SimDXCoilMultiSpeed SimDXCoolingSystem SimDXHeatPumpSystem SimElecBaseBoard SimElectricBaseBoard SimElectricConvective SimElectricEIRChiller SimEvapCooler SimEvapFluidCoolers SimExhaustAbsorber SimFanCoilUnit SimFluidCoolers SimFluidHeatExchanger SimFourPipeIndUnit SimFuelCellGenerator SimFuelCellPlantHeatRecovery SimFurnace SimGasAbsorber SimGroundHeatExchangers SimHeatPumpWaterHeater SimHeatRecovery SimHighTempRadiantSystem SimHPWatertoWaterCOOLING SimHPWatertoWaterHEATING SimHPWatertoWaterSimple SimHumidifier SimHVAC SimHWBaseboard SimHWConvective SimHXAssistedCoolingCoil SimICEngineGenerator SimICEPlantHeatRecovery SimIceStorage SimIndirectAbsorber SimIndUnit SimLowTempRadiantSystem SimMicroCHPGenerator SimMicroCHPPlantHeatRecovery SimMSHeatPump SimMSHP SimMTGenerator SimMTPlantHeatRecovery SimMultiSpeedCoils SimOAComponent SimOAController SimOAMixer SimOnOffFan SimOutdoorAirEquipComps SimOutdoorAirUnit SimOutsideAirSys SimOutsideEnergy SimPackagedTerminalUnit SimPipes SimPipesHeatTransfer SimPipingSystemCircuit SimPIU SimPlantEquip SimPlantValves SimpleCoolingCoilUAResidual SimpleEvapFluidCoolerUAResidual SimpleFluidCoolerUAResidual SimpleHeatingCoilUAResidual SimpleTowerApproachResidual SimpleTowerTrResidual SimpleTowerUAResidual SimPondGroundHeatExchanger SimPressureDropSystem SimPTUnit SimPumps SimPurchasedAir SimPVGenerator SimPVTcollectors SimReformulatedEIRChiller SimRefrigCondenser SimReturnAirPath SimSelectedEquipment SimSetPointManagers SimSimpleEvapFluidCooler SimSimpleFan SimSimpleFluidCooler SimSimpleTower SimSolarCollector SimStandAloneERV SimSteamBaseboard SimSteamBoiler SimSteamCoils SimSurfaceGroundHeatExchanger SimSysAvailManager SimTESCoil SimTowers SimTranspiredCollector SimulateAllInteriorRadialSoilSlices SimulateAllLoopSideBranches SimulateAllLoopSidePumps SimulateDemandManagerList SimulateDetailedRefrigerationSystems SimulateDetailedTransRefrigSystems SimulateDualDuct SimulateFanComponents SimulateFluidCell SimulateHeatingCoilComponents SimulateInnerMostRadialSoilSlice SimulateLoopSideBranchGroup SimulateOuterMostRadialSoilSlice SimulatePlantProfile SimulateRadialInsulationCell SimulateRadialPipeCell SimulateRadialToCartesianInterface SimulateSingleDuct SimulateSteamCoilComponents SimulateVRF SimulateWaterCoilComponents SimulateWaterHeaterStandAlone SimulateWaterUse SimulateWaterUseConnection SimUnitaryBypassVAV SimUnitarySystem SimUnitHeater SimUnitVentilator SimUnitVentOAMixer SimUserDefinedPlantComponent SimVariableSpeedCoils SimVariableSpeedHP SimVariableSpeedHP SimVariableTower SimVariableVolumeFan SimVAV SimVAVVS SimVentilatedSlab SimVentSlabOAMixer SimVRF SimVRFCondenserPlant SimWaterCoils SimWaterSource SimWaterThermalTank SimWatertoAirHP SimWatertoAirHPSimple SimWindowAC SimWindTurbine SimZoneAirLoopEquipment SimZoneAirUserDefined SimZoneDehumidifier SimZoneEquipment SimZoneEvaporativeCoolerUnit SimZoneExhaustFan SimZoneOutAirUnitComps SingelSpeedDXCoolingCoilStandardRatings SingleSpeedDXHeatingCoilStandardRatings SingleSpeedFluidCooler SizeAbsorpChiller SizeAirLoopBranches SizeAirLoops SizeBaseboard SizeBoiler SizeBoiler SizeCBVAV SizeConstCOPChiller SizeController SizeCoolBeam SizeDemandSidePlantConnections SizeDirectAir SizeDualDuct SizeDXCoil SizeElecReformEIRChiller SizeElectricBaseboard SizeElectricBaseboard SizeElectricChiller SizeElectricEIRChiller SizeEngineDrivenChiller SizeEvapCooler SizeEvapFluidCooler SizeExhaustAbsorber SizeFan SizeFanCoilUnit SizeFluidCooler SizeFluidHeatExchanger SizeFurnace SizeGasAbsorber SizeGTChiller SizeHeatingCoil SizeHeatRecovery SizeHighTempRadiantSystem SizeHumidifier SizeHVACWaterToAir SizeHWBaseboard SizeIndirectAbsorpChiller SizeIndUnit SizeLowTempRadiantSystem SizeMSHeatPump SizeOAController SizeOutdoorAirUnit SizePIU SizePlantLoop SizePTUnit SizePump SizePurchasedAir SizePVT SizeStandAloneERV SizeStandAloneWaterHeater SizeSteamBaseboard SizeSteamCoil SizeSupplySidePlantConnections SizeSys SizeTankForDemandSide SizeTankForSupplySide SizeTESCoil SizeTower SizeUCSDUF SizeUnitarySystem SizeUnitHeater SizeUnitVentilator SizeVarSpeedCoil SizeVentilatedSlab SizeVRF SizeVRFCondenser SizeVSMerkelTower SizeWaterCoil SizeWaterManager SizeWaterSource SizeWindowAC SizeWrapper SizeZoneDehumidifier SizeZoneEquipment SizeZoneEvaporativeCoolerUnit SkipEPlusWFHeader SkyDifSolarShading SkyGndWeight SkyWeight SLtoAMB SLtoGL SLVSKY solar_EN673 solarISO15099 SolarSprectrumAverage SOLMATS SolveAirLoopControllers SolveForWindowTemperatures SolveRegression SolveRegulaFalsi SolverMoistureBalanceEMPD SOLVZP SortHistory Specular_Adjust Specular_EstimateDiffuseProps Specular_F Specular_OffNormal Specular_RATDiff Specular_SWP SQLiteBegin SQLiteBegin SQLiteBindDouble SQLiteBindInteger SQLiteBindLogicalMacro SQLiteBindNULL SQLiteBindText SQLiteBindTextMacro SQLiteClearBindings SQLiteCloseDatabase SQLiteColumnInt SQLiteColumnIntMacro SQLiteCommit SQLiteCommit SQLiteExecuteCommand SQLiteExecuteCommandMacro SQLiteFinalizeCommand SQLiteOpenDatabase SQLiteOpenDatabaseMacro SQLitePrepareStatement SQLitePrepareStatementMacro SQLiteResetCommand SQLiteStepCommand SQLiteWriteMessage SQLiteWriteMessageMacro SQLiteWriteMessageMacro StandardIndexTypeKey StandardVariableTypeKey StartingWindowTemps StartingWinTempsForNominalCond SteamHeatingCoilResidual StorageType StoreAPumpOnCurrentTempLoop storeIterationResults StoreRecurringErrorMessage StringValue StrToReal SumAllInternalCO2Gains SumAllInternalConvectionGains SumAllInternalGenericContamGains SumAllInternalLatentGains SumAllInternalRadiationGains SumAllReturnAirConvectionGains SumAllReturnAirLatentGains SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumInternalCO2GainsByTypes SumInternalConvectionGainsByTypes SumInternalLatentGainsByTypes SumInternalRadiationGainsByTypes SummarizeErrors SumReturnAirConvectionGainsByTypes SumZoneImpacts SUN3 SUN4 SupSATResidual SurfaceScheduledSolarInc SurveyDemandManagers SystemPropertiesAtLambdaAndPhi SystemSpectralPropertiesAtPhi TableLookupObject TARCOG90 TBND TdbFnHRhPb TDMA TDMA_R TellMeHowManyObjectItemArgs TemperaturesFromEnergy TempIPtoSI TempSItoIP terpld TESCoilHumRatResidual TESCoilResidual TestAirPathIntegrity TestBranchIntegrity TestCompSet TestCompSetInletOutletNodes TestInletOutletNodes TestReturnAirPathIntegrity TestSupplyAirPathIntegrity therm1d TightenNodeMinMaxAvails TimestepInitComplexFenestration TimestepTypeName TraceAirLoopController TraceAirLoopControllers TraceIndividualController TraceIterationStamp TrackAirLoopController TrackAirLoopControllers TRadC TransAndReflAtPhi TransformVertsByAspect TransTDD Triangulate TrimSigDigits TurnOffLoopEquipment TurnOffLoopSideEquipment TurnOffReportRangeCheckErrors TurnOnPlantLoopPipes TurnOnReportRangeCheckErrors TwoSpeedFluidCooler UnitarySystemHeatRecovery UpdateAbsorberChillerComponentGeneratorSide UpdateAirflowNetwork UpdateAirMixer UpdateAirSysCompPtrArray UpdateAirSysSubCompPtrArray UpdateAirSysSubSubCompPtrArray UpdateAirZoneReturnPlenum UpdateAirZoneSupplyPlenum UpdateAnyLoopDemandAlterations UpdateATMixer UpdateBaseboard UpdateBaseboardPlantConnection UpdateBasementSurfaceTemperatures UpdateBBElecRadSourceValAvg UpdateBBRadSourceValAvg UpdateBBSteamRadSourceValAvg UpdateBLASTAbsorberRecords UpdateBoilerRecords UpdateBoilerRecords UpdateBracket UpdateBranchConnections UpdateChillerComponentCondenserSide UpdateChillerheaterRecords UpdateChillerRecords UpdateColdWeatherProtection UpdateCommonPipe UpdateComplexWindows UpdateComponentHeatRecoverySide UpdateConstCOPChillerRecords UpdateController UpdateCoolBeam UpdateCoolTower UpdateCTGeneratorRecords UpdateDataandReport UpdateDemandManagers UpdateDesiccantDehumidifier UpdateDetailedIceStorage UpdateDualDuct UpdateDuct UpdateDXCoil UpdateElectricBaseboard UpdateElectricChillerRecords UpdateElectricEIRChillerRecords UpdateEMSTrendVariables UpdateEngineDrivenChiller UpdateEvapCooler UpdateEvapFluidCooler UpdateEvaporativeCondenserBasinHeater UpdateEvaporativeCondenserWaterUse UpdateExhaustAbsorberCoolRecords UpdateExhaustAbsorberHeatRecords UpdateExhaustAirFlows UpdateFan UpdateFinalSurfaceHeatBalance UpdateFluidCooler UpdateFluidHeatExchanger UpdateFuelCellGeneratorRecords UpdateGasAbsorberCoolRecords UpdateGasAbsorberHeatRecords UpdateGSHPRecords UpdateGSHPRecords UpdateGSHPRecords UpdateGTChillerRecords UpdateHalfLoopInletTemp UpdateHeatBalHAMT UpdateHeatingCoil UpdateHeatRecovery UpdateHighTempRadiantSystem UpdateHistories UpdateHistory UpdateHTRadSourceValAvg UpdateHumidifier UpdateHVACInterface UpdateHWBaseboard UpdateHWBaseboardPlantConnection UpdateIceFractions UpdateICEngineGeneratorRecords UpdateIndirectAbsorberRecords UpdateInternalGainValues UpdateIrrigation UpdateLoadCenterRecords UpdateLoopSideReportVars UpdateLowTempRadiantSystem UpdateMeterReporting UpdateMeters UpdateMeterValues UpdateMicroCHPGeneratorRecords UpdateMinMax UpdateMixedAirSetPoints UpdateMoistureBalanceEMPD UpdateMoistureBalanceFD UpdateMSHeatPump UpdateMTGeneratorRecords UpdateNode UpdateNodeThermalHistory UpdateOAController UpdateOAMixer UpdateOAPretreatSetPoints UpdatePipesHeatTransfer UpdatePipingSystems UpdatePlantLoopInterface UpdatePlantMixer UpdatePlantProfile UpdatePlantSplitter UpdatePlantValves UpdatePondGroundHeatExchanger UpdatePrecipitation UpdatePressureDrop UpdatePurchasedAir UpdatePVTcollectors UpdateRadSysSourceValAvg UpdateRecords UpdateReformEIRChillerRecords UpdateRefrigCondenser UpdateReportWaterSystem UpdateRootFinder UpdateScheduleValues UpdateSetPointManagers UpdateSimpleWatertoAirHP UpdateSoilProps UpdateSolarCollector UpdateSplitter UpdateSQLiteErrorRecord UpdateSQLiteErrorRecord UpdateSQLiteSimulationRecord UpdateSQLiteSimulationRecord UpdateSteamBaseboard UpdateSteamBaseboardPlantConnection UpdateSteamCoil UpdateSurfaceGroundHeatExchngr UpdateSys UpdateSysSizing UpdateSystemOutputRequired UpdateTabularReports UpdateTEStorage UpdateThermalHistories UpdateTowers UpdateTranspiredCollector UpdateUnitarySystemControl UpdateUtilityBills UpdateVarSpeedCoil UpdateVentilatedSlab UpdateVerticalGroundHeatExchanger UpdateVRFCondenser UpdateWaterCoil UpdateWaterConnections UpdateWaterManager UpdateWaterSource UpdateWaterThermalTank UpdateWaterToAirCoilPlantConnection UpdateWatertoAirHP UpdateWeatherData UpdateWholeBuildingRecords UpdateZoneAirLoopEquipment UpdateZoneCompPtrArray UpdateZoneDehumidifier UpdateZoneEquipment UpdateZoneInletConvergenceLog UpdateZoneListAndGroupLoads UpdateZoneSizing UpdateZoneSubCompPtrArray UpdateZoneSubSubCompPtrArray ValidateAndSetSysAvailabilityManagerType ValidateComponent ValidateDistributionSystem ValidateEMSProgramName ValidateEMSVariableName ValidateExhaustFanInput ValidateFlowControlPaths ValidateFuelType ValidateIndexType ValidateMaterialRoughness ValidateMonthDay ValidateNStandardizeMeterTitles ValidateObjectandParse ValidatePipeConstruction ValidatePLFCurve ValidateSection ValidateSectionsInput ValidateVariableType value_to_vector ValueToString VAVVSCoolingResidual VAVVSHCFanOnResidual VAVVSHWFanOnResidual VAVVSHWNoFanResidual VB_CriticalSlatAngle VB_DIFF VB_LWP VB_ShadeControl VB_SLAT_RADIUS_RATIO VB_SOL4 VB_SOL46_CURVE VB_SOL6 VB_SWP vec2d_cross_product vec2d_dot_product vec_cross_product vec_dot_product VecLength VecNegate VecNormalize VecRound VecSquaredLength vector_add vector_div_int vector_div_real vector_subtract vector_times_int vector_times_real vector_to_array VerifyControlledZoneForThermostat VerifyCustomMetersElecPowerMgr VerifyHeatExchangerParent VerifyName VerifySetPointManagers VerifyThermostatInZone VerifyUniqueBaseboardName VerifyUniqueBoilerName VerifyUniqueChillerName VerifyUniqueCoilName ViewFac VisibleSprectrumAverage Volume VRMLOut VSCoilCyclingHumResidual VSCoilCyclingResidual VSCoilCyclingResidual VSCoilSpeedHumResidual VSCoilSpeedResidual VSCoilSpeedResidual VSEvapUnitLoadResidual VSHPCyclingResidual VSHPCyclingResidual VSHPSpeedResidual VSHPSpeedResidual VSMerkelResidual W5InitGlassParameters W5LsqFit W5LsqFit2 W6CoordsFromWorldVect warnIfNativeVarname WetCoilOutletCondition WhichCompSet WhichParentCompSet WhichParentSet Width WindowGapAirflowControl WindowGasConductance WindowGasPropertiesAtTemp WindowHeatBalanceEquations WindowScheduledSolarAbs WindowShadingManager WindowTempsForNominalCond WindSpeedAt Windward WorldVectFromW6 WriteAdaptiveComfortTable WriteAirLoopStatistics WriteBEPSTable WriteCompCostTable WriteComponentSizing WriteCumulativeReportMeterData WriteDaylightMapTitle WriteDemandEndUseSummary WriteInputArguments WriteIntegerData WriteIntegerVariableOutput WriteMeterDictionaryItem WriteModifiedArguments WriteMonthlyTables WriteOutputArguments WriteOutputEN673 WritePoint WritePredefinedTables WriteRealData WriteRealVariableOutput WriteReportHeaders WriteReportIntegerData WriteReportMeterData WriteReportRealData WriteReportVariableDictionaryItem WriteRootFinderStatus WriteRootFinderTrace WriteRootFinderTraceHeader WriteSourceEnergyEndUseSummary writeSubtitle WriteSurfaceShadowing WriteTable WriteTableOfContents WriteTabularLifeCycleCostReport WriteTabularReports WriteTabularTariffReports WriteTARCOGInputFile writeTextLine WriteTimeBinTables WriteTimeStampFormatData WriteTrace WriteVeriSumTable WriteZoneLoadComponentTable WVDC XNormalArea XYRectangle XZRectangle YNormalArea YZRectangle ZeroHVACValues ZNormalArea
Call graph
getcurveinput calls getnumobjectsfound, cnumericfieldnames, getobjectdefmaxargs, solveregression, showcontinueerror, lnumericfieldblanks, showsevereerror, readtabledata, finditeminlist, showfatalerror, verifyname, calphafieldnames, iscurveoutputtypevalid, iscurveinputtypevalid, roundsigdigits, showwarningerror, lalphafieldblanks, getobjectitem
solveregression calls showcontinueerror, showsevereerror, roundsigdigits, trimsigdigits
showcontinueerror calls showerrormessage, updatesqliteerrorrecord
showsevereerror calls showerrormessage, matchcounts, messagesearch, createsqliteerrorrecord
readtabledata calls showcontinueerror, showsevereerror, showfatalerror, roundsigdigits, showwarningerror, checkforactualfilename, 10
showfatalerror calls roundsigdigits, showerrormessage, displaystring, createsqliteerrorrecord, abortenergyplus
iscurveoutputtypevalid calls samestring
iscurveinputtypevalid calls samestring
showwarningerror calls showerrormessage, matchcounts, messagesearch, createsqliteerrorrecord
showerrormessage calls showfatalerror, displaystring
abortenergyplus calls roundsigdigits, displaystring, testairpathintegrity, updatesqlitesimulationrecord, checkmarkednodes, reportairloopconnections, showrecurringerrors, testcompsetinletoutletnodes, summarizeerrors, reportsurfaceerrors, reportloopconnections, closemiscopenfiles, setupnodevarsforreporting, closesocket, closeoutopenfiles, reportsurfaces, testbranchintegrity, checkplantonabort, epelapsedtime, epstoptime, epsummarytimes, showmessage, checknodeconnections
testairpathintegrity calls showcontinueerror, showsevereerror, airtozonenodeinfo, nodeid
showrecurringerrors calls roundsigdigits, updatesqliteerrorrecord, createsqliteerrorrecord, showmessage, removetrailingzeros, recurringerrors
summarizeerrors calls matchcounts, showmessage, summaries, moredetails
closemiscopenfiles calls closedfsfile, closereportillummaps
reportsurfaces calls showwarningerror, detailsforsurfaces, setupschemecolors, vrmlout, scanforreports, dxfoutwireframe, costinfoout, linesout, dxfout
epstoptime calls showfatalerror, tstop
epsummarytimes calls roundsigdigits
showmessage calls showerrormessage
detailsforsurfaces calls roundsigdigits, trimsigdigits, getschedulename, oscm, nominalu, zone, framedivider, getschedulemaxvalue, 2, computenominaluwithconvcoeffs, 3, osc, construct, 4, csurfaceclass, userintconvectioncoeffs, userextconvectioncoeffs, surface, getscheduleminvalue, surfacewindow
setupschemecolors calls getobjectdefmaxargs, showwarningerror, getobjectitem, getobjectitemnum, matchandsetcolortextstring
vrmlout calls showcontinueerror, showfatalerror, showwarningerror, zone, surface, triangulate, getnewunitnumber
dxfoutwireframe calls showfatalerror, trimsigdigits, zone, surface, surfacewindow, getnewunitnumber, zonedaylight, dxfcolorno
costinfoout calls showfatalerror, construct, csurfaceclass, surface, getnewunitnumber
linesout calls showcontinueerror, showfatalerror, roundsigdigits, showwarningerror, csurfaceclass, surface, getnewunitnumber
dxfout calls showcontinueerror, showfatalerror, showwarningerror, trimsigdigits, zone, surface, surfacewindow, triangulate, getnewunitnumber, zonedaylight, dxfcolorno, illummapcalc
computenominaluwithconvcoeffs calls surface
matchandsetcolortextstring calls finditem
triangulate calls showcontinueerror, roundsigdigits, showwarningerror, showmessage, csurfaceclass, generate_ears, calcrfflrcoordinatetransformation, calcwallcoordinatetransformation
generate_ears calls polygon_contains_point_2d, angle_2dvector
getpressurecurvetypeandindex calls getcurveinput, getcurveindex
getcurveindex calls getcurveinput
getdesiccantdehumidifierinput calls getcurveindex
getsetpointmanagerinputs calls getcurveindex
getcurvecheck calls getcurveindex
gettescoilinput calls getcurveindex
geticestorageinput calls getcurveindex
simdesiccantdehumidifier calls getdesiccantdehumidifierinput
nodehasspmctrlvartype calls getsetpointmanagerinputs
isnodeonsetptmanager calls getsetpointmanagerinputs
managesetpoints calls getsetpointmanagerinputs
gettescoilindex calls gettescoilinput
simtescoil calls gettescoilinput
simicestorage calls geticestorageinput