GetPollutionFactorInput – EnergyPlusFortran
GetPollutionFactorInput Subroutine
854 statements
Source File
private subroutine GetPollutionFactorInput()
Uses:
DataIPShortCuts
InputProcessor
DataInterfaces
Arguments
None
Calls
Called By
Source Code
GetPollutionFactorInput
Source Code
SUBROUTINE GetPollutionFactorInput
          ! SUBROUTINE INFORMATION:
          !       AUTHOR         Linda Lawrie
          !       DATE WRITTEN   August 2008
          !       MODIFIED       na
          !       RE-ENGINEERED  na
          ! PURPOSE OF THIS SUBROUTINE:
          ! SetupPollutionCalculation must be called after meters are initialized.  This caused a problem
          ! in runs so have added this routine to allow central get for most inputs.
          ! METHODOLOGY EMPLOYED:
          ! na
          ! REFERENCES:
          ! na
          ! USE STATEMENTS:
    USE DataIPShortCuts
    USE InputProcessor, ONLY: GetNumObjectsFound,GetObjectItem,MakeUPPERCase
    USE DataInterfaces, ONLY: ShowWarningError,ShowSevereError,ShowFatalError
  IMPLICIT NONE ! Enforce explicit typing of all variables in this routine
          ! SUBROUTINE ARGUMENT DEFINITIONS:
          ! na
          ! SUBROUTINE PARAMETER DEFINITIONS:
          ! na
          ! INTERFACE BLOCK SPECIFICATIONS:
          ! na
          ! DERIVED TYPE DEFINITIONS:
          ! na
          ! SUBROUTINE LOCAL VARIABLE DECLARATIONS:
    INTEGER :: NumAlphas
    INTEGER :: NumNums
    INTEGER :: Loop
    INTEGER :: IOSTAT
    LOGICAL :: ErrorsFound = .False.
    INTEGER, external :: GetMeterIndex
    IF (.not. GetInputFlagPollution) RETURN   ! Input already gotten
    GetInputFlagPollution=.false.
    cCurrentModuleObject='EnvironmentalImpactFactors'
    NumEnvImpactFactors=GetNumObjectsFound(cCurrentModuleObject)
    IF (NumEnvImpactFactors > 0) THEN
      ! Now find and load all of the user inputs and factors.
      CALL GetObjectItem(cCurrentModuleObject,1,cAlphaArgs,NumAlphas,rNumericArgs,NumNums,IOSTAT,  &
                   AlphaBlank=lAlphaFieldBlanks,NumBlank=lNumericFieldBlanks,  &
                   AlphaFieldnames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
    ELSE
      IF (PollutionReportSetup)  &
        CALL ShowWarningError(TRIM(cCurrentModuleObject)//': not entered.  Values will be defaulted.')
    ENDIF
    Pollution%PurchHeatEffic = 0.3d0
    Pollution%PurchCoolCOP =  3.0d0
    Pollution%SteamConvEffic = 0.25d0
    Pollution%CarbonEquivN2O = 0.0d0
    Pollution%CarbonEquivCH4 = 0.0d0
    Pollution%CarbonEquivCO2 = 0.0d0
    IF (NumEnvImpactFactors > 0) THEN
      !If Heating Efficiency defined by the User is negative or zero then a default of 30% will be assigned.
      If(rNumericArgs(1) > 0.0d0) Then
        Pollution%PurchHeatEffic = rNumericArgs(1)
      End If
      !If COP defined by the User is negative or zero then a default of 3.0 will be assigned.
      If(rNumericArgs(2) > 0.0d0) Then
        Pollution%PurchCoolCOP =  rNumericArgs(2)
      End If
      !If Steam Conversion Efficiency defined by the User is negative or zero then a default of 25% will be assigned.
      If(rNumericArgs(1) > 0.0d0) Then
        Pollution%SteamConvEffic = rNumericArgs(3)
      End If
      !Load the Total Carbon Equivalent Pollution Factor coefficients
      Pollution%CarbonEquivN2O = rNumericArgs(4)
      Pollution%CarbonEquivCH4 = rNumericArgs(5)
      Pollution%CarbonEquivCO2 = rNumericArgs(6)
    End If
    !Compare all of the Fuel Factors and compare to PollutionCalculationFactors List
    cCurrentModuleObject='FuelFactors'
    NumFuelFactors = GetNumObjectsFound(cCurrentModuleObject)
    Do Loop = 1,NumFuelFactors
      ! Now find and load all of the user inputs and factors.
      CALL GetObjectItem(cCurrentModuleObject,Loop,cAlphaArgs,NumAlphas,rNumericArgs,NumNums,IOSTAT,  &
                   AlphaBlank=lAlphaFieldBlanks,NumBlank=lNumericFieldBlanks,  &
                   AlphaFieldnames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
      FuelType%FuelTypeNames(Loop) = Trim(cAlphaArgs(1))
      SELECT CASE (MakeUPPERCase(FuelType%FuelTypeNames(Loop)))
        CASE ('NATURALGAS','NATURAL GAS','GAS')
          IF (Pollution%NatGasCoef%FuelFactorUsed) THEN
            CALL ShowWarningError(TRIM(cCurrentModuleObject)//': '//TRIM(FuelType%FuelTypeNames(Loop))//' already entered.'//  &
              ' Previous entry will be used.')
            CYCLE
          ENDIF
          Pollution%NatGasCoef%FuelFactorUsed = .True.
         !Natural Gas Coeffs
          Pollution%NatGasCoef%Source = rNumericArgs(2)
          IF (.not. lAlphaFieldBlanks(3)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Natural Gas',trim(cAlphaFieldNames(3)),trim(cAlphaArgs(3)),  &
                                      Pollution%NatGasCoef%SourceSched,ErrorsFound)
          END IF
          Pollution%NatGasCoef%CO2    = rNumericArgs(3)
          IF (.not. lAlphaFieldBlanks(4)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Natural Gas',trim(cAlphaFieldNames(4)),trim(cAlphaArgs(4)),  &
                                      Pollution%NatGasCoef%CO2Sched,ErrorsFound)
          END IF
          Pollution%NatGasCoef%CO     = rNumericArgs(4)
          IF (.not. lAlphaFieldBlanks(5)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Natural Gas',trim(cAlphaFieldNames(5)),trim(cAlphaArgs(5)),  &
                                      Pollution%NatGasCoef%COSched,ErrorsFound)
          END IF
          Pollution%NatGasCoef%CH4    = rNumericArgs(5)
          IF (.not. lAlphaFieldBlanks(6)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Natural Gas',trim(cAlphaFieldNames(6)),trim(cAlphaArgs(6)),  &
                                      Pollution%NatGasCoef%CH4Sched,ErrorsFound)
          END IF
          Pollution%NatGasCoef%NOx    = rNumericArgs(6)
          IF (.not. lAlphaFieldBlanks(7)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Natural Gas',trim(cAlphaFieldNames(7)),trim(cAlphaArgs(7)),  &
                                      Pollution%NatGasCoef%NOxSched,ErrorsFound)
          END IF
          Pollution%NatGasCoef%N2O    = rNumericArgs(7)
          IF (.not. lAlphaFieldBlanks(8)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Natural Gas',trim(cAlphaFieldNames(8)),trim(cAlphaArgs(8)),  &
                                      Pollution%NatGasCoef%N2OSched,ErrorsFound)
          END IF
          Pollution%NatGasCoef%SO2    = rNumericArgs(8)
          IF (.not. lAlphaFieldBlanks(9)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Natural Gas',trim(cAlphaFieldNames(9)),trim(cAlphaArgs(9)),  &
                                      Pollution%NatGasCoef%SO2Sched,ErrorsFound)
          END IF
          Pollution%NatGasCoef%PM     = rNumericArgs(9)
          IF (.not. lAlphaFieldBlanks(10)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Natural Gas',trim(cAlphaFieldNames(10)),trim(cAlphaArgs(10)),  &
                                      Pollution%NatGasCoef%PMSched,ErrorsFound)
          END IF
          Pollution%NatGasCoef%PM10   = rNumericArgs(10)
          IF (.not. lAlphaFieldBlanks(11)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Natural Gas',trim(cAlphaFieldNames(11)),trim(cAlphaArgs(11)),  &
                                      Pollution%NatGasCoef%PM10Sched,ErrorsFound)
          END IF
          Pollution%NatGasCoef%PM25   = rNumericArgs(11)
          IF (.not. lAlphaFieldBlanks(12)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Natural Gas',trim(cAlphaFieldNames(12)),trim(cAlphaArgs(12)),  &
                                      Pollution%NatGasCoef%PM25Sched,ErrorsFound)
          END IF
          Pollution%NatGasCoef%NH3    = rNumericArgs(12)
          IF (.not. lAlphaFieldBlanks(13)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Natural Gas',trim(cAlphaFieldNames(13)),trim(cAlphaArgs(13)),  &
                                      Pollution%NatGasCoef%NH3Sched,ErrorsFound)
          END IF
          Pollution%NatGasCoef%NMVOC  = rNumericArgs(13)
          IF (.not. lAlphaFieldBlanks(14)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Natural Gas',trim(cAlphaFieldNames(14)),trim(cAlphaArgs(14)),  &
                                      Pollution%NatGasCoef%NMVOCSched,ErrorsFound)
          END IF
          Pollution%NatGasCoef%Hg     = rNumericArgs(14)
          IF (.not. lAlphaFieldBlanks(15)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Natural Gas',trim(cAlphaFieldNames(15)),trim(cAlphaArgs(15)),  &
                                      Pollution%NatGasCoef%HgSched,ErrorsFound)
          END IF
          Pollution%NatGasCoef%Pb     = rNumericArgs(15)
          IF (.not. lAlphaFieldBlanks(16)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Natural Gas',trim(cAlphaFieldNames(16)),trim(cAlphaArgs(16)),  &
                                      Pollution%NatGasCoef%PbSched,ErrorsFound)
          END IF
          Pollution%NatGasCoef%Water  = rNumericArgs(16)
          IF (.not. lAlphaFieldBlanks(17)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Natural Gas',trim(cAlphaFieldNames(17)),trim(cAlphaArgs(17)),  &
                                      Pollution%NatGasCoef%WaterSched,ErrorsFound)
          END IF
          Pollution%NatGasCoef%NucHi  = rNumericArgs(17)
          IF (.not. lAlphaFieldBlanks(18)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Natural Gas',trim(cAlphaFieldNames(18)),trim(cAlphaArgs(18)),  &
                                      Pollution%NatGasCoef%NucHiSched,ErrorsFound)
          END IF
          Pollution%NatGasCoef%NucLo  = rNumericArgs(18)
          IF (.not. lAlphaFieldBlanks(19)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Natural Gas',trim(cAlphaFieldNames(19)),trim(cAlphaArgs(19)),  &
                                      Pollution%NatGasCoef%NucLoSched,ErrorsFound)
          END IF
        CASE ('RESIDUALOIL','RESIDUAL OIL','FUEL OIL #2','FUELOIL#2')
          IF (Pollution%FuelOil2Coef%FuelFactorUsed) THEN
            CALL ShowWarningError(TRIM(cCurrentModuleObject)//': '//TRIM(FuelType%FuelTypeNames(Loop))//' already entered.'//  &
              ' Previous entry will be used.')
            CYCLE
          ENDIF
          Pollution%FuelOil2Coef%FuelFactorUsed = .True.
         !FuelOil#2 Coeffs
          Pollution%FuelOil2Coef%Source = rNumericArgs(2)
          IF (.not. lAlphaFieldBlanks(3)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#2',trim(cAlphaFieldNames(3)),trim(cAlphaArgs(3)),  &
                                      Pollution%FuelOil2Coef%SourceSched,ErrorsFound)
          END IF
          Pollution%FuelOil2Coef%CO2    = rNumericArgs(3)
          IF (.not. lAlphaFieldBlanks(4)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#2',trim(cAlphaFieldNames(4)),trim(cAlphaArgs(4)),  &
                                      Pollution%FuelOil2Coef%CO2Sched,ErrorsFound)
          END IF
          Pollution%FuelOil2Coef%CO     = rNumericArgs(4)
          IF (.not. lAlphaFieldBlanks(5)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#2',trim(cAlphaFieldNames(5)),trim(cAlphaArgs(5)),  &
                                      Pollution%FuelOil2Coef%COSched,ErrorsFound)
          END IF
          Pollution%FuelOil2Coef%CH4    = rNumericArgs(5)
          IF (.not. lAlphaFieldBlanks(6)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#2',trim(cAlphaFieldNames(6)),trim(cAlphaArgs(6)),  &
                                      Pollution%FuelOil2Coef%CH4Sched,ErrorsFound)
          END IF
          Pollution%FuelOil2Coef%NOx    = rNumericArgs(6)
          IF (.not. lAlphaFieldBlanks(7)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#2',trim(cAlphaFieldNames(7)),trim(cAlphaArgs(7)),  &
                                      Pollution%FuelOil2Coef%NOxSched,ErrorsFound)
          END IF
          Pollution%FuelOil2Coef%N2O    = rNumericArgs(7)
          IF (.not. lAlphaFieldBlanks(8)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#2',trim(cAlphaFieldNames(8)),trim(cAlphaArgs(8)),  &
                                      Pollution%FuelOil2Coef%N2OSched,ErrorsFound)
          END IF
          Pollution%FuelOil2Coef%SO2    = rNumericArgs(8)
          IF (.not. lAlphaFieldBlanks(9)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#2',trim(cAlphaFieldNames(9)),trim(cAlphaArgs(9)),  &
                                      Pollution%FuelOil2Coef%SO2Sched,ErrorsFound)
          END IF
          Pollution%FuelOil2Coef%PM     = rNumericArgs(9)
          IF (.not. lAlphaFieldBlanks(10)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#2',trim(cAlphaFieldNames(10)),trim(cAlphaArgs(10)),  &
                                      Pollution%FuelOil2Coef%PMSched,ErrorsFound)
          END IF
          Pollution%FuelOil2Coef%PM10   = rNumericArgs(10)
          IF (.not. lAlphaFieldBlanks(11)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#2',trim(cAlphaFieldNames(11)),trim(cAlphaArgs(11)),  &
                                      Pollution%FuelOil2Coef%PM10Sched,ErrorsFound)
          END IF
          Pollution%FuelOil2Coef%PM25   = rNumericArgs(11)
          IF (.not. lAlphaFieldBlanks(12)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#2',trim(cAlphaFieldNames(12)),trim(cAlphaArgs(12)),  &
                                      Pollution%FuelOil2Coef%PM25Sched,ErrorsFound)
          END IF
          Pollution%FuelOil2Coef%NH3    = rNumericArgs(12)
          IF (.not. lAlphaFieldBlanks(13)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#2',trim(cAlphaFieldNames(13)),trim(cAlphaArgs(13)),  &
                                      Pollution%FuelOil2Coef%NH3Sched,ErrorsFound)
          END IF
          Pollution%FuelOil2Coef%NMVOC  = rNumericArgs(13)
          IF (.not. lAlphaFieldBlanks(14)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#2',trim(cAlphaFieldNames(14)),trim(cAlphaArgs(14)),  &
                                      Pollution%FuelOil2Coef%NMVOCSched,ErrorsFound)
          END IF
          Pollution%FuelOil2Coef%Hg     = rNumericArgs(14)
          IF (.not. lAlphaFieldBlanks(15)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#2',trim(cAlphaFieldNames(15)),trim(cAlphaArgs(15)),  &
                                      Pollution%FuelOil2Coef%HgSched,ErrorsFound)
          END IF
          Pollution%FuelOil2Coef%Pb     = rNumericArgs(15)
          IF (.not. lAlphaFieldBlanks(16)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#2',trim(cAlphaFieldNames(16)),trim(cAlphaArgs(16)),  &
                                      Pollution%FuelOil2Coef%PbSched,ErrorsFound)
          END IF
          Pollution%FuelOil2Coef%Water  = rNumericArgs(16)
          IF (.not. lAlphaFieldBlanks(17)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#2',trim(cAlphaFieldNames(17)),trim(cAlphaArgs(17)),  &
                                      Pollution%FuelOil2Coef%WaterSched,ErrorsFound)
          END IF
          Pollution%FuelOil2Coef%NucHi  = rNumericArgs(17)
          IF (.not. lAlphaFieldBlanks(18)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#2',trim(cAlphaFieldNames(18)),trim(cAlphaArgs(18)),  &
                                      Pollution%FuelOil2Coef%NucHiSched,ErrorsFound)
          END IF
          Pollution%FuelOil2Coef%NucLo  = rNumericArgs(18)
          IF (.not. lAlphaFieldBlanks(19)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#2',trim(cAlphaFieldNames(19)),trim(cAlphaArgs(19)),  &
                                      Pollution%FuelOil2Coef%NucLoSched,ErrorsFound)
          END IF
        CASE ('DISTILLATEOIL','DISTILLATE OIL','FUEL OIL #1','FUELOIL#1','FUEL OIL')
          IF (Pollution%FuelOil1Coef%FuelFactorUsed) THEN
            CALL ShowWarningError(TRIM(cCurrentModuleObject)//': '//TRIM(FuelType%FuelTypeNames(Loop))//' already entered.'//  &
              ' Previous entry will be used.')
            CYCLE
          ENDIF
          Pollution%FuelOil1Coef%FuelFactorUsed = .True.
         !FuelOil#1 Coeffs
          Pollution%FuelOil1Coef%Source = rNumericArgs(2)
          IF (.not. lAlphaFieldBlanks(3)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#1',trim(cAlphaFieldNames(3)),trim(cAlphaArgs(3)),  &
                                      Pollution%FuelOil1Coef%SourceSched,ErrorsFound)
          END IF
          Pollution%FuelOil1Coef%CO2    = rNumericArgs(3)
          IF (.not. lAlphaFieldBlanks(4)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#1',trim(cAlphaFieldNames(4)),trim(cAlphaArgs(4)),  &
                                      Pollution%FuelOil1Coef%CO2Sched,ErrorsFound)
          END IF
          Pollution%FuelOil1Coef%CO     = rNumericArgs(4)
          IF (.not. lAlphaFieldBlanks(5)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#1',trim(cAlphaFieldNames(5)),trim(cAlphaArgs(5)),  &
                                      Pollution%FuelOil1Coef%COSched,ErrorsFound)
          END IF
          Pollution%FuelOil1Coef%CH4    = rNumericArgs(5)
          IF (.not. lAlphaFieldBlanks(6)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#1',trim(cAlphaFieldNames(6)),trim(cAlphaArgs(6)),  &
                                      Pollution%FuelOil1Coef%CH4Sched,ErrorsFound)
          END IF
          Pollution%FuelOil1Coef%NOx    = rNumericArgs(6)
          IF (.not. lAlphaFieldBlanks(7)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#1',trim(cAlphaFieldNames(7)),trim(cAlphaArgs(7)),  &
                                      Pollution%FuelOil1Coef%NOxSched,ErrorsFound)
          END IF
          Pollution%FuelOil1Coef%N2O    = rNumericArgs(7)
          IF (.not. lAlphaFieldBlanks(8)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#1',trim(cAlphaFieldNames(8)),trim(cAlphaArgs(8)),  &
                                      Pollution%FuelOil1Coef%N2OSched,ErrorsFound)
          END IF
          Pollution%FuelOil1Coef%SO2    = rNumericArgs(8)
          IF (.not. lAlphaFieldBlanks(9)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#1',trim(cAlphaFieldNames(9)),trim(cAlphaArgs(9)),  &
                                      Pollution%FuelOil1Coef%SO2Sched,ErrorsFound)
          END IF
          Pollution%FuelOil1Coef%PM     = rNumericArgs(9)
          IF (.not. lAlphaFieldBlanks(10)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#1',trim(cAlphaFieldNames(10)),trim(cAlphaArgs(10)),  &
                                      Pollution%FuelOil1Coef%PMSched,ErrorsFound)
          END IF
          Pollution%FuelOil1Coef%PM10   = rNumericArgs(10)
          IF (.not. lAlphaFieldBlanks(11)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#1',trim(cAlphaFieldNames(11)),trim(cAlphaArgs(11)),  &
                                      Pollution%FuelOil1Coef%PM10Sched,ErrorsFound)
          END IF
          Pollution%FuelOil1Coef%PM25   = rNumericArgs(11)
          IF (.not. lAlphaFieldBlanks(12)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#1',trim(cAlphaFieldNames(12)),trim(cAlphaArgs(12)),  &
                                      Pollution%FuelOil1Coef%PM25Sched,ErrorsFound)
          END IF
          Pollution%FuelOil1Coef%NH3    = rNumericArgs(12)
          IF (.not. lAlphaFieldBlanks(13)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#1',trim(cAlphaFieldNames(13)),trim(cAlphaArgs(13)),  &
                                      Pollution%FuelOil1Coef%NH3Sched,ErrorsFound)
          END IF
          Pollution%FuelOil1Coef%NMVOC  = rNumericArgs(13)
          IF (.not. lAlphaFieldBlanks(14)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#1',trim(cAlphaFieldNames(14)),trim(cAlphaArgs(14)),  &
                                      Pollution%FuelOil1Coef%NMVOCSched,ErrorsFound)
          END IF
          Pollution%FuelOil1Coef%Hg     = rNumericArgs(14)
          IF (.not. lAlphaFieldBlanks(15)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#1',trim(cAlphaFieldNames(15)),trim(cAlphaArgs(15)),  &
                                      Pollution%FuelOil1Coef%HgSched,ErrorsFound)
          END IF
          Pollution%FuelOil1Coef%Pb     = rNumericArgs(15)
          IF (.not. lAlphaFieldBlanks(16)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#1',trim(cAlphaFieldNames(16)),trim(cAlphaArgs(16)),  &
                                      Pollution%FuelOil1Coef%PbSched,ErrorsFound)
          END IF
          Pollution%FuelOil1Coef%Water  = rNumericArgs(16)
          IF (.not. lAlphaFieldBlanks(17)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#1',trim(cAlphaFieldNames(17)),trim(cAlphaArgs(17)),  &
                                      Pollution%FuelOil1Coef%WaterSched,ErrorsFound)
          END IF
          Pollution%FuelOil1Coef%NucHi  = rNumericArgs(17)
          IF (.not. lAlphaFieldBlanks(18)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#1',trim(cAlphaFieldNames(18)),trim(cAlphaArgs(18)),  &
                                      Pollution%FuelOil1Coef%NucHiSched,ErrorsFound)
          END IF
          Pollution%FuelOil1Coef%NucLo  = rNumericArgs(18)
          IF (.not. lAlphaFieldBlanks(19)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Fuel Oil#1',trim(cAlphaFieldNames(19)),trim(cAlphaArgs(19)),  &
                                      Pollution%FuelOil1Coef%NucLoSched,ErrorsFound)
          END IF
        CASE ('COAL')
          IF (Pollution%CoalCoef%FuelFactorUsed) THEN
            CALL ShowWarningError(TRIM(cCurrentModuleObject)//': '//TRIM(FuelType%FuelTypeNames(Loop))//' already entered.'//  &
              ' Previous entry will be used.')
            CYCLE
          ENDIF
          Pollution%CoalCoef%FuelFactorUsed = .True.
        ! Coal
          Pollution%CoalCoef%Source = rNumericArgs(2)
          IF (.not. lAlphaFieldBlanks(3)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Coal',trim(cAlphaFieldNames(3)),trim(cAlphaArgs(3)),  &
                                      Pollution%CoalCoef%SourceSched,ErrorsFound)
          END IF
          Pollution%CoalCoef%CO2    = rNumericArgs(3)
          IF (.not. lAlphaFieldBlanks(4)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Coal',trim(cAlphaFieldNames(4)),trim(cAlphaArgs(4)),  &
                                      Pollution%CoalCoef%CO2Sched,ErrorsFound)
          END IF
          Pollution%CoalCoef%CO     = rNumericArgs(4)
          IF (.not. lAlphaFieldBlanks(5)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Coal',trim(cAlphaFieldNames(5)),trim(cAlphaArgs(5)),  &
                                      Pollution%CoalCoef%COSched,ErrorsFound)
          END IF
          Pollution%CoalCoef%CH4    = rNumericArgs(5)
          IF (.not. lAlphaFieldBlanks(6)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Coal',trim(cAlphaFieldNames(6)),trim(cAlphaArgs(6)),  &
                                      Pollution%CoalCoef%CH4Sched,ErrorsFound)
          END IF
          Pollution%CoalCoef%NOx    = rNumericArgs(6)
          IF (.not. lAlphaFieldBlanks(7)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Coal',trim(cAlphaFieldNames(7)),trim(cAlphaArgs(7)),  &
                                      Pollution%CoalCoef%NOxSched,ErrorsFound)
          END IF
          Pollution%CoalCoef%N2O    = rNumericArgs(7)
          IF (.not. lAlphaFieldBlanks(8)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Coal',trim(cAlphaFieldNames(8)),trim(cAlphaArgs(8)),  &
                                      Pollution%CoalCoef%N2OSched,ErrorsFound)
          END IF
          Pollution%CoalCoef%SO2    = rNumericArgs(8)
          IF (.not. lAlphaFieldBlanks(9)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Coal',trim(cAlphaFieldNames(9)),trim(cAlphaArgs(9)),  &
                                      Pollution%CoalCoef%SO2Sched,ErrorsFound)
          END IF
          Pollution%CoalCoef%PM     = rNumericArgs(9)
          IF (.not. lAlphaFieldBlanks(10)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Coal',trim(cAlphaFieldNames(10)),trim(cAlphaArgs(10)),  &
                                      Pollution%CoalCoef%PMSched,ErrorsFound)
          END IF
          Pollution%CoalCoef%PM10   = rNumericArgs(10)
          IF (.not. lAlphaFieldBlanks(11)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Coal',trim(cAlphaFieldNames(11)),trim(cAlphaArgs(11)),  &
                                      Pollution%CoalCoef%PM10Sched,ErrorsFound)
          END IF
          Pollution%CoalCoef%PM25   = rNumericArgs(11)
          IF (.not. lAlphaFieldBlanks(12)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Coal',trim(cAlphaFieldNames(12)),trim(cAlphaArgs(12)),  &
                                      Pollution%CoalCoef%PM25Sched,ErrorsFound)
          END IF
          Pollution%CoalCoef%NH3    = rNumericArgs(12)
          IF (.not. lAlphaFieldBlanks(13)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Coal',trim(cAlphaFieldNames(13)),trim(cAlphaArgs(13)),  &
                                      Pollution%CoalCoef%NH3Sched,ErrorsFound)
          END IF
          Pollution%CoalCoef%NMVOC  = rNumericArgs(13)
          IF (.not. lAlphaFieldBlanks(14)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Coal',trim(cAlphaFieldNames(14)),trim(cAlphaArgs(14)),  &
                                      Pollution%CoalCoef%NMVOCSched,ErrorsFound)
          END IF
          Pollution%CoalCoef%Hg     = rNumericArgs(14)
          IF (.not. lAlphaFieldBlanks(15)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Coal',trim(cAlphaFieldNames(15)),trim(cAlphaArgs(15)),  &
                                      Pollution%CoalCoef%HgSched,ErrorsFound)
          END IF
          Pollution%CoalCoef%Pb     = rNumericArgs(15)
          IF (.not. lAlphaFieldBlanks(16)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Coal',trim(cAlphaFieldNames(16)),trim(cAlphaArgs(16)),  &
                                      Pollution%CoalCoef%PbSched,ErrorsFound)
          END IF
          Pollution%CoalCoef%Water  = rNumericArgs(16)
          IF (.not. lAlphaFieldBlanks(17)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Coal',trim(cAlphaFieldNames(17)),trim(cAlphaArgs(17)),  &
                                      Pollution%CoalCoef%WaterSched,ErrorsFound)
          END IF
          Pollution%CoalCoef%NucHi  = rNumericArgs(17)
          IF (.not. lAlphaFieldBlanks(18)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Coal',trim(cAlphaFieldNames(18)),trim(cAlphaArgs(18)),  &
                                      Pollution%CoalCoef%NucHiSched,ErrorsFound)
          END IF
          Pollution%CoalCoef%NucLo  = rNumericArgs(18)
          IF (.not. lAlphaFieldBlanks(19)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Coal',trim(cAlphaFieldNames(19)),trim(cAlphaArgs(19)),  &
                                      Pollution%CoalCoef%NucLoSched,ErrorsFound)
          END IF
        CASE ('ELECTRICITY','ELECTRIC','ELEC')
          IF (Pollution%ElecCoef%FuelFactorUsed) THEN
            CALL ShowWarningError(TRIM(cCurrentModuleObject)//': '//TRIM(FuelType%FuelTypeNames(Loop))//' already entered.'//  &
              ' Previous entry will be used.')
            CYCLE
          ENDIF
          Pollution%ElecCoef%FuelFactorUsed = .True.
         !Electric Coeffs
          Pollution%ElecCoef%Source = rNumericArgs(2)
          IF (.not. lAlphaFieldBlanks(3)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Electricity',trim(cAlphaFieldNames(3)),trim(cAlphaArgs(3)),  &
                                      Pollution%ElecCoef%SourceSched,ErrorsFound)
          END IF
          Pollution%ElecCoef%CO2    = rNumericArgs(3)
          IF (.not. lAlphaFieldBlanks(4)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Electricity',trim(cAlphaFieldNames(4)),trim(cAlphaArgs(4)),  &
                                      Pollution%ElecCoef%CO2Sched,ErrorsFound)
          END IF
          Pollution%ElecCoef%CO     = rNumericArgs(4)
          IF (.not. lAlphaFieldBlanks(5)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Electricity',trim(cAlphaFieldNames(5)),trim(cAlphaArgs(5)),  &
                                      Pollution%ElecCoef%COSched,ErrorsFound)
          END IF
          Pollution%ElecCoef%CH4    = rNumericArgs(5)
          IF (.not. lAlphaFieldBlanks(6)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Electricity',trim(cAlphaFieldNames(6)),trim(cAlphaArgs(6)),  &
                                      Pollution%ElecCoef%CH4Sched,ErrorsFound)
          END IF
          Pollution%ElecCoef%NOx    = rNumericArgs(6)
          IF (.not. lAlphaFieldBlanks(7)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Electricity',trim(cAlphaFieldNames(7)),trim(cAlphaArgs(7)),  &
                                      Pollution%ElecCoef%NOxSched,ErrorsFound)
          END IF
          Pollution%ElecCoef%N2O    = rNumericArgs(7)
          IF (.not. lAlphaFieldBlanks(8)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Electricity',trim(cAlphaFieldNames(8)),trim(cAlphaArgs(8)),  &
                                      Pollution%ElecCoef%N2OSched,ErrorsFound)
          END IF
          Pollution%ElecCoef%SO2    = rNumericArgs(8)
          IF (.not. lAlphaFieldBlanks(9)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Electricity',trim(cAlphaFieldNames(9)),trim(cAlphaArgs(9)),  &
                                      Pollution%ElecCoef%SO2Sched,ErrorsFound)
          END IF
          Pollution%ElecCoef%PM     = rNumericArgs(9)
          IF (.not. lAlphaFieldBlanks(10)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Electricity',trim(cAlphaFieldNames(10)),trim(cAlphaArgs(10)),  &
                                      Pollution%ElecCoef%PMSched,ErrorsFound)
          END IF
          Pollution%ElecCoef%PM10   = rNumericArgs(10)
          IF (.not. lAlphaFieldBlanks(11)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Electricity',trim(cAlphaFieldNames(11)),trim(cAlphaArgs(11)),  &
                                      Pollution%ElecCoef%PM10Sched,ErrorsFound)
          END IF
          Pollution%ElecCoef%PM25   = rNumericArgs(11)
          IF (.not. lAlphaFieldBlanks(12)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Electricity',trim(cAlphaFieldNames(12)),trim(cAlphaArgs(12)),  &
                                      Pollution%ElecCoef%PM25Sched,ErrorsFound)
          END IF
          Pollution%ElecCoef%NH3    = rNumericArgs(12)
          IF (.not. lAlphaFieldBlanks(13)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Electricity',trim(cAlphaFieldNames(13)),trim(cAlphaArgs(13)),  &
                                      Pollution%ElecCoef%NH3Sched,ErrorsFound)
          END IF
          Pollution%ElecCoef%NMVOC  = rNumericArgs(13)
          IF (.not. lAlphaFieldBlanks(14)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Electricity',trim(cAlphaFieldNames(14)),trim(cAlphaArgs(14)),  &
                                      Pollution%ElecCoef%NMVOCSched,ErrorsFound)
          END IF
          Pollution%ElecCoef%Hg     = rNumericArgs(14)
          IF (.not. lAlphaFieldBlanks(15)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Electricity',trim(cAlphaFieldNames(15)),trim(cAlphaArgs(15)),  &
                                      Pollution%ElecCoef%HgSched,ErrorsFound)
          END IF
          Pollution%ElecCoef%Pb     = rNumericArgs(15)
          IF (.not. lAlphaFieldBlanks(16)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Electricity',trim(cAlphaFieldNames(16)),trim(cAlphaArgs(16)),  &
                                      Pollution%ElecCoef%PbSched,ErrorsFound)
          END IF
          Pollution%ElecCoef%Water  = rNumericArgs(16)
          IF (.not. lAlphaFieldBlanks(17)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Electricity',trim(cAlphaFieldNames(17)),trim(cAlphaArgs(17)),  &
                                      Pollution%ElecCoef%WaterSched,ErrorsFound)
          END IF
          Pollution%ElecCoef%NucHi  = rNumericArgs(17)
          IF (.not. lAlphaFieldBlanks(18)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Electricity',trim(cAlphaFieldNames(18)),trim(cAlphaArgs(18)),  &
                                      Pollution%ElecCoef%NucHiSched,ErrorsFound)
          END IF
          Pollution%ElecCoef%NucLo  = rNumericArgs(18)
          IF (.not. lAlphaFieldBlanks(19)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Electricity',trim(cAlphaFieldNames(19)),trim(cAlphaArgs(19)),  &
                                      Pollution%ElecCoef%NucLoSched,ErrorsFound)
          END IF
        CASE ('GASOLINE')
          IF (Pollution%GasolineCoef%FuelFactorUsed) THEN
            CALL ShowWarningError(TRIM(cCurrentModuleObject)//': '//TRIM(FuelType%FuelTypeNames(Loop))//' already entered.'//  &
              ' Previous entry will be used.')
            CYCLE
          ENDIF
          Pollution%GasolineCoef%FuelFactorUsed = .True.
         !Gasoline Coeffs
          Pollution%GasolineCoef%Source = rNumericArgs(2)
          IF (.not. lAlphaFieldBlanks(3)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Gasoline',trim(cAlphaFieldNames(3)),trim(cAlphaArgs(3)),  &
                                      Pollution%GasolineCoef%SourceSched,ErrorsFound)
          END IF
          Pollution%GasolineCoef%CO2    = rNumericArgs(3)
          IF (.not. lAlphaFieldBlanks(4)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Gasoline',trim(cAlphaFieldNames(4)),trim(cAlphaArgs(4)),  &
                                      Pollution%GasolineCoef%CO2Sched,ErrorsFound)
          END IF
          Pollution%GasolineCoef%CO     = rNumericArgs(4)
          IF (.not. lAlphaFieldBlanks(5)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Gasoline',trim(cAlphaFieldNames(5)),trim(cAlphaArgs(5)),  &
                                      Pollution%GasolineCoef%COSched,ErrorsFound)
          END IF
          Pollution%GasolineCoef%CH4    = rNumericArgs(5)
          IF (.not. lAlphaFieldBlanks(6)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Gasoline',trim(cAlphaFieldNames(6)),trim(cAlphaArgs(6)),  &
                                      Pollution%GasolineCoef%CH4Sched,ErrorsFound)
          END IF
          Pollution%GasolineCoef%NOx    = rNumericArgs(6)
          IF (.not. lAlphaFieldBlanks(7)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Gasoline',trim(cAlphaFieldNames(7)),trim(cAlphaArgs(7)),  &
                                      Pollution%GasolineCoef%NOxSched,ErrorsFound)
          END IF
          Pollution%GasolineCoef%N2O    = rNumericArgs(7)
          IF (.not. lAlphaFieldBlanks(8)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Gasoline',trim(cAlphaFieldNames(8)),trim(cAlphaArgs(8)),  &
                                      Pollution%GasolineCoef%N2OSched,ErrorsFound)
          END IF
          Pollution%GasolineCoef%SO2    = rNumericArgs(8)
          IF (.not. lAlphaFieldBlanks(9)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Gasoline',trim(cAlphaFieldNames(9)),trim(cAlphaArgs(9)),  &
                                      Pollution%GasolineCoef%SO2Sched,ErrorsFound)
          END IF
          Pollution%GasolineCoef%PM     = rNumericArgs(9)
          IF (.not. lAlphaFieldBlanks(10)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Gasoline',trim(cAlphaFieldNames(10)),trim(cAlphaArgs(10)),  &
                                      Pollution%GasolineCoef%PMSched,ErrorsFound)
          END IF
          Pollution%GasolineCoef%PM10   = rNumericArgs(10)
          IF (.not. lAlphaFieldBlanks(11)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Gasoline',trim(cAlphaFieldNames(11)),trim(cAlphaArgs(11)),  &
                                      Pollution%GasolineCoef%PM10Sched,ErrorsFound)
          END IF
          Pollution%GasolineCoef%PM25   = rNumericArgs(11)
          IF (.not. lAlphaFieldBlanks(12)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Gasoline',trim(cAlphaFieldNames(12)),trim(cAlphaArgs(12)),  &
                                      Pollution%GasolineCoef%PM25Sched,ErrorsFound)
          END IF
          Pollution%GasolineCoef%NH3    = rNumericArgs(12)
          IF (.not. lAlphaFieldBlanks(13)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Gasoline',trim(cAlphaFieldNames(13)),trim(cAlphaArgs(13)),  &
                                      Pollution%GasolineCoef%NH3Sched,ErrorsFound)
          END IF
          Pollution%GasolineCoef%NMVOC  = rNumericArgs(13)
          IF (.not. lAlphaFieldBlanks(14)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Gasoline',trim(cAlphaFieldNames(14)),trim(cAlphaArgs(14)),  &
                                      Pollution%GasolineCoef%NMVOCSched,ErrorsFound)
          END IF
          Pollution%GasolineCoef%Hg     = rNumericArgs(14)
          IF (.not. lAlphaFieldBlanks(15)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Gasoline',trim(cAlphaFieldNames(15)),trim(cAlphaArgs(15)),  &
                                      Pollution%GasolineCoef%HgSched,ErrorsFound)
          END IF
          Pollution%GasolineCoef%Pb     = rNumericArgs(15)
          IF (.not. lAlphaFieldBlanks(16)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Gasoline',trim(cAlphaFieldNames(16)),trim(cAlphaArgs(16)),  &
                                      Pollution%GasolineCoef%PbSched,ErrorsFound)
          END IF
          Pollution%GasolineCoef%Water  = rNumericArgs(16)
          IF (.not. lAlphaFieldBlanks(17)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Gasoline',trim(cAlphaFieldNames(17)),trim(cAlphaArgs(17)),  &
                                      Pollution%GasolineCoef%WaterSched,ErrorsFound)
          END IF
          Pollution%GasolineCoef%NucHi  = rNumericArgs(17)
          IF (.not. lAlphaFieldBlanks(18)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Gasoline',trim(cAlphaFieldNames(18)),trim(cAlphaArgs(18)),  &
                                      Pollution%GasolineCoef%NucHiSched,ErrorsFound)
          END IF
          Pollution%GasolineCoef%NucLo  = rNumericArgs(18)
          IF (.not. lAlphaFieldBlanks(19)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Gasoline',trim(cAlphaFieldNames(19)),trim(cAlphaArgs(19)),  &
                                      Pollution%GasolineCoef%NucLoSched,ErrorsFound)
          END IF
        CASE ('PROPANE','LPG','PROPANEGAS','PROPANE GAS')
          IF (Pollution%PropaneCoef%FuelFactorUsed) THEN
            CALL ShowWarningError(TRIM(cCurrentModuleObject)//': '//TRIM(FuelType%FuelTypeNames(Loop))//' already entered.'//  &
              ' Previous entry will be used.')
            CYCLE
          ENDIF
          Pollution%PropaneCoef%FuelFactorUsed = .True.
         !Propane Coeffs
          Pollution%PropaneCoef%Source = rNumericArgs(2)
          IF (.not. lAlphaFieldBlanks(3)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Propane',trim(cAlphaFieldNames(3)),trim(cAlphaArgs(3)),  &
                                      Pollution%PropaneCoef%SourceSched,ErrorsFound)
          END IF
          Pollution%PropaneCoef%CO2    = rNumericArgs(3)
          IF (.not. lAlphaFieldBlanks(4)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Propane',trim(cAlphaFieldNames(4)),trim(cAlphaArgs(4)),  &
                                      Pollution%PropaneCoef%CO2Sched,ErrorsFound)
          END IF
          Pollution%PropaneCoef%CO     = rNumericArgs(4)
          IF (.not. lAlphaFieldBlanks(5)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Propane',trim(cAlphaFieldNames(5)),trim(cAlphaArgs(5)),  &
                                      Pollution%PropaneCoef%COSched,ErrorsFound)
          END IF
          Pollution%PropaneCoef%CH4    = rNumericArgs(5)
          IF (.not. lAlphaFieldBlanks(6)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Propane',trim(cAlphaFieldNames(6)),trim(cAlphaArgs(6)),  &
                                      Pollution%PropaneCoef%CH4Sched,ErrorsFound)
          END IF
          Pollution%PropaneCoef%NOx    = rNumericArgs(6)
          IF (.not. lAlphaFieldBlanks(7)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Propane',trim(cAlphaFieldNames(7)),trim(cAlphaArgs(7)),  &
                                      Pollution%PropaneCoef%NOxSched,ErrorsFound)
          END IF
          Pollution%PropaneCoef%N2O    = rNumericArgs(7)
          IF (.not. lAlphaFieldBlanks(8)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Propane',trim(cAlphaFieldNames(8)),trim(cAlphaArgs(8)),  &
                                      Pollution%PropaneCoef%N2OSched,ErrorsFound)
          END IF
          Pollution%PropaneCoef%SO2    = rNumericArgs(8)
          IF (.not. lAlphaFieldBlanks(9)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Propane',trim(cAlphaFieldNames(9)),trim(cAlphaArgs(9)),  &
                                      Pollution%PropaneCoef%SO2Sched,ErrorsFound)
          END IF
          Pollution%PropaneCoef%PM     = rNumericArgs(9)
          IF (.not. lAlphaFieldBlanks(10)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Propane',trim(cAlphaFieldNames(10)),trim(cAlphaArgs(10)),  &
                                      Pollution%PropaneCoef%PMSched,ErrorsFound)
          END IF
          Pollution%PropaneCoef%PM10   = rNumericArgs(10)
          IF (.not. lAlphaFieldBlanks(11)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Propane',trim(cAlphaFieldNames(11)),trim(cAlphaArgs(11)),  &
                                      Pollution%PropaneCoef%PM10Sched,ErrorsFound)
          END IF
          Pollution%PropaneCoef%PM25   = rNumericArgs(11)
          IF (.not. lAlphaFieldBlanks(12)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Propane',trim(cAlphaFieldNames(12)),trim(cAlphaArgs(12)),  &
                                      Pollution%PropaneCoef%PM25Sched,ErrorsFound)
          END IF
          Pollution%PropaneCoef%NH3    = rNumericArgs(12)
          IF (.not. lAlphaFieldBlanks(13)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Propane',trim(cAlphaFieldNames(13)),trim(cAlphaArgs(13)),  &
                                      Pollution%PropaneCoef%NH3Sched,ErrorsFound)
          END IF
          Pollution%PropaneCoef%NMVOC  = rNumericArgs(13)
          IF (.not. lAlphaFieldBlanks(14)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Propane',trim(cAlphaFieldNames(14)),trim(cAlphaArgs(14)),  &
                                      Pollution%PropaneCoef%NMVOCSched,ErrorsFound)
          END IF
          Pollution%PropaneCoef%Hg     = rNumericArgs(14)
          IF (.not. lAlphaFieldBlanks(15)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Propane',trim(cAlphaFieldNames(15)),trim(cAlphaArgs(15)),  &
                                      Pollution%PropaneCoef%HgSched,ErrorsFound)
          END IF
          Pollution%PropaneCoef%Pb     = rNumericArgs(15)
          IF (.not. lAlphaFieldBlanks(16)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Propane',trim(cAlphaFieldNames(16)),trim(cAlphaArgs(16)),  &
                                      Pollution%PropaneCoef%PbSched,ErrorsFound)
          END IF
          Pollution%PropaneCoef%Water  = rNumericArgs(16)
          IF (.not. lAlphaFieldBlanks(17)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Propane',trim(cAlphaFieldNames(17)),trim(cAlphaArgs(17)),  &
                                      Pollution%PropaneCoef%WaterSched,ErrorsFound)
          END IF
          Pollution%PropaneCoef%NucHi  = rNumericArgs(17)
          IF (.not. lAlphaFieldBlanks(18)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Propane',trim(cAlphaFieldNames(18)),trim(cAlphaArgs(18)),  &
                                      Pollution%PropaneCoef%NucHiSched,ErrorsFound)
          END IF
          Pollution%PropaneCoef%NucLo  = rNumericArgs(18)
          IF (.not. lAlphaFieldBlanks(19)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Propane',trim(cAlphaFieldNames(19)),trim(cAlphaArgs(19)),  &
                                      Pollution%PropaneCoef%NucLoSched,ErrorsFound)
          END IF
        CASE ('DIESEL')
          IF (Pollution%DieselCoef%FuelFactorUsed) THEN
            CALL ShowWarningError(TRIM(cCurrentModuleObject)//': '//TRIM(FuelType%FuelTypeNames(Loop))//' already entered.'//  &
              ' Previous entry will be used.')
            CYCLE
          ENDIF
          Pollution%DieselCoef%FuelFactorUsed = .True.
         !Diesel Coeffs
          Pollution%DieselCoef%Source = rNumericArgs(2)
          IF (.not. lAlphaFieldBlanks(3)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Diesel',trim(cAlphaFieldNames(3)),trim(cAlphaArgs(3)),  &
                                      Pollution%DieselCoef%SourceSched,ErrorsFound)
          END IF
          Pollution%DieselCoef%CO2    = rNumericArgs(3)
          IF (.not. lAlphaFieldBlanks(4)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Diesel',trim(cAlphaFieldNames(4)),trim(cAlphaArgs(4)),  &
                                      Pollution%DieselCoef%CO2Sched,ErrorsFound)
          END IF
          Pollution%DieselCoef%CO     = rNumericArgs(4)
          IF (.not. lAlphaFieldBlanks(5)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Diesel',trim(cAlphaFieldNames(5)),trim(cAlphaArgs(5)),  &
                                      Pollution%DieselCoef%COSched,ErrorsFound)
          END IF
          Pollution%DieselCoef%CH4    = rNumericArgs(5)
          IF (.not. lAlphaFieldBlanks(6)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Diesel',trim(cAlphaFieldNames(6)),trim(cAlphaArgs(6)),  &
                                      Pollution%DieselCoef%CH4Sched,ErrorsFound)
          END IF
          Pollution%DieselCoef%NOx    = rNumericArgs(6)
          IF (.not. lAlphaFieldBlanks(7)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Diesel',trim(cAlphaFieldNames(7)),trim(cAlphaArgs(7)),  &
                                      Pollution%DieselCoef%NOxSched,ErrorsFound)
          END IF
          Pollution%DieselCoef%N2O    = rNumericArgs(7)
          IF (.not. lAlphaFieldBlanks(8)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Diesel',trim(cAlphaFieldNames(8)),trim(cAlphaArgs(8)),  &
                                      Pollution%DieselCoef%N2OSched,ErrorsFound)
          END IF
          Pollution%DieselCoef%SO2    = rNumericArgs(8)
          IF (.not. lAlphaFieldBlanks(9)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Diesel',trim(cAlphaFieldNames(9)),trim(cAlphaArgs(9)),  &
                                      Pollution%DieselCoef%SO2Sched,ErrorsFound)
          END IF
          Pollution%DieselCoef%PM     = rNumericArgs(9)
          IF (.not. lAlphaFieldBlanks(10)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Diesel',trim(cAlphaFieldNames(10)),trim(cAlphaArgs(10)),  &
                                      Pollution%DieselCoef%PMSched,ErrorsFound)
          END IF
          Pollution%DieselCoef%PM10   = rNumericArgs(10)
          IF (.not. lAlphaFieldBlanks(11)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Diesel',trim(cAlphaFieldNames(11)),trim(cAlphaArgs(11)),  &
                                      Pollution%DieselCoef%PM10Sched,ErrorsFound)
          END IF
          Pollution%DieselCoef%PM25   = rNumericArgs(11)
          IF (.not. lAlphaFieldBlanks(12)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Diesel',trim(cAlphaFieldNames(12)),trim(cAlphaArgs(12)),  &
                                      Pollution%DieselCoef%PM25Sched,ErrorsFound)
          END IF
          Pollution%DieselCoef%NH3    = rNumericArgs(12)
          IF (.not. lAlphaFieldBlanks(13)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Diesel',trim(cAlphaFieldNames(13)),trim(cAlphaArgs(13)),  &
                                      Pollution%DieselCoef%NH3Sched,ErrorsFound)
          END IF
          Pollution%DieselCoef%NMVOC  = rNumericArgs(13)
          IF (.not. lAlphaFieldBlanks(14)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Diesel',trim(cAlphaFieldNames(14)),trim(cAlphaArgs(14)),  &
                                      Pollution%DieselCoef%NMVOCSched,ErrorsFound)
          END IF
          Pollution%DieselCoef%Hg     = rNumericArgs(14)
          IF (.not. lAlphaFieldBlanks(15)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Diesel',trim(cAlphaFieldNames(15)),trim(cAlphaArgs(15)),  &
                                      Pollution%DieselCoef%HgSched,ErrorsFound)
          END IF
          Pollution%DieselCoef%Pb     = rNumericArgs(15)
          IF (.not. lAlphaFieldBlanks(16)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Diesel',trim(cAlphaFieldNames(16)),trim(cAlphaArgs(16)),  &
                                      Pollution%DieselCoef%PbSched,ErrorsFound)
          END IF
          Pollution%DieselCoef%Water  = rNumericArgs(16)
          IF (.not. lAlphaFieldBlanks(17)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Diesel',trim(cAlphaFieldNames(17)),trim(cAlphaArgs(17)),  &
                                      Pollution%DieselCoef%WaterSched,ErrorsFound)
          END IF
          Pollution%DieselCoef%NucHi  = rNumericArgs(17)
          IF (.not. lAlphaFieldBlanks(18)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Diesel',trim(cAlphaFieldNames(18)),trim(cAlphaArgs(18)),  &
                                      Pollution%DieselCoef%NucHiSched,ErrorsFound)
          END IF
          Pollution%DieselCoef%NucLo  = rNumericArgs(18)
          IF (.not. lAlphaFieldBlanks(19)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'Diesel',trim(cAlphaFieldNames(19)),trim(cAlphaArgs(19)),  &
                                      Pollution%DieselCoef%NucLoSched,ErrorsFound)
          END IF
        CASE ('OTHERFUEL1')
          IF (Pollution%OtherFuel1Coef%FuelFactorUsed) THEN
            CALL ShowWarningError(TRIM(cCurrentModuleObject)//': '//TRIM(FuelType%FuelTypeNames(Loop))//' already entered.'//  &
              ' Previous entry will be used.')
            CYCLE
          ENDIF
          Pollution%OtherFuel1Coef%FuelFactorUsed = .True.
         !OtherFuel1 Coeffs
          Pollution%OtherFuel1Coef%Source = rNumericArgs(2)
          IF (.not. lAlphaFieldBlanks(3)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel1',trim(cAlphaFieldNames(3)),trim(cAlphaArgs(3)),  &
                                      Pollution%OtherFuel1Coef%SourceSched,ErrorsFound)
          END IF
          Pollution%OtherFuel1Coef%CO2    = rNumericArgs(3)
          IF (.not. lAlphaFieldBlanks(4)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel1',trim(cAlphaFieldNames(4)),trim(cAlphaArgs(4)),  &
                                      Pollution%OtherFuel1Coef%CO2Sched,ErrorsFound)
          END IF
          Pollution%OtherFuel1Coef%CO     = rNumericArgs(4)
          IF (.not. lAlphaFieldBlanks(5)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel1',trim(cAlphaFieldNames(5)),trim(cAlphaArgs(5)),  &
                                      Pollution%OtherFuel1Coef%COSched,ErrorsFound)
          END IF
          Pollution%OtherFuel1Coef%CH4    = rNumericArgs(5)
          IF (.not. lAlphaFieldBlanks(6)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel1',trim(cAlphaFieldNames(6)),trim(cAlphaArgs(6)),  &
                                      Pollution%OtherFuel1Coef%CH4Sched,ErrorsFound)
          END IF
          Pollution%OtherFuel1Coef%NOx    = rNumericArgs(6)
          IF (.not. lAlphaFieldBlanks(7)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel1',trim(cAlphaFieldNames(7)),trim(cAlphaArgs(7)),  &
                                      Pollution%OtherFuel1Coef%NOxSched,ErrorsFound)
          END IF
          Pollution%OtherFuel1Coef%N2O    = rNumericArgs(7)
          IF (.not. lAlphaFieldBlanks(8)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel1',trim(cAlphaFieldNames(8)),trim(cAlphaArgs(8)),  &
                                      Pollution%OtherFuel1Coef%N2OSched,ErrorsFound)
          END IF
          Pollution%OtherFuel1Coef%SO2    = rNumericArgs(8)
          IF (.not. lAlphaFieldBlanks(9)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel1',trim(cAlphaFieldNames(9)),trim(cAlphaArgs(9)),  &
                                      Pollution%OtherFuel1Coef%SO2Sched,ErrorsFound)
          END IF
          Pollution%OtherFuel1Coef%PM     = rNumericArgs(9)
          IF (.not. lAlphaFieldBlanks(10)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel1',trim(cAlphaFieldNames(10)),trim(cAlphaArgs(10)),  &
                                      Pollution%OtherFuel1Coef%PMSched,ErrorsFound)
          END IF
          Pollution%OtherFuel1Coef%PM10   = rNumericArgs(10)
          IF (.not. lAlphaFieldBlanks(11)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel1',trim(cAlphaFieldNames(11)),trim(cAlphaArgs(11)),  &
                                      Pollution%OtherFuel1Coef%PM10Sched,ErrorsFound)
          END IF
          Pollution%OtherFuel1Coef%PM25   = rNumericArgs(11)
          IF (.not. lAlphaFieldBlanks(12)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel1',trim(cAlphaFieldNames(12)),trim(cAlphaArgs(12)),  &
                                      Pollution%OtherFuel1Coef%PM25Sched,ErrorsFound)
          END IF
          Pollution%OtherFuel1Coef%NH3    = rNumericArgs(12)
          IF (.not. lAlphaFieldBlanks(13)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel1',trim(cAlphaFieldNames(13)),trim(cAlphaArgs(13)),  &
                                      Pollution%OtherFuel1Coef%NH3Sched,ErrorsFound)
          END IF
          Pollution%OtherFuel1Coef%NMVOC  = rNumericArgs(13)
          IF (.not. lAlphaFieldBlanks(14)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel1',trim(cAlphaFieldNames(14)),trim(cAlphaArgs(14)),  &
                                      Pollution%OtherFuel1Coef%NMVOCSched,ErrorsFound)
          END IF
          Pollution%OtherFuel1Coef%Hg     = rNumericArgs(14)
          IF (.not. lAlphaFieldBlanks(15)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel1',trim(cAlphaFieldNames(15)),trim(cAlphaArgs(15)),  &
                                      Pollution%OtherFuel1Coef%HgSched,ErrorsFound)
          END IF
          Pollution%OtherFuel1Coef%Pb     = rNumericArgs(15)
          IF (.not. lAlphaFieldBlanks(16)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel1',trim(cAlphaFieldNames(16)),trim(cAlphaArgs(16)),  &
                                      Pollution%OtherFuel1Coef%PbSched,ErrorsFound)
          END IF
          Pollution%OtherFuel1Coef%Water  = rNumericArgs(16)
          IF (.not. lAlphaFieldBlanks(17)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel1',trim(cAlphaFieldNames(17)),trim(cAlphaArgs(17)),  &
                                      Pollution%OtherFuel1Coef%WaterSched,ErrorsFound)
          END IF
          Pollution%OtherFuel1Coef%NucHi  = rNumericArgs(17)
          IF (.not. lAlphaFieldBlanks(18)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel1',trim(cAlphaFieldNames(18)),trim(cAlphaArgs(18)),  &
                                      Pollution%OtherFuel1Coef%NucHiSched,ErrorsFound)
          END IF
          Pollution%OtherFuel1Coef%NucLo  = rNumericArgs(18)
          IF (.not. lAlphaFieldBlanks(19)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel1',trim(cAlphaFieldNames(19)),trim(cAlphaArgs(19)),  &
                                      Pollution%OtherFuel1Coef%NucLoSched,ErrorsFound)
          END IF
        CASE ('OTHERFUEL2')
          IF (Pollution%OtherFuel2Coef%FuelFactorUsed) THEN
            CALL ShowWarningError(TRIM(cCurrentModuleObject)//': '//TRIM(FuelType%FuelTypeNames(Loop))//' already entered.'//  &
              ' Previous entry will be used.')
            CYCLE
          ENDIF
          Pollution%OtherFuel2Coef%FuelFactorUsed = .True.
         !OtherFuel2 Coeffs
          Pollution%OtherFuel2Coef%Source = rNumericArgs(2)
          IF (.not. lAlphaFieldBlanks(3)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel2',trim(cAlphaFieldNames(3)),trim(cAlphaArgs(3)),  &
                                      Pollution%OtherFuel2Coef%SourceSched,ErrorsFound)
          END IF
          Pollution%OtherFuel2Coef%CO2    = rNumericArgs(3)
          IF (.not. lAlphaFieldBlanks(4)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel2',trim(cAlphaFieldNames(4)),trim(cAlphaArgs(4)),  &
                                      Pollution%OtherFuel2Coef%CO2Sched,ErrorsFound)
          END IF
          Pollution%OtherFuel2Coef%CO     = rNumericArgs(4)
          IF (.not. lAlphaFieldBlanks(5)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel2',trim(cAlphaFieldNames(5)),trim(cAlphaArgs(5)),  &
                                      Pollution%OtherFuel2Coef%COSched,ErrorsFound)
          END IF
          Pollution%OtherFuel2Coef%CH4    = rNumericArgs(5)
          IF (.not. lAlphaFieldBlanks(6)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel2',trim(cAlphaFieldNames(6)),trim(cAlphaArgs(6)),  &
                                      Pollution%OtherFuel2Coef%CH4Sched,ErrorsFound)
          END IF
          Pollution%OtherFuel2Coef%NOx    = rNumericArgs(6)
          IF (.not. lAlphaFieldBlanks(7)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel2',trim(cAlphaFieldNames(7)),trim(cAlphaArgs(7)),  &
                                      Pollution%OtherFuel2Coef%NOxSched,ErrorsFound)
          END IF
          Pollution%OtherFuel2Coef%N2O    = rNumericArgs(7)
          IF (.not. lAlphaFieldBlanks(8)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel2',trim(cAlphaFieldNames(8)),trim(cAlphaArgs(8)),  &
                                      Pollution%OtherFuel2Coef%N2OSched,ErrorsFound)
          END IF
          Pollution%OtherFuel2Coef%SO2    = rNumericArgs(8)
          IF (.not. lAlphaFieldBlanks(9)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel2',trim(cAlphaFieldNames(9)),trim(cAlphaArgs(9)),  &
                                      Pollution%OtherFuel2Coef%SO2Sched,ErrorsFound)
          END IF
          Pollution%OtherFuel2Coef%PM     = rNumericArgs(9)
          IF (.not. lAlphaFieldBlanks(10)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel2',trim(cAlphaFieldNames(10)),trim(cAlphaArgs(10)),  &
                                      Pollution%OtherFuel2Coef%PMSched,ErrorsFound)
          END IF
          Pollution%OtherFuel2Coef%PM10   = rNumericArgs(10)
          IF (.not. lAlphaFieldBlanks(11)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel2',trim(cAlphaFieldNames(11)),trim(cAlphaArgs(11)),  &
                                      Pollution%OtherFuel2Coef%PM10Sched,ErrorsFound)
          END IF
          Pollution%OtherFuel2Coef%PM25   = rNumericArgs(11)
          IF (.not. lAlphaFieldBlanks(12)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel2',trim(cAlphaFieldNames(12)),trim(cAlphaArgs(12)),  &
                                      Pollution%OtherFuel2Coef%PM25Sched,ErrorsFound)
          END IF
          Pollution%OtherFuel2Coef%NH3    = rNumericArgs(12)
          IF (.not. lAlphaFieldBlanks(13)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel2',trim(cAlphaFieldNames(13)),trim(cAlphaArgs(13)),  &
                                      Pollution%OtherFuel2Coef%NH3Sched,ErrorsFound)
          END IF
          Pollution%OtherFuel2Coef%NMVOC  = rNumericArgs(13)
          IF (.not. lAlphaFieldBlanks(14)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel2',trim(cAlphaFieldNames(14)),trim(cAlphaArgs(14)),  &
                                      Pollution%OtherFuel2Coef%NMVOCSched,ErrorsFound)
          END IF
          Pollution%OtherFuel2Coef%Hg     = rNumericArgs(14)
          IF (.not. lAlphaFieldBlanks(15)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel2',trim(cAlphaFieldNames(15)),trim(cAlphaArgs(15)),  &
                                      Pollution%OtherFuel2Coef%HgSched,ErrorsFound)
          END IF
          Pollution%OtherFuel2Coef%Pb     = rNumericArgs(15)
          IF (.not. lAlphaFieldBlanks(16)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel2',trim(cAlphaFieldNames(16)),trim(cAlphaArgs(16)),  &
                                      Pollution%OtherFuel2Coef%PbSched,ErrorsFound)
          END IF
          Pollution%OtherFuel2Coef%Water  = rNumericArgs(16)
          IF (.not. lAlphaFieldBlanks(17)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel2',trim(cAlphaFieldNames(17)),trim(cAlphaArgs(17)),  &
                                      Pollution%OtherFuel2Coef%WaterSched,ErrorsFound)
          END IF
          Pollution%OtherFuel2Coef%NucHi  = rNumericArgs(17)
          IF (.not. lAlphaFieldBlanks(18)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel2',trim(cAlphaFieldNames(18)),trim(cAlphaArgs(18)),  &
                                      Pollution%OtherFuel2Coef%NucHiSched,ErrorsFound)
          END IF
          Pollution%OtherFuel2Coef%NucLo  = rNumericArgs(18)
          IF (.not. lAlphaFieldBlanks(19)) THEN
            CALL CheckFFSchedule(trim(cCurrentModuleObject),'OtherFuel2',trim(cAlphaFieldNames(19)),trim(cAlphaArgs(19)),  &
                                      Pollution%OtherFuel2Coef%NucLoSched,ErrorsFound)
          END IF
        CASE DEFAULT
          CALL ShowSevereError('Illegal FuelType for Pollution Calc Entered='//TRIM(FuelType%FuelTypeNames(Loop)))
          ErrorsFound=.true.
      END SELECT
    End Do ! End of the NumEnergyTypes Do Loop
    FuelType%ElecFacilityIndex     = GetMeterIndex('Electricity:Facility')
    FuelType%DieselFacilityIndex   = GetMeterIndex('Diesel:Facility')
    FuelType%PurchCoolFacilityIndex = GetMeterIndex('DistrictCooling:Facility')
    FuelType%PurchHeatFacilityIndex = GetMeterIndex('DistrictHeating:Facility')
    FuelType%NatGasFacilityIndex   = GetMeterIndex('Gas:Facility')
    FuelType%GasolineFacilityIndex = GetMeterIndex('Gasoline:Facility')
    FuelType%CoalFacilityIndex     = GetMeterIndex('Coal:Facility')
    FuelType%FuelOil1FacilityIndex = GetMeterIndex('FuelOil#1:Facility')
    FuelType%FuelOil2FacilityIndex = GetMeterIndex('FuelOil#2:Facility')
    FuelType%PropaneFacilityIndex  = GetMeterIndex('Propane:Facility')
    FuelType%OtherFuel1FacilityIndex  = GetMeterIndex('OtherFuel1:Facility')
    FuelType%OtherFuel2FacilityIndex  = GetMeterIndex('OtherFuel2:Facility')
    FuelType%ElecProducedFacilityIndex = GetMeterIndex('ElectricityProduced:Facility')
    FuelType%SteamFacilityIndex    = GetMeterIndex('Steam:Facility')
    FuelType%ElecPurchasedFacilityIndex = GetMeterIndex('ElectricityPurchased:Facility')
    FuelType%ElecSurplusSoldFacilityIndex = GetMeterIndex('ElectricitySurplusSold:Facility')
    IF (PollutionReportSetup) THEN  ! only do this if reporting on the pollution
      !Need to go through all of the Fuel Types and make sure a Fuel Factor was found for each type of energy being simulated
      ! Check for Electricity
      If(.not. Pollution%ElecCoef%FuelFactorUsed  &
              .and. ((FuelType%ElecFacilityIndex > 0) .or. (FuelType%ElecProducedFacilityIndex > 0)  &
              .or. (FuelType%PurchCoolFacilityIndex > 0))) Then
          CALL ShowSevereError(TRIM(cCurrentModuleObject)//  &
             ' Not Found or Fuel not specified For Pollution Calculation for ELECTRICITY')
          ErrorsFound=.true.
      End If
      ! Check for Natural Gas
      If(.not. Pollution%NatGasCoef%FuelFactorUsed &
               .and. ((FuelType%NatGasFacilityIndex > 0) .or. (FuelType%PurchHeatFacilityIndex>0) &
               .or. (FuelType%SteamFacilityIndex  > 0))) Then
          CALL ShowSevereError(TRIM(cCurrentModuleObject)//  &
             ' Not Found or Fuel not specified For Pollution Calculation for NATURAL GAS')
          ErrorsFound=.true.
      End If
      ! Check for Residual Oil
      If(.not. Pollution%FuelOil2Coef%FuelFactorUsed .and. (FuelType%FuelOil2FacilityIndex>0)) Then
          CALL ShowSevereError(TRIM(cCurrentModuleObject)//  &
             ' Not Found or Fuel not specified For Pollution Calculation for RESIDUAL/FUEL OIL #2')
          ErrorsFound=.true.
      End If
      ! Check for Distillate Oil
      If(.not. Pollution%FuelOil1Coef%FuelFactorUsed .and. (FuelType%FuelOil1FacilityIndex>0)) Then
          CALL ShowSevereError(TRIM(cCurrentModuleObject)//  &
             ' Not Found or Fuel not specified For Pollution Calculation for DISTILLATE/FUEL OIL #1')
          ErrorsFound=.true.
      End If
      ! Check for Coal
      If(.not. Pollution%CoalCoef%FuelFactorUsed .and. (FuelType%CoalFacilityIndex > 0)) Then
          CALL ShowSevereError(TRIM(cCurrentModuleObject)//  &
             ' Not Found or Fuel not specified For Pollution Calculation for COAL')
          ErrorsFound=.true.
      End If
      ! Check for Gasoline
      If(.not. Pollution%GasolineCoef%FuelFactorUsed .and. (FuelType%GasolineFacilityIndex > 0)) Then
          CALL ShowSevereError(TRIM(cCurrentModuleObject)//  &
             ' Not Found or Fuel not specified For Pollution Calculation for GASOLINE')
          ErrorsFound=.true.
      End If
      ! Check for Propane
      If(.not. Pollution%PropaneCoef%FuelFactorUsed .and. (FuelType%PropaneFacilityIndex > 0)) Then
          CALL ShowSevereError(TRIM(cCurrentModuleObject)//  &
             ' Not Found or Fuel not specified For Pollution Calculation for PROPANE')
          ErrorsFound=.true.
      End If
      ! Check for Diesel
      If(.not. Pollution%DieselCoef%FuelFactorUsed .and. (FuelType%DieselFacilityIndex > 0)) Then
          CALL ShowSevereError(TRIM(cCurrentModuleObject)//  &
             ' Not Found or Fuel not specified For Pollution Calculation for DIESEL')
          ErrorsFound=.true.
      End If
      ! Check for OtherFuel1
      If(.not. Pollution%OtherFuel1Coef%FuelFactorUsed .and. (FuelType%OtherFuel1FacilityIndex > 0)) Then
          CALL ShowSevereError(TRIM(cCurrentModuleObject)//  &
             ' Not Found or Fuel not specified For Pollution Calculation for OTHERFUEL1')
          ErrorsFound=.true.
      End If
      ! Check for OtherFuel2
      If(.not. Pollution%OtherFuel2Coef%FuelFactorUsed .and. (FuelType%OtherFuel2FacilityIndex > 0)) Then
          CALL ShowSevereError(TRIM(cCurrentModuleObject)//  &
             ' Not Found or Fuel not specified For Pollution Calculation for OTHERFUEL2')
          ErrorsFound=.true.
      End If
    END IF
    IF (ErrorsFound) THEN
      CALL ShowFatalError('Errors found in getting Pollution Calculation Reporting Input')
    ENDIF
  RETURN
END SUBROUTINE GetPollutionFactorInput
All Procedures
AbortEnergyPlus AbsoluteAirMass ActivateDemandManagers ActivateEMSControls AddBlankKeys addChargesToOperand AddCompSizeTableEntry AddEndUseSubcategory AddError addFootNoteSubTable AddInstruction AddMeter addMonthlyCharge AddMonthlyFieldSetInput AddMonthlyReport AddNeighborInformation AddObjectDefandParse addOperand AddRecordFromSection AddRecordToOutputVariableStructure AddSectionDef AddShadowRelateTableEntry AddSQLiteComponentSizingRecord AddSQLiteComponentSizingRecord AddSQLiteSystemSizingRecord AddSQLiteSystemSizingRecord AddSQLiteZoneSizingRecord AddSQLiteZoneSizingRecord AddTOCEntry AddTOCZoneLoadComponentTable AddToOutputVariableList AddVariablesForMonthlyReport AddVariableSlatBlind AddWindow AdjustAirSetpointsforOpTempCntrl AdjustCBF AdjustCBF AdjustChangeInLoadByEMSControls AdjustChangeInLoadByHowServed AdjustChangeInLoadForLastStageUpperRangeLimit AdjustCoolingSetPointforTempAndHumidityControl adjusthhat AdjustPumpFlowRequestByEMSControls AdjustReportingHourAndMinutes AdjustVBGap AdvanceRootFinder AFECFR AFECOI AFECPD AFECPF AFEDMP AFEDOP AFEDWC AFEELR AFEEXF AFEFAN AFEHEX AFEHOP AFEPLR AFESCR AFESEL AFESOP AFETMU AirflowNetworkVentingControl AirMass AIRMOV AllocateAirflowNetworkData AllocateAirHeatBalArrays AllocateAndInitData AllocateAndSetUpVentReports AllocateCFSStateHourlyData AllocateForCFSRefPointsGeometry AllocateForCFSRefPointsState AllocateHeatBalArrays AllocateLoadComponentArrays AllocateModuleArrays AllocateModuleArrays AllocateSurfaceHeatBalArrays AllocateWeatherData angle_2dvector AnisoSkyViewFactors AnyPlantLoopSidesNeedSim AnyPlantSplitterMixerLacksContinuity AreaPolygon ArgCheck array_to_vector ASHRAETauModel ASHWAT_OffNormalProperties ASHWAT_Solar ASHWAT_Thermal ASSIGNMENT (=) AssignNodeNumber AssignReportNumber AssignResourceTypeNum AssignReverseConstructionNumber AssignVariablePt AttachCustomMeters AttachMeters AuditBranches AUTOTDMA BaseThermalPropertySet_Diffusivity BeginEnvrnInitializeRuntimeLanguage BetweenDates BetweenGlassForcedFlow BetweenGlassShadeForcedFlow BetweenGlassShadeNaturalFlow BisectionMethod BlindBeamBeamTrans BlindOpticsBeam BlindOpticsDiffuse BoreholeResistance BoundValueToNodeMinMaxAvail BoundValueToWithinTwoValues BracketRoot BranchPressureDrop BrentMethod BuildGap BuildKeyVarList Calc4PipeFanCoil Calc_EN673 Calc_ISO15099 CalcActiveTranspiredCollector CalcAggregateLoad CalcAirflowNetworkAirBalance CalcAirflowNetworkCO2Balance CalcAirflowNetworkGCBalance CalcAirflowNetworkHeatBalance CalcAirflowNetworkMoisBalance CalcAirFlowSimple CalcAirLoopSplitter CalcAirMixer CalcAirToAirGenericHeatExch CalcAirToAirPlateHeatExch CalcAirZoneReturnPlenum CalcAirZoneSupplyPlenum CalcAlamdariHammondStableHorizontal CalcAlamdariHammondUnstableHorizontal CalcAlamdariHammondVerticalWall CalcAngleFactorMRT CalcApproximateViewFactors CalcASHRAEDetailedIntConvCoeff CalcASHRAESimpExtConvectCoeff CalcASHRAESimpleIntConvCoeff CalcASHRAEVerticalWall CalcATMixer CalcAwbiHattonHeatedFloor CalcAwbiHattonHeatedWall CalcBasinHeaterPower CalcBasinHeaterPowerForMultiModeDXCoil CalcBeamSolarOnWinRevealSurface CalcBeamSolDiffuseReflFactors CalcBeamSolSpecularReflFactors CalcBeausoleilMorrisonMixedAssistedWall CalcBeausoleilMorrisonMixedOpposingWall CalcBeausoleilMorrisonMixedStableCeiling CalcBeausoleilMorrisonMixedStableFloor CalcBeausoleilMorrisonMixedUnstableCeiling CalcBeausoleilMorrisonMixedUnstableFloor CalcBLASTAbsorberModel CalcBlockenWindward CalcBoilerModel CalcBoilerModel CalcBottomFluxCoefficents CalcBottomSurfTemp CalcBuriedPipeSoil CalcCBF CalcCBF CalcCBVAV CalcCeilingDiffuserInletCorr CalcCeilingDiffuserIntConvCoeff CalcChillerHeaterModel CalcChillerIPLV CalcChillerModel CalcClearRoof CalcCoilUAbyEffectNTU CalcColdestSetPoint CalcComplexWindowOverlap CalcComplexWindowThermal CalcCompSuctionTempResidual CalcCondEntSetPoint CalcConnectionsDrainTemp CalcConnectionsFlowRates CalcConnectionsHeatRecovery CalcConstCOPChillerModel CalcConvCoeffAbsPlateAndWater CalcConvCoeffBetweenPlates CalcCoolBeam CalcCoolTower CalcCoordinateTransformation CalcCoPlanarNess CalcCostEstimate CalcCTGeneratorModel CalcDayltgCoefficients CalcDayltgCoeffsMapPoints CalcDayltgCoeffsRefMapPoints CalcDayltgCoeffsRefPoints CalcDesiccantBalancedHeatExch CalcDesignSpecificationOutdoorAir CalcDesuperheaterHeatingCoil CalcDesuperheaterWaterHeater CalcDetailedHcInForDVModel CalcDetailedSystem CalcDetailedTransSystem CalcDetailFlatFinCoolingCoil CalcDetIceStorLMTDstar CalcDiffTSysAvailMgr CalcDirectAir CalcDirectEvapCooler CalcDirectResearchSpecialEvapCooler CalcDoe2DXCoil CalcDOE2Leeward CalcDOE2Windward CalcDryFinEffCoef CalcDryIndirectEvapCooler CalcDuct CalcDXCoilStandardRating CalcDXHeatingCoil CalcEarthTube CalcEcoRoof CalcEffectiveness CalcEffectiveSHR CalcEffectiveSHR CalcEffectiveSHR CalcEffectiveSHR CalcElecSteamHumidifier CalcElectricBaseboard CalcElectricChillerHeatRecovery CalcElectricChillerModel CalcElectricEIRChillerModel CalcElectricHeatingCoil CalcEmmelRoof CalcEmmelVertical CalcEngineChillerHeatRec CalcEngineDrivenChillerModel CalcEQLOpticalProperty CalcEQLWindowOpticalProperty CalcEQLWindowSHGCAndTransNormal CalcEQLWindowStandardRatings CalcEQLWindowUvalue CalcEquipmentDrainTemp CalcEquipmentFlowRates CalcExhaustAbsorberChillerModel CalcExhaustAbsorberHeaterModel CalcExteriorVentedCavity CalcFisherPedersenCeilDiffuserCeiling CalcFisherPedersenCeilDiffuserFloor CalcFisherPedersenCeilDiffuserWalls CalcFluidHeatExchanger CalcFohannoPolidoriVerticalWall CalcFollowOATempSetPoint CalcFollowSysNodeTempSetPoint CalcFourPipeIndUnit CalcFrameDividerShadow CalcFuelCellAuxHeater CalcFuelCellGeneratorModel CalcFuelCellGenHeatRecovery CalcFurnaceOutput CalcFurnaceResidual CalcGasAbsorberChillerModel CalcGasAbsorberHeaterModel CalcGasCooler CalcGasHeatingCoil CalcGenericDesiccantDehumidifier CalcGoldsteinNovoselacCeilingDiffuserFloor CalcGoldsteinNovoselacCeilingDiffuserWall CalcGoldsteinNovoselacCeilingDiffuserWindow CalcGroundTempSetPoint CalcGroundwaterWell CalcGshpModel CalcGshpModel CalcGTChillerModel CalcHeatBalanceAir CalcHeatBalanceInsideSurf CalcHeatBalanceInsideSurf CalcHeatBalanceOutsideSurf CalcHeatBalanceOutsideSurf CalcHeatBalFiniteDiff CalcHeatBalHAMT CalcHeatPumpWaterHeater CalcHeatTransCoeffAndCoverTemp CalcHfExteriorSparrow CalcHighTempRadiantSystem CalcHighTempRadiantSystemSP CalcHiTurnOffSysAvailMgr CalcHiTurnOnSysAvailMgr CalcHnASHRAETARPExterior CalcHPCoolingSimple CalcHPHeatingSimple CalcHPWHDXCoil CalcHWBaseboard CalcHXAssistedCoolingCoil CalcHXEffectTerm CalcHybridVentSysAvailMgr CalcIBesselFunc CalcICEngineGeneratorModel CalcICEngineGenHeatRecovery CalcIceStorageCapacity CalcIceStorageCharge CalcIceStorageDischarge CalcIceStorageDormant CalcICSSolarCollector CalcIdealCondEntSetPoint CalcIfSetpointMet CalcIndirectAbsorberModel CalcIndirectResearchSpecialEvapCooler CalcInteriorRadExchange CalcInteriorSolarDistribution CalcInteriorSolarOverlaps CalcInteriorWinTransDifSolInitialDistribution CalcISO15099WindowIntConvCoeff CalcKaradagChilledCeiling CalcKBesselFunc CalcKhalifaEq3WallAwayFromHeat CalcKhalifaEq4CeilingAwayFromHeat CalcKhalifaEq5WallsNearHeat CalcKhalifaEq6NonHeatedWalls CalcKhalifaEq7Ceiling CalcLoadCenterThermalLoad CalcLoTurnOffSysAvailMgr CalcLoTurnOnSysAvailMgr CalcLowTempCFloRadiantSystem CalcLowTempCFloRadSysComps CalcLowTempElecRadiantSystem CalcLowTempHydrRadiantSystem CalcLowTempHydrRadSysComps CalcMatrixInverse CalcMcAdams CalcMerkelVariableSpeedTower CalcMicroCHPNoNormalizeGeneratorModel CalcMinIntWinSolidAngs CalcMitchell CalcMixedAirSetPoint CalcMoistureBalanceEMPD CalcMoreNodeInfo CalcMoWITTLeeward CalcMoWITTWindward CalcMSHeatPump CalcMTGeneratorModel CalcMultiSpeedDXCoil CalcMultiSpeedDXCoilCooling CalcMultiSpeedDXCoilHeating CalcMultiStageElectricHeatingCoil CalcMultiStageGasHeatingCoil CalcMultiZoneAverageCoolingSetPoint CalcMultiZoneAverageHeatingSetPoint CalcMultiZoneAverageMaxHumSetPoint CalcMultiZoneAverageMinHumSetPoint CalcMultiZoneMaxHumSetPoint CalcMultiZoneMinHumSetPoint CalcMundtModel CalcNCycSysAvailMgr CalcNewZoneHeatCoolFlowRates CalcNewZoneHeatOnlyFlowRates CalcNodeMassFlows CalcNominalWindowCond CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNusselt CalcNusseltJurges CalcNVentSysAvailMgr CalcOAController CalcOAMassFlow CalcOAMassFlow CalcOAMixer CalcOAOnlyMassFlow CalcOAPretreatSetPoint CalcOAUnitCoilComps CalcObstrMultiplier CalcOptStartSysAvailMgr CalcOtherSideDemand CalcOutdoorAirUnit CalcOutsideAirSetPoint CalcOutsideSurfTemp CalcParallelPIU CalcPassiveExteriorBaffleGap CalcPassiveSystem CalcPassiveTranspiredCollector CalcPerSolarBeam CalcPipeHeatTransCoef CalcPipesHeatTransfer CalcPipeTransBeam CalcPlantValves CalcPollution CalcPolyhedronVolume CalcPolynomCoef CalcPondGroundHeatExchanger CalcPredictedHumidityRatio CalcPredictedSystemLoad CalcPTUnit CalcPumps CalcPurchAirLoads CalcPurchAirMinOAMassFlow CalcPurchAirMixedAir CalcPVTcollectors CalcQiceChargeMaxByChiller CalcQiceChargeMaxByITS CalcQiceDischageMax CalcRABFlowSetPoint CalcRackSystem CalcRadSysHXEffectTerm CalcRadTemp CalcRainCollector CalcReformEIRChillerModel CalcResearchSpecialPartLoad CalcReturnAirPath CalcRfFlrCoordinateTransformation CalcSandiaPV CalcSatVapPressFromTemp CalcSchedOffSysAvailMgr CalcSchedOnSysAvailMgr CalcSchedSysAvailMgr CalcScheduledDualSetPoint CalcScheduledSetPoint CalcScreenTransmittance CalcScriptF CalcSeriesPIU CalcSetpointTempTarget CalcSHRUserDefinedCurves CalcSimpleController CalcSimpleHeatingCoil CalcSimplePV CalcSingleSpeedEvapFluidCooler CalcSingleSpeedTower CalcSingZoneClSetPoint CalcSingZoneHtSetPoint CalcSingZoneMaxHumSetPoint CalcSingZoneMinHumSetPoint CalcSingZoneRhSetPoint CalcSkySolDiffuseReflFactors CalcSolarCollector CalcSolarFlux CalcSolidDesiccantDehumidifier CalcSourceFlux CalcSourceTempCoefficents CalcSparrowLeeward CalcSparrowWindward CalcSpecialDayTypes CalcStandAloneERV CalcStandardRatings CalcStaticProperties CalcSteamAirCoil CalcSteamBaseboard CalcSurfaceCentroid CalcSurfaceGroundHeatExchanger CalcSystemEnergyUse CalcSZOneStageCoolingSetPt CalcSZOneStageHeatingSetPt CalcTankTemp CalcTDDTransSolAniso CalcTDDTransSolHorizon CalcTDDTransSolIso CalcTempDistModel CalcTempIntegral CalcTESCoilChargeOnlyMode CalcTESCoilCoolingAndChargeMode CalcTESCoilCoolingAndDischargeMode CalcTESCoilCoolingOnlyMode CalcTESCoilDischargeOnlyMode CalcTESCoilOffMode CalcTESIceStorageTank CalcTESWaterStorageTank CalcThermalChimney CalcThermalComfortAdaptiveASH55 CalcThermalComfortAdaptiveCEN15251 CalcThermalComfortFanger CalcThermalComfortKSU CalcThermalComfortPierce CalcThermalComfortSimpleASH55 CalcTimeNeeded CalcTopFluxCoefficents CalcTopSurfTemp CalcTotalFLux CalcTotCapSHR CalcTotCapSHR_VSWSHP CalcTransAbsorProduct CalcTransRefAbsOfCover CalcTRNSYSPV CalcTrombeWallIntConvCoeff CalcTwoSpeedDXCoilIEERResidual CalcTwoSpeedDXCoilStandardRating CalcTwoSpeedEvapFluidCooler CalcTwoSpeedTower CalcUAIce CalcUCSDCV CalcUCSDDV CalcUCSDUE CalcUCSDUI CalculateAirChillerSets CalculateBasisLength CalculateCase CalculateCoil CalculateCompressors CalculateCondensers CalculateCTFs CalculateDailySolarCoeffs CalculateDayOfWeek CalculateEpsFromNTUandZ CalculateExponentialMatrix CalculateFuncResults CalculateGammas CalculateInverseMatrix CalculateMoodyFrictionFactor CalculateNTUfromEpsAndZ CalculatePollution CalculateSecondary CalculateSubcoolers CalculateSunDirectionCosines CalculateTransCompressors CalculateWalkIn CalculateWaterUseage CalculateWaterUseage CalculateWindowBeamProperties CalculateZoneMRT CalculateZoneVolume CalcUnitaryCoolingSystem CalcUnitaryHeatingSystem CalcUnitarySuppHeatingSystem CalcUnitarySuppSystemtoSP CalcUnitarySystemLoadResidual CalcUnitarySystemToLoad CalcUnitHeater CalcUnitHeaterComponents CalcUnitVentilator CalcUnitVentilatorComponents CalcUnmetPlantDemand CalcUpdateHeatRecovery CalcUpdateHeatRecovery CalcUserDefinedInsideHcModel CalcUserDefinedOutsideHcModel CalcVariableSpeedTower CalcVarSpeedCoilCooling CalcVarSpeedCoilHeating CalcVarSpeedHeatPump CalcVarSpeedHeatPump CalcVAVVS CalcVentilatedSlab CalcVentilatedSlabComps CalcVentilatedSlabRadComps CalcVentSlabHXEffectTerm CalcVerticalGroundHeatExchanger CalcViewFactorToShelf CalcVRF CalcVRFCondenser CalcVRFCoolingCoil CalcVSTowerApproach CalcWallCoordinateTransformation CalcWaltonStableHorizontalOrTilt CalcWaltonUnstableHorizontalOrTilt CalcWarmestSetPoint CalcWarmestSetPointTempFlow CalcWaterMainsTemp CalcWaterSource CalcWaterStorageTank CalcWaterThermalTankMixed CalcWaterThermalTankStratified CalcWaterThermalTankZoneGains CalcWaterToAirHeatpump CalcWatertoAirHPCooling CalcWatertoAirHPHeating CalcWaterToAirResidual CalcWatertoWaterHPCooling CalcWatertoWaterHPHeating CalcWaterUseZoneGains CalcWetIndirectEvapCooler CalcWindowACOutput CalcWindowBlindProperties CalcWindowHeatBalance CalcWindowProfileAngles CalcWindowScreenProperties CalcWindowStaticProperties CalcWindPressure CalcWindPressureCoeffs CalcWindTurbine CalcWinFrameAndDividerTemps CalcWinTransDifSolInitialDistribution CalcWrapperModel CalcZoneAirComfortSetpoints CalcZoneAirTempSetpoints CalcZoneComponentLoadSums CalcZoneDehumidifier CalcZoneEvaporativeCoolerUnit CalcZoneLeavingConditions CalcZoneMassBalance CalcZonePipesHeatGain CalcZoneSums CartesianPipeCellInformation_ctor CellType_IsFieldCell CFSHasControlledShade CFSNGlz CFSRefPointPosFactor CFSRefPointSolidAngle CFSShadeAndBeamInitialization CFSUFactor cGetCoilAirOutletNode cGetCoilSteamInletNode cGetCoilSteamOutletNode CharPreDefTableEntry CheckActuatorNode CheckAndAddAirNodeNumber CheckAndFixCFSLayer CheckAndReadCustomSprectrumData CheckAndReadFaults CheckAndSetConstructionProperties CheckBracketRoundOff CheckBranchForOASys CheckCachedIPErrors CheckCFSStates CheckCoilWaterInletNode CheckControllerListOrder CheckControllerLists CheckConvexity CheckCostEstimateInput CheckCreatedZoneItemName CheckCurveLimitsForIPLV CheckCurveLimitsForStandardRatings CheckDayScheduleValueMinMax CheckDXCoolingCoilInOASysExists CheckFDSurfaceTempLimits CheckFFSchedule CheckFluidPropertyName CheckForActualFileName CheckForBalancedFlow CheckForControllerWaterCoil CheckForGeometricTransform CheckForGeometricTransform CheckForMisMatchedEnvironmentSpecifications CheckForOutOfRangeTempResult CheckForOutOfRangeTemps CheckForRequestedReporting CheckForRunawayPlantTemps CheckForSensorAndSetpointNode CheckGasCoefs CheckHeatingCoilSchedule CheckHXAssistedCoolingCoilSchedule CheckIFAnyEMS CheckIFAnyIdealCondEntSetPoint CheckIfAnyPlant CheckIfNodeSetpointManagedByEMS CheckIncrementRoundOff CheckInternalConsistency CheckLightsReplaceableMinMaxForZone CheckLocationValidity CheckLoopExitNode CheckLowerUpperBracket CheckMarkedNodes CheckMaxActiveController CheckMaxConstraint CheckMicroCHPThermalBalance CheckMinActiveController CheckMinConstraint checkMinimumMonthlyCharge CheckMinMaxCurveBoundaries CheckMinMaxRange CheckModelBoundOutput_HumRat CheckModelBoundOutput_Temp CheckModelBounds CheckModelBoundsHumRatEq CheckModelBoundsRH_HumRatEq CheckModelBoundsRH_TempEq CheckModelBoundsTempEq CheckNodeConnections CheckNodeSetPoint CheckNonSingularity CheckOAControllerName CheckOutAirNodeNumber CheckPlantConvergence CheckPlantMixerSplitterConsistency CheckPlantOnAbort CheckPollutionMeterReporting CheckRefrigerationInput CheckReportVariable CheckRootFinderCandidate CheckRootFinderConvergence CheckScheduledSurfaceGains CheckScheduleValue CheckScheduleValueMinMax Checksetpoints CheckSimpleController CheckSlope CheckSteamCoilSchedule CheckSubSurfaceMiscellaneous CheckSysSizing CheckSystemBranchFlow CheckTDDsAndLightShelvesInDaylitZones CheckThisAirSystemForSizing CheckThisZoneForSizing CheckThreading CheckUniqueNodes CheckUnitarySysCoilInOASysExists CheckUsedConstructions CheckValidSimulationObjects CheckWarmupConvergence CheckWaterCoilSchedule CheckWeatherFileValidity CheckWindowShadingControlFrameDivider CheckZoneEquipmentList CheckZoneSizing CHKBKS CHKGSS CHKSBS CLIP CLIPPOLY CloseDFSFile CloseMiscOpenFiles CloseMoistureBalanceEMPD CloseOutOpenFiles CloseOutputFiles CloseOutputTabularFile CloseReportIllumMaps CloseSocket CloseWeatherFile CoilAreaFracIter CoilCompletelyDry CoilCompletelyWet CoilOutletStreamCondition CoilPartWetPartDry COMMAND_ARGUMENT_COUNT CompactObjectsCheck CompareTwoVectors ComplexFenestrationLuminances ComputeDelayedComponents ComputeDifSolExcZonesWIZWindows ComputeIntSolarAbsorpFactors ComputeIntSWAbsorpFactors ComputeIntThermalAbsorpFactors ComputeLifeCycleCostAndReport ComputeLoadComponentDecayCurve ComputeNominalUwithConvCoeffs ComputePresentValue ComputeTariff ComputeTaxAndDepreciation ComputeWinShadeAbsorpFactors CondOutTempResidual ConstructBasis ControlCBVAVOutput ControlCompOutput ControlCompOutput ControlCoolBeam ControlCoolingSystem ControlCycWindACOutput ControlDesiccantDehumidifier ControlDXHeatingSystem ControlDXSystem ControlFluidHeatExchanger ControlHeatingSystem ControlHumidifier ControlMSHPOutput ControlPTUnitOutput ControlPVTcollector ControlReformEIRChillerModel ControlSuppHeatSystem ControlUnitarySystemOutput ControlUnitarySystemtoLoad ControlUnitarySystemtoSP ControlVRF ControlVSEvapUnitToMeetLoad ControlVSHPOutput ControlVSHPOutput ConvectionFactor ConvertCasetoLower ConvertCasetoUpper ConvertIP ConvertIPdelta ConvertToElementTag ConvertToEscaped CoolBeamResidual CoolingCoil CoolWaterHumRatResidual CoolWaterTempResidual CoolWatertoAirHPHumRatResidual CoolWatertoAirHPTempResidual CorrectZoneAirTemp CorrectZoneContaminants CorrectZoneHumRat CostInfoOut CPCW CPHW CreateBoundaryList CreateBoundaryListCount CreateCategoryNativeVariables CreateCellArray CreateCurrentDateTimeString CreateDefaultComputation CreateEnergyReportStructure CreateFCfactorConstructions CreateHVACStepFullString CreateHVACTimeIntervalString CreateHVACTimeString CreateNewellAreaVector CreateNewellSurfaceNormalVector CreatePartitionCenterList CreatePartitionRegionList CreatePredefinedMonthlyReports CreateRegionList CreateRegionListCount CreateShadedWindowConstruction CreateSQLiteConstructionsTable CreateSQLiteConstructionsTable CreateSQLiteDatabase CreateSQLiteDatabase CreateSQLiteDaylightMap CreateSQLiteDaylightMap CreateSQLiteDaylightMapTitle CreateSQLiteDaylightMapTitle CreateSQLiteEnvironmentPeriodRecord CreateSQLiteEnvironmentPeriodRecord CreateSQLiteErrorRecord CreateSQLiteErrorRecord CreateSQLiteInfiltrationTable CreateSQLiteInfiltrationTable CreateSQLiteMaterialsTable CreateSQLiteMaterialsTable CreateSQLiteMeterDictionaryRecord CreateSQLiteMeterDictionaryRecord CreateSQLiteMeterRecord CreateSQLiteMeterRecord CreateSQLiteNominalBaseboardHeatTable CreateSQLiteNominalBaseboardHeatTable CreateSQLiteNominalElectricEquipmentTable CreateSQLiteNominalElectricEquipmentTable CreateSQLiteNominalGasEquipmentTable CreateSQLiteNominalGasEquipmentTable CreateSQLiteNominalHotWaterEquipmentTable CreateSQLiteNominalHotWaterEquipmentTable CreateSQLiteNominalLightingTable CreateSQLiteNominalLightingTable CreateSQLiteNominalOtherEquipmentTable CreateSQLiteNominalOtherEquipmentTable CreateSQLiteNominalPeopleTable CreateSQLiteNominalPeopleTable CreateSQLiteNominalSteamEquipmentTable CreateSQLiteNominalSteamEquipmentTable CreateSQLiteReportVariableDataRecord CreateSQLiteReportVariableDataRecord CreateSQLiteReportVariableDictionaryRecord CreateSQLiteReportVariableDictionaryRecord CreateSQLiteRoomAirModelTable CreateSQLiteRoomAirModelTable CreateSQLiteSchedulesTable CreateSQLiteSimulationsRecord CreateSQLiteSimulationsRecord CreateSQLiteStringTableRecord CreateSQLiteSurfacesTable CreateSQLiteSurfacesTable CreateSQLiteTabularDataRecords CreateSQLiteTabularDataRecords CreateSQLiteTimeIndexRecord CreateSQLiteTimeIndexRecord CreateSQLiteVentilationTable CreateSQLiteVentilationTable CreateSQLiteZoneGroupTable CreateSQLiteZoneGroupTable CreateSQLiteZoneListTable CreateSQLiteZoneListTable CreateSQLiteZoneTable CreateSQLiteZoneTable CreateStormWindowConstructions CreateSysTimeIntervalString CreateTCConstructions CreateTimeIntervalString CreateTimeString CreatExtBooundCondName CreateZoneExtendedOutput CreateZoneExtendedOutput CrossProduct CrossProduct cSurfaceClass CTRANS CurveValue DateToString DateToStringWithMonth DaylghtAltAndAzimuth DayltgAveInteriorReflectance DayltgClosestObstruction DayltgCrossProduct DayltgCurrentExtHorizIllum DayltgDirectIllumComplexFenestration DayltgDirectSunDiskComplexFenestration DayltgElecLightingControl DayltgExtHorizIllum DayltgGlare DayltgGlarePositionFactor DayltgGlareWithIntWins DayltgHitBetWinObstruction DayltgHitInteriorObstruction DayltgHitObstruction DayltgInteriorIllum DayltgInteriorMapIllum DayltgInteriorTDDIllum DayltgInterReflectedIllum DayltgInterReflectedIllumComplexFenestration DayltgInterReflIllFrIntWins DayltgLuminousEfficacy DayltgPierceSurface DayltgSetupAdjZoneListsAndPointers DayltgSkyLuminance DayltgSurfaceLumFromSun dCheckScheduleValueMinMax1 dCheckScheduleValueMinMax2 DeallocateLoadComponentArrays DebugRootFinder DecodeHHMMField DecodeMonDayHrMin DeflectionTemperatures DeflectionWidths DegradF DElightDaylightCoefficients DElightDaylightCoefficients DElightElecLtgCtrl DElightElecLtgCtrl DElightFreeMemory DElightFreeMemory DElightInputGenerator DElightInputGenerator DElightOutputGenerator DElightOutputGenerator DensityCFSFillGas Depth DERIV DetailsForSurfaces DetectOscillatingZoneTemp DetermineAzimuthAndTilt DetermineBranchFlowRequest DetermineBuildingFloorArea DetermineDateTokens DetermineFrequency DetermineIndexGroupFromMeterGroup DetermineIndexGroupKeyFromMeterName DetermineMaxBackSurfaces DetermineMeterIPUnits DetermineMinuteForReporting DeterminePolygonOverlap DetermineShadowingCombinations DetermineSunUpDown DevelopMesh DiffuseAverage DiffuseAverageProfAngGnd DiffuseAverageProfAngSky DisplayMaterialRoughness DisplayNumberandString DisplaySimDaysProgress DisplayString distance DistributeBBElecRadGains DistributeBBRadGains DistributeBBSteamRadGains DistributeHTRadGains DistributePlantLoad DistributePressureOnBranch DistributeTDDAbsorbedSolar DistributeUserDefinedPlantLoad DL_RES_r2 DLAG DOE2DXCoilHumRatResidual DOE2DXCoilHumRatResidual DOE2DXCoilResidual DOE2DXCoilResidual DOE2DXCoilResidual DoEndOfIterationOperations DomainRectangle_Contains DOMakeUPPERCase DoOneTimeInitializations DOSameString DoShadeControl DoStartOfTimeStepInitializations DownInterpolate4HistoryValues DumpAirLoopStatistics DumpCurrentLineBuffer DUMPVD DUMPVR DXCoilCyclingHumRatResidual DXCoilCyclingHumRatResidual DXCoilCyclingResidual DXCoilCyclingResidual DXCoilVarSpeedHumRatResidual DXCoilVarSpeedHumRatResidual DXCoilVarSpeedResidual DXCoilVarSpeedResidual DXFOut DXFOutLines DXFOutWireFrame DXHeatingCoilResidual DXHeatingCoilResidual DXHeatingCoilResidual DynamicClothingModel DynamicExtConvSurfaceClassification DynamicIntConvSurfaceClassification EchoOutActuatorKeyChoices EchoOutInternalVariableChoices EffectiveEPSLB EffectiveEPSLF EIRChillerHeatRecovery EN673ISO10292 EncodeMonDayHrMin EndEnergyPlus EndUniqueNodeCheck EnthalpyResidual epElapsedTime epGetTimeUsed epGetTimeUsedperCall epStartTime epStopTime epSummaryTimes eptime EQLWindowInsideEffectiveEmiss EQLWindowOutsideEffectiveEmiss EQLWindowSurfaceHeatBalance EquationsSolver ERF EstimateHEXSurfaceArea EvalInsideMovableInsulation EvalOutsideMovableInsulation EvaluateAdiabaticSurfaceTemperature EvaluateBasementCellTemperature EvaluateCellNeighborDirections evaluateChargeBlock evaluateChargeSimple EvaluateExpression EvaluateExtHcModels EvaluateFarfieldBoundaryTemperature EvaluateFarfieldCharacteristics EvaluateFieldCellTemperature EvaluateGroundSurfaceTemperature EvaluateIntHcModels EvaluateLoopSetPointLoad EvaluateNeighborCharacteristics evaluateQualify evaluateRatchet EvaluateSoilRhoCp EvaluateStack EvolveParaUCSDCV ExitCalcController ExpandComplexState ExpressAsCashFlows ExtendObjectDefinition ExteriorBCEqns ExternalInterfaceExchangeVariables ExternalInterfaceInitializeErlVariable ExternalInterfaceSetErlVariable ExternalInterfaceSetSchedule ExtOrIntShadeNaturalFlow Fabric_EstimateDiffuseProps FACSKY FalsePositionMethod FEQX FI FigureACAncillaries FigureAirEnthalpy FigureAirHeatCap FigureAuxilHeatGasHeatCap FigureBeamSolDiffuseReflFactors FigureBeamSolSpecularReflFactors FigureConstGradPattern FigureDayltgCoeffsAtPointsForSunPosition FigureDayltgCoeffsAtPointsForWindowElements FigureDayltgCoeffsAtPointsSetupForWindow FigureElectricalStorageZoneGains FigureFuelCellZoneGains FigureFuelEnthalpy FigureFuelHeatCap FigureGaseousWaterEnthalpy FigureHeightPattern FigureHXleavingGasHeatCap FigureInverterZoneGains FigureLHVofFuel FigureLiquidWaterEnthalpy FigureLiquidWaterHeatCap FigureMapPointDayltgFactorsToAddIllums FigureMicroCHPZoneGains FigureNDheightInZone FigurePowerConditioningLosses FigureProductGasesEnthalpy FigureProductGasHeatCap FigureRefPointDayltgFactorsToAddIllums FigureRefrigerationZoneGains FigureSolarBeamAtTimestep FigureSunCosines FigureSurfMapPattern FigureTDDZoneGains FigureTransformerZoneGains FigureTransientConstraints FigureTwoGradInterpPattern FILJAC FillBasisElement FillDefaultsSWP FillRemainingPredefinedEntries FillWeatherPredefinedEntries film filmg filmi filmPillar FILSKY FinalizeCFS FinalizeCFSLAYER FinalRateCoils FindAirLoopBranchConnection FindAirPlantCondenserLoopFromBranchList FindAllNumbersinList FindArrayIndex FindCompSPInput FindCompSPLoad FindCondenserLoopBranchConnection FindControlledZoneIndexFromSystemNodeNumberForZone FindDeltaTempRangeInput FindDemandSideMatch FindEMSVariable FindFirstLastPtr FindFirstRecord FindGlycol FindHXDemandSideLoopFlow FindInBasis FindItem FindIteminList FindIteminSortedList FindItemInVariableList FindLoopSideInCallingOrder FindNextRecord FindNonSpace FindNumberinList FindOAMixerMatchForOASystem FindPlantLoopBranchConnection FindRangeBasedOrUncontrolledInput FindRangeVariable FindRefrigerant FindRootSimpleController FindStratifiedTankSensedTemp FindTariffIndex FindTDDPipe FindUnitNumber FinishDebugOutputFiles FixViewFactors FluidCellInformation_ctor FM_BEAM FM_DIFF FM_F FNU forcedventilation FourPipeInductionUnitHasMixer FourPipeIUCoolingResidual FourPipeIUHeatingResidual FRA FrostControl FrostControlSetPointLimit FrostControlSetPointLimit FuelCellProductGasEnthResidual FUN FuncDetermineCoolantWaterExitTemp FuncDetermineCWMdotForInternalFlowControl FuncDetermineEngineTemp FV GasElecHeatingCoilResidual GASSES90 GassesLow GatherBEPSResultsForTimestep GatherBinResultsForTimestep GatherComponentLoadsHVAC GatherComponentLoadsIntGain GatherComponentLoadsSurfAbsFact GatherComponentLoadsSurface GatherForEconomics GatherForPredefinedReport GatherHeatGainReport GatherMonthlyResultsForTimestep GatherPeakDemandForTimestep GatherSourceEnergyEndUseResultsForTimestep GaussElimination generate_ears GenerateDElightDaylightCoefficients GenerateDElightDaylightCoefficients GeneratorPowerOutput GenericCrack GenOutputVariablesAuditReport Get2DMatrix Get2DMatrixDimensions GET_COMMAND GET_COMMAND_ARGUMENT Get_Environment_Variable GetActualDXCoilIndex GetAirBranchIndex GetAirFlowFlag GetAirflowNetworkInput GetAirHeatBalanceInput GetAirLoopAvailabilityManager GetAirModelDatas GetAirNodeData GetAirPathData GetAngleFactorList GetATMixer GetATMixerOutNode GetATMixerPriNode GetATMixers GetATMixerSecNode GetAttShdSurfaceData GetAverageTempByType GetBaseboardInput GetBaseboardInput GetBasementFloorHeatFlux GetBasementWallHeatFlux GetBLASTAbsorberInput GetBoilerInput GetBoilerInput GetBranchData GetBranchFanTypeName GetBranchFlow GetBranchInput GetBranchList GetBranchListInput GetBuildingData GetCBVAV GetCellWidths GetCellWidthsCount GetChildrenData GetChillerheaterInput GetCoilAirFlowRate GetCoilAirFlowRateVariableSpeed GetCoilAirInletNode GetCoilAirOutletNode GetCoilAvailScheduleIndex GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacityByIndexType GetCoilCapacityVariableSpeed GetCoilCondenserInletNode GetCoilControlNodeNum GetCoilGroupTypeNum GetCoilIndex GetCoilIndex GetCoilIndex GetCoilIndexVariableSpeed GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNodeVariableSpeed GetCoilMaxSteamFlowRate GetCoilMaxWaterFlowRate GetCoilMaxWaterFlowRate GetCoilMaxWaterFlowRate GetCoilObjectTypeNum GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNodeVariableSpeed GetCoilSteamInletNode GetCoilSteamOutletNode GetCoilTypeNum GetCoilWaterInletNode GetCoilWaterInletNode GetCoilWaterOutletNode GetColumnUsingTabs GetComfortSetpoints GetComponentData GetCondFDInput GetConductivityGlycol GetConnectorList GetConnectorListInput GetConstCOPChillerInput GetConstructData GetControlledZoneIndex GetControllerActuatorNodeNum GetControllerInput GetCoolBeams GetCoolingCoilTypeNameAndIndex GetCooltower GetCostEstimateInput GetCrossVentData GetCTGeneratorInput GetCTGeneratorResults GetCurrentHVACTime GetCurrentMeterValue GetCurrentScheduleValue GetCurveCheck GetCurveIndex GetCurveInput GetCurveMinMaxValues GetCurveName GetCurveObjectTypeNum GetCurveType GetCustomMeterInput GetDaylightingParametersDetaild GetDaylightingParametersInput GetDayScheduleIndex GetDemandManagerInput GetDemandManagerListInput GetDensityGlycol GetDesiccantDehumidifierInput GetDesignDayData GetDesignLightingLevelForZone GetDetShdSurfaceData GetDirectAirInput GetDisplacementVentData GetDSTData GetDualDuctInput GetDualDuctOutdoorAirRecircUse GetDuctInput GetDXCoilAirFlow GetDXCoilAvailSchPtr GetDXCoilBypassedFlowFrac GetDXCoilCapFTCurveIndex GetDXCoilIndex GetDXCoilNumberOfSpeeds GetDXCoils GetDXCoolingSystemInput GetDXHeatPumpSystemInput GetEarthTube GetElecReformEIRChillerInput GetElectricBaseboardInput GetElectricChillerInput GetElectricEIRChillerInput GetEMSInput GetEngineDrivenChillerInput GetEnvironmentalImpactFactorInfo GetEvapFluidCoolerInput GetEvapInput GetExhaustAbsorberInput GetExhaustAirInletNode GetExteriorEnergyUseInput GetExtVentedCavityIndex GetExtVentedCavityIndex GetExtVentedCavityTsColl GetExtVentedCavityTsColl GetFanAvailSchPtr GetFanCoilIndex GetFanCoilInletAirNode GetFanCoilMixedAirNode GetFanCoilOutAirNode GetFanCoilReturnAirNode GetFanCoilUnits GetFanCoilZoneInletAirNode GetFanDesignVolumeFlowRate GetFanIndex GetFanIndexForTwoSpeedCoil GetFanInletNode GetFanInput GetFanOutletNode GetFanPower GetFanSpeedRatioCurveIndex GetFanType GetFanVolFlow GetFarfieldTemp GetFirstBranchInletNodeName GetFluidCoolerInput GetFluidDensityTemperatureLimits GetFluidHeatExchangerInput GetFluidPropertiesData GetFluidSpecificHeatTemperatureLimits GetFrameAndDividerData GetFuelCellGeneratorInput GetFuelCellGeneratorResults GetFuelFactorInfo GetFurnaceInput GetGasAbsorberInput GetGeneratorFuelSupplyInput GetGeometryParameters GetGlycolNameByIndex GetGroundheatExchangerInput GetGroundReflectances GetGroundTemps GetGshpInput GetGshpInput GetGTChillerInput GetHeatBalanceInput GetHeatBalHAMTInput GetHeatExchangerObjectTypeNum GetHeatingCoilIndex GetHeatingCoilInput GetHeatingCoilNumberOfStages GetHeatingCoilPLFCurveIndex GetHeatingCoilTypeNum GetHeatReclaimSourceIndex GetHeatRecoveryInput GetHighTempRadiantSystem GetHPCoolingCoilIndex GetHTSubSurfaceData GetHTSurfaceData GetHTSurfExtVentedCavityData GetHumidifierInput GetHVACSingleDuctSysIndex GetHWBaseboardInput GetHXAssistedCoolingCoilInput GetHXCoilAirFlowRate GetHXCoilType GetHXCoilTypeAndName GetHXDXCoilIndex GetHXDXCoilName GetHybridVentilationControlStatus GetHybridVentilationInputs GetICEGeneratorResults GetICEngineGeneratorInput GetIceStorageInput GetIDFRecordsStats GetIndirectAbsorberInput GetIndUnits GetInputEconomicsChargeBlock GetInputEconomicsChargeSimple GetInputEconomicsComputation GetInputEconomicsCurrencyType GetInputEconomicsQualify GetInputEconomicsRatchet GetInputEconomicsTariff GetInputEconomicsVariable GetInputForLifeCycleCost GetInputFuelAndPollutionFactors GetInputLifeCycleCostNonrecurringCost GetInputLifeCycleCostParameters GetInputLifeCycleCostRecurringCosts GetInputLifeCycleCostUseAdjustment GetInputLifeCycleCostUsePriceEscalation GetInputTabularMonthly GetInputTabularPredefined GetInputTabularStyle GetInputTabularTimeBins GetInputViewFactors GetInputViewFactorsbyName GetInputZoneEvaporativeCoolerUnit GetInstantMeterValue GetInternalBranchData GetInternalHeatGainsInput GetInternalVariableValue GetInternalVariableValue GetInternalVariableValueExternalInterface GetInternalVariableValueExternalInterface GetInterpolatedSatProp GetInterpValue GetIntMassSurfaceData GetLastBranchOutletNodeName GetLastWord GetLightWellData GetListOfObjectsInIDD GetListofSectionsinInput GetLocationInfo GetLoopMixer GetLoopSidePumpIndex GetLoopSplitter GetLowTempRadiantSystem GetMaterialData GetMatrixInput getMaxAndSum GetMeteredVariables GetMeterIndex GetMeterResourceType GetMicroCHPGeneratorInput GetMicroCHPGeneratorResults GetMinOATCompressor GetMixerInput GetMixerInput GetMoistureBalanceEMPDInput GetMonthlyCostForResource GetMovableInsulationData GetMSHeatPumpInput GetMTGeneratorExhaustNode GetMTGeneratorInput GetMTGeneratorResults GetMundtData GetNewUnitNumber GetNextEnvironment GetNodeConnectionType GetNodeList GetNodeListsInput GetNodeNums GetNTUforCrossFlowBothUnmixed GetNumberOfSchedules GetNumberOfSurfaceLists GetNumberOfSurfListVentSlab GetNumChildren GetNumMeteredVariables GetNumOAControllers GetNumOAMixers GetNumOASystems GetNumObjectsFound GetNumObjectsInIDD GetNumRangeCheckErrorsFound GetNumSectionsFound GetNumSectionsinInput GetNumSegmentsForHorizontalTrenches GetNumSplitterMixerInConntrList GetOACompListNumber GetOACompName GetOACompType GetOACompTypeNum GetOAControllerInputs GetOAMixerIndex GetOAMixerInletNodeNumber GetOAMixerInputs GetOAMixerMixedNodeNumber GetOAMixerNodeNumbers GetOAMixerReliefNodeNumber GetOAMixerReturnNodeNumber GetOARequirements GetOASysControllerListIndex GetOASysNumCoolingCoils GetOASysNumHeatingCoils GetOASysNumSimpControllers GetOASystemNumber GetObjectDefInIDD GetObjectDefMaxArgs GetObjectItem GetObjectItemfromFile GetObjectItemNum GetOnlySingleNode GetOperationSchemeInput GetOSCData GetOSCMData GetOutAirNodesInput GetOutdoorAirUnitInputs GetOutdoorAirUnitOutAirNode GetOutdoorAirUnitReturnAirNode GetOutdoorAirUnitZoneInletNode GetOutsideAirSysInputs GetOutsideEnergySourcesInput GetParentData GetPipeInput GetPipesHeatTransfer GetPipingSystemsInput GetPIUs GetPlantAvailabilityManager GetPlantInput GetPlantLoopData GetPlantOperationInput GetPlantProfileInput GetPlantSizingInput GetPlantValvesInput GetPollutionFactorInput GetPondGroundHeatExchanger GetPowerManagerInput GetPressureCurveTypeAndIndex GetPressureSystemInput GetPreviousHVACTime GetProjectControlData GetProjectData GetPTUnit GetPTUnitMixedAirNode GetPTUnitOutAirNode GetPTUnitReturnAirNode GetPTUnitZoneInletAirNode GetPumpInput GetPurchasedAir GetPurchasedAirMixedAirHumRat GetPurchasedAirMixedAirTemp GetPurchasedAirOutAirMassFlow GetPurchasedAirReturnAirNode GetPurchasedAirZoneInletAirNode GetPVGeneratorResults GetPVInput GetPVTcollectorsInput GetPVTThermalPowerProduction GetQualityRefrig GetRecordLocations GetRectDetShdSurfaceData GetRectSubSurfaces GetRectSurfaces GetRefrigeratedRackIndex GetRefrigerationInput GetReportVariableInput GetRequiredMassFlowRate GetResidCrossFlowBothUnmixed GetResourceTypeChar GetReturnAirNodeForZone GetReturnAirPathInput GetRoomAirModelParameters GetRunPeriodData GetRunPeriodDesignData GetRuntimeLanguageUserInput GetSatDensityRefrig GetSatEnthalpyRefrig GetSatPressureRefrig GetSatSpecificHeatRefrig GetSatTemperatureRefrig GetScheduledSurfaceGains GetScheduleIndex GetScheduleMaxValue GetScheduleMinValue GetScheduleName GetScheduleType GetScheduleValuesForDay GetSecondaryInletNode GetSecondaryOutletNode GetSetPointManagerInputs GetShadingSurfReflectanceData GetShadowingInput GetShelfInput GetSimpleAirModelInputs GetSimpleShdSurfaceData GetSimpleWatertoAirHPInput GetSingleDayScheduleValues GetSiteAtmosphereData GetSizingParams GetSnowGroundRefModifiers GetSolarCollectorInput GetSpecialDayPeriodData GetSpecificHeatGlycol getSpecificUnitDivider getSpecificUnitIndex getSpecificUnitMultiplier GetSplitterInput GetSplitterInput GetSplitterNodeNumbers GetSplitterOutletNumber GetStandAloneERV GetStandAloneERVNodes GetStandAloneERVOutAirNode GetStandAloneERVReturnAirNode GetStandAloneERVZoneInletAirNode GetStandardMeterResourceType GetSteamBaseboardInput GetSteamCoilAvailScheduleIndex GetSteamCoilControlNodeNum GetSteamCoilIndex GetSteamCoilInput GetSTM GetStormWindowData GetSupHeatDensityRefrig GetSupHeatEnthalpyRefrig GetSupHeatPressureRefrig GetSupplyAirFlowRate GetSupplyAirFlowRate GetSupplyAirInletNode GetSupplyInletNode GetSupplyOutletNode GetSurfaceCountForOSCM GetSurfaceData GetSurfaceGroundHeatExchanger GetSurfaceHeatTransferAlgorithmOverrides GetSurfaceIndecesForOSCM GetSurfaceListsInputs GetSurfHBDataForMundtModel GetSurfHBDataForTempDistModel GetSysAvailManagerInputs GetSysAvailManagerListInputs GetSysInput GetSystemNodeNumberForZone GetSystemSizingInput GetTDDInput GetTESCoilIndex GetTESCoilInput GetThermalChimney GetTowerInput GetTranspiredCollectorIndex GetTranspiredCollectorInput GetTypeOfCoil GetUFADZoneData GetUnitarySystemDXCoolingCoilIndex GetUnitarySystemInput GetUnitarySystemOAHeatCoolCoil GetUnitConversion GetUnitHeaterInput GetUnitsString GetUnitSubString GetUnitVentilatorInput GetUnitVentilatorMixedAirNode GetUnitVentilatorOutAirNode GetUnitVentilatorReturnAirNode GetUnitVentilatorZoneInletAirNode GetUserConvectionCoefficients GetUserDefinedComponents GetUserDefinedOpSchemeInput GetUserDefinedPatternData GetUTSCTsColl GetVariableKeyCountandType GetVariableKeyCountandType GetVariableKeys GetVariableKeys GetVariableTypeAndIndex GetVariableUnitsString GetVarSpeedCoilInput GetVentilatedSlabInput GetVertices GetViscosityGlycol GetVRFInput GetVSCoilCondenserInletNode GetVSCoilMinOATCompressor GetVSCoilNumOfSpeeds GetWaterCoilAvailScheduleIndex GetWaterCoilCapacity GetWaterCoilIndex GetWaterCoilInput GetWaterMainsTemperatures GetWaterManagerInput GetWaterSource GetWaterThermalTankInput GetWatertoAirHPInput GetWatertoWaterHPInput GetWaterUseInput GetWeatherProperties GetWeatherStation GetWindowAC GetWindowACMixedAirNode GetWindowACOutAirNode GetWindowACReturnAirNode GetWindowACZoneInletAirNode GetWindowGapAirflowControlData GetWindowGlassSpectralData GetWindowShadingControlData GetWindTurbineInput GetWrapperInput GetWTGeneratorResults GetZoneAirDistribution GetZoneAirLoopEquipment GetZoneAirSetpoints GetZoneAndZoneListNames GetZoneContaminanInputs GetZoneContaminanSetpoints GetZoneData GetZoneDehumidifierInput GetZoneDehumidifierNodeNumber GetZoneEqAvailabilityManager GetZoneEquipment GetZoneEquipmentData GetZoneEquipmentData1 GetZoneInfilAirChangeRate GetZoneLoads GetZonePlenumInput GetZoneSizingInput GLtoAMB GoAhead guess HasFractionalScheduleValue hatter HCInWindowStandardRatings HConvGap HcUCSDCV HcUCSDDV HcUCSDUF HeatingCoilVarSpeedCycResidual HeatingCoilVarSpeedResidual HeatPumpRunFrac HeatPumpRunFrac HeatPumpRunFrac HeatWatertoAirHPTempResidual Height HEMINT HIC_ASHRAE HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterHeatingCoilResidual HRadPar HTRANS HTRANS0 HTRANS1 HWBaseboardUAResidual HXAssistDXCoilResidual HXAssistedCoolCoilHRResidual HXAssistedCoolCoilHRResidual HXAssistedCoolCoilTempResidual HXAssistedCoolCoilTempResidual HXDemandSideLoopFlowResidual HybridVentilationControl IAM iCheckScheduleValue ICSCollectorAnalyticalSoluton iGetCoilAirOutletNode iGetCoilSteamInletNode iGetCoilSteamOutletNode INCLOS incrementEconVar IncrementInstMeterCache incrementSteps incrementTableEntry InitAirflowNetwork InitAirflowNetworkData InitAirHeatBalance InitAirLoops InitAirLoopSplitter InitAirMixer InitAirTerminalUserDefined InitAirZoneReturnPlenum InitAirZoneSupplyPlenum InitATMixer InitBaseboard InitBaseboard InitBLASTAbsorberModel InitBoiler InitBoiler InitBoreholeHXSimVars InitBSDFWindows InitCBVAV InitCoilUserDefined InitComplexWindows InitComponentNodes InitConductionTransferFunctions InitConnections InitConstCOPChiller InitController InitCoolBeam InitCTGenerators InitCurveReporting InitDaylightingDevices InitDemandManagers InitDesiccantDehumidifier InitDetailedIceStorage InitDirectAir InitDualDuct InitDuct InitDXCoil InitDXCoolingSystem InitDXHeatPumpSystem InitElecReformEIRChiller InitElectricBaseboard InitElectricChiller InitElectricEIRChiller InitEMS InitEMSControlledConstructions InitEMSControlledSurfaceProperties InitEnergyReports InitEngineDrivenChiller InitEquivalentLayerWindowCalculations InitEvapCooler InitEvapFluidCooler InitExhaustAbsorber InitExteriorConvectionCoeff InitFan InitFanCoilUnits InitFluidCooler InitFluidHeatExchanger InitFuelCellGenerators InitFurnace InitGasAbsorber InitGlassOpticalCalculations InitGshp InitGshp InitGTChiller InitHeatBalance InitHeatBalFiniteDiff InitHeatBalHAMT InitHeatingCoil InitHeatRecovery InitHighTempRadiantSystem InitHumidifier InitHWBaseboard InitHXAssistedCoolingCoil InitHybridVentSysAvailMgr InitialInitHeatBalFiniteDiff InitializeCFSDaylighting InitializeCFSStateData InitializeComponentSizingTable InitializeConstructionsTables InitializeDaylightMapTables InitializeEnvironmentPeriodsTable InitializeErrorsTable InitializeGlycolTempLimits InitializeHeatTransferPipes InitializeIndexes InitializeIndexes InitializeLoops InitializeMaterialsTable InitializeMeters initializeMonetaryUnit InitializeNominalBaseboardHeatTable InitializeNominalElectricEquipmentTable InitializeNominalGasEquipmentTable InitializeNominalHotWaterEquipmentTable InitializeNominalInfiltrationTable InitializeNominalLightingTable InitializeNominalOtherEquipmentTable InitializeNominalPeopleTable InitializeNominalSteamEquipmentTable InitializeNominalVentilationTable InitializeOperatingMode InitializeOutput InitializePipes InitializePredefinedMonthlyTitles InitializePsychRoutines InitializePumps InitializeRefrigerantLimits InitializeReportMeterDataDictionaryTable InitializeReportMeterDataTables InitializeReportVariableDataDictionaryTable InitializeReportVariableDataTables InitializeRoomAirModelTable InitializeRootFinder InitializeRuntimeLanguage InitializeSchedulesTable InitializeSimulationsTable InitializeSQLiteTables InitializeSurfacesTable InitializeSystemSizingTable InitializeTabularDataTable InitializeTabularDataTable InitializeTabularDataView InitializeTabularDataView InitializeTabularMonthly InitializeTimeIndicesTable InitializeViews InitializeWeather InitializeZoneGroupTable InitializeZoneInfoTable InitializeZoneListTable InitializeZoneSizingTable InitICEngineGenerators InitIndirectAbsorpChiller InitIndUnit InitInteriorConvectionCoeffs InitInteriorRadExchange InitInternalHeatGains InitIntSolarDistribution InitLoadBasedControl InitLoadDistribution InitLowTempRadiantSystem InitMicroCHPNoNormalizeGenerators InitMoistureBalanceEMPD InitMSHeatPump InitMTGenerators InitMundtModel InitOAController InitOAMixer InitOneTimePlantSizingInfo InitOutAirNodes InitOutdoorAirUnit InitOutsideAirSys InitPipesHeatTransfer InitPipingSystems InitPIU InitPlantProfile InitPlantUserComponent InitPlantValves InitPollutionMeterReporting InitPondGroundHeatExchanger InitPressureDrop InitPTUnit InitPurchasedAir InitPVTcollectors InitRefrigeration InitRefrigerationPlantConnections InitReturnAirPath InitSecretObjects InitSetPointManagers InitSimpleIceStorage InitSimpleMixingConvectiveHeatGains InitSimpleWatertoAirHP InitSimVars InitSimVars InitSimVars InitSimVars InitSolarCalculations InitSolarCollector InitSolarHeatGains InitSolReflRecSurf InitStandAloneERV InitSteamBaseboard InitSteamCoil InitSurfaceGroundHeatExchanger InitSurfaceHeatBalance InitSys InitSysAvailManagers InitSystemOutputRequired InitTempDistModel InitTESCoil InitThermalAndFluxHistories InitThermalComfort InitTower InitTranspiredCollector InitTRNSYSPV InitUCSDCV InitUCSDDV InitUCSDUF InitUniqueNodeCheck InitUnitarySystems InitUnitHeater InitUnitVentilator InitVarSpeedCoil InitVentilatedSlab InitVRF InitWaterCoil InitWaterSource InitWaterThermalTank InitWatertoAirHP InitWatertoWaterHP InitWindowAC InitWindTurbine InitWrapper InitZoneAirLoopEquipment InitZoneAirSetpoints InitZoneAirUserDefined InitZoneContSetpoints InitZoneDehumidifier InitZoneEquipment InitZoneEvaporativeCoolerUnit InPolygon InsertCurrencySymbol int_times_vector INTCPT Integer_IsInRange IntegerIsWithinTwoValues IntegerToString InterConnectTwoPlantLoopSides InteriorBCEqns InteriorNodeEqns InternalRangeCheck InternalSetupTankDemandComponent InternalSetupTankSupplyComponent interp INTERP InterpBlind InterpDefValuesForGlycolConc Interpolate Interpolate_Lagrange InterpolateBetweenFourValues InterpolateBetweenTwoValues InterpolatePipeTransBeam InterpProfAng InterpProfSlatAng InterpretWeatherDataLine InterpSlatAng InterpSw InterpValuesForGlycolConc IntInterfaceNodeEqns IntPreDefTableEntry IntToStr Invert3By3Matrix InvertMatrix InvJulianDay IPTrimSigDigits iRoundSigDigits IS_BEAM IS_DIFF IS_DSRATIO IS_F IS_LWP IS_OPENNESS IS_SWP isCompLoadRepReq IsControlledShade IsConverged_CurrentToPrevIteration IsConverged_PipeCurrentToPrevIteration IsCurveInputTypeValid IsCurveOutputTypeValid isExternalInterfaceErlVariable IsGlazeLayerX IsGZSLayer isInQuadrilateral IsInRange isInTriangle IsLeapYear IsNodeOnSetPtManager IsParentObject IsParentObjectCompSet IsShadingLayer IssueSevereAlphaInputFieldError IssueSevereInputFieldError IssueSevereRealInputFieldError IsValidConnectionType IsVBLayer isWithinRange ITERATE IterateRootFinder iTrimSigDigits JGDate JulianDay LClimb LDSumMax LDSumMean LEEDtariffReporting LimitCoilCapacity LimitController LimitTUCapacity LinesOut linint LoadEquipList LoadInterface LogicalToInteger LogicalToInteger LogPlantConvergencePoints lookupOperator LookUpScheduleValue LookUpSeason LookupSItoIP lubksb LUBKSB ludcmp LUDCMP LUdecomposition LUsolution MakeAnchorName MakeHVACTimeIntervalString MakeMirrorSurface MakeRectangularVertices MakeRelativeRectangularVertices MakeTransition MakeUPPERCase ManageAirflowNetworkBalance ManageAirHeatBalance ManageAirLoops ManageAirModel ManageBranchInput ManageControllers ManageCoolTower ManageDemand ManageEarthTube ManageElectCenterStorageInteractions ManageElectricLoadCenters ManageElectStorInteractions ManageEMS ManageExteriorEnergyUse ManageGeneratorControlState ManageGeneratorFuelFlow ManageHeatBalance ManageHeatBalFiniteDiff ManageHeatBalHAMT ManageHVAC ManageHybridVentilation ManageInsideAdaptiveConvectionAlgo ManageInternalHeatGains ManageInverter ManageMundtModel ManageNonZoneEquipment ManageOutsideAdaptiveConvectionAlgo ManageOutsideAirSystem ManagePlantLoadDistribution ManagePlantLoops ManageRefrigeratedCaseRacks ManageSetPoints ManageSimulation ManageSingleCommonPipe ManageSizing ManageSurfaceHeatBalance ManageSystemAvailability ManageThermalChimney ManageThermalComfort ManageTransformers ManageTwoWayCommonPipe ManageUCSDCVModel ManageUCSDDVModel ManageUCSDUFModels ManageUserDefinedPatterns ManageWater ManageWaterInits ManageWeather ManageZoneAirLoopEquipment ManageZoneAirUpdates ManageZoneContaminanUpdates ManageZoneEquipment MapExtConvClassificationToHcModels MapIntConvClassificationToHcModels MarkNode MatchAndSetColorTextString MatchPlantSys MatrixIndex matrixQBalance MeshPartition_CompareByDimension MeshPartition_SelectionSort MeshPartitionArray_Contains MinePlantStructForInfo MixedAirControlTempResidual ModifyWindow Modulus MonthToMonthNumber MovingAvg MRXINV MSHPCyclingResidual MSHPHeatRecovery MSHPVarSpeedResidual MultiModeDXCoilHumRatResidual MultiModeDXCoilHumRatResidual MultiModeDXCoilResidual MultiModeDXCoilResidual MultiModeDXCoilResidual MultiSpeedDXCoolingCoilStandardRatings MultiSpeedDXHeatingCoilStandardRatings MULTOL MyPlantSizingIndex NeighborInformationArray_Value NETRAD NewEMSVariable NewExpression newPreDefColumn newPreDefReport newPreDefSubTable NEWTON NodeHasSPMCtrlVarType NormalArea NumBranchesInBranchList NumCompsInBranch nusselt NusseltNumber OpenEPlusWeatherFile OPENNESS_LW OpenOutputFiles OpenOutputTabularFile OpenWeatherFile OPERATOR (*) OPERATOR (+) OPERATOR (-) OPERATOR (.dot.) OPERATOR (.twodcross.) OPERATOR (.twoddot.) OPERATOR (/) ORDER OutBaroPressAt OutDewPointTempAt OutDryBulbTempAt OutsidePipeHeatTransCoef OutWetBulbTempAt P01 PanesDeflection ParametricObjectsCheck parseComputeLine ParseExpression ParseStack ParseTime PartLoadFactor PassiveGapNusseltNumber PassPressureAcrossInterface PassPressureAcrossMixer PassPressureAcrossSplitter PD_BEAM PD_BEAM_CASE_I PD_BEAM_CASE_II PD_BEAM_CASE_III PD_BEAM_CASE_IV PD_BEAM_CASE_V PD_BEAM_CASE_VI PD_DIFF PD_LW PD_LWP PD_SWP PerformanceCurveObject PerformanceTableObject PerformIterationLoop PerformPipeCellSimulation PerformPipeCircuitSimulation PerformSolarCalculations PerformTemperatureFieldUpdate PierceSurface PierceSurfaceVector PipeCircuitInfo_InitInOutCells PipeSegmentInfo_InitPipeCells PIUInducesPlenumAir PIUnitHasMixer PlaneEquation PlantHalfLoopSolver PlantMassFlowRatesFunc PLRResidual PLRResidual PLRResidualMixedTank PLRResidualStratifiedTank PMVResidual POLY1F POLY2F POLYF polygon_contains_point_2d popStack pos PostIPProcessing POWER PreDefTableEntry PredictSystemLoads PredictZoneContaminants PreparePipeCircuitSimulation PrepDebugFilesAndVariables PreProcessorCheck PrepVariablesISO15099 PreScanReportingVariables PresProfile PressureCurveValue ProcessDataDicFile ProcessDateString ProcessEMSInput ProcessEPWHeader ProcessForDayTypes ProcessInput ProcessInputDataFile ProcessIntervalFields ProcessMinMaxDefLine ProcessNumber ProcessScheduleInput ProcessSurfaceVertices ProcessTokens ProduceMinMaxString ProduceMinMaxStringWStartMinute ProduceRDDMDD ProfileAngle PropagateResolvedFlow PStack PsyCpAirFnWTdb PsyHfgAirFnWTdb PsyHFnTdbRhPb PsyHFnTdbW PsyHgAirFnWTdb PsyPsatFnTemp PsyPsatFnTemp_raw PsyRhFnTdbRhov PsyRhFnTdbRhovLBnd0C PsyRhFnTdbWPb PsyRhoAirFnPbTdbW PsyRhovFnTdbRh PsyRhovFnTdbRhLBnd0C PsyRhovFnTdbWPb PsyTdbFnHW PsyTdpFnTdbTwbPb PsyTdpFnWPb PsyTsatFnHPb PsyTsatFnPb PsyTwbFnTdbWPb PsyTwbFnTdbWPb_raw PsyVFnTdbWPb PsyWFnTdbH PsyWFnTdbRhPb PsyWFnTdbTwbPb PsyWFnTdpPb psz Pt2Plane PullCompInterconnectTrigger PumpDataForTable PushBranchFlowCharacteristics PushInnerTimeStepArrays pushStack PushSystemTimestepHistories PushSystemTimestepHistories PushZoneTimestepHistories PushZoneTimestepHistories QsortC QsortPartition RadialCellInfo_XY_CrossSectArea RadialCellInformation_ctor RadialSizing_Thickness Rainflow RangeCheck RB_BEAM RB_DIFF RB_F RB_LWP RB_SWP rCheckDayScheduleValueMinMax rCheckScheduleValue rCheckScheduleValueMinMax1 rCheckScheduleValueMinMax2 ReadEnergyMeters ReadEPlusWeatherForDay ReadGeneralDomainInputs ReadHorizontalTrenchInputs ReadINIFile ReadInputLine ReadPipeCircuitInputs ReadPipeSegmentInputs ReadTableData ReadUserWeatherInput ReadWeatherForDay Real_ConstrainTo Real_IsInRange real_times_vector ReAllocateAndPreserveOutputVariablesForSimulation ReallocateIntegerArray ReallocateIVar ReallocateRealArray ReallocateRVar RealPreDefTableEntry RealToStr RecKeepHeatBalance RecordOutput RectangleF_Contains ReformEIRChillerCondInletTempResidual ReformEIRChillerHeatRecovery RegisterNodeConnection RegisterPlantCompDesignFlow RegulateCondenserCompFlowReqOp ReInitPlantLoopsAtFirstHVACIteration RemoveSpaces RemoveTrailingZeros reorder ReplaceBlanksWithUnderscores ReplaceBlanksWithUnderscores ReportAirflowNetwork ReportAirHeatBalance ReportAirLoopConnections ReportAirTerminalUserDefined ReportAndTestGlycols ReportAndTestRefrigerants ReportBaseboard ReportBaseboard ReportCBVAV ReportChillerIPLV ReportCoilUserDefined ReportCompSetMeterVariables ReportController ReportCoolBeam ReportCoolTower ReportCTFs ReportCWTankInits ReportDemandManagerList ReportDesiccantDehumidifier ReportDetailedIceStorage ReportDirectAir ReportDualDuct ReportDualDuctConnections ReportDuct ReportDXCoil ReportDXCoilRating ReportDYMeters ReportEarthTube ReportEconomicVariable ReportElectricBaseboard ReportEMS ReportEvapCooler ReportEvapFluidCooler ReportExteriorEnergyUse ReportFan ReportFanCoilUnit ReportFatalGlycolErrors ReportFatalRefrigerantErrors ReportFiniteDiffInits ReportFluidCooler ReportFluidHeatExchanger ReportForTabularReports ReportFurnace ReportGlass ReportHeatBalance ReportHeatingCoil ReportHeatRecovery ReportHighTempRadiantSystem ReportHRMeters ReportHumidifier ReportHWBaseboard ReportIllumMap ReportingFreqName ReportingThisVariable ReportInternalHeatGains ReportLoopConnections ReportLowTempRadiantSystem ReportMaxVentilationLoads ReportMeterDetails ReportMissing_RangeData ReportMixer ReportMNMeters ReportMoistureBalanceEMPD ReportMSHeatPump ReportNodeConnections ReportOAController ReportOAMixer ReportOrphanFluids ReportOrphanRecordObjects ReportOrphanSchedules ReportOutdoorAirUnit ReportOutputFileHeaders ReportParentChildren ReportPipesHeatTransfer ReportPIU ReportPlantProfile ReportPlantUserComponent ReportPlantValves ReportPondGroundHeatExchanger ReportPTUnit ReportPumps ReportPurchasedAir ReportPV ReportRackSystem ReportRefrigerationComponents ReportReturnAirPath ReportRuntimeLanguage ReportScheduleDetails ReportScheduleValues ReportSizingOutput ReportSMMeters ReportSolarCollector ReportSplitter ReportStandAloneERV ReportStandAloneWaterUse ReportSteamBaseboard ReportSteamCoil ReportSurfaceErrors ReportSurfaceGroundHeatExchngr ReportSurfaceHeatBalance ReportSurfaces ReportSurfaceShading ReportSys ReportSysSizing ReportSystemEnergyUse ReportThermalChimney ReportTowers ReportTSMeters ReportUnitarySystem ReportUnitHeater ReportUnitVentilator ReportVentilatedSlab ReportVRFCondenser ReportVRFTerminalUnit ReportWarmupConvergence ReportWaterCoil ReportWaterManager ReportWaterThermalTank ReportWaterUse ReportWeatherAndTimeInformation ReportWindowAC ReportWindTurbine ReportZoneAirLoopEquipment ReportZoneAirUserDefined ReportZoneDehumidifier ReportZoneEquipment ReportZoneEvaporativeCoolerUnit ReportZoneMeanAirTemp ReportZoneReturnPlenum ReportZoneSizing ReportZoneSupplyPlenum ResetAllPlantInterConnectFlags ResetController ResetEnvironmentCounter ResetHVACControl ResetNodeData ResetPerformanceCurveOutput ResetRootFinder ResetTerminalUnitFlowLimits ResetWeekDaysByMonth Resimulate resist ReSolveAirLoopControllers ResolveAirLoopFlowLimits ResolveLocationInformation ResolveLockoutFlags ResolveLoopFlowVsPressure ResolveParallelFlows ResolveSysFlow ReverseAndRecalculate RevertZoneTimestepHistories RevertZoneTimestepHistories RevisePlantCallingOrder RezeroZoneSizingArrays RhoH2O RHtoVP RKG RoundSigDigits rRoundSigDigits rTrimSigDigits SafeCopyPlantNode SafeDiv SafeDivide SameString SandiaCellTemperature SandiaEffectiveIrradiance SandiaF1 SandiaF2 SandiaImp SandiaIsc SandiaIx SandiaIxx SandiaModuleTemperature SandiaTcellFromTmodule SandiaVmp SandiaVoc SaveSimpleController ScanForReports ScanPlantLoopsForNodeNum ScanPlantLoopsForObject sCheckDayScheduleValueMinMax ScheduleAverageHoursPerWeek SEARCH SearchAscTable SearchWindow5DataFile SecantFormula SecantMethod selectTariff SetActuatedBranchFlowRate SetAdditionalNeighborData SetAllFlowLocks SetAllPlantSimFlagsToValue SetATMixerPriFlow SetATMixerPriFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetCoilDesFlow SetCoilSystemCoolingData SetCoilSystemHeatingDXFlag SetCompFlowRate SetComponentFlowRate SetCurrentWeather SetCurveOutputMinMaxValues SetDSTDateRanges SetDXCoilTypeData SetDXCoolingCoilData SetEquivalentLayerWindowProperties SetErlValueNumber SetExtConvectionCoeff SetFanData SetHeatExchangerData SetHeatToReturnAirFlag SetInitialMeterReportingAndOutputNames SetIntConvectionCoeff SetInternalVariableValue SetMinMax setNativeVariables SetNodeResult SetOAControllerData SetOnOffMassFlowRate SetOnOffMassFlowRate SetOnOffMassFlowRate SetOnOffMassFlowRateVSCoil SetOnOffMassFlowRateVSCoil SetOutAirNodes SetOutBulbTempAt SetPredefinedTables SetSimpleWSHPData SETSKY SetSpecialDayDates SetSpeedVariables SetStormWindowControl SetSurfHBDataForMundtModel SetSurfHBDataForTempDistModel SetSurfTmeanAir SETUP4x4_A SetupAdaptiveConvectionRadiantSurfaceData SetupAdaptiveConvectionStaticMetaData SetupAirLoopControllersTracer SetupAllOutputVariables SetUpAndSort SetupBranchControlTypes SetupCellNeighbors SetupCommonPipes SetupComplexFenestrationMaterialInput SetupComplexFenestrationStateInput SetupComplexWindowStateGeometry SetUpCompSets SetupDElightOutput4EPlus SetupDElightOutput4EPlus SetUpDesignDay SetupEMSActuator SetupEMSIntegerActuator SetupEMSIntegerInternalVariable SetupEMSInternalVariable SetupEMSLogicalActuator SetupEMSRealActuator SetupEMSRealInternalVariable SetupEnvironmentTypes SetupFuelConstituentData SetupGeneratorControlStateManager SetupIndividualControllerTracer SetupInitialPlantCallingOrder SetupIntegerOutputVariable SetupInterpolationValues SetupLoopFlowRequest SetupMeteredVarsForSetPt SetupMundtModel SetupNodeSetpointsAsActuators SetupNodeVarsForReporting SetupOutputVariable SetupPipeCircuitInOutCells SetupPlantEMSActuators SetupPollutionCalculations SetupPollutionMeterReporting SetupPossibleOperators SetupPrimaryAirSystemAvailMgrAsActuators SetupPumpMinMaxFlows SetupRealOutputVariable SetupRealOutputVariable_IntKey SetupReportInput SetupReports SetupRootFinder SetUpSchemeColors SetupShadeSurfacesForSolarCalcs SetupSimpleWindowGlazingSystem SetupSimulation SetupStratifiedNodes SetupSurfaceConstructionActuators SetupSurfaceConvectionActuators SetupSurfaceOutdoorBoundaryConditionActuators SetUpSysSizingArrays SetupTankDemandComponent SetupTankSupplyComponent SetupThermostatActuators SetupTimePointers SetupUnitConversions SetupWeekDaysByMonth SetupWindowShadingControlActuators SetupZoneEquipmentForConvectionFlowRegime SetupZoneGeometry SetupZoneInfoAsInternalDataAvail SetupZoneInternalGain SetupZoneInternalGain SetupZoneSizing SetUpZoneSizingArrays SetUTSCQdotSource SetVarSpeedCoilData SetVentedModuleQdotSource SetVSHPAirFlow SetVSHPAirFlow SetWindSpeedAt SetZoneEquipSimOrder shading shadingedge shadingin SHADOW SharedDVCVUFDataInit SHDBKS SHDGSS SHDRVL SHDSBS shift ShiftPipeTemperaturesForNewIteration ShiftPlantLoopSideCallingOrder ShiftTemperaturesForNewIteration ShiftTemperaturesForNewTimeStep ShowAuditErrorMessage ShowBranchesOnLoop ShowContinueError ShowContinueError ShowContinueErrorTimeStamp ShowContinueErrorTimeStamp ShowErrorMessage ShowErrorMessage ShowFatalError ShowFatalError ShowMessage ShowMessage ShowPsychrometricSummary ShowRecurringContinueErrorAtEnd ShowRecurringContinueErrorAtEnd ShowRecurringErrors ShowRecurringSevereErrorAtEnd ShowRecurringSevereErrorAtEnd ShowRecurringWarningErrorAtEnd ShowRecurringWarningErrorAtEnd ShowSevereError ShowSevereError ShowSevereMessage ShowSevereMessage ShowWarningError ShowWarningError ShowWarningMessage ShowWarningMessage showWarningsBasedOnTotal Sim4PipeFanCoil SimAirChillerSet SimAirLoop SimAirLoopComponent SimAirLoopComponents SimAirLoops SimAirLoopSplitter SimAirMixer SimAirTerminalUserDefined SimAirZonePlenum SimATMixer SimBaseboard SimBLASTAbsorber SimBoiler SimCBVAV SimCBVAV SimCentralGroundSourceHeatPump SimChiller SimCoilUserDefined SimComponentModelFan SimConstVol SimCoolBeam SimCostEstimate SimCTGenerator SimCTPlantHeatRecovery SimCyclingWindowAC SimDesiccantDehumidifier SimDetailedIceStorage SimDirectAir SimDistrictEnergy SimDualDuctConstVol SimDualDuctVarVol SimDualDuctVAVOutdoorAir SimDuct SimDXCoil SimDXCoilMultiMode SimDXCoilMultiSpeed SimDXCoolingSystem SimDXHeatPumpSystem SimElecBaseBoard SimElectricBaseBoard SimElectricConvective SimElectricEIRChiller SimEvapCooler SimEvapFluidCoolers SimExhaustAbsorber SimFanCoilUnit SimFluidCoolers SimFluidHeatExchanger SimFourPipeIndUnit SimFuelCellGenerator SimFuelCellPlantHeatRecovery SimFurnace SimGasAbsorber SimGroundHeatExchangers SimHeatPumpWaterHeater SimHeatRecovery SimHighTempRadiantSystem SimHPWatertoWaterCOOLING SimHPWatertoWaterHEATING SimHPWatertoWaterSimple SimHumidifier SimHVAC SimHWBaseboard SimHWConvective SimHXAssistedCoolingCoil SimICEngineGenerator SimICEPlantHeatRecovery SimIceStorage SimIndirectAbsorber SimIndUnit SimLowTempRadiantSystem SimMicroCHPGenerator SimMicroCHPPlantHeatRecovery SimMSHeatPump SimMSHP SimMTGenerator SimMTPlantHeatRecovery SimMultiSpeedCoils SimOAComponent SimOAController SimOAMixer SimOnOffFan SimOutdoorAirEquipComps SimOutdoorAirUnit SimOutsideAirSys SimOutsideEnergy SimPackagedTerminalUnit SimPipes SimPipesHeatTransfer SimPipingSystemCircuit SimPIU SimPlantEquip SimPlantValves SimpleCoolingCoilUAResidual SimpleEvapFluidCoolerUAResidual SimpleFluidCoolerUAResidual SimpleHeatingCoilUAResidual SimpleTowerApproachResidual SimpleTowerTrResidual SimpleTowerUAResidual SimPondGroundHeatExchanger SimPressureDropSystem SimPTUnit SimPumps SimPurchasedAir SimPVGenerator SimPVTcollectors SimReformulatedEIRChiller SimRefrigCondenser SimReturnAirPath SimSelectedEquipment SimSetPointManagers SimSimpleEvapFluidCooler SimSimpleFan SimSimpleFluidCooler SimSimpleTower SimSolarCollector SimStandAloneERV SimSteamBaseboard SimSteamBoiler SimSteamCoils SimSurfaceGroundHeatExchanger SimSysAvailManager SimTESCoil SimTowers SimTranspiredCollector SimulateAllInteriorRadialSoilSlices SimulateAllLoopSideBranches SimulateAllLoopSidePumps SimulateDemandManagerList SimulateDetailedRefrigerationSystems SimulateDetailedTransRefrigSystems SimulateDualDuct SimulateFanComponents SimulateFluidCell SimulateHeatingCoilComponents SimulateInnerMostRadialSoilSlice SimulateLoopSideBranchGroup SimulateOuterMostRadialSoilSlice SimulatePlantProfile SimulateRadialInsulationCell SimulateRadialPipeCell SimulateRadialToCartesianInterface SimulateSingleDuct SimulateSteamCoilComponents SimulateVRF SimulateWaterCoilComponents SimulateWaterHeaterStandAlone SimulateWaterUse SimulateWaterUseConnection SimUnitaryBypassVAV SimUnitarySystem SimUnitHeater SimUnitVentilator SimUnitVentOAMixer SimUserDefinedPlantComponent SimVariableSpeedCoils SimVariableSpeedHP SimVariableSpeedHP SimVariableTower SimVariableVolumeFan SimVAV SimVAVVS SimVentilatedSlab SimVentSlabOAMixer SimVRF SimVRFCondenserPlant SimWaterCoils SimWaterSource SimWaterThermalTank SimWatertoAirHP SimWatertoAirHPSimple SimWindowAC SimWindTurbine SimZoneAirLoopEquipment SimZoneAirUserDefined SimZoneDehumidifier SimZoneEquipment SimZoneEvaporativeCoolerUnit SimZoneExhaustFan SimZoneOutAirUnitComps SingelSpeedDXCoolingCoilStandardRatings SingleSpeedDXHeatingCoilStandardRatings SingleSpeedFluidCooler SizeAbsorpChiller SizeAirLoopBranches SizeAirLoops SizeBaseboard SizeBoiler SizeBoiler SizeCBVAV SizeConstCOPChiller SizeController SizeCoolBeam SizeDemandSidePlantConnections SizeDirectAir SizeDualDuct SizeDXCoil SizeElecReformEIRChiller SizeElectricBaseboard SizeElectricBaseboard SizeElectricChiller SizeElectricEIRChiller SizeEngineDrivenChiller SizeEvapCooler SizeEvapFluidCooler SizeExhaustAbsorber SizeFan SizeFanCoilUnit SizeFluidCooler SizeFluidHeatExchanger SizeFurnace SizeGasAbsorber SizeGTChiller SizeHeatingCoil SizeHeatRecovery SizeHighTempRadiantSystem SizeHumidifier SizeHVACWaterToAir SizeHWBaseboard SizeIndirectAbsorpChiller SizeIndUnit SizeLowTempRadiantSystem SizeMSHeatPump SizeOAController SizeOutdoorAirUnit SizePIU SizePlantLoop SizePTUnit SizePump SizePurchasedAir SizePVT SizeStandAloneERV SizeStandAloneWaterHeater SizeSteamBaseboard SizeSteamCoil SizeSupplySidePlantConnections SizeSys SizeTankForDemandSide SizeTankForSupplySide SizeTESCoil SizeTower SizeUCSDUF SizeUnitarySystem SizeUnitHeater SizeUnitVentilator SizeVarSpeedCoil SizeVentilatedSlab SizeVRF SizeVRFCondenser SizeVSMerkelTower SizeWaterCoil SizeWaterManager SizeWaterSource SizeWindowAC SizeWrapper SizeZoneDehumidifier SizeZoneEquipment SizeZoneEvaporativeCoolerUnit SkipEPlusWFHeader SkyDifSolarShading SkyGndWeight SkyWeight SLtoAMB SLtoGL SLVSKY solar_EN673 solarISO15099 SolarSprectrumAverage SOLMATS SolveAirLoopControllers SolveForWindowTemperatures SolveRegression SolveRegulaFalsi SolverMoistureBalanceEMPD SOLVZP SortHistory Specular_Adjust Specular_EstimateDiffuseProps Specular_F Specular_OffNormal Specular_RATDiff Specular_SWP SQLiteBegin SQLiteBegin SQLiteBindDouble SQLiteBindInteger SQLiteBindLogicalMacro SQLiteBindNULL SQLiteBindText SQLiteBindTextMacro SQLiteClearBindings SQLiteCloseDatabase SQLiteColumnInt SQLiteColumnIntMacro SQLiteCommit SQLiteCommit SQLiteExecuteCommand SQLiteExecuteCommandMacro SQLiteFinalizeCommand SQLiteOpenDatabase SQLiteOpenDatabaseMacro SQLitePrepareStatement SQLitePrepareStatementMacro SQLiteResetCommand SQLiteStepCommand SQLiteWriteMessage SQLiteWriteMessageMacro SQLiteWriteMessageMacro StandardIndexTypeKey StandardVariableTypeKey StartingWindowTemps StartingWinTempsForNominalCond SteamHeatingCoilResidual StorageType StoreAPumpOnCurrentTempLoop storeIterationResults StoreRecurringErrorMessage StringValue StrToReal SumAllInternalCO2Gains SumAllInternalConvectionGains SumAllInternalGenericContamGains SumAllInternalLatentGains SumAllInternalRadiationGains SumAllReturnAirConvectionGains SumAllReturnAirLatentGains SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumInternalCO2GainsByTypes SumInternalConvectionGainsByTypes SumInternalLatentGainsByTypes SumInternalRadiationGainsByTypes SummarizeErrors SumReturnAirConvectionGainsByTypes SumZoneImpacts SUN3 SUN4 SupSATResidual SurfaceScheduledSolarInc SurveyDemandManagers SystemPropertiesAtLambdaAndPhi SystemSpectralPropertiesAtPhi TableLookupObject TARCOG90 TBND TdbFnHRhPb TDMA TDMA_R TellMeHowManyObjectItemArgs TemperaturesFromEnergy TempIPtoSI TempSItoIP terpld TESCoilHumRatResidual TESCoilResidual TestAirPathIntegrity TestBranchIntegrity TestCompSet TestCompSetInletOutletNodes TestInletOutletNodes TestReturnAirPathIntegrity TestSupplyAirPathIntegrity therm1d TightenNodeMinMaxAvails TimestepInitComplexFenestration TimestepTypeName TraceAirLoopController TraceAirLoopControllers TraceIndividualController TraceIterationStamp TrackAirLoopController TrackAirLoopControllers TRadC TransAndReflAtPhi TransformVertsByAspect TransTDD Triangulate TrimSigDigits TurnOffLoopEquipment TurnOffLoopSideEquipment TurnOffReportRangeCheckErrors TurnOnPlantLoopPipes TurnOnReportRangeCheckErrors TwoSpeedFluidCooler UnitarySystemHeatRecovery UpdateAbsorberChillerComponentGeneratorSide UpdateAirflowNetwork UpdateAirMixer UpdateAirSysCompPtrArray UpdateAirSysSubCompPtrArray UpdateAirSysSubSubCompPtrArray UpdateAirZoneReturnPlenum UpdateAirZoneSupplyPlenum UpdateAnyLoopDemandAlterations UpdateATMixer UpdateBaseboard UpdateBaseboardPlantConnection UpdateBasementSurfaceTemperatures UpdateBBElecRadSourceValAvg UpdateBBRadSourceValAvg UpdateBBSteamRadSourceValAvg UpdateBLASTAbsorberRecords UpdateBoilerRecords UpdateBoilerRecords UpdateBracket UpdateBranchConnections UpdateChillerComponentCondenserSide UpdateChillerheaterRecords UpdateChillerRecords UpdateColdWeatherProtection UpdateCommonPipe UpdateComplexWindows UpdateComponentHeatRecoverySide UpdateConstCOPChillerRecords UpdateController UpdateCoolBeam UpdateCoolTower UpdateCTGeneratorRecords UpdateDataandReport UpdateDemandManagers UpdateDesiccantDehumidifier UpdateDetailedIceStorage UpdateDualDuct UpdateDuct UpdateDXCoil UpdateElectricBaseboard UpdateElectricChillerRecords UpdateElectricEIRChillerRecords UpdateEMSTrendVariables UpdateEngineDrivenChiller UpdateEvapCooler UpdateEvapFluidCooler UpdateEvaporativeCondenserBasinHeater UpdateEvaporativeCondenserWaterUse UpdateExhaustAbsorberCoolRecords UpdateExhaustAbsorberHeatRecords UpdateExhaustAirFlows UpdateFan UpdateFinalSurfaceHeatBalance UpdateFluidCooler UpdateFluidHeatExchanger UpdateFuelCellGeneratorRecords UpdateGasAbsorberCoolRecords UpdateGasAbsorberHeatRecords UpdateGSHPRecords UpdateGSHPRecords UpdateGSHPRecords UpdateGTChillerRecords UpdateHalfLoopInletTemp UpdateHeatBalHAMT UpdateHeatingCoil UpdateHeatRecovery UpdateHighTempRadiantSystem UpdateHistories UpdateHistory UpdateHTRadSourceValAvg UpdateHumidifier UpdateHVACInterface UpdateHWBaseboard UpdateHWBaseboardPlantConnection UpdateIceFractions UpdateICEngineGeneratorRecords UpdateIndirectAbsorberRecords UpdateInternalGainValues UpdateIrrigation UpdateLoadCenterRecords UpdateLoopSideReportVars UpdateLowTempRadiantSystem UpdateMeterReporting UpdateMeters UpdateMeterValues UpdateMicroCHPGeneratorRecords UpdateMinMax UpdateMixedAirSetPoints UpdateMoistureBalanceEMPD UpdateMoistureBalanceFD UpdateMSHeatPump UpdateMTGeneratorRecords UpdateNode UpdateNodeThermalHistory UpdateOAController UpdateOAMixer UpdateOAPretreatSetPoints UpdatePipesHeatTransfer UpdatePipingSystems UpdatePlantLoopInterface UpdatePlantMixer UpdatePlantProfile UpdatePlantSplitter UpdatePlantValves UpdatePondGroundHeatExchanger UpdatePrecipitation UpdatePressureDrop UpdatePurchasedAir UpdatePVTcollectors UpdateRadSysSourceValAvg UpdateRecords UpdateReformEIRChillerRecords UpdateRefrigCondenser UpdateReportWaterSystem UpdateRootFinder UpdateScheduleValues UpdateSetPointManagers UpdateSimpleWatertoAirHP UpdateSoilProps UpdateSolarCollector UpdateSplitter UpdateSQLiteErrorRecord UpdateSQLiteErrorRecord UpdateSQLiteSimulationRecord UpdateSQLiteSimulationRecord UpdateSteamBaseboard UpdateSteamBaseboardPlantConnection UpdateSteamCoil UpdateSurfaceGroundHeatExchngr UpdateSys UpdateSysSizing UpdateSystemOutputRequired UpdateTabularReports UpdateTEStorage UpdateThermalHistories UpdateTowers UpdateTranspiredCollector UpdateUnitarySystemControl UpdateUtilityBills UpdateVarSpeedCoil UpdateVentilatedSlab UpdateVerticalGroundHeatExchanger UpdateVRFCondenser UpdateWaterCoil UpdateWaterConnections UpdateWaterManager UpdateWaterSource UpdateWaterThermalTank UpdateWaterToAirCoilPlantConnection UpdateWatertoAirHP UpdateWeatherData UpdateWholeBuildingRecords UpdateZoneAirLoopEquipment UpdateZoneCompPtrArray UpdateZoneDehumidifier UpdateZoneEquipment UpdateZoneInletConvergenceLog UpdateZoneListAndGroupLoads UpdateZoneSizing UpdateZoneSubCompPtrArray UpdateZoneSubSubCompPtrArray ValidateAndSetSysAvailabilityManagerType ValidateComponent ValidateDistributionSystem ValidateEMSProgramName ValidateEMSVariableName ValidateExhaustFanInput ValidateFlowControlPaths ValidateFuelType ValidateIndexType ValidateMaterialRoughness ValidateMonthDay ValidateNStandardizeMeterTitles ValidateObjectandParse ValidatePipeConstruction ValidatePLFCurve ValidateSection ValidateSectionsInput ValidateVariableType value_to_vector ValueToString VAVVSCoolingResidual VAVVSHCFanOnResidual VAVVSHWFanOnResidual VAVVSHWNoFanResidual VB_CriticalSlatAngle VB_DIFF VB_LWP VB_ShadeControl VB_SLAT_RADIUS_RATIO VB_SOL4 VB_SOL46_CURVE VB_SOL6 VB_SWP vec2d_cross_product vec2d_dot_product vec_cross_product vec_dot_product VecLength VecNegate VecNormalize VecRound VecSquaredLength vector_add vector_div_int vector_div_real vector_subtract vector_times_int vector_times_real vector_to_array VerifyControlledZoneForThermostat VerifyCustomMetersElecPowerMgr VerifyHeatExchangerParent VerifyName VerifySetPointManagers VerifyThermostatInZone VerifyUniqueBaseboardName VerifyUniqueBoilerName VerifyUniqueChillerName VerifyUniqueCoilName ViewFac VisibleSprectrumAverage Volume VRMLOut VSCoilCyclingHumResidual VSCoilCyclingResidual VSCoilCyclingResidual VSCoilSpeedHumResidual VSCoilSpeedResidual VSCoilSpeedResidual VSEvapUnitLoadResidual VSHPCyclingResidual VSHPCyclingResidual VSHPSpeedResidual VSHPSpeedResidual VSMerkelResidual W5InitGlassParameters W5LsqFit W5LsqFit2 W6CoordsFromWorldVect warnIfNativeVarname WetCoilOutletCondition WhichCompSet WhichParentCompSet WhichParentSet Width WindowGapAirflowControl WindowGasConductance WindowGasPropertiesAtTemp WindowHeatBalanceEquations WindowScheduledSolarAbs WindowShadingManager WindowTempsForNominalCond WindSpeedAt Windward WorldVectFromW6 WriteAdaptiveComfortTable WriteAirLoopStatistics WriteBEPSTable WriteCompCostTable WriteComponentSizing WriteCumulativeReportMeterData WriteDaylightMapTitle WriteDemandEndUseSummary WriteInputArguments WriteIntegerData WriteIntegerVariableOutput WriteMeterDictionaryItem WriteModifiedArguments WriteMonthlyTables WriteOutputArguments WriteOutputEN673 WritePoint WritePredefinedTables WriteRealData WriteRealVariableOutput WriteReportHeaders WriteReportIntegerData WriteReportMeterData WriteReportRealData WriteReportVariableDictionaryItem WriteRootFinderStatus WriteRootFinderTrace WriteRootFinderTraceHeader WriteSourceEnergyEndUseSummary writeSubtitle WriteSurfaceShadowing WriteTable WriteTableOfContents WriteTabularLifeCycleCostReport WriteTabularReports WriteTabularTariffReports WriteTARCOGInputFile writeTextLine WriteTimeBinTables WriteTimeStampFormatData WriteTrace WriteVeriSumTable WriteZoneLoadComponentTable WVDC XNormalArea XYRectangle XZRectangle YNormalArea YZRectangle ZeroHVACValues ZNormalArea
Call graph
getpollutionfactorinput calls rnumericargs, getnumobjectsfound, calphaargs, getmeterindex, showsevereerror, makeuppercase, showfatalerror, calphafieldnames, showwarningerror, checkffschedule, lalphafieldblanks, getobjectitem
getmeterindex calls makeuppercase, finditeminsortedlist, setupandsort, energymeters
showsevereerror calls showerrormessage, matchcounts, messagesearch, createsqliteerrorrecord
showfatalerror calls showerrormessage, createsqliteerrorrecord, displaystring, abortenergyplus, roundsigdigits
showwarningerror calls showerrormessage, matchcounts, messagesearch, createsqliteerrorrecord
checkffschedule calls showsevereerror, showcontinueerror, checkschedulevalueminmax, getscheduleindex
showerrormessage calls showfatalerror, displaystring
abortenergyplus calls displaystring, roundsigdigits, testairpathintegrity, updatesqlitesimulationrecord, checkmarkednodes, reportairloopconnections, showrecurringerrors, testcompsetinletoutletnodes, summarizeerrors, reportsurfaceerrors, reportloopconnections, closemiscopenfiles, setupnodevarsforreporting, closesocket, closeoutopenfiles, reportsurfaces, testbranchintegrity, checkplantonabort, epelapsedtime, epstoptime, epsummarytimes, showmessage, checknodeconnections
testairpathintegrity calls showsevereerror, airtozonenodeinfo, nodeid, showcontinueerror
showrecurringerrors calls createsqliteerrorrecord, roundsigdigits, showmessage, updatesqliteerrorrecord, removetrailingzeros, recurringerrors
summarizeerrors calls matchcounts, showmessage, summaries, moredetails
closemiscopenfiles calls closedfsfile, closereportillummaps
reportsurfaces calls showwarningerror, detailsforsurfaces, setupschemecolors, vrmlout, scanforreports, dxfoutwireframe, costinfoout, linesout, dxfout
epstoptime calls showfatalerror, tstop
epsummarytimes calls roundsigdigits
showmessage calls showerrormessage
showcontinueerror calls showerrormessage, updatesqliteerrorrecord
detailsforsurfaces calls roundsigdigits, getschedulename, oscm, nominalu, zone, framedivider, getschedulemaxvalue, 2, computenominaluwithconvcoeffs, 3, osc, trimsigdigits, construct, 4, csurfaceclass, userintconvectioncoeffs, userextconvectioncoeffs, surface, getscheduleminvalue, surfacewindow
setupschemecolors calls showwarningerror, getobjectitem, getobjectitemnum, getobjectdefmaxargs, matchandsetcolortextstring
vrmlout calls showfatalerror, showwarningerror, showcontinueerror, zone, surface, triangulate, getnewunitnumber
dxfoutwireframe calls showfatalerror, zone, trimsigdigits, surface, surfacewindow, getnewunitnumber, zonedaylight, dxfcolorno
costinfoout calls showfatalerror, construct, csurfaceclass, surface, getnewunitnumber
linesout calls showfatalerror, showwarningerror, roundsigdigits, showcontinueerror, csurfaceclass, surface, getnewunitnumber
dxfout calls showfatalerror, showwarningerror, showcontinueerror, zone, trimsigdigits, surface, surfacewindow, triangulate, getnewunitnumber, zonedaylight, dxfcolorno, illummapcalc
computenominaluwithconvcoeffs calls surface
matchandsetcolortextstring calls finditem
triangulate calls showwarningerror, roundsigdigits, showmessage, showcontinueerror, csurfaceclass, generate_ears, calcrfflrcoordinatetransformation, calcwallcoordinatetransformation
generate_ears calls polygon_contains_point_2d, angle_2dvector
getfuelfactorinfo calls getpollutionfactorinput
getenvironmentalimpactfactorinfo calls getpollutionfactorinput
setuppollutionmeterreporting calls getpollutionfactorinput