GetTESCoilInput – EnergyPlusFortran
GetTESCoilInput Subroutine
1244 statements
Source File
private subroutine GetTESCoilInput()
Uses:
DataIPShortCuts
InputProcessor
WaterManager
GlobalNames
DataSizing
OutAirNodeManager
ScheduleManager
NodeInputManager
BranchNodeConnections
FluidProperties
DataZoneEquipment
DataHeatBalance
Arguments
None
Calls
Called By
Source Code
GetTESCoilInput
Source Code
SUBROUTINE GetTESCoilInput
          ! SUBROUTINE INFORMATION:
          !       AUTHOR         <author>
          !       DATE WRITTEN   <date_written>
          !       MODIFIED       na
          !       RE-ENGINEERED  na
          ! PURPOSE OF THIS SUBROUTINE:
          ! <description>
          ! METHODOLOGY EMPLOYED:
          ! <description>
          ! REFERENCES:
          ! na
          ! USE STATEMENTS:
  USE DataIPShortCuts
  USE InputProcessor,        ONLY: GetNumObjectsFound, GetObjectItem, GetObjectItemNum, VerifyName, SameString,GetObjectDefMaxArgs
  USE WaterManager,          ONLY: SetupTankDemandComponent, SetupTankSupplyComponent
  USE GlobalNames,           ONLY: VerifyUniqueCoilName
  USE DataSizing,            ONLY: AutoSize
  USE OutAirNodeManager,     ONLY: CheckOutAirNodeNumber
  USE ScheduleManager,       ONLY: GetScheduleIndex
  USE NodeInputManager,      ONLY: GetOnlySingleNode
  USE BranchNodeConnections, ONLY: TestCompSet
  USE FluidProperties,       ONLY: CheckFluidPropertyName, FindGlycol, GetFluidDensityTemperatureLimits, &
                                   GetFluidSpecificHeatTemperatureLimits
  USE DataZoneEquipment,     ONLY: FindControlledZoneIndexFromSystemNodeNumberForZone
  USE DataHeatBalance,       ONLY: IntGainTypeOf_PackagedTESCoilTank
  IMPLICIT NONE ! Enforce explicit typing of all variables in this routine
          ! SUBROUTINE ARGUMENT DEFINITIONS:
          ! na
          ! SUBROUTINE PARAMETER DEFINITIONS:
  CHARACTER(len=*), PARAMETER :: RoutineName='GetTESCoilInput: ' ! include trailing blank space
          ! INTERFACE BLOCK SPECIFICATIONS:
          ! na
          ! DERIVED TYPE DEFINITIONS:
          ! na
          ! SUBROUTINE LOCAL VARIABLE DECLARATIONS:
  INTEGER  :: item  ! do loop counter
  INTEGER :: NumAlphas            ! Number of alphas in input
  INTEGER :: NumNumbers           ! Number of numeric items in input
  INTEGER :: IOStatus             ! Input status returned from GetObjectItem
  LOGICAL :: IsNotOK              ! Flag to verify name
  LOGICAL :: IsBlank              ! Flag for blank name
  LOGICAL :: ErrorsFound=.false.  ! Set to true if errors in input, fatal at end of routine
  LOGICAL :: errflag
  REAL(r64) :: TminRho
  REAL(r64) :: TmaxRho
  REAL(r64) :: TminCp
  REAL(r64) :: TmaxCp
  INTEGER   :: ZoneIndexTrial
  cCurrentModuleObject = 'Coil:Cooling:DX:SingleSpeed:ThermalStorage'
  NumTESCoils = GetNumObjectsFound(cCurrentModuleObject)
  ALLOCATE( TESCoil (NumTESCoils))
  ALLOCATE( CheckEquipName(NumTESCoils))
  CheckEquipName = .TRUE.
  DO item = 1, NumTESCoils
    CALL GetObjectItem(cCurrentModuleObject, item, cAlphaArgs, NumAlphas, rNumericArgs, NumNumbers, &
                       IOStatus, NumBlank=lNumericFieldBlanks, AlphaBlank=lAlphaFieldBlanks,        &
                       AlphaFieldNames= cAlphaFieldNames  , NumericFieldNames= cNumericFieldNames )
    IsNotOK=.FALSE.
    IsBlank=.FALSE.
    CALL VerifyName(cAlphaArgs(1), TESCoil%Name, item - 1, IsNotOK, IsBlank, TRIM(cCurrentModuleObject)//' Name')
    IF (IsNotOK) THEN
      ErrorsFound=.true.
      IF (IsBlank) cAlphaArgs(1)='xxxxx'
    ENDIF
    CALL VerifyUniqueCoilName(cCurrentModuleObject, cAlphaArgs(1), errflag, TRIM(cCurrentModuleObject)//' Name')
    IF (errflag) THEN
      ErrorsFound=.true.
    ENDIF
    TESCoil(item)%Name = cAlphaArgs(1)
    IF (lAlphaFieldBlanks(2)) THEN
      TESCoil(item)%AvailSchedNum = ScheduleAlwaysOn
    ELSE
      TESCoil(item)%AvailSchedNum = GetScheduleIndex(cAlphaArgs(2))
      IF (TESCoil(item)%AvailSchedNum == 0) THEN
        CALL ShowSevereError(RoutineName//trim(cCurrentModuleObject)//'="'//trim(TESCoil(item)%Name)//'", invalid')
        CALL ShowContinueError('...'//TRIM(cAlphaFieldNames(2))//'="'//TRIM(cAlphaArgs(2))//'".')
        ErrorsFound=.TRUE.
      ENDIF
    ENDIF
    SELECT CASE (cAlphaArgs(3))
    CASE ('SCHEDULEDMODES')
      TESCoil(item)%ModeControlType = ScheduledOpModes
    CASE ('EMSCONTROLLED')
      TESCoil(item)%ModeControlType = EMSActuatedOpModes
    CASE DEFAULT
      CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
      CALL ShowContinueError('...'//TRIM(cAlphaFieldNames(3))//'="'//TRIM(cAlphaArgs(3))//'".')
      CALL ShowContinueError('Available choices are ScheduledModes or EMSControlled')
      ErrorsFound=.TRUE.
    END SELECT
    IF (lAlphaFieldBlanks(4)) THEN
      IF (TESCoil(item)%ModeControlType == ScheduledOpModes) THEN
        CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
        CALL ShowContinueError(TRIM(cAlphaFieldNames(4))//' is blank but a schedule is needed')
        ErrorsFound=.TRUE.
      ENDIF
    ELSE
      TESCoil(item)%ControlModeSchedNum = GetScheduleIndex(cAlphaArgs(4))
      IF (TESCoil(item)%ControlModeSchedNum == 0 .AND. TESCoil(item)%ModeControlType == ScheduledOpModes) THEN
        CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
        CALL ShowContinueError('...'//TRIM(cAlphaFieldNames(4))//'="'//TRIM(cAlphaArgs(4))//'".')
        ErrorsFound=.TRUE.
      ENDIF
    ENDIF
    SELECT CASE (cAlphaArgs(5))
    CASE ('ICE')
      TESCoil(item)%StorageMedia = IceBased
    CASE ('WATER')
      TESCoil(item)%StorageMedia = FluidBased
      TESCoil(item)%StorageFluidName = 'WATER'
      TESCoil(item)%StorageFluidIndex = FindGlycol('WATER')
    CASE ('USERDEFINEDFLUIDTYPE' )
      TESCoil(item)%StorageMedia = FluidBased
    CASE DEFAULT
      CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
      CALL ShowContinueError('...'//TRIM(cAlphaFieldNames(5))//'="'//TRIM(cAlphaArgs(5))//'".')
      CALL ShowContinueError('Available choices are Ice, Water, or UserDefindedFluidType')
      ErrorsFound=.TRUE.
    END SELECT
    IF (SameString(cAlphaArgs(5), 'USERDEFINEDFLUIDTYPE' )) THEN
      IF (.NOT. (lAlphaFieldBlanks(6))) THEN
        TESCoil(item)%StorageFluidName = cAlphaArgs(6)
        IF(CheckFluidPropertyName(cAlphaArgs(6)) == 0) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", missing fluid data')
          CALL ShowContinueError('Check that fluid property data have been input for fluid name = '//trim(cAlphaArgs(6)) )
          ErrorsFound=.TRUE.
        ELSE
          TESCoil(item)%StorageFluidIndex = FindGlycol(cAlphaArgs(6))
          IF (TESCoil(item)%StorageFluidIndex == 0) THEN
            CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid fluid data')
            CALL ShowContinueError('Check that correct fluid property data have been input for fluid name = '//trim(cAlphaArgs(6)) )
            ErrorsFound=.TRUE.
          ENDIF
        ENDIF
      ELSE
        CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
        CALL ShowContinueError('Storage Type is set to UserDefinedFluidType but no name of fluid was entered.' )
        ErrorsFound=.TRUE.
      ENDIF
    ENDIF
    IF ((TESCoil(item)%StorageMedia == FluidBased) .AND. (.not. lNumericFieldBlanks(1))) THEN
      TESCoil(item)%FluidStorageVolume = rNumericArgs(1)
    ELSEIF ((TESCoil(item)%StorageMedia == FluidBased)   .AND. ( lNumericFieldBlanks(1))) THEN
      CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
      CALL ShowContinueError(TRIM(cNumericFieldNames(1))//' cannot be blank for Water storage type')
      CALL ShowContinueError('Enter fluid storage tank volume in m3/s.')
      ErrorsFound=.TRUE.
    ENDIF
    IF ((TESCoil(item)%StorageMedia == IceBased) .AND. (.not. lNumericFieldBlanks(2))) THEN
      IF (rNumericArgs(2) == AutoCalculate) THEN
        TESCoil(item)%IceStorageCapacity = rNumericArgs(2)
      ELSE
        TESCoil(item)%IceStorageCapacity = rNumericArgs(2) * 1.d+09 ! input in giga joules, used as joules internally
      ENDIF
    ELSEIF ((TESCoil(item)%StorageMedia == IceBased) .AND. (lNumericFieldBlanks(2))) THEN
      CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
      CALL ShowContinueError(TRIM(cNumericFieldNames(2))//' cannot be blank for Ice storage type')
      CALL ShowContinueError('Enter ice storage tank capacity in GJ.')
      ErrorsFound=.TRUE.
    ENDIF
    TESCoil(item)%StorageCapacitySizingFactor = rNumericArgs(3)
    TESCoil(item)%StorageAmbientNodeNum = GetOnlySingleNode(cAlphaArgs(7), ErrorsFound, TRIM(cCurrentModuleObject), &
                                           cAlphaArgs(1), NodeType_Air, NodeConnectionType_Sensor,  &
                                          1, ObjectIsNotParent)
    ZoneIndexTrial = FindControlledZoneIndexFromSystemNodeNumberForZone(TESCoil(item)%StorageAmbientNodeNum)
    IF (ZoneIndexTrial > 0) THEN ! tank is inside a zone so setup internal gains
      CALL SetupZoneInternalGain(ZoneIndexTrial,          &
            'Coil:Cooling:DX:SingleSpeed:ThermalStorage', &
            TESCoil(item)%Name,                           &
            IntGainTypeOf_PackagedTESCoilTank,            &
            ConvectionGainRate    =   TESCoil(item)%QdotAmbient )
    ENDIF
    TESCoil(item)%StorageUA               =  rNumericArgs(4)
    TESCoil(item)%RatedFluidTankTemp      =  rNumericArgs(5)
    TESCoil(item)%RatedEvapAirVolFlowRate =  rNumericArgs(6)
    TESCoil(item)%EvapAirInletNodeNum = &
               GetOnlySingleNode(cAlphaArgs(8),ErrorsFound,TRIM(cCurrentModuleObject),cAlphaArgs(1), &
               NodeType_Air,NodeConnectionType_Inlet,1,ObjectIsNotParent)
    TESCoil(item)%EvapAirOutletNodeNum = &
               GetOnlySingleNode(cAlphaArgs(9),ErrorsFound,TRIM(cCurrentModuleObject),cAlphaArgs(1), &
               NodeType_Air,NodeConnectionType_Outlet,1,ObjectIsNotParent)
    CALL TestCompSet(TRIM(cCurrentModuleObject), cAlphaArgs(1), cAlphaArgs(8), cAlphaArgs(9), 'Air Nodes')
    SELECT CASE (cAlphaArgs(10))
    CASE ('YES')
      TESCoil(item)%CoolingOnlyModeIsAvailable = .TRUE.
    CASE ('NO')
      TESCoil(item)%CoolingOnlyModeIsAvailable = .FALSE.
    CASE DEFAULT
      TESCoil(item)%CoolingOnlyModeIsAvailable = .FALSE.
      CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
      CALL ShowContinueError('...'//TRIM(cAlphaFieldNames(10))//'="'//TRIM(cAlphaArgs(10))//'".')
      CALL ShowContinueError('Available choices are Yes or No.')
      ErrorsFound=.TRUE.
    END SELECT
    TESCoil(item)%CoolingOnlyRatedTotCap = rNumericArgs(7)
    IF (TESCoil(item)%CoolingOnlyModeIsAvailable) THEN ! get input data for this mode
      TESCoil(item)%CoolingOnlyRatedSHR    = rNumericArgs(8)
      TESCoil(item)%CoolingOnlyRatedCOP    = rNumericArgs(9)
      TESCoil(item)%CoolingOnlyCapFTempCurve = GetCurveIndex( cAlphaArgs(11) )
      IF (TESCoil(item)%CoolingOnlyCapFTempCurve == 0) THEN
        IF (lAlphaFieldBlanks(11)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(11))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(11))//'="'//TRIM(cAlphaArgs(11))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingOnlyCapFTempCurve) )
        CASE (CurveType_BiCubic, CurveType_BiQuadratic, CurveType_QuadraticLinear, CurveType_TableTwoIV)
          TESCoil(item)%CoolingOnlyCapFTempObjectNum = GetCurveObjectTypeNum(TESCoil(item)%CoolingOnlyCapFTempCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(11))//'="'//TRIM(cAlphaArgs(11))//'".')
          CALL ShowContinueError('Choose a curve or table with two independent variables, x and y.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingOnlyCapFFlowCurve = GetCurveIndex( cAlphaArgs(12) )
      IF (TESCoil(item)%CoolingOnlyCapFFlowCurve == 0) THEN
        IF (lAlphaFieldBlanks(12)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(12))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(12))//'="'//TRIM(cAlphaArgs(12))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingOnlyCapFFlowCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%CoolingOnlyCapFFlowObjectNum = GetCurveObjectTypeNum(TESCoil(item)%CoolingOnlyCapFFlowCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(12))//'="'//TRIM(cAlphaArgs(12))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingOnlyEIRFTempCurve = GetCurveIndex( cAlphaArgs(13) )
      IF (TESCoil(item)%CoolingOnlyEIRFTempCurve == 0) THEN
        IF (lAlphaFieldBlanks(13)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(13))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(13))//'="'//TRIM(cAlphaArgs(13))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingOnlyEIRFTempCurve) )
        CASE (CurveType_BiCubic, CurveType_BiQuadratic, CurveType_QuadraticLinear, CurveType_TableTwoIV)
          TESCoil(item)%CoolingOnlyEIRFTempObjectNum = GetCurveObjectTypeNum(TESCoil(item)%CoolingOnlyEIRFTempCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(13))//'="'//TRIM(cAlphaArgs(13))//'".')
          CALL ShowContinueError('Choose a curve or table with two independent variables, x and y.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingOnlyEIRFFlowCurve = GetCurveIndex( cAlphaArgs(14) )
      IF (TESCoil(item)%CoolingOnlyEIRFFlowCurve == 0) THEN
        IF (lAlphaFieldBlanks(14)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(14))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(14))//'="'//TRIM(cAlphaArgs(14))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingOnlyEIRFFlowCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%CoolingOnlyEIRFFlowObjectNum = GetCurveObjectTypeNum(TESCoil(item)%CoolingOnlyEIRFFlowCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(14))//'="'//TRIM(cAlphaArgs(14))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingOnlyPLFFPLRCurve = GetCurveIndex( cAlphaArgs(15) )
      IF (TESCoil(item)%CoolingOnlyPLFFPLRCurve == 0) THEN
        IF (lAlphaFieldBlanks(15)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(15))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(15))//'="'//TRIM(cAlphaArgs(15))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingOnlyPLFFPLRCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%CoolingOnlyPLFFPLRObjectNum = GetCurveObjectTypeNum(TESCoil(item)%CoolingOnlyPLFFPLRCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(15))//'="'//TRIM(cAlphaArgs(15))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingOnlySHRFTempCurve = GetCurveIndex( cAlphaArgs(16) )
      IF (TESCoil(item)%CoolingOnlySHRFTempCurve == 0) THEN
        IF (lAlphaFieldBlanks(16)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(16))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(16))//'="'//TRIM(cAlphaArgs(16))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingOnlySHRFTempCurve) )
        CASE (CurveType_BiCubic, CurveType_BiQuadratic, CurveType_QuadraticLinear, CurveType_TableTwoIV)
          TESCoil(item)%CoolingOnlySHRFTempObjectNum = GetCurveObjectTypeNum(TESCoil(item)%CoolingOnlySHRFTempCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(16))//'="'//TRIM(cAlphaArgs(16))//'".')
          CALL ShowContinueError('Choose a curve or table with two independent variables, x and y.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingOnlySHRFFlowCurve = GetCurveIndex( cAlphaArgs(17) )
      IF (TESCoil(item)%CoolingOnlySHRFFlowCurve == 0) THEN
        IF (lAlphaFieldBlanks(17)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(17))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(17))//'="'//TRIM(cAlphaArgs(17))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingOnlySHRFFlowCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%CoolingOnlySHRFFlowObjectNum = GetCurveObjectTypeNum(TESCoil(item)%CoolingOnlySHRFFlowCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(17))//'="'//TRIM(cAlphaArgs(17))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
    ENDIF
    SELECT CASE (cAlphaArgs(18))
    CASE ('YES')
      TESCoil(item)%CoolingAndChargeModeAvailable = .TRUE.
    CASE ('NO')
      TESCoil(item)%CoolingAndChargeModeAvailable = .FALSE.
    CASE DEFAULT
      TESCoil(item)%CoolingAndChargeModeAvailable = .FALSE.
      CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
      CALL ShowContinueError('...'//TRIM(cAlphaFieldNames(18))//'="'//TRIM(cAlphaArgs(18))//'".')
      CALL ShowContinueError('Available choices are Yes or No.')
      ErrorsFound=.TRUE.
    END SELECT
    IF (TESCoil(item)%CoolingAndChargeModeAvailable ) THEN
      TESCoil(item)%CoolingAndChargeRatedTotCap      = rNumericArgs(10) ! gross total evaporator cooling capacity [W]
      TESCoil(item)%CoolingAndChargeRatedTotCapSizingFactor = rNumericArgs(11) !sizing factor for gross total evaporator [ ]
      TESCoil(item)%CoolingAndChargeRatedChargeCap   = rNumericArgs(12)  !net storage charging capacity at rating conditions [W]
      TESCoil(item)%CoolingAndChargeRatedChargeCapSizingFactor = rNumericArgs(13) !sizing factor for charging capacity [ ]
      TESCoil(item)%CoolingAndChargeRatedSHR         = rNumericArgs(14) ! Sensible heat ratio (sens cap/total cap)  [W/W]
      TESCoil(item)%CoolingAndChargeCoolingRatedCOP  = rNumericArgs(15) ! Coefficient of performance , for cooling [W/W]
      TESCoil(item)%CoolingAndChargeChargingRatedCOP = rNumericArgs(16) ! Coefficient of performance , for charging [W/W]
      TESCoil(item)%CoolingAndChargeCoolingCapFTempCurve = GetCurveIndex( cAlphaArgs(19) )
      IF (TESCoil(item)%CoolingAndChargeCoolingCapFTempCurve == 0) THEN
        IF (lAlphaFieldBlanks(19)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(19))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(19))//'="'//TRIM(cAlphaArgs(19))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeCoolingCapFTempCurve) )
        CASE (CurveType_TriQuadratic, CurveType_TableMultiIV)
          TESCoil(item)%CoolingAndChargeCoolingCapFTempObjectNum = &
                                   GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeCoolingCapFTempCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(19))//'="'//TRIM(cAlphaArgs(19))//'".')
          CALL ShowContinueError('Choose a curve or table with three independent variables -- x, y, and z.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndChargeCoolingCapFFlowCurve = GetCurveIndex( cAlphaArgs(20) )
      IF (TESCoil(item)%CoolingAndChargeCoolingCapFFlowCurve == 0) THEN
        IF (lAlphaFieldBlanks(20)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(20))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(20))//'="'//TRIM(cAlphaArgs(20))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeCoolingCapFFlowCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%CoolingAndChargeCoolingCapFFlowObjectNum = &
                        GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeCoolingCapFFlowCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(20))//'="'//TRIM(cAlphaArgs(20))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndChargeCoolingEIRFTempCurve = GetCurveIndex( cAlphaArgs(21) )
      IF (TESCoil(item)%CoolingAndChargeCoolingEIRFTempCurve == 0) THEN
        IF (lAlphaFieldBlanks(21)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(21))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(21))//'="'//TRIM(cAlphaArgs(21))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeCoolingEIRFTempCurve) )
        CASE (CurveType_TriQuadratic, CurveType_TableMultiIV)
          TESCoil(item)%CoolingAndChargeCoolingEIRFTempObjectNum = &
                         GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeCoolingEIRFTempCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(21))//'="'//TRIM(cAlphaArgs(21))//'".')
          CALL ShowContinueError('Choose a curve or table with three independent variables -- x, y, and z.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndChargeCoolingEIRFFlowCurve = GetCurveIndex( cAlphaArgs(22) )
      IF (TESCoil(item)%CoolingAndChargeCoolingEIRFFlowCurve == 0) THEN
        IF (lAlphaFieldBlanks(22)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(22))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(22))//'="'//TRIM(cAlphaArgs(22))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeCoolingEIRFFlowCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%CoolingAndChargeCoolingEIRFFlowObjectNum = &
                        GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeCoolingEIRFFlowCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(22))//'="'//TRIM(cAlphaArgs(22))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndChargeCoolingPLFFPLRCurve = GetCurveIndex( cAlphaArgs(23) )
      IF (TESCoil(item)%CoolingAndChargeCoolingPLFFPLRCurve == 0) THEN
        IF (lAlphaFieldBlanks(23)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(23))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(23))//'="'//TRIM(cAlphaArgs(23))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeCoolingPLFFPLRCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%CoolingAndChargeCoolingPLFFPLRObjectNum = &
                        GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeCoolingPLFFPLRCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(23))//'="'//TRIM(cAlphaArgs(23))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndChargeChargingCapFTempCurve = GetCurveIndex( cAlphaArgs(24) )
      IF (TESCoil(item)%CoolingAndChargeChargingCapFTempCurve == 0) THEN
        IF (lAlphaFieldBlanks(24)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(24))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(24))//'="'//TRIM(cAlphaArgs(24))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeChargingCapFTempCurve) )
        CASE (CurveType_TriQuadratic, CurveType_TableMultiIV)
          TESCoil(item)%CoolingAndChargeCoolingEIRFTempObjectNum = &
                                  GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeChargingCapFTempCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(24))//'="'//TRIM(cAlphaArgs(24))//'".')
          CALL ShowContinueError('Choose a curve or table with three independent variables -- x, y, and z.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndChargeChargingCapFEvapPLRCurve = GetCurveIndex( cAlphaArgs(25) )
      IF (TESCoil(item)%CoolingAndChargeChargingCapFEvapPLRCurve == 0) THEN
        IF (lAlphaFieldBlanks(25)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(25))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(25))//'="'//TRIM(cAlphaArgs(25))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeChargingCapFEvapPLRCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%CoolingAndChargeChargingCapFEvapPLRObjectNum = &
                        GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeChargingCapFEvapPLRCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(25))//'="'//TRIM(cAlphaArgs(25))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndChargeChargingEIRFTempCurve = GetCurveIndex( cAlphaArgs(26) )
      IF (TESCoil(item)%CoolingAndChargeChargingEIRFTempCurve == 0) THEN
        IF (lAlphaFieldBlanks(26)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(26))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(26))//'="'//TRIM(cAlphaArgs(26))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeChargingEIRFTempCurve) )
        CASE (CurveType_TriQuadratic, CurveType_TableMultiIV)
          TESCoil(item)%CoolingAndChargeChargingEIRFTempObjectNum = &
                                  GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeChargingEIRFTempCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(26))//'="'//TRIM(cAlphaArgs(26))//'".')
          CALL ShowContinueError('Choose a curve or table with three independent variables -- x, y, and z.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndChargeChargingEIRFFLowCurve = GetCurveIndex( cAlphaArgs(27) )
      IF (TESCoil(item)%CoolingAndChargeChargingEIRFFLowCurve == 0) THEN
        IF (lAlphaFieldBlanks(27)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(27))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(27))//'="'//TRIM(cAlphaArgs(27))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeChargingEIRFFLowCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%CoolingAndChargeChargingEIRFFLowObjectNum = &
                        GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeChargingEIRFFLowCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(27))//'="'//TRIM(cAlphaArgs(27))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndChargeChargingPLFFPLRCurve = GetCurveIndex( cAlphaArgs(28) )
      IF (TESCoil(item)%CoolingAndChargeChargingPLFFPLRCurve == 0) THEN
        IF (lAlphaFieldBlanks(28)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(28))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(28))//'="'//TRIM(cAlphaArgs(28))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeChargingPLFFPLRCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%CoolingAndChargeChargingPLFFPLRObjectNum = &
                        GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeChargingPLFFPLRCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(28))//'="'//TRIM(cAlphaArgs(28))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndChargeSHRFTempCurve = GetCurveIndex( cAlphaArgs(29) )
      IF (TESCoil(item)%CoolingAndChargeSHRFTempCurve == 0) THEN
        IF (lAlphaFieldBlanks(29)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(29))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(29))//'="'//TRIM(cAlphaArgs(29))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeSHRFTempCurve) )
        CASE (CurveType_BiCubic, CurveType_BiQuadratic, CurveType_QuadraticLinear, CurveType_TableTwoIV, &
                 CurveType_TriQuadratic, CurveType_TableMultiIV)
          TESCoil(item)%CoolingAndChargeSHRFTempObjectNum = GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeSHRFTempCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(29))//'="'//TRIM(cAlphaArgs(29))//'".')
          CALL ShowContinueError('Choose a curve or table with two or three independent variables.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndChargeSHRFFlowCurve = GetCurveIndex( cAlphaArgs(30) )
      IF (TESCoil(item)%CoolingAndChargeSHRFFlowCurve == 0) THEN
        IF (lAlphaFieldBlanks(30)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(30))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(30))//'="'//TRIM(cAlphaArgs(30))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeSHRFFlowCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%CoolingAndChargeSHRFFlowObjectNum = &
                        GetCurveObjectTypeNum(TESCoil(item)%CoolingAndChargeSHRFFlowCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(30))//'="'//TRIM(cAlphaArgs(30))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
    ENDIF ! Cooling and Charge Mode available
    SELECT CASE (cAlphaArgs(31))
    CASE ('YES')
      TESCoil(item)%CoolingAndDischargeModeAvailable = .TRUE.
    CASE ('NO')
      TESCoil(item)%CoolingAndDischargeModeAvailable = .FALSE.
    CASE DEFAULT
      TESCoil(item)%CoolingAndDischargeModeAvailable = .FALSE.
      CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
      CALL ShowContinueError('...'//TRIM(cAlphaFieldNames(31))//'="'//TRIM(cAlphaArgs(31))//'".')
      CALL ShowContinueError('Available choices are Yes or No.')
      ErrorsFound=.TRUE.
    END SELECT
    IF ( TESCoil(item)%CoolingAndDischargeModeAvailable ) THEN
      TESCoil(item)%CoolingAndDischargeRatedTotCap         = rNumericArgs(17) ! gross total evaporator cooling capacity  [W]
      TESCoil(item)%CoolingAndDischargeRatedTotCapSizingFactor = rNumericArgs(18) !sizing factor gross total cooling capacity []
      TESCoil(item)%CoolingAndDischargeRatedDischargeCap   = rNumericArgs(19)  !net storage discharging capacity  [W]
      TESCoil(item)%CoolingAndDischargeRatedDischargeCapSizingFactor = rNumericArgs(20) !sizing factor discharging capacity []
      TESCoil(item)%CoolingAndDischargeRatedSHR            = rNumericArgs(21)  ! Sensible heat ratio (sens cap/total cap) [W/W]
      TESCoil(item)%CoolingAndDischargeCoolingRatedCOP     = rNumericArgs(22)  ! Coefficient of performance , for cooling [W/W]
      TESCoil(item)%CoolingAndDischargeDischargingRatedCOP = rNumericArgs(23)  ! Coefficient of performance , for charging [W/W]
      TESCoil(item)%CoolingAndDischargeCoolingCapFTempCurve = GetCurveIndex( cAlphaArgs(32) )
      IF (TESCoil(item)%CoolingAndDischargeCoolingCapFTempCurve == 0) THEN
        IF (lAlphaFieldBlanks(32)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(32))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(32))//'="'//TRIM(cAlphaArgs(32))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeCoolingCapFTempCurve) )
        CASE (CurveType_TriQuadratic, CurveType_TableMultiIV)
          TESCoil(item)%CoolingAndDischargeCoolingCapFTempObjectNum = &
                                   GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeCoolingCapFTempCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(32))//'="'//TRIM(cAlphaArgs(32))//'".')
          CALL ShowContinueError('Choose a curve or table with three independent variables -- x, y, and z.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndDischargeCoolingCapFFlowCurve = GetCurveIndex( cAlphaArgs(33) )
      IF (TESCoil(item)%CoolingAndDischargeCoolingCapFFlowCurve == 0) THEN
        IF (lAlphaFieldBlanks(33)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(33))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(33))//'="'//TRIM(cAlphaArgs(33))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeCoolingCapFFlowCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%CoolingAndDischargeCoolingCapFFlowObjectNum = &
                        GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeCoolingCapFFlowCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(33))//'="'//TRIM(cAlphaArgs(33))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndDischargeCoolingEIRFTempCurve = GetCurveIndex( cAlphaArgs(34) )
      IF (TESCoil(item)%CoolingAndDischargeCoolingEIRFTempCurve == 0) THEN
        IF (lAlphaFieldBlanks(34)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(34))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(34))//'="'//TRIM(cAlphaArgs(34))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeCoolingEIRFTempCurve) )
        CASE (CurveType_TriQuadratic, CurveType_TableMultiIV)
          TESCoil(item)%CoolingAndDischargeCoolingEIRFTempObjectNum = &
                                   GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeCoolingEIRFTempCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(34))//'="'//TRIM(cAlphaArgs(34))//'".')
          CALL ShowContinueError('Choose a curve or table with three independent variables -- x, y, and z.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndDischargeCoolingEIRFFlowCurve = GetCurveIndex( cAlphaArgs(35) )
      IF (TESCoil(item)%CoolingAndDischargeCoolingEIRFFlowCurve == 0) THEN
        IF (lAlphaFieldBlanks(35)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(35))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(35))//'="'//TRIM(cAlphaArgs(35))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeCoolingEIRFFlowCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%CoolingAndDischargeCoolingEIRFFlowObjectNum = &
                        GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeCoolingEIRFFlowCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(35))//'="'//TRIM(cAlphaArgs(35))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndDischargeCoolingPLFFPLRCurve = GetCurveIndex( cAlphaArgs(36) )
      IF (TESCoil(item)%CoolingAndDischargeCoolingPLFFPLRCurve == 0) THEN
        IF (lAlphaFieldBlanks(36)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(36))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(36))//'="'//TRIM(cAlphaArgs(36))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeCoolingPLFFPLRCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%CoolingAndDischargeCoolingPLFFPLRObjectNum = &
                        GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeCoolingPLFFPLRCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(36))//'="'//TRIM(cAlphaArgs(36))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndDischargeDischargingCapFTempCurve = GetCurveIndex( cAlphaArgs(37) )
      IF (TESCoil(item)%CoolingAndDischargeDischargingCapFTempCurve == 0) THEN
        IF (lAlphaFieldBlanks(37)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(37))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(37))//'="'//TRIM(cAlphaArgs(37))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeDischargingCapFTempCurve) )
        CASE (CurveType_TriQuadratic, CurveType_TableMultiIV)
          TESCoil(item)%CoolingAndDischargeDischargingCapFTempObjectNum = &
                                   GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeDischargingCapFTempCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(37))//'="'//TRIM(cAlphaArgs(37))//'".')
          CALL ShowContinueError('Choose a curve or table with three independent variables -- x, y, and z.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndDischargeDischargingCapFFlowCurve = GetCurveIndex( cAlphaArgs(38) )
      IF (TESCoil(item)%CoolingAndDischargeDischargingCapFFlowCurve == 0) THEN
        IF (lAlphaFieldBlanks(38)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(38))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(38))//'="'//TRIM(cAlphaArgs(38))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeDischargingCapFFlowCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%CoolingAndDischargeDischargingCapFFlowObjectNum = &
                        GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeDischargingCapFFlowCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(38))//'="'//TRIM(cAlphaArgs(38))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndDischargeDischargingCapFEvapPLRCurve = GetCurveIndex( cAlphaArgs(39) )
      IF (TESCoil(item)%CoolingAndDischargeDischargingCapFEvapPLRCurve == 0) THEN
        IF (lAlphaFieldBlanks(39)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(39))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(39))//'="'//TRIM(cAlphaArgs(39))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeDischargingCapFEvapPLRCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%CoolingAndDischargeDischargingCapFEvapPLRObjectNum = &
                        GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeDischargingCapFEvapPLRCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(39))//'="'//TRIM(cAlphaArgs(39))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndDischargeDischargingEIRFTempCurve = GetCurveIndex( cAlphaArgs(40) )
      IF (TESCoil(item)%CoolingAndDischargeDischargingEIRFTempCurve == 0) THEN
        IF (lAlphaFieldBlanks(40)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(40))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(40))//'="'//TRIM(cAlphaArgs(40))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeDischargingEIRFTempCurve) )
        CASE (CurveType_TriQuadratic, CurveType_TableMultiIV)
          TESCoil(item)%CoolingAndDischargeDischargingEIRFTempObjectNum = &
                                   GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeDischargingEIRFTempCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(40))//'="'//TRIM(cAlphaArgs(40))//'".')
          CALL ShowContinueError('Choose a curve or table with three independent variables -- x, y, and z.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndDischargeDischargingEIRFFLowCurve = GetCurveIndex( cAlphaArgs(41) )
      IF (TESCoil(item)%CoolingAndDischargeDischargingEIRFFLowCurve == 0) THEN
        IF (lAlphaFieldBlanks(41)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(41))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(41))//'="'//TRIM(cAlphaArgs(41))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeDischargingEIRFFLowCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%CoolingAndDischargeDischargingEIRFFLowObjectNum = &
                        GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeDischargingEIRFFLowCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(41))//'="'//TRIM(cAlphaArgs(41))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndDischargeDischargingPLFFPLRCurve = GetCurveIndex( cAlphaArgs(42) )
      IF (TESCoil(item)%CoolingAndDischargeDischargingPLFFPLRCurve == 0) THEN
        IF (lAlphaFieldBlanks(42)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(42))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(42))//'="'//TRIM(cAlphaArgs(42))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeDischargingPLFFPLRCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%CoolingAndDischargeDischargingPLFFPLRObjectNum = &
                        GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeDischargingPLFFPLRCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(42))//'="'//TRIM(cAlphaArgs(42))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndDischargeSHRFTempCurve = GetCurveIndex( cAlphaArgs(43) )
      IF (TESCoil(item)%CoolingAndDischargeSHRFTempCurve == 0) THEN
        IF (lAlphaFieldBlanks(43)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(43))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(43))//'="'//TRIM(cAlphaArgs(43))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeSHRFTempCurve) )
        CASE (CurveType_BiCubic, CurveType_BiQuadratic, CurveType_QuadraticLinear, CurveType_TableTwoIV, &
                 CurveType_TriQuadratic, CurveType_TableMultiIV)
          TESCoil(item)%CoolingAndDischargeSHRFTempObjectNum = &
                     GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeSHRFTempCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(43))//'="'//TRIM(cAlphaArgs(43))//'".')
          CALL ShowContinueError('Choose a curve or table with two or three independent variables.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%CoolingAndDischargeSHRFFlowCurve = GetCurveIndex( cAlphaArgs(44) )
      IF (TESCoil(item)%CoolingAndDischargeSHRFFlowCurve == 0) THEN
        IF (lAlphaFieldBlanks(44)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(44))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(44))//'="'//TRIM(cAlphaArgs(44))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeSHRFFlowCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%CoolingAndDischargeSHRFFlowObjectNum = &
                        GetCurveObjectTypeNum(TESCoil(item)%CoolingAndDischargeSHRFFlowCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(44))//'="'//TRIM(cAlphaArgs(44))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
    ENDIF ! cooling and discharge mode available
    SELECT CASE (cAlphaArgs(45))
    CASE ('YES')
      TESCoil(item)%ChargeOnlyModeAvailable = .TRUE.
    CASE ('NO')
      TESCoil(item)%ChargeOnlyModeAvailable = .FALSE.
    CASE DEFAULT
      TESCoil(item)%ChargeOnlyModeAvailable = .FALSE.
      CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
      CALL ShowContinueError('...'//TRIM(cAlphaFieldNames(45))//'="'//TRIM(cAlphaArgs(45))//'".')
      CALL ShowContinueError('Available choices are Yes or No.')
      ErrorsFound=.TRUE.
    END SELECT
    IF ( TESCoil(item)%ChargeOnlyModeAvailable ) THEN
      TESCoil(item)%ChargeOnlyRatedCapacity = rNumericArgs(24) ! net storage charging capacity at rating conditions [W]
      TESCoil(item)%ChargeOnlyRatedCapacitySizingFactor  = rNumericArgs(25) !sizing factor for charging capacity []
      TESCoil(item)%ChargeOnlyRatedCOP      = rNumericArgs(26)  ! coefficient of performance at rating conditions [W/W]
      TESCoil(item)%ChargeOnlyChargingCapFTempCurve = GetCurveIndex( cAlphaArgs(46) )
      IF (TESCoil(item)%ChargeOnlyChargingCapFTempCurve == 0) THEN
        IF (lAlphaFieldBlanks(46)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(46))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(46))//'="'//TRIM(cAlphaArgs(46))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%ChargeOnlyChargingCapFTempCurve) )
        CASE (CurveType_BiCubic, CurveType_BiQuadratic, CurveType_QuadraticLinear, CurveType_TableTwoIV)
          TESCoil(item)%ChargeOnlyChargingCapFTempObjectNum = &
                     GetCurveObjectTypeNum(TESCoil(item)%ChargeOnlyChargingCapFTempCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(46))//'="'//TRIM(cAlphaArgs(46))//'".')
          CALL ShowContinueError('Choose a curve or table with two independent variables, x and y.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%ChargeOnlyChargingEIRFTempCurve = GetCurveIndex( cAlphaArgs(47) )
      IF (TESCoil(item)%ChargeOnlyChargingEIRFTempCurve == 0) THEN
        IF (lAlphaFieldBlanks(47)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(47))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(47))//'="'//TRIM(cAlphaArgs(47))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%ChargeOnlyChargingEIRFTempCurve) )
        CASE (CurveType_BiCubic, CurveType_BiQuadratic, CurveType_QuadraticLinear, CurveType_TableTwoIV)
          TESCoil(item)%ChargeOnlyChargingEIRFTempObjectNum = &
                     GetCurveObjectTypeNum(TESCoil(item)%ChargeOnlyChargingEIRFTempCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(47))//'="'//TRIM(cAlphaArgs(47))//'".')
          CALL ShowContinueError('Choose a curve or table with two independent variables, x and y.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
    ENDIF ! Charge only mode available
    SELECT CASE (cAlphaArgs(48))
    CASE ('YES')
      TESCoil(item)%DischargeOnlyModeAvailable = .TRUE.
    CASE ('NO')
      TESCoil(item)%DischargeOnlyModeAvailable = .FALSE.
    CASE DEFAULT
      TESCoil(item)%DischargeOnlyModeAvailable = .FALSE.
      CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
      CALL ShowContinueError('...'//TRIM(cAlphaFieldNames(48))//'="'//TRIM(cAlphaArgs(48))//'".')
      CALL ShowContinueError('Available choices are Yes or No.')
      ErrorsFound=.TRUE.
    END SELECT
    IF ( TESCoil(item)%DischargeOnlyModeAvailable ) THEN
      TESCoil(item)%DischargeOnlyRatedDischargeCap = rNumericArgs(27) ! gross total evaporator cooling capacity  [W]
      TESCoil(item)%DischargeOnlyRatedDischargeCapSizingFactor = rNumericArgs(28) ! sizing factor for cooling capacity []
      TESCoil(item)%DischargeOnlyRatedSHR          = rNumericArgs(29)! sensible heat ratio (sens cap/total cap)
      TESCoil(item)%DischargeOnlyRatedCOP          = rNumericArgs(30)! coefficient of performance  for discharging [W/W]
      TESCoil(item)%DischargeOnlyCapFTempCurve = GetCurveIndex( cAlphaArgs(49) )
      IF (TESCoil(item)%DischargeOnlyCapFTempCurve == 0) THEN
        IF (lAlphaFieldBlanks(49)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(49))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(49))//'="'//TRIM(cAlphaArgs(49))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%DischargeOnlyCapFTempCurve) )
        CASE (CurveType_BiCubic, CurveType_BiQuadratic, CurveType_QuadraticLinear, CurveType_TableTwoIV)
          TESCoil(item)%DischargeOnlyCapFTempObjectNum = &
                     GetCurveObjectTypeNum(TESCoil(item)%DischargeOnlyCapFTempCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(49))//'="'//TRIM(cAlphaArgs(49))//'".')
          CALL ShowContinueError('Choose a curve or table with two independent variables, x and y.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%DischargeOnlyCapFFlowCurve = GetCurveIndex( cAlphaArgs(50) )
      IF (TESCoil(item)%DischargeOnlyCapFFlowCurve == 0) THEN
        IF (lAlphaFieldBlanks(50)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(50))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(50))//'="'//TRIM(cAlphaArgs(50))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%DischargeOnlyCapFFlowCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%DischargeOnlyCapFFlowObjectNum = &
                        GetCurveObjectTypeNum(TESCoil(item)%DischargeOnlyCapFFlowCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(50))//'="'//TRIM(cAlphaArgs(50))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%DischargeOnlyEIRFTempCurve = GetCurveIndex( cAlphaArgs(51) )
      IF (TESCoil(item)%DischargeOnlyEIRFTempCurve == 0) THEN
        IF (lAlphaFieldBlanks(51)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(51))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(51))//'="'//TRIM(cAlphaArgs(51))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%DischargeOnlyEIRFTempCurve) )
        CASE (CurveType_BiCubic, CurveType_BiQuadratic, CurveType_QuadraticLinear, CurveType_TableTwoIV)
          TESCoil(item)%DischargeOnlyEIRFTempObjectNum = &
                     GetCurveObjectTypeNum(TESCoil(item)%DischargeOnlyEIRFTempCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(51))//'="'//TRIM(cAlphaArgs(51))//'".')
          CALL ShowContinueError('Choose a curve or table with two independent variables, x and y.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%DischargeOnlyEIRFFlowCurve = GetCurveIndex( cAlphaArgs(52) )
      IF (TESCoil(item)%DischargeOnlyEIRFFlowCurve == 0) THEN
        IF (lAlphaFieldBlanks(52)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(52))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(52))//'="'//TRIM(cAlphaArgs(52))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%DischargeOnlyEIRFFlowCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%DischargeOnlyEIRFFlowObjectNum = &
                        GetCurveObjectTypeNum(TESCoil(item)%DischargeOnlyEIRFFlowCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(52))//'="'//TRIM(cAlphaArgs(52))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%DischargeOnlyPLFFPLRCurve = GetCurveIndex( cAlphaArgs(53) )
      IF (TESCoil(item)%DischargeOnlyPLFFPLRCurve == 0) THEN
        IF (lAlphaFieldBlanks(53)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(53))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(53))//'="'//TRIM(cAlphaArgs(53))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%DischargeOnlyPLFFPLRCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%DischargeOnlyPLFFPLRObjectNum = &
                        GetCurveObjectTypeNum(TESCoil(item)%DischargeOnlyPLFFPLRCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(53))//'="'//TRIM(cAlphaArgs(53))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%DischargeOnlySHRFTempCurve = GetCurveIndex( cAlphaArgs(54) )
      IF (TESCoil(item)%DischargeOnlySHRFTempCurve == 0) THEN
        IF (lAlphaFieldBlanks(54)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(54))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(54))//'="'//TRIM(cAlphaArgs(54))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%DischargeOnlySHRFTempCurve) )
        CASE (CurveType_BiCubic, CurveType_BiQuadratic, CurveType_QuadraticLinear, CurveType_TableTwoIV, &
                 CurveType_TriQuadratic, CurveType_TableMultiIV)
          TESCoil(item)%DischargeOnlySHRFTempObjectNum = &
                     GetCurveObjectTypeNum(TESCoil(item)%DischargeOnlySHRFTempCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(54))//'="'//TRIM(cAlphaArgs(54))//'".')
          CALL ShowContinueError('Choose a curve or table with two or three independent variables')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
      TESCoil(item)%DischargeOnlySHRFFLowCurve = GetCurveIndex( cAlphaArgs(55) )
      IF (TESCoil(item)%DischargeOnlySHRFFLowCurve == 0) THEN
        IF (lAlphaFieldBlanks(55)) THEN
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Required '//TRIM(cAlphaFieldNames(55))//'is blank.')
        ELSE
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError('Not found '//TRIM(cAlphaFieldNames(55))//'="'//TRIM(cAlphaArgs(55))//'".')
        ENDIF
        ErrorsFound=.TRUE.
      ELSE
        ! Verify Curve Object, any curve with just x as single independent variable
        SELECT CASE( GetCurveObjectTypeNum(TESCoil(item)%DischargeOnlySHRFFLowCurve) )
        CASE (CurveType_Linear, CurveType_Quadratic, CurveType_Cubic, CurveType_Quartic,&
              CurveType_Exponent, CurveType_TableOneIV, CurveType_ExponentialSkewNormal, &
              CurveType_Sigmoid,CurveType_RectangularHyperbola1, CurveType_RectangularHyperbola2, &
              CurveType_ExponentialDecay, CurveType_DoubleExponentialDecay)
          TESCoil(item)%DischargeOnlySHRFFLowObjectNum = &
                        GetCurveObjectTypeNum(TESCoil(item)%DischargeOnlySHRFFLowCurve)
        CASE DEFAULT
          CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
          CALL ShowContinueError(TRIM(cAlphaFieldNames(55))//'="'//TRIM(cAlphaArgs(55))//'".')
          CALL ShowContinueError('Choose a curve or table with one independent variable, x.')
          ErrorsFound=.TRUE.
        END SELECT
      ENDIF
    ENDIF ! Discharge Only mode available
    TESCoil(item)%AncillaryControlsPower      = rNumericArgs(31)
    TESCoil(item)%ColdWeatherMinimumTempLimit = rNumericArgs(32)
    TESCoil(item)%ColdWeatherAncillaryPower   = rNumericArgs(33)
    TESCoil(item)%CondAirInletNodeNum = GetOnlySingleNode(cAlphaArgs(56),ErrorsFound, &
                         TRIM(cCurrentModuleObject),TESCoil(item)%Name, &
                         NodeType_Air,NodeConnectionType_OutsideAirReference,1,ObjectIsNotParent)
    TESCoil(item)%CondAirOutletNodeNum = GetOnlySingleNode(cAlphaArgs(57),ErrorsFound, &
                         TRIM(cCurrentModuleObject),TESCoil(item)%Name, &
                         NodeType_Air,NodeConnectionType_ReliefAir,1,ObjectIsNotParent)
    TESCoil(item)%CondenserAirVolumeFlow   = rNumericArgs(34)
    TESCoil(item)%CondenserAirFlowSizingFactor  = rNumericArgs(35)
    SELECT CASE ( cAlphaArgs(58) )
    CASE ('AIRCOOLED')
      TESCoil(item)%CondenserType = AirCooled
    CASE ('EVAPORATIVELYCOOLED')
      TESCoil(item)%CondenserType = EvapCooled
    CASE DEFAULT
      CALL ShowSevereError(RoutineName//TRIM(cCurrentModuleObject)//'="'//TRIM(TESCoil(item)%Name)//'", invalid')
      CALL ShowContinueError(TRIM(cAlphaFieldNames(58))//'="'//TRIM(cAlphaArgs(58))//'".')
      CALL ShowContinueError('Available choices are AirCooled or EvaporativelyCooled.')
      ErrorsFound=.TRUE.
    END SELECT
    TESCoil(item)%EvapCondEffect            = rNumericArgs(36)
    TESCoil(item)%EvapCondPumpElecNomPower  = rNumericArgs(37)
    TESCoil(item)%BasinHeaterPowerFTempDiff = rNumericArgs(38)
    TESCoil(item)%BasinHeaterSetpointTemp   = rNumericArgs(39)
    IF (lAlphaFieldBlanks(59)) THEN
      TESCoil(item)%BasinHeaterAvailSchedNum = ScheduleAlwaysOn
    ELSE
      TESCoil(item)%BasinHeaterAvailSchedNum = GetScheduleIndex(cAlphaArgs(59))
      IF (TESCoil(item)%BasinHeaterAvailSchedNum == 0) THEN
        CALL ShowSevereError(RoutineName//trim(cCurrentModuleObject)//'="'//trim(TESCoil(item)%Name)//'", invalid')
        CALL ShowContinueError('...'//TRIM(cAlphaFieldNames(59))//'="'//TRIM(cAlphaArgs(59))//'".')
        ErrorsFound=.TRUE.
      ENDIF
    ENDIF
    IF (lAlphaFieldBlanks(60)) THEN
      TESCoil(item)%EvapWaterSupplyMode = WaterSupplyFromMains
    ELSE
      TESCoil(item)%EvapWaterSupplyName = cAlphaArgs(60)
      TESCoil(item)%EvapWaterSupplyMode = WaterSupplyFromTank
      CALL SetupTankDemandComponent(TESCoil(item)%Name,TRIM(cCurrentModuleObject), &
                 TESCoil(item)%EvapWaterSupplyName, ErrorsFound, TESCoil(item)%EvapWaterSupTankID, &
                 TESCoil(item)%EvapWaterTankDemandARRID )
    ENDIF
    IF (lAlphaFieldBlanks(61)) THEN
      TESCoil(item)%CondensateCollectMode  = CondensateDiscarded
    ELSE
      TESCoil(item)%CondensateCollectName = cAlphaArgs(61)
      TESCoil(item)%CondensateCollectMode = CondensateToTank
      CALL SetupTankSupplyComponent(TESCoil(item)%Name,TRIM(cCurrentModuleObject), &
                 TESCoil(item)%CondensateCollectName, ErrorsFound, TESCoil(item)%CondensateTankID, &
                 TESCoil(item)%CondensateTankSupplyARRID )
    ENDIF
    IF (.NOT. lAlphaFieldBlanks(62)) THEN
      TESCoil(item)%TESPlantInletNodeNum =  &
               GetOnlySingleNode(cAlphaArgs(62),ErrorsFound,TRIM(cCurrentModuleObject),cAlphaArgs(1),NodeType_Water, &
               NodeConnectionType_Inlet, 2, ObjectIsNotParent)
      TESCoil(item)%TESPlantConnectionAvailable = .TRUE.
    ELSE
      TESCoil(item)%TESPlantConnectionAvailable = .FALSE.
    ENDIF
    IF (.NOT. lAlphaFieldBlanks(63)) THEN
      TESCoil(item)%TESPlantOutletNodeNum =  &
               GetOnlySingleNode(cAlphaArgs(63),ErrorsFound,TRIM(cCurrentModuleObject),cAlphaArgs(1),NodeType_Water, &
               NodeConnectionType_Outlet, 2, ObjectIsNotParent)
    ELSE
      IF (TESCoil(item)%TESPlantConnectionAvailable) THEN
        CALL ShowSevereError(RoutineName//trim(cCurrentModuleObject)//'="'//trim(TESCoil(item)%Name)//'", invalid')
        CALL ShowContinueError('...'//TRIM(cAlphaFieldNames(63))//' cannot be blank.')
        ErrorsFound=.TRUE.
      ENDIF
    ENDIF
    IF (TESCoil(item)%TESPlantConnectionAvailable) THEN
      CALL TestCompSet(TRIM(cCurrentModuleObject),cAlphaArgs(1),cAlphaArgs(62),  cAlphaArgs(63),'Water Nodes')
    ENDIF
    IF (.NOT. lNumericFieldBlanks(40) ) THEN
      TESCoil(item)%TESPlantDesignVolumeFlowRate = rNumericArgs(40)
    ENDIF
    IF (.NOT. lNumericFieldBlanks(41) ) THEN
      TESCoil(item)%TESPlantEffectiveness = rNumericArgs(41)
    ENDIF
    IF (TESCoil(item)%StorageMedia == FluidBased)  THEN
      IF (.NOT. lNumericFieldBlanks(42) ) THEN
        TESCoil(item)%MinimumFluidTankTempLimit = rNumericArgs(42)
      ELSE
        Call GetFluidDensityTemperatureLimits(TESCoil(item)%StorageFluidIndex, TminRho, TmaxRho)
        CALL GetFluidSpecificHeatTemperatureLimits(TESCoil(item)%StorageFluidIndex, TminCp, TmaxCp)
        TESCoil(item)%MinimumFluidTankTempLimit = MAX(TminRho, TminCp)
      ENDIF
      IF (.NOT. lNumericFieldBlanks(43) ) THEN
        TESCoil(item)%MaximumFluidTankTempLimit = rNumericArgs(43)
      ELSE
        Call GetFluidDensityTemperatureLimits(TESCoil(item)%StorageFluidIndex, TminRho, TmaxRho)
        CALL GetFluidSpecificHeatTemperatureLimits(TESCoil(item)%StorageFluidIndex, TminCp, TmaxCp)
        TESCoil(item)%MaximumFluidTankTempLimit = MIN(TmaxRho, TmaxCp)
      ENDIF
    ENDIF
  ENDDO
  IF (ErrorsFound) THEN
    CALL ShowFatalError(RoutineName//'Errors found in getting '//TRIM(cCurrentModuleObject)//' input. '//&
                        'Preceding condition(s) causes termination.')
  END IF
  ! setup reporting
  DO item = 1, NumTESCoils
    CALL SetupOutputVariable('Cooling Coil Operating Mode Index []', &
                                    TESCoil(item)%CurControlMode, 'System', 'Average', TESCoil(item)%Name)
    CALL SetupOutputVariable('Cooling Coil Total Cooling Rate [W]', &
                                    TESCoil(item)%EvapTotCoolingRate, 'System', 'Average', TESCoil(item)%Name)
    CALL SetupOutputVariable('Cooling Coil Total Cooling Energy [J]', &
                                    TESCoil(item)%EvapTotCoolingEnergy, 'System', 'Sum', TESCoil(item)%Name, &
                                    ResourceTypeKey='ENERGYTRANSFER',EndUseKey='COOLINGCOILS',GroupKey='System')
    CALL SetupOutputVariable('Cooling Coil Sensible Cooling Rate [W]', &
                                    TESCoil(item)%EvapSensCoolingRate, 'System', 'Average', TESCoil(item)%Name)
    CALL SetupOutputVariable('Cooling Coil Sensible Cooling Energy [J]', &
                                    TESCoil(item)%EvapSensCoolingEnergy, 'System', 'Sum', TESCoil(item)%Name)
    CALL SetupOutputVariable('Cooling Coil Latent Cooling Rate [W]', &
                                    TESCoil(item)%EvapLatCoolingRate, 'System', 'Average', TESCoil(item)%Name)
    CALL SetupOutputVariable('Cooling Coil Latent Cooling Energy [J]', &
                                    TESCoil(item)%EvapLatCoolingEnergy, 'System', 'Sum', TESCoil(item)%Name)
    CALL SetupOutputVariable('Cooling Coil Electric Power [W]', &
                                    TESCoil(item)%ElecCoolingPower, 'System', 'Average', TESCoil(item)%Name)
    CALL SetupOutputVariable('Cooling Coil Electric Energy [J]', &
                                    TESCoil(item)%ElecCoolingEnergy, 'System', 'Sum', TESCoil(item)%Name, &
                                    ResourceTypeKey='Electric',EndUseKey='COOLING',GroupKey='System')
    CALL SetupOutputVariable('Cooling Coil Runtime Fraction []', &
                                    TESCoil(item)%RuntimeFraction, 'System', 'Average', TESCoil(item)%Name)
    CALL SetupOutputVariable('Cooling Coil Cold Weather Protection Electric Energy [J]', &
                                    TESCoil(item)%ElectColdWeatherEnergy, 'System','Sum',TESCoil(item)%Name, &
                                    ResourceTypeKey='Electric',EndUseKey='COOLING',EndUseSubKey='Thermal Protection', &
                                    GroupKey='System')
    CALL SetupOutputVariable('Cooling Coil Cold Weather Protection Electric Power [W]', &
                                    TESCoil(item)%ElectColdWeatherPower, 'System', 'Average', TESCoil(item)%Name)
    CALL SetupOutputVariable('Cooling Coil Thermal Storage Mechanical Heat Transfer Rate [W]', &
                                    TESCoil(item)%QdotTES, 'System', 'Average', TESCoil(item)%Name)
    CALL SetupOutputVariable('Cooling Coil Thermal Storage Mechanical Heat Transfer Energy [J]', &
                                    TESCoil(item)%Q_TES, 'System', 'Sum', TESCoil(item)%Name)
    CALL SetupOutputVariable('Cooling Coil Thermal Storage Ambient Heat Transfer Rate [W]', &
                                    TESCoil(item)%QdotAmbient, 'System', 'Average', TESCoil(item)%Name)
    CALL SetupOutputVariable('Cooling Coil Thermal Storage Ambient Heat Transfer Energy [J]', &
                                    TESCoil(item)%Q_Ambient, 'System', 'Sum', TESCoil(item)%Name)
    IF (TESCoil(item)%TESPlantConnectionAvailable) THEN
      CALL SetupOutputVariable('Cooling Coil Thermal Storage Plant Heat Transfer Rate [W]', &
                                    TESCoil(item)%QdotPlant, 'System', 'Average', TESCoil(item)%Name)
      CALL SetupOutputVariable('Cooling Coil Thermal Storage Plant Heat Transfer Energy [J]', &
                                    TESCoil(item)%Q_Plant, 'System', 'Sum', TESCoil(item)%Name)
    ENDIF
    IF (TESCoil(item)%CondenserType == EvapCooled) THEN
      CALL SetupOutputVariable('Cooling Coil Condenser Inlet Temperature [C]', &
                               TESCoil(item)%CondInletTemp,'System','Average',  TESCoil(item)%Name)
      IF (TESCoil(item)%EvapWaterSupplyMode == WaterSupplyFromMains) THEN
        CALL SetupOutputVariable('Cooling Coil Evaporative Condenser Water Volume [m3]',TESCoil(item)%EvapWaterConsump, &
                                 'System','Sum',TESCoil(item)%Name, &
                                  ResourceTypeKey='Water',EndUseKey='Cooling',GroupKey='System')
        CALL SetupOutputVariable('Cooling Coil Evaporative Condenser Mains Supply Water Volume [m3]',  &
                                  TESCoil(item)%EvapWaterConsump, &
                                 'System','Sum',TESCoil(item)%Name, &
                                  ResourceTypeKey='MainsWater',EndUseKey='Cooling',GroupKey='System')
      ELSEIF (TESCoil(item)%EvapWaterSupplyMode == WaterSupplyFromTank) THEN
        CALL SetupOutputVariable('Cooling Coil Evaporative Condenser Storage Tank Water Volume [m3]',&
                            TESCoil(item)%EvapWaterConsump, &
                            'System','Sum',TESCoil(item)%Name, &
                             ResourceTypeKey='Water',EndUseKey='Cooling' , GroupKey='System')
        CALL SetupOutputVariable('Cooling Coil Evaporative Condenser Starved Water Volume [m3]', &
                             TESCoil(item)%EvapWaterStarvMakup, &
                            'System','Sum',TESCoil(item)%Name, &
                             ResourceTypeKey='Water',EndUseKey='Cooling', GroupKey='System')
        CALL SetupOutputVariable('Cooling Coil Evaporative Condenser Starved Mains Water Volume [m3]',&
                             TESCoil(item)%EvapWaterStarvMakup, &
                            'System','Sum',TESCoil(item)%Name, &
                             ResourceTypeKey='MainsWater',EndUseKey='Cooling', GroupKey='System')
      ENDIf
      CALL SetupOutputVariable('Cooling Coil Evaporative Condenser Pump Electric Power [W]',TESCoil(item)%EvapCondPumpElecPower, &
                               'System','Average',TESCoil(item)%Name)
      CALL SetupOutputVariable('Cooling Coil Evaporative Condenser Pump Electric Energy [J]', &
                                TESCoil(item)%EvapCondPumpElecConsumption,'System','Sum',TESCoil(item)%Name, &
                                ResourceTypeKey='Electric',EndUseKey='COOLING',GroupKey='System')
      CALL SetupOutputVariable('Cooling Coil Basin Heater Electric Power [W]', &
                                    TESCoil(item)%ElectEvapCondBasinHeaterPower, 'System','Average',TESCoil(item)%Name)
      CALL SetupOutputVariable('Cooling Coil Basin Heater Electric Energy [J]', &
                                    TESCoil(item)%ElectEvapCondBasinHeaterEnergy, 'System','Sum',TESCoil(item)%Name, &
                                    ResourceTypeKey='Electric',EndUseKey='COOLING',EndUseSubKey='Thermal Protection', &
                                    GroupKey='System')
    ENDIF
    IF (TESCoil(item)%StorageMedia == FluidBased) THEN
      CALL SetupOutputVariable('Cooling Coil Fluid Thermal Storage End Temperature [C]', &
                                    TESCoil(item)%FluidTankTempFinal, 'System','Average',TESCoil(item)%Name)
    ELSEIF (TESCoil(item)%StorageMedia == IceBased) THEN
      CALL SetupOutputVariable('Cooling Coil Ice Thermal Storage End Fraction []', &
                                    TESCoil(item)%IceFracRemain, 'System','Average',TESCoil(item)%Name)
    ENDIF
  ENDDO
  IF (AnyEnergyManagementSystemInModel) THEN
    DO item = 1, NumTESCoils
    ! setup EMS actuator for control mode
      CALL SetupEMSActuator('Coil:Cooling:DX:SingleSpeed:ThermalStorage', TESCoil(item)%Name, &
                            'Operating Mode' , '[ ]', &
                            TESCoil(item)%EMSControlModeOn, &
                            TESCoil(item)%EMSControlModeValue )
    ENDDO
  ENDIF
  RETURN
END SUBROUTINE GetTESCoilInput
All Procedures
AbortEnergyPlus AbsoluteAirMass ActivateDemandManagers ActivateEMSControls AddBlankKeys addChargesToOperand AddCompSizeTableEntry AddEndUseSubcategory AddError addFootNoteSubTable AddInstruction AddMeter addMonthlyCharge AddMonthlyFieldSetInput AddMonthlyReport AddNeighborInformation AddObjectDefandParse addOperand AddRecordFromSection AddRecordToOutputVariableStructure AddSectionDef AddShadowRelateTableEntry AddSQLiteComponentSizingRecord AddSQLiteComponentSizingRecord AddSQLiteSystemSizingRecord AddSQLiteSystemSizingRecord AddSQLiteZoneSizingRecord AddSQLiteZoneSizingRecord AddTOCEntry AddTOCZoneLoadComponentTable AddToOutputVariableList AddVariablesForMonthlyReport AddVariableSlatBlind AddWindow AdjustAirSetpointsforOpTempCntrl AdjustCBF AdjustCBF AdjustChangeInLoadByEMSControls AdjustChangeInLoadByHowServed AdjustChangeInLoadForLastStageUpperRangeLimit AdjustCoolingSetPointforTempAndHumidityControl adjusthhat AdjustPumpFlowRequestByEMSControls AdjustReportingHourAndMinutes AdjustVBGap AdvanceRootFinder AFECFR AFECOI AFECPD AFECPF AFEDMP AFEDOP AFEDWC AFEELR AFEEXF AFEFAN AFEHEX AFEHOP AFEPLR AFESCR AFESEL AFESOP AFETMU AirflowNetworkVentingControl AirMass AIRMOV AllocateAirflowNetworkData AllocateAirHeatBalArrays AllocateAndInitData AllocateAndSetUpVentReports AllocateCFSStateHourlyData AllocateForCFSRefPointsGeometry AllocateForCFSRefPointsState AllocateHeatBalArrays AllocateLoadComponentArrays AllocateModuleArrays AllocateModuleArrays AllocateSurfaceHeatBalArrays AllocateWeatherData angle_2dvector AnisoSkyViewFactors AnyPlantLoopSidesNeedSim AnyPlantSplitterMixerLacksContinuity AreaPolygon ArgCheck array_to_vector ASHRAETauModel ASHWAT_OffNormalProperties ASHWAT_Solar ASHWAT_Thermal ASSIGNMENT (=) AssignNodeNumber AssignReportNumber AssignResourceTypeNum AssignReverseConstructionNumber AssignVariablePt AttachCustomMeters AttachMeters AuditBranches AUTOTDMA BaseThermalPropertySet_Diffusivity BeginEnvrnInitializeRuntimeLanguage BetweenDates BetweenGlassForcedFlow BetweenGlassShadeForcedFlow BetweenGlassShadeNaturalFlow BisectionMethod BlindBeamBeamTrans BlindOpticsBeam BlindOpticsDiffuse BoreholeResistance BoundValueToNodeMinMaxAvail BoundValueToWithinTwoValues BracketRoot BranchPressureDrop BrentMethod BuildGap BuildKeyVarList Calc4PipeFanCoil Calc_EN673 Calc_ISO15099 CalcActiveTranspiredCollector CalcAggregateLoad CalcAirflowNetworkAirBalance CalcAirflowNetworkCO2Balance CalcAirflowNetworkGCBalance CalcAirflowNetworkHeatBalance CalcAirflowNetworkMoisBalance CalcAirFlowSimple CalcAirLoopSplitter CalcAirMixer CalcAirToAirGenericHeatExch CalcAirToAirPlateHeatExch CalcAirZoneReturnPlenum CalcAirZoneSupplyPlenum CalcAlamdariHammondStableHorizontal CalcAlamdariHammondUnstableHorizontal CalcAlamdariHammondVerticalWall CalcAngleFactorMRT CalcApproximateViewFactors CalcASHRAEDetailedIntConvCoeff CalcASHRAESimpExtConvectCoeff CalcASHRAESimpleIntConvCoeff CalcASHRAEVerticalWall CalcATMixer CalcAwbiHattonHeatedFloor CalcAwbiHattonHeatedWall CalcBasinHeaterPower CalcBasinHeaterPowerForMultiModeDXCoil CalcBeamSolarOnWinRevealSurface CalcBeamSolDiffuseReflFactors CalcBeamSolSpecularReflFactors CalcBeausoleilMorrisonMixedAssistedWall CalcBeausoleilMorrisonMixedOpposingWall CalcBeausoleilMorrisonMixedStableCeiling CalcBeausoleilMorrisonMixedStableFloor CalcBeausoleilMorrisonMixedUnstableCeiling CalcBeausoleilMorrisonMixedUnstableFloor CalcBLASTAbsorberModel CalcBlockenWindward CalcBoilerModel CalcBoilerModel CalcBottomFluxCoefficents CalcBottomSurfTemp CalcBuriedPipeSoil CalcCBF CalcCBF CalcCBVAV CalcCeilingDiffuserInletCorr CalcCeilingDiffuserIntConvCoeff CalcChillerHeaterModel CalcChillerIPLV CalcChillerModel CalcClearRoof CalcCoilUAbyEffectNTU CalcColdestSetPoint CalcComplexWindowOverlap CalcComplexWindowThermal CalcCompSuctionTempResidual CalcCondEntSetPoint CalcConnectionsDrainTemp CalcConnectionsFlowRates CalcConnectionsHeatRecovery CalcConstCOPChillerModel CalcConvCoeffAbsPlateAndWater CalcConvCoeffBetweenPlates CalcCoolBeam CalcCoolTower CalcCoordinateTransformation CalcCoPlanarNess CalcCostEstimate CalcCTGeneratorModel CalcDayltgCoefficients CalcDayltgCoeffsMapPoints CalcDayltgCoeffsRefMapPoints CalcDayltgCoeffsRefPoints CalcDesiccantBalancedHeatExch CalcDesignSpecificationOutdoorAir CalcDesuperheaterHeatingCoil CalcDesuperheaterWaterHeater CalcDetailedHcInForDVModel CalcDetailedSystem CalcDetailedTransSystem CalcDetailFlatFinCoolingCoil CalcDetIceStorLMTDstar CalcDiffTSysAvailMgr CalcDirectAir CalcDirectEvapCooler CalcDirectResearchSpecialEvapCooler CalcDoe2DXCoil CalcDOE2Leeward CalcDOE2Windward CalcDryFinEffCoef CalcDryIndirectEvapCooler CalcDuct CalcDXCoilStandardRating CalcDXHeatingCoil CalcEarthTube CalcEcoRoof CalcEffectiveness CalcEffectiveSHR CalcEffectiveSHR CalcEffectiveSHR CalcEffectiveSHR CalcElecSteamHumidifier CalcElectricBaseboard CalcElectricChillerHeatRecovery CalcElectricChillerModel CalcElectricEIRChillerModel CalcElectricHeatingCoil CalcEmmelRoof CalcEmmelVertical CalcEngineChillerHeatRec CalcEngineDrivenChillerModel CalcEQLOpticalProperty CalcEQLWindowOpticalProperty CalcEQLWindowSHGCAndTransNormal CalcEQLWindowStandardRatings CalcEQLWindowUvalue CalcEquipmentDrainTemp CalcEquipmentFlowRates CalcExhaustAbsorberChillerModel CalcExhaustAbsorberHeaterModel CalcExteriorVentedCavity CalcFisherPedersenCeilDiffuserCeiling CalcFisherPedersenCeilDiffuserFloor CalcFisherPedersenCeilDiffuserWalls CalcFluidHeatExchanger CalcFohannoPolidoriVerticalWall CalcFollowOATempSetPoint CalcFollowSysNodeTempSetPoint CalcFourPipeIndUnit CalcFrameDividerShadow CalcFuelCellAuxHeater CalcFuelCellGeneratorModel CalcFuelCellGenHeatRecovery CalcFurnaceOutput CalcFurnaceResidual CalcGasAbsorberChillerModel CalcGasAbsorberHeaterModel CalcGasCooler CalcGasHeatingCoil CalcGenericDesiccantDehumidifier CalcGoldsteinNovoselacCeilingDiffuserFloor CalcGoldsteinNovoselacCeilingDiffuserWall CalcGoldsteinNovoselacCeilingDiffuserWindow CalcGroundTempSetPoint CalcGroundwaterWell CalcGshpModel CalcGshpModel CalcGTChillerModel CalcHeatBalanceAir CalcHeatBalanceInsideSurf CalcHeatBalanceInsideSurf CalcHeatBalanceOutsideSurf CalcHeatBalanceOutsideSurf CalcHeatBalFiniteDiff CalcHeatBalHAMT CalcHeatPumpWaterHeater CalcHeatTransCoeffAndCoverTemp CalcHfExteriorSparrow CalcHighTempRadiantSystem CalcHighTempRadiantSystemSP CalcHiTurnOffSysAvailMgr CalcHiTurnOnSysAvailMgr CalcHnASHRAETARPExterior CalcHPCoolingSimple CalcHPHeatingSimple CalcHPWHDXCoil CalcHWBaseboard CalcHXAssistedCoolingCoil CalcHXEffectTerm CalcHybridVentSysAvailMgr CalcIBesselFunc CalcICEngineGeneratorModel CalcICEngineGenHeatRecovery CalcIceStorageCapacity CalcIceStorageCharge CalcIceStorageDischarge CalcIceStorageDormant CalcICSSolarCollector CalcIdealCondEntSetPoint CalcIfSetpointMet CalcIndirectAbsorberModel CalcIndirectResearchSpecialEvapCooler CalcInteriorRadExchange CalcInteriorSolarDistribution CalcInteriorSolarOverlaps CalcInteriorWinTransDifSolInitialDistribution CalcISO15099WindowIntConvCoeff CalcKaradagChilledCeiling CalcKBesselFunc CalcKhalifaEq3WallAwayFromHeat CalcKhalifaEq4CeilingAwayFromHeat CalcKhalifaEq5WallsNearHeat CalcKhalifaEq6NonHeatedWalls CalcKhalifaEq7Ceiling CalcLoadCenterThermalLoad CalcLoTurnOffSysAvailMgr CalcLoTurnOnSysAvailMgr CalcLowTempCFloRadiantSystem CalcLowTempCFloRadSysComps CalcLowTempElecRadiantSystem CalcLowTempHydrRadiantSystem CalcLowTempHydrRadSysComps CalcMatrixInverse CalcMcAdams CalcMerkelVariableSpeedTower CalcMicroCHPNoNormalizeGeneratorModel CalcMinIntWinSolidAngs CalcMitchell CalcMixedAirSetPoint CalcMoistureBalanceEMPD CalcMoreNodeInfo CalcMoWITTLeeward CalcMoWITTWindward CalcMSHeatPump CalcMTGeneratorModel CalcMultiSpeedDXCoil CalcMultiSpeedDXCoilCooling CalcMultiSpeedDXCoilHeating CalcMultiStageElectricHeatingCoil CalcMultiStageGasHeatingCoil CalcMultiZoneAverageCoolingSetPoint CalcMultiZoneAverageHeatingSetPoint CalcMultiZoneAverageMaxHumSetPoint CalcMultiZoneAverageMinHumSetPoint CalcMultiZoneMaxHumSetPoint CalcMultiZoneMinHumSetPoint CalcMundtModel CalcNCycSysAvailMgr CalcNewZoneHeatCoolFlowRates CalcNewZoneHeatOnlyFlowRates CalcNodeMassFlows CalcNominalWindowCond CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNusselt CalcNusseltJurges CalcNVentSysAvailMgr CalcOAController CalcOAMassFlow CalcOAMassFlow CalcOAMixer CalcOAOnlyMassFlow CalcOAPretreatSetPoint CalcOAUnitCoilComps CalcObstrMultiplier CalcOptStartSysAvailMgr CalcOtherSideDemand CalcOutdoorAirUnit CalcOutsideAirSetPoint CalcOutsideSurfTemp CalcParallelPIU CalcPassiveExteriorBaffleGap CalcPassiveSystem CalcPassiveTranspiredCollector CalcPerSolarBeam CalcPipeHeatTransCoef CalcPipesHeatTransfer CalcPipeTransBeam CalcPlantValves CalcPollution CalcPolyhedronVolume CalcPolynomCoef CalcPondGroundHeatExchanger CalcPredictedHumidityRatio CalcPredictedSystemLoad CalcPTUnit CalcPumps CalcPurchAirLoads CalcPurchAirMinOAMassFlow CalcPurchAirMixedAir CalcPVTcollectors CalcQiceChargeMaxByChiller CalcQiceChargeMaxByITS CalcQiceDischageMax CalcRABFlowSetPoint CalcRackSystem CalcRadSysHXEffectTerm CalcRadTemp CalcRainCollector CalcReformEIRChillerModel CalcResearchSpecialPartLoad CalcReturnAirPath CalcRfFlrCoordinateTransformation CalcSandiaPV CalcSatVapPressFromTemp CalcSchedOffSysAvailMgr CalcSchedOnSysAvailMgr CalcSchedSysAvailMgr CalcScheduledDualSetPoint CalcScheduledSetPoint CalcScreenTransmittance CalcScriptF CalcSeriesPIU CalcSetpointTempTarget CalcSHRUserDefinedCurves CalcSimpleController CalcSimpleHeatingCoil CalcSimplePV CalcSingleSpeedEvapFluidCooler CalcSingleSpeedTower CalcSingZoneClSetPoint CalcSingZoneHtSetPoint CalcSingZoneMaxHumSetPoint CalcSingZoneMinHumSetPoint CalcSingZoneRhSetPoint CalcSkySolDiffuseReflFactors CalcSolarCollector CalcSolarFlux CalcSolidDesiccantDehumidifier CalcSourceFlux CalcSourceTempCoefficents CalcSparrowLeeward CalcSparrowWindward CalcSpecialDayTypes CalcStandAloneERV CalcStandardRatings CalcStaticProperties CalcSteamAirCoil CalcSteamBaseboard CalcSurfaceCentroid CalcSurfaceGroundHeatExchanger CalcSystemEnergyUse CalcSZOneStageCoolingSetPt CalcSZOneStageHeatingSetPt CalcTankTemp CalcTDDTransSolAniso CalcTDDTransSolHorizon CalcTDDTransSolIso CalcTempDistModel CalcTempIntegral CalcTESCoilChargeOnlyMode CalcTESCoilCoolingAndChargeMode CalcTESCoilCoolingAndDischargeMode CalcTESCoilCoolingOnlyMode CalcTESCoilDischargeOnlyMode CalcTESCoilOffMode CalcTESIceStorageTank CalcTESWaterStorageTank CalcThermalChimney CalcThermalComfortAdaptiveASH55 CalcThermalComfortAdaptiveCEN15251 CalcThermalComfortFanger CalcThermalComfortKSU CalcThermalComfortPierce CalcThermalComfortSimpleASH55 CalcTimeNeeded CalcTopFluxCoefficents CalcTopSurfTemp CalcTotalFLux CalcTotCapSHR CalcTotCapSHR_VSWSHP CalcTransAbsorProduct CalcTransRefAbsOfCover CalcTRNSYSPV CalcTrombeWallIntConvCoeff CalcTwoSpeedDXCoilIEERResidual CalcTwoSpeedDXCoilStandardRating CalcTwoSpeedEvapFluidCooler CalcTwoSpeedTower CalcUAIce CalcUCSDCV CalcUCSDDV CalcUCSDUE CalcUCSDUI CalculateAirChillerSets CalculateBasisLength CalculateCase CalculateCoil CalculateCompressors CalculateCondensers CalculateCTFs CalculateDailySolarCoeffs CalculateDayOfWeek CalculateEpsFromNTUandZ CalculateExponentialMatrix CalculateFuncResults CalculateGammas CalculateInverseMatrix CalculateMoodyFrictionFactor CalculateNTUfromEpsAndZ CalculatePollution CalculateSecondary CalculateSubcoolers CalculateSunDirectionCosines CalculateTransCompressors CalculateWalkIn CalculateWaterUseage CalculateWaterUseage CalculateWindowBeamProperties CalculateZoneMRT CalculateZoneVolume CalcUnitaryCoolingSystem CalcUnitaryHeatingSystem CalcUnitarySuppHeatingSystem CalcUnitarySuppSystemtoSP CalcUnitarySystemLoadResidual CalcUnitarySystemToLoad CalcUnitHeater CalcUnitHeaterComponents CalcUnitVentilator CalcUnitVentilatorComponents CalcUnmetPlantDemand CalcUpdateHeatRecovery CalcUpdateHeatRecovery CalcUserDefinedInsideHcModel CalcUserDefinedOutsideHcModel CalcVariableSpeedTower CalcVarSpeedCoilCooling CalcVarSpeedCoilHeating CalcVarSpeedHeatPump CalcVarSpeedHeatPump CalcVAVVS CalcVentilatedSlab CalcVentilatedSlabComps CalcVentilatedSlabRadComps CalcVentSlabHXEffectTerm CalcVerticalGroundHeatExchanger CalcViewFactorToShelf CalcVRF CalcVRFCondenser CalcVRFCoolingCoil CalcVSTowerApproach CalcWallCoordinateTransformation CalcWaltonStableHorizontalOrTilt CalcWaltonUnstableHorizontalOrTilt CalcWarmestSetPoint CalcWarmestSetPointTempFlow CalcWaterMainsTemp CalcWaterSource CalcWaterStorageTank CalcWaterThermalTankMixed CalcWaterThermalTankStratified CalcWaterThermalTankZoneGains CalcWaterToAirHeatpump CalcWatertoAirHPCooling CalcWatertoAirHPHeating CalcWaterToAirResidual CalcWatertoWaterHPCooling CalcWatertoWaterHPHeating CalcWaterUseZoneGains CalcWetIndirectEvapCooler CalcWindowACOutput CalcWindowBlindProperties CalcWindowHeatBalance CalcWindowProfileAngles CalcWindowScreenProperties CalcWindowStaticProperties CalcWindPressure CalcWindPressureCoeffs CalcWindTurbine CalcWinFrameAndDividerTemps CalcWinTransDifSolInitialDistribution CalcWrapperModel CalcZoneAirComfortSetpoints CalcZoneAirTempSetpoints CalcZoneComponentLoadSums CalcZoneDehumidifier CalcZoneEvaporativeCoolerUnit CalcZoneLeavingConditions CalcZoneMassBalance CalcZonePipesHeatGain CalcZoneSums CartesianPipeCellInformation_ctor CellType_IsFieldCell CFSHasControlledShade CFSNGlz CFSRefPointPosFactor CFSRefPointSolidAngle CFSShadeAndBeamInitialization CFSUFactor cGetCoilAirOutletNode cGetCoilSteamInletNode cGetCoilSteamOutletNode CharPreDefTableEntry CheckActuatorNode CheckAndAddAirNodeNumber CheckAndFixCFSLayer CheckAndReadCustomSprectrumData CheckAndReadFaults CheckAndSetConstructionProperties CheckBracketRoundOff CheckBranchForOASys CheckCachedIPErrors CheckCFSStates CheckCoilWaterInletNode CheckControllerListOrder CheckControllerLists CheckConvexity CheckCostEstimateInput CheckCreatedZoneItemName CheckCurveLimitsForIPLV CheckCurveLimitsForStandardRatings CheckDayScheduleValueMinMax CheckDXCoolingCoilInOASysExists CheckFDSurfaceTempLimits CheckFFSchedule CheckFluidPropertyName CheckForActualFileName CheckForBalancedFlow CheckForControllerWaterCoil CheckForGeometricTransform CheckForGeometricTransform CheckForMisMatchedEnvironmentSpecifications CheckForOutOfRangeTempResult CheckForOutOfRangeTemps CheckForRequestedReporting CheckForRunawayPlantTemps CheckForSensorAndSetpointNode CheckGasCoefs CheckHeatingCoilSchedule CheckHXAssistedCoolingCoilSchedule CheckIFAnyEMS CheckIFAnyIdealCondEntSetPoint CheckIfAnyPlant CheckIfNodeSetpointManagedByEMS CheckIncrementRoundOff CheckInternalConsistency CheckLightsReplaceableMinMaxForZone CheckLocationValidity CheckLoopExitNode CheckLowerUpperBracket CheckMarkedNodes CheckMaxActiveController CheckMaxConstraint CheckMicroCHPThermalBalance CheckMinActiveController CheckMinConstraint checkMinimumMonthlyCharge CheckMinMaxCurveBoundaries CheckMinMaxRange CheckModelBoundOutput_HumRat CheckModelBoundOutput_Temp CheckModelBounds CheckModelBoundsHumRatEq CheckModelBoundsRH_HumRatEq CheckModelBoundsRH_TempEq CheckModelBoundsTempEq CheckNodeConnections CheckNodeSetPoint CheckNonSingularity CheckOAControllerName CheckOutAirNodeNumber CheckPlantConvergence CheckPlantMixerSplitterConsistency CheckPlantOnAbort CheckPollutionMeterReporting CheckRefrigerationInput CheckReportVariable CheckRootFinderCandidate CheckRootFinderConvergence CheckScheduledSurfaceGains CheckScheduleValue CheckScheduleValueMinMax Checksetpoints CheckSimpleController CheckSlope CheckSteamCoilSchedule CheckSubSurfaceMiscellaneous CheckSysSizing CheckSystemBranchFlow CheckTDDsAndLightShelvesInDaylitZones CheckThisAirSystemForSizing CheckThisZoneForSizing CheckThreading CheckUniqueNodes CheckUnitarySysCoilInOASysExists CheckUsedConstructions CheckValidSimulationObjects CheckWarmupConvergence CheckWaterCoilSchedule CheckWeatherFileValidity CheckWindowShadingControlFrameDivider CheckZoneEquipmentList CheckZoneSizing CHKBKS CHKGSS CHKSBS CLIP CLIPPOLY CloseDFSFile CloseMiscOpenFiles CloseMoistureBalanceEMPD CloseOutOpenFiles CloseOutputFiles CloseOutputTabularFile CloseReportIllumMaps CloseSocket CloseWeatherFile CoilAreaFracIter CoilCompletelyDry CoilCompletelyWet CoilOutletStreamCondition CoilPartWetPartDry COMMAND_ARGUMENT_COUNT CompactObjectsCheck CompareTwoVectors ComplexFenestrationLuminances ComputeDelayedComponents ComputeDifSolExcZonesWIZWindows ComputeIntSolarAbsorpFactors ComputeIntSWAbsorpFactors ComputeIntThermalAbsorpFactors ComputeLifeCycleCostAndReport ComputeLoadComponentDecayCurve ComputeNominalUwithConvCoeffs ComputePresentValue ComputeTariff ComputeTaxAndDepreciation ComputeWinShadeAbsorpFactors CondOutTempResidual ConstructBasis ControlCBVAVOutput ControlCompOutput ControlCompOutput ControlCoolBeam ControlCoolingSystem ControlCycWindACOutput ControlDesiccantDehumidifier ControlDXHeatingSystem ControlDXSystem ControlFluidHeatExchanger ControlHeatingSystem ControlHumidifier ControlMSHPOutput ControlPTUnitOutput ControlPVTcollector ControlReformEIRChillerModel ControlSuppHeatSystem ControlUnitarySystemOutput ControlUnitarySystemtoLoad ControlUnitarySystemtoSP ControlVRF ControlVSEvapUnitToMeetLoad ControlVSHPOutput ControlVSHPOutput ConvectionFactor ConvertCasetoLower ConvertCasetoUpper ConvertIP ConvertIPdelta ConvertToElementTag ConvertToEscaped CoolBeamResidual CoolingCoil CoolWaterHumRatResidual CoolWaterTempResidual CoolWatertoAirHPHumRatResidual CoolWatertoAirHPTempResidual CorrectZoneAirTemp CorrectZoneContaminants CorrectZoneHumRat CostInfoOut CPCW CPHW CreateBoundaryList CreateBoundaryListCount CreateCategoryNativeVariables CreateCellArray CreateCurrentDateTimeString CreateDefaultComputation CreateEnergyReportStructure CreateFCfactorConstructions CreateHVACStepFullString CreateHVACTimeIntervalString CreateHVACTimeString CreateNewellAreaVector CreateNewellSurfaceNormalVector CreatePartitionCenterList CreatePartitionRegionList CreatePredefinedMonthlyReports CreateRegionList CreateRegionListCount CreateShadedWindowConstruction CreateSQLiteConstructionsTable CreateSQLiteConstructionsTable CreateSQLiteDatabase CreateSQLiteDatabase CreateSQLiteDaylightMap CreateSQLiteDaylightMap CreateSQLiteDaylightMapTitle CreateSQLiteDaylightMapTitle CreateSQLiteEnvironmentPeriodRecord CreateSQLiteEnvironmentPeriodRecord CreateSQLiteErrorRecord CreateSQLiteErrorRecord CreateSQLiteInfiltrationTable CreateSQLiteInfiltrationTable CreateSQLiteMaterialsTable CreateSQLiteMaterialsTable CreateSQLiteMeterDictionaryRecord CreateSQLiteMeterDictionaryRecord CreateSQLiteMeterRecord CreateSQLiteMeterRecord CreateSQLiteNominalBaseboardHeatTable CreateSQLiteNominalBaseboardHeatTable CreateSQLiteNominalElectricEquipmentTable CreateSQLiteNominalElectricEquipmentTable CreateSQLiteNominalGasEquipmentTable CreateSQLiteNominalGasEquipmentTable CreateSQLiteNominalHotWaterEquipmentTable CreateSQLiteNominalHotWaterEquipmentTable CreateSQLiteNominalLightingTable CreateSQLiteNominalLightingTable CreateSQLiteNominalOtherEquipmentTable CreateSQLiteNominalOtherEquipmentTable CreateSQLiteNominalPeopleTable CreateSQLiteNominalPeopleTable CreateSQLiteNominalSteamEquipmentTable CreateSQLiteNominalSteamEquipmentTable CreateSQLiteReportVariableDataRecord CreateSQLiteReportVariableDataRecord CreateSQLiteReportVariableDictionaryRecord CreateSQLiteReportVariableDictionaryRecord CreateSQLiteRoomAirModelTable CreateSQLiteRoomAirModelTable CreateSQLiteSchedulesTable CreateSQLiteSimulationsRecord CreateSQLiteSimulationsRecord CreateSQLiteStringTableRecord CreateSQLiteSurfacesTable CreateSQLiteSurfacesTable CreateSQLiteTabularDataRecords CreateSQLiteTabularDataRecords CreateSQLiteTimeIndexRecord CreateSQLiteTimeIndexRecord CreateSQLiteVentilationTable CreateSQLiteVentilationTable CreateSQLiteZoneGroupTable CreateSQLiteZoneGroupTable CreateSQLiteZoneListTable CreateSQLiteZoneListTable CreateSQLiteZoneTable CreateSQLiteZoneTable CreateStormWindowConstructions CreateSysTimeIntervalString CreateTCConstructions CreateTimeIntervalString CreateTimeString CreatExtBooundCondName CreateZoneExtendedOutput CreateZoneExtendedOutput CrossProduct CrossProduct cSurfaceClass CTRANS CurveValue DateToString DateToStringWithMonth DaylghtAltAndAzimuth DayltgAveInteriorReflectance DayltgClosestObstruction DayltgCrossProduct DayltgCurrentExtHorizIllum DayltgDirectIllumComplexFenestration DayltgDirectSunDiskComplexFenestration DayltgElecLightingControl DayltgExtHorizIllum DayltgGlare DayltgGlarePositionFactor DayltgGlareWithIntWins DayltgHitBetWinObstruction DayltgHitInteriorObstruction DayltgHitObstruction DayltgInteriorIllum DayltgInteriorMapIllum DayltgInteriorTDDIllum DayltgInterReflectedIllum DayltgInterReflectedIllumComplexFenestration DayltgInterReflIllFrIntWins DayltgLuminousEfficacy DayltgPierceSurface DayltgSetupAdjZoneListsAndPointers DayltgSkyLuminance DayltgSurfaceLumFromSun dCheckScheduleValueMinMax1 dCheckScheduleValueMinMax2 DeallocateLoadComponentArrays DebugRootFinder DecodeHHMMField DecodeMonDayHrMin DeflectionTemperatures DeflectionWidths DegradF DElightDaylightCoefficients DElightDaylightCoefficients DElightElecLtgCtrl DElightElecLtgCtrl DElightFreeMemory DElightFreeMemory DElightInputGenerator DElightInputGenerator DElightOutputGenerator DElightOutputGenerator DensityCFSFillGas Depth DERIV DetailsForSurfaces DetectOscillatingZoneTemp DetermineAzimuthAndTilt DetermineBranchFlowRequest DetermineBuildingFloorArea DetermineDateTokens DetermineFrequency DetermineIndexGroupFromMeterGroup DetermineIndexGroupKeyFromMeterName DetermineMaxBackSurfaces DetermineMeterIPUnits DetermineMinuteForReporting DeterminePolygonOverlap DetermineShadowingCombinations DetermineSunUpDown DevelopMesh DiffuseAverage DiffuseAverageProfAngGnd DiffuseAverageProfAngSky DisplayMaterialRoughness DisplayNumberandString DisplaySimDaysProgress DisplayString distance DistributeBBElecRadGains DistributeBBRadGains DistributeBBSteamRadGains DistributeHTRadGains DistributePlantLoad DistributePressureOnBranch DistributeTDDAbsorbedSolar DistributeUserDefinedPlantLoad DL_RES_r2 DLAG DOE2DXCoilHumRatResidual DOE2DXCoilHumRatResidual DOE2DXCoilResidual DOE2DXCoilResidual DOE2DXCoilResidual DoEndOfIterationOperations DomainRectangle_Contains DOMakeUPPERCase DoOneTimeInitializations DOSameString DoShadeControl DoStartOfTimeStepInitializations DownInterpolate4HistoryValues DumpAirLoopStatistics DumpCurrentLineBuffer DUMPVD DUMPVR DXCoilCyclingHumRatResidual DXCoilCyclingHumRatResidual DXCoilCyclingResidual DXCoilCyclingResidual DXCoilVarSpeedHumRatResidual DXCoilVarSpeedHumRatResidual DXCoilVarSpeedResidual DXCoilVarSpeedResidual DXFOut DXFOutLines DXFOutWireFrame DXHeatingCoilResidual DXHeatingCoilResidual DXHeatingCoilResidual DynamicClothingModel DynamicExtConvSurfaceClassification DynamicIntConvSurfaceClassification EchoOutActuatorKeyChoices EchoOutInternalVariableChoices EffectiveEPSLB EffectiveEPSLF EIRChillerHeatRecovery EN673ISO10292 EncodeMonDayHrMin EndEnergyPlus EndUniqueNodeCheck EnthalpyResidual epElapsedTime epGetTimeUsed epGetTimeUsedperCall epStartTime epStopTime epSummaryTimes eptime EQLWindowInsideEffectiveEmiss EQLWindowOutsideEffectiveEmiss EQLWindowSurfaceHeatBalance EquationsSolver ERF EstimateHEXSurfaceArea EvalInsideMovableInsulation EvalOutsideMovableInsulation EvaluateAdiabaticSurfaceTemperature EvaluateBasementCellTemperature EvaluateCellNeighborDirections evaluateChargeBlock evaluateChargeSimple EvaluateExpression EvaluateExtHcModels EvaluateFarfieldBoundaryTemperature EvaluateFarfieldCharacteristics EvaluateFieldCellTemperature EvaluateGroundSurfaceTemperature EvaluateIntHcModels EvaluateLoopSetPointLoad EvaluateNeighborCharacteristics evaluateQualify evaluateRatchet EvaluateSoilRhoCp EvaluateStack EvolveParaUCSDCV ExitCalcController ExpandComplexState ExpressAsCashFlows ExtendObjectDefinition ExteriorBCEqns ExternalInterfaceExchangeVariables ExternalInterfaceInitializeErlVariable ExternalInterfaceSetErlVariable ExternalInterfaceSetSchedule ExtOrIntShadeNaturalFlow Fabric_EstimateDiffuseProps FACSKY FalsePositionMethod FEQX FI FigureACAncillaries FigureAirEnthalpy FigureAirHeatCap FigureAuxilHeatGasHeatCap FigureBeamSolDiffuseReflFactors FigureBeamSolSpecularReflFactors FigureConstGradPattern FigureDayltgCoeffsAtPointsForSunPosition FigureDayltgCoeffsAtPointsForWindowElements FigureDayltgCoeffsAtPointsSetupForWindow FigureElectricalStorageZoneGains FigureFuelCellZoneGains FigureFuelEnthalpy FigureFuelHeatCap FigureGaseousWaterEnthalpy FigureHeightPattern FigureHXleavingGasHeatCap FigureInverterZoneGains FigureLHVofFuel FigureLiquidWaterEnthalpy FigureLiquidWaterHeatCap FigureMapPointDayltgFactorsToAddIllums FigureMicroCHPZoneGains FigureNDheightInZone FigurePowerConditioningLosses FigureProductGasesEnthalpy FigureProductGasHeatCap FigureRefPointDayltgFactorsToAddIllums FigureRefrigerationZoneGains FigureSolarBeamAtTimestep FigureSunCosines FigureSurfMapPattern FigureTDDZoneGains FigureTransformerZoneGains FigureTransientConstraints FigureTwoGradInterpPattern FILJAC FillBasisElement FillDefaultsSWP FillRemainingPredefinedEntries FillWeatherPredefinedEntries film filmg filmi filmPillar FILSKY FinalizeCFS FinalizeCFSLAYER FinalRateCoils FindAirLoopBranchConnection FindAirPlantCondenserLoopFromBranchList FindAllNumbersinList FindArrayIndex FindCompSPInput FindCompSPLoad FindCondenserLoopBranchConnection FindControlledZoneIndexFromSystemNodeNumberForZone FindDeltaTempRangeInput FindDemandSideMatch FindEMSVariable FindFirstLastPtr FindFirstRecord FindGlycol FindHXDemandSideLoopFlow FindInBasis FindItem FindIteminList FindIteminSortedList FindItemInVariableList FindLoopSideInCallingOrder FindNextRecord FindNonSpace FindNumberinList FindOAMixerMatchForOASystem FindPlantLoopBranchConnection FindRangeBasedOrUncontrolledInput FindRangeVariable FindRefrigerant FindRootSimpleController FindStratifiedTankSensedTemp FindTariffIndex FindTDDPipe FindUnitNumber FinishDebugOutputFiles FixViewFactors FluidCellInformation_ctor FM_BEAM FM_DIFF FM_F FNU forcedventilation FourPipeInductionUnitHasMixer FourPipeIUCoolingResidual FourPipeIUHeatingResidual FRA FrostControl FrostControlSetPointLimit FrostControlSetPointLimit FuelCellProductGasEnthResidual FUN FuncDetermineCoolantWaterExitTemp FuncDetermineCWMdotForInternalFlowControl FuncDetermineEngineTemp FV GasElecHeatingCoilResidual GASSES90 GassesLow GatherBEPSResultsForTimestep GatherBinResultsForTimestep GatherComponentLoadsHVAC GatherComponentLoadsIntGain GatherComponentLoadsSurfAbsFact GatherComponentLoadsSurface GatherForEconomics GatherForPredefinedReport GatherHeatGainReport GatherMonthlyResultsForTimestep GatherPeakDemandForTimestep GatherSourceEnergyEndUseResultsForTimestep GaussElimination generate_ears GenerateDElightDaylightCoefficients GenerateDElightDaylightCoefficients GeneratorPowerOutput GenericCrack GenOutputVariablesAuditReport Get2DMatrix Get2DMatrixDimensions GET_COMMAND GET_COMMAND_ARGUMENT Get_Environment_Variable GetActualDXCoilIndex GetAirBranchIndex GetAirFlowFlag GetAirflowNetworkInput GetAirHeatBalanceInput GetAirLoopAvailabilityManager GetAirModelDatas GetAirNodeData GetAirPathData GetAngleFactorList GetATMixer GetATMixerOutNode GetATMixerPriNode GetATMixers GetATMixerSecNode GetAttShdSurfaceData GetAverageTempByType GetBaseboardInput GetBaseboardInput GetBasementFloorHeatFlux GetBasementWallHeatFlux GetBLASTAbsorberInput GetBoilerInput GetBoilerInput GetBranchData GetBranchFanTypeName GetBranchFlow GetBranchInput GetBranchList GetBranchListInput GetBuildingData GetCBVAV GetCellWidths GetCellWidthsCount GetChildrenData GetChillerheaterInput GetCoilAirFlowRate GetCoilAirFlowRateVariableSpeed GetCoilAirInletNode GetCoilAirOutletNode GetCoilAvailScheduleIndex GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacityByIndexType GetCoilCapacityVariableSpeed GetCoilCondenserInletNode GetCoilControlNodeNum GetCoilGroupTypeNum GetCoilIndex GetCoilIndex GetCoilIndex GetCoilIndexVariableSpeed GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNodeVariableSpeed GetCoilMaxSteamFlowRate GetCoilMaxWaterFlowRate GetCoilMaxWaterFlowRate GetCoilMaxWaterFlowRate GetCoilObjectTypeNum GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNodeVariableSpeed GetCoilSteamInletNode GetCoilSteamOutletNode GetCoilTypeNum GetCoilWaterInletNode GetCoilWaterInletNode GetCoilWaterOutletNode GetColumnUsingTabs GetComfortSetpoints GetComponentData GetCondFDInput GetConductivityGlycol GetConnectorList GetConnectorListInput GetConstCOPChillerInput GetConstructData GetControlledZoneIndex GetControllerActuatorNodeNum GetControllerInput GetCoolBeams GetCoolingCoilTypeNameAndIndex GetCooltower GetCostEstimateInput GetCrossVentData GetCTGeneratorInput GetCTGeneratorResults GetCurrentHVACTime GetCurrentMeterValue GetCurrentScheduleValue GetCurveCheck GetCurveIndex GetCurveInput GetCurveMinMaxValues GetCurveName GetCurveObjectTypeNum GetCurveType GetCustomMeterInput GetDaylightingParametersDetaild GetDaylightingParametersInput GetDayScheduleIndex GetDemandManagerInput GetDemandManagerListInput GetDensityGlycol GetDesiccantDehumidifierInput GetDesignDayData GetDesignLightingLevelForZone GetDetShdSurfaceData GetDirectAirInput GetDisplacementVentData GetDSTData GetDualDuctInput GetDualDuctOutdoorAirRecircUse GetDuctInput GetDXCoilAirFlow GetDXCoilAvailSchPtr GetDXCoilBypassedFlowFrac GetDXCoilCapFTCurveIndex GetDXCoilIndex GetDXCoilNumberOfSpeeds GetDXCoils GetDXCoolingSystemInput GetDXHeatPumpSystemInput GetEarthTube GetElecReformEIRChillerInput GetElectricBaseboardInput GetElectricChillerInput GetElectricEIRChillerInput GetEMSInput GetEngineDrivenChillerInput GetEnvironmentalImpactFactorInfo GetEvapFluidCoolerInput GetEvapInput GetExhaustAbsorberInput GetExhaustAirInletNode GetExteriorEnergyUseInput GetExtVentedCavityIndex GetExtVentedCavityIndex GetExtVentedCavityTsColl GetExtVentedCavityTsColl GetFanAvailSchPtr GetFanCoilIndex GetFanCoilInletAirNode GetFanCoilMixedAirNode GetFanCoilOutAirNode GetFanCoilReturnAirNode GetFanCoilUnits GetFanCoilZoneInletAirNode GetFanDesignVolumeFlowRate GetFanIndex GetFanIndexForTwoSpeedCoil GetFanInletNode GetFanInput GetFanOutletNode GetFanPower GetFanSpeedRatioCurveIndex GetFanType GetFanVolFlow GetFarfieldTemp GetFirstBranchInletNodeName GetFluidCoolerInput GetFluidDensityTemperatureLimits GetFluidHeatExchangerInput GetFluidPropertiesData GetFluidSpecificHeatTemperatureLimits GetFrameAndDividerData GetFuelCellGeneratorInput GetFuelCellGeneratorResults GetFuelFactorInfo GetFurnaceInput GetGasAbsorberInput GetGeneratorFuelSupplyInput GetGeometryParameters GetGlycolNameByIndex GetGroundheatExchangerInput GetGroundReflectances GetGroundTemps GetGshpInput GetGshpInput GetGTChillerInput GetHeatBalanceInput GetHeatBalHAMTInput GetHeatExchangerObjectTypeNum GetHeatingCoilIndex GetHeatingCoilInput GetHeatingCoilNumberOfStages GetHeatingCoilPLFCurveIndex GetHeatingCoilTypeNum GetHeatReclaimSourceIndex GetHeatRecoveryInput GetHighTempRadiantSystem GetHPCoolingCoilIndex GetHTSubSurfaceData GetHTSurfaceData GetHTSurfExtVentedCavityData GetHumidifierInput GetHVACSingleDuctSysIndex GetHWBaseboardInput GetHXAssistedCoolingCoilInput GetHXCoilAirFlowRate GetHXCoilType GetHXCoilTypeAndName GetHXDXCoilIndex GetHXDXCoilName GetHybridVentilationControlStatus GetHybridVentilationInputs GetICEGeneratorResults GetICEngineGeneratorInput GetIceStorageInput GetIDFRecordsStats GetIndirectAbsorberInput GetIndUnits GetInputEconomicsChargeBlock GetInputEconomicsChargeSimple GetInputEconomicsComputation GetInputEconomicsCurrencyType GetInputEconomicsQualify GetInputEconomicsRatchet GetInputEconomicsTariff GetInputEconomicsVariable GetInputForLifeCycleCost GetInputFuelAndPollutionFactors GetInputLifeCycleCostNonrecurringCost GetInputLifeCycleCostParameters GetInputLifeCycleCostRecurringCosts GetInputLifeCycleCostUseAdjustment GetInputLifeCycleCostUsePriceEscalation GetInputTabularMonthly GetInputTabularPredefined GetInputTabularStyle GetInputTabularTimeBins GetInputViewFactors GetInputViewFactorsbyName GetInputZoneEvaporativeCoolerUnit GetInstantMeterValue GetInternalBranchData GetInternalHeatGainsInput GetInternalVariableValue GetInternalVariableValue GetInternalVariableValueExternalInterface GetInternalVariableValueExternalInterface GetInterpolatedSatProp GetInterpValue GetIntMassSurfaceData GetLastBranchOutletNodeName GetLastWord GetLightWellData GetListOfObjectsInIDD GetListofSectionsinInput GetLocationInfo GetLoopMixer GetLoopSidePumpIndex GetLoopSplitter GetLowTempRadiantSystem GetMaterialData GetMatrixInput getMaxAndSum GetMeteredVariables GetMeterIndex GetMeterResourceType GetMicroCHPGeneratorInput GetMicroCHPGeneratorResults GetMinOATCompressor GetMixerInput GetMixerInput GetMoistureBalanceEMPDInput GetMonthlyCostForResource GetMovableInsulationData GetMSHeatPumpInput GetMTGeneratorExhaustNode GetMTGeneratorInput GetMTGeneratorResults GetMundtData GetNewUnitNumber GetNextEnvironment GetNodeConnectionType GetNodeList GetNodeListsInput GetNodeNums GetNTUforCrossFlowBothUnmixed GetNumberOfSchedules GetNumberOfSurfaceLists GetNumberOfSurfListVentSlab GetNumChildren GetNumMeteredVariables GetNumOAControllers GetNumOAMixers GetNumOASystems GetNumObjectsFound GetNumObjectsInIDD GetNumRangeCheckErrorsFound GetNumSectionsFound GetNumSectionsinInput GetNumSegmentsForHorizontalTrenches GetNumSplitterMixerInConntrList GetOACompListNumber GetOACompName GetOACompType GetOACompTypeNum GetOAControllerInputs GetOAMixerIndex GetOAMixerInletNodeNumber GetOAMixerInputs GetOAMixerMixedNodeNumber GetOAMixerNodeNumbers GetOAMixerReliefNodeNumber GetOAMixerReturnNodeNumber GetOARequirements GetOASysControllerListIndex GetOASysNumCoolingCoils GetOASysNumHeatingCoils GetOASysNumSimpControllers GetOASystemNumber GetObjectDefInIDD GetObjectDefMaxArgs GetObjectItem GetObjectItemfromFile GetObjectItemNum GetOnlySingleNode GetOperationSchemeInput GetOSCData GetOSCMData GetOutAirNodesInput GetOutdoorAirUnitInputs GetOutdoorAirUnitOutAirNode GetOutdoorAirUnitReturnAirNode GetOutdoorAirUnitZoneInletNode GetOutsideAirSysInputs GetOutsideEnergySourcesInput GetParentData GetPipeInput GetPipesHeatTransfer GetPipingSystemsInput GetPIUs GetPlantAvailabilityManager GetPlantInput GetPlantLoopData GetPlantOperationInput GetPlantProfileInput GetPlantSizingInput GetPlantValvesInput GetPollutionFactorInput GetPondGroundHeatExchanger GetPowerManagerInput GetPressureCurveTypeAndIndex GetPressureSystemInput GetPreviousHVACTime GetProjectControlData GetProjectData GetPTUnit GetPTUnitMixedAirNode GetPTUnitOutAirNode GetPTUnitReturnAirNode GetPTUnitZoneInletAirNode GetPumpInput GetPurchasedAir GetPurchasedAirMixedAirHumRat GetPurchasedAirMixedAirTemp GetPurchasedAirOutAirMassFlow GetPurchasedAirReturnAirNode GetPurchasedAirZoneInletAirNode GetPVGeneratorResults GetPVInput GetPVTcollectorsInput GetPVTThermalPowerProduction GetQualityRefrig GetRecordLocations GetRectDetShdSurfaceData GetRectSubSurfaces GetRectSurfaces GetRefrigeratedRackIndex GetRefrigerationInput GetReportVariableInput GetRequiredMassFlowRate GetResidCrossFlowBothUnmixed GetResourceTypeChar GetReturnAirNodeForZone GetReturnAirPathInput GetRoomAirModelParameters GetRunPeriodData GetRunPeriodDesignData GetRuntimeLanguageUserInput GetSatDensityRefrig GetSatEnthalpyRefrig GetSatPressureRefrig GetSatSpecificHeatRefrig GetSatTemperatureRefrig GetScheduledSurfaceGains GetScheduleIndex GetScheduleMaxValue GetScheduleMinValue GetScheduleName GetScheduleType GetScheduleValuesForDay GetSecondaryInletNode GetSecondaryOutletNode GetSetPointManagerInputs GetShadingSurfReflectanceData GetShadowingInput GetShelfInput GetSimpleAirModelInputs GetSimpleShdSurfaceData GetSimpleWatertoAirHPInput GetSingleDayScheduleValues GetSiteAtmosphereData GetSizingParams GetSnowGroundRefModifiers GetSolarCollectorInput GetSpecialDayPeriodData GetSpecificHeatGlycol getSpecificUnitDivider getSpecificUnitIndex getSpecificUnitMultiplier GetSplitterInput GetSplitterInput GetSplitterNodeNumbers GetSplitterOutletNumber GetStandAloneERV GetStandAloneERVNodes GetStandAloneERVOutAirNode GetStandAloneERVReturnAirNode GetStandAloneERVZoneInletAirNode GetStandardMeterResourceType GetSteamBaseboardInput GetSteamCoilAvailScheduleIndex GetSteamCoilControlNodeNum GetSteamCoilIndex GetSteamCoilInput GetSTM GetStormWindowData GetSupHeatDensityRefrig GetSupHeatEnthalpyRefrig GetSupHeatPressureRefrig GetSupplyAirFlowRate GetSupplyAirFlowRate GetSupplyAirInletNode GetSupplyInletNode GetSupplyOutletNode GetSurfaceCountForOSCM GetSurfaceData GetSurfaceGroundHeatExchanger GetSurfaceHeatTransferAlgorithmOverrides GetSurfaceIndecesForOSCM GetSurfaceListsInputs GetSurfHBDataForMundtModel GetSurfHBDataForTempDistModel GetSysAvailManagerInputs GetSysAvailManagerListInputs GetSysInput GetSystemNodeNumberForZone GetSystemSizingInput GetTDDInput GetTESCoilIndex GetTESCoilInput GetThermalChimney GetTowerInput GetTranspiredCollectorIndex GetTranspiredCollectorInput GetTypeOfCoil GetUFADZoneData GetUnitarySystemDXCoolingCoilIndex GetUnitarySystemInput GetUnitarySystemOAHeatCoolCoil GetUnitConversion GetUnitHeaterInput GetUnitsString GetUnitSubString GetUnitVentilatorInput GetUnitVentilatorMixedAirNode GetUnitVentilatorOutAirNode GetUnitVentilatorReturnAirNode GetUnitVentilatorZoneInletAirNode GetUserConvectionCoefficients GetUserDefinedComponents GetUserDefinedOpSchemeInput GetUserDefinedPatternData GetUTSCTsColl GetVariableKeyCountandType GetVariableKeyCountandType GetVariableKeys GetVariableKeys GetVariableTypeAndIndex GetVariableUnitsString GetVarSpeedCoilInput GetVentilatedSlabInput GetVertices GetViscosityGlycol GetVRFInput GetVSCoilCondenserInletNode GetVSCoilMinOATCompressor GetVSCoilNumOfSpeeds GetWaterCoilAvailScheduleIndex GetWaterCoilCapacity GetWaterCoilIndex GetWaterCoilInput GetWaterMainsTemperatures GetWaterManagerInput GetWaterSource GetWaterThermalTankInput GetWatertoAirHPInput GetWatertoWaterHPInput GetWaterUseInput GetWeatherProperties GetWeatherStation GetWindowAC GetWindowACMixedAirNode GetWindowACOutAirNode GetWindowACReturnAirNode GetWindowACZoneInletAirNode GetWindowGapAirflowControlData GetWindowGlassSpectralData GetWindowShadingControlData GetWindTurbineInput GetWrapperInput GetWTGeneratorResults GetZoneAirDistribution GetZoneAirLoopEquipment GetZoneAirSetpoints GetZoneAndZoneListNames GetZoneContaminanInputs GetZoneContaminanSetpoints GetZoneData GetZoneDehumidifierInput GetZoneDehumidifierNodeNumber GetZoneEqAvailabilityManager GetZoneEquipment GetZoneEquipmentData GetZoneEquipmentData1 GetZoneInfilAirChangeRate GetZoneLoads GetZonePlenumInput GetZoneSizingInput GLtoAMB GoAhead guess HasFractionalScheduleValue hatter HCInWindowStandardRatings HConvGap HcUCSDCV HcUCSDDV HcUCSDUF HeatingCoilVarSpeedCycResidual HeatingCoilVarSpeedResidual HeatPumpRunFrac HeatPumpRunFrac HeatPumpRunFrac HeatWatertoAirHPTempResidual Height HEMINT HIC_ASHRAE HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterHeatingCoilResidual HRadPar HTRANS HTRANS0 HTRANS1 HWBaseboardUAResidual HXAssistDXCoilResidual HXAssistedCoolCoilHRResidual HXAssistedCoolCoilHRResidual HXAssistedCoolCoilTempResidual HXAssistedCoolCoilTempResidual HXDemandSideLoopFlowResidual HybridVentilationControl IAM iCheckScheduleValue ICSCollectorAnalyticalSoluton iGetCoilAirOutletNode iGetCoilSteamInletNode iGetCoilSteamOutletNode INCLOS incrementEconVar IncrementInstMeterCache incrementSteps incrementTableEntry InitAirflowNetwork InitAirflowNetworkData InitAirHeatBalance InitAirLoops InitAirLoopSplitter InitAirMixer InitAirTerminalUserDefined InitAirZoneReturnPlenum InitAirZoneSupplyPlenum InitATMixer InitBaseboard InitBaseboard InitBLASTAbsorberModel InitBoiler InitBoiler InitBoreholeHXSimVars InitBSDFWindows InitCBVAV InitCoilUserDefined InitComplexWindows InitComponentNodes InitConductionTransferFunctions InitConnections InitConstCOPChiller InitController InitCoolBeam InitCTGenerators InitCurveReporting InitDaylightingDevices InitDemandManagers InitDesiccantDehumidifier InitDetailedIceStorage InitDirectAir InitDualDuct InitDuct InitDXCoil InitDXCoolingSystem InitDXHeatPumpSystem InitElecReformEIRChiller InitElectricBaseboard InitElectricChiller InitElectricEIRChiller InitEMS InitEMSControlledConstructions InitEMSControlledSurfaceProperties InitEnergyReports InitEngineDrivenChiller InitEquivalentLayerWindowCalculations InitEvapCooler InitEvapFluidCooler InitExhaustAbsorber InitExteriorConvectionCoeff InitFan InitFanCoilUnits InitFluidCooler InitFluidHeatExchanger InitFuelCellGenerators InitFurnace InitGasAbsorber InitGlassOpticalCalculations InitGshp InitGshp InitGTChiller InitHeatBalance InitHeatBalFiniteDiff InitHeatBalHAMT InitHeatingCoil InitHeatRecovery InitHighTempRadiantSystem InitHumidifier InitHWBaseboard InitHXAssistedCoolingCoil InitHybridVentSysAvailMgr InitialInitHeatBalFiniteDiff InitializeCFSDaylighting InitializeCFSStateData InitializeComponentSizingTable InitializeConstructionsTables InitializeDaylightMapTables InitializeEnvironmentPeriodsTable InitializeErrorsTable InitializeGlycolTempLimits InitializeHeatTransferPipes InitializeIndexes InitializeIndexes InitializeLoops InitializeMaterialsTable InitializeMeters initializeMonetaryUnit InitializeNominalBaseboardHeatTable InitializeNominalElectricEquipmentTable InitializeNominalGasEquipmentTable InitializeNominalHotWaterEquipmentTable InitializeNominalInfiltrationTable InitializeNominalLightingTable InitializeNominalOtherEquipmentTable InitializeNominalPeopleTable InitializeNominalSteamEquipmentTable InitializeNominalVentilationTable InitializeOperatingMode InitializeOutput InitializePipes InitializePredefinedMonthlyTitles InitializePsychRoutines InitializePumps InitializeRefrigerantLimits InitializeReportMeterDataDictionaryTable InitializeReportMeterDataTables InitializeReportVariableDataDictionaryTable InitializeReportVariableDataTables InitializeRoomAirModelTable InitializeRootFinder InitializeRuntimeLanguage InitializeSchedulesTable InitializeSimulationsTable InitializeSQLiteTables InitializeSurfacesTable InitializeSystemSizingTable InitializeTabularDataTable InitializeTabularDataTable InitializeTabularDataView InitializeTabularDataView InitializeTabularMonthly InitializeTimeIndicesTable InitializeViews InitializeWeather InitializeZoneGroupTable InitializeZoneInfoTable InitializeZoneListTable InitializeZoneSizingTable InitICEngineGenerators InitIndirectAbsorpChiller InitIndUnit InitInteriorConvectionCoeffs InitInteriorRadExchange InitInternalHeatGains InitIntSolarDistribution InitLoadBasedControl InitLoadDistribution InitLowTempRadiantSystem InitMicroCHPNoNormalizeGenerators InitMoistureBalanceEMPD InitMSHeatPump InitMTGenerators InitMundtModel InitOAController InitOAMixer InitOneTimePlantSizingInfo InitOutAirNodes InitOutdoorAirUnit InitOutsideAirSys InitPipesHeatTransfer InitPipingSystems InitPIU InitPlantProfile InitPlantUserComponent InitPlantValves InitPollutionMeterReporting InitPondGroundHeatExchanger InitPressureDrop InitPTUnit InitPurchasedAir InitPVTcollectors InitRefrigeration InitRefrigerationPlantConnections InitReturnAirPath InitSecretObjects InitSetPointManagers InitSimpleIceStorage InitSimpleMixingConvectiveHeatGains InitSimpleWatertoAirHP InitSimVars InitSimVars InitSimVars InitSimVars InitSolarCalculations InitSolarCollector InitSolarHeatGains InitSolReflRecSurf InitStandAloneERV InitSteamBaseboard InitSteamCoil InitSurfaceGroundHeatExchanger InitSurfaceHeatBalance InitSys InitSysAvailManagers InitSystemOutputRequired InitTempDistModel InitTESCoil InitThermalAndFluxHistories InitThermalComfort InitTower InitTranspiredCollector InitTRNSYSPV InitUCSDCV InitUCSDDV InitUCSDUF InitUniqueNodeCheck InitUnitarySystems InitUnitHeater InitUnitVentilator InitVarSpeedCoil InitVentilatedSlab InitVRF InitWaterCoil InitWaterSource InitWaterThermalTank InitWatertoAirHP InitWatertoWaterHP InitWindowAC InitWindTurbine InitWrapper InitZoneAirLoopEquipment InitZoneAirSetpoints InitZoneAirUserDefined InitZoneContSetpoints InitZoneDehumidifier InitZoneEquipment InitZoneEvaporativeCoolerUnit InPolygon InsertCurrencySymbol int_times_vector INTCPT Integer_IsInRange IntegerIsWithinTwoValues IntegerToString InterConnectTwoPlantLoopSides InteriorBCEqns InteriorNodeEqns InternalRangeCheck InternalSetupTankDemandComponent InternalSetupTankSupplyComponent interp INTERP InterpBlind InterpDefValuesForGlycolConc Interpolate Interpolate_Lagrange InterpolateBetweenFourValues InterpolateBetweenTwoValues InterpolatePipeTransBeam InterpProfAng InterpProfSlatAng InterpretWeatherDataLine InterpSlatAng InterpSw InterpValuesForGlycolConc IntInterfaceNodeEqns IntPreDefTableEntry IntToStr Invert3By3Matrix InvertMatrix InvJulianDay IPTrimSigDigits iRoundSigDigits IS_BEAM IS_DIFF IS_DSRATIO IS_F IS_LWP IS_OPENNESS IS_SWP isCompLoadRepReq IsControlledShade IsConverged_CurrentToPrevIteration IsConverged_PipeCurrentToPrevIteration IsCurveInputTypeValid IsCurveOutputTypeValid isExternalInterfaceErlVariable IsGlazeLayerX IsGZSLayer isInQuadrilateral IsInRange isInTriangle IsLeapYear IsNodeOnSetPtManager IsParentObject IsParentObjectCompSet IsShadingLayer IssueSevereAlphaInputFieldError IssueSevereInputFieldError IssueSevereRealInputFieldError IsValidConnectionType IsVBLayer isWithinRange ITERATE IterateRootFinder iTrimSigDigits JGDate JulianDay LClimb LDSumMax LDSumMean LEEDtariffReporting LimitCoilCapacity LimitController LimitTUCapacity LinesOut linint LoadEquipList LoadInterface LogicalToInteger LogicalToInteger LogPlantConvergencePoints lookupOperator LookUpScheduleValue LookUpSeason LookupSItoIP lubksb LUBKSB ludcmp LUDCMP LUdecomposition LUsolution MakeAnchorName MakeHVACTimeIntervalString MakeMirrorSurface MakeRectangularVertices MakeRelativeRectangularVertices MakeTransition MakeUPPERCase ManageAirflowNetworkBalance ManageAirHeatBalance ManageAirLoops ManageAirModel ManageBranchInput ManageControllers ManageCoolTower ManageDemand ManageEarthTube ManageElectCenterStorageInteractions ManageElectricLoadCenters ManageElectStorInteractions ManageEMS ManageExteriorEnergyUse ManageGeneratorControlState ManageGeneratorFuelFlow ManageHeatBalance ManageHeatBalFiniteDiff ManageHeatBalHAMT ManageHVAC ManageHybridVentilation ManageInsideAdaptiveConvectionAlgo ManageInternalHeatGains ManageInverter ManageMundtModel ManageNonZoneEquipment ManageOutsideAdaptiveConvectionAlgo ManageOutsideAirSystem ManagePlantLoadDistribution ManagePlantLoops ManageRefrigeratedCaseRacks ManageSetPoints ManageSimulation ManageSingleCommonPipe ManageSizing ManageSurfaceHeatBalance ManageSystemAvailability ManageThermalChimney ManageThermalComfort ManageTransformers ManageTwoWayCommonPipe ManageUCSDCVModel ManageUCSDDVModel ManageUCSDUFModels ManageUserDefinedPatterns ManageWater ManageWaterInits ManageWeather ManageZoneAirLoopEquipment ManageZoneAirUpdates ManageZoneContaminanUpdates ManageZoneEquipment MapExtConvClassificationToHcModels MapIntConvClassificationToHcModels MarkNode MatchAndSetColorTextString MatchPlantSys MatrixIndex matrixQBalance MeshPartition_CompareByDimension MeshPartition_SelectionSort MeshPartitionArray_Contains MinePlantStructForInfo MixedAirControlTempResidual ModifyWindow Modulus MonthToMonthNumber MovingAvg MRXINV MSHPCyclingResidual MSHPHeatRecovery MSHPVarSpeedResidual MultiModeDXCoilHumRatResidual MultiModeDXCoilHumRatResidual MultiModeDXCoilResidual MultiModeDXCoilResidual MultiModeDXCoilResidual MultiSpeedDXCoolingCoilStandardRatings MultiSpeedDXHeatingCoilStandardRatings MULTOL MyPlantSizingIndex NeighborInformationArray_Value NETRAD NewEMSVariable NewExpression newPreDefColumn newPreDefReport newPreDefSubTable NEWTON NodeHasSPMCtrlVarType NormalArea NumBranchesInBranchList NumCompsInBranch nusselt NusseltNumber OpenEPlusWeatherFile OPENNESS_LW OpenOutputFiles OpenOutputTabularFile OpenWeatherFile OPERATOR (*) OPERATOR (+) OPERATOR (-) OPERATOR (.dot.) OPERATOR (.twodcross.) OPERATOR (.twoddot.) OPERATOR (/) ORDER OutBaroPressAt OutDewPointTempAt OutDryBulbTempAt OutsidePipeHeatTransCoef OutWetBulbTempAt P01 PanesDeflection ParametricObjectsCheck parseComputeLine ParseExpression ParseStack ParseTime PartLoadFactor PassiveGapNusseltNumber PassPressureAcrossInterface PassPressureAcrossMixer PassPressureAcrossSplitter PD_BEAM PD_BEAM_CASE_I PD_BEAM_CASE_II PD_BEAM_CASE_III PD_BEAM_CASE_IV PD_BEAM_CASE_V PD_BEAM_CASE_VI PD_DIFF PD_LW PD_LWP PD_SWP PerformanceCurveObject PerformanceTableObject PerformIterationLoop PerformPipeCellSimulation PerformPipeCircuitSimulation PerformSolarCalculations PerformTemperatureFieldUpdate PierceSurface PierceSurfaceVector PipeCircuitInfo_InitInOutCells PipeSegmentInfo_InitPipeCells PIUInducesPlenumAir PIUnitHasMixer PlaneEquation PlantHalfLoopSolver PlantMassFlowRatesFunc PLRResidual PLRResidual PLRResidualMixedTank PLRResidualStratifiedTank PMVResidual POLY1F POLY2F POLYF polygon_contains_point_2d popStack pos PostIPProcessing POWER PreDefTableEntry PredictSystemLoads PredictZoneContaminants PreparePipeCircuitSimulation PrepDebugFilesAndVariables PreProcessorCheck PrepVariablesISO15099 PreScanReportingVariables PresProfile PressureCurveValue ProcessDataDicFile ProcessDateString ProcessEMSInput ProcessEPWHeader ProcessForDayTypes ProcessInput ProcessInputDataFile ProcessIntervalFields ProcessMinMaxDefLine ProcessNumber ProcessScheduleInput ProcessSurfaceVertices ProcessTokens ProduceMinMaxString ProduceMinMaxStringWStartMinute ProduceRDDMDD ProfileAngle PropagateResolvedFlow PStack PsyCpAirFnWTdb PsyHfgAirFnWTdb PsyHFnTdbRhPb PsyHFnTdbW PsyHgAirFnWTdb PsyPsatFnTemp PsyPsatFnTemp_raw PsyRhFnTdbRhov PsyRhFnTdbRhovLBnd0C PsyRhFnTdbWPb PsyRhoAirFnPbTdbW PsyRhovFnTdbRh PsyRhovFnTdbRhLBnd0C PsyRhovFnTdbWPb PsyTdbFnHW PsyTdpFnTdbTwbPb PsyTdpFnWPb PsyTsatFnHPb PsyTsatFnPb PsyTwbFnTdbWPb PsyTwbFnTdbWPb_raw PsyVFnTdbWPb PsyWFnTdbH PsyWFnTdbRhPb PsyWFnTdbTwbPb PsyWFnTdpPb psz Pt2Plane PullCompInterconnectTrigger PumpDataForTable PushBranchFlowCharacteristics PushInnerTimeStepArrays pushStack PushSystemTimestepHistories PushSystemTimestepHistories PushZoneTimestepHistories PushZoneTimestepHistories QsortC QsortPartition RadialCellInfo_XY_CrossSectArea RadialCellInformation_ctor RadialSizing_Thickness Rainflow RangeCheck RB_BEAM RB_DIFF RB_F RB_LWP RB_SWP rCheckDayScheduleValueMinMax rCheckScheduleValue rCheckScheduleValueMinMax1 rCheckScheduleValueMinMax2 ReadEnergyMeters ReadEPlusWeatherForDay ReadGeneralDomainInputs ReadHorizontalTrenchInputs ReadINIFile ReadInputLine ReadPipeCircuitInputs ReadPipeSegmentInputs ReadTableData ReadUserWeatherInput ReadWeatherForDay Real_ConstrainTo Real_IsInRange real_times_vector ReAllocateAndPreserveOutputVariablesForSimulation ReallocateIntegerArray ReallocateIVar ReallocateRealArray ReallocateRVar RealPreDefTableEntry RealToStr RecKeepHeatBalance RecordOutput RectangleF_Contains ReformEIRChillerCondInletTempResidual ReformEIRChillerHeatRecovery RegisterNodeConnection RegisterPlantCompDesignFlow RegulateCondenserCompFlowReqOp ReInitPlantLoopsAtFirstHVACIteration RemoveSpaces RemoveTrailingZeros reorder ReplaceBlanksWithUnderscores ReplaceBlanksWithUnderscores ReportAirflowNetwork ReportAirHeatBalance ReportAirLoopConnections ReportAirTerminalUserDefined ReportAndTestGlycols ReportAndTestRefrigerants ReportBaseboard ReportBaseboard ReportCBVAV ReportChillerIPLV ReportCoilUserDefined ReportCompSetMeterVariables ReportController ReportCoolBeam ReportCoolTower ReportCTFs ReportCWTankInits ReportDemandManagerList ReportDesiccantDehumidifier ReportDetailedIceStorage ReportDirectAir ReportDualDuct ReportDualDuctConnections ReportDuct ReportDXCoil ReportDXCoilRating ReportDYMeters ReportEarthTube ReportEconomicVariable ReportElectricBaseboard ReportEMS ReportEvapCooler ReportEvapFluidCooler ReportExteriorEnergyUse ReportFan ReportFanCoilUnit ReportFatalGlycolErrors ReportFatalRefrigerantErrors ReportFiniteDiffInits ReportFluidCooler ReportFluidHeatExchanger ReportForTabularReports ReportFurnace ReportGlass ReportHeatBalance ReportHeatingCoil ReportHeatRecovery ReportHighTempRadiantSystem ReportHRMeters ReportHumidifier ReportHWBaseboard ReportIllumMap ReportingFreqName ReportingThisVariable ReportInternalHeatGains ReportLoopConnections ReportLowTempRadiantSystem ReportMaxVentilationLoads ReportMeterDetails ReportMissing_RangeData ReportMixer ReportMNMeters ReportMoistureBalanceEMPD ReportMSHeatPump ReportNodeConnections ReportOAController ReportOAMixer ReportOrphanFluids ReportOrphanRecordObjects ReportOrphanSchedules ReportOutdoorAirUnit ReportOutputFileHeaders ReportParentChildren ReportPipesHeatTransfer ReportPIU ReportPlantProfile ReportPlantUserComponent ReportPlantValves ReportPondGroundHeatExchanger ReportPTUnit ReportPumps ReportPurchasedAir ReportPV ReportRackSystem ReportRefrigerationComponents ReportReturnAirPath ReportRuntimeLanguage ReportScheduleDetails ReportScheduleValues ReportSizingOutput ReportSMMeters ReportSolarCollector ReportSplitter ReportStandAloneERV ReportStandAloneWaterUse ReportSteamBaseboard ReportSteamCoil ReportSurfaceErrors ReportSurfaceGroundHeatExchngr ReportSurfaceHeatBalance ReportSurfaces ReportSurfaceShading ReportSys ReportSysSizing ReportSystemEnergyUse ReportThermalChimney ReportTowers ReportTSMeters ReportUnitarySystem ReportUnitHeater ReportUnitVentilator ReportVentilatedSlab ReportVRFCondenser ReportVRFTerminalUnit ReportWarmupConvergence ReportWaterCoil ReportWaterManager ReportWaterThermalTank ReportWaterUse ReportWeatherAndTimeInformation ReportWindowAC ReportWindTurbine ReportZoneAirLoopEquipment ReportZoneAirUserDefined ReportZoneDehumidifier ReportZoneEquipment ReportZoneEvaporativeCoolerUnit ReportZoneMeanAirTemp ReportZoneReturnPlenum ReportZoneSizing ReportZoneSupplyPlenum ResetAllPlantInterConnectFlags ResetController ResetEnvironmentCounter ResetHVACControl ResetNodeData ResetPerformanceCurveOutput ResetRootFinder ResetTerminalUnitFlowLimits ResetWeekDaysByMonth Resimulate resist ReSolveAirLoopControllers ResolveAirLoopFlowLimits ResolveLocationInformation ResolveLockoutFlags ResolveLoopFlowVsPressure ResolveParallelFlows ResolveSysFlow ReverseAndRecalculate RevertZoneTimestepHistories RevertZoneTimestepHistories RevisePlantCallingOrder RezeroZoneSizingArrays RhoH2O RHtoVP RKG RoundSigDigits rRoundSigDigits rTrimSigDigits SafeCopyPlantNode SafeDiv SafeDivide SameString SandiaCellTemperature SandiaEffectiveIrradiance SandiaF1 SandiaF2 SandiaImp SandiaIsc SandiaIx SandiaIxx SandiaModuleTemperature SandiaTcellFromTmodule SandiaVmp SandiaVoc SaveSimpleController ScanForReports ScanPlantLoopsForNodeNum ScanPlantLoopsForObject sCheckDayScheduleValueMinMax ScheduleAverageHoursPerWeek SEARCH SearchAscTable SearchWindow5DataFile SecantFormula SecantMethod selectTariff SetActuatedBranchFlowRate SetAdditionalNeighborData SetAllFlowLocks SetAllPlantSimFlagsToValue SetATMixerPriFlow SetATMixerPriFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetCoilDesFlow SetCoilSystemCoolingData SetCoilSystemHeatingDXFlag SetCompFlowRate SetComponentFlowRate SetCurrentWeather SetCurveOutputMinMaxValues SetDSTDateRanges SetDXCoilTypeData SetDXCoolingCoilData SetEquivalentLayerWindowProperties SetErlValueNumber SetExtConvectionCoeff SetFanData SetHeatExchangerData SetHeatToReturnAirFlag SetInitialMeterReportingAndOutputNames SetIntConvectionCoeff SetInternalVariableValue SetMinMax setNativeVariables SetNodeResult SetOAControllerData SetOnOffMassFlowRate SetOnOffMassFlowRate SetOnOffMassFlowRate SetOnOffMassFlowRateVSCoil SetOnOffMassFlowRateVSCoil SetOutAirNodes SetOutBulbTempAt SetPredefinedTables SetSimpleWSHPData SETSKY SetSpecialDayDates SetSpeedVariables SetStormWindowControl SetSurfHBDataForMundtModel SetSurfHBDataForTempDistModel SetSurfTmeanAir SETUP4x4_A SetupAdaptiveConvectionRadiantSurfaceData SetupAdaptiveConvectionStaticMetaData SetupAirLoopControllersTracer SetupAllOutputVariables SetUpAndSort SetupBranchControlTypes SetupCellNeighbors SetupCommonPipes SetupComplexFenestrationMaterialInput SetupComplexFenestrationStateInput SetupComplexWindowStateGeometry SetUpCompSets SetupDElightOutput4EPlus SetupDElightOutput4EPlus SetUpDesignDay SetupEMSActuator SetupEMSIntegerActuator SetupEMSIntegerInternalVariable SetupEMSInternalVariable SetupEMSLogicalActuator SetupEMSRealActuator SetupEMSRealInternalVariable SetupEnvironmentTypes SetupFuelConstituentData SetupGeneratorControlStateManager SetupIndividualControllerTracer SetupInitialPlantCallingOrder SetupIntegerOutputVariable SetupInterpolationValues SetupLoopFlowRequest SetupMeteredVarsForSetPt SetupMundtModel SetupNodeSetpointsAsActuators SetupNodeVarsForReporting SetupOutputVariable SetupPipeCircuitInOutCells SetupPlantEMSActuators SetupPollutionCalculations SetupPollutionMeterReporting SetupPossibleOperators SetupPrimaryAirSystemAvailMgrAsActuators SetupPumpMinMaxFlows SetupRealOutputVariable SetupRealOutputVariable_IntKey SetupReportInput SetupReports SetupRootFinder SetUpSchemeColors SetupShadeSurfacesForSolarCalcs SetupSimpleWindowGlazingSystem SetupSimulation SetupStratifiedNodes SetupSurfaceConstructionActuators SetupSurfaceConvectionActuators SetupSurfaceOutdoorBoundaryConditionActuators SetUpSysSizingArrays SetupTankDemandComponent SetupTankSupplyComponent SetupThermostatActuators SetupTimePointers SetupUnitConversions SetupWeekDaysByMonth SetupWindowShadingControlActuators SetupZoneEquipmentForConvectionFlowRegime SetupZoneGeometry SetupZoneInfoAsInternalDataAvail SetupZoneInternalGain SetupZoneInternalGain SetupZoneSizing SetUpZoneSizingArrays SetUTSCQdotSource SetVarSpeedCoilData SetVentedModuleQdotSource SetVSHPAirFlow SetVSHPAirFlow SetWindSpeedAt SetZoneEquipSimOrder shading shadingedge shadingin SHADOW SharedDVCVUFDataInit SHDBKS SHDGSS SHDRVL SHDSBS shift ShiftPipeTemperaturesForNewIteration ShiftPlantLoopSideCallingOrder ShiftTemperaturesForNewIteration ShiftTemperaturesForNewTimeStep ShowAuditErrorMessage ShowBranchesOnLoop ShowContinueError ShowContinueError ShowContinueErrorTimeStamp ShowContinueErrorTimeStamp ShowErrorMessage ShowErrorMessage ShowFatalError ShowFatalError ShowMessage ShowMessage ShowPsychrometricSummary ShowRecurringContinueErrorAtEnd ShowRecurringContinueErrorAtEnd ShowRecurringErrors ShowRecurringSevereErrorAtEnd ShowRecurringSevereErrorAtEnd ShowRecurringWarningErrorAtEnd ShowRecurringWarningErrorAtEnd ShowSevereError ShowSevereError ShowSevereMessage ShowSevereMessage ShowWarningError ShowWarningError ShowWarningMessage ShowWarningMessage showWarningsBasedOnTotal Sim4PipeFanCoil SimAirChillerSet SimAirLoop SimAirLoopComponent SimAirLoopComponents SimAirLoops SimAirLoopSplitter SimAirMixer SimAirTerminalUserDefined SimAirZonePlenum SimATMixer SimBaseboard SimBLASTAbsorber SimBoiler SimCBVAV SimCBVAV SimCentralGroundSourceHeatPump SimChiller SimCoilUserDefined SimComponentModelFan SimConstVol SimCoolBeam SimCostEstimate SimCTGenerator SimCTPlantHeatRecovery SimCyclingWindowAC SimDesiccantDehumidifier SimDetailedIceStorage SimDirectAir SimDistrictEnergy SimDualDuctConstVol SimDualDuctVarVol SimDualDuctVAVOutdoorAir SimDuct SimDXCoil SimDXCoilMultiMode SimDXCoilMultiSpeed SimDXCoolingSystem SimDXHeatPumpSystem SimElecBaseBoard SimElectricBaseBoard SimElectricConvective SimElectricEIRChiller SimEvapCooler SimEvapFluidCoolers SimExhaustAbsorber SimFanCoilUnit SimFluidCoolers SimFluidHeatExchanger SimFourPipeIndUnit SimFuelCellGenerator SimFuelCellPlantHeatRecovery SimFurnace SimGasAbsorber SimGroundHeatExchangers SimHeatPumpWaterHeater SimHeatRecovery SimHighTempRadiantSystem SimHPWatertoWaterCOOLING SimHPWatertoWaterHEATING SimHPWatertoWaterSimple SimHumidifier SimHVAC SimHWBaseboard SimHWConvective SimHXAssistedCoolingCoil SimICEngineGenerator SimICEPlantHeatRecovery SimIceStorage SimIndirectAbsorber SimIndUnit SimLowTempRadiantSystem SimMicroCHPGenerator SimMicroCHPPlantHeatRecovery SimMSHeatPump SimMSHP SimMTGenerator SimMTPlantHeatRecovery SimMultiSpeedCoils SimOAComponent SimOAController SimOAMixer SimOnOffFan SimOutdoorAirEquipComps SimOutdoorAirUnit SimOutsideAirSys SimOutsideEnergy SimPackagedTerminalUnit SimPipes SimPipesHeatTransfer SimPipingSystemCircuit SimPIU SimPlantEquip SimPlantValves SimpleCoolingCoilUAResidual SimpleEvapFluidCoolerUAResidual SimpleFluidCoolerUAResidual SimpleHeatingCoilUAResidual SimpleTowerApproachResidual SimpleTowerTrResidual SimpleTowerUAResidual SimPondGroundHeatExchanger SimPressureDropSystem SimPTUnit SimPumps SimPurchasedAir SimPVGenerator SimPVTcollectors SimReformulatedEIRChiller SimRefrigCondenser SimReturnAirPath SimSelectedEquipment SimSetPointManagers SimSimpleEvapFluidCooler SimSimpleFan SimSimpleFluidCooler SimSimpleTower SimSolarCollector SimStandAloneERV SimSteamBaseboard SimSteamBoiler SimSteamCoils SimSurfaceGroundHeatExchanger SimSysAvailManager SimTESCoil SimTowers SimTranspiredCollector SimulateAllInteriorRadialSoilSlices SimulateAllLoopSideBranches SimulateAllLoopSidePumps SimulateDemandManagerList SimulateDetailedRefrigerationSystems SimulateDetailedTransRefrigSystems SimulateDualDuct SimulateFanComponents SimulateFluidCell SimulateHeatingCoilComponents SimulateInnerMostRadialSoilSlice SimulateLoopSideBranchGroup SimulateOuterMostRadialSoilSlice SimulatePlantProfile SimulateRadialInsulationCell SimulateRadialPipeCell SimulateRadialToCartesianInterface SimulateSingleDuct SimulateSteamCoilComponents SimulateVRF SimulateWaterCoilComponents SimulateWaterHeaterStandAlone SimulateWaterUse SimulateWaterUseConnection SimUnitaryBypassVAV SimUnitarySystem SimUnitHeater SimUnitVentilator SimUnitVentOAMixer SimUserDefinedPlantComponent SimVariableSpeedCoils SimVariableSpeedHP SimVariableSpeedHP SimVariableTower SimVariableVolumeFan SimVAV SimVAVVS SimVentilatedSlab SimVentSlabOAMixer SimVRF SimVRFCondenserPlant SimWaterCoils SimWaterSource SimWaterThermalTank SimWatertoAirHP SimWatertoAirHPSimple SimWindowAC SimWindTurbine SimZoneAirLoopEquipment SimZoneAirUserDefined SimZoneDehumidifier SimZoneEquipment SimZoneEvaporativeCoolerUnit SimZoneExhaustFan SimZoneOutAirUnitComps SingelSpeedDXCoolingCoilStandardRatings SingleSpeedDXHeatingCoilStandardRatings SingleSpeedFluidCooler SizeAbsorpChiller SizeAirLoopBranches SizeAirLoops SizeBaseboard SizeBoiler SizeBoiler SizeCBVAV SizeConstCOPChiller SizeController SizeCoolBeam SizeDemandSidePlantConnections SizeDirectAir SizeDualDuct SizeDXCoil SizeElecReformEIRChiller SizeElectricBaseboard SizeElectricBaseboard SizeElectricChiller SizeElectricEIRChiller SizeEngineDrivenChiller SizeEvapCooler SizeEvapFluidCooler SizeExhaustAbsorber SizeFan SizeFanCoilUnit SizeFluidCooler SizeFluidHeatExchanger SizeFurnace SizeGasAbsorber SizeGTChiller SizeHeatingCoil SizeHeatRecovery SizeHighTempRadiantSystem SizeHumidifier SizeHVACWaterToAir SizeHWBaseboard SizeIndirectAbsorpChiller SizeIndUnit SizeLowTempRadiantSystem SizeMSHeatPump SizeOAController SizeOutdoorAirUnit SizePIU SizePlantLoop SizePTUnit SizePump SizePurchasedAir SizePVT SizeStandAloneERV SizeStandAloneWaterHeater SizeSteamBaseboard SizeSteamCoil SizeSupplySidePlantConnections SizeSys SizeTankForDemandSide SizeTankForSupplySide SizeTESCoil SizeTower SizeUCSDUF SizeUnitarySystem SizeUnitHeater SizeUnitVentilator SizeVarSpeedCoil SizeVentilatedSlab SizeVRF SizeVRFCondenser SizeVSMerkelTower SizeWaterCoil SizeWaterManager SizeWaterSource SizeWindowAC SizeWrapper SizeZoneDehumidifier SizeZoneEquipment SizeZoneEvaporativeCoolerUnit SkipEPlusWFHeader SkyDifSolarShading SkyGndWeight SkyWeight SLtoAMB SLtoGL SLVSKY solar_EN673 solarISO15099 SolarSprectrumAverage SOLMATS SolveAirLoopControllers SolveForWindowTemperatures SolveRegression SolveRegulaFalsi SolverMoistureBalanceEMPD SOLVZP SortHistory Specular_Adjust Specular_EstimateDiffuseProps Specular_F Specular_OffNormal Specular_RATDiff Specular_SWP SQLiteBegin SQLiteBegin SQLiteBindDouble SQLiteBindInteger SQLiteBindLogicalMacro SQLiteBindNULL SQLiteBindText SQLiteBindTextMacro SQLiteClearBindings SQLiteCloseDatabase SQLiteColumnInt SQLiteColumnIntMacro SQLiteCommit SQLiteCommit SQLiteExecuteCommand SQLiteExecuteCommandMacro SQLiteFinalizeCommand SQLiteOpenDatabase SQLiteOpenDatabaseMacro SQLitePrepareStatement SQLitePrepareStatementMacro SQLiteResetCommand SQLiteStepCommand SQLiteWriteMessage SQLiteWriteMessageMacro SQLiteWriteMessageMacro StandardIndexTypeKey StandardVariableTypeKey StartingWindowTemps StartingWinTempsForNominalCond SteamHeatingCoilResidual StorageType StoreAPumpOnCurrentTempLoop storeIterationResults StoreRecurringErrorMessage StringValue StrToReal SumAllInternalCO2Gains SumAllInternalConvectionGains SumAllInternalGenericContamGains SumAllInternalLatentGains SumAllInternalRadiationGains SumAllReturnAirConvectionGains SumAllReturnAirLatentGains SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumInternalCO2GainsByTypes SumInternalConvectionGainsByTypes SumInternalLatentGainsByTypes SumInternalRadiationGainsByTypes SummarizeErrors SumReturnAirConvectionGainsByTypes SumZoneImpacts SUN3 SUN4 SupSATResidual SurfaceScheduledSolarInc SurveyDemandManagers SystemPropertiesAtLambdaAndPhi SystemSpectralPropertiesAtPhi TableLookupObject TARCOG90 TBND TdbFnHRhPb TDMA TDMA_R TellMeHowManyObjectItemArgs TemperaturesFromEnergy TempIPtoSI TempSItoIP terpld TESCoilHumRatResidual TESCoilResidual TestAirPathIntegrity TestBranchIntegrity TestCompSet TestCompSetInletOutletNodes TestInletOutletNodes TestReturnAirPathIntegrity TestSupplyAirPathIntegrity therm1d TightenNodeMinMaxAvails TimestepInitComplexFenestration TimestepTypeName TraceAirLoopController TraceAirLoopControllers TraceIndividualController TraceIterationStamp TrackAirLoopController TrackAirLoopControllers TRadC TransAndReflAtPhi TransformVertsByAspect TransTDD Triangulate TrimSigDigits TurnOffLoopEquipment TurnOffLoopSideEquipment TurnOffReportRangeCheckErrors TurnOnPlantLoopPipes TurnOnReportRangeCheckErrors TwoSpeedFluidCooler UnitarySystemHeatRecovery UpdateAbsorberChillerComponentGeneratorSide UpdateAirflowNetwork UpdateAirMixer UpdateAirSysCompPtrArray UpdateAirSysSubCompPtrArray UpdateAirSysSubSubCompPtrArray UpdateAirZoneReturnPlenum UpdateAirZoneSupplyPlenum UpdateAnyLoopDemandAlterations UpdateATMixer UpdateBaseboard UpdateBaseboardPlantConnection UpdateBasementSurfaceTemperatures UpdateBBElecRadSourceValAvg UpdateBBRadSourceValAvg UpdateBBSteamRadSourceValAvg UpdateBLASTAbsorberRecords UpdateBoilerRecords UpdateBoilerRecords UpdateBracket UpdateBranchConnections UpdateChillerComponentCondenserSide UpdateChillerheaterRecords UpdateChillerRecords UpdateColdWeatherProtection UpdateCommonPipe UpdateComplexWindows UpdateComponentHeatRecoverySide UpdateConstCOPChillerRecords UpdateController UpdateCoolBeam UpdateCoolTower UpdateCTGeneratorRecords UpdateDataandReport UpdateDemandManagers UpdateDesiccantDehumidifier UpdateDetailedIceStorage UpdateDualDuct UpdateDuct UpdateDXCoil UpdateElectricBaseboard UpdateElectricChillerRecords UpdateElectricEIRChillerRecords UpdateEMSTrendVariables UpdateEngineDrivenChiller UpdateEvapCooler UpdateEvapFluidCooler UpdateEvaporativeCondenserBasinHeater UpdateEvaporativeCondenserWaterUse UpdateExhaustAbsorberCoolRecords UpdateExhaustAbsorberHeatRecords UpdateExhaustAirFlows UpdateFan UpdateFinalSurfaceHeatBalance UpdateFluidCooler UpdateFluidHeatExchanger UpdateFuelCellGeneratorRecords UpdateGasAbsorberCoolRecords UpdateGasAbsorberHeatRecords UpdateGSHPRecords UpdateGSHPRecords UpdateGSHPRecords UpdateGTChillerRecords UpdateHalfLoopInletTemp UpdateHeatBalHAMT UpdateHeatingCoil UpdateHeatRecovery UpdateHighTempRadiantSystem UpdateHistories UpdateHistory UpdateHTRadSourceValAvg UpdateHumidifier UpdateHVACInterface UpdateHWBaseboard UpdateHWBaseboardPlantConnection UpdateIceFractions UpdateICEngineGeneratorRecords UpdateIndirectAbsorberRecords UpdateInternalGainValues UpdateIrrigation UpdateLoadCenterRecords UpdateLoopSideReportVars UpdateLowTempRadiantSystem UpdateMeterReporting UpdateMeters UpdateMeterValues UpdateMicroCHPGeneratorRecords UpdateMinMax UpdateMixedAirSetPoints UpdateMoistureBalanceEMPD UpdateMoistureBalanceFD UpdateMSHeatPump UpdateMTGeneratorRecords UpdateNode UpdateNodeThermalHistory UpdateOAController UpdateOAMixer UpdateOAPretreatSetPoints UpdatePipesHeatTransfer UpdatePipingSystems UpdatePlantLoopInterface UpdatePlantMixer UpdatePlantProfile UpdatePlantSplitter UpdatePlantValves UpdatePondGroundHeatExchanger UpdatePrecipitation UpdatePressureDrop UpdatePurchasedAir UpdatePVTcollectors UpdateRadSysSourceValAvg UpdateRecords UpdateReformEIRChillerRecords UpdateRefrigCondenser UpdateReportWaterSystem UpdateRootFinder UpdateScheduleValues UpdateSetPointManagers UpdateSimpleWatertoAirHP UpdateSoilProps UpdateSolarCollector UpdateSplitter UpdateSQLiteErrorRecord UpdateSQLiteErrorRecord UpdateSQLiteSimulationRecord UpdateSQLiteSimulationRecord UpdateSteamBaseboard UpdateSteamBaseboardPlantConnection UpdateSteamCoil UpdateSurfaceGroundHeatExchngr UpdateSys UpdateSysSizing UpdateSystemOutputRequired UpdateTabularReports UpdateTEStorage UpdateThermalHistories UpdateTowers UpdateTranspiredCollector UpdateUnitarySystemControl UpdateUtilityBills UpdateVarSpeedCoil UpdateVentilatedSlab UpdateVerticalGroundHeatExchanger UpdateVRFCondenser UpdateWaterCoil UpdateWaterConnections UpdateWaterManager UpdateWaterSource UpdateWaterThermalTank UpdateWaterToAirCoilPlantConnection UpdateWatertoAirHP UpdateWeatherData UpdateWholeBuildingRecords UpdateZoneAirLoopEquipment UpdateZoneCompPtrArray UpdateZoneDehumidifier UpdateZoneEquipment UpdateZoneInletConvergenceLog UpdateZoneListAndGroupLoads UpdateZoneSizing UpdateZoneSubCompPtrArray UpdateZoneSubSubCompPtrArray ValidateAndSetSysAvailabilityManagerType ValidateComponent ValidateDistributionSystem ValidateEMSProgramName ValidateEMSVariableName ValidateExhaustFanInput ValidateFlowControlPaths ValidateFuelType ValidateIndexType ValidateMaterialRoughness ValidateMonthDay ValidateNStandardizeMeterTitles ValidateObjectandParse ValidatePipeConstruction ValidatePLFCurve ValidateSection ValidateSectionsInput ValidateVariableType value_to_vector ValueToString VAVVSCoolingResidual VAVVSHCFanOnResidual VAVVSHWFanOnResidual VAVVSHWNoFanResidual VB_CriticalSlatAngle VB_DIFF VB_LWP VB_ShadeControl VB_SLAT_RADIUS_RATIO VB_SOL4 VB_SOL46_CURVE VB_SOL6 VB_SWP vec2d_cross_product vec2d_dot_product vec_cross_product vec_dot_product VecLength VecNegate VecNormalize VecRound VecSquaredLength vector_add vector_div_int vector_div_real vector_subtract vector_times_int vector_times_real vector_to_array VerifyControlledZoneForThermostat VerifyCustomMetersElecPowerMgr VerifyHeatExchangerParent VerifyName VerifySetPointManagers VerifyThermostatInZone VerifyUniqueBaseboardName VerifyUniqueBoilerName VerifyUniqueChillerName VerifyUniqueCoilName ViewFac VisibleSprectrumAverage Volume VRMLOut VSCoilCyclingHumResidual VSCoilCyclingResidual VSCoilCyclingResidual VSCoilSpeedHumResidual VSCoilSpeedResidual VSCoilSpeedResidual VSEvapUnitLoadResidual VSHPCyclingResidual VSHPCyclingResidual VSHPSpeedResidual VSHPSpeedResidual VSMerkelResidual W5InitGlassParameters W5LsqFit W5LsqFit2 W6CoordsFromWorldVect warnIfNativeVarname WetCoilOutletCondition WhichCompSet WhichParentCompSet WhichParentSet Width WindowGapAirflowControl WindowGasConductance WindowGasPropertiesAtTemp WindowHeatBalanceEquations WindowScheduledSolarAbs WindowShadingManager WindowTempsForNominalCond WindSpeedAt Windward WorldVectFromW6 WriteAdaptiveComfortTable WriteAirLoopStatistics WriteBEPSTable WriteCompCostTable WriteComponentSizing WriteCumulativeReportMeterData WriteDaylightMapTitle WriteDemandEndUseSummary WriteInputArguments WriteIntegerData WriteIntegerVariableOutput WriteMeterDictionaryItem WriteModifiedArguments WriteMonthlyTables WriteOutputArguments WriteOutputEN673 WritePoint WritePredefinedTables WriteRealData WriteRealVariableOutput WriteReportHeaders WriteReportIntegerData WriteReportMeterData WriteReportRealData WriteReportVariableDictionaryItem WriteRootFinderStatus WriteRootFinderTrace WriteRootFinderTraceHeader WriteSourceEnergyEndUseSummary writeSubtitle WriteSurfaceShadowing WriteTable WriteTableOfContents WriteTabularLifeCycleCostReport WriteTabularReports WriteTabularTariffReports WriteTARCOGInputFile writeTextLine WriteTimeBinTables WriteTimeStampFormatData WriteTrace WriteVeriSumTable WriteZoneLoadComponentTable WVDC XNormalArea XYRectangle XZRectangle YNormalArea YZRectangle ZeroHVACValues ZNormalArea
Call graph
gettescoilinput calls verifyname, calphafieldnames, getonlysinglenode, getcurveindex, setuptankdemandcomponent, setupemsactuator, calphaargs, findcontrolledzoneindexfromsystemnodenumberforzone, setupoutputvariable, samestring, checkfluidpropertyname, showcontinueerror, getfluiddensitytemperaturelimits, setupzoneinternalgain, getfluidspecificheattemperaturelimits, lalphafieldblanks, verifyuniquecoilname, rnumericargs, showsevereerror, cnumericfieldnames, lnumericfieldblanks, showfatalerror, findglycol, getscheduleindex, setuptanksupplycomponent, getnumobjectsfound, getobjectitem, getcurveobjecttypenum, testcompset
getcurveindex calls getpressuresysteminput, getcurveinput, finditeminlist
getpressuresysteminput calls verifyname, lnumericfieldblanks, getnumobjectsfound, getobjectitem, finditeminlist, showcontinueerror, pressurecurve, showsevereerror, showfatalerror
getcurveinput calls verifyname, calphafieldnames, lalphafieldblanks, cnumericfieldnames, lnumericfieldblanks, getnumobjectsfound, getobjectitem, finditeminlist, showcontinueerror, showsevereerror, showfatalerror, roundsigdigits, showwarningerror, getobjectdefmaxargs, solveregression, readtabledata, iscurveoutputtypevalid, iscurveinputtypevalid
showcontinueerror calls showerrormessage, updatesqliteerrorrecord
showsevereerror calls showerrormessage, matchcounts, messagesearch, createsqliteerrorrecord
showfatalerror calls showerrormessage, displaystring, createsqliteerrorrecord, abortenergyplus, roundsigdigits
showerrormessage calls showfatalerror, displaystring
abortenergyplus calls displaystring, roundsigdigits, testairpathintegrity, updatesqlitesimulationrecord, checkmarkednodes, reportairloopconnections, showrecurringerrors, testcompsetinletoutletnodes, summarizeerrors, reportsurfaceerrors, reportloopconnections, closemiscopenfiles, setupnodevarsforreporting, closesocket, closeoutopenfiles, reportsurfaces, testbranchintegrity, checkplantonabort, epelapsedtime, epstoptime, epsummarytimes, showmessage, checknodeconnections
testairpathintegrity calls showcontinueerror, showsevereerror, airtozonenodeinfo, nodeid
showrecurringerrors calls updatesqliteerrorrecord, createsqliteerrorrecord, roundsigdigits, showmessage, removetrailingzeros, recurringerrors
summarizeerrors calls matchcounts, showmessage, summaries, moredetails
closemiscopenfiles calls closedfsfile, closereportillummaps
reportsurfaces calls detailsforsurfaces, setupschemecolors, vrmlout, scanforreports, dxfoutwireframe, costinfoout, linesout, showwarningerror, dxfout
epstoptime calls showfatalerror, tstop
epsummarytimes calls roundsigdigits
showmessage calls showerrormessage
detailsforsurfaces calls roundsigdigits, getschedulename, oscm, nominalu, zone, framedivider, getschedulemaxvalue, 2, computenominaluwithconvcoeffs, 3, osc, trimsigdigits, construct, 4, csurfaceclass, userintconvectioncoeffs, userextconvectioncoeffs, surface, getscheduleminvalue, surfacewindow
setupschemecolors calls getobjectitem, showwarningerror, getobjectitemnum, getobjectdefmaxargs, matchandsetcolortextstring
vrmlout calls showcontinueerror, showfatalerror, showwarningerror, zone, surface, triangulate, getnewunitnumber
dxfoutwireframe calls showfatalerror, zone, trimsigdigits, surface, surfacewindow, getnewunitnumber, zonedaylight, dxfcolorno
costinfoout calls showfatalerror, construct, csurfaceclass, surface, getnewunitnumber
linesout calls showcontinueerror, showfatalerror, roundsigdigits, showwarningerror, csurfaceclass, surface, getnewunitnumber
showwarningerror calls showerrormessage, matchcounts, messagesearch, createsqliteerrorrecord
dxfout calls showcontinueerror, showfatalerror, showwarningerror, zone, trimsigdigits, surface, surfacewindow, triangulate, getnewunitnumber, zonedaylight, dxfcolorno, illummapcalc
computenominaluwithconvcoeffs calls surface
matchandsetcolortextstring calls finditem
triangulate calls showcontinueerror, roundsigdigits, showmessage, showwarningerror, csurfaceclass, generate_ears, calcrfflrcoordinatetransformation, calcwallcoordinatetransformation
generate_ears calls polygon_contains_point_2d, angle_2dvector
solveregression calls showcontinueerror, showsevereerror, roundsigdigits, trimsigdigits
readtabledata calls showcontinueerror, showsevereerror, showfatalerror, roundsigdigits, showwarningerror, checkforactualfilename, 10
iscurveoutputtypevalid calls samestring
iscurveinputtypevalid calls samestring
gettescoilindex calls gettescoilinput
simtescoil calls gettescoilinput