GetZoneAirSetpoints – EnergyPlusFortran
GetZoneAirSetpoints Subroutine
1365 statements
Source File
private subroutine GetZoneAirSetpoints()
Uses:
DataIPShortCuts
InputProcessor
ScheduleManager
General
Arguments
None
Calls
Called By
Source Code
GetZoneAirSetpoints
Source Code
SUBROUTINE GetZoneAirSetpoints
          ! SUBROUTINE INFORMATION:
          !       AUTHOR         Russell Taylor
          !       DATE WRITTEN   September 1998
          !       MODIFIED       L.Gu, May 2006, B. Griffith June 2006
          !       RE-ENGINEERED  na
          ! PURPOSE OF THIS SUBROUTINE:
          ! This subroutine gets the inputs related to thermostatic control.
          ! METHODOLOGY EMPLOYED:
          ! Uses the status flags to trigger events.
          ! REFERENCES:
          ! na
          ! USE STATEMENTS:
  USE DataIPShortCuts
  USE InputProcessor
  USE ScheduleManager, ONLY: GetScheduleIndex, CheckScheduleValueMinMax, GetScheduleMinValue, GetScheduleMaxValue,  &
                             CheckScheduleValue
  USE General, ONLY: TrimSigDigits, FindNumberInList, RoundSigDigits, CheckCreatedZoneItemName
  IMPLICIT NONE ! Enforce explicit typing of all variables in this routine
          ! SUBROUTINE ARGUMENT DEFINITIONS:
          ! na
          ! SUBROUTINE PARAMETER DEFINITIONS:
  CHARACTER(len=*), PARAMETER :: RoutineName='GetZoneAirSetpoints: '
          ! INTERFACE BLOCK SPECIFICATIONS:
          ! na
          ! DERIVED TYPE DEFINITIONS:
  TYPE NeededControlTypes
    LOGICAL, DIMENSION(4) :: MustHave=.false.  ! 4= the four control types
    LOGICAL, DIMENSION(4) :: DidHave =.false.
  END TYPE
  TYPE NeededComfortControlTypes
    LOGICAL, DIMENSION(12) :: MustHave=.false.  ! 4= the four control types
    LOGICAL, DIMENSION(12) :: DidHave =.false.
  END TYPE
          ! SUBROUTINE LOCAL VARIABLE DECLARATIONS:
  INTEGER :: TempControlledZoneNum      ! The Splitter that you are currently loading input into
  INTEGER :: NumAlphas
  INTEGER :: NumNums
  INTEGER :: SingleTempHeatingControlNum
  INTEGER :: SingleTempCoolingControlNum
  INTEGER :: SingleTempHeatCoolControlNum
  INTEGER :: DualTempHeatCoolControlNum
  INTEGER :: ControlTypeNum
  INTEGER :: IOSTAT
!unused1208  REAL(r64), DIMENSION(2) :: NumArray
!unused1208  CHARACTER(len=MaxNameLength), DIMENSION(29) :: AlphArray
  LOGICAL :: ErrorsFound = .FALSE.
  LOGICAL :: ErrFlag
  LOGICAL :: IsNotOK               ! Flag to verify name
  LOGICAL :: IsBlank               ! Flag for blank name
  INTEGER :: CTIndex
  INTEGER :: HumidControlledZoneNum      ! The Humidity Controller that information is being loaded into
  LOGICAL :: ValidScheduleControlType
  LOGICAL :: ValidRadFractSched          ! check for if radiative fraction schedule has valid numbers
  LOGICAL :: ValidZoneOvercoolRangeSched ! check for if Zone Overcool range schedule has valid numbers
  INTEGER :: TempIndex
  INTEGER :: SchedMin
  INTEGER :: SchedMax
  INTEGER :: ActualZoneNum
  INTEGER :: SchedTypeIndex
  INTEGER :: ComfortControlledZoneNum      ! The Splitter that you are currently loading input into
  INTEGER :: I, IZoneCount
  INTEGER :: OpTempContrlNum  ! do loop index
  INTEGER :: found
  INTEGER :: TempHumidityCntrlNum   ! do loop index for overcooled controlled zone
  INTEGER :: SingleFangerHeatingControlNum
  INTEGER :: SingleFangerCoolingControlNum
  INTEGER :: SingleFangerHeatCoolControlNum
  INTEGER :: DualFangerHeatCoolControlNum
  INTEGER :: ComfortIndex
  INTEGER :: ZoneAssigned
  INTEGER :: NumStageControlledZones ! Number of staged controlled objects
  INTEGER :: StageControlledZoneNum  ! Index for staged controlled zones
  TYPE (NeededControlTypes), ALLOCATABLE, DIMENSION(:) :: TStatControlTypes
  TYPE (NeededComfortControlTypes), ALLOCATABLE, DIMENSION(:) :: TComfortControlTypes
  INTEGER, ALLOCATABLE, DIMENSION(:) :: CTSchedMapToControlledZone
  INTEGER, ALLOCATABLE, DIMENSION(:) :: CCmSchedMapToControlledZone
  INTEGER :: Item
  INTEGER :: Item1
  INTEGER :: ZLItem
          ! FLOW:
  cCurrentModuleObject=cZControlTypes(iZC_TStat)
  NumTStatStatements = GetNumObjectsFound(cCurrentModuleObject)
  ALLOCATE(TStatObjects(NumTStatStatements))
! Pre-scan for use of Zone lists in TStat statements (i.e. Global application of TStat)
  NumTempControlledZones=0
  DO Item=1,NumTStatStatements
    CALL GetObjectItem(cCurrentModuleObject,Item,cAlphaArgs,NumAlphas,rNumericArgs,NumNums,IOSTAT, &
                       NumBlank=lNumericFieldBlanks,AlphaBlank=lAlphaFieldBlanks, &
                       AlphaFieldNames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
    IsNotOK = .FALSE.
    IsBlank = .FALSE.
    CALL VerifyName(cAlphaArgs(1),TStatObjects%Name,Item-1,IsNotOK,IsBlank, &
                    trim(cCurrentModuleObject)//' Name')
    IF (IsNotOK) THEN
      ErrorsFound = .TRUE.
      IF (IsBlank) cAlphaArgs(1) = 'xxxxx'
    END IF
    TStatObjects(Item)%Name=cAlphaArgs(1)
    Item1=FindItemInList(cAlphaArgs(2),Zone%Name,NumOfZones)
    ZLItem=0
    IF (Item1 == 0 .and. NumOfZoneLists > 0) &
        ZLItem=FindItemInList(cAlphaArgs(2),ZoneList%Name,NumOfZoneLists)
    IF (Item1 > 0) THEN
      TStatObjects(Item)%TempControlledZoneStartPtr=NumTempControlledZones+1
      NumTempControlledZones=NumTempControlledZones+1
      TStatObjects(Item)%NumOfZones=1
      TStatObjects(Item)%ZoneListActive=.false.
      TStatObjects(Item)%ZoneOrZoneListPtr=Item1
    ELSEIF (ZLItem > 0) THEN
      TStatObjects(Item)%TempControlledZoneStartPtr=NumTempControlledZones+1
      NumTempControlledZones=NumTempControlledZones+ZoneList(ZLItem)%NumOfZones
      TStatObjects(Item)%NumOfZones=ZoneList(ZLItem)%NumOfZones
      TStatObjects(Item)%ZoneListActive=.true.
      TStatObjects(Item)%ZoneOrZoneListPtr=ZLItem
    ELSE
      CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
           trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" not found.')
      ErrorsFound=.true.
    ENDIF
  ENDDO
  IF (ErrorsFound) THEN
    CALL ShowSevereError('GetZoneAirSetpoints: Errors with invalid names in '//trim(cCurrentModuleObject)//  &
       ' objects.')
    CALL ShowContinueError('...These will not be read in.  Other errors may occur.')
    NumTempControlledZones=0
  ENDIF
  IF (NumTempControlledZones > 0) THEN
    ALLOCATE(TempControlledZone(NumTempControlledZones))
    ALLOCATE(TStatControlTypes(NumTempControlledZones))  ! Number of set point types
    ALLOCATE(CTSchedMapToControlledZone(NumTempControlledZones))
    CTSchedMapToControlledZone=0
    TempControlledZoneNum = 0
    DO Item = 1, NumTStatStatements
      CALL GetObjectItem(cCurrentModuleObject,Item,cAlphaArgs,NumAlphas,rNumericArgs,NumNums,IOSTAT, &
                         NumBlank=lNumericFieldBlanks,AlphaBlank=lAlphaFieldBlanks, &
                         AlphaFieldNames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
      DO Item1=1,TStatObjects(Item)%NumOfZones
        TempControlledZoneNum=TempControlledZoneNum+1
        IF (TStatObjects(Item)%ZoneListActive) THEN
          cAlphaArgs(2)=Zone(ZoneList(TStatObjects(Item)%ZoneOrZoneListPtr)%Zone(Item1))%Name
        ENDIF
        ZoneAssigned=FindItemInList(cAlphaArgs(2),TempControlledZone%ZoneName,TempControlledZoneNum-1)
        IF (ZoneAssigned == 0) THEN
          TempControlledZone(TempControlledZoneNum)%ZoneName = cAlphaArgs(2)
          TempControlledZone(TempControlledZoneNum)%ActualZoneNum = FindIteminList(cAlphaArgs(2),Zone%Name,NumOfZones)
          IF (TempControlledZone(TempControlledZoneNum)%ActualZoneNum == 0) THEN
            CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
               trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" not found.')
            ErrorsFound = .TRUE.
          ELSE
            Zone(TempControlledZone(TempControlledZoneNum)%ActualZoneNum)%TempControlledZoneIndex = TempControlledZoneNum
          END IF
        ELSE
          TempControlledZone(TempControlledZoneNum)%ZoneName = cAlphaArgs(2)  ! for continuity
          CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
             trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" zone previously assigned.')
          CALL ShowContinueError('...Zone was previously assigned to Thermostat="'//  &
             trim(TempControlledZone(ZoneAssigned)%Name)//'".')
          ErrorsFound = .TRUE.
          CYCLE
        ENDIF
        IF (.not. TStatObjects(Item)%ZoneListActive) THEN
          TempControlledZone(TempControlledZoneNum)%Name = cAlphaArgs(1)
        ELSE
          CALL CheckCreatedZoneItemName(RoutineName,cCurrentModuleObject,  &
                                        Zone(ZoneList(TStatObjects(Item)%ZoneOrZoneListPtr)%Zone(Item1))%Name,  &
                                        ZoneList(TStatObjects(Item)%ZoneOrZoneListPtr)%MaxZoneNameLength,  &
                                        TStatObjects(Item)%Name,     &
                                        TempControlledZone%Name,           &
                                        TempControlledZoneNum-1,                       &
                                        TempControlledZone(TempControlledZoneNum)%Name,            &
                                        ErrFlag)
          IF (ErrFlag) ErrorsFound=.true.
        ENDIF
        TempControlledZone(TempControlledZoneNum)%ControlTypeSchedName = cAlphaArgs(3)
        TempControlledZone(TempControlledZoneNum)%CTSchedIndex=GetScheduleIndex(cAlphaArgs(3))
        IF (Item1 == 1) THEN  ! only show error on first of several if zone list
          IF (TempControlledZone(TempControlledZoneNum)%CTSchedIndex == 0) THEN
            CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
               trim(cAlphaFieldNames(3))//'="'//trim(cAlphaArgs(3))//'" not found.')
            ErrorsFound = .TRUE.
          ELSE
            ! Check validity of control types.
            ValidScheduleControlType=CheckScheduleValueMinMax(TempControlledZone(TempControlledZoneNum)%CTSchedIndex,  &
                                                               '>=',0.0d0,'<=',4.0d0)
            IF (.not. ValidScheduleControlType) THEN
              CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid range '//  &
                 trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'"')
              CALL ShowContinueError('..contains values outside of range [0,4].')
              ErrorsFound=.TRUE.
            ENDIF
          END IF
        ENDIF
        TempControlledZone(TempControlledZoneNum)%NumControlTypes = NINT((NumAlphas - 3.0d0)/2.0d0)
        ALLOCATE(TempControlledZone(TempControlledZoneNum)%ControlType(TempControlledZone(  &
           TempControlledZoneNum)%NumControlTypes))
        ALLOCATE(TempControlledZone(TempControlledZoneNum)%ControlTypeName(TempControlledZone(  &
           TempControlledZoneNum)%NumControlTypes))
        ALLOCATE(TempControlledZone(TempControlledZoneNum)%ControlTypeSchIndx(TempControlledZone(  &
                                                                                TempControlledZoneNum)%NumControlTypes))
        DO ControlTypeNum = 1, TempControlledZone(TempControlledZoneNum)%NumControlTypes
          TempControlledZone(TempControlledZoneNum)%ControlType(ControlTypeNum) = cAlphaArgs(NINT(2.0d0*ControlTypeNum-1+3))
          TempControlledZone(TempControlledZoneNum)%ControlTypeName(ControlTypeNum) = cAlphaArgs(NINT(2.0d0*ControlTypeNum+3))
          IF (TempControlledZone(TempControlledZoneNum)%ControlType(ControlTypeNum) /= ' ') THEN
            CTIndex=FindItem(TempControlledZone(TempControlledZoneNum)%ControlType(ControlTypeNum),ValidControlTypes,4)
            IF (CTIndex == 0) THEN
              CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
                 trim(cAlphaFieldNames(NINT(2.0d0*ControlTypeNum-1+3)))//'="'//  &
                    trim(cAlphaArgs(NINT(2.0d0*ControlTypeNum-1+3)))//'"')
              ErrorsFound = .TRUE.
            END IF
          ELSE
            CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
                 trim(cAlphaFieldNames(NINT(2.0d0*ControlTypeNum-1+3)))//'="<blank>"')
            ErrorsFound = .TRUE.
          ENDIF
          TempControlledZone(TempControlledZoneNum)%ControlTypeSchIndx(ControlTypeNum) = 0
        END DO
      END DO
    END DO ! NumTStatStatements
  ENDIF ! Check on number of TempControlledZones
  cCurrentModuleObject=ValidControlTypes(SglHeatSetPoint)
  NumSingleTempHeatingControls = GetNumObjectsFound(cCurrentModuleObject)
  IF (NumSingleTempHeatingControls .GT. 0) ALLOCATE(SetPointSingleHeating(NumSingleTempHeatingControls))
  DO SingleTempHeatingControlNum = 1, NumSingleTempHeatingControls
    CALL GetObjectItem(cCurrentModuleObject,SingleTempHeatingControlNum,cAlphaArgs,NumAlphas,rNumericArgs,NumNums,IOSTAT, &
                       NumBlank=lNumericFieldBlanks,AlphaBlank=lAlphaFieldBlanks, &
                       AlphaFieldNames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
    IsNotOK = .FALSE.
    IsBlank = .FALSE.
    CALL VerifyName(cAlphaArgs(1),SetPointSingleHeating%Name,SingleTempHeatingControlNum-1,IsNotOK,IsBlank, &
                    trim(cCurrentModuleObject)//' Name')
    IF (IsNotOK) THEN
      ErrorsFound = .TRUE.
      IF (IsBlank) cAlphaArgs(1) = 'xxxxx'
    END IF
    SetPointSingleHeating(SingleTempHeatingControlNum)%Name = cAlphaArgs(1)
    SetPointSingleHeating(SingleTempHeatingControlNum)%TempSchedName = cAlphaArgs(2)
    SetPointSingleHeating(SingleTempHeatingControlNum)%TempSchedIndex = GetScheduleIndex(cAlphaArgs(2))
    IF (SetPointSingleHeating(SingleTempHeatingControlNum)%TempSchedIndex == 0) THEN
      CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
         trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" not found.')
      ErrorsFound = .TRUE.
    END IF
  END DO ! SingleTempHeatingControlNum
  cCurrentModuleObject=ValidControlTypes(SglCoolSetPoint)
  NumSingleTempCoolingControls = GetNumObjectsFound(cCurrentModuleObject)
  IF (NumSingleTempCoolingControls .GT. 0) ALLOCATE(SetPointSingleCooling(NumSingleTempCoolingControls))
  DO SingleTempCoolingControlNum = 1, NumSingleTempCoolingControls
    CALL GetObjectItem(cCurrentModuleObject,SingleTempCoolingControlNum,cAlphaArgs,NumAlphas,rNumericArgs,NumNums,IOSTAT, &
                       NumBlank=lNumericFieldBlanks,AlphaBlank=lAlphaFieldBlanks, &
                       AlphaFieldNames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
    IsNotOK = .FALSE.
    IsBlank = .FALSE.
    CALL VerifyName(cAlphaArgs(1),SetPointSingleCooling%Name,SingleTempCoolingControlNum-1,IsNotOK,IsBlank, &
                    trim(cCurrentModuleObject)//' Name')
    IF (IsNotOK) THEN
      ErrorsFound = .TRUE.
      IF (IsBlank) cAlphaArgs(1) = 'xxxxx'
    END IF
    SetPointSingleCooling(SingleTempCoolingControlNum)%Name = cAlphaArgs(1)
    SetPointSingleCooling(SingleTempCoolingControlNum)%TempSchedName = cAlphaArgs(2)
    SetPointSingleCooling(SingleTempCoolingControlNum)%TempSchedIndex = GetScheduleIndex(cAlphaArgs(2))
    IF (SetPointSingleCooling(SingleTempCoolingControlNum)%TempSchedIndex == 0) THEN
      CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
         trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" not found.')
      ErrorsFound = .TRUE.
    END IF
  END DO ! SingleTempCoolingControlNum
  cCurrentModuleObject=ValidControlTypes(SglHCSetPoint)
  NumSingleTempHeatCoolControls = GetNumObjectsFound(cCurrentModuleObject)
  IF (NumSingleTempHeatCoolControls .GT. 0) ALLOCATE(SetPointSingleHeatCool(NumSingleTempHeatCoolControls))
  DO SingleTempHeatCoolControlNum = 1, NumSingleTempHeatCoolControls
    CALL GetObjectItem(cCurrentModuleObject,SingleTempHeatCoolControlNum,cAlphaArgs,NumAlphas,rNumericArgs,NumNums,IOSTAT, &
                       NumBlank=lNumericFieldBlanks,AlphaBlank=lAlphaFieldBlanks, &
                       AlphaFieldNames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
    SetPointSingleHeatCool(SingleTempHeatCoolControlNum)%Name = cAlphaArgs(1)
    SetPointSingleHeatCool(SingleTempHeatCoolControlNum)%TempSchedName = cAlphaArgs(2)
    SetPointSingleHeatCool(SingleTempHeatCoolControlNum)%TempSchedIndex = GetScheduleIndex(cAlphaArgs(2))
    IF (SetPointSingleHeatCool(SingleTempHeatCoolControlNum)%TempSchedIndex == 0) THEN
      CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
         trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" not found.')
      ErrorsFound = .TRUE.
    END IF
  END DO ! SingleTempHeatCoolControlNum
  cCurrentModuleObject=ValidControlTypes(DualSetPoint)
  NumDualTempHeatCoolControls = GetNumObjectsFound(cCurrentModuleObject)
  IF (NumDualTempHeatCoolControls .GT. 0) ALLOCATE(SetPointDualHeatCool(NumDualTempHeatCoolControls))
  DO DualTempHeatCoolControlNum = 1, NumDualTempHeatCoolControls
    CALL GetObjectItem(cCurrentModuleObject,DualTempHeatCoolControlNum,cAlphaArgs,NumAlphas,rNumericArgs,NumNums,IOSTAT, &
                       NumBlank=lNumericFieldBlanks,AlphaBlank=lAlphaFieldBlanks, &
                       AlphaFieldNames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
    IsNotOK = .FALSE.
    IsBlank = .FALSE.
    CALL VerifyName(cAlphaArgs(1),SetPointDualHeatCool%Name,DualTempHeatCoolControlNum-1,IsNotOK,IsBlank, &
                    trim(cCurrentModuleObject)//' Name')
    IF (IsNotOK) THEN
      ErrorsFound = .TRUE.
      IF (IsBlank) cAlphaArgs(1) = 'xxxxx'
    END IF
    SetPointDualHeatCool(DualTempHeatCoolControlNum)%Name = cAlphaArgs(1)
    SetPointDualHeatCool(DualTempHeatCoolControlNum)%HeatTempSetptSchedName = cAlphaArgs(2)
    SetPointDualHeatCool(DualTempHeatCoolControlNum)%HeatTempSchedIndex = GetScheduleIndex(cAlphaArgs(2))
    IF (SetPointDualHeatCool(DualTempHeatCoolControlNum)%HeatTempSchedIndex == 0) THEN
      CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
         trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" not found.')
      ErrorsFound = .TRUE.
    END IF
    SetPointDualHeatCool(DualTempHeatCoolControlNum)%CoolTempSetptSchedName = cAlphaArgs(3)
    SetPointDualHeatCool(DualTempHeatCoolControlNum)%CoolTempSchedIndex = GetScheduleIndex(cAlphaArgs(3))
    IF (SetPointDualHeatCool(DualTempHeatCoolControlNum)%CoolTempSchedIndex == 0) THEN
      CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
         trim(cAlphaFieldNames(3))//'="'//trim(cAlphaArgs(3))//'" not found.')
      ErrorsFound = .TRUE.
    END IF
  END DO ! DualTempHeatCoolControlNum
 ! Finish filling in Schedule pointing indexes
  DO TempControlledZoneNum = 1, NumTempControlledZones
    TempIndex = FindItem(trim(ValidControlTypes(SglHeatSetPoint)),   &
       TempControlledZone(TempControlledZoneNum)%ControlType,TempControlledZone(TempControlledZoneNum)%NumControlTypes)
    TempControlledZone(TempControlledZoneNum)%SchIndx_SingleHeatSetPoint = TempIndex
    IF (TempIndex > 0) THEN
      TempControlledZone(TempControlledZoneNum)%ControlTypeSchIndx(TempIndex) =   &
                           FindItem(TempControlledZone(TempControlledZoneNum)%ControlTypeName(TempIndex), &
                                        SetPointSingleHeating%Name, NumSingleTempHeatingControls)
      TStatControlTypes(TempControlledZoneNum)%MustHave(SingleHeatingSetpoint)=.true.
    ENDIF
    TempIndex = FindItem(trim(ValidControlTypes(SglCoolSetPoint)),  &
      TempControlledZone(TempControlledZoneNum)%ControlType,TempControlledZone(TempControlledZoneNum)%NumControlTypes)
    TempControlledZone(TempControlledZoneNum)%SchIndx_SingleCoolSetPoint = TempIndex
    IF (TempIndex > 0) THEN
      TempControlledZone(TempControlledZoneNum)%ControlTypeSchIndx(TempIndex) =   &
                           FindItem(TempControlledZone(TempControlledZoneNum)%ControlTypeName(TempIndex), &
                                        SetPointSingleCooling%Name, NumSingleTempCoolingControls)
      TStatControlTypes(TempControlledZoneNum)%MustHave(SingleCoolingSetpoint)=.true.
    ENDIF
    TempIndex = FindItem(trim(ValidControlTypes(SglHCSetPoint)),  &
      TempControlledZone(TempControlledZoneNum)%ControlType,TempControlledZone(TempControlledZoneNum)%NumControlTypes)
    TempControlledZone(TempControlledZoneNum)%SchIndx_SingleHeatCoolSetPoint = TempIndex
    IF (TempIndex > 0) THEN
      TempControlledZone(TempControlledZoneNum)%ControlTypeSchIndx(TempIndex) =   &
                           FindItem(TempControlledZone(TempControlledZoneNum)%ControlTypeName(TempIndex), &
                                        SetPointSingleHeatCool%Name, NumSingleTempHeatCoolControls)
      TStatControlTypes(TempControlledZoneNum)%MustHave(SingleHeatCoolSetPoint)=.true.
    ENDIF
    TempIndex = FindItem(trim(ValidControlTypes(DualSetPoint)),  &
      TempControlledZone(TempControlledZoneNum)%ControlType,TempControlledZone(TempControlledZoneNum)%NumControlTypes)
    TempControlledZone(TempControlledZoneNum)%SchIndx_DualSetPointWDeadBand = TempIndex
    IF (TempIndex > 0) THEN
      TempControlledZone(TempControlledZoneNum)%ControlTypeSchIndx(TempIndex) =   &
                           FindItem(TempControlledZone(TempControlledZoneNum)%ControlTypeName(TempIndex), &
                                        SetPointDualHeatCool%Name, NumDualTempHeatCoolControls)
      TStatControlTypes(TempControlledZoneNum)%MustHave(DualSetPointWithDeadBand)=.true.
    ENDIF
  ENDDO
  ! Now, Check the schedule values/indices for validity
  DO TempControlledZoneNum = 1, NumTempControlledZones
    ActualZoneNum = TempControlledZone(TempControlledZoneNum)%ActualZoneNum
    CTIndex = TempControlledZone(TempControlledZoneNum)%CTSchedIndex
    IF (CTIndex == 0) CYCLE   ! error will be caught elsewhere
    SchedMin=GetScheduleMinValue(CTIndex)
    SchedMax=GetScheduleMaxValue(CTIndex)
    IF (SchedMin == 0 .and. SchedMax == 0) THEN
      IF (FindNumberInList(CTIndex,CTSchedMapToControlledZone,NumTempControlledZones) == 0) THEN
        CALL ShowSevereError('Control Type Schedule='//TRIM(TempControlledZone(TempControlledZoneNum)%ControlTypeSchedName))
        CALL ShowContinueError('..specifies control type 0 for all entries.')
        CALL ShowContinueError('All zones using this Control Type Schedule have no heating or cooling available.')
      ENDIF
      CTSchedMapToControlledZone(TempControlledZoneNum)=CTIndex
    ENDIF
    DO ControlTypeNum=SchedMin,SchedMax
      SELECT CASE (ControlTypeNum)
        CASE (0) ! Uncontrolled
        CASE (SingleHeatingSetPoint)
          TempIndex=TempControlledZone(TempControlledZoneNum)%SchIndx_SingleHeatSetPoint
          TStatControlTypes(TempControlledZoneNum)%DidHave(SingleHeatingSetPoint)=.true.
          IF (TempIndex /= 0) THEN
            SchedTypeIndex = TempControlledZone(TempControlledZoneNum)%ControlTypeSchIndx(TempIndex)
            IF (SchedTypeIndex == 0) THEN
              CALL ShowSevereError('GetZoneAirSetpoints: Could not find '//trim(ValidControlTypes(SglHeatSetPoint))//  &
                 ' Schedule='//TRIM(TempControlledZone(TempControlledZoneNum)%ControlTypeName(TempIndex)))
              ErrorsFound=.true.
            END IF
          ELSE   ! TempIndex = 0
            IF (CheckScheduleValue(CTIndex,SingleHeatingSetPoint)) THEN
              CALL ShowSevereError('Control Type Schedule='//TRIM(TempControlledZone(TempControlledZoneNum)%ControlTypeSchedName))
              CALL ShowContinueError('..specifies control type 1 ('//trim(ValidControlTypes(SglHeatSetPoint))//  &
                 ') as the control type. Not valid for this zone.')
              CALL ShowContinueError('..reference '//trim(cZControlTypes(iZC_TStat))//'='//  &
                 TRIM(TempControlledZone(TempControlledZoneNum)%Name))
              CALL ShowContinueError('..reference ZONE='//TRIM(TempControlledZone(TempControlledZoneNum)%ZoneName))
              ErrorsFound=.true.
            ENDIF
          ENDIF
        CASE (SingleCoolingSetPoint)
          TempIndex = TempControlledZone(TempControlledZoneNum)%SchIndx_SingleCoolSetPoint
          TStatControlTypes(TempControlledZoneNum)%DidHave(SingleCoolingSetPoint)=.true.
          IF (TempIndex /= 0) THEN
            SchedTypeIndex = TempControlledZone(TempControlledZoneNum)%ControlTypeSchIndx(TempIndex)
            IF (SchedTypeIndex == 0) THEN
              CALL ShowSevereError('GetZoneAirSetpoints: Could not find '//trim(ValidControlTypes(SglCoolSetPoint))//  &
                 ' Schedule='//TRIM(TempControlledZone(TempControlledZoneNum)%ControlTypeName(TempIndex)))
              ErrorsFound=.true.
            END IF
          ELSE   ! TempIndex = 0
            IF (CheckScheduleValue(CTIndex,SingleCoolingSetPoint)) THEN
              CALL ShowSevereError('Control Type Schedule='//TRIM(TempControlledZone(TempControlledZoneNum)%ControlTypeSchedName))
              CALL ShowContinueError('..specifies control type 2 ('//trim(ValidControlTypes(SglCoolSetPoint))//  &
                 ') as the control type. Not valid for this zone.')
              CALL ShowContinueError('..reference '//trim(cZControlTypes(iZC_TStat))//'='//  &
                 TRIM(TempControlledZone(TempControlledZoneNum)%Name))
              CALL ShowContinueError('..reference ZONE='//TRIM(TempControlledZone(TempControlledZoneNum)%ZoneName))
              ErrorsFound=.true.
            ENDIF
          ENDIF
        CASE (SingleHeatCoolSetPoint)
          TempIndex = TempControlledZone(TempControlledZoneNum)%SchIndx_SingleHeatCoolSetPoint
          TStatControlTypes(TempControlledZoneNum)%DidHave(SingleHeatCoolSetPoint)=.true.
          IF (TempIndex /= 0) THEN
            SchedTypeIndex = TempControlledZone(TempControlledZoneNum)%ControlTypeSchIndx(TempIndex)
            IF (SchedTypeIndex == 0) THEN
              CALL ShowSevereError('GetZoneAirSetpoints: Could not find '//trim(ValidControlTypes(SglHCSetPoint))//  &
                 ' Schedule='//TRIM(TempControlledZone(TempControlledZoneNum)%ControlTypeName(TempIndex)))
              ErrorsFound=.true.
            END IF
          ELSE   ! TempIndex = 0
            IF (CheckScheduleValue(CTIndex,SingleHeatCoolSetPoint)) THEN
              CALL ShowSevereError('Schedule='//TRIM(TempControlledZone(TempControlledZoneNum)%ControlTypeSchedName))
              CALL ShowContinueError('..specifies control type 3 ('//trim(ValidControlTypes(SglHCSetPoint))//  &
                 ') as the control type. Not valid for this zone.')
              CALL ShowContinueError('..reference '//trim(cZControlTypes(iZC_TStat))//'='//  &
                 TRIM(TempControlledZone(TempControlledZoneNum)%Name))
              CALL ShowContinueError('..reference ZONE='//TRIM(TempControlledZone(TempControlledZoneNum)%ZoneName))
              ErrorsFound=.true.
            ENDIF
          ENDIF
        CASE (DualSetPointWithDeadBand)
          TempIndex = TempControlledZone(TempControlledZoneNum)%SchIndx_DualSetPointWDeadBand
          TStatControlTypes(TempControlledZoneNum)%DidHave(DualSetPointWithDeadBand)=.true.
          IF (TempIndex /= 0) THEN
            SchedTypeIndex = TempControlledZone(TempControlledZoneNum)%ControlTypeSchIndx(TempIndex)
            IF (SchedTypeIndex == 0) THEN
              CALL ShowSevereError('GetZoneAirSetpoints: Could not find '//trim(ValidControlTypes(DualSetPoint))//  &
                 ' Schedule='//TRIM(TempControlledZone(TempControlledZoneNum)%ControlTypeName(TempIndex)))
              ErrorsFound=.true.
            END IF
          ELSE   ! TempIndex = 0
            IF (CheckScheduleValue(CTIndex,DualSetPointWithDeadBand)) THEN
              CALL ShowSevereError('Schedule='//TRIM(TempControlledZone(TempControlledZoneNum)%ControlTypeSchedName))
              CALL ShowContinueError('..specifies control type 4 ('//trim(ValidControlTypes(DualSetPoint))//  &
                 ') as the control type. Not valid for this zone.')
              CALL ShowContinueError('..reference '//trim(cZControlTypes(iZC_TStat))//'='//  &
                 TRIM(TempControlledZone(TempControlledZoneNum)%Name))
              CALL ShowContinueError('..reference ZONE='//TRIM(TempControlledZone(TempControlledZoneNum)%ZoneName))
              ErrorsFound=.true.
            ENDIF
          ENDIF
        CASE DEFAULT
          CALL ShowSevereError('GetZoneAirSetpoints: Illegal control type for Zone='//TRIM(Zone(ActualZoneNum)%Name)//  &
                               ', Found value='//TRIM(TrimSigDigits(ControlTypeNum))//', in Schedule='//        &
                               TRIM(TempControlledZone(TempControlledZoneNum)%ControlTypeSchedName))
          CALL ShowContinueError('..valid range values are [0,4].')
          ErrorsFound=.true.
      END SELECT
    END DO
  END DO
  DO TempControlledZoneNum = 1, NumTempControlledZones
    ActualZoneNum = TempControlledZone(TempControlledZoneNum)%ActualZoneNum
    CTIndex = TempControlledZone(TempControlledZoneNum)%CTSchedIndex
    IF (CTIndex == 0) CYCLE  ! error caught elsewhere -- would just be confusing here
    DO ControlTypeNum=1,4
      IF (TStatControlTypes(TempControlledZoneNum)%MustHave(ControlTypeNum) .and.  &
          TStatControlTypes(TempControlledZoneNum)%DidHave(ControlTypeNum)) CYCLE
      SELECT CASE (ControlTypeNum)
        CASE (SingleHeatingSetPoint)
          IF (.not. TStatControlTypes(TempControlledZoneNum)%MustHave(ControlTypeNum)) CYCLE
          CALL ShowWarningError('Schedule='//TRIM(TempControlledZone(TempControlledZoneNum)%ControlTypeSchedName))
          CALL ShowContinueError('...should include control type 1 ('//trim(ValidControlTypes(SglHeatSetPoint))//  &
                      ') but does not.')
          CALL ShowContinueError('..reference '//trim(cZControlTypes(iZC_TStat))//'='//  &
                   TRIM(TempControlledZone(TempControlledZoneNum)%Name))
          CALL ShowContinueError('..reference ZONE='//TRIM(TempControlledZone(TempControlledZoneNum)%ZoneName))
        CASE (SingleCoolingSetPoint)
          IF (.not. TStatControlTypes(TempControlledZoneNum)%MustHave(ControlTypeNum)) CYCLE
          CALL ShowWarningError('Schedule='//TRIM(TempControlledZone(TempControlledZoneNum)%ControlTypeSchedName))
          CALL ShowContinueError('...should include control type 2 ('//trim(ValidControlTypes(SglCoolSetPoint))//  &
                      ') but does not.')
          CALL ShowContinueError('..reference '//trim(cZControlTypes(iZC_TStat))//'='//  &
                   TRIM(TempControlledZone(TempControlledZoneNum)%Name))
          CALL ShowContinueError('..reference ZONE='//TRIM(TempControlledZone(TempControlledZoneNum)%ZoneName))
        CASE (SingleHeatCoolSetPoint)
          IF (.not. TStatControlTypes(TempControlledZoneNum)%MustHave(ControlTypeNum)) CYCLE
          CALL ShowWarningError('Schedule='//TRIM(TempControlledZone(TempControlledZoneNum)%ControlTypeSchedName))
          CALL ShowContinueError('...should include control type 3 ('//trim(ValidControlTypes(SglHCSetPoint))//  &
                      ') but does not.')
          CALL ShowContinueError('..reference '//trim(cZControlTypes(iZC_TStat))//'='//  &
                   TRIM(TempControlledZone(TempControlledZoneNum)%Name))
          CALL ShowContinueError('..reference ZONE='//TRIM(TempControlledZone(TempControlledZoneNum)%ZoneName))
        CASE (DualSetPointWithDeadBand)
          IF (.not. TStatControlTypes(TempControlledZoneNum)%MustHave(ControlTypeNum)) CYCLE
          CALL ShowWarningError('Schedule='//TRIM(TempControlledZone(TempControlledZoneNum)%ControlTypeSchedName))
          CALL ShowContinueError('...should include control type 4 ('//trim(ValidControlTypes(DualSetPoint))//  &
                      ') but does not.')
          CALL ShowContinueError('..reference '//trim(cZControlTypes(iZC_TStat))//'='//  &
                   TRIM(TempControlledZone(TempControlledZoneNum)%Name))
          CALL ShowContinueError('..reference ZONE='//TRIM(TempControlledZone(TempControlledZoneNum)%ZoneName))
        CASE DEFAULT
      END SELECT
    ENDDO
  ENDDO
  IF (ALLOCATED(TStatControlTypes)) DEALLOCATE(TStatControlTypes)
  ! This starts the Humidity Control Get Input section
  cCurrentModuleObject=cZControlTypes(iZC_HStat)
  NumHumidityControlZones = GetNumObjectsFound(cCurrentModuleObject)
  IF (NumHumidityControlZones .GT. 0) ALLOCATE(HumidityControlZone(NumHumidityControlZones))
  DO HumidControlledZoneNum = 1, NumHumidityControlZones
    CALL GetObjectItem(cCurrentModuleObject,HumidControlledZoneNum,cAlphaArgs,NumAlphas,rNumericArgs,NumNums,IOSTAT, &
                       NumBlank=lNumericFieldBlanks,AlphaBlank=lAlphaFieldBlanks, &
                       AlphaFieldNames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
    IsNotOK = .FALSE.
    IsBlank = .FALSE.
    CALL VerifyName(cAlphaArgs(1),HumidityControlZone%ControlName,HumidControlledZoneNum-1,IsNotOK,IsBlank, &
                    trim(cCurrentModuleObject)//' Name')
    IF (IsNotOK) THEN
      ErrorsFound = .TRUE.
      IF (IsBlank) cAlphaArgs(1) = 'xxxxx'
    END IF
    HumidityControlZone(HumidControlledZoneNum)%ControlName = cAlphaArgs(1)
    ! Ensure unique zone name
    IsNotOK = .FALSE.
    IsBlank = .FALSE.
    CALL VerifyName(cAlphaArgs(2),HumidityControlZone%ZoneName,HumidControlledZoneNum-1,IsNotOK,IsBlank, &
                    trim(cCurrentModuleObject)//' Zone Name')
    IF (IsNotOK) THEN
      ErrorsFound = .TRUE.
      IF (IsBlank) cAlphaArgs(2) = 'xxxxx'
    END IF
    HumidityControlZone(HumidControlledZoneNum)%ZoneName = cAlphaArgs(2)
    HumidityControlZone(HumidControlledZoneNum)%ActualZoneNum = FindItem(cAlphaArgs(2),Zone%Name,NumOfZones)
    IF (HumidityControlZone(HumidControlledZoneNum)%ActualZoneNum == 0) THEN
      CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//' invalid '//  &
         trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" not found.')
      ErrorsFound = .TRUE.
    END IF
    HumidityControlZone(HumidControlledZoneNum)%HumidifyingSched = cAlphaArgs(3)
    HumidityControlZone(HumidControlledZoneNum)%HumidifyingSchedIndex = GetScheduleIndex(cAlphaArgs(3))
    IF (HumidityControlZone(HumidControlledZoneNum)%HumidifyingSchedIndex == 0) THEN
      CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//' invalid '//  &
         trim(cAlphaFieldNames(3))//'="'//trim(cAlphaArgs(3))//'" not found.')
      ErrorsFound = .TRUE.
    END IF
    If (NumAlphas .eq. 4) Then
      HumidityControlZone(HumidControlledZoneNum)%DehumidifyingSched = cAlphaArgs(4)
      HumidityControlZone(HumidControlledZoneNum)%DehumidifyingSchedIndex = GetScheduleIndex(cAlphaArgs(4))
      IF (HumidityControlZone(HumidControlledZoneNum)%DehumidifyingSchedIndex == 0) THEN
        CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//' invalid '//  &
           trim(cAlphaFieldNames(4))//'="'//trim(cAlphaArgs(4))//'" not found.')
        ErrorsFound = .TRUE.
      END IF
    Else
      HumidityControlZone(HumidControlledZoneNum)%DehumidifyingSched = cAlphaArgs(3)
      HumidityControlZone(HumidControlledZoneNum)%DehumidifyingSchedIndex = GetScheduleIndex(cAlphaArgs(3))
    End If
  END DO ! HumidControlledZoneNum
  ! Start to read Thermal comfort control objects
  cCurrentModuleObject=cZControlTypes(iZC_TCTStat)
  NumComfortTStatStatements = GetNumObjectsFound(cCurrentModuleObject)
  ALLOCATE(ComfortTStatObjects(NumComfortTStatStatements))
! Pre-scan for use of Zone lists in TStat statements (i.e. Global application of TStat)
  NumComfortControlledZones=0
  ErrFlag=.false.
  DO Item=1,NumComfortTStatStatements
    CALL GetObjectItem(cCurrentModuleObject,Item,cAlphaArgs,NumAlphas,rNumericArgs,NumNums,IOSTAT, &
                       NumBlank=lNumericFieldBlanks,AlphaBlank=lAlphaFieldBlanks, &
                       AlphaFieldNames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
    ! will not do much verifying -- that will come later.
    IsNotOK = .FALSE.
    IsBlank = .FALSE.
    CALL VerifyName(cAlphaArgs(1),ComfortTStatObjects%Name,Item-1,IsNotOK,IsBlank, &
                    trim(cCurrentModuleObject)//' Name')
    IF (IsNotOK) THEN
      ErrFlag = .TRUE.
      ErrorsFound=.true.
      IF (IsBlank) cAlphaArgs(1) = 'xxxxx'
    END IF
    Item1=FindItemInList(cAlphaArgs(2),Zone%Name,NumOfZones)
    ZLItem=0
    IF (Item1 == 0 .and. NumOfZoneLists > 0) &
      ZLItem=FindItemInList(cAlphaArgs(2),ZoneList%Name,NumOfZoneLists)
    ComfortTStatObjects(Item)%Name=cAlphaArgs(1)
    IF (Item1 > 0) THEN
      ComfortTStatObjects(Item)%ComfortControlledZoneStartPtr=NumComfortControlledZones+1
      NumComfortControlledZones=NumComfortControlledZones+1
      ComfortTStatObjects(Item)%NumOfZones=1
      ComfortTStatObjects(Item)%ZoneListActive=.false.
      ComfortTStatObjects(Item)%ZoneOrZoneListPtr=Item1
    ELSEIF (ZLItem > 0) THEN
      ComfortTStatObjects(Item)%ComfortControlledZoneStartPtr=NumComfortControlledZones+1
      NumComfortControlledZones=NumComfortControlledZones+ZoneList(ZLItem)%NumOfZones
      ComfortTStatObjects(Item)%NumOfZones=ZoneList(ZLItem)%NumOfZones
      ComfortTStatObjects(Item)%ZoneListActive=.true.
      ComfortTStatObjects(Item)%ZoneOrZoneListPtr=ZLItem
    ELSE
      CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
           trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" not found.')
      ErrFlag=.true.
      ErrorsFound=.true.
    ENDIF
  ENDDO
  IF (ErrFlag) THEN
    CALL ShowSevereError('GetZoneAirSetpoints: Errors with invalid names in '//trim(cCurrentModuleObject)//  &
       ' objects.')
    CALL ShowContinueError('...These will not be read in.  Other errors may occur.')
    NumComfortControlledZones=0
  ENDIF
  IF (NumComfortControlledZones > 0) THEN
    ALLOCATE(ComfortControlledZone(NumComfortControlledZones))
    ALLOCATE(TComfortControlTypes(NumComfortControlledZones))  ! Number of set point types
    ALLOCATE(CCmSchedMapToControlledZone(NumComfortControlledZones))
    CCmSchedMapToControlledZone=0
    ComfortControlledZoneNum=0
    DO Item = 1, NumComfortTStatStatements
      CALL GetObjectItem(cCurrentModuleObject,Item,cAlphaArgs,NumAlphas,rNumericArgs,NumNums,IOSTAT, &
                         NumBlank=lNumericFieldBlanks,AlphaBlank=lAlphaFieldBlanks, &
                         AlphaFieldNames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
      DO Item1=1,ComfortTStatObjects(Item)%NumOfZones
        ComfortControlledZoneNum=ComfortControlledZoneNum+1
        IF (ComfortTStatObjects(Item)%ZoneListActive) THEN
          cAlphaArgs(2)=Zone(ZoneList(ComfortTStatObjects(Item)%ZoneOrZoneListPtr)%Zone(Item1))%Name
        ENDIF
        ZoneAssigned=FindItemInList(cAlphaArgs(2),ComfortControlledZone%ZoneName,ComfortControlledZoneNum-1)
        IF (ZoneAssigned == 0) THEN
          ComfortControlledZone(ComfortControlledZoneNum)%ZoneName = cAlphaArgs(2)
          ComfortControlledZone(ComfortControlledZoneNum)%ActualZoneNum = FindIteminList(cAlphaArgs(2),Zone%Name,NumOfZones)
          IF (ComfortControlledZone(ComfortControlledZoneNum)%ActualZoneNum == 0) THEN
            CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
               trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" not found.')
            ErrorsFound = .TRUE.
          END IF
        ELSE
          ComfortControlledZone(ComfortControlledZoneNum)%ZoneName = cAlphaArgs(2)  ! for continuity
          CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
             trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" zone previously assigned.')
          CALL ShowContinueError('...Zone was previously assigned to Thermostat="'//  &
             trim(ComfortControlledZone(ZoneAssigned)%Name)//'".')
          ErrorsFound = .TRUE.
          CYCLE
        ENDIF
        IF (.not. ComfortTStatObjects(Item)%ZoneListActive) THEN
          ComfortControlledZone(ComfortControlledZoneNum)%Name = cAlphaArgs(1)
        ELSE
          ComfortControlledZone(ComfortControlledZoneNum)%Name =   &
             trim(Zone(ZoneList(ComfortTStatObjects(Item)%ZoneOrZoneListPtr)%Zone(Item1))%Name)//  &
                ' '//trim(ComfortTStatObjects(Item)%Name)
        ENDIF
        ! Read Fields A3 and A4 for averaging method
        IZoneCount = 0
        Do i=1,TotPeople
          If (ComfortControlledZone(ComfortControlledZoneNum)%ActualZoneNum == People(I)%ZonePtr) then
            IZoneCount = IZoneCount+1
          End If
        End Do
        ! Could not find a people object for this particular zone
        If (IZoneCount == 0 .and. ComfortControlledZone(ComfortControlledZoneNum)%ActualZoneNum > 0) then
          CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//' no PEOPLE in '//  &
             trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" - cannot use Comfort Control.')
          ErrorsFound=.true.
        End If
        ComfortControlledZone(ComfortControlledZoneNum)%AverageMethodNum = AverageMethodNum_NO
        If (IZoneCount > 1) then
          ComfortControlledZone(ComfortControlledZoneNum)%AverageMethodName = cAlphaArgs(3)
          If (SameString(cAlphaArgs(3),'SpecificObject')) then
            ComfortControlledZone(ComfortControlledZoneNum)%AverageMethodNum = AverageMethodNum_SPE
          End If
          If (SameString(cAlphaArgs(3),'ObjectAverage')) then
            ComfortControlledZone(ComfortControlledZoneNum)%AverageMethodNum = AverageMethodNum_OBJ
          End If
          If (SameString(cAlphaArgs(3),'PeopleAverage')) then
            ComfortControlledZone(ComfortControlledZoneNum)%AverageMethodNum = AverageMethodNum_PEO
          End If
          If (ComfortControlledZone(ComfortControlledZoneNum)%AverageMethodNum == 0) then
            CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//' invalid '//  &
             trim(cAlphaFieldNames(3))//'="'//trim(cAlphaArgs(3))//'".')
            CALL ShowContinueError('Allowed keys are SpecificObject, ObjectAverage, or PeopleAverage')
            ErrorsFound=.true.
          End If
          If (ComfortControlledZone(ComfortControlledZoneNum)%AverageMethodNum == AverageMethodNum_SPE) then
            ComfortControlledZone(ComfortControlledZoneNum)%AverageObjectName = cAlphaArgs(4)
            If (FindItem(cAlphaArgs(4),People%Name,TotPeople) == 0) then
              CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//' invalid '//  &
                 trim(cAlphaFieldNames(4))//'="'//trim(cAlphaArgs(4))//'".')
              ErrorsFound=.true.
            Else
              ComfortControlledZone(ComfortControlledZoneNum)%SpecificObjectNum =  &
                                  FindItem(cAlphaArgs(4),People%Name,TotPeople)
            End If
          End If
        Else
          Do i=1,TotPeople
            If (ComfortControlledZone(ComfortControlledZoneNum)%ActualZoneNum == People(I)%ZonePtr) Exit
          End Do
          ComfortControlledZone(ComfortControlledZoneNum)%SpecificObjectNum = i
        End If
        ! Check values used for thermal comfort calculation
        Do i=1,TotPeople
          If (ComfortControlledZone(ComfortControlledZoneNum)%ActualZoneNum == People(I)%ZonePtr) then
            ! Check activity level
            If (People(i)%ActivityLevelPtr > 0) then
              ValidScheduleControlType=CheckScheduleValueMinMax( &
                                   People(i)%ActivityLevelPtr, '>=',72.0d0, '<=',909.0d0)
              IF (.not. ValidScheduleControlType) THEN
                CALL ShowSevereError('GetPeople Activity Level: Invalid activity level values entered '// &
                                 'for thermal comfort calculation')
                CALL ShowContinueError('Outside of range values [72,909], Reference object='//TRIM(People(i)%Name))
                ErrorsFound=.TRUE.
              ENDIF
            Else
              CALL ShowSevereError('GetPeople Activity Level: Activity level schedule is not found='//TRIM(People(i)%Name))
              CALL ShowContinueError('Required when the zone has Thermal Comfort Controls.')
              ErrorsFound=.TRUE.
            End If
            ! Check Work Efficiency
            If (People(i)%WorkEffPtr > 0) then
              ValidScheduleControlType=CheckScheduleValueMinMax( &
                                     People(i)%WorkEffPtr, '>=',0.0d0, '<=',1.0d0)
              IF (.not. ValidScheduleControlType) THEN
                CALL ShowSevereError('GetPeople work efficiency: Invalid work efficiency values entered '// &
                                   'for thermal comfort calculation')
                CALL ShowContinueError('Outside of range values [0,1], Reference object='//TRIM(People(i)%Name))
                ErrorsFound=.TRUE.
              ENDIF
            Else
              CALL ShowSevereError('GetPeople work efficiency: Work efficiency schedule is not found='//TRIM(People(i)%Name))
              CALL ShowContinueError('Required when the zone has Thermal Comfort Controls.')
              ErrorsFound=.TRUE.
            End If
            ! Check Clothing Insulation
            If (People(i)%ClothingPtr > 0) then
              ValidScheduleControlType=CheckScheduleValueMinMax( &
                                     People(i)%ClothingPtr, '>',0.0d0, '<=',2.0d0)
              IF (.not. ValidScheduleControlType) THEN
                CALL ShowSevereError('GetPeople Clothing Insulation: Invalid Clothing Insulation values entered '// &
                                   'for thermal comfort calculation')
                CALL ShowContinueError('Outside of range values [0.0,2.0], Reference object='//TRIM(People(i)%Name))
                ErrorsFound=.TRUE.
              ENDIF
            Else
              CALL ShowSevereError('GetPeople Clothing Insulation: Clothing Insulation schedule is not found='//  &
                 TRIM(People(i)%Name))
              CALL ShowContinueError('Required when the zone has Thermal Comfort Controls.')
              ErrorsFound=.TRUE.
            End If
            ! Check Air velocity
            If (People(i)%AirVelocityPtr .LE. 0) then
              CALL ShowSevereError('GetPeople Air Velocity: Air velocity schedule is not found='//TRIM(People(i)%Name))
              CALL ShowContinueError('Required when the zone has Thermal Comfort Controls.')
              ErrorsFound=.TRUE.
            End If
          End If
        End Do
        ! Read Max and Min temperature setpoint
        If (NumNums > 0) then
          ComfortControlledZone(ComfortControlledZoneNum)%TdbMinSetPoint = rNumericArgs(1)
          If (rNumericArgs(1) > 50 .OR. rNumericArgs(1) < 0) then
            CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//' invalid '//  &
             trim(cNumericFieldNames(1))//'=['//trim(TrimSigDigits(rNumericArgs(1),0))//'].')
            CALL ShowContinueError('..Allowable values must be between 0 C and 50 C')
            ErrorsFound = .TRUE.
          End If
        End If
        If (NumNums > 1) then
          ComfortControlledZone(ComfortControlledZoneNum)%TdbMaxSetPoint = rNumericArgs(2)
          If (rNumericArgs(2) > 50 .OR. rNumericArgs(2) < 0) then
            CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//' invalid '//  &
             trim(cNumericFieldNames(2))//'=['//trim(TrimSigDigits(rNumericArgs(2),0))//'].')
            CALL ShowContinueError('..Allowable values must be between 0 C and 50 C')
            ErrorsFound = .TRUE.
          End If
        End If
        ! Ensure MaxTemp >= MinTemp
        If (ComfortControlledZone(ComfortControlledZoneNum)%TdbMinSetPoint > &
            ComfortControlledZone(ComfortControlledZoneNum)%TdbMaxSetPoint) then
            CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1)))
            CALL ShowContinueError('..'//trim(cNumericFieldNames(1))//' > '//trim(cNumericFieldNames(2)))
            CALL ShowContinueError('..['//trim(TrimSigDigits(rNumericArgs(1),0))//'] > ['//  &
               trim(TrimSigDigits(rNumericArgs(2),0))//'].')
            ErrorsFound = .TRUE.
        End If
        ! If MaxTemp = MinTemp, no thermal comfort control
        If (ComfortControlledZone(ComfortControlledZoneNum)%TdbMinSetPoint == &
            ComfortControlledZone(ComfortControlledZoneNum)%TdbMaxSetPoint) then
          CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1)))
          CALL ShowContinueError('..'//trim(cNumericFieldNames(1))//' = '//trim(cNumericFieldNames(2)))
          CALL ShowContinueError('The zone will be controlled using this dry-bulb temperature setpoint.')
        End If
        ! read Thermal comfort type schedule name
        ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeSchedName = cAlphaArgs(5)
        ComfortControlledZone(ComfortControlledZoneNum)%ComfortSchedIndex=GetScheduleIndex(cAlphaArgs(5))
        IF (ComfortControlledZone(ComfortControlledZoneNum)%ComfortSchedIndex == 0) THEN
          CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//' invalid '//  &
             trim(cAlphaFieldNames(5))//'="'//trim(cAlphaArgs(5))//'" not found.')
          ErrorsFound = .TRUE.
        ELSE
          ! Check validity of control types.
          ValidScheduleControlType=CheckScheduleValueMinMax(ComfortControlledZone(ComfortControlledZoneNum)%ComfortSchedIndex, &
                                                           '>=',0.0d0, '<=',4.0d0)
          IF (.not. ValidScheduleControlType) THEN
            CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid range '//  &
               trim(cAlphaFieldNames(5))//'="'//trim(cAlphaArgs(5))//'"')
            CALL ShowContinueError('..contains values outside of range [0,4].')
            ErrorsFound=.TRUE.
          ENDIF
        END IF
        ComfortControlledZone(ComfortControlledZoneNum)%NumControlTypes = NINT((NumAlphas - 5.0d0)/2.0d0)
        ALLOCATE(ComfortControlledZone(ComfortControlledZoneNum)%ControlType(ComfortControlledZone( &
                                       ComfortControlledZoneNum)%NumControlTypes))
        ALLOCATE(ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeName(ComfortControlledZone( &
                                       ComfortControlledZoneNum)%NumControlTypes))
        ALLOCATE(ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeSchIndx(ComfortControlledZone(  &
                                       ComfortControlledZoneNum)%NumControlTypes))
        DO ControlTypeNum = 1, ComfortControlledZone(ComfortControlledZoneNum)%NumControlTypes
          ComfortControlledZone(ComfortControlledZoneNum)%ControlType(ControlTypeNum) = cAlphaArgs(NINT(2.0d0*ControlTypeNum-1+5))
          ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeName(ControlTypeNum) = cAlphaArgs(NINT(2.0d0*ControlTypeNum+5))
          IF (ComfortControlledZone(ComfortControlledZoneNum)%ControlType(ControlTypeNum) /= ' ') THEN
            CTIndex=FindItem(ComfortControlledZone(ComfortControlledZoneNum)%ControlType(ControlTypeNum), &
                                   ValidComfortControlTypes,12)
            IF (CTIndex == 0) THEN
              CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
                 trim(cAlphaFieldNames(NINT(2.0d0*ControlTypeNum-1+5)))//'="'//  &
                    trim(cAlphaArgs(NINT(2.0d0*ControlTypeNum-1+5)))//'"')
              ErrorsFound = .TRUE.
            END IF
            IF (CTIndex > 4) THEN ! For Fanger control only for the time being
              CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
                 trim(cAlphaFieldNames(NINT(2.0d0*ControlTypeNum-1+5)))//'="'//  &
                    trim(cAlphaArgs(NINT(2.0d0*ControlTypeNum-1+5)))//'"')
              CALL ShowContinueError('..Fanger is the only valid model.')
              ErrorsFound = .TRUE.
            END IF
          ELSE
            CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
                 trim(cAlphaFieldNames(NINT(2.0d0*ControlTypeNum-1+5)))//'="<blank>"')
            ErrorsFound = .TRUE.
          ENDIF
          ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeSchIndx(ControlTypeNum) = 0
        END DO
      END DO
    END DO ! NumComfortTStatStatements
  ENDIF
  ! End of Thermal comfort control reading and checking
  cCurrentModuleObject=ValidComfortControlTypes(SglHeatSetPointFanger)
  NumSingleFangerHeatingControls = GetNumObjectsFound(cCurrentModuleObject)
  IF (NumSingleFangerHeatingControls .GT. 0) ALLOCATE(SetPointSingleHeatingFanger(NumSingleFangerHeatingControls))
  DO SingleFangerHeatingControlNum = 1, NumSingleFangerHeatingControls
    CALL GetObjectItem(cCurrentModuleObject,SingleFangerHeatingControlNum,  &
                       cAlphaArgs,NumAlphas,rNumericArgs,NumNums,IOSTAT, &
                       NumBlank=lNumericFieldBlanks,AlphaBlank=lAlphaFieldBlanks, &
                       AlphaFieldNames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
    IsNotOK = .FALSE.
    IsBlank = .FALSE.
    CALL VerifyName(cAlphaArgs(1),SetPointSingleHeatingFanger%Name,SingleFangerHeatingControlNum-1,IsNotOK,IsBlank, &
                    trim(cCurrentModuleObject)//' Name')
    IF (IsNotOK) THEN
      ErrorsFound = .TRUE.
      IF (IsBlank) cAlphaArgs(1) = 'xxxxx'
    END IF
    SetPointSingleHeatingFanger(SingleFangerHeatingControlNum)%Name = cAlphaArgs(1)
    SetPointSingleHeatingFanger(SingleFangerHeatingControlNum)%PMVSchedName = cAlphaArgs(2)
    SetPointSingleHeatingFanger(SingleFangerHeatingControlNum)%PMVSchedIndex = GetScheduleIndex(cAlphaArgs(2))
    IF (SetPointSingleHeatingFanger(SingleFangerHeatingControlNum)%PMVSchedIndex == 0) THEN
      CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
         trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" not found.')
      ErrorsFound = .TRUE.
    ELSE
      ValidScheduleControlType=CheckScheduleValueMinMax( &
         SetPointSingleHeatingFanger(SingleFangerHeatingControlNum)%PMVSchedIndex, '>=',-3.0d0, '<=',3.0d0)
      IF (.not. ValidScheduleControlType) THEN
        CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid PMV values '//  &
           trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" entered.')
        CALL ShowContinueError('..Values outside of range [-3,+3].')
        ErrorsFound=.TRUE.
      ENDIF
    END IF
  END DO ! SingleFangerHeatingControlNum
  cCurrentModuleObject=ValidComfortControlTypes(SglCoolSetPointFanger)
  NumSingleFangerCoolingControls = GetNumObjectsFound(cCurrentModuleObject)
  IF (NumSingleFangerCoolingControls .GT. 0) ALLOCATE(SetPointSingleCoolingFanger(NumSingleFangerCoolingControls))
  DO SingleFangerCoolingControlNum = 1, NumSingleFangerCoolingControls
    CALL GetObjectItem(cCurrentModuleObject,SingleFangerCoolingControlNum,  &
                       cAlphaArgs,NumAlphas,rNumericArgs,NumNums,IOSTAT, &
                       NumBlank=lNumericFieldBlanks,AlphaBlank=lAlphaFieldBlanks, &
                       AlphaFieldNames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
    IsNotOK = .FALSE.
    IsBlank = .FALSE.
    CALL VerifyName(cAlphaArgs(1),SetPointSingleCoolingFanger%Name,SingleFangerCoolingControlNum-1,IsNotOK,IsBlank, &
                    trim(cCurrentModuleObject)//' Name')
    IF (IsNotOK) THEN
      ErrorsFound = .TRUE.
      IF (IsBlank) cAlphaArgs(1) = 'xxxxx'
    END IF
    SetPointSingleCoolingFanger(SingleFangerCoolingControlNum)%Name = cAlphaArgs(1)
    SetPointSingleCoolingFanger(SingleFangerCoolingControlNum)%PMVSchedName = cAlphaArgs(2)
    SetPointSingleCoolingFanger(SingleFangerCoolingControlNum)%PMVSchedIndex = GetScheduleIndex(cAlphaArgs(2))
    IF (SetPointSingleCoolingFanger(SingleFangerCoolingControlNum)%PMVSchedIndex == 0) THEN
      CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
         trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" not found.')
      ErrorsFound = .TRUE.
    ELSE
      ValidScheduleControlType=CheckScheduleValueMinMax( &
         SetPointSingleCoolingFanger(SingleFangerCoolingControlNum)%PMVSchedIndex, '>=',-3.0d0, '<=',3.0d0)
      IF (.not. ValidScheduleControlType) THEN
        CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid PMV values '//  &
           trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" entered.')
        CALL ShowContinueError('..Values outside of range [-3,+3].')
        ErrorsFound=.TRUE.
      ENDIF
    END IF
  END DO ! SingleFangerCoolingControlNum
  cCurrentModuleObject=ValidComfortControlTypes(SglHCSetPointFanger)
  NumSingleFangerHeatCoolControls = GetNumObjectsFound(cCurrentModuleObject)
  IF (NumSingleFangerHeatCoolControls .GT. 0) ALLOCATE(SetPointSingleHeatCoolFanger(NumSingleFangerHeatCoolControls))
  DO SingleFangerHeatCoolControlNum = 1, NumSingleFangerHeatCoolControls
    CALL GetObjectItem(cCurrentModuleObject,SingleFangerHeatCoolControlNum,  &
                       cAlphaArgs,NumAlphas,rNumericArgs,NumNums,IOSTAT, &
                       NumBlank=lNumericFieldBlanks,AlphaBlank=lAlphaFieldBlanks, &
                       AlphaFieldNames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
    IsNotOK = .FALSE.
    IsBlank = .FALSE.
    CALL VerifyName(cAlphaArgs(1),SetPointSingleCoolingFanger%Name,SingleFangerCoolingControlNum-1,IsNotOK,IsBlank, &
                    trim(cCurrentModuleObject)//' Name')
    IF (IsNotOK) THEN
      ErrorsFound = .TRUE.
      IF (IsBlank) cAlphaArgs(1) = 'xxxxx'
    END IF
    SetPointSingleHeatCoolFanger(SingleFangerHeatCoolControlNum)%Name = cAlphaArgs(1)
    SetPointSingleHeatCoolFanger(SingleFangerHeatCoolControlNum)%PMVSchedName = cAlphaArgs(2)
    SetPointSingleHeatCoolFanger(SingleFangerHeatCoolControlNum)%PMVSchedIndex = GetScheduleIndex(cAlphaArgs(2))
    IF (SetPointSingleHeatCoolFanger(SingleFangerHeatCoolControlNum)%PMVSchedIndex == 0) THEN
      CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
         trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" not found.')
      ErrorsFound = .TRUE.
    ELSE
      ValidScheduleControlType=CheckScheduleValueMinMax( &
         SetPointSingleHeatCoolFanger(SingleFangerHeatCoolControlNum)%PMVSchedIndex, '>=',-3.0d0, '<=',3.0d0)
      IF (.not. ValidScheduleControlType) THEN
        CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid PMV values '//  &
           trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" entered.')
        CALL ShowContinueError('..Values outside of range [-3,+3].')
        ErrorsFound=.TRUE.
      ENDIF
    END IF
  END DO ! SingleFangerHeatCoolControlNum
  cCurrentModuleObject=ValidComfortControlTypes(DualSetPointFanger)
  NumDualFangerHeatCoolControls = GetNumObjectsFound(cCurrentModuleObject)
  IF (NumDualFangerHeatCoolControls .GT. 0) ALLOCATE(SetPointDualHeatCoolFanger(NumDualFangerHeatCoolControls))
  DO DualFangerHeatCoolControlNum = 1, NumDualFangerHeatCoolControls
    CALL GetObjectItem(cCurrentModuleObject,DualFangerHeatCoolControlNum,  &
                       cAlphaArgs,NumAlphas,rNumericArgs,NumNums,IOSTAT, &
                       NumBlank=lNumericFieldBlanks,AlphaBlank=lAlphaFieldBlanks, &
                       AlphaFieldNames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
    IsNotOK = .FALSE.
    IsBlank = .FALSE.
    CALL VerifyName(cAlphaArgs(1),SetPointDualHeatCoolFanger%Name,DualFangerHeatCoolControlNum-1,IsNotOK,IsBlank, &
                    trim(cCurrentModuleObject)//' Name')
    IF (IsNotOK) THEN
      ErrorsFound = .TRUE.
      IF (IsBlank) cAlphaArgs(1) = 'xxxxx'
    END IF
    SetPointDualHeatCoolFanger(DualFangerHeatCoolControlNum)%Name = cAlphaArgs(1)
    SetPointDualHeatCoolFanger(DualFangerHeatCoolControlNum)%HeatPMVSetptSchedName = cAlphaArgs(2)
    SetPointDualHeatCoolFanger(DualFangerHeatCoolControlNum)%HeatPMVSchedIndex = GetScheduleIndex(cAlphaArgs(2))
    IF (SetPointDualHeatCoolFanger(DualFangerHeatCoolControlNum)%HeatPMVSchedIndex == 0) THEN
      CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
         trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" not found.')
      ErrorsFound = .TRUE.
    END IF
    SetPointDualHeatCoolFanger(DualFangerHeatCoolControlNum)%CoolPMVSetptSchedName = cAlphaArgs(3)
    SetPointDualHeatCoolFanger(DualFangerHeatCoolControlNum)%CoolPMVSchedIndex = GetScheduleIndex(cAlphaArgs(3))
    IF (SetPointDualHeatCoolFanger(DualFangerHeatCoolControlNum)%CoolPMVSchedIndex == 0) THEN
      CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
         trim(cAlphaFieldNames(3))//'="'//trim(cAlphaArgs(3))//'" not found.')
      ErrorsFound = .TRUE.
    ELSE
      ValidScheduleControlType=CheckScheduleValueMinMax( &
         SetPointDualHeatCoolFanger(DualFangerHeatCoolControlNum)%HeatPMVSchedIndex, '>=',-3.0d0, '<=',3.0d0)
      IF (.not. ValidScheduleControlType) THEN
        CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid PMV values '//  &
           trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" entered.')
        CALL ShowContinueError('..Values outside of range [-3,+3].')
        ErrorsFound=.TRUE.
      ENDIF
      ValidScheduleControlType=CheckScheduleValueMinMax( &
         SetPointDualHeatCoolFanger(DualFangerHeatCoolControlNum)%CoolPMVSchedIndex, '>=',-3.0d0, '<=',3.0d0)
      IF (.not. ValidScheduleControlType) THEN
        CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid PMV values '//  &
           trim(cAlphaFieldNames(3))//'="'//trim(cAlphaArgs(3))//'" entered.')
        CALL ShowContinueError('..Values outside of range [-3,+3].')
        ErrorsFound=.TRUE.
      ENDIF
    END IF
  END DO ! DualFangerHeatCoolControlNum
 ! Finish filling in Schedule pointing indexes for Thermal Comfort Control
  DO ComfortControlledZoneNum = 1, NumComfortControlledZones
    ComfortIndex = FindItem(trim(ValidComfortControlTypes(SglHeatSetPointFanger)),  &
                                  ComfortControlledZone(ComfortControlledZoneNum)%ControlType,   &
                                  ComfortControlledZone(ComfortControlledZoneNum)%NumControlTypes)
    ComfortControlledZone(ComfortControlledZoneNum)%SchIndx_SglHeatSetPointFanger = ComfortIndex
    IF (ComfortIndex > 0) THEN
      ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeSchIndx(ComfortIndex) =   &
            FindItem(ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeName(ComfortIndex), &
                                        SetPointSingleHeatingFanger%Name, NumSingleFangerHeatingControls)
      TComfortControlTypes(ComfortControlledZoneNum)%MustHave(SglHeatSetPointFanger)=.true.
    ENDIF
    ComfortIndex = FindItem(trim(ValidComfortControlTypes(SglCoolSetPointFanger)),  &
                                  ComfortControlledZone(ComfortControlledZoneNum)%ControlType,   &
                                  ComfortControlledZone(ComfortControlledZoneNum)%NumControlTypes)
    ComfortControlledZone(ComfortControlledZoneNum)%SchIndx_SglCoolSetPointFanger = ComfortIndex
    IF (ComfortIndex > 0) THEN
      ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeSchIndx(ComfortIndex) =   &
            FindItem(ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeName(ComfortIndex), &
                                        SetPointSingleCoolingFanger%Name, NumSingleFangerCoolingControls)
      TComfortControlTypes(ComfortControlledZoneNum)%MustHave(SglCoolSetpointFanger)=.true.
    ENDIF
    ComfortIndex = FindItem(trim(ValidComfortControlTypes(SglHCSetPointFanger)),  &
                                  ComfortControlledZone(ComfortControlledZoneNum)%ControlType,   &
                                  ComfortControlledZone(ComfortControlledZoneNum)%NumControlTypes)
    ComfortControlledZone(ComfortControlledZoneNum)%SchIndx_SglHCSetPointFanger = ComfortIndex
    IF (ComfortIndex > 0) THEN
      ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeSchIndx(ComfortIndex) =   &
            FindItem(ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeName(ComfortIndex), &
                                        SetPointSingleHeatCoolFanger%Name, NumSingleFangerHeatCoolControls)
      TComfortControlTypes(ComfortControlledZoneNum)%MustHave(SglHCSetPointFanger)=.true.
    ENDIF
    ComfortIndex = FindItem(trim(ValidComfortControlTypes(DualSetPointFanger)),  &
                                  ComfortControlledZone(ComfortControlledZoneNum)%ControlType,   &
                                  ComfortControlledZone(ComfortControlledZoneNum)%NumControlTypes)
    ComfortControlledZone(ComfortControlledZoneNum)%SchIndx_DualSetPointFanger = ComfortIndex
    IF (ComfortIndex > 0) THEN
      ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeSchIndx(ComfortIndex) =   &
            FindItem(ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeName(ComfortIndex), &
                                        SetPointDualHeatCoolFanger%Name, NumDualFangerHeatCoolControls)
      TComfortControlTypes(ComfortControlledZoneNum)%MustHave(DualSetPointFanger)=.true.
    ENDIF
  ENDDO
  ! Now, Check the schedule values/indices for validity for Thermal Comfort Control
   DO ComfortControlledZoneNum = 1, NumComfortControlledZones
    ActualZoneNum = ComfortControlledZone(ComfortControlledZoneNum)%ActualZoneNum
    CTIndex = ComfortControlledZone(ComfortControlledZoneNum)%ComfortSchedIndex
    IF (CTIndex == 0) CYCLE   ! error will be caught elsewhere
    SchedMin=GetScheduleMinValue(CTIndex)
    SchedMax=GetScheduleMaxValue(CTIndex)
    IF (SchedMin == 0 .and. SchedMax == 0) THEN
      IF (FindNumberInList(CTIndex,CCmSchedMapToControlledZone,NumComfortControlledZones) == 0) THEN
        CALL ShowWarningError('Control Type Schedule='//TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeSchedName))
        CALL ShowContinueError('..specifies control type 0 for all entries.')
        CALL ShowContinueError('All zones using this Control Type Schedule have no thermal comfort control.')
      ENDIF
      CCmSchedMapToControlledZone(ComfortControlledZoneNum)=CTIndex
    END IF
    DO ControlTypeNum=SchedMin,SchedMax
      SELECT CASE (ControlTypeNum)
        CASE (0) ! Thermal comfort uncontrolled
        CASE (SglHeatSetpointFanger)
          ComfortIndex=ComfortControlledZone(ComfortControlledZoneNum)%SchIndx_SglHeatSetPointFanger
          TComfortControlTypes(ComfortControlledZoneNum)%DidHave(SglHeatSetPointFanger)=.true.
          IF (ComfortIndex /= 0) THEN
            SchedTypeIndex = ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeSchIndx(ComfortIndex)
            IF (SchedTypeIndex == 0) THEN
              CALL ShowSevereError('GetZoneAirSetpoints: Could not find '//  &
                 trim(ValidComfortControlTypes(SglHeatSetPointFanger))//  &
                 ' Schedule='//TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeName(ComfortIndex)))
              ErrorsFound=.true.
            END IF
          ELSE   ! ComfortIndex = 0
            IF (CheckScheduleValue(CTIndex,SglHeatSetPointFanger)) THEN
              CALL ShowSevereError('Control Type Schedule='// &
                   TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeSchedName))
              CALL ShowContinueError('..specifies thermal control type 1 ('//  &
                 trim(ValidComfortControlTypes(SglHeatSetPointFanger))//  &
                 ') as the control type. Not valid for this zone.')
              CALL ShowContinueError('..reference '//trim(cZControlTypes(iZC_TCTStat))//'='//  &
                 TRIM(ComfortControlledZone(ComfortControlledZoneNum)%Name))
              CALL ShowContinueError('..reference ZONE='//TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ZoneName))
              ErrorsFound=.true.
            ENDIF
          ENDIF
        CASE (SglCoolSetPointFanger)
          ComfortIndex = ComfortControlledZone(ComfortControlledZoneNum)%SchIndx_SglCoolSetPointFanger
          TComfortControlTypes(ComfortControlledZoneNum)%DidHave(SglCoolSetPointFanger)=.true.
          IF (ComfortIndex /= 0) THEN
            SchedTypeIndex = ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeSchIndx(ComfortIndex)
            IF (SchedTypeIndex == 0) THEN
              CALL ShowSevereError('GetZoneAirSetpoints: Could not find '//  &
                 trim(ValidComfortControlTypes(SglCoolSetPointFanger))//  &
                 ' Schedule='//TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeName(ComfortIndex)))
              ErrorsFound=.true.
            END IF
          ELSE   ! ComfortIndex = 0
            IF (CheckScheduleValue(CTIndex,SglCoolSetPointFanger)) THEN
              CALL ShowSevereError('Control Type Schedule='// &
                                   TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeSchedName))
              CALL ShowContinueError('..specifies thermal control type 2 ('//  &
                 trim(ValidComfortControlTypes(SglCoolSetPointFanger))//  &
                 ') as the control type. Not valid for this zone.')
              CALL ShowContinueError('..reference '//trim(cZControlTypes(iZC_TCTStat))//'='//  &
                 TRIM(ComfortControlledZone(ComfortControlledZoneNum)%Name))
              CALL ShowContinueError('..reference ZONE='//TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ZoneName))
              ErrorsFound=.true.
            ENDIF
          ENDIF
        CASE (SglHCSetPointFanger)
          ComfortIndex = ComfortControlledZone(ComfortControlledZoneNum)%SchIndx_SglHCSetPointFanger
          TComfortControlTypes(ComfortControlledZoneNum)%DidHave(SglHCSetPointFanger)=.true.
          IF (ComfortIndex /= 0) THEN
            SchedTypeIndex = ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeSchIndx(ComfortIndex)
            IF (SchedTypeIndex == 0) THEN
              CALL ShowSevereError('GetZoneAirSetpoints: Could not find '//trim(ValidComfortControlTypes(SglHCSetPointFanger))//  &
                      ' Schedule='//TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeName(ComfortIndex)))
              ErrorsFound=.true.
            END IF
          ELSE   ! ComfortIndex = 0
            IF (CheckScheduleValue(CTIndex,SglHCSetPointFanger)) THEN
              CALL ShowSevereError('Schedule='//TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeSchedName))
              CALL ShowContinueError('..specifies thermal control type 3 ('//  &
                 trim(ValidComfortControlTypes(SglHCSetPointFanger))//  &
                 ') as the control type. Not valid for this zone.')
              CALL ShowContinueError('..reference '//trim(cZControlTypes(iZC_TCTStat))//'='//  &
                 TRIM(ComfortControlledZone(ComfortControlledZoneNum)%Name))
              CALL ShowContinueError('..reference ZONE='//TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ZoneName))
              ErrorsFound=.true.
            ENDIF
          ENDIF
        CASE (DualSetPointFanger)
          ComfortIndex = ComfortControlledZone(ComfortControlledZoneNum)%SchIndx_DualSetPointFanger
          TComfortControlTypes(ComfortControlledZoneNum)%DidHave(DualSetPointFanger)=.true.
          IF (ComfortIndex /= 0) THEN
            SchedTypeIndex = ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeSchIndx(ComfortIndex)
            IF (SchedTypeIndex == 0) THEN
              CALL ShowSevereError('GetZoneAirSetpoints: Could not find '//trim(ValidComfortControlTypes(DualSetPointFanger))//  &
                      ' Schedule='//TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeName(ComfortIndex)))
              ErrorsFound=.true.
            END IF
          ELSE   ! ComfortIndex = 0
            IF (CheckScheduleValue(CTIndex,DualSetPointFanger)) THEN
              CALL ShowSevereError('Schedule='//TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeSchedName))
              CALL ShowContinueError('..specifies thermal control type 4 ('//trim(ValidComfortControlTypes(DualSetPointFanger))//  &
                 ') as the control type. Not valid for this zone.')
              CALL ShowContinueError('..reference '//trim(cZControlTypes(iZC_TCTStat))//'='//  &
                 TRIM(ComfortControlledZone(ComfortControlledZoneNum)%Name))
              CALL ShowContinueError('..reference ZONE='//TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ZoneName))
              ErrorsFound=.true.
            ENDIF
          ENDIF
        ! CASE PIERCE
        ! CASE KSU
        CASE DEFAULT
          CALL ShowSevereError('GetZoneAirSetpoints: Illegal control type for Zone='//TRIM(Zone(ActualZoneNum)%Name)//  &
                               ', Found value='//TRIM(TrimSigDigits(ControlTypeNum))//', in Schedule='//        &
                               TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeSchedName))
          CALL ShowContinueError('..valid range values are [0,4].')
          ErrorsFound=.true.
      END SELECT
    END DO
  END DO
  DO ComfortControlledZoneNum = 1, NumComfortControlledZones
    ActualZoneNum = ComfortControlledZone(ComfortControlledZoneNum)%ActualZoneNum
    CTIndex = ComfortControlledZone(ComfortControlledZoneNum)%ComfortSchedIndex
    IF (CTIndex == 0) CYCLE  ! error caught elsewhere -- would just be confusing here
    DO ControlTypeNum=1,12
      IF (TComfortControlTypes(ComfortControlledZoneNum)%MustHave(ControlTypeNum) .and.  &
          TComfortControlTypes(ComfortControlledZoneNum)%DidHave(ControlTypeNum)) CYCLE
      SELECT CASE (ControlTypeNum)
        CASE (SglHeatSetpointFanger)
          IF (.not. TComfortControlTypes(ComfortControlledZoneNum)%MustHave(ControlTypeNum)) CYCLE
          CALL ShowWarningError('Schedule='//TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeSchedName))
          CALL ShowContinueError('...should include control type 1 ('//trim(ValidComfortControlTypes(SglHeatSetpointFanger))//  &
                      ') but does not.')
          CALL ShowContinueError('..reference '//trim(cZControlTypes(iZC_TCTStat))//'='//  &
                                 TRIM(ComfortControlledZone(ComfortControlledZoneNum)%Name))
          CALL ShowContinueError('..reference ZONE='//TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ZoneName))
        CASE (SglCoolSetpointFanger)
          IF (.not. TComfortControlTypes(ComfortControlledZoneNum)%MustHave(ControlTypeNum)) CYCLE
          CALL ShowWarningError('Schedule='//TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeSchedName))
          CALL ShowContinueError('...should include control type 2 ('//trim(ValidComfortControlTypes(SglCoolSetpointFanger))//  &
                      ') but does not.')
          CALL ShowContinueError('..reference '//trim(cZControlTypes(iZC_TCTStat))//'='//  &
                                 TRIM(ComfortControlledZone(ComfortControlledZoneNum)%Name))
          CALL ShowContinueError('..reference ZONE='//TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ZoneName))
        CASE (SglHCSetpointFanger)
          IF (.not. TComfortControlTypes(ComfortControlledZoneNum)%MustHave(ControlTypeNum)) CYCLE
          CALL ShowWarningError('Schedule='//TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeSchedName))
          CALL ShowContinueError('...should include control type 3 ('//trim(ValidComfortControlTypes(SglHCSetpointFanger))//  &
                      ') but does not.')
          CALL ShowContinueError('..reference '//trim(cZControlTypes(iZC_TCTStat))//'='//  &
                                 TRIM(ComfortControlledZone(ComfortControlledZoneNum)%Name))
          CALL ShowContinueError('..reference ZONE='//TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ZoneName))
        CASE (DualSetPointFanger)
          IF (.not. TComfortControlTypes(ComfortControlledZoneNum)%MustHave(ControlTypeNum)) CYCLE
          CALL ShowWarningError('Schedule='//TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ControlTypeSchedName))
          CALL ShowContinueError('...should include control type 4 ('//trim(ValidComfortControlTypes(DualSetPointFanger))//  &
                      ') but does not.')
          CALL ShowContinueError('..reference '//trim(cZControlTypes(iZC_TCTStat))//'='//  &
                                 TRIM(ComfortControlledZone(ComfortControlledZoneNum)%Name))
          CALL ShowContinueError('..reference ZONE='//TRIM(ComfortControlledZone(ComfortControlledZoneNum)%ZoneName))
        ! CASE PIERCE
        ! CASE KSU
        CASE DEFAULT
      END SELECT
    ENDDO
  ENDDO
  IF (ALLOCATED(TComfortControlTypes)) DEALLOCATE(TComfortControlTypes)
  ! Get the Zone Air Capacitance Multiplier for use in the Predictor-Corrrector Procedure
  cCurrentModuleObject='ZoneCapacitanceMultiplier:ResearchSpecial'
  NumNums=GetNumObjectsFound(cCurrentModuleObject)
  IF (NumNums == 0) THEN
    ZoneVolCapMultpSens  = 1.d0
    ZoneVolCapMultpMoist = 1.d0
    ZoneVolCapMultpCO2   = 1.d0
    ZoneVolCapMultpGenContam = 1.0d0
  ELSE
    CALL GetObjectItem(cCurrentModuleObject,1,cAlphaArgs,NumAlphas,rNumericArgs,NumNums,IOStat, &
                       NumBlank=lNumericFieldBlanks,AlphaBlank=lAlphaFieldBlanks, &
                       AlphaFieldNames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
    ZoneVolCapMultpSens  = rNumericArgs(1)
    ZoneVolCapMultpMoist = rNumericArgs(2)
    ZoneVolCapMultpCO2   = rNumericArgs(3)
    ZoneVolCapMultpGenContam = rNumericArgs(4)
  END IF
  WRITE(OutputFileInits, 700)
  WRITE(OutputFileInits,701) ZoneVolCapMultpSens, ZoneVolCapMultpMoist, ZoneVolCapMultpCO2, ZoneVolCapMultpGenContam
700 FORMAT ('! <Zone Volume Capacitance Multiplier>, Sensible Heat Capacity Multiplier, Moisture Capacity Multiplier, ',  &
                   'Carbon Dioxide Capacity Multiplier, Generic Contaminant Capacity Multiplier')
701 FORMAT('Zone Volume Capacitance Multiplier,' , F8.3,' ,', F8.3,',', F8.3,',', F8.3)
  cCurrentModuleObject=cZControlTypes(iZC_OTTStat)
  NumOpTempControlledZones =  GetNumObjectsFound(cCurrentModuleObject)
  IF (NumOpTempControlledZones > 0) then
    AnyOpTempControl = .TRUE.
    DO OpTempContrlNum = 1, NumOpTempControlledZones
       CALL GetObjectItem(cCurrentModuleObject,OpTempContrlNum,  &
                       cAlphaArgs,NumAlphas,rNumericArgs,NumNums,IOSTAT, &
                       NumBlank=lNumericFieldBlanks,AlphaBlank=lAlphaFieldBlanks, &
                       AlphaFieldNames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
       ! find matching name of  ZONECONTROL:THERMOSTAT object
       found = FindItem(cAlphaArgs(1),TStatObjects%Name,NumTStatStatements)
       IF (found == 0) THEN
         ! It might be in the TempControlledZones
         found=FindItem(cAlphaArgs(1),TempControlledZone%Name,NumTempControlledZones)
         IF (found == 0) THEN ! throw error
          CALL ShowSevereError(trim(cCurrentModuleObject)//'='//trim(cAlphaArgs(1))//' invalid '//  &
            trim(cZControlTypes(iZC_TStat))//' reference not found.')
          ErrorsFound = .TRUE.
         ELSE
           TempControlledZoneNum = found
           TempControlledZone(TempControlledZoneNum)%OperativeTempControl = .TRUE.
           IF (SameString(cAlphaArgs(2), 'Scheduled')) THEN
             TempControlledZone(TempControlledZoneNum)%OpTempCntrlModeScheduled=.TRUE.
           ENDIF
           IF ( ( .NOT. (SameString(cAlphaArgs(2), 'Scheduled')))  .AND. ( .NOT. (SameString(cAlphaArgs(2), 'Constant'))) ) THEN
              CALL ShowSevereError(trim(cCurrentModuleObject)//'='//trim(cAlphaArgs(1))//' invalid '//  &
                trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'".')
             ErrorsFound = .TRUE.
           ENDIF
           TempControlledZone(TempControlledZoneNum)%FixedRadiativeFraction    = rNumericArgs(1)
           TempControlledZone(TempControlledZoneNum)%OpTempRadiativeFractionSched = GetScheduleIndex(cAlphaArgs(3))
           If ( (TempControlledZone(TempControlledZoneNum)%OpTempRadiativeFractionSched == 0) &
               .AND. (TempControlledZone(TempControlledZoneNum)%OpTempCntrlModeScheduled) ) THEN !throw error
             CALL ShowSevereError(trim(cCurrentModuleObject)//'='//trim(cAlphaArgs(1))//' invalid '//  &
                trim(cAlphaFieldNames(3))//'="'//trim(cAlphaArgs(3))//'" not found.')
             ErrorsFound = .TRUE.
           ENDIF
           !check validity of fixed radiative fraction
           IF ( (TempControlledZone(TempControlledZoneNum)%FixedRadiativeFraction < 0.0d0)  &
                .AND. (.NOT. (TempControlledZone(TempControlledZoneNum)%OpTempCntrlModeScheduled)) ) THEN
             CALL ShowSevereError(trim(cCurrentModuleObject)//'='//trim(cAlphaArgs(1))//' invalid '//  &
                 trim(cNumericFieldNames(1))//'=['//trim(TrimSigDigits(rNumericArgs(1),2))//'" cannot be negative.')
             ErrorsFound = .TRUE.
           ENDIF
           IF ( (TempControlledZone(TempControlledZoneNum)%FixedRadiativeFraction >= 0.9d0) &
                .AND. (.NOT. (TempControlledZone(TempControlledZoneNum)%OpTempCntrlModeScheduled)) ) THEN
             CALL ShowSevereError(trim(cCurrentModuleObject)//'='//trim(cAlphaArgs(1))//' invalid '//  &
                 trim(cNumericFieldNames(1))//'=['//trim(TrimSigDigits(rNumericArgs(1),2))//'" cannot >= .9.')
             ErrorsFound = .TRUE.
           ENDIF
           ! check schedule min max.
           IF (TempControlledZone(TempControlledZoneNum)%OpTempCntrlModeScheduled) THEN
             ValidRadFractSched =   &
                CheckScheduleValueMinMax(TempControlledZone(TempControlledZoneNum)%OpTempRadiativeFractionSched,  &
                                                '>=',0.0,'<',0.9)
             IF (.not. ValidRadFractSched) THEN
               CALL ShowSevereError(trim(cCurrentModuleObject)//'='//trim(cAlphaArgs(1))//' invalid values '//  &
                  trim(cAlphaFieldNames(3))//'=['//trim(cAlphaArgs(3))//'".')
               CALL ShowContinueError('..Values outside of range [0.0,0.9).')
               ErrorsFound=.TRUE.
             ENDIF
           ENDIF
           ! CurrentModuleObject='ZoneControl:Thermostat:OperativeTemperature'
           CALL SetupOutputVariable('Zone Thermostat Operative Temperature [C]',  &
                                     ZnAirRpt(TempControlledZone(TempControlledZoneNum)%ActualZoneNum)%ThermOperativeTemp,  &
                                     'Zone','Average',Zone(TempControlledZone(TempControlledZoneNum)%ActualZoneNum)%Name)
         ENDIF
       ELSE
         DO Item=1,TStatObjects(found)%NumOfZones
           TempControlledZoneNum = TStatObjects(found)%TempControlledZoneStartPtr+Item-1
           IF (NumTempControlledZones == 0) CYCLE
           TempControlledZone(TempControlledZoneNum)%OperativeTempControl = .TRUE.
           IF (SameString(cAlphaArgs(2), 'Scheduled')) THEN
             TempControlledZone(TempControlledZoneNum)%OpTempCntrlModeScheduled=.TRUE.
           ENDIF
           IF (Item == 1) THEN
             IF ( ( .NOT. (SameString(cAlphaArgs(2), 'Scheduled')))  .AND. ( .NOT. (SameString(cAlphaArgs(2), 'Constant'))) ) THEN
                CALL ShowSevereError(trim(cCurrentModuleObject)//'='//trim(cAlphaArgs(1))//' invalid '//  &
                  trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'".')
               ErrorsFound = .TRUE.
             ENDIF
           ENDIF
           TempControlledZone(TempControlledZoneNum)%FixedRadiativeFraction    = rNumericArgs(1)
           TempControlledZone(TempControlledZoneNum)%OpTempRadiativeFractionSched = GetScheduleIndex(cAlphaArgs(3))
           IF (Item == 1) THEN
             If ( (TempControlledZone(TempControlledZoneNum)%OpTempRadiativeFractionSched == 0) &
                 .AND. (TempControlledZone(TempControlledZoneNum)%OpTempCntrlModeScheduled) ) THEN !throw error
                CALL ShowSevereError(trim(cCurrentModuleObject)//'='//trim(cAlphaArgs(1))//' invalid '//  &
                  trim(cAlphaFieldNames(3))//'="'//trim(cAlphaArgs(3))//'" not found.')
               ErrorsFound = .TRUE.
             ENDIF
           ENDIF
           !check validity of fixed radiative fraction
           IF (Item == 1) THEN
             IF ( (TempControlledZone(TempControlledZoneNum)%FixedRadiativeFraction < 0.0d0)  &
                  .AND. (.NOT. (TempControlledZone(TempControlledZoneNum)%OpTempCntrlModeScheduled)) ) THEN
                CALL ShowSevereError(trim(cCurrentModuleObject)//'='//trim(cAlphaArgs(1))//' invalid '//  &
                  trim(cNumericFieldNames(1))//'=['//trim(TrimSigDigits(rNumericArgs(1),2))//'" cannot be negative.')
               ErrorsFound = .TRUE.
             ENDIF
           ENDIF
           IF (Item == 1) THEN
             IF ( (TempControlledZone(TempControlledZoneNum)%FixedRadiativeFraction >= 0.9d0) &
                  .AND. (.NOT. (TempControlledZone(TempControlledZoneNum)%OpTempCntrlModeScheduled)) ) THEN
                CALL ShowSevereError(trim(cCurrentModuleObject)//'='//trim(cAlphaArgs(1))//' invalid '//  &
                  trim(cNumericFieldNames(1))//'=['//trim(TrimSigDigits(rNumericArgs(1),2))//'" cannot >= .9.')
               ErrorsFound = .TRUE.
             ENDIF
           ENDIF
           ! check schedule min max.
           IF (Item == 1) THEN
             IF (TempControlledZone(TempControlledZoneNum)%OpTempCntrlModeScheduled) THEN
               ValidRadFractSched =   &
                  CheckScheduleValueMinMax(TempControlledZone(TempControlledZoneNum)%OpTempRadiativeFractionSched,  &
                                                  '>=',0.0,'<',0.9)
               IF (.not. ValidRadFractSched) THEN
                  CALL ShowSevereError(trim(cCurrentModuleObject)//'='//trim(cAlphaArgs(1))//' invalid values '//  &
                    trim(cAlphaFieldNames(3))//'=['//trim(cAlphaArgs(3))//'".')
                  CALL ShowContinueError('..Values outside of range [0.0,0.9).')
                  ErrorsFound=.TRUE.
               ENDIF
             ENDIF
           ENDIF
           ! CurrentModuleObject='ZoneControl:Thermostat:OperativeTemperature'
           CALL SetupOutputVariable('Zone Thermostat Operative Temperature [C]',  &
                                     ZnAirRpt(TempControlledZone(TempControlledZoneNum)%ActualZoneNum)%ThermOperativeTemp,  &
                                     'Zone','Average',Zone(TempControlledZone(TempControlledZoneNum)%ActualZoneNum)%Name)
        ENDDO  ! TStat Objects Loop
      ENDIF  ! found thermostat referene
    ENDDO !loop over NumOpTempControlledZones
  ENDIF ! NumOpTempControlledZones > 0
  ! Overcool dehumidificaton GetInput starts here
  cCurrentModuleObject=cZControlTypes(iZC_TandHStat)
  NumTempAndHumidityControlledZones =  GetNumObjectsFound(cCurrentModuleObject)
  IF (NumTempAndHumidityControlledZones > 0) THEN
    AnyZoneTempAndHumidityControl = .TRUE.
    DO TempHumidityCntrlNum = 1, NumTempAndHumidityControlledZones
       CALL GetObjectItem(cCurrentModuleObject,TempHumidityCntrlNum,  &
                       cAlphaArgs,NumAlphas,rNumericArgs,NumNums,IOSTAT, &
                       NumBlank=lNumericFieldBlanks,AlphaBlank=lAlphaFieldBlanks, &
                       AlphaFieldNames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
       ! find matching name of  ZONECONTROL:THERMOSTAT object
       found = FindItem(cAlphaArgs(1),TStatObjects%Name,NumTStatStatements)
       IF (found == 0) THEN
         ! It might be in the TempControlledZones
         found=FindItem(cAlphaArgs(1),TempControlledZone%Name,NumTempControlledZones)
         IF (found == 0) THEN ! throw error
          CALL ShowSevereError(TRIM(cCurrentModuleObject)//'='//TRIM(cAlphaArgs(1))//' invalid '//  &
            TRIM(cZControlTypes(iZC_TStat))//' reference not found.')
          ErrorsFound = .TRUE.
         ELSE
           TempControlledZoneNum = found
           TempControlledZone(TempControlledZoneNum)%DehumidifyingSched = cAlphaArgs(2)
           TempControlledZone(TempControlledZoneNum)%DehumidifyingSchedIndex = GetScheduleIndex(cAlphaArgs(2))
           IF (TempControlledZone(TempControlledZoneNum)%DehumidifyingSchedIndex == 0) THEN
               CALL ShowSevereError(TRIM(cCurrentModuleObject)//'="'//TRIM(cAlphaArgs(1))//' invalid '//  &
               TRIM(cAlphaFieldNames(2))//'="'//TRIM(cAlphaArgs(2))//'" not found.')
               ErrorsFound = .TRUE.
           END IF
           TempControlledZone(TempControlledZoneNum)%ZoneOvercoolControl =.TRUE.
           IF ( (SameString(cAlphaArgs(3), 'None')) ) THEN
             TempControlledZone(TempControlledZoneNum)%ZoneOvercoolControl =.FALSE.
           ENDIF
           IF (SameString(cAlphaArgs(4), 'Scheduled')) THEN
             TempControlledZone(TempControlledZoneNum)%OverCoolCntrlModeScheduled=.TRUE.
           ENDIF
           IF ( ( .NOT. (SameString(cAlphaArgs(4), 'Scheduled')))  .AND. ( .NOT. (SameString(cAlphaArgs(4), 'Constant'))) ) THEN
              CALL ShowSevereError(TRIM(cCurrentModuleObject)//'='//TRIM(cAlphaArgs(1))//' invalid '//  &
                trim(cAlphaFieldNames(4))//'="'//TRIM(cAlphaArgs(4))//'".')
             ErrorsFound = .TRUE.
           ENDIF
           TempControlledZone(TempControlledZoneNum)%ZoneOvercoolConstRange = rNumericArgs(1)
           TempControlledZone(TempControlledZoneNum)%ZoneOverCoolRangeSchedIndex = GetScheduleIndex(cAlphaArgs(4))
           IF ( (TempControlledZone(TempControlledZoneNum)%ZoneOverCoolRangeSchedIndex == 0) &
               .AND. (TempControlledZone(TempControlledZoneNum)%OverCoolCntrlModeScheduled) ) THEN !throw error
             CALL ShowSevereError(TRIM(cCurrentModuleObject)//'='//TRIM(cAlphaArgs(1))//' invalid '//  &
                trim(cAlphaFieldNames(5))//'="'//TRIM(cAlphaArgs(5))//'" not found.')
             ErrorsFound = .TRUE.
           ENDIF
           !check validity of zone Overcool constant range
           IF ( (TempControlledZone(TempControlledZoneNum)%ZoneOvercoolConstRange < 0.0d0)  &
                .AND. (.NOT. (TempControlledZone(TempControlledZoneNum)%OverCoolCntrlModeScheduled)) ) THEN
             CALL ShowSevereError(TRIM(cCurrentModuleObject)//'='//TRIM(cAlphaArgs(1))//' invalid '//  &
                 TRIM(cNumericFieldNames(1))//'=['//TRIM(TrimSigDigits(rNumericArgs(1),2))//'" cannot be negative.')
             ErrorsFound = .TRUE.
           ENDIF
           IF ( (TempControlledZone(TempControlledZoneNum)%ZoneOvercoolConstRange > 3.0d0) &
                .AND. (.NOT. (TempControlledZone(TempControlledZoneNum)%OvercoolCntrlModeScheduled)) ) THEN
             CALL ShowSevereError(TRIM(cCurrentModuleObject)//'='//TRIM(cAlphaArgs(1))//' invalid '//  &
                 TRIM(cNumericFieldNames(1))//'=['//TRIM(TrimSigDigits(rNumericArgs(1),2))//'" cannot be > 3.0')
             ErrorsFound = .TRUE.
           ENDIF
           ! check zone Overcool range schedule min/max values.
           IF (TempControlledZone(TempControlledZoneNum)%OvercoolCntrlModeScheduled) THEN
             ValidZoneOvercoolRangeSched =   &
                CheckScheduleValueMinMax(TempControlledZone(TempControlledZoneNum)%ZoneOvercoolRangeSchedIndex,  &
                                                '>=',0.0d0,'<=',3.0d0)
             IF (.not. ValidZoneOvercoolRangeSched) THEN
               CALL ShowSevereError(trim(cCurrentModuleObject)//'='//trim(cAlphaArgs(1))//' invalid values '//  &
                  trim(cAlphaFieldNames(5))//'=['//trim(cAlphaArgs(5))//'".')
               CALL ShowContinueError('..Values outside of range [0.0,3.0].')
               ErrorsFound=.TRUE.
             ENDIF
           ENDIF
           ! check Overcool Control Ratio limits
           TempControlledZone(TempControlledZoneNum)%ZoneOvercoolControlRatio = rNumericArgs(2)
           IF (TempControlledZone(TempControlledZoneNum)%ZoneOvercoolControlRatio < 0.0d0) THEN
             CALL ShowSevereError(TRIM(cCurrentModuleObject)//'='//TRIM(cAlphaArgs(2))//' invalid '//  &
                 trim(cNumericFieldNames(2))//'=['//TRIM(TrimSigDigits(rNumericArgs(2),2))//'" cannot be negative.')
             ErrorsFound = .TRUE.
           ENDIF
         ENDIF
       ELSE
         DO Item=1,TStatObjects(found)%NumOfZones
           TempControlledZoneNum = TStatObjects(found)%TempControlledZoneStartPtr+Item-1
           TempControlledZone(TempControlledZoneNum)%DehumidifyingSched = cAlphaArgs(2)
           TempControlledZone(TempControlledZoneNum)%DehumidifyingSchedIndex = GetScheduleIndex(cAlphaArgs(2))
           IF (TempControlledZone(TempControlledZoneNum)%DehumidifyingSchedIndex == 0) THEN
               CALL ShowSevereError(TRIM(cCurrentModuleObject)//'="'//TRIM(cAlphaArgs(1))//' invalid '//  &
               TRIM(cAlphaFieldNames(2))//'="'//TRIM(cAlphaArgs(2))//'" not found.')
               ErrorsFound = .TRUE.
           ENDIF
           TempControlledZone(TempControlledZoneNum)%ZoneOvercoolControl =.TRUE.
           IF ( (SameString(cAlphaArgs(3), 'None'))) THEN
             TempControlledZone(TempControlledZoneNum)%ZoneOvercoolControl =.FALSE.
           ENDIF
           IF (SameString(cAlphaArgs(4), 'Scheduled')) THEN
             TempControlledZone(TempControlledZoneNum)%OvercoolCntrlModeScheduled =.FALSE.
           ENDIF
           IF (Item == 1) THEN
             IF ( ( .NOT. (SameString(cAlphaArgs(4), 'Scheduled')))  .AND. ( .NOT. (SameString(cAlphaArgs(4), 'Constant'))) ) THEN
                CALL ShowSevereError(TRIM(cCurrentModuleObject)//'='//TRIM(cAlphaArgs(1))//' invalid '//  &
                  TRIM(cAlphaFieldNames(4))//'="'//TRIM(cAlphaArgs(4))//'".')
               ErrorsFound = .TRUE.
             ENDIF
           ENDIF
           TempControlledZone(TempControlledZoneNum)%ZoneOvercoolConstRange = rNumericArgs(1)
           TempControlledZone(TempControlledZoneNum)%ZoneOvercoolRangeSchedIndex = GetScheduleIndex(cAlphaArgs(6))
           IF (Item == 1) THEN
             If ( (TempControlledZone(TempControlledZoneNum)%ZoneOvercoolRangeSchedIndex == 0) &
                 .AND. (TempControlledZone(TempControlledZoneNum)%OvercoolCntrlModeScheduled) ) THEN !throw error
                CALL ShowSevereError(TRIM(cCurrentModuleObject)//'='//TRIM(cAlphaArgs(1))//' invalid '//  &
                  TRIM(cAlphaFieldNames(5))//'="'//TRIM(cAlphaArgs(5))//'" not found.')
               ErrorsFound = .TRUE.
             ENDIF
           ENDIF
           !check validity of zone Overcool constant range
           IF (Item == 1) THEN
             IF ( (TempControlledZone(TempControlledZoneNum)%ZoneOvercoolConstRange < 0.0d0)  &
                  .AND. (.NOT. (TempControlledZone(TempControlledZoneNum)%OvercoolCntrlModeScheduled)) ) THEN
                CALL ShowSevereError(TRIM(cCurrentModuleObject)//'='//TRIM(cAlphaArgs(1))//' invalid '//  &
                  TRIM(cNumericFieldNames(1))//'=['//TRIM(TrimSigDigits(rNumericArgs(1),2))//'" cannot be negative.')
               ErrorsFound = .TRUE.
             ENDIF
           ENDIF
           IF (Item == 1) THEN
             IF ( (TempControlledZone(TempControlledZoneNum)%ZoneOvercoolConstRange > 3.0d0) &
                  .AND. (.NOT. (TempControlledZone(TempControlledZoneNum)%OvercoolCntrlModeScheduled)) ) THEN
                CALL ShowSevereError(TRIM(cCurrentModuleObject)//'='//TRIM(cAlphaArgs(1))//' invalid '//  &
                  TRIM(cNumericFieldNames(1))//'=['//TRIM(TrimSigDigits(rNumericArgs(1),2))//'" cannot > 3.0')
               ErrorsFound = .TRUE.
             ENDIF
           ENDIF
           ! check zone Overcool range schedule min/max values.
           IF (Item == 1) THEN
             IF (TempControlledZone(TempControlledZoneNum)%OvercoolCntrlModeScheduled) THEN
               ValidZoneOverCoolRangeSched =   &
                  CheckScheduleValueMinMax(TempControlledZone(TempControlledZoneNum)%ZoneOvercoolRangeSchedIndex,  &
                                                  '>=',0.0d0,'<=',3.0d0)
               IF (.not. ValidZoneOverCoolRangeSched) THEN
                  CALL ShowSevereError(TRIM(cCurrentModuleObject)//'='//TRIM(cAlphaArgs(1))//' invalid values '//  &
                    TRIM(cAlphaFieldNames(5))//'=['//TRIM(cAlphaArgs(5))//'".')
                  CALL ShowContinueError('..Values outside of range [0.0,3.0].')
                  ErrorsFound=.TRUE.
               ENDIF
             ENDIF
           ENDIF
           TempControlledZone(TempControlledZoneNum)%ZoneOvercoolControlRatio = rNumericArgs(2)
           ! check Overcool Control Ratio limits
           IF (Item == 1) THEN
             IF (TempControlledZone(TempControlledZoneNum)%ZoneOvercoolControlRatio < 0.0d0) THEN
               CALL ShowSevereError(TRIM(cCurrentModuleObject)//'='//TRIM(cAlphaArgs(2))//' invalid '//  &
                  trim(cNumericFieldNames(2))//'=['//TRIM(TrimSigDigits(rNumericArgs(2),2))//'" cannot be negative.')
               ErrorsFound = .TRUE.
             ENDIF
           ENDIF
        ENDDO  ! TStat Objects Loop
      ENDIF  ! found thermostat reference
    ENDDO !loop over NumTempAndHumidityControlledZones
  ENDIF ! NumTempAndHumidityControlledZones > 0
  ! Staged thermostat control inputs start
  cCurrentModuleObject=cZControlTypes(iZC_StagedDual)
  NumStageControlledZones =  GetNumObjectsFound(cCurrentModuleObject)
  If (NumStageControlledZones > 0) ALLOCATE(StagedTStatObjects(NumStageControlledZones))
! Pre-scan for use of Zone lists in TStat statements (i.e. Global application of TStat)
  NumStageCtrZone=0
  DO Item=1,NumStageControlledZones
    CALL GetObjectItem(cCurrentModuleObject,Item,cAlphaArgs,NumAlphas,rNumericArgs,NumNums,IOSTAT, &
                       NumBlank=lNumericFieldBlanks,AlphaBlank=lAlphaFieldBlanks, &
                       AlphaFieldNames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
    IsNotOK = .FALSE.
    IsBlank = .FALSE.
    CALL VerifyName(cAlphaArgs(1),StagedTStatObjects%Name,Item-1,IsNotOK,IsBlank, &
                    trim(cCurrentModuleObject)//' Name')
    IF (IsNotOK) THEN
      ErrorsFound = .TRUE.
      IF (IsBlank) cAlphaArgs(1) = 'xxxxx'
    END IF
    StagedTStatObjects(Item)%Name=cAlphaArgs(1)
    Item1=FindItemInList(cAlphaArgs(2),Zone%Name,NumOfZones)
    ZLItem=0
    IF (Item1 == 0 .and. NumOfZoneLists > 0) &
        ZLItem=FindItemInList(cAlphaArgs(2),ZoneList%Name,NumOfZoneLists)
    IF (Item1 > 0) THEN
      StagedTStatObjects(Item)%StageControlledZoneStartPtr=NumStageCtrZone+1
      NumStageCtrZone=NumStageCtrZone+1
      StagedTStatObjects(Item)%NumOfZones=1
      StagedTStatObjects(Item)%ZoneListActive=.false.
      StagedTStatObjects(Item)%ZoneOrZoneListPtr=Item1
    ELSEIF (ZLItem > 0) THEN
      StagedTStatObjects(Item)%TempControlledZoneStartPtr=NumStageCtrZone+1
      NumStageCtrZone=NumStageCtrZone+ZoneList(ZLItem)%NumOfZones
      StagedTStatObjects(Item)%NumOfZones=ZoneList(ZLItem)%NumOfZones
      StagedTStatObjects(Item)%ZoneListActive=.true.
      StagedTStatObjects(Item)%ZoneOrZoneListPtr=ZLItem
    ELSE
      CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
           trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" not found.')
      ErrorsFound=.true.
    ENDIF
  ENDDO
  IF (ErrorsFound) THEN
    CALL ShowSevereError('GetStagedDualSetpoint: Errors with invalid names in '//trim(cCurrentModuleObject)//  &
       ' objects.')
    CALL ShowContinueError('...These will not be read in.  Other errors may occur.')
    NumStageCtrZone=0
  ENDIF
  IF (NumStageCtrZone > 0) THEN
    ALLOCATE(StageControlledZone(NumStageCtrZone))
    ALLOCATE(StageZoneLogic(NumOfZones))
    StageZoneLogic = .FALSE.
    StageControlledZoneNum = 0
    DO Item = 1, NumStageControlledZones
      CALL GetObjectItem(cCurrentModuleObject,Item,cAlphaArgs,NumAlphas,rNumericArgs,NumNums,IOSTAT, &
                         NumBlank=lNumericFieldBlanks,AlphaBlank=lAlphaFieldBlanks, &
                         AlphaFieldNames=cAlphaFieldNames,NumericFieldNames=cNumericFieldNames)
      DO Item1=1,StagedTStatObjects(Item)%NumOfZones
        StageControlledZoneNum=StageControlledZoneNum+1
        IF (StagedTStatObjects(Item)%ZoneListActive) THEN
          cAlphaArgs(2)=Zone(ZoneList(StagedTStatObjects(Item)%ZoneOrZoneListPtr)%Zone(Item1))%Name
        ENDIF
        ZoneAssigned=FindItemInList(cAlphaArgs(2),StageControlledZone%ZoneName,StageControlledZoneNum-1)
        IF (ZoneAssigned == 0) THEN
          StageControlledZone(StageControlledZoneNum)%ZoneName = cAlphaArgs(2)
          StageControlledZone(StageControlledZoneNum)%ActualZoneNum = FindIteminList(cAlphaArgs(2),Zone%Name,NumOfZones)
          IF (StageControlledZone(StageControlledZoneNum)%ActualZoneNum == 0) THEN
            CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
               trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" not found.')
            ErrorsFound = .TRUE.
          ELSE
 !           Zone(StageControlledZone(StageControlledZoneNum)%ActualZoneNum)%StageControlledZoneIndex = StageControlledZoneNum
          END IF
          StageZoneLogic(StageControlledZone(StageControlledZoneNum)%ActualZoneNum) = .TRUE.
        ELSE
          StageControlledZone(StageControlledZoneNum)%ZoneName = cAlphaArgs(2)  ! for continuity
          CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
             trim(cAlphaFieldNames(2))//'="'//trim(cAlphaArgs(2))//'" zone previously assigned.')
          CALL ShowContinueError('...Zone was previously assigned to Thermostat="'//  &
             trim(StageControlledZone(ZoneAssigned)%Name)//'".')
          ErrorsFound = .TRUE.
          CYCLE
        ENDIF
        IF (.not. StagedTStatObjects(Item)%ZoneListActive) THEN
          StageControlledZone(StageControlledZoneNum)%Name = cAlphaArgs(1)
        ELSE
          CALL CheckCreatedZoneItemName(RoutineName,cCurrentModuleObject,  &
                                        Zone(ZoneList(StagedTStatObjects(Item)%ZoneOrZoneListPtr)%Zone(Item1))%Name,  &
                                        ZoneList(StagedTStatObjects(Item)%ZoneOrZoneListPtr)%MaxZoneNameLength,  &
                                        StagedTStatObjects(Item)%Name,     &
                                        StageControlledZone%Name,           &
                                        StageControlledZoneNum-1,                       &
                                        StageControlledZone(StageControlledZoneNum)%Name,            &
                                        ErrFlag)
          IF (ErrFlag) ErrorsFound=.true.
        ENDIF
        StageControlledZone(StageControlledZoneNum)%NumOfHeatStages = rNumericArgs(1)
        If (rNumericArgs(1) .LT. 1 .or. rNumericArgs(1) .GT. 4) Then
          CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid range '//  &
                 trim(cNumericFieldNames(1))//'="'//trim(RoundSigDigits(rNumericArgs(1),0))//'"')
          CALL ShowContinueError('..contains values outside of range [1,4].')
          ErrorsFound=.TRUE.
        End If
        StageControlledZone(StageControlledZoneNum)%HeatSetBaseSchedName = cAlphaArgs(3)
        StageControlledZone(StageControlledZoneNum)%HSBchedIndex=GetScheduleIndex(cAlphaArgs(3))
        IF (Item1 == 1) THEN  ! only show error on first of several if zone list
          IF (StageControlledZone(StageControlledZoneNum)%HSBchedIndex == 0) THEN
            CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
               trim(cAlphaFieldNames(3))//'="'//trim(cAlphaArgs(3))//'" not found.')
            ErrorsFound = .TRUE.
          END IF
        ENDIF
        StageControlledZone(StageControlledZoneNum)%HeatThroRange = rNumericArgs(2)
        If (rNumericArgs(1) .LT. 0.d0) Then
          CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" negative value is found at '//  &
                 trim(cNumericFieldNames(2))//'="'//trim(RoundSigDigits(rNumericArgs(2),1))//'"')
          CALL ShowContinueError('.. The minumum value is 0.')
          ErrorsFound=.TRUE.
        End If
        If (StageControlledZone(StageControlledZoneNum)%NumOfHeatStages .GT. 0) Then
          ALLOCATE(StageControlledZone(StageControlledZoneNum)%HeatTOffset( &
                   StageControlledZone(StageControlledZoneNum)%NumOfHeatStages))
          Do i=1, StageControlledZone(StageControlledZoneNum)%NumOfHeatStages
            StageControlledZone(StageControlledZoneNum)%HeatTOffset(i) = rNumericArgs(2+i)
            If (rNumericArgs(2+i) .GT. 0.d0) Then
              CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" positive value is found at '//  &
                 trim(cNumericFieldNames(2+i))//'="'//trim(RoundSigDigits(rNumericArgs(2+i),1))//'"')
              CALL ShowContinueError('.. The maximum value is 0.')
              ErrorsFound=.TRUE.
            End If
            If (lNumericFieldBlanks(2+i)) Then
              CALL ShowSevereError(trim(cCurrentModuleObject)//' object ='//TRIM(cAlphaArgs(1))// &
                '. The input of ' //TRIM(cNumericFieldNames(2+i))//' is required, but a blank is found.')
              ErrorsFound=.TRUE.
            End If
            If (i > 1) Then
              If (rNumericArgs(2+i) >= rNumericArgs(1+i)) Then
                CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" The value at '//  &
                 trim(cNumericFieldNames(2+i))//'="'//trim(RoundSigDigits(rNumericArgs(2+i),1))//'" has to be less than ')
                CALL ShowContinueError(trim(cNumericFieldNames(1+i))//'="'//trim(RoundSigDigits(rNumericArgs(1+i),1)))
                ErrorsFound=.TRUE.
              End If
            End If
          End Do
        End If
        StageControlledZone(StageControlledZoneNum)%NumOfCoolStages = rNumericArgs(7)
        If (rNumericArgs(7) .LT. 1 .or. rNumericArgs(7) .GT. 4) Then
          CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid range '//  &
                 trim(cNumericFieldNames(7))//'="'//trim(RoundSigDigits(rNumericArgs(7),0))//'"')
          CALL ShowContinueError('..contains values outside of range [1,4].')
          ErrorsFound=.TRUE.
        End If
        StageControlledZone(StageControlledZoneNum)%CoolSetBaseSchedName = cAlphaArgs(4)
        StageControlledZone(StageControlledZoneNum)%CSBchedIndex=GetScheduleIndex(cAlphaArgs(4))
        IF (Item1 == 1) THEN  ! only show error on first of several if zone list
          IF (StageControlledZone(StageControlledZoneNum)%CSBchedIndex == 0) THEN
            CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" invalid '//  &
               trim(cAlphaFieldNames(4))//'="'//trim(cAlphaArgs(4))//'" not found.')
            ErrorsFound = .TRUE.
          END IF
        ENDIF
        StageControlledZone(StageControlledZoneNum)%CoolThroRange = rNumericArgs(8)
        If (rNumericArgs(8) .LT. 0.d0) Then
          CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" negative value is found at '//  &
                 trim(cNumericFieldNames(8))//'="'//trim(RoundSigDigits(rNumericArgs(8),1))//'"')
          CALL ShowContinueError('.. The minumum value is 0.')
          ErrorsFound=.TRUE.
        End If
        If (StageControlledZone(StageControlledZoneNum)%NumOfCoolStages .GT. 0) Then
          ALLOCATE(StageControlledZone(StageControlledZoneNum)%CoolTOffset( &
            StageControlledZone(StageControlledZoneNum)%NumOfCoolStages))
          Do i=1, StageControlledZone(StageControlledZoneNum)%NumOfCoolStages
            StageControlledZone(StageControlledZoneNum)%CoolTOffset(i) = rNumericArgs(8+i)
            If (rNumericArgs(8+i) .LT. 0.d0) Then
              CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" negative value is found at '//  &
                 trim(cNumericFieldNames(8+i))//'="'//trim(RoundSigDigits(rNumericArgs(8+i),1))//'"')
              CALL ShowContinueError('.. The minimum value is 0.')
              ErrorsFound=.TRUE.
            End If
            If (lNumericFieldBlanks(8+i)) Then
              CALL ShowSevereError(trim(cCurrentModuleObject)//' object ='//TRIM(cAlphaArgs(1))// &
                '. The input of ' //TRIM(cNumericFieldNames(8+i))//' is required, but a blank is found.')
              ErrorsFound=.TRUE.
            End If
            If (i > 1) Then
              If (rNumericArgs(8+i) <= rNumericArgs(7+i)) Then
                CALL ShowSevereError(trim(cCurrentModuleObject)//'="'//trim(cAlphaArgs(1))//'" The value at '//  &
                 trim(cNumericFieldNames(8+i))//'="'//trim(RoundSigDigits(rNumericArgs(8+i),1))//'" has to be greater than ')
                CALL ShowContinueError(trim(cNumericFieldNames(7+i))//'="'//trim(RoundSigDigits(rNumericArgs(7+i),1)))
                ErrorsFound=.TRUE.
              End If
            End If
          End Do
        End If
      End Do
    ENDDO !loop over NumStageControlledZones
    If ((GetNumObjectsFound('AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed') .EQ. 0) .AND. &
        (GetNumObjectsFound('AirLoopHVAC:UnitarySystem') .EQ. 0) .AND. &
        (GetNumObjectsFound('SetpointManager:SingleZone:OneStageCooling') == 0) .AND. &
        (GetNumObjectsFound('SetpointManager:SingleZone:OneStageHeating') == 0) )     THEN
      CALL ShowWarningError(Trim(cCurrentModuleObject)// &
        ' is applicable to only selected HVAC objects which are missing from input.' )
      CALL ShowContinueError('Model should include one or more of the following objects:  ')
      CALL ShowContinueError('AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed, AirLoopHVAC:UnitarySystem, ')
      CALL ShowContinueError('SetpointManager:SingleZone:OneStageCooling, '// &
                             'and/or SetpointManager:SingleZone:OneStageHeating. The simulation continues...')
    End If
  ENDIF ! NumStageControlledZones > 0
  IF (ErrorsFound) THEN
    CALL ShowFatalError('Errors getting Zone Control input data.  Preceding condition(s) cause termination.')
  END IF
  RETURN
END SUBROUTINE GetZoneAirSetpoints
All Procedures
AbortEnergyPlus AbsoluteAirMass ActivateDemandManagers ActivateEMSControls AddBlankKeys addChargesToOperand AddCompSizeTableEntry AddEndUseSubcategory AddError addFootNoteSubTable AddInstruction AddMeter addMonthlyCharge AddMonthlyFieldSetInput AddMonthlyReport AddNeighborInformation AddObjectDefandParse addOperand AddRecordFromSection AddRecordToOutputVariableStructure AddSectionDef AddShadowRelateTableEntry AddSQLiteComponentSizingRecord AddSQLiteComponentSizingRecord AddSQLiteSystemSizingRecord AddSQLiteSystemSizingRecord AddSQLiteZoneSizingRecord AddSQLiteZoneSizingRecord AddTOCEntry AddTOCZoneLoadComponentTable AddToOutputVariableList AddVariablesForMonthlyReport AddVariableSlatBlind AddWindow AdjustAirSetpointsforOpTempCntrl AdjustCBF AdjustCBF AdjustChangeInLoadByEMSControls AdjustChangeInLoadByHowServed AdjustChangeInLoadForLastStageUpperRangeLimit AdjustCoolingSetPointforTempAndHumidityControl adjusthhat AdjustPumpFlowRequestByEMSControls AdjustReportingHourAndMinutes AdjustVBGap AdvanceRootFinder AFECFR AFECOI AFECPD AFECPF AFEDMP AFEDOP AFEDWC AFEELR AFEEXF AFEFAN AFEHEX AFEHOP AFEPLR AFESCR AFESEL AFESOP AFETMU AirflowNetworkVentingControl AirMass AIRMOV AllocateAirflowNetworkData AllocateAirHeatBalArrays AllocateAndInitData AllocateAndSetUpVentReports AllocateCFSStateHourlyData AllocateForCFSRefPointsGeometry AllocateForCFSRefPointsState AllocateHeatBalArrays AllocateLoadComponentArrays AllocateModuleArrays AllocateModuleArrays AllocateSurfaceHeatBalArrays AllocateWeatherData angle_2dvector AnisoSkyViewFactors AnyPlantLoopSidesNeedSim AnyPlantSplitterMixerLacksContinuity AreaPolygon ArgCheck array_to_vector ASHRAETauModel ASHWAT_OffNormalProperties ASHWAT_Solar ASHWAT_Thermal ASSIGNMENT (=) AssignNodeNumber AssignReportNumber AssignResourceTypeNum AssignReverseConstructionNumber AssignVariablePt AttachCustomMeters AttachMeters AuditBranches AUTOTDMA BaseThermalPropertySet_Diffusivity BeginEnvrnInitializeRuntimeLanguage BetweenDates BetweenGlassForcedFlow BetweenGlassShadeForcedFlow BetweenGlassShadeNaturalFlow BisectionMethod BlindBeamBeamTrans BlindOpticsBeam BlindOpticsDiffuse BoreholeResistance BoundValueToNodeMinMaxAvail BoundValueToWithinTwoValues BracketRoot BranchPressureDrop BrentMethod BuildGap BuildKeyVarList Calc4PipeFanCoil Calc_EN673 Calc_ISO15099 CalcActiveTranspiredCollector CalcAggregateLoad CalcAirflowNetworkAirBalance CalcAirflowNetworkCO2Balance CalcAirflowNetworkGCBalance CalcAirflowNetworkHeatBalance CalcAirflowNetworkMoisBalance CalcAirFlowSimple CalcAirLoopSplitter CalcAirMixer CalcAirToAirGenericHeatExch CalcAirToAirPlateHeatExch CalcAirZoneReturnPlenum CalcAirZoneSupplyPlenum CalcAlamdariHammondStableHorizontal CalcAlamdariHammondUnstableHorizontal CalcAlamdariHammondVerticalWall CalcAngleFactorMRT CalcApproximateViewFactors CalcASHRAEDetailedIntConvCoeff CalcASHRAESimpExtConvectCoeff CalcASHRAESimpleIntConvCoeff CalcASHRAEVerticalWall CalcATMixer CalcAwbiHattonHeatedFloor CalcAwbiHattonHeatedWall CalcBasinHeaterPower CalcBasinHeaterPowerForMultiModeDXCoil CalcBeamSolarOnWinRevealSurface CalcBeamSolDiffuseReflFactors CalcBeamSolSpecularReflFactors CalcBeausoleilMorrisonMixedAssistedWall CalcBeausoleilMorrisonMixedOpposingWall CalcBeausoleilMorrisonMixedStableCeiling CalcBeausoleilMorrisonMixedStableFloor CalcBeausoleilMorrisonMixedUnstableCeiling CalcBeausoleilMorrisonMixedUnstableFloor CalcBLASTAbsorberModel CalcBlockenWindward CalcBoilerModel CalcBoilerModel CalcBottomFluxCoefficents CalcBottomSurfTemp CalcBuriedPipeSoil CalcCBF CalcCBF CalcCBVAV CalcCeilingDiffuserInletCorr CalcCeilingDiffuserIntConvCoeff CalcChillerHeaterModel CalcChillerIPLV CalcChillerModel CalcClearRoof CalcCoilUAbyEffectNTU CalcColdestSetPoint CalcComplexWindowOverlap CalcComplexWindowThermal CalcCompSuctionTempResidual CalcCondEntSetPoint CalcConnectionsDrainTemp CalcConnectionsFlowRates CalcConnectionsHeatRecovery CalcConstCOPChillerModel CalcConvCoeffAbsPlateAndWater CalcConvCoeffBetweenPlates CalcCoolBeam CalcCoolTower CalcCoordinateTransformation CalcCoPlanarNess CalcCostEstimate CalcCTGeneratorModel CalcDayltgCoefficients CalcDayltgCoeffsMapPoints CalcDayltgCoeffsRefMapPoints CalcDayltgCoeffsRefPoints CalcDesiccantBalancedHeatExch CalcDesignSpecificationOutdoorAir CalcDesuperheaterHeatingCoil CalcDesuperheaterWaterHeater CalcDetailedHcInForDVModel CalcDetailedSystem CalcDetailedTransSystem CalcDetailFlatFinCoolingCoil CalcDetIceStorLMTDstar CalcDiffTSysAvailMgr CalcDirectAir CalcDirectEvapCooler CalcDirectResearchSpecialEvapCooler CalcDoe2DXCoil CalcDOE2Leeward CalcDOE2Windward CalcDryFinEffCoef CalcDryIndirectEvapCooler CalcDuct CalcDXCoilStandardRating CalcDXHeatingCoil CalcEarthTube CalcEcoRoof CalcEffectiveness CalcEffectiveSHR CalcEffectiveSHR CalcEffectiveSHR CalcEffectiveSHR CalcElecSteamHumidifier CalcElectricBaseboard CalcElectricChillerHeatRecovery CalcElectricChillerModel CalcElectricEIRChillerModel CalcElectricHeatingCoil CalcEmmelRoof CalcEmmelVertical CalcEngineChillerHeatRec CalcEngineDrivenChillerModel CalcEQLOpticalProperty CalcEQLWindowOpticalProperty CalcEQLWindowSHGCAndTransNormal CalcEQLWindowStandardRatings CalcEQLWindowUvalue CalcEquipmentDrainTemp CalcEquipmentFlowRates CalcExhaustAbsorberChillerModel CalcExhaustAbsorberHeaterModel CalcExteriorVentedCavity CalcFisherPedersenCeilDiffuserCeiling CalcFisherPedersenCeilDiffuserFloor CalcFisherPedersenCeilDiffuserWalls CalcFluidHeatExchanger CalcFohannoPolidoriVerticalWall CalcFollowOATempSetPoint CalcFollowSysNodeTempSetPoint CalcFourPipeIndUnit CalcFrameDividerShadow CalcFuelCellAuxHeater CalcFuelCellGeneratorModel CalcFuelCellGenHeatRecovery CalcFurnaceOutput CalcFurnaceResidual CalcGasAbsorberChillerModel CalcGasAbsorberHeaterModel CalcGasCooler CalcGasHeatingCoil CalcGenericDesiccantDehumidifier CalcGoldsteinNovoselacCeilingDiffuserFloor CalcGoldsteinNovoselacCeilingDiffuserWall CalcGoldsteinNovoselacCeilingDiffuserWindow CalcGroundTempSetPoint CalcGroundwaterWell CalcGshpModel CalcGshpModel CalcGTChillerModel CalcHeatBalanceAir CalcHeatBalanceInsideSurf CalcHeatBalanceInsideSurf CalcHeatBalanceOutsideSurf CalcHeatBalanceOutsideSurf CalcHeatBalFiniteDiff CalcHeatBalHAMT CalcHeatPumpWaterHeater CalcHeatTransCoeffAndCoverTemp CalcHfExteriorSparrow CalcHighTempRadiantSystem CalcHighTempRadiantSystemSP CalcHiTurnOffSysAvailMgr CalcHiTurnOnSysAvailMgr CalcHnASHRAETARPExterior CalcHPCoolingSimple CalcHPHeatingSimple CalcHPWHDXCoil CalcHWBaseboard CalcHXAssistedCoolingCoil CalcHXEffectTerm CalcHybridVentSysAvailMgr CalcIBesselFunc CalcICEngineGeneratorModel CalcICEngineGenHeatRecovery CalcIceStorageCapacity CalcIceStorageCharge CalcIceStorageDischarge CalcIceStorageDormant CalcICSSolarCollector CalcIdealCondEntSetPoint CalcIfSetpointMet CalcIndirectAbsorberModel CalcIndirectResearchSpecialEvapCooler CalcInteriorRadExchange CalcInteriorSolarDistribution CalcInteriorSolarOverlaps CalcInteriorWinTransDifSolInitialDistribution CalcISO15099WindowIntConvCoeff CalcKaradagChilledCeiling CalcKBesselFunc CalcKhalifaEq3WallAwayFromHeat CalcKhalifaEq4CeilingAwayFromHeat CalcKhalifaEq5WallsNearHeat CalcKhalifaEq6NonHeatedWalls CalcKhalifaEq7Ceiling CalcLoadCenterThermalLoad CalcLoTurnOffSysAvailMgr CalcLoTurnOnSysAvailMgr CalcLowTempCFloRadiantSystem CalcLowTempCFloRadSysComps CalcLowTempElecRadiantSystem CalcLowTempHydrRadiantSystem CalcLowTempHydrRadSysComps CalcMatrixInverse CalcMcAdams CalcMerkelVariableSpeedTower CalcMicroCHPNoNormalizeGeneratorModel CalcMinIntWinSolidAngs CalcMitchell CalcMixedAirSetPoint CalcMoistureBalanceEMPD CalcMoreNodeInfo CalcMoWITTLeeward CalcMoWITTWindward CalcMSHeatPump CalcMTGeneratorModel CalcMultiSpeedDXCoil CalcMultiSpeedDXCoilCooling CalcMultiSpeedDXCoilHeating CalcMultiStageElectricHeatingCoil CalcMultiStageGasHeatingCoil CalcMultiZoneAverageCoolingSetPoint CalcMultiZoneAverageHeatingSetPoint CalcMultiZoneAverageMaxHumSetPoint CalcMultiZoneAverageMinHumSetPoint CalcMultiZoneMaxHumSetPoint CalcMultiZoneMinHumSetPoint CalcMundtModel CalcNCycSysAvailMgr CalcNewZoneHeatCoolFlowRates CalcNewZoneHeatOnlyFlowRates CalcNodeMassFlows CalcNominalWindowCond CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNusselt CalcNusseltJurges CalcNVentSysAvailMgr CalcOAController CalcOAMassFlow CalcOAMassFlow CalcOAMixer CalcOAOnlyMassFlow CalcOAPretreatSetPoint CalcOAUnitCoilComps CalcObstrMultiplier CalcOptStartSysAvailMgr CalcOtherSideDemand CalcOutdoorAirUnit CalcOutsideAirSetPoint CalcOutsideSurfTemp CalcParallelPIU CalcPassiveExteriorBaffleGap CalcPassiveSystem CalcPassiveTranspiredCollector CalcPerSolarBeam CalcPipeHeatTransCoef CalcPipesHeatTransfer CalcPipeTransBeam CalcPlantValves CalcPollution CalcPolyhedronVolume CalcPolynomCoef CalcPondGroundHeatExchanger CalcPredictedHumidityRatio CalcPredictedSystemLoad CalcPTUnit CalcPumps CalcPurchAirLoads CalcPurchAirMinOAMassFlow CalcPurchAirMixedAir CalcPVTcollectors CalcQiceChargeMaxByChiller CalcQiceChargeMaxByITS CalcQiceDischageMax CalcRABFlowSetPoint CalcRackSystem CalcRadSysHXEffectTerm CalcRadTemp CalcRainCollector CalcReformEIRChillerModel CalcResearchSpecialPartLoad CalcReturnAirPath CalcRfFlrCoordinateTransformation CalcSandiaPV CalcSatVapPressFromTemp CalcSchedOffSysAvailMgr CalcSchedOnSysAvailMgr CalcSchedSysAvailMgr CalcScheduledDualSetPoint CalcScheduledSetPoint CalcScreenTransmittance CalcScriptF CalcSeriesPIU CalcSetpointTempTarget CalcSHRUserDefinedCurves CalcSimpleController CalcSimpleHeatingCoil CalcSimplePV CalcSingleSpeedEvapFluidCooler CalcSingleSpeedTower CalcSingZoneClSetPoint CalcSingZoneHtSetPoint CalcSingZoneMaxHumSetPoint CalcSingZoneMinHumSetPoint CalcSingZoneRhSetPoint CalcSkySolDiffuseReflFactors CalcSolarCollector CalcSolarFlux CalcSolidDesiccantDehumidifier CalcSourceFlux CalcSourceTempCoefficents CalcSparrowLeeward CalcSparrowWindward CalcSpecialDayTypes CalcStandAloneERV CalcStandardRatings CalcStaticProperties CalcSteamAirCoil CalcSteamBaseboard CalcSurfaceCentroid CalcSurfaceGroundHeatExchanger CalcSystemEnergyUse CalcSZOneStageCoolingSetPt CalcSZOneStageHeatingSetPt CalcTankTemp CalcTDDTransSolAniso CalcTDDTransSolHorizon CalcTDDTransSolIso CalcTempDistModel CalcTempIntegral CalcTESCoilChargeOnlyMode CalcTESCoilCoolingAndChargeMode CalcTESCoilCoolingAndDischargeMode CalcTESCoilCoolingOnlyMode CalcTESCoilDischargeOnlyMode CalcTESCoilOffMode CalcTESIceStorageTank CalcTESWaterStorageTank CalcThermalChimney CalcThermalComfortAdaptiveASH55 CalcThermalComfortAdaptiveCEN15251 CalcThermalComfortFanger CalcThermalComfortKSU CalcThermalComfortPierce CalcThermalComfortSimpleASH55 CalcTimeNeeded CalcTopFluxCoefficents CalcTopSurfTemp CalcTotalFLux CalcTotCapSHR CalcTotCapSHR_VSWSHP CalcTransAbsorProduct CalcTransRefAbsOfCover CalcTRNSYSPV CalcTrombeWallIntConvCoeff CalcTwoSpeedDXCoilIEERResidual CalcTwoSpeedDXCoilStandardRating CalcTwoSpeedEvapFluidCooler CalcTwoSpeedTower CalcUAIce CalcUCSDCV CalcUCSDDV CalcUCSDUE CalcUCSDUI CalculateAirChillerSets CalculateBasisLength CalculateCase CalculateCoil CalculateCompressors CalculateCondensers CalculateCTFs CalculateDailySolarCoeffs CalculateDayOfWeek CalculateEpsFromNTUandZ CalculateExponentialMatrix CalculateFuncResults CalculateGammas CalculateInverseMatrix CalculateMoodyFrictionFactor CalculateNTUfromEpsAndZ CalculatePollution CalculateSecondary CalculateSubcoolers CalculateSunDirectionCosines CalculateTransCompressors CalculateWalkIn CalculateWaterUseage CalculateWaterUseage CalculateWindowBeamProperties CalculateZoneMRT CalculateZoneVolume CalcUnitaryCoolingSystem CalcUnitaryHeatingSystem CalcUnitarySuppHeatingSystem CalcUnitarySuppSystemtoSP CalcUnitarySystemLoadResidual CalcUnitarySystemToLoad CalcUnitHeater CalcUnitHeaterComponents CalcUnitVentilator CalcUnitVentilatorComponents CalcUnmetPlantDemand CalcUpdateHeatRecovery CalcUpdateHeatRecovery CalcUserDefinedInsideHcModel CalcUserDefinedOutsideHcModel CalcVariableSpeedTower CalcVarSpeedCoilCooling CalcVarSpeedCoilHeating CalcVarSpeedHeatPump CalcVarSpeedHeatPump CalcVAVVS CalcVentilatedSlab CalcVentilatedSlabComps CalcVentilatedSlabRadComps CalcVentSlabHXEffectTerm CalcVerticalGroundHeatExchanger CalcViewFactorToShelf CalcVRF CalcVRFCondenser CalcVRFCoolingCoil CalcVSTowerApproach CalcWallCoordinateTransformation CalcWaltonStableHorizontalOrTilt CalcWaltonUnstableHorizontalOrTilt CalcWarmestSetPoint CalcWarmestSetPointTempFlow CalcWaterMainsTemp CalcWaterSource CalcWaterStorageTank CalcWaterThermalTankMixed CalcWaterThermalTankStratified CalcWaterThermalTankZoneGains CalcWaterToAirHeatpump CalcWatertoAirHPCooling CalcWatertoAirHPHeating CalcWaterToAirResidual CalcWatertoWaterHPCooling CalcWatertoWaterHPHeating CalcWaterUseZoneGains CalcWetIndirectEvapCooler CalcWindowACOutput CalcWindowBlindProperties CalcWindowHeatBalance CalcWindowProfileAngles CalcWindowScreenProperties CalcWindowStaticProperties CalcWindPressure CalcWindPressureCoeffs CalcWindTurbine CalcWinFrameAndDividerTemps CalcWinTransDifSolInitialDistribution CalcWrapperModel CalcZoneAirComfortSetpoints CalcZoneAirTempSetpoints CalcZoneComponentLoadSums CalcZoneDehumidifier CalcZoneEvaporativeCoolerUnit CalcZoneLeavingConditions CalcZoneMassBalance CalcZonePipesHeatGain CalcZoneSums CartesianPipeCellInformation_ctor CellType_IsFieldCell CFSHasControlledShade CFSNGlz CFSRefPointPosFactor CFSRefPointSolidAngle CFSShadeAndBeamInitialization CFSUFactor cGetCoilAirOutletNode cGetCoilSteamInletNode cGetCoilSteamOutletNode CharPreDefTableEntry CheckActuatorNode CheckAndAddAirNodeNumber CheckAndFixCFSLayer CheckAndReadCustomSprectrumData CheckAndReadFaults CheckAndSetConstructionProperties CheckBracketRoundOff CheckBranchForOASys CheckCachedIPErrors CheckCFSStates CheckCoilWaterInletNode CheckControllerListOrder CheckControllerLists CheckConvexity CheckCostEstimateInput CheckCreatedZoneItemName CheckCurveLimitsForIPLV CheckCurveLimitsForStandardRatings CheckDayScheduleValueMinMax CheckDXCoolingCoilInOASysExists CheckFDSurfaceTempLimits CheckFFSchedule CheckFluidPropertyName CheckForActualFileName CheckForBalancedFlow CheckForControllerWaterCoil CheckForGeometricTransform CheckForGeometricTransform CheckForMisMatchedEnvironmentSpecifications CheckForOutOfRangeTempResult CheckForOutOfRangeTemps CheckForRequestedReporting CheckForRunawayPlantTemps CheckForSensorAndSetpointNode CheckGasCoefs CheckHeatingCoilSchedule CheckHXAssistedCoolingCoilSchedule CheckIFAnyEMS CheckIFAnyIdealCondEntSetPoint CheckIfAnyPlant CheckIfNodeSetpointManagedByEMS CheckIncrementRoundOff CheckInternalConsistency CheckLightsReplaceableMinMaxForZone CheckLocationValidity CheckLoopExitNode CheckLowerUpperBracket CheckMarkedNodes CheckMaxActiveController CheckMaxConstraint CheckMicroCHPThermalBalance CheckMinActiveController CheckMinConstraint checkMinimumMonthlyCharge CheckMinMaxCurveBoundaries CheckMinMaxRange CheckModelBoundOutput_HumRat CheckModelBoundOutput_Temp CheckModelBounds CheckModelBoundsHumRatEq CheckModelBoundsRH_HumRatEq CheckModelBoundsRH_TempEq CheckModelBoundsTempEq CheckNodeConnections CheckNodeSetPoint CheckNonSingularity CheckOAControllerName CheckOutAirNodeNumber CheckPlantConvergence CheckPlantMixerSplitterConsistency CheckPlantOnAbort CheckPollutionMeterReporting CheckRefrigerationInput CheckReportVariable CheckRootFinderCandidate CheckRootFinderConvergence CheckScheduledSurfaceGains CheckScheduleValue CheckScheduleValueMinMax Checksetpoints CheckSimpleController CheckSlope CheckSteamCoilSchedule CheckSubSurfaceMiscellaneous CheckSysSizing CheckSystemBranchFlow CheckTDDsAndLightShelvesInDaylitZones CheckThisAirSystemForSizing CheckThisZoneForSizing CheckThreading CheckUniqueNodes CheckUnitarySysCoilInOASysExists CheckUsedConstructions CheckValidSimulationObjects CheckWarmupConvergence CheckWaterCoilSchedule CheckWeatherFileValidity CheckWindowShadingControlFrameDivider CheckZoneEquipmentList CheckZoneSizing CHKBKS CHKGSS CHKSBS CLIP CLIPPOLY CloseDFSFile CloseMiscOpenFiles CloseMoistureBalanceEMPD CloseOutOpenFiles CloseOutputFiles CloseOutputTabularFile CloseReportIllumMaps CloseSocket CloseWeatherFile CoilAreaFracIter CoilCompletelyDry CoilCompletelyWet CoilOutletStreamCondition CoilPartWetPartDry COMMAND_ARGUMENT_COUNT CompactObjectsCheck CompareTwoVectors ComplexFenestrationLuminances ComputeDelayedComponents ComputeDifSolExcZonesWIZWindows ComputeIntSolarAbsorpFactors ComputeIntSWAbsorpFactors ComputeIntThermalAbsorpFactors ComputeLifeCycleCostAndReport ComputeLoadComponentDecayCurve ComputeNominalUwithConvCoeffs ComputePresentValue ComputeTariff ComputeTaxAndDepreciation ComputeWinShadeAbsorpFactors CondOutTempResidual ConstructBasis ControlCBVAVOutput ControlCompOutput ControlCompOutput ControlCoolBeam ControlCoolingSystem ControlCycWindACOutput ControlDesiccantDehumidifier ControlDXHeatingSystem ControlDXSystem ControlFluidHeatExchanger ControlHeatingSystem ControlHumidifier ControlMSHPOutput ControlPTUnitOutput ControlPVTcollector ControlReformEIRChillerModel ControlSuppHeatSystem ControlUnitarySystemOutput ControlUnitarySystemtoLoad ControlUnitarySystemtoSP ControlVRF ControlVSEvapUnitToMeetLoad ControlVSHPOutput ControlVSHPOutput ConvectionFactor ConvertCasetoLower ConvertCasetoUpper ConvertIP ConvertIPdelta ConvertToElementTag ConvertToEscaped CoolBeamResidual CoolingCoil CoolWaterHumRatResidual CoolWaterTempResidual CoolWatertoAirHPHumRatResidual CoolWatertoAirHPTempResidual CorrectZoneAirTemp CorrectZoneContaminants CorrectZoneHumRat CostInfoOut CPCW CPHW CreateBoundaryList CreateBoundaryListCount CreateCategoryNativeVariables CreateCellArray CreateCurrentDateTimeString CreateDefaultComputation CreateEnergyReportStructure CreateFCfactorConstructions CreateHVACStepFullString CreateHVACTimeIntervalString CreateHVACTimeString CreateNewellAreaVector CreateNewellSurfaceNormalVector CreatePartitionCenterList CreatePartitionRegionList CreatePredefinedMonthlyReports CreateRegionList CreateRegionListCount CreateShadedWindowConstruction CreateSQLiteConstructionsTable CreateSQLiteConstructionsTable CreateSQLiteDatabase CreateSQLiteDatabase CreateSQLiteDaylightMap CreateSQLiteDaylightMap CreateSQLiteDaylightMapTitle CreateSQLiteDaylightMapTitle CreateSQLiteEnvironmentPeriodRecord CreateSQLiteEnvironmentPeriodRecord CreateSQLiteErrorRecord CreateSQLiteErrorRecord CreateSQLiteInfiltrationTable CreateSQLiteInfiltrationTable CreateSQLiteMaterialsTable CreateSQLiteMaterialsTable CreateSQLiteMeterDictionaryRecord CreateSQLiteMeterDictionaryRecord CreateSQLiteMeterRecord CreateSQLiteMeterRecord CreateSQLiteNominalBaseboardHeatTable CreateSQLiteNominalBaseboardHeatTable CreateSQLiteNominalElectricEquipmentTable CreateSQLiteNominalElectricEquipmentTable CreateSQLiteNominalGasEquipmentTable CreateSQLiteNominalGasEquipmentTable CreateSQLiteNominalHotWaterEquipmentTable CreateSQLiteNominalHotWaterEquipmentTable CreateSQLiteNominalLightingTable CreateSQLiteNominalLightingTable CreateSQLiteNominalOtherEquipmentTable CreateSQLiteNominalOtherEquipmentTable CreateSQLiteNominalPeopleTable CreateSQLiteNominalPeopleTable CreateSQLiteNominalSteamEquipmentTable CreateSQLiteNominalSteamEquipmentTable CreateSQLiteReportVariableDataRecord CreateSQLiteReportVariableDataRecord CreateSQLiteReportVariableDictionaryRecord CreateSQLiteReportVariableDictionaryRecord CreateSQLiteRoomAirModelTable CreateSQLiteRoomAirModelTable CreateSQLiteSchedulesTable CreateSQLiteSimulationsRecord CreateSQLiteSimulationsRecord CreateSQLiteStringTableRecord CreateSQLiteSurfacesTable CreateSQLiteSurfacesTable CreateSQLiteTabularDataRecords CreateSQLiteTabularDataRecords CreateSQLiteTimeIndexRecord CreateSQLiteTimeIndexRecord CreateSQLiteVentilationTable CreateSQLiteVentilationTable CreateSQLiteZoneGroupTable CreateSQLiteZoneGroupTable CreateSQLiteZoneListTable CreateSQLiteZoneListTable CreateSQLiteZoneTable CreateSQLiteZoneTable CreateStormWindowConstructions CreateSysTimeIntervalString CreateTCConstructions CreateTimeIntervalString CreateTimeString CreatExtBooundCondName CreateZoneExtendedOutput CreateZoneExtendedOutput CrossProduct CrossProduct cSurfaceClass CTRANS CurveValue DateToString DateToStringWithMonth DaylghtAltAndAzimuth DayltgAveInteriorReflectance DayltgClosestObstruction DayltgCrossProduct DayltgCurrentExtHorizIllum DayltgDirectIllumComplexFenestration DayltgDirectSunDiskComplexFenestration DayltgElecLightingControl DayltgExtHorizIllum DayltgGlare DayltgGlarePositionFactor DayltgGlareWithIntWins DayltgHitBetWinObstruction DayltgHitInteriorObstruction DayltgHitObstruction DayltgInteriorIllum DayltgInteriorMapIllum DayltgInteriorTDDIllum DayltgInterReflectedIllum DayltgInterReflectedIllumComplexFenestration DayltgInterReflIllFrIntWins DayltgLuminousEfficacy DayltgPierceSurface DayltgSetupAdjZoneListsAndPointers DayltgSkyLuminance DayltgSurfaceLumFromSun dCheckScheduleValueMinMax1 dCheckScheduleValueMinMax2 DeallocateLoadComponentArrays DebugRootFinder DecodeHHMMField DecodeMonDayHrMin DeflectionTemperatures DeflectionWidths DegradF DElightDaylightCoefficients DElightDaylightCoefficients DElightElecLtgCtrl DElightElecLtgCtrl DElightFreeMemory DElightFreeMemory DElightInputGenerator DElightInputGenerator DElightOutputGenerator DElightOutputGenerator DensityCFSFillGas Depth DERIV DetailsForSurfaces DetectOscillatingZoneTemp DetermineAzimuthAndTilt DetermineBranchFlowRequest DetermineBuildingFloorArea DetermineDateTokens DetermineFrequency DetermineIndexGroupFromMeterGroup DetermineIndexGroupKeyFromMeterName DetermineMaxBackSurfaces DetermineMeterIPUnits DetermineMinuteForReporting DeterminePolygonOverlap DetermineShadowingCombinations DetermineSunUpDown DevelopMesh DiffuseAverage DiffuseAverageProfAngGnd DiffuseAverageProfAngSky DisplayMaterialRoughness DisplayNumberandString DisplaySimDaysProgress DisplayString distance DistributeBBElecRadGains DistributeBBRadGains DistributeBBSteamRadGains DistributeHTRadGains DistributePlantLoad DistributePressureOnBranch DistributeTDDAbsorbedSolar DistributeUserDefinedPlantLoad DL_RES_r2 DLAG DOE2DXCoilHumRatResidual DOE2DXCoilHumRatResidual DOE2DXCoilResidual DOE2DXCoilResidual DOE2DXCoilResidual DoEndOfIterationOperations DomainRectangle_Contains DOMakeUPPERCase DoOneTimeInitializations DOSameString DoShadeControl DoStartOfTimeStepInitializations DownInterpolate4HistoryValues DumpAirLoopStatistics DumpCurrentLineBuffer DUMPVD DUMPVR DXCoilCyclingHumRatResidual DXCoilCyclingHumRatResidual DXCoilCyclingResidual DXCoilCyclingResidual DXCoilVarSpeedHumRatResidual DXCoilVarSpeedHumRatResidual DXCoilVarSpeedResidual DXCoilVarSpeedResidual DXFOut DXFOutLines DXFOutWireFrame DXHeatingCoilResidual DXHeatingCoilResidual DXHeatingCoilResidual DynamicClothingModel DynamicExtConvSurfaceClassification DynamicIntConvSurfaceClassification EchoOutActuatorKeyChoices EchoOutInternalVariableChoices EffectiveEPSLB EffectiveEPSLF EIRChillerHeatRecovery EN673ISO10292 EncodeMonDayHrMin EndEnergyPlus EndUniqueNodeCheck EnthalpyResidual epElapsedTime epGetTimeUsed epGetTimeUsedperCall epStartTime epStopTime epSummaryTimes eptime EQLWindowInsideEffectiveEmiss EQLWindowOutsideEffectiveEmiss EQLWindowSurfaceHeatBalance EquationsSolver ERF EstimateHEXSurfaceArea EvalInsideMovableInsulation EvalOutsideMovableInsulation EvaluateAdiabaticSurfaceTemperature EvaluateBasementCellTemperature EvaluateCellNeighborDirections evaluateChargeBlock evaluateChargeSimple EvaluateExpression EvaluateExtHcModels EvaluateFarfieldBoundaryTemperature EvaluateFarfieldCharacteristics EvaluateFieldCellTemperature EvaluateGroundSurfaceTemperature EvaluateIntHcModels EvaluateLoopSetPointLoad EvaluateNeighborCharacteristics evaluateQualify evaluateRatchet EvaluateSoilRhoCp EvaluateStack EvolveParaUCSDCV ExitCalcController ExpandComplexState ExpressAsCashFlows ExtendObjectDefinition ExteriorBCEqns ExternalInterfaceExchangeVariables ExternalInterfaceInitializeErlVariable ExternalInterfaceSetErlVariable ExternalInterfaceSetSchedule ExtOrIntShadeNaturalFlow Fabric_EstimateDiffuseProps FACSKY FalsePositionMethod FEQX FI FigureACAncillaries FigureAirEnthalpy FigureAirHeatCap FigureAuxilHeatGasHeatCap FigureBeamSolDiffuseReflFactors FigureBeamSolSpecularReflFactors FigureConstGradPattern FigureDayltgCoeffsAtPointsForSunPosition FigureDayltgCoeffsAtPointsForWindowElements FigureDayltgCoeffsAtPointsSetupForWindow FigureElectricalStorageZoneGains FigureFuelCellZoneGains FigureFuelEnthalpy FigureFuelHeatCap FigureGaseousWaterEnthalpy FigureHeightPattern FigureHXleavingGasHeatCap FigureInverterZoneGains FigureLHVofFuel FigureLiquidWaterEnthalpy FigureLiquidWaterHeatCap FigureMapPointDayltgFactorsToAddIllums FigureMicroCHPZoneGains FigureNDheightInZone FigurePowerConditioningLosses FigureProductGasesEnthalpy FigureProductGasHeatCap FigureRefPointDayltgFactorsToAddIllums FigureRefrigerationZoneGains FigureSolarBeamAtTimestep FigureSunCosines FigureSurfMapPattern FigureTDDZoneGains FigureTransformerZoneGains FigureTransientConstraints FigureTwoGradInterpPattern FILJAC FillBasisElement FillDefaultsSWP FillRemainingPredefinedEntries FillWeatherPredefinedEntries film filmg filmi filmPillar FILSKY FinalizeCFS FinalizeCFSLAYER FinalRateCoils FindAirLoopBranchConnection FindAirPlantCondenserLoopFromBranchList FindAllNumbersinList FindArrayIndex FindCompSPInput FindCompSPLoad FindCondenserLoopBranchConnection FindControlledZoneIndexFromSystemNodeNumberForZone FindDeltaTempRangeInput FindDemandSideMatch FindEMSVariable FindFirstLastPtr FindFirstRecord FindGlycol FindHXDemandSideLoopFlow FindInBasis FindItem FindIteminList FindIteminSortedList FindItemInVariableList FindLoopSideInCallingOrder FindNextRecord FindNonSpace FindNumberinList FindOAMixerMatchForOASystem FindPlantLoopBranchConnection FindRangeBasedOrUncontrolledInput FindRangeVariable FindRefrigerant FindRootSimpleController FindStratifiedTankSensedTemp FindTariffIndex FindTDDPipe FindUnitNumber FinishDebugOutputFiles FixViewFactors FluidCellInformation_ctor FM_BEAM FM_DIFF FM_F FNU forcedventilation FourPipeInductionUnitHasMixer FourPipeIUCoolingResidual FourPipeIUHeatingResidual FRA FrostControl FrostControlSetPointLimit FrostControlSetPointLimit FuelCellProductGasEnthResidual FUN FuncDetermineCoolantWaterExitTemp FuncDetermineCWMdotForInternalFlowControl FuncDetermineEngineTemp FV GasElecHeatingCoilResidual GASSES90 GassesLow GatherBEPSResultsForTimestep GatherBinResultsForTimestep GatherComponentLoadsHVAC GatherComponentLoadsIntGain GatherComponentLoadsSurfAbsFact GatherComponentLoadsSurface GatherForEconomics GatherForPredefinedReport GatherHeatGainReport GatherMonthlyResultsForTimestep GatherPeakDemandForTimestep GatherSourceEnergyEndUseResultsForTimestep GaussElimination generate_ears GenerateDElightDaylightCoefficients GenerateDElightDaylightCoefficients GeneratorPowerOutput GenericCrack GenOutputVariablesAuditReport Get2DMatrix Get2DMatrixDimensions GET_COMMAND GET_COMMAND_ARGUMENT Get_Environment_Variable GetActualDXCoilIndex GetAirBranchIndex GetAirFlowFlag GetAirflowNetworkInput GetAirHeatBalanceInput GetAirLoopAvailabilityManager GetAirModelDatas GetAirNodeData GetAirPathData GetAngleFactorList GetATMixer GetATMixerOutNode GetATMixerPriNode GetATMixers GetATMixerSecNode GetAttShdSurfaceData GetAverageTempByType GetBaseboardInput GetBaseboardInput GetBasementFloorHeatFlux GetBasementWallHeatFlux GetBLASTAbsorberInput GetBoilerInput GetBoilerInput GetBranchData GetBranchFanTypeName GetBranchFlow GetBranchInput GetBranchList GetBranchListInput GetBuildingData GetCBVAV GetCellWidths GetCellWidthsCount GetChildrenData GetChillerheaterInput GetCoilAirFlowRate GetCoilAirFlowRateVariableSpeed GetCoilAirInletNode GetCoilAirOutletNode GetCoilAvailScheduleIndex GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacityByIndexType GetCoilCapacityVariableSpeed GetCoilCondenserInletNode GetCoilControlNodeNum GetCoilGroupTypeNum GetCoilIndex GetCoilIndex GetCoilIndex GetCoilIndexVariableSpeed GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNodeVariableSpeed GetCoilMaxSteamFlowRate GetCoilMaxWaterFlowRate GetCoilMaxWaterFlowRate GetCoilMaxWaterFlowRate GetCoilObjectTypeNum GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNodeVariableSpeed GetCoilSteamInletNode GetCoilSteamOutletNode GetCoilTypeNum GetCoilWaterInletNode GetCoilWaterInletNode GetCoilWaterOutletNode GetColumnUsingTabs GetComfortSetpoints GetComponentData GetCondFDInput GetConductivityGlycol GetConnectorList GetConnectorListInput GetConstCOPChillerInput GetConstructData GetControlledZoneIndex GetControllerActuatorNodeNum GetControllerInput GetCoolBeams GetCoolingCoilTypeNameAndIndex GetCooltower GetCostEstimateInput GetCrossVentData GetCTGeneratorInput GetCTGeneratorResults GetCurrentHVACTime GetCurrentMeterValue GetCurrentScheduleValue GetCurveCheck GetCurveIndex GetCurveInput GetCurveMinMaxValues GetCurveName GetCurveObjectTypeNum GetCurveType GetCustomMeterInput GetDaylightingParametersDetaild GetDaylightingParametersInput GetDayScheduleIndex GetDemandManagerInput GetDemandManagerListInput GetDensityGlycol GetDesiccantDehumidifierInput GetDesignDayData GetDesignLightingLevelForZone GetDetShdSurfaceData GetDirectAirInput GetDisplacementVentData GetDSTData GetDualDuctInput GetDualDuctOutdoorAirRecircUse GetDuctInput GetDXCoilAirFlow GetDXCoilAvailSchPtr GetDXCoilBypassedFlowFrac GetDXCoilCapFTCurveIndex GetDXCoilIndex GetDXCoilNumberOfSpeeds GetDXCoils GetDXCoolingSystemInput GetDXHeatPumpSystemInput GetEarthTube GetElecReformEIRChillerInput GetElectricBaseboardInput GetElectricChillerInput GetElectricEIRChillerInput GetEMSInput GetEngineDrivenChillerInput GetEnvironmentalImpactFactorInfo GetEvapFluidCoolerInput GetEvapInput GetExhaustAbsorberInput GetExhaustAirInletNode GetExteriorEnergyUseInput GetExtVentedCavityIndex GetExtVentedCavityIndex GetExtVentedCavityTsColl GetExtVentedCavityTsColl GetFanAvailSchPtr GetFanCoilIndex GetFanCoilInletAirNode GetFanCoilMixedAirNode GetFanCoilOutAirNode GetFanCoilReturnAirNode GetFanCoilUnits GetFanCoilZoneInletAirNode GetFanDesignVolumeFlowRate GetFanIndex GetFanIndexForTwoSpeedCoil GetFanInletNode GetFanInput GetFanOutletNode GetFanPower GetFanSpeedRatioCurveIndex GetFanType GetFanVolFlow GetFarfieldTemp GetFirstBranchInletNodeName GetFluidCoolerInput GetFluidDensityTemperatureLimits GetFluidHeatExchangerInput GetFluidPropertiesData GetFluidSpecificHeatTemperatureLimits GetFrameAndDividerData GetFuelCellGeneratorInput GetFuelCellGeneratorResults GetFuelFactorInfo GetFurnaceInput GetGasAbsorberInput GetGeneratorFuelSupplyInput GetGeometryParameters GetGlycolNameByIndex GetGroundheatExchangerInput GetGroundReflectances GetGroundTemps GetGshpInput GetGshpInput GetGTChillerInput GetHeatBalanceInput GetHeatBalHAMTInput GetHeatExchangerObjectTypeNum GetHeatingCoilIndex GetHeatingCoilInput GetHeatingCoilNumberOfStages GetHeatingCoilPLFCurveIndex GetHeatingCoilTypeNum GetHeatReclaimSourceIndex GetHeatRecoveryInput GetHighTempRadiantSystem GetHPCoolingCoilIndex GetHTSubSurfaceData GetHTSurfaceData GetHTSurfExtVentedCavityData GetHumidifierInput GetHVACSingleDuctSysIndex GetHWBaseboardInput GetHXAssistedCoolingCoilInput GetHXCoilAirFlowRate GetHXCoilType GetHXCoilTypeAndName GetHXDXCoilIndex GetHXDXCoilName GetHybridVentilationControlStatus GetHybridVentilationInputs GetICEGeneratorResults GetICEngineGeneratorInput GetIceStorageInput GetIDFRecordsStats GetIndirectAbsorberInput GetIndUnits GetInputEconomicsChargeBlock GetInputEconomicsChargeSimple GetInputEconomicsComputation GetInputEconomicsCurrencyType GetInputEconomicsQualify GetInputEconomicsRatchet GetInputEconomicsTariff GetInputEconomicsVariable GetInputForLifeCycleCost GetInputFuelAndPollutionFactors GetInputLifeCycleCostNonrecurringCost GetInputLifeCycleCostParameters GetInputLifeCycleCostRecurringCosts GetInputLifeCycleCostUseAdjustment GetInputLifeCycleCostUsePriceEscalation GetInputTabularMonthly GetInputTabularPredefined GetInputTabularStyle GetInputTabularTimeBins GetInputViewFactors GetInputViewFactorsbyName GetInputZoneEvaporativeCoolerUnit GetInstantMeterValue GetInternalBranchData GetInternalHeatGainsInput GetInternalVariableValue GetInternalVariableValue GetInternalVariableValueExternalInterface GetInternalVariableValueExternalInterface GetInterpolatedSatProp GetInterpValue GetIntMassSurfaceData GetLastBranchOutletNodeName GetLastWord GetLightWellData GetListOfObjectsInIDD GetListofSectionsinInput GetLocationInfo GetLoopMixer GetLoopSidePumpIndex GetLoopSplitter GetLowTempRadiantSystem GetMaterialData GetMatrixInput getMaxAndSum GetMeteredVariables GetMeterIndex GetMeterResourceType GetMicroCHPGeneratorInput GetMicroCHPGeneratorResults GetMinOATCompressor GetMixerInput GetMixerInput GetMoistureBalanceEMPDInput GetMonthlyCostForResource GetMovableInsulationData GetMSHeatPumpInput GetMTGeneratorExhaustNode GetMTGeneratorInput GetMTGeneratorResults GetMundtData GetNewUnitNumber GetNextEnvironment GetNodeConnectionType GetNodeList GetNodeListsInput GetNodeNums GetNTUforCrossFlowBothUnmixed GetNumberOfSchedules GetNumberOfSurfaceLists GetNumberOfSurfListVentSlab GetNumChildren GetNumMeteredVariables GetNumOAControllers GetNumOAMixers GetNumOASystems GetNumObjectsFound GetNumObjectsInIDD GetNumRangeCheckErrorsFound GetNumSectionsFound GetNumSectionsinInput GetNumSegmentsForHorizontalTrenches GetNumSplitterMixerInConntrList GetOACompListNumber GetOACompName GetOACompType GetOACompTypeNum GetOAControllerInputs GetOAMixerIndex GetOAMixerInletNodeNumber GetOAMixerInputs GetOAMixerMixedNodeNumber GetOAMixerNodeNumbers GetOAMixerReliefNodeNumber GetOAMixerReturnNodeNumber GetOARequirements GetOASysControllerListIndex GetOASysNumCoolingCoils GetOASysNumHeatingCoils GetOASysNumSimpControllers GetOASystemNumber GetObjectDefInIDD GetObjectDefMaxArgs GetObjectItem GetObjectItemfromFile GetObjectItemNum GetOnlySingleNode GetOperationSchemeInput GetOSCData GetOSCMData GetOutAirNodesInput GetOutdoorAirUnitInputs GetOutdoorAirUnitOutAirNode GetOutdoorAirUnitReturnAirNode GetOutdoorAirUnitZoneInletNode GetOutsideAirSysInputs GetOutsideEnergySourcesInput GetParentData GetPipeInput GetPipesHeatTransfer GetPipingSystemsInput GetPIUs GetPlantAvailabilityManager GetPlantInput GetPlantLoopData GetPlantOperationInput GetPlantProfileInput GetPlantSizingInput GetPlantValvesInput GetPollutionFactorInput GetPondGroundHeatExchanger GetPowerManagerInput GetPressureCurveTypeAndIndex GetPressureSystemInput GetPreviousHVACTime GetProjectControlData GetProjectData GetPTUnit GetPTUnitMixedAirNode GetPTUnitOutAirNode GetPTUnitReturnAirNode GetPTUnitZoneInletAirNode GetPumpInput GetPurchasedAir GetPurchasedAirMixedAirHumRat GetPurchasedAirMixedAirTemp GetPurchasedAirOutAirMassFlow GetPurchasedAirReturnAirNode GetPurchasedAirZoneInletAirNode GetPVGeneratorResults GetPVInput GetPVTcollectorsInput GetPVTThermalPowerProduction GetQualityRefrig GetRecordLocations GetRectDetShdSurfaceData GetRectSubSurfaces GetRectSurfaces GetRefrigeratedRackIndex GetRefrigerationInput GetReportVariableInput GetRequiredMassFlowRate GetResidCrossFlowBothUnmixed GetResourceTypeChar GetReturnAirNodeForZone GetReturnAirPathInput GetRoomAirModelParameters GetRunPeriodData GetRunPeriodDesignData GetRuntimeLanguageUserInput GetSatDensityRefrig GetSatEnthalpyRefrig GetSatPressureRefrig GetSatSpecificHeatRefrig GetSatTemperatureRefrig GetScheduledSurfaceGains GetScheduleIndex GetScheduleMaxValue GetScheduleMinValue GetScheduleName GetScheduleType GetScheduleValuesForDay GetSecondaryInletNode GetSecondaryOutletNode GetSetPointManagerInputs GetShadingSurfReflectanceData GetShadowingInput GetShelfInput GetSimpleAirModelInputs GetSimpleShdSurfaceData GetSimpleWatertoAirHPInput GetSingleDayScheduleValues GetSiteAtmosphereData GetSizingParams GetSnowGroundRefModifiers GetSolarCollectorInput GetSpecialDayPeriodData GetSpecificHeatGlycol getSpecificUnitDivider getSpecificUnitIndex getSpecificUnitMultiplier GetSplitterInput GetSplitterInput GetSplitterNodeNumbers GetSplitterOutletNumber GetStandAloneERV GetStandAloneERVNodes GetStandAloneERVOutAirNode GetStandAloneERVReturnAirNode GetStandAloneERVZoneInletAirNode GetStandardMeterResourceType GetSteamBaseboardInput GetSteamCoilAvailScheduleIndex GetSteamCoilControlNodeNum GetSteamCoilIndex GetSteamCoilInput GetSTM GetStormWindowData GetSupHeatDensityRefrig GetSupHeatEnthalpyRefrig GetSupHeatPressureRefrig GetSupplyAirFlowRate GetSupplyAirFlowRate GetSupplyAirInletNode GetSupplyInletNode GetSupplyOutletNode GetSurfaceCountForOSCM GetSurfaceData GetSurfaceGroundHeatExchanger GetSurfaceHeatTransferAlgorithmOverrides GetSurfaceIndecesForOSCM GetSurfaceListsInputs GetSurfHBDataForMundtModel GetSurfHBDataForTempDistModel GetSysAvailManagerInputs GetSysAvailManagerListInputs GetSysInput GetSystemNodeNumberForZone GetSystemSizingInput GetTDDInput GetTESCoilIndex GetTESCoilInput GetThermalChimney GetTowerInput GetTranspiredCollectorIndex GetTranspiredCollectorInput GetTypeOfCoil GetUFADZoneData GetUnitarySystemDXCoolingCoilIndex GetUnitarySystemInput GetUnitarySystemOAHeatCoolCoil GetUnitConversion GetUnitHeaterInput GetUnitsString GetUnitSubString GetUnitVentilatorInput GetUnitVentilatorMixedAirNode GetUnitVentilatorOutAirNode GetUnitVentilatorReturnAirNode GetUnitVentilatorZoneInletAirNode GetUserConvectionCoefficients GetUserDefinedComponents GetUserDefinedOpSchemeInput GetUserDefinedPatternData GetUTSCTsColl GetVariableKeyCountandType GetVariableKeyCountandType GetVariableKeys GetVariableKeys GetVariableTypeAndIndex GetVariableUnitsString GetVarSpeedCoilInput GetVentilatedSlabInput GetVertices GetViscosityGlycol GetVRFInput GetVSCoilCondenserInletNode GetVSCoilMinOATCompressor GetVSCoilNumOfSpeeds GetWaterCoilAvailScheduleIndex GetWaterCoilCapacity GetWaterCoilIndex GetWaterCoilInput GetWaterMainsTemperatures GetWaterManagerInput GetWaterSource GetWaterThermalTankInput GetWatertoAirHPInput GetWatertoWaterHPInput GetWaterUseInput GetWeatherProperties GetWeatherStation GetWindowAC GetWindowACMixedAirNode GetWindowACOutAirNode GetWindowACReturnAirNode GetWindowACZoneInletAirNode GetWindowGapAirflowControlData GetWindowGlassSpectralData GetWindowShadingControlData GetWindTurbineInput GetWrapperInput GetWTGeneratorResults GetZoneAirDistribution GetZoneAirLoopEquipment GetZoneAirSetpoints GetZoneAndZoneListNames GetZoneContaminanInputs GetZoneContaminanSetpoints GetZoneData GetZoneDehumidifierInput GetZoneDehumidifierNodeNumber GetZoneEqAvailabilityManager GetZoneEquipment GetZoneEquipmentData GetZoneEquipmentData1 GetZoneInfilAirChangeRate GetZoneLoads GetZonePlenumInput GetZoneSizingInput GLtoAMB GoAhead guess HasFractionalScheduleValue hatter HCInWindowStandardRatings HConvGap HcUCSDCV HcUCSDDV HcUCSDUF HeatingCoilVarSpeedCycResidual HeatingCoilVarSpeedResidual HeatPumpRunFrac HeatPumpRunFrac HeatPumpRunFrac HeatWatertoAirHPTempResidual Height HEMINT HIC_ASHRAE HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterHeatingCoilResidual HRadPar HTRANS HTRANS0 HTRANS1 HWBaseboardUAResidual HXAssistDXCoilResidual HXAssistedCoolCoilHRResidual HXAssistedCoolCoilHRResidual HXAssistedCoolCoilTempResidual HXAssistedCoolCoilTempResidual HXDemandSideLoopFlowResidual HybridVentilationControl IAM iCheckScheduleValue ICSCollectorAnalyticalSoluton iGetCoilAirOutletNode iGetCoilSteamInletNode iGetCoilSteamOutletNode INCLOS incrementEconVar IncrementInstMeterCache incrementSteps incrementTableEntry InitAirflowNetwork InitAirflowNetworkData InitAirHeatBalance InitAirLoops InitAirLoopSplitter InitAirMixer InitAirTerminalUserDefined InitAirZoneReturnPlenum InitAirZoneSupplyPlenum InitATMixer InitBaseboard InitBaseboard InitBLASTAbsorberModel InitBoiler InitBoiler InitBoreholeHXSimVars InitBSDFWindows InitCBVAV InitCoilUserDefined InitComplexWindows InitComponentNodes InitConductionTransferFunctions InitConnections InitConstCOPChiller InitController InitCoolBeam InitCTGenerators InitCurveReporting InitDaylightingDevices InitDemandManagers InitDesiccantDehumidifier InitDetailedIceStorage InitDirectAir InitDualDuct InitDuct InitDXCoil InitDXCoolingSystem InitDXHeatPumpSystem InitElecReformEIRChiller InitElectricBaseboard InitElectricChiller InitElectricEIRChiller InitEMS InitEMSControlledConstructions InitEMSControlledSurfaceProperties InitEnergyReports InitEngineDrivenChiller InitEquivalentLayerWindowCalculations InitEvapCooler InitEvapFluidCooler InitExhaustAbsorber InitExteriorConvectionCoeff InitFan InitFanCoilUnits InitFluidCooler InitFluidHeatExchanger InitFuelCellGenerators InitFurnace InitGasAbsorber InitGlassOpticalCalculations InitGshp InitGshp InitGTChiller InitHeatBalance InitHeatBalFiniteDiff InitHeatBalHAMT InitHeatingCoil InitHeatRecovery InitHighTempRadiantSystem InitHumidifier InitHWBaseboard InitHXAssistedCoolingCoil InitHybridVentSysAvailMgr InitialInitHeatBalFiniteDiff InitializeCFSDaylighting InitializeCFSStateData InitializeComponentSizingTable InitializeConstructionsTables InitializeDaylightMapTables InitializeEnvironmentPeriodsTable InitializeErrorsTable InitializeGlycolTempLimits InitializeHeatTransferPipes InitializeIndexes InitializeIndexes InitializeLoops InitializeMaterialsTable InitializeMeters initializeMonetaryUnit InitializeNominalBaseboardHeatTable InitializeNominalElectricEquipmentTable InitializeNominalGasEquipmentTable InitializeNominalHotWaterEquipmentTable InitializeNominalInfiltrationTable InitializeNominalLightingTable InitializeNominalOtherEquipmentTable InitializeNominalPeopleTable InitializeNominalSteamEquipmentTable InitializeNominalVentilationTable InitializeOperatingMode InitializeOutput InitializePipes InitializePredefinedMonthlyTitles InitializePsychRoutines InitializePumps InitializeRefrigerantLimits InitializeReportMeterDataDictionaryTable InitializeReportMeterDataTables InitializeReportVariableDataDictionaryTable InitializeReportVariableDataTables InitializeRoomAirModelTable InitializeRootFinder InitializeRuntimeLanguage InitializeSchedulesTable InitializeSimulationsTable InitializeSQLiteTables InitializeSurfacesTable InitializeSystemSizingTable InitializeTabularDataTable InitializeTabularDataTable InitializeTabularDataView InitializeTabularDataView InitializeTabularMonthly InitializeTimeIndicesTable InitializeViews InitializeWeather InitializeZoneGroupTable InitializeZoneInfoTable InitializeZoneListTable InitializeZoneSizingTable InitICEngineGenerators InitIndirectAbsorpChiller InitIndUnit InitInteriorConvectionCoeffs InitInteriorRadExchange InitInternalHeatGains InitIntSolarDistribution InitLoadBasedControl InitLoadDistribution InitLowTempRadiantSystem InitMicroCHPNoNormalizeGenerators InitMoistureBalanceEMPD InitMSHeatPump InitMTGenerators InitMundtModel InitOAController InitOAMixer InitOneTimePlantSizingInfo InitOutAirNodes InitOutdoorAirUnit InitOutsideAirSys InitPipesHeatTransfer InitPipingSystems InitPIU InitPlantProfile InitPlantUserComponent InitPlantValves InitPollutionMeterReporting InitPondGroundHeatExchanger InitPressureDrop InitPTUnit InitPurchasedAir InitPVTcollectors InitRefrigeration InitRefrigerationPlantConnections InitReturnAirPath InitSecretObjects InitSetPointManagers InitSimpleIceStorage InitSimpleMixingConvectiveHeatGains InitSimpleWatertoAirHP InitSimVars InitSimVars InitSimVars InitSimVars InitSolarCalculations InitSolarCollector InitSolarHeatGains InitSolReflRecSurf InitStandAloneERV InitSteamBaseboard InitSteamCoil InitSurfaceGroundHeatExchanger InitSurfaceHeatBalance InitSys InitSysAvailManagers InitSystemOutputRequired InitTempDistModel InitTESCoil InitThermalAndFluxHistories InitThermalComfort InitTower InitTranspiredCollector InitTRNSYSPV InitUCSDCV InitUCSDDV InitUCSDUF InitUniqueNodeCheck InitUnitarySystems InitUnitHeater InitUnitVentilator InitVarSpeedCoil InitVentilatedSlab InitVRF InitWaterCoil InitWaterSource InitWaterThermalTank InitWatertoAirHP InitWatertoWaterHP InitWindowAC InitWindTurbine InitWrapper InitZoneAirLoopEquipment InitZoneAirSetpoints InitZoneAirUserDefined InitZoneContSetpoints InitZoneDehumidifier InitZoneEquipment InitZoneEvaporativeCoolerUnit InPolygon InsertCurrencySymbol int_times_vector INTCPT Integer_IsInRange IntegerIsWithinTwoValues IntegerToString InterConnectTwoPlantLoopSides InteriorBCEqns InteriorNodeEqns InternalRangeCheck InternalSetupTankDemandComponent InternalSetupTankSupplyComponent interp INTERP InterpBlind InterpDefValuesForGlycolConc Interpolate Interpolate_Lagrange InterpolateBetweenFourValues InterpolateBetweenTwoValues InterpolatePipeTransBeam InterpProfAng InterpProfSlatAng InterpretWeatherDataLine InterpSlatAng InterpSw InterpValuesForGlycolConc IntInterfaceNodeEqns IntPreDefTableEntry IntToStr Invert3By3Matrix InvertMatrix InvJulianDay IPTrimSigDigits iRoundSigDigits IS_BEAM IS_DIFF IS_DSRATIO IS_F IS_LWP IS_OPENNESS IS_SWP isCompLoadRepReq IsControlledShade IsConverged_CurrentToPrevIteration IsConverged_PipeCurrentToPrevIteration IsCurveInputTypeValid IsCurveOutputTypeValid isExternalInterfaceErlVariable IsGlazeLayerX IsGZSLayer isInQuadrilateral IsInRange isInTriangle IsLeapYear IsNodeOnSetPtManager IsParentObject IsParentObjectCompSet IsShadingLayer IssueSevereAlphaInputFieldError IssueSevereInputFieldError IssueSevereRealInputFieldError IsValidConnectionType IsVBLayer isWithinRange ITERATE IterateRootFinder iTrimSigDigits JGDate JulianDay LClimb LDSumMax LDSumMean LEEDtariffReporting LimitCoilCapacity LimitController LimitTUCapacity LinesOut linint LoadEquipList LoadInterface LogicalToInteger LogicalToInteger LogPlantConvergencePoints lookupOperator LookUpScheduleValue LookUpSeason LookupSItoIP lubksb LUBKSB ludcmp LUDCMP LUdecomposition LUsolution MakeAnchorName MakeHVACTimeIntervalString MakeMirrorSurface MakeRectangularVertices MakeRelativeRectangularVertices MakeTransition MakeUPPERCase ManageAirflowNetworkBalance ManageAirHeatBalance ManageAirLoops ManageAirModel ManageBranchInput ManageControllers ManageCoolTower ManageDemand ManageEarthTube ManageElectCenterStorageInteractions ManageElectricLoadCenters ManageElectStorInteractions ManageEMS ManageExteriorEnergyUse ManageGeneratorControlState ManageGeneratorFuelFlow ManageHeatBalance ManageHeatBalFiniteDiff ManageHeatBalHAMT ManageHVAC ManageHybridVentilation ManageInsideAdaptiveConvectionAlgo ManageInternalHeatGains ManageInverter ManageMundtModel ManageNonZoneEquipment ManageOutsideAdaptiveConvectionAlgo ManageOutsideAirSystem ManagePlantLoadDistribution ManagePlantLoops ManageRefrigeratedCaseRacks ManageSetPoints ManageSimulation ManageSingleCommonPipe ManageSizing ManageSurfaceHeatBalance ManageSystemAvailability ManageThermalChimney ManageThermalComfort ManageTransformers ManageTwoWayCommonPipe ManageUCSDCVModel ManageUCSDDVModel ManageUCSDUFModels ManageUserDefinedPatterns ManageWater ManageWaterInits ManageWeather ManageZoneAirLoopEquipment ManageZoneAirUpdates ManageZoneContaminanUpdates ManageZoneEquipment MapExtConvClassificationToHcModels MapIntConvClassificationToHcModels MarkNode MatchAndSetColorTextString MatchPlantSys MatrixIndex matrixQBalance MeshPartition_CompareByDimension MeshPartition_SelectionSort MeshPartitionArray_Contains MinePlantStructForInfo MixedAirControlTempResidual ModifyWindow Modulus MonthToMonthNumber MovingAvg MRXINV MSHPCyclingResidual MSHPHeatRecovery MSHPVarSpeedResidual MultiModeDXCoilHumRatResidual MultiModeDXCoilHumRatResidual MultiModeDXCoilResidual MultiModeDXCoilResidual MultiModeDXCoilResidual MultiSpeedDXCoolingCoilStandardRatings MultiSpeedDXHeatingCoilStandardRatings MULTOL MyPlantSizingIndex NeighborInformationArray_Value NETRAD NewEMSVariable NewExpression newPreDefColumn newPreDefReport newPreDefSubTable NEWTON NodeHasSPMCtrlVarType NormalArea NumBranchesInBranchList NumCompsInBranch nusselt NusseltNumber OpenEPlusWeatherFile OPENNESS_LW OpenOutputFiles OpenOutputTabularFile OpenWeatherFile OPERATOR (*) OPERATOR (+) OPERATOR (-) OPERATOR (.dot.) OPERATOR (.twodcross.) OPERATOR (.twoddot.) OPERATOR (/) ORDER OutBaroPressAt OutDewPointTempAt OutDryBulbTempAt OutsidePipeHeatTransCoef OutWetBulbTempAt P01 PanesDeflection ParametricObjectsCheck parseComputeLine ParseExpression ParseStack ParseTime PartLoadFactor PassiveGapNusseltNumber PassPressureAcrossInterface PassPressureAcrossMixer PassPressureAcrossSplitter PD_BEAM PD_BEAM_CASE_I PD_BEAM_CASE_II PD_BEAM_CASE_III PD_BEAM_CASE_IV PD_BEAM_CASE_V PD_BEAM_CASE_VI PD_DIFF PD_LW PD_LWP PD_SWP PerformanceCurveObject PerformanceTableObject PerformIterationLoop PerformPipeCellSimulation PerformPipeCircuitSimulation PerformSolarCalculations PerformTemperatureFieldUpdate PierceSurface PierceSurfaceVector PipeCircuitInfo_InitInOutCells PipeSegmentInfo_InitPipeCells PIUInducesPlenumAir PIUnitHasMixer PlaneEquation PlantHalfLoopSolver PlantMassFlowRatesFunc PLRResidual PLRResidual PLRResidualMixedTank PLRResidualStratifiedTank PMVResidual POLY1F POLY2F POLYF polygon_contains_point_2d popStack pos PostIPProcessing POWER PreDefTableEntry PredictSystemLoads PredictZoneContaminants PreparePipeCircuitSimulation PrepDebugFilesAndVariables PreProcessorCheck PrepVariablesISO15099 PreScanReportingVariables PresProfile PressureCurveValue ProcessDataDicFile ProcessDateString ProcessEMSInput ProcessEPWHeader ProcessForDayTypes ProcessInput ProcessInputDataFile ProcessIntervalFields ProcessMinMaxDefLine ProcessNumber ProcessScheduleInput ProcessSurfaceVertices ProcessTokens ProduceMinMaxString ProduceMinMaxStringWStartMinute ProduceRDDMDD ProfileAngle PropagateResolvedFlow PStack PsyCpAirFnWTdb PsyHfgAirFnWTdb PsyHFnTdbRhPb PsyHFnTdbW PsyHgAirFnWTdb PsyPsatFnTemp PsyPsatFnTemp_raw PsyRhFnTdbRhov PsyRhFnTdbRhovLBnd0C PsyRhFnTdbWPb PsyRhoAirFnPbTdbW PsyRhovFnTdbRh PsyRhovFnTdbRhLBnd0C PsyRhovFnTdbWPb PsyTdbFnHW PsyTdpFnTdbTwbPb PsyTdpFnWPb PsyTsatFnHPb PsyTsatFnPb PsyTwbFnTdbWPb PsyTwbFnTdbWPb_raw PsyVFnTdbWPb PsyWFnTdbH PsyWFnTdbRhPb PsyWFnTdbTwbPb PsyWFnTdpPb psz Pt2Plane PullCompInterconnectTrigger PumpDataForTable PushBranchFlowCharacteristics PushInnerTimeStepArrays pushStack PushSystemTimestepHistories PushSystemTimestepHistories PushZoneTimestepHistories PushZoneTimestepHistories QsortC QsortPartition RadialCellInfo_XY_CrossSectArea RadialCellInformation_ctor RadialSizing_Thickness Rainflow RangeCheck RB_BEAM RB_DIFF RB_F RB_LWP RB_SWP rCheckDayScheduleValueMinMax rCheckScheduleValue rCheckScheduleValueMinMax1 rCheckScheduleValueMinMax2 ReadEnergyMeters ReadEPlusWeatherForDay ReadGeneralDomainInputs ReadHorizontalTrenchInputs ReadINIFile ReadInputLine ReadPipeCircuitInputs ReadPipeSegmentInputs ReadTableData ReadUserWeatherInput ReadWeatherForDay Real_ConstrainTo Real_IsInRange real_times_vector ReAllocateAndPreserveOutputVariablesForSimulation ReallocateIntegerArray ReallocateIVar ReallocateRealArray ReallocateRVar RealPreDefTableEntry RealToStr RecKeepHeatBalance RecordOutput RectangleF_Contains ReformEIRChillerCondInletTempResidual ReformEIRChillerHeatRecovery RegisterNodeConnection RegisterPlantCompDesignFlow RegulateCondenserCompFlowReqOp ReInitPlantLoopsAtFirstHVACIteration RemoveSpaces RemoveTrailingZeros reorder ReplaceBlanksWithUnderscores ReplaceBlanksWithUnderscores ReportAirflowNetwork ReportAirHeatBalance ReportAirLoopConnections ReportAirTerminalUserDefined ReportAndTestGlycols ReportAndTestRefrigerants ReportBaseboard ReportBaseboard ReportCBVAV ReportChillerIPLV ReportCoilUserDefined ReportCompSetMeterVariables ReportController ReportCoolBeam ReportCoolTower ReportCTFs ReportCWTankInits ReportDemandManagerList ReportDesiccantDehumidifier ReportDetailedIceStorage ReportDirectAir ReportDualDuct ReportDualDuctConnections ReportDuct ReportDXCoil ReportDXCoilRating ReportDYMeters ReportEarthTube ReportEconomicVariable ReportElectricBaseboard ReportEMS ReportEvapCooler ReportEvapFluidCooler ReportExteriorEnergyUse ReportFan ReportFanCoilUnit ReportFatalGlycolErrors ReportFatalRefrigerantErrors ReportFiniteDiffInits ReportFluidCooler ReportFluidHeatExchanger ReportForTabularReports ReportFurnace ReportGlass ReportHeatBalance ReportHeatingCoil ReportHeatRecovery ReportHighTempRadiantSystem ReportHRMeters ReportHumidifier ReportHWBaseboard ReportIllumMap ReportingFreqName ReportingThisVariable ReportInternalHeatGains ReportLoopConnections ReportLowTempRadiantSystem ReportMaxVentilationLoads ReportMeterDetails ReportMissing_RangeData ReportMixer ReportMNMeters ReportMoistureBalanceEMPD ReportMSHeatPump ReportNodeConnections ReportOAController ReportOAMixer ReportOrphanFluids ReportOrphanRecordObjects ReportOrphanSchedules ReportOutdoorAirUnit ReportOutputFileHeaders ReportParentChildren ReportPipesHeatTransfer ReportPIU ReportPlantProfile ReportPlantUserComponent ReportPlantValves ReportPondGroundHeatExchanger ReportPTUnit ReportPumps ReportPurchasedAir ReportPV ReportRackSystem ReportRefrigerationComponents ReportReturnAirPath ReportRuntimeLanguage ReportScheduleDetails ReportScheduleValues ReportSizingOutput ReportSMMeters ReportSolarCollector ReportSplitter ReportStandAloneERV ReportStandAloneWaterUse ReportSteamBaseboard ReportSteamCoil ReportSurfaceErrors ReportSurfaceGroundHeatExchngr ReportSurfaceHeatBalance ReportSurfaces ReportSurfaceShading ReportSys ReportSysSizing ReportSystemEnergyUse ReportThermalChimney ReportTowers ReportTSMeters ReportUnitarySystem ReportUnitHeater ReportUnitVentilator ReportVentilatedSlab ReportVRFCondenser ReportVRFTerminalUnit ReportWarmupConvergence ReportWaterCoil ReportWaterManager ReportWaterThermalTank ReportWaterUse ReportWeatherAndTimeInformation ReportWindowAC ReportWindTurbine ReportZoneAirLoopEquipment ReportZoneAirUserDefined ReportZoneDehumidifier ReportZoneEquipment ReportZoneEvaporativeCoolerUnit ReportZoneMeanAirTemp ReportZoneReturnPlenum ReportZoneSizing ReportZoneSupplyPlenum ResetAllPlantInterConnectFlags ResetController ResetEnvironmentCounter ResetHVACControl ResetNodeData ResetPerformanceCurveOutput ResetRootFinder ResetTerminalUnitFlowLimits ResetWeekDaysByMonth Resimulate resist ReSolveAirLoopControllers ResolveAirLoopFlowLimits ResolveLocationInformation ResolveLockoutFlags ResolveLoopFlowVsPressure ResolveParallelFlows ResolveSysFlow ReverseAndRecalculate RevertZoneTimestepHistories RevertZoneTimestepHistories RevisePlantCallingOrder RezeroZoneSizingArrays RhoH2O RHtoVP RKG RoundSigDigits rRoundSigDigits rTrimSigDigits SafeCopyPlantNode SafeDiv SafeDivide SameString SandiaCellTemperature SandiaEffectiveIrradiance SandiaF1 SandiaF2 SandiaImp SandiaIsc SandiaIx SandiaIxx SandiaModuleTemperature SandiaTcellFromTmodule SandiaVmp SandiaVoc SaveSimpleController ScanForReports ScanPlantLoopsForNodeNum ScanPlantLoopsForObject sCheckDayScheduleValueMinMax ScheduleAverageHoursPerWeek SEARCH SearchAscTable SearchWindow5DataFile SecantFormula SecantMethod selectTariff SetActuatedBranchFlowRate SetAdditionalNeighborData SetAllFlowLocks SetAllPlantSimFlagsToValue SetATMixerPriFlow SetATMixerPriFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetCoilDesFlow SetCoilSystemCoolingData SetCoilSystemHeatingDXFlag SetCompFlowRate SetComponentFlowRate SetCurrentWeather SetCurveOutputMinMaxValues SetDSTDateRanges SetDXCoilTypeData SetDXCoolingCoilData SetEquivalentLayerWindowProperties SetErlValueNumber SetExtConvectionCoeff SetFanData SetHeatExchangerData SetHeatToReturnAirFlag SetInitialMeterReportingAndOutputNames SetIntConvectionCoeff SetInternalVariableValue SetMinMax setNativeVariables SetNodeResult SetOAControllerData SetOnOffMassFlowRate SetOnOffMassFlowRate SetOnOffMassFlowRate SetOnOffMassFlowRateVSCoil SetOnOffMassFlowRateVSCoil SetOutAirNodes SetOutBulbTempAt SetPredefinedTables SetSimpleWSHPData SETSKY SetSpecialDayDates SetSpeedVariables SetStormWindowControl SetSurfHBDataForMundtModel SetSurfHBDataForTempDistModel SetSurfTmeanAir SETUP4x4_A SetupAdaptiveConvectionRadiantSurfaceData SetupAdaptiveConvectionStaticMetaData SetupAirLoopControllersTracer SetupAllOutputVariables SetUpAndSort SetupBranchControlTypes SetupCellNeighbors SetupCommonPipes SetupComplexFenestrationMaterialInput SetupComplexFenestrationStateInput SetupComplexWindowStateGeometry SetUpCompSets SetupDElightOutput4EPlus SetupDElightOutput4EPlus SetUpDesignDay SetupEMSActuator SetupEMSIntegerActuator SetupEMSIntegerInternalVariable SetupEMSInternalVariable SetupEMSLogicalActuator SetupEMSRealActuator SetupEMSRealInternalVariable SetupEnvironmentTypes SetupFuelConstituentData SetupGeneratorControlStateManager SetupIndividualControllerTracer SetupInitialPlantCallingOrder SetupIntegerOutputVariable SetupInterpolationValues SetupLoopFlowRequest SetupMeteredVarsForSetPt SetupMundtModel SetupNodeSetpointsAsActuators SetupNodeVarsForReporting SetupOutputVariable SetupPipeCircuitInOutCells SetupPlantEMSActuators SetupPollutionCalculations SetupPollutionMeterReporting SetupPossibleOperators SetupPrimaryAirSystemAvailMgrAsActuators SetupPumpMinMaxFlows SetupRealOutputVariable SetupRealOutputVariable_IntKey SetupReportInput SetupReports SetupRootFinder SetUpSchemeColors SetupShadeSurfacesForSolarCalcs SetupSimpleWindowGlazingSystem SetupSimulation SetupStratifiedNodes SetupSurfaceConstructionActuators SetupSurfaceConvectionActuators SetupSurfaceOutdoorBoundaryConditionActuators SetUpSysSizingArrays SetupTankDemandComponent SetupTankSupplyComponent SetupThermostatActuators SetupTimePointers SetupUnitConversions SetupWeekDaysByMonth SetupWindowShadingControlActuators SetupZoneEquipmentForConvectionFlowRegime SetupZoneGeometry SetupZoneInfoAsInternalDataAvail SetupZoneInternalGain SetupZoneInternalGain SetupZoneSizing SetUpZoneSizingArrays SetUTSCQdotSource SetVarSpeedCoilData SetVentedModuleQdotSource SetVSHPAirFlow SetVSHPAirFlow SetWindSpeedAt SetZoneEquipSimOrder shading shadingedge shadingin SHADOW SharedDVCVUFDataInit SHDBKS SHDGSS SHDRVL SHDSBS shift ShiftPipeTemperaturesForNewIteration ShiftPlantLoopSideCallingOrder ShiftTemperaturesForNewIteration ShiftTemperaturesForNewTimeStep ShowAuditErrorMessage ShowBranchesOnLoop ShowContinueError ShowContinueError ShowContinueErrorTimeStamp ShowContinueErrorTimeStamp ShowErrorMessage ShowErrorMessage ShowFatalError ShowFatalError ShowMessage ShowMessage ShowPsychrometricSummary ShowRecurringContinueErrorAtEnd ShowRecurringContinueErrorAtEnd ShowRecurringErrors ShowRecurringSevereErrorAtEnd ShowRecurringSevereErrorAtEnd ShowRecurringWarningErrorAtEnd ShowRecurringWarningErrorAtEnd ShowSevereError ShowSevereError ShowSevereMessage ShowSevereMessage ShowWarningError ShowWarningError ShowWarningMessage ShowWarningMessage showWarningsBasedOnTotal Sim4PipeFanCoil SimAirChillerSet SimAirLoop SimAirLoopComponent SimAirLoopComponents SimAirLoops SimAirLoopSplitter SimAirMixer SimAirTerminalUserDefined SimAirZonePlenum SimATMixer SimBaseboard SimBLASTAbsorber SimBoiler SimCBVAV SimCBVAV SimCentralGroundSourceHeatPump SimChiller SimCoilUserDefined SimComponentModelFan SimConstVol SimCoolBeam SimCostEstimate SimCTGenerator SimCTPlantHeatRecovery SimCyclingWindowAC SimDesiccantDehumidifier SimDetailedIceStorage SimDirectAir SimDistrictEnergy SimDualDuctConstVol SimDualDuctVarVol SimDualDuctVAVOutdoorAir SimDuct SimDXCoil SimDXCoilMultiMode SimDXCoilMultiSpeed SimDXCoolingSystem SimDXHeatPumpSystem SimElecBaseBoard SimElectricBaseBoard SimElectricConvective SimElectricEIRChiller SimEvapCooler SimEvapFluidCoolers SimExhaustAbsorber SimFanCoilUnit SimFluidCoolers SimFluidHeatExchanger SimFourPipeIndUnit SimFuelCellGenerator SimFuelCellPlantHeatRecovery SimFurnace SimGasAbsorber SimGroundHeatExchangers SimHeatPumpWaterHeater SimHeatRecovery SimHighTempRadiantSystem SimHPWatertoWaterCOOLING SimHPWatertoWaterHEATING SimHPWatertoWaterSimple SimHumidifier SimHVAC SimHWBaseboard SimHWConvective SimHXAssistedCoolingCoil SimICEngineGenerator SimICEPlantHeatRecovery SimIceStorage SimIndirectAbsorber SimIndUnit SimLowTempRadiantSystem SimMicroCHPGenerator SimMicroCHPPlantHeatRecovery SimMSHeatPump SimMSHP SimMTGenerator SimMTPlantHeatRecovery SimMultiSpeedCoils SimOAComponent SimOAController SimOAMixer SimOnOffFan SimOutdoorAirEquipComps SimOutdoorAirUnit SimOutsideAirSys SimOutsideEnergy SimPackagedTerminalUnit SimPipes SimPipesHeatTransfer SimPipingSystemCircuit SimPIU SimPlantEquip SimPlantValves SimpleCoolingCoilUAResidual SimpleEvapFluidCoolerUAResidual SimpleFluidCoolerUAResidual SimpleHeatingCoilUAResidual SimpleTowerApproachResidual SimpleTowerTrResidual SimpleTowerUAResidual SimPondGroundHeatExchanger SimPressureDropSystem SimPTUnit SimPumps SimPurchasedAir SimPVGenerator SimPVTcollectors SimReformulatedEIRChiller SimRefrigCondenser SimReturnAirPath SimSelectedEquipment SimSetPointManagers SimSimpleEvapFluidCooler SimSimpleFan SimSimpleFluidCooler SimSimpleTower SimSolarCollector SimStandAloneERV SimSteamBaseboard SimSteamBoiler SimSteamCoils SimSurfaceGroundHeatExchanger SimSysAvailManager SimTESCoil SimTowers SimTranspiredCollector SimulateAllInteriorRadialSoilSlices SimulateAllLoopSideBranches SimulateAllLoopSidePumps SimulateDemandManagerList SimulateDetailedRefrigerationSystems SimulateDetailedTransRefrigSystems SimulateDualDuct SimulateFanComponents SimulateFluidCell SimulateHeatingCoilComponents SimulateInnerMostRadialSoilSlice SimulateLoopSideBranchGroup SimulateOuterMostRadialSoilSlice SimulatePlantProfile SimulateRadialInsulationCell SimulateRadialPipeCell SimulateRadialToCartesianInterface SimulateSingleDuct SimulateSteamCoilComponents SimulateVRF SimulateWaterCoilComponents SimulateWaterHeaterStandAlone SimulateWaterUse SimulateWaterUseConnection SimUnitaryBypassVAV SimUnitarySystem SimUnitHeater SimUnitVentilator SimUnitVentOAMixer SimUserDefinedPlantComponent SimVariableSpeedCoils SimVariableSpeedHP SimVariableSpeedHP SimVariableTower SimVariableVolumeFan SimVAV SimVAVVS SimVentilatedSlab SimVentSlabOAMixer SimVRF SimVRFCondenserPlant SimWaterCoils SimWaterSource SimWaterThermalTank SimWatertoAirHP SimWatertoAirHPSimple SimWindowAC SimWindTurbine SimZoneAirLoopEquipment SimZoneAirUserDefined SimZoneDehumidifier SimZoneEquipment SimZoneEvaporativeCoolerUnit SimZoneExhaustFan SimZoneOutAirUnitComps SingelSpeedDXCoolingCoilStandardRatings SingleSpeedDXHeatingCoilStandardRatings SingleSpeedFluidCooler SizeAbsorpChiller SizeAirLoopBranches SizeAirLoops SizeBaseboard SizeBoiler SizeBoiler SizeCBVAV SizeConstCOPChiller SizeController SizeCoolBeam SizeDemandSidePlantConnections SizeDirectAir SizeDualDuct SizeDXCoil SizeElecReformEIRChiller SizeElectricBaseboard SizeElectricBaseboard SizeElectricChiller SizeElectricEIRChiller SizeEngineDrivenChiller SizeEvapCooler SizeEvapFluidCooler SizeExhaustAbsorber SizeFan SizeFanCoilUnit SizeFluidCooler SizeFluidHeatExchanger SizeFurnace SizeGasAbsorber SizeGTChiller SizeHeatingCoil SizeHeatRecovery SizeHighTempRadiantSystem SizeHumidifier SizeHVACWaterToAir SizeHWBaseboard SizeIndirectAbsorpChiller SizeIndUnit SizeLowTempRadiantSystem SizeMSHeatPump SizeOAController SizeOutdoorAirUnit SizePIU SizePlantLoop SizePTUnit SizePump SizePurchasedAir SizePVT SizeStandAloneERV SizeStandAloneWaterHeater SizeSteamBaseboard SizeSteamCoil SizeSupplySidePlantConnections SizeSys SizeTankForDemandSide SizeTankForSupplySide SizeTESCoil SizeTower SizeUCSDUF SizeUnitarySystem SizeUnitHeater SizeUnitVentilator SizeVarSpeedCoil SizeVentilatedSlab SizeVRF SizeVRFCondenser SizeVSMerkelTower SizeWaterCoil SizeWaterManager SizeWaterSource SizeWindowAC SizeWrapper SizeZoneDehumidifier SizeZoneEquipment SizeZoneEvaporativeCoolerUnit SkipEPlusWFHeader SkyDifSolarShading SkyGndWeight SkyWeight SLtoAMB SLtoGL SLVSKY solar_EN673 solarISO15099 SolarSprectrumAverage SOLMATS SolveAirLoopControllers SolveForWindowTemperatures SolveRegression SolveRegulaFalsi SolverMoistureBalanceEMPD SOLVZP SortHistory Specular_Adjust Specular_EstimateDiffuseProps Specular_F Specular_OffNormal Specular_RATDiff Specular_SWP SQLiteBegin SQLiteBegin SQLiteBindDouble SQLiteBindInteger SQLiteBindLogicalMacro SQLiteBindNULL SQLiteBindText SQLiteBindTextMacro SQLiteClearBindings SQLiteCloseDatabase SQLiteColumnInt SQLiteColumnIntMacro SQLiteCommit SQLiteCommit SQLiteExecuteCommand SQLiteExecuteCommandMacro SQLiteFinalizeCommand SQLiteOpenDatabase SQLiteOpenDatabaseMacro SQLitePrepareStatement SQLitePrepareStatementMacro SQLiteResetCommand SQLiteStepCommand SQLiteWriteMessage SQLiteWriteMessageMacro SQLiteWriteMessageMacro StandardIndexTypeKey StandardVariableTypeKey StartingWindowTemps StartingWinTempsForNominalCond SteamHeatingCoilResidual StorageType StoreAPumpOnCurrentTempLoop storeIterationResults StoreRecurringErrorMessage StringValue StrToReal SumAllInternalCO2Gains SumAllInternalConvectionGains SumAllInternalGenericContamGains SumAllInternalLatentGains SumAllInternalRadiationGains SumAllReturnAirConvectionGains SumAllReturnAirLatentGains SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumInternalCO2GainsByTypes SumInternalConvectionGainsByTypes SumInternalLatentGainsByTypes SumInternalRadiationGainsByTypes SummarizeErrors SumReturnAirConvectionGainsByTypes SumZoneImpacts SUN3 SUN4 SupSATResidual SurfaceScheduledSolarInc SurveyDemandManagers SystemPropertiesAtLambdaAndPhi SystemSpectralPropertiesAtPhi TableLookupObject TARCOG90 TBND TdbFnHRhPb TDMA TDMA_R TellMeHowManyObjectItemArgs TemperaturesFromEnergy TempIPtoSI TempSItoIP terpld TESCoilHumRatResidual TESCoilResidual TestAirPathIntegrity TestBranchIntegrity TestCompSet TestCompSetInletOutletNodes TestInletOutletNodes TestReturnAirPathIntegrity TestSupplyAirPathIntegrity therm1d TightenNodeMinMaxAvails TimestepInitComplexFenestration TimestepTypeName TraceAirLoopController TraceAirLoopControllers TraceIndividualController TraceIterationStamp TrackAirLoopController TrackAirLoopControllers TRadC TransAndReflAtPhi TransformVertsByAspect TransTDD Triangulate TrimSigDigits TurnOffLoopEquipment TurnOffLoopSideEquipment TurnOffReportRangeCheckErrors TurnOnPlantLoopPipes TurnOnReportRangeCheckErrors TwoSpeedFluidCooler UnitarySystemHeatRecovery UpdateAbsorberChillerComponentGeneratorSide UpdateAirflowNetwork UpdateAirMixer UpdateAirSysCompPtrArray UpdateAirSysSubCompPtrArray UpdateAirSysSubSubCompPtrArray UpdateAirZoneReturnPlenum UpdateAirZoneSupplyPlenum UpdateAnyLoopDemandAlterations UpdateATMixer UpdateBaseboard UpdateBaseboardPlantConnection UpdateBasementSurfaceTemperatures UpdateBBElecRadSourceValAvg UpdateBBRadSourceValAvg UpdateBBSteamRadSourceValAvg UpdateBLASTAbsorberRecords UpdateBoilerRecords UpdateBoilerRecords UpdateBracket UpdateBranchConnections UpdateChillerComponentCondenserSide UpdateChillerheaterRecords UpdateChillerRecords UpdateColdWeatherProtection UpdateCommonPipe UpdateComplexWindows UpdateComponentHeatRecoverySide UpdateConstCOPChillerRecords UpdateController UpdateCoolBeam UpdateCoolTower UpdateCTGeneratorRecords UpdateDataandReport UpdateDemandManagers UpdateDesiccantDehumidifier UpdateDetailedIceStorage UpdateDualDuct UpdateDuct UpdateDXCoil UpdateElectricBaseboard UpdateElectricChillerRecords UpdateElectricEIRChillerRecords UpdateEMSTrendVariables UpdateEngineDrivenChiller UpdateEvapCooler UpdateEvapFluidCooler UpdateEvaporativeCondenserBasinHeater UpdateEvaporativeCondenserWaterUse UpdateExhaustAbsorberCoolRecords UpdateExhaustAbsorberHeatRecords UpdateExhaustAirFlows UpdateFan UpdateFinalSurfaceHeatBalance UpdateFluidCooler UpdateFluidHeatExchanger UpdateFuelCellGeneratorRecords UpdateGasAbsorberCoolRecords UpdateGasAbsorberHeatRecords UpdateGSHPRecords UpdateGSHPRecords UpdateGSHPRecords UpdateGTChillerRecords UpdateHalfLoopInletTemp UpdateHeatBalHAMT UpdateHeatingCoil UpdateHeatRecovery UpdateHighTempRadiantSystem UpdateHistories UpdateHistory UpdateHTRadSourceValAvg UpdateHumidifier UpdateHVACInterface UpdateHWBaseboard UpdateHWBaseboardPlantConnection UpdateIceFractions UpdateICEngineGeneratorRecords UpdateIndirectAbsorberRecords UpdateInternalGainValues UpdateIrrigation UpdateLoadCenterRecords UpdateLoopSideReportVars UpdateLowTempRadiantSystem UpdateMeterReporting UpdateMeters UpdateMeterValues UpdateMicroCHPGeneratorRecords UpdateMinMax UpdateMixedAirSetPoints UpdateMoistureBalanceEMPD UpdateMoistureBalanceFD UpdateMSHeatPump UpdateMTGeneratorRecords UpdateNode UpdateNodeThermalHistory UpdateOAController UpdateOAMixer UpdateOAPretreatSetPoints UpdatePipesHeatTransfer UpdatePipingSystems UpdatePlantLoopInterface UpdatePlantMixer UpdatePlantProfile UpdatePlantSplitter UpdatePlantValves UpdatePondGroundHeatExchanger UpdatePrecipitation UpdatePressureDrop UpdatePurchasedAir UpdatePVTcollectors UpdateRadSysSourceValAvg UpdateRecords UpdateReformEIRChillerRecords UpdateRefrigCondenser UpdateReportWaterSystem UpdateRootFinder UpdateScheduleValues UpdateSetPointManagers UpdateSimpleWatertoAirHP UpdateSoilProps UpdateSolarCollector UpdateSplitter UpdateSQLiteErrorRecord UpdateSQLiteErrorRecord UpdateSQLiteSimulationRecord UpdateSQLiteSimulationRecord UpdateSteamBaseboard UpdateSteamBaseboardPlantConnection UpdateSteamCoil UpdateSurfaceGroundHeatExchngr UpdateSys UpdateSysSizing UpdateSystemOutputRequired UpdateTabularReports UpdateTEStorage UpdateThermalHistories UpdateTowers UpdateTranspiredCollector UpdateUnitarySystemControl UpdateUtilityBills UpdateVarSpeedCoil UpdateVentilatedSlab UpdateVerticalGroundHeatExchanger UpdateVRFCondenser UpdateWaterCoil UpdateWaterConnections UpdateWaterManager UpdateWaterSource UpdateWaterThermalTank UpdateWaterToAirCoilPlantConnection UpdateWatertoAirHP UpdateWeatherData UpdateWholeBuildingRecords UpdateZoneAirLoopEquipment UpdateZoneCompPtrArray UpdateZoneDehumidifier UpdateZoneEquipment UpdateZoneInletConvergenceLog UpdateZoneListAndGroupLoads UpdateZoneSizing UpdateZoneSubCompPtrArray UpdateZoneSubSubCompPtrArray ValidateAndSetSysAvailabilityManagerType ValidateComponent ValidateDistributionSystem ValidateEMSProgramName ValidateEMSVariableName ValidateExhaustFanInput ValidateFlowControlPaths ValidateFuelType ValidateIndexType ValidateMaterialRoughness ValidateMonthDay ValidateNStandardizeMeterTitles ValidateObjectandParse ValidatePipeConstruction ValidatePLFCurve ValidateSection ValidateSectionsInput ValidateVariableType value_to_vector ValueToString VAVVSCoolingResidual VAVVSHCFanOnResidual VAVVSHWFanOnResidual VAVVSHWNoFanResidual VB_CriticalSlatAngle VB_DIFF VB_LWP VB_ShadeControl VB_SLAT_RADIUS_RATIO VB_SOL4 VB_SOL46_CURVE VB_SOL6 VB_SWP vec2d_cross_product vec2d_dot_product vec_cross_product vec_dot_product VecLength VecNegate VecNormalize VecRound VecSquaredLength vector_add vector_div_int vector_div_real vector_subtract vector_times_int vector_times_real vector_to_array VerifyControlledZoneForThermostat VerifyCustomMetersElecPowerMgr VerifyHeatExchangerParent VerifyName VerifySetPointManagers VerifyThermostatInZone VerifyUniqueBaseboardName VerifyUniqueBoilerName VerifyUniqueChillerName VerifyUniqueCoilName ViewFac VisibleSprectrumAverage Volume VRMLOut VSCoilCyclingHumResidual VSCoilCyclingResidual VSCoilCyclingResidual VSCoilSpeedHumResidual VSCoilSpeedResidual VSCoilSpeedResidual VSEvapUnitLoadResidual VSHPCyclingResidual VSHPCyclingResidual VSHPSpeedResidual VSHPSpeedResidual VSMerkelResidual W5InitGlassParameters W5LsqFit W5LsqFit2 W6CoordsFromWorldVect warnIfNativeVarname WetCoilOutletCondition WhichCompSet WhichParentCompSet WhichParentSet Width WindowGapAirflowControl WindowGasConductance WindowGasPropertiesAtTemp WindowHeatBalanceEquations WindowScheduledSolarAbs WindowShadingManager WindowTempsForNominalCond WindSpeedAt Windward WorldVectFromW6 WriteAdaptiveComfortTable WriteAirLoopStatistics WriteBEPSTable WriteCompCostTable WriteComponentSizing WriteCumulativeReportMeterData WriteDaylightMapTitle WriteDemandEndUseSummary WriteInputArguments WriteIntegerData WriteIntegerVariableOutput WriteMeterDictionaryItem WriteModifiedArguments WriteMonthlyTables WriteOutputArguments WriteOutputEN673 WritePoint WritePredefinedTables WriteRealData WriteRealVariableOutput WriteReportHeaders WriteReportIntegerData WriteReportMeterData WriteReportRealData WriteReportVariableDictionaryItem WriteRootFinderStatus WriteRootFinderTrace WriteRootFinderTraceHeader WriteSourceEnergyEndUseSummary writeSubtitle WriteSurfaceShadowing WriteTable WriteTableOfContents WriteTabularLifeCycleCostReport WriteTabularReports WriteTabularTariffReports WriteTARCOGInputFile writeTextLine WriteTimeBinTables WriteTimeStampFormatData WriteTrace WriteVeriSumTable WriteZoneLoadComponentTable WVDC XNormalArea XYRectangle XZRectangle YNormalArea YZRectangle ZeroHVACValues ZNormalArea
Call graph
getzoneairsetpoints calls comfortcontrolledzone, znairrpt, calphafieldnames, roundsigdigits, stagezonelogic, checkschedulevalueminmax, checkschedulevalue, calphaargs, setupoutputvariable, showcontinueerror, zonelist, trimsigdigits, findnumberinlist, showwarningerror, rnumericargs, showsevereerror, cnumericfieldnames, verifyname, getobjectitem, lnumericfieldblanks, showfatalerror, finditem, checkcreatedzoneitemname, finditeminlist, getscheduleindex, tempcontrolledzone, getnumobjectsfound, stagedtstatobjects, getscheduleminvalue, tstatobjects, comforttstatobjects, samestring, stagecontrolledzone, getschedulemaxvalue, people, humiditycontrolzone, zone
verifyname calls finditem, showsevereerror
getobjectitem calls finditeminlist, samestring, showfatalerror, showwarningerror, getobjectitemfromfile, makeuppercase, processinput, iptrimsigdigits, finditeminsortedlist
finditem calls finditeminlist, makeuppercase
getnumobjectsfound calls finditeminlist, showwarningerror, makeuppercase, finditeminsortedlist
samestring calls makeuppercase
showsevereerror calls showerrormessage, matchcounts, messagesearch, createsqliteerrorrecord
showerrormessage calls displaystring, showfatalerror
showfatalerror calls roundsigdigits, showerrormessage, createsqliteerrorrecord, displaystring, abortenergyplus
abortenergyplus calls roundsigdigits, displaystring, testairpathintegrity, updatesqlitesimulationrecord, checkmarkednodes, reportairloopconnections, showrecurringerrors, testcompsetinletoutletnodes, summarizeerrors, reportsurfaceerrors, reportloopconnections, closemiscopenfiles, setupnodevarsforreporting, closesocket, closeoutopenfiles, reportsurfaces, testbranchintegrity, checkplantonabort, epelapsedtime, epstoptime, epsummarytimes, showmessage, checknodeconnections
testairpathintegrity calls showsevereerror, airtozonenodeinfo, nodeid, showcontinueerror
showrecurringerrors calls roundsigdigits, createsqliteerrorrecord, showmessage, updatesqliteerrorrecord, removetrailingzeros, recurringerrors
summarizeerrors calls matchcounts, showmessage, summaries, moredetails
closemiscopenfiles calls closedfsfile, closereportillummaps
reportsurfaces calls detailsforsurfaces, setupschemecolors, vrmlout, scanforreports, dxfoutwireframe, costinfoout, linesout, showwarningerror, dxfout
epstoptime calls showfatalerror, tstop
epsummarytimes calls roundsigdigits
showmessage calls showerrormessage
showcontinueerror calls showerrormessage, updatesqliteerrorrecord
detailsforsurfaces calls roundsigdigits, trimsigdigits, getscheduleminvalue, getschedulemaxvalue, zone, getschedulename, oscm, nominalu, framedivider, 2, computenominaluwithconvcoeffs, 3, osc, construct, 4, csurfaceclass, userintconvectioncoeffs, userextconvectioncoeffs, surface, surfacewindow
setupschemecolors calls showwarningerror, getobjectitemnum, getobjectdefmaxargs, matchandsetcolortextstring, getobjectitem
vrmlout calls zone, showfatalerror, showcontinueerror, showwarningerror, surface, triangulate, getnewunitnumber
dxfoutwireframe calls trimsigdigits, zone, showfatalerror, surface, surfacewindow, getnewunitnumber, zonedaylight, dxfcolorno
costinfoout calls showfatalerror, construct, csurfaceclass, surface, getnewunitnumber
linesout calls roundsigdigits, showfatalerror, showcontinueerror, showwarningerror, csurfaceclass, surface, getnewunitnumber
showwarningerror calls showerrormessage, matchcounts, messagesearch, createsqliteerrorrecord
dxfout calls trimsigdigits, zone, showfatalerror, showcontinueerror, showwarningerror, surface, surfacewindow, triangulate, getnewunitnumber, zonedaylight, dxfcolorno, illummapcalc
computenominaluwithconvcoeffs calls surface
matchandsetcolortextstring calls finditem
triangulate calls roundsigdigits, showmessage, showcontinueerror, showwarningerror, csurfaceclass, generate_ears, calcrfflrcoordinatetransformation, calcwallcoordinatetransformation
generate_ears calls polygon_contains_point_2d, angle_2dvector
processinput calls calphafieldnames, calphaargs, rnumericargs, cnumericfieldnames, lnumericfieldblanks, finditeminlist, samestring, showsevereerror, displaystring, showfatalerror, showcontinueerror, showwarningerror, makeuppercase, iptrimsigdigits, finditeminsortedlist, setupandsort, processdatadicfile, lalphafieldblanks, matchversion, getidfrecordsstats, processinputdatafile, initsecretobjects, programpath
finditeminsortedlist calls samestring, makeuppercase
processdatadicfile calls showsevereerror, iptrimsigdigits, readinputline, addsectiondef, addobjectdefandparse
processinputdatafile calls showsevereerror, showmessage, iptrimsigdigits, readinputline, validatesection, validateobjectandparse
readinputline calls showsevereerror, showfatalerror, showcontinueerror, makeuppercase, iptrimsigdigits, processnumber, processminmaxdefline
addsectiondef calls finditeminlist, showsevereerror, showcontinueerror, showwarningerror, makeuppercase
addobjectdefandparse calls finditeminlist, showsevereerror, showcontinueerror, showwarningerror, makeuppercase, iptrimsigdigits, readinputline
processminmaxdefline calls showsevereerror, makeuppercase, iptrimsigdigits, processnumber
validatesection calls finditeminlist, samestring, showcontinueerror, showwarningerror, makeuppercase, finditeminsortedlist, addrecordfromsection
validateobjectandparse calls finditeminlist, showsevereerror, showcontinueerror, showwarningerror, makeuppercase, iptrimsigdigits, finditeminsortedlist, readinputline, processnumber, showauditerrormessage, internalrangecheck, dumpcurrentlinebuffer, maketransition, extendobjectdefinition
addrecordfromsection calls showsevereerror, showcontinueerror, iptrimsigdigits, showauditerrormessage, internalrangecheck
internalrangecheck calls showsevereerror, iptrimsigdigits
dumpcurrentlinebuffer calls showmessage, iptrimsigdigits
maketransition calls finditeminlist, samestring, showsevereerror, showfatalerror, makeuppercase
extendobjectdefinition calls displaystring, iptrimsigdigits
verifythermostatinzone calls getzoneairsetpoints
managezoneairupdates calls getzoneairsetpoints