SetUpZoneSizingArrays – EnergyPlusFortran
SetUpZoneSizingArrays Subroutine
574 statements
Source File
private subroutine SetUpZoneSizingArrays()
Uses:
DataGlobals
DataInterfaces
InputProcessor
DataHeatBalance
DataHeatBalance
ZoneTempPredictorCorrector
EMSManager
ScheduleManager
DataZoneEquipment
Arguments
None
Calls
Called By
Source Code
SetUpZoneSizingArrays
Source Code
SUBROUTINE SetUpZoneSizingArrays
          ! SUBROUTINE INFORMATION:
          !       AUTHOR         Fred Buhl
          !       DATE WRITTEN   December 2000
          !       MODIFIED       na
          !       RE-ENGINEERED  na
          ! PURPOSE OF THIS SUBROUTINE:
          ! Allocate and fill the ZoneSizing data array.
          ! METHODOLOGY EMPLOYED:
          ! Obtains data from Zone Sizing and Zone Equipment objects already input.
          ! REFERENCES:
          ! na
          ! USE STATEMENTS:
  USE DataGlobals ,   ONLY : OutputFileInits, AnyEnergyManagementSystemInModel,isPulseZoneSizing
  USE DataInterfaces, ONLY : SetupEMSActuator, SetupEMSInternalVariable
  USE InputProcessor, ONLY : FindItemInList
  USE DataHeatBalance, ONLY : People, TotPeople
  USE DataHeatBalance, ONLY: Zone
  USE ZoneTempPredictorCorrector, ONLY: VerifyThermostatInZone
  USE EMSManager, ONLY:  ManageEMS
  USE ScheduleManager, ONLY: GetScheduleMaxValue
  USE DataZoneEquipment, ONLY: CalcDesignSpecificationOutdoorAir
  IMPLICIT NONE    ! Enforce explicit typing of all variables in this routine
          ! SUBROUTINE ARGUMENT DEFINITIONS:
          ! na
          ! SUBROUTINE PARAMETER DEFINITIONS:
          ! na
          ! INTERFACE BLOCK SPECIFICATIONS
          ! na
          ! DERIVED TYPE DEFINITIONS
          ! na
          ! SUBROUTINE LOCAL VARIABLE DECLARATIONS:
  INTEGER :: DesDayNum   ! design day index
!unused  INTEGER :: DesDayEnvrnNum   ! design day index
  INTEGER :: CtrlZoneNum ! controlled zone index
  INTEGER :: ZoneSizNum  ! zone sizing input index
  INTEGER :: NumOfTimeStepInDay ! number of zone time steps in a day
  INTEGER :: TimeStepIndex      ! zone time step index
  REAL(r64)    :: TotPeopleInZone    ! total (maximum) number of people in a zone
  INTEGER :: PeopleNum          ! index of People structure
  REAL(r64)    :: OAFromPeople = 0.0d0 ! min OA calculated from zone occupancy [m3/s]
  REAL(r64)    :: OAFromArea = 0.0d0   ! min OA calculated from zone area and OA flow per area [m3/s]
  INTEGER :: ZoneIndex          ! index of Zone Sizing zone name in zone array
  INTEGER :: ZoneSizIndex       ! zone sizing do loop index
  LOGICAL :: ErrorsFound=.false.! Set to true if errors in input, fatal at end of routine
  REAL (r64) :: SchMax   = 0.0d0  ! maximum people multiplier value
  REAL(r64) :: OAVolumeFlowRate ! outside air flow rate (m3/s)
  LOGICAL :: UseOccSchFlag      ! flag to use occupancy schedule when calculating OA
  LOGICAL :: UseMinOASchFlag    ! flag to use min OA schedule when calculating OA
  INTEGER :: DSOAPtr            ! index to DesignSpecification:OutdoorAir object
  DO ZoneSizIndex=1,NumZoneSizingInput
    ZoneIndex = FindItemInList(ZoneSizingInput(ZoneSizIndex)%ZoneName,Zone%Name,NumOfZones)
    IF (ZoneIndex == 0) THEN
      CALL ShowSevereError('SetUpZoneSizingArrays: Sizing:Zone="'//TRIM(ZoneSizingInput(ZoneSizIndex)%ZoneName)// &
                           '" references unknown zone')
      ErrorsFound = .TRUE.
    END IF
    IF (ANY(ZoneEquipConfig%IsControlled)) THEN
      ZoneIndex = FindItemInList(ZoneSizingInput(ZoneSizIndex)%ZoneName,ZoneEquipConfig%ZoneName,NumOfZones)
      IF (ZoneIndex == 0) THEN
        IF (.NOT. isPulseZoneSizing) THEN
          CALL ShowWarningError('SetUpZoneSizingArrays: Requested Sizing for Zone="'//  &
                              TRIM(ZoneSizingInput(ZoneSizIndex)%ZoneName)//  &
                              '", Zone is not found in the Controlled Zones List')
        ENDIF
      ELSE
        ZoneSizingInput(ZoneSizIndex)%ZoneNum = ZoneIndex
      ENDIF
      IF (ZoneSizingInput(ZoneSizIndex)%CoolAirDesMethod == FromDDCalc .or.   &
          ZoneSizingInput(ZoneSizIndex)%HeatAirDesMethod == FromDDCalc) THEN
        IF (.not. VerifyThermostatInZone(ZoneSizingInput(ZoneSizIndex)%ZoneName)) THEN
          IF (.NOT. isPulseZoneSizing) THEN
            CALL ShowWarningError('SetUpZoneSizingArrays: Requested Sizing for Zone="'//  &
                             TRIM(ZoneSizingInput(ZoneSizIndex)%ZoneName)//  &
                             '", Zone has no thermostat (ref: ZoneControl:Thermostat, et al)')
          ENDIF
        ENDIF
      ENDIF
    ELSE
      CALL ShowSevereError('SetUpZoneSizingArrays: Zone Sizing is requested '//  &
         'but there are no ZoneHVAC:EquipmentConnections statements.')
      ErrorsFound = .TRUE.
    ENDIF
  END DO
  IF (ErrorsFound) THEN
    CALL ShowFatalError('SetUpZoneSizingArrays: Errors found in Sizing:Zone input')
  END IF
  ALLOCATE(ZoneSizing(NumOfZones,TotDesDays+TotRunDesPersDays))
  ALLOCATE(FinalZoneSizing(NumOfZones))
  ALLOCATE(CalcZoneSizing(NumOfZones,TotDesDays+TotRunDesPersDays))
  ALLOCATE(CalcFinalZoneSizing(NumOfZones))
  ALLOCATE(TermUnitFinalZoneSizing(NumOfZones))
  ALLOCATE(DesDayWeath(TotDesDays+TotRunDesPersDays))
  NumOfTimeStepInDay = NumOfTimeStepInHour * 24
  ALLOCATE(AvgData(NumOfTimeStepInDay))
  ALLOCATE(CoolPeakDateHrMin(NumOfZones))
  ALLOCATE(HeatPeakDateHrMin(NumOfZones))
  ALLOCATE(ZoneSizThermSetPtHi(NumOfZones))
  ALLOCATE(ZoneSizThermSetPtLo(NumOfZones))
  CoolPeakDateHrMin = ' '
  HeatPeakDateHrMin = ' '
  ZoneSizThermSetPtHi = 0.0d0
  ZoneSizThermSetPtLo = 1000.d0
  DO DesDayNum=1,TotDesDays+TotRunDesPersDays
    ALLOCATE( DesDayWeath(DesDayNum)%Temp(NumOfTimeStepInHour*24) )
    ALLOCATE( DesDayWeath(DesDayNum)%HumRat(NumOfTimeStepInHour*24) )
    ALLOCATE( DesDayWeath(DesDayNum)%Press(NumOfTimeStepInHour*24) )
    DesDayWeath(DesDayNum)%Temp = 0.0d0
    DesDayWeath(DesDayNum)%HumRat = 0.0d0
    DesDayWeath(DesDayNum)%Press = 0.0d0
  END DO
  ! Fill zone sizing arrays from input array
  DO DesDayNum=1,TotDesDays+TotRunDesPersDays
    DO CtrlZoneNum = 1,NumOfZones
      IF (.not. ZoneEquipConfig(CtrlZoneNum)%IsControlled) CYCLE
      ZoneSizing(CtrlZoneNum,DesDayNum)%ZoneName = ZoneEquipConfig(CtrlZoneNum)%ZoneName
      ZoneSizing(CtrlZoneNum,DesDayNum)%ActualZoneNum = ZoneEquipConfig(CtrlZoneNum)%ActualZoneNum
      IF (ZoneEquipConfig(CtrlZoneNum)%NumInletNodes > 0) THEN
        ZoneSizing(CtrlZoneNum,DesDayNum)%SupplyAirNode = ZoneEquipConfig(CtrlZoneNum)%InletNode(1)
      END IF
      CalcZoneSizing(CtrlZoneNum,DesDayNum)%ZoneName = ZoneEquipConfig(CtrlZoneNum)%ZoneName
      CalcZoneSizing(CtrlZoneNum,DesDayNum)%ActualZoneNum = ZoneEquipConfig(CtrlZoneNum)%ActualZoneNum
      IF (ZoneEquipConfig(CtrlZoneNum)%NumInletNodes > 0) THEN
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%SupplyAirNode = ZoneEquipConfig(CtrlZoneNum)%InletNode(1)
      END IF
      ! For each Zone Sizing object, find the corresponding controlled zone
      ZoneSizNum = FindItemInList(ZoneEquipConfig(CtrlZoneNum)%ZoneName,ZoneSizingInput%ZoneName, &
                                  NumZoneSizingInput)
      IF (ZoneSizNum > 0) THEN  ! move data from zone sizing input
        ZoneSizing(CtrlZoneNum,DesDayNum)%ZnCoolDgnSAMethod = ZoneSizingInput(ZoneSizNum)%ZnCoolDgnSAMethod
        ZoneSizing(CtrlZoneNum,DesDayNum)%ZnHeatDgnSAMethod = ZoneSizingInput(ZoneSizNum)%ZnHeatDgnSAMethod
        ZoneSizing(CtrlZoneNum,DesDayNum)%CoolDesTemp = ZoneSizingInput(ZoneSizNum)%CoolDesTemp
        ZoneSizing(CtrlZoneNum,DesDayNum)%HeatDesTemp = ZoneSizingInput(ZoneSizNum)%HeatDesTemp
        ZoneSizing(CtrlZoneNum,DesDayNum)%CoolDesTempDiff = ZoneSizingInput(ZoneSizNum)%CoolDesTempDiff
        ZoneSizing(CtrlZoneNum,DesDayNum)%HeatDesTempDiff = ZoneSizingInput(ZoneSizNum)%HeatDesTempDiff
        ZoneSizing(CtrlZoneNum,DesDayNum)%CoolDesHumRat = ZoneSizingInput(ZoneSizNum)%CoolDesHumRat
        ZoneSizing(CtrlZoneNum,DesDayNum)%HeatDesHumRat = ZoneSizingInput(ZoneSizNum)%HeatDesHumRat
        ZoneSizing(CtrlZoneNum,DesDayNum)%OADesMethod = ZoneSizingInput(ZoneSizNum)%OADesMethod
        ZoneSizing(CtrlZoneNum,DesDayNum)%DesOAFlowPPer = ZoneSizingInput(ZoneSizNum)%DesOAFlowPPer
        ZoneSizing(CtrlZoneNum,DesDayNum)%DesOAFlowPerArea = ZoneSizingInput(ZoneSizNum)%DesOAFlowPerArea
        ZoneSizing(CtrlZoneNum,DesDayNum)%DesOAFlow = ZoneSizingInput(ZoneSizNum)%DesOAFlow
        ZoneSizing(CtrlZoneNum,DesDayNum)%CoolAirDesMethod = ZoneSizingInput(ZoneSizNum)%CoolAirDesMethod
        ZoneSizing(CtrlZoneNum,DesDayNum)%HeatAirDesMethod = ZoneSizingInput(ZoneSizNum)%HeatAirDesMethod
        ZoneSizing(CtrlZoneNum,DesDayNum)%InpDesCoolAirFlow = ZoneSizingInput(ZoneSizNum)%DesCoolAirFlow
        ZoneSizing(CtrlZoneNum,DesDayNum)%DesCoolMinAirFlowPerArea = ZoneSizingInput(ZoneSizNum)%DesCoolMinAirFlowPerArea
        ZoneSizing(CtrlZoneNum,DesDayNum)%DesCoolMinAirFlow = ZoneSizingInput(ZoneSizNum)%DesCoolMinAirFlow
        ZoneSizing(CtrlZoneNum,DesDayNum)%DesCoolMinAirFlowFrac = ZoneSizingInput(ZoneSizNum)%DesCoolMinAirFlowFrac
        ZoneSizing(CtrlZoneNum,DesDayNum)%InpDesHeatAirFlow = ZoneSizingInput(ZoneSizNum)%DesHeatAirFlow
        ZoneSizing(CtrlZoneNum,DesDayNum)%DesHeatMaxAirFlowPerArea = ZoneSizingInput(ZoneSizNum)%DesHeatMaxAirFlowPerArea
        ZoneSizing(CtrlZoneNum,DesDayNum)%DesHeatMaxAirFlow = ZoneSizingInput(ZoneSizNum)%DesHeatMaxAirFlow
        ZoneSizing(CtrlZoneNum,DesDayNum)%DesHeatMaxAirFlowFrac = ZoneSizingInput(ZoneSizNum)%DesHeatMaxAirFlowFrac
        ZoneSizing(CtrlZoneNum,DesDayNum)%HeatSizingFactor = ZoneSizingInput(ZoneSizNum)%HeatSizingFactor
        ZoneSizing(CtrlZoneNum,DesDayNum)%CoolSizingFactor = ZoneSizingInput(ZoneSizNum)%CoolSizingFactor
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%ZnCoolDgnSAMethod = ZoneSizingInput(ZoneSizNum)%ZnCoolDgnSAMethod
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%ZnHeatDgnSAMethod = ZoneSizingInput(ZoneSizNum)%ZnHeatDgnSAMethod
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolDesTemp = ZoneSizingInput(ZoneSizNum)%CoolDesTemp
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatDesTemp = ZoneSizingInput(ZoneSizNum)%HeatDesTemp
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolDesTempDiff = ZoneSizingInput(ZoneSizNum)%CoolDesTempDiff
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatDesTempDiff = ZoneSizingInput(ZoneSizNum)%HeatDesTempDiff
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolDesHumRat = ZoneSizingInput(ZoneSizNum)%CoolDesHumRat
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatDesHumRat = ZoneSizingInput(ZoneSizNum)%HeatDesHumRat
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%OADesMethod = ZoneSizingInput(ZoneSizNum)%OADesMethod
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesOAFlowPPer = ZoneSizingInput(ZoneSizNum)%DesOAFlowPPer
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesOAFlowPerArea = ZoneSizingInput(ZoneSizNum)%DesOAFlowPerArea
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesOAFlow = ZoneSizingInput(ZoneSizNum)%DesOAFlow
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolAirDesMethod = ZoneSizingInput(ZoneSizNum)%CoolAirDesMethod
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatAirDesMethod = ZoneSizingInput(ZoneSizNum)%HeatAirDesMethod
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%InpDesCoolAirFlow = ZoneSizingInput(ZoneSizNum)%DesCoolAirFlow
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesCoolMinAirFlowPerArea = ZoneSizingInput(ZoneSizNum)%DesCoolMinAirFlowPerArea
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesCoolMinAirFlow = ZoneSizingInput(ZoneSizNum)%DesCoolMinAirFlow
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesCoolMinAirFlowFrac = ZoneSizingInput(ZoneSizNum)%DesCoolMinAirFlowFrac
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%InpDesHeatAirFlow = ZoneSizingInput(ZoneSizNum)%DesHeatAirFlow
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesHeatMaxAirFlowPerArea = ZoneSizingInput(ZoneSizNum)%DesHeatMaxAirFlowPerArea
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesHeatMaxAirFlow = ZoneSizingInput(ZoneSizNum)%DesHeatMaxAirFlow
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesHeatMaxAirFlowFrac = ZoneSizingInput(ZoneSizNum)%DesHeatMaxAirFlowFrac
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatSizingFactor = ZoneSizingInput(ZoneSizNum)%HeatSizingFactor
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolSizingFactor = ZoneSizingInput(ZoneSizNum)%CoolSizingFactor
      ELSE ! Every controlled zone must be simulated, so set missing inputs to the first
        !LKL I think this is sufficient for warning -- no need for array
        IF (DesDayNum == 1) THEN
          IF (.NOT. isPulseZoneSizing) THEN
            CALL ShowWarningError('SetUpZoneSizingArrays: Sizing for Zone="'//  &
              trim(ZoneEquipConfig(CtrlZoneNum)%ZoneName)//'" will use Sizing:Zone specifications listed for Zone="'//  &
              trim(ZoneSizingInput(1)%ZoneName)//'".')
          ENDIF
          ! Following needs to be implemented first:
!          CALL ShowContinueError('  A better option would be to set up global ZoneList objects for Sizing:Zone objects.')
        ENDIF
        ZoneSizing(CtrlZoneNum,DesDayNum)%ZnCoolDgnSAMethod = ZoneSizingInput(1)%ZnCoolDgnSAMethod
        ZoneSizing(CtrlZoneNum,DesDayNum)%ZnHeatDgnSAMethod = ZoneSizingInput(1)%ZnHeatDgnSAMethod
        ZoneSizing(CtrlZoneNum,DesDayNum)%CoolDesTemp = ZoneSizingInput(1)%CoolDesTemp
        ZoneSizing(CtrlZoneNum,DesDayNum)%HeatDesTemp = ZoneSizingInput(1)%HeatDesTemp
        ZoneSizing(CtrlZoneNum,DesDayNum)%CoolDesTempDiff = ZoneSizingInput(1)%CoolDesTempDiff
        ZoneSizing(CtrlZoneNum,DesDayNum)%HeatDesTempDiff = ZoneSizingInput(1)%HeatDesTempDiff
        ZoneSizing(CtrlZoneNum,DesDayNum)%CoolDesHumRat = ZoneSizingInput(1)%CoolDesHumRat
        ZoneSizing(CtrlZoneNum,DesDayNum)%HeatDesHumRat = ZoneSizingInput(1)%HeatDesHumRat
        ZoneSizing(CtrlZoneNum,DesDayNum)%OADesMethod = ZoneSizingInput(1)%OADesMethod
        ZoneSizing(CtrlZoneNum,DesDayNum)%DesOAFlowPPer = ZoneSizingInput(1)%DesOAFlowPPer
        ZoneSizing(CtrlZoneNum,DesDayNum)%DesOAFlowPerArea = ZoneSizingInput(1)%DesOAFlowPerArea
        ZoneSizing(CtrlZoneNum,DesDayNum)%DesOAFlow = ZoneSizingInput(1)%DesOAFlow
        ZoneSizing(CtrlZoneNum,DesDayNum)%CoolAirDesMethod = ZoneSizingInput(1)%CoolAirDesMethod
        ZoneSizing(CtrlZoneNum,DesDayNum)%HeatAirDesMethod = ZoneSizingInput(1)%HeatAirDesMethod
        ZoneSizing(CtrlZoneNum,DesDayNum)%InpDesCoolAirFlow = ZoneSizingInput(1)%DesCoolAirFlow
        ZoneSizing(CtrlZoneNum,DesDayNum)%DesCoolMinAirFlowPerArea = ZoneSizingInput(1)%DesCoolMinAirFlowPerArea
        ZoneSizing(CtrlZoneNum,DesDayNum)%DesCoolMinAirFlow = ZoneSizingInput(1)%DesCoolMinAirFlow
        ZoneSizing(CtrlZoneNum,DesDayNum)%DesCoolMinAirFlowFrac = ZoneSizingInput(1)%DesCoolMinAirFlowFrac
        ZoneSizing(CtrlZoneNum,DesDayNum)%InpDesHeatAirFlow = ZoneSizingInput(1)%DesHeatAirFlow
        ZoneSizing(CtrlZoneNum,DesDayNum)%DesHeatMaxAirFlowPerArea = ZoneSizingInput(1)%DesHeatMaxAirFlowPerArea
        ZoneSizing(CtrlZoneNum,DesDayNum)%DesHeatMaxAirFlow = ZoneSizingInput(1)%DesHeatMaxAirFlow
        ZoneSizing(CtrlZoneNum,DesDayNum)%DesHeatMaxAirFlowFrac = ZoneSizingInput(1)%DesHeatMaxAirFlowFrac
        ZoneSizing(CtrlZoneNum,DesDayNum)%HeatSizingFactor = ZoneSizingInput(1)%HeatSizingFactor
        ZoneSizing(CtrlZoneNum,DesDayNum)%CoolSizingFactor = ZoneSizingInput(1)%CoolSizingFactor
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%ZnCoolDgnSAMethod = ZoneSizingInput(1)%ZnCoolDgnSAMethod
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%ZnHeatDgnSAMethod = ZoneSizingInput(1)%ZnHeatDgnSAMethod
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolDesTemp = ZoneSizingInput(1)%CoolDesTemp
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatDesTemp = ZoneSizingInput(1)%HeatDesTemp
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolDesTempDiff = ZoneSizingInput(1)%CoolDesTempDiff
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatDesTempDiff = ZoneSizingInput(1)%HeatDesTempDiff
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolDesHumRat = ZoneSizingInput(1)%CoolDesHumRat
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatDesHumRat = ZoneSizingInput(1)%HeatDesHumRat
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%OADesMethod = ZoneSizingInput(1)%OADesMethod
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesOAFlowPPer = ZoneSizingInput(1)%DesOAFlowPPer
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesOAFlowPerArea = ZoneSizingInput(1)%DesOAFlowPerArea
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesOAFlow = ZoneSizingInput(1)%DesOAFlow
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolAirDesMethod = ZoneSizingInput(1)%CoolAirDesMethod
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatAirDesMethod = ZoneSizingInput(1)%HeatAirDesMethod
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%InpDesCoolAirFlow = ZoneSizingInput(1)%DesCoolAirFlow
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesCoolMinAirFlowPerArea = ZoneSizingInput(1)%DesCoolMinAirFlowPerArea
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesCoolMinAirFlow = ZoneSizingInput(1)%DesCoolMinAirFlow
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesCoolMinAirFlowFrac = ZoneSizingInput(1)%DesCoolMinAirFlowFrac
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%InpDesHeatAirFlow = ZoneSizingInput(1)%DesHeatAirFlow
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesHeatMaxAirFlowPerArea = ZoneSizingInput(1)%DesHeatMaxAirFlowPerArea
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesHeatMaxAirFlow = ZoneSizingInput(1)%DesHeatMaxAirFlow
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesHeatMaxAirFlowFrac = ZoneSizingInput(1)%DesHeatMaxAirFlowFrac
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatSizingFactor = ZoneSizingInput(1)%HeatSizingFactor
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolSizingFactor = ZoneSizingInput(1)%CoolSizingFactor
      END IF
      ALLOCATE(ZoneSizing(CtrlZoneNum,DesDayNum)%HeatFlowSeq(NumOfTimeStepInDay))
      ALLOCATE(ZoneSizing(CtrlZoneNum,DesDayNum)%CoolFlowSeq(NumOfTimeStepInDay))
      ALLOCATE(ZoneSizing(CtrlZoneNum,DesDayNum)%HeatLoadSeq(NumOfTimeStepInDay))
      ALLOCATE(ZoneSizing(CtrlZoneNum,DesDayNum)%CoolLoadSeq(NumOfTimeStepInDay))
      ALLOCATE(ZoneSizing(CtrlZoneNum,DesDayNum)%HeatZoneTempSeq(NumOfTimeStepInDay))
      ALLOCATE(ZoneSizing(CtrlZoneNum,DesDayNum)%DesHeatSetPtSeq(NumOfTimeStepInDay))
      ALLOCATE(ZoneSizing(CtrlZoneNum,DesDayNum)%CoolZoneTempSeq(NumOfTimeStepInDay))
      ALLOCATE(ZoneSizing(CtrlZoneNum,DesDayNum)%DesCoolSetPtSeq(NumOfTimeStepInDay))
      ALLOCATE(ZoneSizing(CtrlZoneNum,DesDayNum)%HeatOutTempSeq(NumOfTimeStepInDay))
      ALLOCATE(ZoneSizing(CtrlZoneNum,DesDayNum)%CoolOutTempSeq(NumOfTimeStepInDay))
      ALLOCATE(ZoneSizing(CtrlZoneNum,DesDayNum)%HeatZoneRetTempSeq(NumOfTimeStepInDay))
      ALLOCATE(ZoneSizing(CtrlZoneNum,DesDayNum)%HeatTstatTempSeq(NumOfTimeStepInDay))
      ALLOCATE(ZoneSizing(CtrlZoneNum,DesDayNum)%CoolZoneRetTempSeq(NumOfTimeStepInDay))
      ALLOCATE(ZoneSizing(CtrlZoneNum,DesDayNum)%CoolTstatTempSeq(NumOfTimeStepInDay))
      ALLOCATE(ZoneSizing(CtrlZoneNum,DesDayNum)%HeatZoneHumRatSeq(NumOfTimeStepInDay))
      ALLOCATE(ZoneSizing(CtrlZoneNum,DesDayNum)%CoolZoneHumRatSeq(NumOfTimeStepInDay))
      ALLOCATE(ZoneSizing(CtrlZoneNum,DesDayNum)%HeatOutHumRatSeq(NumOfTimeStepInDay))
      ALLOCATE(ZoneSizing(CtrlZoneNum,DesDayNum)%CoolOutHumRatSeq(NumOfTimeStepInDay))
      ALLOCATE(CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatFlowSeq(NumOfTimeStepInDay))
      ALLOCATE(CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolFlowSeq(NumOfTimeStepInDay))
      ALLOCATE(CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatLoadSeq(NumOfTimeStepInDay))
      ALLOCATE(CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolLoadSeq(NumOfTimeStepInDay))
      ALLOCATE(CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatZoneTempSeq(NumOfTimeStepInDay))
      ALLOCATE(CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolZoneTempSeq(NumOfTimeStepInDay))
      ALLOCATE(CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatOutTempSeq(NumOfTimeStepInDay))
      ALLOCATE(CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolOutTempSeq(NumOfTimeStepInDay))
      ALLOCATE(CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatZoneRetTempSeq(NumOfTimeStepInDay))
      ALLOCATE(CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatTstatTempSeq(NumOfTimeStepInDay))
      ALLOCATE(CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolZoneRetTempSeq(NumOfTimeStepInDay))
      ALLOCATE(CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolTstatTempSeq(NumOfTimeStepInDay))
      ALLOCATE(CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatZoneHumRatSeq(NumOfTimeStepInDay))
      ALLOCATE(CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolZoneHumRatSeq(NumOfTimeStepInDay))
      ALLOCATE(CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatOutHumRatSeq(NumOfTimeStepInDay))
      ALLOCATE(CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolOutHumRatSeq(NumOfTimeStepInDay))
      DO TimeStepIndex=1,NumOfTimeStepInDay
        ZoneSizing(CtrlZoneNum,DesDayNum)%HeatFlowSeq(TimeStepIndex) = 0.0d0
        ZoneSizing(CtrlZoneNum,DesDayNum)%CoolFlowSeq(TimeStepIndex) = 0.0d0
        ZoneSizing(CtrlZoneNum,DesDayNum)%HeatLoadSeq(TimeStepIndex) = 0.0d0
        ZoneSizing(CtrlZoneNum,DesDayNum)%CoolLoadSeq(TimeStepIndex) = 0.0d0
        ZoneSizing(CtrlZoneNum,DesDayNum)%HeatZoneTempSeq(TimeStepIndex) = 0.0d0
        ZoneSizing(CtrlZoneNum,DesDayNum)%DesHeatSetPtSeq(TimeStepIndex) = 0.0d0
        ZoneSizing(CtrlZoneNum,DesDayNum)%CoolZoneTempSeq(TimeStepIndex) = 0.0d0
        ZoneSizing(CtrlZoneNum,DesDayNum)%DesCoolSetPtSeq(TimeStepIndex) = 0.0d0
        ZoneSizing(CtrlZoneNum,DesDayNum)%HeatOutTempSeq(TimeStepIndex) = 0.0d0
        ZoneSizing(CtrlZoneNum,DesDayNum)%CoolOutTempSeq(TimeStepIndex) = 0.0d0
        ZoneSizing(CtrlZoneNum,DesDayNum)%HeatZoneRetTempSeq(TimeStepIndex) = 0.0d0
        ZoneSizing(CtrlZoneNum,DesDayNum)%HeatTstatTempSeq(TimeStepIndex) = 0.0d0
        ZoneSizing(CtrlZoneNum,DesDayNum)%CoolZoneRetTempSeq(TimeStepIndex) = 0.0d0
        ZoneSizing(CtrlZoneNum,DesDayNum)%CoolTstatTempSeq(TimeStepIndex) = 0.0d0
        ZoneSizing(CtrlZoneNum,DesDayNum)%HeatZoneHumRatSeq(TimeStepIndex) = 0.0d0
        ZoneSizing(CtrlZoneNum,DesDayNum)%CoolZoneHumRatSeq(TimeStepIndex) = 0.0d0
        ZoneSizing(CtrlZoneNum,DesDayNum)%HeatOutHumRatSeq(TimeStepIndex) = 0.0d0
        ZoneSizing(CtrlZoneNum,DesDayNum)%CoolOutHumRatSeq(TimeStepIndex) = 0.0d0
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatFlowSeq(TimeStepIndex) = 0.0d0
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolFlowSeq(TimeStepIndex) = 0.0d0
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatLoadSeq(TimeStepIndex) = 0.0d0
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolLoadSeq(TimeStepIndex) = 0.0d0
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatZoneTempSeq(TimeStepIndex) = 0.0d0
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolZoneTempSeq(TimeStepIndex) = 0.0d0
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatOutTempSeq(TimeStepIndex) = 0.0d0
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolOutTempSeq(TimeStepIndex) = 0.0d0
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatZoneRetTempSeq(TimeStepIndex) = 0.0d0
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatTstatTempSeq(TimeStepIndex) = 0.0d0
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolZoneRetTempSeq(TimeStepIndex) = 0.0d0
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolTstatTempSeq(TimeStepIndex) = 0.0d0
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatZoneHumRatSeq(TimeStepIndex) = 0.0d0
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolZoneHumRatSeq(TimeStepIndex) = 0.0d0
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatOutHumRatSeq(TimeStepIndex) = 0.0d0
        CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolOutHumRatSeq(TimeStepIndex) = 0.0d0
     END DO
    END DO
  END DO
  DO CtrlZoneNum = 1,NumOfZones
    IF (.not. ZoneEquipConfig(CtrlZoneNum)%IsControlled) CYCLE
    FinalZoneSizing(CtrlZoneNum)%ZoneName = ZoneEquipConfig(CtrlZoneNum)%ZoneName
    FinalZoneSizing(CtrlZoneNum)%ActualZoneNum = ZoneEquipConfig(CtrlZoneNum)%ActualZoneNum
    IF (ZoneEquipConfig(CtrlZoneNum)%NumInletNodes > 0) THEN
      FinalZoneSizing(CtrlZoneNum)%SupplyAirNode = ZoneEquipConfig(CtrlZoneNum)%InletNode(1)
    END IF
    CalcFinalZoneSizing(CtrlZoneNum)%ZoneName = ZoneEquipConfig(CtrlZoneNum)%ZoneName
    CalcFinalZoneSizing(CtrlZoneNum)%ActualZoneNum = ZoneEquipConfig(CtrlZoneNum)%ActualZoneNum
    IF (ZoneEquipConfig(CtrlZoneNum)%NumInletNodes > 0) THEN
      CalcFinalZoneSizing(CtrlZoneNum)%SupplyAirNode = ZoneEquipConfig(CtrlZoneNum)%InletNode(1)
    END IF
    ZoneSizNum = FindItemInList(ZoneEquipConfig(CtrlZoneNum)%ZoneName,ZoneSizingInput%ZoneName,NumZoneSizingInput)
    IF (ZoneSizNum > 0) THEN  ! move data from zone sizing input
      FinalZoneSizing(CtrlZoneNum)%ZnCoolDgnSAMethod = ZoneSizingInput(ZoneSizNum)%ZnCoolDgnSAMethod
      FinalZoneSizing(CtrlZoneNum)%ZnHeatDgnSAMethod = ZoneSizingInput(ZoneSizNum)%ZnHeatDgnSAMethod
      FinalZoneSizing(CtrlZoneNum)%CoolDesTemp = ZoneSizingInput(ZoneSizNum)%CoolDesTemp
      FinalZoneSizing(CtrlZoneNum)%HeatDesTemp = ZoneSizingInput(ZoneSizNum)%HeatDesTemp
      FinalZoneSizing(CtrlZoneNum)%CoolDesTempDiff = ZoneSizingInput(ZoneSizNum)%CoolDesTempDiff
      FinalZoneSizing(CtrlZoneNum)%HeatDesTempDiff = ZoneSizingInput(ZoneSizNum)%HeatDesTempDiff
      FinalZoneSizing(CtrlZoneNum)%CoolDesHumRat = ZoneSizingInput(ZoneSizNum)%CoolDesHumRat
      FinalZoneSizing(CtrlZoneNum)%HeatDesHumRat = ZoneSizingInput(ZoneSizNum)%HeatDesHumRat
      FinalZoneSizing(CtrlZoneNum)%ZoneDesignSpecOAIndex = ZoneSizingInput(ZoneSizNum)%ZoneDesignSpecOAIndex
      FinalZoneSizing(CtrlZoneNum)%OADesMethod = ZoneSizingInput(ZoneSizNum)%OADesMethod
      FinalZoneSizing(CtrlZoneNum)%DesOAFlowPPer = ZoneSizingInput(ZoneSizNum)%DesOAFlowPPer
      FinalZoneSizing(CtrlZoneNum)%DesOAFlowPerArea = ZoneSizingInput(ZoneSizNum)%DesOAFlowPerArea
      FinalZoneSizing(CtrlZoneNum)%DesOAFlow = ZoneSizingInput(ZoneSizNum)%DesOAFlow
      FinalZoneSizing(CtrlZoneNum)%CoolAirDesMethod = ZoneSizingInput(ZoneSizNum)%CoolAirDesMethod
      FinalZoneSizing(CtrlZoneNum)%HeatAirDesMethod = ZoneSizingInput(ZoneSizNum)%HeatAirDesMethod
      FinalZoneSizing(CtrlZoneNum)%InpDesCoolAirFlow = ZoneSizingInput(ZoneSizNum)%DesCoolAirFlow
      FinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlowPerArea = ZoneSizingInput(ZoneSizNum)%DesCoolMinAirFlowPerArea
      FinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlow = ZoneSizingInput(ZoneSizNum)%DesCoolMinAirFlow
      FinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlowFrac = ZoneSizingInput(ZoneSizNum)%DesCoolMinAirFlowFrac
      FinalZoneSizing(CtrlZoneNum)%InpDesHeatAirFlow = ZoneSizingInput(ZoneSizNum)%DesHeatAirFlow
      FinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlowPerArea = ZoneSizingInput(ZoneSizNum)%DesHeatMaxAirFlowPerArea
      FinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlow = ZoneSizingInput(ZoneSizNum)%DesHeatMaxAirFlow
      FinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlowFrac = ZoneSizingInput(ZoneSizNum)%DesHeatMaxAirFlowFrac
      FinalZoneSizing(CtrlZoneNum)%HeatSizingFactor = ZoneSizingInput(ZoneSizNum)%HeatSizingFactor
      FinalZoneSizing(CtrlZoneNum)%CoolSizingFactor = ZoneSizingInput(ZoneSizNum)%CoolSizingFactor
      FinalZoneSizing(CtrlZoneNum)%ZoneADEffCooling = ZoneSizingInput(ZoneSizNum)%ZoneADEffCooling
      FinalZoneSizing(CtrlZoneNum)%ZoneADEffHeating = ZoneSizingInput(ZoneSizNum)%ZoneADEffHeating
      FinalZoneSizing(CtrlZoneNum)%ZoneSecondaryRecirculation = ZoneSizingInput(ZoneSizNum)%ZoneSecondaryRecirculation
      CalcFinalZoneSizing(CtrlZoneNum)%ZnCoolDgnSAMethod = ZoneSizingInput(ZoneSizNum)%ZnCoolDgnSAMethod
      CalcFinalZoneSizing(CtrlZoneNum)%ZnHeatDgnSAMethod = ZoneSizingInput(ZoneSizNum)%ZnHeatDgnSAMethod
      CalcFinalZoneSizing(CtrlZoneNum)%CoolDesTemp = ZoneSizingInput(ZoneSizNum)%CoolDesTemp
      CalcFinalZoneSizing(CtrlZoneNum)%HeatDesTemp = ZoneSizingInput(ZoneSizNum)%HeatDesTemp
      CalcFinalZoneSizing(CtrlZoneNum)%CoolDesTempDiff = ZoneSizingInput(ZoneSizNum)%CoolDesTempDiff
      CalcFinalZoneSizing(CtrlZoneNum)%HeatDesTempDiff = ZoneSizingInput(ZoneSizNum)%HeatDesTempDiff
      CalcFinalZoneSizing(CtrlZoneNum)%CoolDesHumRat = ZoneSizingInput(ZoneSizNum)%CoolDesHumRat
      CalcFinalZoneSizing(CtrlZoneNum)%HeatDesHumRat = ZoneSizingInput(ZoneSizNum)%HeatDesHumRat
      CalcFinalZoneSizing(CtrlZoneNum)%ZoneDesignSpecOAIndex = ZoneSizingInput(ZoneSizNum)%ZoneDesignSpecOAIndex
      CalcFinalZoneSizing(CtrlZoneNum)%OADesMethod = ZoneSizingInput(ZoneSizNum)%OADesMethod
      CalcFinalZoneSizing(CtrlZoneNum)%DesOAFlowPPer = ZoneSizingInput(ZoneSizNum)%DesOAFlowPPer
      CalcFinalZoneSizing(CtrlZoneNum)%DesOAFlowPerArea = ZoneSizingInput(ZoneSizNum)%DesOAFlowPerArea
      CalcFinalZoneSizing(CtrlZoneNum)%DesOAFlow = ZoneSizingInput(ZoneSizNum)%DesOAFlow
      CalcFinalZoneSizing(CtrlZoneNum)%CoolAirDesMethod = ZoneSizingInput(ZoneSizNum)%CoolAirDesMethod
      CalcFinalZoneSizing(CtrlZoneNum)%HeatAirDesMethod = ZoneSizingInput(ZoneSizNum)%HeatAirDesMethod
      CalcFinalZoneSizing(CtrlZoneNum)%InpDesCoolAirFlow = ZoneSizingInput(ZoneSizNum)%DesCoolAirFlow
      CalcFinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlowPerArea = ZoneSizingInput(ZoneSizNum)%DesCoolMinAirFlowPerArea
      CalcFinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlow = ZoneSizingInput(ZoneSizNum)%DesCoolMinAirFlow
      CalcFinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlowFrac = ZoneSizingInput(ZoneSizNum)%DesCoolMinAirFlowFrac
      CalcFinalZoneSizing(CtrlZoneNum)%InpDesHeatAirFlow = ZoneSizingInput(ZoneSizNum)%DesHeatAirFlow
      CalcFinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlowPerArea = ZoneSizingInput(ZoneSizNum)%DesHeatMaxAirFlowPerArea
      CalcFinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlow = ZoneSizingInput(ZoneSizNum)%DesHeatMaxAirFlow
      CalcFinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlowFrac = ZoneSizingInput(ZoneSizNum)%DesHeatMaxAirFlowFrac
      CalcFinalZoneSizing(CtrlZoneNum)%HeatSizingFactor = ZoneSizingInput(ZoneSizNum)%HeatSizingFactor
      CalcFinalZoneSizing(CtrlZoneNum)%CoolSizingFactor = ZoneSizingInput(ZoneSizNum)%CoolSizingFactor
      CalcFinalZoneSizing(CtrlZoneNum)%ZoneADEffCooling = ZoneSizingInput(ZoneSizNum)%ZoneADEffCooling
      CalcFinalZoneSizing(CtrlZoneNum)%ZoneADEffHeating = ZoneSizingInput(ZoneSizNum)%ZoneADEffHeating
    ELSE ! Every controlled zone must be simulated, so set missing inputs to the first
      FinalZoneSizing(CtrlZoneNum)%ZnCoolDgnSAMethod = ZoneSizingInput(1)%ZnCoolDgnSAMethod
      FinalZoneSizing(CtrlZoneNum)%ZnHeatDgnSAMethod = ZoneSizingInput(1)%ZnHeatDgnSAMethod
      FinalZoneSizing(CtrlZoneNum)%CoolDesTemp = ZoneSizingInput(1)%CoolDesTemp
      FinalZoneSizing(CtrlZoneNum)%HeatDesTemp = ZoneSizingInput(1)%HeatDesTemp
      FinalZoneSizing(CtrlZoneNum)%CoolDesTempDiff = ZoneSizingInput(1)%CoolDesTempDiff
      FinalZoneSizing(CtrlZoneNum)%HeatDesTempDiff = ZoneSizingInput(1)%HeatDesTempDiff
      FinalZoneSizing(CtrlZoneNum)%CoolDesHumRat = ZoneSizingInput(1)%CoolDesHumRat
      FinalZoneSizing(CtrlZoneNum)%HeatDesHumRat = ZoneSizingInput(1)%HeatDesHumRat
      FinalZoneSizing(CtrlZoneNum)%ZoneDesignSpecOAIndex = ZoneSizingInput(1)%ZoneDesignSpecOAIndex
      FinalZoneSizing(CtrlZoneNum)%OADesMethod = ZoneSizingInput(1)%OADesMethod
      FinalZoneSizing(CtrlZoneNum)%DesOAFlowPPer = ZoneSizingInput(1)%DesOAFlowPPer
      FinalZoneSizing(CtrlZoneNum)%DesOAFlowPerArea = ZoneSizingInput(1)%DesOAFlowPerArea
      FinalZoneSizing(CtrlZoneNum)%DesOAFlow = ZoneSizingInput(1)%DesOAFlow
      FinalZoneSizing(CtrlZoneNum)%CoolAirDesMethod = ZoneSizingInput(1)%CoolAirDesMethod
      FinalZoneSizing(CtrlZoneNum)%HeatAirDesMethod = ZoneSizingInput(1)%HeatAirDesMethod
      FinalZoneSizing(CtrlZoneNum)%InpDesCoolAirFlow = ZoneSizingInput(1)%DesCoolAirFlow
      FinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlowPerArea = ZoneSizingInput(1)%DesCoolMinAirFlowPerArea
      FinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlow = ZoneSizingInput(1)%DesCoolMinAirFlow
      FinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlowFrac = ZoneSizingInput(1)%DesCoolMinAirFlowFrac
      FinalZoneSizing(CtrlZoneNum)%InpDesHeatAirFlow = ZoneSizingInput(1)%DesHeatAirFlow
      FinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlowPerArea = ZoneSizingInput(1)%DesHeatMaxAirFlowPerArea
      FinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlow = ZoneSizingInput(1)%DesHeatMaxAirFlow
      FinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlowFrac = ZoneSizingInput(1)%DesHeatMaxAirFlowFrac
      FinalZoneSizing(CtrlZoneNum)%HeatSizingFactor = ZoneSizingInput(1)%HeatSizingFactor
      FinalZoneSizing(CtrlZoneNum)%CoolSizingFactor = ZoneSizingInput(1)%CoolSizingFactor
      FinalZoneSizing(CtrlZoneNum)%ZoneADEffCooling = ZoneSizingInput(1)%ZoneADEffCooling
      FinalZoneSizing(CtrlZoneNum)%ZoneADEffHeating = ZoneSizingInput(1)%ZoneADEffHeating
      FinalZoneSizing(CtrlZoneNum)%ZoneSecondaryRecirculation = ZoneSizingInput(1)%ZoneSecondaryRecirculation
      CalcFinalZoneSizing(CtrlZoneNum)%ZnCoolDgnSAMethod = ZoneSizingInput(1)%ZnCoolDgnSAMethod
      CalcFinalZoneSizing(CtrlZoneNum)%ZnHeatDgnSAMethod = ZoneSizingInput(1)%ZnHeatDgnSAMethod
      CalcFinalZoneSizing(CtrlZoneNum)%CoolDesTemp = ZoneSizingInput(1)%CoolDesTemp
      CalcFinalZoneSizing(CtrlZoneNum)%HeatDesTemp = ZoneSizingInput(1)%HeatDesTemp
      CalcFinalZoneSizing(CtrlZoneNum)%CoolDesTempDiff = ZoneSizingInput(1)%CoolDesTempDiff
      CalcFinalZoneSizing(CtrlZoneNum)%HeatDesTempDiff = ZoneSizingInput(1)%HeatDesTempDiff
      CalcFinalZoneSizing(CtrlZoneNum)%CoolDesHumRat = ZoneSizingInput(1)%CoolDesHumRat
      CalcFinalZoneSizing(CtrlZoneNum)%HeatDesHumRat = ZoneSizingInput(1)%HeatDesHumRat
      CalcFinalZoneSizing(CtrlZoneNum)%ZoneDesignSpecOAIndex = ZoneSizingInput(1)%ZoneDesignSpecOAIndex
      CalcFinalZoneSizing(CtrlZoneNum)%OADesMethod = ZoneSizingInput(1)%OADesMethod
      CalcFinalZoneSizing(CtrlZoneNum)%DesOAFlowPPer = ZoneSizingInput(1)%DesOAFlowPPer
      CalcFinalZoneSizing(CtrlZoneNum)%DesOAFlowPerArea = ZoneSizingInput(1)%DesOAFlowPerArea
      CalcFinalZoneSizing(CtrlZoneNum)%DesOAFlow = ZoneSizingInput(1)%DesOAFlow
      CalcFinalZoneSizing(CtrlZoneNum)%CoolAirDesMethod = ZoneSizingInput(1)%CoolAirDesMethod
      CalcFinalZoneSizing(CtrlZoneNum)%HeatAirDesMethod = ZoneSizingInput(1)%HeatAirDesMethod
      CalcFinalZoneSizing(CtrlZoneNum)%InpDesCoolAirFlow = ZoneSizingInput(1)%DesCoolAirFlow
      CalcFinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlowPerArea = ZoneSizingInput(1)%DesCoolMinAirFlowPerArea
      CalcFinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlow = ZoneSizingInput(1)%DesCoolMinAirFlow
      CalcFinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlowFrac = ZoneSizingInput(1)%DesCoolMinAirFlowFrac
      CalcFinalZoneSizing(CtrlZoneNum)%InpDesHeatAirFlow = ZoneSizingInput(1)%DesHeatAirFlow
      CalcFinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlowPerArea = ZoneSizingInput(1)%DesHeatMaxAirFlowPerArea
      CalcFinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlow = ZoneSizingInput(1)%DesHeatMaxAirFlow
      CalcFinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlowFrac = ZoneSizingInput(1)%DesHeatMaxAirFlowFrac
      CalcFinalZoneSizing(CtrlZoneNum)%HeatSizingFactor = ZoneSizingInput(1)%HeatSizingFactor
      CalcFinalZoneSizing(CtrlZoneNum)%CoolSizingFactor = ZoneSizingInput(1)%CoolSizingFactor
      CalcFinalZoneSizing(CtrlZoneNum)%ZoneADEffCooling = ZoneSizingInput(1)%ZoneADEffCooling
      CalcFinalZoneSizing(CtrlZoneNum)%ZoneADEffHeating = ZoneSizingInput(1)%ZoneADEffHeating
    END IF
    ALLOCATE(FinalZoneSizing(CtrlZoneNum)%HeatFlowSeq(NumOfTimeStepInDay))
    ALLOCATE(FinalZoneSizing(CtrlZoneNum)%CoolFlowSeq(NumOfTimeStepInDay))
    ALLOCATE(FinalZoneSizing(CtrlZoneNum)%HeatLoadSeq(NumOfTimeStepInDay))
    ALLOCATE(FinalZoneSizing(CtrlZoneNum)%CoolLoadSeq(NumOfTimeStepInDay))
    ALLOCATE(FinalZoneSizing(CtrlZoneNum)%HeatZoneTempSeq(NumOfTimeStepInDay))
    ALLOCATE(FinalZoneSizing(CtrlZoneNum)%CoolZoneTempSeq(NumOfTimeStepInDay))
    ALLOCATE(FinalZoneSizing(CtrlZoneNum)%HeatOutTempSeq(NumOfTimeStepInDay))
    ALLOCATE(FinalZoneSizing(CtrlZoneNum)%CoolOutTempSeq(NumOfTimeStepInDay))
    ALLOCATE(FinalZoneSizing(CtrlZoneNum)%HeatZoneRetTempSeq(NumOfTimeStepInDay))
    ALLOCATE(FinalZoneSizing(CtrlZoneNum)%HeatTstatTempSeq(NumOfTimeStepInDay))
    ALLOCATE(FinalZoneSizing(CtrlZoneNum)%CoolZoneRetTempSeq(NumOfTimeStepInDay))
    ALLOCATE(FinalZoneSizing(CtrlZoneNum)%CoolTstatTempSeq(NumOfTimeStepInDay))
    ALLOCATE(FinalZoneSizing(CtrlZoneNum)%HeatZoneHumRatSeq(NumOfTimeStepInDay))
    ALLOCATE(FinalZoneSizing(CtrlZoneNum)%CoolZoneHumRatSeq(NumOfTimeStepInDay))
    ALLOCATE(FinalZoneSizing(CtrlZoneNum)%HeatOutHumRatSeq(NumOfTimeStepInDay))
    ALLOCATE(FinalZoneSizing(CtrlZoneNum)%CoolOutHumRatSeq(NumOfTimeStepInDay))
    ALLOCATE(CalcFinalZoneSizing(CtrlZoneNum)%HeatFlowSeq(NumOfTimeStepInDay))
    ALLOCATE(CalcFinalZoneSizing(CtrlZoneNum)%CoolFlowSeq(NumOfTimeStepInDay))
    ALLOCATE(CalcFinalZoneSizing(CtrlZoneNum)%HeatLoadSeq(NumOfTimeStepInDay))
    ALLOCATE(CalcFinalZoneSizing(CtrlZoneNum)%CoolLoadSeq(NumOfTimeStepInDay))
    ALLOCATE(CalcFinalZoneSizing(CtrlZoneNum)%HeatZoneTempSeq(NumOfTimeStepInDay))
    ALLOCATE(CalcFinalZoneSizing(CtrlZoneNum)%CoolZoneTempSeq(NumOfTimeStepInDay))
    ALLOCATE(CalcFinalZoneSizing(CtrlZoneNum)%HeatOutTempSeq(NumOfTimeStepInDay))
    ALLOCATE(CalcFinalZoneSizing(CtrlZoneNum)%CoolOutTempSeq(NumOfTimeStepInDay))
    ALLOCATE(CalcFinalZoneSizing(CtrlZoneNum)%HeatZoneRetTempSeq(NumOfTimeStepInDay))
    ALLOCATE(CalcFinalZoneSizing(CtrlZoneNum)%HeatTstatTempSeq(NumOfTimeStepInDay))
    ALLOCATE(CalcFinalZoneSizing(CtrlZoneNum)%CoolZoneRetTempSeq(NumOfTimeStepInDay))
    ALLOCATE(CalcFinalZoneSizing(CtrlZoneNum)%CoolTstatTempSeq(NumOfTimeStepInDay))
    ALLOCATE(CalcFinalZoneSizing(CtrlZoneNum)%HeatZoneHumRatSeq(NumOfTimeStepInDay))
    ALLOCATE(CalcFinalZoneSizing(CtrlZoneNum)%CoolZoneHumRatSeq(NumOfTimeStepInDay))
    ALLOCATE(CalcFinalZoneSizing(CtrlZoneNum)%HeatOutHumRatSeq(NumOfTimeStepInDay))
    ALLOCATE(CalcFinalZoneSizing(CtrlZoneNum)%CoolOutHumRatSeq(NumOfTimeStepInDay))
   DO TimeStepIndex=1,NumOfTimeStepInDay
      FinalZoneSizing(CtrlZoneNum)%HeatFlowSeq(TimeStepIndex) = 0.0d0
      FinalZoneSizing(CtrlZoneNum)%CoolFlowSeq(TimeStepIndex) = 0.0d0
      FinalZoneSizing(CtrlZoneNum)%HeatLoadSeq(TimeStepIndex) = 0.0d0
      FinalZoneSizing(CtrlZoneNum)%CoolLoadSeq(TimeStepIndex) = 0.0d0
      FinalZoneSizing(CtrlZoneNum)%HeatZoneTempSeq(TimeStepIndex) = 0.0d0
      FinalZoneSizing(CtrlZoneNum)%CoolZoneTempSeq(TimeStepIndex) = 0.0d0
      FinalZoneSizing(CtrlZoneNum)%HeatOutTempSeq(TimeStepIndex) = 0.0d0
      FinalZoneSizing(CtrlZoneNum)%CoolOutTempSeq(TimeStepIndex) = 0.0d0
      FinalZoneSizing(CtrlZoneNum)%HeatZoneRetTempSeq(TimeStepIndex) = 0.0d0
      FinalZoneSizing(CtrlZoneNum)%HeatTstatTempSeq(TimeStepIndex) = 0.0d0
      FinalZoneSizing(CtrlZoneNum)%CoolZoneRetTempSeq(TimeStepIndex) = 0.0d0
      FinalZoneSizing(CtrlZoneNum)%CoolTstatTempSeq(TimeStepIndex) = 0.0d0
      FinalZoneSizing(CtrlZoneNum)%HeatZoneHumRatSeq(TimeStepIndex) = 0.0d0
      FinalZoneSizing(CtrlZoneNum)%CoolZoneHumRatSeq(TimeStepIndex) = 0.0d0
      FinalZoneSizing(CtrlZoneNum)%HeatOutHumRatSeq(TimeStepIndex) = 0.0d0
      FinalZoneSizing(CtrlZoneNum)%CoolOutHumRatSeq(TimeStepIndex) = 0.0d0
      CalcFinalZoneSizing(CtrlZoneNum)%HeatFlowSeq(TimeStepIndex) = 0.0d0
      CalcFinalZoneSizing(CtrlZoneNum)%CoolFlowSeq(TimeStepIndex) = 0.0d0
      CalcFinalZoneSizing(CtrlZoneNum)%HeatLoadSeq(TimeStepIndex) = 0.0d0
      CalcFinalZoneSizing(CtrlZoneNum)%CoolLoadSeq(TimeStepIndex) = 0.0d0
      CalcFinalZoneSizing(CtrlZoneNum)%HeatZoneTempSeq(TimeStepIndex) = 0.0d0
      CalcFinalZoneSizing(CtrlZoneNum)%CoolZoneTempSeq(TimeStepIndex) = 0.0d0
      CalcFinalZoneSizing(CtrlZoneNum)%HeatOutTempSeq(TimeStepIndex) = 0.0d0
      CalcFinalZoneSizing(CtrlZoneNum)%CoolOutTempSeq(TimeStepIndex) = 0.0d0
      CalcFinalZoneSizing(CtrlZoneNum)%HeatZoneRetTempSeq(TimeStepIndex) = 0.0d0
      CalcFinalZoneSizing(CtrlZoneNum)%HeatTstatTempSeq(TimeStepIndex) = 0.0d0
      CalcFinalZoneSizing(CtrlZoneNum)%CoolZoneRetTempSeq(TimeStepIndex) = 0.0d0
      CalcFinalZoneSizing(CtrlZoneNum)%CoolTstatTempSeq(TimeStepIndex) = 0.0d0
      CalcFinalZoneSizing(CtrlZoneNum)%HeatZoneHumRatSeq(TimeStepIndex) = 0.0d0
      CalcFinalZoneSizing(CtrlZoneNum)%CoolZoneHumRatSeq(TimeStepIndex) = 0.0d0
      CalcFinalZoneSizing(CtrlZoneNum)%HeatOutHumRatSeq(TimeStepIndex) = 0.0d0
      CalcFinalZoneSizing(CtrlZoneNum)%CoolOutHumRatSeq(TimeStepIndex) = 0.0d0
    END DO
    ! setup CalcFinalZoneSizing structure for use with EMS, some as sensors, some as actuators
    IF (AnyEnergyManagementSystemInModel) Then !
      !actuate  REAL(r64)             :: DesHeatMassFlow          = 0.0d0   ! zone design heating air mass flow rate [kg/s]
      CALL SetupEMSInternalVariable('Final Zone Design Heating Air Mass Flow Rate', FinalZoneSizing(CtrlZoneNum)%ZoneName, &
                                    '[kg/s]', FinalZoneSizing(CtrlZoneNum)%DesHeatMassFlow )
      CALL SetupEMSInternalVariable('Intermediate Zone Design Heating Air Mass Flow Rate', &
                                     CalcFinalZoneSizing(CtrlZoneNum)%ZoneName, '[kg/s]', &
                                     CalcFinalZoneSizing(CtrlZoneNum)%DesHeatMassFlow )
      CALL SetupEMSActuator('Sizing:Zone', CalcFinalZoneSizing(CtrlZoneNum)%ZoneName, 'Zone Design Heating Air Mass Flow Rate', &
                            '[kg/s]', CalcFinalZoneSizing(CtrlZoneNum)%EMSOverrideDesHeatMassOn, &
                            CalcFinalZoneSizing(CtrlZoneNum)%EMSValueDesHeatMassFlow )
      !actuate  REAL(r64)             :: DesCoolMassFlow          = 0.0d0   ! zone design cooling air mass flow rate [kg/s]
      CALL SetupEMSInternalVariable('Final Zone Design Cooling Air Mass Flow Rate', FinalZoneSizing(CtrlZoneNum)%ZoneName, &
                                    '[kg/s]', FinalZoneSizing(CtrlZoneNum)%DesCoolMassFlow )
      CALL SetupEMSInternalVariable('Intermediate Zone Design Cooling Air Mass Flow Rate', &
                                     CalcFinalZoneSizing(CtrlZoneNum)%ZoneName, '[kg/s]', &
                                     CalcFinalZoneSizing(CtrlZoneNum)%DesCoolMassFlow )
      CALL SetupEMSActuator('Sizing:Zone', CalcFinalZoneSizing(CtrlZoneNum)%ZoneName, 'Zone Design Cooling Air Mass Flow Rate', &
                            '[kg/s]',  CalcFinalZoneSizing(CtrlZoneNum)%EMSOverrideDesCoolMassOn, &
                            CalcFinalZoneSizing(CtrlZoneNum)%EMSValueDesCoolMassFlow )
      !actuate  REAL(r64)             :: DesHeatLoad              = 0.0d0   ! zone design heating load [W]
      CALL SetupEMSInternalVariable('Final Zone Design Heating Load', FinalZoneSizing(CtrlZoneNum)%ZoneName, '[W]', &
                                    FinalZoneSizing(CtrlZoneNum)%DesHeatLoad )
      CALL SetupEMSInternalVariable('Intermediate Zone Design Heating Load', CalcFinalZoneSizing(CtrlZoneNum)%ZoneName, '[W]', &
                                    CalcFinalZoneSizing(CtrlZoneNum)%DesHeatLoad )
      CALL SetupEMSActuator('Sizing:Zone', CalcFinalZoneSizing(CtrlZoneNum)%ZoneName, 'Zone Design Heating Load', '[W]', &
                        CalcFinalZoneSizing(CtrlZoneNum)%EMSOverrideDesHeatLoadOn, &
                        CalcFinalZoneSizing(CtrlZoneNum)%EMSValueDesHeatLoad )
      !actuate  REAL(r64)             :: DesCoolLoad              = 0.0d0   ! zone design cooling load [W]
      CALL SetupEMSInternalVariable('Final Zone Design Cooling Load', FinalZoneSizing(CtrlZoneNum)%ZoneName, '[W]', &
                                    FinalZoneSizing(CtrlZoneNum)%DesCoolLoad )
      CALL SetupEMSInternalVariable('Intermediate Zone Design Cooling Load', CalcFinalZoneSizing(CtrlZoneNum)%ZoneName, '[W]', &
                                    CalcFinalZoneSizing(CtrlZoneNum)%DesCoolLoad )
      CALL SetupEMSActuator('Sizing:Zone', CalcFinalZoneSizing(CtrlZoneNum)%ZoneName, 'Zone Design Cooling Load', '[W]', &
                        CalcFinalZoneSizing(CtrlZoneNum)%EMSOverrideDesCoolLoadOn, &
                        CalcFinalZoneSizing(CtrlZoneNum)%EMSValueDesCoolLoad )
      !sensor?  REAL(r64)             :: DesHeatDens              = 0.0d0   ! zone design heating air density [kg/m3]
      CALL SetupEMSInternalVariable('Final Zone Design Heating Air Density', FinalZoneSizing(CtrlZoneNum)%ZoneName, '[kg/m3]', &
                                    FinalZoneSizing(CtrlZoneNum)%DesHeatDens )
      CALL SetupEMSInternalVariable('Intermediate Zone Design Heating Air Density', CalcFinalZoneSizing(CtrlZoneNum)%ZoneName, &
                                    '[kg/m3]', CalcFinalZoneSizing(CtrlZoneNum)%DesHeatDens )
      !sensor?  REAL(r64)             :: DesCoolDens              = 0.0d0   ! zone design cooling air density [kg/m3]
      CALL SetupEMSInternalVariable('Final Zone Design Cooling Air Density', FinalZoneSizing(CtrlZoneNum)%ZoneName, '[kg/m3]', &
                                    FinalZoneSizing(CtrlZoneNum)%DesCoolDens )
      CALL SetupEMSInternalVariable('Intermediate Zone Design Cooling Air Density', CalcFinalZoneSizing(CtrlZoneNum)%ZoneName, &
                                    '[kg/m3]', CalcFinalZoneSizing(CtrlZoneNum)%DesCoolDens )
      !actuate  REAL(r64)             :: DesHeatVolFlow           = 0.0d0   ! zone design heating air volume flow rate [m3/s]
      CALL SetupEMSInternalVariable('Final Zone Design Heating Volume Flow', FinalZoneSizing(CtrlZoneNum)%ZoneName, '[m3/s]', &
                                    FinalZoneSizing(CtrlZoneNum)%DesHeatVolFlow )
      CALL SetupEMSInternalVariable('Intermediate Zone Design Heating Volume Flow', CalcFinalZoneSizing(CtrlZoneNum)%ZoneName, &
                                    '[m3/s]', CalcFinalZoneSizing(CtrlZoneNum)%DesHeatVolFlow )
      CALL SetupEMSActuator('Sizing:Zone', CalcFinalZoneSizing(CtrlZoneNum)%ZoneName, 'Zone Design Heating Vol Flow', '[m3/s]', &
                            CalcFinalZoneSizing(CtrlZoneNum)%EMSOverrideDesHeatVolOn, &
                            CalcFinalZoneSizing(CtrlZoneNum)%EMSValueDesHeatVolFlow )
      !actuate  REAL(r64)             :: DesCoolVolFlow           = 0.0d0   ! zone design cooling air volume flow rate [m3/s]
      CALL SetupEMSInternalVariable('Final Zone Design Cooling Volume Flow', FinalZoneSizing(CtrlZoneNum)%ZoneName, '[m3/s]', &
                                    FinalZoneSizing(CtrlZoneNum)%DesCoolVolFlow )
      CALL SetupEMSInternalVariable('Intermediate Zone Design Cooling Volume Flow', CalcFinalZoneSizing(CtrlZoneNum)%ZoneName, &
                                    '[m3/s]', CalcFinalZoneSizing(CtrlZoneNum)%DesCoolVolFlow )
      CALL SetupEMSActuator('Sizing:Zone', CalcFinalZoneSizing(CtrlZoneNum)%ZoneName, 'Zone Design Cooling Vol Flow', '[m3/s]', &
                        CalcFinalZoneSizing(CtrlZoneNum)%EMSOverrideDesCoolVolOn, &
                        CalcFinalZoneSizing(CtrlZoneNum)%EMSValueDesCoolVolFlow )
      !actuate  REAL(r64)          :: DesHeatVolFlowMax        = 0.0d0   ! zone design heating maximum air volume flow rate [m3/s]
      !actuate  REAL(r64)          :: DesCoolVolFlowMin        = 0.0d0   ! zone design cooling minimum air volume flow rate [m3/s]
      CALL SetupEMSInternalVariable('Zone Outdoor Air Design Volume Flow Rate', CalcFinalZoneSizing(CtrlZoneNum)%ZoneName, &
                                    '[m3/s]', CalcFinalZoneSizing(CtrlZoneNum)%MinOA )
    ENDIF
  END DO
  ! Use the max occupancy data from the PEOPLE structure to calculate design min OA for each zone
  ! Calculate the zone design minimum outside air flow rate from the 3 Zone Sizing OA inputs and
  ! from the specified OA method
  DO CtrlZoneNum = 1,NumOfZones
    IF (.not. ZoneEquipConfig(CtrlZoneNum)%IsControlled) CYCLE
    ! Use the max occupancy data from the PEOPLE structure to calculate design min OA for each zone
    ! from the outside air flow per person input
    TotPeopleInZone = 0.0d0
    ZoneIndex = FinalZoneSizing(CtrlZoneNum)%ActualZoneNum
    DO PeopleNum=1,TotPeople
      IF (People(PeopleNum)%ZonePtr == FinalZoneSizing(CtrlZoneNum)%ActualZoneNum) THEN
        TotPeopleInZone = TotPeopleInZone + (People(PeopleNum)%NumberOfPeople &
                               * Zone(FinalZoneSizing(CtrlZoneNum)%ActualZoneNum)%Multiplier &
                               * Zone(FinalZoneSizing(CtrlZoneNum)%ActualZoneNum)%ListMultiplier)
        SchMax = GetScheduleMaxValue(People(PeopleNum)%NumberOfPeoplePtr)
        IF (SchMax > 0) THEN
          FinalZoneSizing(CtrlZoneNum)%ZonePeakOccupancy = TotPeopleInZone*SchMax
        ELSE
          FinalZoneSizing(CtrlZoneNum)%ZonePeakOccupancy = TotPeopleInZone
        ENDIF
      END IF
    END DO
    FinalZoneSizing(CtrlZoneNum)%TotalZoneFloorArea = (Zone(ZoneIndex)%FloorArea &
                               * Zone(FinalZoneSizing(CtrlZoneNum)%ActualZoneNum)%Multiplier &
                               * Zone(FinalZoneSizing(CtrlZoneNum)%ActualZoneNum)%ListMultiplier)
    OAFromPeople = FinalZoneSizing(CtrlZoneNum)%DesOAFlowPPer * TotPeopleInZone
    OAFromArea = FinalZoneSizing(CtrlZoneNum)%DesOAFlowPerArea * FinalZoneSizing(CtrlZoneNum)%TotalZoneFloorArea
    FinalZoneSizing(CtrlZoneNum)%TotPeopleInZone = TotPeopleInZone
    FinalZoneSizing(CtrlZoneNum)%TotalOAFromPeople = OAFromPeople
    FinalZoneSizing(CtrlZoneNum)%TotalOAFromArea = OAFromArea
    ! Calculate the design min OA flow rate for this zone
    UseOccSchFlag = .FALSE.
    UseMinOASchFlag = .FALSE.
    DSOAPtr = FinalZoneSizing(CtrlZoneNum)%ZoneDesignSpecOAIndex
    OAVolumeFlowRate = CalcDesignSpecificationOutdoorAir(DSOAPtr, ZoneIndex, UseOccSchFlag, UseMinOASchFlag)
    ! Zone(ZoneIndex)%Multiplier and Zone(ZoneIndex)%ListMultiplier applied in CalcDesignSpecificationOutdoorAir
    FinalZoneSizing(CtrlZoneNum)%MinOA = OAVolumeFlowRate
    CalcFinalZoneSizing(CtrlZoneNum)%MinOA = OAVolumeFlowRate
    IF (FinalZoneSizing(CtrlZoneNum)%ZoneADEffCooling > 0.0d0 .OR. FinalZoneSizing(CtrlZoneNum)%ZoneADEffHeating > 0.0d0) THEN
      FinalZoneSizing(CtrlZoneNum)%MinOA = FinalZoneSizing(CtrlZoneNum)%MinOA / Min(FinalZoneSizing(CtrlZoneNum)%ZoneADEffCooling, &
                                                 FinalZoneSizing(CtrlZoneNum)%ZoneADEffHeating)
      CalcFinalZoneSizing(CtrlZoneNum)%MinOA = FinalZoneSizing(CtrlZoneNum)%MinOA
    END IF
    ! calculated zone design flow rates automatically take into account zone multipliers, since the zone
    ! loads are multiplied (in ZoneTempPredictorCorrector.f90). Flow rates derived directly from
    ! user inputs need to be explicitly multiplied by the zone multipliers.
    FinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlow2 = FinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlowPerArea   &
                                                      * Zone(ZoneIndex)%FloorArea &
                                                      *  Zone(ZoneIndex)%Multiplier * Zone(ZoneIndex)%ListMultiplier
    CalcFinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlow2 = CalcFinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlowPerArea   &
                                                      * Zone(ZoneIndex)%FloorArea &
                                                      *  Zone(ZoneIndex)%Multiplier * Zone(ZoneIndex)%ListMultiplier
    FinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlow2 = FinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlowPerArea   &
                                                      * Zone(ZoneIndex)%FloorArea &
                                                      *  Zone(ZoneIndex)%Multiplier * Zone(ZoneIndex)%ListMultiplier
    CalcFinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlow2 = CalcFinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlowPerArea   &
                                                      * Zone(ZoneIndex)%FloorArea &
                                                      *  Zone(ZoneIndex)%Multiplier * Zone(ZoneIndex)%ListMultiplier
    FinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlow = FinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlow &
                                                      *  Zone(ZoneIndex)%Multiplier * Zone(ZoneIndex)%ListMultiplier
    CalcFinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlow = CalcFinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlow &
                                                      *  Zone(ZoneIndex)%Multiplier * Zone(ZoneIndex)%ListMultiplier
    FinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlow = FinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlow &
                                                      *  Zone(ZoneIndex)%Multiplier * Zone(ZoneIndex)%ListMultiplier
    CalcFinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlow = CalcFinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlow &
                                                      *  Zone(ZoneIndex)%Multiplier * Zone(ZoneIndex)%ListMultiplier
    FinalZoneSizing(CtrlZoneNum)%InpDesCoolAirFlow = FinalZoneSizing(CtrlZoneNum)%InpDesCoolAirFlow &
                                                      *  Zone(ZoneIndex)%Multiplier * Zone(ZoneIndex)%ListMultiplier
    CalcFinalZoneSizing(CtrlZoneNum)%InpDesCoolAirFlow = CalcFinalZoneSizing(CtrlZoneNum)%InpDesCoolAirFlow &
                                                      *  Zone(ZoneIndex)%Multiplier * Zone(ZoneIndex)%ListMultiplier
    FinalZoneSizing(CtrlZoneNum)%InpDesHeatAirFlow = FinalZoneSizing(CtrlZoneNum)%InpDesHeatAirFlow &
                                                      *  Zone(ZoneIndex)%Multiplier * Zone(ZoneIndex)%ListMultiplier
    CalcFinalZoneSizing(CtrlZoneNum)%InpDesHeatAirFlow = CalcFinalZoneSizing(CtrlZoneNum)%InpDesHeatAirFlow &
                                                      *  Zone(ZoneIndex)%Multiplier * Zone(ZoneIndex)%ListMultiplier
    DO DesDayNum=1,TotDesDays+TotRunDesPersDays
      ZoneSizing(CtrlZoneNum,DesDayNum)%MinOA = FinalZoneSizing(CtrlZoneNum)%MinOA
      CalcZoneSizing(CtrlZoneNum,DesDayNum)%MinOA = CalcFinalZoneSizing(CtrlZoneNum)%MinOA
      ZoneSizing(CtrlZoneNum,DesDayNum)%DesCoolMinAirFlow2 = FinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlow2
      CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesCoolMinAirFlow2 = CalcFinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlow2
      ZoneSizing(CtrlZoneNum,DesDayNum)%DesCoolMinAirFlow = FinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlow
      CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesCoolMinAirFlow = CalcFinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlow
      ZoneSizing(CtrlZoneNum,DesDayNum)%DesHeatMaxAirFlow2 = FinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlow2
      CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesHeatMaxAirFlow2 = CalcFinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlow2
      ZoneSizing(CtrlZoneNum,DesDayNum)%DesHeatMaxAirFlow = FinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlow
      CalcZoneSizing(CtrlZoneNum,DesDayNum)%DesHeatMaxAirFlow = CalcFinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlow
    END DO
  END DO
  WRITE (OutputFileInits, 890)
  WRITE (OutputFileInits, 891) NumTimeStepsInAvg
  WRITE (OutputFileInits, 990)
  WRITE (OutputFileInits, 991) GlobalHeatSizingFactor
  DO CtrlZoneNum = 1,NumOfZones
    IF (.not. ZoneEquipConfig(CtrlZoneNum)%IsControlled) CYCLE
    IF (FinalZoneSizing(CtrlZoneNum)%HeatSizingFactor .NE. 1.0d0) THEN
      WRITE (OutputFileInits, 992) TRIM(FinalZoneSizing(CtrlZoneNum)%ZoneName), FinalZoneSizing(CtrlZoneNum)%HeatSizingFactor
    END IF
  END DO
  WRITE (OutputFileInits, 993)
  WRITE (OutputFileInits, 994) GlobalCoolSizingFactor
  DO CtrlZoneNum = 1,NumOfZones
    IF (.not. ZoneEquipConfig(CtrlZoneNum)%IsControlled) CYCLE
    IF (FinalZoneSizing(CtrlZoneNum)%CoolSizingFactor .NE. 1.0d0) THEN
      WRITE (OutputFileInits, 995) TRIM(FinalZoneSizing(CtrlZoneNum)%ZoneName), FinalZoneSizing(CtrlZoneNum)%CoolSizingFactor
    END IF
  END DO
  890 FORMAT('! <Load Timesteps in Zone Design Calculation Averaging Window>, Value')
  891 FORMAT(' Load Timesteps in Zone Design Calculation Averaging Window, ',I4)
  990 FORMAT('! <Heating Sizing Factor Information>, Sizing Factor ID, Value')
  991 FORMAT(' Heating Sizing Factor Information, Global, ',G12.5)
  992 FORMAT(' Heating Sizing Factor Information, Zone ',A,', ',G12.5)
  993 FORMAT('! <Cooling Sizing Factor Information>, Sizing Factor ID, Value')
  994 FORMAT(' Cooling Sizing Factor Information, Global, ',G12.5)
  995 FORMAT(' Cooling Sizing Factor Information, Zone ',A,', ',G12.5)
  RETURN
END SUBROUTINE SetUpZoneSizingArrays
All Procedures
AbortEnergyPlus AbsoluteAirMass ActivateDemandManagers ActivateEMSControls AddBlankKeys addChargesToOperand AddCompSizeTableEntry AddEndUseSubcategory AddError addFootNoteSubTable AddInstruction AddMeter addMonthlyCharge AddMonthlyFieldSetInput AddMonthlyReport AddNeighborInformation AddObjectDefandParse addOperand AddRecordFromSection AddRecordToOutputVariableStructure AddSectionDef AddShadowRelateTableEntry AddSQLiteComponentSizingRecord AddSQLiteComponentSizingRecord AddSQLiteSystemSizingRecord AddSQLiteSystemSizingRecord AddSQLiteZoneSizingRecord AddSQLiteZoneSizingRecord AddTOCEntry AddTOCZoneLoadComponentTable AddToOutputVariableList AddVariablesForMonthlyReport AddVariableSlatBlind AddWindow AdjustAirSetpointsforOpTempCntrl AdjustCBF AdjustCBF AdjustChangeInLoadByEMSControls AdjustChangeInLoadByHowServed AdjustChangeInLoadForLastStageUpperRangeLimit AdjustCoolingSetPointforTempAndHumidityControl adjusthhat AdjustPumpFlowRequestByEMSControls AdjustReportingHourAndMinutes AdjustVBGap AdvanceRootFinder AFECFR AFECOI AFECPD AFECPF AFEDMP AFEDOP AFEDWC AFEELR AFEEXF AFEFAN AFEHEX AFEHOP AFEPLR AFESCR AFESEL AFESOP AFETMU AirflowNetworkVentingControl AirMass AIRMOV AllocateAirflowNetworkData AllocateAirHeatBalArrays AllocateAndInitData AllocateAndSetUpVentReports AllocateCFSStateHourlyData AllocateForCFSRefPointsGeometry AllocateForCFSRefPointsState AllocateHeatBalArrays AllocateLoadComponentArrays AllocateModuleArrays AllocateModuleArrays AllocateSurfaceHeatBalArrays AllocateWeatherData angle_2dvector AnisoSkyViewFactors AnyPlantLoopSidesNeedSim AnyPlantSplitterMixerLacksContinuity AreaPolygon ArgCheck array_to_vector ASHRAETauModel ASHWAT_OffNormalProperties ASHWAT_Solar ASHWAT_Thermal ASSIGNMENT (=) AssignNodeNumber AssignReportNumber AssignResourceTypeNum AssignReverseConstructionNumber AssignVariablePt AttachCustomMeters AttachMeters AuditBranches AUTOTDMA BaseThermalPropertySet_Diffusivity BeginEnvrnInitializeRuntimeLanguage BetweenDates BetweenGlassForcedFlow BetweenGlassShadeForcedFlow BetweenGlassShadeNaturalFlow BisectionMethod BlindBeamBeamTrans BlindOpticsBeam BlindOpticsDiffuse BoreholeResistance BoundValueToNodeMinMaxAvail BoundValueToWithinTwoValues BracketRoot BranchPressureDrop BrentMethod BuildGap BuildKeyVarList Calc4PipeFanCoil Calc_EN673 Calc_ISO15099 CalcActiveTranspiredCollector CalcAggregateLoad CalcAirflowNetworkAirBalance CalcAirflowNetworkCO2Balance CalcAirflowNetworkGCBalance CalcAirflowNetworkHeatBalance CalcAirflowNetworkMoisBalance CalcAirFlowSimple CalcAirLoopSplitter CalcAirMixer CalcAirToAirGenericHeatExch CalcAirToAirPlateHeatExch CalcAirZoneReturnPlenum CalcAirZoneSupplyPlenum CalcAlamdariHammondStableHorizontal CalcAlamdariHammondUnstableHorizontal CalcAlamdariHammondVerticalWall CalcAngleFactorMRT CalcApproximateViewFactors CalcASHRAEDetailedIntConvCoeff CalcASHRAESimpExtConvectCoeff CalcASHRAESimpleIntConvCoeff CalcASHRAEVerticalWall CalcATMixer CalcAwbiHattonHeatedFloor CalcAwbiHattonHeatedWall CalcBasinHeaterPower CalcBasinHeaterPowerForMultiModeDXCoil CalcBeamSolarOnWinRevealSurface CalcBeamSolDiffuseReflFactors CalcBeamSolSpecularReflFactors CalcBeausoleilMorrisonMixedAssistedWall CalcBeausoleilMorrisonMixedOpposingWall CalcBeausoleilMorrisonMixedStableCeiling CalcBeausoleilMorrisonMixedStableFloor CalcBeausoleilMorrisonMixedUnstableCeiling CalcBeausoleilMorrisonMixedUnstableFloor CalcBLASTAbsorberModel CalcBlockenWindward CalcBoilerModel CalcBoilerModel CalcBottomFluxCoefficents CalcBottomSurfTemp CalcBuriedPipeSoil CalcCBF CalcCBF CalcCBVAV CalcCeilingDiffuserInletCorr CalcCeilingDiffuserIntConvCoeff CalcChillerHeaterModel CalcChillerIPLV CalcChillerModel CalcClearRoof CalcCoilUAbyEffectNTU CalcColdestSetPoint CalcComplexWindowOverlap CalcComplexWindowThermal CalcCompSuctionTempResidual CalcCondEntSetPoint CalcConnectionsDrainTemp CalcConnectionsFlowRates CalcConnectionsHeatRecovery CalcConstCOPChillerModel CalcConvCoeffAbsPlateAndWater CalcConvCoeffBetweenPlates CalcCoolBeam CalcCoolTower CalcCoordinateTransformation CalcCoPlanarNess CalcCostEstimate CalcCTGeneratorModel CalcDayltgCoefficients CalcDayltgCoeffsMapPoints CalcDayltgCoeffsRefMapPoints CalcDayltgCoeffsRefPoints CalcDesiccantBalancedHeatExch CalcDesignSpecificationOutdoorAir CalcDesuperheaterHeatingCoil CalcDesuperheaterWaterHeater CalcDetailedHcInForDVModel CalcDetailedSystem CalcDetailedTransSystem CalcDetailFlatFinCoolingCoil CalcDetIceStorLMTDstar CalcDiffTSysAvailMgr CalcDirectAir CalcDirectEvapCooler CalcDirectResearchSpecialEvapCooler CalcDoe2DXCoil CalcDOE2Leeward CalcDOE2Windward CalcDryFinEffCoef CalcDryIndirectEvapCooler CalcDuct CalcDXCoilStandardRating CalcDXHeatingCoil CalcEarthTube CalcEcoRoof CalcEffectiveness CalcEffectiveSHR CalcEffectiveSHR CalcEffectiveSHR CalcEffectiveSHR CalcElecSteamHumidifier CalcElectricBaseboard CalcElectricChillerHeatRecovery CalcElectricChillerModel CalcElectricEIRChillerModel CalcElectricHeatingCoil CalcEmmelRoof CalcEmmelVertical CalcEngineChillerHeatRec CalcEngineDrivenChillerModel CalcEQLOpticalProperty CalcEQLWindowOpticalProperty CalcEQLWindowSHGCAndTransNormal CalcEQLWindowStandardRatings CalcEQLWindowUvalue CalcEquipmentDrainTemp CalcEquipmentFlowRates CalcExhaustAbsorberChillerModel CalcExhaustAbsorberHeaterModel CalcExteriorVentedCavity CalcFisherPedersenCeilDiffuserCeiling CalcFisherPedersenCeilDiffuserFloor CalcFisherPedersenCeilDiffuserWalls CalcFluidHeatExchanger CalcFohannoPolidoriVerticalWall CalcFollowOATempSetPoint CalcFollowSysNodeTempSetPoint CalcFourPipeIndUnit CalcFrameDividerShadow CalcFuelCellAuxHeater CalcFuelCellGeneratorModel CalcFuelCellGenHeatRecovery CalcFurnaceOutput CalcFurnaceResidual CalcGasAbsorberChillerModel CalcGasAbsorberHeaterModel CalcGasCooler CalcGasHeatingCoil CalcGenericDesiccantDehumidifier CalcGoldsteinNovoselacCeilingDiffuserFloor CalcGoldsteinNovoselacCeilingDiffuserWall CalcGoldsteinNovoselacCeilingDiffuserWindow CalcGroundTempSetPoint CalcGroundwaterWell CalcGshpModel CalcGshpModel CalcGTChillerModel CalcHeatBalanceAir CalcHeatBalanceInsideSurf CalcHeatBalanceInsideSurf CalcHeatBalanceOutsideSurf CalcHeatBalanceOutsideSurf CalcHeatBalFiniteDiff CalcHeatBalHAMT CalcHeatPumpWaterHeater CalcHeatTransCoeffAndCoverTemp CalcHfExteriorSparrow CalcHighTempRadiantSystem CalcHighTempRadiantSystemSP CalcHiTurnOffSysAvailMgr CalcHiTurnOnSysAvailMgr CalcHnASHRAETARPExterior CalcHPCoolingSimple CalcHPHeatingSimple CalcHPWHDXCoil CalcHWBaseboard CalcHXAssistedCoolingCoil CalcHXEffectTerm CalcHybridVentSysAvailMgr CalcIBesselFunc CalcICEngineGeneratorModel CalcICEngineGenHeatRecovery CalcIceStorageCapacity CalcIceStorageCharge CalcIceStorageDischarge CalcIceStorageDormant CalcICSSolarCollector CalcIdealCondEntSetPoint CalcIfSetpointMet CalcIndirectAbsorberModel CalcIndirectResearchSpecialEvapCooler CalcInteriorRadExchange CalcInteriorSolarDistribution CalcInteriorSolarOverlaps CalcInteriorWinTransDifSolInitialDistribution CalcISO15099WindowIntConvCoeff CalcKaradagChilledCeiling CalcKBesselFunc CalcKhalifaEq3WallAwayFromHeat CalcKhalifaEq4CeilingAwayFromHeat CalcKhalifaEq5WallsNearHeat CalcKhalifaEq6NonHeatedWalls CalcKhalifaEq7Ceiling CalcLoadCenterThermalLoad CalcLoTurnOffSysAvailMgr CalcLoTurnOnSysAvailMgr CalcLowTempCFloRadiantSystem CalcLowTempCFloRadSysComps CalcLowTempElecRadiantSystem CalcLowTempHydrRadiantSystem CalcLowTempHydrRadSysComps CalcMatrixInverse CalcMcAdams CalcMerkelVariableSpeedTower CalcMicroCHPNoNormalizeGeneratorModel CalcMinIntWinSolidAngs CalcMitchell CalcMixedAirSetPoint CalcMoistureBalanceEMPD CalcMoreNodeInfo CalcMoWITTLeeward CalcMoWITTWindward CalcMSHeatPump CalcMTGeneratorModel CalcMultiSpeedDXCoil CalcMultiSpeedDXCoilCooling CalcMultiSpeedDXCoilHeating CalcMultiStageElectricHeatingCoil CalcMultiStageGasHeatingCoil CalcMultiZoneAverageCoolingSetPoint CalcMultiZoneAverageHeatingSetPoint CalcMultiZoneAverageMaxHumSetPoint CalcMultiZoneAverageMinHumSetPoint CalcMultiZoneMaxHumSetPoint CalcMultiZoneMinHumSetPoint CalcMundtModel CalcNCycSysAvailMgr CalcNewZoneHeatCoolFlowRates CalcNewZoneHeatOnlyFlowRates CalcNodeMassFlows CalcNominalWindowCond CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNusselt CalcNusseltJurges CalcNVentSysAvailMgr CalcOAController CalcOAMassFlow CalcOAMassFlow CalcOAMixer CalcOAOnlyMassFlow CalcOAPretreatSetPoint CalcOAUnitCoilComps CalcObstrMultiplier CalcOptStartSysAvailMgr CalcOtherSideDemand CalcOutdoorAirUnit CalcOutsideAirSetPoint CalcOutsideSurfTemp CalcParallelPIU CalcPassiveExteriorBaffleGap CalcPassiveSystem CalcPassiveTranspiredCollector CalcPerSolarBeam CalcPipeHeatTransCoef CalcPipesHeatTransfer CalcPipeTransBeam CalcPlantValves CalcPollution CalcPolyhedronVolume CalcPolynomCoef CalcPondGroundHeatExchanger CalcPredictedHumidityRatio CalcPredictedSystemLoad CalcPTUnit CalcPumps CalcPurchAirLoads CalcPurchAirMinOAMassFlow CalcPurchAirMixedAir CalcPVTcollectors CalcQiceChargeMaxByChiller CalcQiceChargeMaxByITS CalcQiceDischageMax CalcRABFlowSetPoint CalcRackSystem CalcRadSysHXEffectTerm CalcRadTemp CalcRainCollector CalcReformEIRChillerModel CalcResearchSpecialPartLoad CalcReturnAirPath CalcRfFlrCoordinateTransformation CalcSandiaPV CalcSatVapPressFromTemp CalcSchedOffSysAvailMgr CalcSchedOnSysAvailMgr CalcSchedSysAvailMgr CalcScheduledDualSetPoint CalcScheduledSetPoint CalcScreenTransmittance CalcScriptF CalcSeriesPIU CalcSetpointTempTarget CalcSHRUserDefinedCurves CalcSimpleController CalcSimpleHeatingCoil CalcSimplePV CalcSingleSpeedEvapFluidCooler CalcSingleSpeedTower CalcSingZoneClSetPoint CalcSingZoneHtSetPoint CalcSingZoneMaxHumSetPoint CalcSingZoneMinHumSetPoint CalcSingZoneRhSetPoint CalcSkySolDiffuseReflFactors CalcSolarCollector CalcSolarFlux CalcSolidDesiccantDehumidifier CalcSourceFlux CalcSourceTempCoefficents CalcSparrowLeeward CalcSparrowWindward CalcSpecialDayTypes CalcStandAloneERV CalcStandardRatings CalcStaticProperties CalcSteamAirCoil CalcSteamBaseboard CalcSurfaceCentroid CalcSurfaceGroundHeatExchanger CalcSystemEnergyUse CalcSZOneStageCoolingSetPt CalcSZOneStageHeatingSetPt CalcTankTemp CalcTDDTransSolAniso CalcTDDTransSolHorizon CalcTDDTransSolIso CalcTempDistModel CalcTempIntegral CalcTESCoilChargeOnlyMode CalcTESCoilCoolingAndChargeMode CalcTESCoilCoolingAndDischargeMode CalcTESCoilCoolingOnlyMode CalcTESCoilDischargeOnlyMode CalcTESCoilOffMode CalcTESIceStorageTank CalcTESWaterStorageTank CalcThermalChimney CalcThermalComfortAdaptiveASH55 CalcThermalComfortAdaptiveCEN15251 CalcThermalComfortFanger CalcThermalComfortKSU CalcThermalComfortPierce CalcThermalComfortSimpleASH55 CalcTimeNeeded CalcTopFluxCoefficents CalcTopSurfTemp CalcTotalFLux CalcTotCapSHR CalcTotCapSHR_VSWSHP CalcTransAbsorProduct CalcTransRefAbsOfCover CalcTRNSYSPV CalcTrombeWallIntConvCoeff CalcTwoSpeedDXCoilIEERResidual CalcTwoSpeedDXCoilStandardRating CalcTwoSpeedEvapFluidCooler CalcTwoSpeedTower CalcUAIce CalcUCSDCV CalcUCSDDV CalcUCSDUE CalcUCSDUI CalculateAirChillerSets CalculateBasisLength CalculateCase CalculateCoil CalculateCompressors CalculateCondensers CalculateCTFs CalculateDailySolarCoeffs CalculateDayOfWeek CalculateEpsFromNTUandZ CalculateExponentialMatrix CalculateFuncResults CalculateGammas CalculateInverseMatrix CalculateMoodyFrictionFactor CalculateNTUfromEpsAndZ CalculatePollution CalculateSecondary CalculateSubcoolers CalculateSunDirectionCosines CalculateTransCompressors CalculateWalkIn CalculateWaterUseage CalculateWaterUseage CalculateWindowBeamProperties CalculateZoneMRT CalculateZoneVolume CalcUnitaryCoolingSystem CalcUnitaryHeatingSystem CalcUnitarySuppHeatingSystem CalcUnitarySuppSystemtoSP CalcUnitarySystemLoadResidual CalcUnitarySystemToLoad CalcUnitHeater CalcUnitHeaterComponents CalcUnitVentilator CalcUnitVentilatorComponents CalcUnmetPlantDemand CalcUpdateHeatRecovery CalcUpdateHeatRecovery CalcUserDefinedInsideHcModel CalcUserDefinedOutsideHcModel CalcVariableSpeedTower CalcVarSpeedCoilCooling CalcVarSpeedCoilHeating CalcVarSpeedHeatPump CalcVarSpeedHeatPump CalcVAVVS CalcVentilatedSlab CalcVentilatedSlabComps CalcVentilatedSlabRadComps CalcVentSlabHXEffectTerm CalcVerticalGroundHeatExchanger CalcViewFactorToShelf CalcVRF CalcVRFCondenser CalcVRFCoolingCoil CalcVSTowerApproach CalcWallCoordinateTransformation CalcWaltonStableHorizontalOrTilt CalcWaltonUnstableHorizontalOrTilt CalcWarmestSetPoint CalcWarmestSetPointTempFlow CalcWaterMainsTemp CalcWaterSource CalcWaterStorageTank CalcWaterThermalTankMixed CalcWaterThermalTankStratified CalcWaterThermalTankZoneGains CalcWaterToAirHeatpump CalcWatertoAirHPCooling CalcWatertoAirHPHeating CalcWaterToAirResidual CalcWatertoWaterHPCooling CalcWatertoWaterHPHeating CalcWaterUseZoneGains CalcWetIndirectEvapCooler CalcWindowACOutput CalcWindowBlindProperties CalcWindowHeatBalance CalcWindowProfileAngles CalcWindowScreenProperties CalcWindowStaticProperties CalcWindPressure CalcWindPressureCoeffs CalcWindTurbine CalcWinFrameAndDividerTemps CalcWinTransDifSolInitialDistribution CalcWrapperModel CalcZoneAirComfortSetpoints CalcZoneAirTempSetpoints CalcZoneComponentLoadSums CalcZoneDehumidifier CalcZoneEvaporativeCoolerUnit CalcZoneLeavingConditions CalcZoneMassBalance CalcZonePipesHeatGain CalcZoneSums CartesianPipeCellInformation_ctor CellType_IsFieldCell CFSHasControlledShade CFSNGlz CFSRefPointPosFactor CFSRefPointSolidAngle CFSShadeAndBeamInitialization CFSUFactor cGetCoilAirOutletNode cGetCoilSteamInletNode cGetCoilSteamOutletNode CharPreDefTableEntry CheckActuatorNode CheckAndAddAirNodeNumber CheckAndFixCFSLayer CheckAndReadCustomSprectrumData CheckAndReadFaults CheckAndSetConstructionProperties CheckBracketRoundOff CheckBranchForOASys CheckCachedIPErrors CheckCFSStates CheckCoilWaterInletNode CheckControllerListOrder CheckControllerLists CheckConvexity CheckCostEstimateInput CheckCreatedZoneItemName CheckCurveLimitsForIPLV CheckCurveLimitsForStandardRatings CheckDayScheduleValueMinMax CheckDXCoolingCoilInOASysExists CheckFDSurfaceTempLimits CheckFFSchedule CheckFluidPropertyName CheckForActualFileName CheckForBalancedFlow CheckForControllerWaterCoil CheckForGeometricTransform CheckForGeometricTransform CheckForMisMatchedEnvironmentSpecifications CheckForOutOfRangeTempResult CheckForOutOfRangeTemps CheckForRequestedReporting CheckForRunawayPlantTemps CheckForSensorAndSetpointNode CheckGasCoefs CheckHeatingCoilSchedule CheckHXAssistedCoolingCoilSchedule CheckIFAnyEMS CheckIFAnyIdealCondEntSetPoint CheckIfAnyPlant CheckIfNodeSetpointManagedByEMS CheckIncrementRoundOff CheckInternalConsistency CheckLightsReplaceableMinMaxForZone CheckLocationValidity CheckLoopExitNode CheckLowerUpperBracket CheckMarkedNodes CheckMaxActiveController CheckMaxConstraint CheckMicroCHPThermalBalance CheckMinActiveController CheckMinConstraint checkMinimumMonthlyCharge CheckMinMaxCurveBoundaries CheckMinMaxRange CheckModelBoundOutput_HumRat CheckModelBoundOutput_Temp CheckModelBounds CheckModelBoundsHumRatEq CheckModelBoundsRH_HumRatEq CheckModelBoundsRH_TempEq CheckModelBoundsTempEq CheckNodeConnections CheckNodeSetPoint CheckNonSingularity CheckOAControllerName CheckOutAirNodeNumber CheckPlantConvergence CheckPlantMixerSplitterConsistency CheckPlantOnAbort CheckPollutionMeterReporting CheckRefrigerationInput CheckReportVariable CheckRootFinderCandidate CheckRootFinderConvergence CheckScheduledSurfaceGains CheckScheduleValue CheckScheduleValueMinMax Checksetpoints CheckSimpleController CheckSlope CheckSteamCoilSchedule CheckSubSurfaceMiscellaneous CheckSysSizing CheckSystemBranchFlow CheckTDDsAndLightShelvesInDaylitZones CheckThisAirSystemForSizing CheckThisZoneForSizing CheckThreading CheckUniqueNodes CheckUnitarySysCoilInOASysExists CheckUsedConstructions CheckValidSimulationObjects CheckWarmupConvergence CheckWaterCoilSchedule CheckWeatherFileValidity CheckWindowShadingControlFrameDivider CheckZoneEquipmentList CheckZoneSizing CHKBKS CHKGSS CHKSBS CLIP CLIPPOLY CloseDFSFile CloseMiscOpenFiles CloseMoistureBalanceEMPD CloseOutOpenFiles CloseOutputFiles CloseOutputTabularFile CloseReportIllumMaps CloseSocket CloseWeatherFile CoilAreaFracIter CoilCompletelyDry CoilCompletelyWet CoilOutletStreamCondition CoilPartWetPartDry COMMAND_ARGUMENT_COUNT CompactObjectsCheck CompareTwoVectors ComplexFenestrationLuminances ComputeDelayedComponents ComputeDifSolExcZonesWIZWindows ComputeIntSolarAbsorpFactors ComputeIntSWAbsorpFactors ComputeIntThermalAbsorpFactors ComputeLifeCycleCostAndReport ComputeLoadComponentDecayCurve ComputeNominalUwithConvCoeffs ComputePresentValue ComputeTariff ComputeTaxAndDepreciation ComputeWinShadeAbsorpFactors CondOutTempResidual ConstructBasis ControlCBVAVOutput ControlCompOutput ControlCompOutput ControlCoolBeam ControlCoolingSystem ControlCycWindACOutput ControlDesiccantDehumidifier ControlDXHeatingSystem ControlDXSystem ControlFluidHeatExchanger ControlHeatingSystem ControlHumidifier ControlMSHPOutput ControlPTUnitOutput ControlPVTcollector ControlReformEIRChillerModel ControlSuppHeatSystem ControlUnitarySystemOutput ControlUnitarySystemtoLoad ControlUnitarySystemtoSP ControlVRF ControlVSEvapUnitToMeetLoad ControlVSHPOutput ControlVSHPOutput ConvectionFactor ConvertCasetoLower ConvertCasetoUpper ConvertIP ConvertIPdelta ConvertToElementTag ConvertToEscaped CoolBeamResidual CoolingCoil CoolWaterHumRatResidual CoolWaterTempResidual CoolWatertoAirHPHumRatResidual CoolWatertoAirHPTempResidual CorrectZoneAirTemp CorrectZoneContaminants CorrectZoneHumRat CostInfoOut CPCW CPHW CreateBoundaryList CreateBoundaryListCount CreateCategoryNativeVariables CreateCellArray CreateCurrentDateTimeString CreateDefaultComputation CreateEnergyReportStructure CreateFCfactorConstructions CreateHVACStepFullString CreateHVACTimeIntervalString CreateHVACTimeString CreateNewellAreaVector CreateNewellSurfaceNormalVector CreatePartitionCenterList CreatePartitionRegionList CreatePredefinedMonthlyReports CreateRegionList CreateRegionListCount CreateShadedWindowConstruction CreateSQLiteConstructionsTable CreateSQLiteConstructionsTable CreateSQLiteDatabase CreateSQLiteDatabase CreateSQLiteDaylightMap CreateSQLiteDaylightMap CreateSQLiteDaylightMapTitle CreateSQLiteDaylightMapTitle CreateSQLiteEnvironmentPeriodRecord CreateSQLiteEnvironmentPeriodRecord CreateSQLiteErrorRecord CreateSQLiteErrorRecord CreateSQLiteInfiltrationTable CreateSQLiteInfiltrationTable CreateSQLiteMaterialsTable CreateSQLiteMaterialsTable CreateSQLiteMeterDictionaryRecord CreateSQLiteMeterDictionaryRecord CreateSQLiteMeterRecord CreateSQLiteMeterRecord CreateSQLiteNominalBaseboardHeatTable CreateSQLiteNominalBaseboardHeatTable CreateSQLiteNominalElectricEquipmentTable CreateSQLiteNominalElectricEquipmentTable CreateSQLiteNominalGasEquipmentTable CreateSQLiteNominalGasEquipmentTable CreateSQLiteNominalHotWaterEquipmentTable CreateSQLiteNominalHotWaterEquipmentTable CreateSQLiteNominalLightingTable CreateSQLiteNominalLightingTable CreateSQLiteNominalOtherEquipmentTable CreateSQLiteNominalOtherEquipmentTable CreateSQLiteNominalPeopleTable CreateSQLiteNominalPeopleTable CreateSQLiteNominalSteamEquipmentTable CreateSQLiteNominalSteamEquipmentTable CreateSQLiteReportVariableDataRecord CreateSQLiteReportVariableDataRecord CreateSQLiteReportVariableDictionaryRecord CreateSQLiteReportVariableDictionaryRecord CreateSQLiteRoomAirModelTable CreateSQLiteRoomAirModelTable CreateSQLiteSchedulesTable CreateSQLiteSimulationsRecord CreateSQLiteSimulationsRecord CreateSQLiteStringTableRecord CreateSQLiteSurfacesTable CreateSQLiteSurfacesTable CreateSQLiteTabularDataRecords CreateSQLiteTabularDataRecords CreateSQLiteTimeIndexRecord CreateSQLiteTimeIndexRecord CreateSQLiteVentilationTable CreateSQLiteVentilationTable CreateSQLiteZoneGroupTable CreateSQLiteZoneGroupTable CreateSQLiteZoneListTable CreateSQLiteZoneListTable CreateSQLiteZoneTable CreateSQLiteZoneTable CreateStormWindowConstructions CreateSysTimeIntervalString CreateTCConstructions CreateTimeIntervalString CreateTimeString CreatExtBooundCondName CreateZoneExtendedOutput CreateZoneExtendedOutput CrossProduct CrossProduct cSurfaceClass CTRANS CurveValue DateToString DateToStringWithMonth DaylghtAltAndAzimuth DayltgAveInteriorReflectance DayltgClosestObstruction DayltgCrossProduct DayltgCurrentExtHorizIllum DayltgDirectIllumComplexFenestration DayltgDirectSunDiskComplexFenestration DayltgElecLightingControl DayltgExtHorizIllum DayltgGlare DayltgGlarePositionFactor DayltgGlareWithIntWins DayltgHitBetWinObstruction DayltgHitInteriorObstruction DayltgHitObstruction DayltgInteriorIllum DayltgInteriorMapIllum DayltgInteriorTDDIllum DayltgInterReflectedIllum DayltgInterReflectedIllumComplexFenestration DayltgInterReflIllFrIntWins DayltgLuminousEfficacy DayltgPierceSurface DayltgSetupAdjZoneListsAndPointers DayltgSkyLuminance DayltgSurfaceLumFromSun dCheckScheduleValueMinMax1 dCheckScheduleValueMinMax2 DeallocateLoadComponentArrays DebugRootFinder DecodeHHMMField DecodeMonDayHrMin DeflectionTemperatures DeflectionWidths DegradF DElightDaylightCoefficients DElightDaylightCoefficients DElightElecLtgCtrl DElightElecLtgCtrl DElightFreeMemory DElightFreeMemory DElightInputGenerator DElightInputGenerator DElightOutputGenerator DElightOutputGenerator DensityCFSFillGas Depth DERIV DetailsForSurfaces DetectOscillatingZoneTemp DetermineAzimuthAndTilt DetermineBranchFlowRequest DetermineBuildingFloorArea DetermineDateTokens DetermineFrequency DetermineIndexGroupFromMeterGroup DetermineIndexGroupKeyFromMeterName DetermineMaxBackSurfaces DetermineMeterIPUnits DetermineMinuteForReporting DeterminePolygonOverlap DetermineShadowingCombinations DetermineSunUpDown DevelopMesh DiffuseAverage DiffuseAverageProfAngGnd DiffuseAverageProfAngSky DisplayMaterialRoughness DisplayNumberandString DisplaySimDaysProgress DisplayString distance DistributeBBElecRadGains DistributeBBRadGains DistributeBBSteamRadGains DistributeHTRadGains DistributePlantLoad DistributePressureOnBranch DistributeTDDAbsorbedSolar DistributeUserDefinedPlantLoad DL_RES_r2 DLAG DOE2DXCoilHumRatResidual DOE2DXCoilHumRatResidual DOE2DXCoilResidual DOE2DXCoilResidual DOE2DXCoilResidual DoEndOfIterationOperations DomainRectangle_Contains DOMakeUPPERCase DoOneTimeInitializations DOSameString DoShadeControl DoStartOfTimeStepInitializations DownInterpolate4HistoryValues DumpAirLoopStatistics DumpCurrentLineBuffer DUMPVD DUMPVR DXCoilCyclingHumRatResidual DXCoilCyclingHumRatResidual DXCoilCyclingResidual DXCoilCyclingResidual DXCoilVarSpeedHumRatResidual DXCoilVarSpeedHumRatResidual DXCoilVarSpeedResidual DXCoilVarSpeedResidual DXFOut DXFOutLines DXFOutWireFrame DXHeatingCoilResidual DXHeatingCoilResidual DXHeatingCoilResidual DynamicClothingModel DynamicExtConvSurfaceClassification DynamicIntConvSurfaceClassification EchoOutActuatorKeyChoices EchoOutInternalVariableChoices EffectiveEPSLB EffectiveEPSLF EIRChillerHeatRecovery EN673ISO10292 EncodeMonDayHrMin EndEnergyPlus EndUniqueNodeCheck EnthalpyResidual epElapsedTime epGetTimeUsed epGetTimeUsedperCall epStartTime epStopTime epSummaryTimes eptime EQLWindowInsideEffectiveEmiss EQLWindowOutsideEffectiveEmiss EQLWindowSurfaceHeatBalance EquationsSolver ERF EstimateHEXSurfaceArea EvalInsideMovableInsulation EvalOutsideMovableInsulation EvaluateAdiabaticSurfaceTemperature EvaluateBasementCellTemperature EvaluateCellNeighborDirections evaluateChargeBlock evaluateChargeSimple EvaluateExpression EvaluateExtHcModels EvaluateFarfieldBoundaryTemperature EvaluateFarfieldCharacteristics EvaluateFieldCellTemperature EvaluateGroundSurfaceTemperature EvaluateIntHcModels EvaluateLoopSetPointLoad EvaluateNeighborCharacteristics evaluateQualify evaluateRatchet EvaluateSoilRhoCp EvaluateStack EvolveParaUCSDCV ExitCalcController ExpandComplexState ExpressAsCashFlows ExtendObjectDefinition ExteriorBCEqns ExternalInterfaceExchangeVariables ExternalInterfaceInitializeErlVariable ExternalInterfaceSetErlVariable ExternalInterfaceSetSchedule ExtOrIntShadeNaturalFlow Fabric_EstimateDiffuseProps FACSKY FalsePositionMethod FEQX FI FigureACAncillaries FigureAirEnthalpy FigureAirHeatCap FigureAuxilHeatGasHeatCap FigureBeamSolDiffuseReflFactors FigureBeamSolSpecularReflFactors FigureConstGradPattern FigureDayltgCoeffsAtPointsForSunPosition FigureDayltgCoeffsAtPointsForWindowElements FigureDayltgCoeffsAtPointsSetupForWindow FigureElectricalStorageZoneGains FigureFuelCellZoneGains FigureFuelEnthalpy FigureFuelHeatCap FigureGaseousWaterEnthalpy FigureHeightPattern FigureHXleavingGasHeatCap FigureInverterZoneGains FigureLHVofFuel FigureLiquidWaterEnthalpy FigureLiquidWaterHeatCap FigureMapPointDayltgFactorsToAddIllums FigureMicroCHPZoneGains FigureNDheightInZone FigurePowerConditioningLosses FigureProductGasesEnthalpy FigureProductGasHeatCap FigureRefPointDayltgFactorsToAddIllums FigureRefrigerationZoneGains FigureSolarBeamAtTimestep FigureSunCosines FigureSurfMapPattern FigureTDDZoneGains FigureTransformerZoneGains FigureTransientConstraints FigureTwoGradInterpPattern FILJAC FillBasisElement FillDefaultsSWP FillRemainingPredefinedEntries FillWeatherPredefinedEntries film filmg filmi filmPillar FILSKY FinalizeCFS FinalizeCFSLAYER FinalRateCoils FindAirLoopBranchConnection FindAirPlantCondenserLoopFromBranchList FindAllNumbersinList FindArrayIndex FindCompSPInput FindCompSPLoad FindCondenserLoopBranchConnection FindControlledZoneIndexFromSystemNodeNumberForZone FindDeltaTempRangeInput FindDemandSideMatch FindEMSVariable FindFirstLastPtr FindFirstRecord FindGlycol FindHXDemandSideLoopFlow FindInBasis FindItem FindIteminList FindIteminSortedList FindItemInVariableList FindLoopSideInCallingOrder FindNextRecord FindNonSpace FindNumberinList FindOAMixerMatchForOASystem FindPlantLoopBranchConnection FindRangeBasedOrUncontrolledInput FindRangeVariable FindRefrigerant FindRootSimpleController FindStratifiedTankSensedTemp FindTariffIndex FindTDDPipe FindUnitNumber FinishDebugOutputFiles FixViewFactors FluidCellInformation_ctor FM_BEAM FM_DIFF FM_F FNU forcedventilation FourPipeInductionUnitHasMixer FourPipeIUCoolingResidual FourPipeIUHeatingResidual FRA FrostControl FrostControlSetPointLimit FrostControlSetPointLimit FuelCellProductGasEnthResidual FUN FuncDetermineCoolantWaterExitTemp FuncDetermineCWMdotForInternalFlowControl FuncDetermineEngineTemp FV GasElecHeatingCoilResidual GASSES90 GassesLow GatherBEPSResultsForTimestep GatherBinResultsForTimestep GatherComponentLoadsHVAC GatherComponentLoadsIntGain GatherComponentLoadsSurfAbsFact GatherComponentLoadsSurface GatherForEconomics GatherForPredefinedReport GatherHeatGainReport GatherMonthlyResultsForTimestep GatherPeakDemandForTimestep GatherSourceEnergyEndUseResultsForTimestep GaussElimination generate_ears GenerateDElightDaylightCoefficients GenerateDElightDaylightCoefficients GeneratorPowerOutput GenericCrack GenOutputVariablesAuditReport Get2DMatrix Get2DMatrixDimensions GET_COMMAND GET_COMMAND_ARGUMENT Get_Environment_Variable GetActualDXCoilIndex GetAirBranchIndex GetAirFlowFlag GetAirflowNetworkInput GetAirHeatBalanceInput GetAirLoopAvailabilityManager GetAirModelDatas GetAirNodeData GetAirPathData GetAngleFactorList GetATMixer GetATMixerOutNode GetATMixerPriNode GetATMixers GetATMixerSecNode GetAttShdSurfaceData GetAverageTempByType GetBaseboardInput GetBaseboardInput GetBasementFloorHeatFlux GetBasementWallHeatFlux GetBLASTAbsorberInput GetBoilerInput GetBoilerInput GetBranchData GetBranchFanTypeName GetBranchFlow GetBranchInput GetBranchList GetBranchListInput GetBuildingData GetCBVAV GetCellWidths GetCellWidthsCount GetChildrenData GetChillerheaterInput GetCoilAirFlowRate GetCoilAirFlowRateVariableSpeed GetCoilAirInletNode GetCoilAirOutletNode GetCoilAvailScheduleIndex GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacityByIndexType GetCoilCapacityVariableSpeed GetCoilCondenserInletNode GetCoilControlNodeNum GetCoilGroupTypeNum GetCoilIndex GetCoilIndex GetCoilIndex GetCoilIndexVariableSpeed GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNodeVariableSpeed GetCoilMaxSteamFlowRate GetCoilMaxWaterFlowRate GetCoilMaxWaterFlowRate GetCoilMaxWaterFlowRate GetCoilObjectTypeNum GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNodeVariableSpeed GetCoilSteamInletNode GetCoilSteamOutletNode GetCoilTypeNum GetCoilWaterInletNode GetCoilWaterInletNode GetCoilWaterOutletNode GetColumnUsingTabs GetComfortSetpoints GetComponentData GetCondFDInput GetConductivityGlycol GetConnectorList GetConnectorListInput GetConstCOPChillerInput GetConstructData GetControlledZoneIndex GetControllerActuatorNodeNum GetControllerInput GetCoolBeams GetCoolingCoilTypeNameAndIndex GetCooltower GetCostEstimateInput GetCrossVentData GetCTGeneratorInput GetCTGeneratorResults GetCurrentHVACTime GetCurrentMeterValue GetCurrentScheduleValue GetCurveCheck GetCurveIndex GetCurveInput GetCurveMinMaxValues GetCurveName GetCurveObjectTypeNum GetCurveType GetCustomMeterInput GetDaylightingParametersDetaild GetDaylightingParametersInput GetDayScheduleIndex GetDemandManagerInput GetDemandManagerListInput GetDensityGlycol GetDesiccantDehumidifierInput GetDesignDayData GetDesignLightingLevelForZone GetDetShdSurfaceData GetDirectAirInput GetDisplacementVentData GetDSTData GetDualDuctInput GetDualDuctOutdoorAirRecircUse GetDuctInput GetDXCoilAirFlow GetDXCoilAvailSchPtr GetDXCoilBypassedFlowFrac GetDXCoilCapFTCurveIndex GetDXCoilIndex GetDXCoilNumberOfSpeeds GetDXCoils GetDXCoolingSystemInput GetDXHeatPumpSystemInput GetEarthTube GetElecReformEIRChillerInput GetElectricBaseboardInput GetElectricChillerInput GetElectricEIRChillerInput GetEMSInput GetEngineDrivenChillerInput GetEnvironmentalImpactFactorInfo GetEvapFluidCoolerInput GetEvapInput GetExhaustAbsorberInput GetExhaustAirInletNode GetExteriorEnergyUseInput GetExtVentedCavityIndex GetExtVentedCavityIndex GetExtVentedCavityTsColl GetExtVentedCavityTsColl GetFanAvailSchPtr GetFanCoilIndex GetFanCoilInletAirNode GetFanCoilMixedAirNode GetFanCoilOutAirNode GetFanCoilReturnAirNode GetFanCoilUnits GetFanCoilZoneInletAirNode GetFanDesignVolumeFlowRate GetFanIndex GetFanIndexForTwoSpeedCoil GetFanInletNode GetFanInput GetFanOutletNode GetFanPower GetFanSpeedRatioCurveIndex GetFanType GetFanVolFlow GetFarfieldTemp GetFirstBranchInletNodeName GetFluidCoolerInput GetFluidDensityTemperatureLimits GetFluidHeatExchangerInput GetFluidPropertiesData GetFluidSpecificHeatTemperatureLimits GetFrameAndDividerData GetFuelCellGeneratorInput GetFuelCellGeneratorResults GetFuelFactorInfo GetFurnaceInput GetGasAbsorberInput GetGeneratorFuelSupplyInput GetGeometryParameters GetGlycolNameByIndex GetGroundheatExchangerInput GetGroundReflectances GetGroundTemps GetGshpInput GetGshpInput GetGTChillerInput GetHeatBalanceInput GetHeatBalHAMTInput GetHeatExchangerObjectTypeNum GetHeatingCoilIndex GetHeatingCoilInput GetHeatingCoilNumberOfStages GetHeatingCoilPLFCurveIndex GetHeatingCoilTypeNum GetHeatReclaimSourceIndex GetHeatRecoveryInput GetHighTempRadiantSystem GetHPCoolingCoilIndex GetHTSubSurfaceData GetHTSurfaceData GetHTSurfExtVentedCavityData GetHumidifierInput GetHVACSingleDuctSysIndex GetHWBaseboardInput GetHXAssistedCoolingCoilInput GetHXCoilAirFlowRate GetHXCoilType GetHXCoilTypeAndName GetHXDXCoilIndex GetHXDXCoilName GetHybridVentilationControlStatus GetHybridVentilationInputs GetICEGeneratorResults GetICEngineGeneratorInput GetIceStorageInput GetIDFRecordsStats GetIndirectAbsorberInput GetIndUnits GetInputEconomicsChargeBlock GetInputEconomicsChargeSimple GetInputEconomicsComputation GetInputEconomicsCurrencyType GetInputEconomicsQualify GetInputEconomicsRatchet GetInputEconomicsTariff GetInputEconomicsVariable GetInputForLifeCycleCost GetInputFuelAndPollutionFactors GetInputLifeCycleCostNonrecurringCost GetInputLifeCycleCostParameters GetInputLifeCycleCostRecurringCosts GetInputLifeCycleCostUseAdjustment GetInputLifeCycleCostUsePriceEscalation GetInputTabularMonthly GetInputTabularPredefined GetInputTabularStyle GetInputTabularTimeBins GetInputViewFactors GetInputViewFactorsbyName GetInputZoneEvaporativeCoolerUnit GetInstantMeterValue GetInternalBranchData GetInternalHeatGainsInput GetInternalVariableValue GetInternalVariableValue GetInternalVariableValueExternalInterface GetInternalVariableValueExternalInterface GetInterpolatedSatProp GetInterpValue GetIntMassSurfaceData GetLastBranchOutletNodeName GetLastWord GetLightWellData GetListOfObjectsInIDD GetListofSectionsinInput GetLocationInfo GetLoopMixer GetLoopSidePumpIndex GetLoopSplitter GetLowTempRadiantSystem GetMaterialData GetMatrixInput getMaxAndSum GetMeteredVariables GetMeterIndex GetMeterResourceType GetMicroCHPGeneratorInput GetMicroCHPGeneratorResults GetMinOATCompressor GetMixerInput GetMixerInput GetMoistureBalanceEMPDInput GetMonthlyCostForResource GetMovableInsulationData GetMSHeatPumpInput GetMTGeneratorExhaustNode GetMTGeneratorInput GetMTGeneratorResults GetMundtData GetNewUnitNumber GetNextEnvironment GetNodeConnectionType GetNodeList GetNodeListsInput GetNodeNums GetNTUforCrossFlowBothUnmixed GetNumberOfSchedules GetNumberOfSurfaceLists GetNumberOfSurfListVentSlab GetNumChildren GetNumMeteredVariables GetNumOAControllers GetNumOAMixers GetNumOASystems GetNumObjectsFound GetNumObjectsInIDD GetNumRangeCheckErrorsFound GetNumSectionsFound GetNumSectionsinInput GetNumSegmentsForHorizontalTrenches GetNumSplitterMixerInConntrList GetOACompListNumber GetOACompName GetOACompType GetOACompTypeNum GetOAControllerInputs GetOAMixerIndex GetOAMixerInletNodeNumber GetOAMixerInputs GetOAMixerMixedNodeNumber GetOAMixerNodeNumbers GetOAMixerReliefNodeNumber GetOAMixerReturnNodeNumber GetOARequirements GetOASysControllerListIndex GetOASysNumCoolingCoils GetOASysNumHeatingCoils GetOASysNumSimpControllers GetOASystemNumber GetObjectDefInIDD GetObjectDefMaxArgs GetObjectItem GetObjectItemfromFile GetObjectItemNum GetOnlySingleNode GetOperationSchemeInput GetOSCData GetOSCMData GetOutAirNodesInput GetOutdoorAirUnitInputs GetOutdoorAirUnitOutAirNode GetOutdoorAirUnitReturnAirNode GetOutdoorAirUnitZoneInletNode GetOutsideAirSysInputs GetOutsideEnergySourcesInput GetParentData GetPipeInput GetPipesHeatTransfer GetPipingSystemsInput GetPIUs GetPlantAvailabilityManager GetPlantInput GetPlantLoopData GetPlantOperationInput GetPlantProfileInput GetPlantSizingInput GetPlantValvesInput GetPollutionFactorInput GetPondGroundHeatExchanger GetPowerManagerInput GetPressureCurveTypeAndIndex GetPressureSystemInput GetPreviousHVACTime GetProjectControlData GetProjectData GetPTUnit GetPTUnitMixedAirNode GetPTUnitOutAirNode GetPTUnitReturnAirNode GetPTUnitZoneInletAirNode GetPumpInput GetPurchasedAir GetPurchasedAirMixedAirHumRat GetPurchasedAirMixedAirTemp GetPurchasedAirOutAirMassFlow GetPurchasedAirReturnAirNode GetPurchasedAirZoneInletAirNode GetPVGeneratorResults GetPVInput GetPVTcollectorsInput GetPVTThermalPowerProduction GetQualityRefrig GetRecordLocations GetRectDetShdSurfaceData GetRectSubSurfaces GetRectSurfaces GetRefrigeratedRackIndex GetRefrigerationInput GetReportVariableInput GetRequiredMassFlowRate GetResidCrossFlowBothUnmixed GetResourceTypeChar GetReturnAirNodeForZone GetReturnAirPathInput GetRoomAirModelParameters GetRunPeriodData GetRunPeriodDesignData GetRuntimeLanguageUserInput GetSatDensityRefrig GetSatEnthalpyRefrig GetSatPressureRefrig GetSatSpecificHeatRefrig GetSatTemperatureRefrig GetScheduledSurfaceGains GetScheduleIndex GetScheduleMaxValue GetScheduleMinValue GetScheduleName GetScheduleType GetScheduleValuesForDay GetSecondaryInletNode GetSecondaryOutletNode GetSetPointManagerInputs GetShadingSurfReflectanceData GetShadowingInput GetShelfInput GetSimpleAirModelInputs GetSimpleShdSurfaceData GetSimpleWatertoAirHPInput GetSingleDayScheduleValues GetSiteAtmosphereData GetSizingParams GetSnowGroundRefModifiers GetSolarCollectorInput GetSpecialDayPeriodData GetSpecificHeatGlycol getSpecificUnitDivider getSpecificUnitIndex getSpecificUnitMultiplier GetSplitterInput GetSplitterInput GetSplitterNodeNumbers GetSplitterOutletNumber GetStandAloneERV GetStandAloneERVNodes GetStandAloneERVOutAirNode GetStandAloneERVReturnAirNode GetStandAloneERVZoneInletAirNode GetStandardMeterResourceType GetSteamBaseboardInput GetSteamCoilAvailScheduleIndex GetSteamCoilControlNodeNum GetSteamCoilIndex GetSteamCoilInput GetSTM GetStormWindowData GetSupHeatDensityRefrig GetSupHeatEnthalpyRefrig GetSupHeatPressureRefrig GetSupplyAirFlowRate GetSupplyAirFlowRate GetSupplyAirInletNode GetSupplyInletNode GetSupplyOutletNode GetSurfaceCountForOSCM GetSurfaceData GetSurfaceGroundHeatExchanger GetSurfaceHeatTransferAlgorithmOverrides GetSurfaceIndecesForOSCM GetSurfaceListsInputs GetSurfHBDataForMundtModel GetSurfHBDataForTempDistModel GetSysAvailManagerInputs GetSysAvailManagerListInputs GetSysInput GetSystemNodeNumberForZone GetSystemSizingInput GetTDDInput GetTESCoilIndex GetTESCoilInput GetThermalChimney GetTowerInput GetTranspiredCollectorIndex GetTranspiredCollectorInput GetTypeOfCoil GetUFADZoneData GetUnitarySystemDXCoolingCoilIndex GetUnitarySystemInput GetUnitarySystemOAHeatCoolCoil GetUnitConversion GetUnitHeaterInput GetUnitsString GetUnitSubString GetUnitVentilatorInput GetUnitVentilatorMixedAirNode GetUnitVentilatorOutAirNode GetUnitVentilatorReturnAirNode GetUnitVentilatorZoneInletAirNode GetUserConvectionCoefficients GetUserDefinedComponents GetUserDefinedOpSchemeInput GetUserDefinedPatternData GetUTSCTsColl GetVariableKeyCountandType GetVariableKeyCountandType GetVariableKeys GetVariableKeys GetVariableTypeAndIndex GetVariableUnitsString GetVarSpeedCoilInput GetVentilatedSlabInput GetVertices GetViscosityGlycol GetVRFInput GetVSCoilCondenserInletNode GetVSCoilMinOATCompressor GetVSCoilNumOfSpeeds GetWaterCoilAvailScheduleIndex GetWaterCoilCapacity GetWaterCoilIndex GetWaterCoilInput GetWaterMainsTemperatures GetWaterManagerInput GetWaterSource GetWaterThermalTankInput GetWatertoAirHPInput GetWatertoWaterHPInput GetWaterUseInput GetWeatherProperties GetWeatherStation GetWindowAC GetWindowACMixedAirNode GetWindowACOutAirNode GetWindowACReturnAirNode GetWindowACZoneInletAirNode GetWindowGapAirflowControlData GetWindowGlassSpectralData GetWindowShadingControlData GetWindTurbineInput GetWrapperInput GetWTGeneratorResults GetZoneAirDistribution GetZoneAirLoopEquipment GetZoneAirSetpoints GetZoneAndZoneListNames GetZoneContaminanInputs GetZoneContaminanSetpoints GetZoneData GetZoneDehumidifierInput GetZoneDehumidifierNodeNumber GetZoneEqAvailabilityManager GetZoneEquipment GetZoneEquipmentData GetZoneEquipmentData1 GetZoneInfilAirChangeRate GetZoneLoads GetZonePlenumInput GetZoneSizingInput GLtoAMB GoAhead guess HasFractionalScheduleValue hatter HCInWindowStandardRatings HConvGap HcUCSDCV HcUCSDDV HcUCSDUF HeatingCoilVarSpeedCycResidual HeatingCoilVarSpeedResidual HeatPumpRunFrac HeatPumpRunFrac HeatPumpRunFrac HeatWatertoAirHPTempResidual Height HEMINT HIC_ASHRAE HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterHeatingCoilResidual HRadPar HTRANS HTRANS0 HTRANS1 HWBaseboardUAResidual HXAssistDXCoilResidual HXAssistedCoolCoilHRResidual HXAssistedCoolCoilHRResidual HXAssistedCoolCoilTempResidual HXAssistedCoolCoilTempResidual HXDemandSideLoopFlowResidual HybridVentilationControl IAM iCheckScheduleValue ICSCollectorAnalyticalSoluton iGetCoilAirOutletNode iGetCoilSteamInletNode iGetCoilSteamOutletNode INCLOS incrementEconVar IncrementInstMeterCache incrementSteps incrementTableEntry InitAirflowNetwork InitAirflowNetworkData InitAirHeatBalance InitAirLoops InitAirLoopSplitter InitAirMixer InitAirTerminalUserDefined InitAirZoneReturnPlenum InitAirZoneSupplyPlenum InitATMixer InitBaseboard InitBaseboard InitBLASTAbsorberModel InitBoiler InitBoiler InitBoreholeHXSimVars InitBSDFWindows InitCBVAV InitCoilUserDefined InitComplexWindows InitComponentNodes InitConductionTransferFunctions InitConnections InitConstCOPChiller InitController InitCoolBeam InitCTGenerators InitCurveReporting InitDaylightingDevices InitDemandManagers InitDesiccantDehumidifier InitDetailedIceStorage InitDirectAir InitDualDuct InitDuct InitDXCoil InitDXCoolingSystem InitDXHeatPumpSystem InitElecReformEIRChiller InitElectricBaseboard InitElectricChiller InitElectricEIRChiller InitEMS InitEMSControlledConstructions InitEMSControlledSurfaceProperties InitEnergyReports InitEngineDrivenChiller InitEquivalentLayerWindowCalculations InitEvapCooler InitEvapFluidCooler InitExhaustAbsorber InitExteriorConvectionCoeff InitFan InitFanCoilUnits InitFluidCooler InitFluidHeatExchanger InitFuelCellGenerators InitFurnace InitGasAbsorber InitGlassOpticalCalculations InitGshp InitGshp InitGTChiller InitHeatBalance InitHeatBalFiniteDiff InitHeatBalHAMT InitHeatingCoil InitHeatRecovery InitHighTempRadiantSystem InitHumidifier InitHWBaseboard InitHXAssistedCoolingCoil InitHybridVentSysAvailMgr InitialInitHeatBalFiniteDiff InitializeCFSDaylighting InitializeCFSStateData InitializeComponentSizingTable InitializeConstructionsTables InitializeDaylightMapTables InitializeEnvironmentPeriodsTable InitializeErrorsTable InitializeGlycolTempLimits InitializeHeatTransferPipes InitializeIndexes InitializeIndexes InitializeLoops InitializeMaterialsTable InitializeMeters initializeMonetaryUnit InitializeNominalBaseboardHeatTable InitializeNominalElectricEquipmentTable InitializeNominalGasEquipmentTable InitializeNominalHotWaterEquipmentTable InitializeNominalInfiltrationTable InitializeNominalLightingTable InitializeNominalOtherEquipmentTable InitializeNominalPeopleTable InitializeNominalSteamEquipmentTable InitializeNominalVentilationTable InitializeOperatingMode InitializeOutput InitializePipes InitializePredefinedMonthlyTitles InitializePsychRoutines InitializePumps InitializeRefrigerantLimits InitializeReportMeterDataDictionaryTable InitializeReportMeterDataTables InitializeReportVariableDataDictionaryTable InitializeReportVariableDataTables InitializeRoomAirModelTable InitializeRootFinder InitializeRuntimeLanguage InitializeSchedulesTable InitializeSimulationsTable InitializeSQLiteTables InitializeSurfacesTable InitializeSystemSizingTable InitializeTabularDataTable InitializeTabularDataTable InitializeTabularDataView InitializeTabularDataView InitializeTabularMonthly InitializeTimeIndicesTable InitializeViews InitializeWeather InitializeZoneGroupTable InitializeZoneInfoTable InitializeZoneListTable InitializeZoneSizingTable InitICEngineGenerators InitIndirectAbsorpChiller InitIndUnit InitInteriorConvectionCoeffs InitInteriorRadExchange InitInternalHeatGains InitIntSolarDistribution InitLoadBasedControl InitLoadDistribution InitLowTempRadiantSystem InitMicroCHPNoNormalizeGenerators InitMoistureBalanceEMPD InitMSHeatPump InitMTGenerators InitMundtModel InitOAController InitOAMixer InitOneTimePlantSizingInfo InitOutAirNodes InitOutdoorAirUnit InitOutsideAirSys InitPipesHeatTransfer InitPipingSystems InitPIU InitPlantProfile InitPlantUserComponent InitPlantValves InitPollutionMeterReporting InitPondGroundHeatExchanger InitPressureDrop InitPTUnit InitPurchasedAir InitPVTcollectors InitRefrigeration InitRefrigerationPlantConnections InitReturnAirPath InitSecretObjects InitSetPointManagers InitSimpleIceStorage InitSimpleMixingConvectiveHeatGains InitSimpleWatertoAirHP InitSimVars InitSimVars InitSimVars InitSimVars InitSolarCalculations InitSolarCollector InitSolarHeatGains InitSolReflRecSurf InitStandAloneERV InitSteamBaseboard InitSteamCoil InitSurfaceGroundHeatExchanger InitSurfaceHeatBalance InitSys InitSysAvailManagers InitSystemOutputRequired InitTempDistModel InitTESCoil InitThermalAndFluxHistories InitThermalComfort InitTower InitTranspiredCollector InitTRNSYSPV InitUCSDCV InitUCSDDV InitUCSDUF InitUniqueNodeCheck InitUnitarySystems InitUnitHeater InitUnitVentilator InitVarSpeedCoil InitVentilatedSlab InitVRF InitWaterCoil InitWaterSource InitWaterThermalTank InitWatertoAirHP InitWatertoWaterHP InitWindowAC InitWindTurbine InitWrapper InitZoneAirLoopEquipment InitZoneAirSetpoints InitZoneAirUserDefined InitZoneContSetpoints InitZoneDehumidifier InitZoneEquipment InitZoneEvaporativeCoolerUnit InPolygon InsertCurrencySymbol int_times_vector INTCPT Integer_IsInRange IntegerIsWithinTwoValues IntegerToString InterConnectTwoPlantLoopSides InteriorBCEqns InteriorNodeEqns InternalRangeCheck InternalSetupTankDemandComponent InternalSetupTankSupplyComponent interp INTERP InterpBlind InterpDefValuesForGlycolConc Interpolate Interpolate_Lagrange InterpolateBetweenFourValues InterpolateBetweenTwoValues InterpolatePipeTransBeam InterpProfAng InterpProfSlatAng InterpretWeatherDataLine InterpSlatAng InterpSw InterpValuesForGlycolConc IntInterfaceNodeEqns IntPreDefTableEntry IntToStr Invert3By3Matrix InvertMatrix InvJulianDay IPTrimSigDigits iRoundSigDigits IS_BEAM IS_DIFF IS_DSRATIO IS_F IS_LWP IS_OPENNESS IS_SWP isCompLoadRepReq IsControlledShade IsConverged_CurrentToPrevIteration IsConverged_PipeCurrentToPrevIteration IsCurveInputTypeValid IsCurveOutputTypeValid isExternalInterfaceErlVariable IsGlazeLayerX IsGZSLayer isInQuadrilateral IsInRange isInTriangle IsLeapYear IsNodeOnSetPtManager IsParentObject IsParentObjectCompSet IsShadingLayer IssueSevereAlphaInputFieldError IssueSevereInputFieldError IssueSevereRealInputFieldError IsValidConnectionType IsVBLayer isWithinRange ITERATE IterateRootFinder iTrimSigDigits JGDate JulianDay LClimb LDSumMax LDSumMean LEEDtariffReporting LimitCoilCapacity LimitController LimitTUCapacity LinesOut linint LoadEquipList LoadInterface LogicalToInteger LogicalToInteger LogPlantConvergencePoints lookupOperator LookUpScheduleValue LookUpSeason LookupSItoIP lubksb LUBKSB ludcmp LUDCMP LUdecomposition LUsolution MakeAnchorName MakeHVACTimeIntervalString MakeMirrorSurface MakeRectangularVertices MakeRelativeRectangularVertices MakeTransition MakeUPPERCase ManageAirflowNetworkBalance ManageAirHeatBalance ManageAirLoops ManageAirModel ManageBranchInput ManageControllers ManageCoolTower ManageDemand ManageEarthTube ManageElectCenterStorageInteractions ManageElectricLoadCenters ManageElectStorInteractions ManageEMS ManageExteriorEnergyUse ManageGeneratorControlState ManageGeneratorFuelFlow ManageHeatBalance ManageHeatBalFiniteDiff ManageHeatBalHAMT ManageHVAC ManageHybridVentilation ManageInsideAdaptiveConvectionAlgo ManageInternalHeatGains ManageInverter ManageMundtModel ManageNonZoneEquipment ManageOutsideAdaptiveConvectionAlgo ManageOutsideAirSystem ManagePlantLoadDistribution ManagePlantLoops ManageRefrigeratedCaseRacks ManageSetPoints ManageSimulation ManageSingleCommonPipe ManageSizing ManageSurfaceHeatBalance ManageSystemAvailability ManageThermalChimney ManageThermalComfort ManageTransformers ManageTwoWayCommonPipe ManageUCSDCVModel ManageUCSDDVModel ManageUCSDUFModels ManageUserDefinedPatterns ManageWater ManageWaterInits ManageWeather ManageZoneAirLoopEquipment ManageZoneAirUpdates ManageZoneContaminanUpdates ManageZoneEquipment MapExtConvClassificationToHcModels MapIntConvClassificationToHcModels MarkNode MatchAndSetColorTextString MatchPlantSys MatrixIndex matrixQBalance MeshPartition_CompareByDimension MeshPartition_SelectionSort MeshPartitionArray_Contains MinePlantStructForInfo MixedAirControlTempResidual ModifyWindow Modulus MonthToMonthNumber MovingAvg MRXINV MSHPCyclingResidual MSHPHeatRecovery MSHPVarSpeedResidual MultiModeDXCoilHumRatResidual MultiModeDXCoilHumRatResidual MultiModeDXCoilResidual MultiModeDXCoilResidual MultiModeDXCoilResidual MultiSpeedDXCoolingCoilStandardRatings MultiSpeedDXHeatingCoilStandardRatings MULTOL MyPlantSizingIndex NeighborInformationArray_Value NETRAD NewEMSVariable NewExpression newPreDefColumn newPreDefReport newPreDefSubTable NEWTON NodeHasSPMCtrlVarType NormalArea NumBranchesInBranchList NumCompsInBranch nusselt NusseltNumber OpenEPlusWeatherFile OPENNESS_LW OpenOutputFiles OpenOutputTabularFile OpenWeatherFile OPERATOR (*) OPERATOR (+) OPERATOR (-) OPERATOR (.dot.) OPERATOR (.twodcross.) OPERATOR (.twoddot.) OPERATOR (/) ORDER OutBaroPressAt OutDewPointTempAt OutDryBulbTempAt OutsidePipeHeatTransCoef OutWetBulbTempAt P01 PanesDeflection ParametricObjectsCheck parseComputeLine ParseExpression ParseStack ParseTime PartLoadFactor PassiveGapNusseltNumber PassPressureAcrossInterface PassPressureAcrossMixer PassPressureAcrossSplitter PD_BEAM PD_BEAM_CASE_I PD_BEAM_CASE_II PD_BEAM_CASE_III PD_BEAM_CASE_IV PD_BEAM_CASE_V PD_BEAM_CASE_VI PD_DIFF PD_LW PD_LWP PD_SWP PerformanceCurveObject PerformanceTableObject PerformIterationLoop PerformPipeCellSimulation PerformPipeCircuitSimulation PerformSolarCalculations PerformTemperatureFieldUpdate PierceSurface PierceSurfaceVector PipeCircuitInfo_InitInOutCells PipeSegmentInfo_InitPipeCells PIUInducesPlenumAir PIUnitHasMixer PlaneEquation PlantHalfLoopSolver PlantMassFlowRatesFunc PLRResidual PLRResidual PLRResidualMixedTank PLRResidualStratifiedTank PMVResidual POLY1F POLY2F POLYF polygon_contains_point_2d popStack pos PostIPProcessing POWER PreDefTableEntry PredictSystemLoads PredictZoneContaminants PreparePipeCircuitSimulation PrepDebugFilesAndVariables PreProcessorCheck PrepVariablesISO15099 PreScanReportingVariables PresProfile PressureCurveValue ProcessDataDicFile ProcessDateString ProcessEMSInput ProcessEPWHeader ProcessForDayTypes ProcessInput ProcessInputDataFile ProcessIntervalFields ProcessMinMaxDefLine ProcessNumber ProcessScheduleInput ProcessSurfaceVertices ProcessTokens ProduceMinMaxString ProduceMinMaxStringWStartMinute ProduceRDDMDD ProfileAngle PropagateResolvedFlow PStack PsyCpAirFnWTdb PsyHfgAirFnWTdb PsyHFnTdbRhPb PsyHFnTdbW PsyHgAirFnWTdb PsyPsatFnTemp PsyPsatFnTemp_raw PsyRhFnTdbRhov PsyRhFnTdbRhovLBnd0C PsyRhFnTdbWPb PsyRhoAirFnPbTdbW PsyRhovFnTdbRh PsyRhovFnTdbRhLBnd0C PsyRhovFnTdbWPb PsyTdbFnHW PsyTdpFnTdbTwbPb PsyTdpFnWPb PsyTsatFnHPb PsyTsatFnPb PsyTwbFnTdbWPb PsyTwbFnTdbWPb_raw PsyVFnTdbWPb PsyWFnTdbH PsyWFnTdbRhPb PsyWFnTdbTwbPb PsyWFnTdpPb psz Pt2Plane PullCompInterconnectTrigger PumpDataForTable PushBranchFlowCharacteristics PushInnerTimeStepArrays pushStack PushSystemTimestepHistories PushSystemTimestepHistories PushZoneTimestepHistories PushZoneTimestepHistories QsortC QsortPartition RadialCellInfo_XY_CrossSectArea RadialCellInformation_ctor RadialSizing_Thickness Rainflow RangeCheck RB_BEAM RB_DIFF RB_F RB_LWP RB_SWP rCheckDayScheduleValueMinMax rCheckScheduleValue rCheckScheduleValueMinMax1 rCheckScheduleValueMinMax2 ReadEnergyMeters ReadEPlusWeatherForDay ReadGeneralDomainInputs ReadHorizontalTrenchInputs ReadINIFile ReadInputLine ReadPipeCircuitInputs ReadPipeSegmentInputs ReadTableData ReadUserWeatherInput ReadWeatherForDay Real_ConstrainTo Real_IsInRange real_times_vector ReAllocateAndPreserveOutputVariablesForSimulation ReallocateIntegerArray ReallocateIVar ReallocateRealArray ReallocateRVar RealPreDefTableEntry RealToStr RecKeepHeatBalance RecordOutput RectangleF_Contains ReformEIRChillerCondInletTempResidual ReformEIRChillerHeatRecovery RegisterNodeConnection RegisterPlantCompDesignFlow RegulateCondenserCompFlowReqOp ReInitPlantLoopsAtFirstHVACIteration RemoveSpaces RemoveTrailingZeros reorder ReplaceBlanksWithUnderscores ReplaceBlanksWithUnderscores ReportAirflowNetwork ReportAirHeatBalance ReportAirLoopConnections ReportAirTerminalUserDefined ReportAndTestGlycols ReportAndTestRefrigerants ReportBaseboard ReportBaseboard ReportCBVAV ReportChillerIPLV ReportCoilUserDefined ReportCompSetMeterVariables ReportController ReportCoolBeam ReportCoolTower ReportCTFs ReportCWTankInits ReportDemandManagerList ReportDesiccantDehumidifier ReportDetailedIceStorage ReportDirectAir ReportDualDuct ReportDualDuctConnections ReportDuct ReportDXCoil ReportDXCoilRating ReportDYMeters ReportEarthTube ReportEconomicVariable ReportElectricBaseboard ReportEMS ReportEvapCooler ReportEvapFluidCooler ReportExteriorEnergyUse ReportFan ReportFanCoilUnit ReportFatalGlycolErrors ReportFatalRefrigerantErrors ReportFiniteDiffInits ReportFluidCooler ReportFluidHeatExchanger ReportForTabularReports ReportFurnace ReportGlass ReportHeatBalance ReportHeatingCoil ReportHeatRecovery ReportHighTempRadiantSystem ReportHRMeters ReportHumidifier ReportHWBaseboard ReportIllumMap ReportingFreqName ReportingThisVariable ReportInternalHeatGains ReportLoopConnections ReportLowTempRadiantSystem ReportMaxVentilationLoads ReportMeterDetails ReportMissing_RangeData ReportMixer ReportMNMeters ReportMoistureBalanceEMPD ReportMSHeatPump ReportNodeConnections ReportOAController ReportOAMixer ReportOrphanFluids ReportOrphanRecordObjects ReportOrphanSchedules ReportOutdoorAirUnit ReportOutputFileHeaders ReportParentChildren ReportPipesHeatTransfer ReportPIU ReportPlantProfile ReportPlantUserComponent ReportPlantValves ReportPondGroundHeatExchanger ReportPTUnit ReportPumps ReportPurchasedAir ReportPV ReportRackSystem ReportRefrigerationComponents ReportReturnAirPath ReportRuntimeLanguage ReportScheduleDetails ReportScheduleValues ReportSizingOutput ReportSMMeters ReportSolarCollector ReportSplitter ReportStandAloneERV ReportStandAloneWaterUse ReportSteamBaseboard ReportSteamCoil ReportSurfaceErrors ReportSurfaceGroundHeatExchngr ReportSurfaceHeatBalance ReportSurfaces ReportSurfaceShading ReportSys ReportSysSizing ReportSystemEnergyUse ReportThermalChimney ReportTowers ReportTSMeters ReportUnitarySystem ReportUnitHeater ReportUnitVentilator ReportVentilatedSlab ReportVRFCondenser ReportVRFTerminalUnit ReportWarmupConvergence ReportWaterCoil ReportWaterManager ReportWaterThermalTank ReportWaterUse ReportWeatherAndTimeInformation ReportWindowAC ReportWindTurbine ReportZoneAirLoopEquipment ReportZoneAirUserDefined ReportZoneDehumidifier ReportZoneEquipment ReportZoneEvaporativeCoolerUnit ReportZoneMeanAirTemp ReportZoneReturnPlenum ReportZoneSizing ReportZoneSupplyPlenum ResetAllPlantInterConnectFlags ResetController ResetEnvironmentCounter ResetHVACControl ResetNodeData ResetPerformanceCurveOutput ResetRootFinder ResetTerminalUnitFlowLimits ResetWeekDaysByMonth Resimulate resist ReSolveAirLoopControllers ResolveAirLoopFlowLimits ResolveLocationInformation ResolveLockoutFlags ResolveLoopFlowVsPressure ResolveParallelFlows ResolveSysFlow ReverseAndRecalculate RevertZoneTimestepHistories RevertZoneTimestepHistories RevisePlantCallingOrder RezeroZoneSizingArrays RhoH2O RHtoVP RKG RoundSigDigits rRoundSigDigits rTrimSigDigits SafeCopyPlantNode SafeDiv SafeDivide SameString SandiaCellTemperature SandiaEffectiveIrradiance SandiaF1 SandiaF2 SandiaImp SandiaIsc SandiaIx SandiaIxx SandiaModuleTemperature SandiaTcellFromTmodule SandiaVmp SandiaVoc SaveSimpleController ScanForReports ScanPlantLoopsForNodeNum ScanPlantLoopsForObject sCheckDayScheduleValueMinMax ScheduleAverageHoursPerWeek SEARCH SearchAscTable SearchWindow5DataFile SecantFormula SecantMethod selectTariff SetActuatedBranchFlowRate SetAdditionalNeighborData SetAllFlowLocks SetAllPlantSimFlagsToValue SetATMixerPriFlow SetATMixerPriFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetCoilDesFlow SetCoilSystemCoolingData SetCoilSystemHeatingDXFlag SetCompFlowRate SetComponentFlowRate SetCurrentWeather SetCurveOutputMinMaxValues SetDSTDateRanges SetDXCoilTypeData SetDXCoolingCoilData SetEquivalentLayerWindowProperties SetErlValueNumber SetExtConvectionCoeff SetFanData SetHeatExchangerData SetHeatToReturnAirFlag SetInitialMeterReportingAndOutputNames SetIntConvectionCoeff SetInternalVariableValue SetMinMax setNativeVariables SetNodeResult SetOAControllerData SetOnOffMassFlowRate SetOnOffMassFlowRate SetOnOffMassFlowRate SetOnOffMassFlowRateVSCoil SetOnOffMassFlowRateVSCoil SetOutAirNodes SetOutBulbTempAt SetPredefinedTables SetSimpleWSHPData SETSKY SetSpecialDayDates SetSpeedVariables SetStormWindowControl SetSurfHBDataForMundtModel SetSurfHBDataForTempDistModel SetSurfTmeanAir SETUP4x4_A SetupAdaptiveConvectionRadiantSurfaceData SetupAdaptiveConvectionStaticMetaData SetupAirLoopControllersTracer SetupAllOutputVariables SetUpAndSort SetupBranchControlTypes SetupCellNeighbors SetupCommonPipes SetupComplexFenestrationMaterialInput SetupComplexFenestrationStateInput SetupComplexWindowStateGeometry SetUpCompSets SetupDElightOutput4EPlus SetupDElightOutput4EPlus SetUpDesignDay SetupEMSActuator SetupEMSIntegerActuator SetupEMSIntegerInternalVariable SetupEMSInternalVariable SetupEMSLogicalActuator SetupEMSRealActuator SetupEMSRealInternalVariable SetupEnvironmentTypes SetupFuelConstituentData SetupGeneratorControlStateManager SetupIndividualControllerTracer SetupInitialPlantCallingOrder SetupIntegerOutputVariable SetupInterpolationValues SetupLoopFlowRequest SetupMeteredVarsForSetPt SetupMundtModel SetupNodeSetpointsAsActuators SetupNodeVarsForReporting SetupOutputVariable SetupPipeCircuitInOutCells SetupPlantEMSActuators SetupPollutionCalculations SetupPollutionMeterReporting SetupPossibleOperators SetupPrimaryAirSystemAvailMgrAsActuators SetupPumpMinMaxFlows SetupRealOutputVariable SetupRealOutputVariable_IntKey SetupReportInput SetupReports SetupRootFinder SetUpSchemeColors SetupShadeSurfacesForSolarCalcs SetupSimpleWindowGlazingSystem SetupSimulation SetupStratifiedNodes SetupSurfaceConstructionActuators SetupSurfaceConvectionActuators SetupSurfaceOutdoorBoundaryConditionActuators SetUpSysSizingArrays SetupTankDemandComponent SetupTankSupplyComponent SetupThermostatActuators SetupTimePointers SetupUnitConversions SetupWeekDaysByMonth SetupWindowShadingControlActuators SetupZoneEquipmentForConvectionFlowRegime SetupZoneGeometry SetupZoneInfoAsInternalDataAvail SetupZoneInternalGain SetupZoneInternalGain SetupZoneSizing SetUpZoneSizingArrays SetUTSCQdotSource SetVarSpeedCoilData SetVentedModuleQdotSource SetVSHPAirFlow SetVSHPAirFlow SetWindSpeedAt SetZoneEquipSimOrder shading shadingedge shadingin SHADOW SharedDVCVUFDataInit SHDBKS SHDGSS SHDRVL SHDSBS shift ShiftPipeTemperaturesForNewIteration ShiftPlantLoopSideCallingOrder ShiftTemperaturesForNewIteration ShiftTemperaturesForNewTimeStep ShowAuditErrorMessage ShowBranchesOnLoop ShowContinueError ShowContinueError ShowContinueErrorTimeStamp ShowContinueErrorTimeStamp ShowErrorMessage ShowErrorMessage ShowFatalError ShowFatalError ShowMessage ShowMessage ShowPsychrometricSummary ShowRecurringContinueErrorAtEnd ShowRecurringContinueErrorAtEnd ShowRecurringErrors ShowRecurringSevereErrorAtEnd ShowRecurringSevereErrorAtEnd ShowRecurringWarningErrorAtEnd ShowRecurringWarningErrorAtEnd ShowSevereError ShowSevereError ShowSevereMessage ShowSevereMessage ShowWarningError ShowWarningError ShowWarningMessage ShowWarningMessage showWarningsBasedOnTotal Sim4PipeFanCoil SimAirChillerSet SimAirLoop SimAirLoopComponent SimAirLoopComponents SimAirLoops SimAirLoopSplitter SimAirMixer SimAirTerminalUserDefined SimAirZonePlenum SimATMixer SimBaseboard SimBLASTAbsorber SimBoiler SimCBVAV SimCBVAV SimCentralGroundSourceHeatPump SimChiller SimCoilUserDefined SimComponentModelFan SimConstVol SimCoolBeam SimCostEstimate SimCTGenerator SimCTPlantHeatRecovery SimCyclingWindowAC SimDesiccantDehumidifier SimDetailedIceStorage SimDirectAir SimDistrictEnergy SimDualDuctConstVol SimDualDuctVarVol SimDualDuctVAVOutdoorAir SimDuct SimDXCoil SimDXCoilMultiMode SimDXCoilMultiSpeed SimDXCoolingSystem SimDXHeatPumpSystem SimElecBaseBoard SimElectricBaseBoard SimElectricConvective SimElectricEIRChiller SimEvapCooler SimEvapFluidCoolers SimExhaustAbsorber SimFanCoilUnit SimFluidCoolers SimFluidHeatExchanger SimFourPipeIndUnit SimFuelCellGenerator SimFuelCellPlantHeatRecovery SimFurnace SimGasAbsorber SimGroundHeatExchangers SimHeatPumpWaterHeater SimHeatRecovery SimHighTempRadiantSystem SimHPWatertoWaterCOOLING SimHPWatertoWaterHEATING SimHPWatertoWaterSimple SimHumidifier SimHVAC SimHWBaseboard SimHWConvective SimHXAssistedCoolingCoil SimICEngineGenerator SimICEPlantHeatRecovery SimIceStorage SimIndirectAbsorber SimIndUnit SimLowTempRadiantSystem SimMicroCHPGenerator SimMicroCHPPlantHeatRecovery SimMSHeatPump SimMSHP SimMTGenerator SimMTPlantHeatRecovery SimMultiSpeedCoils SimOAComponent SimOAController SimOAMixer SimOnOffFan SimOutdoorAirEquipComps SimOutdoorAirUnit SimOutsideAirSys SimOutsideEnergy SimPackagedTerminalUnit SimPipes SimPipesHeatTransfer SimPipingSystemCircuit SimPIU SimPlantEquip SimPlantValves SimpleCoolingCoilUAResidual SimpleEvapFluidCoolerUAResidual SimpleFluidCoolerUAResidual SimpleHeatingCoilUAResidual SimpleTowerApproachResidual SimpleTowerTrResidual SimpleTowerUAResidual SimPondGroundHeatExchanger SimPressureDropSystem SimPTUnit SimPumps SimPurchasedAir SimPVGenerator SimPVTcollectors SimReformulatedEIRChiller SimRefrigCondenser SimReturnAirPath SimSelectedEquipment SimSetPointManagers SimSimpleEvapFluidCooler SimSimpleFan SimSimpleFluidCooler SimSimpleTower SimSolarCollector SimStandAloneERV SimSteamBaseboard SimSteamBoiler SimSteamCoils SimSurfaceGroundHeatExchanger SimSysAvailManager SimTESCoil SimTowers SimTranspiredCollector SimulateAllInteriorRadialSoilSlices SimulateAllLoopSideBranches SimulateAllLoopSidePumps SimulateDemandManagerList SimulateDetailedRefrigerationSystems SimulateDetailedTransRefrigSystems SimulateDualDuct SimulateFanComponents SimulateFluidCell SimulateHeatingCoilComponents SimulateInnerMostRadialSoilSlice SimulateLoopSideBranchGroup SimulateOuterMostRadialSoilSlice SimulatePlantProfile SimulateRadialInsulationCell SimulateRadialPipeCell SimulateRadialToCartesianInterface SimulateSingleDuct SimulateSteamCoilComponents SimulateVRF SimulateWaterCoilComponents SimulateWaterHeaterStandAlone SimulateWaterUse SimulateWaterUseConnection SimUnitaryBypassVAV SimUnitarySystem SimUnitHeater SimUnitVentilator SimUnitVentOAMixer SimUserDefinedPlantComponent SimVariableSpeedCoils SimVariableSpeedHP SimVariableSpeedHP SimVariableTower SimVariableVolumeFan SimVAV SimVAVVS SimVentilatedSlab SimVentSlabOAMixer SimVRF SimVRFCondenserPlant SimWaterCoils SimWaterSource SimWaterThermalTank SimWatertoAirHP SimWatertoAirHPSimple SimWindowAC SimWindTurbine SimZoneAirLoopEquipment SimZoneAirUserDefined SimZoneDehumidifier SimZoneEquipment SimZoneEvaporativeCoolerUnit SimZoneExhaustFan SimZoneOutAirUnitComps SingelSpeedDXCoolingCoilStandardRatings SingleSpeedDXHeatingCoilStandardRatings SingleSpeedFluidCooler SizeAbsorpChiller SizeAirLoopBranches SizeAirLoops SizeBaseboard SizeBoiler SizeBoiler SizeCBVAV SizeConstCOPChiller SizeController SizeCoolBeam SizeDemandSidePlantConnections SizeDirectAir SizeDualDuct SizeDXCoil SizeElecReformEIRChiller SizeElectricBaseboard SizeElectricBaseboard SizeElectricChiller SizeElectricEIRChiller SizeEngineDrivenChiller SizeEvapCooler SizeEvapFluidCooler SizeExhaustAbsorber SizeFan SizeFanCoilUnit SizeFluidCooler SizeFluidHeatExchanger SizeFurnace SizeGasAbsorber SizeGTChiller SizeHeatingCoil SizeHeatRecovery SizeHighTempRadiantSystem SizeHumidifier SizeHVACWaterToAir SizeHWBaseboard SizeIndirectAbsorpChiller SizeIndUnit SizeLowTempRadiantSystem SizeMSHeatPump SizeOAController SizeOutdoorAirUnit SizePIU SizePlantLoop SizePTUnit SizePump SizePurchasedAir SizePVT SizeStandAloneERV SizeStandAloneWaterHeater SizeSteamBaseboard SizeSteamCoil SizeSupplySidePlantConnections SizeSys SizeTankForDemandSide SizeTankForSupplySide SizeTESCoil SizeTower SizeUCSDUF SizeUnitarySystem SizeUnitHeater SizeUnitVentilator SizeVarSpeedCoil SizeVentilatedSlab SizeVRF SizeVRFCondenser SizeVSMerkelTower SizeWaterCoil SizeWaterManager SizeWaterSource SizeWindowAC SizeWrapper SizeZoneDehumidifier SizeZoneEquipment SizeZoneEvaporativeCoolerUnit SkipEPlusWFHeader SkyDifSolarShading SkyGndWeight SkyWeight SLtoAMB SLtoGL SLVSKY solar_EN673 solarISO15099 SolarSprectrumAverage SOLMATS SolveAirLoopControllers SolveForWindowTemperatures SolveRegression SolveRegulaFalsi SolverMoistureBalanceEMPD SOLVZP SortHistory Specular_Adjust Specular_EstimateDiffuseProps Specular_F Specular_OffNormal Specular_RATDiff Specular_SWP SQLiteBegin SQLiteBegin SQLiteBindDouble SQLiteBindInteger SQLiteBindLogicalMacro SQLiteBindNULL SQLiteBindText SQLiteBindTextMacro SQLiteClearBindings SQLiteCloseDatabase SQLiteColumnInt SQLiteColumnIntMacro SQLiteCommit SQLiteCommit SQLiteExecuteCommand SQLiteExecuteCommandMacro SQLiteFinalizeCommand SQLiteOpenDatabase SQLiteOpenDatabaseMacro SQLitePrepareStatement SQLitePrepareStatementMacro SQLiteResetCommand SQLiteStepCommand SQLiteWriteMessage SQLiteWriteMessageMacro SQLiteWriteMessageMacro StandardIndexTypeKey StandardVariableTypeKey StartingWindowTemps StartingWinTempsForNominalCond SteamHeatingCoilResidual StorageType StoreAPumpOnCurrentTempLoop storeIterationResults StoreRecurringErrorMessage StringValue StrToReal SumAllInternalCO2Gains SumAllInternalConvectionGains SumAllInternalGenericContamGains SumAllInternalLatentGains SumAllInternalRadiationGains SumAllReturnAirConvectionGains SumAllReturnAirLatentGains SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumInternalCO2GainsByTypes SumInternalConvectionGainsByTypes SumInternalLatentGainsByTypes SumInternalRadiationGainsByTypes SummarizeErrors SumReturnAirConvectionGainsByTypes SumZoneImpacts SUN3 SUN4 SupSATResidual SurfaceScheduledSolarInc SurveyDemandManagers SystemPropertiesAtLambdaAndPhi SystemSpectralPropertiesAtPhi TableLookupObject TARCOG90 TBND TdbFnHRhPb TDMA TDMA_R TellMeHowManyObjectItemArgs TemperaturesFromEnergy TempIPtoSI TempSItoIP terpld TESCoilHumRatResidual TESCoilResidual TestAirPathIntegrity TestBranchIntegrity TestCompSet TestCompSetInletOutletNodes TestInletOutletNodes TestReturnAirPathIntegrity TestSupplyAirPathIntegrity therm1d TightenNodeMinMaxAvails TimestepInitComplexFenestration TimestepTypeName TraceAirLoopController TraceAirLoopControllers TraceIndividualController TraceIterationStamp TrackAirLoopController TrackAirLoopControllers TRadC TransAndReflAtPhi TransformVertsByAspect TransTDD Triangulate TrimSigDigits TurnOffLoopEquipment TurnOffLoopSideEquipment TurnOffReportRangeCheckErrors TurnOnPlantLoopPipes TurnOnReportRangeCheckErrors TwoSpeedFluidCooler UnitarySystemHeatRecovery UpdateAbsorberChillerComponentGeneratorSide UpdateAirflowNetwork UpdateAirMixer UpdateAirSysCompPtrArray UpdateAirSysSubCompPtrArray UpdateAirSysSubSubCompPtrArray UpdateAirZoneReturnPlenum UpdateAirZoneSupplyPlenum UpdateAnyLoopDemandAlterations UpdateATMixer UpdateBaseboard UpdateBaseboardPlantConnection UpdateBasementSurfaceTemperatures UpdateBBElecRadSourceValAvg UpdateBBRadSourceValAvg UpdateBBSteamRadSourceValAvg UpdateBLASTAbsorberRecords UpdateBoilerRecords UpdateBoilerRecords UpdateBracket UpdateBranchConnections UpdateChillerComponentCondenserSide UpdateChillerheaterRecords UpdateChillerRecords UpdateColdWeatherProtection UpdateCommonPipe UpdateComplexWindows UpdateComponentHeatRecoverySide UpdateConstCOPChillerRecords UpdateController UpdateCoolBeam UpdateCoolTower UpdateCTGeneratorRecords UpdateDataandReport UpdateDemandManagers UpdateDesiccantDehumidifier UpdateDetailedIceStorage UpdateDualDuct UpdateDuct UpdateDXCoil UpdateElectricBaseboard UpdateElectricChillerRecords UpdateElectricEIRChillerRecords UpdateEMSTrendVariables UpdateEngineDrivenChiller UpdateEvapCooler UpdateEvapFluidCooler UpdateEvaporativeCondenserBasinHeater UpdateEvaporativeCondenserWaterUse UpdateExhaustAbsorberCoolRecords UpdateExhaustAbsorberHeatRecords UpdateExhaustAirFlows UpdateFan UpdateFinalSurfaceHeatBalance UpdateFluidCooler UpdateFluidHeatExchanger UpdateFuelCellGeneratorRecords UpdateGasAbsorberCoolRecords UpdateGasAbsorberHeatRecords UpdateGSHPRecords UpdateGSHPRecords UpdateGSHPRecords UpdateGTChillerRecords UpdateHalfLoopInletTemp UpdateHeatBalHAMT UpdateHeatingCoil UpdateHeatRecovery UpdateHighTempRadiantSystem UpdateHistories UpdateHistory UpdateHTRadSourceValAvg UpdateHumidifier UpdateHVACInterface UpdateHWBaseboard UpdateHWBaseboardPlantConnection UpdateIceFractions UpdateICEngineGeneratorRecords UpdateIndirectAbsorberRecords UpdateInternalGainValues UpdateIrrigation UpdateLoadCenterRecords UpdateLoopSideReportVars UpdateLowTempRadiantSystem UpdateMeterReporting UpdateMeters UpdateMeterValues UpdateMicroCHPGeneratorRecords UpdateMinMax UpdateMixedAirSetPoints UpdateMoistureBalanceEMPD UpdateMoistureBalanceFD UpdateMSHeatPump UpdateMTGeneratorRecords UpdateNode UpdateNodeThermalHistory UpdateOAController UpdateOAMixer UpdateOAPretreatSetPoints UpdatePipesHeatTransfer UpdatePipingSystems UpdatePlantLoopInterface UpdatePlantMixer UpdatePlantProfile UpdatePlantSplitter UpdatePlantValves UpdatePondGroundHeatExchanger UpdatePrecipitation UpdatePressureDrop UpdatePurchasedAir UpdatePVTcollectors UpdateRadSysSourceValAvg UpdateRecords UpdateReformEIRChillerRecords UpdateRefrigCondenser UpdateReportWaterSystem UpdateRootFinder UpdateScheduleValues UpdateSetPointManagers UpdateSimpleWatertoAirHP UpdateSoilProps UpdateSolarCollector UpdateSplitter UpdateSQLiteErrorRecord UpdateSQLiteErrorRecord UpdateSQLiteSimulationRecord UpdateSQLiteSimulationRecord UpdateSteamBaseboard UpdateSteamBaseboardPlantConnection UpdateSteamCoil UpdateSurfaceGroundHeatExchngr UpdateSys UpdateSysSizing UpdateSystemOutputRequired UpdateTabularReports UpdateTEStorage UpdateThermalHistories UpdateTowers UpdateTranspiredCollector UpdateUnitarySystemControl UpdateUtilityBills UpdateVarSpeedCoil UpdateVentilatedSlab UpdateVerticalGroundHeatExchanger UpdateVRFCondenser UpdateWaterCoil UpdateWaterConnections UpdateWaterManager UpdateWaterSource UpdateWaterThermalTank UpdateWaterToAirCoilPlantConnection UpdateWatertoAirHP UpdateWeatherData UpdateWholeBuildingRecords UpdateZoneAirLoopEquipment UpdateZoneCompPtrArray UpdateZoneDehumidifier UpdateZoneEquipment UpdateZoneInletConvergenceLog UpdateZoneListAndGroupLoads UpdateZoneSizing UpdateZoneSubCompPtrArray UpdateZoneSubSubCompPtrArray ValidateAndSetSysAvailabilityManagerType ValidateComponent ValidateDistributionSystem ValidateEMSProgramName ValidateEMSVariableName ValidateExhaustFanInput ValidateFlowControlPaths ValidateFuelType ValidateIndexType ValidateMaterialRoughness ValidateMonthDay ValidateNStandardizeMeterTitles ValidateObjectandParse ValidatePipeConstruction ValidatePLFCurve ValidateSection ValidateSectionsInput ValidateVariableType value_to_vector ValueToString VAVVSCoolingResidual VAVVSHCFanOnResidual VAVVSHWFanOnResidual VAVVSHWNoFanResidual VB_CriticalSlatAngle VB_DIFF VB_LWP VB_ShadeControl VB_SLAT_RADIUS_RATIO VB_SOL4 VB_SOL46_CURVE VB_SOL6 VB_SWP vec2d_cross_product vec2d_dot_product vec_cross_product vec_dot_product VecLength VecNegate VecNormalize VecRound VecSquaredLength vector_add vector_div_int vector_div_real vector_subtract vector_times_int vector_times_real vector_to_array VerifyControlledZoneForThermostat VerifyCustomMetersElecPowerMgr VerifyHeatExchangerParent VerifyName VerifySetPointManagers VerifyThermostatInZone VerifyUniqueBaseboardName VerifyUniqueBoilerName VerifyUniqueChillerName VerifyUniqueCoilName ViewFac VisibleSprectrumAverage Volume VRMLOut VSCoilCyclingHumResidual VSCoilCyclingResidual VSCoilCyclingResidual VSCoilSpeedHumResidual VSCoilSpeedResidual VSCoilSpeedResidual VSEvapUnitLoadResidual VSHPCyclingResidual VSHPCyclingResidual VSHPSpeedResidual VSHPSpeedResidual VSMerkelResidual W5InitGlassParameters W5LsqFit W5LsqFit2 W6CoordsFromWorldVect warnIfNativeVarname WetCoilOutletCondition WhichCompSet WhichParentCompSet WhichParentSet Width WindowGapAirflowControl WindowGasConductance WindowGasPropertiesAtTemp WindowHeatBalanceEquations WindowScheduledSolarAbs WindowShadingManager WindowTempsForNominalCond WindSpeedAt Windward WorldVectFromW6 WriteAdaptiveComfortTable WriteAirLoopStatistics WriteBEPSTable WriteCompCostTable WriteComponentSizing WriteCumulativeReportMeterData WriteDaylightMapTitle WriteDemandEndUseSummary WriteInputArguments WriteIntegerData WriteIntegerVariableOutput WriteMeterDictionaryItem WriteModifiedArguments WriteMonthlyTables WriteOutputArguments WriteOutputEN673 WritePoint WritePredefinedTables WriteRealData WriteRealVariableOutput WriteReportHeaders WriteReportIntegerData WriteReportMeterData WriteReportRealData WriteReportVariableDictionaryItem WriteRootFinderStatus WriteRootFinderTrace WriteRootFinderTraceHeader WriteSourceEnergyEndUseSummary writeSubtitle WriteSurfaceShadowing WriteTable WriteTableOfContents WriteTabularLifeCycleCostReport WriteTabularReports WriteTabularTariffReports WriteTARCOGInputFile writeTextLine WriteTimeBinTables WriteTimeStampFormatData WriteTrace WriteVeriSumTable WriteZoneLoadComponentTable WVDC XNormalArea XYRectangle XZRectangle YNormalArea YZRectangle ZeroHVACValues ZNormalArea
Call graph
setupzonesizingarrays calls zonesizinginput, verifythermostatinzone, finditeminlist, showfatalerror, finalzonesizing, zonesizthermsetpthi, zonesizing, zonesizthermsetptlo, calcfinalzonesizing, calczonesizing, showwarningerror, zoneequipconfig, setupemsinternalvariable, setupemsactuator, heatpeakdatehrmin, calcdesignspecificationoutdoorair, desdayweath, termunitfinalzonesizing, coolpeakdatehrmin, showsevereerror, getschedulemaxvalue, people, zone
showfatalerror calls abortenergyplus, displaystring, showerrormessage, roundsigdigits, createsqliteerrorrecord
showwarningerror calls showerrormessage, createsqliteerrorrecord, matchcounts, messagesearch
calcdesignspecificationoutdoorair calls getschedulemaxvalue, people, zone, oarequirements, zoneintgain, getcurrentschedulevalue
showsevereerror calls showerrormessage, createsqliteerrorrecord, matchcounts, messagesearch
abortenergyplus calls displaystring, roundsigdigits, testairpathintegrity, updatesqlitesimulationrecord, checkmarkednodes, reportairloopconnections, showrecurringerrors, testcompsetinletoutletnodes, summarizeerrors, reportsurfaceerrors, reportloopconnections, closemiscopenfiles, setupnodevarsforreporting, closesocket, closeoutopenfiles, reportsurfaces, testbranchintegrity, checkplantonabort, epelapsedtime, epstoptime, epsummarytimes, showmessage, checknodeconnections
showerrormessage calls showfatalerror, displaystring
testairpathintegrity calls showsevereerror, airtozonenodeinfo, nodeid, showcontinueerror
showrecurringerrors calls roundsigdigits, createsqliteerrorrecord, showmessage, updatesqliteerrorrecord, removetrailingzeros, recurringerrors
summarizeerrors calls showmessage, matchcounts, summaries, moredetails
closemiscopenfiles calls closedfsfile, closereportillummaps
reportsurfaces calls showwarningerror, detailsforsurfaces, setupschemecolors, vrmlout, scanforreports, dxfoutwireframe, costinfoout, linesout, dxfout
epstoptime calls showfatalerror, tstop
epsummarytimes calls roundsigdigits
showmessage calls showerrormessage
showcontinueerror calls showerrormessage, updatesqliteerrorrecord
detailsforsurfaces calls getschedulemaxvalue, zone, roundsigdigits, getschedulename, oscm, nominalu, framedivider, 2, computenominaluwithconvcoeffs, 3, osc, trimsigdigits, construct, 4, csurfaceclass, userintconvectioncoeffs, userextconvectioncoeffs, surface, getscheduleminvalue, surfacewindow
setupschemecolors calls showwarningerror, getobjectitemnum, getobjectdefmaxargs, matchandsetcolortextstring, getobjectitem
vrmlout calls showfatalerror, showwarningerror, zone, showcontinueerror, surface, triangulate, getnewunitnumber
dxfoutwireframe calls showfatalerror, zone, trimsigdigits, surface, surfacewindow, getnewunitnumber, zonedaylight, dxfcolorno
costinfoout calls showfatalerror, construct, csurfaceclass, surface, getnewunitnumber
linesout calls showfatalerror, showwarningerror, roundsigdigits, showcontinueerror, csurfaceclass, surface, getnewunitnumber
dxfout calls showfatalerror, showwarningerror, zone, showcontinueerror, trimsigdigits, surface, surfacewindow, triangulate, getnewunitnumber, zonedaylight, dxfcolorno, illummapcalc
computenominaluwithconvcoeffs calls surface
matchandsetcolortextstring calls finditem
triangulate calls showwarningerror, roundsigdigits, showmessage, showcontinueerror, csurfaceclass, generate_ears, calcrfflrcoordinatetransformation, calcwallcoordinatetransformation
generate_ears calls polygon_contains_point_2d, angle_2dvector
sizezoneequipment calls setupzonesizingarrays
managezoneequipment calls sizezoneequipment