SizeUnitarySystem – EnergyPlusFortran
SizeUnitarySystem Subroutine
1571 statements
Source File
private subroutine SizeUnitarySystem(UnitarySysNum, FirstHVACIteration, AirLoopNum)
Uses:
BranchInputManager
DataAirSystems
CurveManager
DXCoils
Fans
HVACHXAssistedCoolingCoil
ReportSizingManager
VariableSpeedCoils
WatertoAirHeatPump
WatertoAirHeatPumpSimple
PlantUtilities
InputProcessor
General
WaterCoils
Psychrometrics
HVACDXSystem
EMSManager
DataGlobals
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UnitarySysNum
logical, intent(in) :: FirstHVACIteration
integer, intent(in) :: AirLoopNum
Calls
Called By
Source Code
SizeUnitarySystem
Source Code
SUBROUTINE SizeUnitarySystem(UnitarySysNum, FirstHVACIteration, AirLoopNum)
          ! SUBROUTINE INFORMATION:
          !       AUTHOR         Richard Raustad, FSEC
          !       DATE WRITTEN   February 2013
          !       MODIFIED       na
          !       RE-ENGINEERED  na
          ! PURPOSE OF THIS SUBROUTINE:
          ! This subroutine is for sizing unitary system components for which nominal cpacities
          ! and flow rates have not been specified in the input. Coil sizing is preformed in the coil module.
          ! Future modifications will size coils here and "push" this info to the specific coil.
          ! METHODOLOGY EMPLOYED:
          ! Obtains heating capacities and flow rates from the zone or system sizing arrays.
          !
          ! NOTE: In UNITARYSYSTEM:HEATPUMP:AIRTOAIR we are sizing the heating capacity to be
          ! equal to the cooling capacity.  Thus the cooling and
          ! and heating capacities of a DX heat pump system will be identical. In real life the ARI
          ! heating and cooling capacities are close but not identical.
          ! REFERENCES:
          ! na
          ! USE STATEMENTS:
  USE BranchInputManager,        ONLY: CheckSystemBranchFlow, GetAirBranchIndex, GetBranchFanTypeName, GetBranchFlow
  USE DataAirSystems,            ONLY: PrimaryAirSystem
  USE CurveManager,              ONLY: CurveValue
  USE DXCoils,                   ONLY: SimDXCoil, SimDXCoilMultiSpeed, GetCoilCapacityByIndexType, &
                                       GetDXCoilCapFTCurveIndex !, SetDXCoolingCoilData
  USE Fans,                      ONLY: GetFanDesignVolumeFlowRate
  USE HVACHXAssistedCoolingCoil, ONLY: SimHXAssistedCoolingCoil,GetCoilCapacity,GetHXDXCoilName,GetCoilObjectTypeNum
  USE ReportSizingManager,       ONLY: ReportSizingOutput
  USE VariableSpeedCoils,        ONLY: SimVariableSpeedCoils, VarSpeedCoil, GetCoilCapacityVariableSpeed
  USE WatertoAirHeatPump,        ONLY: SimWaterToAirHP,GetWAHPCoilCapacity=>GetCoilCapacity
  USE WatertoAirHeatPumpSimple,  ONLY: SimWatertoAirHPSimple,GetSimpleCoilCapacity=>GetCoilCapacity
  USE PlantUtilities,            ONLY: RegisterPlantCompDesignFlow
  USE InputProcessor,            ONLY: SameString, FindItemInList,MakeUPPERCase
  USE General,                   ONLY: TrimSigDigits
  USE WaterCoils,                ONLY: SetCoilDesFlow,GetWaterCoilCapacity
  USE Psychrometrics
  USE HVACDXSystem,              ONLY: GetCoolingCoilTypeNameAndIndex
  USE EMSManager,                ONLY: ManageEMS
  USE DataGlobals,               ONLY: emsCallFromUnitarySystemSizing
  IMPLICIT NONE    ! Enforce explicit typing of all variables in this routine
          ! SUBROUTINE ARGUMENT DEFINITIONS:
  INTEGER, INTENT(IN) :: UnitarySysNum
  LOGICAL, INTENT(IN) :: FirstHVACIteration
  INTEGER, INTENT(IN) :: AirLoopNum ! does this need to be optional?
          ! SUBROUTINE PARAMETER DEFINITIONS:
  CHARACTER(len=*), PARAMETER ::  RoutineName='SizeUnitarySystem'
  REAL(r64), PARAMETER ::    MaxRatedVolFlowPerRatedTotCap1 = 0.00006041d0 ! m3/s per watt = 450 cfm/ton
  REAL(r64), PARAMETER ::    MinRatedVolFlowPerRatedTotCap1 = 0.00004027d0 ! m3/s per watt = 300 cfm/ton
          ! INTERFACE BLOCK SPECIFICATIONS
          ! na
          ! DERIVED TYPE DEFINITIONS
          ! na
          ! SUBROUTINE LOCAL VARIABLE DECLARATIONS:
  INTEGER   :: ThisCtrlZoneNum    ! the controlled zone number of the control zone !!!
  INTEGER   :: Iter               ! iteration count
  REAL(r64) :: MulSpeedFlowScale  ! variable speed air flow scaling factor
  INTEGER   :: MSHPIndex          ! Index to design Specification object
  INTEGER   :: BranchNum          ! Index to branch on air loop
  INTEGER   :: CompNum            ! Index to component on branch
  REAL(r64) :: BranchFlow         ! branch flow rate [m3/s]
  REAL(r64) :: BranchFanFlow      ! branch fan flow rate [m3/s]
  LOGICAL   :: ErrFound           ! logical error flag
  CHARACTER(len=MaxNameLength) :: FanType  ! fan type
  CHARACTER(len=MaxNameLength) :: FanName  ! fan name
  INTEGER   :: DXHeatCoilBranch   ! branch where DX heating coil is located
  INTEGER   :: DXHeatCoilCompNum  ! comp number of DX heating coil on branch
  INTEGER   :: CoolUnitarySystemNum ! index to unitary system with DX cooling coil
  INTEGER   :: CoolCoilIndex      ! index to DX cooling coil
  INTEGER   :: CoolCoilType       ! type of DX cooling coil
  CHARACTER(len=MaxNameLength) :: CoolCoilName ! name of DX cooling coil
  REAL(r64) :: rhoair             ! air density [kg/m3]
  REAL(r64) :: CpAirStd           ! air specific heat [J/kg-k]
  REAL(r64) :: MixTemp            ! mixed air temp used for sizing [C]
  REAL(r64) :: MixHumRat          ! mixed air humidity ratio used for sizing [kg/kg]
  REAL(r64) :: MixEnth            ! mixed air enthalpy used for sizing [J/kg]
  REAL(r64) :: MixWetBulb         ! mixed air wet bulb temp used for sizing [C]
  REAL(r64) :: SupTemp            ! supply air temp used for sizing [C]
  REAL(r64) :: SupHumRat          ! supply air humidity ratio used for sizing [kg/kg]
  REAL(r64) :: SupEnth            ! supply air enthalpy used for sizing [J/kg]
  REAL(r64) :: OutTemp            ! outdoor air temp used for sizing [C]
  REAL(r64) :: OutAirFrac         ! fraction of outdoor air flow
  REAL(r64) :: VolFlowRate        ! volumetric flow rate [m3/s]
  REAL(r64) :: CoolCapAtPeak      ! cooling capacity at peak [W]
  REAL(r64) :: HeatCapAtPeak      ! heating capacity at peak [W]
  INTEGER   :: TimeStepNumAtMax   ! time step at peak
  INTEGER   :: DDNum              ! design day index at peak
  REAL(r64) :: TotCapTempModFac   ! capacity modifier used for sizing
  REAL(r64) :: RatedVolFlowPerRatedTotCap !Rated Air Volume Flow Rate divided by Rated Total Capacity[m3/s-W)
  CHARACTER(len=MaxNameLength) :: SystemType ! type of air loop equipment
  REAL(r64) :: OnOffAirFlowRatio  ! used to pass to cooling coil for sizing
  REAL(r64) :: PartLoadRatio      ! used to pass to cooling coil for sizing
  INTEGER   :: CapFTCurve         ! index to DX coil Capacity as a function of Temperature curve
  LOGICAL   :: TempCoolingLoad    ! size cooling coils with a cooling load, save actual load
  LOGICAL   :: TempHeatingLoad    ! save actual load
  REAL(r64) :: SysCoolingFlow     ! individually sized cooling flow rate [m3/s]
  REAL(r64) :: SysHeatingFlow     ! individually sized heating flow rate [m3/s]
  CHARACTER(len=MaxNameLength) :: HXCoilName         ! cooling coil name in HXAssisted parent
  INTEGER :: ActualCoolCoilType ! cooling coil type in HXAssisted parent
  CALL ManageEMS(emsCallFromUnitarySystemSizing) ! calling point
  ThisCtrlZoneNum = 0
  DXCoolCap = 0.0d0
  UnitaryHeatCap = 0.0d0
  SuppHeatCap = 0.0d0
  TempCoolingLoad = CoolingLoad
  TempHeatingLoad = HeatingLoad
  CoolingLoad = .TRUE.
  HeatingLoad = .FALSE.
  ZoneCoolingOnlyFan = .FALSE.
  ZoneHeatingOnlyFan = .FALSE.
  SysCoolingFlow = 0.0d0
  SysHeatingFlow = 0.0d0
  CoolCapAtPeak = 0.0d0
  HeatCapAtPeak = 0.0d0
!  IF(UnitarySystem(UnitarySysNum)%CoolCoilExists)THEN
!    IF(
!    UnitarySystem(UnitarySysNum)%DesignCoolingCapacity =    &
!     GetWaterHXAssistedCoilCapacity(CoolingCoilType,CoolingCoilName,ErrFlag)
!    IF(UnitarySystem(UnitarySysNum)%DesignCoolingCapacity == Autosize) &
!        UnitarySystem(UnitarySysNum)%RequestAutosize = .TRUE.
!    IF (ErrFlag) THEN
!      CALL ShowContinueError('Occurs in '//TRIM(CurrentModuleObject)//' = '//TRIM(UnitarySystem(UnitarySysNum)%Name))
!      ErrorsFound=.TRUE.
!    END IF
!  END IF
  IF ((CurOASysNum > 0 .OR. CurSysNum > 0) .AND. UnitarySystem(UnitarySysNum)%RequestAutosize) THEN
    CALL CheckSysSizing(UnitarySystem(UnitarySysNum)%UnitarySystemType, UnitarySystem(UnitarySysNum)%Name)
  ELSE IF(CurZoneEqNum > 0)THEN
    CALL CheckZoneSizing(UnitarySystem(UnitarySysNum)%UnitarySystemType, UnitarySystem(UnitarySysNum)%Name)
  END IF
  IF(UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow /= AutoSize) &
    SysCoolingFlow = UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
  IF(UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow /= AutoSize) &
    SysHeatingFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
  IF(UnitarySystem(UnitarySysNum)%RequestAutosize)THEN
  IF (CurOASysNum > 0) THEN
!    CALL CheckSysSizing(UnitarySystem(UnitarySysNum)%UnitarySystemType, UnitarySystem(UnitarySysNum)%Name)
    IF(UnitarySystem(UnitarySysNum)%CoolCoilExists .AND. .NOT. UnitarySystem(UnitarySysNum)%HeatCoilExists)THEN
      SELECT CASE(UnitarySystem(UnitarySysNum)%CoolingSAFMethod)
        CASE (SupplyAirFlowRate, None)
          IF(UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow == Autosize)THEN
            SysCoolingFlow = FinalSysSizing(CurSysNum)%DesOutAirVolFlow
          ELSE
            SysCoolingFlow = UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
          END IF
          OASysEqSizing(CurOASysNum)%AirFlow = .TRUE.
          OASysEqSizing(CurOASysNum)%AirVolFlow = SysCoolingFlow
        CASE (FlowPerFloorArea)
          SysCoolingFlow = UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
          UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = Autosize
          OASysEqSizing(CurOASysNum)%AirFlow = .TRUE.
          OASysEqSizing(CurOASysNum)%AirVolFlow = SysCoolingFlow
        CASE (FractionOfAutosizedCoolingValue)
          SysCoolingFlow = FinalSysSizing(CurSysNum)%DesOutAirVolFlow * &
                           UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
          UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = Autosize
          OASysEqSizing(CurOASysNum)%AirFlow = .TRUE.
          OASysEqSizing(CurOASysNum)%AirVolFlow = SysCoolingFlow
        CASE (FlowPerCoolingCapacity)
          VolFlowRate = FinalSysSizing(CurSysNum)%DesOutAirVolFlow
          MixTemp = FinalSysSizing(CurSysNum)%CoolOutTemp
          MixHumRat = FinalSysSizing(CurSysNum)%CoolOutHumRat
          SupTemp = FinalSysSizing(CurSysNum)%PrecoolTemp
          SupHumRat = FinalSysSizing(CurSysNum)%PrecoolHumRat
          OutTemp = FinalSysSizing(CurSysNum)%CoolOutTemp
          rhoair = PsyRhoAirFnPbTdbW(StdBaroPress,MixTemp,MixHumRat,RoutineName)
          MixEnth = PsyHFnTdbW(MixTemp,MixHumRat,RoutineName)
          MixWetBulb = PsyTwbFnTdbWPb(MixTemp,MixHumRat,StdBaroPress,RoutineName)
          SupEnth = PsyHFnTdbW(SupTemp,SupHumRat,RoutineName)
          IF(UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_CoolingSingleSpeed .OR. &
             UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_MultiSpeedCooling .OR. &
             UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_CoolingTwoSpeed .OR. &
             UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_CoolingTwoStageWHumControl)THEN
              CapFTCurve = GetDXCoilCapFTCurveIndex(UnitarySystem(UnitarySysNum)%CoolingCoilIndex,ErrFound)
            TotCapTempModFac = CurveValue(CapFTCurve,MixWetBulb,OutTemp)
          ELSE
            TotCapTempModFac = 1.0d0
          END IF
          CoolCapAtPeak = MAX(0.d0, (rhoair * VolFlowRate * (MixEnth-SupEnth)))
          IF(TotCapTempModFac .GT. 0.d0)THEN
            CoolCapAtPeak = CoolCapAtPeak / TotCapTempModFac
          END IF
          SysCoolingFlow = CoolCapAtPeak * UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
          UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = Autosize
          OASysEqSizing(CurOASysNum)%AirFlow = .TRUE.
          OASysEqSizing(CurOASysNum)%AirVolFlow = SysCoolingFlow
          OASysEqSizing(CurOASysNum)%Capacity = .TRUE.
          OASysEqSizing(CurOASysNum)%DesCoolingLoad = CoolCapAtPeak
        CASE DEFAULT
          IF(UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow == Autosize)THEN
            SysCoolingFlow = FinalSysSizing(CurSysNum)%DesOutAirVolFlow
          ELSE
            SysCoolingFlow = UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
          END IF
      END SELECT
    ELSE IF(UnitarySystem(UnitarySysNum)%HeatCoilExists .AND. .NOT. UnitarySystem(UnitarySysNum)%CoolCoilExists)THEN
      SELECT CASE(UnitarySystem(UnitarySysNum)%HeatingSAFMethod)
        CASE (SupplyAirFlowRate, None)
          IF(UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow == Autosize)THEN
            SysHeatingFlow = FinalSysSizing(CurSysNum)%DesOutAirVolFlow
          ELSE
            SysHeatingFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
          END IF
          OASysEqSizing(CurOASysNum)%AirFlow = .TRUE.
          OASysEqSizing(CurOASysNum)%AirVolFlow = SysHeatingFlow
        CASE (FlowPerFloorArea)
          SysHeatingFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
          UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = Autosize
          OASysEqSizing(CurOASysNum)%AirFlow = .TRUE.
          OASysEqSizing(CurOASysNum)%AirVolFlow = SysHeatingFlow
        CASE (FractionOfAutosizedCoolingValue)
          SysHeatingFlow = FinalSysSizing(CurSysNum)%DesOutAirVolFlow * &
                           UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
          UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = Autosize
          OASysEqSizing(CurOASysNum)%AirFlow = .TRUE.
          OASysEqSizing(CurOASysNum)%AirVolFlow = SysHeatingFlow
        CASE (FlowPerHeatingCapacity)
          VolFlowRate = FinalSysSizing(CurSysNum)%DesOutAirVolFlow
          MixTemp = FinalSysSizing(CurSysNum)%HeatOutTemp
          MixHumRat = FinalSysSizing(CurSysNum)%HeatOutHumRat
          SupTemp = FinalSysSizing(CurSysNum)%PrecoolTemp
          SupHumRat = FinalSysSizing(CurSysNum)%PrecoolHumRat
          OutTemp = FinalSysSizing(CurSysNum)%HeatOutTemp
          rhoair = PsyRhoAirFnPbTdbW(StdBaroPress,MixTemp,MixHumRat,RoutineName)
          MixEnth = PsyHFnTdbW(MixTemp,MixHumRat,RoutineName)
          MixWetBulb = PsyTwbFnTdbWPb(MixTemp,MixHumRat,StdBaroPress,RoutineName)
          SupEnth = PsyHFnTdbW(SupTemp,SupHumRat,RoutineName)
          IF(UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == CoilDX_MultiSpeedHeating .OR. &
             UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == CoilDX_HeatingEmpirical)THEN
              CapFTCurve = GetDXCoilCapFTCurveIndex(UnitarySystem(UnitarySysNum)%HeatingCoilIndex,ErrFound)
            TotCapTempModFac = CurveValue(CapFTCurve,MixWetBulb,OutTemp)
          ELSE
            TotCapTempModFac = 1.0d0
          END IF
          HeatCapAtPeak = MAX(0.d0, (rhoair * VolFlowRate * (SupEnth-MixEnth)))
          IF(TotCapTempModFac .GT. 0.d0)THEN
            HeatCapAtPeak = HeatCapAtPeak / TotCapTempModFac
          END IF
          SysHeatingFlow = HeatCapAtPeak * UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
          UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = Autosize
          OASysEqSizing(CurOASysNum)%AirFlow = .TRUE.
          OASysEqSizing(CurOASysNum)%AirVolFlow = SysCoolingFlow
          OASysEqSizing(CurOASysNum)%Capacity = .TRUE.
          OASysEqSizing(CurOASysNum)%DesCoolingLoad = HeatCapAtPeak
        CASE DEFAULT
          IF(UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow == Autosize)THEN
            SysHeatingFlow = FinalSysSizing(CurSysNum)%DesOutAirVolFlow
          ELSE
            SysHeatingFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
          END IF
          OASysEqSizing(CurOASysNum)%AirFlow = .TRUE.
          OASysEqSizing(CurOASysNum)%AirVolFlow = SysCoolingFlow
      END SELECT
    ELSE ! Cooling and Heating coil are present
      SELECT CASE(UnitarySystem(UnitarySysNum)%CoolingSAFMethod)
        CASE (SupplyAirFlowRate, None)
          IF(UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow == Autosize)THEN
            SysCoolingFlow = FinalSysSizing(CurSysNum)%DesOutAirVolFlow
          ELSE
            SysCoolingFlow = UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
          END IF
          OASysEqSizing(CurOASysNum)%AirFlow = .TRUE.
        CASE (FlowPerFloorArea)
          SysCoolingFlow = MAX(UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow, &
                               UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow)
          UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = Autosize
          OASysEqSizing(CurOASysNum)%AirFlow = .TRUE.
        CASE (FractionOfAutosizedCoolingValue)
          SysCoolingFlow = FinalSysSizing(CurSysNum)%DesOutAirVolFlow * &
              MAX(UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow, UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow)
          UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = SysCoolingFlow
          OASysEqSizing(CurOASysNum)%AirFlow = .TRUE.
        CASE (FlowPerCoolingCapacity)
          VolFlowRate = FinalSysSizing(CurSysNum)%DesOutAirVolFlow
          MixTemp = FinalSysSizing(CurSysNum)%CoolOutTemp
          MixHumRat = FinalSysSizing(CurSysNum)%CoolOutHumRat
          SupTemp = FinalSysSizing(CurSysNum)%PrecoolTemp
          SupHumRat = FinalSysSizing(CurSysNum)%PrecoolHumRat
          OutTemp = FinalSysSizing(CurSysNum)%CoolOutTemp
          rhoair = PsyRhoAirFnPbTdbW(StdBaroPress,MixTemp,MixHumRat,RoutineName)
          MixEnth = PsyHFnTdbW(MixTemp,MixHumRat,RoutineName)
          MixWetBulb = PsyTwbFnTdbWPb(MixTemp,MixHumRat,StdBaroPress,RoutineName)
          SupEnth = PsyHFnTdbW(SupTemp,SupHumRat,RoutineName)
          IF(UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_CoolingSingleSpeed .OR. &
             UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_MultiSpeedCooling .OR. &
             UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_CoolingTwoSpeed .OR. &
             UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_CoolingTwoStageWHumControl)THEN
              CapFTCurve = GetDXCoilCapFTCurveIndex(UnitarySystem(UnitarySysNum)%CoolingCoilIndex,ErrFound)
            TotCapTempModFac = CurveValue(CapFTCurve,MixWetBulb,OutTemp)
          ELSE
            TotCapTempModFac = 1.0d0
          END IF
          CoolCapAtPeak = MAX(0.d0, (rhoair * VolFlowRate * (MixEnth-SupEnth)))
          IF(TotCapTempModFac .GT. 0.d0)THEN
            CoolCapAtPeak = CoolCapAtPeak / TotCapTempModFac
          END IF
          SysCoolingFlow = CoolCapAtPeak * UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
          UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = Autosize
          OASysEqSizing(CurOASysNum)%AirFlow = .TRUE.
          OASysEqSizing(CurOASysNum)%Capacity = .TRUE.
        CASE DEFAULT
          IF(UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow == Autosize)THEN
            SysCoolingFlow = FinalSysSizing(CurSysNum)%DesOutAirVolFlow
          ELSE
            SysCoolingFlow = UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
          END IF
          OASysEqSizing(CurOASysNum)%AirFlow = .TRUE.
      END SELECT
      SELECT CASE(UnitarySystem(UnitarySysNum)%HeatingSAFMethod)
        CASE (SupplyAirFlowRate, None)
          IF(UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow == Autosize)THEN
            SysHeatingFlow = FinalSysSizing(CurSysNum)%DesOutAirVolFlow
          ELSE
            SysHeatingFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
          END IF
          OASysEqSizing(CurOASysNum)%AirFlow = .TRUE.
        CASE (FlowPerFloorArea)
          SysHeatingFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
          UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = Autosize
          OASysEqSizing(CurOASysNum)%AirFlow = .TRUE.
        CASE (FractionOfAutosizedCoolingValue)
          SysHeatingFlow = FinalSysSizing(CurSysNum)%DesOutAirVolFlow * &
              UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
          UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = SysHeatingFlow
          OASysEqSizing(CurOASysNum)%AirFlow = .TRUE.
        CASE (FlowPerHeatingCapacity)
          VolFlowRate = FinalSysSizing(CurSysNum)%DesOutAirVolFlow
          MixTemp = FinalSysSizing(CurSysNum)%HeatOutTemp
          MixHumRat = FinalSysSizing(CurSysNum)%HeatOutHumRat
          SupTemp = FinalSysSizing(CurSysNum)%PrecoolTemp
          SupHumRat = FinalSysSizing(CurSysNum)%PrecoolHumRat
          OutTemp = FinalSysSizing(CurSysNum)%HeatOutTemp
          rhoair = PsyRhoAirFnPbTdbW(StdBaroPress,MixTemp,MixHumRat,RoutineName)
          MixEnth = PsyHFnTdbW(MixTemp,MixHumRat,RoutineName)
          MixWetBulb = PsyTwbFnTdbWPb(MixTemp,MixHumRat,StdBaroPress,RoutineName)
          SupEnth = PsyHFnTdbW(SupTemp,SupHumRat,RoutineName)
          IF(UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == CoilDX_MultiSpeedHeating .OR. &
             UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == CoilDX_HeatingEmpirical)THEN
              CapFTCurve = GetDXCoilCapFTCurveIndex(UnitarySystem(UnitarySysNum)%HeatingCoilIndex,ErrFound)
            TotCapTempModFac = CurveValue(CapFTCurve,MixWetBulb,OutTemp)
          ELSE
            TotCapTempModFac = 1.0d0
          END IF
          HeatCapAtPeak = MAX(0.d0, (rhoair * VolFlowRate * (SupEnth-MixEnth)))
          IF(TotCapTempModFac .GT. 0.d0)THEN
            HeatCapAtPeak = HeatCapAtPeak / TotCapTempModFac
          END IF
          SysHeatingFlow = HeatCapAtPeak * UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
          UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = Autosize
          OASysEqSizing(CurOASysNum)%AirFlow = .TRUE.
          OASysEqSizing(CurOASysNum)%Capacity = .TRUE.
        CASE DEFAULT
          IF(UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow == Autosize)THEN
            SysHeatingFlow = FinalSysSizing(CurSysNum)%DesOutAirVolFlow
          ELSE
            SysHeatingFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
          END IF
          OASysEqSizing(CurOASysNum)%AirFlow = .TRUE.
      END SELECT
      OASysEqSizing(CurOASysNum)%AirVolFlow = MAX(SysCoolingFlow,SysHeatingFlow)
      OASysEqSizing(CurOASysNum)%DesHeatingLoad = MAX(CoolCapAtPeak,HeatCapAtPeak)
    END IF
  ELSE
    IF (CurSysNum > 0) THEN
!      CALL CheckSysSizing(UnitarySystem(UnitarySysNum)%UnitarySystemType, UnitarySystem(UnitarySysNum)%Name)
      IF(UnitarySystem(UnitarySysNum)%CoolCoilExists .AND. .NOT. UnitarySystem(UnitarySysNum)%HeatCoilExists)THEN
        SELECT CASE(UnitarySystem(UnitarySysNum)%CoolingSAFMethod)
          CASE (SupplyAirFlowRate, None)
            IF(UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow == Autosize)THEN
              SysCoolingFlow = FinalSysSizing(CurSysNum)%DesMainVolFlow
            ELSE
              SysCoolingFlow = UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
            END IF
            UnitarySysEqSizing(CurSysNum)%AirFlow = .TRUE.
            UnitarySysEqSizing(CurSysNum)%AirVolFlow = SysCoolingFlow
          CASE (FlowPerFloorArea)
            SysCoolingFlow = UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
            UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = Autosize
            UnitarySysEqSizing(CurSysNum)%AirFlow = .TRUE.
            UnitarySysEqSizing(CurSysNum)%AirVolFlow = SysCoolingFlow
          CASE (FractionOfAutosizedCoolingValue)
            SysCoolingFlow = FinalSysSizing(CurSysNum)%DesMainVolFlow * &
                             UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
            UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = Autosize
            UnitarySysEqSizing(CurSysNum)%AirFlow = .TRUE.
            UnitarySysEqSizing(CurSysNum)%AirVolFlow = SysCoolingFlow
          CASE (FlowPerCoolingCapacity)
            VolFlowRate = FinalSysSizing(CurSysNum)%DesMainVolFlow
            SupTemp = FinalSysSizing(CurSysNum)%CoolSupTemp
            SupHumRat = FinalSysSizing(CurSysNum)%CoolSupHumRat
            IF (PrimaryAirSystem(CurSysNum)%NumOACoolCoils == 0) THEN ! there is no precooling of the OA stream
              MixTemp = FinalSysSizing(CurSysNum)%CoolMixTemp
              MixHumRat = FinalSysSizing(CurSysNum)%CoolMixHumRat
            ELSE ! there is precooling of OA stream
              IF (VolFlowRate > 0.0d0) THEN
                OutAirFrac = FinalSysSizing(CurSysNum)%DesOutAirVolFlow / VolFlowRate
              ELSE
                OutAirFrac = 1.0d0
              END IF
              OutAirFrac = MIN(1.0d0,MAX(0.0d0,OutAirFrac))
              MixTemp = OutAirFrac*FinalSysSizing(CurSysNum)%PrecoolTemp + &
                          (1.0d0-OutAirFrac)*FinalSysSizing(CurSysNum)%CoolRetTemp
              MixHumRat = OutAirFrac*FinalSysSizing(CurSysNum)%PrecoolHumRat + &
                            (1.0d0-OutAirFrac)*FinalSysSizing(CurSysNum)%CoolRetHumRat
            END IF
            OutTemp = FinalSysSizing(CurSysNum)%CoolOutTemp
            rhoair = PsyRhoAirFnPbTdbW(StdBaroPress,MixTemp,MixHumRat,RoutineName)
            MixEnth = PsyHFnTdbW(MixTemp,MixHumRat,RoutineName)
            MixWetBulb = PsyTwbFnTdbWPb(MixTemp,MixHumRat,StdBaroPress,RoutineName)
            SupEnth = PsyHFnTdbW(SupTemp,SupHumRat,RoutineName)
            IF(UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_CoolingSingleSpeed .OR. &
               UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_MultiSpeedCooling .OR. &
               UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_CoolingTwoSpeed .OR. &
               UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_CoolingTwoStageWHumControl)THEN
                CapFTCurve = GetDXCoilCapFTCurveIndex(UnitarySystem(UnitarySysNum)%CoolingCoilIndex,ErrFound)
              TotCapTempModFac = CurveValue(CapFTCurve,MixWetBulb,OutTemp)
            ELSE
              TotCapTempModFac = 1.0d0
            END IF
            CoolCapAtPeak = MAX(0.d0, (rhoair * VolFlowRate * (MixEnth-SupEnth)))
            IF(TotCapTempModFac .GT. 0.d0)THEN
              CoolCapAtPeak = CoolCapAtPeak / TotCapTempModFac
            END IF
            SysCoolingFlow = CoolCapAtPeak * UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
            UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = Autosize
            UnitarySysEqSizing(CurSysNum)%AirFlow = .TRUE.
            UnitarySysEqSizing(CurSysNum)%AirVolFlow = SysCoolingFlow
            UnitarySysEqSizing(CurSysNum)%Capacity = .TRUE.
            UnitarySysEqSizing(CurSysNum)%DesCoolingLoad = CoolCapAtPeak
          CASE DEFAULT
            IF(UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow == Autosize)THEN
              SysCoolingFlow = FinalSysSizing(CurSysNum)%DesMainVolFlow
            ELSE
              SysCoolingFlow = UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
            END IF
            UnitarySysEqSizing(CurSysNum)%AirFlow = .TRUE.
            UnitarySysEqSizing(CurSysNum)%AirVolFlow = SysCoolingFlow
        END SELECT
      ELSE IF(UnitarySystem(UnitarySysNum)%HeatCoilExists .AND. .NOT. UnitarySystem(UnitarySysNum)%CoolCoilExists)THEN
        SELECT CASE(UnitarySystem(UnitarySysNum)%HeatingSAFMethod)
          CASE (SupplyAirFlowRate)
            IF(UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow == Autosize)THEN
              SysHeatingFlow = FinalSysSizing(CurSysNum)%DesMainVolFlow
            ELSE
              SysHeatingFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
            END IF
            UnitarySysEqSizing(CurSysNum)%AirFlow = .TRUE.
            UnitarySysEqSizing(CurSysNum)%AirVolFlow = SysHeatingFlow
          CASE (FlowPerFloorArea)
            SysHeatingFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
            UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = Autosize
            UnitarySysEqSizing(CurSysNum)%AirFlow = .TRUE.
            UnitarySysEqSizing(CurSysNum)%AirVolFlow = SysHeatingFlow
          CASE (FractionOfAutosizedCoolingValue)
            SysHeatingFlow = FinalSysSizing(CurSysNum)%DesMainVolFlow * &
                             UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
            UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = Autosize
            UnitarySysEqSizing(CurSysNum)%AirFlow = .TRUE.
            UnitarySysEqSizing(CurSysNum)%AirVolFlow = SysHeatingFlow
          CASE (FlowPerHeatingCapacity)
            VolFlowRate = FinalSysSizing(CurSysNum)%DesMainVolFlow
            SupTemp = FinalSysSizing(CurSysNum)%HeatSupTemp
            SupHumRat = FinalSysSizing(CurSysNum)%HeatSupHumRat
            IF (PrimaryAirSystem(CurSysNum)%NumOACoolCoils == 0) THEN ! there is no precooling of the OA stream
              MixTemp = FinalSysSizing(CurSysNum)%HeatMixTemp
              MixHumRat = FinalSysSizing(CurSysNum)%HeatMixHumRat
            ELSE ! there is precooling of OA stream
              IF (VolFlowRate > 0.0d0) THEN
                OutAirFrac = FinalSysSizing(CurSysNum)%DesOutAirVolFlow / VolFlowRate
              ELSE
                OutAirFrac = 1.0d0
              END IF
              OutAirFrac = MIN(1.0d0,MAX(0.0d0,OutAirFrac))
              MixTemp = OutAirFrac*FinalSysSizing(CurSysNum)%PrecoolTemp + &
                          (1.0d0-OutAirFrac)*FinalSysSizing(CurSysNum)%HeatRetTemp
              MixHumRat = OutAirFrac*FinalSysSizing(CurSysNum)%PrecoolHumRat + &
                            (1.0d0-OutAirFrac)*FinalSysSizing(CurSysNum)%HeatRetHumRat
            END IF
            OutTemp = FinalSysSizing(CurSysNum)%HeatOutTemp
            rhoair = PsyRhoAirFnPbTdbW(StdBaroPress,MixTemp,MixHumRat,RoutineName)
            MixEnth = PsyHFnTdbW(MixTemp,MixHumRat,RoutineName)
            MixWetBulb = PsyTwbFnTdbWPb(MixTemp,MixHumRat,StdBaroPress,RoutineName)
            SupEnth = PsyHFnTdbW(SupTemp,SupHumRat,RoutineName)
            IF(UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == CoilDX_MultiSpeedHeating .OR. &
               UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == CoilDX_HeatingEmpirical)THEN
                CapFTCurve = GetDXCoilCapFTCurveIndex(UnitarySystem(UnitarySysNum)%HeatingCoilIndex,ErrFound)
              TotCapTempModFac = CurveValue(CapFTCurve,MixWetBulb,OutTemp)
            ELSE
              TotCapTempModFac = 1.0d0
            END IF
            HeatCapAtPeak = MAX(0.d0, (rhoair * VolFlowRate * (SupEnth-MixEnth)))
            IF(TotCapTempModFac .GT. 0.d0)THEN
              HeatCapAtPeak = HeatCapAtPeak / TotCapTempModFac
            END IF
            SysHeatingFlow = HeatCapAtPeak * UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
            UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = Autosize
            UnitarySysEqSizing(CurSysNum)%AirFlow = .TRUE.
            UnitarySysEqSizing(CurSysNum)%AirVolFlow = SysHeatingFlow
            UnitarySysEqSizing(CurSysNum)%Capacity = .TRUE.
            UnitarySysEqSizing(CurSysNum)%DesHeatingLoad = HeatCapAtPeak
          CASE DEFAULT
            IF(UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow == Autosize)THEN
              SysHeatingFlow = FinalSysSizing(CurSysNum)%DesMainVolFlow
            ELSE
              SysHeatingFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
            END IF
            UnitarySysEqSizing(CurSysNum)%AirFlow = .TRUE.
            UnitarySysEqSizing(CurSysNum)%AirVolFlow = SysHeatingFlow
        END SELECT
      ELSE ! Cooling and Heating coil are present
        SELECT CASE(UnitarySystem(UnitarySysNum)%CoolingSAFMethod)
          CASE (SupplyAirFlowRate, None)
            IF(UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow == Autosize)THEN
              SysCoolingFlow = FinalSysSizing(CurSysNum)%DesMainVolFlow
            ELSE
              SysCoolingFlow = UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
            END IF
            UnitarySysEqSizing(CurSysNum)%AirFlow = .TRUE.
          CASE (FlowPerFloorArea)
            SysCoolingFlow = MAX(UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow, &
                                 UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow)
            UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = Autosize
            UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = Autosize
            UnitarySysEqSizing(CurSysNum)%AirFlow = .TRUE.
          CASE (FractionOfAutosizedCoolingValue)
            SysCoolingFlow = FinalSysSizing(CurSysNum)%DesMainVolFlow * &
                MAX(UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow, UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow)
            UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = Autosize
            UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = Autosize
            UnitarySysEqSizing(CurSysNum)%AirFlow = .TRUE.
          CASE (FlowPerCoolingCapacity)
            VolFlowRate = FinalSysSizing(CurSysNum)%DesMainVolFlow
            SupTemp = FinalSysSizing(CurSysNum)%CoolSupTemp
            SupHumRat = FinalSysSizing(CurSysNum)%CoolSupHumRat
            IF (PrimaryAirSystem(CurSysNum)%NumOACoolCoils == 0) THEN ! there is no precooling of the OA stream
              MixTemp = FinalSysSizing(CurSysNum)%CoolMixTemp
              MixHumRat = FinalSysSizing(CurSysNum)%CoolMixHumRat
            ELSE ! there is precooling of OA stream
              IF (VolFlowRate > 0.0d0) THEN
                OutAirFrac = FinalSysSizing(CurSysNum)%DesMainVolFlow / VolFlowRate
              ELSE
                OutAirFrac = 1.0d0
              END IF
              OutAirFrac = MIN(1.0d0,MAX(0.0d0,OutAirFrac))
              MixTemp = OutAirFrac*FinalSysSizing(CurSysNum)%PrecoolTemp + &
                          (1.0d0-OutAirFrac)*FinalSysSizing(CurSysNum)%CoolRetTemp
              MixHumRat = OutAirFrac*FinalSysSizing(CurSysNum)%PrecoolHumRat + &
                            (1.0d0-OutAirFrac)*FinalSysSizing(CurSysNum)%CoolRetHumRat
            END IF
            OutTemp = FinalSysSizing(CurSysNum)%CoolOutTemp
            rhoair = PsyRhoAirFnPbTdbW(StdBaroPress,MixTemp,MixHumRat,RoutineName)
            MixEnth = PsyHFnTdbW(MixTemp,MixHumRat,RoutineName)
            MixWetBulb = PsyTwbFnTdbWPb(MixTemp,MixHumRat,StdBaroPress,RoutineName)
            SupEnth = PsyHFnTdbW(SupTemp,SupHumRat,RoutineName)
            IF(UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_CoolingSingleSpeed .OR. &
               UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_MultiSpeedCooling .OR. &
               UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_CoolingTwoSpeed .OR. &
               UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_CoolingTwoStageWHumControl)THEN
              CapFTCurve = GetDXCoilCapFTCurveIndex(UnitarySystem(UnitarySysNum)%CoolingCoilIndex,ErrFound)
              TotCapTempModFac = CurveValue(CapFTCurve,MixWetBulb,OutTemp)
            ELSE
              TotCapTempModFac = 1.0d0
            END IF
            CoolCapAtPeak = MAX(0.d0, (rhoair * VolFlowRate * (MixEnth-SupEnth)))
            IF(TotCapTempModFac .GT. 0.d0)THEN
              CoolCapAtPeak = CoolCapAtPeak / TotCapTempModFac
            END IF
            SysCoolingFlow = CoolCapAtPeak * UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
            UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = Autosize
            UnitarySysEqSizing(CurSysNum)%AirFlow = .TRUE.
            UnitarySysEqSizing(CurSysNum)%Capacity = .TRUE.
          CASE DEFAULT
            IF(UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow == Autosize)THEN
              SysCoolingFlow = FinalSysSizing(CurSysNum)%DesMainVolFlow
            ELSE
              SysCoolingFlow = UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
            END IF
            UnitarySysEqSizing(CurSysNum)%AirFlow = .TRUE.
        END SELECT
        SELECT CASE(UnitarySystem(UnitarySysNum)%HeatingSAFMethod)
          CASE (SupplyAirFlowRate)
            IF(UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow == Autosize)THEN
              SysHeatingFlow = FinalSysSizing(CurSysNum)%DesMainVolFlow
            ELSE
              SysHeatingFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
            END IF
            UnitarySysEqSizing(CurSysNum)%AirFlow = .TRUE.
          CASE (FlowPerFloorArea)
            SysHeatingFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
            UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = Autosize
            UnitarySysEqSizing(CurSysNum)%AirFlow = .TRUE.
          CASE (FractionOfAutosizedCoolingValue)
            SysHeatingFlow = FinalSysSizing(CurSysNum)%DesMainVolFlow * &
                             UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
            UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = Autosize
            UnitarySysEqSizing(CurSysNum)%AirFlow = .TRUE.
          CASE (FlowPerHeatingCapacity)
            VolFlowRate = FinalSysSizing(CurSysNum)%DesMainVolFlow
            SupTemp = FinalSysSizing(CurSysNum)%HeatSupTemp
            SupHumRat = FinalSysSizing(CurSysNum)%HeatSupHumRat
            IF (PrimaryAirSystem(CurSysNum)%NumOACoolCoils == 0) THEN ! there is no precooling of the OA stream
              MixTemp = FinalSysSizing(CurSysNum)%HeatMixTemp
              MixHumRat = FinalSysSizing(CurSysNum)%HeatMixHumRat
            ELSE ! there is precooling of OA stream
              IF (VolFlowRate > 0.0d0) THEN
                OutAirFrac = FinalSysSizing(CurSysNum)%DesMainVolFlow / VolFlowRate
              ELSE
                OutAirFrac = 1.0d0
              END IF
              OutAirFrac = MIN(1.0d0,MAX(0.0d0,OutAirFrac))
              MixTemp = OutAirFrac*FinalSysSizing(CurSysNum)%PrecoolTemp + &
                          (1.0d0-OutAirFrac)*FinalSysSizing(CurSysNum)%HeatRetTemp
              MixHumRat = OutAirFrac*FinalSysSizing(CurSysNum)%PrecoolHumRat + &
                            (1.0d0-OutAirFrac)*FinalSysSizing(CurSysNum)%HeatRetHumRat
            END IF
            OutTemp = FinalSysSizing(CurSysNum)%HeatOutTemp
            rhoair = PsyRhoAirFnPbTdbW(StdBaroPress,MixTemp,MixHumRat,RoutineName)
            MixEnth = PsyHFnTdbW(MixTemp,MixHumRat,RoutineName)
            MixWetBulb = PsyTwbFnTdbWPb(MixTemp,MixHumRat,StdBaroPress,RoutineName)
            SupEnth = PsyHFnTdbW(SupTemp,SupHumRat,RoutineName)
            IF(UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == CoilDX_MultiSpeedHeating .OR. &
               UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == CoilDX_HeatingEmpirical)THEN
              CapFTCurve = GetDXCoilCapFTCurveIndex(UnitarySystem(UnitarySysNum)%HeatingCoilIndex,ErrFound)
              TotCapTempModFac = CurveValue(CapFTCurve,MixWetBulb,OutTemp)
            ELSE
              TotCapTempModFac = 1.0d0
            END IF
            HeatCapAtPeak = MAX(0.d0, (rhoair * VolFlowRate * (SupEnth-MixEnth)))
            IF(TotCapTempModFac .GT. 0.d0)THEN
              HeatCapAtPeak = HeatCapAtPeak / TotCapTempModFac
            END IF
            SysHeatingFlow = HeatCapAtPeak * UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
            UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = Autosize
            UnitarySysEqSizing(CurSysNum)%AirFlow = .TRUE.
            UnitarySysEqSizing(CurSysNum)%Capacity = .TRUE.
          CASE DEFAULT
            IF(UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow == Autosize)THEN
              SysHeatingFlow = FinalSysSizing(CurSysNum)%DesMainVolFlow
            ELSE
              SysHeatingFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
            END IF
            UnitarySysEqSizing(CurSysNum)%AirFlow = .TRUE.
        END SELECT
        UnitarySysEqSizing(CurSysNum)%AirVolFlow = MAX(SysCoolingFlow,SysHeatingFlow)
        UnitarySysEqSizing(CurSysNum)%DesCoolingLoad = MAX(CoolCapAtPeak,HeatCapAtPeak)
      END IF
    ELSEIF (CurZoneEqNum > 0) THEN
      ! if we keep this (zone equipment) then we should probably check to see IF a cooling/heating coil is present
      ! and use just cooling if only a cooling coil, or just heating if only a heating coil
!      CALL CheckZoneSizing(UnitarySystem(UnitarySysNum)%UnitarySystemType, UnitarySystem(UnitarySysNum)%Name)
       IF(UnitarySystem(UnitarySysNum)%CoolCoilExists .AND. .NOT. UnitarySystem(UnitarySysNum)%HeatCoilExists)THEN
         ZoneCoolingOnlyFan = .TRUE.
         SELECT CASE(UnitarySystem(UnitarySysNum)%CoolingSAFMethod)
           CASE (SupplyAirFlowRate)
            IF(UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow == Autosize)THEN
              SysCoolingFlow = FinalZoneSizing(CurZoneEqNum)%DesCoolVolFlow
            ELSE
              SysCoolingFlow = UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
            END IF
            ZoneEqSizing(CurZoneEqNum)%AirFlow = .TRUE.
            ZoneEqSizing(CurZoneEqNum)%AirVolFlow = SysCoolingFlow
           CASE (FlowPerFloorArea)
             SysCoolingFlow = UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
             UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = Autosize
             ZoneEqSizing(CurZoneEqNum)%AirFlow = .TRUE.
             ZoneEqSizing(CurZoneEqNum)%AirVolFlow = SysCoolingFlow
           CASE (FractionOfAutosizedCoolingValue)
             SysCoolingFlow = FinalZoneSizing(CurZoneEqNum)%DesCoolVolFlow * &
                              UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
             UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = Autosize
             ZoneEqSizing(CurZoneEqNum)%AirFlow = .TRUE.
             ZoneEqSizing(CurZoneEqNum)%AirVolFlow = SysCoolingFlow
           CASE (FlowPerCoolingCapacity)
             VolFlowRate = FinalZoneSizing(CurZoneEqNum)%DesCoolVolFlow
             IF(ZoneEqDXCoil)THEN
               IF (ZoneEqSizing(CurZoneEqNum)%OAVolFlow > 0.0d0) THEN
                 MixTemp = FinalZoneSizing(CurZoneEqNum)%DesCoolCoilInTemp
                 MixHumRat = FinalZoneSizing(CurZoneEqNum)%DesCoolCoilInHumRat
               ELSE
                 MixTemp = FinalZoneSizing(CurZoneEqNum)%ZoneRetTempAtCoolPeak
                 MixHumRat = FinalZoneSizing(CurZoneEqNum)%ZoneHumRatAtCoolPeak
               END IF
             ELSE
               MixTemp = FinalZoneSizing(CurZoneEqNum)%DesCoolCoilInTemp
               MixHumRat = FinalZoneSizing(CurZoneEqNum)%DesCoolCoilInHumRat
             END IF
             SupTemp = FinalZoneSizing(CurZoneEqNum)%CoolDesTemp
             SupHumRat = FinalZoneSizing(CurZoneEqNum)%CoolDesHumRat
             TimeStepNumAtMax = FinalZoneSizing(CurZoneEqNum)%TimeStepNumAtCoolMax
             DDNum = FinalZoneSizing(CurZoneEqNum)%CoolDDNum
             IF (DDNum > 0 .and. TimeStepNumAtMax > 0) THEN
               OutTemp = DesDayWeath(DDNum)%Temp(TimeStepNumAtMax)
             ELSE
               OutTemp = 0.0d0
             END IF
             rhoair = PsyRhoAirFnPbTdbW(StdBaroPress,MixTemp,MixHumRat,RoutineName)
             MixEnth = PsyHFnTdbW(MixTemp,MixHumRat,RoutineName)
             MixWetBulb = PsyTwbFnTdbWPb(MixTemp,MixHumRat,StdBaroPress,RoutineName)
             SupEnth = PsyHFnTdbW(SupTemp,SupHumRat,RoutineName)
             IF(UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_CoolingSingleSpeed .OR. &
                UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_MultiSpeedCooling .OR. &
                UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_CoolingTwoSpeed .OR. &
                UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_CoolingTwoStageWHumControl)THEN
               CapFTCurve = GetDXCoilCapFTCurveIndex(UnitarySystem(UnitarySysNum)%CoolingCoilIndex,ErrFound)
               TotCapTempModFac = CurveValue(CapFTCurve,MixWetBulb,OutTemp)
             ELSE
               TotCapTempModFac = 1.0d0
             END IF
             CoolCapAtPeak = MAX(0.d0, (rhoair * VolFlowRate * (MixEnth-SupEnth)))
             IF(TotCapTempModFac .GT. 0.d0)THEN
               CoolCapAtPeak = CoolCapAtPeak / TotCapTempModFac
             END IF
             SysCoolingFlow = CoolCapAtPeak * UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
             UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = Autosize
             ZoneEqSizing(CurZoneEqNum)%AirFlow = .TRUE.
             ZoneEqSizing(CurZoneEqNum)%AirVolFlow = SysCoolingFlow
             ZoneEqSizing(CurZoneEqNum)%Capacity = .TRUE.
             ZoneEqSizing(CurZoneEqNum)%DesCoolingLoad = CoolCapAtPeak
           CASE DEFAULT
            IF(UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow == Autosize)THEN
              SysCoolingFlow = FinalZoneSizing(CurZoneEqNum)%DesCoolVolFlow
            ELSE
              SysCoolingFlow = UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
            END IF
            ZoneEqSizing(CurZoneEqNum)%AirFlow = .TRUE.
            ZoneEqSizing(CurZoneEqNum)%AirVolFlow = SysCoolingFlow
         END SELECT
       ELSE IF(UnitarySystem(UnitarySysNum)%HeatCoilExists .AND. .NOT. UnitarySystem(UnitarySysNum)%CoolCoilExists)THEN
         ZoneHeatingOnlyFan = .TRUE.
        SELECT CASE(UnitarySystem(UnitarySysNum)%HeatingSAFMethod)
          CASE (SupplyAirFlowRate)
            IF(UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow == Autosize)THEN
              SysHeatingFlow = FinalZoneSizing(CurZoneEqNum)%DesHeatVolFlow
            ELSE
              SysHeatingFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
            END IF
            ZoneEqSizing(CurZoneEqNum)%AirFlow = .TRUE.
            ZoneEqSizing(CurZoneEqNum)%AirVolFlow = SysHeatingFlow
          CASE (FlowPerFloorArea)
            SysHeatingFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
            UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = Autosize
            ZoneEqSizing(CurZoneEqNum)%AirFlow = .TRUE.
            ZoneEqSizing(CurZoneEqNum)%AirVolFlow = SysHeatingFlow
          CASE (FractionOfAutosizedCoolingValue)
            SysHeatingFlow = FinalZoneSizing(CurZoneEqNum)%DesHeatVolFlow * &
                             UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
            UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = Autosize
            ZoneEqSizing(CurZoneEqNum)%AirFlow = .TRUE.
            ZoneEqSizing(CurZoneEqNum)%AirVolFlow = SysHeatingFlow
          CASE (FlowPerHeatingCapacity)
            VolFlowRate = FinalZoneSizing(CurZoneEqNum)%DesHeatVolFlow
            IF(ZoneEqDXCoil)THEN
              IF (ZoneEqSizing(CurZoneEqNum)%OAVolFlow > 0.0d0) THEN
                MixTemp = FinalZoneSizing(CurZoneEqNum)%DesHeatCoilInTemp
                MixHumRat = FinalZoneSizing(CurZoneEqNum)%DesHeatCoilInHumRat
              ELSE
                MixTemp = FinalZoneSizing(CurZoneEqNum)%ZoneRetTempAtHeatPeak
                MixHumRat = FinalZoneSizing(CurZoneEqNum)%ZoneHumRatAtHeatPeak
              END IF
            ELSE
              MixTemp = FinalZoneSizing(CurZoneEqNum)%DesHeatCoilInTemp
              MixHumRat = FinalZoneSizing(CurZoneEqNum)%DesHeatCoilInHumRat
            END IF
            SupTemp = FinalZoneSizing(CurZoneEqNum)%HeatDesTemp
            SupHumRat = FinalZoneSizing(CurZoneEqNum)%HeatDesHumRat
            TimeStepNumAtMax = FinalZoneSizing(CurZoneEqNum)%TimeStepNumAtHeatMax
            DDNum = FinalZoneSizing(CurZoneEqNum)%HeatDDNum
            IF (DDNum > 0 .and. TimeStepNumAtMax > 0) THEN
              OutTemp = DesDayWeath(DDNum)%Temp(TimeStepNumAtMax)
            ELSE
              OutTemp = 0.0d0
            END IF
            rhoair = PsyRhoAirFnPbTdbW(StdBaroPress,MixTemp,MixHumRat,RoutineName)
            MixEnth = PsyHFnTdbW(MixTemp,MixHumRat,RoutineName)
            MixWetBulb = PsyTwbFnTdbWPb(MixTemp,MixHumRat,StdBaroPress,RoutineName)
            SupEnth = PsyHFnTdbW(SupTemp,SupHumRat,RoutineName)
            IF(UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == CoilDX_MultiSpeedHeating .OR. &
               UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == CoilDX_HeatingEmpirical)THEN
              CapFTCurve = GetDXCoilCapFTCurveIndex(UnitarySystem(UnitarySysNum)%HeatingCoilIndex,ErrFound)
              TotCapTempModFac = CurveValue(CapFTCurve,MixWetBulb,OutTemp)
            ELSE
              TotCapTempModFac = 1.0d0
            END IF
            HeatCapAtPeak = MAX(0.d0, (rhoair * VolFlowRate * (SupEnth-MixEnth)))
            IF(TotCapTempModFac .GT. 0.d0)THEN
              HeatCapAtPeak = HeatCapAtPeak / TotCapTempModFac
            END IF
            SysHeatingFlow = HeatCapAtPeak * UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
            UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = Autosize
            ZoneEqSizing(CurZoneEqNum)%AirFlow = .TRUE.
            ZoneEqSizing(CurZoneEqNum)%AirVolFlow = SysHeatingFlow
            ZoneEqSizing(CurZoneEqNum)%Capacity = .TRUE.
            ZoneEqSizing(CurZoneEqNum)%DesHeatingLoad = HeatCapAtPeak
          CASE DEFAULT
            IF(UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow == Autosize)THEN
              SysHeatingFlow = FinalZoneSizing(CurZoneEqNum)%DesHeatVolFlow
            ELSE
              SysHeatingFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
            END IF
            ZoneEqSizing(CurZoneEqNum)%AirFlow = .TRUE.
            ZoneEqSizing(CurZoneEqNum)%AirVolFlow = SysHeatingFlow
        END SELECT
      ELSE
        SELECT CASE(UnitarySystem(UnitarySysNum)%CoolingSAFMethod)
          CASE (SupplyAirFlowRate, None)
            IF(UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow == Autosize)THEN
              SysCoolingFlow = FinalZoneSizing(CurZoneEqNum)%DesCoolVolFlow
            ELSE
              SysCoolingFlow = UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
            END IF
            ZoneEqSizing(CurZoneEqNum)%AirFlow = .TRUE.
          CASE (FlowPerFloorArea)
            SysCoolingFlow = UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
            UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = Autosize ! allow reporting for sizing
            ZoneEqSizing(CurZoneEqNum)%AirFlow = .TRUE.
          CASE (FractionOfAutosizedCoolingValue)
            SysCoolingFlow = UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow * FinalZoneSizing(CurZoneEqNum)%DesCoolVolFlow
            UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = Autosize
            ZoneEqSizing(CurZoneEqNum)%AirFlow = .TRUE.
          CASE (FlowPerCoolingCapacity)
            VolFlowRate = FinalZoneSizing(CurZoneEqNum)%DesCoolVolFlow
            IF(ZoneEqDXCoil)THEN
              IF (ZoneEqSizing(CurZoneEqNum)%OAVolFlow > 0.0d0) THEN
                MixTemp = FinalZoneSizing(CurZoneEqNum)%DesCoolCoilInTemp
                MixHumRat = FinalZoneSizing(CurZoneEqNum)%DesCoolCoilInHumRat
              ELSE
                MixTemp = FinalZoneSizing(CurZoneEqNum)%ZoneRetTempAtCoolPeak
                MixHumRat = FinalZoneSizing(CurZoneEqNum)%ZoneHumRatAtCoolPeak
              END IF
            ELSE
              MixTemp = FinalZoneSizing(CurZoneEqNum)%DesCoolCoilInTemp
              MixHumRat = FinalZoneSizing(CurZoneEqNum)%DesCoolCoilInHumRat
            END IF
            SupTemp = FinalZoneSizing(CurZoneEqNum)%CoolDesTemp
            SupHumRat = FinalZoneSizing(CurZoneEqNum)%CoolDesHumRat
            TimeStepNumAtMax = FinalZoneSizing(CurZoneEqNum)%TimeStepNumAtCoolMax
            DDNum = FinalZoneSizing(CurZoneEqNum)%CoolDDNum
            IF (DDNum > 0 .and. TimeStepNumAtMax > 0) THEN
              OutTemp = DesDayWeath(DDNum)%Temp(TimeStepNumAtMax)
            ELSE
              OutTemp = 0.0d0
            END IF
            rhoair = PsyRhoAirFnPbTdbW(StdBaroPress,MixTemp,MixHumRat,RoutineName)
            MixEnth = PsyHFnTdbW(MixTemp,MixHumRat,RoutineName)
            MixWetBulb = PsyTwbFnTdbWPb(MixTemp,MixHumRat,StdBaroPress,RoutineName)
            SupEnth = PsyHFnTdbW(SupTemp,SupHumRat,RoutineName)
            IF(UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_CoolingSingleSpeed .OR. &
               UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_MultiSpeedCooling .OR. &
               UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_CoolingTwoSpeed .OR. &
               UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilDX_CoolingTwoStageWHumControl)THEN
              CapFTCurve = GetDXCoilCapFTCurveIndex(UnitarySystem(UnitarySysNum)%CoolingCoilIndex,ErrFound)
              TotCapTempModFac = CurveValue(CapFTCurve,MixWetBulb,OutTemp)
            ELSE
              TotCapTempModFac = 1.0d0
            END IF
            CoolCapAtPeak = MAX(0.d0, (rhoair * VolFlowRate * (MixEnth-SupEnth)))
            IF(TotCapTempModFac .GT. 0.d0)THEN
              CoolCapAtPeak = CoolCapAtPeak / TotCapTempModFac
            END IF
            SysCoolingFlow = CoolCapAtPeak * UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
            UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = Autosize
            ZoneEqSizing(CurZoneEqNum)%AirFlow = .TRUE.
            ZoneEqSizing(CurZoneEqNum)%Capacity = .TRUE.
          CASE DEFAULT
            IF(UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow == Autosize)THEN
              SysCoolingFlow = FinalZoneSizing(CurZoneEqNum)%DesCoolVolFlow
            ELSE
              SysCoolingFlow = UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow
            END IF
            ZoneEqSizing(CurZoneEqNum)%AirFlow = .TRUE.
        END SELECT
        SELECT CASE(UnitarySystem(UnitarySysNum)%HeatingSAFMethod)
          CASE (SupplyAirFlowRate)
            IF(UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow == Autosize)THEN
              SysHeatingFlow = FinalZoneSizing(CurZoneEqNum)%DesHeatVolFlow
            ELSE
              SysHeatingFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
            END IF
            ZoneEqSizing(CurZoneEqNum)%AirFlow = .TRUE.
          CASE (FlowPerFloorArea)
            SysHeatingFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
            UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = Autosize
            ZoneEqSizing(CurZoneEqNum)%AirFlow = .TRUE.
          CASE (FractionOfAutosizedCoolingValue)
            SysHeatingFlow = FinalZoneSizing(CurZoneEqNum)%DesHeatVolFlow * &
                             UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
            UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = Autosize
            ZoneEqSizing(CurZoneEqNum)%AirFlow = .TRUE.
          CASE (FlowPerHeatingCapacity)
            VolFlowRate = FinalZoneSizing(CurZoneEqNum)%DesHeatVolFlow
            IF(ZoneEqDXCoil)THEN
              IF (ZoneEqSizing(CurZoneEqNum)%OAVolFlow > 0.0d0) THEN
                MixTemp = FinalZoneSizing(CurZoneEqNum)%DesHeatCoilInTemp
                MixHumRat = FinalZoneSizing(CurZoneEqNum)%DesHeatCoilInHumRat
              ELSE
                MixTemp = FinalZoneSizing(CurZoneEqNum)%ZoneRetTempAtHeatPeak
                MixHumRat = FinalZoneSizing(CurZoneEqNum)%ZoneHumRatAtHeatPeak
              END IF
            ELSE
              MixTemp = FinalZoneSizing(CurZoneEqNum)%DesHeatCoilInTemp
              MixHumRat = FinalZoneSizing(CurZoneEqNum)%DesHeatCoilInHumRat
            END IF
            SupTemp = FinalZoneSizing(CurZoneEqNum)%HeatDesTemp
            SupHumRat = FinalZoneSizing(CurZoneEqNum)%HeatDesHumRat
            TimeStepNumAtMax = FinalZoneSizing(CurZoneEqNum)%TimeStepNumAtHeatMax
            DDNum = FinalZoneSizing(CurZoneEqNum)%HeatDDNum
            IF (DDNum > 0 .and. TimeStepNumAtMax > 0) THEN
              OutTemp = DesDayWeath(DDNum)%Temp(TimeStepNumAtMax)
            ELSE
              OutTemp = 0.0d0
            END IF
            rhoair = PsyRhoAirFnPbTdbW(StdBaroPress,MixTemp,MixHumRat,RoutineName)
            MixEnth = PsyHFnTdbW(MixTemp,MixHumRat,RoutineName)
            MixWetBulb = PsyTwbFnTdbWPb(MixTemp,MixHumRat,StdBaroPress,RoutineName)
            SupEnth = PsyHFnTdbW(SupTemp,SupHumRat,RoutineName)
            IF(UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == CoilDX_MultiSpeedHeating .OR. &
               UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == CoilDX_HeatingEmpirical)THEN
              CapFTCurve = GetDXCoilCapFTCurveIndex(UnitarySystem(UnitarySysNum)%HeatingCoilIndex,ErrFound)
              TotCapTempModFac = CurveValue(CapFTCurve,MixWetBulb,OutTemp)
            ELSE
              TotCapTempModFac = 1.0d0
            END IF
            HeatCapAtPeak = MAX(0.d0, (rhoair * VolFlowRate * (SupEnth-MixEnth)))
            IF(TotCapTempModFac .GT. 0.d0)THEN
              HeatCapAtPeak = HeatCapAtPeak / TotCapTempModFac
            END IF
            SysHeatingFlow = HeatCapAtPeak * UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
            UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = Autosize
            ZoneEqSizing(CurZoneEqNum)%AirFlow = .TRUE.
            ZoneEqSizing(CurZoneEqNum)%Capacity = .TRUE.
          CASE DEFAULT
            IF(UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow == Autosize)THEN
              SysHeatingFlow = FinalZoneSizing(CurZoneEqNum)%DesHeatVolFlow
            ELSE
              SysHeatingFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
            END IF
            ZoneEqSizing(CurZoneEqNum)%AirFlow = .TRUE.
        END SELECT
        ZoneEqSizing(CurZoneEqNum)%AirVolFlow = MAX(SysCoolingFlow,SysHeatingFlow)
        ZoneEqSizing(CurZoneEqNum)%DesCoolingLoad = MAX(CoolCapAtPeak,HeatCapAtPeak)
      END IF
    END IF
  END IF
  END IF ! IF(UnitarySystem(UnitarySysNum)%RequestAutosize)THEN
! Not sure yet how to enforce heat pump cooling/heating air flow and capacity limits.
! Other checks are in place (e.g., DXCoolCap) to already account for heat pump DX coils but apply to all coil types.
! This method would actually size the HP to the larger of cooling or heating but not yet ready to implement.
!  IF(UnitarySystem(UnitarySysNum)%HeatPump .AND. UnitarySystem(UnitarySysNum)%RequestAutosize)THEN
!    IF(UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow == Autosize .AND. &
!       UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow == Autosize)THEN
!      IF(CurOASysNum > 0)THEN
!        IF(OASysEqSizing(CurOASysNum)%AirFlow .AND. .NOT. OASysEqSizing(CurOASysNum)%Capacity)THEN
!          SysCoolingFlow = MAX(SysCoolingFlow,SysHeatingFlow)
!          SysHeatingFlow = SysCoolingFlow
!          OASysEqSizing(CurOASysNum)%AirVolFlow = SysCoolingFlow
!        ELSE IF(OASysEqSizing(CurOASysNum)%Capacity)THEN
!          SysCoolingFlow = MAX(SysCoolingFlow,SysHeatingFlow)
!          SysHeatingFlow = SysCoolingFlow
!          OASysEqSizing(CurOASysNum)%AirVolFlow = SysCoolingFlow
!          CoolCapAtPeak = MAX(CoolCapAtPeak,HeatCapAtPeak)
!          HeatCapAtPeak = CoolCapAtPeak
!          OASysEqSizing(CurOASysNum)%DesCoolingLoad = CoolCapAtPeak
!          OASysEqSizing(CurOASysNum)%DesHeatingLoad = CoolCapAtPeak * UnitarySystem(UnitarySysNum)%HeatingSizingRatio
!        END IF
!      ELSE IF(CurSysNum > 0)THEN
!        IF(UnitarySysEqSizing(CurSysNum)%AirFlow .AND. .NOT. UnitarySysEqSizing(CurSysNum)%Capacity)THEN
!          SysCoolingFlow = MAX(SysCoolingFlow,SysHeatingFlow)
!          SysHeatingFlow = SysCoolingFlow
!          UnitarySysEqSizing(CurSysNum)%AirVolFlow = SysCoolingFlow
!        ELSE IF(UnitarySysEqSizing(CurSysNum)%Capacity)THEN
!          SysCoolingFlow = MAX(SysCoolingFlow,SysHeatingFlow)
!          SysHeatingFlow = SysCoolingFlow
!          UnitarySysEqSizing(CurSysNum)%AirVolFlow = SysCoolingFlow
!          CoolCapAtPeak = MAX(CoolCapAtPeak,HeatCapAtPeak)
!          HeatCapAtPeak = CoolCapAtPeak
!          UnitarySysEqSizing(CurSysNum)%DesCoolingLoad = CoolCapAtPeak
!          UnitarySysEqSizing(CurSysNum)%DesHeatingLoad = CoolCapAtPeak * UnitarySystem(UnitarySysNum)%HeatingSizingRatio
!        END IF
!      ELSE IF(CurZoneEqNum > 0)THEN
!        IF(ZoneEqSizing(CurZoneEqNum)%AirFlow .AND. .NOT. ZoneEqSizing(CurZoneEqNum)%Capacity)THEN
!          SysCoolingFlow = MAX(SysCoolingFlow,SysHeatingFlow)
!          SysHeatingFlow = SysCoolingFlow
!          ZoneEqSizing(CurZoneEqNum)%AirVolFlow = SysCoolingFlow
!        ELSE IF(ZoneEqSizing(CurZoneEqNum)%Capacity)THEN
!          SysCoolingFlow = MAX(SysCoolingFlow,SysHeatingFlow)
!          SysHeatingFlow = SysCoolingFlow
!          ZoneEqSizing(CurZoneEqNum)%AirVolFlow = SysCoolingFlow
!          CoolCapAtPeak = MAX(CoolCapAtPeak,HeatCapAtPeak)
!          HeatCapAtPeak = CoolCapAtPeak
!          ZoneEqSizing(CurZoneEqNum)%DesCoolingLoad = CoolCapAtPeak
!          ZoneEqSizing(CurZoneEqNum)%DesHeatingLoad = CoolCapAtPeak * UnitarySystem(UnitarySysNum)%HeatingSizingRatio
!        END IF
!      END IF
!    END IF
!  END IF
  IF (UnitarySystem(UnitarySysNum)%DesignFanVolFlowRate == AutoSize .AND. &
      UnitarySystem(UnitarySysNum)%FanExists) THEN
    UnitarySystem(UnitarySysNum)%DesignFanVolFlowRate = MAX(SysCoolingFlow,SysHeatingFlow)
    IF (UnitarySystem(UnitarySysNum)%DesignFanVolFlowRateEMSOverrideOn) THEN
      UnitarySystem(UnitarySysNum)%DesignFanVolFlowRate = UnitarySystem(UnitarySysNum)%DesignFanVolFlowRateEMSOverrideValue
    END IF
    IF(UnitarySystem(UnitarySysNum)%DesignFanVolFlowRate < SmallAirVolFlow) THEN
      UnitarySystem(UnitarySysNum)%DesignFanVolFlowRate = 0.0d0
    END IF
    CALL ReportSizingOutput(UnitarySystem(UnitarySysNum)%UnitarySystemType, UnitarySystem(UnitarySysNum)%Name, &
                            'Supply Air Flow Rate [m3/s]', &
                             UnitarySystem(UnitarySysNum)%DesignFanVolFlowRate)
  END IF
  ! not sure what to do if UnitarySystem has only 1 coil type and flow needs to occur when present coil is off
  ! how does constant fan operating mode pertain here?
  IF(UnitarySystem(UnitarySysNum)%HeatCoilExists .AND. .NOT. UnitarySystem(UnitarySysNum)%CoolCoilExists)THEN
    UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = SysHeatingFlow
  ELSE IF(UnitarySystem(UnitarySysNum)%CoolCoilExists .AND. .NOT. UnitarySystem(UnitarySysNum)%HeatCoilExists)THEN
    UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = SysCoolingFlow
  END IF
    IF (UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow == AutoSize .AND. &
      UnitarySystem(UnitarySysNum)%HeatCoilExists) THEN
    IF (CurOASysNum > 0) THEN
      IF(OASysEqSizing(CurOASysNum)%AirFlow)THEN
        UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = OASysEqSizing(CurOASysNum)%AirVolFlow
      ELSE
        UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = FinalSysSizing(CurSysNum)%DesOutAirVolFlow
      END IF
      IF (UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow < SmallAirVolFlow) THEN
        UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = 0.0d0
      END IF
    ELSE
      IF (CurSysNum > 0) THEN
        IF(UnitarySysEqSizing(CurSysNum)%AirFlow)THEN
          UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = UnitarySysEqSizing(CurSysNum)%AirVolFlow
        ELSE
          UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = FinalSysSizing(CurSysNum)%DesMainVolFlow
        END IF
        IF (FinalSysSizing(CurSysNum)%DesMainVolFlow < SmallAirVolFlow) THEN
          UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = 0.0d0
        END IF
        IF (UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlowEMSOverrideOn) THEN
          UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlowEMSOverrideValue
        END IF
      ELSEIF (CurZoneEqNum > 0) THEN
        ! if we keep this (zone equipment) then we should probably check to see if a cooling/heating coil is present
        ! and use just cooling if only a cooling coil, or just heating if only a heating coil
        IF(ZoneEqSizing(CurZoneEqNum)%AirFlow)THEN
          UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = ZoneEqSizing(CurZoneEqNum)%AirVolFlow
        ELSE
          UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow =   &
                 MAX(FinalZoneSizing(CurZoneEqNum)%DesCoolVolFlow,FinalZoneSizing(CurZoneEqNum)%DesHeatVolFlow)
        END IF
        IF (UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow < SmallAirVolFlow) THEN
          UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = 0.0d0
        END IF
        IF (UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlowEMSOverrideOn) THEN
          UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlowEMSOverrideValue
        END IF
      END IF
    END IF
    CALL ReportSizingOutput(UnitarySystem(UnitarySysNum)%UnitarySystemType, UnitarySystem(UnitarySysNum)%Name, &
                            'Supply Air Flow Rate During Heating Operation [m3/s]', &
                            UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow)
  END IF
  IF (UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow == AutoSize .AND. &
      UnitarySystem(UnitarySysNum)%CoolCoilExists) THEN
    IF (CurOASysNum > 0) THEN
      IF(OASysEqSizing(CurOASysNum)%AirFlow)THEN
        UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = OASysEqSizing(CurOASysNum)%AirVolFlow
      ELSE
        UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = FinalSysSizing(CurSysNum)%DesOutAirVolFlow
      END IF
    ELSE
      IF (CurSysNum > 0) THEN
        IF(UnitarySysEqSizing(CurSysNum)%AirFlow)THEN
          UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = UnitarySysEqSizing(CurSysNum)%AirVolFlow
        ELSE
          UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = FinalSysSizing(CurSysNum)%DesMainVolFlow
        END IF
        IF (UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow < SmallAirVolFlow) THEN
          UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = 0.0d0
        END IF
        IF (UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlowEMSOverrideOn) THEN
          UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlowEMSOverrideValue
        END IF
      ELSEIF (CurZoneEqNum > 0) THEN
        ! if we keep this (zone equipment) then we should probably check to see if a cooling/heating coil is present
        ! and use just cooling if only a cooling coil, or just heating if only a heating coil
        IF(ZoneEqSizing(CurZoneEqNum)%AirFlow)THEN
          UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = ZoneEqSizing(CurZoneEqNum)%AirVolFlow
        ELSE
          UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow =   &
                 MAX(FinalZoneSizing(CurZoneEqNum)%DesCoolVolFlow,FinalZoneSizing(CurZoneEqNum)%DesHeatVolFlow)
        END IF
        IF (UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow < SmallAirVolFlow) THEN
          UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = 0.0d0
        END IF
        IF (UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlowEMSOverrideOn) THEN
          UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlowEMSOverrideValue
        END IF
      END IF
    END IF
    CALL ReportSizingOutput(UnitarySystem(UnitarySysNum)%UnitarySystemType, UnitarySystem(UnitarySysNum)%Name, &
                            'Supply Air Flow Rate During Cooling Operation [m3/s]', &
                             UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow)
  END IF
  IF (UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow == AutoSize .AND. &
      (UnitarySystem(UnitarySysNum)%CoolCoilExists .OR. &
       (UnitarySystem(UnitarySysNum)%HeatCoilExists .OR. UnitarySystem(UnitarySysNum)%SuppCoilExists))) THEN
    IF (CurOASysNum > 0) THEN
      IF(OASysEqSizing(CurOASysNum)%AirFlow)THEN
        UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow = OASysEqSizing(CurOASysNum)%AirVolFlow
      ELSE
        UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow = FinalSysSizing(CurSysNum)%DesOutAirVolFlow
      END IF
    ELSE
      IF (CurSysNum > 0) THEN
        IF(UnitarySysEqSizing(CurSysNum)%AirFlow)THEN
          UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow = UnitarySysEqSizing(CurSysNum)%AirVolFlow
        ELSE
          UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow = FinalSysSizing(CurSysNum)%DesMainVolFlow
        END IF
        IF (UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow < SmallAirVolFlow) THEN
          UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow = 0.0d0
        END IF
        IF (UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlowEMSOverrideOn) THEN
          UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow=UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlowEMSOverrideValue
        END IF
        CALL ReportSizingOutput(UnitarySystem(UnitarySysNum)%UnitarySystemType, UnitarySystem(UnitarySysNum)%Name, &
                               'Supply Air Flow Rate When No Cooling or Heating is Needed [m3/s]', &
                                UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow)
      ELSEIF (CurZoneEqNum > 0) THEN
        ! if we keep this (zone equipment) then we should probably check to see if a cooling/heating coil is present
        ! and use just cooling if only a cooling coil, or just heating if only a heating coil
!        CALL CheckZoneSizing(UnitarySystem(UnitarySysNum)%UnitarySystemType, UnitarySystem(UnitarySysNum)%Name)
!  would use this to size cooling or heating only systems except for the case where dual UnitarySystems are on the branch
!  and each has only 1 cooling or heating coil ??? How to handle?
!  Use same logic for other flow rates in this sizing module.
        IF(UnitarySystem(UnitarySysNum)%CoolCoilExists .AND. UnitarySystem(UnitarySysNum)%HeatCoilExists)THEN
          UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow =   &
                 MAX(FinalZoneSizing(CurZoneEqNum)%DesCoolVolFlow,FinalZoneSizing(CurZoneEqNum)%DesHeatVolFlow)
        ELSE IF(UnitarySystem(UnitarySysNum)%CoolCoilExists)THEN
          UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow =   &
                 FinalZoneSizing(CurZoneEqNum)%DesCoolVolFlow
        ELSE IF(UnitarySystem(UnitarySysNum)%HeatCoilExists .OR. UnitarySystem(UnitarySysNum)%SuppCoilExists)THEN
          UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow =   &
                 FinalZoneSizing(CurZoneEqNum)%DesHeatVolFlow
        ELSE
          UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow = 0.0d0 ! ?
        END IF
        IF (UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow < SmallAirVolFlow) THEN
          UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow = 0.0d0
        END IF
        IF (UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlowEMSOverrideOn) THEN
          UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow=UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlowEMSOverrideValue
        END IF
        CALL ReportSizingOutput(UnitarySystem(UnitarySysNum)%UnitarySystemType, UnitarySystem(UnitarySysNum)%Name, &
                               'Supply Air Flow Rate When No Cooling or Heating is Needed [m3/s]', &
                                UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow)
      END IF
    END IF
  ELSE IF (UnitarySystem(UnitarySysNum)%CoolCoilExists .OR. UnitarySystem(UnitarySysNum)%HeatCoilExists) THEN
    SELECT CASE(UnitarySystem(UnitarySysNum)%NoCoolHeatSAFMethod)
      CASE (SupplyAirFlowRate)
        IF(UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow == Autosize)THEN
          IF (CurOASysNum > 0) THEN
            UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow = FinalSysSizing(CurSysNum)%DesOutAirVolFlow
          ELSE IF (CurSysNum > 0) THEN
            UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow = FinalSysSizing(CurSysNum)%DesMainVolFlow
          ELSE IF (CurZoneEqNum > 0) THEN
            IF(UnitarySystem(UnitarySysNum)%CoolCoilExists .AND. UnitarySystem(UnitarySysNum)%HeatCoilExists)THEN
              UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow = &
                MAX(FinalZoneSizing(CurZoneEqNum)%DesCoolVolFlow, FinalZoneSizing(CurZoneEqNum)%DesHeatVolFlow)
            ELSE IF(UnitarySystem(UnitarySysNum)%CoolCoilExists)THEN
              UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow = FinalZoneSizing(CurZoneEqNum)%DesCoolVolFlow
            ELSE IF(UnitarySystem(UnitarySysNum)%HeatCoilExists)THEN
              UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow = FinalZoneSizing(CurZoneEqNum)%DesHeatVolFlow
            ELSE
              ! just guessing here what this should be
              UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow = 0.0d0
            END IF
          END IF
        END IF
      CASE (FlowPerFloorArea)
        ! already calculated in GetInput
      CASE (FractionOfAutosizedCoolingValue, FractionOfAutosizedHeatingValue)
        IF (CurOASysNum > 0) THEN
          UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow = &
          UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow * FinalSysSizing(CurSysNum)%DesOutAirVolFlow
        ELSE IF (CurSysNum > 0) THEN
          UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow = &
          UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow * FinalSysSizing(CurSysNum)%DesMainVolFlow
        ELSE IF (CurZoneEqNum > 0) THEN
          IF(UnitarySystem(UnitarySysNum)%NoCoolHeatSAFMethod == FractionOfAutosizedCoolingValue)THEN
            UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow = &
              UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow * FinalZoneSizing(CurZoneEqNum)%DesCoolVolFlow
          ELSE
            UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow = &
              UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow * FinalZoneSizing(CurZoneEqNum)%DesHeatVolFlow
          END IF
        END IF
      CASE (FlowPerCoolingCapacity) ! these aren't going to work if the user doesn't choose the same method for all cases
        IF(DXCoolCap .EQ. 0.0d0)THEN
          UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow = &
            UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow * &
              ZoneEqSizing(CurZoneEqNum)%DesCoolingLoad
        ELSE
          UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow = &
            UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow * DXCoolCap
        END IF
      CASE (FlowPerHeatingCapacity)
        UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow = &
          UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow * &
            ZoneEqSizing(CurZoneEqNum)%DesHeatingLoad
      CASE (None)
        ! what does this mean?
      CASE DEFAULT
      ! wait for CR's
    END SELECT
  ELSE
    UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow = 0.0d0
  END IF
  SELECT CASE(UnitarySystem(UnitarySysNum)%CoolingCoilType_Num)
  CASE(CoilDX_CoolingSingleSpeed)
    CALL SimDXCoil(Blank,On,.TRUE.,0.0d0,UnitarySystem(UnitarySysNum)%CoolingCoilIndex, 1)
    DXCoolCap = GetCoilCapacityByIndexType(UnitarySystem(UnitarySysNum)%CoolingCoilIndex, &
                                           UnitarySystem(UnitarySysNum)%CoolingCoilType_Num,ErrFound)
  CASE(CoilDX_CoolingHXAssisted,CoilWater_CoolingHXAssisted)
    Node(UnitarySystem(UnitarySysNum)%CoolCoilInletNodeNum)%MassFlowRate = SysCoolingFlow
    IF(UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilWater_CoolingHXAssisted)THEN
      HXCoilName = GetHXDXCoilName(cAllCoilTypes(UnitarySystem(UnitarySysNum)%CoolingCoilType_Num), &
                                   UnitarySystem(UnitarySysNum)%CoolingCoilName,ErrFound)
      ActualCoolCoilType = GetCoilObjectTypeNum(cAllCoilTypes(UnitarySystem(UnitarySysNum)%CoolingCoilType_Num), &
                           UnitarySystem(UnitarySysNum)%CoolingCoilName,ErrFound,.TRUE.)
      CALL SetCoilDesFlow(cAllCoilTypes(ActualCoolCoilType),HXCoilName,SysCoolingFlow,ErrFound)
    END IF
    CALL SimHXAssistedCoolingCoil(Blank,.TRUE.,On, &
                                  1.0d0, UnitarySystem(UnitarySysNum)%CoolingCoilIndex, 1, &
                                  HXUnitEnable=.FALSE., OnOffAFR = 1.0d0, EconomizerFlag=.FALSE.)
    IF(UnitarySystem(UnitarySysNum)%CoolingCoilType_Num == CoilWater_CoolingHXAssisted)THEN
      DXCoolCap = GetWaterCoilCapacity(MakeUPPERCase(cAllCoilTypes(ActualCoolCoilType)),HXCoilName,ErrFound)
    ELSE
      DXCoolCap = GetCoilCapacity(cAllCoilTypes(UnitarySystem(UnitarySysNum)%CoolingCoilType_Num), &
                                UnitarySystem(UnitarySysNum)%CoolingCoilName,ErrFound)
    END IF
  CASE(Coil_CoolingWaterDetailed)
    CALL SetCoilDesFlow(cAllCoilTypes(UnitarySystem(UnitarySysNum)%CoolingCoilType_Num), &
                        UnitarySystem(UnitarySysNum)%CoolingCoilName,SysCoolingFlow,ErrFound)
  CASE(Coil_CoolingWaterToAirHPSimple)
    CALL SimWatertoAirHPSimple(Blank, &
           UnitarySystem(UnitarySysNum)%CoolingCoilIndex, &
           UnitarySystem(UnitarySysNum)%CoolingCoilSensDemand, UnitarySystem(UnitarySysNum)%CoolingCoilLatentDemand, &
           0,0.0d0, UnitarySystem(UnitarySysNum)%MaxONOFFCyclesperHour, &
           UnitarySystem(UnitarySysNum)%HPTimeConstant, UnitarySystem(UnitarySysNum)%FanDelayTime, &
           0,0.0d0,FirstHVACIteration)
    DXCoolCap = GetSimpleCoilCapacity(cAllCoilTypes(UnitarySystem(UnitarySysNum)%CoolingCoilType_Num), &
                                      UnitarySystem(UnitarySysNum)%CoolingCoilName,ErrFound)
  CASE(Coil_CoolingWaterToAirHP)
    CALL SimWatertoAirHP(Blank, UnitarySystem(UnitarySysNum)%CoolingCoilIndex, &
           UnitarySystem(UnitarySysNum)%MaxCoolAirMassFlow,UnitarySystem(UnitarySysNum)%FanOpMode,&
           FirstHVACIteration,0.0d0,&
           UnitarySystem(UnitarySysNum)%MaxONOFFCyclesperHour, &
           UnitarySystem(UnitarySysNum)%HPTimeConstant, &
           UnitarySystem(UnitarySysNum)%FanDelayTime, &
           UnitarySystem(UnitarySysNum)%InitHeatPump, &
           0.0d0,0.0d0,0, 0.0d0)
    DXCoolCap = GetWAHPCoilCapacity(cAllCoilTypes(UnitarySystem(UnitarySysNum)%CoolingCoilType_Num), &
                                    UnitarySystem(UnitarySysNum)%CoolingCoilName,ErrFound)
  CASE(Coil_CoolingWaterToAirHPVSEquationFit, Coil_CoolingAirToAirVariableSpeed)
    IF (UnitarySystem(UnitarySysNum)%NumOfSpeedCooling .GT. 0)THEN
      IF(.NOT. ALLOCATED(UnitarySystem(UnitarySysNum)%CoolVolumeFlowRate)) &
        ALLOCATE(UnitarySystem(UnitarySysNum)%CoolVolumeFlowRate(UnitarySystem(UnitarySysNum)%NumOfSpeedCooling))
      IF(.NOT. ALLOCATED(UnitarySystem(UnitarySysNum)%CoolMassFlowRate)) &
        ALLOCATE(UnitarySystem(UnitarySysNum)%CoolMassFlowRate(UnitarySystem(UnitarySysNum)%NumOfSpeedCooling))
      IF(.NOT. ALLOCATED(UnitarySystem(UnitarySysNum)%MSCoolingSpeedRatio)) &
        ALLOCATE(UnitarySystem(UnitarySysNum)%MSCoolingSpeedRatio(UnitarySystem(UnitarySysNum)%NumOfSpeedCooling))
    END IF
    CALL SimVariableSpeedCoils(Blank,UnitarySystem(UnitarySysNum)%CoolingCoilIndex,&
           0,UnitarySystem(UnitarySysNum)%MaxONOFFCyclesperHour, &
           UnitarySystem(UnitarySysNum)%HPTimeConstant,UnitarySystem(UnitarySysNum)%FanDelayTime,&
           0,0.0d0,0.0d0,1,0.0d0,0.0d0,0.0d0 )     !conduct the sizing operation in the VS WSHP
    UnitarySystem(UnitarySysNum)%NumOfSpeedCooling = VarSpeedCoil(UnitarySystem(UnitarySysNum)%CoolingCoilIndex)%NumOfSpeeds
    DXCoolCap = GetCoilCapacityVariableSpeed(cAllCoilTypes(UnitarySystem(UnitarySysNum)%CoolingCoilType_Num), &
                                      UnitarySystem(UnitarySysNum)%CoolingCoilName,ErrFound)
    MulSpeedFlowScale = VarSpeedCoil(UnitarySystem(UnitarySysNum)%CoolingCoilIndex)%RatedAirVolFlowRate/ &
       VarSpeedCoil(UnitarySystem(UnitarySysNum)%CoolingCoilIndex)%MSRatedAirVolFlowRate(  &
          VarSpeedCoil(UnitarySystem(UnitarySysNum)%CoolingCoilIndex)%NormSpedLevel)
    DO Iter = 1,UnitarySystem(UnitarySysNum)%NumOfSpeedCooling
      UnitarySystem(UnitarySysNum)%CoolVolumeFlowRate(Iter) =   &
         VarSpeedCoil(UnitarySystem(UnitarySysNum)%CoolingCoilIndex)%MSRatedAirVolFlowRate(Iter) * MulSpeedFlowScale
      UnitarySystem(UnitarySysNum)%CoolMassFlowRate(Iter) = UnitarySystem(UnitarySysNum)%CoolVolumeFlowRate(Iter)* StdRhoAir
! it seems the ratio should reference the actual flow rates, not the fan flow ???
      IF(UnitarySystem(UnitarySysNum)%DesignFanVolFlowRate .GT. 0.0d0 .AND. UnitarySystem(UnitarySysNum)%FanExists)THEN
        UnitarySystem(UnitarySysNum)%MSCoolingSpeedRatio(Iter) = UnitarySystem(UnitarySysNum)%CoolVolumeFlowRate(Iter)/ &
!             UnitarySystem(UnitarySysNum)%CoolVolumeFlowRate(UnitarySystem(UnitarySysNum)%NumOfSpeedCooling)
              UnitarySystem(UnitarySysNum)%DesignFanVolFlowRate
      ELSE
        UnitarySystem(UnitarySysNum)%MSCoolingSpeedRatio(Iter) = UnitarySystem(UnitarySysNum)%CoolVolumeFlowRate(Iter)/ &
             UnitarySystem(UnitarySysNum)%CoolVolumeFlowRate(UnitarySystem(UnitarySysNum)%NumOfSpeedCooling)
      END IF
    END DO
    UnitarySystem(UnitarySysNum)%IdleVolumeAirRate = UnitarySystem(UnitarySysNum)%CoolVolumeFlowRate(1)
    UnitarySystem(UnitarySysNum)%IdleMassFlowRate  = UnitarySystem(UnitarySysNum)%CoolMassFlowRate(1)
    UnitarySystem(UnitarySysNum)%IdleSpeedRatio    = UnitarySystem(UnitarySysNum)%MSCoolingSpeedRatio(1)
  CASE(CoilDX_MultiSpeedCooling)
    IF (UnitarySystem(UnitarySysNum)%NumOfSpeedCooling .GT. 0)THEN
      IF(.NOT. ALLOCATED(UnitarySystem(UnitarySysNum)%CoolVolumeFlowRate)) &
        ALLOCATE(UnitarySystem(UnitarySysNum)%CoolVolumeFlowRate(UnitarySystem(UnitarySysNum)%NumOfSpeedCooling))
      IF(.NOT. ALLOCATED(UnitarySystem(UnitarySysNum)%CoolMassFlowRate)) &
        ALLOCATE(UnitarySystem(UnitarySysNum)%CoolMassFlowRate(UnitarySystem(UnitarySysNum)%NumOfSpeedCooling))
      IF(.NOT. ALLOCATED(UnitarySystem(UnitarySysNum)%MSCoolingSpeedRatio)) &
        ALLOCATE(UnitarySystem(UnitarySysNum)%MSCoolingSpeedRatio(UnitarySystem(UnitarySysNum)%NumOfSpeedCooling))
    END IF
    OnOffAirFlowRatio = 1.0d0
    PartLoadRatio = 1.0d0
    CALL SetOnOffMassFlowRate(UnitarySysNum, OnOffAirFlowRatio, PartLoadRatio)
    CALL SimDXCoilMultiSpeed(Blank,1.0d0,1.0d0,UnitarySystem(UnitarySysNum)%CoolingCoilIndex,0,0,0)
    DXCoolCap = GetCoilCapacityByIndexType(UnitarySystem(UnitarySysNum)%CoolingCoilIndex, &
                                           UnitarySystem(UnitarySysNum)%CoolingCoilType_Num,ErrFound)
    MSHPIndex = UnitarySystem(UnitarySysNum)%DesignSpecMSHPIndex
    IF(MSHPIndex .GT. 0)THEN
      DO Iter = DesignSpecMSHP(MSHPIndex)%NumOfSpeedCooling, 1 , -1 ! use reverse order since we divide by CoolVolumeFlowRate(max)
        IF(DesignSpecMSHP(MSHPIndex)%CoolingVolFlowRatio(Iter) == Autosize) &
             DesignSpecMSHP(MSHPIndex)%CoolingVolFlowRatio(Iter) = &
               REAL(Iter,r64)/REAL(DesignSpecMSHP(MSHPIndex)%NumOfSpeedCooling,r64)
        UnitarySystem(UnitarySysNum)%CoolVolumeFlowRate(Iter) =   UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow * &
                                                           DesignSpecMSHP(MSHPIndex)%CoolingVolFlowRatio(Iter)
        UnitarySystem(UnitarySysNum)%CoolMassFlowRate(Iter) = UnitarySystem(UnitarySysNum)%CoolVolumeFlowRate(Iter)* StdRhoAir
        UnitarySystem(UnitarySysNum)%MSCoolingSpeedRatio(Iter) = UnitarySystem(UnitarySysNum)%CoolVolumeFlowRate(Iter)/ &
                              UnitarySystem(UnitarySysNum)%CoolVolumeFlowRate(DesignSpecMSHP(MSHPIndex)%NumOfSpeedCooling)
      END DO
      UnitarySystem(UnitarySysNum)%IdleVolumeAirRate = UnitarySystem(UnitarySysNum)%CoolVolumeFlowRate(1)
      UnitarySystem(UnitarySysNum)%IdleMassFlowRate = UnitarySystem(UnitarySysNum)%CoolMassFlowRate(1)
      UnitarySystem(UnitarySysNum)%IdleSpeedRatio   = UnitarySystem(UnitarySysNum)%MSCoolingSpeedRatio(1)
    END IF
  CASE DEFAULT
  END SELECT
  IF (UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == CoilDX_MultiSpeedHeating .OR. &
      UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == Coil_HeatingElectric_MultiStage .OR. &
      UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == Coil_HeatingGas_MultiStage) THEN
    IF (UnitarySystem(UnitarySysNum)%NumOfSpeedHeating .GT. 0)THEN
      IF(.NOT. ALLOCATED(UnitarySystem(UnitarySysNum)%HeatVolumeFlowRate)) &
        ALLOCATE(UnitarySystem(UnitarySysNum)%HeatVolumeFlowRate(UnitarySystem(UnitarySysNum)%NumOfSpeedHeating))
      IF(.NOT. ALLOCATED(UnitarySystem(UnitarySysNum)%HeatMassFlowRate)) &
        ALLOCATE(UnitarySystem(UnitarySysNum)%HeatMassFlowRate(UnitarySystem(UnitarySysNum)%NumOfSpeedHeating))
      IF(.NOT. ALLOCATED(UnitarySystem(UnitarySysNum)%MSHeatingSpeedRatio)) &
        ALLOCATE(UnitarySystem(UnitarySysNum)%MSHeatingSpeedRatio(UnitarySystem(UnitarySysNum)%NumOfSpeedHeating))
    END IF
    MSHPIndex = UnitarySystem(UnitarySysNum)%DesignSpecMSHPIndex
    IF(MSHPIndex .GT. 0)THEN
      DO Iter = DesignSpecMSHP(MSHPIndex)%NumOfSpeedHeating, 1 , -1 ! use reverse order since we divide by HeatVolumeFlowRate(max)
        IF(DesignSpecMSHP(MSHPIndex)%HeatingVolFlowRatio(Iter) == Autosize) &
             DesignSpecMSHP(MSHPIndex)%HeatingVolFlowRatio(Iter) = &
                REAL(Iter,r64)/REAL(DesignSpecMSHP(MSHPIndex)%NumOfSpeedHeating,r64)
        UnitarySystem(UnitarySysNum)%HeatVolumeFlowRate(Iter) =   UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow * &
                                                                  DesignSpecMSHP(MSHPIndex)%HeatingVolFlowRatio(Iter)
        UnitarySystem(UnitarySysNum)%HeatMassFlowRate(Iter) = UnitarySystem(UnitarySysNum)%HeatVolumeFlowRate(Iter)* StdRhoAir
        UnitarySystem(UnitarySysNum)%MSHeatingSpeedRatio(Iter) = UnitarySystem(UnitarySysNum)%HeatVolumeFlowRate(Iter)/ &
                                      UnitarySystem(UnitarySysNum)%HeatVolumeFlowRate(DesignSpecMSHP(MSHPIndex)%NumOfSpeedHeating)
      END DO
      UnitarySystem(UnitarySysNum)%IdleVolumeAirRate = UnitarySystem(UnitarySysNum)%HeatVolumeFlowRate(1)
      UnitarySystem(UnitarySysNum)%IdleMassFlowRate = UnitarySystem(UnitarySysNum)%HeatMassFlowRate(1)
      UnitarySystem(UnitarySysNum)%IdleSpeedRatio   = UnitarySystem(UnitarySysNum)%MSHeatingSpeedRatio(1)
    END IF
  ELSEIF (UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == Coil_HeatingWaterToAirHPVSEquationFit .OR. &
            UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == Coil_HeatingAirToAirVariableSpeed) THEN
    CALL SimVariableSpeedCoils(Blank,UnitarySystem(UnitarySysNum)%HeatingCoilIndex,&
           0,UnitarySystem(UnitarySysNum)%MaxONOFFCyclesperHour, &
           UnitarySystem(UnitarySysNum)%HPTimeConstant,UnitarySystem(UnitarySysNum)%FanDelayTime,&
           0,0.0d0,0.0d0,1,0.0d0,0.0d0,0.0d0 ) !conduct the sizing operation in the VS WSHP
    UnitarySystem(UnitarySysNum)%NumOfSpeedHeating = VarSpeedCoil(UnitarySystem(UnitarySysNum)%HeatingCoilIndex)%NumOfSpeeds
    IF (UnitarySystem(UnitarySysNum)%NumOfSpeedHeating .GT. 0)THEN
      IF(.NOT. ALLOCATED(UnitarySystem(UnitarySysNum)%HeatVolumeFlowRate)) &
        ALLOCATE(UnitarySystem(UnitarySysNum)%HeatVolumeFlowRate(UnitarySystem(UnitarySysNum)%NumOfSpeedHeating))
      IF(.NOT. ALLOCATED(UnitarySystem(UnitarySysNum)%HeatMassFlowRate)) &
        ALLOCATE(UnitarySystem(UnitarySysNum)%HeatMassFlowRate(UnitarySystem(UnitarySysNum)%NumOfSpeedHeating))
      IF(.NOT. ALLOCATED(UnitarySystem(UnitarySysNum)%MSHeatingSpeedRatio)) &
        ALLOCATE(UnitarySystem(UnitarySysNum)%MSHeatingSpeedRatio(UnitarySystem(UnitarySysNum)%NumOfSpeedHeating))
    END IF
    MulSpeedFlowScale = VarSpeedCoil(UnitarySystem(UnitarySysNum)%HeatingCoilIndex)%RatedAirVolFlowRate/ &
                        VarSpeedCoil(UnitarySystem(UnitarySysNum)%HeatingCoilIndex)%MSRatedAirVolFlowRate(  &
                           VarSpeedCoil(UnitarySystem(UnitarySysNum)%HeatingCoilIndex)%NormSpedLevel)
    DO Iter = 1,UnitarySystem(UnitarySysNum)%NumOfSpeedHeating
      UnitarySystem(UnitarySysNum)%HeatVolumeFlowRate(Iter) =   &
         VarSpeedCoil(UnitarySystem(UnitarySysNum)%HeatingCoilIndex)%MSRatedAirVolFlowRate(Iter) * MulSpeedFlowScale
      UnitarySystem(UnitarySysNum)%HeatMassFlowRate(Iter) = UnitarySystem(UnitarySysNum)%HeatVolumeFlowRate(Iter)* StdRhoAir
      IF(UnitarySystem(UnitarySysNum)%DesignFanVolFlowRate .GT. 0.0d0 .AND. UnitarySystem(UnitarySysNum)%FanExists)THEN
        UnitarySystem(UnitarySysNum)%MSHeatingSpeedRatio(Iter) = UnitarySystem(UnitarySysNum)%HeatVolumeFlowRate(Iter)/ &
          UnitarySystem(UnitarySysNum)%DesignFanVolFlowRate
      ELSE
        UnitarySystem(UnitarySysNum)%MSHeatingSpeedRatio(Iter) = UnitarySystem(UnitarySysNum)%HeatVolumeFlowRate(Iter)/ &
          UnitarySystem(UnitarySysNum)%HeatVolumeFlowRate(UnitarySystem(UnitarySysNum)%NumOfSpeedHeating)
      END IF
    END DO
    IF(UnitarySystem(UnitarySysNum)%CoolCoilExists)THEN
      IF(ALLOCATED(UnitarySystem(UnitarySysNum)%CoolVolumeFlowRate))THEN
        UnitarySystem(UnitarySysNum)%IdleVolumeAirRate = &
          MIN(UnitarySystem(UnitarySysNum)%IdleVolumeAirRate,UnitarySystem(UnitarySysNum)%HeatVolumeFlowRate(1))
        UnitarySystem(UnitarySysNum)%IdleMassFlowRate  = &
          MIN(UnitarySystem(UnitarySysNum)%IdleMassFlowRate,UnitarySystem(UnitarySysNum)%HeatMassFlowRate(1))
        UnitarySystem(UnitarySysNum)%IdleSpeedRatio    = &
          MIN(UnitarySystem(UnitarySysNum)%IdleSpeedRatio,UnitarySystem(UnitarySysNum)%MSHeatingSpeedRatio(1))
      ELSE
        UnitarySystem(UnitarySysNum)%IdleVolumeAirRate = UnitarySystem(UnitarySysNum)%HeatVolumeFlowRate(1)
        UnitarySystem(UnitarySysNum)%IdleMassFlowRate  = UnitarySystem(UnitarySysNum)%HeatMassFlowRate(1)
        UnitarySystem(UnitarySysNum)%IdleSpeedRatio    = UnitarySystem(UnitarySysNum)%MSHeatingSpeedRatio(1)
      END IF
    ELSE
      UnitarySystem(UnitarySysNum)%IdleVolumeAirRate = UnitarySystem(UnitarySysNum)%HeatVolumeFlowRate(1)
      UnitarySystem(UnitarySysNum)%IdleMassFlowRate  = UnitarySystem(UnitarySysNum)%HeatMassFlowRate(1)
      UnitarySystem(UnitarySysNum)%IdleSpeedRatio    = UnitarySystem(UnitarySysNum)%MSHeatingSpeedRatio(1)
    END IF
  END IF
  IF(UnitarySystem(UnitarySysNum)%CoolCoilExists .AND. UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow < 0.0d0)THEN
    IF ( .NOT. SysSizingRunDone) THEN
      BranchNum = GetAirBranchIndex('AirloopHVAC:UnitarySystem',UnitarySystem(UnitarySysNum)%Name)
      FanType = ' '
      FanName = ' '
      BranchFanFlow = 0.0d0
      IF(BranchNum .GT. 0.0d0)CALL GetBranchFanTypeName(BranchNum, FanType, FanName, ErrFound)
      IF(.NOT. ErrFound .AND. BranchNum .GT. 0)BranchFanFlow = GetFanDesignVolumeFlowRate(FanType,FanName,ErrFound)
      IF(BranchNum .GT. 0.0d0)BranchFlow = GetBranchFlow(BranchNum)
      IF(BranchFanFlow > 0.0d0)THEN
        UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = BranchFanFlow
      ELSEIF(BranchFlow > 0.0d0)THEN
        UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow = BranchFlow
      ELSEIF(BranchFlow == Autosize)THEN
        ! what do I do?
      END IF
    END IF
  END IF
    !Change the Volume Flow Rates to Mass Flow Rates
    UnitarySystem(UnitarySysNum)%DesignMassFlowRate = UnitarySystem(UnitarySysNum)%DesignFanVolFlowRate * StdRhoAir
    UnitarySystem(UnitarySysNum)%MaxCoolAirMassFlow = UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow * StdRhoAir
    UnitarySystem(UnitarySysNum)%MaxHeatAirMassFlow = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow* StdRhoAir
    UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirMassFlow = UnitarySystem(UnitarySysNum)%MaxNoCoolHeatAirVolFlow* StdRhoAir
    UnitarySystem(UnitarySysNum)%SenLoadLoss = 0.0d0
    IF (UnitarySystem(UnitarySysNum)%Humidistat) THEN
      UnitarySystem(UnitarySysNum)%LatLoadLoss = 0.0d0
    END IF
  IF (UnitarySystem(UnitarySysNum)%DesignHeatingCapacity == AutoSize) THEN
    IF (CurOASysNum > 0) THEN
      IF(OASysEqSizing(CurOASysNum)%Capacity)THEN
        IF(OASysEqSizing(CurOASysNum)%DesHeatingLoad .GT. 0.0d0)THEN
          UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = OASysEqSizing(CurOASysNum)%DesHeatingLoad
        ELSE
          UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = OASysEqSizing(CurOASysNum)%DesCoolingLoad * &
                                                               UnitarySystem(UnitarySysNum)%HeatingSizingRatio
        END IF
      ELSE
        IF (DXCoolCap >= SmallLoad) THEN
          UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = DXCoolCap * UnitarySystem(UnitarySysNum)%HeatingSizingRatio
        ELSE
          UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = 0.0d0
        END IF
      END IF
    ELSE IF (CurZoneEqNum > 0) THEN
      IF(ZoneEqSizing(CurZoneEqNum)%Capacity)THEN
        IF(ZoneEqSizing(CurZoneEqNum)%DesHeatingLoad .GT. 0.0d0)THEN
          UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = ZoneEqSizing(CurZoneEqNum)%DesHeatingLoad
        ELSE
          UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = ZoneEqSizing(CurZoneEqNum)%DesCoolingLoad * &
                                                               UnitarySystem(UnitarySysNum)%HeatingSizingRatio
        END IF
      ELSE
        IF (DXCoolCap >= SmallLoad) THEN
          UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = DXCoolCap * UnitarySystem(UnitarySysNum)%HeatingSizingRatio
        ELSE
          UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = 0.0d0
        END IF
      END IF
    ELSE IF(DXCoolCap > 0 .AND. UnitarySystem(UnitarySysNum)%HeatPump) THEN
      IF (DXCoolCap >= SmallLoad) THEN
        UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = DXCoolCap * UnitarySystem(UnitarySysNum)%HeatingSizingRatio
      ELSE
        UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = 0.0d0
      END IF
    ELSE IF (CurSysNum > 0) THEN
      IF (UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == Coil_HeatingAirToAirVariableSpeed .OR. &
          UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == CoilDX_MultiSpeedHeating .OR. &
          UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == Coil_HeatingWaterToAirHPSimple .OR. &
          UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == Coil_HeatingWaterToAirHP .OR. &
          UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == Coil_HeatingWaterToAirHPVSEquationFit .OR. &
          UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == CoilDX_HeatingEmpirical)  THEN
        ! for now, find the associated DX cooling coil to identically size heating coil
        DXHeatCoilBranch = 0
        DXHeatCoilCompNum = 0
        IF(UnitarySystem(UnitarySysNum)%DXHeatingCoil .AND. .NOT. UnitarySystem(UnitarySysNum)%CoolCoilExists)THEN
          BRANCHLoop: DO BranchNum = 1, PrimaryAirSystem(AirLoopNum)%NumBranches
            DO CompNum = 1, PrimaryAirSystem(AirLoopNum)%Branch(BranchNum)%TotalComponents
              IF(.NOT. SameString(PrimaryAirSystem(AirLoopNum)%Branch(BranchNum)%Comp(CompNum)%TypeOf, &
                           UnitarySystem(UnitarySysNum)%UnitarySystemType)) CYCLE
              IF(.NOT. SameString(PrimaryAirSystem(AirLoopNum)%Branch(BranchNum)%Comp(CompNum)%Name, &
                           UnitarySystem(UnitarySysNum)%Name)) CYCLE
              DXHeatCoilBranch = BranchNum
              DXHeatCoilCompNum = CompNum
              EXIT BRANCHLoop
            END DO
          END DO BRANCHLoop
        END IF
        IF(DXHeatCoilCompNum .GT. 0)THEN
          DO CompNum = PrimaryAirSystem(AirLoopNum)%Branch(DXHeatCoilBranch)%TotalComponents, 1, -1
            IF(SameString(PrimaryAirSystem(AirLoopNum)%Branch(BranchNum)%Comp(CompNum)%TypeOf, &
                        UnitarySystem(UnitarySysNum)%UnitarySystemType)) THEN
              IF(SameString(PrimaryAirSystem(AirLoopNum)%Branch(BranchNum)%Comp(CompNum)%Name, &
                        UnitarySystem(UnitarySysNum)%Name))CYCLE
              CoolCoilIndex = &
                GetUnitarySystemDXCoolingCoilIndex(PrimaryAirSystem(AirLoopNum)%Branch(DXHeatCoilBranch)%Comp(CompNum)%Name)
              IF(CoolCoilIndex .GT. 0)THEN
                CoolUnitarySystemNum = FinditemInList(PrimaryAirSystem(AirLoopNum)%Branch(DXHeatCoilBranch)%Comp(CompNum)%Name, &
                                                    UnitarySystem%Name,NumUnitarySystem)
                CoolCoilType = UnitarySystem(CoolUnitarySystemNum)%CoolingCoilType_Num
                DXCoolCap = GetCoilCapacityByIndexType(CoolCoilIndex,CoolCoilType,ErrFound)
                UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = DXCoolCap*UnitarySystem(UnitarySysNum)%HeatingSizingRatio
                EXIT
              END IF
            ELSE IF(SameString(PrimaryAirSystem(AirLoopNum)%Branch(BranchNum)%Comp(CompNum)%TypeOf, &
                        'CoilSystem:Cooling:DX'))THEN
              CoolCoilType  = 0
              CoolCoilIndex = 0
              CoolCoilName =' '
              CALL GetCoolingCoilTypeNameAndIndex(PrimaryAirSystem(AirLoopNum)%Branch(BranchNum)%Comp(CompNum)%Name, &
                                              CoolCoilType,CoolCoilIndex,CoolCoilName,ErrFound)
              SELECT CASE(CoolCoilType)
                CASE(CoilDX_CoolingSingleSpeed,CoilDX_CoolingTwoSpeed,CoilDX_CoolingTwoStageWHumControl)
                  DXCoolCap = GetCoilCapacityByIndexType(CoolCoilIndex,CoolCoilType,ErrFound)
                CASE(CoilDX_CoolingHXAssisted)
                  DXCoolCap = GetCoilCapacity(cAllCoilTypes(CoolCoilType), CoolCoilName,ErrFound)
                CASE(Coil_CoolingAirToAirVariableSpeed)
                  DXCoolCap = GetCoilCapacityByIndexType(CoolCoilIndex,CoolCoilType,ErrFound)
                ! the following CASE's are not allowed in CoilSystem:Cooling:DX
                CASE(Coil_CoolingWaterToAirHPSimple)
                  DXCoolCap = GetSimpleCoilCapacity(cAllCoilTypes(CoolCoilType), CoolCoilName,ErrFound)
                CASE(Coil_CoolingWaterToAirHP)
                  DXCoolCap = GetWAHPCoilCapacity(cAllCoilTypes(CoolCoilType), CoolCoilName,ErrFound)
                CASE(Coil_CoolingWaterToAirHPVSEquationFit)
                  DXCoolCap = GetCoilCapacityVariableSpeed(cAllCoilTypes(CoolCoilType), CoolCoilName,ErrFound)
                CASE(CoilDX_MultiSpeedCooling)
                  DXCoolCap = GetCoilCapacityByIndexType(CoolCoilIndex,CoolCoilType,ErrFound)
                CASE DEFAULT
              END SELECT
              UnitarySystem(UnitarySysNum)%CoolingCoilIndex = CoolCoilIndex
              IF(UnitarySystem(UnitarySysNum)%CoolingCoilIndex .GT. 0)THEN
                IF (DXCoolCap > 0.0d0) UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = &
                   DXCoolCap*UnitarySystem(UnitarySysNum)%HeatingSizingRatio
!                EXIT - don't exit, see if there is a UnitarySystem on the branch more upstream of the CoilSystem
              END IF
            END IF
          END DO
          IF(DXCoolCap == 0.0d0)THEN
            IF(UnitarySystem(UnitarySysNum)%DesignHeatingCapacity == Autosize)THEN
              VolFlowRate = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
              IF (VolFlowRate >= SmallAirVolFlow) THEN
                IF (CurOASysNum > 0) THEN ! coil is in the OA stream
                  MixTemp = FinalSysSizing(CurSysNum)%HeatOutTemp
                  MixHumRat = FinalSysSizing(CurSysNum)%HeatOutHumRat
                  SupTemp = FinalSysSizing(CurSysNum)%PrecoolTemp
                  SupHumRat = FinalSysSizing(CurSysNum)%PrecoolHumRat
                  OutTemp = FinalSysSizing(CurSysNum)%HeatOutTemp
                ELSE IF(CurSysNum > 0)THEN ! coil is on the main air loop
                  SupTemp = FinalSysSizing(CurSysNum)%HeatSupTemp
                  SupHumRat = FinalSysSizing(CurSysNum)%HeatSupHumRat
                  MixTemp = FinalSysSizing(CurSysNum)%HeatMixTemp
                  MixHumRat = FinalSysSizing(CurSysNum)%HeatMixHumRat
                  OutTemp = FinalSysSizing(CurSysNum)%HeatOutTemp
                ELSE ! coil is zone equipment
                  IF (ZoneEqSizing(CurZoneEqNum)%OAVolFlow > 0.0d0) THEN
                    MixTemp = FinalZoneSizing(CurZoneEqNum)%DesHeatCoilInTemp
                    MixHumRat = FinalZoneSizing(CurZoneEqNum)%DesHeatCoilInHumRat
                  ELSE
                    MixTemp = FinalZoneSizing(CurZoneEqNum)%ZoneRetTempAtCoolPeak
                    MixHumRat = FinalZoneSizing(CurZoneEqNum)%ZoneHumRatAtCoolPeak
                  END IF
                  SupTemp = FinalZoneSizing(CurZoneEqNum)%HeatDesTemp
                  SupHumRat = FinalZoneSizing(CurZoneEqNum)%HeatDesHumRat
                  TimeStepNumAtMax = FinalZoneSizing(CurZoneEqNum)%TimeStepNumAtCoolMax
                  DDNum = FinalZoneSizing(CurZoneEqNum)%CoolDDNum
                  IF (DDNum > 0 .and. TimeStepNumAtMax > 0) THEN
                    OutTemp = DesDayWeath(DDNum)%Temp(TimeStepNumAtMax)
                  ELSE
                    OutTemp = 0.0d0
                  ENDIF
                END IF
                rhoair = PsyRhoAirFnPbTdbW(StdBaroPress,MixTemp,MixHumRat,RoutineName)
                MixEnth = PsyHFnTdbW(MixTemp,MixHumRat,RoutineName)
                MixWetBulb = PsyTwbFnTdbWPb(MixTemp,MixHumRat,StdBaroPress,RoutineName)
                SupEnth = PsyHFnTdbW(SupTemp,SupHumRat,RoutineName)
                IF(UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == CoilDX_MultiSpeedHeating .OR. &
                   UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == CoilDX_HeatingEmpirical)THEN
                  CapFTCurve = GetDXCoilCapFTCurveIndex(UnitarySystem(UnitarySysNum)%HeatingCoilIndex,ErrFound)
                  TotCapTempModFac = CurveValue(CapFTCurve,MixWetBulb,OutTemp)
                ELSE
                  TotCapTempModFac = 1.0d0
                END IF
                HeatCapAtPeak = MAX(0.0d0, (rhoair * VolFlowRate * (SupEnth-MixEnth)))
                IF(TotCapTempModFac .GT. 0.0d0)THEN
                  UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = HeatCapAtPeak / TotCapTempModFac
                ELSE
                  UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = HeatCapAtPeak
                END IF
                IF(UnitarySystem(UnitarySysNum)%DesignHeatingCapacity .GT. 0.d0)THEN
                  RatedVolFlowPerRatedTotCap = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow /   &
                     UnitarySystem(UnitarySysNum)%DesignHeatingCapacity
                ELSE
                  RatedVolFlowPerRatedTotCap = 0.0d0
                END IF
                ! check capacity to make sure design volume flow per total capacity is within range
                IF (RatedVolFlowPerRatedTotCap .LT. MinRatedVolFlowPerRatedTotCap1) THEN
                  HeatCapAtPeak = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow &
                                                   / MinRatedVolFlowPerRatedTotCap1
                  UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = HeatCapAtPeak
                  DXCoolCap = HeatCapAtPeak
                ELSEIF (RatedVolFlowPerRatedTotCap .GT. MaxRatedVolFlowPerRatedTotCap1) THEN
                  HeatCapAtPeak = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow &
                                                    / MaxRatedVolFlowPerRatedTotCap1
                  UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = HeatCapAtPeak
                  DXCoolCap = HeatCapAtPeak
                END IF
              END IF ! IF (VolFlowRate >= SmallAirVolFlow) THEN
            END IF ! IF(UnitarySystem(UnitarySysNum)%DesignHeatingCapacity == Autosize)THEN
          END IF ! IF(DXCoolCap == 0.0d0)THEN
        ELSE
          IF(UnitarySystem(UnitarySysNum)%DesignHeatingCapacity == Autosize)THEN
            VolFlowRate = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow
            IF (VolFlowRate >= SmallAirVolFlow) THEN
              IF (CurOASysNum > 0) THEN ! coil is in the OA stream
                MixTemp = FinalSysSizing(CurSysNum)%HeatOutTemp
                MixHumRat = FinalSysSizing(CurSysNum)%HeatOutHumRat
                SupTemp = FinalSysSizing(CurSysNum)%PrecoolTemp
                SupHumRat = FinalSysSizing(CurSysNum)%PrecoolHumRat
                OutTemp = FinalSysSizing(CurSysNum)%HeatOutTemp
              ELSE IF(CurSysNum > 0)THEN ! coil is on the main air loop
                SupTemp = FinalSysSizing(CurSysNum)%HeatSupTemp
                SupHumRat = FinalSysSizing(CurSysNum)%HeatSupHumRat
                MixTemp = FinalSysSizing(CurSysNum)%HeatMixTemp
                MixHumRat = FinalSysSizing(CurSysNum)%HeatMixHumRat
                OutTemp = FinalSysSizing(CurSysNum)%HeatOutTemp
              ELSE ! coil is zone equipment
                IF (ZoneEqSizing(CurZoneEqNum)%OAVolFlow > 0.0d0) THEN
                  MixTemp = FinalZoneSizing(CurZoneEqNum)%DesHeatCoilInTemp
                  MixHumRat = FinalZoneSizing(CurZoneEqNum)%DesHeatCoilInHumRat
                ELSE
                  MixTemp = FinalZoneSizing(CurZoneEqNum)%ZoneRetTempAtCoolPeak
                  MixHumRat = FinalZoneSizing(CurZoneEqNum)%ZoneHumRatAtCoolPeak
                END IF
                SupTemp = FinalZoneSizing(CurZoneEqNum)%HeatDesTemp
                SupHumRat = FinalZoneSizing(CurZoneEqNum)%HeatDesHumRat
                TimeStepNumAtMax = FinalZoneSizing(CurZoneEqNum)%TimeStepNumAtHeatMax
                DDNum = FinalZoneSizing(CurZoneEqNum)%HeatDDNum
                IF (DDNum > 0 .and. TimeStepNumAtMax > 0) THEN
                  OutTemp = DesDayWeath(DDNum)%Temp(TimeStepNumAtMax)
                ELSE
                  OutTemp = 0.0d0
                ENDIF
              END IF
              rhoair = PsyRhoAirFnPbTdbW(StdBaroPress,MixTemp,MixHumRat,RoutineName)
              MixEnth = PsyHFnTdbW(MixTemp,MixHumRat,RoutineName)
              MixWetBulb = PsyTwbFnTdbWPb(MixTemp,MixHumRat,StdBaroPress,RoutineName)
              SupEnth = PsyHFnTdbW(SupTemp,SupHumRat,RoutineName)
              IF(UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == CoilDX_MultiSpeedHeating .OR. &
                 UnitarySystem(UnitarySysNum)%HeatingCoilType_Num == CoilDX_HeatingEmpirical)THEN
                CapFTCurve = GetDXCoilCapFTCurveIndex(UnitarySystem(UnitarySysNum)%HeatingCoilIndex,ErrFound)
                TotCapTempModFac = CurveValue(CapFTCurve,MixWetBulb,OutTemp)
              ELSE
                TotCapTempModFac = 1.0d0
              END IF
              HeatCapAtPeak = MAX(0.0d0, (rhoair * VolFlowRate * (SupEnth-MixEnth)))
              IF(TotCapTempModFac .GT. 0.0d0)THEN
                UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = HeatCapAtPeak / TotCapTempModFac
              ELSE
                UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = HeatCapAtPeak
              END IF
              DXCoolCap = UnitarySystem(UnitarySysNum)%DesignHeatingCapacity
              IF(UnitarySystem(UnitarySysNum)%DesignHeatingCapacity .GT. 0.d0)THEN
                RatedVolFlowPerRatedTotCap = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow /   &
                   UnitarySystem(UnitarySysNum)%DesignHeatingCapacity
              ELSE
                RatedVolFlowPerRatedTotCap = 0.0d0
              END IF
              ! check capacity to make sure design volume flow per total capacity is within range
              IF (RatedVolFlowPerRatedTotCap .LT. MinRatedVolFlowPerRatedTotCap1) THEN
                HeatCapAtPeak = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow &
                                                 / MinRatedVolFlowPerRatedTotCap1
                UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = HeatCapAtPeak
                DXCoolCap = HeatCapAtPeak
              ELSEIF (RatedVolFlowPerRatedTotCap .GT. MaxRatedVolFlowPerRatedTotCap1) THEN
                HeatCapAtPeak = UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow &
                                                  / MaxRatedVolFlowPerRatedTotCap1
                UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = HeatCapAtPeak
                DXCoolCap = HeatCapAtPeak
              END IF
            END IF ! IF (VolFlowRate >= SmallAirVolFlow) THEN
          END IF ! IF(UnitarySystem(UnitarySysNum)%DesignHeatingCapacity == Autosize)THEN
        END IF ! IF(DXHeatCoilCompNum .GT. 0)THEN
      ELSE ! else not a HP heating coil
        IF (CurOASysNum > 0) THEN
          IF(OASysEqSizing(CurOASysNum)%Capacity) &
            UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = OASysEqSizing(CurOASysNum)%DesHeatingLoad
        ELSE IF (CurSysNum > 0) THEN
          IF(UnitarySysEqSizing(CurSysNum)%Capacity) &
            UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = UnitarySysEqSizing(CurSysNum)%DesHeatingLoad
        ELSE IF (CurZoneEqNum > 0) THEN
          IF(ZoneEqSizing(CurZoneEqNum)%Capacity) &
            UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = ZoneEqSizing(CurZoneEqNum)%DesHeatingLoad
        END IF
        IF (UnitarySystem(UnitarySysNum)%DesignHeatingCapacity == Autosize) THEN
          IF (CurOASysNum > 0) THEN
            IF(OASysEqSizing(CurOASysNum)%AirFlow)THEN
              VolFlowRate = OASysEqSizing(CurOASysNum)%AirVolFlow
            ELSE
              VolFlowRate = FinalSysSizing(CurSysNum)%DesOutAirVolFlow
            END IF
          ELSE
            IF(CurZoneEqNum > 0)THEN
              IF(ZoneEqSizing(CurZoneEqNum)%AirFlow)THEN
                VolFlowRate = ZoneEqSizing(CurZoneEqNum)%AirVolFlow
              ELSE
                VolFlowRate = FinalZoneSizing(CurZoneEqNum)%DesHeatVolFlow
              END IF
            ELSE
              IF(UnitarySysEqSizing(CurSysNum)%AirFlow)THEN
                VolFlowRate = UnitarySysEqSizing(CurSysNum)%AirVolFlow
              ELSE
                SELECT CASE(CurDuctType)
                  CASE(Main)
                    VolFlowRate = FinalSysSizing(CurSysNum)%SysAirMinFlowRat*FinalSysSizing(CurSysNum)%DesMainVolFlow
                  CASE(Cooling)
                    VolFlowRate = FinalSysSizing(CurSysNum)%SysAirMinFlowRat*FinalSysSizing(CurSysNum)%DesCoolVolFlow
                  CASE(Heating)
                    VolFlowRate = FinalSysSizing(CurSysNum)%DesHeatVolFlow
                  CASE(Other)
                    VolFlowRate = FinalSysSizing(CurSysNum)%DesMainVolFlow
                  CASE DEFAULT
                    VolFlowRate = FinalSysSizing(CurSysNum)%DesMainVolFlow
                END SELECT
              END IF
            END IF
          END IF
          ! get the outside air fraction
          IF (CurOASysNum > 0) THEN
            OutAirFrac = 1.0d0
          ELSE IF (CurSysNum > 0) THEN
            IF (FinalSysSizing(CurSysNum)%HeatOAOption == MinOA) THEN
              IF (VolFlowRate > 0.0d0) THEN
                OutAirFrac = FinalSysSizing(CurSysNum)%DesOutAirVolFlow / VolFlowRate
              ELSE
                OutAirFrac = 1.0d0
              END IF
            ELSE
              OutAirFrac = 1.0d0
            END IF
            OutAirFrac = MIN(1.0d0,MAX(0.0d0,OutAirFrac))
          ELSE
            OutAirFrac = 1.0d0
          END IF
          ! coil inlet temperature
          IF (CurZoneEqNum > 0) THEN
            MixTemp = FinalZoneSizing(CurZoneEqNum)%DesHeatCoilInTemp
            CpAirStd = PsyCpAirFnWTdb(0.0d0,20.0d0)
            HeatCapAtPeak = CpAirStd*StdRhoAir*VolFlowRate*(FinalZoneSizing(CurZoneEqNum)%HeatDesTemp - MixTemp)
            ZoneEqSizing(CurZoneEqNum)%Capacity = .TRUE.
            ZoneEqSizing(CurZoneEqNum)%DesHeatingLoad = HeatCapAtPeak
          ELSE
            IF (CurOASysNum == 0 .AND. PrimaryAirSystem(CurSysNum)%NumOAHeatCoils > 0) THEN
              MixTemp = OutAirFrac*FinalSysSizing(CurSysNum)%PreheatTemp + &
                         (1.0d0-OutAirFrac)*FinalSysSizing(CurSysNum)%HeatRetTemp
            ELSE
              MixTemp = OutAirFrac*FinalSysSizing(CurSysNum)%HeatOutTemp + &
                         (1.0d0-OutAirFrac)*FinalSysSizing(CurSysNum)%HeatRetTemp
            END IF
            ! coil load
            IF (CurOASysNum > 0) THEN
              IF(OASysEqSizing(CurOASysNum)%Capacity)THEN
                HeatCapAtPeak = OASysEqSizing(CurOASysNum)%DesHeatingLoad
              ELSE
                CpAirStd = PsyCpAirFnWTdb(0.0d0,20.0d0)
                HeatCapAtPeak = CpAirStd*StdRhoAir*VolFlowRate*(FinalSysSizing(CurSysNum)%PreheatTemp - MixTemp)
              END IF
            ELSE
              IF(UnitarySysEqSizing(CurSysNum)%Capacity)THEN
                HeatCapAtPeak = UnitarySysEqSizing(CurSysNum)%DesHeatingLoad
              ELSE
                CpAirStd = PsyCpAirFnWTdb(0.0d0,20.0d0)
                HeatCapAtPeak = CpAirStd*StdRhoAir*VolFlowRate*(FinalSysSizing(CurSysNum)%HeatSupTemp - MixTemp)
              END IF
            END IF
            UnitaryHeatCap = HeatCapAtPeak
          END IF
          UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = HeatCapAtPeak
        END IF
      END IF
      IF (UnitarySystem(UnitarySysNum)%DesignHeatingCapacity < SmallLoad) THEN
        UnitarySystem(UnitarySysNum)%DesignHeatingCapacity = 0.0d0
      END IF
    END IF
    CALL ReportSizingOutput(UnitarySystem(UnitarySysNum)%UnitarySystemType, UnitarySystem(UnitarySysNum)%Name, &
                            'Nominal Heating Capacity [W]', &
                            UnitarySystem(UnitarySysNum)%DesignHeatingCapacity)
  END IF
  UnitaryHeatCap = UnitarySystem(UnitarySysNum)%DesignHeatingCapacity
  IF (UnitarySystem(UnitarySysNum)%DesignCoolingCapacity == AutoSize) THEN
    IF (CurOASysNum > 0) THEN
      IF (DXCoolCap >= SmallLoad) THEN
        UnitarySystem(UnitarySysNum)%DesignCoolingCapacity = DXCoolCap
      ELSE
        UnitarySystem(UnitarySysNum)%DesignCoolingCapacity = 0.0d0
      END IF
    ELSE IF (CurZoneEqNum > 0) THEN
      IF (DXCoolCap >= SmallLoad) THEN
        UnitarySystem(UnitarySysNum)%DesignCoolingCapacity = DXCoolCap
      ELSE
        UnitarySystem(UnitarySysNum)%DesignCoolingCapacity = 0.0d0
      END IF
    ELSE IF (CurSysNum > 0) THEN
      IF (DXCoolCap >= SmallLoad) THEN
        UnitarySystem(UnitarySysNum)%DesignCoolingCapacity = DXCoolCap
      ELSE
        UnitarySystem(UnitarySysNum)%DesignCoolingCapacity = 0.0d0
      END IF
    END IF
    CALL ReportSizingOutput(UnitarySystem(UnitarySysNum)%UnitarySystemType, UnitarySystem(UnitarySysNum)%Name, &
                            'Nominal Cooling Capacity [W]', &
                            UnitarySystem(UnitarySysNum)%DesigncoolingCapacity)
  END IF
  IF (UnitarySystem(UnitarySysNum)%DesignMaxOutletTemp == AutoSize .AND. &
      (UnitarySystem(UnitarySysNum)%HeatCoilExists .OR. UnitarySystem(UnitarySysNum)%SuppCoilExists)) THEN
    IF (CurOASysNum > 0) THEN
      UnitarySystem(UnitarySysNum)%DesignMaxOutletTemp = FinalSysSizing(CurSysNum)%HeatSupTemp
    ELSE IF (CurZoneEqNum > 0) THEN
      UnitarySystem(UnitarySysNum)%DesignMaxOutletTemp = FinalZoneSizing(CurZoneEqNum)%HeatDesTemp
    ELSE IF (CurSysNum > 0) THEN
      UnitarySystem(UnitarySysNum)%DesignMaxOutletTemp = FinalSysSizing(CurSysNum)%HeatSupTemp
    END IF
    CALL ReportSizingOutput(UnitarySystem(UnitarySysNum)%UnitarySystemType, UnitarySystem(UnitarySysNum)%Name, &
                            'Maximum Supply Air Temperature from Unitary Heater [C]', &
                            UnitarySystem(UnitarySysNum)%DesignMaxOutletTemp)
  END IF
  IF (UnitarySystem(UnitarySysNum)%DesignSuppHeatingCapacity == AutoSize) THEN
    IF (CurOASysNum > 0) THEN
      UnitarySystem(UnitarySysNum)%DesignSuppHeatingCapacity = FinalSysSizing(CurSysNum)%HeatCap
    ELSE IF (CurZoneEqNum > 0) THEN
      UnitarySystem(UnitarySysNum)%DesignSuppHeatingCapacity = FinalZoneSizing(CurZoneEqNum)%DesHeatLoad
    ELSE IF (CurSysNum > 0) THEN
      ! set the supplemental heating capacity to the actual heating load
      UnitarySystem(UnitarySysNum)%DesignSuppHeatingCapacity = FinalSysSizing(CurSysNum)%HeatCap
      ! If reheat needed for humidity control, make sure supplemental heating is at least as big
      ! as the cooling capacity
      IF (UnitarySystem(UnitarySysNum)%Humidistat .AND. &
          UnitarySystem(UnitarySysNum)%DehumidControlType_Num == DehumidControl_CoolReheat) THEN
        UnitarySystem(UnitarySysNum)%DesignSuppHeatingCapacity = MAX(UnitarySystem(UnitarySysNum)%DesignSuppHeatingCapacity, &
                                                            UnitarySystem(UnitarySysNum)%DesignCoolingCapacity)
        IF (UnitarySystem(UnitarySysNum)%DesignSuppHeatingCapacity < SmallLoad) THEN
          UnitarySystem(UnitarySysNum)%DesignSuppHeatingCapacity = 0.0d0
        END IF
      END IF
    END IF
    CALL ReportSizingOutput(UnitarySystem(UnitarySysNum)%UnitarySystemType, UnitarySystem(UnitarySysNum)%Name, &
                            'Supplemental Heating Coil Nominal Capacity [W]', &
                            UnitarySystem(UnitarySysNum)%DesignSuppHeatingCapacity)
  END IF
  SuppHeatCap = UnitarySystem(UnitarySysNum)%DesignSuppHeatingCapacity
  IF (UnitarySystem(UnitarySysNum)%HeatRecActive) THEN
    CALL RegisterPlantCompDesignFlow(UnitarySystem(UnitarySysNum)%HeatRecoveryInletNodeNum, &
                              UnitarySystem(UnitarySysNum)%DesignHRWaterVolumeFlow )
  END IF
  IF(CurOASysNum .EQ. 0 .AND. CurZoneEqNum .EQ. 0)THEN
    BranchFlow = 0.0d0
    SystemType = cFurnaceTypes(UnitarySystem(UnitarySysNum)%UnitarySystemType_Num)
    ErrFound  = .FALSE.
    ! check branch flow rate vs system flow rate. Branch must match system of OA system is present
    CALL CheckSystemBranchFlow(TRIM(SystemType),UnitarySystem(UnitarySysNum)%Name, &
                               BranchFlow,UnitarySystem(UnitarySysNum)%DesignFanVolFlowRate,ErrFound)
    IF(ErrFound)CALL ShowContinueError('...occurs in '//TRIM(SystemType)//' "'//TRIM(UnitarySystem(UnitarySysNum)%Name))
    IF(UnitarySystem(UnitarySysNum)%DesignFanVolFlowRate .LE. 0.0d0)THEN
      IF(BranchFlow .NE. Autosize)THEN
        UnitarySystem(UnitarySysNum)%DesignFanVolFlowRate = BranchFlow
      ELSE
        UnitarySystem(UnitarySysNum)%DesignFanVolFlowRate = MAX(UnitarySystem(UnitarySysNum)%MaxCoolAirVolFlow, &
                                                                UnitarySystem(UnitarySysNum)%MaxHeatAirVolFlow)
      END IF
      UnitarySystem(UnitarySysNum)%DesignMassFlowRate = UnitarySystem(UnitarySysNum)%DesignFanVolFlowRate * StdRhoAir
    END IF
  END IF
  CoolingLoad = TempCoolingLoad
  HeatingLoad = TempHeatingLoad
  RETURN
END SUBROUTINE SizeUnitarySystem
All Procedures
AbortEnergyPlus AbsoluteAirMass ActivateDemandManagers ActivateEMSControls AddBlankKeys addChargesToOperand AddCompSizeTableEntry AddEndUseSubcategory AddError addFootNoteSubTable AddInstruction AddMeter addMonthlyCharge AddMonthlyFieldSetInput AddMonthlyReport AddNeighborInformation AddObjectDefandParse addOperand AddRecordFromSection AddRecordToOutputVariableStructure AddSectionDef AddShadowRelateTableEntry AddSQLiteComponentSizingRecord AddSQLiteComponentSizingRecord AddSQLiteSystemSizingRecord AddSQLiteSystemSizingRecord AddSQLiteZoneSizingRecord AddSQLiteZoneSizingRecord AddTOCEntry AddTOCZoneLoadComponentTable AddToOutputVariableList AddVariablesForMonthlyReport AddVariableSlatBlind AddWindow AdjustAirSetpointsforOpTempCntrl AdjustCBF AdjustCBF AdjustChangeInLoadByEMSControls AdjustChangeInLoadByHowServed AdjustChangeInLoadForLastStageUpperRangeLimit AdjustCoolingSetPointforTempAndHumidityControl adjusthhat AdjustPumpFlowRequestByEMSControls AdjustReportingHourAndMinutes AdjustVBGap AdvanceRootFinder AFECFR AFECOI AFECPD AFECPF AFEDMP AFEDOP AFEDWC AFEELR AFEEXF AFEFAN AFEHEX AFEHOP AFEPLR AFESCR AFESEL AFESOP AFETMU AirflowNetworkVentingControl AirMass AIRMOV AllocateAirflowNetworkData AllocateAirHeatBalArrays AllocateAndInitData AllocateAndSetUpVentReports AllocateCFSStateHourlyData AllocateForCFSRefPointsGeometry AllocateForCFSRefPointsState AllocateHeatBalArrays AllocateLoadComponentArrays AllocateModuleArrays AllocateModuleArrays AllocateSurfaceHeatBalArrays AllocateWeatherData angle_2dvector AnisoSkyViewFactors AnyPlantLoopSidesNeedSim AnyPlantSplitterMixerLacksContinuity AreaPolygon ArgCheck array_to_vector ASHRAETauModel ASHWAT_OffNormalProperties ASHWAT_Solar ASHWAT_Thermal ASSIGNMENT (=) AssignNodeNumber AssignReportNumber AssignResourceTypeNum AssignReverseConstructionNumber AssignVariablePt AttachCustomMeters AttachMeters AuditBranches AUTOTDMA BaseThermalPropertySet_Diffusivity BeginEnvrnInitializeRuntimeLanguage BetweenDates BetweenGlassForcedFlow BetweenGlassShadeForcedFlow BetweenGlassShadeNaturalFlow BisectionMethod BlindBeamBeamTrans BlindOpticsBeam BlindOpticsDiffuse BoreholeResistance BoundValueToNodeMinMaxAvail BoundValueToWithinTwoValues BracketRoot BranchPressureDrop BrentMethod BuildGap BuildKeyVarList Calc4PipeFanCoil Calc_EN673 Calc_ISO15099 CalcActiveTranspiredCollector CalcAggregateLoad CalcAirflowNetworkAirBalance CalcAirflowNetworkCO2Balance CalcAirflowNetworkGCBalance CalcAirflowNetworkHeatBalance CalcAirflowNetworkMoisBalance CalcAirFlowSimple CalcAirLoopSplitter CalcAirMixer CalcAirToAirGenericHeatExch CalcAirToAirPlateHeatExch CalcAirZoneReturnPlenum CalcAirZoneSupplyPlenum CalcAlamdariHammondStableHorizontal CalcAlamdariHammondUnstableHorizontal CalcAlamdariHammondVerticalWall CalcAngleFactorMRT CalcApproximateViewFactors CalcASHRAEDetailedIntConvCoeff CalcASHRAESimpExtConvectCoeff CalcASHRAESimpleIntConvCoeff CalcASHRAEVerticalWall CalcATMixer CalcAwbiHattonHeatedFloor CalcAwbiHattonHeatedWall CalcBasinHeaterPower CalcBasinHeaterPowerForMultiModeDXCoil CalcBeamSolarOnWinRevealSurface CalcBeamSolDiffuseReflFactors CalcBeamSolSpecularReflFactors CalcBeausoleilMorrisonMixedAssistedWall CalcBeausoleilMorrisonMixedOpposingWall CalcBeausoleilMorrisonMixedStableCeiling CalcBeausoleilMorrisonMixedStableFloor CalcBeausoleilMorrisonMixedUnstableCeiling CalcBeausoleilMorrisonMixedUnstableFloor CalcBLASTAbsorberModel CalcBlockenWindward CalcBoilerModel CalcBoilerModel CalcBottomFluxCoefficents CalcBottomSurfTemp CalcBuriedPipeSoil CalcCBF CalcCBF CalcCBVAV CalcCeilingDiffuserInletCorr CalcCeilingDiffuserIntConvCoeff CalcChillerHeaterModel CalcChillerIPLV CalcChillerModel CalcClearRoof CalcCoilUAbyEffectNTU CalcColdestSetPoint CalcComplexWindowOverlap CalcComplexWindowThermal CalcCompSuctionTempResidual CalcCondEntSetPoint CalcConnectionsDrainTemp CalcConnectionsFlowRates CalcConnectionsHeatRecovery CalcConstCOPChillerModel CalcConvCoeffAbsPlateAndWater CalcConvCoeffBetweenPlates CalcCoolBeam CalcCoolTower CalcCoordinateTransformation CalcCoPlanarNess CalcCostEstimate CalcCTGeneratorModel CalcDayltgCoefficients CalcDayltgCoeffsMapPoints CalcDayltgCoeffsRefMapPoints CalcDayltgCoeffsRefPoints CalcDesiccantBalancedHeatExch CalcDesignSpecificationOutdoorAir CalcDesuperheaterHeatingCoil CalcDesuperheaterWaterHeater CalcDetailedHcInForDVModel CalcDetailedSystem CalcDetailedTransSystem CalcDetailFlatFinCoolingCoil CalcDetIceStorLMTDstar CalcDiffTSysAvailMgr CalcDirectAir CalcDirectEvapCooler CalcDirectResearchSpecialEvapCooler CalcDoe2DXCoil CalcDOE2Leeward CalcDOE2Windward CalcDryFinEffCoef CalcDryIndirectEvapCooler CalcDuct CalcDXCoilStandardRating CalcDXHeatingCoil CalcEarthTube CalcEcoRoof CalcEffectiveness CalcEffectiveSHR CalcEffectiveSHR CalcEffectiveSHR CalcEffectiveSHR CalcElecSteamHumidifier CalcElectricBaseboard CalcElectricChillerHeatRecovery CalcElectricChillerModel CalcElectricEIRChillerModel CalcElectricHeatingCoil CalcEmmelRoof CalcEmmelVertical CalcEngineChillerHeatRec CalcEngineDrivenChillerModel CalcEQLOpticalProperty CalcEQLWindowOpticalProperty CalcEQLWindowSHGCAndTransNormal CalcEQLWindowStandardRatings CalcEQLWindowUvalue CalcEquipmentDrainTemp CalcEquipmentFlowRates CalcExhaustAbsorberChillerModel CalcExhaustAbsorberHeaterModel CalcExteriorVentedCavity CalcFisherPedersenCeilDiffuserCeiling CalcFisherPedersenCeilDiffuserFloor CalcFisherPedersenCeilDiffuserWalls CalcFluidHeatExchanger CalcFohannoPolidoriVerticalWall CalcFollowOATempSetPoint CalcFollowSysNodeTempSetPoint CalcFourPipeIndUnit CalcFrameDividerShadow CalcFuelCellAuxHeater CalcFuelCellGeneratorModel CalcFuelCellGenHeatRecovery CalcFurnaceOutput CalcFurnaceResidual CalcGasAbsorberChillerModel CalcGasAbsorberHeaterModel CalcGasCooler CalcGasHeatingCoil CalcGenericDesiccantDehumidifier CalcGoldsteinNovoselacCeilingDiffuserFloor CalcGoldsteinNovoselacCeilingDiffuserWall CalcGoldsteinNovoselacCeilingDiffuserWindow CalcGroundTempSetPoint CalcGroundwaterWell CalcGshpModel CalcGshpModel CalcGTChillerModel CalcHeatBalanceAir CalcHeatBalanceInsideSurf CalcHeatBalanceInsideSurf CalcHeatBalanceOutsideSurf CalcHeatBalanceOutsideSurf CalcHeatBalFiniteDiff CalcHeatBalHAMT CalcHeatPumpWaterHeater CalcHeatTransCoeffAndCoverTemp CalcHfExteriorSparrow CalcHighTempRadiantSystem CalcHighTempRadiantSystemSP CalcHiTurnOffSysAvailMgr CalcHiTurnOnSysAvailMgr CalcHnASHRAETARPExterior CalcHPCoolingSimple CalcHPHeatingSimple CalcHPWHDXCoil CalcHWBaseboard CalcHXAssistedCoolingCoil CalcHXEffectTerm CalcHybridVentSysAvailMgr CalcIBesselFunc CalcICEngineGeneratorModel CalcICEngineGenHeatRecovery CalcIceStorageCapacity CalcIceStorageCharge CalcIceStorageDischarge CalcIceStorageDormant CalcICSSolarCollector CalcIdealCondEntSetPoint CalcIfSetpointMet CalcIndirectAbsorberModel CalcIndirectResearchSpecialEvapCooler CalcInteriorRadExchange CalcInteriorSolarDistribution CalcInteriorSolarOverlaps CalcInteriorWinTransDifSolInitialDistribution CalcISO15099WindowIntConvCoeff CalcKaradagChilledCeiling CalcKBesselFunc CalcKhalifaEq3WallAwayFromHeat CalcKhalifaEq4CeilingAwayFromHeat CalcKhalifaEq5WallsNearHeat CalcKhalifaEq6NonHeatedWalls CalcKhalifaEq7Ceiling CalcLoadCenterThermalLoad CalcLoTurnOffSysAvailMgr CalcLoTurnOnSysAvailMgr CalcLowTempCFloRadiantSystem CalcLowTempCFloRadSysComps CalcLowTempElecRadiantSystem CalcLowTempHydrRadiantSystem CalcLowTempHydrRadSysComps CalcMatrixInverse CalcMcAdams CalcMerkelVariableSpeedTower CalcMicroCHPNoNormalizeGeneratorModel CalcMinIntWinSolidAngs CalcMitchell CalcMixedAirSetPoint CalcMoistureBalanceEMPD CalcMoreNodeInfo CalcMoWITTLeeward CalcMoWITTWindward CalcMSHeatPump CalcMTGeneratorModel CalcMultiSpeedDXCoil CalcMultiSpeedDXCoilCooling CalcMultiSpeedDXCoilHeating CalcMultiStageElectricHeatingCoil CalcMultiStageGasHeatingCoil CalcMultiZoneAverageCoolingSetPoint CalcMultiZoneAverageHeatingSetPoint CalcMultiZoneAverageMaxHumSetPoint CalcMultiZoneAverageMinHumSetPoint CalcMultiZoneMaxHumSetPoint CalcMultiZoneMinHumSetPoint CalcMundtModel CalcNCycSysAvailMgr CalcNewZoneHeatCoolFlowRates CalcNewZoneHeatOnlyFlowRates CalcNodeMassFlows CalcNominalWindowCond CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNusselt CalcNusseltJurges CalcNVentSysAvailMgr CalcOAController CalcOAMassFlow CalcOAMassFlow CalcOAMixer CalcOAOnlyMassFlow CalcOAPretreatSetPoint CalcOAUnitCoilComps CalcObstrMultiplier CalcOptStartSysAvailMgr CalcOtherSideDemand CalcOutdoorAirUnit CalcOutsideAirSetPoint CalcOutsideSurfTemp CalcParallelPIU CalcPassiveExteriorBaffleGap CalcPassiveSystem CalcPassiveTranspiredCollector CalcPerSolarBeam CalcPipeHeatTransCoef CalcPipesHeatTransfer CalcPipeTransBeam CalcPlantValves CalcPollution CalcPolyhedronVolume CalcPolynomCoef CalcPondGroundHeatExchanger CalcPredictedHumidityRatio CalcPredictedSystemLoad CalcPTUnit CalcPumps CalcPurchAirLoads CalcPurchAirMinOAMassFlow CalcPurchAirMixedAir CalcPVTcollectors CalcQiceChargeMaxByChiller CalcQiceChargeMaxByITS CalcQiceDischageMax CalcRABFlowSetPoint CalcRackSystem CalcRadSysHXEffectTerm CalcRadTemp CalcRainCollector CalcReformEIRChillerModel CalcResearchSpecialPartLoad CalcReturnAirPath CalcRfFlrCoordinateTransformation CalcSandiaPV CalcSatVapPressFromTemp CalcSchedOffSysAvailMgr CalcSchedOnSysAvailMgr CalcSchedSysAvailMgr CalcScheduledDualSetPoint CalcScheduledSetPoint CalcScreenTransmittance CalcScriptF CalcSeriesPIU CalcSetpointTempTarget CalcSHRUserDefinedCurves CalcSimpleController CalcSimpleHeatingCoil CalcSimplePV CalcSingleSpeedEvapFluidCooler CalcSingleSpeedTower CalcSingZoneClSetPoint CalcSingZoneHtSetPoint CalcSingZoneMaxHumSetPoint CalcSingZoneMinHumSetPoint CalcSingZoneRhSetPoint CalcSkySolDiffuseReflFactors CalcSolarCollector CalcSolarFlux CalcSolidDesiccantDehumidifier CalcSourceFlux CalcSourceTempCoefficents CalcSparrowLeeward CalcSparrowWindward CalcSpecialDayTypes CalcStandAloneERV CalcStandardRatings CalcStaticProperties CalcSteamAirCoil CalcSteamBaseboard CalcSurfaceCentroid CalcSurfaceGroundHeatExchanger CalcSystemEnergyUse CalcSZOneStageCoolingSetPt CalcSZOneStageHeatingSetPt CalcTankTemp CalcTDDTransSolAniso CalcTDDTransSolHorizon CalcTDDTransSolIso CalcTempDistModel CalcTempIntegral CalcTESCoilChargeOnlyMode CalcTESCoilCoolingAndChargeMode CalcTESCoilCoolingAndDischargeMode CalcTESCoilCoolingOnlyMode CalcTESCoilDischargeOnlyMode CalcTESCoilOffMode CalcTESIceStorageTank CalcTESWaterStorageTank CalcThermalChimney CalcThermalComfortAdaptiveASH55 CalcThermalComfortAdaptiveCEN15251 CalcThermalComfortFanger CalcThermalComfortKSU CalcThermalComfortPierce CalcThermalComfortSimpleASH55 CalcTimeNeeded CalcTopFluxCoefficents CalcTopSurfTemp CalcTotalFLux CalcTotCapSHR CalcTotCapSHR_VSWSHP CalcTransAbsorProduct CalcTransRefAbsOfCover CalcTRNSYSPV CalcTrombeWallIntConvCoeff CalcTwoSpeedDXCoilIEERResidual CalcTwoSpeedDXCoilStandardRating CalcTwoSpeedEvapFluidCooler CalcTwoSpeedTower CalcUAIce CalcUCSDCV CalcUCSDDV CalcUCSDUE CalcUCSDUI CalculateAirChillerSets CalculateBasisLength CalculateCase CalculateCoil CalculateCompressors CalculateCondensers CalculateCTFs CalculateDailySolarCoeffs CalculateDayOfWeek CalculateEpsFromNTUandZ CalculateExponentialMatrix CalculateFuncResults CalculateGammas CalculateInverseMatrix CalculateMoodyFrictionFactor CalculateNTUfromEpsAndZ CalculatePollution CalculateSecondary CalculateSubcoolers CalculateSunDirectionCosines CalculateTransCompressors CalculateWalkIn CalculateWaterUseage CalculateWaterUseage CalculateWindowBeamProperties CalculateZoneMRT CalculateZoneVolume CalcUnitaryCoolingSystem CalcUnitaryHeatingSystem CalcUnitarySuppHeatingSystem CalcUnitarySuppSystemtoSP CalcUnitarySystemLoadResidual CalcUnitarySystemToLoad CalcUnitHeater CalcUnitHeaterComponents CalcUnitVentilator CalcUnitVentilatorComponents CalcUnmetPlantDemand CalcUpdateHeatRecovery CalcUpdateHeatRecovery CalcUserDefinedInsideHcModel CalcUserDefinedOutsideHcModel CalcVariableSpeedTower CalcVarSpeedCoilCooling CalcVarSpeedCoilHeating CalcVarSpeedHeatPump CalcVarSpeedHeatPump CalcVAVVS CalcVentilatedSlab CalcVentilatedSlabComps CalcVentilatedSlabRadComps CalcVentSlabHXEffectTerm CalcVerticalGroundHeatExchanger CalcViewFactorToShelf CalcVRF CalcVRFCondenser CalcVRFCoolingCoil CalcVSTowerApproach CalcWallCoordinateTransformation CalcWaltonStableHorizontalOrTilt CalcWaltonUnstableHorizontalOrTilt CalcWarmestSetPoint CalcWarmestSetPointTempFlow CalcWaterMainsTemp CalcWaterSource CalcWaterStorageTank CalcWaterThermalTankMixed CalcWaterThermalTankStratified CalcWaterThermalTankZoneGains CalcWaterToAirHeatpump CalcWatertoAirHPCooling CalcWatertoAirHPHeating CalcWaterToAirResidual CalcWatertoWaterHPCooling CalcWatertoWaterHPHeating CalcWaterUseZoneGains CalcWetIndirectEvapCooler CalcWindowACOutput CalcWindowBlindProperties CalcWindowHeatBalance CalcWindowProfileAngles CalcWindowScreenProperties CalcWindowStaticProperties CalcWindPressure CalcWindPressureCoeffs CalcWindTurbine CalcWinFrameAndDividerTemps CalcWinTransDifSolInitialDistribution CalcWrapperModel CalcZoneAirComfortSetpoints CalcZoneAirTempSetpoints CalcZoneComponentLoadSums CalcZoneDehumidifier CalcZoneEvaporativeCoolerUnit CalcZoneLeavingConditions CalcZoneMassBalance CalcZonePipesHeatGain CalcZoneSums CartesianPipeCellInformation_ctor CellType_IsFieldCell CFSHasControlledShade CFSNGlz CFSRefPointPosFactor CFSRefPointSolidAngle CFSShadeAndBeamInitialization CFSUFactor cGetCoilAirOutletNode cGetCoilSteamInletNode cGetCoilSteamOutletNode CharPreDefTableEntry CheckActuatorNode CheckAndAddAirNodeNumber CheckAndFixCFSLayer CheckAndReadCustomSprectrumData CheckAndReadFaults CheckAndSetConstructionProperties CheckBracketRoundOff CheckBranchForOASys CheckCachedIPErrors CheckCFSStates CheckCoilWaterInletNode CheckControllerListOrder CheckControllerLists CheckConvexity CheckCostEstimateInput CheckCreatedZoneItemName CheckCurveLimitsForIPLV CheckCurveLimitsForStandardRatings CheckDayScheduleValueMinMax CheckDXCoolingCoilInOASysExists CheckFDSurfaceTempLimits CheckFFSchedule CheckFluidPropertyName CheckForActualFileName CheckForBalancedFlow CheckForControllerWaterCoil CheckForGeometricTransform CheckForGeometricTransform CheckForMisMatchedEnvironmentSpecifications CheckForOutOfRangeTempResult CheckForOutOfRangeTemps CheckForRequestedReporting CheckForRunawayPlantTemps CheckForSensorAndSetpointNode CheckGasCoefs CheckHeatingCoilSchedule CheckHXAssistedCoolingCoilSchedule CheckIFAnyEMS CheckIFAnyIdealCondEntSetPoint CheckIfAnyPlant CheckIfNodeSetpointManagedByEMS CheckIncrementRoundOff CheckInternalConsistency CheckLightsReplaceableMinMaxForZone CheckLocationValidity CheckLoopExitNode CheckLowerUpperBracket CheckMarkedNodes CheckMaxActiveController CheckMaxConstraint CheckMicroCHPThermalBalance CheckMinActiveController CheckMinConstraint checkMinimumMonthlyCharge CheckMinMaxCurveBoundaries CheckMinMaxRange CheckModelBoundOutput_HumRat CheckModelBoundOutput_Temp CheckModelBounds CheckModelBoundsHumRatEq CheckModelBoundsRH_HumRatEq CheckModelBoundsRH_TempEq CheckModelBoundsTempEq CheckNodeConnections CheckNodeSetPoint CheckNonSingularity CheckOAControllerName CheckOutAirNodeNumber CheckPlantConvergence CheckPlantMixerSplitterConsistency CheckPlantOnAbort CheckPollutionMeterReporting CheckRefrigerationInput CheckReportVariable CheckRootFinderCandidate CheckRootFinderConvergence CheckScheduledSurfaceGains CheckScheduleValue CheckScheduleValueMinMax Checksetpoints CheckSimpleController CheckSlope CheckSteamCoilSchedule CheckSubSurfaceMiscellaneous CheckSysSizing CheckSystemBranchFlow CheckTDDsAndLightShelvesInDaylitZones CheckThisAirSystemForSizing CheckThisZoneForSizing CheckThreading CheckUniqueNodes CheckUnitarySysCoilInOASysExists CheckUsedConstructions CheckValidSimulationObjects CheckWarmupConvergence CheckWaterCoilSchedule CheckWeatherFileValidity CheckWindowShadingControlFrameDivider CheckZoneEquipmentList CheckZoneSizing CHKBKS CHKGSS CHKSBS CLIP CLIPPOLY CloseDFSFile CloseMiscOpenFiles CloseMoistureBalanceEMPD CloseOutOpenFiles CloseOutputFiles CloseOutputTabularFile CloseReportIllumMaps CloseSocket CloseWeatherFile CoilAreaFracIter CoilCompletelyDry CoilCompletelyWet CoilOutletStreamCondition CoilPartWetPartDry COMMAND_ARGUMENT_COUNT CompactObjectsCheck CompareTwoVectors ComplexFenestrationLuminances ComputeDelayedComponents ComputeDifSolExcZonesWIZWindows ComputeIntSolarAbsorpFactors ComputeIntSWAbsorpFactors ComputeIntThermalAbsorpFactors ComputeLifeCycleCostAndReport ComputeLoadComponentDecayCurve ComputeNominalUwithConvCoeffs ComputePresentValue ComputeTariff ComputeTaxAndDepreciation ComputeWinShadeAbsorpFactors CondOutTempResidual ConstructBasis ControlCBVAVOutput ControlCompOutput ControlCompOutput ControlCoolBeam ControlCoolingSystem ControlCycWindACOutput ControlDesiccantDehumidifier ControlDXHeatingSystem ControlDXSystem ControlFluidHeatExchanger ControlHeatingSystem ControlHumidifier ControlMSHPOutput ControlPTUnitOutput ControlPVTcollector ControlReformEIRChillerModel ControlSuppHeatSystem ControlUnitarySystemOutput ControlUnitarySystemtoLoad ControlUnitarySystemtoSP ControlVRF ControlVSEvapUnitToMeetLoad ControlVSHPOutput ControlVSHPOutput ConvectionFactor ConvertCasetoLower ConvertCasetoUpper ConvertIP ConvertIPdelta ConvertToElementTag ConvertToEscaped CoolBeamResidual CoolingCoil CoolWaterHumRatResidual CoolWaterTempResidual CoolWatertoAirHPHumRatResidual CoolWatertoAirHPTempResidual CorrectZoneAirTemp CorrectZoneContaminants CorrectZoneHumRat CostInfoOut CPCW CPHW CreateBoundaryList CreateBoundaryListCount CreateCategoryNativeVariables CreateCellArray CreateCurrentDateTimeString CreateDefaultComputation CreateEnergyReportStructure CreateFCfactorConstructions CreateHVACStepFullString CreateHVACTimeIntervalString CreateHVACTimeString CreateNewellAreaVector CreateNewellSurfaceNormalVector CreatePartitionCenterList CreatePartitionRegionList CreatePredefinedMonthlyReports CreateRegionList CreateRegionListCount CreateShadedWindowConstruction CreateSQLiteConstructionsTable CreateSQLiteConstructionsTable CreateSQLiteDatabase CreateSQLiteDatabase CreateSQLiteDaylightMap CreateSQLiteDaylightMap CreateSQLiteDaylightMapTitle CreateSQLiteDaylightMapTitle CreateSQLiteEnvironmentPeriodRecord CreateSQLiteEnvironmentPeriodRecord CreateSQLiteErrorRecord CreateSQLiteErrorRecord CreateSQLiteInfiltrationTable CreateSQLiteInfiltrationTable CreateSQLiteMaterialsTable CreateSQLiteMaterialsTable CreateSQLiteMeterDictionaryRecord CreateSQLiteMeterDictionaryRecord CreateSQLiteMeterRecord CreateSQLiteMeterRecord CreateSQLiteNominalBaseboardHeatTable CreateSQLiteNominalBaseboardHeatTable CreateSQLiteNominalElectricEquipmentTable CreateSQLiteNominalElectricEquipmentTable CreateSQLiteNominalGasEquipmentTable CreateSQLiteNominalGasEquipmentTable CreateSQLiteNominalHotWaterEquipmentTable CreateSQLiteNominalHotWaterEquipmentTable CreateSQLiteNominalLightingTable CreateSQLiteNominalLightingTable CreateSQLiteNominalOtherEquipmentTable CreateSQLiteNominalOtherEquipmentTable CreateSQLiteNominalPeopleTable CreateSQLiteNominalPeopleTable CreateSQLiteNominalSteamEquipmentTable CreateSQLiteNominalSteamEquipmentTable CreateSQLiteReportVariableDataRecord CreateSQLiteReportVariableDataRecord CreateSQLiteReportVariableDictionaryRecord CreateSQLiteReportVariableDictionaryRecord CreateSQLiteRoomAirModelTable CreateSQLiteRoomAirModelTable CreateSQLiteSchedulesTable CreateSQLiteSimulationsRecord CreateSQLiteSimulationsRecord CreateSQLiteStringTableRecord CreateSQLiteSurfacesTable CreateSQLiteSurfacesTable CreateSQLiteTabularDataRecords CreateSQLiteTabularDataRecords CreateSQLiteTimeIndexRecord CreateSQLiteTimeIndexRecord CreateSQLiteVentilationTable CreateSQLiteVentilationTable CreateSQLiteZoneGroupTable CreateSQLiteZoneGroupTable CreateSQLiteZoneListTable CreateSQLiteZoneListTable CreateSQLiteZoneTable CreateSQLiteZoneTable CreateStormWindowConstructions CreateSysTimeIntervalString CreateTCConstructions CreateTimeIntervalString CreateTimeString CreatExtBooundCondName CreateZoneExtendedOutput CreateZoneExtendedOutput CrossProduct CrossProduct cSurfaceClass CTRANS CurveValue DateToString DateToStringWithMonth DaylghtAltAndAzimuth DayltgAveInteriorReflectance DayltgClosestObstruction DayltgCrossProduct DayltgCurrentExtHorizIllum DayltgDirectIllumComplexFenestration DayltgDirectSunDiskComplexFenestration DayltgElecLightingControl DayltgExtHorizIllum DayltgGlare DayltgGlarePositionFactor DayltgGlareWithIntWins DayltgHitBetWinObstruction DayltgHitInteriorObstruction DayltgHitObstruction DayltgInteriorIllum DayltgInteriorMapIllum DayltgInteriorTDDIllum DayltgInterReflectedIllum DayltgInterReflectedIllumComplexFenestration DayltgInterReflIllFrIntWins DayltgLuminousEfficacy DayltgPierceSurface DayltgSetupAdjZoneListsAndPointers DayltgSkyLuminance DayltgSurfaceLumFromSun dCheckScheduleValueMinMax1 dCheckScheduleValueMinMax2 DeallocateLoadComponentArrays DebugRootFinder DecodeHHMMField DecodeMonDayHrMin DeflectionTemperatures DeflectionWidths DegradF DElightDaylightCoefficients DElightDaylightCoefficients DElightElecLtgCtrl DElightElecLtgCtrl DElightFreeMemory DElightFreeMemory DElightInputGenerator DElightInputGenerator DElightOutputGenerator DElightOutputGenerator DensityCFSFillGas Depth DERIV DetailsForSurfaces DetectOscillatingZoneTemp DetermineAzimuthAndTilt DetermineBranchFlowRequest DetermineBuildingFloorArea DetermineDateTokens DetermineFrequency DetermineIndexGroupFromMeterGroup DetermineIndexGroupKeyFromMeterName DetermineMaxBackSurfaces DetermineMeterIPUnits DetermineMinuteForReporting DeterminePolygonOverlap DetermineShadowingCombinations DetermineSunUpDown DevelopMesh DiffuseAverage DiffuseAverageProfAngGnd DiffuseAverageProfAngSky DisplayMaterialRoughness DisplayNumberandString DisplaySimDaysProgress DisplayString distance DistributeBBElecRadGains DistributeBBRadGains DistributeBBSteamRadGains DistributeHTRadGains DistributePlantLoad DistributePressureOnBranch DistributeTDDAbsorbedSolar DistributeUserDefinedPlantLoad DL_RES_r2 DLAG DOE2DXCoilHumRatResidual DOE2DXCoilHumRatResidual DOE2DXCoilResidual DOE2DXCoilResidual DOE2DXCoilResidual DoEndOfIterationOperations DomainRectangle_Contains DOMakeUPPERCase DoOneTimeInitializations DOSameString DoShadeControl DoStartOfTimeStepInitializations DownInterpolate4HistoryValues DumpAirLoopStatistics DumpCurrentLineBuffer DUMPVD DUMPVR DXCoilCyclingHumRatResidual DXCoilCyclingHumRatResidual DXCoilCyclingResidual DXCoilCyclingResidual DXCoilVarSpeedHumRatResidual DXCoilVarSpeedHumRatResidual DXCoilVarSpeedResidual DXCoilVarSpeedResidual DXFOut DXFOutLines DXFOutWireFrame DXHeatingCoilResidual DXHeatingCoilResidual DXHeatingCoilResidual DynamicClothingModel DynamicExtConvSurfaceClassification DynamicIntConvSurfaceClassification EchoOutActuatorKeyChoices EchoOutInternalVariableChoices EffectiveEPSLB EffectiveEPSLF EIRChillerHeatRecovery EN673ISO10292 EncodeMonDayHrMin EndEnergyPlus EndUniqueNodeCheck EnthalpyResidual epElapsedTime epGetTimeUsed epGetTimeUsedperCall epStartTime epStopTime epSummaryTimes eptime EQLWindowInsideEffectiveEmiss EQLWindowOutsideEffectiveEmiss EQLWindowSurfaceHeatBalance EquationsSolver ERF EstimateHEXSurfaceArea EvalInsideMovableInsulation EvalOutsideMovableInsulation EvaluateAdiabaticSurfaceTemperature EvaluateBasementCellTemperature EvaluateCellNeighborDirections evaluateChargeBlock evaluateChargeSimple EvaluateExpression EvaluateExtHcModels EvaluateFarfieldBoundaryTemperature EvaluateFarfieldCharacteristics EvaluateFieldCellTemperature EvaluateGroundSurfaceTemperature EvaluateIntHcModels EvaluateLoopSetPointLoad EvaluateNeighborCharacteristics evaluateQualify evaluateRatchet EvaluateSoilRhoCp EvaluateStack EvolveParaUCSDCV ExitCalcController ExpandComplexState ExpressAsCashFlows ExtendObjectDefinition ExteriorBCEqns ExternalInterfaceExchangeVariables ExternalInterfaceInitializeErlVariable ExternalInterfaceSetErlVariable ExternalInterfaceSetSchedule ExtOrIntShadeNaturalFlow Fabric_EstimateDiffuseProps FACSKY FalsePositionMethod FEQX FI FigureACAncillaries FigureAirEnthalpy FigureAirHeatCap FigureAuxilHeatGasHeatCap FigureBeamSolDiffuseReflFactors FigureBeamSolSpecularReflFactors FigureConstGradPattern FigureDayltgCoeffsAtPointsForSunPosition FigureDayltgCoeffsAtPointsForWindowElements FigureDayltgCoeffsAtPointsSetupForWindow FigureElectricalStorageZoneGains FigureFuelCellZoneGains FigureFuelEnthalpy FigureFuelHeatCap FigureGaseousWaterEnthalpy FigureHeightPattern FigureHXleavingGasHeatCap FigureInverterZoneGains FigureLHVofFuel FigureLiquidWaterEnthalpy FigureLiquidWaterHeatCap FigureMapPointDayltgFactorsToAddIllums FigureMicroCHPZoneGains FigureNDheightInZone FigurePowerConditioningLosses FigureProductGasesEnthalpy FigureProductGasHeatCap FigureRefPointDayltgFactorsToAddIllums FigureRefrigerationZoneGains FigureSolarBeamAtTimestep FigureSunCosines FigureSurfMapPattern FigureTDDZoneGains FigureTransformerZoneGains FigureTransientConstraints FigureTwoGradInterpPattern FILJAC FillBasisElement FillDefaultsSWP FillRemainingPredefinedEntries FillWeatherPredefinedEntries film filmg filmi filmPillar FILSKY FinalizeCFS FinalizeCFSLAYER FinalRateCoils FindAirLoopBranchConnection FindAirPlantCondenserLoopFromBranchList FindAllNumbersinList FindArrayIndex FindCompSPInput FindCompSPLoad FindCondenserLoopBranchConnection FindControlledZoneIndexFromSystemNodeNumberForZone FindDeltaTempRangeInput FindDemandSideMatch FindEMSVariable FindFirstLastPtr FindFirstRecord FindGlycol FindHXDemandSideLoopFlow FindInBasis FindItem FindIteminList FindIteminSortedList FindItemInVariableList FindLoopSideInCallingOrder FindNextRecord FindNonSpace FindNumberinList FindOAMixerMatchForOASystem FindPlantLoopBranchConnection FindRangeBasedOrUncontrolledInput FindRangeVariable FindRefrigerant FindRootSimpleController FindStratifiedTankSensedTemp FindTariffIndex FindTDDPipe FindUnitNumber FinishDebugOutputFiles FixViewFactors FluidCellInformation_ctor FM_BEAM FM_DIFF FM_F FNU forcedventilation FourPipeInductionUnitHasMixer FourPipeIUCoolingResidual FourPipeIUHeatingResidual FRA FrostControl FrostControlSetPointLimit FrostControlSetPointLimit FuelCellProductGasEnthResidual FUN FuncDetermineCoolantWaterExitTemp FuncDetermineCWMdotForInternalFlowControl FuncDetermineEngineTemp FV GasElecHeatingCoilResidual GASSES90 GassesLow GatherBEPSResultsForTimestep GatherBinResultsForTimestep GatherComponentLoadsHVAC GatherComponentLoadsIntGain GatherComponentLoadsSurfAbsFact GatherComponentLoadsSurface GatherForEconomics GatherForPredefinedReport GatherHeatGainReport GatherMonthlyResultsForTimestep GatherPeakDemandForTimestep GatherSourceEnergyEndUseResultsForTimestep GaussElimination generate_ears GenerateDElightDaylightCoefficients GenerateDElightDaylightCoefficients GeneratorPowerOutput GenericCrack GenOutputVariablesAuditReport Get2DMatrix Get2DMatrixDimensions GET_COMMAND GET_COMMAND_ARGUMENT Get_Environment_Variable GetActualDXCoilIndex GetAirBranchIndex GetAirFlowFlag GetAirflowNetworkInput GetAirHeatBalanceInput GetAirLoopAvailabilityManager GetAirModelDatas GetAirNodeData GetAirPathData GetAngleFactorList GetATMixer GetATMixerOutNode GetATMixerPriNode GetATMixers GetATMixerSecNode GetAttShdSurfaceData GetAverageTempByType GetBaseboardInput GetBaseboardInput GetBasementFloorHeatFlux GetBasementWallHeatFlux GetBLASTAbsorberInput GetBoilerInput GetBoilerInput GetBranchData GetBranchFanTypeName GetBranchFlow GetBranchInput GetBranchList GetBranchListInput GetBuildingData GetCBVAV GetCellWidths GetCellWidthsCount GetChildrenData GetChillerheaterInput GetCoilAirFlowRate GetCoilAirFlowRateVariableSpeed GetCoilAirInletNode GetCoilAirOutletNode GetCoilAvailScheduleIndex GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacityByIndexType GetCoilCapacityVariableSpeed GetCoilCondenserInletNode GetCoilControlNodeNum GetCoilGroupTypeNum GetCoilIndex GetCoilIndex GetCoilIndex GetCoilIndexVariableSpeed GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNodeVariableSpeed GetCoilMaxSteamFlowRate GetCoilMaxWaterFlowRate GetCoilMaxWaterFlowRate GetCoilMaxWaterFlowRate GetCoilObjectTypeNum GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNodeVariableSpeed GetCoilSteamInletNode GetCoilSteamOutletNode GetCoilTypeNum GetCoilWaterInletNode GetCoilWaterInletNode GetCoilWaterOutletNode GetColumnUsingTabs GetComfortSetpoints GetComponentData GetCondFDInput GetConductivityGlycol GetConnectorList GetConnectorListInput GetConstCOPChillerInput GetConstructData GetControlledZoneIndex GetControllerActuatorNodeNum GetControllerInput GetCoolBeams GetCoolingCoilTypeNameAndIndex GetCooltower GetCostEstimateInput GetCrossVentData GetCTGeneratorInput GetCTGeneratorResults GetCurrentHVACTime GetCurrentMeterValue GetCurrentScheduleValue GetCurveCheck GetCurveIndex GetCurveInput GetCurveMinMaxValues GetCurveName GetCurveObjectTypeNum GetCurveType GetCustomMeterInput GetDaylightingParametersDetaild GetDaylightingParametersInput GetDayScheduleIndex GetDemandManagerInput GetDemandManagerListInput GetDensityGlycol GetDesiccantDehumidifierInput GetDesignDayData GetDesignLightingLevelForZone GetDetShdSurfaceData GetDirectAirInput GetDisplacementVentData GetDSTData GetDualDuctInput GetDualDuctOutdoorAirRecircUse GetDuctInput GetDXCoilAirFlow GetDXCoilAvailSchPtr GetDXCoilBypassedFlowFrac GetDXCoilCapFTCurveIndex GetDXCoilIndex GetDXCoilNumberOfSpeeds GetDXCoils GetDXCoolingSystemInput GetDXHeatPumpSystemInput GetEarthTube GetElecReformEIRChillerInput GetElectricBaseboardInput GetElectricChillerInput GetElectricEIRChillerInput GetEMSInput GetEngineDrivenChillerInput GetEnvironmentalImpactFactorInfo GetEvapFluidCoolerInput GetEvapInput GetExhaustAbsorberInput GetExhaustAirInletNode GetExteriorEnergyUseInput GetExtVentedCavityIndex GetExtVentedCavityIndex GetExtVentedCavityTsColl GetExtVentedCavityTsColl GetFanAvailSchPtr GetFanCoilIndex GetFanCoilInletAirNode GetFanCoilMixedAirNode GetFanCoilOutAirNode GetFanCoilReturnAirNode GetFanCoilUnits GetFanCoilZoneInletAirNode GetFanDesignVolumeFlowRate GetFanIndex GetFanIndexForTwoSpeedCoil GetFanInletNode GetFanInput GetFanOutletNode GetFanPower GetFanSpeedRatioCurveIndex GetFanType GetFanVolFlow GetFarfieldTemp GetFirstBranchInletNodeName GetFluidCoolerInput GetFluidDensityTemperatureLimits GetFluidHeatExchangerInput GetFluidPropertiesData GetFluidSpecificHeatTemperatureLimits GetFrameAndDividerData GetFuelCellGeneratorInput GetFuelCellGeneratorResults GetFuelFactorInfo GetFurnaceInput GetGasAbsorberInput GetGeneratorFuelSupplyInput GetGeometryParameters GetGlycolNameByIndex GetGroundheatExchangerInput GetGroundReflectances GetGroundTemps GetGshpInput GetGshpInput GetGTChillerInput GetHeatBalanceInput GetHeatBalHAMTInput GetHeatExchangerObjectTypeNum GetHeatingCoilIndex GetHeatingCoilInput GetHeatingCoilNumberOfStages GetHeatingCoilPLFCurveIndex GetHeatingCoilTypeNum GetHeatReclaimSourceIndex GetHeatRecoveryInput GetHighTempRadiantSystem GetHPCoolingCoilIndex GetHTSubSurfaceData GetHTSurfaceData GetHTSurfExtVentedCavityData GetHumidifierInput GetHVACSingleDuctSysIndex GetHWBaseboardInput GetHXAssistedCoolingCoilInput GetHXCoilAirFlowRate GetHXCoilType GetHXCoilTypeAndName GetHXDXCoilIndex GetHXDXCoilName GetHybridVentilationControlStatus GetHybridVentilationInputs GetICEGeneratorResults GetICEngineGeneratorInput GetIceStorageInput GetIDFRecordsStats GetIndirectAbsorberInput GetIndUnits GetInputEconomicsChargeBlock GetInputEconomicsChargeSimple GetInputEconomicsComputation GetInputEconomicsCurrencyType GetInputEconomicsQualify GetInputEconomicsRatchet GetInputEconomicsTariff GetInputEconomicsVariable GetInputForLifeCycleCost GetInputFuelAndPollutionFactors GetInputLifeCycleCostNonrecurringCost GetInputLifeCycleCostParameters GetInputLifeCycleCostRecurringCosts GetInputLifeCycleCostUseAdjustment GetInputLifeCycleCostUsePriceEscalation GetInputTabularMonthly GetInputTabularPredefined GetInputTabularStyle GetInputTabularTimeBins GetInputViewFactors GetInputViewFactorsbyName GetInputZoneEvaporativeCoolerUnit GetInstantMeterValue GetInternalBranchData GetInternalHeatGainsInput GetInternalVariableValue GetInternalVariableValue GetInternalVariableValueExternalInterface GetInternalVariableValueExternalInterface GetInterpolatedSatProp GetInterpValue GetIntMassSurfaceData GetLastBranchOutletNodeName GetLastWord GetLightWellData GetListOfObjectsInIDD GetListofSectionsinInput GetLocationInfo GetLoopMixer GetLoopSidePumpIndex GetLoopSplitter GetLowTempRadiantSystem GetMaterialData GetMatrixInput getMaxAndSum GetMeteredVariables GetMeterIndex GetMeterResourceType GetMicroCHPGeneratorInput GetMicroCHPGeneratorResults GetMinOATCompressor GetMixerInput GetMixerInput GetMoistureBalanceEMPDInput GetMonthlyCostForResource GetMovableInsulationData GetMSHeatPumpInput GetMTGeneratorExhaustNode GetMTGeneratorInput GetMTGeneratorResults GetMundtData GetNewUnitNumber GetNextEnvironment GetNodeConnectionType GetNodeList GetNodeListsInput GetNodeNums GetNTUforCrossFlowBothUnmixed GetNumberOfSchedules GetNumberOfSurfaceLists GetNumberOfSurfListVentSlab GetNumChildren GetNumMeteredVariables GetNumOAControllers GetNumOAMixers GetNumOASystems GetNumObjectsFound GetNumObjectsInIDD GetNumRangeCheckErrorsFound GetNumSectionsFound GetNumSectionsinInput GetNumSegmentsForHorizontalTrenches GetNumSplitterMixerInConntrList GetOACompListNumber GetOACompName GetOACompType GetOACompTypeNum GetOAControllerInputs GetOAMixerIndex GetOAMixerInletNodeNumber GetOAMixerInputs GetOAMixerMixedNodeNumber GetOAMixerNodeNumbers GetOAMixerReliefNodeNumber GetOAMixerReturnNodeNumber GetOARequirements GetOASysControllerListIndex GetOASysNumCoolingCoils GetOASysNumHeatingCoils GetOASysNumSimpControllers GetOASystemNumber GetObjectDefInIDD GetObjectDefMaxArgs GetObjectItem GetObjectItemfromFile GetObjectItemNum GetOnlySingleNode GetOperationSchemeInput GetOSCData GetOSCMData GetOutAirNodesInput GetOutdoorAirUnitInputs GetOutdoorAirUnitOutAirNode GetOutdoorAirUnitReturnAirNode GetOutdoorAirUnitZoneInletNode GetOutsideAirSysInputs GetOutsideEnergySourcesInput GetParentData GetPipeInput GetPipesHeatTransfer GetPipingSystemsInput GetPIUs GetPlantAvailabilityManager GetPlantInput GetPlantLoopData GetPlantOperationInput GetPlantProfileInput GetPlantSizingInput GetPlantValvesInput GetPollutionFactorInput GetPondGroundHeatExchanger GetPowerManagerInput GetPressureCurveTypeAndIndex GetPressureSystemInput GetPreviousHVACTime GetProjectControlData GetProjectData GetPTUnit GetPTUnitMixedAirNode GetPTUnitOutAirNode GetPTUnitReturnAirNode GetPTUnitZoneInletAirNode GetPumpInput GetPurchasedAir GetPurchasedAirMixedAirHumRat GetPurchasedAirMixedAirTemp GetPurchasedAirOutAirMassFlow GetPurchasedAirReturnAirNode GetPurchasedAirZoneInletAirNode GetPVGeneratorResults GetPVInput GetPVTcollectorsInput GetPVTThermalPowerProduction GetQualityRefrig GetRecordLocations GetRectDetShdSurfaceData GetRectSubSurfaces GetRectSurfaces GetRefrigeratedRackIndex GetRefrigerationInput GetReportVariableInput GetRequiredMassFlowRate GetResidCrossFlowBothUnmixed GetResourceTypeChar GetReturnAirNodeForZone GetReturnAirPathInput GetRoomAirModelParameters GetRunPeriodData GetRunPeriodDesignData GetRuntimeLanguageUserInput GetSatDensityRefrig GetSatEnthalpyRefrig GetSatPressureRefrig GetSatSpecificHeatRefrig GetSatTemperatureRefrig GetScheduledSurfaceGains GetScheduleIndex GetScheduleMaxValue GetScheduleMinValue GetScheduleName GetScheduleType GetScheduleValuesForDay GetSecondaryInletNode GetSecondaryOutletNode GetSetPointManagerInputs GetShadingSurfReflectanceData GetShadowingInput GetShelfInput GetSimpleAirModelInputs GetSimpleShdSurfaceData GetSimpleWatertoAirHPInput GetSingleDayScheduleValues GetSiteAtmosphereData GetSizingParams GetSnowGroundRefModifiers GetSolarCollectorInput GetSpecialDayPeriodData GetSpecificHeatGlycol getSpecificUnitDivider getSpecificUnitIndex getSpecificUnitMultiplier GetSplitterInput GetSplitterInput GetSplitterNodeNumbers GetSplitterOutletNumber GetStandAloneERV GetStandAloneERVNodes GetStandAloneERVOutAirNode GetStandAloneERVReturnAirNode GetStandAloneERVZoneInletAirNode GetStandardMeterResourceType GetSteamBaseboardInput GetSteamCoilAvailScheduleIndex GetSteamCoilControlNodeNum GetSteamCoilIndex GetSteamCoilInput GetSTM GetStormWindowData GetSupHeatDensityRefrig GetSupHeatEnthalpyRefrig GetSupHeatPressureRefrig GetSupplyAirFlowRate GetSupplyAirFlowRate GetSupplyAirInletNode GetSupplyInletNode GetSupplyOutletNode GetSurfaceCountForOSCM GetSurfaceData GetSurfaceGroundHeatExchanger GetSurfaceHeatTransferAlgorithmOverrides GetSurfaceIndecesForOSCM GetSurfaceListsInputs GetSurfHBDataForMundtModel GetSurfHBDataForTempDistModel GetSysAvailManagerInputs GetSysAvailManagerListInputs GetSysInput GetSystemNodeNumberForZone GetSystemSizingInput GetTDDInput GetTESCoilIndex GetTESCoilInput GetThermalChimney GetTowerInput GetTranspiredCollectorIndex GetTranspiredCollectorInput GetTypeOfCoil GetUFADZoneData GetUnitarySystemDXCoolingCoilIndex GetUnitarySystemInput GetUnitarySystemOAHeatCoolCoil GetUnitConversion GetUnitHeaterInput GetUnitsString GetUnitSubString GetUnitVentilatorInput GetUnitVentilatorMixedAirNode GetUnitVentilatorOutAirNode GetUnitVentilatorReturnAirNode GetUnitVentilatorZoneInletAirNode GetUserConvectionCoefficients GetUserDefinedComponents GetUserDefinedOpSchemeInput GetUserDefinedPatternData GetUTSCTsColl GetVariableKeyCountandType GetVariableKeyCountandType GetVariableKeys GetVariableKeys GetVariableTypeAndIndex GetVariableUnitsString GetVarSpeedCoilInput GetVentilatedSlabInput GetVertices GetViscosityGlycol GetVRFInput GetVSCoilCondenserInletNode GetVSCoilMinOATCompressor GetVSCoilNumOfSpeeds GetWaterCoilAvailScheduleIndex GetWaterCoilCapacity GetWaterCoilIndex GetWaterCoilInput GetWaterMainsTemperatures GetWaterManagerInput GetWaterSource GetWaterThermalTankInput GetWatertoAirHPInput GetWatertoWaterHPInput GetWaterUseInput GetWeatherProperties GetWeatherStation GetWindowAC GetWindowACMixedAirNode GetWindowACOutAirNode GetWindowACReturnAirNode GetWindowACZoneInletAirNode GetWindowGapAirflowControlData GetWindowGlassSpectralData GetWindowShadingControlData GetWindTurbineInput GetWrapperInput GetWTGeneratorResults GetZoneAirDistribution GetZoneAirLoopEquipment GetZoneAirSetpoints GetZoneAndZoneListNames GetZoneContaminanInputs GetZoneContaminanSetpoints GetZoneData GetZoneDehumidifierInput GetZoneDehumidifierNodeNumber GetZoneEqAvailabilityManager GetZoneEquipment GetZoneEquipmentData GetZoneEquipmentData1 GetZoneInfilAirChangeRate GetZoneLoads GetZonePlenumInput GetZoneSizingInput GLtoAMB GoAhead guess HasFractionalScheduleValue hatter HCInWindowStandardRatings HConvGap HcUCSDCV HcUCSDDV HcUCSDUF HeatingCoilVarSpeedCycResidual HeatingCoilVarSpeedResidual HeatPumpRunFrac HeatPumpRunFrac HeatPumpRunFrac HeatWatertoAirHPTempResidual Height HEMINT HIC_ASHRAE HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterHeatingCoilResidual HRadPar HTRANS HTRANS0 HTRANS1 HWBaseboardUAResidual HXAssistDXCoilResidual HXAssistedCoolCoilHRResidual HXAssistedCoolCoilHRResidual HXAssistedCoolCoilTempResidual HXAssistedCoolCoilTempResidual HXDemandSideLoopFlowResidual HybridVentilationControl IAM iCheckScheduleValue ICSCollectorAnalyticalSoluton iGetCoilAirOutletNode iGetCoilSteamInletNode iGetCoilSteamOutletNode INCLOS incrementEconVar IncrementInstMeterCache incrementSteps incrementTableEntry InitAirflowNetwork InitAirflowNetworkData InitAirHeatBalance InitAirLoops InitAirLoopSplitter InitAirMixer InitAirTerminalUserDefined InitAirZoneReturnPlenum InitAirZoneSupplyPlenum InitATMixer InitBaseboard InitBaseboard InitBLASTAbsorberModel InitBoiler InitBoiler InitBoreholeHXSimVars InitBSDFWindows InitCBVAV InitCoilUserDefined InitComplexWindows InitComponentNodes InitConductionTransferFunctions InitConnections InitConstCOPChiller InitController InitCoolBeam InitCTGenerators InitCurveReporting InitDaylightingDevices InitDemandManagers InitDesiccantDehumidifier InitDetailedIceStorage InitDirectAir InitDualDuct InitDuct InitDXCoil InitDXCoolingSystem InitDXHeatPumpSystem InitElecReformEIRChiller InitElectricBaseboard InitElectricChiller InitElectricEIRChiller InitEMS InitEMSControlledConstructions InitEMSControlledSurfaceProperties InitEnergyReports InitEngineDrivenChiller InitEquivalentLayerWindowCalculations InitEvapCooler InitEvapFluidCooler InitExhaustAbsorber InitExteriorConvectionCoeff InitFan InitFanCoilUnits InitFluidCooler InitFluidHeatExchanger InitFuelCellGenerators InitFurnace InitGasAbsorber InitGlassOpticalCalculations InitGshp InitGshp InitGTChiller InitHeatBalance InitHeatBalFiniteDiff InitHeatBalHAMT InitHeatingCoil InitHeatRecovery InitHighTempRadiantSystem InitHumidifier InitHWBaseboard InitHXAssistedCoolingCoil InitHybridVentSysAvailMgr InitialInitHeatBalFiniteDiff InitializeCFSDaylighting InitializeCFSStateData InitializeComponentSizingTable InitializeConstructionsTables InitializeDaylightMapTables InitializeEnvironmentPeriodsTable InitializeErrorsTable InitializeGlycolTempLimits InitializeHeatTransferPipes InitializeIndexes InitializeIndexes InitializeLoops InitializeMaterialsTable InitializeMeters initializeMonetaryUnit InitializeNominalBaseboardHeatTable InitializeNominalElectricEquipmentTable InitializeNominalGasEquipmentTable InitializeNominalHotWaterEquipmentTable InitializeNominalInfiltrationTable InitializeNominalLightingTable InitializeNominalOtherEquipmentTable InitializeNominalPeopleTable InitializeNominalSteamEquipmentTable InitializeNominalVentilationTable InitializeOperatingMode InitializeOutput InitializePipes InitializePredefinedMonthlyTitles InitializePsychRoutines InitializePumps InitializeRefrigerantLimits InitializeReportMeterDataDictionaryTable InitializeReportMeterDataTables InitializeReportVariableDataDictionaryTable InitializeReportVariableDataTables InitializeRoomAirModelTable InitializeRootFinder InitializeRuntimeLanguage InitializeSchedulesTable InitializeSimulationsTable InitializeSQLiteTables InitializeSurfacesTable InitializeSystemSizingTable InitializeTabularDataTable InitializeTabularDataTable InitializeTabularDataView InitializeTabularDataView InitializeTabularMonthly InitializeTimeIndicesTable InitializeViews InitializeWeather InitializeZoneGroupTable InitializeZoneInfoTable InitializeZoneListTable InitializeZoneSizingTable InitICEngineGenerators InitIndirectAbsorpChiller InitIndUnit InitInteriorConvectionCoeffs InitInteriorRadExchange InitInternalHeatGains InitIntSolarDistribution InitLoadBasedControl InitLoadDistribution InitLowTempRadiantSystem InitMicroCHPNoNormalizeGenerators InitMoistureBalanceEMPD InitMSHeatPump InitMTGenerators InitMundtModel InitOAController InitOAMixer InitOneTimePlantSizingInfo InitOutAirNodes InitOutdoorAirUnit InitOutsideAirSys InitPipesHeatTransfer InitPipingSystems InitPIU InitPlantProfile InitPlantUserComponent InitPlantValves InitPollutionMeterReporting InitPondGroundHeatExchanger InitPressureDrop InitPTUnit InitPurchasedAir InitPVTcollectors InitRefrigeration InitRefrigerationPlantConnections InitReturnAirPath InitSecretObjects InitSetPointManagers InitSimpleIceStorage InitSimpleMixingConvectiveHeatGains InitSimpleWatertoAirHP InitSimVars InitSimVars InitSimVars InitSimVars InitSolarCalculations InitSolarCollector InitSolarHeatGains InitSolReflRecSurf InitStandAloneERV InitSteamBaseboard InitSteamCoil InitSurfaceGroundHeatExchanger InitSurfaceHeatBalance InitSys InitSysAvailManagers InitSystemOutputRequired InitTempDistModel InitTESCoil InitThermalAndFluxHistories InitThermalComfort InitTower InitTranspiredCollector InitTRNSYSPV InitUCSDCV InitUCSDDV InitUCSDUF InitUniqueNodeCheck InitUnitarySystems InitUnitHeater InitUnitVentilator InitVarSpeedCoil InitVentilatedSlab InitVRF InitWaterCoil InitWaterSource InitWaterThermalTank InitWatertoAirHP InitWatertoWaterHP InitWindowAC InitWindTurbine InitWrapper InitZoneAirLoopEquipment InitZoneAirSetpoints InitZoneAirUserDefined InitZoneContSetpoints InitZoneDehumidifier InitZoneEquipment InitZoneEvaporativeCoolerUnit InPolygon InsertCurrencySymbol int_times_vector INTCPT Integer_IsInRange IntegerIsWithinTwoValues IntegerToString InterConnectTwoPlantLoopSides InteriorBCEqns InteriorNodeEqns InternalRangeCheck InternalSetupTankDemandComponent InternalSetupTankSupplyComponent interp INTERP InterpBlind InterpDefValuesForGlycolConc Interpolate Interpolate_Lagrange InterpolateBetweenFourValues InterpolateBetweenTwoValues InterpolatePipeTransBeam InterpProfAng InterpProfSlatAng InterpretWeatherDataLine InterpSlatAng InterpSw InterpValuesForGlycolConc IntInterfaceNodeEqns IntPreDefTableEntry IntToStr Invert3By3Matrix InvertMatrix InvJulianDay IPTrimSigDigits iRoundSigDigits IS_BEAM IS_DIFF IS_DSRATIO IS_F IS_LWP IS_OPENNESS IS_SWP isCompLoadRepReq IsControlledShade IsConverged_CurrentToPrevIteration IsConverged_PipeCurrentToPrevIteration IsCurveInputTypeValid IsCurveOutputTypeValid isExternalInterfaceErlVariable IsGlazeLayerX IsGZSLayer isInQuadrilateral IsInRange isInTriangle IsLeapYear IsNodeOnSetPtManager IsParentObject IsParentObjectCompSet IsShadingLayer IssueSevereAlphaInputFieldError IssueSevereInputFieldError IssueSevereRealInputFieldError IsValidConnectionType IsVBLayer isWithinRange ITERATE IterateRootFinder iTrimSigDigits JGDate JulianDay LClimb LDSumMax LDSumMean LEEDtariffReporting LimitCoilCapacity LimitController LimitTUCapacity LinesOut linint LoadEquipList LoadInterface LogicalToInteger LogicalToInteger LogPlantConvergencePoints lookupOperator LookUpScheduleValue LookUpSeason LookupSItoIP lubksb LUBKSB ludcmp LUDCMP LUdecomposition LUsolution MakeAnchorName MakeHVACTimeIntervalString MakeMirrorSurface MakeRectangularVertices MakeRelativeRectangularVertices MakeTransition MakeUPPERCase ManageAirflowNetworkBalance ManageAirHeatBalance ManageAirLoops ManageAirModel ManageBranchInput ManageControllers ManageCoolTower ManageDemand ManageEarthTube ManageElectCenterStorageInteractions ManageElectricLoadCenters ManageElectStorInteractions ManageEMS ManageExteriorEnergyUse ManageGeneratorControlState ManageGeneratorFuelFlow ManageHeatBalance ManageHeatBalFiniteDiff ManageHeatBalHAMT ManageHVAC ManageHybridVentilation ManageInsideAdaptiveConvectionAlgo ManageInternalHeatGains ManageInverter ManageMundtModel ManageNonZoneEquipment ManageOutsideAdaptiveConvectionAlgo ManageOutsideAirSystem ManagePlantLoadDistribution ManagePlantLoops ManageRefrigeratedCaseRacks ManageSetPoints ManageSimulation ManageSingleCommonPipe ManageSizing ManageSurfaceHeatBalance ManageSystemAvailability ManageThermalChimney ManageThermalComfort ManageTransformers ManageTwoWayCommonPipe ManageUCSDCVModel ManageUCSDDVModel ManageUCSDUFModels ManageUserDefinedPatterns ManageWater ManageWaterInits ManageWeather ManageZoneAirLoopEquipment ManageZoneAirUpdates ManageZoneContaminanUpdates ManageZoneEquipment MapExtConvClassificationToHcModels MapIntConvClassificationToHcModels MarkNode MatchAndSetColorTextString MatchPlantSys MatrixIndex matrixQBalance MeshPartition_CompareByDimension MeshPartition_SelectionSort MeshPartitionArray_Contains MinePlantStructForInfo MixedAirControlTempResidual ModifyWindow Modulus MonthToMonthNumber MovingAvg MRXINV MSHPCyclingResidual MSHPHeatRecovery MSHPVarSpeedResidual MultiModeDXCoilHumRatResidual MultiModeDXCoilHumRatResidual MultiModeDXCoilResidual MultiModeDXCoilResidual MultiModeDXCoilResidual MultiSpeedDXCoolingCoilStandardRatings MultiSpeedDXHeatingCoilStandardRatings MULTOL MyPlantSizingIndex NeighborInformationArray_Value NETRAD NewEMSVariable NewExpression newPreDefColumn newPreDefReport newPreDefSubTable NEWTON NodeHasSPMCtrlVarType NormalArea NumBranchesInBranchList NumCompsInBranch nusselt NusseltNumber OpenEPlusWeatherFile OPENNESS_LW OpenOutputFiles OpenOutputTabularFile OpenWeatherFile OPERATOR (*) OPERATOR (+) OPERATOR (-) OPERATOR (.dot.) OPERATOR (.twodcross.) OPERATOR (.twoddot.) OPERATOR (/) ORDER OutBaroPressAt OutDewPointTempAt OutDryBulbTempAt OutsidePipeHeatTransCoef OutWetBulbTempAt P01 PanesDeflection ParametricObjectsCheck parseComputeLine ParseExpression ParseStack ParseTime PartLoadFactor PassiveGapNusseltNumber PassPressureAcrossInterface PassPressureAcrossMixer PassPressureAcrossSplitter PD_BEAM PD_BEAM_CASE_I PD_BEAM_CASE_II PD_BEAM_CASE_III PD_BEAM_CASE_IV PD_BEAM_CASE_V PD_BEAM_CASE_VI PD_DIFF PD_LW PD_LWP PD_SWP PerformanceCurveObject PerformanceTableObject PerformIterationLoop PerformPipeCellSimulation PerformPipeCircuitSimulation PerformSolarCalculations PerformTemperatureFieldUpdate PierceSurface PierceSurfaceVector PipeCircuitInfo_InitInOutCells PipeSegmentInfo_InitPipeCells PIUInducesPlenumAir PIUnitHasMixer PlaneEquation PlantHalfLoopSolver PlantMassFlowRatesFunc PLRResidual PLRResidual PLRResidualMixedTank PLRResidualStratifiedTank PMVResidual POLY1F POLY2F POLYF polygon_contains_point_2d popStack pos PostIPProcessing POWER PreDefTableEntry PredictSystemLoads PredictZoneContaminants PreparePipeCircuitSimulation PrepDebugFilesAndVariables PreProcessorCheck PrepVariablesISO15099 PreScanReportingVariables PresProfile PressureCurveValue ProcessDataDicFile ProcessDateString ProcessEMSInput ProcessEPWHeader ProcessForDayTypes ProcessInput ProcessInputDataFile ProcessIntervalFields ProcessMinMaxDefLine ProcessNumber ProcessScheduleInput ProcessSurfaceVertices ProcessTokens ProduceMinMaxString ProduceMinMaxStringWStartMinute ProduceRDDMDD ProfileAngle PropagateResolvedFlow PStack PsyCpAirFnWTdb PsyHfgAirFnWTdb PsyHFnTdbRhPb PsyHFnTdbW PsyHgAirFnWTdb PsyPsatFnTemp PsyPsatFnTemp_raw PsyRhFnTdbRhov PsyRhFnTdbRhovLBnd0C PsyRhFnTdbWPb PsyRhoAirFnPbTdbW PsyRhovFnTdbRh PsyRhovFnTdbRhLBnd0C PsyRhovFnTdbWPb PsyTdbFnHW PsyTdpFnTdbTwbPb PsyTdpFnWPb PsyTsatFnHPb PsyTsatFnPb PsyTwbFnTdbWPb PsyTwbFnTdbWPb_raw PsyVFnTdbWPb PsyWFnTdbH PsyWFnTdbRhPb PsyWFnTdbTwbPb PsyWFnTdpPb psz Pt2Plane PullCompInterconnectTrigger PumpDataForTable PushBranchFlowCharacteristics PushInnerTimeStepArrays pushStack PushSystemTimestepHistories PushSystemTimestepHistories PushZoneTimestepHistories PushZoneTimestepHistories QsortC QsortPartition RadialCellInfo_XY_CrossSectArea RadialCellInformation_ctor RadialSizing_Thickness Rainflow RangeCheck RB_BEAM RB_DIFF RB_F RB_LWP RB_SWP rCheckDayScheduleValueMinMax rCheckScheduleValue rCheckScheduleValueMinMax1 rCheckScheduleValueMinMax2 ReadEnergyMeters ReadEPlusWeatherForDay ReadGeneralDomainInputs ReadHorizontalTrenchInputs ReadINIFile ReadInputLine ReadPipeCircuitInputs ReadPipeSegmentInputs ReadTableData ReadUserWeatherInput ReadWeatherForDay Real_ConstrainTo Real_IsInRange real_times_vector ReAllocateAndPreserveOutputVariablesForSimulation ReallocateIntegerArray ReallocateIVar ReallocateRealArray ReallocateRVar RealPreDefTableEntry RealToStr RecKeepHeatBalance RecordOutput RectangleF_Contains ReformEIRChillerCondInletTempResidual ReformEIRChillerHeatRecovery RegisterNodeConnection RegisterPlantCompDesignFlow RegulateCondenserCompFlowReqOp ReInitPlantLoopsAtFirstHVACIteration RemoveSpaces RemoveTrailingZeros reorder ReplaceBlanksWithUnderscores ReplaceBlanksWithUnderscores ReportAirflowNetwork ReportAirHeatBalance ReportAirLoopConnections ReportAirTerminalUserDefined ReportAndTestGlycols ReportAndTestRefrigerants ReportBaseboard ReportBaseboard ReportCBVAV ReportChillerIPLV ReportCoilUserDefined ReportCompSetMeterVariables ReportController ReportCoolBeam ReportCoolTower ReportCTFs ReportCWTankInits ReportDemandManagerList ReportDesiccantDehumidifier ReportDetailedIceStorage ReportDirectAir ReportDualDuct ReportDualDuctConnections ReportDuct ReportDXCoil ReportDXCoilRating ReportDYMeters ReportEarthTube ReportEconomicVariable ReportElectricBaseboard ReportEMS ReportEvapCooler ReportEvapFluidCooler ReportExteriorEnergyUse ReportFan ReportFanCoilUnit ReportFatalGlycolErrors ReportFatalRefrigerantErrors ReportFiniteDiffInits ReportFluidCooler ReportFluidHeatExchanger ReportForTabularReports ReportFurnace ReportGlass ReportHeatBalance ReportHeatingCoil ReportHeatRecovery ReportHighTempRadiantSystem ReportHRMeters ReportHumidifier ReportHWBaseboard ReportIllumMap ReportingFreqName ReportingThisVariable ReportInternalHeatGains ReportLoopConnections ReportLowTempRadiantSystem ReportMaxVentilationLoads ReportMeterDetails ReportMissing_RangeData ReportMixer ReportMNMeters ReportMoistureBalanceEMPD ReportMSHeatPump ReportNodeConnections ReportOAController ReportOAMixer ReportOrphanFluids ReportOrphanRecordObjects ReportOrphanSchedules ReportOutdoorAirUnit ReportOutputFileHeaders ReportParentChildren ReportPipesHeatTransfer ReportPIU ReportPlantProfile ReportPlantUserComponent ReportPlantValves ReportPondGroundHeatExchanger ReportPTUnit ReportPumps ReportPurchasedAir ReportPV ReportRackSystem ReportRefrigerationComponents ReportReturnAirPath ReportRuntimeLanguage ReportScheduleDetails ReportScheduleValues ReportSizingOutput ReportSMMeters ReportSolarCollector ReportSplitter ReportStandAloneERV ReportStandAloneWaterUse ReportSteamBaseboard ReportSteamCoil ReportSurfaceErrors ReportSurfaceGroundHeatExchngr ReportSurfaceHeatBalance ReportSurfaces ReportSurfaceShading ReportSys ReportSysSizing ReportSystemEnergyUse ReportThermalChimney ReportTowers ReportTSMeters ReportUnitarySystem ReportUnitHeater ReportUnitVentilator ReportVentilatedSlab ReportVRFCondenser ReportVRFTerminalUnit ReportWarmupConvergence ReportWaterCoil ReportWaterManager ReportWaterThermalTank ReportWaterUse ReportWeatherAndTimeInformation ReportWindowAC ReportWindTurbine ReportZoneAirLoopEquipment ReportZoneAirUserDefined ReportZoneDehumidifier ReportZoneEquipment ReportZoneEvaporativeCoolerUnit ReportZoneMeanAirTemp ReportZoneReturnPlenum ReportZoneSizing ReportZoneSupplyPlenum ResetAllPlantInterConnectFlags ResetController ResetEnvironmentCounter ResetHVACControl ResetNodeData ResetPerformanceCurveOutput ResetRootFinder ResetTerminalUnitFlowLimits ResetWeekDaysByMonth Resimulate resist ReSolveAirLoopControllers ResolveAirLoopFlowLimits ResolveLocationInformation ResolveLockoutFlags ResolveLoopFlowVsPressure ResolveParallelFlows ResolveSysFlow ReverseAndRecalculate RevertZoneTimestepHistories RevertZoneTimestepHistories RevisePlantCallingOrder RezeroZoneSizingArrays RhoH2O RHtoVP RKG RoundSigDigits rRoundSigDigits rTrimSigDigits SafeCopyPlantNode SafeDiv SafeDivide SameString SandiaCellTemperature SandiaEffectiveIrradiance SandiaF1 SandiaF2 SandiaImp SandiaIsc SandiaIx SandiaIxx SandiaModuleTemperature SandiaTcellFromTmodule SandiaVmp SandiaVoc SaveSimpleController ScanForReports ScanPlantLoopsForNodeNum ScanPlantLoopsForObject sCheckDayScheduleValueMinMax ScheduleAverageHoursPerWeek SEARCH SearchAscTable SearchWindow5DataFile SecantFormula SecantMethod selectTariff SetActuatedBranchFlowRate SetAdditionalNeighborData SetAllFlowLocks SetAllPlantSimFlagsToValue SetATMixerPriFlow SetATMixerPriFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetCoilDesFlow SetCoilSystemCoolingData SetCoilSystemHeatingDXFlag SetCompFlowRate SetComponentFlowRate SetCurrentWeather SetCurveOutputMinMaxValues SetDSTDateRanges SetDXCoilTypeData SetDXCoolingCoilData SetEquivalentLayerWindowProperties SetErlValueNumber SetExtConvectionCoeff SetFanData SetHeatExchangerData SetHeatToReturnAirFlag SetInitialMeterReportingAndOutputNames SetIntConvectionCoeff SetInternalVariableValue SetMinMax setNativeVariables SetNodeResult SetOAControllerData SetOnOffMassFlowRate SetOnOffMassFlowRate SetOnOffMassFlowRate SetOnOffMassFlowRateVSCoil SetOnOffMassFlowRateVSCoil SetOutAirNodes SetOutBulbTempAt SetPredefinedTables SetSimpleWSHPData SETSKY SetSpecialDayDates SetSpeedVariables SetStormWindowControl SetSurfHBDataForMundtModel SetSurfHBDataForTempDistModel SetSurfTmeanAir SETUP4x4_A SetupAdaptiveConvectionRadiantSurfaceData SetupAdaptiveConvectionStaticMetaData SetupAirLoopControllersTracer SetupAllOutputVariables SetUpAndSort SetupBranchControlTypes SetupCellNeighbors SetupCommonPipes SetupComplexFenestrationMaterialInput SetupComplexFenestrationStateInput SetupComplexWindowStateGeometry SetUpCompSets SetupDElightOutput4EPlus SetupDElightOutput4EPlus SetUpDesignDay SetupEMSActuator SetupEMSIntegerActuator SetupEMSIntegerInternalVariable SetupEMSInternalVariable SetupEMSLogicalActuator SetupEMSRealActuator SetupEMSRealInternalVariable SetupEnvironmentTypes SetupFuelConstituentData SetupGeneratorControlStateManager SetupIndividualControllerTracer SetupInitialPlantCallingOrder SetupIntegerOutputVariable SetupInterpolationValues SetupLoopFlowRequest SetupMeteredVarsForSetPt SetupMundtModel SetupNodeSetpointsAsActuators SetupNodeVarsForReporting SetupOutputVariable SetupPipeCircuitInOutCells SetupPlantEMSActuators SetupPollutionCalculations SetupPollutionMeterReporting SetupPossibleOperators SetupPrimaryAirSystemAvailMgrAsActuators SetupPumpMinMaxFlows SetupRealOutputVariable SetupRealOutputVariable_IntKey SetupReportInput SetupReports SetupRootFinder SetUpSchemeColors SetupShadeSurfacesForSolarCalcs SetupSimpleWindowGlazingSystem SetupSimulation SetupStratifiedNodes SetupSurfaceConstructionActuators SetupSurfaceConvectionActuators SetupSurfaceOutdoorBoundaryConditionActuators SetUpSysSizingArrays SetupTankDemandComponent SetupTankSupplyComponent SetupThermostatActuators SetupTimePointers SetupUnitConversions SetupWeekDaysByMonth SetupWindowShadingControlActuators SetupZoneEquipmentForConvectionFlowRegime SetupZoneGeometry SetupZoneInfoAsInternalDataAvail SetupZoneInternalGain SetupZoneInternalGain SetupZoneSizing SetUpZoneSizingArrays SetUTSCQdotSource SetVarSpeedCoilData SetVentedModuleQdotSource SetVSHPAirFlow SetVSHPAirFlow SetWindSpeedAt SetZoneEquipSimOrder shading shadingedge shadingin SHADOW SharedDVCVUFDataInit SHDBKS SHDGSS SHDRVL SHDSBS shift ShiftPipeTemperaturesForNewIteration ShiftPlantLoopSideCallingOrder ShiftTemperaturesForNewIteration ShiftTemperaturesForNewTimeStep ShowAuditErrorMessage ShowBranchesOnLoop ShowContinueError ShowContinueError ShowContinueErrorTimeStamp ShowContinueErrorTimeStamp ShowErrorMessage ShowErrorMessage ShowFatalError ShowFatalError ShowMessage ShowMessage ShowPsychrometricSummary ShowRecurringContinueErrorAtEnd ShowRecurringContinueErrorAtEnd ShowRecurringErrors ShowRecurringSevereErrorAtEnd ShowRecurringSevereErrorAtEnd ShowRecurringWarningErrorAtEnd ShowRecurringWarningErrorAtEnd ShowSevereError ShowSevereError ShowSevereMessage ShowSevereMessage ShowWarningError ShowWarningError ShowWarningMessage ShowWarningMessage showWarningsBasedOnTotal Sim4PipeFanCoil SimAirChillerSet SimAirLoop SimAirLoopComponent SimAirLoopComponents SimAirLoops SimAirLoopSplitter SimAirMixer SimAirTerminalUserDefined SimAirZonePlenum SimATMixer SimBaseboard SimBLASTAbsorber SimBoiler SimCBVAV SimCBVAV SimCentralGroundSourceHeatPump SimChiller SimCoilUserDefined SimComponentModelFan SimConstVol SimCoolBeam SimCostEstimate SimCTGenerator SimCTPlantHeatRecovery SimCyclingWindowAC SimDesiccantDehumidifier SimDetailedIceStorage SimDirectAir SimDistrictEnergy SimDualDuctConstVol SimDualDuctVarVol SimDualDuctVAVOutdoorAir SimDuct SimDXCoil SimDXCoilMultiMode SimDXCoilMultiSpeed SimDXCoolingSystem SimDXHeatPumpSystem SimElecBaseBoard SimElectricBaseBoard SimElectricConvective SimElectricEIRChiller SimEvapCooler SimEvapFluidCoolers SimExhaustAbsorber SimFanCoilUnit SimFluidCoolers SimFluidHeatExchanger SimFourPipeIndUnit SimFuelCellGenerator SimFuelCellPlantHeatRecovery SimFurnace SimGasAbsorber SimGroundHeatExchangers SimHeatPumpWaterHeater SimHeatRecovery SimHighTempRadiantSystem SimHPWatertoWaterCOOLING SimHPWatertoWaterHEATING SimHPWatertoWaterSimple SimHumidifier SimHVAC SimHWBaseboard SimHWConvective SimHXAssistedCoolingCoil SimICEngineGenerator SimICEPlantHeatRecovery SimIceStorage SimIndirectAbsorber SimIndUnit SimLowTempRadiantSystem SimMicroCHPGenerator SimMicroCHPPlantHeatRecovery SimMSHeatPump SimMSHP SimMTGenerator SimMTPlantHeatRecovery SimMultiSpeedCoils SimOAComponent SimOAController SimOAMixer SimOnOffFan SimOutdoorAirEquipComps SimOutdoorAirUnit SimOutsideAirSys SimOutsideEnergy SimPackagedTerminalUnit SimPipes SimPipesHeatTransfer SimPipingSystemCircuit SimPIU SimPlantEquip SimPlantValves SimpleCoolingCoilUAResidual SimpleEvapFluidCoolerUAResidual SimpleFluidCoolerUAResidual SimpleHeatingCoilUAResidual SimpleTowerApproachResidual SimpleTowerTrResidual SimpleTowerUAResidual SimPondGroundHeatExchanger SimPressureDropSystem SimPTUnit SimPumps SimPurchasedAir SimPVGenerator SimPVTcollectors SimReformulatedEIRChiller SimRefrigCondenser SimReturnAirPath SimSelectedEquipment SimSetPointManagers SimSimpleEvapFluidCooler SimSimpleFan SimSimpleFluidCooler SimSimpleTower SimSolarCollector SimStandAloneERV SimSteamBaseboard SimSteamBoiler SimSteamCoils SimSurfaceGroundHeatExchanger SimSysAvailManager SimTESCoil SimTowers SimTranspiredCollector SimulateAllInteriorRadialSoilSlices SimulateAllLoopSideBranches SimulateAllLoopSidePumps SimulateDemandManagerList SimulateDetailedRefrigerationSystems SimulateDetailedTransRefrigSystems SimulateDualDuct SimulateFanComponents SimulateFluidCell SimulateHeatingCoilComponents SimulateInnerMostRadialSoilSlice SimulateLoopSideBranchGroup SimulateOuterMostRadialSoilSlice SimulatePlantProfile SimulateRadialInsulationCell SimulateRadialPipeCell SimulateRadialToCartesianInterface SimulateSingleDuct SimulateSteamCoilComponents SimulateVRF SimulateWaterCoilComponents SimulateWaterHeaterStandAlone SimulateWaterUse SimulateWaterUseConnection SimUnitaryBypassVAV SimUnitarySystem SimUnitHeater SimUnitVentilator SimUnitVentOAMixer SimUserDefinedPlantComponent SimVariableSpeedCoils SimVariableSpeedHP SimVariableSpeedHP SimVariableTower SimVariableVolumeFan SimVAV SimVAVVS SimVentilatedSlab SimVentSlabOAMixer SimVRF SimVRFCondenserPlant SimWaterCoils SimWaterSource SimWaterThermalTank SimWatertoAirHP SimWatertoAirHPSimple SimWindowAC SimWindTurbine SimZoneAirLoopEquipment SimZoneAirUserDefined SimZoneDehumidifier SimZoneEquipment SimZoneEvaporativeCoolerUnit SimZoneExhaustFan SimZoneOutAirUnitComps SingelSpeedDXCoolingCoilStandardRatings SingleSpeedDXHeatingCoilStandardRatings SingleSpeedFluidCooler SizeAbsorpChiller SizeAirLoopBranches SizeAirLoops SizeBaseboard SizeBoiler SizeBoiler SizeCBVAV SizeConstCOPChiller SizeController SizeCoolBeam SizeDemandSidePlantConnections SizeDirectAir SizeDualDuct SizeDXCoil SizeElecReformEIRChiller SizeElectricBaseboard SizeElectricBaseboard SizeElectricChiller SizeElectricEIRChiller SizeEngineDrivenChiller SizeEvapCooler SizeEvapFluidCooler SizeExhaustAbsorber SizeFan SizeFanCoilUnit SizeFluidCooler SizeFluidHeatExchanger SizeFurnace SizeGasAbsorber SizeGTChiller SizeHeatingCoil SizeHeatRecovery SizeHighTempRadiantSystem SizeHumidifier SizeHVACWaterToAir SizeHWBaseboard SizeIndirectAbsorpChiller SizeIndUnit SizeLowTempRadiantSystem SizeMSHeatPump SizeOAController SizeOutdoorAirUnit SizePIU SizePlantLoop SizePTUnit SizePump SizePurchasedAir SizePVT SizeStandAloneERV SizeStandAloneWaterHeater SizeSteamBaseboard SizeSteamCoil SizeSupplySidePlantConnections SizeSys SizeTankForDemandSide SizeTankForSupplySide SizeTESCoil SizeTower SizeUCSDUF SizeUnitarySystem SizeUnitHeater SizeUnitVentilator SizeVarSpeedCoil SizeVentilatedSlab SizeVRF SizeVRFCondenser SizeVSMerkelTower SizeWaterCoil SizeWaterManager SizeWaterSource SizeWindowAC SizeWrapper SizeZoneDehumidifier SizeZoneEquipment SizeZoneEvaporativeCoolerUnit SkipEPlusWFHeader SkyDifSolarShading SkyGndWeight SkyWeight SLtoAMB SLtoGL SLVSKY solar_EN673 solarISO15099 SolarSprectrumAverage SOLMATS SolveAirLoopControllers SolveForWindowTemperatures SolveRegression SolveRegulaFalsi SolverMoistureBalanceEMPD SOLVZP SortHistory Specular_Adjust Specular_EstimateDiffuseProps Specular_F Specular_OffNormal Specular_RATDiff Specular_SWP SQLiteBegin SQLiteBegin SQLiteBindDouble SQLiteBindInteger SQLiteBindLogicalMacro SQLiteBindNULL SQLiteBindText SQLiteBindTextMacro SQLiteClearBindings SQLiteCloseDatabase SQLiteColumnInt SQLiteColumnIntMacro SQLiteCommit SQLiteCommit SQLiteExecuteCommand SQLiteExecuteCommandMacro SQLiteFinalizeCommand SQLiteOpenDatabase SQLiteOpenDatabaseMacro SQLitePrepareStatement SQLitePrepareStatementMacro SQLiteResetCommand SQLiteStepCommand SQLiteWriteMessage SQLiteWriteMessageMacro SQLiteWriteMessageMacro StandardIndexTypeKey StandardVariableTypeKey StartingWindowTemps StartingWinTempsForNominalCond SteamHeatingCoilResidual StorageType StoreAPumpOnCurrentTempLoop storeIterationResults StoreRecurringErrorMessage StringValue StrToReal SumAllInternalCO2Gains SumAllInternalConvectionGains SumAllInternalGenericContamGains SumAllInternalLatentGains SumAllInternalRadiationGains SumAllReturnAirConvectionGains SumAllReturnAirLatentGains SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumInternalCO2GainsByTypes SumInternalConvectionGainsByTypes SumInternalLatentGainsByTypes SumInternalRadiationGainsByTypes SummarizeErrors SumReturnAirConvectionGainsByTypes SumZoneImpacts SUN3 SUN4 SupSATResidual SurfaceScheduledSolarInc SurveyDemandManagers SystemPropertiesAtLambdaAndPhi SystemSpectralPropertiesAtPhi TableLookupObject TARCOG90 TBND TdbFnHRhPb TDMA TDMA_R TellMeHowManyObjectItemArgs TemperaturesFromEnergy TempIPtoSI TempSItoIP terpld TESCoilHumRatResidual TESCoilResidual TestAirPathIntegrity TestBranchIntegrity TestCompSet TestCompSetInletOutletNodes TestInletOutletNodes TestReturnAirPathIntegrity TestSupplyAirPathIntegrity therm1d TightenNodeMinMaxAvails TimestepInitComplexFenestration TimestepTypeName TraceAirLoopController TraceAirLoopControllers TraceIndividualController TraceIterationStamp TrackAirLoopController TrackAirLoopControllers TRadC TransAndReflAtPhi TransformVertsByAspect TransTDD Triangulate TrimSigDigits TurnOffLoopEquipment TurnOffLoopSideEquipment TurnOffReportRangeCheckErrors TurnOnPlantLoopPipes TurnOnReportRangeCheckErrors TwoSpeedFluidCooler UnitarySystemHeatRecovery UpdateAbsorberChillerComponentGeneratorSide UpdateAirflowNetwork UpdateAirMixer UpdateAirSysCompPtrArray UpdateAirSysSubCompPtrArray UpdateAirSysSubSubCompPtrArray UpdateAirZoneReturnPlenum UpdateAirZoneSupplyPlenum UpdateAnyLoopDemandAlterations UpdateATMixer UpdateBaseboard UpdateBaseboardPlantConnection UpdateBasementSurfaceTemperatures UpdateBBElecRadSourceValAvg UpdateBBRadSourceValAvg UpdateBBSteamRadSourceValAvg UpdateBLASTAbsorberRecords UpdateBoilerRecords UpdateBoilerRecords UpdateBracket UpdateBranchConnections UpdateChillerComponentCondenserSide UpdateChillerheaterRecords UpdateChillerRecords UpdateColdWeatherProtection UpdateCommonPipe UpdateComplexWindows UpdateComponentHeatRecoverySide UpdateConstCOPChillerRecords UpdateController UpdateCoolBeam UpdateCoolTower UpdateCTGeneratorRecords UpdateDataandReport UpdateDemandManagers UpdateDesiccantDehumidifier UpdateDetailedIceStorage UpdateDualDuct UpdateDuct UpdateDXCoil UpdateElectricBaseboard UpdateElectricChillerRecords UpdateElectricEIRChillerRecords UpdateEMSTrendVariables UpdateEngineDrivenChiller UpdateEvapCooler UpdateEvapFluidCooler UpdateEvaporativeCondenserBasinHeater UpdateEvaporativeCondenserWaterUse UpdateExhaustAbsorberCoolRecords UpdateExhaustAbsorberHeatRecords UpdateExhaustAirFlows UpdateFan UpdateFinalSurfaceHeatBalance UpdateFluidCooler UpdateFluidHeatExchanger UpdateFuelCellGeneratorRecords UpdateGasAbsorberCoolRecords UpdateGasAbsorberHeatRecords UpdateGSHPRecords UpdateGSHPRecords UpdateGSHPRecords UpdateGTChillerRecords UpdateHalfLoopInletTemp UpdateHeatBalHAMT UpdateHeatingCoil UpdateHeatRecovery UpdateHighTempRadiantSystem UpdateHistories UpdateHistory UpdateHTRadSourceValAvg UpdateHumidifier UpdateHVACInterface UpdateHWBaseboard UpdateHWBaseboardPlantConnection UpdateIceFractions UpdateICEngineGeneratorRecords UpdateIndirectAbsorberRecords UpdateInternalGainValues UpdateIrrigation UpdateLoadCenterRecords UpdateLoopSideReportVars UpdateLowTempRadiantSystem UpdateMeterReporting UpdateMeters UpdateMeterValues UpdateMicroCHPGeneratorRecords UpdateMinMax UpdateMixedAirSetPoints UpdateMoistureBalanceEMPD UpdateMoistureBalanceFD UpdateMSHeatPump UpdateMTGeneratorRecords UpdateNode UpdateNodeThermalHistory UpdateOAController UpdateOAMixer UpdateOAPretreatSetPoints UpdatePipesHeatTransfer UpdatePipingSystems UpdatePlantLoopInterface UpdatePlantMixer UpdatePlantProfile UpdatePlantSplitter UpdatePlantValves UpdatePondGroundHeatExchanger UpdatePrecipitation UpdatePressureDrop UpdatePurchasedAir UpdatePVTcollectors UpdateRadSysSourceValAvg UpdateRecords UpdateReformEIRChillerRecords UpdateRefrigCondenser UpdateReportWaterSystem UpdateRootFinder UpdateScheduleValues UpdateSetPointManagers UpdateSimpleWatertoAirHP UpdateSoilProps UpdateSolarCollector UpdateSplitter UpdateSQLiteErrorRecord UpdateSQLiteErrorRecord UpdateSQLiteSimulationRecord UpdateSQLiteSimulationRecord UpdateSteamBaseboard UpdateSteamBaseboardPlantConnection UpdateSteamCoil UpdateSurfaceGroundHeatExchngr UpdateSys UpdateSysSizing UpdateSystemOutputRequired UpdateTabularReports UpdateTEStorage UpdateThermalHistories UpdateTowers UpdateTranspiredCollector UpdateUnitarySystemControl UpdateUtilityBills UpdateVarSpeedCoil UpdateVentilatedSlab UpdateVerticalGroundHeatExchanger UpdateVRFCondenser UpdateWaterCoil UpdateWaterConnections UpdateWaterManager UpdateWaterSource UpdateWaterThermalTank UpdateWaterToAirCoilPlantConnection UpdateWatertoAirHP UpdateWeatherData UpdateWholeBuildingRecords UpdateZoneAirLoopEquipment UpdateZoneCompPtrArray UpdateZoneDehumidifier UpdateZoneEquipment UpdateZoneInletConvergenceLog UpdateZoneListAndGroupLoads UpdateZoneSizing UpdateZoneSubCompPtrArray UpdateZoneSubSubCompPtrArray ValidateAndSetSysAvailabilityManagerType ValidateComponent ValidateDistributionSystem ValidateEMSProgramName ValidateEMSVariableName ValidateExhaustFanInput ValidateFlowControlPaths ValidateFuelType ValidateIndexType ValidateMaterialRoughness ValidateMonthDay ValidateNStandardizeMeterTitles ValidateObjectandParse ValidatePipeConstruction ValidatePLFCurve ValidateSection ValidateSectionsInput ValidateVariableType value_to_vector ValueToString VAVVSCoolingResidual VAVVSHCFanOnResidual VAVVSHWFanOnResidual VAVVSHWNoFanResidual VB_CriticalSlatAngle VB_DIFF VB_LWP VB_ShadeControl VB_SLAT_RADIUS_RATIO VB_SOL4 VB_SOL46_CURVE VB_SOL6 VB_SWP vec2d_cross_product vec2d_dot_product vec_cross_product vec_dot_product VecLength VecNegate VecNormalize VecRound VecSquaredLength vector_add vector_div_int vector_div_real vector_subtract vector_times_int vector_times_real vector_to_array VerifyControlledZoneForThermostat VerifyCustomMetersElecPowerMgr VerifyHeatExchangerParent VerifyName VerifySetPointManagers VerifyThermostatInZone VerifyUniqueBaseboardName VerifyUniqueBoilerName VerifyUniqueChillerName VerifyUniqueCoilName ViewFac VisibleSprectrumAverage Volume VRMLOut VSCoilCyclingHumResidual VSCoilCyclingResidual VSCoilCyclingResidual VSCoilSpeedHumResidual VSCoilSpeedResidual VSCoilSpeedResidual VSEvapUnitLoadResidual VSHPCyclingResidual VSHPCyclingResidual VSHPSpeedResidual VSHPSpeedResidual VSMerkelResidual W5InitGlassParameters W5LsqFit W5LsqFit2 W6CoordsFromWorldVect warnIfNativeVarname WetCoilOutletCondition WhichCompSet WhichParentCompSet WhichParentSet Width WindowGapAirflowControl WindowGasConductance WindowGasPropertiesAtTemp WindowHeatBalanceEquations WindowScheduledSolarAbs WindowShadingManager WindowTempsForNominalCond WindSpeedAt Windward WorldVectFromW6 WriteAdaptiveComfortTable WriteAirLoopStatistics WriteBEPSTable WriteCompCostTable WriteComponentSizing WriteCumulativeReportMeterData WriteDaylightMapTitle WriteDemandEndUseSummary WriteInputArguments WriteIntegerData WriteIntegerVariableOutput WriteMeterDictionaryItem WriteModifiedArguments WriteMonthlyTables WriteOutputArguments WriteOutputEN673 WritePoint WritePredefinedTables WriteRealData WriteRealVariableOutput WriteReportHeaders WriteReportIntegerData WriteReportMeterData WriteReportRealData WriteReportVariableDictionaryItem WriteRootFinderStatus WriteRootFinderTrace WriteRootFinderTraceHeader WriteSourceEnergyEndUseSummary writeSubtitle WriteSurfaceShadowing WriteTable WriteTableOfContents WriteTabularLifeCycleCostReport WriteTabularReports WriteTabularTariffReports WriteTARCOGInputFile writeTextLine WriteTimeBinTables WriteTimeStampFormatData WriteTrace WriteVeriSumTable WriteZoneLoadComponentTable WVDC XNormalArea XYRectangle XZRectangle YNormalArea YZRectangle ZeroHVACValues ZNormalArea
Call graph
sizeunitarysystem calls node, getbranchflow, curvevalue, callcoiltypes, getcoolingcoiltypenameandindex, oasyseqsizing, getsimplecoilcapacity, reportsizingoutput, simdxcoil, getwahpcoilcapacity, finditeminlist, finalsyssizing, simdxcoilmultispeed, getairbranchindex, getfandesignvolumeflowrate, unitarysyseqsizing, finalzonesizing, getbranchfantypename, getunitarysystemdxcoolingcoilindex, registerplantcompdesignflow, simwatertoairhp, cfurnacetypes, samestring, showcontinueerror, primaryairsystem, psytwbfntdbwpb, getwatercoilcapacity, manageems, checksystembranchflow, gethxdxcoilname, getcoilcapacityvariablespeed, setcoildesflow, psycpairfnwtdb, desdayweath, checksyssizing, getcoilobjecttypenum, psyhfntdbw, simhxassistedcoolingcoil, varspeedcoil, checkzonesizing, zoneeqsizing, getdxcoilcapftcurveindex, psyrhoairfnpbtdbw, getcoilcapacitybyindextype, getcoilcapacity, setonoffmassflowrate, makeuppercase, simvariablespeedcoils, simwatertoairhpsimple
getunitarysystemdxcoolingcoilindex calls samestring, getunitarysysteminput
psytwbfntdbwpb calls psytwbfntdbwpb_raw
psycpairfnwtdb calls psyhfntdbw
checksyssizing calls showsevereerror, showfatalerror, showcontinueerror
checkzonesizing calls showsevereerror, showfatalerror, showcontinueerror
psyrhoairfnpbtdbw calls showcontinueerror, showsevereerror, showfatalerror, roundsigdigits, showcontinueerrortimestamp
setonoffmassflowrate calls setaverageairflow
getunitarysysteminput calls callcoiltypes, getfandesignvolumeflowrate, showcontinueerror, primaryairsystem, manageems, gethxdxcoilname, getcoilcapacityvariablespeed, getcoilobjecttypenum, getfanoutletnode, zoneequipconfig, verifyname, getfanindex, zoneequiplist, humiditycontrolzone, getsatdensityrefrig, getdxcoilairflow, comfortcontrolledzone, nodeid, getcoilavailscheduleindex, getwatercoilavailscheduleindex, nodehasspmctrlvartype, getfantype, getcoilindexvariablespeed, getfaninletnode, getvscoilnumofspeeds, gethxdxcoilindex, getobjectdefmaxargs, getheatingcoiloutletnode, setupoutputvariable, getwatercoilindex, setupemsinternalvariable, getdxcoiloutletnode, getcoilwaterinletnode, getdxcoilindex, getheatingcoilinletnode, getobjectitem, getdxcoilcapacity, getsteamcoilavailscheduleindex, getwatercoilinletnode, finditeminlist, getsteamcoilindex, getcoilmaxwaterflowrate, getnumobjectsfound, getwatercoiloutletnode, getcoilmaxsteamflowrate, samestring, getscheduleindex, getsteamcoilsteaminletnode, getsteamcoilairinletnode, testcompset, setupcompsets, getsteamcoilairoutletnode, tempcontrolledzone, zone, getheatingcoiltypenum, getfanavailschptr, getonlysinglenode, getheatingcoilcapacity, outsideairsys, getheatingcoilindex, getdxcoiltypenum, getdxcoilavailschptr, setupemsactuator, getheatingcoilplfcurveindex, controllertypes, gethxassistedcoiltypenum, getdxcoilinletnode, getdxcoilcondenserinletnode, gethxcoilairflowrate, getvscoilcondenserinletnode, setdxcoolingcoildata, getdxhxasstdcoilinletnode, getdxhxasstdcoilcapacity, getdxhxasstdcoiloutletnode, showsevereerror, getcoilairflowratevariablespeed, getactualdxcoilindex, showfatalerror, getcoilinletnodevariablespeed, getvscoilminoatcompressor, setvarspeedcoildata, getcoiloutletnodevariablespeed, getminoatdxcoilcompressor, getwtoahpcoilindex, getwtoahpcoilinletnode, getwtoahpsimplecoilindex, getwtoahpcoiloutletnode, getwtoahpsimplecoilinletnode, setsimplewshpdata, validatecomponent, getwtoahpsimplecoiloutletnode, trimsigdigits, checkschedulevalueminmax, setdxcoiltypedata
verifyname calls showsevereerror, finditem
getobjectdefmaxargs calls finditeminlist, showsevereerror, makeuppercase, finditeminsortedlist
getobjectitem calls finditeminlist, samestring, showfatalerror, showwarningerror, makeuppercase, finditeminsortedlist, getobjectitemfromfile, processinput, iptrimsigdigits
getnumobjectsfound calls finditeminlist, showwarningerror, makeuppercase, finditeminsortedlist
samestring calls makeuppercase
getscheduleindex calls finditeminlist, processscheduleinput
validatecomponent calls showsevereerror, showcontinueerror, getobjectitemnum
checkschedulevalueminmax calls dcheckschedulevalueminmax2, rcheckschedulevalueminmax1, rcheckschedulevalueminmax2, dcheckschedulevalueminmax1
showsevereerror calls showerrormessage, matchcounts, messagesearch, createsqliteerrorrecord
finditem calls finditeminlist, makeuppercase
showerrormessage calls displaystring, showfatalerror
showfatalerror calls showerrormessage, createsqliteerrorrecord, displaystring, abortenergyplus, roundsigdigits
abortenergyplus calls displaystring, roundsigdigits, testairpathintegrity, updatesqlitesimulationrecord, checkmarkednodes, reportairloopconnections, showrecurringerrors, testcompsetinletoutletnodes, summarizeerrors, reportsurfaceerrors, reportloopconnections, closemiscopenfiles, setupnodevarsforreporting, closesocket, closeoutopenfiles, reportsurfaces, testbranchintegrity, checkplantonabort, epelapsedtime, epstoptime, epsummarytimes, showmessage, checknodeconnections
testairpathintegrity calls nodeid, showsevereerror, airtozonenodeinfo, showcontinueerror
showrecurringerrors calls createsqliteerrorrecord, roundsigdigits, showmessage, updatesqliteerrorrecord, removetrailingzeros, recurringerrors
summarizeerrors calls matchcounts, showmessage, summaries, moredetails
closemiscopenfiles calls closedfsfile, closereportillummaps
reportsurfaces calls detailsforsurfaces, setupschemecolors, vrmlout, scanforreports, dxfoutwireframe, costinfoout, linesout, showwarningerror, dxfout
epstoptime calls showfatalerror, tstop
epsummarytimes calls roundsigdigits
showmessage calls showerrormessage
showcontinueerror calls showerrormessage, updatesqliteerrorrecord
detailsforsurfaces calls zone, trimsigdigits, roundsigdigits, getschedulename, oscm, nominalu, framedivider, getschedulemaxvalue, 2, computenominaluwithconvcoeffs, 3, osc, construct, 4, csurfaceclass, userintconvectioncoeffs, userextconvectioncoeffs, surface, getscheduleminvalue, surfacewindow
setupschemecolors calls showwarningerror, getobjectitemnum, getobjectdefmaxargs, matchandsetcolortextstring, getobjectitem
vrmlout calls zone, showfatalerror, showcontinueerror, showwarningerror, surface, triangulate, getnewunitnumber
dxfoutwireframe calls zone, trimsigdigits, showfatalerror, surface, surfacewindow, getnewunitnumber, zonedaylight, dxfcolorno
costinfoout calls showfatalerror, construct, csurfaceclass, surface, getnewunitnumber
linesout calls showfatalerror, roundsigdigits, showcontinueerror, showwarningerror, csurfaceclass, surface, getnewunitnumber
showwarningerror calls showerrormessage, matchcounts, messagesearch, createsqliteerrorrecord
dxfout calls zone, trimsigdigits, showfatalerror, showcontinueerror, showwarningerror, surface, surfacewindow, triangulate, getnewunitnumber, zonedaylight, dxfcolorno, illummapcalc
computenominaluwithconvcoeffs calls surface
matchandsetcolortextstring calls finditem
triangulate calls roundsigdigits, showmessage, showcontinueerror, showwarningerror, csurfaceclass, generate_ears, calcrfflrcoordinatetransformation, calcwallcoordinatetransformation
generate_ears calls polygon_contains_point_2d, angle_2dvector
finditeminsortedlist calls samestring, makeuppercase
processinput calls finditeminlist, samestring, showsevereerror, displaystring, showfatalerror, showcontinueerror, showwarningerror, makeuppercase, finditeminsortedlist, iptrimsigdigits, setupandsort, calphafieldnames, processdatadicfile, calphaargs, lalphafieldblanks, rnumericargs, cnumericfieldnames, lnumericfieldblanks, matchversion, getidfrecordsstats, processinputdatafile, initsecretobjects, programpath
processdatadicfile calls showsevereerror, iptrimsigdigits, readinputline, addsectiondef, addobjectdefandparse
processinputdatafile calls showsevereerror, showmessage, iptrimsigdigits, readinputline, validatesection, validateobjectandparse
readinputline calls showsevereerror, showfatalerror, showcontinueerror, makeuppercase, iptrimsigdigits, processnumber, processminmaxdefline
addsectiondef calls finditeminlist, showsevereerror, showcontinueerror, showwarningerror, makeuppercase
addobjectdefandparse calls finditeminlist, showsevereerror, showcontinueerror, showwarningerror, makeuppercase, iptrimsigdigits, readinputline
processminmaxdefline calls showsevereerror, makeuppercase, iptrimsigdigits, processnumber
validatesection calls finditeminlist, samestring, showcontinueerror, showwarningerror, makeuppercase, finditeminsortedlist, addrecordfromsection
validateobjectandparse calls finditeminlist, showsevereerror, showcontinueerror, showwarningerror, makeuppercase, finditeminsortedlist, iptrimsigdigits, readinputline, processnumber, showauditerrormessage, internalrangecheck, dumpcurrentlinebuffer, maketransition, extendobjectdefinition
addrecordfromsection calls showsevereerror, showcontinueerror, iptrimsigdigits, showauditerrormessage, internalrangecheck
internalrangecheck calls showsevereerror, iptrimsigdigits
dumpcurrentlinebuffer calls showmessage, iptrimsigdigits
maketransition calls finditeminlist, samestring, showsevereerror, showfatalerror, makeuppercase
extendobjectdefinition calls displaystring, iptrimsigdigits
processscheduleinput calls finditeminlist, samestring, trimsigdigits, checkschedulevalueminmax, showsevereerror, displaystring, showfatalerror, roundsigdigits, showcontinueerror, showwarningerror, getobjectdefmaxargs, getobjectitem, finditem, verifyname, processintervalfields, processdatestring, setupemsactuator, processfordaytypes, julianday, getnumobjectsfound, externalinterfacesetschedule, processnumber, checkforactualfilename, reportscheduledetails
processintervalfields calls showsevereerror, showcontinueerror, showwarningerror, decodehhmmfield
processfordaytypes calls showsevereerror
reportscheduledetails calls roundsigdigits, invjulianday
decodehhmmfield calls showsevereerror, showcontinueerror, showwarningerror
dcheckschedulevalueminmax2 calls showfatalerror
rcheckschedulevalueminmax1 calls showfatalerror
rcheckschedulevalueminmax2 calls showfatalerror
dcheckschedulevalueminmax1 calls showfatalerror
psytwbfntdbwpb_raw calls showcontinueerror, trimsigdigits, showrecurringwarningerroratend, psytsatfnpb, showwarningmessage, iterate, showcontinueerrortimestamp, psypsatfntemp
psytsatfnpb calls showcontinueerror, trimsigdigits, showrecurringwarningerroratend, showwarningmessage, iterate, showcontinueerrortimestamp, psypsatfntemp
psypsatfntemp calls psypsatfntemp_raw
psypsatfntemp_raw calls showcontinueerror, showsevereerror, showfatalerror, trimsigdigits, showrecurringwarningerroratend, showwarningmessage, showcontinueerrortimestamp
setaverageairflow calls node, getcurrentschedulevalue
getcurrentschedulevalue calls showcontinueerror, showwarningerror
initunitarysystems calls sizeunitarysystem
simunitarysystem calls initunitarysystems