UpdateZoneSizing – EnergyPlusFortran
UpdateZoneSizing Subroutine
701 statements
Source File
public subroutine UpdateZoneSizing(CallIndicator)
Uses:
DataGlobals
DataInterfaces
DataHVACGlobals
DataEnvironment
General
DataHeatBalFanSys
EMSManager
Arguments
Type Intent Optional Attributes Name
integer :: CallIndicator
Calls
Source Code
UpdateZoneSizing
Source Code
SUBROUTINE UpdateZoneSizing(CallIndicator)
          ! SUBROUTINE INFORMATION:
          !       AUTHOR         Fred Buhl
          !       DATE WRITTEN   December 2000
          !       MODIFIED       na
          !       RE-ENGINEERED  na
          ! PURPOSE OF THIS SUBROUTINE:
          ! Update the result variables of the zone sizing calculation
          ! METHODOLOGY EMPLOYED:
          ! CallIndicator = 1 (BeginDay) zero the result arrays
          ! CallIndicator = 2 (DuringDay) fill arrays, averaging over 1 zone time step
          ! CallIndicator = 3 (EndDay) calculate daily maxima
          ! CallIndicator = 4 (EndZoneSizingCalc) write out results
          ! REFERENCES:
          ! na
          ! USE STATEMENTS:
  USE DataGlobals, ONLY: HourOfDay, TimeStep, TimeStepZone, NumOfTimeStepInHour, &
                         BeginDay, DuringDay, EndDay, EndZoneSizingCalc, MinutesPerTimeStep, &
                         OutputFileZoneSizing, OutputFileDebug, emsCallFromZoneSizing, AnyEnergyManagementSystemInModel, &
                         isPulseZoneSizing, OutputFileZonePulse
  USE DataInterfaces, ONLY: SetupEMSActuator
  USE DataHVACGlobals, ONLY: FracTimeStepZone, SmallMassFlow, SmallTempDiff
  USE DataEnvironment, ONLY : StdBaroPress, StdRhoAir
  USE General, ONLY: MovingAvg, RoundSigDigits
  USE DataHeatBalFanSys, ONLY: ZoneThermostatSetPointHi, ZoneThermostatSetPointLo,TempZoneThermostatSetPoint
  USE EMSManager, ONLY: ManageEMS
  IMPLICIT NONE    ! Enforce explicit typing of all variables in this routine
          ! SUBROUTINE ARGUMENT DEFINITIONS:
  INTEGER :: CallIndicator
          ! SUBROUTINE PARAMETER DEFINITIONS:
  CHARACTER(len=*), PARAMETER :: fmta="(A)"
  CHARACTER(len=*), PARAMETER :: ZSizeFmt10="('Time')"
  CHARACTER(len=*), PARAMETER :: ZSizeFmt11="(A1,A,':',A,A,A1,A,':',A,A,A1,A,':',A,A,A1,A,':',A,A )"
  CHARACTER(len=*), PARAMETER :: ZSizeFmt20="(I2.2,':',I2.2,':00')"
  CHARACTER(len=*), PARAMETER :: ZSizeFmt21="(A1,ES12.6,A1,ES12.6,A1,ES12.6,A1,ES12.6 )"
  CHARACTER(len=*), PARAMETER :: ZSizeFmt30="('Peak')"
  CHARACTER(len=*), PARAMETER :: ZSizeFmt31="(A1,ES12.6,A1,ES12.6,A1,ES12.6,A1,ES12.6)"
  CHARACTER(len=*), PARAMETER :: ZSizeFmt40="(/'Peak Vol Flow (m3/s)')"
  CHARACTER(len=*), PARAMETER :: ZSizeFmt41="(A1,A1,A1,ES12.6,A1,ES12.6)"
          ! INTERFACE BLOCK SPECIFICATIONS
          ! na
          ! DERIVED TYPE DEFINITIONS
          ! na
          ! SUBROUTINE LOCAL VARIABLE DECLARATIONS:
  INTEGER :: DesDayNum   ! design day index
  INTEGER :: TimeStepIndex      ! zone time step index
  INTEGER :: CtrlZoneNum ! controlled zone index
  INTEGER :: TimeStepInDay ! zone time step in day
  INTEGER :: I                  ! write statement index
!  REAL(r64)    :: HourFrac           ! fractional hour
  INTEGER :: HourCounter        ! Hour Counter
  INTEGER :: TimeStepCounter    ! Time Step Counter
  INTEGER :: Minutes            ! Current Minutes Counter
  INTEGER :: HourPrint          ! Hour to print (timestamp)
  REAL(r64)    :: OAFrac             ! outside air fraction
  INTEGER :: TimeStepAtPeak     ! time step number at heat or cool peak
  INTEGER :: TimeStepAtPeakF    ! time step number at heat or cool peak (final)
  INTEGER :: DDNum              ! Design Day index
  INTEGER :: DDNumF             ! Design Day index (final)
  REAL(r64)    :: TotCoolSizMult     ! combines user cooling design flow input with zone sizing multiplier
  REAL(r64)    :: TotHeatSizMult     ! combines user heating design flow input with zone sizing multiplier
  REAL(r64)    :: MinOAMass          ! zone minimum outside air mass flow rate kg/s
  REAL(r64)    :: MaxOfMinCoolVolFlow  ! max of the user specified design cooling minimum flows and min OA flow [m3/s]
  REAL(r64)    :: MaxOfMinCoolMassFlow ! max of the user specified design cooling minimum flows and min OA flow [kg/s]
  REAL(r64)    :: MaxHeatVolFlow     ! max of user specified design heating max flow [m3/s]
  CHARACTER(len=8) :: HrMinString   ! store hour/minute string before assigning to peak string array
  REAL(r64)    :: SupplyTemp        ! supply air temperature [C]
  REAL(r64)    :: DeltaTemp         ! supply air delta temperature [deltaC]
  SELECT CASE (CallIndicator)
    CASE (BeginDay)
      DO CtrlZoneNum = 1,NumOfZones
        IF (.not. ZoneEquipConfig(CtrlZoneNum)%IsControlled) CYCLE
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolDesDay = EnvironmentName
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatDesDay = EnvironmentName
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesHeatDens = StdRhoAir
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesCoolDens = StdRhoAir
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatDDNum = CurOverallSimDay
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolDDNum = CurOverallSimDay
      END DO
    CASE (DuringDay)
      TimeStepInDay = (HourOfDay-1)*NumOfTimeStepInHour + TimeStep
      DO CtrlZoneNum = 1,NumOfZones
        IF (.not. ZoneEquipConfig(CtrlZoneNum)%IsControlled) CYCLE
        IF (ZoneThermostatSetPointHi(CtrlZoneNum) > 0.0d0 .AND.   &
               ZoneThermostatSetPointHi(CtrlZoneNum) > ZoneSizThermSetPtHi(CtrlZoneNum)) THEN
          ZoneSizThermSetPtHi(CtrlZoneNum) = ZoneThermostatSetPointHi(CtrlZoneNum)
        END IF
        IF (ZoneThermostatSetPointLo(CtrlZoneNum) > 0.0d0 .AND.   &
               ZoneThermostatSetPointLo(CtrlZoneNum) < ZoneSizThermSetPtLo(CtrlZoneNum)) THEN
          ZoneSizThermSetPtLo(CtrlZoneNum) = ZoneThermostatSetPointLo(CtrlZoneNum)
        END IF
        ZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesHeatSetPtSeq(TimeStepInDay) = ZoneThermostatSetPointLo(CtrlZoneNum)
        ZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatTstatTempSeq(TimeStepInDay) = TempZoneThermostatSetPoint(CtrlZoneNum)
        ZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesCoolSetPtSeq(TimeStepInDay) = ZoneThermostatSetPointHi(CtrlZoneNum)
        ZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolTstatTempSeq(TimeStepInDay) = TempZoneThermostatSetPoint(CtrlZoneNum)
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatFlowSeq(TimeStepInDay) = &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatFlowSeq(TimeStepInDay) + &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatMassFlow * FracTimeStepZone
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatLoadSeq(TimeStepInDay) = &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatLoadSeq(TimeStepInDay) + &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatLoad * FracTimeStepZone
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatZoneTempSeq(TimeStepInDay) = &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatZoneTempSeq(TimeStepInDay) + &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatZoneTemp * FracTimeStepZone
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatOutTempSeq(TimeStepInDay) = &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatOutTempSeq(TimeStepInDay) + &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatOutTemp * FracTimeStepZone
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatZoneRetTempSeq(TimeStepInDay) = &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatZoneRetTempSeq(TimeStepInDay) + &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatZoneRetTemp * FracTimeStepZone
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatTstatTempSeq(TimeStepInDay) = &
          TempZoneThermostatSetPoint(CtrlZoneNum)
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatZoneHumRatSeq(TimeStepInDay) = &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatZoneHumRatSeq(TimeStepInDay) + &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatZoneHumRat * FracTimeStepZone
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatOutHumRatSeq(TimeStepInDay) = &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatOutHumRatSeq(TimeStepInDay) + &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatOutHumRat * FracTimeStepZone
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolFlowSeq(TimeStepInDay) = &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolFlowSeq(TimeStepInDay) + &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolMassFlow * FracTimeStepZone
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolLoadSeq(TimeStepInDay) = &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolLoadSeq(TimeStepInDay) + &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolLoad * FracTimeStepZone
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolZoneTempSeq(TimeStepInDay) = &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolZoneTempSeq(TimeStepInDay) + &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolZoneTemp * FracTimeStepZone
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolOutTempSeq(TimeStepInDay) = &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolOutTempSeq(TimeStepInDay) + &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolOutTemp * FracTimeStepZone
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolZoneRetTempSeq(TimeStepInDay) = &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolZoneRetTempSeq(TimeStepInDay) + &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolZoneRetTemp * FracTimeStepZone
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolTstatTempSeq(TimeStepInDay) = &
          TempZoneThermostatSetPoint(CtrlZoneNum)
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolZoneHumRatSeq(TimeStepInDay) = &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolZoneHumRatSeq(TimeStepInDay) + &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolZoneHumRat * FracTimeStepZone
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolOutHumRatSeq(TimeStepInDay) = &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolOutHumRatSeq(TimeStepInDay) + &
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolOutHumRat * FracTimeStepZone
      END DO
    CASE (EndDay)
      DO CtrlZoneNum = 1,NumOfZones
        IF (.not. ZoneEquipConfig(CtrlZoneNum)%IsControlled) CYCLE
        AvgData = 0.0d0
        CALL MovingAvg(CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolFlowSeq,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolFlowSeq = AvgData
      END DO
      DO CtrlZoneNum = 1,NumOfZones
        IF (.not. ZoneEquipConfig(CtrlZoneNum)%IsControlled) CYCLE
        AvgData = 0.0d0
        CALL MovingAvg(CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolLoadSeq,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolLoadSeq = AvgData
      END DO
      DO CtrlZoneNum = 1,NumOfZones
        IF (.not. ZoneEquipConfig(CtrlZoneNum)%IsControlled) CYCLE
        AvgData = 0.0d0
        CALL MovingAvg(CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatFlowSeq,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatFlowSeq = AvgData
      END DO
      DO CtrlZoneNum = 1,NumOfZones
        IF (.not. ZoneEquipConfig(CtrlZoneNum)%IsControlled) CYCLE
        AvgData = 0.0d0
        CALL MovingAvg(CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatLoadSeq,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatLoadSeq = AvgData
      END DO
      DO CtrlZoneNum = 1,NumOfZones
        IF (.not. ZoneEquipConfig(CtrlZoneNum)%IsControlled) CYCLE
        AvgData = 0.0d0
        CALL MovingAvg(CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolZoneRetTempSeq,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolZoneRetTempSeq = AvgData
      END DO
      DO CtrlZoneNum = 1,NumOfZones
        IF (.not. ZoneEquipConfig(CtrlZoneNum)%IsControlled) CYCLE
        AvgData = 0.0d0
        CALL MovingAvg(CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatZoneRetTempSeq,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
        CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatZoneRetTempSeq = AvgData
      END DO
      DO CtrlZoneNum = 1,NumOfZones
        IF (.not. ZoneEquipConfig(CtrlZoneNum)%IsControlled) CYCLE
        DO TimeStepIndex = 1,NumOfTimeStepInDay
          IF ( CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatLoadSeq(TimeStepIndex) > &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesHeatLoad ) THEN
            CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesHeatLoad = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatLoadSeq(TimeStepIndex)
            CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesHeatMassFlow = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatFlowSeq(TimeStepIndex)
            CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%ZoneTempAtHeatPeak = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatZoneTempSeq(TimeStepIndex)
            CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%OutTempAtHeatPeak = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatOutTempSeq(TimeStepIndex)
            CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%ZoneRetTempAtHeatPeak = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatZoneRetTempSeq(TimeStepIndex)
            CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatTstatTemp = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatTstatTempSeq(TimeStepIndex)
            CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%ZoneHumRatAtHeatPeak = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatZoneHumRatSeq(TimeStepIndex)
            CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%OutHumRatAtHeatPeak = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatOutHumRatSeq(TimeStepIndex)
            CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%TimeStepNumAtHeatMax = TimeStepIndex
          END IF
        END DO
        IF (CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesHeatMassFlow > 0.0d0) THEN
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesHeatVolFlow = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesHeatMassFlow &
              / CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesHeatDens
          OAFrac = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%MinOA &
                     / MAX(CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesHeatVolFlow,SmallMassFlow)
          OAFrac = MIN(1.0d0,MAX(0.0d0,OAFrac))
          TimeStepAtPeak = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%TimeStepNumAtHeatMax
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesHeatCoilInTemp = &
              OAFrac*DesDayWeath(CurOverallSimDay)%Temp(TimeStepAtPeak) + &
              (1.d0-OAFrac)*CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%ZoneTempAtHeatPeak
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesHeatCoilInHumRat = &
              OAFrac*DesDayWeath(CurOverallSimDay)%HumRat(TimeStepAtPeak) + &
              (1.d0-OAFrac)*CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%ZoneHumRatAtHeatPeak
        END IF
        DO  TimeStepIndex = 1,NumOfTimeStepInDay
          IF ( CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolLoadSeq(TimeStepIndex) > &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesCoolLoad ) THEN
            CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesCoolLoad = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolLoadSeq(TimeStepIndex)
            CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesCoolMassFlow = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolFlowSeq(TimeStepIndex)
            CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%ZoneTempAtCoolPeak = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolZoneTempSeq(TimeStepIndex)
            CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%OutTempAtCoolPeak = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolOutTempSeq(TimeStepIndex)
            CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%ZoneRetTempAtCoolPeak = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolZoneRetTempSeq(TimeStepIndex)
            CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolTstatTemp = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolTstatTempSeq(TimeStepIndex)
            CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%ZoneHumRatAtCoolPeak = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolZoneHumRatSeq(TimeStepIndex)
            CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%OutHumRatAtCoolPeak = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolOutHumRatSeq(TimeStepIndex)
            CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%TimeStepNumAtCoolMax = TimeStepIndex
          END IF
        END DO
        IF (CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesCoolMassFlow > 0.0d0) THEN
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesCoolVolFlow = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesCoolMassFlow &
              / CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesCoolDens
          OAFrac = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%MinOA &
                     / MAX(CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesCoolVolFlow,SmallMassFlow)
          OAFrac = MIN(1.0d0,MAX(0.0d0,OAFrac))
          TimeStepAtPeak = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%TimeStepNumAtCoolMax
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesCoolCoilInTemp = &
              OAFrac*DesDayWeath(CurOverallSimDay)%Temp(TimeStepAtPeak) + &
              (1.d0-OAFrac)*CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%ZoneTempAtCoolPeak
          CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesCoolCoilInHumRat = &
              OAFrac*DesDayWeath(CurOverallSimDay)%HumRat(TimeStepAtPeak) + &
              (1.d0-OAFrac)*CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%ZoneHumRatAtCoolPeak
        END IF
        IF (CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesHeatVolFlow > CalcFinalZoneSizing(CtrlZoneNum)%DesHeatVolFlow) THEN
          CalcFinalZoneSizing(CtrlZoneNum)%DesHeatVolFlow = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesHeatVolFlow
          CalcFinalZoneSizing(CtrlZoneNum)%DesHeatLoad = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesHeatLoad
          CalcFinalZoneSizing(CtrlZoneNum)%DesHeatMassFlow = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesHeatMassFlow
          CalcFinalZoneSizing(CtrlZoneNum)%HeatDesDay = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatDesDay
          CalcFinalZoneSizing(CtrlZoneNum)%DesHeatDens = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesHeatDens
          CalcFinalZoneSizing(CtrlZoneNum)%HeatFlowSeq = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatFlowSeq
          CalcFinalZoneSizing(CtrlZoneNum)%HeatLoadSeq = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatLoadSeq
          CalcFinalZoneSizing(CtrlZoneNum)%HeatZoneTempSeq = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatZoneTempSeq
          CalcFinalZoneSizing(CtrlZoneNum)%HeatOutTempSeq = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatOutTempSeq
          CalcFinalZoneSizing(CtrlZoneNum)%HeatZoneRetTempSeq = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatZoneRetTempSeq
          CalcFinalZoneSizing(CtrlZoneNum)%HeatTstatTempSeq = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatTstatTempSeq
          CalcFinalZoneSizing(CtrlZoneNum)%HeatTstatTemp = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatTstatTemp
          CalcFinalZoneSizing(CtrlZoneNum)%HeatZoneHumRatSeq = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatZoneHumRatSeq
          CalcFinalZoneSizing(CtrlZoneNum)%HeatOutHumRatSeq = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatOutHumRatSeq
          CalcFinalZoneSizing(CtrlZoneNum)%ZoneTempAtHeatPeak = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%ZoneTempAtHeatPeak
          CalcFinalZoneSizing(CtrlZoneNum)%OutTempAtHeatPeak = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%OutTempAtHeatPeak
          CalcFinalZoneSizing(CtrlZoneNum)%ZoneRetTempAtHeatPeak = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%ZoneRetTempAtHeatPeak
          CalcFinalZoneSizing(CtrlZoneNum)%ZoneHumRatAtHeatPeak = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%ZoneHumRatAtHeatPeak
          CalcFinalZoneSizing(CtrlZoneNum)%OutHumRatAtHeatPeak = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%OutHumRatAtHeatPeak
          CalcFinalZoneSizing(CtrlZoneNum)%HeatDDNum = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%HeatDDNum
          CalcFinalZoneSizing(CtrlZoneNum)%cHeatDDDate = DesDayWeath(CurOverallSimDay)%DateString
          CalcFinalZoneSizing(CtrlZoneNum)%TimeStepNumAtHeatMax = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%TimeStepNumAtHeatMax
          CalcFinalZoneSizing(CtrlZoneNum)%DesHeatCoilInTemp = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesHeatCoilInTemp
          CalcFinalZoneSizing(CtrlZoneNum)%DesHeatCoilInHumRat = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesHeatCoilInHumRat
        ELSE
          CalcFinalZoneSizing(CtrlZoneNum)%DesHeatDens = StdRhoAir
        END IF
        IF (CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesCoolVolFlow > CalcFinalZoneSizing(CtrlZoneNum)%DesCoolVolFlow) THEN
          CalcFinalZoneSizing(CtrlZoneNum)%DesCoolVolFlow = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesCoolVolFlow
          CalcFinalZoneSizing(CtrlZoneNum)%DesCoolLoad = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesCoolLoad
          CalcFinalZoneSizing(CtrlZoneNum)%DesCoolMassFlow = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesCoolMassFlow
          CalcFinalZoneSizing(CtrlZoneNum)%CoolDesDay = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolDesDay
          CalcFinalZoneSizing(CtrlZoneNum)%DesCoolDens = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesCoolDens
          CalcFinalZoneSizing(CtrlZoneNum)%CoolFlowSeq = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolFlowSeq
          CalcFinalZoneSizing(CtrlZoneNum)%CoolLoadSeq = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolLoadSeq
          CalcFinalZoneSizing(CtrlZoneNum)%CoolZoneTempSeq = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolZoneTempSeq
          CalcFinalZoneSizing(CtrlZoneNum)%CoolOutTempSeq = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolOutTempSeq
          CalcFinalZoneSizing(CtrlZoneNum)%CoolZoneRetTempSeq = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolZoneRetTempSeq
          CalcFinalZoneSizing(CtrlZoneNum)%CoolTstatTempSeq = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolTstatTempSeq
          CalcFinalZoneSizing(CtrlZoneNum)%CoolTstatTemp = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolTstatTemp
          CalcFinalZoneSizing(CtrlZoneNum)%CoolZoneHumRatSeq = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolZoneHumRatSeq
          CalcFinalZoneSizing(CtrlZoneNum)%CoolOutHumRatSeq = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolOutHumRatSeq
          CalcFinalZoneSizing(CtrlZoneNum)%ZoneTempAtCoolPeak = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%ZoneTempAtCoolPeak
          CalcFinalZoneSizing(CtrlZoneNum)%OutTempAtCoolPeak = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%OutTempAtCoolPeak
          CalcFinalZoneSizing(CtrlZoneNum)%ZoneRetTempAtCoolPeak = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%ZoneRetTempAtCoolPeak
          CalcFinalZoneSizing(CtrlZoneNum)%ZoneHumRatAtCoolPeak = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%ZoneHumRatAtCoolPeak
          CalcFinalZoneSizing(CtrlZoneNum)%OutHumRatAtCoolPeak = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%OutHumRatAtCoolPeak
          CalcFinalZoneSizing(CtrlZoneNum)%CoolDDNum = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%CoolDDNum
          CalcFinalZoneSizing(CtrlZoneNum)%cCoolDDDate = DesDayWeath(CurOverallSimDay)%DateString
          CalcFinalZoneSizing(CtrlZoneNum)%TimeStepNumAtCoolMax = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%TimeStepNumAtCoolMax
          CalcFinalZoneSizing(CtrlZoneNum)%DesCoolCoilInTemp = CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesCoolCoilInTemp
          CalcFinalZoneSizing(CtrlZoneNum)%DesCoolCoilInHumRat = &
              CalcZoneSizing(CtrlZoneNum,CurOverallSimDay)%DesCoolCoilInHumRat
        ELSE
          CalcFinalZoneSizing(CtrlZoneNum)%DesCoolDens = StdRhoAir
        END IF
      END DO
    CASE (EndZoneSizingCalc)
      ! candidate EMS calling point to customize CalcFinalZoneSizing
      Call ManageEMS(emsCallFromZoneSizing)
      ! now apply EMS overrides (if any)
      IF (AnyEnergyManagementSystemInModel) THEN
        DO CtrlZoneNum = 1,NumOfZones
          IF (CalcFinalZoneSizing(CtrlZoneNum)%EMSOverrideDesHeatMassOn ) THEN
            IF (CalcFinalZoneSizing(CtrlZoneNum)%DesHeatMassFlow > 0.0D0) &
              CalcFinalZoneSizing(CtrlZoneNum)%DesHeatMassFlow = CalcFinalZoneSizing(CtrlZoneNum)%EMSValueDesHeatMassFlow
          ENDIF
          IF (CalcFinalZoneSizing(CtrlZoneNum)%EMSOverrideDesCoolMassOn) THEN
            IF (CalcFinalZoneSizing(CtrlZoneNum)%DesCoolMassFlow > 0.0D0) &
              CalcFinalZoneSizing(CtrlZoneNum)%DesCoolMassFlow = CalcFinalZoneSizing(CtrlZoneNum)%EMSValueDesCoolMassFlow
          ENDIF
          IF (CalcFinalZoneSizing(CtrlZoneNum)%EMSOverrideDesHeatLoadOn) THEN
            IF (CalcFinalZoneSizing(CtrlZoneNum)%DesHeatLoad > 0.0D0) &
              CalcFinalZoneSizing(CtrlZoneNum)%DesHeatLoad = CalcFinalZoneSizing(CtrlZoneNum)%EMSValueDesHeatLoad
          ENDIF
          IF (CalcFinalZoneSizing(CtrlZoneNum)%EMSOverrideDesCoolLoadOn) THEN
            IF (CalcFinalZoneSizing(CtrlZoneNum)%DesCoolLoad > 0.0D0) &
              CalcFinalZoneSizing(CtrlZoneNum)%DesCoolLoad = CalcFinalZoneSizing(CtrlZoneNum)%EMSValueDesCoolLoad
          ENDIF
          IF (CalcFinalZoneSizing(CtrlZoneNum)%EMSOverrideDesHeatVolOn) THEN
            IF (CalcFinalZoneSizing(CtrlZoneNum)%DesHeatVolFlow > 0.0D0) &
              CalcFinalZoneSizing(CtrlZoneNum)%DesHeatVolFlow = CalcFinalZoneSizing(CtrlZoneNum)%EMSValueDesHeatVolFlow
          ENDIF
          IF (CalcFinalZoneSizing(CtrlZoneNum)%EMSOverrideDesCoolVolOn) THEN
            IF (CalcFinalZoneSizing(CtrlZoneNum)%DesCoolVolFlow > 0.0D0) &
              CalcFinalZoneSizing(CtrlZoneNum)%DesCoolVolFlow = CalcFinalZoneSizing(CtrlZoneNum)%EMSValueDesCoolVolFlow
          ENDIF
        ENDDO
      ENDIF
      IF (.NOT. isPulseZoneSizing) THEN
        DO CtrlZoneNum=1,NumOfZones
          IF (.not. ZoneEquipConfig(CtrlZoneNum)%IsControlled) CYCLE
          IF (ABS(CalcFinalZoneSizing(CtrlZoneNum)%DesCoolLoad) <= 1.d-8) THEN
            CALL ShowWarningError('Calculated design cooling load for zone='//  &
                              TRIM(CalcFinalZoneSizing(CtrlZoneNum)%ZoneName)//' is zero.')
            CALL ShowContinueError('Check Sizing:Zone and ZoneControl:Thermostat inputs.')
          ENDIF
          IF (ABS(CalcFinalZoneSizing(CtrlZoneNum)%DesHeatLoad) <= 1.d-8) THEN
            CALL ShowWarningError('Calculated design heating load for zone='//  &
                              TRIM(CalcFinalZoneSizing(CtrlZoneNum)%ZoneName)//' is zero.')
            CALL ShowContinueError('Check Sizing:Zone and ZoneControl:Thermostat inputs.')
          ENDIF
        ENDDO
        WRITE(OutputFileZoneSizing,ZSizeFmt10,ADVANCE='No')
        DO I=1,NumOfZones
          IF (.not. ZoneEquipConfig(I)%IsControlled) CYCLE
           WRITE(OutputFileZoneSizing,ZSizeFmt11,ADVANCE='No')   &
                      SizingFileColSep,TRIM(CalcFinalZoneSizing(I)%ZoneName),   &
                              TRIM(CalcFinalZoneSizing(I)%HeatDesDay),':Des Heat Load [W]',  &
                      SizingFileColSep,TRIM(CalcFinalZoneSizing(I)%ZoneName),   &
                              TRIM(CalcFinalZoneSizing(I)%CoolDesDay),':Des Sens Cool Load [W]',  &
                      SizingFileColSep,TRIM(CalcFinalZoneSizing(I)%ZoneName),   &
                              TRIM(CalcFinalZoneSizing(I)%HeatDesDay),':Des Heat Mass Flow [kg/s]',  &
                      SizingFileColSep,TRIM(CalcFinalZoneSizing(I)%ZoneName),   &
                              TRIM(CalcFinalZoneSizing(I)%CoolDesDay),':Des Cool Mass Flow [kg/s]'
! Should this be done only if there is a cooling load? Or would this message help dermine why there was no load?
        IF (ABS(CalcFinalZoneSizing(I)%DesCoolLoad) > 1.d-8) THEN
          ! check for low cooling delta T from supply to zone to see if air volume flow rate might be excessively high
          IF (CalcFinalZoneSizing(I)%ZnCoolDgnSAMethod == SupplyAirTemperature) THEN
            SupplyTemp = CalcFinalZoneSizing(I)%CoolDesTemp
            DeltaTemp = SupplyTemp - CalcFinalZoneSizing(I)%ZoneTempatCoolPeak
          ELSE
            DeltaTemp = -ABS(CalcFinalZoneSizing(I)%CoolDesTempDiff)
            SupplyTemp = DeltaTemp + CalcFinalZoneSizing(I)%ZoneTempatCoolPeak
          END IF
          ! check for low delta T to avoid very high flow rates
          IF(ABS(DeltaTemp) .LT. 5.0d0 .AND. ABS(DeltaTemp) > SmallTempDiff)THEN ! Vdot exceeds 1200 cfm/ton @ DT=5
            IF(ABS(DeltaTemp) .GE. 2.0d0)THEN ! Vdot exceeds 3000 cfm/ton @ DT=2
              CALL ShowWarningError('UpdateZoneSizing: Cooling supply air temperature (calculated) within 5C of'// &
                                    ' zone temperature')
            ELSE
              CALL ShowSevereError('UpdateZoneSizing: Cooling supply air temperature (calculated) within 2C of'// &
                                   ' zone temperature')
            END IF
            CALL ShowContinueError('...check zone thermostat set point and design supply air temperatures')
            CALL ShowContinueError('...zone name = '//TRIM(CalcFinalZoneSizing(I)%ZoneName))
            CALL ShowContinueError('...design sensible cooling load = '// &
                 TRIM(RoundSigDigits(CalcFinalZoneSizing(I)%DesCoolLoad,2))//' W')
            CALL ShowContinueError('...thermostat set point temp    = '// &
                 TRIM(RoundSigDigits(CalcFinalZoneSizing(I)%CoolTstatTemp,3))//' C')
            CALL ShowContinueError('...zone temperature             = '// &
                 TRIM(RoundSigDigits(CalcFinalZoneSizing(I)%ZoneTempatCoolPeak,3))//' C')
            CALL ShowContinueError('...supply air temperature       = '//TRIM(RoundSigDigits(SupplyTemp,3))//' C')
            CALL ShowContinueError('...temperature difference       = '//TRIM(RoundSigDigits(DeltaTemp,5))//' C')
            CALL ShowContinueError('...calculated volume flow rate  = '// &
                 TRIM(RoundSigDigits((CalcFinalZoneSizing(I)%DesCoolVolFlow),5))//' m3/s')
            CALL ShowContinueError('...calculated mass flow rate    = '// &
                 TRIM(RoundSigDigits((CalcFinalZoneSizing(I)%DesCoolMassFlow),5))//' kg/s')
            IF(SupplyTemp .GT. CalcFinalZoneSizing(I)%ZoneTempatCoolPeak) &
              CALL ShowContinueError('...Note: supply air temperature should be less than zone'// &
                                     ' temperature during cooling air flow calculations')
          ELSE IF(ABS(DeltaTemp) > SmallTempDiff .AND. SupplyTemp .GT. CalcFinalZoneSizing(I)%ZoneTempatCoolPeak)THEN
            CALL ShowSevereError('UpdateZoneSizing: Supply air temperature is greater than zone'// &
                                 ' temperature during cooling air flow calculations')
            CALL ShowContinueError('...zone temperature            = '// &
                 TRIM(RoundSigDigits(CalcFinalZoneSizing(I)%ZoneTempatCoolPeak,3))//' C')
            CALL ShowContinueError('...supply air temperature      = '//TRIM(RoundSigDigits(SupplyTemp,3))//' C')
            CALL ShowContinueError('...occurs in zone              = '//TRIM(CalcFinalZoneSizing(I)%ZoneName))
          END IF
        END IF
! Should this be done only if there is a heating load? Or would this message help dermine why there was no load?
        IF (ABS(CalcFinalZoneSizing(I)%DesHeatLoad) > 1.d-8) THEN ! ABS() ?
          ! check for low cooling delta T from supply to zone to see if air volume flow rate might be excessively high
          IF (CalcFinalZoneSizing(I)%ZnHeatDgnSAMethod == SupplyAirTemperature) THEN
            SupplyTemp = CalcFinalZoneSizing(I)%HeatDesTemp
            DeltaTemp = SupplyTemp - CalcFinalZoneSizing(I)%ZoneTempatHeatPeak
          ELSE
            DeltaTemp = CalcFinalZoneSizing(I)%HeatDesTempDiff
            SupplyTemp = DeltaTemp + CalcFinalZoneSizing(I)%ZoneTempatHeatPeak
          END IF
          IF(ABS(DeltaTemp) .LT. 5.0d0 .AND. ABS(DeltaTemp) > SmallTempDiff)THEN ! Vdot exceeds 1200 cfm/ton @ DT=5
            IF(ABS(DeltaTemp) .GE. 2.0d0)THEN ! Vdot exceeds 3000 cfm/ton @ DT=2
              CALL ShowWarningError('UpdateZoneSizing: Heating supply air temperature (calculated) within 5C of'// &
                                    ' zone temperature')
            ELSE
              CALL ShowSevereError('UpdateZoneSizing: Heating supply air temperature (calculated) within 2C of'// &
                                   ' zone temperature')
            END IF
            CALL ShowContinueError('...check zone thermostat set point and design supply air temperatures')
            CALL ShowContinueError('...zone name = '//TRIM(CalcFinalZoneSizing(I)%ZoneName))
            CALL ShowContinueError('...design heating load         = '// &
                 TRIM(RoundSigDigits(CalcFinalZoneSizing(I)%DesCoolLoad,2))//' W')
            CALL ShowContinueError('...thermostat set piont temp   = '// &
                 TRIM(RoundSigDigits(CalcFinalZoneSizing(I)%HeatTstatTemp,3))//' C')
            CALL ShowContinueError('...zone temperature            = '// &
                 TRIM(RoundSigDigits(CalcFinalZoneSizing(I)%ZoneTempatHeatPeak,3))//' C')
            CALL ShowContinueError('...supply air temperature      = '//TRIM(RoundSigDigits(SupplyTemp,3))//' C')
            CALL ShowContinueError('...temperature difference      = '//TRIM(RoundSigDigits(DeltaTemp,5))//' C')
            CALL ShowContinueError('...calculated volume flow rate = '// &
                 TRIM(RoundSigDigits((CalcFinalZoneSizing(I)%DesHeatVolFlow),5))//' m3/s')
            CALL ShowContinueError('...calculated mass flow rate   = '// &
                 TRIM(RoundSigDigits((CalcFinalZoneSizing(I)%DesHeatMassFlow),5))//' kg/s')
            IF(SupplyTemp .LT. CalcFinalZoneSizing(I)%ZoneTempatHeatPeak) &
              CALL ShowContinueError('...Note: supply air temperature should be greater than zone'// &
                                     ' temperature during heating air flow calculations')
          ELSE IF(ABS(DeltaTemp) > SmallTempDiff .AND. SupplyTemp .LT. CalcFinalZoneSizing(I)%ZoneTempatHeatPeak)THEN
            CALL ShowSevereError('UpdateZoneSizing: Supply air temperature is less than zone'// &
                                 ' temperature during heating air flow calculations')
            CALL ShowContinueError('...zone temperature            = '// &
                 TRIM(RoundSigDigits(CalcFinalZoneSizing(I)%ZoneTempatHeatPeak,3))//' C')
            CALL ShowContinueError('...supply air temperature      = '//TRIM(RoundSigDigits(SupplyTemp,3))//' C')
            CALL ShowContinueError('...occurs in zone              = '// &
                 TRIM(CalcFinalZoneSizing(I)%ZoneName))
          END IF
        END IF
        ENDDO
        WRITE(OutputFileZoneSizing,fmta) ' '
  !      HourFrac = 0.0
        Minutes=0
        TimeStepIndex=0
        DO HourCounter=1,24
          DO TimeStepCounter=1,NumOfTimeStepInHour
            TimeStepIndex=TimeStepIndex+1
            Minutes=Minutes+MinutesPerTimeStep
            IF (Minutes == 60) THEN
              Minutes=0
              HourPrint=HourCounter
            ELSE
              HourPrint=HourCounter-1
            ENDIF
            DO CtrlZoneNum = 1,NumOfZones
              IF (.not. ZoneEquipConfig(CtrlZoneNum)%IsControlled) CYCLE
              IF (TimeStepIndex == CalcFinalZoneSizing(CtrlZoneNum)%TimeStepNumAtHeatMax) THEN
                WRITE(HrMinString,PeakHrMinFmt) HourPrint, Minutes
                HeatPeakDateHrMin(CtrlZoneNum)=TRIM(CalcFinalZoneSizing(CtrlZoneNum)%cHeatDDDate)//' '//TRIM(HrMinString)
              END IF
              IF (TimeStepIndex == CalcFinalZoneSizing(CtrlZoneNum)%TimeStepNumAtCoolMax) THEN
                WRITE(HrMinString,PeakHrMinFmt) HourPrint, Minutes
                CoolPeakDateHrMin(CtrlZoneNum)=TRIM(CalcFinalZoneSizing(CtrlZoneNum)%cCoolDDDate)//' '//TRIM(HrMinString)
              END IF
            END DO
            WRITE(OutputFileZoneSizing,ZSizeFmt20,ADVANCE='No') HourPrint,Minutes
            DO I=1,NumOfZones
              IF (.not. ZoneEquipConfig(I)%IsControlled) CYCLE
              WRITE(OutputFileZoneSizing,ZSizeFmt21,ADVANCE='No')   &
                 SizingFileColSep,CalcFinalZoneSizing(I)%HeatLoadSeq(TimeStepIndex),  &
                 SizingFileColSep,CalcFinalZoneSizing(I)%CoolLoadSeq(TimeStepIndex),  &
                 SizingFileColSep,CalcFinalZoneSizing(I)%HeatFlowSeq(TimeStepIndex),  &
                 SizingFileColSep,CalcFinalZoneSizing(I)%CoolFlowSeq(TimeStepIndex)
            END DO
            WRITE(OutputFileZoneSizing,fmta) ' '
          END DO
        END DO
        WRITE(OutputFileZoneSizing,ZSizeFmt30,ADVANCE='No')
        DO I=1,NumOfZones
          IF (.not. ZoneEquipConfig(I)%IsControlled) CYCLE
          WRITE(OutputFileZoneSizing,ZSizeFmt31,ADVANCE='No') SizingFileColSep,CalcFinalZoneSizing(I)%DesHeatLoad,     &
                                        SizingFileColSep,CalcFinalZoneSizing(I)%DesCoolLoad,     &
                                        SizingFileColSep,CalcFinalZoneSizing(I)%DesHeatMassFlow, &
                                        SizingFileColSep,CalcFinalZoneSizing(I)%DesCoolMassFlow
        END DO
        WRITE(OutputFileZoneSizing,fmta) ' '
        WRITE(OutputFileZoneSizing,ZSizeFmt40,ADVANCE='No')
        DO I=1,NumOfZones
          IF (.not. ZoneEquipConfig(I)%IsControlled) CYCLE
          WRITE(OutputFileZoneSizing,ZSizeFmt41,ADVANCE='No') SizingFileColSep,SizingFileColSep,     &
                                        SizingFileColSep,CalcFinalZoneSizing(I)%DesHeatVolFlow,  &
                                        SizingFileColSep,CalcFinalZoneSizing(I)%DesCoolVolFlow
        END DO
        WRITE(OutputFileZoneSizing,fmta) ' '
        CLOSE (OutputFileZoneSizing)
      END IF
      ! Move data from Calc arrays to user modified arrays
      ZoneSizing%CoolDesDay = CalcZoneSizing%CoolDesDay
      ZoneSizing%HeatDesDay = CalcZoneSizing%HeatDesDay
      ZoneSizing%DesHeatDens = CalcZoneSizing%DesHeatDens
      ZoneSizing%DesCoolDens = CalcZoneSizing%DesCoolDens
      ZoneSizing%HeatDDNum = CalcZoneSizing%HeatDDNum
      ZoneSizing%CoolDDNum = CalcZoneSizing%CoolDDNum
      ZoneSizing%DesHeatLoad = CalcZoneSizing%DesHeatLoad
      ZoneSizing%DesHeatMassFlow = CalcZoneSizing%DesHeatMassFlow
      ZoneSizing%ZoneTempAtHeatPeak = CalcZoneSizing%ZoneTempAtHeatPeak
      ZoneSizing%OutTempAtHeatPeak = CalcZoneSizing%OutTempAtHeatPeak
      ZoneSizing%ZoneRetTempAtHeatPeak = CalcZoneSizing%ZoneRetTempAtHeatPeak
      ZoneSizing%ZoneHumRatAtHeatPeak = CalcZoneSizing%ZoneHumRatAtHeatPeak
      ZoneSizing%OutHumRatAtHeatPeak = CalcZoneSizing%OutHumRatAtHeatPeak
      ZoneSizing%TimeStepNumAtHeatMax = CalcZoneSizing%TimeStepNumAtHeatMax
      ZoneSizing%DesHeatVolFlow = CalcZoneSizing%DesHeatVolFlow
      ZoneSizing%DesHeatCoilInTemp = CalcZoneSizing%DesHeatCoilInTemp
      ZoneSizing%DesHeatCoilInHumRat = CalcZoneSizing%DesHeatCoilInHumRat
      ZoneSizing%DesCoolLoad = CalcZoneSizing%DesCoolLoad
      ZoneSizing%DesCoolMassFlow = CalcZoneSizing%DesCoolMassFlow
      ZoneSizing%ZoneTempAtCoolPeak = CalcZoneSizing%ZoneTempAtCoolPeak
      ZoneSizing%OutTempAtCoolPeak = CalcZoneSizing%OutTempAtCoolPeak
      ZoneSizing%ZoneRetTempAtCoolPeak = CalcZoneSizing%ZoneRetTempAtCoolPeak
      ZoneSizing%ZoneHumRatAtCoolPeak = CalcZoneSizing%ZoneHumRatAtCoolPeak
      ZoneSizing%OutHumRatAtCoolPeak = CalcZoneSizing%OutHumRatAtCoolPeak
      ZoneSizing%TimeStepNumAtCoolMax = CalcZoneSizing%TimeStepNumAtCoolMax
      ZoneSizing%DesCoolVolFlow = CalcZoneSizing%DesCoolVolFlow
      ZoneSizing%DesCoolCoilInTemp = CalcZoneSizing%DesCoolCoilInTemp
      ZoneSizing%DesCoolCoilInHumRat = CalcZoneSizing%DesCoolCoilInHumRat
      FinalZoneSizing%CoolDesDay = CalcFinalZoneSizing%CoolDesDay
      FinalZoneSizing%HeatDesDay = CalcFinalZoneSizing%HeatDesDay
      FinalZoneSizing%DesHeatDens = CalcFinalZoneSizing%DesHeatDens
      FinalZoneSizing%DesCoolDens = CalcFinalZoneSizing%DesCoolDens
      FinalZoneSizing%HeatDDNum = CalcFinalZoneSizing%HeatDDNum
      FinalZoneSizing%CoolDDNum = CalcFinalZoneSizing%CoolDDNum
      FinalZoneSizing%DesHeatLoad = CalcFinalZoneSizing%DesHeatLoad
      FinalZoneSizing%DesHeatMassFlow = CalcFinalZoneSizing%DesHeatMassFlow
      FinalZoneSizing%ZoneTempAtHeatPeak = CalcFinalZoneSizing%ZoneTempAtHeatPeak
      FinalZoneSizing%OutTempAtHeatPeak = CalcFinalZoneSizing%OutTempAtHeatPeak
      FinalZoneSizing%ZoneRetTempAtHeatPeak = CalcFinalZoneSizing%ZoneRetTempAtHeatPeak
      FinalZoneSizing%ZoneHumRatAtHeatPeak = CalcFinalZoneSizing%ZoneHumRatAtHeatPeak
      FinalZoneSizing%OutHumRatAtHeatPeak = CalcFinalZoneSizing%OutHumRatAtHeatPeak
      FinalZoneSizing%TimeStepNumAtHeatMax = CalcFinalZoneSizing%TimeStepNumAtHeatMax
      FinalZoneSizing%DesHeatVolFlow = CalcFinalZoneSizing%DesHeatVolFlow
      FinalZoneSizing%DesHeatCoilInTemp = CalcFinalZoneSizing%DesHeatCoilInTemp
      FinalZoneSizing%DesHeatCoilInHumRat = CalcFinalZoneSizing%DesHeatCoilInHumRat
      FinalZoneSizing%DesCoolLoad = CalcFinalZoneSizing%DesCoolLoad
      FinalZoneSizing%DesCoolMassFlow = CalcFinalZoneSizing%DesCoolMassFlow
      FinalZoneSizing%ZoneTempAtCoolPeak = CalcFinalZoneSizing%ZoneTempAtCoolPeak
      FinalZoneSizing%OutTempAtCoolPeak = CalcFinalZoneSizing%OutTempAtCoolPeak
      FinalZoneSizing%ZoneRetTempAtCoolPeak = CalcFinalZoneSizing%ZoneRetTempAtCoolPeak
      FinalZoneSizing%ZoneHumRatAtCoolPeak = CalcFinalZoneSizing%ZoneHumRatAtCoolPeak
      FinalZoneSizing%OutHumRatAtCoolPeak = CalcFinalZoneSizing%OutHumRatAtCoolPeak
      FinalZoneSizing%TimeStepNumAtCoolMax = CalcFinalZoneSizing%TimeStepNumAtCoolMax
      FinalZoneSizing%DesCoolVolFlow = CalcFinalZoneSizing%DesCoolVolFlow
      FinalZoneSizing%DesCoolCoilInTemp = CalcFinalZoneSizing%DesCoolCoilInTemp
      FinalZoneSizing%DesCoolCoilInHumRat = CalcFinalZoneSizing%DesCoolCoilInHumRat
      DO DesDayNum = 1,TotDesDays+TotRunDesPersDays
        DO CtrlZoneNum = 1,NumOfZones
          IF (.not. ZoneEquipConfig(CtrlZoneNum)%IsControlled) CYCLE
          DO TimeStepIndex = 1,NumOfTimeStepInDay
            ZoneSizing(CtrlZoneNum,DesDayNum)%HeatFlowSeq(TimeStepIndex) = &
              CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatFlowSeq(TimeStepIndex)
            ZoneSizing(CtrlZoneNum,DesDayNum)%HeatLoadSeq(TimeStepIndex) = &
              CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatLoadSeq(TimeStepIndex)
            ZoneSizing(CtrlZoneNum,DesDayNum)%CoolFlowSeq(TimeStepIndex) = &
              CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolFlowSeq(TimeStepIndex)
            ZoneSizing(CtrlZoneNum,DesDayNum)%CoolLoadSeq(TimeStepIndex) = &
              CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolLoadSeq(TimeStepIndex)
            ZoneSizing(CtrlZoneNum,DesDayNum)%HeatZoneTempSeq(TimeStepIndex) = &
              CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatZoneTempSeq(TimeStepIndex)
            ZoneSizing(CtrlZoneNum,DesDayNum)%HeatOutTempSeq(TimeStepIndex) = &
              CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatOutTempSeq(TimeStepIndex)
            ZoneSizing(CtrlZoneNum,DesDayNum)%HeatZoneRetTempSeq(TimeStepIndex) = &
              CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatZoneRetTempSeq(TimeStepIndex)
            ZoneSizing(CtrlZoneNum,DesDayNum)%HeatTstatTempSeq(TimeStepIndex) = &
              CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatTstatTempSeq(TimeStepIndex)
            ZoneSizing(CtrlZoneNum,DesDayNum)%HeatZoneHumRatSeq(TimeStepIndex) = &
              CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatZoneHumRatSeq(TimeStepIndex)
            ZoneSizing(CtrlZoneNum,DesDayNum)%HeatOutHumRatSeq(TimeStepIndex) = &
              CalcZoneSizing(CtrlZoneNum,DesDayNum)%HeatOutHumRatSeq(TimeStepIndex)
            ZoneSizing(CtrlZoneNum,DesDayNum)%CoolZoneTempSeq(TimeStepIndex) = &
              CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolZoneTempSeq(TimeStepIndex)
            ZoneSizing(CtrlZoneNum,DesDayNum)%CoolOutTempSeq(TimeStepIndex) = &
              CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolOutTempSeq(TimeStepIndex)
            ZoneSizing(CtrlZoneNum,DesDayNum)%CoolZoneRetTempSeq(TimeStepIndex) = &
              CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolZoneRetTempSeq(TimeStepIndex)
            ZoneSizing(CtrlZoneNum,DesDayNum)%CoolTstatTempSeq(TimeStepIndex) = &
              CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolTstatTempSeq(TimeStepIndex)
            ZoneSizing(CtrlZoneNum,DesDayNum)%CoolZoneHumRatSeq(TimeStepIndex) = &
              CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolZoneHumRatSeq(TimeStepIndex)
            ZoneSizing(CtrlZoneNum,DesDayNum)%CoolOutHumRatSeq(TimeStepIndex) = &
              CalcZoneSizing(CtrlZoneNum,DesDayNum)%CoolOutHumRatSeq(TimeStepIndex)
          END DO
        END DO
      END DO
      DO CtrlZoneNum = 1,NumOfZones
        IF (.not. ZoneEquipConfig(CtrlZoneNum)%IsControlled) CYCLE
        DO TimeStepIndex = 1,NumOfTimeStepInDay
          FinalZoneSizing(CtrlZoneNum)%HeatFlowSeq(TimeStepIndex) = &
            CalcFinalZoneSizing(CtrlZoneNum)%HeatFlowSeq(TimeStepIndex)
          FinalZoneSizing(CtrlZoneNum)%HeatLoadSeq(TimeStepIndex) = &
            CalcFinalZoneSizing(CtrlZoneNum)%HeatLoadSeq(TimeStepIndex)
          FinalZoneSizing(CtrlZoneNum)%CoolFlowSeq(TimeStepIndex) = &
            CalcFinalZoneSizing(CtrlZoneNum)%CoolFlowSeq(TimeStepIndex)
          FinalZoneSizing(CtrlZoneNum)%CoolLoadSeq(TimeStepIndex) = &
            CalcFinalZoneSizing(CtrlZoneNum)%CoolLoadSeq(TimeStepIndex)
          FinalZoneSizing(CtrlZoneNum)%HeatZoneTempSeq(TimeStepIndex) = &
            CalcFinalZoneSizing(CtrlZoneNum)%HeatZoneTempSeq(TimeStepIndex)
          FinalZoneSizing(CtrlZoneNum)%HeatOutTempSeq(TimeStepIndex) = &
            CalcFinalZoneSizing(CtrlZoneNum)%HeatOutTempSeq(TimeStepIndex)
          FinalZoneSizing(CtrlZoneNum)%HeatZoneRetTempSeq(TimeStepIndex) = &
            CalcFinalZoneSizing(CtrlZoneNum)%HeatZoneRetTempSeq(TimeStepIndex)
          FinalZoneSizing(CtrlZoneNum)%HeatTstatTempSeq(TimeStepIndex) = &
            CalcFinalZoneSizing(CtrlZoneNum)%HeatTstatTempSeq(TimeStepIndex)
          FinalZoneSizing(CtrlZoneNum)%HeatZoneHumRatSeq(TimeStepIndex) = &
            CalcFinalZoneSizing(CtrlZoneNum)%HeatZoneHumRatSeq(TimeStepIndex)
          FinalZoneSizing(CtrlZoneNum)%HeatOutHumRatSeq(TimeStepIndex) = &
            CalcFinalZoneSizing(CtrlZoneNum)%HeatOutHumRatSeq(TimeStepIndex)
          FinalZoneSizing(CtrlZoneNum)%CoolZoneTempSeq(TimeStepIndex) = &
            CalcFinalZoneSizing(CtrlZoneNum)%CoolZoneTempSeq(TimeStepIndex)
          FinalZoneSizing(CtrlZoneNum)%CoolOutTempSeq(TimeStepIndex) = &
            CalcFinalZoneSizing(CtrlZoneNum)%CoolOutTempSeq(TimeStepIndex)
          FinalZoneSizing(CtrlZoneNum)%CoolZoneRetTempSeq(TimeStepIndex) = &
            CalcFinalZoneSizing(CtrlZoneNum)%CoolZoneRetTempSeq(TimeStepIndex)
          FinalZoneSizing(CtrlZoneNum)%CoolTstatTempSeq(TimeStepIndex) = &
            CalcFinalZoneSizing(CtrlZoneNum)%CoolTstatTempSeq(TimeStepIndex)
          FinalZoneSizing(CtrlZoneNum)%CoolZoneHumRatSeq(TimeStepIndex) = &
            CalcFinalZoneSizing(CtrlZoneNum)%CoolZoneHumRatSeq(TimeStepIndex)
          FinalZoneSizing(CtrlZoneNum)%CoolOutHumRatSeq(TimeStepIndex) = &
            CalcFinalZoneSizing(CtrlZoneNum)%CoolOutHumRatSeq(TimeStepIndex)
        END DO
      END DO
      DO  CtrlZoneNum = 1,NumOfZones
        IF (.not. ZoneEquipConfig(CtrlZoneNum)%IsControlled) CYCLE
        ! Now take into account the user specified sizing factor and user specified cooling design air flow
        ! rate
        TotCoolSizMult = 0.0d0
        ! Calculate a sizing factor from the user specified cooling design air flow rate
        IF (FinalZoneSizing(CtrlZoneNum)%InpDesCoolAirFlow > 0.0d0 .AND. &
            FinalZoneSizing(CtrlZoneNum)%CoolAirDesMethod == InpDesAirFlow .AND. &
            FinalZoneSizing(CtrlZoneNum)%DesCoolVolFlow > 0.0d0) THEN
          TotCoolSizMult = (FinalZoneSizing(CtrlZoneNum)%InpDesCoolAirFlow / &
            FinalZoneSizing(CtrlZoneNum)%DesCoolVolFlow) * FinalZoneSizing(CtrlZoneNum)%CoolSizingFactor
        ! If no user specified cooling design air flow rate input, use the user specified szing factor
        ELSE
          TotCoolSizMult = FinalZoneSizing(CtrlZoneNum)%CoolSizingFactor
        END IF
        ! If the cooling sizing multiplier is not 1, adjust the cooling design data
        IF (ABS(TotCoolSizMult-1.0d0) > .00001d0) THEN
          IF (FinalZoneSizing(CtrlZoneNum)%DesCoolVolFlow > 0.0d0) THEN
            TimeStepAtPeak = FinalZoneSizing(CtrlZoneNum)%TimeStepNumAtCoolMax
            DDNum = FinalZoneSizing(CtrlZoneNum)%CoolDDNum
            FinalZoneSizing(CtrlZoneNum)%DesCoolVolFlow = CalcFinalZoneSizing(CtrlZoneNum)%DesCoolVolFlow * TotCoolSizMult
            FinalZoneSizing(CtrlZoneNum)%DesCoolMassFlow = CalcFinalZoneSizing(CtrlZoneNum)%DesCoolMassFlow &
                                                             * TotCoolSizMult
            FinalZoneSizing(CtrlZoneNum)%DesCoolLoad = CalcFinalZoneSizing(CtrlZoneNum)%DesCoolLoad * TotCoolSizMult
            FinalZoneSizing(CtrlZoneNum)%CoolFlowSeq = CalcFinalZoneSizing(CtrlZoneNum)%CoolFlowSeq * TotCoolSizMult
            FinalZoneSizing(CtrlZoneNum)%CoolLoadSeq = CalcFinalZoneSizing(CtrlZoneNum)%CoolLoadSeq * TotCoolSizMult
            OAFrac = FinalZoneSizing(CtrlZoneNum)%MinOA &
                       / FinalZoneSizing(CtrlZoneNum)%DesCoolVolFlow
            OAFrac = MIN(1.0d0,MAX(0.0d0,OAFrac))
            FinalZoneSizing(CtrlZoneNum)%DesCoolCoilInTemp = OAFrac*DesDayWeath(DDNum)%Temp(TimeStepAtPeak) + &
                                                      (1.0d0-OAFrac)*FinalZoneSizing(CtrlZoneNum)%ZoneTempAtCoolPeak
            FinalZoneSizing(CtrlZoneNum)%DesCoolCoilInHumRat = &
                                                 OAFrac*DesDayWeath(DDNum)%HumRat(TimeStepAtPeak) + &
                                                 (1.0d0-OAFrac)*FinalZoneSizing(CtrlZoneNum)%ZoneHumRatAtCoolPeak
          ELSE
            FinalZoneSizing(CtrlZoneNum)%DesCoolVolFlow = FinalZoneSizing(CtrlZoneNum)%InpDesCoolAirFlow
            FinalZoneSizing(CtrlZoneNum)%DesCoolMassFlow = FinalZoneSizing(CtrlZoneNum)%DesCoolVolFlow * &
              FinalZoneSizing(CtrlZoneNum)%DesCoolDens
          END IF
          DO DDNum = 1,TotDesDays+TotRunDesPersDays
            IF (ZoneSizing(CtrlZoneNum,DDNum)%DesCoolVolFlow > 0.0d0) THEN
              TimeStepAtPeak = ZoneSizing(CtrlZoneNum,DDNum)%TimeStepNumAtCoolMax
              ZoneSizing(CtrlZoneNum,DDNum)%DesCoolVolFlow = CalcZoneSizing(CtrlZoneNum,DDNum)%DesCoolVolFlow * &
                                                               TotCoolSizMult
              ZoneSizing(CtrlZoneNum,DDNum)%DesCoolMassFlow = CalcZoneSizing(CtrlZoneNum,DDNum)%DesCoolMassFlow &
                                                               * TotCoolSizMult
              ZoneSizing(CtrlZoneNum,DDNum)%DesCoolLoad = CalcZoneSizing(CtrlZoneNum,DDNum)%DesCoolLoad * TotCoolSizMult
              ZoneSizing(CtrlZoneNum,DDNum)%CoolFlowSeq = CalcZoneSizing(CtrlZoneNum,DDNum)%CoolFlowSeq * TotCoolSizMult
              ZoneSizing(CtrlZoneNum,DDNum)%CoolLoadSeq = CalcZoneSizing(CtrlZoneNum,DDNum)%CoolLoadSeq * TotCoolSizMult
              OAFrac = ZoneSizing(CtrlZoneNum,DDNum)%MinOA &
                         / ZoneSizing(CtrlZoneNum,DDNum)%DesCoolVolFlow
              OAFrac = MIN(1.0d0,MAX(0.0d0,OAFrac))
              ZoneSizing(CtrlZoneNum,DDNum)%DesCoolCoilInTemp = OAFrac*DesDayWeath(DDNum)%Temp(TimeStepAtPeak) + &
                                                        (1.0d0-OAFrac)*ZoneSizing(CtrlZoneNum,DDNum)%ZoneTempAtCoolPeak
              ZoneSizing(CtrlZoneNum,DDNum)%DesCoolCoilInHumRat = &
                                                   OAFrac*DesDayWeath(DDNum)%HumRat(TimeStepAtPeak) + &
                                                   (1.0d0-OAFrac)*ZoneSizing(CtrlZoneNum,DDNum)%ZoneHumRatAtCoolPeak
            ELSE
              ZoneSizing(CtrlZoneNum,DDNum)%DesCoolVolFlow = ZoneSizing(CtrlZoneNum,DDNum)%InpDesCoolAirFlow
              ZoneSizing(CtrlZoneNum,DDNum)%DesCoolMassFlow = ZoneSizing(CtrlZoneNum,DDNum)%DesCoolVolFlow * &
                ZoneSizing(CtrlZoneNum,DDNum)%DesCoolDens
            END IF
          END DO
        END IF
        ! Now make sure that the design cooling air flow rates are greater than or equal to the specified minimums
        IF (FinalZoneSizing(CtrlZoneNum)%CoolAirDesMethod == DesAirFlowWithLim) THEN
          MaxOfMinCoolVolFlow = MAX(FinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlow,   &
                                 FinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlow2, &
                                 FinalZoneSizing(CtrlZoneNum)%MinOA)
        ELSE
          MaxOfMinCoolVolFlow = FinalZoneSizing(CtrlZoneNum)%MinOA
        END IF
        MaxOfMinCoolMassFlow = MaxOfMinCoolVolFlow * FinalZoneSizing(CtrlZoneNum)%DesCoolDens
        IF (MaxOfMinCoolVolFlow > FinalZoneSizing(CtrlZoneNum)%DesCoolVolFlow) THEN
          FinalZoneSizing(CtrlZoneNum)%DesCoolVolFlow = MaxOfMinCoolVolFlow
          FinalZoneSizing(CtrlZoneNum)%DesCoolMassFlow = MaxOfMinCoolMassFlow
        END IF
        DO TimeStepIndex = 1,NumOfTimeStepInDay
          IF (MaxOfMinCoolMassFlow > FinalZoneSizing(CtrlZoneNum)%CoolFlowSeq(TimeStepIndex)) THEN
            FinalZoneSizing(CtrlZoneNum)%CoolFlowSeq(TimeStepIndex) = MaxOfMinCoolMassFlow
          END IF
        END DO
        DO DDNum = 1,TotDesDays+TotRunDesPersDays
          MaxOfMinCoolVolFlow = MAX(ZoneSizing(CtrlZoneNum,DDNum)%DesCoolMinAirFlow,   &
                                 ZoneSizing(CtrlZoneNum,DDNum)%DesCoolMinAirFlow, &
                                 ZoneSizing(CtrlZoneNum,DDNum)%MinOA)
          MaxOfMinCoolMassFlow =   MaxOfMinCoolVolFlow * ZoneSizing(CtrlZoneNum,DDNum)%DesCoolDens
          IF (MaxOfMinCoolVolFlow > ZoneSizing(CtrlZoneNum,DDNum)%DesCoolVolFlow) THEN
            ZoneSizing(CtrlZoneNum,DDNum)%DesCoolVolFlow = MaxOfMinCoolVolFlow
            ZoneSizing(CtrlZoneNum,DDNum)%DesCoolMassFlow = MaxOfMinCoolMassFlow
          END IF
          DO TimeStepIndex = 1,NumOfTimeStepInDay
            IF (MaxOfMinCoolMassFlow > ZoneSizing(CtrlZoneNum,DDNum)%CoolFlowSeq(TimeStepIndex)) THEN
              ZoneSizing(CtrlZoneNum,DDNum)%CoolFlowSeq(TimeStepIndex) = MaxOfMinCoolMassFlow
            END IF
          END DO
        END DO
! IF cooling flow rate is 0, this data may be used to size a HP so initialize DDNum, TimeStepatPeak, and sizing data (end of IF)
        ! check for flow rate having been set (by MinOA or other min) but no timestep at max
!        IF (FinalZoneSizing(CtrlZoneNum)%DesCoolMassFlow > 0.0d0 .AND. &
         IF ((FinalZoneSizing(CtrlZoneNum)%TimeStepNumAtCoolMax == 0 .OR. &
              FinalZoneSizing(CtrlZoneNum)%CoolDDNum == 0) ) THEN
          DO DDNum = 1,TotDesDays+TotRunDesPersDays
            ZoneSizing(CtrlZoneNum,DDNum)%TimeStepNumAtCoolMax = 1
            TimeStepAtPeak = ZoneSizing(CtrlZoneNum,DDNum)%TimeStepNumAtCoolMax
            DO TimeStepIndex = 1,NumOfTimeStepInDay
             IF (DesDayWeath(DDNum)%Temp(TimeStepIndex) > DesDayWeath(DDNum)%Temp(TimeStepAtPeak)) THEN
               TimeStepAtPeak = TimeStepIndex
             END IF
            END DO
            ZoneSizing(CtrlZoneNum,DDNum)%TimeStepNumAtCoolMax = TimeStepAtPeak
          END DO
          FinalZoneSizing(CtrlZoneNum)%TimeStepNumAtCoolMax = 1
          FinalZoneSizing(CtrlZoneNum)%CoolDDNum = 1
          TimeStepAtPeakF = FinalZoneSizing(CtrlZoneNum)%TimeStepNumAtCoolMax
          DDNumF = FinalZoneSizing(CtrlZoneNum)%CoolDDNum
          DO DDNum = 1,TotDesDays+TotRunDesPersDays
            TimeStepAtPeak = ZoneSizing(CtrlZoneNum,DDNum)%TimeStepNumAtCoolMax
            IF (DesDayWeath(DDNum)%Temp(TimeStepAtPeak) > DesDayWeath(DDNumF)%Temp(TimeStepAtPeakF)) THEN
              DDNumF = DDNum
              TimeStepAtPeakF = TimeStepAtPeak
            END IF
          END DO
          FinalZoneSizing(CtrlZoneNum)%TimeStepNumAtCoolMax = TimeStepAtPeakF
          FinalZoneSizing(CtrlZoneNum)%CoolDDNum = DDNumF
          FinalZoneSizing(CtrlZoneNum)%CoolDesDay = ZoneSizing(CtrlZoneNum,DDNumF)%CoolDesDay
          ! initialize sizing conditions if they have not been set (i.e., no corresponding load) to zone condition
          IF(FinalZoneSizing(CtrlZoneNum)%ZoneTempAtCoolPeak == 0.d0)THEN
            FinalZoneSizing(CtrlZoneNum)%ZoneTempAtCoolPeak = ZoneSizing(CtrlZoneNum,DDNumF)%DesCoolSetPtSeq(TimeStepAtPeakF)
            FinalZoneSizing(CtrlZoneNum)%ZoneHumRatAtCoolPeak = ZoneSizing(CtrlZoneNum,DDNumF)%CoolZoneHumRatSeq(TimeStepAtPeakF)
            IF(FinalZoneSizing(CtrlZoneNum)%ZoneHumRatAtCoolPeak .GT. 0.d0)THEN
              FinalZoneSizing(CtrlZoneNum)%ZoneHumRatAtCoolPeak = &
                 MIN(FinalZoneSizing(CtrlZoneNum)%ZoneHumRatAtCoolPeak, &
                   PsyWFnTdpPb(FinalZoneSizing(CtrlZoneNum)%ZoneTempAtCoolPeak,StdBaroPress,'UpdateZoneSizing'))
            ELSE
              FinalZoneSizing(CtrlZoneNum)%ZoneHumRatAtCoolPeak = ZoneSizing(CtrlZoneNum,DDNumF)%CoolDesHumRat
            END IF
            FinalZoneSizing(CtrlZoneNum)%DesCoolCoilInTemp = FinalZoneSizing(CtrlZoneNum)%ZoneTempAtCoolPeak
            FinalZoneSizing(CtrlZoneNum)%DesCoolCoilInHumRat = FinalZoneSizing(CtrlZoneNum)%ZoneHumRatAtCoolPeak
            FinalZoneSizing(CtrlZoneNum)%ZoneRetTempAtCoolPeak = FinalZoneSizing(CtrlZoneNum)%ZoneTempAtCoolPeak
          END IF
        END IF
        ! Now take into account the user specified sizing factor or user specified heating design air flow
        ! rate (which overrides the sizing factor)
        TotHeatSizMult = 0.0d0
        ! Calculate a sizing factor from the user specified heating design air flow rate
        IF (FinalZoneSizing(CtrlZoneNum)%InpDesHeatAirFlow > 0.0d0 .AND. &
            FinalZoneSizing(CtrlZoneNum)%HeatAirDesMethod == InpDesAirFlow .AND. &
            FinalZoneSizing(CtrlZoneNum)%DesHeatVolFlow > 0.0d0) THEN
          TotHeatSizMult = (FinalZoneSizing(CtrlZoneNum)%InpDesHeatAirFlow / &
            FinalZoneSizing(CtrlZoneNum)%DesHeatVolFlow) * FinalZoneSizing(CtrlZoneNum)%HeatSizingFactor
        ! Calculate a sizing factor from the user specified max heating design air flow rates
        ELSE IF ( FinalZoneSizing(CtrlZoneNum)%HeatAirDesMethod == DesAirFlowWithLim .AND. &
            FinalZoneSizing(CtrlZoneNum)%DesHeatVolFlow > 0.0d0) THEN
            MaxHeatVolFlow = MAX(FinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlow, &
                                                             FinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlow2, &
                                                             FinalZoneSizing(CtrlZoneNum)%DesCoolVolFlow * &
                                                             FinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlowFrac)
          IF (MaxHeatVolFlow < FinalZoneSizing(CtrlZoneNum)%DesHeatVolFlow) THEN
            TotHeatSizMult = (MaxHeatVolFlow / FinalZoneSizing(CtrlZoneNum)%DesHeatVolFlow) *   &
               FinalZoneSizing(CtrlZoneNum)%HeatSizingFactor
          ELSE
            TotHeatSizMult = FinalZoneSizing(CtrlZoneNum)%HeatSizingFactor
          END IF
        ! If no user specified heating design air flow rate input, use the user specified sizing factor
        ELSE
          TotHeatSizMult = FinalZoneSizing(CtrlZoneNum)%HeatSizingFactor
        END IF
        IF (ABS(TotHeatSizMult-1.0d0) > .00001d0 ) THEN
         IF (FinalZoneSizing(CtrlZoneNum)%DesHeatVolFlow > 0.0d0) THEN
            TimeStepAtPeak = FinalZoneSizing(CtrlZoneNum)%TimeStepNumAtHeatMax
            DDNum = FinalZoneSizing(CtrlZoneNum)%HeatDDNum
            FinalZoneSizing(CtrlZoneNum)%DesHeatVolFlow = CalcFinalZoneSizing(CtrlZoneNum)%DesHeatVolFlow * TotHeatSizMult
            FinalZoneSizing(CtrlZoneNum)%DesHeatMassFlow = CalcFinalZoneSizing(CtrlZoneNum)%DesHeatMassFlow * TotHeatSizMult
            FinalZoneSizing(CtrlZoneNum)%DesHeatLoad = CalcFinalZoneSizing(CtrlZoneNum)%DesHeatLoad * TotHeatSizMult
            FinalZoneSizing(CtrlZoneNum)%HeatFlowSeq = CalcFinalZoneSizing(CtrlZoneNum)%HeatFlowSeq * TotHeatSizMult
            FinalZoneSizing(CtrlZoneNum)%HeatLoadSeq = CalcFinalZoneSizing(CtrlZoneNum)%HeatLoadSeq * TotHeatSizMult
            OAFrac = FinalZoneSizing(CtrlZoneNum)%MinOA &
                       / FinalZoneSizing(CtrlZoneNum)%DesHeatVolFlow
            OAFrac = MIN(1.0d0,MAX(0.0d0,OAFrac))
            FinalZoneSizing(CtrlZoneNum)%DesHeatCoilInTemp = OAFrac*DesDayWeath(DDNum)%Temp(TimeStepAtPeak) + &
                                                      (1.d0-OAFrac)*FinalZoneSizing(CtrlZoneNum)%ZoneTempAtHeatPeak
            FinalZoneSizing(CtrlZoneNum)%DesHeatCoilInHumRat = &
                                                 OAFrac*DesDayWeath(DDNum)%HumRat(TimeStepAtPeak) + &
                                                 (1.d0-OAFrac)*FinalZoneSizing(CtrlZoneNum)%ZoneHumRatAtHeatPeak
          ELSE
            FinalZoneSizing(CtrlZoneNum)%DesHeatVolFlow = FinalZoneSizing(CtrlZoneNum)%InpDesHeatAirFlow
            FinalZoneSizing(CtrlZoneNum)%DesHeatMassFlow = FinalZoneSizing(CtrlZoneNum)%DesHeatVolFlow * &
              FinalZoneSizing(CtrlZoneNum)%DesHeatDens
          END IF
          DO DDNum = 1,TotDesDays+TotRunDesPersDays
            IF (ZoneSizing(CtrlZoneNum,DDNum)%DesHeatVolFlow > 0.0d0) THEN
              TimeStepAtPeak = ZoneSizing(CtrlZoneNum,DDNum)%TimeStepNumAtHeatMax
              ZoneSizing(CtrlZoneNum,DDNum)%DesHeatVolFlow = CalcZoneSizing(CtrlZoneNum,DDNum)%DesHeatVolFlow * &
                                                               TotHeatSizMult
              ZoneSizing(CtrlZoneNum,DDNum)%DesHeatMassFlow = CalcZoneSizing(CtrlZoneNum,DDNum)%DesHeatMassFlow &
                                                               * TotHeatSizMult
              ZoneSizing(CtrlZoneNum,DDNum)%DesHeatLoad = CalcZoneSizing(CtrlZoneNum,DDNum)%DesHeatLoad * TotHeatSizMult
              ZoneSizing(CtrlZoneNum,DDNum)%HeatFlowSeq = CalcZoneSizing(CtrlZoneNum,DDNum)%HeatFlowSeq * TotHeatSizMult
              ZoneSizing(CtrlZoneNum,DDNum)%HeatLoadSeq = CalcZoneSizing(CtrlZoneNum,DDNum)%HeatLoadSeq * TotHeatSizMult
              OAFrac = ZoneSizing(CtrlZoneNum,DDNum)%MinOA &
                         / ZoneSizing(CtrlZoneNum,DDNum)%DesHeatVolFlow
              OAFrac = MIN(1.0d0,MAX(0.0d0,OAFrac))
              ZoneSizing(CtrlZoneNum,DDNum)%DesHeatCoilInTemp = OAFrac*DesDayWeath(DDNum)%Temp(TimeStepAtPeak) + &
                                                        (1.d0-OAFrac)*ZoneSizing(CtrlZoneNum,DDNum)%ZoneTempAtHeatPeak
              ZoneSizing(CtrlZoneNum,DDNum)%DesHeatCoilInHumRat = &
                                                   OAFrac*DesDayWeath(DDNum)%HumRat(TimeStepAtPeak) + &
                                                   (1.d0-OAFrac)*ZoneSizing(CtrlZoneNum,DDNum)%ZoneHumRatAtHeatPeak
            ELSE
              ZoneSizing(CtrlZoneNum,DDNum)%DesHeatVolFlow = ZoneSizing(CtrlZoneNum,DDNum)%InpDesHeatAirFlow
              ZoneSizing(CtrlZoneNum,DDNum)%DesHeatMassFlow = ZoneSizing(CtrlZoneNum,DDNum)%DesHeatVolFlow * &
                ZoneSizing(CtrlZoneNum,DDNum)%DesHeatDens
            END IF
          END DO
        END IF
        MinOAMass = FinalZoneSizing(CtrlZoneNum)%MinOA * FinalZoneSizing(CtrlZoneNum)%DesHeatDens
        IF (FinalZoneSizing(CtrlZoneNum)%MinOA > FinalZoneSizing(CtrlZoneNum)%DesHeatVolFlow) THEN
          FinalZoneSizing(CtrlZoneNum)%DesHeatVolFlow = FinalZoneSizing(CtrlZoneNum)%MinOA
          FinalZoneSizing(CtrlZoneNum)%DesHeatMassFlow = MinOAMass
        END IF
        DO TimeStepIndex = 1,NumOfTimeStepInDay
          IF (MinOAMass > FinalZoneSizing(CtrlZoneNum)%HeatFlowSeq(TimeStepIndex)) THEN
            FinalZoneSizing(CtrlZoneNum)%HeatFlowSeq(TimeStepIndex) = MinOAMass
          END IF
        END DO
        DO DDNum = 1,TotDesDays+TotRunDesPersDays
          MinOAMass = ZoneSizing(CtrlZoneNum,DDNum)%MinOA * ZoneSizing(CtrlZoneNum,DDNum)%DesHeatDens
          IF (ZoneSizing(CtrlZoneNum,DDNum)%MinOA > ZoneSizing(CtrlZoneNum,DDNum)%DesHeatVolFlow) THEN
            ZoneSizing(CtrlZoneNum,DDNum)%DesHeatVolFlow = ZoneSizing(CtrlZoneNum,DDNum)%MinOA
            ZoneSizing(CtrlZoneNum,DDNum)%DesHeatMassFlow = MinOAMass
          END IF
          DO TimeStepIndex = 1,NumOfTimeStepInDay
            IF (MinOAMass > ZoneSizing(CtrlZoneNum,DDNum)%HeatFlowSeq(TimeStepIndex)) THEN
              ZoneSizing(CtrlZoneNum,DDNum)%HeatFlowSeq(TimeStepIndex) = MinOAMass
            END IF
          END DO
        END DO
! IF heating flow rate is 0, this data may be used to size a HP so initialize DDNum, TimeStepatPeak, and sizing data (end of IF)
        ! check for flow rate having been set (by MinOA or other min) but no timestep at max
!        IF (FinalZoneSizing(CtrlZoneNum)%DesHeatMassFlow > 0.0d0 .AND. &
         IF ((FinalZoneSizing(CtrlZoneNum)%TimeStepNumAtHeatMax == 0 .OR. &
              FinalZoneSizing(CtrlZoneNum)%HeatDDNum == 0) ) THEN
          DO DDNum = 1,TotDesDays+TotRunDesPersDays
            ZoneSizing(CtrlZoneNum,DDNum)%TimeStepNumAtHeatMax = 1
            TimeStepAtPeak = ZoneSizing(CtrlZoneNum,DDNum)%TimeStepNumAtHeatMax
            DO TimeStepIndex = 1,NumOfTimeStepInDay
             IF (DesDayWeath(DDNum)%Temp(TimeStepIndex) < DesDayWeath(DDNum)%Temp(TimeStepAtPeak)) THEN
               TimeStepAtPeak = TimeStepIndex
             END IF
            END DO
            ZoneSizing(CtrlZoneNum,DDNum)%TimeStepNumAtHeatMax = TimeStepAtPeak
          END DO
          FinalZoneSizing(CtrlZoneNum)%TimeStepNumAtHeatMax = 1
          FinalZoneSizing(CtrlZoneNum)%HeatDDNum = 1
          TimeStepAtPeakF = FinalZoneSizing(CtrlZoneNum)%TimeStepNumAtHeatMax
          DDNumF = FinalZoneSizing(CtrlZoneNum)%HeatDDNum
          DO DDNum = 1,TotDesDays+TotRunDesPersDays
            TimeStepAtPeak = ZoneSizing(CtrlZoneNum,DDNum)%TimeStepNumAtHeatMax
            IF (DesDayWeath(DDNum)%Temp(TimeStepAtPeak) < DesDayWeath(DDNumF)%Temp(TimeStepAtPeakF)) THEN
              DDNumF = DDNum
              TimeStepAtPeakF = TimeStepAtPeak
            END IF
          END DO
          FinalZoneSizing(CtrlZoneNum)%TimeStepNumAtHeatMax = TimeStepAtPeakF
          FinalZoneSizing(CtrlZoneNum)%HeatDDNum = DDNumF
          FinalZoneSizing(CtrlZoneNum)%HeatDesDay = ZoneSizing(CtrlZoneNum,DDNumF)%HeatDesDay
          ! initialize sizing conditions if they have not been set (i.e., no corresponding load) to zone condition
          IF(FinalZoneSizing(CtrlZoneNum)%ZoneTempAtHeatPeak == 0.d0)THEN
            FinalZoneSizing(CtrlZoneNum)%ZoneTempAtHeatPeak = ZoneSizing(CtrlZoneNum,DDNumF)%DesHeatSetPtSeq(TimeStepAtPeakF)
            FinalZoneSizing(CtrlZoneNum)%ZoneHumRatAtHeatPeak = ZoneSizing(CtrlZoneNum,DDNumF)%HeatZoneHumRatSeq(TimeStepAtPeakF)
            IF(FinalZoneSizing(CtrlZoneNum)%ZoneHumRatAtHeatPeak .GT. 0.d0)THEN
              FinalZoneSizing(CtrlZoneNum)%ZoneHumRatAtHeatPeak = &
                 MIN(FinalZoneSizing(CtrlZoneNum)%ZoneHumRatAtHeatPeak, &
                   PsyWFnTdpPb(FinalZoneSizing(CtrlZoneNum)%ZoneTempAtHeatPeak,StdBaroPress,'UpdateZoneSizing'))
            ELSE
              FinalZoneSizing(CtrlZoneNum)%ZoneHumRatAtHeatPeak = ZoneSizing(CtrlZoneNum,DDNumF)%HeatDesHumRat
            END IF
            FinalZoneSizing(CtrlZoneNum)%DesHeatCoilInTemp = FinalZoneSizing(CtrlZoneNum)%ZoneTempAtHeatPeak
            FinalZoneSizing(CtrlZoneNum)%DesHeatCoilInHumRat = FinalZoneSizing(CtrlZoneNum)%ZoneHumRatAtHeatPeak
            FinalZoneSizing(CtrlZoneNum)%ZoneRetTempAtHeatPeak = FinalZoneSizing(CtrlZoneNum)%ZoneTempAtHeatPeak
          END IF
        END IF
        ! set the zone minimum cooling supply air flow rate. This will be used for autosizing VAV terminal unit
        ! minimum flow rates
        FinalZoneSizing(CtrlZoneNum)%DesCoolVolFlowMin = MAX(FinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlow, &
                                                             FinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlow2, &
                                                             FinalZoneSizing(CtrlZoneNum)%DesCoolVolFlow * &
                                                               FinalZoneSizing(CtrlZoneNum)%DesCoolMinAirFlowFrac)
        ! set the zone maximum heating supply air flow rate. This will be used for autosizing VAV terminal unit
        ! max heating flow rates
        FinalZoneSizing(CtrlZoneNum)%DesHeatVolFlowMax = MAX(FinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlow, &
                                                             FinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlow2, &
                                                             FinalZoneSizing(CtrlZoneNum)%DesHeatVolFlow * &
                                                               FinalZoneSizing(CtrlZoneNum)%DesHeatMaxAirFlowFrac)
        ! Determine the design cooling supply air temperature if the supply air temperature difference is specified by user.
        IF (FinalZoneSizing(CtrlZoneNum)%ZnCoolDgnSAMethod == TemperatureDifference) THEN
          FinalZoneSizing(CtrlZoneNum)%CoolDesTemp = FinalZoneSizing(CtrlZoneNum)%ZoneTempAtCoolPeak - &
                                                       ABS(FinalZoneSizing(CtrlZoneNum)%CoolDesTempDiff)
        END IF
        ! Determine the design heating supply air temperature if the supply air temperature difference is specified by user.
        IF (FinalZoneSizing(CtrlZoneNum)%ZnHeatDgnSAMethod == TemperatureDifference) THEN
          FinalZoneSizing(CtrlZoneNum)%HeatDesTemp = FinalZoneSizing(CtrlZoneNum)%ZoneTempAtHeatPeak + &
                                                       ABS(FinalZoneSizing(CtrlZoneNum)%HeatDesTempDiff)
        END IF
      END DO
  END SELECT
  TermUnitFinalZoneSizing = FinalZoneSizing
  RETURN
END SUBROUTINE UpdateZoneSizing
All Procedures
AbortEnergyPlus AbsoluteAirMass ActivateDemandManagers ActivateEMSControls AddBlankKeys addChargesToOperand AddCompSizeTableEntry AddEndUseSubcategory AddError addFootNoteSubTable AddInstruction AddMeter addMonthlyCharge AddMonthlyFieldSetInput AddMonthlyReport AddNeighborInformation AddObjectDefandParse addOperand AddRecordFromSection AddRecordToOutputVariableStructure AddSectionDef AddShadowRelateTableEntry AddSQLiteComponentSizingRecord AddSQLiteComponentSizingRecord AddSQLiteSystemSizingRecord AddSQLiteSystemSizingRecord AddSQLiteZoneSizingRecord AddSQLiteZoneSizingRecord AddTOCEntry AddTOCZoneLoadComponentTable AddToOutputVariableList AddVariablesForMonthlyReport AddVariableSlatBlind AddWindow AdjustAirSetpointsforOpTempCntrl AdjustCBF AdjustCBF AdjustChangeInLoadByEMSControls AdjustChangeInLoadByHowServed AdjustChangeInLoadForLastStageUpperRangeLimit AdjustCoolingSetPointforTempAndHumidityControl adjusthhat AdjustPumpFlowRequestByEMSControls AdjustReportingHourAndMinutes AdjustVBGap AdvanceRootFinder AFECFR AFECOI AFECPD AFECPF AFEDMP AFEDOP AFEDWC AFEELR AFEEXF AFEFAN AFEHEX AFEHOP AFEPLR AFESCR AFESEL AFESOP AFETMU AirflowNetworkVentingControl AirMass AIRMOV AllocateAirflowNetworkData AllocateAirHeatBalArrays AllocateAndInitData AllocateAndSetUpVentReports AllocateCFSStateHourlyData AllocateForCFSRefPointsGeometry AllocateForCFSRefPointsState AllocateHeatBalArrays AllocateLoadComponentArrays AllocateModuleArrays AllocateModuleArrays AllocateSurfaceHeatBalArrays AllocateWeatherData angle_2dvector AnisoSkyViewFactors AnyPlantLoopSidesNeedSim AnyPlantSplitterMixerLacksContinuity AreaPolygon ArgCheck array_to_vector ASHRAETauModel ASHWAT_OffNormalProperties ASHWAT_Solar ASHWAT_Thermal ASSIGNMENT (=) AssignNodeNumber AssignReportNumber AssignResourceTypeNum AssignReverseConstructionNumber AssignVariablePt AttachCustomMeters AttachMeters AuditBranches AUTOTDMA BaseThermalPropertySet_Diffusivity BeginEnvrnInitializeRuntimeLanguage BetweenDates BetweenGlassForcedFlow BetweenGlassShadeForcedFlow BetweenGlassShadeNaturalFlow BisectionMethod BlindBeamBeamTrans BlindOpticsBeam BlindOpticsDiffuse BoreholeResistance BoundValueToNodeMinMaxAvail BoundValueToWithinTwoValues BracketRoot BranchPressureDrop BrentMethod BuildGap BuildKeyVarList Calc4PipeFanCoil Calc_EN673 Calc_ISO15099 CalcActiveTranspiredCollector CalcAggregateLoad CalcAirflowNetworkAirBalance CalcAirflowNetworkCO2Balance CalcAirflowNetworkGCBalance CalcAirflowNetworkHeatBalance CalcAirflowNetworkMoisBalance CalcAirFlowSimple CalcAirLoopSplitter CalcAirMixer CalcAirToAirGenericHeatExch CalcAirToAirPlateHeatExch CalcAirZoneReturnPlenum CalcAirZoneSupplyPlenum CalcAlamdariHammondStableHorizontal CalcAlamdariHammondUnstableHorizontal CalcAlamdariHammondVerticalWall CalcAngleFactorMRT CalcApproximateViewFactors CalcASHRAEDetailedIntConvCoeff CalcASHRAESimpExtConvectCoeff CalcASHRAESimpleIntConvCoeff CalcASHRAEVerticalWall CalcATMixer CalcAwbiHattonHeatedFloor CalcAwbiHattonHeatedWall CalcBasinHeaterPower CalcBasinHeaterPowerForMultiModeDXCoil CalcBeamSolarOnWinRevealSurface CalcBeamSolDiffuseReflFactors CalcBeamSolSpecularReflFactors CalcBeausoleilMorrisonMixedAssistedWall CalcBeausoleilMorrisonMixedOpposingWall CalcBeausoleilMorrisonMixedStableCeiling CalcBeausoleilMorrisonMixedStableFloor CalcBeausoleilMorrisonMixedUnstableCeiling CalcBeausoleilMorrisonMixedUnstableFloor CalcBLASTAbsorberModel CalcBlockenWindward CalcBoilerModel CalcBoilerModel CalcBottomFluxCoefficents CalcBottomSurfTemp CalcBuriedPipeSoil CalcCBF CalcCBF CalcCBVAV CalcCeilingDiffuserInletCorr CalcCeilingDiffuserIntConvCoeff CalcChillerHeaterModel CalcChillerIPLV CalcChillerModel CalcClearRoof CalcCoilUAbyEffectNTU CalcColdestSetPoint CalcComplexWindowOverlap CalcComplexWindowThermal CalcCompSuctionTempResidual CalcCondEntSetPoint CalcConnectionsDrainTemp CalcConnectionsFlowRates CalcConnectionsHeatRecovery CalcConstCOPChillerModel CalcConvCoeffAbsPlateAndWater CalcConvCoeffBetweenPlates CalcCoolBeam CalcCoolTower CalcCoordinateTransformation CalcCoPlanarNess CalcCostEstimate CalcCTGeneratorModel CalcDayltgCoefficients CalcDayltgCoeffsMapPoints CalcDayltgCoeffsRefMapPoints CalcDayltgCoeffsRefPoints CalcDesiccantBalancedHeatExch CalcDesignSpecificationOutdoorAir CalcDesuperheaterHeatingCoil CalcDesuperheaterWaterHeater CalcDetailedHcInForDVModel CalcDetailedSystem CalcDetailedTransSystem CalcDetailFlatFinCoolingCoil CalcDetIceStorLMTDstar CalcDiffTSysAvailMgr CalcDirectAir CalcDirectEvapCooler CalcDirectResearchSpecialEvapCooler CalcDoe2DXCoil CalcDOE2Leeward CalcDOE2Windward CalcDryFinEffCoef CalcDryIndirectEvapCooler CalcDuct CalcDXCoilStandardRating CalcDXHeatingCoil CalcEarthTube CalcEcoRoof CalcEffectiveness CalcEffectiveSHR CalcEffectiveSHR CalcEffectiveSHR CalcEffectiveSHR CalcElecSteamHumidifier CalcElectricBaseboard CalcElectricChillerHeatRecovery CalcElectricChillerModel CalcElectricEIRChillerModel CalcElectricHeatingCoil CalcEmmelRoof CalcEmmelVertical CalcEngineChillerHeatRec CalcEngineDrivenChillerModel CalcEQLOpticalProperty CalcEQLWindowOpticalProperty CalcEQLWindowSHGCAndTransNormal CalcEQLWindowStandardRatings CalcEQLWindowUvalue CalcEquipmentDrainTemp CalcEquipmentFlowRates CalcExhaustAbsorberChillerModel CalcExhaustAbsorberHeaterModel CalcExteriorVentedCavity CalcFisherPedersenCeilDiffuserCeiling CalcFisherPedersenCeilDiffuserFloor CalcFisherPedersenCeilDiffuserWalls CalcFluidHeatExchanger CalcFohannoPolidoriVerticalWall CalcFollowOATempSetPoint CalcFollowSysNodeTempSetPoint CalcFourPipeIndUnit CalcFrameDividerShadow CalcFuelCellAuxHeater CalcFuelCellGeneratorModel CalcFuelCellGenHeatRecovery CalcFurnaceOutput CalcFurnaceResidual CalcGasAbsorberChillerModel CalcGasAbsorberHeaterModel CalcGasCooler CalcGasHeatingCoil CalcGenericDesiccantDehumidifier CalcGoldsteinNovoselacCeilingDiffuserFloor CalcGoldsteinNovoselacCeilingDiffuserWall CalcGoldsteinNovoselacCeilingDiffuserWindow CalcGroundTempSetPoint CalcGroundwaterWell CalcGshpModel CalcGshpModel CalcGTChillerModel CalcHeatBalanceAir CalcHeatBalanceInsideSurf CalcHeatBalanceInsideSurf CalcHeatBalanceOutsideSurf CalcHeatBalanceOutsideSurf CalcHeatBalFiniteDiff CalcHeatBalHAMT CalcHeatPumpWaterHeater CalcHeatTransCoeffAndCoverTemp CalcHfExteriorSparrow CalcHighTempRadiantSystem CalcHighTempRadiantSystemSP CalcHiTurnOffSysAvailMgr CalcHiTurnOnSysAvailMgr CalcHnASHRAETARPExterior CalcHPCoolingSimple CalcHPHeatingSimple CalcHPWHDXCoil CalcHWBaseboard CalcHXAssistedCoolingCoil CalcHXEffectTerm CalcHybridVentSysAvailMgr CalcIBesselFunc CalcICEngineGeneratorModel CalcICEngineGenHeatRecovery CalcIceStorageCapacity CalcIceStorageCharge CalcIceStorageDischarge CalcIceStorageDormant CalcICSSolarCollector CalcIdealCondEntSetPoint CalcIfSetpointMet CalcIndirectAbsorberModel CalcIndirectResearchSpecialEvapCooler CalcInteriorRadExchange CalcInteriorSolarDistribution CalcInteriorSolarOverlaps CalcInteriorWinTransDifSolInitialDistribution CalcISO15099WindowIntConvCoeff CalcKaradagChilledCeiling CalcKBesselFunc CalcKhalifaEq3WallAwayFromHeat CalcKhalifaEq4CeilingAwayFromHeat CalcKhalifaEq5WallsNearHeat CalcKhalifaEq6NonHeatedWalls CalcKhalifaEq7Ceiling CalcLoadCenterThermalLoad CalcLoTurnOffSysAvailMgr CalcLoTurnOnSysAvailMgr CalcLowTempCFloRadiantSystem CalcLowTempCFloRadSysComps CalcLowTempElecRadiantSystem CalcLowTempHydrRadiantSystem CalcLowTempHydrRadSysComps CalcMatrixInverse CalcMcAdams CalcMerkelVariableSpeedTower CalcMicroCHPNoNormalizeGeneratorModel CalcMinIntWinSolidAngs CalcMitchell CalcMixedAirSetPoint CalcMoistureBalanceEMPD CalcMoreNodeInfo CalcMoWITTLeeward CalcMoWITTWindward CalcMSHeatPump CalcMTGeneratorModel CalcMultiSpeedDXCoil CalcMultiSpeedDXCoilCooling CalcMultiSpeedDXCoilHeating CalcMultiStageElectricHeatingCoil CalcMultiStageGasHeatingCoil CalcMultiZoneAverageCoolingSetPoint CalcMultiZoneAverageHeatingSetPoint CalcMultiZoneAverageMaxHumSetPoint CalcMultiZoneAverageMinHumSetPoint CalcMultiZoneMaxHumSetPoint CalcMultiZoneMinHumSetPoint CalcMundtModel CalcNCycSysAvailMgr CalcNewZoneHeatCoolFlowRates CalcNewZoneHeatOnlyFlowRates CalcNodeMassFlows CalcNominalWindowCond CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNusselt CalcNusseltJurges CalcNVentSysAvailMgr CalcOAController CalcOAMassFlow CalcOAMassFlow CalcOAMixer CalcOAOnlyMassFlow CalcOAPretreatSetPoint CalcOAUnitCoilComps CalcObstrMultiplier CalcOptStartSysAvailMgr CalcOtherSideDemand CalcOutdoorAirUnit CalcOutsideAirSetPoint CalcOutsideSurfTemp CalcParallelPIU CalcPassiveExteriorBaffleGap CalcPassiveSystem CalcPassiveTranspiredCollector CalcPerSolarBeam CalcPipeHeatTransCoef CalcPipesHeatTransfer CalcPipeTransBeam CalcPlantValves CalcPollution CalcPolyhedronVolume CalcPolynomCoef CalcPondGroundHeatExchanger CalcPredictedHumidityRatio CalcPredictedSystemLoad CalcPTUnit CalcPumps CalcPurchAirLoads CalcPurchAirMinOAMassFlow CalcPurchAirMixedAir CalcPVTcollectors CalcQiceChargeMaxByChiller CalcQiceChargeMaxByITS CalcQiceDischageMax CalcRABFlowSetPoint CalcRackSystem CalcRadSysHXEffectTerm CalcRadTemp CalcRainCollector CalcReformEIRChillerModel CalcResearchSpecialPartLoad CalcReturnAirPath CalcRfFlrCoordinateTransformation CalcSandiaPV CalcSatVapPressFromTemp CalcSchedOffSysAvailMgr CalcSchedOnSysAvailMgr CalcSchedSysAvailMgr CalcScheduledDualSetPoint CalcScheduledSetPoint CalcScreenTransmittance CalcScriptF CalcSeriesPIU CalcSetpointTempTarget CalcSHRUserDefinedCurves CalcSimpleController CalcSimpleHeatingCoil CalcSimplePV CalcSingleSpeedEvapFluidCooler CalcSingleSpeedTower CalcSingZoneClSetPoint CalcSingZoneHtSetPoint CalcSingZoneMaxHumSetPoint CalcSingZoneMinHumSetPoint CalcSingZoneRhSetPoint CalcSkySolDiffuseReflFactors CalcSolarCollector CalcSolarFlux CalcSolidDesiccantDehumidifier CalcSourceFlux CalcSourceTempCoefficents CalcSparrowLeeward CalcSparrowWindward CalcSpecialDayTypes CalcStandAloneERV CalcStandardRatings CalcStaticProperties CalcSteamAirCoil CalcSteamBaseboard CalcSurfaceCentroid CalcSurfaceGroundHeatExchanger CalcSystemEnergyUse CalcSZOneStageCoolingSetPt CalcSZOneStageHeatingSetPt CalcTankTemp CalcTDDTransSolAniso CalcTDDTransSolHorizon CalcTDDTransSolIso CalcTempDistModel CalcTempIntegral CalcTESCoilChargeOnlyMode CalcTESCoilCoolingAndChargeMode CalcTESCoilCoolingAndDischargeMode CalcTESCoilCoolingOnlyMode CalcTESCoilDischargeOnlyMode CalcTESCoilOffMode CalcTESIceStorageTank CalcTESWaterStorageTank CalcThermalChimney CalcThermalComfortAdaptiveASH55 CalcThermalComfortAdaptiveCEN15251 CalcThermalComfortFanger CalcThermalComfortKSU CalcThermalComfortPierce CalcThermalComfortSimpleASH55 CalcTimeNeeded CalcTopFluxCoefficents CalcTopSurfTemp CalcTotalFLux CalcTotCapSHR CalcTotCapSHR_VSWSHP CalcTransAbsorProduct CalcTransRefAbsOfCover CalcTRNSYSPV CalcTrombeWallIntConvCoeff CalcTwoSpeedDXCoilIEERResidual CalcTwoSpeedDXCoilStandardRating CalcTwoSpeedEvapFluidCooler CalcTwoSpeedTower CalcUAIce CalcUCSDCV CalcUCSDDV CalcUCSDUE CalcUCSDUI CalculateAirChillerSets CalculateBasisLength CalculateCase CalculateCoil CalculateCompressors CalculateCondensers CalculateCTFs CalculateDailySolarCoeffs CalculateDayOfWeek CalculateEpsFromNTUandZ CalculateExponentialMatrix CalculateFuncResults CalculateGammas CalculateInverseMatrix CalculateMoodyFrictionFactor CalculateNTUfromEpsAndZ CalculatePollution CalculateSecondary CalculateSubcoolers CalculateSunDirectionCosines CalculateTransCompressors CalculateWalkIn CalculateWaterUseage CalculateWaterUseage CalculateWindowBeamProperties CalculateZoneMRT CalculateZoneVolume CalcUnitaryCoolingSystem CalcUnitaryHeatingSystem CalcUnitarySuppHeatingSystem CalcUnitarySuppSystemtoSP CalcUnitarySystemLoadResidual CalcUnitarySystemToLoad CalcUnitHeater CalcUnitHeaterComponents CalcUnitVentilator CalcUnitVentilatorComponents CalcUnmetPlantDemand CalcUpdateHeatRecovery CalcUpdateHeatRecovery CalcUserDefinedInsideHcModel CalcUserDefinedOutsideHcModel CalcVariableSpeedTower CalcVarSpeedCoilCooling CalcVarSpeedCoilHeating CalcVarSpeedHeatPump CalcVarSpeedHeatPump CalcVAVVS CalcVentilatedSlab CalcVentilatedSlabComps CalcVentilatedSlabRadComps CalcVentSlabHXEffectTerm CalcVerticalGroundHeatExchanger CalcViewFactorToShelf CalcVRF CalcVRFCondenser CalcVRFCoolingCoil CalcVSTowerApproach CalcWallCoordinateTransformation CalcWaltonStableHorizontalOrTilt CalcWaltonUnstableHorizontalOrTilt CalcWarmestSetPoint CalcWarmestSetPointTempFlow CalcWaterMainsTemp CalcWaterSource CalcWaterStorageTank CalcWaterThermalTankMixed CalcWaterThermalTankStratified CalcWaterThermalTankZoneGains CalcWaterToAirHeatpump CalcWatertoAirHPCooling CalcWatertoAirHPHeating CalcWaterToAirResidual CalcWatertoWaterHPCooling CalcWatertoWaterHPHeating CalcWaterUseZoneGains CalcWetIndirectEvapCooler CalcWindowACOutput CalcWindowBlindProperties CalcWindowHeatBalance CalcWindowProfileAngles CalcWindowScreenProperties CalcWindowStaticProperties CalcWindPressure CalcWindPressureCoeffs CalcWindTurbine CalcWinFrameAndDividerTemps CalcWinTransDifSolInitialDistribution CalcWrapperModel CalcZoneAirComfortSetpoints CalcZoneAirTempSetpoints CalcZoneComponentLoadSums CalcZoneDehumidifier CalcZoneEvaporativeCoolerUnit CalcZoneLeavingConditions CalcZoneMassBalance CalcZonePipesHeatGain CalcZoneSums CartesianPipeCellInformation_ctor CellType_IsFieldCell CFSHasControlledShade CFSNGlz CFSRefPointPosFactor CFSRefPointSolidAngle CFSShadeAndBeamInitialization CFSUFactor cGetCoilAirOutletNode cGetCoilSteamInletNode cGetCoilSteamOutletNode CharPreDefTableEntry CheckActuatorNode CheckAndAddAirNodeNumber CheckAndFixCFSLayer CheckAndReadCustomSprectrumData CheckAndReadFaults CheckAndSetConstructionProperties CheckBracketRoundOff CheckBranchForOASys CheckCachedIPErrors CheckCFSStates CheckCoilWaterInletNode CheckControllerListOrder CheckControllerLists CheckConvexity CheckCostEstimateInput CheckCreatedZoneItemName CheckCurveLimitsForIPLV CheckCurveLimitsForStandardRatings CheckDayScheduleValueMinMax CheckDXCoolingCoilInOASysExists CheckFDSurfaceTempLimits CheckFFSchedule CheckFluidPropertyName CheckForActualFileName CheckForBalancedFlow CheckForControllerWaterCoil CheckForGeometricTransform CheckForGeometricTransform CheckForMisMatchedEnvironmentSpecifications CheckForOutOfRangeTempResult CheckForOutOfRangeTemps CheckForRequestedReporting CheckForRunawayPlantTemps CheckForSensorAndSetpointNode CheckGasCoefs CheckHeatingCoilSchedule CheckHXAssistedCoolingCoilSchedule CheckIFAnyEMS CheckIFAnyIdealCondEntSetPoint CheckIfAnyPlant CheckIfNodeSetpointManagedByEMS CheckIncrementRoundOff CheckInternalConsistency CheckLightsReplaceableMinMaxForZone CheckLocationValidity CheckLoopExitNode CheckLowerUpperBracket CheckMarkedNodes CheckMaxActiveController CheckMaxConstraint CheckMicroCHPThermalBalance CheckMinActiveController CheckMinConstraint checkMinimumMonthlyCharge CheckMinMaxCurveBoundaries CheckMinMaxRange CheckModelBoundOutput_HumRat CheckModelBoundOutput_Temp CheckModelBounds CheckModelBoundsHumRatEq CheckModelBoundsRH_HumRatEq CheckModelBoundsRH_TempEq CheckModelBoundsTempEq CheckNodeConnections CheckNodeSetPoint CheckNonSingularity CheckOAControllerName CheckOutAirNodeNumber CheckPlantConvergence CheckPlantMixerSplitterConsistency CheckPlantOnAbort CheckPollutionMeterReporting CheckRefrigerationInput CheckReportVariable CheckRootFinderCandidate CheckRootFinderConvergence CheckScheduledSurfaceGains CheckScheduleValue CheckScheduleValueMinMax Checksetpoints CheckSimpleController CheckSlope CheckSteamCoilSchedule CheckSubSurfaceMiscellaneous CheckSysSizing CheckSystemBranchFlow CheckTDDsAndLightShelvesInDaylitZones CheckThisAirSystemForSizing CheckThisZoneForSizing CheckThreading CheckUniqueNodes CheckUnitarySysCoilInOASysExists CheckUsedConstructions CheckValidSimulationObjects CheckWarmupConvergence CheckWaterCoilSchedule CheckWeatherFileValidity CheckWindowShadingControlFrameDivider CheckZoneEquipmentList CheckZoneSizing CHKBKS CHKGSS CHKSBS CLIP CLIPPOLY CloseDFSFile CloseMiscOpenFiles CloseMoistureBalanceEMPD CloseOutOpenFiles CloseOutputFiles CloseOutputTabularFile CloseReportIllumMaps CloseSocket CloseWeatherFile CoilAreaFracIter CoilCompletelyDry CoilCompletelyWet CoilOutletStreamCondition CoilPartWetPartDry COMMAND_ARGUMENT_COUNT CompactObjectsCheck CompareTwoVectors ComplexFenestrationLuminances ComputeDelayedComponents ComputeDifSolExcZonesWIZWindows ComputeIntSolarAbsorpFactors ComputeIntSWAbsorpFactors ComputeIntThermalAbsorpFactors ComputeLifeCycleCostAndReport ComputeLoadComponentDecayCurve ComputeNominalUwithConvCoeffs ComputePresentValue ComputeTariff ComputeTaxAndDepreciation ComputeWinShadeAbsorpFactors CondOutTempResidual ConstructBasis ControlCBVAVOutput ControlCompOutput ControlCompOutput ControlCoolBeam ControlCoolingSystem ControlCycWindACOutput ControlDesiccantDehumidifier ControlDXHeatingSystem ControlDXSystem ControlFluidHeatExchanger ControlHeatingSystem ControlHumidifier ControlMSHPOutput ControlPTUnitOutput ControlPVTcollector ControlReformEIRChillerModel ControlSuppHeatSystem ControlUnitarySystemOutput ControlUnitarySystemtoLoad ControlUnitarySystemtoSP ControlVRF ControlVSEvapUnitToMeetLoad ControlVSHPOutput ControlVSHPOutput ConvectionFactor ConvertCasetoLower ConvertCasetoUpper ConvertIP ConvertIPdelta ConvertToElementTag ConvertToEscaped CoolBeamResidual CoolingCoil CoolWaterHumRatResidual CoolWaterTempResidual CoolWatertoAirHPHumRatResidual CoolWatertoAirHPTempResidual CorrectZoneAirTemp CorrectZoneContaminants CorrectZoneHumRat CostInfoOut CPCW CPHW CreateBoundaryList CreateBoundaryListCount CreateCategoryNativeVariables CreateCellArray CreateCurrentDateTimeString CreateDefaultComputation CreateEnergyReportStructure CreateFCfactorConstructions CreateHVACStepFullString CreateHVACTimeIntervalString CreateHVACTimeString CreateNewellAreaVector CreateNewellSurfaceNormalVector CreatePartitionCenterList CreatePartitionRegionList CreatePredefinedMonthlyReports CreateRegionList CreateRegionListCount CreateShadedWindowConstruction CreateSQLiteConstructionsTable CreateSQLiteConstructionsTable CreateSQLiteDatabase CreateSQLiteDatabase CreateSQLiteDaylightMap CreateSQLiteDaylightMap CreateSQLiteDaylightMapTitle CreateSQLiteDaylightMapTitle CreateSQLiteEnvironmentPeriodRecord CreateSQLiteEnvironmentPeriodRecord CreateSQLiteErrorRecord CreateSQLiteErrorRecord CreateSQLiteInfiltrationTable CreateSQLiteInfiltrationTable CreateSQLiteMaterialsTable CreateSQLiteMaterialsTable CreateSQLiteMeterDictionaryRecord CreateSQLiteMeterDictionaryRecord CreateSQLiteMeterRecord CreateSQLiteMeterRecord CreateSQLiteNominalBaseboardHeatTable CreateSQLiteNominalBaseboardHeatTable CreateSQLiteNominalElectricEquipmentTable CreateSQLiteNominalElectricEquipmentTable CreateSQLiteNominalGasEquipmentTable CreateSQLiteNominalGasEquipmentTable CreateSQLiteNominalHotWaterEquipmentTable CreateSQLiteNominalHotWaterEquipmentTable CreateSQLiteNominalLightingTable CreateSQLiteNominalLightingTable CreateSQLiteNominalOtherEquipmentTable CreateSQLiteNominalOtherEquipmentTable CreateSQLiteNominalPeopleTable CreateSQLiteNominalPeopleTable CreateSQLiteNominalSteamEquipmentTable CreateSQLiteNominalSteamEquipmentTable CreateSQLiteReportVariableDataRecord CreateSQLiteReportVariableDataRecord CreateSQLiteReportVariableDictionaryRecord CreateSQLiteReportVariableDictionaryRecord CreateSQLiteRoomAirModelTable CreateSQLiteRoomAirModelTable CreateSQLiteSchedulesTable CreateSQLiteSimulationsRecord CreateSQLiteSimulationsRecord CreateSQLiteStringTableRecord CreateSQLiteSurfacesTable CreateSQLiteSurfacesTable CreateSQLiteTabularDataRecords CreateSQLiteTabularDataRecords CreateSQLiteTimeIndexRecord CreateSQLiteTimeIndexRecord CreateSQLiteVentilationTable CreateSQLiteVentilationTable CreateSQLiteZoneGroupTable CreateSQLiteZoneGroupTable CreateSQLiteZoneListTable CreateSQLiteZoneListTable CreateSQLiteZoneTable CreateSQLiteZoneTable CreateStormWindowConstructions CreateSysTimeIntervalString CreateTCConstructions CreateTimeIntervalString CreateTimeString CreatExtBooundCondName CreateZoneExtendedOutput CreateZoneExtendedOutput CrossProduct CrossProduct cSurfaceClass CTRANS CurveValue DateToString DateToStringWithMonth DaylghtAltAndAzimuth DayltgAveInteriorReflectance DayltgClosestObstruction DayltgCrossProduct DayltgCurrentExtHorizIllum DayltgDirectIllumComplexFenestration DayltgDirectSunDiskComplexFenestration DayltgElecLightingControl DayltgExtHorizIllum DayltgGlare DayltgGlarePositionFactor DayltgGlareWithIntWins DayltgHitBetWinObstruction DayltgHitInteriorObstruction DayltgHitObstruction DayltgInteriorIllum DayltgInteriorMapIllum DayltgInteriorTDDIllum DayltgInterReflectedIllum DayltgInterReflectedIllumComplexFenestration DayltgInterReflIllFrIntWins DayltgLuminousEfficacy DayltgPierceSurface DayltgSetupAdjZoneListsAndPointers DayltgSkyLuminance DayltgSurfaceLumFromSun dCheckScheduleValueMinMax1 dCheckScheduleValueMinMax2 DeallocateLoadComponentArrays DebugRootFinder DecodeHHMMField DecodeMonDayHrMin DeflectionTemperatures DeflectionWidths DegradF DElightDaylightCoefficients DElightDaylightCoefficients DElightElecLtgCtrl DElightElecLtgCtrl DElightFreeMemory DElightFreeMemory DElightInputGenerator DElightInputGenerator DElightOutputGenerator DElightOutputGenerator DensityCFSFillGas Depth DERIV DetailsForSurfaces DetectOscillatingZoneTemp DetermineAzimuthAndTilt DetermineBranchFlowRequest DetermineBuildingFloorArea DetermineDateTokens DetermineFrequency DetermineIndexGroupFromMeterGroup DetermineIndexGroupKeyFromMeterName DetermineMaxBackSurfaces DetermineMeterIPUnits DetermineMinuteForReporting DeterminePolygonOverlap DetermineShadowingCombinations DetermineSunUpDown DevelopMesh DiffuseAverage DiffuseAverageProfAngGnd DiffuseAverageProfAngSky DisplayMaterialRoughness DisplayNumberandString DisplaySimDaysProgress DisplayString distance DistributeBBElecRadGains DistributeBBRadGains DistributeBBSteamRadGains DistributeHTRadGains DistributePlantLoad DistributePressureOnBranch DistributeTDDAbsorbedSolar DistributeUserDefinedPlantLoad DL_RES_r2 DLAG DOE2DXCoilHumRatResidual DOE2DXCoilHumRatResidual DOE2DXCoilResidual DOE2DXCoilResidual DOE2DXCoilResidual DoEndOfIterationOperations DomainRectangle_Contains DOMakeUPPERCase DoOneTimeInitializations DOSameString DoShadeControl DoStartOfTimeStepInitializations DownInterpolate4HistoryValues DumpAirLoopStatistics DumpCurrentLineBuffer DUMPVD DUMPVR DXCoilCyclingHumRatResidual DXCoilCyclingHumRatResidual DXCoilCyclingResidual DXCoilCyclingResidual DXCoilVarSpeedHumRatResidual DXCoilVarSpeedHumRatResidual DXCoilVarSpeedResidual DXCoilVarSpeedResidual DXFOut DXFOutLines DXFOutWireFrame DXHeatingCoilResidual DXHeatingCoilResidual DXHeatingCoilResidual DynamicClothingModel DynamicExtConvSurfaceClassification DynamicIntConvSurfaceClassification EchoOutActuatorKeyChoices EchoOutInternalVariableChoices EffectiveEPSLB EffectiveEPSLF EIRChillerHeatRecovery EN673ISO10292 EncodeMonDayHrMin EndEnergyPlus EndUniqueNodeCheck EnthalpyResidual epElapsedTime epGetTimeUsed epGetTimeUsedperCall epStartTime epStopTime epSummaryTimes eptime EQLWindowInsideEffectiveEmiss EQLWindowOutsideEffectiveEmiss EQLWindowSurfaceHeatBalance EquationsSolver ERF EstimateHEXSurfaceArea EvalInsideMovableInsulation EvalOutsideMovableInsulation EvaluateAdiabaticSurfaceTemperature EvaluateBasementCellTemperature EvaluateCellNeighborDirections evaluateChargeBlock evaluateChargeSimple EvaluateExpression EvaluateExtHcModels EvaluateFarfieldBoundaryTemperature EvaluateFarfieldCharacteristics EvaluateFieldCellTemperature EvaluateGroundSurfaceTemperature EvaluateIntHcModels EvaluateLoopSetPointLoad EvaluateNeighborCharacteristics evaluateQualify evaluateRatchet EvaluateSoilRhoCp EvaluateStack EvolveParaUCSDCV ExitCalcController ExpandComplexState ExpressAsCashFlows ExtendObjectDefinition ExteriorBCEqns ExternalInterfaceExchangeVariables ExternalInterfaceInitializeErlVariable ExternalInterfaceSetErlVariable ExternalInterfaceSetSchedule ExtOrIntShadeNaturalFlow Fabric_EstimateDiffuseProps FACSKY FalsePositionMethod FEQX FI FigureACAncillaries FigureAirEnthalpy FigureAirHeatCap FigureAuxilHeatGasHeatCap FigureBeamSolDiffuseReflFactors FigureBeamSolSpecularReflFactors FigureConstGradPattern FigureDayltgCoeffsAtPointsForSunPosition FigureDayltgCoeffsAtPointsForWindowElements FigureDayltgCoeffsAtPointsSetupForWindow FigureElectricalStorageZoneGains FigureFuelCellZoneGains FigureFuelEnthalpy FigureFuelHeatCap FigureGaseousWaterEnthalpy FigureHeightPattern FigureHXleavingGasHeatCap FigureInverterZoneGains FigureLHVofFuel FigureLiquidWaterEnthalpy FigureLiquidWaterHeatCap FigureMapPointDayltgFactorsToAddIllums FigureMicroCHPZoneGains FigureNDheightInZone FigurePowerConditioningLosses FigureProductGasesEnthalpy FigureProductGasHeatCap FigureRefPointDayltgFactorsToAddIllums FigureRefrigerationZoneGains FigureSolarBeamAtTimestep FigureSunCosines FigureSurfMapPattern FigureTDDZoneGains FigureTransformerZoneGains FigureTransientConstraints FigureTwoGradInterpPattern FILJAC FillBasisElement FillDefaultsSWP FillRemainingPredefinedEntries FillWeatherPredefinedEntries film filmg filmi filmPillar FILSKY FinalizeCFS FinalizeCFSLAYER FinalRateCoils FindAirLoopBranchConnection FindAirPlantCondenserLoopFromBranchList FindAllNumbersinList FindArrayIndex FindCompSPInput FindCompSPLoad FindCondenserLoopBranchConnection FindControlledZoneIndexFromSystemNodeNumberForZone FindDeltaTempRangeInput FindDemandSideMatch FindEMSVariable FindFirstLastPtr FindFirstRecord FindGlycol FindHXDemandSideLoopFlow FindInBasis FindItem FindIteminList FindIteminSortedList FindItemInVariableList FindLoopSideInCallingOrder FindNextRecord FindNonSpace FindNumberinList FindOAMixerMatchForOASystem FindPlantLoopBranchConnection FindRangeBasedOrUncontrolledInput FindRangeVariable FindRefrigerant FindRootSimpleController FindStratifiedTankSensedTemp FindTariffIndex FindTDDPipe FindUnitNumber FinishDebugOutputFiles FixViewFactors FluidCellInformation_ctor FM_BEAM FM_DIFF FM_F FNU forcedventilation FourPipeInductionUnitHasMixer FourPipeIUCoolingResidual FourPipeIUHeatingResidual FRA FrostControl FrostControlSetPointLimit FrostControlSetPointLimit FuelCellProductGasEnthResidual FUN FuncDetermineCoolantWaterExitTemp FuncDetermineCWMdotForInternalFlowControl FuncDetermineEngineTemp FV GasElecHeatingCoilResidual GASSES90 GassesLow GatherBEPSResultsForTimestep GatherBinResultsForTimestep GatherComponentLoadsHVAC GatherComponentLoadsIntGain GatherComponentLoadsSurfAbsFact GatherComponentLoadsSurface GatherForEconomics GatherForPredefinedReport GatherHeatGainReport GatherMonthlyResultsForTimestep GatherPeakDemandForTimestep GatherSourceEnergyEndUseResultsForTimestep GaussElimination generate_ears GenerateDElightDaylightCoefficients GenerateDElightDaylightCoefficients GeneratorPowerOutput GenericCrack GenOutputVariablesAuditReport Get2DMatrix Get2DMatrixDimensions GET_COMMAND GET_COMMAND_ARGUMENT Get_Environment_Variable GetActualDXCoilIndex GetAirBranchIndex GetAirFlowFlag GetAirflowNetworkInput GetAirHeatBalanceInput GetAirLoopAvailabilityManager GetAirModelDatas GetAirNodeData GetAirPathData GetAngleFactorList GetATMixer GetATMixerOutNode GetATMixerPriNode GetATMixers GetATMixerSecNode GetAttShdSurfaceData GetAverageTempByType GetBaseboardInput GetBaseboardInput GetBasementFloorHeatFlux GetBasementWallHeatFlux GetBLASTAbsorberInput GetBoilerInput GetBoilerInput GetBranchData GetBranchFanTypeName GetBranchFlow GetBranchInput GetBranchList GetBranchListInput GetBuildingData GetCBVAV GetCellWidths GetCellWidthsCount GetChildrenData GetChillerheaterInput GetCoilAirFlowRate GetCoilAirFlowRateVariableSpeed GetCoilAirInletNode GetCoilAirOutletNode GetCoilAvailScheduleIndex GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacityByIndexType GetCoilCapacityVariableSpeed GetCoilCondenserInletNode GetCoilControlNodeNum GetCoilGroupTypeNum GetCoilIndex GetCoilIndex GetCoilIndex GetCoilIndexVariableSpeed GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNodeVariableSpeed GetCoilMaxSteamFlowRate GetCoilMaxWaterFlowRate GetCoilMaxWaterFlowRate GetCoilMaxWaterFlowRate GetCoilObjectTypeNum GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNodeVariableSpeed GetCoilSteamInletNode GetCoilSteamOutletNode GetCoilTypeNum GetCoilWaterInletNode GetCoilWaterInletNode GetCoilWaterOutletNode GetColumnUsingTabs GetComfortSetpoints GetComponentData GetCondFDInput GetConductivityGlycol GetConnectorList GetConnectorListInput GetConstCOPChillerInput GetConstructData GetControlledZoneIndex GetControllerActuatorNodeNum GetControllerInput GetCoolBeams GetCoolingCoilTypeNameAndIndex GetCooltower GetCostEstimateInput GetCrossVentData GetCTGeneratorInput GetCTGeneratorResults GetCurrentHVACTime GetCurrentMeterValue GetCurrentScheduleValue GetCurveCheck GetCurveIndex GetCurveInput GetCurveMinMaxValues GetCurveName GetCurveObjectTypeNum GetCurveType GetCustomMeterInput GetDaylightingParametersDetaild GetDaylightingParametersInput GetDayScheduleIndex GetDemandManagerInput GetDemandManagerListInput GetDensityGlycol GetDesiccantDehumidifierInput GetDesignDayData GetDesignLightingLevelForZone GetDetShdSurfaceData GetDirectAirInput GetDisplacementVentData GetDSTData GetDualDuctInput GetDualDuctOutdoorAirRecircUse GetDuctInput GetDXCoilAirFlow GetDXCoilAvailSchPtr GetDXCoilBypassedFlowFrac GetDXCoilCapFTCurveIndex GetDXCoilIndex GetDXCoilNumberOfSpeeds GetDXCoils GetDXCoolingSystemInput GetDXHeatPumpSystemInput GetEarthTube GetElecReformEIRChillerInput GetElectricBaseboardInput GetElectricChillerInput GetElectricEIRChillerInput GetEMSInput GetEngineDrivenChillerInput GetEnvironmentalImpactFactorInfo GetEvapFluidCoolerInput GetEvapInput GetExhaustAbsorberInput GetExhaustAirInletNode GetExteriorEnergyUseInput GetExtVentedCavityIndex GetExtVentedCavityIndex GetExtVentedCavityTsColl GetExtVentedCavityTsColl GetFanAvailSchPtr GetFanCoilIndex GetFanCoilInletAirNode GetFanCoilMixedAirNode GetFanCoilOutAirNode GetFanCoilReturnAirNode GetFanCoilUnits GetFanCoilZoneInletAirNode GetFanDesignVolumeFlowRate GetFanIndex GetFanIndexForTwoSpeedCoil GetFanInletNode GetFanInput GetFanOutletNode GetFanPower GetFanSpeedRatioCurveIndex GetFanType GetFanVolFlow GetFarfieldTemp GetFirstBranchInletNodeName GetFluidCoolerInput GetFluidDensityTemperatureLimits GetFluidHeatExchangerInput GetFluidPropertiesData GetFluidSpecificHeatTemperatureLimits GetFrameAndDividerData GetFuelCellGeneratorInput GetFuelCellGeneratorResults GetFuelFactorInfo GetFurnaceInput GetGasAbsorberInput GetGeneratorFuelSupplyInput GetGeometryParameters GetGlycolNameByIndex GetGroundheatExchangerInput GetGroundReflectances GetGroundTemps GetGshpInput GetGshpInput GetGTChillerInput GetHeatBalanceInput GetHeatBalHAMTInput GetHeatExchangerObjectTypeNum GetHeatingCoilIndex GetHeatingCoilInput GetHeatingCoilNumberOfStages GetHeatingCoilPLFCurveIndex GetHeatingCoilTypeNum GetHeatReclaimSourceIndex GetHeatRecoveryInput GetHighTempRadiantSystem GetHPCoolingCoilIndex GetHTSubSurfaceData GetHTSurfaceData GetHTSurfExtVentedCavityData GetHumidifierInput GetHVACSingleDuctSysIndex GetHWBaseboardInput GetHXAssistedCoolingCoilInput GetHXCoilAirFlowRate GetHXCoilType GetHXCoilTypeAndName GetHXDXCoilIndex GetHXDXCoilName GetHybridVentilationControlStatus GetHybridVentilationInputs GetICEGeneratorResults GetICEngineGeneratorInput GetIceStorageInput GetIDFRecordsStats GetIndirectAbsorberInput GetIndUnits GetInputEconomicsChargeBlock GetInputEconomicsChargeSimple GetInputEconomicsComputation GetInputEconomicsCurrencyType GetInputEconomicsQualify GetInputEconomicsRatchet GetInputEconomicsTariff GetInputEconomicsVariable GetInputForLifeCycleCost GetInputFuelAndPollutionFactors GetInputLifeCycleCostNonrecurringCost GetInputLifeCycleCostParameters GetInputLifeCycleCostRecurringCosts GetInputLifeCycleCostUseAdjustment GetInputLifeCycleCostUsePriceEscalation GetInputTabularMonthly GetInputTabularPredefined GetInputTabularStyle GetInputTabularTimeBins GetInputViewFactors GetInputViewFactorsbyName GetInputZoneEvaporativeCoolerUnit GetInstantMeterValue GetInternalBranchData GetInternalHeatGainsInput GetInternalVariableValue GetInternalVariableValue GetInternalVariableValueExternalInterface GetInternalVariableValueExternalInterface GetInterpolatedSatProp GetInterpValue GetIntMassSurfaceData GetLastBranchOutletNodeName GetLastWord GetLightWellData GetListOfObjectsInIDD GetListofSectionsinInput GetLocationInfo GetLoopMixer GetLoopSidePumpIndex GetLoopSplitter GetLowTempRadiantSystem GetMaterialData GetMatrixInput getMaxAndSum GetMeteredVariables GetMeterIndex GetMeterResourceType GetMicroCHPGeneratorInput GetMicroCHPGeneratorResults GetMinOATCompressor GetMixerInput GetMixerInput GetMoistureBalanceEMPDInput GetMonthlyCostForResource GetMovableInsulationData GetMSHeatPumpInput GetMTGeneratorExhaustNode GetMTGeneratorInput GetMTGeneratorResults GetMundtData GetNewUnitNumber GetNextEnvironment GetNodeConnectionType GetNodeList GetNodeListsInput GetNodeNums GetNTUforCrossFlowBothUnmixed GetNumberOfSchedules GetNumberOfSurfaceLists GetNumberOfSurfListVentSlab GetNumChildren GetNumMeteredVariables GetNumOAControllers GetNumOAMixers GetNumOASystems GetNumObjectsFound GetNumObjectsInIDD GetNumRangeCheckErrorsFound GetNumSectionsFound GetNumSectionsinInput GetNumSegmentsForHorizontalTrenches GetNumSplitterMixerInConntrList GetOACompListNumber GetOACompName GetOACompType GetOACompTypeNum GetOAControllerInputs GetOAMixerIndex GetOAMixerInletNodeNumber GetOAMixerInputs GetOAMixerMixedNodeNumber GetOAMixerNodeNumbers GetOAMixerReliefNodeNumber GetOAMixerReturnNodeNumber GetOARequirements GetOASysControllerListIndex GetOASysNumCoolingCoils GetOASysNumHeatingCoils GetOASysNumSimpControllers GetOASystemNumber GetObjectDefInIDD GetObjectDefMaxArgs GetObjectItem GetObjectItemfromFile GetObjectItemNum GetOnlySingleNode GetOperationSchemeInput GetOSCData GetOSCMData GetOutAirNodesInput GetOutdoorAirUnitInputs GetOutdoorAirUnitOutAirNode GetOutdoorAirUnitReturnAirNode GetOutdoorAirUnitZoneInletNode GetOutsideAirSysInputs GetOutsideEnergySourcesInput GetParentData GetPipeInput GetPipesHeatTransfer GetPipingSystemsInput GetPIUs GetPlantAvailabilityManager GetPlantInput GetPlantLoopData GetPlantOperationInput GetPlantProfileInput GetPlantSizingInput GetPlantValvesInput GetPollutionFactorInput GetPondGroundHeatExchanger GetPowerManagerInput GetPressureCurveTypeAndIndex GetPressureSystemInput GetPreviousHVACTime GetProjectControlData GetProjectData GetPTUnit GetPTUnitMixedAirNode GetPTUnitOutAirNode GetPTUnitReturnAirNode GetPTUnitZoneInletAirNode GetPumpInput GetPurchasedAir GetPurchasedAirMixedAirHumRat GetPurchasedAirMixedAirTemp GetPurchasedAirOutAirMassFlow GetPurchasedAirReturnAirNode GetPurchasedAirZoneInletAirNode GetPVGeneratorResults GetPVInput GetPVTcollectorsInput GetPVTThermalPowerProduction GetQualityRefrig GetRecordLocations GetRectDetShdSurfaceData GetRectSubSurfaces GetRectSurfaces GetRefrigeratedRackIndex GetRefrigerationInput GetReportVariableInput GetRequiredMassFlowRate GetResidCrossFlowBothUnmixed GetResourceTypeChar GetReturnAirNodeForZone GetReturnAirPathInput GetRoomAirModelParameters GetRunPeriodData GetRunPeriodDesignData GetRuntimeLanguageUserInput GetSatDensityRefrig GetSatEnthalpyRefrig GetSatPressureRefrig GetSatSpecificHeatRefrig GetSatTemperatureRefrig GetScheduledSurfaceGains GetScheduleIndex GetScheduleMaxValue GetScheduleMinValue GetScheduleName GetScheduleType GetScheduleValuesForDay GetSecondaryInletNode GetSecondaryOutletNode GetSetPointManagerInputs GetShadingSurfReflectanceData GetShadowingInput GetShelfInput GetSimpleAirModelInputs GetSimpleShdSurfaceData GetSimpleWatertoAirHPInput GetSingleDayScheduleValues GetSiteAtmosphereData GetSizingParams GetSnowGroundRefModifiers GetSolarCollectorInput GetSpecialDayPeriodData GetSpecificHeatGlycol getSpecificUnitDivider getSpecificUnitIndex getSpecificUnitMultiplier GetSplitterInput GetSplitterInput GetSplitterNodeNumbers GetSplitterOutletNumber GetStandAloneERV GetStandAloneERVNodes GetStandAloneERVOutAirNode GetStandAloneERVReturnAirNode GetStandAloneERVZoneInletAirNode GetStandardMeterResourceType GetSteamBaseboardInput GetSteamCoilAvailScheduleIndex GetSteamCoilControlNodeNum GetSteamCoilIndex GetSteamCoilInput GetSTM GetStormWindowData GetSupHeatDensityRefrig GetSupHeatEnthalpyRefrig GetSupHeatPressureRefrig GetSupplyAirFlowRate GetSupplyAirFlowRate GetSupplyAirInletNode GetSupplyInletNode GetSupplyOutletNode GetSurfaceCountForOSCM GetSurfaceData GetSurfaceGroundHeatExchanger GetSurfaceHeatTransferAlgorithmOverrides GetSurfaceIndecesForOSCM GetSurfaceListsInputs GetSurfHBDataForMundtModel GetSurfHBDataForTempDistModel GetSysAvailManagerInputs GetSysAvailManagerListInputs GetSysInput GetSystemNodeNumberForZone GetSystemSizingInput GetTDDInput GetTESCoilIndex GetTESCoilInput GetThermalChimney GetTowerInput GetTranspiredCollectorIndex GetTranspiredCollectorInput GetTypeOfCoil GetUFADZoneData GetUnitarySystemDXCoolingCoilIndex GetUnitarySystemInput GetUnitarySystemOAHeatCoolCoil GetUnitConversion GetUnitHeaterInput GetUnitsString GetUnitSubString GetUnitVentilatorInput GetUnitVentilatorMixedAirNode GetUnitVentilatorOutAirNode GetUnitVentilatorReturnAirNode GetUnitVentilatorZoneInletAirNode GetUserConvectionCoefficients GetUserDefinedComponents GetUserDefinedOpSchemeInput GetUserDefinedPatternData GetUTSCTsColl GetVariableKeyCountandType GetVariableKeyCountandType GetVariableKeys GetVariableKeys GetVariableTypeAndIndex GetVariableUnitsString GetVarSpeedCoilInput GetVentilatedSlabInput GetVertices GetViscosityGlycol GetVRFInput GetVSCoilCondenserInletNode GetVSCoilMinOATCompressor GetVSCoilNumOfSpeeds GetWaterCoilAvailScheduleIndex GetWaterCoilCapacity GetWaterCoilIndex GetWaterCoilInput GetWaterMainsTemperatures GetWaterManagerInput GetWaterSource GetWaterThermalTankInput GetWatertoAirHPInput GetWatertoWaterHPInput GetWaterUseInput GetWeatherProperties GetWeatherStation GetWindowAC GetWindowACMixedAirNode GetWindowACOutAirNode GetWindowACReturnAirNode GetWindowACZoneInletAirNode GetWindowGapAirflowControlData GetWindowGlassSpectralData GetWindowShadingControlData GetWindTurbineInput GetWrapperInput GetWTGeneratorResults GetZoneAirDistribution GetZoneAirLoopEquipment GetZoneAirSetpoints GetZoneAndZoneListNames GetZoneContaminanInputs GetZoneContaminanSetpoints GetZoneData GetZoneDehumidifierInput GetZoneDehumidifierNodeNumber GetZoneEqAvailabilityManager GetZoneEquipment GetZoneEquipmentData GetZoneEquipmentData1 GetZoneInfilAirChangeRate GetZoneLoads GetZonePlenumInput GetZoneSizingInput GLtoAMB GoAhead guess HasFractionalScheduleValue hatter HCInWindowStandardRatings HConvGap HcUCSDCV HcUCSDDV HcUCSDUF HeatingCoilVarSpeedCycResidual HeatingCoilVarSpeedResidual HeatPumpRunFrac HeatPumpRunFrac HeatPumpRunFrac HeatWatertoAirHPTempResidual Height HEMINT HIC_ASHRAE HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterHeatingCoilResidual HRadPar HTRANS HTRANS0 HTRANS1 HWBaseboardUAResidual HXAssistDXCoilResidual HXAssistedCoolCoilHRResidual HXAssistedCoolCoilHRResidual HXAssistedCoolCoilTempResidual HXAssistedCoolCoilTempResidual HXDemandSideLoopFlowResidual HybridVentilationControl IAM iCheckScheduleValue ICSCollectorAnalyticalSoluton iGetCoilAirOutletNode iGetCoilSteamInletNode iGetCoilSteamOutletNode INCLOS incrementEconVar IncrementInstMeterCache incrementSteps incrementTableEntry InitAirflowNetwork InitAirflowNetworkData InitAirHeatBalance InitAirLoops InitAirLoopSplitter InitAirMixer InitAirTerminalUserDefined InitAirZoneReturnPlenum InitAirZoneSupplyPlenum InitATMixer InitBaseboard InitBaseboard InitBLASTAbsorberModel InitBoiler InitBoiler InitBoreholeHXSimVars InitBSDFWindows InitCBVAV InitCoilUserDefined InitComplexWindows InitComponentNodes InitConductionTransferFunctions InitConnections InitConstCOPChiller InitController InitCoolBeam InitCTGenerators InitCurveReporting InitDaylightingDevices InitDemandManagers InitDesiccantDehumidifier InitDetailedIceStorage InitDirectAir InitDualDuct InitDuct InitDXCoil InitDXCoolingSystem InitDXHeatPumpSystem InitElecReformEIRChiller InitElectricBaseboard InitElectricChiller InitElectricEIRChiller InitEMS InitEMSControlledConstructions InitEMSControlledSurfaceProperties InitEnergyReports InitEngineDrivenChiller InitEquivalentLayerWindowCalculations InitEvapCooler InitEvapFluidCooler InitExhaustAbsorber InitExteriorConvectionCoeff InitFan InitFanCoilUnits InitFluidCooler InitFluidHeatExchanger InitFuelCellGenerators InitFurnace InitGasAbsorber InitGlassOpticalCalculations InitGshp InitGshp InitGTChiller InitHeatBalance InitHeatBalFiniteDiff InitHeatBalHAMT InitHeatingCoil InitHeatRecovery InitHighTempRadiantSystem InitHumidifier InitHWBaseboard InitHXAssistedCoolingCoil InitHybridVentSysAvailMgr InitialInitHeatBalFiniteDiff InitializeCFSDaylighting InitializeCFSStateData InitializeComponentSizingTable InitializeConstructionsTables InitializeDaylightMapTables InitializeEnvironmentPeriodsTable InitializeErrorsTable InitializeGlycolTempLimits InitializeHeatTransferPipes InitializeIndexes InitializeIndexes InitializeLoops InitializeMaterialsTable InitializeMeters initializeMonetaryUnit InitializeNominalBaseboardHeatTable InitializeNominalElectricEquipmentTable InitializeNominalGasEquipmentTable InitializeNominalHotWaterEquipmentTable InitializeNominalInfiltrationTable InitializeNominalLightingTable InitializeNominalOtherEquipmentTable InitializeNominalPeopleTable InitializeNominalSteamEquipmentTable InitializeNominalVentilationTable InitializeOperatingMode InitializeOutput InitializePipes InitializePredefinedMonthlyTitles InitializePsychRoutines InitializePumps InitializeRefrigerantLimits InitializeReportMeterDataDictionaryTable InitializeReportMeterDataTables InitializeReportVariableDataDictionaryTable InitializeReportVariableDataTables InitializeRoomAirModelTable InitializeRootFinder InitializeRuntimeLanguage InitializeSchedulesTable InitializeSimulationsTable InitializeSQLiteTables InitializeSurfacesTable InitializeSystemSizingTable InitializeTabularDataTable InitializeTabularDataTable InitializeTabularDataView InitializeTabularDataView InitializeTabularMonthly InitializeTimeIndicesTable InitializeViews InitializeWeather InitializeZoneGroupTable InitializeZoneInfoTable InitializeZoneListTable InitializeZoneSizingTable InitICEngineGenerators InitIndirectAbsorpChiller InitIndUnit InitInteriorConvectionCoeffs InitInteriorRadExchange InitInternalHeatGains InitIntSolarDistribution InitLoadBasedControl InitLoadDistribution InitLowTempRadiantSystem InitMicroCHPNoNormalizeGenerators InitMoistureBalanceEMPD InitMSHeatPump InitMTGenerators InitMundtModel InitOAController InitOAMixer InitOneTimePlantSizingInfo InitOutAirNodes InitOutdoorAirUnit InitOutsideAirSys InitPipesHeatTransfer InitPipingSystems InitPIU InitPlantProfile InitPlantUserComponent InitPlantValves InitPollutionMeterReporting InitPondGroundHeatExchanger InitPressureDrop InitPTUnit InitPurchasedAir InitPVTcollectors InitRefrigeration InitRefrigerationPlantConnections InitReturnAirPath InitSecretObjects InitSetPointManagers InitSimpleIceStorage InitSimpleMixingConvectiveHeatGains InitSimpleWatertoAirHP InitSimVars InitSimVars InitSimVars InitSimVars InitSolarCalculations InitSolarCollector InitSolarHeatGains InitSolReflRecSurf InitStandAloneERV InitSteamBaseboard InitSteamCoil InitSurfaceGroundHeatExchanger InitSurfaceHeatBalance InitSys InitSysAvailManagers InitSystemOutputRequired InitTempDistModel InitTESCoil InitThermalAndFluxHistories InitThermalComfort InitTower InitTranspiredCollector InitTRNSYSPV InitUCSDCV InitUCSDDV InitUCSDUF InitUniqueNodeCheck InitUnitarySystems InitUnitHeater InitUnitVentilator InitVarSpeedCoil InitVentilatedSlab InitVRF InitWaterCoil InitWaterSource InitWaterThermalTank InitWatertoAirHP InitWatertoWaterHP InitWindowAC InitWindTurbine InitWrapper InitZoneAirLoopEquipment InitZoneAirSetpoints InitZoneAirUserDefined InitZoneContSetpoints InitZoneDehumidifier InitZoneEquipment InitZoneEvaporativeCoolerUnit InPolygon InsertCurrencySymbol int_times_vector INTCPT Integer_IsInRange IntegerIsWithinTwoValues IntegerToString InterConnectTwoPlantLoopSides InteriorBCEqns InteriorNodeEqns InternalRangeCheck InternalSetupTankDemandComponent InternalSetupTankSupplyComponent interp INTERP InterpBlind InterpDefValuesForGlycolConc Interpolate Interpolate_Lagrange InterpolateBetweenFourValues InterpolateBetweenTwoValues InterpolatePipeTransBeam InterpProfAng InterpProfSlatAng InterpretWeatherDataLine InterpSlatAng InterpSw InterpValuesForGlycolConc IntInterfaceNodeEqns IntPreDefTableEntry IntToStr Invert3By3Matrix InvertMatrix InvJulianDay IPTrimSigDigits iRoundSigDigits IS_BEAM IS_DIFF IS_DSRATIO IS_F IS_LWP IS_OPENNESS IS_SWP isCompLoadRepReq IsControlledShade IsConverged_CurrentToPrevIteration IsConverged_PipeCurrentToPrevIteration IsCurveInputTypeValid IsCurveOutputTypeValid isExternalInterfaceErlVariable IsGlazeLayerX IsGZSLayer isInQuadrilateral IsInRange isInTriangle IsLeapYear IsNodeOnSetPtManager IsParentObject IsParentObjectCompSet IsShadingLayer IssueSevereAlphaInputFieldError IssueSevereInputFieldError IssueSevereRealInputFieldError IsValidConnectionType IsVBLayer isWithinRange ITERATE IterateRootFinder iTrimSigDigits JGDate JulianDay LClimb LDSumMax LDSumMean LEEDtariffReporting LimitCoilCapacity LimitController LimitTUCapacity LinesOut linint LoadEquipList LoadInterface LogicalToInteger LogicalToInteger LogPlantConvergencePoints lookupOperator LookUpScheduleValue LookUpSeason LookupSItoIP lubksb LUBKSB ludcmp LUDCMP LUdecomposition LUsolution MakeAnchorName MakeHVACTimeIntervalString MakeMirrorSurface MakeRectangularVertices MakeRelativeRectangularVertices MakeTransition MakeUPPERCase ManageAirflowNetworkBalance ManageAirHeatBalance ManageAirLoops ManageAirModel ManageBranchInput ManageControllers ManageCoolTower ManageDemand ManageEarthTube ManageElectCenterStorageInteractions ManageElectricLoadCenters ManageElectStorInteractions ManageEMS ManageExteriorEnergyUse ManageGeneratorControlState ManageGeneratorFuelFlow ManageHeatBalance ManageHeatBalFiniteDiff ManageHeatBalHAMT ManageHVAC ManageHybridVentilation ManageInsideAdaptiveConvectionAlgo ManageInternalHeatGains ManageInverter ManageMundtModel ManageNonZoneEquipment ManageOutsideAdaptiveConvectionAlgo ManageOutsideAirSystem ManagePlantLoadDistribution ManagePlantLoops ManageRefrigeratedCaseRacks ManageSetPoints ManageSimulation ManageSingleCommonPipe ManageSizing ManageSurfaceHeatBalance ManageSystemAvailability ManageThermalChimney ManageThermalComfort ManageTransformers ManageTwoWayCommonPipe ManageUCSDCVModel ManageUCSDDVModel ManageUCSDUFModels ManageUserDefinedPatterns ManageWater ManageWaterInits ManageWeather ManageZoneAirLoopEquipment ManageZoneAirUpdates ManageZoneContaminanUpdates ManageZoneEquipment MapExtConvClassificationToHcModels MapIntConvClassificationToHcModels MarkNode MatchAndSetColorTextString MatchPlantSys MatrixIndex matrixQBalance MeshPartition_CompareByDimension MeshPartition_SelectionSort MeshPartitionArray_Contains MinePlantStructForInfo MixedAirControlTempResidual ModifyWindow Modulus MonthToMonthNumber MovingAvg MRXINV MSHPCyclingResidual MSHPHeatRecovery MSHPVarSpeedResidual MultiModeDXCoilHumRatResidual MultiModeDXCoilHumRatResidual MultiModeDXCoilResidual MultiModeDXCoilResidual MultiModeDXCoilResidual MultiSpeedDXCoolingCoilStandardRatings MultiSpeedDXHeatingCoilStandardRatings MULTOL MyPlantSizingIndex NeighborInformationArray_Value NETRAD NewEMSVariable NewExpression newPreDefColumn newPreDefReport newPreDefSubTable NEWTON NodeHasSPMCtrlVarType NormalArea NumBranchesInBranchList NumCompsInBranch nusselt NusseltNumber OpenEPlusWeatherFile OPENNESS_LW OpenOutputFiles OpenOutputTabularFile OpenWeatherFile OPERATOR (*) OPERATOR (+) OPERATOR (-) OPERATOR (.dot.) OPERATOR (.twodcross.) OPERATOR (.twoddot.) OPERATOR (/) ORDER OutBaroPressAt OutDewPointTempAt OutDryBulbTempAt OutsidePipeHeatTransCoef OutWetBulbTempAt P01 PanesDeflection ParametricObjectsCheck parseComputeLine ParseExpression ParseStack ParseTime PartLoadFactor PassiveGapNusseltNumber PassPressureAcrossInterface PassPressureAcrossMixer PassPressureAcrossSplitter PD_BEAM PD_BEAM_CASE_I PD_BEAM_CASE_II PD_BEAM_CASE_III PD_BEAM_CASE_IV PD_BEAM_CASE_V PD_BEAM_CASE_VI PD_DIFF PD_LW PD_LWP PD_SWP PerformanceCurveObject PerformanceTableObject PerformIterationLoop PerformPipeCellSimulation PerformPipeCircuitSimulation PerformSolarCalculations PerformTemperatureFieldUpdate PierceSurface PierceSurfaceVector PipeCircuitInfo_InitInOutCells PipeSegmentInfo_InitPipeCells PIUInducesPlenumAir PIUnitHasMixer PlaneEquation PlantHalfLoopSolver PlantMassFlowRatesFunc PLRResidual PLRResidual PLRResidualMixedTank PLRResidualStratifiedTank PMVResidual POLY1F POLY2F POLYF polygon_contains_point_2d popStack pos PostIPProcessing POWER PreDefTableEntry PredictSystemLoads PredictZoneContaminants PreparePipeCircuitSimulation PrepDebugFilesAndVariables PreProcessorCheck PrepVariablesISO15099 PreScanReportingVariables PresProfile PressureCurveValue ProcessDataDicFile ProcessDateString ProcessEMSInput ProcessEPWHeader ProcessForDayTypes ProcessInput ProcessInputDataFile ProcessIntervalFields ProcessMinMaxDefLine ProcessNumber ProcessScheduleInput ProcessSurfaceVertices ProcessTokens ProduceMinMaxString ProduceMinMaxStringWStartMinute ProduceRDDMDD ProfileAngle PropagateResolvedFlow PStack PsyCpAirFnWTdb PsyHfgAirFnWTdb PsyHFnTdbRhPb PsyHFnTdbW PsyHgAirFnWTdb PsyPsatFnTemp PsyPsatFnTemp_raw PsyRhFnTdbRhov PsyRhFnTdbRhovLBnd0C PsyRhFnTdbWPb PsyRhoAirFnPbTdbW PsyRhovFnTdbRh PsyRhovFnTdbRhLBnd0C PsyRhovFnTdbWPb PsyTdbFnHW PsyTdpFnTdbTwbPb PsyTdpFnWPb PsyTsatFnHPb PsyTsatFnPb PsyTwbFnTdbWPb PsyTwbFnTdbWPb_raw PsyVFnTdbWPb PsyWFnTdbH PsyWFnTdbRhPb PsyWFnTdbTwbPb PsyWFnTdpPb psz Pt2Plane PullCompInterconnectTrigger PumpDataForTable PushBranchFlowCharacteristics PushInnerTimeStepArrays pushStack PushSystemTimestepHistories PushSystemTimestepHistories PushZoneTimestepHistories PushZoneTimestepHistories QsortC QsortPartition RadialCellInfo_XY_CrossSectArea RadialCellInformation_ctor RadialSizing_Thickness Rainflow RangeCheck RB_BEAM RB_DIFF RB_F RB_LWP RB_SWP rCheckDayScheduleValueMinMax rCheckScheduleValue rCheckScheduleValueMinMax1 rCheckScheduleValueMinMax2 ReadEnergyMeters ReadEPlusWeatherForDay ReadGeneralDomainInputs ReadHorizontalTrenchInputs ReadINIFile ReadInputLine ReadPipeCircuitInputs ReadPipeSegmentInputs ReadTableData ReadUserWeatherInput ReadWeatherForDay Real_ConstrainTo Real_IsInRange real_times_vector ReAllocateAndPreserveOutputVariablesForSimulation ReallocateIntegerArray ReallocateIVar ReallocateRealArray ReallocateRVar RealPreDefTableEntry RealToStr RecKeepHeatBalance RecordOutput RectangleF_Contains ReformEIRChillerCondInletTempResidual ReformEIRChillerHeatRecovery RegisterNodeConnection RegisterPlantCompDesignFlow RegulateCondenserCompFlowReqOp ReInitPlantLoopsAtFirstHVACIteration RemoveSpaces RemoveTrailingZeros reorder ReplaceBlanksWithUnderscores ReplaceBlanksWithUnderscores ReportAirflowNetwork ReportAirHeatBalance ReportAirLoopConnections ReportAirTerminalUserDefined ReportAndTestGlycols ReportAndTestRefrigerants ReportBaseboard ReportBaseboard ReportCBVAV ReportChillerIPLV ReportCoilUserDefined ReportCompSetMeterVariables ReportController ReportCoolBeam ReportCoolTower ReportCTFs ReportCWTankInits ReportDemandManagerList ReportDesiccantDehumidifier ReportDetailedIceStorage ReportDirectAir ReportDualDuct ReportDualDuctConnections ReportDuct ReportDXCoil ReportDXCoilRating ReportDYMeters ReportEarthTube ReportEconomicVariable ReportElectricBaseboard ReportEMS ReportEvapCooler ReportEvapFluidCooler ReportExteriorEnergyUse ReportFan ReportFanCoilUnit ReportFatalGlycolErrors ReportFatalRefrigerantErrors ReportFiniteDiffInits ReportFluidCooler ReportFluidHeatExchanger ReportForTabularReports ReportFurnace ReportGlass ReportHeatBalance ReportHeatingCoil ReportHeatRecovery ReportHighTempRadiantSystem ReportHRMeters ReportHumidifier ReportHWBaseboard ReportIllumMap ReportingFreqName ReportingThisVariable ReportInternalHeatGains ReportLoopConnections ReportLowTempRadiantSystem ReportMaxVentilationLoads ReportMeterDetails ReportMissing_RangeData ReportMixer ReportMNMeters ReportMoistureBalanceEMPD ReportMSHeatPump ReportNodeConnections ReportOAController ReportOAMixer ReportOrphanFluids ReportOrphanRecordObjects ReportOrphanSchedules ReportOutdoorAirUnit ReportOutputFileHeaders ReportParentChildren ReportPipesHeatTransfer ReportPIU ReportPlantProfile ReportPlantUserComponent ReportPlantValves ReportPondGroundHeatExchanger ReportPTUnit ReportPumps ReportPurchasedAir ReportPV ReportRackSystem ReportRefrigerationComponents ReportReturnAirPath ReportRuntimeLanguage ReportScheduleDetails ReportScheduleValues ReportSizingOutput ReportSMMeters ReportSolarCollector ReportSplitter ReportStandAloneERV ReportStandAloneWaterUse ReportSteamBaseboard ReportSteamCoil ReportSurfaceErrors ReportSurfaceGroundHeatExchngr ReportSurfaceHeatBalance ReportSurfaces ReportSurfaceShading ReportSys ReportSysSizing ReportSystemEnergyUse ReportThermalChimney ReportTowers ReportTSMeters ReportUnitarySystem ReportUnitHeater ReportUnitVentilator ReportVentilatedSlab ReportVRFCondenser ReportVRFTerminalUnit ReportWarmupConvergence ReportWaterCoil ReportWaterManager ReportWaterThermalTank ReportWaterUse ReportWeatherAndTimeInformation ReportWindowAC ReportWindTurbine ReportZoneAirLoopEquipment ReportZoneAirUserDefined ReportZoneDehumidifier ReportZoneEquipment ReportZoneEvaporativeCoolerUnit ReportZoneMeanAirTemp ReportZoneReturnPlenum ReportZoneSizing ReportZoneSupplyPlenum ResetAllPlantInterConnectFlags ResetController ResetEnvironmentCounter ResetHVACControl ResetNodeData ResetPerformanceCurveOutput ResetRootFinder ResetTerminalUnitFlowLimits ResetWeekDaysByMonth Resimulate resist ReSolveAirLoopControllers ResolveAirLoopFlowLimits ResolveLocationInformation ResolveLockoutFlags ResolveLoopFlowVsPressure ResolveParallelFlows ResolveSysFlow ReverseAndRecalculate RevertZoneTimestepHistories RevertZoneTimestepHistories RevisePlantCallingOrder RezeroZoneSizingArrays RhoH2O RHtoVP RKG RoundSigDigits rRoundSigDigits rTrimSigDigits SafeCopyPlantNode SafeDiv SafeDivide SameString SandiaCellTemperature SandiaEffectiveIrradiance SandiaF1 SandiaF2 SandiaImp SandiaIsc SandiaIx SandiaIxx SandiaModuleTemperature SandiaTcellFromTmodule SandiaVmp SandiaVoc SaveSimpleController ScanForReports ScanPlantLoopsForNodeNum ScanPlantLoopsForObject sCheckDayScheduleValueMinMax ScheduleAverageHoursPerWeek SEARCH SearchAscTable SearchWindow5DataFile SecantFormula SecantMethod selectTariff SetActuatedBranchFlowRate SetAdditionalNeighborData SetAllFlowLocks SetAllPlantSimFlagsToValue SetATMixerPriFlow SetATMixerPriFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetCoilDesFlow SetCoilSystemCoolingData SetCoilSystemHeatingDXFlag SetCompFlowRate SetComponentFlowRate SetCurrentWeather SetCurveOutputMinMaxValues SetDSTDateRanges SetDXCoilTypeData SetDXCoolingCoilData SetEquivalentLayerWindowProperties SetErlValueNumber SetExtConvectionCoeff SetFanData SetHeatExchangerData SetHeatToReturnAirFlag SetInitialMeterReportingAndOutputNames SetIntConvectionCoeff SetInternalVariableValue SetMinMax setNativeVariables SetNodeResult SetOAControllerData SetOnOffMassFlowRate SetOnOffMassFlowRate SetOnOffMassFlowRate SetOnOffMassFlowRateVSCoil SetOnOffMassFlowRateVSCoil SetOutAirNodes SetOutBulbTempAt SetPredefinedTables SetSimpleWSHPData SETSKY SetSpecialDayDates SetSpeedVariables SetStormWindowControl SetSurfHBDataForMundtModel SetSurfHBDataForTempDistModel SetSurfTmeanAir SETUP4x4_A SetupAdaptiveConvectionRadiantSurfaceData SetupAdaptiveConvectionStaticMetaData SetupAirLoopControllersTracer SetupAllOutputVariables SetUpAndSort SetupBranchControlTypes SetupCellNeighbors SetupCommonPipes SetupComplexFenestrationMaterialInput SetupComplexFenestrationStateInput SetupComplexWindowStateGeometry SetUpCompSets SetupDElightOutput4EPlus SetupDElightOutput4EPlus SetUpDesignDay SetupEMSActuator SetupEMSIntegerActuator SetupEMSIntegerInternalVariable SetupEMSInternalVariable SetupEMSLogicalActuator SetupEMSRealActuator SetupEMSRealInternalVariable SetupEnvironmentTypes SetupFuelConstituentData SetupGeneratorControlStateManager SetupIndividualControllerTracer SetupInitialPlantCallingOrder SetupIntegerOutputVariable SetupInterpolationValues SetupLoopFlowRequest SetupMeteredVarsForSetPt SetupMundtModel SetupNodeSetpointsAsActuators SetupNodeVarsForReporting SetupOutputVariable SetupPipeCircuitInOutCells SetupPlantEMSActuators SetupPollutionCalculations SetupPollutionMeterReporting SetupPossibleOperators SetupPrimaryAirSystemAvailMgrAsActuators SetupPumpMinMaxFlows SetupRealOutputVariable SetupRealOutputVariable_IntKey SetupReportInput SetupReports SetupRootFinder SetUpSchemeColors SetupShadeSurfacesForSolarCalcs SetupSimpleWindowGlazingSystem SetupSimulation SetupStratifiedNodes SetupSurfaceConstructionActuators SetupSurfaceConvectionActuators SetupSurfaceOutdoorBoundaryConditionActuators SetUpSysSizingArrays SetupTankDemandComponent SetupTankSupplyComponent SetupThermostatActuators SetupTimePointers SetupUnitConversions SetupWeekDaysByMonth SetupWindowShadingControlActuators SetupZoneEquipmentForConvectionFlowRegime SetupZoneGeometry SetupZoneInfoAsInternalDataAvail SetupZoneInternalGain SetupZoneInternalGain SetupZoneSizing SetUpZoneSizingArrays SetUTSCQdotSource SetVarSpeedCoilData SetVentedModuleQdotSource SetVSHPAirFlow SetVSHPAirFlow SetWindSpeedAt SetZoneEquipSimOrder shading shadingedge shadingin SHADOW SharedDVCVUFDataInit SHDBKS SHDGSS SHDRVL SHDSBS shift ShiftPipeTemperaturesForNewIteration ShiftPlantLoopSideCallingOrder ShiftTemperaturesForNewIteration ShiftTemperaturesForNewTimeStep ShowAuditErrorMessage ShowBranchesOnLoop ShowContinueError ShowContinueError ShowContinueErrorTimeStamp ShowContinueErrorTimeStamp ShowErrorMessage ShowErrorMessage ShowFatalError ShowFatalError ShowMessage ShowMessage ShowPsychrometricSummary ShowRecurringContinueErrorAtEnd ShowRecurringContinueErrorAtEnd ShowRecurringErrors ShowRecurringSevereErrorAtEnd ShowRecurringSevereErrorAtEnd ShowRecurringWarningErrorAtEnd ShowRecurringWarningErrorAtEnd ShowSevereError ShowSevereError ShowSevereMessage ShowSevereMessage ShowWarningError ShowWarningError ShowWarningMessage ShowWarningMessage showWarningsBasedOnTotal Sim4PipeFanCoil SimAirChillerSet SimAirLoop SimAirLoopComponent SimAirLoopComponents SimAirLoops SimAirLoopSplitter SimAirMixer SimAirTerminalUserDefined SimAirZonePlenum SimATMixer SimBaseboard SimBLASTAbsorber SimBoiler SimCBVAV SimCBVAV SimCentralGroundSourceHeatPump SimChiller SimCoilUserDefined SimComponentModelFan SimConstVol SimCoolBeam SimCostEstimate SimCTGenerator SimCTPlantHeatRecovery SimCyclingWindowAC SimDesiccantDehumidifier SimDetailedIceStorage SimDirectAir SimDistrictEnergy SimDualDuctConstVol SimDualDuctVarVol SimDualDuctVAVOutdoorAir SimDuct SimDXCoil SimDXCoilMultiMode SimDXCoilMultiSpeed SimDXCoolingSystem SimDXHeatPumpSystem SimElecBaseBoard SimElectricBaseBoard SimElectricConvective SimElectricEIRChiller SimEvapCooler SimEvapFluidCoolers SimExhaustAbsorber SimFanCoilUnit SimFluidCoolers SimFluidHeatExchanger SimFourPipeIndUnit SimFuelCellGenerator SimFuelCellPlantHeatRecovery SimFurnace SimGasAbsorber SimGroundHeatExchangers SimHeatPumpWaterHeater SimHeatRecovery SimHighTempRadiantSystem SimHPWatertoWaterCOOLING SimHPWatertoWaterHEATING SimHPWatertoWaterSimple SimHumidifier SimHVAC SimHWBaseboard SimHWConvective SimHXAssistedCoolingCoil SimICEngineGenerator SimICEPlantHeatRecovery SimIceStorage SimIndirectAbsorber SimIndUnit SimLowTempRadiantSystem SimMicroCHPGenerator SimMicroCHPPlantHeatRecovery SimMSHeatPump SimMSHP SimMTGenerator SimMTPlantHeatRecovery SimMultiSpeedCoils SimOAComponent SimOAController SimOAMixer SimOnOffFan SimOutdoorAirEquipComps SimOutdoorAirUnit SimOutsideAirSys SimOutsideEnergy SimPackagedTerminalUnit SimPipes SimPipesHeatTransfer SimPipingSystemCircuit SimPIU SimPlantEquip SimPlantValves SimpleCoolingCoilUAResidual SimpleEvapFluidCoolerUAResidual SimpleFluidCoolerUAResidual SimpleHeatingCoilUAResidual SimpleTowerApproachResidual SimpleTowerTrResidual SimpleTowerUAResidual SimPondGroundHeatExchanger SimPressureDropSystem SimPTUnit SimPumps SimPurchasedAir SimPVGenerator SimPVTcollectors SimReformulatedEIRChiller SimRefrigCondenser SimReturnAirPath SimSelectedEquipment SimSetPointManagers SimSimpleEvapFluidCooler SimSimpleFan SimSimpleFluidCooler SimSimpleTower SimSolarCollector SimStandAloneERV SimSteamBaseboard SimSteamBoiler SimSteamCoils SimSurfaceGroundHeatExchanger SimSysAvailManager SimTESCoil SimTowers SimTranspiredCollector SimulateAllInteriorRadialSoilSlices SimulateAllLoopSideBranches SimulateAllLoopSidePumps SimulateDemandManagerList SimulateDetailedRefrigerationSystems SimulateDetailedTransRefrigSystems SimulateDualDuct SimulateFanComponents SimulateFluidCell SimulateHeatingCoilComponents SimulateInnerMostRadialSoilSlice SimulateLoopSideBranchGroup SimulateOuterMostRadialSoilSlice SimulatePlantProfile SimulateRadialInsulationCell SimulateRadialPipeCell SimulateRadialToCartesianInterface SimulateSingleDuct SimulateSteamCoilComponents SimulateVRF SimulateWaterCoilComponents SimulateWaterHeaterStandAlone SimulateWaterUse SimulateWaterUseConnection SimUnitaryBypassVAV SimUnitarySystem SimUnitHeater SimUnitVentilator SimUnitVentOAMixer SimUserDefinedPlantComponent SimVariableSpeedCoils SimVariableSpeedHP SimVariableSpeedHP SimVariableTower SimVariableVolumeFan SimVAV SimVAVVS SimVentilatedSlab SimVentSlabOAMixer SimVRF SimVRFCondenserPlant SimWaterCoils SimWaterSource SimWaterThermalTank SimWatertoAirHP SimWatertoAirHPSimple SimWindowAC SimWindTurbine SimZoneAirLoopEquipment SimZoneAirUserDefined SimZoneDehumidifier SimZoneEquipment SimZoneEvaporativeCoolerUnit SimZoneExhaustFan SimZoneOutAirUnitComps SingelSpeedDXCoolingCoilStandardRatings SingleSpeedDXHeatingCoilStandardRatings SingleSpeedFluidCooler SizeAbsorpChiller SizeAirLoopBranches SizeAirLoops SizeBaseboard SizeBoiler SizeBoiler SizeCBVAV SizeConstCOPChiller SizeController SizeCoolBeam SizeDemandSidePlantConnections SizeDirectAir SizeDualDuct SizeDXCoil SizeElecReformEIRChiller SizeElectricBaseboard SizeElectricBaseboard SizeElectricChiller SizeElectricEIRChiller SizeEngineDrivenChiller SizeEvapCooler SizeEvapFluidCooler SizeExhaustAbsorber SizeFan SizeFanCoilUnit SizeFluidCooler SizeFluidHeatExchanger SizeFurnace SizeGasAbsorber SizeGTChiller SizeHeatingCoil SizeHeatRecovery SizeHighTempRadiantSystem SizeHumidifier SizeHVACWaterToAir SizeHWBaseboard SizeIndirectAbsorpChiller SizeIndUnit SizeLowTempRadiantSystem SizeMSHeatPump SizeOAController SizeOutdoorAirUnit SizePIU SizePlantLoop SizePTUnit SizePump SizePurchasedAir SizePVT SizeStandAloneERV SizeStandAloneWaterHeater SizeSteamBaseboard SizeSteamCoil SizeSupplySidePlantConnections SizeSys SizeTankForDemandSide SizeTankForSupplySide SizeTESCoil SizeTower SizeUCSDUF SizeUnitarySystem SizeUnitHeater SizeUnitVentilator SizeVarSpeedCoil SizeVentilatedSlab SizeVRF SizeVRFCondenser SizeVSMerkelTower SizeWaterCoil SizeWaterManager SizeWaterSource SizeWindowAC SizeWrapper SizeZoneDehumidifier SizeZoneEquipment SizeZoneEvaporativeCoolerUnit SkipEPlusWFHeader SkyDifSolarShading SkyGndWeight SkyWeight SLtoAMB SLtoGL SLVSKY solar_EN673 solarISO15099 SolarSprectrumAverage SOLMATS SolveAirLoopControllers SolveForWindowTemperatures SolveRegression SolveRegulaFalsi SolverMoistureBalanceEMPD SOLVZP SortHistory Specular_Adjust Specular_EstimateDiffuseProps Specular_F Specular_OffNormal Specular_RATDiff Specular_SWP SQLiteBegin SQLiteBegin SQLiteBindDouble SQLiteBindInteger SQLiteBindLogicalMacro SQLiteBindNULL SQLiteBindText SQLiteBindTextMacro SQLiteClearBindings SQLiteCloseDatabase SQLiteColumnInt SQLiteColumnIntMacro SQLiteCommit SQLiteCommit SQLiteExecuteCommand SQLiteExecuteCommandMacro SQLiteFinalizeCommand SQLiteOpenDatabase SQLiteOpenDatabaseMacro SQLitePrepareStatement SQLitePrepareStatementMacro SQLiteResetCommand SQLiteStepCommand SQLiteWriteMessage SQLiteWriteMessageMacro SQLiteWriteMessageMacro StandardIndexTypeKey StandardVariableTypeKey StartingWindowTemps StartingWinTempsForNominalCond SteamHeatingCoilResidual StorageType StoreAPumpOnCurrentTempLoop storeIterationResults StoreRecurringErrorMessage StringValue StrToReal SumAllInternalCO2Gains SumAllInternalConvectionGains SumAllInternalGenericContamGains SumAllInternalLatentGains SumAllInternalRadiationGains SumAllReturnAirConvectionGains SumAllReturnAirLatentGains SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumInternalCO2GainsByTypes SumInternalConvectionGainsByTypes SumInternalLatentGainsByTypes SumInternalRadiationGainsByTypes SummarizeErrors SumReturnAirConvectionGainsByTypes SumZoneImpacts SUN3 SUN4 SupSATResidual SurfaceScheduledSolarInc SurveyDemandManagers SystemPropertiesAtLambdaAndPhi SystemSpectralPropertiesAtPhi TableLookupObject TARCOG90 TBND TdbFnHRhPb TDMA TDMA_R TellMeHowManyObjectItemArgs TemperaturesFromEnergy TempIPtoSI TempSItoIP terpld TESCoilHumRatResidual TESCoilResidual TestAirPathIntegrity TestBranchIntegrity TestCompSet TestCompSetInletOutletNodes TestInletOutletNodes TestReturnAirPathIntegrity TestSupplyAirPathIntegrity therm1d TightenNodeMinMaxAvails TimestepInitComplexFenestration TimestepTypeName TraceAirLoopController TraceAirLoopControllers TraceIndividualController TraceIterationStamp TrackAirLoopController TrackAirLoopControllers TRadC TransAndReflAtPhi TransformVertsByAspect TransTDD Triangulate TrimSigDigits TurnOffLoopEquipment TurnOffLoopSideEquipment TurnOffReportRangeCheckErrors TurnOnPlantLoopPipes TurnOnReportRangeCheckErrors TwoSpeedFluidCooler UnitarySystemHeatRecovery UpdateAbsorberChillerComponentGeneratorSide UpdateAirflowNetwork UpdateAirMixer UpdateAirSysCompPtrArray UpdateAirSysSubCompPtrArray UpdateAirSysSubSubCompPtrArray UpdateAirZoneReturnPlenum UpdateAirZoneSupplyPlenum UpdateAnyLoopDemandAlterations UpdateATMixer UpdateBaseboard UpdateBaseboardPlantConnection UpdateBasementSurfaceTemperatures UpdateBBElecRadSourceValAvg UpdateBBRadSourceValAvg UpdateBBSteamRadSourceValAvg UpdateBLASTAbsorberRecords UpdateBoilerRecords UpdateBoilerRecords UpdateBracket UpdateBranchConnections UpdateChillerComponentCondenserSide UpdateChillerheaterRecords UpdateChillerRecords UpdateColdWeatherProtection UpdateCommonPipe UpdateComplexWindows UpdateComponentHeatRecoverySide UpdateConstCOPChillerRecords UpdateController UpdateCoolBeam UpdateCoolTower UpdateCTGeneratorRecords UpdateDataandReport UpdateDemandManagers UpdateDesiccantDehumidifier UpdateDetailedIceStorage UpdateDualDuct UpdateDuct UpdateDXCoil UpdateElectricBaseboard UpdateElectricChillerRecords UpdateElectricEIRChillerRecords UpdateEMSTrendVariables UpdateEngineDrivenChiller UpdateEvapCooler UpdateEvapFluidCooler UpdateEvaporativeCondenserBasinHeater UpdateEvaporativeCondenserWaterUse UpdateExhaustAbsorberCoolRecords UpdateExhaustAbsorberHeatRecords UpdateExhaustAirFlows UpdateFan UpdateFinalSurfaceHeatBalance UpdateFluidCooler UpdateFluidHeatExchanger UpdateFuelCellGeneratorRecords UpdateGasAbsorberCoolRecords UpdateGasAbsorberHeatRecords UpdateGSHPRecords UpdateGSHPRecords UpdateGSHPRecords UpdateGTChillerRecords UpdateHalfLoopInletTemp UpdateHeatBalHAMT UpdateHeatingCoil UpdateHeatRecovery UpdateHighTempRadiantSystem UpdateHistories UpdateHistory UpdateHTRadSourceValAvg UpdateHumidifier UpdateHVACInterface UpdateHWBaseboard UpdateHWBaseboardPlantConnection UpdateIceFractions UpdateICEngineGeneratorRecords UpdateIndirectAbsorberRecords UpdateInternalGainValues UpdateIrrigation UpdateLoadCenterRecords UpdateLoopSideReportVars UpdateLowTempRadiantSystem UpdateMeterReporting UpdateMeters UpdateMeterValues UpdateMicroCHPGeneratorRecords UpdateMinMax UpdateMixedAirSetPoints UpdateMoistureBalanceEMPD UpdateMoistureBalanceFD UpdateMSHeatPump UpdateMTGeneratorRecords UpdateNode UpdateNodeThermalHistory UpdateOAController UpdateOAMixer UpdateOAPretreatSetPoints UpdatePipesHeatTransfer UpdatePipingSystems UpdatePlantLoopInterface UpdatePlantMixer UpdatePlantProfile UpdatePlantSplitter UpdatePlantValves UpdatePondGroundHeatExchanger UpdatePrecipitation UpdatePressureDrop UpdatePurchasedAir UpdatePVTcollectors UpdateRadSysSourceValAvg UpdateRecords UpdateReformEIRChillerRecords UpdateRefrigCondenser UpdateReportWaterSystem UpdateRootFinder UpdateScheduleValues UpdateSetPointManagers UpdateSimpleWatertoAirHP UpdateSoilProps UpdateSolarCollector UpdateSplitter UpdateSQLiteErrorRecord UpdateSQLiteErrorRecord UpdateSQLiteSimulationRecord UpdateSQLiteSimulationRecord UpdateSteamBaseboard UpdateSteamBaseboardPlantConnection UpdateSteamCoil UpdateSurfaceGroundHeatExchngr UpdateSys UpdateSysSizing UpdateSystemOutputRequired UpdateTabularReports UpdateTEStorage UpdateThermalHistories UpdateTowers UpdateTranspiredCollector UpdateUnitarySystemControl UpdateUtilityBills UpdateVarSpeedCoil UpdateVentilatedSlab UpdateVerticalGroundHeatExchanger UpdateVRFCondenser UpdateWaterCoil UpdateWaterConnections UpdateWaterManager UpdateWaterSource UpdateWaterThermalTank UpdateWaterToAirCoilPlantConnection UpdateWatertoAirHP UpdateWeatherData UpdateWholeBuildingRecords UpdateZoneAirLoopEquipment UpdateZoneCompPtrArray UpdateZoneDehumidifier UpdateZoneEquipment UpdateZoneInletConvergenceLog UpdateZoneListAndGroupLoads UpdateZoneSizing UpdateZoneSubCompPtrArray UpdateZoneSubSubCompPtrArray ValidateAndSetSysAvailabilityManagerType ValidateComponent ValidateDistributionSystem ValidateEMSProgramName ValidateEMSVariableName ValidateExhaustFanInput ValidateFlowControlPaths ValidateFuelType ValidateIndexType ValidateMaterialRoughness ValidateMonthDay ValidateNStandardizeMeterTitles ValidateObjectandParse ValidatePipeConstruction ValidatePLFCurve ValidateSection ValidateSectionsInput ValidateVariableType value_to_vector ValueToString VAVVSCoolingResidual VAVVSHCFanOnResidual VAVVSHWFanOnResidual VAVVSHWNoFanResidual VB_CriticalSlatAngle VB_DIFF VB_LWP VB_ShadeControl VB_SLAT_RADIUS_RATIO VB_SOL4 VB_SOL46_CURVE VB_SOL6 VB_SWP vec2d_cross_product vec2d_dot_product vec_cross_product vec_dot_product VecLength VecNegate VecNormalize VecRound VecSquaredLength vector_add vector_div_int vector_div_real vector_subtract vector_times_int vector_times_real vector_to_array VerifyControlledZoneForThermostat VerifyCustomMetersElecPowerMgr VerifyHeatExchangerParent VerifyName VerifySetPointManagers VerifyThermostatInZone VerifyUniqueBaseboardName VerifyUniqueBoilerName VerifyUniqueChillerName VerifyUniqueCoilName ViewFac VisibleSprectrumAverage Volume VRMLOut VSCoilCyclingHumResidual VSCoilCyclingResidual VSCoilCyclingResidual VSCoilSpeedHumResidual VSCoilSpeedResidual VSCoilSpeedResidual VSEvapUnitLoadResidual VSHPCyclingResidual VSHPCyclingResidual VSHPSpeedResidual VSHPSpeedResidual VSMerkelResidual W5InitGlassParameters W5LsqFit W5LsqFit2 W6CoordsFromWorldVect warnIfNativeVarname WetCoilOutletCondition WhichCompSet WhichParentCompSet WhichParentSet Width WindowGapAirflowControl WindowGasConductance WindowGasPropertiesAtTemp WindowHeatBalanceEquations WindowScheduledSolarAbs WindowShadingManager WindowTempsForNominalCond WindSpeedAt Windward WorldVectFromW6 WriteAdaptiveComfortTable WriteAirLoopStatistics WriteBEPSTable WriteCompCostTable WriteComponentSizing WriteCumulativeReportMeterData WriteDaylightMapTitle WriteDemandEndUseSummary WriteInputArguments WriteIntegerData WriteIntegerVariableOutput WriteMeterDictionaryItem WriteModifiedArguments WriteMonthlyTables WriteOutputArguments WriteOutputEN673 WritePoint WritePredefinedTables WriteRealData WriteRealVariableOutput WriteReportHeaders WriteReportIntegerData WriteReportMeterData WriteReportRealData WriteReportVariableDictionaryItem WriteRootFinderStatus WriteRootFinderTrace WriteRootFinderTraceHeader WriteSourceEnergyEndUseSummary writeSubtitle WriteSurfaceShadowing WriteTable WriteTableOfContents WriteTabularLifeCycleCostReport WriteTabularReports WriteTabularTariffReports WriteTARCOGInputFile writeTextLine WriteTimeBinTables WriteTimeStampFormatData WriteTrace WriteVeriSumTable WriteZoneLoadComponentTable WVDC XNormalArea XYRectangle XZRectangle YNormalArea YZRectangle ZeroHVACValues ZNormalArea
Call graph
updatezonesizing calls finalzonesizing, zonethermostatsetpointhi, coolpeakdatehrmin, showcontinueerror, movingavg, showsevereerror, manageems, showwarningerror, zonesizthermsetptlo, tempzonethermostatsetpoint, zonethermostatsetpointlo, desdayweath, psywfntdppb, calcfinalzonesizing, calczonesizing, roundsigdigits, zonesizthermsetpthi, zonesizing, zoneequipconfig, heatpeakdatehrmin
showcontinueerror calls showerrormessage, updatesqliteerrorrecord
showsevereerror calls showerrormessage, createsqliteerrorrecord, matchcounts, messagesearch
showwarningerror calls showerrormessage, createsqliteerrorrecord, matchcounts, messagesearch
showerrormessage calls displaystring, showfatalerror
showfatalerror calls roundsigdigits, showerrormessage, displaystring, abortenergyplus, createsqliteerrorrecord
abortenergyplus calls roundsigdigits, displaystring, testairpathintegrity, updatesqlitesimulationrecord, checkmarkednodes, reportairloopconnections, showrecurringerrors, testcompsetinletoutletnodes, summarizeerrors, reportsurfaceerrors, reportloopconnections, closemiscopenfiles, setupnodevarsforreporting, closesocket, closeoutopenfiles, reportsurfaces, testbranchintegrity, checkplantonabort, epelapsedtime, epstoptime, epsummarytimes, showmessage, checknodeconnections
testairpathintegrity calls showcontinueerror, showsevereerror, airtozonenodeinfo, nodeid
showrecurringerrors calls roundsigdigits, updatesqliteerrorrecord, createsqliteerrorrecord, showmessage, removetrailingzeros, recurringerrors
summarizeerrors calls showmessage, matchcounts, summaries, moredetails
closemiscopenfiles calls closedfsfile, closereportillummaps
reportsurfaces calls showwarningerror, detailsforsurfaces, setupschemecolors, vrmlout, scanforreports, dxfoutwireframe, costinfoout, linesout, dxfout
epstoptime calls showfatalerror, tstop
epsummarytimes calls roundsigdigits
showmessage calls showerrormessage
detailsforsurfaces calls roundsigdigits, getschedulename, oscm, nominalu, zone, framedivider, getschedulemaxvalue, 2, computenominaluwithconvcoeffs, 3, osc, trimsigdigits, construct, 4, csurfaceclass, userintconvectioncoeffs, userextconvectioncoeffs, surface, getscheduleminvalue, surfacewindow
setupschemecolors calls showwarningerror, getobjectitemnum, getobjectdefmaxargs, matchandsetcolortextstring, getobjectitem
vrmlout calls showcontinueerror, showwarningerror, showfatalerror, zone, surface, triangulate, getnewunitnumber
dxfoutwireframe calls showfatalerror, zone, trimsigdigits, surface, surfacewindow, getnewunitnumber, zonedaylight, dxfcolorno
costinfoout calls showfatalerror, construct, csurfaceclass, surface, getnewunitnumber
linesout calls showcontinueerror, showwarningerror, roundsigdigits, showfatalerror, csurfaceclass, surface, getnewunitnumber
dxfout calls showcontinueerror, showwarningerror, showfatalerror, zone, trimsigdigits, surface, surfacewindow, triangulate, getnewunitnumber, zonedaylight, dxfcolorno, illummapcalc
computenominaluwithconvcoeffs calls surface
matchandsetcolortextstring calls finditem
triangulate calls showcontinueerror, showwarningerror, roundsigdigits, showmessage, csurfaceclass, generate_ears, calcrfflrcoordinatetransformation, calcwallcoordinatetransformation
generate_ears calls polygon_contains_point_2d, angle_2dvector