WriteZoneLoadComponentTable – EnergyPlusFortran
WriteZoneLoadComponentTable Subroutine
750 statements
Source File
private subroutine WriteZoneLoadComponentTable()
Uses:
DataHeatBalance
SQLiteProcedures
DataZoneEquipment
DataSurfaces
DataSizing
DataZoneEquipment
DataGlobals
General
Psychrometrics
Arguments
None
Calls
Called By
Source Code
WriteZoneLoadComponentTable
Source Code
SUBROUTINE WriteZoneLoadComponentTable
          ! SUBROUTINE INFORMATION:
          !       AUTHOR         Jason Glazer
          !       DATE WRITTEN   March 2012
          !       MODIFIED       na
          !       RE-ENGINEERED  na
          ! PURPOSE OF THIS SUBROUTINE:
          !   Write the tables for the ZoneLoadComponentSummary and
          !   ZoneLoadComponentDetail reports which summarize the major
          !   load components for each zone in the building.
          ! METHODOLOGY EMPLOYED:
          !   Create arrays for the call to writeTable and then call it.
          !   This report actually consists of many sub-tables each with
          !   its own call to writeTable.
!
! The overall methodology is explained below:
!
! Determine decay curve - Pulse of radiant heat which is about 5% of lighting and
! equipment input [radiantPulseUsed(iZone)] for a single timestep a few hours after
! cooling or heat is scheduled on for each zone [radiantPulseTimestep(iZone)].
! The radiant heat received on each wall is stored [radiantPulseReceived(jSurface)].
! The load convected in the normal case [loadConvectedNormal(jSurface, kTime, mode)]
! and in the case with the pulse [loadConvectedWithPulse(jSurface, kTime, mode)].
! The difference divided by the pulse received by each surface
! [radiantPulseReceived(jSurface)] is stored in [decayCurve(jSurface,kTime,mode)].
!
! Determine delayed loads - From the last timestep of the peak load on the zone
! working backwards any radiant heat that was absorbed by the wall from an internal gain
! or solar gain is multiplied by the appropriate timesteps in the decay curve
! [decayCurve(jSurface,kTime,mode)] for timesteps that make up
! the number of averaged timesteps are used to determine the peak load
! [NumTimeStepsInAvg]. The sum for all surfaces in the zone are added together to
! determine the delayed load.
!
! Determine instant loads - Average the convective portion of the internal gains
! for the timesteps made up of the peak load period. Average those across the peak
! load period.
!
          ! REFERENCES:
          ! na
          ! USE STATEMENTS:
          ! na
USE DataHeatBalance,   ONLY: Zone
USE SQLiteProcedures, ONLY: CreateSQLiteTabularDataRecords
USE DataZoneEquipment, ONLY: ZoneEquipConfig
USE DataSurfaces, ONLY: Surface, TotSurfaces,ExternalEnvironment,Ground,GroundFCfactorMethod, &
                        OtherSideCoefNoCalcExt,OtherSideCoefCalcExt,OtherSideCondModeledExt, &
                        SurfaceClass_Wall,SurfaceClass_Floor,SurfaceClass_Roof, &
                        SurfaceClass_Door,OSC
USE DataSizing, ONLY: CalcFinalZoneSizing,NumTimeStepsInAvg,CoolPeakDateHrMin,HeatPeakDateHrMin
USE DataZoneEquipment, ONLY: ZoneEquipConfig
USE DataGlobals, ONLY: NumOfTimeStepInHour, CompLoadReportIsReq,ShowDecayCurvesInEIO
USE General, ONLY: MovingAvg
USE Psychrometrics,  ONLY: PsyTwbFnTdbWPb,PsyRhFnTdbWPb
IMPLICIT NONE
          ! SUBROUTINE ARGUMENT DEFINITIONS:
          ! na
          ! SUBROUTINE PARAMETER DEFINITIONS:
! These correspond to the columns in the load component table
INTEGER, PARAMETER :: cSensInst = 1
INTEGER, PARAMETER :: cSensDelay = 2
INTEGER, PARAMETER :: cSensRA = 3
INTEGER, PARAMETER :: cLatent = 4
INTEGER, PARAMETER :: cTotal = 5
INTEGER, PARAMETER :: cPerc = 6
!internal gains
INTEGER, PARAMETER :: rPeople =     1
INTEGER, PARAMETER :: rLights =     2
INTEGER, PARAMETER :: rEquip =      3
INTEGER, PARAMETER :: rRefrig =     4
INTEGER, PARAMETER :: rWaterUse =   5
INTEGER, PARAMETER :: rHvacLoss =   6
INTEGER, PARAMETER :: rPowerGen =   7
!misc
INTEGER, PARAMETER :: rInfil =      8
INTEGER, PARAMETER :: rZoneVent =   9
INTEGER, PARAMETER :: rIntZonMix =  10
!opaque surfaces
INTEGER, PARAMETER :: rRoof =       11
INTEGER, PARAMETER :: rIntZonCeil = 12
INTEGER, PARAMETER :: rOtherRoof =  13
INTEGER, PARAMETER :: rExtWall =    14
INTEGER, PARAMETER :: rIntZonWall = 15
INTEGER, PARAMETER :: rGrdWall =    16
INTEGER, PARAMETER :: rOtherWall =  17
INTEGER, PARAMETER :: rExtFlr =     18
INTEGER, PARAMETER :: rIntZonFlr =  19
INTEGER, PARAMETER :: rGrdFlr =     20
INTEGER, PARAMETER :: rOtherFlr =   21
!subsurfaces
INTEGER, PARAMETER :: rFeneCond =   22
INTEGER, PARAMETER :: rFeneSolr =   23
INTEGER, PARAMETER :: rOpqDoor =    24
!total
INTEGER, PARAMETER :: rGrdTot =     25
          ! na
          ! INTERFACE BLOCK SPECIFICATIONS:
          ! na
          ! DERIVED TYPE DEFINITIONS:
          ! na
          ! SUBROUTINE LOCAL VARIABLE DECLARATIONS:
INTEGER :: CoolDesSelected = 0  !design day selected for cooling
INTEGER :: HeatDesSelected = 0  !design day selected for heating
INTEGER :: timeCoolMax = 0 !Time Step at Cool max
INTEGER :: timeHeatMax = 0 !Time Step at Heat Max
INTEGER :: iZone = 0
INTEGER :: jTime = 0
INTEGER :: k = 0
INTEGER :: kSurf = 0
INTEGER :: numObj = 0
INTEGER :: objCount = 0
INTEGER :: ZoneNum = 0
INTEGER :: tempUnitConvIndex = 0
REAL(r64),ALLOCATABLE, DIMENSION(:) :: seqData  !raw data sequence that has not been averaged yet
REAL(r64),ALLOCATABLE, DIMENSION(:) :: avgData  !sequence data after averaging
INTEGER :: NumOfTimeStepInDay
REAL(r64),ALLOCATABLE, DIMENSION(:) :: delayOpaque !hold values for report for delayed opaque
REAL(r64) :: singleSurfDelay
REAL(r64),ALLOCATABLE, DIMENSION(:) :: totalColumn
REAL(r64),ALLOCATABLE, DIMENSION(:) :: percentColumn
REAL(r64),ALLOCATABLE, DIMENSION(:) :: grandTotalRow
REAL(r64) :: totalGrandTotal
REAL(r64) :: powerConversion
INTEGER :: tempConvIndx !temperature conversion index
CHARACTER(len=MaxNameLength) :: stringWithTemp
INTEGER :: curExtBoundCond
REAL(r64) :: mult !zone multiplier
! all arrays are in the format: (row, column)
CHARACTER(len=MaxNameLength),ALLOCATABLE, DIMENSION(:)     :: columnHead
INTEGER,ALLOCATABLE,DIMENSION(:)                           :: columnWidth
CHARACTER(len=MaxNameLength),ALLOCATABLE, DIMENSION(:)     :: rowHead
CHARACTER(len=MaxNameLength),ALLOCATABLE, DIMENSION(:,:)   :: tableBody
IF (displayZoneComponentLoadSummary .AND. CompLoadReportIsReq) THEN
  CALL ComputeDelayedComponents
  NumOfTimeStepInDay = NumOfTimeStepInHour*24
  ALLOCATE(seqData(NumOfTimeStepInDay))
  ALLOCATE(avgData(NumOfTimeStepInDay))
  ALLOCATE(delayOpaque(rGrdTot))
  ALLOCATE(totalColumn(rGrdTot))
  ALLOCATE(percentColumn(rGrdTot))
  ALLOCATE(grandTotalRow(cPerc))
  !establish unit conversion factors
  IF (unitsStyle .EQ. unitsStyleInchPound) THEN
    powerConversion = getSpecificUnitMultiplier('W','Btu/h') !or kBtuh?
    tempConvIndx = getSpecificUnitIndex('C','F')
  ELSE
    powerConversion = 1.0d0
    tempConvIndx = 0 !when zero is used with ConvertIP the value is returned unconverted
  END IF
  ! show the line definition for the decay curves
  IF (ShowDecayCurvesInEIO) THEN
    WRITE (OutputFileInits, '(A)') '! <Radiant to Convective Decay Curves for Cooling>,Zone Name, Surface Name, Time ' &
                  // '1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36'
    WRITE (OutputFileInits, '(A)') '! <Radiant to Convective Decay Curves for Heating>,Zone Name, Surface Name, Time ' &
                  // '1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36'
  END IF
  DO iZone = 1, NumOfZones
    IF (.not. ZoneEquipConfig(iZone)%IsControlled) CYCLE
    mult = Zone(iZone)%Multiplier * Zone(iZone)%ListMultiplier
    IF (mult .EQ. 0.0) mult = 1.0
    !
    !---- Cooling Peak Load Components Sub-Table
    !
    CALL WriteReportHeaders('Zone Component Load Summary',TRIM(Zone(iZone)%Name),isAverage)
    ALLOCATE(rowHead(rGrdTot))
    ALLOCATE(columnHead(cPerc))
    ALLOCATE(columnWidth(cPerc))
    columnWidth = 14 !array assignment - same for all columns
    ALLOCATE(tableBody(rGrdTot,cPerc))
    IF (unitsStyle .NE. unitsStyleInchPound) THEN
      columnHead(cSensInst) = 'Sensible - Instant [W]'
      columnHead(cSensDelay) = 'Sensible - Delayed [W]'
      columnHead(cSensRA) = 'Sensible - Return Air [W]'
      columnHead(cLatent) = 'Latent [W]'
      columnHead(cTotal) = 'Total [W]'
      columnHead(cPerc) = '%Grand Total'
    ELSE
      columnHead(cSensInst) = 'Sensible - Instant [Btu/h]'
      columnHead(cSensDelay) = 'Sensible - Delayed [Btu/h]'
      columnHead(cSensRA) = 'Sensible - Return Air [Btu/h]'
      columnHead(cLatent) = 'Latent [Btu/h]'
      columnHead(cTotal) = 'Total [Btu/h]'
      columnHead(cPerc) = '%Grand Total'
    END IF
    !internal gains
    rowHead(rPeople) = 'People'
    rowHead(rLights) = 'Lights'
    rowHead(rEquip) = 'Equipment'
    rowHead(rRefrig) = 'Refrigeration Equipment'
    rowHead(rWaterUse) = 'Water Use Equipment'
    rowHead(rPowerGen) = 'Power Generation Equipment'
    rowHead(rHvacLoss) = 'HVAC Equipment Losses'
    rowHead(rRefrig) = 'Refrigeration'
    !misc
    rowHead(rInfil) = 'Infiltration'
    rowHead(rZoneVent) = 'Zone Ventilation'
    rowHead(rIntZonMix) = 'Interzone Mixing'
    !opaque surfaces
    rowHead(rRoof) = 'Roof'
    rowHead(rIntZonCeil) = 'Interzone Ceiling'
    rowHead(rOtherRoof) = 'Other Roof'
    rowHead(rExtWall) = 'Exterior Wall'
    rowHead(rIntZonWall) = 'Interzone Wall'
    rowHead(rGrdWall) = 'Ground Contact Wall'
    rowHead(rOtherWall) = 'Other Wall'
    rowHead(rExtFlr) = 'Exterior Floor'
    rowHead(rIntZonFlr) = 'Interzone Floor'
    rowHead(rGrdFlr) = 'Ground Contact Floor'
    rowHead(rOtherFlr) = 'Other Floor'
    !subsurfaces
    rowHead(rFeneCond) = 'Fenestration Conduction'
    rowHead(rFeneSolr) = 'Fenestration Solar'
    rowHead(rOpqDoor) = 'Opaque Door'
    rowHead(rGrdTot) = 'Grand Total'
    tableBody = ''
    totalColumn = 0.0d0
    percentColumn = 0.0d0
    grandTotalRow = 0.0d0
    CoolDesSelected = CalcFinalZoneSizing(iZone)%CoolDDNum
    timeCoolMax = CalcFinalZoneSizing(iZone)%TimeStepNumAtCoolMax
    IF (CoolDesSelected .NE. 0 .AND. timeCoolMax .NE. 0) THEN
      !PEOPLE
      seqData = peopleInstantSeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rPeople,cSensInst)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rPeople) = totalColumn(rPeople) + AvgData(timeCoolMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeCoolMax)
      seqData = peopleLatentSeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rPeople,cLatent)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rPeople) = totalColumn(rPeople) + AvgData(timeCoolMax)
      grandTotalRow(cLatent) = grandTotalRow(cLatent) + AvgData(timeCoolMax)
      seqData = peopleDelaySeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rPeople,cSensDelay)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rPeople) = totalColumn(rPeople) + AvgData(timeCoolMax)
      grandTotalRow(cSensDelay) = grandTotalRow(cSensDelay) + AvgData(timeCoolMax)
      !LIGHTS
      seqData = lightInstantSeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rLights,cSensInst)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rLights) = totalColumn(rLights) + AvgData(timeCoolMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeCoolMax)
      seqData = lightRetAirSeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rLights,cSensRA)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rLights) = totalColumn(rLights) + AvgData(timeCoolMax)
      grandTotalRow(cSensRA) = grandTotalRow(cSensRA) + AvgData(timeCoolMax)
      seqData = lightDelaySeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rLights,cSensDelay)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rLights) = totalColumn(rLights) + AvgData(timeCoolMax)
      grandTotalRow(cSensDelay) = grandTotalRow(cSensDelay) + AvgData(timeCoolMax)
      !EQUIPMENT
      seqData = equipInstantSeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rEquip,cSensInst)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rEquip) = totalColumn(rEquip) + AvgData(timeCoolMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeCoolMax)
      seqData = equipLatentSeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rEquip,cLatent)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rEquip) = totalColumn(rEquip) + AvgData(timeCoolMax)
      grandTotalRow(cLatent) = grandTotalRow(cLatent) + AvgData(timeCoolMax)
      seqData = equipDelaySeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rEquip,cSensDelay)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rEquip) = totalColumn(rEquip) + AvgData(timeCoolMax)
      grandTotalRow(cSensDelay) = grandTotalRow(cSensDelay) + AvgData(timeCoolMax)
      !REFRIGERATION EQUIPMENT
      seqData = refrigInstantSeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rRefrig,cSensInst)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rRefrig) = totalColumn(rRefrig) + AvgData(timeCoolMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeCoolMax)
      seqData = refrigRetAirSeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rRefrig,cSensRA)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rRefrig) = totalColumn(rRefrig) + AvgData(timeCoolMax)
      grandTotalRow(cSensRA) = grandTotalRow(cSensRA) + AvgData(timeCoolMax)
      seqData = refrigLatentSeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rRefrig,cLatent)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rRefrig) = totalColumn(rRefrig) + AvgData(timeCoolMax)
      grandTotalRow(cLatent) = grandTotalRow(cLatent) + AvgData(timeCoolMax)
      !WATER USE EQUIPMENT
      seqData = waterUseInstantSeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rWaterUse,cSensInst)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rWaterUse) = totalColumn(rWaterUse) + AvgData(timeCoolMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeCoolMax)
      seqData = waterUseLatentSeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rWaterUse,cLatent)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rWaterUse) = totalColumn(rWaterUse) + AvgData(timeCoolMax)
      grandTotalRow(cLatent) = grandTotalRow(cLatent) + AvgData(timeCoolMax)
      !HVAC EQUIPMENT LOSSES
      seqData = hvacLossInstantSeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rHvacLoss,cSensInst)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rHvacLoss) = totalColumn(rHvacLoss) + AvgData(timeCoolMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeCoolMax)
      seqData = hvacLossDelaySeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rHvacLoss,cSensDelay)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rHvacLoss) = totalColumn(rHvacLoss) + AvgData(timeCoolMax)
      grandTotalRow(cSensDelay) = grandTotalRow(cSensDelay) + AvgData(timeCoolMax)
      !POWER GENERATION EQUIPMENT
      seqData = powerGenInstantSeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rPowerGen,cSensInst)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rPowerGen) = totalColumn(rPowerGen) + AvgData(timeCoolMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeCoolMax)
      seqData = powerGenDelaySeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rPowerGen,cSensDelay)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rPowerGen) = totalColumn(rPowerGen) + AvgData(timeCoolMax)
      grandTotalRow(cSensDelay) = grandTotalRow(cSensDelay) + AvgData(timeCoolMax)
      !INFILTRATION
      seqData = infilInstantSeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rInfil,cSensInst)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rInfil) = totalColumn(rInfil) + AvgData(timeCoolMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeCoolMax)
      seqData = infilLatentSeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rInfil,cLatent)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rInfil) = totalColumn(rInfil) + AvgData(timeCoolMax)
      grandTotalRow(cLatent) = grandTotalRow(cLatent) + AvgData(timeCoolMax)
      !ZONE VENTILATION
      seqData = zoneVentInstantSeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rZoneVent,cSensInst)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rZoneVent) = totalColumn(rZoneVent) + AvgData(timeCoolMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeCoolMax)
      seqData = zoneVentLatentSeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rZoneVent,cLatent)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rZoneVent) = totalColumn(rZoneVent) + AvgData(timeCoolMax)
      grandTotalRow(cLatent) = grandTotalRow(cLatent) + AvgData(timeCoolMax)
      !INTERZONE MIXING
      seqData = interZoneMixInstantSeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rIntZonMix,cSensInst)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rIntZonMix) = totalColumn(rIntZonMix) + AvgData(timeCoolMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeCoolMax)
      seqData = interZoneMixLatentSeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rIntZonMix,cLatent)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rIntZonMix) = totalColumn(rIntZonMix) + AvgData(timeCoolMax)
      grandTotalRow(cLatent) = grandTotalRow(cLatent) + AvgData(timeCoolMax)
      !FENESTRATION CONDUCTION
      seqData = feneCondInstantSeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rFeneCond,cSensInst)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rFeneCond) = totalColumn(rFeneCond) + AvgData(timeCoolMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeCoolMax)
      !FENESTRATION SOLAR
!      seqData = feneSolarInstantSeq(iZone,:,CoolDesSelected) * powerConversion
!      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
!      tableBody(rFeneSolr,cSensInst)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
!      totalColumn(rFeneSolr) = totalColumn(rFeneSolr) + AvgData(timeCoolMax)
!      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeCoolMax)
      seqData = feneSolarDelaySeq(iZone,:,CoolDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rFeneSolr,cSensDelay)  = TRIM(RealToStr(AvgData(timeCoolMax),2))
      totalColumn(rFeneSolr) = totalColumn(rFeneSolr) + AvgData(timeCoolMax)
      grandTotalRow(cSensDelay) = grandTotalRow(cSensDelay) + AvgData(timeCoolMax)
      !opaque surfaces - must combine individual surfaces by class and other side conditions
      delayOpaque = 0.0d0
      DO kSurf = 1,TotSurfaces
        IF (.NOT. Surface(kSurf)%HeatTransSurf) CYCLE ! Skip non-heat transfer surfaces
        IF (Surface(kSurf)%Zone .EQ. iZone) THEN
          curExtBoundCond = surface(kSurf)%ExtBoundCond
          !if exterior is other side coefficients using ground preprocessor terms then
          !set it to ground instead of other side coefficients
          IF (curExtBoundCond .EQ. OtherSideCoefNoCalcExt .OR. curExtBoundCond .EQ. OtherSideCoefCalcExt) THEN
            IF (SameString(OSC(Surface(kSurf)%OSCPtr)%Name(1:17), 'surfPropOthSdCoef')) THEN
              curExtBoundCond = Ground
            END IF
          END IF
          seqData = surfDelaySeq(kSurf,:,CoolDesSelected)
          CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
          singleSurfDelay = AvgData(timeCoolMax) * powerConversion
          SELECT CASE (surface(kSurf)%class)
            CASE (SurfaceClass_Wall)
              SELECT CASE (curExtBoundCond)
                CASE (ExternalEnvironment)
                  delayOpaque(rExtWall) = delayOpaque(rExtWall) + singleSurfDelay
                CASE (Ground,GroundFCfactorMethod)
                  delayOpaque(rGrdWall) = delayOpaque(rGrdWall) + singleSurfDelay
                CASE (OtherSideCoefNoCalcExt,OtherSideCoefCalcExt,OtherSideCondModeledExt)
                  delayOpaque(rOtherWall) = delayOpaque(rOtherWall) + singleSurfDelay
                CASE DEFAULT !interzone
                  delayOpaque(rIntZonWall) = delayOpaque(rIntZonWall) + singleSurfDelay
              END SELECT
            CASE (SurfaceClass_Floor)
              SELECT CASE (curExtBoundCond)
                CASE (ExternalEnvironment)
                  delayOpaque(rExtFlr) = delayOpaque(rExtFlr) + singleSurfDelay
                CASE (Ground,GroundFCfactorMethod)
                  delayOpaque(rGrdFlr) = delayOpaque(rGrdFlr) + singleSurfDelay
                CASE (OtherSideCoefNoCalcExt,OtherSideCoefCalcExt,OtherSideCondModeledExt)
                  delayOpaque(rOtherFlr) = delayOpaque(rOtherFlr) + singleSurfDelay
                CASE DEFAULT !interzone
                  delayOpaque(rIntZonFlr) = delayOpaque(rIntZonFlr) + singleSurfDelay
              END SELECT
            CASE (SurfaceClass_Roof)
              SELECT CASE (curExtBoundCond)
                CASE (ExternalEnvironment)
                  delayOpaque(rRoof) = delayOpaque(rRoof) + singleSurfDelay
                CASE (Ground,GroundFCfactorMethod,OtherSideCoefNoCalcExt,OtherSideCoefCalcExt,OtherSideCondModeledExt)
                  delayOpaque(rOtherRoof) = delayOpaque(rOtherRoof) + singleSurfDelay
                CASE DEFAULT !interzone
                  delayOpaque(rIntZonCeil) = delayOpaque(rIntZonCeil) + singleSurfDelay
              END SELECT
            CASE (SurfaceClass_Door)
              delayOpaque(rOpqDoor) = delayOpaque(rOpqDoor) + singleSurfDelay
          END SELECT
        END IF
      END DO
      DO k = rRoof,rOtherFlr
        tableBody(k,cSensDelay)  = TRIM(RealToStr(delayOpaque(k),2))
        totalColumn(k) = totalColumn(k) + delayOpaque(k)
        grandTotalRow(cSensDelay) = grandTotalRow(cSensDelay) + delayOpaque(k)
      END DO
      tableBody(rOpqDoor,cSensDelay) = TRIM(RealToStr(delayOpaque(rOpqDoor),2))
      totalColumn(rOpqDoor) = totalColumn(rOpqDoor) + delayOpaque(rOpqDoor)
      grandTotalRow(cSensDelay) = grandTotalRow(cSensDelay) + delayOpaque(rOpqDoor)
    END IF
    !GRAND TOTAL ROW
    totalGrandTotal = 0.0d0
    DO k = 1,cLatent
      tableBody(rGrdTot,k)  = TRIM(RealToStr(grandTotalRow(k),2))
      totalGrandTotal = totalGrandTotal + grandTotalRow(k)
    END DO
    tableBody(rGrdTot,cTotal)  = TRIM(RealToStr(totalGrandTotal,2))
    !TOTAL COLUMN AND PERCENT COLUMN
    DO k = 1,rOpqDoor !to last row before total
      tableBody(k,cTotal) = TRIM(RealToStr(totalColumn(k),2))
      IF (totalGrandTotal .NE. 0.0d0) THEN
        tableBody(k,cPerc) = TRIM(RealToStr(100 * totalColumn(k)/totalGrandTotal,2))
      END IF
    END DO
    CALL writeSubtitle('Estimated Cooling Peak Load Components')
    CALL writeTable(tableBody,rowHead,columnHead,columnWidth)
    CALL CreateSQLiteTabularDataRecords(tableBody,rowHead,columnHead,&
                                        'ZoneComponentLoadSummary',&
                                        TRIM(Zone(iZone)%Name),&
                                        'Estimated Cooling Peak Load Components')
    DEALLOCATE(columnHead)
    DEALLOCATE(rowHead)
    DEALLOCATE(columnWidth)
    DEALLOCATE(tableBody)
    !
    !---- Cooling Peak Conditions
    !
    ALLOCATE(rowHead(10))
    ALLOCATE(columnHead(1))
    ALLOCATE(columnWidth(1))
    columnWidth = 14 !array assignment - same for all columns
    ALLOCATE(tableBody(10,1))
    columnHead(1) = 'Value'
    IF (unitsStyle .NE. unitsStyleInchPound) THEN
      rowHead(1) = 'Time of Peak Load'
      rowHead(2) = 'Outside  Dry Bulb Temperature [C]'
      rowHead(3) = 'Outside  Wet Bulb Temperature [C]'
      rowHead(4) = 'Outside Humidity Ratio at Peak [kgWater/kgAir]'
      rowHead(5) = 'Zone Dry Bulb Temperature [C]'
      rowHead(6) = 'Zone Relative Humdity [%]'
      rowHead(7) = 'Zone Humidity Ratio at Peak [kgWater/kgAir]'
      rowHead(8) = 'Peak Design Sensible Load [W]'
      rowHead(9) = 'Estimated Instant + Delayed Sensible Load [W]'
      rowHead(10) = 'Difference [W]'
    ELSE
      rowHead(1) = 'Time of Peak Load'
      rowHead(2) = 'Outside  Dry Bulb Temperature [F]'
      rowHead(3) = 'Outside  Wet Bulb Temperature [F]'
      rowHead(4) = 'Outside Humidity Ratio at Peak [lbWater/lbAir]'
      rowHead(5) = 'Zone Dry Bulb Temperature [F]'
      rowHead(6) = 'Zone Relative Humdity [%]'
      rowHead(7) = 'Zone Humidity Ratio at Peak [lbWater/lbAir]'
      rowHead(8) = 'Peak Design Sensible Load [Btu/h]'
      rowHead(9) = 'Estimated Instant + Delayed Sensible Load [Btu/h]'
      rowHead(10) = 'Difference [Btu/h]'
    END IF
    tableBody = ''
    IF (timeCoolMax .NE. 0) THEN
      !Time of Peak Load
      tableBody(1,1) = TRIM(CoolPeakDateHrMin(iZone))
      !Outside  Dry Bulb Temperature
      tableBody(2,1) = TRIM(RealToStr(convertIP(tempConvIndx,CalcFinalZoneSizing(iZone)%CoolOutTempSeq(timeCoolMax)),2))
      !Outside  Wet Bulb Temperature
      !use standard sea level air pressure because air pressure is not tracked with sizing data
      IF (CalcFinalZoneSizing(iZone)%CoolOutHumRatSeq(timeCoolMax) .LT. 1.0d0 .AND.     &
          CalcFinalZoneSizing(iZone)%CoolOutHumRatSeq(timeCoolMax) .GT. 0.0d0) THEN
        tableBody(3,1) = TRIM(RealToStr(convertIP(tempConvIndx, &
                                     PsyTwbFnTdbWPb(CalcFinalZoneSizing(iZone)%CoolOutTempSeq(timeCoolMax), &
                                     CalcFinalZoneSizing(iZone)%CoolOutHumRatSeq(timeCoolMax), &
                                     101325.0d0))  ,2))
      END IF
      !Outside Humidity Ratio at Peak
      tableBody(4,1) = TRIM(RealToStr(CalcFinalZoneSizing(iZone)%CoolOutHumRatSeq(timeCoolMax),5))
      !Zone Dry Bulb Temperature
      tableBody(5,1) = TRIM(RealToStr(convertIP(tempConvIndx,CalcFinalZoneSizing(iZone)%CoolZoneTempSeq(timeCoolMax)),2))
      !Zone Relative Humdity
      !use standard sea level air pressure because air pressure is not tracked with sizing data
      tableBody(6,1) = TRIM(RealToStr(100 * PsyRhFnTdbWPb(CalcFinalZoneSizing(iZone)%CoolZoneTempSeq(timeCoolMax), &
                                                     CalcFinalZoneSizing(iZone)%CoolZoneHumRatSeq(timeCoolMax), &
                                                     101325.0d0)  ,2))
      !Zone Humidity Ratio at Peak
      tableBody(7,1) = TRIM(RealToStr(CalcFinalZoneSizing(iZone)%CoolZoneHumRatSeq(timeCoolMax),5))
    END IF
    !Peak Design Sensible Load
    tableBody(8,1) = TRIM(RealToStr((CalcFinalZoneSizing(iZone)%DesCoolLoad / mult) * powerConversion,2))
    !Estimated Instant + Delayed Sensible Load
    tableBody(9,1) = TRIM(RealToStr(grandTotalRow(cSensInst) + grandTotalRow(cSensDelay),2))
    !Difference
    tableBody(10,1) = TRIM(RealToStr((CalcFinalZoneSizing(iZone)%DesCoolLoad / mult) * powerConversion &
                         - (grandTotalRow(cSensInst) + grandTotalRow(cSensDelay)),2))
    CALL writeSubtitle('Cooling Peak Conditions')
    CALL writeTable(tableBody,rowHead,columnHead,columnWidth)
    CALL CreateSQLiteTabularDataRecords(tableBody,rowHead,columnHead,&
                                        'ZoneComponentLoadSummary',&
                                        TRIM(Zone(iZone)%Name),&
                                        'Cooling Peak Conditions')
    DEALLOCATE(columnHead)
    DEALLOCATE(rowHead)
    DEALLOCATE(columnWidth)
    DEALLOCATE(tableBody)
!    !
!    !---- Radiant to Convective Decay Curves for Cooling
!    !
!    numObj = 0
!    !determine the number of surfaces to include
!    DO kSurf = 1, TotSurfaces
!      ZoneNum = Surface(kSurf)%Zone
!      IF (ZoneNum .NE. iZone) CYCLE
!      IF (ZoneNum .EQ. 0) CYCLE
!      IF (.not. ZoneEquipConfig(ZoneNum)%IsControlled) CYCLE
!      numObj = numObj + 1
!    END DO
!
!    ALLOCATE(rowHead(numObj))
!    ALLOCATE(columnHead(16))
!    ALLOCATE(columnWidth(16))
!    columnWidth = 14 !array assignment - same for all columns
!    ALLOCATE(tableBody(numObj,16))
!
!    columnHead(1) = 'Time 1'
!    columnHead(2) = 'Time 2'
!    columnHead(3) = 'Time 3'
!    columnHead(4) = 'Time 4'
!    columnHead(5) = 'Time 5'
!    columnHead(6) = 'Time 6'
!    columnHead(7) = 'Time 7'
!    columnHead(8) = 'Time 8'
!    columnHead(9) = 'Time 9'
!    columnHead(10) = 'Time 10'
!    columnHead(11) = 'Time 11'
!    columnHead(12) = 'Time 12'
!    columnHead(13) = 'Time 13'
!    columnHead(14) = 'Time 14'
!    columnHead(15) = 'Time 15'
!    columnHead(16) = 'Time 16'
!
!    tableBody = ''
!    objCount = 0
!    DO kSurf = 1, TotSurfaces
!      ZoneNum = Surface(kSurf)%Zone
!      IF (ZoneNum .NE. iZone) CYCLE
!      IF (ZoneNum .EQ. 0) CYCLE
!      IF (.not. ZoneEquipConfig(ZoneNum)%IsControlled) CYCLE
!      objCount = objCount + 1
!      rowHead(objCount) = TRIM(Surface(kSurf)%Name)
!      DO jTime = 1, 16
!        tableBody(objCount,jTime) = TRIM(RealToStr(decayCurveCool(kSurf,jTime),3))
!      END DO
!    END DO
!
!    CALL writeSubtitle('Radiant to Convective Decay Curves for Cooling')
!    CALL writeTable(tableBody,rowHead,columnHead,columnWidth)
!    CALL CreateSQLiteTabularDataRecords(tableBody,rowHead,columnHead,&
!                                        'ZoneComponentLoadDetail',&
!                                        TRIM(Zone(iZone)%Name),&
!                                        'Radiant to Convective Decay Curves for Cooling')
!
!    DEALLOCATE(columnHead)
!    DEALLOCATE(rowHead)
!    DEALLOCATE(columnWidth)
!    DEALLOCATE(tableBody)
    ! Put the decay curve into the EIO file
    IF (ShowDecayCurvesInEIO) THEN
      DO kSurf = 1, TotSurfaces
        ZoneNum = Surface(kSurf)%Zone
        IF (ZoneNum .NE. iZone) CYCLE
        IF (ZoneNum .EQ. 0) CYCLE
        IF (.not. ZoneEquipConfig(ZoneNum)%IsControlled) CYCLE
        WRITE (OutputFileInits, '(4A)',ADVANCE='NO')  'Radiant to Convective Decay Curves for Cooling,' &
                            ,TRIM(Zone(iZone)%Name),',',TRIM(Surface(kSurf)%Name)
        DO jTime = 1, MIN(NumOfTimeStepInHour*24,36)
          WRITE(OutputFileInits,'(A,F6.3)',ADVANCE='NO') ',',decayCurveCool(kSurf,jTime)
        END DO
        WRITE(OutputFileInits,'()',ADVANCE='YES') !put a line feed at the end of the line
      END DO
    END IF
    !
    !---- Heating Peak Load Components Sub-Table
    !
    ALLOCATE(rowHead(rGrdTot))
    ALLOCATE(columnHead(cPerc))
    ALLOCATE(columnWidth(cPerc))
    columnWidth = 14 !array assignment - same for all columns
    ALLOCATE(tableBody(rGrdTot,cPerc))
    IF (unitsStyle .NE. unitsStyleInchPound) THEN
      columnHead(cSensInst) = 'Sensible - Instant [W]'
      columnHead(cSensDelay) = 'Sensible - Delayed [W]'
      columnHead(cSensRA) = 'Sensible - Return Air [W]'
      columnHead(cLatent) = 'Latent [W]'
      columnHead(cTotal) = 'Total [W]'
      columnHead(cPerc) = '%Grand Total'
    ELSE
      columnHead(cSensInst) = 'Sensible - Instant [Btu/h]'
      columnHead(cSensDelay) = 'Sensible - Delayed [Btu/h]'
      columnHead(cSensRA) = 'Sensible - Return Air [Btu/h]'
      columnHead(cLatent) = 'Latent [Btu/h]'
      columnHead(cTotal) = 'Total [Btu/h]'
      columnHead(cPerc) = '%Grand Total'
    END IF
    !internal gains
    rowHead(rPeople) = 'People'
    rowHead(rLights) = 'Lights'
    rowHead(rEquip) = 'Equipment'
    rowHead(rRefrig) = 'Refrigeration Equipment'
    rowHead(rWaterUse) = 'Water Use Equipment'
    rowHead(rPowerGen) = 'Power Generation Equipment'
    rowHead(rHvacLoss) = 'HVAC Equipment Losses'
    rowHead(rRefrig) = 'Refrigeration'
    !misc
    rowHead(rInfil) = 'Infiltration'
    rowHead(rZoneVent) = 'Zone Ventilation'
    rowHead(rIntZonMix) = 'Interzone Mixing'
    !opaque surfaces
    rowHead(rRoof) = 'Roof'
    rowHead(rIntZonCeil) = 'Interzone Ceiling'
    rowHead(rOtherRoof) = 'Other Roof'
    rowHead(rExtWall) = 'Exterior Wall'
    rowHead(rIntZonWall) = 'Interzone Wall'
    rowHead(rGrdWall) = 'Ground Contact Wall'
    rowHead(rOtherWall) = 'Other Wall'
    rowHead(rExtFlr) = 'Exterior Floor'
    rowHead(rIntZonFlr) = 'Interzone Floor'
    rowHead(rGrdFlr) = 'Ground Contact Floor'
    rowHead(rOtherFlr) = 'Other Floor'
    !subsurfaces
    rowHead(rFeneCond) = 'Fenestration Conduction'
    rowHead(rFeneSolr) = 'Fenestration Solar'
    rowHead(rOpqDoor) = 'Opaque Door'
    rowHead(rGrdTot) = 'Grand Total'
    tableBody = ''
    totalColumn = 0.0d0
    percentColumn = 0.0d0
    grandTotalRow = 0.0d0
    HeatDesSelected = CalcFinalZoneSizing(iZone)%HeatDDNum
    timeHeatMax = CalcFinalZoneSizing(iZone)%TimeStepNumAtHeatMax
    IF (HeatDesSelected .NE. 0 .AND. timeHeatMax .NE. 0) THEN
      !PEOPLE
      seqData = peopleInstantSeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rPeople,cSensInst)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rPeople) = totalColumn(rPeople) + AvgData(timeHeatMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeHeatMax)
      seqData = peopleLatentSeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rPeople,cLatent)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rPeople) = totalColumn(rPeople) + AvgData(timeHeatMax)
      grandTotalRow(cLatent) = grandTotalRow(cLatent) + AvgData(timeHeatMax)
      seqData = peopleDelaySeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rPeople,cSensDelay)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rPeople) = totalColumn(rPeople) + AvgData(timeHeatMax)
      grandTotalRow(cSensDelay) = grandTotalRow(cSensDelay) + AvgData(timeHeatMax)
      !LIGHTS
      seqData = lightInstantSeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rLights,cSensInst)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rLights) = totalColumn(rLights) + AvgData(timeHeatMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeHeatMax)
      seqData = lightRetAirSeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rLights,cSensRA)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rLights) = totalColumn(rLights) + AvgData(timeHeatMax)
      grandTotalRow(cSensRA) = grandTotalRow(cSensRA) + AvgData(timeHeatMax)
      seqData = lightDelaySeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rLights,cSensDelay)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rLights) = totalColumn(rLights) + AvgData(timeHeatMax)
      grandTotalRow(cSensDelay) = grandTotalRow(cSensDelay) + AvgData(timeHeatMax)
      !EQUIPMENT
      seqData = equipInstantSeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rEquip,cSensInst)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rEquip) = totalColumn(rEquip) + AvgData(timeHeatMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeHeatMax)
      seqData = equipLatentSeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rEquip,cLatent)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rEquip) = totalColumn(rEquip) + AvgData(timeHeatMax)
      grandTotalRow(cLatent) = grandTotalRow(cLatent) + AvgData(timeHeatMax)
      seqData = equipDelaySeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rEquip,cSensDelay)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rEquip) = totalColumn(rEquip) + AvgData(timeHeatMax)
      grandTotalRow(cSensDelay) = grandTotalRow(cSensDelay) + AvgData(timeHeatMax)
      !REFRIGERATION EQUIPMENT
      seqData = refrigInstantSeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rRefrig,cSensInst)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rRefrig) = totalColumn(rRefrig) + AvgData(timeHeatMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeHeatMax)
      seqData = refrigRetAirSeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rRefrig,cSensRA)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rRefrig) = totalColumn(rRefrig) + AvgData(timeHeatMax)
      grandTotalRow(cSensRA) = grandTotalRow(cSensRA) + AvgData(timeHeatMax)
      seqData = refrigLatentSeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rRefrig,cLatent)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rRefrig) = totalColumn(rRefrig) + AvgData(timeHeatMax)
      grandTotalRow(cLatent) = grandTotalRow(cLatent) + AvgData(timeHeatMax)
      !WATER USE EQUIPMENT
      seqData = waterUseInstantSeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rWaterUse,cSensInst)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rWaterUse) = totalColumn(rWaterUse) + AvgData(timeHeatMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeHeatMax)
      seqData = waterUseLatentSeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rWaterUse,cLatent)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rWaterUse) = totalColumn(rWaterUse) + AvgData(timeHeatMax)
      grandTotalRow(cLatent) = grandTotalRow(cLatent) + AvgData(timeHeatMax)
      !HVAC EQUIPMENT LOSSES
      seqData = hvacLossInstantSeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rHvacLoss,cSensInst)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rHvacLoss) = totalColumn(rHvacLoss) + AvgData(timeHeatMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeHeatMax)
      seqData = hvacLossDelaySeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rHvacLoss,cSensDelay)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rHvacLoss) = totalColumn(rHvacLoss) + AvgData(timeHeatMax)
      grandTotalRow(cSensDelay) = grandTotalRow(cSensDelay) + AvgData(timeHeatMax)
      !POWER GENERATION EQUIPMENT
      seqData = powerGenInstantSeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rPowerGen,cSensInst)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rPowerGen) = totalColumn(rPowerGen) + AvgData(timeHeatMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeHeatMax)
      seqData = powerGenDelaySeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rPowerGen,cSensDelay)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rPowerGen) = totalColumn(rPowerGen) + AvgData(timeHeatMax)
      grandTotalRow(cSensDelay) = grandTotalRow(cSensDelay) + AvgData(timeHeatMax)
      !INFILTRATION
      seqData = infilInstantSeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rInfil,cSensInst)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rInfil) = totalColumn(rInfil) + AvgData(timeHeatMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeHeatMax)
      seqData = infilLatentSeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rInfil,cLatent)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rInfil) = totalColumn(rInfil) + AvgData(timeHeatMax)
      grandTotalRow(cLatent) = grandTotalRow(cLatent) + AvgData(timeHeatMax)
      !ZONE VENTILATION
      seqData = zoneVentInstantSeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rZoneVent,cSensInst)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rZoneVent) = totalColumn(rZoneVent) + AvgData(timeHeatMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeHeatMax)
      seqData = zoneVentLatentSeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rZoneVent,cLatent)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rZoneVent) = totalColumn(rZoneVent) + AvgData(timeHeatMax)
      grandTotalRow(cLatent) = grandTotalRow(cLatent) + AvgData(timeHeatMax)
      !INTERZONE MIXING
      seqData = interZoneMixInstantSeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rIntZonMix,cSensInst)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rIntZonMix) = totalColumn(rIntZonMix) + AvgData(timeHeatMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeHeatMax)
      seqData = interZoneMixLatentSeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rIntZonMix,cLatent)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rIntZonMix) = totalColumn(rIntZonMix) + AvgData(timeHeatMax)
      grandTotalRow(cLatent) = grandTotalRow(cLatent) + AvgData(timeHeatMax)
      !FENESTRATION CONDUCTION
      seqData = feneCondInstantSeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rFeneCond,cSensInst)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rFeneCond) = totalColumn(rFeneCond) + AvgData(timeHeatMax)
      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeHeatMax)
      !FENESTRATION SOLAR
!      seqData = feneSolarInstantSeq(iZone,:,HeatDesSelected) * powerConversion
!      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
!      tableBody(rFeneSolr,cSensInst)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
!      totalColumn(rFeneSolr) = totalColumn(rFeneSolr) + AvgData(timeHeatMax)
!      grandTotalRow(cSensInst) = grandTotalRow(cSensInst) + AvgData(timeHeatMax)
      seqData = feneSolarDelaySeq(iZone,:,HeatDesSelected) * powerConversion
      CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
      tableBody(rFeneSolr,cSensDelay)  = TRIM(RealToStr(AvgData(timeHeatMax),2))
      totalColumn(rFeneSolr) = totalColumn(rFeneSolr) + AvgData(timeHeatMax)
      grandTotalRow(cSensDelay) = grandTotalRow(cSensDelay) + AvgData(timeHeatMax)
      !opaque surfaces - must combine individual surfaces by class and other side conditions
      delayOpaque = 0.0d0
      DO kSurf = 1,TotSurfaces
        IF (.NOT. Surface(kSurf)%HeatTransSurf) CYCLE ! Skip non-heat transfer surfaces
        IF (Surface(kSurf)%Zone .EQ. iZone) THEN
          curExtBoundCond = surface(kSurf)%ExtBoundCond
          !if exterior is other side coefficients using ground preprocessor terms then
          !set it to ground instead of other side coefficients
          IF (curExtBoundCond .EQ. OtherSideCoefNoCalcExt .OR. curExtBoundCond .EQ. OtherSideCoefCalcExt) THEN
            IF (SameString(OSC(Surface(kSurf)%OSCPtr)%Name(1:17), 'surfPropOthSdCoef')) THEN
              curExtBoundCond = Ground
            END IF
          END IF
          seqData = surfDelaySeq(kSurf,:,HeatDesSelected)
          CALL MovingAvg(seqData,NumOfTimeStepInDay,NumTimeStepsInAvg,AvgData)
          singleSurfDelay = AvgData(timeHeatMax) * powerConversion
          SELECT CASE (surface(kSurf)%class)
            CASE (SurfaceClass_Wall)
              SELECT CASE (curExtBoundCond)
                CASE (ExternalEnvironment)
                  delayOpaque(rExtWall) = delayOpaque(rExtWall) + singleSurfDelay
                CASE (Ground,GroundFCfactorMethod)
                  delayOpaque(rGrdWall) = delayOpaque(rGrdWall) + singleSurfDelay
                CASE (OtherSideCoefNoCalcExt,OtherSideCoefCalcExt,OtherSideCondModeledExt)
                  delayOpaque(rOtherWall) = delayOpaque(rOtherWall) + singleSurfDelay
                CASE DEFAULT !interzone
                  delayOpaque(rIntZonWall) = delayOpaque(rIntZonWall) + singleSurfDelay
              END SELECT
            CASE (SurfaceClass_Floor)
              SELECT CASE (curExtBoundCond)
                CASE (ExternalEnvironment)
                  delayOpaque(rExtFlr) = delayOpaque(rExtFlr) + singleSurfDelay
                CASE (Ground,GroundFCfactorMethod)
                  delayOpaque(rGrdFlr) = delayOpaque(rGrdFlr) + singleSurfDelay
                CASE (OtherSideCoefNoCalcExt,OtherSideCoefCalcExt,OtherSideCondModeledExt)
                  delayOpaque(rOtherFlr) = delayOpaque(rOtherFlr) + singleSurfDelay
                CASE DEFAULT !interzone
                  delayOpaque(rIntZonFlr) = delayOpaque(rIntZonFlr) + singleSurfDelay
              END SELECT
            CASE (SurfaceClass_Roof)
              SELECT CASE (curExtBoundCond)
                CASE (ExternalEnvironment)
                  delayOpaque(rRoof) = delayOpaque(rRoof) + singleSurfDelay
                CASE (Ground,GroundFCfactorMethod,OtherSideCoefNoCalcExt,OtherSideCoefCalcExt,OtherSideCondModeledExt)
                  delayOpaque(rOtherRoof) = delayOpaque(rOtherRoof) + singleSurfDelay
                CASE DEFAULT !interzone
                  delayOpaque(rIntZonCeil) = delayOpaque(rIntZonCeil) + singleSurfDelay
              END SELECT
            CASE (SurfaceClass_Door)
              delayOpaque(rOpqDoor) = delayOpaque(rOpqDoor) + singleSurfDelay
          END SELECT
        END IF
      END DO
      DO k = rRoof,rOtherFlr
        tableBody(k,cSensDelay)  = TRIM(RealToStr(delayOpaque(k),2))
        totalColumn(k) = totalColumn(k) + delayOpaque(k)
        grandTotalRow(cSensDelay) = grandTotalRow(cSensDelay) + delayOpaque(k)
      END DO
      tableBody(rOpqDoor,cSensDelay) = TRIM(RealToStr(delayOpaque(rOpqDoor),2))
      totalColumn(rOpqDoor) = totalColumn(rOpqDoor) + delayOpaque(rOpqDoor)
      grandTotalRow(cSensDelay) = grandTotalRow(cSensDelay) + delayOpaque(rOpqDoor)
    END IF
    !GRAND TOTAL ROW
    totalGrandTotal = 0.0d0
    DO k = 1,cLatent
      tableBody(rGrdTot,k)  = TRIM(RealToStr(grandTotalRow(k),2))
      totalGrandTotal = totalGrandTotal + grandTotalRow(k)
    END DO
    tableBody(rGrdTot,cTotal)  = TRIM(RealToStr(totalGrandTotal,2))
    !TOTAL COLUMN AND PERCENT COLUMN
    DO k = 1,rOpqDoor !to last row before total
      tableBody(k,cTotal) = TRIM(RealToStr(totalColumn(k),2))
      IF (totalGrandTotal .NE. 0.0d0) THEN
        tableBody(k,cPerc) = TRIM(RealToStr(100 * totalColumn(k)/totalGrandTotal,2))
      END IF
    END DO
    CALL writeSubtitle('Estimated Heating Peak Load Components')
    CALL writeTable(tableBody,rowHead,columnHead,columnWidth)
    CALL CreateSQLiteTabularDataRecords(tableBody,rowHead,columnHead,&
                                        'ZoneComponentLoadSummary',&
                                        TRIM(Zone(iZone)%Name),&
                                        'Estimated Heating Peak Load Components')
    DEALLOCATE(columnHead)
    DEALLOCATE(rowHead)
    DEALLOCATE(columnWidth)
    DEALLOCATE(tableBody)
    !
    !---- Heating Peak Conditions Sub-Table
    !
    ALLOCATE(rowHead(10))
    ALLOCATE(columnHead(1))
    ALLOCATE(columnWidth(1))
    columnWidth = 14 !array assignment - same for all columns
    ALLOCATE(tableBody(10,1))
    columnHead(1) = 'Value'
    IF (unitsStyle .NE. unitsStyleInchPound) THEN
      rowHead(1) = 'Time of Peak Load'
      rowHead(2) = 'Outside  Dry Bulb Temperature [C]'
      rowHead(3) = 'Outside  Wet Bulb Temperature [C]'
      rowHead(4) = 'Outside Humidity Ratio at Peak [kgWater/kgAir]'
      rowHead(5) = 'Zone Dry Bulb Temperature [C]'
      rowHead(6) = 'Zone Relative Humdity [%]'
      rowHead(7) = 'Zone Humidity Ratio at Peak [kgWater/kgAir]'
      rowHead(8) = 'Peak Design Sensible Load [W]'
      rowHead(9) = 'Estimated Instant + Delayed Sensible Load [W]'
      rowHead(10) = 'Difference [W]'
    ELSE
      rowHead(1) = 'Time of Peak Load'
      rowHead(2) = 'Outside  Dry Bulb Temperature [F]'
      rowHead(3) = 'Outside  Wet Bulb Temperature [F]'
      rowHead(4) = 'Outside Humidity Ratio at Peak [lbWater/lbAir]'
      rowHead(5) = 'Zone Dry Bulb Temperature [F]'
      rowHead(6) = 'Zone Relative Humdity [%]'
      rowHead(7) = 'Zone Humidity Ratio at Peak [lbWater/lbAir]'
      rowHead(8) = 'Peak Design Sensible Load [Btu/h]'
      rowHead(9) = 'Estimated Instant + Delayed Sensible Load [Btu/h]'
      rowHead(10) = 'Difference [Btu/h]'
    END IF
    tableBody = ''
    IF (timeHeatMax .NE. 0) THEN
       !Time of Peak Load
      tableBody(1,1) = TRIM(HeatPeakDateHrMin(iZone))
      !Outside  Dry Bulb Temperature
      tableBody(2,1) = TRIM(RealToStr(convertIP(tempConvIndx,CalcFinalZoneSizing(iZone)%HeatOutTempSeq(timeHeatMax)),2))
      !Outside  Wet Bulb Temperature
      !use standard sea level air pressure because air pressure is not tracked with sizing data
      IF (CalcFinalZoneSizing(iZone)%HeatOutHumRatSeq(timeHeatMax) .LT. 1.0d0 .AND.       &
          CalcFinalZoneSizing(iZone)%HeatOutHumRatSeq(timeHeatMax) .GT. 0.0d0) THEN
        tableBody(3,1) = TRIM(RealToStr(convertIP(tempConvIndx, &
                                       PsyTwbFnTdbWPb(CalcFinalZoneSizing(iZone)%HeatOutTempSeq(timeHeatMax), &
                                       CalcFinalZoneSizing(iZone)%HeatOutHumRatSeq(timeHeatMax), &
                                       101325.0d0))  ,2))
      END IF
      !Humidity Ratio at Peak
      tableBody(4,1) = TRIM(RealToStr(CalcFinalZoneSizing(iZone)%HeatOutHumRatSeq(timeHeatMax),5))
      !Zone Dry Bulb Temperature
      tableBody(5,1) = TRIM(RealToStr(convertIP(tempConvIndx,CalcFinalZoneSizing(iZone)%HeatZoneTempSeq(timeHeatMax)),2))
      !Zone Relative Temperature
      !use standard sea level air pressure because air pressure is not tracked with sizing data
      tableBody(6,1) = TRIM(RealToStr(100 * PsyRhFnTdbWPb(CalcFinalZoneSizing(iZone)%HeatZoneTempSeq(timeHeatMax), &
                                                     CalcFinalZoneSizing(iZone)%HeatZoneHumRatSeq(timeHeatMax), &
                                                     101325.0d0)  ,2))
      !Zone Relative Humdity
      tableBody(7,1) = TRIM(RealToStr(CalcFinalZoneSizing(iZone)%HeatZoneHumRatSeq(timeHeatMax),5))
    END IF
    !Peak Design Sensible Load
    tableBody(8,1) = TRIM(RealToStr((-CalcFinalZoneSizing(iZone)%DesHeatLoad / mult) * powerConversion,2))    !change sign
    !Estimated Instant + Delayed Sensible Load
    tableBody(9,1) = TRIM(RealToStr(grandTotalRow(cSensInst) + grandTotalRow(cSensDelay),2))
    !Difference
    tableBody(10,1) = TRIM(RealToStr((-CalcFinalZoneSizing(iZone)%DesHeatLoad /mult) * powerConversion &
                             - (grandTotalRow(cSensInst) + grandTotalRow(cSensDelay)),2))
    CALL writeSubtitle('Heating Peak Conditions')
    CALL writeTable(tableBody,rowHead,columnHead,columnWidth)
    CALL CreateSQLiteTabularDataRecords(tableBody,rowHead,columnHead,&
                                        'ZoneComponentLoadSummary',&
                                        TRIM(Zone(iZone)%Name),&
                                        'Heating Peak Conditions')
    DEALLOCATE(columnHead)
    DEALLOCATE(rowHead)
    DEALLOCATE(columnWidth)
    DEALLOCATE(tableBody)
!    !
!    !---- Radiant to Convective Decay Curves for Heating
!    !
!    numObj = 0
!    !determine the number of surfaces to include
!    DO kSurf = 1, TotSurfaces
!      ZoneNum = Surface(kSurf)%Zone
!      IF (ZoneNum .NE. iZone) CYCLE
!      IF (ZoneNum .EQ. 0) CYCLE
!      IF (.not. ZoneEquipConfig(ZoneNum)%IsControlled) CYCLE
!      numObj = numObj + 1
!    END DO
!
!    ALLOCATE(rowHead(numObj))
!    ALLOCATE(columnHead(16))
!    ALLOCATE(columnWidth(16))
!    columnWidth = 14 !array assignment - same for all columns
!    ALLOCATE(tableBody(numObj,16))
!
!    columnHead(1) = 'Time 1'
!    columnHead(2) = 'Time 2'
!    columnHead(3) = 'Time 3'
!    columnHead(4) = 'Time 4'
!    columnHead(5) = 'Time 5'
!    columnHead(6) = 'Time 6'
!    columnHead(7) = 'Time 7'
!    columnHead(8) = 'Time 8'
!    columnHead(9) = 'Time 9'
!    columnHead(10) = 'Time 10'
!    columnHead(11) = 'Time 11'
!    columnHead(12) = 'Time 12'
!    columnHead(13) = 'Time 13'
!    columnHead(14) = 'Time 14'
!    columnHead(15) = 'Time 15'
!    columnHead(16) = 'Time 16'
!
!    tableBody = ''
!    objCount = 0
!    DO kSurf = 1, TotSurfaces
!      ZoneNum = Surface(kSurf)%Zone
!      IF (ZoneNum .NE. iZone) CYCLE
!      IF (ZoneNum .EQ. 0) CYCLE
!      IF (.not. ZoneEquipConfig(ZoneNum)%IsControlled) CYCLE
!      objCount = objCount + 1
!      rowHead(objCount) = TRIM(Surface(kSurf)%Name)
!      DO jTime = 1, 16
!        tableBody(objCount,jTime) = TRIM(RealToStr(decayCurveHeat(kSurf,jTime),3))
!      END DO
!    END DO
!
!    CALL writeSubtitle('Radiant to Convective Decay Curves for Heating')
!    CALL writeTable(tableBody,rowHead,columnHead,columnWidth)
!    CALL CreateSQLiteTabularDataRecords(tableBody,rowHead,columnHead,&
!                                        'ZoneComponentLoadDetail',&
!                                        TRIM(Zone(iZone)%Name),&
!                                        'Radiant to Convective Decay Curves for Heating')
!
!    DEALLOCATE(columnHead)
!    DEALLOCATE(rowHead)
!    DEALLOCATE(columnWidth)
!    DEALLOCATE(tableBody)
    ! Put the decay curve into the EIO file
    IF (ShowDecayCurvesInEIO) THEN
      DO kSurf = 1, TotSurfaces
        ZoneNum = Surface(kSurf)%Zone
        IF (ZoneNum .NE. iZone) CYCLE
        IF (ZoneNum .EQ. 0) CYCLE
        IF (.not. ZoneEquipConfig(ZoneNum)%IsControlled) CYCLE
        WRITE (OutputFileInits, '(4A)',ADVANCE='NO')  'Radiant to Convective Decay Curves for Heating,', &
                                       TRIM(Zone(iZone)%Name),',',TRIM(Surface(kSurf)%Name)
        DO jTime = 1, MIN(NumOfTimeStepInHour*24,36)
          WRITE(OutputFileInits,'(A,F6.3)',ADVANCE='NO') ',', decayCurveHeat(kSurf,jTime)
        END DO
        WRITE(OutputFileInits,'()',ADVANCE='YES') !put a line feed at the end of the line
      END DO
    END IF
  END DO
END IF
END SUBROUTINE WriteZoneLoadComponentTable
All Procedures
AbortEnergyPlus AbsoluteAirMass ActivateDemandManagers ActivateEMSControls AddBlankKeys addChargesToOperand AddCompSizeTableEntry AddEndUseSubcategory AddError addFootNoteSubTable AddInstruction AddMeter addMonthlyCharge AddMonthlyFieldSetInput AddMonthlyReport AddNeighborInformation AddObjectDefandParse addOperand AddRecordFromSection AddRecordToOutputVariableStructure AddSectionDef AddShadowRelateTableEntry AddSQLiteComponentSizingRecord AddSQLiteComponentSizingRecord AddSQLiteSystemSizingRecord AddSQLiteSystemSizingRecord AddSQLiteZoneSizingRecord AddSQLiteZoneSizingRecord AddTOCEntry AddTOCZoneLoadComponentTable AddToOutputVariableList AddVariablesForMonthlyReport AddVariableSlatBlind AddWindow AdjustAirSetpointsforOpTempCntrl AdjustCBF AdjustCBF AdjustChangeInLoadByEMSControls AdjustChangeInLoadByHowServed AdjustChangeInLoadForLastStageUpperRangeLimit AdjustCoolingSetPointforTempAndHumidityControl adjusthhat AdjustPumpFlowRequestByEMSControls AdjustReportingHourAndMinutes AdjustVBGap AdvanceRootFinder AFECFR AFECOI AFECPD AFECPF AFEDMP AFEDOP AFEDWC AFEELR AFEEXF AFEFAN AFEHEX AFEHOP AFEPLR AFESCR AFESEL AFESOP AFETMU AirflowNetworkVentingControl AirMass AIRMOV AllocateAirflowNetworkData AllocateAirHeatBalArrays AllocateAndInitData AllocateAndSetUpVentReports AllocateCFSStateHourlyData AllocateForCFSRefPointsGeometry AllocateForCFSRefPointsState AllocateHeatBalArrays AllocateLoadComponentArrays AllocateModuleArrays AllocateModuleArrays AllocateSurfaceHeatBalArrays AllocateWeatherData angle_2dvector AnisoSkyViewFactors AnyPlantLoopSidesNeedSim AnyPlantSplitterMixerLacksContinuity AreaPolygon ArgCheck array_to_vector ASHRAETauModel ASHWAT_OffNormalProperties ASHWAT_Solar ASHWAT_Thermal ASSIGNMENT (=) AssignNodeNumber AssignReportNumber AssignResourceTypeNum AssignReverseConstructionNumber AssignVariablePt AttachCustomMeters AttachMeters AuditBranches AUTOTDMA BaseThermalPropertySet_Diffusivity BeginEnvrnInitializeRuntimeLanguage BetweenDates BetweenGlassForcedFlow BetweenGlassShadeForcedFlow BetweenGlassShadeNaturalFlow BisectionMethod BlindBeamBeamTrans BlindOpticsBeam BlindOpticsDiffuse BoreholeResistance BoundValueToNodeMinMaxAvail BoundValueToWithinTwoValues BracketRoot BranchPressureDrop BrentMethod BuildGap BuildKeyVarList Calc4PipeFanCoil Calc_EN673 Calc_ISO15099 CalcActiveTranspiredCollector CalcAggregateLoad CalcAirflowNetworkAirBalance CalcAirflowNetworkCO2Balance CalcAirflowNetworkGCBalance CalcAirflowNetworkHeatBalance CalcAirflowNetworkMoisBalance CalcAirFlowSimple CalcAirLoopSplitter CalcAirMixer CalcAirToAirGenericHeatExch CalcAirToAirPlateHeatExch CalcAirZoneReturnPlenum CalcAirZoneSupplyPlenum CalcAlamdariHammondStableHorizontal CalcAlamdariHammondUnstableHorizontal CalcAlamdariHammondVerticalWall CalcAngleFactorMRT CalcApproximateViewFactors CalcASHRAEDetailedIntConvCoeff CalcASHRAESimpExtConvectCoeff CalcASHRAESimpleIntConvCoeff CalcASHRAEVerticalWall CalcATMixer CalcAwbiHattonHeatedFloor CalcAwbiHattonHeatedWall CalcBasinHeaterPower CalcBasinHeaterPowerForMultiModeDXCoil CalcBeamSolarOnWinRevealSurface CalcBeamSolDiffuseReflFactors CalcBeamSolSpecularReflFactors CalcBeausoleilMorrisonMixedAssistedWall CalcBeausoleilMorrisonMixedOpposingWall CalcBeausoleilMorrisonMixedStableCeiling CalcBeausoleilMorrisonMixedStableFloor CalcBeausoleilMorrisonMixedUnstableCeiling CalcBeausoleilMorrisonMixedUnstableFloor CalcBLASTAbsorberModel CalcBlockenWindward CalcBoilerModel CalcBoilerModel CalcBottomFluxCoefficents CalcBottomSurfTemp CalcBuriedPipeSoil CalcCBF CalcCBF CalcCBVAV CalcCeilingDiffuserInletCorr CalcCeilingDiffuserIntConvCoeff CalcChillerHeaterModel CalcChillerIPLV CalcChillerModel CalcClearRoof CalcCoilUAbyEffectNTU CalcColdestSetPoint CalcComplexWindowOverlap CalcComplexWindowThermal CalcCompSuctionTempResidual CalcCondEntSetPoint CalcConnectionsDrainTemp CalcConnectionsFlowRates CalcConnectionsHeatRecovery CalcConstCOPChillerModel CalcConvCoeffAbsPlateAndWater CalcConvCoeffBetweenPlates CalcCoolBeam CalcCoolTower CalcCoordinateTransformation CalcCoPlanarNess CalcCostEstimate CalcCTGeneratorModel CalcDayltgCoefficients CalcDayltgCoeffsMapPoints CalcDayltgCoeffsRefMapPoints CalcDayltgCoeffsRefPoints CalcDesiccantBalancedHeatExch CalcDesignSpecificationOutdoorAir CalcDesuperheaterHeatingCoil CalcDesuperheaterWaterHeater CalcDetailedHcInForDVModel CalcDetailedSystem CalcDetailedTransSystem CalcDetailFlatFinCoolingCoil CalcDetIceStorLMTDstar CalcDiffTSysAvailMgr CalcDirectAir CalcDirectEvapCooler CalcDirectResearchSpecialEvapCooler CalcDoe2DXCoil CalcDOE2Leeward CalcDOE2Windward CalcDryFinEffCoef CalcDryIndirectEvapCooler CalcDuct CalcDXCoilStandardRating CalcDXHeatingCoil CalcEarthTube CalcEcoRoof CalcEffectiveness CalcEffectiveSHR CalcEffectiveSHR CalcEffectiveSHR CalcEffectiveSHR CalcElecSteamHumidifier CalcElectricBaseboard CalcElectricChillerHeatRecovery CalcElectricChillerModel CalcElectricEIRChillerModel CalcElectricHeatingCoil CalcEmmelRoof CalcEmmelVertical CalcEngineChillerHeatRec CalcEngineDrivenChillerModel CalcEQLOpticalProperty CalcEQLWindowOpticalProperty CalcEQLWindowSHGCAndTransNormal CalcEQLWindowStandardRatings CalcEQLWindowUvalue CalcEquipmentDrainTemp CalcEquipmentFlowRates CalcExhaustAbsorberChillerModel CalcExhaustAbsorberHeaterModel CalcExteriorVentedCavity CalcFisherPedersenCeilDiffuserCeiling CalcFisherPedersenCeilDiffuserFloor CalcFisherPedersenCeilDiffuserWalls CalcFluidHeatExchanger CalcFohannoPolidoriVerticalWall CalcFollowOATempSetPoint CalcFollowSysNodeTempSetPoint CalcFourPipeIndUnit CalcFrameDividerShadow CalcFuelCellAuxHeater CalcFuelCellGeneratorModel CalcFuelCellGenHeatRecovery CalcFurnaceOutput CalcFurnaceResidual CalcGasAbsorberChillerModel CalcGasAbsorberHeaterModel CalcGasCooler CalcGasHeatingCoil CalcGenericDesiccantDehumidifier CalcGoldsteinNovoselacCeilingDiffuserFloor CalcGoldsteinNovoselacCeilingDiffuserWall CalcGoldsteinNovoselacCeilingDiffuserWindow CalcGroundTempSetPoint CalcGroundwaterWell CalcGshpModel CalcGshpModel CalcGTChillerModel CalcHeatBalanceAir CalcHeatBalanceInsideSurf CalcHeatBalanceInsideSurf CalcHeatBalanceOutsideSurf CalcHeatBalanceOutsideSurf CalcHeatBalFiniteDiff CalcHeatBalHAMT CalcHeatPumpWaterHeater CalcHeatTransCoeffAndCoverTemp CalcHfExteriorSparrow CalcHighTempRadiantSystem CalcHighTempRadiantSystemSP CalcHiTurnOffSysAvailMgr CalcHiTurnOnSysAvailMgr CalcHnASHRAETARPExterior CalcHPCoolingSimple CalcHPHeatingSimple CalcHPWHDXCoil CalcHWBaseboard CalcHXAssistedCoolingCoil CalcHXEffectTerm CalcHybridVentSysAvailMgr CalcIBesselFunc CalcICEngineGeneratorModel CalcICEngineGenHeatRecovery CalcIceStorageCapacity CalcIceStorageCharge CalcIceStorageDischarge CalcIceStorageDormant CalcICSSolarCollector CalcIdealCondEntSetPoint CalcIfSetpointMet CalcIndirectAbsorberModel CalcIndirectResearchSpecialEvapCooler CalcInteriorRadExchange CalcInteriorSolarDistribution CalcInteriorSolarOverlaps CalcInteriorWinTransDifSolInitialDistribution CalcISO15099WindowIntConvCoeff CalcKaradagChilledCeiling CalcKBesselFunc CalcKhalifaEq3WallAwayFromHeat CalcKhalifaEq4CeilingAwayFromHeat CalcKhalifaEq5WallsNearHeat CalcKhalifaEq6NonHeatedWalls CalcKhalifaEq7Ceiling CalcLoadCenterThermalLoad CalcLoTurnOffSysAvailMgr CalcLoTurnOnSysAvailMgr CalcLowTempCFloRadiantSystem CalcLowTempCFloRadSysComps CalcLowTempElecRadiantSystem CalcLowTempHydrRadiantSystem CalcLowTempHydrRadSysComps CalcMatrixInverse CalcMcAdams CalcMerkelVariableSpeedTower CalcMicroCHPNoNormalizeGeneratorModel CalcMinIntWinSolidAngs CalcMitchell CalcMixedAirSetPoint CalcMoistureBalanceEMPD CalcMoreNodeInfo CalcMoWITTLeeward CalcMoWITTWindward CalcMSHeatPump CalcMTGeneratorModel CalcMultiSpeedDXCoil CalcMultiSpeedDXCoilCooling CalcMultiSpeedDXCoilHeating CalcMultiStageElectricHeatingCoil CalcMultiStageGasHeatingCoil CalcMultiZoneAverageCoolingSetPoint CalcMultiZoneAverageHeatingSetPoint CalcMultiZoneAverageMaxHumSetPoint CalcMultiZoneAverageMinHumSetPoint CalcMultiZoneMaxHumSetPoint CalcMultiZoneMinHumSetPoint CalcMundtModel CalcNCycSysAvailMgr CalcNewZoneHeatCoolFlowRates CalcNewZoneHeatOnlyFlowRates CalcNodeMassFlows CalcNominalWindowCond CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNonDXHeatingCoils CalcNusselt CalcNusseltJurges CalcNVentSysAvailMgr CalcOAController CalcOAMassFlow CalcOAMassFlow CalcOAMixer CalcOAOnlyMassFlow CalcOAPretreatSetPoint CalcOAUnitCoilComps CalcObstrMultiplier CalcOptStartSysAvailMgr CalcOtherSideDemand CalcOutdoorAirUnit CalcOutsideAirSetPoint CalcOutsideSurfTemp CalcParallelPIU CalcPassiveExteriorBaffleGap CalcPassiveSystem CalcPassiveTranspiredCollector CalcPerSolarBeam CalcPipeHeatTransCoef CalcPipesHeatTransfer CalcPipeTransBeam CalcPlantValves CalcPollution CalcPolyhedronVolume CalcPolynomCoef CalcPondGroundHeatExchanger CalcPredictedHumidityRatio CalcPredictedSystemLoad CalcPTUnit CalcPumps CalcPurchAirLoads CalcPurchAirMinOAMassFlow CalcPurchAirMixedAir CalcPVTcollectors CalcQiceChargeMaxByChiller CalcQiceChargeMaxByITS CalcQiceDischageMax CalcRABFlowSetPoint CalcRackSystem CalcRadSysHXEffectTerm CalcRadTemp CalcRainCollector CalcReformEIRChillerModel CalcResearchSpecialPartLoad CalcReturnAirPath CalcRfFlrCoordinateTransformation CalcSandiaPV CalcSatVapPressFromTemp CalcSchedOffSysAvailMgr CalcSchedOnSysAvailMgr CalcSchedSysAvailMgr CalcScheduledDualSetPoint CalcScheduledSetPoint CalcScreenTransmittance CalcScriptF CalcSeriesPIU CalcSetpointTempTarget CalcSHRUserDefinedCurves CalcSimpleController CalcSimpleHeatingCoil CalcSimplePV CalcSingleSpeedEvapFluidCooler CalcSingleSpeedTower CalcSingZoneClSetPoint CalcSingZoneHtSetPoint CalcSingZoneMaxHumSetPoint CalcSingZoneMinHumSetPoint CalcSingZoneRhSetPoint CalcSkySolDiffuseReflFactors CalcSolarCollector CalcSolarFlux CalcSolidDesiccantDehumidifier CalcSourceFlux CalcSourceTempCoefficents CalcSparrowLeeward CalcSparrowWindward CalcSpecialDayTypes CalcStandAloneERV CalcStandardRatings CalcStaticProperties CalcSteamAirCoil CalcSteamBaseboard CalcSurfaceCentroid CalcSurfaceGroundHeatExchanger CalcSystemEnergyUse CalcSZOneStageCoolingSetPt CalcSZOneStageHeatingSetPt CalcTankTemp CalcTDDTransSolAniso CalcTDDTransSolHorizon CalcTDDTransSolIso CalcTempDistModel CalcTempIntegral CalcTESCoilChargeOnlyMode CalcTESCoilCoolingAndChargeMode CalcTESCoilCoolingAndDischargeMode CalcTESCoilCoolingOnlyMode CalcTESCoilDischargeOnlyMode CalcTESCoilOffMode CalcTESIceStorageTank CalcTESWaterStorageTank CalcThermalChimney CalcThermalComfortAdaptiveASH55 CalcThermalComfortAdaptiveCEN15251 CalcThermalComfortFanger CalcThermalComfortKSU CalcThermalComfortPierce CalcThermalComfortSimpleASH55 CalcTimeNeeded CalcTopFluxCoefficents CalcTopSurfTemp CalcTotalFLux CalcTotCapSHR CalcTotCapSHR_VSWSHP CalcTransAbsorProduct CalcTransRefAbsOfCover CalcTRNSYSPV CalcTrombeWallIntConvCoeff CalcTwoSpeedDXCoilIEERResidual CalcTwoSpeedDXCoilStandardRating CalcTwoSpeedEvapFluidCooler CalcTwoSpeedTower CalcUAIce CalcUCSDCV CalcUCSDDV CalcUCSDUE CalcUCSDUI CalculateAirChillerSets CalculateBasisLength CalculateCase CalculateCoil CalculateCompressors CalculateCondensers CalculateCTFs CalculateDailySolarCoeffs CalculateDayOfWeek CalculateEpsFromNTUandZ CalculateExponentialMatrix CalculateFuncResults CalculateGammas CalculateInverseMatrix CalculateMoodyFrictionFactor CalculateNTUfromEpsAndZ CalculatePollution CalculateSecondary CalculateSubcoolers CalculateSunDirectionCosines CalculateTransCompressors CalculateWalkIn CalculateWaterUseage CalculateWaterUseage CalculateWindowBeamProperties CalculateZoneMRT CalculateZoneVolume CalcUnitaryCoolingSystem CalcUnitaryHeatingSystem CalcUnitarySuppHeatingSystem CalcUnitarySuppSystemtoSP CalcUnitarySystemLoadResidual CalcUnitarySystemToLoad CalcUnitHeater CalcUnitHeaterComponents CalcUnitVentilator CalcUnitVentilatorComponents CalcUnmetPlantDemand CalcUpdateHeatRecovery CalcUpdateHeatRecovery CalcUserDefinedInsideHcModel CalcUserDefinedOutsideHcModel CalcVariableSpeedTower CalcVarSpeedCoilCooling CalcVarSpeedCoilHeating CalcVarSpeedHeatPump CalcVarSpeedHeatPump CalcVAVVS CalcVentilatedSlab CalcVentilatedSlabComps CalcVentilatedSlabRadComps CalcVentSlabHXEffectTerm CalcVerticalGroundHeatExchanger CalcViewFactorToShelf CalcVRF CalcVRFCondenser CalcVRFCoolingCoil CalcVSTowerApproach CalcWallCoordinateTransformation CalcWaltonStableHorizontalOrTilt CalcWaltonUnstableHorizontalOrTilt CalcWarmestSetPoint CalcWarmestSetPointTempFlow CalcWaterMainsTemp CalcWaterSource CalcWaterStorageTank CalcWaterThermalTankMixed CalcWaterThermalTankStratified CalcWaterThermalTankZoneGains CalcWaterToAirHeatpump CalcWatertoAirHPCooling CalcWatertoAirHPHeating CalcWaterToAirResidual CalcWatertoWaterHPCooling CalcWatertoWaterHPHeating CalcWaterUseZoneGains CalcWetIndirectEvapCooler CalcWindowACOutput CalcWindowBlindProperties CalcWindowHeatBalance CalcWindowProfileAngles CalcWindowScreenProperties CalcWindowStaticProperties CalcWindPressure CalcWindPressureCoeffs CalcWindTurbine CalcWinFrameAndDividerTemps CalcWinTransDifSolInitialDistribution CalcWrapperModel CalcZoneAirComfortSetpoints CalcZoneAirTempSetpoints CalcZoneComponentLoadSums CalcZoneDehumidifier CalcZoneEvaporativeCoolerUnit CalcZoneLeavingConditions CalcZoneMassBalance CalcZonePipesHeatGain CalcZoneSums CartesianPipeCellInformation_ctor CellType_IsFieldCell CFSHasControlledShade CFSNGlz CFSRefPointPosFactor CFSRefPointSolidAngle CFSShadeAndBeamInitialization CFSUFactor cGetCoilAirOutletNode cGetCoilSteamInletNode cGetCoilSteamOutletNode CharPreDefTableEntry CheckActuatorNode CheckAndAddAirNodeNumber CheckAndFixCFSLayer CheckAndReadCustomSprectrumData CheckAndReadFaults CheckAndSetConstructionProperties CheckBracketRoundOff CheckBranchForOASys CheckCachedIPErrors CheckCFSStates CheckCoilWaterInletNode CheckControllerListOrder CheckControllerLists CheckConvexity CheckCostEstimateInput CheckCreatedZoneItemName CheckCurveLimitsForIPLV CheckCurveLimitsForStandardRatings CheckDayScheduleValueMinMax CheckDXCoolingCoilInOASysExists CheckFDSurfaceTempLimits CheckFFSchedule CheckFluidPropertyName CheckForActualFileName CheckForBalancedFlow CheckForControllerWaterCoil CheckForGeometricTransform CheckForGeometricTransform CheckForMisMatchedEnvironmentSpecifications CheckForOutOfRangeTempResult CheckForOutOfRangeTemps CheckForRequestedReporting CheckForRunawayPlantTemps CheckForSensorAndSetpointNode CheckGasCoefs CheckHeatingCoilSchedule CheckHXAssistedCoolingCoilSchedule CheckIFAnyEMS CheckIFAnyIdealCondEntSetPoint CheckIfAnyPlant CheckIfNodeSetpointManagedByEMS CheckIncrementRoundOff CheckInternalConsistency CheckLightsReplaceableMinMaxForZone CheckLocationValidity CheckLoopExitNode CheckLowerUpperBracket CheckMarkedNodes CheckMaxActiveController CheckMaxConstraint CheckMicroCHPThermalBalance CheckMinActiveController CheckMinConstraint checkMinimumMonthlyCharge CheckMinMaxCurveBoundaries CheckMinMaxRange CheckModelBoundOutput_HumRat CheckModelBoundOutput_Temp CheckModelBounds CheckModelBoundsHumRatEq CheckModelBoundsRH_HumRatEq CheckModelBoundsRH_TempEq CheckModelBoundsTempEq CheckNodeConnections CheckNodeSetPoint CheckNonSingularity CheckOAControllerName CheckOutAirNodeNumber CheckPlantConvergence CheckPlantMixerSplitterConsistency CheckPlantOnAbort CheckPollutionMeterReporting CheckRefrigerationInput CheckReportVariable CheckRootFinderCandidate CheckRootFinderConvergence CheckScheduledSurfaceGains CheckScheduleValue CheckScheduleValueMinMax Checksetpoints CheckSimpleController CheckSlope CheckSteamCoilSchedule CheckSubSurfaceMiscellaneous CheckSysSizing CheckSystemBranchFlow CheckTDDsAndLightShelvesInDaylitZones CheckThisAirSystemForSizing CheckThisZoneForSizing CheckThreading CheckUniqueNodes CheckUnitarySysCoilInOASysExists CheckUsedConstructions CheckValidSimulationObjects CheckWarmupConvergence CheckWaterCoilSchedule CheckWeatherFileValidity CheckWindowShadingControlFrameDivider CheckZoneEquipmentList CheckZoneSizing CHKBKS CHKGSS CHKSBS CLIP CLIPPOLY CloseDFSFile CloseMiscOpenFiles CloseMoistureBalanceEMPD CloseOutOpenFiles CloseOutputFiles CloseOutputTabularFile CloseReportIllumMaps CloseSocket CloseWeatherFile CoilAreaFracIter CoilCompletelyDry CoilCompletelyWet CoilOutletStreamCondition CoilPartWetPartDry COMMAND_ARGUMENT_COUNT CompactObjectsCheck CompareTwoVectors ComplexFenestrationLuminances ComputeDelayedComponents ComputeDifSolExcZonesWIZWindows ComputeIntSolarAbsorpFactors ComputeIntSWAbsorpFactors ComputeIntThermalAbsorpFactors ComputeLifeCycleCostAndReport ComputeLoadComponentDecayCurve ComputeNominalUwithConvCoeffs ComputePresentValue ComputeTariff ComputeTaxAndDepreciation ComputeWinShadeAbsorpFactors CondOutTempResidual ConstructBasis ControlCBVAVOutput ControlCompOutput ControlCompOutput ControlCoolBeam ControlCoolingSystem ControlCycWindACOutput ControlDesiccantDehumidifier ControlDXHeatingSystem ControlDXSystem ControlFluidHeatExchanger ControlHeatingSystem ControlHumidifier ControlMSHPOutput ControlPTUnitOutput ControlPVTcollector ControlReformEIRChillerModel ControlSuppHeatSystem ControlUnitarySystemOutput ControlUnitarySystemtoLoad ControlUnitarySystemtoSP ControlVRF ControlVSEvapUnitToMeetLoad ControlVSHPOutput ControlVSHPOutput ConvectionFactor ConvertCasetoLower ConvertCasetoUpper ConvertIP ConvertIPdelta ConvertToElementTag ConvertToEscaped CoolBeamResidual CoolingCoil CoolWaterHumRatResidual CoolWaterTempResidual CoolWatertoAirHPHumRatResidual CoolWatertoAirHPTempResidual CorrectZoneAirTemp CorrectZoneContaminants CorrectZoneHumRat CostInfoOut CPCW CPHW CreateBoundaryList CreateBoundaryListCount CreateCategoryNativeVariables CreateCellArray CreateCurrentDateTimeString CreateDefaultComputation CreateEnergyReportStructure CreateFCfactorConstructions CreateHVACStepFullString CreateHVACTimeIntervalString CreateHVACTimeString CreateNewellAreaVector CreateNewellSurfaceNormalVector CreatePartitionCenterList CreatePartitionRegionList CreatePredefinedMonthlyReports CreateRegionList CreateRegionListCount CreateShadedWindowConstruction CreateSQLiteConstructionsTable CreateSQLiteConstructionsTable CreateSQLiteDatabase CreateSQLiteDatabase CreateSQLiteDaylightMap CreateSQLiteDaylightMap CreateSQLiteDaylightMapTitle CreateSQLiteDaylightMapTitle CreateSQLiteEnvironmentPeriodRecord CreateSQLiteEnvironmentPeriodRecord CreateSQLiteErrorRecord CreateSQLiteErrorRecord CreateSQLiteInfiltrationTable CreateSQLiteInfiltrationTable CreateSQLiteMaterialsTable CreateSQLiteMaterialsTable CreateSQLiteMeterDictionaryRecord CreateSQLiteMeterDictionaryRecord CreateSQLiteMeterRecord CreateSQLiteMeterRecord CreateSQLiteNominalBaseboardHeatTable CreateSQLiteNominalBaseboardHeatTable CreateSQLiteNominalElectricEquipmentTable CreateSQLiteNominalElectricEquipmentTable CreateSQLiteNominalGasEquipmentTable CreateSQLiteNominalGasEquipmentTable CreateSQLiteNominalHotWaterEquipmentTable CreateSQLiteNominalHotWaterEquipmentTable CreateSQLiteNominalLightingTable CreateSQLiteNominalLightingTable CreateSQLiteNominalOtherEquipmentTable CreateSQLiteNominalOtherEquipmentTable CreateSQLiteNominalPeopleTable CreateSQLiteNominalPeopleTable CreateSQLiteNominalSteamEquipmentTable CreateSQLiteNominalSteamEquipmentTable CreateSQLiteReportVariableDataRecord CreateSQLiteReportVariableDataRecord CreateSQLiteReportVariableDictionaryRecord CreateSQLiteReportVariableDictionaryRecord CreateSQLiteRoomAirModelTable CreateSQLiteRoomAirModelTable CreateSQLiteSchedulesTable CreateSQLiteSimulationsRecord CreateSQLiteSimulationsRecord CreateSQLiteStringTableRecord CreateSQLiteSurfacesTable CreateSQLiteSurfacesTable CreateSQLiteTabularDataRecords CreateSQLiteTabularDataRecords CreateSQLiteTimeIndexRecord CreateSQLiteTimeIndexRecord CreateSQLiteVentilationTable CreateSQLiteVentilationTable CreateSQLiteZoneGroupTable CreateSQLiteZoneGroupTable CreateSQLiteZoneListTable CreateSQLiteZoneListTable CreateSQLiteZoneTable CreateSQLiteZoneTable CreateStormWindowConstructions CreateSysTimeIntervalString CreateTCConstructions CreateTimeIntervalString CreateTimeString CreatExtBooundCondName CreateZoneExtendedOutput CreateZoneExtendedOutput CrossProduct CrossProduct cSurfaceClass CTRANS CurveValue DateToString DateToStringWithMonth DaylghtAltAndAzimuth DayltgAveInteriorReflectance DayltgClosestObstruction DayltgCrossProduct DayltgCurrentExtHorizIllum DayltgDirectIllumComplexFenestration DayltgDirectSunDiskComplexFenestration DayltgElecLightingControl DayltgExtHorizIllum DayltgGlare DayltgGlarePositionFactor DayltgGlareWithIntWins DayltgHitBetWinObstruction DayltgHitInteriorObstruction DayltgHitObstruction DayltgInteriorIllum DayltgInteriorMapIllum DayltgInteriorTDDIllum DayltgInterReflectedIllum DayltgInterReflectedIllumComplexFenestration DayltgInterReflIllFrIntWins DayltgLuminousEfficacy DayltgPierceSurface DayltgSetupAdjZoneListsAndPointers DayltgSkyLuminance DayltgSurfaceLumFromSun dCheckScheduleValueMinMax1 dCheckScheduleValueMinMax2 DeallocateLoadComponentArrays DebugRootFinder DecodeHHMMField DecodeMonDayHrMin DeflectionTemperatures DeflectionWidths DegradF DElightDaylightCoefficients DElightDaylightCoefficients DElightElecLtgCtrl DElightElecLtgCtrl DElightFreeMemory DElightFreeMemory DElightInputGenerator DElightInputGenerator DElightOutputGenerator DElightOutputGenerator DensityCFSFillGas Depth DERIV DetailsForSurfaces DetectOscillatingZoneTemp DetermineAzimuthAndTilt DetermineBranchFlowRequest DetermineBuildingFloorArea DetermineDateTokens DetermineFrequency DetermineIndexGroupFromMeterGroup DetermineIndexGroupKeyFromMeterName DetermineMaxBackSurfaces DetermineMeterIPUnits DetermineMinuteForReporting DeterminePolygonOverlap DetermineShadowingCombinations DetermineSunUpDown DevelopMesh DiffuseAverage DiffuseAverageProfAngGnd DiffuseAverageProfAngSky DisplayMaterialRoughness DisplayNumberandString DisplaySimDaysProgress DisplayString distance DistributeBBElecRadGains DistributeBBRadGains DistributeBBSteamRadGains DistributeHTRadGains DistributePlantLoad DistributePressureOnBranch DistributeTDDAbsorbedSolar DistributeUserDefinedPlantLoad DL_RES_r2 DLAG DOE2DXCoilHumRatResidual DOE2DXCoilHumRatResidual DOE2DXCoilResidual DOE2DXCoilResidual DOE2DXCoilResidual DoEndOfIterationOperations DomainRectangle_Contains DOMakeUPPERCase DoOneTimeInitializations DOSameString DoShadeControl DoStartOfTimeStepInitializations DownInterpolate4HistoryValues DumpAirLoopStatistics DumpCurrentLineBuffer DUMPVD DUMPVR DXCoilCyclingHumRatResidual DXCoilCyclingHumRatResidual DXCoilCyclingResidual DXCoilCyclingResidual DXCoilVarSpeedHumRatResidual DXCoilVarSpeedHumRatResidual DXCoilVarSpeedResidual DXCoilVarSpeedResidual DXFOut DXFOutLines DXFOutWireFrame DXHeatingCoilResidual DXHeatingCoilResidual DXHeatingCoilResidual DynamicClothingModel DynamicExtConvSurfaceClassification DynamicIntConvSurfaceClassification EchoOutActuatorKeyChoices EchoOutInternalVariableChoices EffectiveEPSLB EffectiveEPSLF EIRChillerHeatRecovery EN673ISO10292 EncodeMonDayHrMin EndEnergyPlus EndUniqueNodeCheck EnthalpyResidual epElapsedTime epGetTimeUsed epGetTimeUsedperCall epStartTime epStopTime epSummaryTimes eptime EQLWindowInsideEffectiveEmiss EQLWindowOutsideEffectiveEmiss EQLWindowSurfaceHeatBalance EquationsSolver ERF EstimateHEXSurfaceArea EvalInsideMovableInsulation EvalOutsideMovableInsulation EvaluateAdiabaticSurfaceTemperature EvaluateBasementCellTemperature EvaluateCellNeighborDirections evaluateChargeBlock evaluateChargeSimple EvaluateExpression EvaluateExtHcModels EvaluateFarfieldBoundaryTemperature EvaluateFarfieldCharacteristics EvaluateFieldCellTemperature EvaluateGroundSurfaceTemperature EvaluateIntHcModels EvaluateLoopSetPointLoad EvaluateNeighborCharacteristics evaluateQualify evaluateRatchet EvaluateSoilRhoCp EvaluateStack EvolveParaUCSDCV ExitCalcController ExpandComplexState ExpressAsCashFlows ExtendObjectDefinition ExteriorBCEqns ExternalInterfaceExchangeVariables ExternalInterfaceInitializeErlVariable ExternalInterfaceSetErlVariable ExternalInterfaceSetSchedule ExtOrIntShadeNaturalFlow Fabric_EstimateDiffuseProps FACSKY FalsePositionMethod FEQX FI FigureACAncillaries FigureAirEnthalpy FigureAirHeatCap FigureAuxilHeatGasHeatCap FigureBeamSolDiffuseReflFactors FigureBeamSolSpecularReflFactors FigureConstGradPattern FigureDayltgCoeffsAtPointsForSunPosition FigureDayltgCoeffsAtPointsForWindowElements FigureDayltgCoeffsAtPointsSetupForWindow FigureElectricalStorageZoneGains FigureFuelCellZoneGains FigureFuelEnthalpy FigureFuelHeatCap FigureGaseousWaterEnthalpy FigureHeightPattern FigureHXleavingGasHeatCap FigureInverterZoneGains FigureLHVofFuel FigureLiquidWaterEnthalpy FigureLiquidWaterHeatCap FigureMapPointDayltgFactorsToAddIllums FigureMicroCHPZoneGains FigureNDheightInZone FigurePowerConditioningLosses FigureProductGasesEnthalpy FigureProductGasHeatCap FigureRefPointDayltgFactorsToAddIllums FigureRefrigerationZoneGains FigureSolarBeamAtTimestep FigureSunCosines FigureSurfMapPattern FigureTDDZoneGains FigureTransformerZoneGains FigureTransientConstraints FigureTwoGradInterpPattern FILJAC FillBasisElement FillDefaultsSWP FillRemainingPredefinedEntries FillWeatherPredefinedEntries film filmg filmi filmPillar FILSKY FinalizeCFS FinalizeCFSLAYER FinalRateCoils FindAirLoopBranchConnection FindAirPlantCondenserLoopFromBranchList FindAllNumbersinList FindArrayIndex FindCompSPInput FindCompSPLoad FindCondenserLoopBranchConnection FindControlledZoneIndexFromSystemNodeNumberForZone FindDeltaTempRangeInput FindDemandSideMatch FindEMSVariable FindFirstLastPtr FindFirstRecord FindGlycol FindHXDemandSideLoopFlow FindInBasis FindItem FindIteminList FindIteminSortedList FindItemInVariableList FindLoopSideInCallingOrder FindNextRecord FindNonSpace FindNumberinList FindOAMixerMatchForOASystem FindPlantLoopBranchConnection FindRangeBasedOrUncontrolledInput FindRangeVariable FindRefrigerant FindRootSimpleController FindStratifiedTankSensedTemp FindTariffIndex FindTDDPipe FindUnitNumber FinishDebugOutputFiles FixViewFactors FluidCellInformation_ctor FM_BEAM FM_DIFF FM_F FNU forcedventilation FourPipeInductionUnitHasMixer FourPipeIUCoolingResidual FourPipeIUHeatingResidual FRA FrostControl FrostControlSetPointLimit FrostControlSetPointLimit FuelCellProductGasEnthResidual FUN FuncDetermineCoolantWaterExitTemp FuncDetermineCWMdotForInternalFlowControl FuncDetermineEngineTemp FV GasElecHeatingCoilResidual GASSES90 GassesLow GatherBEPSResultsForTimestep GatherBinResultsForTimestep GatherComponentLoadsHVAC GatherComponentLoadsIntGain GatherComponentLoadsSurfAbsFact GatherComponentLoadsSurface GatherForEconomics GatherForPredefinedReport GatherHeatGainReport GatherMonthlyResultsForTimestep GatherPeakDemandForTimestep GatherSourceEnergyEndUseResultsForTimestep GaussElimination generate_ears GenerateDElightDaylightCoefficients GenerateDElightDaylightCoefficients GeneratorPowerOutput GenericCrack GenOutputVariablesAuditReport Get2DMatrix Get2DMatrixDimensions GET_COMMAND GET_COMMAND_ARGUMENT Get_Environment_Variable GetActualDXCoilIndex GetAirBranchIndex GetAirFlowFlag GetAirflowNetworkInput GetAirHeatBalanceInput GetAirLoopAvailabilityManager GetAirModelDatas GetAirNodeData GetAirPathData GetAngleFactorList GetATMixer GetATMixerOutNode GetATMixerPriNode GetATMixers GetATMixerSecNode GetAttShdSurfaceData GetAverageTempByType GetBaseboardInput GetBaseboardInput GetBasementFloorHeatFlux GetBasementWallHeatFlux GetBLASTAbsorberInput GetBoilerInput GetBoilerInput GetBranchData GetBranchFanTypeName GetBranchFlow GetBranchInput GetBranchList GetBranchListInput GetBuildingData GetCBVAV GetCellWidths GetCellWidthsCount GetChildrenData GetChillerheaterInput GetCoilAirFlowRate GetCoilAirFlowRateVariableSpeed GetCoilAirInletNode GetCoilAirOutletNode GetCoilAvailScheduleIndex GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacity GetCoilCapacityByIndexType GetCoilCapacityVariableSpeed GetCoilCondenserInletNode GetCoilControlNodeNum GetCoilGroupTypeNum GetCoilIndex GetCoilIndex GetCoilIndex GetCoilIndexVariableSpeed GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNode GetCoilInletNodeVariableSpeed GetCoilMaxSteamFlowRate GetCoilMaxWaterFlowRate GetCoilMaxWaterFlowRate GetCoilMaxWaterFlowRate GetCoilObjectTypeNum GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNode GetCoilOutletNodeVariableSpeed GetCoilSteamInletNode GetCoilSteamOutletNode GetCoilTypeNum GetCoilWaterInletNode GetCoilWaterInletNode GetCoilWaterOutletNode GetColumnUsingTabs GetComfortSetpoints GetComponentData GetCondFDInput GetConductivityGlycol GetConnectorList GetConnectorListInput GetConstCOPChillerInput GetConstructData GetControlledZoneIndex GetControllerActuatorNodeNum GetControllerInput GetCoolBeams GetCoolingCoilTypeNameAndIndex GetCooltower GetCostEstimateInput GetCrossVentData GetCTGeneratorInput GetCTGeneratorResults GetCurrentHVACTime GetCurrentMeterValue GetCurrentScheduleValue GetCurveCheck GetCurveIndex GetCurveInput GetCurveMinMaxValues GetCurveName GetCurveObjectTypeNum GetCurveType GetCustomMeterInput GetDaylightingParametersDetaild GetDaylightingParametersInput GetDayScheduleIndex GetDemandManagerInput GetDemandManagerListInput GetDensityGlycol GetDesiccantDehumidifierInput GetDesignDayData GetDesignLightingLevelForZone GetDetShdSurfaceData GetDirectAirInput GetDisplacementVentData GetDSTData GetDualDuctInput GetDualDuctOutdoorAirRecircUse GetDuctInput GetDXCoilAirFlow GetDXCoilAvailSchPtr GetDXCoilBypassedFlowFrac GetDXCoilCapFTCurveIndex GetDXCoilIndex GetDXCoilNumberOfSpeeds GetDXCoils GetDXCoolingSystemInput GetDXHeatPumpSystemInput GetEarthTube GetElecReformEIRChillerInput GetElectricBaseboardInput GetElectricChillerInput GetElectricEIRChillerInput GetEMSInput GetEngineDrivenChillerInput GetEnvironmentalImpactFactorInfo GetEvapFluidCoolerInput GetEvapInput GetExhaustAbsorberInput GetExhaustAirInletNode GetExteriorEnergyUseInput GetExtVentedCavityIndex GetExtVentedCavityIndex GetExtVentedCavityTsColl GetExtVentedCavityTsColl GetFanAvailSchPtr GetFanCoilIndex GetFanCoilInletAirNode GetFanCoilMixedAirNode GetFanCoilOutAirNode GetFanCoilReturnAirNode GetFanCoilUnits GetFanCoilZoneInletAirNode GetFanDesignVolumeFlowRate GetFanIndex GetFanIndexForTwoSpeedCoil GetFanInletNode GetFanInput GetFanOutletNode GetFanPower GetFanSpeedRatioCurveIndex GetFanType GetFanVolFlow GetFarfieldTemp GetFirstBranchInletNodeName GetFluidCoolerInput GetFluidDensityTemperatureLimits GetFluidHeatExchangerInput GetFluidPropertiesData GetFluidSpecificHeatTemperatureLimits GetFrameAndDividerData GetFuelCellGeneratorInput GetFuelCellGeneratorResults GetFuelFactorInfo GetFurnaceInput GetGasAbsorberInput GetGeneratorFuelSupplyInput GetGeometryParameters GetGlycolNameByIndex GetGroundheatExchangerInput GetGroundReflectances GetGroundTemps GetGshpInput GetGshpInput GetGTChillerInput GetHeatBalanceInput GetHeatBalHAMTInput GetHeatExchangerObjectTypeNum GetHeatingCoilIndex GetHeatingCoilInput GetHeatingCoilNumberOfStages GetHeatingCoilPLFCurveIndex GetHeatingCoilTypeNum GetHeatReclaimSourceIndex GetHeatRecoveryInput GetHighTempRadiantSystem GetHPCoolingCoilIndex GetHTSubSurfaceData GetHTSurfaceData GetHTSurfExtVentedCavityData GetHumidifierInput GetHVACSingleDuctSysIndex GetHWBaseboardInput GetHXAssistedCoolingCoilInput GetHXCoilAirFlowRate GetHXCoilType GetHXCoilTypeAndName GetHXDXCoilIndex GetHXDXCoilName GetHybridVentilationControlStatus GetHybridVentilationInputs GetICEGeneratorResults GetICEngineGeneratorInput GetIceStorageInput GetIDFRecordsStats GetIndirectAbsorberInput GetIndUnits GetInputEconomicsChargeBlock GetInputEconomicsChargeSimple GetInputEconomicsComputation GetInputEconomicsCurrencyType GetInputEconomicsQualify GetInputEconomicsRatchet GetInputEconomicsTariff GetInputEconomicsVariable GetInputForLifeCycleCost GetInputFuelAndPollutionFactors GetInputLifeCycleCostNonrecurringCost GetInputLifeCycleCostParameters GetInputLifeCycleCostRecurringCosts GetInputLifeCycleCostUseAdjustment GetInputLifeCycleCostUsePriceEscalation GetInputTabularMonthly GetInputTabularPredefined GetInputTabularStyle GetInputTabularTimeBins GetInputViewFactors GetInputViewFactorsbyName GetInputZoneEvaporativeCoolerUnit GetInstantMeterValue GetInternalBranchData GetInternalHeatGainsInput GetInternalVariableValue GetInternalVariableValue GetInternalVariableValueExternalInterface GetInternalVariableValueExternalInterface GetInterpolatedSatProp GetInterpValue GetIntMassSurfaceData GetLastBranchOutletNodeName GetLastWord GetLightWellData GetListOfObjectsInIDD GetListofSectionsinInput GetLocationInfo GetLoopMixer GetLoopSidePumpIndex GetLoopSplitter GetLowTempRadiantSystem GetMaterialData GetMatrixInput getMaxAndSum GetMeteredVariables GetMeterIndex GetMeterResourceType GetMicroCHPGeneratorInput GetMicroCHPGeneratorResults GetMinOATCompressor GetMixerInput GetMixerInput GetMoistureBalanceEMPDInput GetMonthlyCostForResource GetMovableInsulationData GetMSHeatPumpInput GetMTGeneratorExhaustNode GetMTGeneratorInput GetMTGeneratorResults GetMundtData GetNewUnitNumber GetNextEnvironment GetNodeConnectionType GetNodeList GetNodeListsInput GetNodeNums GetNTUforCrossFlowBothUnmixed GetNumberOfSchedules GetNumberOfSurfaceLists GetNumberOfSurfListVentSlab GetNumChildren GetNumMeteredVariables GetNumOAControllers GetNumOAMixers GetNumOASystems GetNumObjectsFound GetNumObjectsInIDD GetNumRangeCheckErrorsFound GetNumSectionsFound GetNumSectionsinInput GetNumSegmentsForHorizontalTrenches GetNumSplitterMixerInConntrList GetOACompListNumber GetOACompName GetOACompType GetOACompTypeNum GetOAControllerInputs GetOAMixerIndex GetOAMixerInletNodeNumber GetOAMixerInputs GetOAMixerMixedNodeNumber GetOAMixerNodeNumbers GetOAMixerReliefNodeNumber GetOAMixerReturnNodeNumber GetOARequirements GetOASysControllerListIndex GetOASysNumCoolingCoils GetOASysNumHeatingCoils GetOASysNumSimpControllers GetOASystemNumber GetObjectDefInIDD GetObjectDefMaxArgs GetObjectItem GetObjectItemfromFile GetObjectItemNum GetOnlySingleNode GetOperationSchemeInput GetOSCData GetOSCMData GetOutAirNodesInput GetOutdoorAirUnitInputs GetOutdoorAirUnitOutAirNode GetOutdoorAirUnitReturnAirNode GetOutdoorAirUnitZoneInletNode GetOutsideAirSysInputs GetOutsideEnergySourcesInput GetParentData GetPipeInput GetPipesHeatTransfer GetPipingSystemsInput GetPIUs GetPlantAvailabilityManager GetPlantInput GetPlantLoopData GetPlantOperationInput GetPlantProfileInput GetPlantSizingInput GetPlantValvesInput GetPollutionFactorInput GetPondGroundHeatExchanger GetPowerManagerInput GetPressureCurveTypeAndIndex GetPressureSystemInput GetPreviousHVACTime GetProjectControlData GetProjectData GetPTUnit GetPTUnitMixedAirNode GetPTUnitOutAirNode GetPTUnitReturnAirNode GetPTUnitZoneInletAirNode GetPumpInput GetPurchasedAir GetPurchasedAirMixedAirHumRat GetPurchasedAirMixedAirTemp GetPurchasedAirOutAirMassFlow GetPurchasedAirReturnAirNode GetPurchasedAirZoneInletAirNode GetPVGeneratorResults GetPVInput GetPVTcollectorsInput GetPVTThermalPowerProduction GetQualityRefrig GetRecordLocations GetRectDetShdSurfaceData GetRectSubSurfaces GetRectSurfaces GetRefrigeratedRackIndex GetRefrigerationInput GetReportVariableInput GetRequiredMassFlowRate GetResidCrossFlowBothUnmixed GetResourceTypeChar GetReturnAirNodeForZone GetReturnAirPathInput GetRoomAirModelParameters GetRunPeriodData GetRunPeriodDesignData GetRuntimeLanguageUserInput GetSatDensityRefrig GetSatEnthalpyRefrig GetSatPressureRefrig GetSatSpecificHeatRefrig GetSatTemperatureRefrig GetScheduledSurfaceGains GetScheduleIndex GetScheduleMaxValue GetScheduleMinValue GetScheduleName GetScheduleType GetScheduleValuesForDay GetSecondaryInletNode GetSecondaryOutletNode GetSetPointManagerInputs GetShadingSurfReflectanceData GetShadowingInput GetShelfInput GetSimpleAirModelInputs GetSimpleShdSurfaceData GetSimpleWatertoAirHPInput GetSingleDayScheduleValues GetSiteAtmosphereData GetSizingParams GetSnowGroundRefModifiers GetSolarCollectorInput GetSpecialDayPeriodData GetSpecificHeatGlycol getSpecificUnitDivider getSpecificUnitIndex getSpecificUnitMultiplier GetSplitterInput GetSplitterInput GetSplitterNodeNumbers GetSplitterOutletNumber GetStandAloneERV GetStandAloneERVNodes GetStandAloneERVOutAirNode GetStandAloneERVReturnAirNode GetStandAloneERVZoneInletAirNode GetStandardMeterResourceType GetSteamBaseboardInput GetSteamCoilAvailScheduleIndex GetSteamCoilControlNodeNum GetSteamCoilIndex GetSteamCoilInput GetSTM GetStormWindowData GetSupHeatDensityRefrig GetSupHeatEnthalpyRefrig GetSupHeatPressureRefrig GetSupplyAirFlowRate GetSupplyAirFlowRate GetSupplyAirInletNode GetSupplyInletNode GetSupplyOutletNode GetSurfaceCountForOSCM GetSurfaceData GetSurfaceGroundHeatExchanger GetSurfaceHeatTransferAlgorithmOverrides GetSurfaceIndecesForOSCM GetSurfaceListsInputs GetSurfHBDataForMundtModel GetSurfHBDataForTempDistModel GetSysAvailManagerInputs GetSysAvailManagerListInputs GetSysInput GetSystemNodeNumberForZone GetSystemSizingInput GetTDDInput GetTESCoilIndex GetTESCoilInput GetThermalChimney GetTowerInput GetTranspiredCollectorIndex GetTranspiredCollectorInput GetTypeOfCoil GetUFADZoneData GetUnitarySystemDXCoolingCoilIndex GetUnitarySystemInput GetUnitarySystemOAHeatCoolCoil GetUnitConversion GetUnitHeaterInput GetUnitsString GetUnitSubString GetUnitVentilatorInput GetUnitVentilatorMixedAirNode GetUnitVentilatorOutAirNode GetUnitVentilatorReturnAirNode GetUnitVentilatorZoneInletAirNode GetUserConvectionCoefficients GetUserDefinedComponents GetUserDefinedOpSchemeInput GetUserDefinedPatternData GetUTSCTsColl GetVariableKeyCountandType GetVariableKeyCountandType GetVariableKeys GetVariableKeys GetVariableTypeAndIndex GetVariableUnitsString GetVarSpeedCoilInput GetVentilatedSlabInput GetVertices GetViscosityGlycol GetVRFInput GetVSCoilCondenserInletNode GetVSCoilMinOATCompressor GetVSCoilNumOfSpeeds GetWaterCoilAvailScheduleIndex GetWaterCoilCapacity GetWaterCoilIndex GetWaterCoilInput GetWaterMainsTemperatures GetWaterManagerInput GetWaterSource GetWaterThermalTankInput GetWatertoAirHPInput GetWatertoWaterHPInput GetWaterUseInput GetWeatherProperties GetWeatherStation GetWindowAC GetWindowACMixedAirNode GetWindowACOutAirNode GetWindowACReturnAirNode GetWindowACZoneInletAirNode GetWindowGapAirflowControlData GetWindowGlassSpectralData GetWindowShadingControlData GetWindTurbineInput GetWrapperInput GetWTGeneratorResults GetZoneAirDistribution GetZoneAirLoopEquipment GetZoneAirSetpoints GetZoneAndZoneListNames GetZoneContaminanInputs GetZoneContaminanSetpoints GetZoneData GetZoneDehumidifierInput GetZoneDehumidifierNodeNumber GetZoneEqAvailabilityManager GetZoneEquipment GetZoneEquipmentData GetZoneEquipmentData1 GetZoneInfilAirChangeRate GetZoneLoads GetZonePlenumInput GetZoneSizingInput GLtoAMB GoAhead guess HasFractionalScheduleValue hatter HCInWindowStandardRatings HConvGap HcUCSDCV HcUCSDDV HcUCSDUF HeatingCoilVarSpeedCycResidual HeatingCoilVarSpeedResidual HeatPumpRunFrac HeatPumpRunFrac HeatPumpRunFrac HeatWatertoAirHPTempResidual Height HEMINT HIC_ASHRAE HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterCoilResidual HotWaterHeatingCoilResidual HRadPar HTRANS HTRANS0 HTRANS1 HWBaseboardUAResidual HXAssistDXCoilResidual HXAssistedCoolCoilHRResidual HXAssistedCoolCoilHRResidual HXAssistedCoolCoilTempResidual HXAssistedCoolCoilTempResidual HXDemandSideLoopFlowResidual HybridVentilationControl IAM iCheckScheduleValue ICSCollectorAnalyticalSoluton iGetCoilAirOutletNode iGetCoilSteamInletNode iGetCoilSteamOutletNode INCLOS incrementEconVar IncrementInstMeterCache incrementSteps incrementTableEntry InitAirflowNetwork InitAirflowNetworkData InitAirHeatBalance InitAirLoops InitAirLoopSplitter InitAirMixer InitAirTerminalUserDefined InitAirZoneReturnPlenum InitAirZoneSupplyPlenum InitATMixer InitBaseboard InitBaseboard InitBLASTAbsorberModel InitBoiler InitBoiler InitBoreholeHXSimVars InitBSDFWindows InitCBVAV InitCoilUserDefined InitComplexWindows InitComponentNodes InitConductionTransferFunctions InitConnections InitConstCOPChiller InitController InitCoolBeam InitCTGenerators InitCurveReporting InitDaylightingDevices InitDemandManagers InitDesiccantDehumidifier InitDetailedIceStorage InitDirectAir InitDualDuct InitDuct InitDXCoil InitDXCoolingSystem InitDXHeatPumpSystem InitElecReformEIRChiller InitElectricBaseboard InitElectricChiller InitElectricEIRChiller InitEMS InitEMSControlledConstructions InitEMSControlledSurfaceProperties InitEnergyReports InitEngineDrivenChiller InitEquivalentLayerWindowCalculations InitEvapCooler InitEvapFluidCooler InitExhaustAbsorber InitExteriorConvectionCoeff InitFan InitFanCoilUnits InitFluidCooler InitFluidHeatExchanger InitFuelCellGenerators InitFurnace InitGasAbsorber InitGlassOpticalCalculations InitGshp InitGshp InitGTChiller InitHeatBalance InitHeatBalFiniteDiff InitHeatBalHAMT InitHeatingCoil InitHeatRecovery InitHighTempRadiantSystem InitHumidifier InitHWBaseboard InitHXAssistedCoolingCoil InitHybridVentSysAvailMgr InitialInitHeatBalFiniteDiff InitializeCFSDaylighting InitializeCFSStateData InitializeComponentSizingTable InitializeConstructionsTables InitializeDaylightMapTables InitializeEnvironmentPeriodsTable InitializeErrorsTable InitializeGlycolTempLimits InitializeHeatTransferPipes InitializeIndexes InitializeIndexes InitializeLoops InitializeMaterialsTable InitializeMeters initializeMonetaryUnit InitializeNominalBaseboardHeatTable InitializeNominalElectricEquipmentTable InitializeNominalGasEquipmentTable InitializeNominalHotWaterEquipmentTable InitializeNominalInfiltrationTable InitializeNominalLightingTable InitializeNominalOtherEquipmentTable InitializeNominalPeopleTable InitializeNominalSteamEquipmentTable InitializeNominalVentilationTable InitializeOperatingMode InitializeOutput InitializePipes InitializePredefinedMonthlyTitles InitializePsychRoutines InitializePumps InitializeRefrigerantLimits InitializeReportMeterDataDictionaryTable InitializeReportMeterDataTables InitializeReportVariableDataDictionaryTable InitializeReportVariableDataTables InitializeRoomAirModelTable InitializeRootFinder InitializeRuntimeLanguage InitializeSchedulesTable InitializeSimulationsTable InitializeSQLiteTables InitializeSurfacesTable InitializeSystemSizingTable InitializeTabularDataTable InitializeTabularDataTable InitializeTabularDataView InitializeTabularDataView InitializeTabularMonthly InitializeTimeIndicesTable InitializeViews InitializeWeather InitializeZoneGroupTable InitializeZoneInfoTable InitializeZoneListTable InitializeZoneSizingTable InitICEngineGenerators InitIndirectAbsorpChiller InitIndUnit InitInteriorConvectionCoeffs InitInteriorRadExchange InitInternalHeatGains InitIntSolarDistribution InitLoadBasedControl InitLoadDistribution InitLowTempRadiantSystem InitMicroCHPNoNormalizeGenerators InitMoistureBalanceEMPD InitMSHeatPump InitMTGenerators InitMundtModel InitOAController InitOAMixer InitOneTimePlantSizingInfo InitOutAirNodes InitOutdoorAirUnit InitOutsideAirSys InitPipesHeatTransfer InitPipingSystems InitPIU InitPlantProfile InitPlantUserComponent InitPlantValves InitPollutionMeterReporting InitPondGroundHeatExchanger InitPressureDrop InitPTUnit InitPurchasedAir InitPVTcollectors InitRefrigeration InitRefrigerationPlantConnections InitReturnAirPath InitSecretObjects InitSetPointManagers InitSimpleIceStorage InitSimpleMixingConvectiveHeatGains InitSimpleWatertoAirHP InitSimVars InitSimVars InitSimVars InitSimVars InitSolarCalculations InitSolarCollector InitSolarHeatGains InitSolReflRecSurf InitStandAloneERV InitSteamBaseboard InitSteamCoil InitSurfaceGroundHeatExchanger InitSurfaceHeatBalance InitSys InitSysAvailManagers InitSystemOutputRequired InitTempDistModel InitTESCoil InitThermalAndFluxHistories InitThermalComfort InitTower InitTranspiredCollector InitTRNSYSPV InitUCSDCV InitUCSDDV InitUCSDUF InitUniqueNodeCheck InitUnitarySystems InitUnitHeater InitUnitVentilator InitVarSpeedCoil InitVentilatedSlab InitVRF InitWaterCoil InitWaterSource InitWaterThermalTank InitWatertoAirHP InitWatertoWaterHP InitWindowAC InitWindTurbine InitWrapper InitZoneAirLoopEquipment InitZoneAirSetpoints InitZoneAirUserDefined InitZoneContSetpoints InitZoneDehumidifier InitZoneEquipment InitZoneEvaporativeCoolerUnit InPolygon InsertCurrencySymbol int_times_vector INTCPT Integer_IsInRange IntegerIsWithinTwoValues IntegerToString InterConnectTwoPlantLoopSides InteriorBCEqns InteriorNodeEqns InternalRangeCheck InternalSetupTankDemandComponent InternalSetupTankSupplyComponent interp INTERP InterpBlind InterpDefValuesForGlycolConc Interpolate Interpolate_Lagrange InterpolateBetweenFourValues InterpolateBetweenTwoValues InterpolatePipeTransBeam InterpProfAng InterpProfSlatAng InterpretWeatherDataLine InterpSlatAng InterpSw InterpValuesForGlycolConc IntInterfaceNodeEqns IntPreDefTableEntry IntToStr Invert3By3Matrix InvertMatrix InvJulianDay IPTrimSigDigits iRoundSigDigits IS_BEAM IS_DIFF IS_DSRATIO IS_F IS_LWP IS_OPENNESS IS_SWP isCompLoadRepReq IsControlledShade IsConverged_CurrentToPrevIteration IsConverged_PipeCurrentToPrevIteration IsCurveInputTypeValid IsCurveOutputTypeValid isExternalInterfaceErlVariable IsGlazeLayerX IsGZSLayer isInQuadrilateral IsInRange isInTriangle IsLeapYear IsNodeOnSetPtManager IsParentObject IsParentObjectCompSet IsShadingLayer IssueSevereAlphaInputFieldError IssueSevereInputFieldError IssueSevereRealInputFieldError IsValidConnectionType IsVBLayer isWithinRange ITERATE IterateRootFinder iTrimSigDigits JGDate JulianDay LClimb LDSumMax LDSumMean LEEDtariffReporting LimitCoilCapacity LimitController LimitTUCapacity LinesOut linint LoadEquipList LoadInterface LogicalToInteger LogicalToInteger LogPlantConvergencePoints lookupOperator LookUpScheduleValue LookUpSeason LookupSItoIP lubksb LUBKSB ludcmp LUDCMP LUdecomposition LUsolution MakeAnchorName MakeHVACTimeIntervalString MakeMirrorSurface MakeRectangularVertices MakeRelativeRectangularVertices MakeTransition MakeUPPERCase ManageAirflowNetworkBalance ManageAirHeatBalance ManageAirLoops ManageAirModel ManageBranchInput ManageControllers ManageCoolTower ManageDemand ManageEarthTube ManageElectCenterStorageInteractions ManageElectricLoadCenters ManageElectStorInteractions ManageEMS ManageExteriorEnergyUse ManageGeneratorControlState ManageGeneratorFuelFlow ManageHeatBalance ManageHeatBalFiniteDiff ManageHeatBalHAMT ManageHVAC ManageHybridVentilation ManageInsideAdaptiveConvectionAlgo ManageInternalHeatGains ManageInverter ManageMundtModel ManageNonZoneEquipment ManageOutsideAdaptiveConvectionAlgo ManageOutsideAirSystem ManagePlantLoadDistribution ManagePlantLoops ManageRefrigeratedCaseRacks ManageSetPoints ManageSimulation ManageSingleCommonPipe ManageSizing ManageSurfaceHeatBalance ManageSystemAvailability ManageThermalChimney ManageThermalComfort ManageTransformers ManageTwoWayCommonPipe ManageUCSDCVModel ManageUCSDDVModel ManageUCSDUFModels ManageUserDefinedPatterns ManageWater ManageWaterInits ManageWeather ManageZoneAirLoopEquipment ManageZoneAirUpdates ManageZoneContaminanUpdates ManageZoneEquipment MapExtConvClassificationToHcModels MapIntConvClassificationToHcModels MarkNode MatchAndSetColorTextString MatchPlantSys MatrixIndex matrixQBalance MeshPartition_CompareByDimension MeshPartition_SelectionSort MeshPartitionArray_Contains MinePlantStructForInfo MixedAirControlTempResidual ModifyWindow Modulus MonthToMonthNumber MovingAvg MRXINV MSHPCyclingResidual MSHPHeatRecovery MSHPVarSpeedResidual MultiModeDXCoilHumRatResidual MultiModeDXCoilHumRatResidual MultiModeDXCoilResidual MultiModeDXCoilResidual MultiModeDXCoilResidual MultiSpeedDXCoolingCoilStandardRatings MultiSpeedDXHeatingCoilStandardRatings MULTOL MyPlantSizingIndex NeighborInformationArray_Value NETRAD NewEMSVariable NewExpression newPreDefColumn newPreDefReport newPreDefSubTable NEWTON NodeHasSPMCtrlVarType NormalArea NumBranchesInBranchList NumCompsInBranch nusselt NusseltNumber OpenEPlusWeatherFile OPENNESS_LW OpenOutputFiles OpenOutputTabularFile OpenWeatherFile OPERATOR (*) OPERATOR (+) OPERATOR (-) OPERATOR (.dot.) OPERATOR (.twodcross.) OPERATOR (.twoddot.) OPERATOR (/) ORDER OutBaroPressAt OutDewPointTempAt OutDryBulbTempAt OutsidePipeHeatTransCoef OutWetBulbTempAt P01 PanesDeflection ParametricObjectsCheck parseComputeLine ParseExpression ParseStack ParseTime PartLoadFactor PassiveGapNusseltNumber PassPressureAcrossInterface PassPressureAcrossMixer PassPressureAcrossSplitter PD_BEAM PD_BEAM_CASE_I PD_BEAM_CASE_II PD_BEAM_CASE_III PD_BEAM_CASE_IV PD_BEAM_CASE_V PD_BEAM_CASE_VI PD_DIFF PD_LW PD_LWP PD_SWP PerformanceCurveObject PerformanceTableObject PerformIterationLoop PerformPipeCellSimulation PerformPipeCircuitSimulation PerformSolarCalculations PerformTemperatureFieldUpdate PierceSurface PierceSurfaceVector PipeCircuitInfo_InitInOutCells PipeSegmentInfo_InitPipeCells PIUInducesPlenumAir PIUnitHasMixer PlaneEquation PlantHalfLoopSolver PlantMassFlowRatesFunc PLRResidual PLRResidual PLRResidualMixedTank PLRResidualStratifiedTank PMVResidual POLY1F POLY2F POLYF polygon_contains_point_2d popStack pos PostIPProcessing POWER PreDefTableEntry PredictSystemLoads PredictZoneContaminants PreparePipeCircuitSimulation PrepDebugFilesAndVariables PreProcessorCheck PrepVariablesISO15099 PreScanReportingVariables PresProfile PressureCurveValue ProcessDataDicFile ProcessDateString ProcessEMSInput ProcessEPWHeader ProcessForDayTypes ProcessInput ProcessInputDataFile ProcessIntervalFields ProcessMinMaxDefLine ProcessNumber ProcessScheduleInput ProcessSurfaceVertices ProcessTokens ProduceMinMaxString ProduceMinMaxStringWStartMinute ProduceRDDMDD ProfileAngle PropagateResolvedFlow PStack PsyCpAirFnWTdb PsyHfgAirFnWTdb PsyHFnTdbRhPb PsyHFnTdbW PsyHgAirFnWTdb PsyPsatFnTemp PsyPsatFnTemp_raw PsyRhFnTdbRhov PsyRhFnTdbRhovLBnd0C PsyRhFnTdbWPb PsyRhoAirFnPbTdbW PsyRhovFnTdbRh PsyRhovFnTdbRhLBnd0C PsyRhovFnTdbWPb PsyTdbFnHW PsyTdpFnTdbTwbPb PsyTdpFnWPb PsyTsatFnHPb PsyTsatFnPb PsyTwbFnTdbWPb PsyTwbFnTdbWPb_raw PsyVFnTdbWPb PsyWFnTdbH PsyWFnTdbRhPb PsyWFnTdbTwbPb PsyWFnTdpPb psz Pt2Plane PullCompInterconnectTrigger PumpDataForTable PushBranchFlowCharacteristics PushInnerTimeStepArrays pushStack PushSystemTimestepHistories PushSystemTimestepHistories PushZoneTimestepHistories PushZoneTimestepHistories QsortC QsortPartition RadialCellInfo_XY_CrossSectArea RadialCellInformation_ctor RadialSizing_Thickness Rainflow RangeCheck RB_BEAM RB_DIFF RB_F RB_LWP RB_SWP rCheckDayScheduleValueMinMax rCheckScheduleValue rCheckScheduleValueMinMax1 rCheckScheduleValueMinMax2 ReadEnergyMeters ReadEPlusWeatherForDay ReadGeneralDomainInputs ReadHorizontalTrenchInputs ReadINIFile ReadInputLine ReadPipeCircuitInputs ReadPipeSegmentInputs ReadTableData ReadUserWeatherInput ReadWeatherForDay Real_ConstrainTo Real_IsInRange real_times_vector ReAllocateAndPreserveOutputVariablesForSimulation ReallocateIntegerArray ReallocateIVar ReallocateRealArray ReallocateRVar RealPreDefTableEntry RealToStr RecKeepHeatBalance RecordOutput RectangleF_Contains ReformEIRChillerCondInletTempResidual ReformEIRChillerHeatRecovery RegisterNodeConnection RegisterPlantCompDesignFlow RegulateCondenserCompFlowReqOp ReInitPlantLoopsAtFirstHVACIteration RemoveSpaces RemoveTrailingZeros reorder ReplaceBlanksWithUnderscores ReplaceBlanksWithUnderscores ReportAirflowNetwork ReportAirHeatBalance ReportAirLoopConnections ReportAirTerminalUserDefined ReportAndTestGlycols ReportAndTestRefrigerants ReportBaseboard ReportBaseboard ReportCBVAV ReportChillerIPLV ReportCoilUserDefined ReportCompSetMeterVariables ReportController ReportCoolBeam ReportCoolTower ReportCTFs ReportCWTankInits ReportDemandManagerList ReportDesiccantDehumidifier ReportDetailedIceStorage ReportDirectAir ReportDualDuct ReportDualDuctConnections ReportDuct ReportDXCoil ReportDXCoilRating ReportDYMeters ReportEarthTube ReportEconomicVariable ReportElectricBaseboard ReportEMS ReportEvapCooler ReportEvapFluidCooler ReportExteriorEnergyUse ReportFan ReportFanCoilUnit ReportFatalGlycolErrors ReportFatalRefrigerantErrors ReportFiniteDiffInits ReportFluidCooler ReportFluidHeatExchanger ReportForTabularReports ReportFurnace ReportGlass ReportHeatBalance ReportHeatingCoil ReportHeatRecovery ReportHighTempRadiantSystem ReportHRMeters ReportHumidifier ReportHWBaseboard ReportIllumMap ReportingFreqName ReportingThisVariable ReportInternalHeatGains ReportLoopConnections ReportLowTempRadiantSystem ReportMaxVentilationLoads ReportMeterDetails ReportMissing_RangeData ReportMixer ReportMNMeters ReportMoistureBalanceEMPD ReportMSHeatPump ReportNodeConnections ReportOAController ReportOAMixer ReportOrphanFluids ReportOrphanRecordObjects ReportOrphanSchedules ReportOutdoorAirUnit ReportOutputFileHeaders ReportParentChildren ReportPipesHeatTransfer ReportPIU ReportPlantProfile ReportPlantUserComponent ReportPlantValves ReportPondGroundHeatExchanger ReportPTUnit ReportPumps ReportPurchasedAir ReportPV ReportRackSystem ReportRefrigerationComponents ReportReturnAirPath ReportRuntimeLanguage ReportScheduleDetails ReportScheduleValues ReportSizingOutput ReportSMMeters ReportSolarCollector ReportSplitter ReportStandAloneERV ReportStandAloneWaterUse ReportSteamBaseboard ReportSteamCoil ReportSurfaceErrors ReportSurfaceGroundHeatExchngr ReportSurfaceHeatBalance ReportSurfaces ReportSurfaceShading ReportSys ReportSysSizing ReportSystemEnergyUse ReportThermalChimney ReportTowers ReportTSMeters ReportUnitarySystem ReportUnitHeater ReportUnitVentilator ReportVentilatedSlab ReportVRFCondenser ReportVRFTerminalUnit ReportWarmupConvergence ReportWaterCoil ReportWaterManager ReportWaterThermalTank ReportWaterUse ReportWeatherAndTimeInformation ReportWindowAC ReportWindTurbine ReportZoneAirLoopEquipment ReportZoneAirUserDefined ReportZoneDehumidifier ReportZoneEquipment ReportZoneEvaporativeCoolerUnit ReportZoneMeanAirTemp ReportZoneReturnPlenum ReportZoneSizing ReportZoneSupplyPlenum ResetAllPlantInterConnectFlags ResetController ResetEnvironmentCounter ResetHVACControl ResetNodeData ResetPerformanceCurveOutput ResetRootFinder ResetTerminalUnitFlowLimits ResetWeekDaysByMonth Resimulate resist ReSolveAirLoopControllers ResolveAirLoopFlowLimits ResolveLocationInformation ResolveLockoutFlags ResolveLoopFlowVsPressure ResolveParallelFlows ResolveSysFlow ReverseAndRecalculate RevertZoneTimestepHistories RevertZoneTimestepHistories RevisePlantCallingOrder RezeroZoneSizingArrays RhoH2O RHtoVP RKG RoundSigDigits rRoundSigDigits rTrimSigDigits SafeCopyPlantNode SafeDiv SafeDivide SameString SandiaCellTemperature SandiaEffectiveIrradiance SandiaF1 SandiaF2 SandiaImp SandiaIsc SandiaIx SandiaIxx SandiaModuleTemperature SandiaTcellFromTmodule SandiaVmp SandiaVoc SaveSimpleController ScanForReports ScanPlantLoopsForNodeNum ScanPlantLoopsForObject sCheckDayScheduleValueMinMax ScheduleAverageHoursPerWeek SEARCH SearchAscTable SearchWindow5DataFile SecantFormula SecantMethod selectTariff SetActuatedBranchFlowRate SetAdditionalNeighborData SetAllFlowLocks SetAllPlantSimFlagsToValue SetATMixerPriFlow SetATMixerPriFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetAverageAirFlow SetCoilDesFlow SetCoilSystemCoolingData SetCoilSystemHeatingDXFlag SetCompFlowRate SetComponentFlowRate SetCurrentWeather SetCurveOutputMinMaxValues SetDSTDateRanges SetDXCoilTypeData SetDXCoolingCoilData SetEquivalentLayerWindowProperties SetErlValueNumber SetExtConvectionCoeff SetFanData SetHeatExchangerData SetHeatToReturnAirFlag SetInitialMeterReportingAndOutputNames SetIntConvectionCoeff SetInternalVariableValue SetMinMax setNativeVariables SetNodeResult SetOAControllerData SetOnOffMassFlowRate SetOnOffMassFlowRate SetOnOffMassFlowRate SetOnOffMassFlowRateVSCoil SetOnOffMassFlowRateVSCoil SetOutAirNodes SetOutBulbTempAt SetPredefinedTables SetSimpleWSHPData SETSKY SetSpecialDayDates SetSpeedVariables SetStormWindowControl SetSurfHBDataForMundtModel SetSurfHBDataForTempDistModel SetSurfTmeanAir SETUP4x4_A SetupAdaptiveConvectionRadiantSurfaceData SetupAdaptiveConvectionStaticMetaData SetupAirLoopControllersTracer SetupAllOutputVariables SetUpAndSort SetupBranchControlTypes SetupCellNeighbors SetupCommonPipes SetupComplexFenestrationMaterialInput SetupComplexFenestrationStateInput SetupComplexWindowStateGeometry SetUpCompSets SetupDElightOutput4EPlus SetupDElightOutput4EPlus SetUpDesignDay SetupEMSActuator SetupEMSIntegerActuator SetupEMSIntegerInternalVariable SetupEMSInternalVariable SetupEMSLogicalActuator SetupEMSRealActuator SetupEMSRealInternalVariable SetupEnvironmentTypes SetupFuelConstituentData SetupGeneratorControlStateManager SetupIndividualControllerTracer SetupInitialPlantCallingOrder SetupIntegerOutputVariable SetupInterpolationValues SetupLoopFlowRequest SetupMeteredVarsForSetPt SetupMundtModel SetupNodeSetpointsAsActuators SetupNodeVarsForReporting SetupOutputVariable SetupPipeCircuitInOutCells SetupPlantEMSActuators SetupPollutionCalculations SetupPollutionMeterReporting SetupPossibleOperators SetupPrimaryAirSystemAvailMgrAsActuators SetupPumpMinMaxFlows SetupRealOutputVariable SetupRealOutputVariable_IntKey SetupReportInput SetupReports SetupRootFinder SetUpSchemeColors SetupShadeSurfacesForSolarCalcs SetupSimpleWindowGlazingSystem SetupSimulation SetupStratifiedNodes SetupSurfaceConstructionActuators SetupSurfaceConvectionActuators SetupSurfaceOutdoorBoundaryConditionActuators SetUpSysSizingArrays SetupTankDemandComponent SetupTankSupplyComponent SetupThermostatActuators SetupTimePointers SetupUnitConversions SetupWeekDaysByMonth SetupWindowShadingControlActuators SetupZoneEquipmentForConvectionFlowRegime SetupZoneGeometry SetupZoneInfoAsInternalDataAvail SetupZoneInternalGain SetupZoneInternalGain SetupZoneSizing SetUpZoneSizingArrays SetUTSCQdotSource SetVarSpeedCoilData SetVentedModuleQdotSource SetVSHPAirFlow SetVSHPAirFlow SetWindSpeedAt SetZoneEquipSimOrder shading shadingedge shadingin SHADOW SharedDVCVUFDataInit SHDBKS SHDGSS SHDRVL SHDSBS shift ShiftPipeTemperaturesForNewIteration ShiftPlantLoopSideCallingOrder ShiftTemperaturesForNewIteration ShiftTemperaturesForNewTimeStep ShowAuditErrorMessage ShowBranchesOnLoop ShowContinueError ShowContinueError ShowContinueErrorTimeStamp ShowContinueErrorTimeStamp ShowErrorMessage ShowErrorMessage ShowFatalError ShowFatalError ShowMessage ShowMessage ShowPsychrometricSummary ShowRecurringContinueErrorAtEnd ShowRecurringContinueErrorAtEnd ShowRecurringErrors ShowRecurringSevereErrorAtEnd ShowRecurringSevereErrorAtEnd ShowRecurringWarningErrorAtEnd ShowRecurringWarningErrorAtEnd ShowSevereError ShowSevereError ShowSevereMessage ShowSevereMessage ShowWarningError ShowWarningError ShowWarningMessage ShowWarningMessage showWarningsBasedOnTotal Sim4PipeFanCoil SimAirChillerSet SimAirLoop SimAirLoopComponent SimAirLoopComponents SimAirLoops SimAirLoopSplitter SimAirMixer SimAirTerminalUserDefined SimAirZonePlenum SimATMixer SimBaseboard SimBLASTAbsorber SimBoiler SimCBVAV SimCBVAV SimCentralGroundSourceHeatPump SimChiller SimCoilUserDefined SimComponentModelFan SimConstVol SimCoolBeam SimCostEstimate SimCTGenerator SimCTPlantHeatRecovery SimCyclingWindowAC SimDesiccantDehumidifier SimDetailedIceStorage SimDirectAir SimDistrictEnergy SimDualDuctConstVol SimDualDuctVarVol SimDualDuctVAVOutdoorAir SimDuct SimDXCoil SimDXCoilMultiMode SimDXCoilMultiSpeed SimDXCoolingSystem SimDXHeatPumpSystem SimElecBaseBoard SimElectricBaseBoard SimElectricConvective SimElectricEIRChiller SimEvapCooler SimEvapFluidCoolers SimExhaustAbsorber SimFanCoilUnit SimFluidCoolers SimFluidHeatExchanger SimFourPipeIndUnit SimFuelCellGenerator SimFuelCellPlantHeatRecovery SimFurnace SimGasAbsorber SimGroundHeatExchangers SimHeatPumpWaterHeater SimHeatRecovery SimHighTempRadiantSystem SimHPWatertoWaterCOOLING SimHPWatertoWaterHEATING SimHPWatertoWaterSimple SimHumidifier SimHVAC SimHWBaseboard SimHWConvective SimHXAssistedCoolingCoil SimICEngineGenerator SimICEPlantHeatRecovery SimIceStorage SimIndirectAbsorber SimIndUnit SimLowTempRadiantSystem SimMicroCHPGenerator SimMicroCHPPlantHeatRecovery SimMSHeatPump SimMSHP SimMTGenerator SimMTPlantHeatRecovery SimMultiSpeedCoils SimOAComponent SimOAController SimOAMixer SimOnOffFan SimOutdoorAirEquipComps SimOutdoorAirUnit SimOutsideAirSys SimOutsideEnergy SimPackagedTerminalUnit SimPipes SimPipesHeatTransfer SimPipingSystemCircuit SimPIU SimPlantEquip SimPlantValves SimpleCoolingCoilUAResidual SimpleEvapFluidCoolerUAResidual SimpleFluidCoolerUAResidual SimpleHeatingCoilUAResidual SimpleTowerApproachResidual SimpleTowerTrResidual SimpleTowerUAResidual SimPondGroundHeatExchanger SimPressureDropSystem SimPTUnit SimPumps SimPurchasedAir SimPVGenerator SimPVTcollectors SimReformulatedEIRChiller SimRefrigCondenser SimReturnAirPath SimSelectedEquipment SimSetPointManagers SimSimpleEvapFluidCooler SimSimpleFan SimSimpleFluidCooler SimSimpleTower SimSolarCollector SimStandAloneERV SimSteamBaseboard SimSteamBoiler SimSteamCoils SimSurfaceGroundHeatExchanger SimSysAvailManager SimTESCoil SimTowers SimTranspiredCollector SimulateAllInteriorRadialSoilSlices SimulateAllLoopSideBranches SimulateAllLoopSidePumps SimulateDemandManagerList SimulateDetailedRefrigerationSystems SimulateDetailedTransRefrigSystems SimulateDualDuct SimulateFanComponents SimulateFluidCell SimulateHeatingCoilComponents SimulateInnerMostRadialSoilSlice SimulateLoopSideBranchGroup SimulateOuterMostRadialSoilSlice SimulatePlantProfile SimulateRadialInsulationCell SimulateRadialPipeCell SimulateRadialToCartesianInterface SimulateSingleDuct SimulateSteamCoilComponents SimulateVRF SimulateWaterCoilComponents SimulateWaterHeaterStandAlone SimulateWaterUse SimulateWaterUseConnection SimUnitaryBypassVAV SimUnitarySystem SimUnitHeater SimUnitVentilator SimUnitVentOAMixer SimUserDefinedPlantComponent SimVariableSpeedCoils SimVariableSpeedHP SimVariableSpeedHP SimVariableTower SimVariableVolumeFan SimVAV SimVAVVS SimVentilatedSlab SimVentSlabOAMixer SimVRF SimVRFCondenserPlant SimWaterCoils SimWaterSource SimWaterThermalTank SimWatertoAirHP SimWatertoAirHPSimple SimWindowAC SimWindTurbine SimZoneAirLoopEquipment SimZoneAirUserDefined SimZoneDehumidifier SimZoneEquipment SimZoneEvaporativeCoolerUnit SimZoneExhaustFan SimZoneOutAirUnitComps SingelSpeedDXCoolingCoilStandardRatings SingleSpeedDXHeatingCoilStandardRatings SingleSpeedFluidCooler SizeAbsorpChiller SizeAirLoopBranches SizeAirLoops SizeBaseboard SizeBoiler SizeBoiler SizeCBVAV SizeConstCOPChiller SizeController SizeCoolBeam SizeDemandSidePlantConnections SizeDirectAir SizeDualDuct SizeDXCoil SizeElecReformEIRChiller SizeElectricBaseboard SizeElectricBaseboard SizeElectricChiller SizeElectricEIRChiller SizeEngineDrivenChiller SizeEvapCooler SizeEvapFluidCooler SizeExhaustAbsorber SizeFan SizeFanCoilUnit SizeFluidCooler SizeFluidHeatExchanger SizeFurnace SizeGasAbsorber SizeGTChiller SizeHeatingCoil SizeHeatRecovery SizeHighTempRadiantSystem SizeHumidifier SizeHVACWaterToAir SizeHWBaseboard SizeIndirectAbsorpChiller SizeIndUnit SizeLowTempRadiantSystem SizeMSHeatPump SizeOAController SizeOutdoorAirUnit SizePIU SizePlantLoop SizePTUnit SizePump SizePurchasedAir SizePVT SizeStandAloneERV SizeStandAloneWaterHeater SizeSteamBaseboard SizeSteamCoil SizeSupplySidePlantConnections SizeSys SizeTankForDemandSide SizeTankForSupplySide SizeTESCoil SizeTower SizeUCSDUF SizeUnitarySystem SizeUnitHeater SizeUnitVentilator SizeVarSpeedCoil SizeVentilatedSlab SizeVRF SizeVRFCondenser SizeVSMerkelTower SizeWaterCoil SizeWaterManager SizeWaterSource SizeWindowAC SizeWrapper SizeZoneDehumidifier SizeZoneEquipment SizeZoneEvaporativeCoolerUnit SkipEPlusWFHeader SkyDifSolarShading SkyGndWeight SkyWeight SLtoAMB SLtoGL SLVSKY solar_EN673 solarISO15099 SolarSprectrumAverage SOLMATS SolveAirLoopControllers SolveForWindowTemperatures SolveRegression SolveRegulaFalsi SolverMoistureBalanceEMPD SOLVZP SortHistory Specular_Adjust Specular_EstimateDiffuseProps Specular_F Specular_OffNormal Specular_RATDiff Specular_SWP SQLiteBegin SQLiteBegin SQLiteBindDouble SQLiteBindInteger SQLiteBindLogicalMacro SQLiteBindNULL SQLiteBindText SQLiteBindTextMacro SQLiteClearBindings SQLiteCloseDatabase SQLiteColumnInt SQLiteColumnIntMacro SQLiteCommit SQLiteCommit SQLiteExecuteCommand SQLiteExecuteCommandMacro SQLiteFinalizeCommand SQLiteOpenDatabase SQLiteOpenDatabaseMacro SQLitePrepareStatement SQLitePrepareStatementMacro SQLiteResetCommand SQLiteStepCommand SQLiteWriteMessage SQLiteWriteMessageMacro SQLiteWriteMessageMacro StandardIndexTypeKey StandardVariableTypeKey StartingWindowTemps StartingWinTempsForNominalCond SteamHeatingCoilResidual StorageType StoreAPumpOnCurrentTempLoop storeIterationResults StoreRecurringErrorMessage StringValue StrToReal SumAllInternalCO2Gains SumAllInternalConvectionGains SumAllInternalGenericContamGains SumAllInternalLatentGains SumAllInternalRadiationGains SumAllReturnAirConvectionGains SumAllReturnAirLatentGains SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumHATsurf SumInternalCO2GainsByTypes SumInternalConvectionGainsByTypes SumInternalLatentGainsByTypes SumInternalRadiationGainsByTypes SummarizeErrors SumReturnAirConvectionGainsByTypes SumZoneImpacts SUN3 SUN4 SupSATResidual SurfaceScheduledSolarInc SurveyDemandManagers SystemPropertiesAtLambdaAndPhi SystemSpectralPropertiesAtPhi TableLookupObject TARCOG90 TBND TdbFnHRhPb TDMA TDMA_R TellMeHowManyObjectItemArgs TemperaturesFromEnergy TempIPtoSI TempSItoIP terpld TESCoilHumRatResidual TESCoilResidual TestAirPathIntegrity TestBranchIntegrity TestCompSet TestCompSetInletOutletNodes TestInletOutletNodes TestReturnAirPathIntegrity TestSupplyAirPathIntegrity therm1d TightenNodeMinMaxAvails TimestepInitComplexFenestration TimestepTypeName TraceAirLoopController TraceAirLoopControllers TraceIndividualController TraceIterationStamp TrackAirLoopController TrackAirLoopControllers TRadC TransAndReflAtPhi TransformVertsByAspect TransTDD Triangulate TrimSigDigits TurnOffLoopEquipment TurnOffLoopSideEquipment TurnOffReportRangeCheckErrors TurnOnPlantLoopPipes TurnOnReportRangeCheckErrors TwoSpeedFluidCooler UnitarySystemHeatRecovery UpdateAbsorberChillerComponentGeneratorSide UpdateAirflowNetwork UpdateAirMixer UpdateAirSysCompPtrArray UpdateAirSysSubCompPtrArray UpdateAirSysSubSubCompPtrArray UpdateAirZoneReturnPlenum UpdateAirZoneSupplyPlenum UpdateAnyLoopDemandAlterations UpdateATMixer UpdateBaseboard UpdateBaseboardPlantConnection UpdateBasementSurfaceTemperatures UpdateBBElecRadSourceValAvg UpdateBBRadSourceValAvg UpdateBBSteamRadSourceValAvg UpdateBLASTAbsorberRecords UpdateBoilerRecords UpdateBoilerRecords UpdateBracket UpdateBranchConnections UpdateChillerComponentCondenserSide UpdateChillerheaterRecords UpdateChillerRecords UpdateColdWeatherProtection UpdateCommonPipe UpdateComplexWindows UpdateComponentHeatRecoverySide UpdateConstCOPChillerRecords UpdateController UpdateCoolBeam UpdateCoolTower UpdateCTGeneratorRecords UpdateDataandReport UpdateDemandManagers UpdateDesiccantDehumidifier UpdateDetailedIceStorage UpdateDualDuct UpdateDuct UpdateDXCoil UpdateElectricBaseboard UpdateElectricChillerRecords UpdateElectricEIRChillerRecords UpdateEMSTrendVariables UpdateEngineDrivenChiller UpdateEvapCooler UpdateEvapFluidCooler UpdateEvaporativeCondenserBasinHeater UpdateEvaporativeCondenserWaterUse UpdateExhaustAbsorberCoolRecords UpdateExhaustAbsorberHeatRecords UpdateExhaustAirFlows UpdateFan UpdateFinalSurfaceHeatBalance UpdateFluidCooler UpdateFluidHeatExchanger UpdateFuelCellGeneratorRecords UpdateGasAbsorberCoolRecords UpdateGasAbsorberHeatRecords UpdateGSHPRecords UpdateGSHPRecords UpdateGSHPRecords UpdateGTChillerRecords UpdateHalfLoopInletTemp UpdateHeatBalHAMT UpdateHeatingCoil UpdateHeatRecovery UpdateHighTempRadiantSystem UpdateHistories UpdateHistory UpdateHTRadSourceValAvg UpdateHumidifier UpdateHVACInterface UpdateHWBaseboard UpdateHWBaseboardPlantConnection UpdateIceFractions UpdateICEngineGeneratorRecords UpdateIndirectAbsorberRecords UpdateInternalGainValues UpdateIrrigation UpdateLoadCenterRecords UpdateLoopSideReportVars UpdateLowTempRadiantSystem UpdateMeterReporting UpdateMeters UpdateMeterValues UpdateMicroCHPGeneratorRecords UpdateMinMax UpdateMixedAirSetPoints UpdateMoistureBalanceEMPD UpdateMoistureBalanceFD UpdateMSHeatPump UpdateMTGeneratorRecords UpdateNode UpdateNodeThermalHistory UpdateOAController UpdateOAMixer UpdateOAPretreatSetPoints UpdatePipesHeatTransfer UpdatePipingSystems UpdatePlantLoopInterface UpdatePlantMixer UpdatePlantProfile UpdatePlantSplitter UpdatePlantValves UpdatePondGroundHeatExchanger UpdatePrecipitation UpdatePressureDrop UpdatePurchasedAir UpdatePVTcollectors UpdateRadSysSourceValAvg UpdateRecords UpdateReformEIRChillerRecords UpdateRefrigCondenser UpdateReportWaterSystem UpdateRootFinder UpdateScheduleValues UpdateSetPointManagers UpdateSimpleWatertoAirHP UpdateSoilProps UpdateSolarCollector UpdateSplitter UpdateSQLiteErrorRecord UpdateSQLiteErrorRecord UpdateSQLiteSimulationRecord UpdateSQLiteSimulationRecord UpdateSteamBaseboard UpdateSteamBaseboardPlantConnection UpdateSteamCoil UpdateSurfaceGroundHeatExchngr UpdateSys UpdateSysSizing UpdateSystemOutputRequired UpdateTabularReports UpdateTEStorage UpdateThermalHistories UpdateTowers UpdateTranspiredCollector UpdateUnitarySystemControl UpdateUtilityBills UpdateVarSpeedCoil UpdateVentilatedSlab UpdateVerticalGroundHeatExchanger UpdateVRFCondenser UpdateWaterCoil UpdateWaterConnections UpdateWaterManager UpdateWaterSource UpdateWaterThermalTank UpdateWaterToAirCoilPlantConnection UpdateWatertoAirHP UpdateWeatherData UpdateWholeBuildingRecords UpdateZoneAirLoopEquipment UpdateZoneCompPtrArray UpdateZoneDehumidifier UpdateZoneEquipment UpdateZoneInletConvergenceLog UpdateZoneListAndGroupLoads UpdateZoneSizing UpdateZoneSubCompPtrArray UpdateZoneSubSubCompPtrArray ValidateAndSetSysAvailabilityManagerType ValidateComponent ValidateDistributionSystem ValidateEMSProgramName ValidateEMSVariableName ValidateExhaustFanInput ValidateFlowControlPaths ValidateFuelType ValidateIndexType ValidateMaterialRoughness ValidateMonthDay ValidateNStandardizeMeterTitles ValidateObjectandParse ValidatePipeConstruction ValidatePLFCurve ValidateSection ValidateSectionsInput ValidateVariableType value_to_vector ValueToString VAVVSCoolingResidual VAVVSHCFanOnResidual VAVVSHWFanOnResidual VAVVSHWNoFanResidual VB_CriticalSlatAngle VB_DIFF VB_LWP VB_ShadeControl VB_SLAT_RADIUS_RATIO VB_SOL4 VB_SOL46_CURVE VB_SOL6 VB_SWP vec2d_cross_product vec2d_dot_product vec_cross_product vec_dot_product VecLength VecNegate VecNormalize VecRound VecSquaredLength vector_add vector_div_int vector_div_real vector_subtract vector_times_int vector_times_real vector_to_array VerifyControlledZoneForThermostat VerifyCustomMetersElecPowerMgr VerifyHeatExchangerParent VerifyName VerifySetPointManagers VerifyThermostatInZone VerifyUniqueBaseboardName VerifyUniqueBoilerName VerifyUniqueChillerName VerifyUniqueCoilName ViewFac VisibleSprectrumAverage Volume VRMLOut VSCoilCyclingHumResidual VSCoilCyclingResidual VSCoilCyclingResidual VSCoilSpeedHumResidual VSCoilSpeedResidual VSCoilSpeedResidual VSEvapUnitLoadResidual VSHPCyclingResidual VSHPCyclingResidual VSHPSpeedResidual VSHPSpeedResidual VSMerkelResidual W5InitGlassParameters W5LsqFit W5LsqFit2 W6CoordsFromWorldVect warnIfNativeVarname WetCoilOutletCondition WhichCompSet WhichParentCompSet WhichParentSet Width WindowGapAirflowControl WindowGasConductance WindowGasPropertiesAtTemp WindowHeatBalanceEquations WindowScheduledSolarAbs WindowShadingManager WindowTempsForNominalCond WindSpeedAt Windward WorldVectFromW6 WriteAdaptiveComfortTable WriteAirLoopStatistics WriteBEPSTable WriteCompCostTable WriteComponentSizing WriteCumulativeReportMeterData WriteDaylightMapTitle WriteDemandEndUseSummary WriteInputArguments WriteIntegerData WriteIntegerVariableOutput WriteMeterDictionaryItem WriteModifiedArguments WriteMonthlyTables WriteOutputArguments WriteOutputEN673 WritePoint WritePredefinedTables WriteRealData WriteRealVariableOutput WriteReportHeaders WriteReportIntegerData WriteReportMeterData WriteReportRealData WriteReportVariableDictionaryItem WriteRootFinderStatus WriteRootFinderTrace WriteRootFinderTraceHeader WriteSourceEnergyEndUseSummary writeSubtitle WriteSurfaceShadowing WriteTable WriteTableOfContents WriteTabularLifeCycleCostReport WriteTabularReports WriteTabularTariffReports WriteTARCOGInputFile writeTextLine WriteTimeBinTables WriteTimeStampFormatData WriteTrace WriteVeriSumTable WriteZoneLoadComponentTable WVDC XNormalArea XYRectangle XZRectangle YNormalArea YZRectangle ZeroHVACValues ZNormalArea
Call graph
writezoneloadcomponenttable calls samestring, writetable, coolpeakdatehrmin, movingavg, createsqlitetabulardatarecords, heatpeakdatehrmin, computedelayedcomponents, psytwbfntdbwpb, writesubtitle, psyrhfntdbwpb, osc, calcfinalzonesizing, writereportheaders, convertip, surface, getspecificunitmultiplier, zoneequipconfig, zone, getspecificunitindex, realtostr
samestring calls makeuppercase
writetable calls samestring, converttoescaped, getunitsubstring, showwarningerror, insertcurrencysymbol, converttoelementtag
computedelayedcomponents calls calcfinalzonesizing, surface, zoneequipconfig
writereportheaders calls converttoelementtag, makeanchorname
getspecificunitmultiplier calls samestring
getspecificunitindex calls samestring
insertcurrencysymbol calls monetaryunit
writetabularreports calls writezoneloadcomponenttable