EnergyPlus – EnergyPlusFortran
EnergyPlus Program
278 statements
Source File
Uses:
DataPrecisionGlobals
DataStringGlobals
DataGlobals
DataInterfaces
DataSystemVariables
DataTimings
DataEnvironment
InputProcessor
SimulationManager
ScheduleManager
FluidProperties
Psychrometrics
Calls
Variables
EPlusiniFormat Blank LFN GetNewUnitNumber EPlusINI TempIndx cEnvValue iostatus FileExists
Subroutines
CreateCurrentDateTimeString ReadINIFile
Source Code
EnergyPlus
Variables
Type Attributes Name Initial
character(len=*), parameter :: EPlusiniFormat = "(/,'[',A,']',/,'dir=',A)"
character(len=*), parameter :: Blank = ' '
integer :: LFN
integer, EXTERNAL :: GetNewUnitNumber
logical :: EPlusINI
integer :: TempIndx
character(len=10) :: cEnvValue = ' '
integer :: iostatus
logical :: FileExists
Subroutines
subroutine CreateCurrentDateTimeString(CurrentDateTimeString)
Arguments
Type Intent Optional Attributes Name
character(len=*) :: CurrentDateTimeString
subroutine ReadINIFile(UnitNumber, Heading, KindofParameter, DataOut)
Arguments
Type Intent Optional Attributes Name
integer :: UnitNumber
character(len=*) :: Heading
character(len=*) :: KindofParameter
character(len=*) :: DataOut
Source Code
      PROGRAM EnergyPlus
!      NOTICE
!      Copyright  1996-2013 The Board of Trustees of the University of Illinois and The Regents of the
!      University of California through Ernest Orlando Lawrence Berkeley National Laboratory.  All rights
!      reserved.
!      Portions of the EnergyPlus(tm) software package have been developed and copyrighted by other
!      individuals, companies and institutions.  These portions have been incorporated into the EnergyPlus
!      software package under license.
!      In addition to the primary authorship of the LBNL Simulation Research Group (
!      http://simulationresearch.lbl.gov/) and the UIUC Building Systems Laboratory (
!      http://www.bso.uiuc.edu/), the following have contributed to EnergyPlus V1.0:
!      Portions of the EnergyPlus weather processor were developed by US Department of Energy, Building
!      Technologies Program, www.energyplus.gov
!      Portions of the input processing, output processing, weather processor, BLAST Translator were
!      developed by US Army Corps of Engineers, Construction Engineering Research Laboratories, 2902 Newmark
!      Drive, Champaign IL  61821. www.cecer.army.mil
!      Portions of this software package were developed by Linda Lawrie of DHL Consulting LLC.
!      Portions of this software package were developed by C.O. Pedersen Associates.
!      Portions of the EnergyPlus utility software (EP-Launch, IDFEditor, DOE2Translator, HVAC-Diagram,
!      ExpandObjects, CSVProc, System Templates, and convertESOMTR) were developed by GARD Analytics, Inc.
!      1028 Busse Highway, Park Ridge, Illinois 60068-1802, USA (847) 698-5690, www.gard.com.  GARD Analytics
!      performed independent verification and validation testing of the software after developing the testing
!      strategy and plan.  GARD Analytics was also responsible for gas absorption chiller, desiccant
!      dehumidifier, ice storage (simple), table reports and economics.
!      Portions of flow resolver, chiller models (absorption, electric, const cop, engine-driven, gas-
!      turbine), generator models (diesel electric, gas turbine), furnace models, heat recovery loop, plant
!      loop, plant condenser loop, air-change dependent inside film coefficients were developed by Oklahoma
!      State University, 110 Engineering North, Stillwater, OK 74078.
!      Portions of EnergyPlus related to the models for EMPD moisture calculations, DX coils, furnace/unitary
!      systems, cooling towers, air-to-air heat pumps, air distribution systems, refrigerated cases, electric
!      EIR chillers, packaged terminal heat pumps, desuperheater air and water heating coils, and heat pump
!      water heaters were developed by University of Central Florida, Florida Solar Energy Center (FSEC),
!      1679 Clearlake Road, Cocoa, FL  32922, www.fsec.ucf.edu/.
!      Portions of EnergyPlus were developed by the National Renewable Energy Laboratory (NREL), 1617 Cole
!      Blvd, Golden, CO 80401.
!      EnergyPlus v1.0.1, v1.0.2, v1.0.3, v1.1, v1.1.1 (Wintel platform) includes a link to TRNSYS (The Transient
!      Energy System Simulation Tool) for photovoltaic calculations developed by Thermal Energy System Specialists,
!      2916 Marketplace Drive, Suite 104, Madison, WI 53719; Tel: (608) 274-2577. EnergyPlus v1.2 and later
!      includes Photovoltaic calculations implemented in EnergyPlus by Thermal Energy System Specialists.
!      This model was originally developed by Oystein Ulleberg, Institute for Energy Technology, Norway -- based on
!      the Duffie and Beckman equivalent one-diode model.
!      Portions of this software package that convert certain stand-alone heat transfer models for slab-on-
!      grade and basement foundations were developed by William Bahnfleth, Cynthia Cogil, and Edward
!      Clements, Department of Architectural Engineering, Pennsylvania State University, 224 Engineering Unit
!      A, University Park, Pennsylvania  16802-1416, (814) 863-2076.
!      The concept and initial implementation for the EnergyPlus COM/DLL version (Wintel platform) was made
!      possible through cooperation with DesignBuilder Software, Ltd, Andy Tindale - an EnergyPlus
!      collaborative developer.
!      The thickness, conductivity, density and specific heat values of the material layers for the
!      constructions in the Composite Wall Construction reference data set have been taken from the ASHRAE
!      report "Modeling Two- and Three-Dimensional Heat Transfer through Composite Wall and Roof Assemblies
!      in Hourly  Energy Simulation Programs (1145-TRP)," by Enermodal Engineering Limited, Oak Ridge
!      National Laboratory, and the Polish Academy of Sciences, January 2001.
!      EnergyPlus v1.2 contains DELight2 (wintel platform), a simulation engine for daylighting and electric
!      lighting system analysis developed at Ernest Orlando Lawrence Berkeley National Laboratory.
!      Portions of the EnergyPlus v1.2 air distribution system calculations were written by George Walton of
!      the National Institute for Standards and Technology (NIST), 100 Bureau Drive, Gaithersburg, MD 20899,
!      (301) 975-6478.  The EnergyPlus AirflowNetwork model also includes portions of an early version of COMIS
!      (Conjunction Of Multizone Infiltration Specialists) developed by a multinational, multi-institutional
!      effort under the auspices of the International Energy Agency's Buildings and Community Systems Agreement
!      working group focusing on multizone air flow modeling (Annex 23) and now administered by the Swiss Federal
!      Laboratories for Materials Testing and Research (EMPA), Division 175, berlandstrasse 129, CH-8600 Dbendorf,
!      Switzerland.
!      The EnergyPlus v1.2 model for displacement ventilation and cross-ventilation was developed
!      by Guilherme Carrilho da Graa and Paul Linden of the Department of Mechanical and Aerospace
!      Engineering, University of California, San Diego.
!      The EnergyPlus models for UFAD served zones were developed by Anna Liu and Paul Linden at the Department
!      of Mechanical and Aerospace Engineering, University of California, San Diego.
!      ASHRAE research project 1254-RP supported the development of the following features first added in
!      EnergyPlus v1.2.2:
!         DXSystem:AirLoop enhancements (valid as OA system equipment, new humidity control options);
!         New set point managers: SET POINT MANAGER:SINGLE ZONE HEATING, SET POINT MANAGER:SINGLE ZONE COOLING,
!                 and SET POINT MANAGER:OUTSIDE AIR PRETREAT;
!         New 2-stage DX coil with enhanced dehumidification option (COIL:DX:MultiMode:CoolingEmpirical);
!         Additional DESICCANT DEHUMIDIFIER:SOLID setpoint control option;
!      American Society of Heating Refrigerating and Air-Conditioning Engineers, Inc,,
!      1791 Tullie Circle, N.E., Atlanta, GA 30329. www.ashrae.org
!      Work performed by GARD Analytics, Inc., 1028 Busse Highway, Park Ridge, Illinois 60068-1802, USA.
!      www.gard.com, November 2004.
!      EnergyPlus v1.2.2 and later versions (wintel platform) contains links to SPARK, a simulation engine for
!      detailed system modeling developed at Ernest Orlando Lawrence Berkeley National Laboratory in
!      conjunction with Ayres Sowell Associates, Inc.  SPARK was removed in V3.1 - April 2009 release.
!      The Ecoroof (Green Roof) model, first introduced in EnergyPlus v2.0, was developed at Portland State University,
!      by David Sailor and his students. It is based on the FASST vegetation models developed by Frankenstein and
!      Koenig for the US Army Corps of Engineers.
!      The HAMT (Heat And Moisture Transfer) model, first introduced in EnergyPlus v3.0.0 was developed by Phillip Biddulph,
!      Complex Built Environment Systems, The Bartlett School of Graduate Studies, University College London, Gower Street,
!      London WC1E 6BT, United Kingdom. http://www.cbes.ucl.ac.uk/.
!      The SQLite output module, first introduced in EnergyPlus v3.0.0, was developed by Gregory B. Stark, P.E.,
!      Building Synergies, LLC, 1860 Washington Street, Suite 208, Denver, Colorado 80203, United States.
!      http://www.buildingsynergies.com/
!      Refrigeration compressor performance data and refrigeration practices were provided by CDH Energy, Cazenovia, NY 12035.
!      NOTICE: The U.S. Government is granted for itself and others acting on its behalf a paid-up,
!      nonexclusive, irrevocable, worldwide license in this data to reproduce, prepare derivative works, and
!      perform publicly and display publicly.  Beginning five (5) years after permission to assert copyright
!      is granted, subject to two possible five year renewals, the U.S. Government is granted for itself and
!      others acting on its behalf a paid-up, non-exclusive, irrevocable worldwide license in this data to
!      reproduce, prepare derivative works, distribute copies to the public, perform publicly and display
!      publicly, and to permit others to do so.
!      TRADEMARKS: EnergyPlus is a trademark of the US Department of Energy.
!      Other Acknowledgments
!      This work was supported by the Assistant Secretary for Energy Efficiency and Renewable Energy, Office
!      of Building Technologies Program of the US Department of Energy.
!      Additional support was provided by the Gas Technology Institute and the California Energy Commission.
!      The ice thermal storage module development was supported by the U.S. Department of Energy Office of
!      Electricity Delivery and Energy Reliability.
!      The HAMT (Heat And Moisture Transfer) model was supported by the Engineering and Physical Sciences Research Council (EPSRC),
!      the UK government agency for funding research and training in engineering and the physical sciences.
!      The SQLite output module was funded by Building Synergies, LLC and was made possible by inclusion of software code
!      from the SQLite project (http://www.sqlite.org/).
          ! PROGRAM INFORMATION:
          !       AUTHOR         Linda K. Lawrie, et al
          !       DATE WRITTEN   January 1997.....
          !       MODIFIED       na
          !       RE-ENGINEERED  na
          ! PURPOSE OF THIS PROGRAM:
          ! This program implements the calls for EnergyPlus (originally configured
          ! as the merger of BLAST/IBLAST and DOE-2 energy analysis programs).
          ! METHODOLOGY EMPLOYED:
          ! The method used in EnergyPlus is to simplify the main program as much
          ! as possible and contain all "simulation" code in other modules and files.
          ! REFERENCES:
          ! na
          ! USE STATEMENTS:
          ! data only modules
USE DataPrecisionGlobals
USE DataStringGlobals
USE DataGlobals
USE DataInterfaces
USE DataSystemVariables
USE DataTimings
USE DataEnvironment, ONLY: IgnoreSolarRadiation, IgnoreBeamRadiation, IgnoreDiffuseRadiation
          ! routine modules
USE InputProcessor
USE SimulationManager
USE ScheduleManager, ONLY: ReportOrphanSchedules
USE FluidProperties, ONLY: ReportOrphanFluids
USE Psychrometrics, ONLY: ShowPsychrometricSummary
  IMPLICIT NONE    ! Enforce explicit typing of all variables in this routine
          ! PROGRAM PARAMETER DEFINITIONS:
          ! Note: General Parameters for the entire EnergyPlus program are contained
          ! in "DataGlobals.f90"
  CHARACTER(len=*), PARAMETER :: EPlusiniFormat="(/,'[',A,']',/,'dir=',A)"
  CHARACTER(len=*), PARAMETER :: Blank=' '
          ! INTERFACE BLOCK SPECIFICATIONS
          ! na
          ! DERIVED TYPE DEFINITIONS
          ! na
          ! PROGRAM LOCAL VARIABLE DECLARATIONS:
    INTEGER LFN  ! Unit Number for reads
    INTEGER, EXTERNAL :: GetNewUnitNumber
    LOGICAL EPlusINI
    INTEGER TempIndx
    CHARACTER(len=10)  :: cEnvValue=' '
    INTEGER :: iostatus
    LOGICAL :: FileExists
!
!
!                           INITIALIZE VARIABLES
!
                             Time_Start=epElapsedTime()
#ifdef EP_Detailed_Timings
                             CALL epStartTime('EntireRun=')
#endif
      CALL CreateCurrentDateTimeString(CurrentDateTime)
      VerString=TRIM(VerString)//','//TRIM(CurrentDateTime)
      cEnvValue=' '
      CALL Get_Environment_Variable(DDOnlyEnvVar,cEnvValue)
      cEnvValue=MakeUPPERCase(cEnvValue)
      DDOnly=(cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      cEnvValue=' '
      CALL Get_Environment_Variable(ReverseDDEnvVar,cEnvValue)
      cEnvValue=MakeUPPERCase(cEnvValue)
      ReverseDD=(cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      cEnvValue=' '
      CALL Get_Environment_Variable(FullAnnualSimulation,cEnvValue)
      cEnvValue=MakeUPPERCase(cEnvValue)
      FullAnnualRun=(cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      cEnvValue=' '
      CALL Get_Environment_Variable(cDisplayAllWarnings,cEnvValue)
      cEnvValue=MakeUPPERCase(cEnvValue)
      DisplayAllWarnings=(cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      IF (DisplayAllWarnings) THEN
        DisplayAllWarnings=.true.
        DisplayExtraWarnings=.true.
        DisplayUnusedSchedules=.true.
        DisplayUnusedObjects=.true.
      ENDIF
      cEnvValue=' '
      CALL Get_Environment_Variable(cDisplayExtraWarnings,cEnvValue)
      cEnvValue=MakeUPPERCase(cEnvValue)
      IF (cEnvValue /= Blank) &
        DisplayExtraWarnings=(cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      cEnvValue=' '
      CALL Get_Environment_Variable(cDisplayUnusedObjects,cEnvValue)
      cEnvValue=MakeUPPERCase(cEnvValue)
      IF (cEnvValue /= Blank) &
        DisplayUnusedObjects=(cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      cEnvValue=' '
      CALL Get_Environment_Variable(cDisplayUnusedSchedules,cEnvValue)
      cEnvValue=MakeUPPERCase(cEnvValue)
      IF (cEnvValue /= Blank) &
        DisplayUnusedSchedules=(cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      cEnvValue=' '
      CALL Get_Environment_Variable(cDisplayZoneAirHeatBalanceOffBalance,cEnvValue)
      cEnvValue=MakeUPPERCase(cEnvValue)
      IF (cEnvValue /= Blank) &
        DisplayZoneAirHeatBalanceOffBalance=(cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      cEnvValue=' '
      CALL Get_Environment_Variable(cDisplayAdvancedReportVariables,cEnvValue)
      cEnvValue=MakeUPPERCase(cEnvValue)
      IF (cEnvValue /= Blank) &
        DisplayAdvancedReportVariables=(cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      cEnvValue=' '
      CALL Get_Environment_Variable(cReportDuringWarmup,cEnvValue)
      cEnvValue=MakeUPPERCase(cEnvValue)
      IF (cEnvValue /= Blank) &
        ReportDuringWarmup=(cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      cEnvValue=' '
      CALL Get_Environment_Variable(cIgnoreSolarRadiation,cEnvValue)
      cEnvValue=MakeUPPERCase(cEnvValue)
      IF (cEnvValue /= Blank) &
        IgnoreSolarRadiation=(cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      cEnvValue=' '
      CALL Get_Environment_Variable(cMinimalSurfaceVariables,cEnvValue)
      cEnvValue=MakeUPPERCase(cEnvValue)
      IF (cEnvValue /= Blank) &
        CreateMinimalSurfaceVariables=(cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      cEnvValue=' '
      CALL Get_Environment_Variable(cSortIDD,cEnvValue)
      cEnvValue = MakeUPPERCase(cEnvValue)
      IF (cEnvValue /= Blank) &
        SortedIDD = (cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      cEnvValue=' '
      CALL Get_Environment_Variable(MinReportFrequencyEnvVar,cEnvValue)
      cEnvValue = MakeUPPERCase(cEnvValue)
      IF (cEnvValue /= Blank) &
        cMinReportFrequency=cEnvValue   ! turned into value later
      cEnvValue=' '
      CALL Get_Environment_Variable(cDeveloperFlag,cEnvValue)
      cEnvValue = MakeUPPERCase(cEnvValue)
      IF (cEnvValue /= Blank) &
        DeveloperFlag = (cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      cEnvValue=' '
      CALL Get_Environment_Variable(cIgnoreBeamRadiation,cEnvValue)
      cEnvValue = MakeUPPERCase(cEnvValue)
      IF (cEnvValue /= Blank) &
        IgnoreBeamRadiation = (cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      cEnvValue=' '
      CALL Get_Environment_Variable(cIgnoreDiffuseRadiation,cEnvValue)
      cEnvValue = MakeUPPERCase(cEnvValue)
      IF (cEnvValue /= Blank) &
        IgnoreDiffuseRadiation = (cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      cEnvValue=' '
      CALL Get_Environment_Variable(cSutherlandHodgman,cEnvValue)
      cEnvValue = MakeUPPERCase(cEnvValue)
      IF (cEnvValue /= Blank) &
        SutherlandHodgman = (cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      cEnvValue=' '
      CALL Get_Environment_Variable(cMinimalShadowing,cEnvValue)
      cEnvValue = MakeUPPERCase(cEnvValue)
      IF (cEnvValue /= Blank) &
        lMinimalShadowing = (cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      cEnvValue=' '
      CALL Get_Environment_Variable(cTimingFlag,cEnvValue)
      cEnvValue = MakeUPPERCase(cEnvValue)
      IF (cEnvValue /= Blank) &
        TimingFlag = (cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      ! Initialize env flags for air loop simulation debugging
      cEnvValue=' '
      CALL Get_Environment_Variable(TrackAirLoopEnvVar,cEnvValue)
      cEnvValue = MakeUPPERCase(cEnvValue)
      IF (cEnvValue /= Blank) &
        TrackAirLoopEnvFlag  = (cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      cEnvValue=' '
      CALL Get_Environment_Variable(TraceAirLoopEnvVar,cEnvValue)
      cEnvValue = MakeUPPERCase(cEnvValue)
      IF (cEnvValue /= Blank) &
        TraceAirLoopEnvFlag  = (cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      cEnvValue=' '
      CALL Get_Environment_Variable(TraceHVACControllerEnvVar,cEnvValue)
      cEnvValue = MakeUPPERCase(cEnvValue)
      IF (cEnvValue /= Blank) &
        TraceHVACControllerEnvFlag  = (cEnvValue(1:1)=='Y' .or. cEnvValue(1:1)=='T')  ! Yes or True
      INQUIRE(File='eplusout.end',EXIST=FileExists)
      IF (FileExists) THEN
        LFN=GetNewUnitNumber()
        open(unit=LFN,file='eplusout.end',action='read', iostat=iostatus)
        IF (iostatus /= 0) THEN
          CALL ShowFatalError('EnergyPlus: Could not open file "eplusout.end" for input (read).')
        ENDIF
        close(unit=LFN,status='delete')
      ENDIF
      INQUIRE(File='Energy+.ini',EXIST=EPlusINI)
      IF (EPlusINI) THEN
        LFN=GetNewUnitNumber()
        OPEN(UNIT=LFN,FILE='Energy+.ini',Action='read',IOSTAT=iostatus)
        IF (iostatus /= 0) THEN
         CALL ShowFatalError('EnergyPlus: Could not open file "Energy+.ini" for input (read).')
        ENDIF
        INQUIRE(UNIT=LFN,NAME=CurrentWorkingFolder)
        ! Relying on compiler to supply full path name here
        TempIndx=INDEX(CurrentWorkingFolder,PathChar,.true.)
        IF (TempIndx == 0) THEN
          CurrentWorkingFolder=' '
        ELSE
          CurrentWorkingFolder=CurrentWorkingFolder(1:TempIndx)
        ENDIF
                              !       Get directories from ini file
        CALL ReadINIFile(LFN,'program','dir',ProgramPath)
        CLOSE(LFN)
      ELSE
        CALL DisplayString('Missing Energy+.ini')
        ProgramPath='  '
        LFN=GetNewUnitNumber()
        OPEN(UNIT=LFN,File='Energy+.ini',Action='write',IOSTAT=iostatus)
        IF (iostatus /= 0) THEN
         CALL ShowFatalError('EnergyPlus: Could not open file "Energy+.ini" for output (write).')
        ENDIF
        ! Relying on compiler to supply full path name here
        INQUIRE(UNIT=LFN,NAME=CurrentWorkingFolder)
        TempIndx=INDEX(CurrentWorkingFolder,PathChar,.true.)
        IF (TempIndx == 0) THEN
          CurrentWorkingFolder=' '
        ELSE
          CurrentWorkingFolder=CurrentWorkingFolder(1:TempIndx)
        ENDIF
        WRITE(LFN,EPlusiniFormat) 'program',ProgramPath
        CLOSE(LFN)
      ENDIF
      TestAllPaths=.true.
      CALL DisplayString('EnergyPlus Starting')
      CALL DisplayString(VerString)
      OutputFileDebug=GetNewUnitNumber()
      OPEN (OutputFileDebug,FILE='eplusout.dbg',ACTION='write',IOSTAT=iostatus)
      IF (iostatus /= 0) THEN
       CALL ShowFatalError('EnergyPlus: Could not open file "eplusout.dbg" for output (write).')
      ENDIF
        !Call ProcessInput to produce the IDF file which is read by all of the
        ! Get input routines in the rest of the simulation
      CALL ProcessInput
      CALL ManageSimulation
      CALL ShowMessage('Simulation Error Summary *************')
      CALL GenOutputVariablesAuditReport
      CALL ShowPsychrometricSummary
      CALL ReportOrphanRecordObjects
      CALL ReportOrphanFluids
      CALL ReportOrphanSchedules
      CALL EndEnergyPlus
!
CONTAINS
SUBROUTINE CreateCurrentDateTimeString(CurrentDateTimeString)
          ! SUBROUTINE INFORMATION:
          !       AUTHOR         Linda Lawrie
          !       DATE WRITTEN   October 2010
          !       MODIFIED       na
          !       RE-ENGINEERED  na
          ! PURPOSE OF THIS SUBROUTINE:
          ! Be able to supply a current date/time string from intrinsic calls so
          ! that one is always available.
          ! METHODOLOGY EMPLOYED:
          ! na
          ! REFERENCES:
          ! na
          ! USE STATEMENTS:
          ! na
  IMPLICIT NONE ! Enforce explicit typing of all variables in this routine
          ! SUBROUTINE ARGUMENT DEFINITIONS:
  CHARACTER(len=*) :: CurrentDateTimeString
          ! SUBROUTINE PARAMETER DEFINITIONS:
          ! na
          ! INTERFACE BLOCK SPECIFICATIONS:
          ! na
          ! DERIVED TYPE DEFINITIONS:
          ! na
          ! SUBROUTINE LOCAL VARIABLE DECLARATIONS:
   integer, dimension(8) :: value
   character(len=15) datestring  ! supposedly returns blank when no date available.
!value(1)   Current year
!value(2)   Current month
!value(3)   Current day
!value(4)   Time difference with respect to UTC in minutes (0-59)
!value(5)   Hour of the day (0-23)
!value(6)   Minutes (0-59)
!value(7)   Seconds (0-59)
!value(8)   Milliseconds (0-999)
  CALL DATE_AND_TIME(date=datestring,values=value)
  IF (datestring /= Blank) THEN
    WRITE(CurrentDateTimeString,'(1X,"YMD=",I4,".",I2.2,".",I2.2,1X,I2.2,":",I2.2)')  &
       value(1),value(2),value(3),value(5),value(6)
  ELSE
    CurrentDateTimeString=' unknown date/time'
  ENDIF
  RETURN
END SUBROUTINE CreateCurrentDateTimeString
SUBROUTINE ReadINIFile(UnitNumber,Heading,KindofParameter,DataOut)
          ! SUBROUTINE INFORMATION:
          !       AUTHOR         Linda K. Lawrie
          !       DATE WRITTEN   September 1997
          !       MODIFIED       na
          !       RE-ENGINEERED  na
          ! PURPOSE OF THIS SUBROUTINE:
          ! This routine reads the .ini file and retrieves
          ! the path names for the files from it.
          ! METHODOLOGY EMPLOYED:
          ! Duplicate the kind of reading the Windows "GetINISetting" would
          ! do.
          ! REFERENCES:
          ! na
          ! USE STATEMENTS:
USE DataStringGlobals
USE DataSystemVariables
  IMPLICIT NONE    ! Enforce explicit typing of all variables in this routine
  ! SUBROUTINE ARGUMENT DEFINITIONS:
  INTEGER UnitNumber                 ! Unit number of the opened INI file
  CHARACTER(len=*) Heading           ! Heading for the parameters ('[heading]')
  CHARACTER(len=*) KindofParameter   ! Kind of parameter to be found (String)
  CHARACTER(len=*) DataOut           ! Output from the retrieval
  ! SUBROUTINE PARAMETER DEFINITIONS:
  INTEGER, PARAMETER :: LineLength=PathLimit+10
  ! INTERFACE BLOCK SPECIFICATIONS
  ! na
  ! DERIVED TYPE DEFINITIONS
  ! na
  ! SUBROUTINE LOCAL VARIABLE DECLARATIONS:
      CHARACTER(len=LineLength) :: LINE=' '
      CHARACTER(len=LineLength) :: LINEOut=' '
      CHARACTER(len=20) Param
      integer IHEAD,ILB,IRB,IEQ,IPAR,IPOS,ILEN
      INTEGER ReadStat
      LOGICAL EndofFile
      LOGICAL Found
      LOGICAL NewHeading
      DataOut='           '
            ! I tried ADJUSTL(TRIM(KindofParameter)) and got an internal compiler error
      Param=TRIM(KindofParameter)
      Param=ADJUSTL(Param)
      ILEN=LEN_TRIM(Param)
      REWIND(UnitNumber)
      EndofFile=.false.
      Found=.false.
      NewHeading=.false.
 700  FORMAT(A)
      DO WHILE (.not. EndofFile .and. .not. Found)
        READ(UnitNumber,700,IOSTAT=ReadStat) LINE
        IF (ReadStat < GoodIOStatValue) THEN
          EndofFile=.true.
          EXIT
        ENDIF
        IF (LEN_TRIM(LINE) == 0) CYCLE      ! Ignore Blank Lines
        CALL ConvertCasetoLower(LINE,LINEOut)    ! Turn line into lower case
!        LINE=LINEOut
        IHEAD=INDEX(LINEOut,Heading)
        IF (IHEAD .EQ. 0) CYCLE
!                                  See if [ and ] are on line
        ILB=INDEX(LINEOut,'[')
        IRB=INDEX(LINEOut,']')
        IF (ILB == 0 .AND. IRB == 0) CYCLE
        IF (INDEX(LINEOut,'['//TRIM(Heading)//']') == 0) CYCLE    ! Must be really correct heading line
        ILB=0
        IRB=0
!                                  Heading line found, now looking for Kind
        DO WHILE (.not. EndofFile .and. .not. NewHeading)
          READ(UnitNumber,700,IOSTAT=ReadStat) LINE
          IF (ReadStat < GoodIOStatValue) THEN
            EndofFile=.true.
            EXIT
          ENDIF
          LINE=ADJUSTL(LINE)
          IF (LEN_TRIM(LINE) == 0) CYCLE      ! Ignore Blank Lines
          CALL ConvertCasetoLower(LINE,LINEOut)    ! Turn line into lower case
!         LINE=LINEOut
          ILB=INDEX(LINEOut,'[')
          IRB=INDEX(LINEOut,']')
          NewHeading=(ILB /= 0 .and. IRB /= 0)
!                                  Should be a parameter line
!                                  KindofParameter = string
          IEQ=INDEX(LINEOut,'=')
          IPAR=INDEX(LINEOut,TRIM(Param))
          IF (IEQ == 0) CYCLE
          IF (IPAR == 0) CYCLE
          IF (IPAR /= 1) CYCLE
          IF (INDEX(LINEOut,TRIM(Param)//'=') == 0) CYCLE      ! needs to be param=
!                                  = found and parameter found.
          IF (IPAR > IEQ) CYCLE
!                                  parameter = found
!                                  Set output string to start with non-blank character
          DataOut=ADJUSTL(LINE(IEQ+1:))
          Found=.true.
          EXIT
        END DO
      END DO
      SELECT CASE (Param)
        CASE('dir')
          IPOS=LEN_TRIM(DataOut)
          IF (IPOS /= 0) THEN
                             ! Non-blank make sure last position is valid path character
                             !  (Set in DataStringGlobals)
            IF (DataOut(IPOS:IPOS) /= PathChar) THEN
              DataOut(IPOS+1:IPOS+1)=PathChar
            ENDIF
          ENDIF
        CASE DEFAULT
      END SELECT
RETURN
END SUBROUTINE ReadINIFile
END PROGRAM EnergyPlus
All Programs
EnergyPlus
Call graph
energyplus calls showpsychrometricsummary, reportorphanfluids, epelapsedtime, readinifile, showfatalerror, makeuppercase, processinput, displaystring, managesimulation, genoutputvariablesauditreport, createcurrentdatetimestring, reportorphanrecordobjects, epstarttime, currentworkingfolder, showmessage, endenergyplus, reportorphanschedules
readinifile calls convertcasetolower
processinput calls makeuppercase, displaystring, setupandsort, showcontinueerror, showfatalerror, calphafieldnames, processdatadicfile, calphaargs, showwarningerror, lalphafieldblanks, rnumericargs, cnumericfieldnames, lnumericfieldblanks, matchversion, getidfrecordsstats, finditeminlist, finditeminsortedlist, samestring, showsevereerror, processinputdatafile, iptrimsigdigits, initsecretobjects, programpath
managesimulation calls showfatalerror, displaystring, epstarttime, showmessage, testairpathintegrity, checkmarkednodes, reportairloopconnections, testcompsetinletoutletnodes, setupnodevarsforreporting, reportsurfaces, testbranchintegrity, epstoptime, checknodeconnections, trimsigdigits, setpredefinedtables, initdemandmanagers, managesizing, checkcontrollerlists, resetenvironmentcounter, producerddmdd, manageexteriorenergyuse, checkforrequestedreporting, reportnodeconnections, reportloopconnections, createsqlitesimulationsrecord, createenergyreportstructure, sqlitebegin, computelifecyclecostandreport, postipprocessing, simcostestimate, initializepsychroutines, createsqliteenvironmentperiodrecord, getnextenvironment, sqlitecommit, closeoutputtabularfile, getinputforlifecyclecost, manageweather, createzoneextendedoutput, dumpairloopstatistics, computetariff, showwarningerror, manageems, writetabularreports, updatemeterreporting, reportfortabularreports, closeoutputfiles, initializeindexes, openoutputtabularfile, checkifanyplant, getnumrangecheckerrorsfound, externalinterfaceexchangevariables, displaysimdaysprogress, checkpollutionmeterreporting, checkandreadfaults, getnumobjectsfound, setuppollutionmeterreporting, verifycustommeterselecpowermgr, checkifanyidealcondentsetpoint, setuptimepointers, getprojectdata, setuppollutioncalculations, checkifanyems, openoutputfiles, checkthreading, managebranchinput, initcurvereporting, manageheatbalance, checkformismatchedenvironmentspecifications, setupsimulation, writetabulartariffreports
genoutputvariablesauditreport calls showcontinueerror, showwarningerror, showmessage, reqrepvars
reportorphanrecordobjects calls showcontinueerror, showwarningerror, finditeminlist, finditeminsortedlist, iptrimsigdigits, showmessage
epstarttime calls tstart
endenergyplus calls epelapsedtime, displaystring, roundsigdigits, updatesqlitesimulationrecord, showrecurringerrors, summarizeerrors, reportsurfaceerrors, closemiscopenfiles, closesocket, closeoutopenfiles, epstoptime, epsummarytimes, showmessage
convertcasetolower calls lowercase
showcontinueerror calls showerrormessage, updatesqliteerrorrecord
showfatalerror calls displaystring, showerrormessage, abortenergyplus, roundsigdigits, createsqliteerrorrecord
processdatadicfile calls showsevereerror, iptrimsigdigits, readinputline, addsectiondef, addobjectdefandparse
showwarningerror calls showerrormessage, createsqliteerrorrecord, matchcounts, messagesearch
finditeminsortedlist calls makeuppercase, samestring
samestring calls makeuppercase
showsevereerror calls showerrormessage, createsqliteerrorrecord, matchcounts, messagesearch
processinputdatafile calls showsevereerror, iptrimsigdigits, showmessage, readinputline, validatesection, validateobjectandparse
showerrormessage calls displaystring, showfatalerror
abortenergyplus calls epelapsedtime, displaystring, roundsigdigits, testairpathintegrity, updatesqlitesimulationrecord, checkmarkednodes, reportairloopconnections, showrecurringerrors, testcompsetinletoutletnodes, summarizeerrors, reportsurfaceerrors, reportloopconnections, closemiscopenfiles, setupnodevarsforreporting, closesocket, closeoutopenfiles, reportsurfaces, testbranchintegrity, checkplantonabort, epstoptime, epsummarytimes, showmessage, checknodeconnections
testairpathintegrity calls showcontinueerror, showsevereerror, airtozonenodeinfo, nodeid
showrecurringerrors calls updatesqliteerrorrecord, roundsigdigits, createsqliteerrorrecord, showmessage, removetrailingzeros, recurringerrors
summarizeerrors calls showmessage, matchcounts, summaries, moredetails
closemiscopenfiles calls closedfsfile, closereportillummaps
reportsurfaces calls showwarningerror, detailsforsurfaces, setupschemecolors, vrmlout, scanforreports, dxfoutwireframe, costinfoout, linesout, dxfout
epstoptime calls showfatalerror, tstop
epsummarytimes calls roundsigdigits
showmessage calls showerrormessage
detailsforsurfaces calls roundsigdigits, getschedulename, oscm, nominalu, zone, framedivider, getschedulemaxvalue, 2, computenominaluwithconvcoeffs, 3, osc, trimsigdigits, construct, 4, csurfaceclass, userintconvectioncoeffs, userextconvectioncoeffs, surface, getscheduleminvalue, surfacewindow
setupschemecolors calls showwarningerror, getobjectitemnum, getobjectdefmaxargs, matchandsetcolortextstring, getobjectitem
vrmlout calls showcontinueerror, showfatalerror, showwarningerror, zone, surface, triangulate, getnewunitnumber
dxfoutwireframe calls showfatalerror, zone, trimsigdigits, surface, surfacewindow, getnewunitnumber, zonedaylight, dxfcolorno
costinfoout calls showfatalerror, construct, csurfaceclass, surface, getnewunitnumber
linesout calls showcontinueerror, showfatalerror, showwarningerror, roundsigdigits, csurfaceclass, surface, getnewunitnumber
dxfout calls showcontinueerror, showfatalerror, showwarningerror, zone, trimsigdigits, surface, surfacewindow, triangulate, getnewunitnumber, zonedaylight, dxfcolorno, illummapcalc
computenominaluwithconvcoeffs calls surface
matchandsetcolortextstring calls finditem
triangulate calls showcontinueerror, showwarningerror, roundsigdigits, showmessage, csurfaceclass, generate_ears, calcrfflrcoordinatetransformation, calcwallcoordinatetransformation
generate_ears calls polygon_contains_point_2d, angle_2dvector
readinputline calls makeuppercase, showcontinueerror, showfatalerror, showsevereerror, iptrimsigdigits, processnumber, processminmaxdefline
addsectiondef calls makeuppercase, showcontinueerror, showwarningerror, finditeminlist, showsevereerror
addobjectdefandparse calls makeuppercase, showcontinueerror, showwarningerror, finditeminlist, showsevereerror, iptrimsigdigits, readinputline
processminmaxdefline calls makeuppercase, showsevereerror, iptrimsigdigits, processnumber
validatesection calls makeuppercase, showcontinueerror, showwarningerror, finditeminlist, finditeminsortedlist, samestring, addrecordfromsection
validateobjectandparse calls makeuppercase, showcontinueerror, showwarningerror, finditeminlist, finditeminsortedlist, showsevereerror, iptrimsigdigits, readinputline, processnumber, showauditerrormessage, internalrangecheck, dumpcurrentlinebuffer, maketransition, extendobjectdefinition
addrecordfromsection calls showcontinueerror, showsevereerror, iptrimsigdigits, showauditerrormessage, internalrangecheck
internalrangecheck calls showsevereerror, iptrimsigdigits
dumpcurrentlinebuffer calls iptrimsigdigits, showmessage
maketransition calls makeuppercase, showfatalerror, finditeminlist, samestring, showsevereerror
extendobjectdefinition calls displaystring, iptrimsigdigits
producerddmdd calls setupandsort, showfatalerror, scanforreports, standardvariabletypekey, ddvariabletypes, samestring, standardindextypekey, energymeters
checkforrequestedreporting calls showwarningerror, getnumobjectsfound, showcontinueerror
reportnodeconnections calls nodeid, samestring, nodeconnections, parentnodelist, makeuppercase
reportloopconnections calls showmessage, nodeid, showwarningerror, samestring, showcontinueerror, reportdualductconnections, zoneequiplist, plantloop, outsideairnodelist, compsets, zoneequipconfig, loopside
postipprocessing calls showfatalerror, checkcachediperrors, showsevereerror, prescanreportingvariables, findglycol, getnumsectionsfound, compactobjectscheck, createsqlitedatabase, parametricobjectscheck, preprocessorcheck
getnextenvironment calls showfatalerror, roundsigdigits, showwarningerror, displaysimdaysprogress, showcontinueerror, showsevereerror, openweatherfile, setupemsactuator, reportoutputfileheaders, checklocationvalidity, setupoutputvariable, setupinterpolationvalues, checkweatherfilevalidity, resolvelocationinformation, closeweatherfile, calcthermalcomfortadaptivecen15251, calcthermalcomfortadaptiveash55, openeplusweatherfile, setdstdateranges, readuserweatherinput, betweendates, setspecialdaydates, julianday, allocateweatherdata
manageweather calls setcurrentweather, initializeweather, reportweatherandtimeinformation
updatemeterreporting calls showfatalerror, calphafieldnames, showwarningerror, samestring, energymeters, getcustommeterinput, reportmeterdetails, determinefrequency, getobjectitem, finditem, getnumobjectsfound, metervalue, setinitialmeterreportingandoutputnames
closeoutputfiles calls roundsigdigits
externalinterfaceexchangevariables calls showfatalerror, getnumobjectsfound
checkandreadfaults calls makeuppercase, showfatalerror, showsevereerror, getscheduleindex, getobjectitem, getnumobjectsfound
getprojectdata calls showfatalerror, calphaargs, cnumericfieldnames, lnumericfieldblanks, matchversion, samestring, roundsigdigits, 4, showwarningerror, showcontinueerror, showsevereerror, getobjectitem, getnumobjectsfound, 5
openoutputfiles calls showfatalerror, getnewunitnumber
checkthreading calls rnumericargs, roundsigdigits, getobjectitem, showwarningerror, getnumobjectsfound, showcontinueerror, maxthreads
manageheatbalance calls manageems, reckeepheatbalance, reportheatbalance, checkwarmupconvergence, reportwarmupconvergence, managesurfaceheatbalance, updateemstrendvariables, initheatbalance, getheatbalanceinput
checkformismatchedenvironmentspecifications calls showfatalerror, showwarningerror, getnumobjectsfound, showcontinueerror, showsevereerror
setupsimulation calls showfatalerror, displaystring, manageexteriorenergyuse, getnextenvironment, manageweather, getnumrangecheckerrorsfound, manageheatbalance
checkcachediperrors calls updatesqliteerrorrecord, createsqliteerrorrecord, showerrormessage
openweatherfile calls openeplusweatherfile
reportoutputfileheaders calls showfatalerror, assignreportnumber
checklocationvalidity calls showfatalerror, roundsigdigits, showwarningerror, showcontinueerror, showsevereerror, getstm
checkweatherfilevalidity calls showwarningerror
resolvelocationinformation calls roundsigdigits, showwarningerror, showcontinueerror, showsevereerror, psyrhoairfnpbtdbw
openeplusweatherfile calls showfatalerror, showcontinueerror, showsevereerror, findnonspace, skipepluswfheader, processepwheader
setdstdateranges calls showfatalerror, showsevereerror, julianday
readuserweatherinput calls showfatalerror, getnumobjectsfound, getrunperioddata, getsnowgroundrefmodifiers, getwatermainstemperatures, getdesigndaydata, getweatherstation, getgroundreflectances, getgroundtemps, getweatherproperties, getspecialdayperioddata, setupenvironmenttypes, getrunperioddesigndata, getlocationinfo, getdstdata
setspecialdaydates calls showfatalerror, showwarningerror, showcontinueerror, showsevereerror, julianday, invjulianday
psyrhoairfnpbtdbw calls showfatalerror, roundsigdigits, showcontinueerror, showsevereerror, showcontinueerrortimestamp
skipepluswfheader calls showfatalerror, makeuppercase, findnonspace, processnumber
processepwheader calls showfatalerror, roundsigdigits, showwarningerror, getnumobjectsfound, samestring, showcontinueerror, makeuppercase, showsevereerror, julianday, processnumber, setupweekdaysbymonth, finditeminlist, jgdate, processdatestring
getrunperioddata calls calphafieldnames, calphaargs, lalphafieldblanks, rnumericargs, cnumericfieldnames, trimsigdigits, getobjectitem, showwarningerror, getnumobjectsfound, samestring, showcontinueerror, showsevereerror, julianday, setupweekdaysbymonth, finditeminlist, jgdate, verifyname
getsnowgroundrefmodifiers calls 2, getobjectitem, getnumobjectsfound, showsevereerror, 12
getwatermainstemperatures calls calphafieldnames, getobjectitem, getnumobjectsfound, samestring, showsevereerror, getscheduleindex
getdesigndaydata calls calphafieldnames, calphaargs, lalphafieldblanks, rnumericargs, cnumericfieldnames, lnumericfieldblanks, roundsigdigits, getobjectitem, showwarningerror, samestring, showcontinueerror, showsevereerror, setupoutputvariable, finditeminlist, verifyname, predeftableentry, findnumberinlist, getsingledayschedulevalues, getdayscheduleindex, checkdayschedulevalueminmax, rangecheck
getweatherstation calls roundsigdigits, getobjectitem, getnumobjectsfound, showsevereerror, 6
getgroundreflectances calls getobjectitem, getnumobjectsfound, showsevereerror, 12
getgroundtemps calls getobjectitem, showwarningerror, getnumobjectsfound, showcontinueerror, showsevereerror, 12, pubgroundtempsurface
getweatherproperties calls calphafieldnames, calphaargs, lalphafieldblanks, getobjectitem, showwarningerror, getnumobjectsfound, samestring, showcontinueerror, showsevereerror, setupoutputvariable, finditeminlist, verifyname, getscheduleindex, findnumberinlist, getdayscheduleindex
getspecialdayperioddata calls calphafieldnames, cnumericfieldnames, trimsigdigits, getobjectitem, getnumobjectsfound, showsevereerror, finditeminlist, processdatestring, verifyname
setupenvironmenttypes calls julianday, jgdate, isleapyear
getrunperioddesigndata calls calphafieldnames, calphaargs, lalphafieldblanks, rnumericargs, cnumericfieldnames, trimsigdigits, getobjectitem, finditem, showwarningerror, getnumobjectsfound, samestring, showsevereerror, julianday, setupweekdaysbymonth, finditeminlist, verifyname
getlocationinfo calls getobjectitem, getnumobjectsfound, showsevereerror
getdstdata calls calphafieldnames, calphaargs, getobjectitem, getnumobjectsfound, showsevereerror, processdatestring
predeftableentry calls charpredeftableentry, realpredeftableentry, intpredeftableentry
charpredeftableentry calls incrementtableentry
realpredeftableentry calls incrementtableentry
intpredeftableentry calls incrementtableentry
setcurrentweather calls showfatalerror, julianday, psyrhoairfnpbtdbw, updateschedulevalues, determinesunupdown, psytdpfnwpb, psywfntdbrhpb, calcwatermainstemp, psywfntdbtwbpb, dayltgcurrentexthorizillum, solcos, psytwbfntdbwpb, psyhfntdbw
initializeweather calls setdstdateranges, setspecialdaydates, julianday, skipepluswfheader, isleapyear, updateweatherdata, resetweekdaysbymonth, setupdesignday, readweatherforday, reportmissing_rangedata
psytdpfnwpb calls psytsatfnpb
psywfntdbrhpb calls trimsigdigits, showcontinueerror, showcontinueerrortimestamp, showrecurringwarningerroratend, showwarningmessage, psypsatfntemp
calcwatermainstemp calls getcurrentschedulevalue
psywfntdbtwbpb calls trimsigdigits, showcontinueerror, showcontinueerrortimestamp, psywfntdbrhpb, showrecurringwarningerroratend, showwarningmessage, psypsatfntemp
dayltgcurrentexthorizillum calls solcos, dayltgluminousefficacy
psytwbfntdbwpb calls psytwbfntdbwpb_raw
psytsatfnpb calls trimsigdigits, showcontinueerror, showcontinueerrortimestamp, showrecurringwarningerroratend, showwarningmessage, iterate, psypsatfntemp
psypsatfntemp calls psypsatfntemp_raw
psypsatfntemp_raw calls showfatalerror, trimsigdigits, showcontinueerror, showsevereerror, showcontinueerrortimestamp, showrecurringwarningerroratend, showwarningmessage
dayltgluminousefficacy calls solcos
psytwbfntdbwpb_raw calls trimsigdigits, showcontinueerror, showcontinueerrortimestamp, psytsatfnpb, showrecurringwarningerroratend, showwarningmessage, iterate, psypsatfntemp
setupdesignday calls roundsigdigits, showwarningerror, showcontinueerror, showsevereerror, julianday, getsingledayschedulevalues, psytdpfnwpb, psywfntdbrhpb, psywfntdbtwbpb, psytwbfntdbwpb, calculatesundirectioncosines, psywfntdppb, psywfntdbh, psyrhfntdbwpb, ashraetaumodel, calculatedailysolarcoeffs
readweatherforday calls readeplusweatherforday
reportmissing_rangedata calls showmessage, showwarningerror
psywfntdppb calls trimsigdigits, showcontinueerror, showcontinueerrortimestamp, showrecurringwarningerroratend, showwarningmessage, psypsatfntemp
psywfntdbh calls trimsigdigits, showcontinueerror, showcontinueerrortimestamp, showrecurringwarningerroratend, showwarningmessage
psyrhfntdbwpb calls trimsigdigits, showcontinueerror, showcontinueerrortimestamp, showrecurringwarningerroratend, showwarningmessage, psypsatfntemp
ashraetaumodel calls airmass
readeplusweatherforday calls showfatalerror, roundsigdigits, showwarningerror, showcontinueerror, showsevereerror, setdstdateranges, setspecialdaydates, julianday, skipepluswfheader, rangecheck, calculatedailysolarcoeffs, getschedulevaluesforday, interpretweatherdataline
interpretweatherdataline calls showfatalerror, roundsigdigits, showcontinueerror, showsevereerror
getcustommeterinput calls makeuppercase, showcontinueerror, showwarningerror, showsevereerror, getobjectitem, finditem, getnumobjectsfound, addmeter, verifyname, determinemeteripunits, getvariablekeys, getstandardmeterresourcetype, getvariablekeycountandtype, attachcustommeters
determinefrequency calls showcontinueerror, showwarningerror, samestring
getobjectitem calls makeuppercase, processinput, showfatalerror, showwarningerror, finditeminlist, finditeminsortedlist, samestring, iptrimsigdigits, getobjectitemfromfile
finditem calls makeuppercase, finditeminlist
getnumobjectsfound calls makeuppercase, showwarningerror, finditeminlist, finditeminsortedlist
setinitialmeterreportingandoutputnames calls showwarningerror, trimsigdigits, energymeters, determineindexgroupkeyfrommetername, writemeterdictionaryitem, determineindexgroupfrommetergroup
addmeter calls showcontinueerror, showfatalerror, assignreportnumber, finditeminlist, determinemeteripunits
verifyname calls showsevereerror, finditem
determinemeteripunits calls showwarningerror, samestring, makeuppercase
getvariablekeys calls showfatalerror, makeuppercase, getscheduleindex, rvariabletypes, ivariabletypes
getstandardmeterresourcetype calls showsevereerror, makeuppercase
getvariablekeycountandtype calls setupandsort, ddvariabletypes, energymeters, makeuppercase, getscheduleindex, rvariabletypes, ivariabletypes, finditeminsortedlist, reallocateintegerarray, getscheduletype
writemeterdictionaryitem calls createsqlitereportvariabledictionaryrecord, createsqlitemeterdictionaryrecord
createsqlitereportvariabledictionaryrecord calls sqlitebindnull, sqliteresetcommand, storagetype, sqlitebindinteger, sqlitebindtextmacro, reportingfreqname, timesteptypename, sqlitestepcommand
createsqlitemeterdictionaryrecord calls sqlitebindnull, sqliteresetcommand, storagetype, sqlitebindinteger, sqlitebindtextmacro, reportingfreqname, timesteptypename, sqlitestepcommand
sqlitebindtextmacro calls sqlitebindtext
reckeepheatbalance calls roundsigdigits, zone, snloadheatrate, snloadcoolrate, ztav
reportheatbalance calls updatedataandreport, reportschedulevalues, calcmorenodeinfo, updateutilitybills, updatetabularreports
checkwarmupconvergence calls roundsigdigits, zone, showcontinueerror, showsevereerror
reportwarmupconvergence calls roundsigdigits, zone, 10
managesurfaceheatbalance calls displaystring, construct, surface, calcheatbalanceoutsidesurf, updatefinalsurfaceheatbalance, manageairheatbalance, calcheatbalanceinsidesurf, updatemoisturebalancefd, updatethermalhistories, reportsurfaceheatbalance, initsurfaceheatbalance, managethermalcomfort
initheatbalance calls displaystring, surfacewindow, performsolarcalculations, allocateheatbalarrays, initequivalentlayerwindowcalculations, initdaylightingdevices, setstormwindowcontrol, initglassopticalcalculations, stormwindow, initconductiontransferfunctions, initsolarcalculations
getheatbalanceinput calls showfatalerror, showsevereerror, manageinternalheatgains, getprojectcontroldata, getscheduledsurfacegains, getsiteatmospheredata, getconstructdata, checkvalidsimulationobjects, createtcconstructions, getwindowglassspectraldata, getbuildingdata, checkusedconstructions, getmaterialdata, getframeanddividerdata
updatedataandreport calls showfatalerror, showsevereerror, getcurrentschedulevalue, rvariabletypes, ivariabletypes, reporthrmeters, reporttsmeters, writeintegervariableoutput, writerealvariableoutput, reportdymeters, reportsmmeters, reportmnmeters, encodemondayhrmin, timevalue, writetimestampformatdata, updatemeters, daytypes, writerealdata, writeintegerdata, updatemetervalues, varmeterarrays
reporthrmeters calls writetimestampformatdata, writecumulativereportmeterdata, writereportmeterdata
reporttsmeters calls writetimestampformatdata, writecumulativereportmeterdata, writereportmeterdata
writeintegervariableoutput calls writereportintegerdata
writerealvariableoutput calls writereportrealdata
reportdymeters calls writetimestampformatdata, writecumulativereportmeterdata, writereportmeterdata
reportsmmeters calls writetimestampformatdata, writecumulativereportmeterdata, writereportmeterdata
reportmnmeters calls writetimestampformatdata, writecumulativereportmeterdata, writereportmeterdata
writetimestampformatdata calls sqlitewritemessagemacro, createsqlitetimeindexrecord
updatemeters calls setminmax
writerealdata calls removetrailingzeros, createsqlitereportvariabledatarecord
writeintegerdata calls removetrailingzeros, createsqlitereportvariabledatarecord
writecumulativereportmeterdata calls removetrailingzeros, createsqlitemeterrecord, createsqlitereportvariabledatarecord
writereportmeterdata calls removetrailingzeros, createsqlitemeterrecord, createsqlitereportvariabledatarecord, produceminmaxstring
createsqlitemeterrecord calls sqlitebindnull, sqliteresetcommand, sqlitebindinteger, sqlitestepcommand, sqlitewritemessagemacro, adjustreportinghourandminutes, sqlitebinddouble, decodemondayhrmin
createsqlitereportvariabledatarecord calls sqlitebindnull, sqliteresetcommand, sqlitebindinteger, sqlitestepcommand, sqlitewritemessagemacro, adjustreportinghourandminutes, sqlitebinddouble, decodemondayhrmin
sqlitewritemessagemacro calls sqlitewritemessage
produceminmaxstring calls decodemondayhrmin
writereportintegerdata calls removetrailingzeros, createsqlitereportvariabledatarecord, produceminmaxstring
writereportrealdata calls removetrailingzeros, createsqlitereportvariabledatarecord, produceminmaxstring
createsqlitetimeindexrecord calls sqlitebindnull, sqliteresetcommand, sqlitebindinteger, sqlitebindtextmacro, sqlitestepcommand, sqlitewritemessagemacro, adjustreportinghourandminutes
updatefinalsurfaceheatbalance calls calcheatbalanceoutsidesurf, calcheatbalanceinsidesurf, updatehtradsourcevalavg, updateradsyssourcevalavg, updatebbradsourcevalavg, updatebbelecradsourcevalavg, updatebbsteamradsourcevalavg
updatethermalhistories calls construct, surface, ctftsrcconstpart, tempsurfin, sumh, th, ctfconstinpart, tempsource, thm, opaqsurfinsfaceconduction, qh, qsrchist, qhm, opaqsurfinsfaceconductionflux, tsrchistm, opaqsurfinsfacecondlossrep, tsrchist, opaqsurfinsfacecondgainrep, qsrchistm, opaqsurfoutsidefaceconduction, opaqsurfoutsidefaceconductionflux, ctfconstoutpart
reportsurfaceheatbalance calls surface, opaqsurfinsfaceconduction, opaqsurfinsfaceconductionflux, opaqsurfinsfacecondlossrep, opaqsurfinsfacecondgainrep, opaqsurfoutsidefaceconduction, opaqsurfoutsidefaceconductionflux, opaqsurfstoragegainrep, lightswradseq, opaqsurfavgfaceconductionenergy, qelecbaseboardsurf, reportsurfaceshading, qradswinabs, fenesolarradseq, netlwradtosurf, qdotradnetsurfinrepperarea, qsteambaseboardsurf, qradnetsurfinreport, zoneopaqsurfinsfacecond, znopqsurfinsfacecondgnrepenrg, qradsolarinreport, qdotradsolarinrepperarea, qdotradsolarinrep, qradlightsinreport, qdotradlightsinrepperarea, opaqsurfstoragecondlossrep, znopqsurfinsfacecondlsrepenrg, qdotradlightsinrep, opaqsurfstorageconduction, znopqsurfextfacecondlsrepenrg, qradintgainsinreport, opaqsurfstorageconductionflux, znopqsurfextfacecondgnrepenrg, qdotradintgainsinrepperarea, zoneopaqsurfextfacecond, qdotradintgainsinrep, qradtherminabs, opaqsurfstorageconductionenergy, qradhvacinreport, qdotradhvacinrep, zoneopaqsurfinsfacecondgainrep, zoneopaqsurfinsfacecondlossrep, qdotradhvacinrepperarea, zoneopaqsurfextfacecondgainrep, zoneopaqsurfextfacecondlossrep, qhwbaseboardsurf, opaqsurfinsfaceconductionenergy, qradswlightsinabs, qhtradsyssurf, opaqsurfextfacecondgainrep, mrt, opaqsurfextfacecondlossrep, opaqsurfavgfacecondgainrep, zonemrt, qdotradnetsurfinrep, opaqsurfoutsidefaceconductionenergy, opaqsurfavgfacecondlossrep, opaqsurfavgfaceconductionflux, opaqsurfavgfaceconduction
initsurfaceheatbalance calls showfatalerror, displaystring, zone, construct, surface, surfacewindow, zonedaylight, showwarningerror, showsevereerror, solcos, ctftsrcconstpart, th, ctfconstinpart, qh, qsrchist, tsrchist, ctfconstoutpart, initsolarheatgains, iszonecv, timestepinitcomplexfenestration, computedifsolexczoneswizwindows, initintsolardistribution, dayltginterreflillfrintwins, anisoskyviewfactors, gatherforpredefinedreport, computeintswabsorpfactors, iszonedv, windowshadingmanager, computeintthermalabsorpfactors, iszoneui, initinteriorconvectioncoeffs, initheatbalfinitediff, dayltginteriorillum, allocatesurfaceheatbalarrays, dayltgeleclightingcontrol, calcinteriorradexchange, dayltginteriortddillum, dayltginteriormapillum, manageinternalheatgains, reportillummap, setwindspeedat, initthermalandfluxhistories, delightelecltgctrl, initemscontrolledconstructions, dayltgglarewithintwins, setoutbulbtempat, initemscontrolledsurfaceproperties
reportsurfaceshading calls surface, predeftableentry, sunlitfrac, surfsunlitfrac, surfsunlitarea
initsolarheatgains calls framedivider, construct, surface, surfacewindow, solcos, qradswinabs, sunlitfrac, anisoskymult, findtddpipe, dbzone, evaloutsidemovableinsulation, qradswwinabs, dbzoneintwin, initialzonedifsolreflw, recdifshortfromz, fractdifshortztoz, transtdd, qsdifsol, interpsw, calcinteriorsolardistribution, qradswoutabs, calcwindowprofileangles, vmult, windowscheduledsolarabs, shelf, reflfacbmtodiffsolobs, interpprofslatang, reflfacskysolobs, reflfacbmtodiffsolgnd, qradswwinabstot, reflfacskysolgnd, dbzonessg, surfacescreens, surfacescheduledsolarinc, aisurf, material, aosurf, qradswoutincidentbeam, bmtodiffreflfacobs, opaqsurfinsfacebeamsolabsorbed, qradswoutincbmtodiffreflobs, bmtobmreflfacobs, cosincang, cosincidenceangle, bmtodiffreflfacgnd, reflfacbmtobmsolobs, qradswwinabstotenergy, getcurrentschedulevalue, awincfoverlap, qradswoutincskydiffreflobs, polyf, blind, awinsurf, cfs, profileangle, blindbeambeamtrans, swoutabsenergyreport, interpslatang, swoutabstotalreport, qradswwinabslayer, qdfordaylight, qradswoutincidentgnddiffuse, qradswoutincident, fenlayabsssg, qd, qradswoutincidentskydiffuse, qradswoutincbmtodiffreflgnd, qradswoutincbmtobmreflobs, tddpipe, qradswoutincskydiffreflgnd
timestepinitcomplexfenestration calls surfacewindow, complexwind, checkcfsstates, calccomplexwindowoverlap
computedifsolexczoneswizwindows calls zone, construct, surface, recdifshortfromz, fractdifshortztoz, vmult
initintsolardistribution calls zone, construct, surface, surfacewindow, qelecbaseboardsurf, qradswinabs, qsteambaseboardsurf, qradtherminabs, qhwbaseboardsurf, qradswlightsinabs, qhtradsyssurf, evaloutsidemovableinsulation, qradswwinabs, recdifshortfromz, fractdifshortztoz, interpsw, qradswoutabs, vmult, material, blind, cfs, swoutabsenergyreport, interpslatang, swoutabstotalreport, qd, zonebmsolfrintwinsrep, initialdifsolinabs, initialdifsolwinabs, initialdifsolintrans, zonedifsolfrintwinsrepenergy, evalinsidemovableinsulation, zonedifsolfrintwinsrep, qradswoutmvins, zoneintgain, qslights, intbmincinssurfamountrepenergy, distributetddabsorbedsolar, qs, intbmincinssurfintensrep, intbmincinssurfamountrep, tmult, initialdifsolinabsreport, swwinabstotalreport, ql, initialdifsolintransreport, swinabstotalreport, itabsf
dayltginterreflillfrintwins calls zone, construct, surface, surfacewindow, zonedaylight, dbzoneintwin, qsdifsol
anisoskyviewfactors calls surface, solcos, sunlitfrac, anisoskymult, difshdgratioisoskyhrts, curdifshdgratioisosky, difshdgratiohoriz, multcircumsolar, multisosky, difshdgratiohorizhrts, difshdgratioisosky, multhorizonzenith
gatherforpredefinedreport calls nominalu, zone, framedivider, construct, surface, predeftableentry, calcnominalwindowcond, windowshadingcontrol
computeintswabsorpfactors calls zone, construct, surface, surfacewindow, showwarningerror, interpsw, vmult, material, cfs, interpslatang, evalinsidemovableinsulation, vconv
windowshadingmanager calls construct, surface, surfacewindow, zonedaylight, solcos, getcurrentschedulevalue, snloadheatrate, snloadcoolrate, sunlitfrac, anisoskymult, cosincang, polyf, blind, profileangle, windowshadingcontrol, mat, calcscreentransmittance
computeintthermalabsorpfactors calls zone, construct, surface, surfacewindow, evaloutsidemovableinsulation, interpsw, material, blind, interpslatang, tmult, itabsf, tconv
dayltginteriorillum calls zone, construct, surface, surfacewindow, zonedaylight, polyf, interpslatang, windowshadingcontrol, dayltgglare
allocatesurfaceheatbalarrays calls displaystring, zone, construct, surface, surfacewindow, setupoutputvariable, ctftsrcconstpart, tempsurfin, sumh, th, ctfconstinpart, tempsource, thm, opaqsurfinsfaceconduction, qh, qsrchist, qhm, opaqsurfinsfaceconductionflux, tsrchistm, opaqsurfinsfacecondlossrep, tsrchist, opaqsurfinsfacecondgainrep, qsrchistm, opaqsurfoutsidefaceconduction, opaqsurfoutsidefaceconductionflux, ctfconstoutpart, opaqsurfstoragegainrep, opaqsurfavgfaceconductionenergy, qelecbaseboardsurf, qradswinabs, netlwradtosurf, qdotradnetsurfinrepperarea, qsteambaseboardsurf, qradnetsurfinreport, qradsolarinreport, qdotradsolarinrepperarea, qdotradsolarinrep, qradlightsinreport, qdotradlightsinrepperarea, opaqsurfstoragecondlossrep, qdotradlightsinrep, opaqsurfstorageconduction, qradintgainsinreport, opaqsurfstorageconductionflux, qdotradintgainsinrepperarea, qdotradintgainsinrep, qradtherminabs, opaqsurfstorageconductionenergy, qradhvacinreport, qdotradhvacinrep, qdotradhvacinrepperarea, qhwbaseboardsurf, opaqsurfinsfaceconductionenergy, qradswlightsinabs, qhtradsyssurf, opaqsurfextfacecondgainrep, mrt, opaqsurfextfacecondlossrep, opaqsurfavgfacecondgainrep, zonemrt, qdotradnetsurfinrep, opaqsurfoutsidefaceconductionenergy, opaqsurfavgfacecondlossrep, opaqsurfavgfaceconductionflux, opaqsurfavgfaceconduction, qradswwinabs, qradswoutabs, opaqsurfinsfacebeamsolabsorbed, swoutabsenergyreport, swoutabstotalreport, qdfordaylight, qd, initialdifsolinabs, initialdifsolwinabs, initialdifsolintrans, qradswoutmvins, ql, tempeffbulkair, hmassconvinfd, tempsurfintmp, hconvinfd, hairextsurf, hskyextsurf, radsystihbconstcoef, qpvsyssource, radsystihbtoutcoef, radsystihbqsrccoef, hgrndfd, qdotconvinrep, hskyfd, tempsurfinrep, qdotconvinrepperarea, tempsurfout, hairfd, qconvinreport, hconvin, rhovaporsurfin, qdotradoutrep, qradoutreport, radsystohbqsrccoef, qdotradoutrepperarea, radsystohbtincoef, qdotconvoutrep, hcextsurf, qconvoutreport, rhovaporairin, qdotconvoutrepperarea, qradsyssource, hgrdextsurf, tcondfdsourcenode, radsystohbconstcoef, tempoutsideairfd, qc, rhovaporairout, qdv, hconvextfd, hmassconvextfd
dayltgeleclightingcontrol calls zonedaylight, illummapcalc, reportillummap, getcurrentschedulevalue
dayltginteriortddillum calls tddpipe
dayltginteriormapillum calls construct, surface, surfacewindow, zonedaylight, illummapcalc, polyf, interpslatang, windowshadingcontrol
reportillummap calls showfatalerror, roundsigdigits, zonedaylight, illummapcalc, showwarningerror, showcontinueerror, illummap, writedaylightmaptitle, createsqlitedaylightmap, curmndyhr
initthermalandfluxhistories calls oscm, construct, surface, th, thm, qh, qhm, extventedcavity
initemscontrolledconstructions calls trimsigdigits, construct, surface, showwarningerror, showcontinueerror, showsevereerror, emsconstructactuatorchecked, emsconstructactuatorisokay, constructfd
dayltgglarewithintwins calls surfacewindow, zonedaylight
setoutbulbtempat calls showcontinueerror, showfatalerror, showsevereerror, roundsigdigits
initemscontrolledsurfaceproperties calls construct, material
evaloutsidemovableinsulation calls showfatalerror, surface, getcurrentschedulevalue, material
calcinteriorsolardistribution calls zone, construct, surface, surfacewindow, getcurrentschedulevalue, sunlitfrac, anisoskymult, findtddpipe, dbzone, dbzoneintwin, transtdd, interpsw, windowscheduledsolarabs, shelf, interpprofslatang, dbzonessg, surfacescreens, surfacescheduledsolarinc, aisurf, material, aosurf, cosincang, awincfoverlap, polyf, blind, awinsurf, cfs, blindbeambeamtrans, interpslatang, tddpipe, winbmbmsolarenergy, windifsolarenergy, zonebmsolfrextwinsrep, zonetranssolarenergy, zonebmsolfrintwinsrep, profileangle, zonebmsolfrextwinsrepenergy, zonedifsolfrextwinsrepenergy, zonebmsolfrintwinsrepenergy, zonedifsolfrextwinsrep, calceqlopticalproperty, windirsoltransatincangle, bmincinssurfamountrepenergy, winbmsolarenergy, windifsolar, cfsdiffabstrans, calcwintransdifsolinitialdistribution, backsurfaces, sunlitfracwithoutreveal, overlapareas, wintranssolar, winbmdifsolarenergy, dgzone, shadowcomb, bsdfbeamdirectionrep, dszone, bmincinssurfintensrep, bsdfbeamthetarep, bsdfbeamphirep, bmincinssurfamountrep, winbmsolar, complexwind, surfincsolssg, winbmbmsolar, winbmdifsolar, wintranssolarenergy, zonetranssolar
calcwindowprofileangles calls surface, surfacewindow, solcos, cosincang
windowscheduledsolarabs calls fenlayabsssg
surfacescheduledsolarinc calls surfincsolssg
getcurrentschedulevalue calls showcontinueerror, showwarningerror
profileangle calls surface
calcwintransdifsolinitialdistribution calls zone, construct, surface, surfacewindow, getcurrentschedulevalue, initialzonedifsolreflw, interpsw, material, cfs, interpslatang, calceqlopticalproperty, windifsolar, calcinteriorwintransdifsolinitialdistribution, initialdifsolinabs, initialdifsolwinabs, initialdifsolintrans, zoneinfo
calcinteriorwintransdifsolinitialdistribution calls zone, construct, surface, surfacewindow, getcurrentschedulevalue, initialzonedifsolreflw, interpsw, material, interpslatang, initialdifsolinabs, initialdifsolwinabs, initialdifsolintrans, zoneinfo
calccomplexwindowoverlap calls construct, surface, surfacewindow, material, shadowcomb, determinepolygonoverlap, ctrans, htrans1
determinepolygonoverlap calls roundsigdigits, showwarningerror, intcpt, inclos, clippoly, order, htrans0
ctrans calls surface, z0, y0, x0
htrans1 calls showfatalerror, trimsigdigits
clippoly calls safedivide, reallocaterealarray
htrans0 calls showfatalerror, trimsigdigits
evalinsidemovableinsulation calls showfatalerror, surface, getcurrentschedulevalue, material
calcscreentransmittance calls showfatalerror, surface, surfacewindow, solcos
dayltgglare calls surfacewindow, zonedaylight
writedaylightmaptitle calls zone, createsqlitedaylightmaptitle
createsqlitedaylightmap calls sqliteresetcommand, sqlitebindinteger, sqlitestepcommand, sqlitebinddouble
createsqlitedaylightmaptitle calls sqliteresetcommand, sqlitebindinteger, sqlitebindtextmacro, sqlitestepcommand, sqlitebinddouble
performsolarcalculations calls displaystring, calcdayltgcoefficients, skydifsolarshading, calcbeamsolspecularreflfactors, sun3, calcbeamsoldiffusereflfactors, calcpersolarbeam
allocateheatbalarrays calls getcurrentschedulevalue, ztav, mat, eamfl, sumconvhtradsys, qsteambaseboardtoperson, sumlatenthtradsys, xm2t, zoneairco2temp, qhtradsystoperson, mcpe, mcptc, xm3t, dsxmat, xm4t, mcpte, dsxm2t, xmpt, dsxm4t, sumhmara, mcpi, zoneairgc, dsxm3t, mcpti, mcptv, sumhmaraw, mcpv, mcpc, mcpm, zt, mixingmassflowzone, mcptm, ctmfl, mixingmassflowxhumrat, vamfl, oamfl, qhwbaseboardtoperson, ztavcomf, zonetmx, qelecbaseboardtoperson, temptstatair, xmat, zonetm2, sumhmaw, zoneairhumrat, zoneairhumratold, zonelatentgain, zoneairhumratavgcomf, mdotcpoa, zoneairhumratavg, mdotoa, zoneairco2avg, zoneairgcavg, zoneairco2, zoneairgctemp
setstormwindowcontrol calls surfacewindow, betweendates, stormwindow
initglassopticalcalculations calls construct, surface, surfacewindow, showwarningerror, showcontinueerror, surfacescreens, material, blind, systemspectralpropertiesatphi, w5lsqfit, diffuseaverage, checkandreadcustomsprectrumdata, visiblesprectrumaverage, solarsprectrumaverage, transandreflatphi, reportglass, w5initglassparameters, spectraldata
initconductiontransferfunctions calls showfatalerror, roundsigdigits, construct, showcontinueerror, showsevereerror, material, calculateexponentialmatrix, calculateinversematrix, calculatectfs, calculategammas, displaynumberandstring, reportctfs
initsolarcalculations calls showfatalerror, displaystring, determineshadowingcombinations, computewinshadeabsorpfactors, initsolreflrecsurf, allocatemodulearrays, computeintsolarabsorpfactors, getshadowinginput
skydifsolarshading calls surface, setupoutputvariable, difshdgratioisoskyhrts, curdifshdgratioisosky, difshdgratiohoriz, difshdgratiohorizhrts, difshdgratioisosky, withshdghoriz, shadow, withshdgisosky, woshdghoriz, woshdgisosky
calcbeamsolspecularreflfactors calls displaystring, reflfacbmtobmsolobs, cosincavebmtobmsolobs, figurebeamsolspecularreflfactors
calcbeamsoldiffusereflfactors calls displaystring, reflfacbmtodiffsolobs, reflfacbmtodiffsolgnd, figurebeamsoldiffusereflfactors
calcpersolarbeam calls sunlitfrac, aosurf, cosincang, backsurfaces, sunlitfracwithoutreveal, overlapareas, cosincanghr, figuresuncosines, sunlitfrachr, updatecomplexwindows, figuresolarbeamattimestep
shadow calls surface, shadowcomb, ctrans, htrans1, shdgss, shdbks, shdsbs
shdgss calls surface, shadowcomb, determinepolygonoverlap, ctrans, htrans1, htrans0, clip, lookupschedulevalue, multol, shadev
shdbks calls shadowcomb, determinepolygonoverlap, ctrans, htrans1, htrans0
shdsbs calls construct, surface, sunlitfracwithoutreveal, shadowcomb, htrans1, multol, shadev, shdrvl, calcinteriorsolaroverlaps
multol calls determinepolygonoverlap
shdrvl calls surface, determinepolygonoverlap, htrans1, multol, shadev
calcinteriorsolaroverlaps calls surface, surfacewindow, backsurfaces, overlapareas, multol
figurebeamsolspecularreflfactors calls construct, surface, sunlitfrac, reflfacbmtobmsolobs, polyf, cosincavebmtobmsolobs, suncoshr, piercesurface
piercesurface calls surface
figurebeamsoldiffusereflfactors calls surface, sunlitfrac, reflfacbmtodiffsolobs, reflfacbmtodiffsolgnd, suncoshr, piercesurface
figuresuncosines calls suncoshr, suncosts, sun4
figuresolarbeamattimestep calls surface, sunlitfrac, cosincang, difshdgratioisoskyhrts, difshdgratiohorizhrts, withshdghoriz, shadow, withshdgisosky, woshdghoriz, woshdgisosky, cosincanghr, sunlitfrachr, suncosts, calcframedividershadow
calcframedividershadow calls framedivider, surface, surfacewindow
systemspectralpropertiesatphi calls systempropertiesatlambdaandphi, interpolate
checkandreadcustomsprectrumdata calls showfatalerror, samestring, showsevereerror, getobjectitem, getnumobjectsfound, getobjectdefmaxargs
visiblesprectrumaverage calls interpolate
transandreflatphi calls interpolatebetweentwovalues, interpolatebetweenfourvalues
reportglass calls roundsigdigits, scanforreports, nominalu, 3, construct, 4, showwarningerror, showcontinueerror, 6, 5, 10, surfacescreens, material, blind, spectraldata, 8, calccomplexwindowthermal, calcnominalwindowcond, 7, 11, 16, 17
w5initglassparameters calls showmessage, roundsigdigits, framedivider, construct, surface, surfacewindow, showwarningerror, material, windowshadingcontrol
getobjectdefmaxargs calls makeuppercase, finditeminlist, finditeminsortedlist, showsevereerror
calcnominalwindowcond calls construct, interpprofslatang, surfacescreens, material, polyf, blind, blindbeambeamtrans, interpslatang, windowtempsfornominalcond
windowtempsfornominalcond calls showfatalerror, construct, lusolution, startingwintempsfornominalcond, psyrhoairfnpbtdbw, nusseltnumber, windowgasconductance, ludecomposition
nusseltnumber calls surface
ludecomposition calls showfatalerror
reportctfs calls scanforreports, 2, 3, construct, 4, material, displaymaterialroughness
determineshadowingcombinations calls trimsigdigits, construct, surface, showwarningerror, showcontinueerror, showsevereerror, showwarningmessage, shadowcomb, chkbks, showseveremessage, chksbs, chkgss
computewinshadeabsorpfactors calls construct, surface, surfacewindow, material, windowshadingcontrol
initsolreflrecsurf calls construct, surface, showwarningerror, showcontinueerror, reflfacbmtodiffsolobs, reflfacskysolobs, reflfacbmtodiffsolgnd, reflfacskysolgnd, reflfacbmtobmsolobs, cosincavebmtobmsolobs, piercesurface, crossproduct
allocatemodulearrays calls displaystring, roundsigdigits, zone, construct, surface, surfacewindow, setupoutputvariable, zoneopaqsurfinsfacecond, znopqsurfinsfacecondgnrepenrg, znopqsurfinsfacecondlsrepenrg, znopqsurfextfacecondlsrepenrg, znopqsurfextfacecondgnrepenrg, zoneopaqsurfextfacecond, zoneopaqsurfinsfacecondgainrep, zoneopaqsurfinsfacecondlossrep, zoneopaqsurfextfacecondgainrep, zoneopaqsurfextfacecondlossrep, sunlitfrac, surfsunlitfrac, surfsunlitarea, anisoskymult, initialzonedifsolreflw, qradswwinabstot, qradswoutincidentbeam, qradswoutincbmtodiffreflobs, cosincang, cosincidenceangle, qradswwinabstotenergy, qradswoutincskydiffreflobs, qradswwinabslayer, qradswoutincidentgnddiffuse, qradswoutincident, qradswoutincidentskydiffuse, qradswoutincbmtodiffreflgnd, qradswoutincbmtobmreflobs, qradswoutincskydiffreflgnd, winbmbmsolarenergy, windifsolarenergy, zonebmsolfrextwinsrep, zonetranssolarenergy, zonebmsolfrintwinsrep, zonebmsolfrextwinsrepenergy, zonedifsolfrextwinsrepenergy, zonebmsolfrintwinsrepenergy, zonedifsolfrextwinsrep, windirsoltransatincangle, bmincinssurfamountrepenergy, winbmsolarenergy, windifsolar, backsurfaces, sunlitfracwithoutreveal, overlapareas, wintranssolar, winbmdifsolarenergy, bsdfbeamdirectionrep, bmincinssurfintensrep, bsdfbeamthetarep, bsdfbeamphirep, bmincinssurfamountrep, winbmsolar, winbmbmsolar, winbmdifsolar, wintranssolarenergy, zonetranssolar, zonedifsolfrintwinsrepenergy, zonedifsolfrintwinsrep, intbmincinssurfamountrepenergy, intbmincinssurfintensrep, intbmincinssurfamountrep, initialdifsolinabsreport, swwinabstotalreport, initialdifsolintransreport, swinabstotalreport, multcircumsolar, multisosky, multhorizonzenith, windowshadingcontrol, cosincanghr, sunlitfrachr, wingainirglaztozonerep, winheatgain, winheatlossrep, wingainframedividertozonerep, winheatgainrep, wingainconvglaztozonerep, wingainconvshadetozonerep, wingainirshadetozonerep, winlossswzonetooutwinrep, wingainconvglazshadgaptozonerep, otherconvgaininsidefacetozonerep, zonewinheatlossrep, zonewinheatgainrep, zonewinheatgain, zonewinheatgainrepenergy, zonewinheatlossrepenergy, winsyssoltransmittance, insideglasscondensationflag, wingapconvhtflowrep, winshadingabsorbedsolar, winheatgainrepenergy, winheatlossrepenergy, winsyssolreflectance, winsyssolabsorptance, fenlaysurftempfront, fenlaysurftempback, insideframecondensationflag, insidedividercondensationflag, wingapconvhtflowrepenergy, winshadingabsorbedsolarenergy, dbzone, qsdifsol, dbzonessg, aisurf, aosurf, bmtodiffreflfacobs, bmtobmreflfacobs, bmtodiffreflfacgnd, awincfoverlap, awinsurf, dgzone, dszone, z0, y0, x0, shadev, cbzone
computeintsolarabsorpfactors calls roundsigdigits, zone, construct, surface, surfacewindow, showwarningerror, showcontinueerror, showsevereerror, cfs
getshadowinginput calls calphafieldnames, calphaargs, lalphafieldblanks, rnumericargs, cnumericfieldnames, roundsigdigits, getobjectitem, showwarningerror, getnumobjectsfound, samestring, showcontinueerror
chkbks calls surface, showcontinueerror, showsevereerror
chksbs calls surface, determinepolygonoverlap, ctrans, htrans1, shadev
chkgss calls surface
getprojectcontroldata calls calphafieldnames, cnumericfieldnames, lnumericfieldblanks, roundsigdigits, getobjectitem, showwarningerror, getnumobjectsfound, showcontinueerror, showsevereerror, getscheduleindex, 8, buildingname, heattransferalgosused
getscheduledsurfacegains calls calphafieldnames, calphaargs, trimsigdigits, construct, getobjectdefmaxargs, getobjectitem, getnumobjectsfound, showcontinueerror, showsevereerror, finditeminlist, verifyname, getscheduleindex, fenlayabsssg, surfincsolssg, checkscheduledsurfacegains
getsiteatmospheredata calls roundsigdigits, 3, getobjectitem, getnumobjectsfound, showsevereerror
getconstructdata calls displaystring, nominalu, construct, getobjectitem, showwarningerror, getnumobjectsfound, showcontinueerror, showsevereerror, finditeminlist, verifyname, material, tcglazings, nominalrfornominalucalculation, setupcomplexfenestrationstateinput, checkandsetconstructionproperties, createfcfactorconstructions, searchwindow5datafile, nominalr
checkvalidsimulationobjects calls getnumobjectsfound
createtcconstructions calls roundsigdigits, nominalu, construct, material, tcglazings, nominalrfornominalucalculation, nominalrsave, nominalusave, constructsave
getwindowglassspectraldata calls trimsigdigits, getobjectitem, showwarningerror, getnumobjectsfound, showcontinueerror, showsevereerror, verifyname, spectraldata
getbuildingdata calls setupzonegeometry, getzonedata
checkusedconstructions calls showmessage, calphaargs, roundsigdigits, construct, getobjectitem, showwarningerror, getnumobjectsfound, showcontinueerror, finditeminlist
getmaterialdata calls calphafieldnames, calphaargs, lalphafieldblanks, rnumericargs, cnumericfieldnames, lnumericfieldblanks, roundsigdigits, scanforreports, 2, getobjectitem, showwarningerror, getnumobjectsfound, samestring, showcontinueerror, showsevereerror, setupemsactuator, finditeminlist, verifyname, 10, material, blind, displaymaterialroughness, tcglazings, nominalr, validatematerialroughness, gasspecificheatratio, gaswght, gascoeffscon, gascoeffscp, gascoeffsvis, setupcomplexfenestrationmaterialinput, setupsimplewindowglazingsystem
getframeanddividerdata calls calphafieldnames, cnumericfieldnames, framedivider, getobjectitem, showwarningerror, getnumobjectsfound, samestring, showcontinueerror, verifyname
checkscheduledsurfacegains calls zone, surface, showwarningerror, showcontinueerror, windowscheduledsolarabs, surfacescheduledsolarinc
setupcomplexfenestrationstateinput calls showfatalerror, calphafieldnames, calphaargs, rnumericargs, cnumericfieldnames, roundsigdigits, construct, getobjectdefmaxargs, getobjectitem, getnumobjectsfound, showcontinueerror, showsevereerror, finditeminlist, verifyname, nominalrfornominalucalculation, calculatebasislength, matrixindex, get2dmatrix, bsdftempmtrx, get2dmatrixdimensions, windowthermalmodel
checkandsetconstructionproperties calls showcontinueerror, showsevereerror
createfcfactorconstructions calls cnumericfieldnames, roundsigdigits, construct, getobjectitem, getnumobjectsfound, showcontinueerror, showsevereerror, finditeminlist, verifyname, material, nominalrfornominalucalculation, nominalr
searchwindow5datafile calls showfatalerror, displaystring, nominalu, framedivider, trimsigdigits, construct, samestring, showcontinueerror, makeuppercase, showsevereerror, material, polyf, nominalrfornominalucalculation, nominalr, w5lsqfit, checkforactualfilename, materialsave, nominalrsave, nominalusave, constructsave
matrixindex calls finditeminlist, getmatrixinput
getmatrixinput calls showcontinueerror, showfatalerror, calphaargs, rnumericargs, cnumericfieldnames, showsevereerror, getobjectitem, getnumobjectsfound, verifyname
setupzonegeometry calls roundsigdigits, nominalu, zone, computenominaluwithconvcoeffs, construct, surface, surfacewindow, showwarningerror, showcontinueerror, showsevereerror, getnumsectionsfound, predeftableentry, setoutbulbtempat, airskyradsplit, calculatezonevolume, adjacentzonetosurface, getsurfacedata, getwindowgapairflowcontroldata, 28, getstormwindowdata, allocatemodulearrays, processsurfacevertices
getzonedata calls calphafieldnames, calphaargs, lalphafieldblanks, rnumericargs, zone, getobjectitemnum, getobjectitem, zonedaylight, showwarningerror, getnumobjectsfound, samestring, showcontinueerror, showsevereerror, setupoutputvariable, finditeminlist, verifyname, zonegroup, zonelist, zonepredefrep
calculatezonevolume calls showmessage, roundsigdigits, zone, surface, showwarningerror, showcontinueerror, showsevereerror, getnumsectionsfound, createnewellareavector, calcpolyhedronvolume, veclength
getsurfacedata calls showfatalerror, roundsigdigits, nominalu, zone, trimsigdigits, construct, csurfaceclass, surface, surfacewindow, showwarningerror, getnumobjectsfound, samestring, showcontinueerror, showsevereerror, finditeminlist, showwarningmessage, material, blind, windowshadingcontrol, showseveremessage, createnewellareavector, veclength, determineazimuthandtilt, comparetwovectors, gethtsubsurfacedata, assignreverseconstructionnumber, getrectsubsurfaces, getmovableinsulationdata, gethtsurfacedata, getrectsurfaces, getintmasssurfacedata, getattshdsurfacedata, getsimpleshdsurfacedata, addvariableslatblind, setupshadesurfacesforsolarcalcs, getshadingsurfreflectancedata, getgeometryparameters, cextboundcondition, getdetshdsurfacedata, calcsurfacecentroid, getrectdetshdsurfacedata, getsurfaceheattransferalgorithmoverrides, gethtsurfextventedcavitydata, createnewellsurfacenormalvector
getwindowgapairflowcontroldata calls calphafieldnames, calphaargs, lalphafieldblanks, rnumericargs, construct, surface, surfacewindow, getobjectitem, showwarningerror, getnumobjectsfound, samestring, showcontinueerror, showsevereerror, finditeminlist, getscheduleindex, material, windowshadingcontrol
getstormwindowdata calls calphafieldnames, calphaargs, rnumericargs, trimsigdigits, surface, surfacewindow, getobjectitem, showwarningerror, getnumobjectsfound, showcontinueerror, showsevereerror, julianday, finditeminlist, material, stormwindow
processsurfacevertices calls framedivider, trimsigdigits, surface, surfacewindow, showwarningerror, showcontinueerror, showsevereerror, z0, y0, x0, shadev, veclength, calccoordinatetransformation, calccoplanarness, planeequation, pt2plane
veclength calls vecsquaredlength
determineazimuthandtilt calls vecnormalize
gethtsubsurfacedata calls calphafieldnames, calphaargs, lalphafieldblanks, rnumericargs, cnumericfieldnames, lnumericfieldblanks, osc, trimsigdigits, construct, getobjectdefmaxargs, getobjectitem, showwarningerror, showcontinueerror, showsevereerror, finditeminlist, verifyname, checkwindowshadingcontrolframedivider, getwindowshadingcontroldata, checksubsurfacemiscellaneous, getvertices, checkconvexity
assignreverseconstructionnumber calls checkandsetconstructionproperties
getrectsubsurfaces calls calphafieldnames, calphaargs, lalphafieldblanks, rnumericargs, cnumericfieldnames, trimsigdigits, construct, getobjectitem, showwarningerror, showcontinueerror, showsevereerror, finditeminlist, verifyname, checkwindowshadingcontrolframedivider, checksubsurfacemiscellaneous, makerelativerectangularvertices
getmovableinsulationdata calls calphafieldnames, calphaargs, roundsigdigits, getobjectitem, getnumobjectsfound, samestring, showcontinueerror, showsevereerror, finditeminlist, getscheduleindex, material
gethtsurfacedata calls calphafieldnames, calphaargs, lalphafieldblanks, rnumericargs, cnumericfieldnames, lnumericfieldblanks, roundsigdigits, osc, trimsigdigits, construct, getobjectdefmaxargs, getobjectitem, showwarningerror, samestring, showcontinueerror, showsevereerror, finditeminlist, verifyname, getvertices, checkconvexity, getoscmdata, getoscdata
getrectsurfaces calls calphafieldnames, calphaargs, rnumericargs, roundsigdigits, zone, trimsigdigits, construct, getobjectitem, showwarningerror, showcontinueerror, showsevereerror, finditeminlist, verifyname, makerectangularvertices
getintmasssurfacedata calls calphafieldnames, calphaargs, rnumericargs, construct, getobjectitem, showcontinueerror, showsevereerror, finditeminlist, verifyname
getattshdsurfacedata calls calphafieldnames, calphaargs, lalphafieldblanks, rnumericargs, cnumericfieldnames, lnumericfieldblanks, getschedulemaxvalue, trimsigdigits, getscheduleminvalue, getobjectdefmaxargs, getobjectitem, showwarningerror, showcontinueerror, showsevereerror, finditeminlist, verifyname, getscheduleindex, getvertices, checkconvexity, makemirrorsurface, checkschedulevalueminmax
getsimpleshdsurfacedata calls calphafieldnames, calphaargs, rnumericargs, roundsigdigits, getobjectitem, showwarningerror, showcontinueerror, showsevereerror, finditeminlist, verifyname, makerelativerectangularvertices, makemirrorsurface
addvariableslatblind calls showcontinueerror, showwarningerror, showsevereerror, roundsigdigits, finditeminlist
setupshadesurfacesforsolarcalcs calls calphaargs, surface, getobjectitem, getnumobjectsfound, samestring, finditeminlist
getshadingsurfreflectancedata calls calphafieldnames, calphaargs, rnumericargs, roundsigdigits, construct, csurfaceclass, getobjectitem, showwarningerror, getnumobjectsfound, showcontinueerror, showsevereerror, finditeminlist
getgeometryparameters calls calphafieldnames, getobjectitem, finditem, showwarningerror, getnumobjectsfound, samestring, showcontinueerror, showsevereerror
getdetshdsurfacedata calls calphafieldnames, calphaargs, lalphafieldblanks, rnumericargs, cnumericfieldnames, lnumericfieldblanks, getschedulemaxvalue, trimsigdigits, getscheduleminvalue, getobjectdefmaxargs, getobjectitem, showwarningerror, showcontinueerror, showsevereerror, verifyname, getscheduleindex, getvertices, checkconvexity, makemirrorsurface, checkschedulevalueminmax
calcsurfacecentroid calls roundsigdigits, surface, showwarningerror, showcontinueerror, areapolygon
getrectdetshdsurfacedata calls calphaargs, rnumericargs, trimsigdigits, getobjectdefmaxargs, getobjectitem, showwarningerror, showcontinueerror, showsevereerror, verifyname, makerectangularvertices, makemirrorsurface
getsurfaceheattransferalgorithmoverrides calls calphafieldnames, calphaargs, roundsigdigits, construct, surface, surfacewindow, getobjectitem, showwarningerror, getnumobjectsfound, showcontinueerror, showsevereerror, finditeminlist, heattransferalgosused
gethtsurfextventedcavitydata calls calphafieldnames, calphaargs, lalphafieldblanks, rnumericargs, trimsigdigits, surface, getobjectdefmaxargs, getobjectitem, showwarningerror, getnumobjectsfound, samestring, showcontinueerror, showsevereerror, setupoutputvariable, finditeminlist, verifyname, extventedcavity
createnewellsurfacenormalvector calls vecnormalize
vecnormalize calls veclength
checkwindowshadingcontrolframedivider calls calphafieldnames, calphaargs, lalphafieldblanks, roundsigdigits, framedivider, construct, showwarningerror, showcontinueerror, showsevereerror, finditeminlist, material, windowshadingcontrol, createshadedwindowconstruction
getwindowshadingcontroldata calls calphafieldnames, calphaargs, lalphafieldblanks, rnumericargs, construct, getobjectitem, showwarningerror, getnumobjectsfound, showcontinueerror, showsevereerror, finditeminlist, verifyname, getscheduleindex, material, windowshadingcontrol
checksubsurfacemiscellaneous calls construct, showwarningerror, showcontinueerror, showsevereerror, finditeminlist, material, modifywindow
getvertices calls showfatalerror, roundsigdigits, zone, showwarningerror, showcontinueerror, createnewellareavector, veclength, determineazimuthandtilt, createnewellsurfacenormalvector, reverseandrecalculate, transformvertsbyaspect, distance
checkconvexity calls roundsigdigits, zone, showwarningerror, showcontinueerror, showsevereerror
createshadedwindowconstruction calls nominalu, construct, finditeminlist, material, windowshadingcontrol, nominalrfornominalucalculation, nominalrsave, nominalusave, constructsave
modifywindow calls showmessage, roundsigdigits, construct, showwarningerror, showcontinueerror, showsevereerror, finditeminlist, veclength, addwindow
addwindow calls roundsigdigits, construct, showcontinueerror, showsevereerror, finditeminlist, veclength
reverseandrecalculate calls roundsigdigits, showwarningerror, determineazimuthandtilt, createnewellsurfacenormalvector
transformvertsbyaspect calls calphafieldnames, showwarningerror, getobjectitem, getnumobjectsfound
makerelativerectangularvertices calls createnewellareavector, veclength, determineazimuthandtilt, createnewellsurfacenormalvector, transformvertsbyaspect, distance
getoscmdata calls calphaargs, oscm, getobjectitem, getnumobjectsfound, setupemsactuator, setupoutputvariable, verifyname
getoscdata calls calphafieldnames, calphaargs, lalphafieldblanks, rnumericargs, lnumericfieldblanks, roundsigdigits, osc, getobjectitem, getnumobjectsfound, samestring, showcontinueerror, showsevereerror, setupoutputvariable, verifyname, getscheduleindex
makerectangularvertices calls zone, createnewellareavector, veclength, determineazimuthandtilt, createnewellsurfacenormalvector, transformvertsbyaspect, distance
makemirrorsurface calls createnewellareavector, veclength, determineazimuthandtilt, createnewellsurfacenormalvector
areapolygon calls vecnormalize
calccoordinatetransformation calls showfatalerror, surface, showcontinueerror, showsevereerror
calccoplanarness calls planeequation, pt2plane
planeequation calls veclength
validatematerialroughness calls samestring, showsevereerror, material
setupcomplexfenestrationmaterialinput calls showfatalerror, calphafieldnames, calphaargs, lalphafieldblanks, rnumericargs, cnumericfieldnames, roundsigdigits, getobjectitem, getnumobjectsfound, showcontinueerror, showsevereerror, finditeminlist, verifyname, material, supportpillar, deflectionstate, complexshade
setupsimplewindowglazingsystem calls showfatalerror, showwarningerror, showsevereerror, material, nominalr